### ISSUE TITLE
 remove -moz-user-select limitation from browser_style

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1001]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1383910 for full details.

# Acceptance criteria
- [ ] [Browser action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action) page has been updated to describe the bahavior.

**Comment by irenesmith** [comment]
Added the following note to the browser_style row on the [browser_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action) page:

Setting browser_style to true prevents users from selecting text in an extension's popup or sidebar content. This is normal behavior. You can't select parts of the UI in the browser. However, You can work around this limitation to allow your users to select text in two ways:

    1. Set browser_style to false
    2. Use CSS styling on the body of your sidebar or popup's HTML to allow text selection by adding the rule -moz-user-select with a value of all or text.
