### ISSUE TITLE
Document how to test Firefox extension permission warnings on upgrade

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1004]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1505105

When an extensions developer releases an upgrade, if the new version requests different permissions, then Firefox may ask the user to accept the new permissions before upgrading.

Before releasing an upgrade, extension developers would like to understand whether upgrading users will see such a dialog and what it will ask.

So they would like a way to test an upgrade so they can see what their users will see. We should document how to do this.

Alexei has outlined the procedure here: https://mail.mozilla.org/pipermail/dev-addons/2018-November/003989.html. Most of this procedure is generic "how to self-host an extension", so if we already have good docs on that we don't need to duplicate it, but we should point to the existing docs, properly contextualized, as a way for people to test upgrades. Obvious places to include these pointers are 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/onboarding_upboarding_offboarding_best_practices#Upboarding and probably https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions.

**Comment by irenesmith** [comment]
I think some of this or all of it has been done. @rebloor can you please check this and confirm?

**Comment by rebloor** [comment]
The process of testing permission warnings when upgrading is covered in the Extension Workshop page [Test permission requests](https://extensionworkshop.com/documentation/develop/test-permission-requests/) in the section Permission requests for extension upgrade. 

I have added a cross-reference link to the [permission key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) page. However, as the [Best practices for onboarding, upboarding, and offboarding users](https://extensionworkshop.com/documentation/develop/onboard-upboard-offboard-users/#Upboarding) so I'm not sure about the process for updating that one. Following up to find out what process is.
