### ISSUE TITLE
 Need property pages for overflow-block and overflow-inline

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1005]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1487383

The overflow spec now includes flow relative mappings for the overflow properties - overflow-block and overflow-inline. These need property pages.

**Comment by rachelandrew** [comment]
@chrisdavidmills do you want me to have a look at this one this time round? It's been hanging around a while.

**Comment by chrisdavidmills** [comment]
Yes please, that would be good.

**Comment by rachelandrew** [comment]
PR to update data https://github.com/mdn/data/pull/365

**Comment by rachelandrew** [comment]
1. https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-block
2. https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-inline

BCD is there, pages created, other than the PR for data above I think these are done.

**Comment by chrisdavidmills** [comment]
I've reviewed the pages, annd reviewed and merged the data repo PR.

This is now done!
