### ISSUE TITLE
Document deprecated theme properties

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1006]
Certain aliased theme properties that are part of the Firefox WebExtensions API will be deprecated by Firefox 69, currently scheduled for release in September 2019.

| Maintained | Deprecated |
| :-----------: | :------------: |
| theme_frame | headerURL |
| frame | accentcolor |
| tab_background_text | textcolor |
| bookmark_text | toolbar_text |

Starting in Firefox 65, the browser will begin emitting warnings if your theme uses any of the deprecated properties.

# Acceptance criteria
- [x] All properties have been marked as deprecated
- [x] A notice has been added to the documentation in a location that is likely to be seen about the deprecation and the warning.

## Reviewer
Luca Greco

**Comment by irenesmith** [comment]
Added "The property, headerURL will be deprecated beginning in Firefox 69. You will begin to get warnings in Firefox 65 and later if you load a theme that uses this property. Use theme_frame instead." in headerURL

Added the following notice just before the table of alias values:

Beginning in Firefox 69, the following properties will be deprecated: toolbar_text, accentcolor, and textcolor. Use bookmark_text, frame, frame_inactive, and tab_background_text instead. Using these values in themes loaded into Firefox 65 or later will raise warnings.

**Comment by irenesmith** [comment]
Mike Conca has reviewed these changes. Do I need to get him to add his comments here as well?

**Comment by irenesmith** [comment]
This has been done for a long time. Can we close it?

**Comment by chrisdavidmills** [comment]
What page did this documentation get done on? I just thought I'd give it a quick check and then give you sign off.

**Comment by irenesmith** [comment]
The changes were made to [Theme](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme) page.

My updates have since been overwritten because there was a change to what was deprecated.

The original changes were reviewed by Mike Conca.
