### ISSUE TITLE
Finish documenting Alt-Svc HTTP header

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1007]
Originally filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1462992

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc has been written, but it needs some more details.

**Comment by ExE-Boss** [comment]
I have created the&nbsp;<code>Alt&#x2011;Svc</code> documentation page back in September and written the&nbsp;syntax section, but as it says in&nbsp;the&nbsp;`{{Draft}}` macro invocation:

> This page needs to be completed by someone with a deeper understanding of <strong>HTTP&nbsp;Alternative&nbsp;Services</strong> than me.

**Comment by chrisdavidmills** [comment]
Looks done.
