### ISSUE TITLE
 Rework "Functions and classes available to workers" page

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1011]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1484918 for full details

**Comment by chrisdavidmills** [comment]
So IndexedDB is already shown as being supported in workers on this page.

But the bigger question is — how do we make it up-to-date? I mean, this page is out of date, and it will be very hard to make it up to date and keep it up to date manually.

@Elchi3 , do we store any information in BCD about what things are exposed in workers? If so, could we crete some kind of aggregate table to show this information?

Is it even worth it?

**Comment by Elchi3** [comment]
> @Elchi3 , do we store any information in BCD about what things are exposed in workers? If so, could we crete some kind of aggregate table to show this information?

We have added "worker_support" when we migrated the legacy compat tables into BCD, but we've now realized that this isn't the best representation either as there multiple worker types and soon "worklets". So, a general "supported in workers" statement is very imprecise at this point. 

> Is it even worth it?

I don't think so right now. Why would a web developer so much about this sort of aggregation? I think it comes up when you use a particular API and the docs for a given API should clearly state in which worker context it's available. The whole landscape of Web API availability to workers is maybe only interesting to spec authors and browser engineers who can also get this picture from WebIDL, I suppose. That's my thinking at least. Alternatively, we can interview users about workers to get a better picture about user needs here.

**Comment by chrisdavidmills** [comment]
Thanks for the thoughts on this. I think it is a measure of how worth it is that noone has ever complained (to my knowledge at least) about BCD not showing worker compat, or about specific pages not showing worker compat. Maybe the availableinworkers macro is another one we could kill, and then we could look for a better solution to this later on?
