### ISSUE TITLE
Create page: RegExp.prototype.dotAll ("s" flag)

### ISSUE THREAD

**Issue by noinkling** [mdn/sprints#1016]
# Request type
- [x] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

Page that should be created:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll

# Details
Documentation for the `RegExp.prototype.dotAll` property (`s` flag) doesn't exist. It was added in ES2018.

Proposal: https://github.com/tc39/proposal-regexp-dotall-flag

I've updated a couple of the existing pages where the flags are mentioned, but there should be one for the property itself.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

mdn/browser-compat-data#3423

**Comment by ExE-Boss** [comment]
This feels like a&nbsp;`WONTFIX` or&nbsp;`INVALID` to&nbsp;me given that no&nbsp;other `RegExp` flags have their own subpages.

**Comment by noinkling** [comment]
@ExE-Boss 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/ignoreCase
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky

**Comment by ExE-Boss** [comment]
I’ve now created https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll and updated https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/prototype
