### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/disabled

### ISSUE THREAD

**Issue by almirduarte** [mdn/sprints#1018]
# Request type
- [ ] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by almirduarte** [comment]
I'd like to report an issue, as I don't really understand the meaning of the sentence: "Visible controls have a disabled property which, except for menus and menuitems, is normally preferred to use of the attribute, as it may need to update additional state." Is it really correct?

**Comment by Elchi3** [comment]
We no longer maintain XUL docs.
