### ISSUE TITLE
New page

### ISSUE THREAD

**Issue by THEROCK2512** [mdn/sprints#1019]
# Request type
- [x] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by THEROCK2512** [comment]
New page

**Comment by schalkneethling** [comment]
@jwhitlock 	What do we do in situations like this?

**Comment by jmswisher** [comment]
If there are no useful comments in 24 hours, I go ahead and close it.
