### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/tag/Media%20Capture%20and%20Streams%20API

### ISSUE THREAD

**Issue by Pastisa** [mdn/sprints#1022]
# Request type
- [ ] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
@Pastisa What is the problem you are reporting?

**Comment by irenesmith** [comment]
Not enough information to make the fix. Please include details on what page you are reporting a problem with.

**Comment by Pastisa** [comment]
Prevent phone from being hacked
