### ISSUE TITLE
Content not found

### ISSUE THREAD

**Issue by aaron-pham** [mdn/sprints#1024]
Link Under Advanced Learning Material - WebGL redirects to a 404 page. 

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework

**Comment by chrisdavidmills** [comment]
A pull request has been submitted and merged to remove this part of the sidebar (the "beginner's WebGL" page was removed for a number of reasons); the pages just haven't been regenerated yet. If you find other pages still containing this link, regenerate them with Shift + Refresh.
