### ISSUE TITLE
Import performance.memory() documentation

### ISSUE THREAD

**Issue by ccope** [mdn/sprints#1025]
# Request type
- [x] New documentation
- [x] Correction or update

## Page to change
I would like to add https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory (which is currently a dead link on the https://developer.mozilla.org/en-US/docs/Web/API/Performance page)

# Details
Existing docs are here: https://webplatform.github.io/docs/apis/timing/properties/memory/
source: https://github.com/webplatform/webplatform.github.io/blob/8855897b894e17a653ee3de8745ea07aa382d214/docs/apis/timing/properties/memory/index.html

I want to update the note about memory quantization: In Chrome 68+, you can sample every 50ms if your script was served from the page origin (eTLD+1). Chrome patch: https://chromium.googlesource.com/chromium/src/+/7c7847f69de403f6c798dfccba10812039a60480

I haven't seen this documented anywhere online, and there's lots of places still falsely advertising the 20 minute minimum interval. I know this isn't standardized, but my users are mostly using Chrome and I need to monitor memory usage for a complex WebGL application.

**Comment by jmswisher** [comment]
@ccope Please email mdn-admins@mozilla.org to request Page Creation permission so you can add the page.

**Comment by jmswisher** [comment]
And be sure to attribute the source, per the CC-BY license of WebPlatform.org.

**Comment by chrisdavidmills** [comment]
@ccope did you get the permissions you need to do this?

**Comment by jmswisher** [comment]
[Performance.memory()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory) article now exists, though it does not have all the content that the WebPlatform page has. So, it could still be improved by adding that content (with CC-BY attribution).
