### ISSUE TITLE
Object.defineProperty() configurable default value is true?

### ISSUE THREAD

**Issue by zh-kai** [mdn/sprints#1031]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Configurable default value is **true** ？

**Comment by wbamberg** [comment]
I think `false` is correct here. 

Running this in the console:

```js
const object1 = {};

Object.defineProperty(object1, 'property1', {
  value: 42
});

const descriptor1 = Object.getOwnPropertyDescriptor(object1, 'property1');

console.log(descriptor1.configurable);
```

...I get the output `false`. Also from the specification: https://www.ecma-international.org/ecma-262/6.0/#table-4.

Is there a reason you think this should be `true`?

**Comment by wbamberg** [comment]
Closing, but please do comment if you think this is wrong.
