### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

### ISSUE THREAD

**Issue by pandaventurer** [mdn/sprints#1033]
[#](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math) Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update
![image](https://user-images.githubusercontent.com/36056418/52763522-60a2a480-301c-11e9-999e-6d58e591afa1.png)
![error mdn](https://user-images.githubusercontent.com/36056418/52763538-6dbf9380-301c-11e9-91cc-8888745f1af2.jpg)

# Details

7**7=2401 NOT 343.

**Comment by chrisdavidmills** [comment]
`7**7` is actually `823543` — it is the same as `7*7*7*7*7*7*7`, and also the same as `Math.pow(7,7)`.

`7**3` returns the same as `Math.pow(7,3)`, which is `343`. Try them in your JavaScript console.

**Comment by pandaventurer** [comment]
I'm agree that this is "the" functionnement, but the explication, here, is not available:
![image](https://user-images.githubusercontent.com/36056418/52771301-dff0a200-3035-11e9-9d34-3f55b1ec59f0.png)
"C'est l'équivalent du nombre de base multiplié par lui-même le même nombre de fois que l'exposant"
that is your explication. But the truth is ... i'm sorry, i'm a french man and i prefer to write in french 
La vérité c'est que le nombre n'est pas multiplié par lui même le même nombre de fois que l'exposant. Regardez bien; il est multiplié que 6 fois dans l'exemple 7*7*7*7*7*7*7 vous n'avez que 6 signes multiplicateur (*). Et dans l'exemple, 343, soit 7*7*7, il n'y a que 2 signes multiplicateurs (*). En math, lorsqu'on dit qu'un chiffre est multiplié autant de fois que son exposant par exemple 5**5, donnerait 5*5 (1ère fois) *5 (2ème fois) *5 (3è fois) *5(4ème fois) *5 (5ème fois), soit 5 fois le signe (*). Mon explication est logique. 
Your (?) explication est "faussée", car, dans le cas de 7**7 où de 7**3, ou de n'importe quel autre cas,  javascript NE MULTIPLIE PAS LE CHIFFRE AUTANT DE FOIS QUE SON EXPOSANT mais bel et bien UNE FOIS DE MOINS. On pourrait penser qu il multiplie le premier chiffre par un, D ABORD;

**Comment by pandaventurer** [comment]
look at this for comprehension that i said
![image](https://user-images.githubusercontent.com/36056418/52772821-c2253c00-3039-11e9-82b8-7e85f341d0e1.png)
![error mdn2](https://user-images.githubusercontent.com/36056418/52772834-c94c4a00-3039-11e9-9a55-0bd53f5ba4eb.jpg)

**Comment by pandaventurer** [comment]
**So the explication is not good.** 

Sorry for the "format" (3/4 messages for one explication!) of MY explication ...

**Comment by pandaventurer** [comment]
and exactly ...
![error mdn2_li](https://user-images.githubusercontent.com/36056418/52773190-b1c19100-303a-11e9-9a5c-5cbf5abc9f21.jpg)

**Comment by ChALkeR** [comment]
@chrisdavidmills I think all of this is about this passage:
> This is the equivalent of the base number being multipled by itself the same number of times as the exponent.

And the question whether `5*5*5` is multiplied by itself 2 or 3 times.

Btw, "multipled" looks like a mistype on that page.

**Comment by pandaventurer** [comment]
Yes, that's what i want to said.
It is the explication which is not correct.

The truth result is 2401. If not, it is multiplied two times only. Not
three.

**Comment by chrisdavidmills** [comment]
@ChALkeR thank you for helping me to find this quickly ;-) I have now updated the text to "the number of base numbers specified by the exponent are all multiplied together". I hope this makes sense.

@pandaventurer let me know if this fixes the problem you had, and thanks for all your efforts in reporting this! Merci boucoup.

**Comment by pandaventurer** [comment]
That's is the only one explication that we can offer ... !

Thanks you to read me and, understand me.

Best regards.

Philippe Delestan.

Le sam. 16 févr. 2019 à 08:56, Chris Mills <notifications@github.com> a
écrit :

**Comment by chrisdavidmills** [comment]
\o/

;-)

**Comment by pandaventurer** [comment]
That's what i've receive:
[image: image.png]

Le sam. 16 févr. 2019 à 09:48, Chris Mills <notifications@github.com> a
écrit :
