### ISSUE TITLE
Update compat data for min-content and max-content keywords (Fx66)

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1034]
As a web developer I want to understand browser support for intrinsic sizing keywords.

# Acceptance criteria

Updated browser support data on property pages where `min-content` and `max-content` are valid values:

- [x] width
- [x] min-width
- [x] max-width
- [x] height
- [x] min-height
- [x] max-height
- [x] block-size
- [x] max-block-size
- [x] min-block-size
- [x] inline-size
- [x] min-inline-size
- [x] max-inline-size

**Comment by rachelandrew** [comment]
PR for the data: https://github.com/mdn/browser-compat-data/pull/3457

**Comment by rachelandrew** [comment]
This has been merged, waiting for it to show up on pages.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think this is done - I have checked all of the pages and the data is showing up.

**Comment by chrisdavidmills** [comment]
Close, let's close then.
