### ISSUE TITLE
Obsolete DevTools documentation to be removed

### ISSUE THREAD

**Issue by captainbrosset** [mdn/sprints#1035]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It looks to me like everything under  “Extending the devtools” (found in the sidebar on https://developer.mozilla.org/en-US/docs/Tools) needs to be removed.

For example, https://developer.mozilla.org/en-US/docs/Tools/Adding_a_panel_to_the_toolbox talks about addon-SDK extensions, which aren't supported anymore.
Pages like https://developer.mozilla.org/en-US/docs/Tools/Editor also don't apply anymore since they describe APIs that can't be used today.

A suggestion would be to keep the "Extending the devtools" menu item in the sidebar, but link it to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools instead.

**Comment by captainbrosset** [comment]
On the DevTools home page (https://developer.mozilla.org/en-US/docs/Tools) if you scroll down, there's also a section about extending devtools further down that also needs to be replaced with a link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools

**Comment by chrisdavidmills** [comment]
Hello again @captainbrosset ! I have deleted all of the outdated pages and their translations, and filed a PR to update the sidebar: https://github.com/mdn/kumascript/pull/1079.
