### ISSUE TITLE
DevTools contribution docs should be removed

### ISSUE THREAD

**Issue by captainbrosset** [mdn/sprints#1036]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I do not think these pages are linked from anywhere anymore, but they might show up in searches:

* https://developer.mozilla.org/en-US/docs/Tools/Contributing
* https://developer.mozilla.org/en-US/docs/Tools/Contributing/Contribute_on_nightly

These pages document how to contribute to devtools. Unfortunately they are outdated and have not been touched in a long time. 
Our DevTools contribution docs have lived on https://docs.firefox-dev.tools for some time already, so we should probably just delete those pages.

**Comment by chrisdavidmills** [comment]
I've deleted those pages and their translations, and included a note to point anyone landing on the outdated URLs to the up-to-date docs.

I checked GA, and there were only about 50 page views per month across all translations
