### ISSUE TITLE
Issue in Map documentation regarding key equality

### ISSUE THREAD

**Issue by Neamar** [mdn/sprints#1038]
Issue Type: Correction or update

The MDN page for Map at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map states:

> Key equality is based on the "SameValueZero" algorithm: NaN is considered the same as NaN (even though NaN !== NaN) and all other values are considered equal according to the semantics of the === operator.

However, in Chrome, Node and Firefox:

```js
let a = new Map()
a[undefined] = 'foo'
'undefined' === undefined // false, one is a string and the other a keyword. Makes sense
a['undefined'] === 'foo' // true! Even though they should be two different keys.
```

In other words: two keys not equal according to `===` operator (keyword `undefined` and string `'undefined'`) still return the same value in the Map.

I'd have expected `a['undefined']` to return `undefined`, since this key was never defined.

I'm not an expert so I don't know if this is an issue in the documentation, or a problem in the browsers implementation.

**Comment by jchimene** [comment]
I'm pretty sure this should be closed. The reproducer uses `Object` syntax to reference `a`. 
Here is the reproducer written for `Map()` syntax:
```
let a = new Map()
a.set(undefined,'foo')
'undefined' === undefined // false, one is a string and the other a keyword. Makes sense
a.get('undefined') === 'foo' // false
```

**Comment by Neamar** [comment]
You are correct, according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#setting_object_properties

Sorry!
