### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x

### ISSUE THREAD

**Issue by KraxCZ** [mdn/sprints#1040]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Update made by chrisdavidmills on Feb 8, 2019, 5:23:35 AM seems strange to me. 
Could anybody (more familiar with HTTP than me) review the change? If the update is correct, could a small explanation be added?

**Comment by chrisdavidmills** [comment]
I made the change because of a previous content issue that said the value was wrong. Do you not think it should be this value? To be honest, I am no expert in HTTP.

**Comment by a2sheppy** [comment]
Huh. I see no information explaining what the problem is here...

**Comment by jmswisher** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x$compare?to=1458013&from=1370789 changed "close" to "keep-alive". The question is whether that's correct. @teoli2003 wrote the docs originally, so might know more.
