### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

### ISSUE THREAD

**Issue by HughR** [mdn/sprints#1043]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

There is an inappropriate image attached (but not linked) to this page.
If one edits this page, one will see the image listed as "sex teen".
I don't know how to delete this, nor do I have permission.  Would someone else delete this?
I wonder if other pages need to be scrubbed.

**Comment by jmswisher** [comment]
The image has been removed. Now doing a survey of attachments to search for other inappropriate attachments.
