### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_to_HTML/Structuring_a_page_of_content

### ISSUE THREAD

**Issue by Zinavolia** [mdn/sprints#1044]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**Comment by ChALkeR** [comment]
The correct link is https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_%C3%A0_HTML/Structuring_a_page_of_content.
