### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS

### ISSUE THREAD

**Issue by Epykest** [mdn/sprints#1045]
# Request type
- [x] Correction or update

# Details
You cannot make SELECT OPTION text bold no matter what you do. < b > tags and style="font-weight: bold;" will NOT work.

This is highly upsetting as it works fine on Chromium. The initial SELECT can appear bold, but once you click it, the drop-down items will not be bold.

Feel free to contact me for a private demo of how bad this looks.

**Comment by chrisdavidmills** [comment]
This sounds like you are trying to report a problem with Firefox, not with MDN documentation. For reporting Firefox bugs, see https://bugzilla.mozilla.org/.
