### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Simple_selectors

### ISSUE THREAD

**Issue by horshack-dpreview** [mdn/sprints#1046]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The example for the "Class selectors" section contains a mistake. It has HTML that references four classes - first, second, third, and done. But the sample CSS only defines two of those classes - first and done.

**Comment by chrisdavidmills** [comment]
This isn't really a mistake - you don't have to write CSS to style all classes declared in your HTML. But I've updated the sentence above the CSS to make this more clear.
