### ISSUE TITLE
Write an overview for the URL API

### ISSUE THREAD

**Issue by caripizza** [mdn/sprints#1047]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Other tasks:
* GroupData lists URLUtilsReadOnly which got merged into WorkerLocation (annevk believes)
* GroupData lists HTMLHyperlinkElementUtils but that's part of the HTML spec

On this page:
https://developer.mozilla.org/en-US/docs/Web/API
The 'URL API' link (under 'U' heading) is bad - it leads to a 404:
https://developer.mozilla.org/en-US/docs/Web/API/URL_API
Could the page below instead be the intended target?
https://developer.mozilla.org/en-US/docs/Web/API/URL

## Specs
* https://url.spec.whatwg.org/#url
* https://www.w3.org/TR/FileAPI/#creating-revoking

**Comment by a2sheppy** [comment]
This API overview needs to be written.

**Comment by a2sheppy** [comment]
* Updated [URLUtilsReadOnly](https://developer.mozilla.org/en-US/docs/Web/API/URLUtilsReadOnly) to note that it's obsolete and no longer exists after being merged into `WorkerLocation`
* Updated the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface's main overview to clean it up, bring it up to date, and generally make it better
* Created and finished the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL_API) overview page
