### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

### ISSUE THREAD

**Issue by DzonnyDZ** [mdn/sprints#1048]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In my opinion the information provided on page https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types are misleading. 
The page states that:
application/javascript is one of "other JavaScript MIME types that should not be used" and that it is " deprecated API" which "should no longer be used, but will probably still work". 
It also states 

> Servers should use text/javascript for JavaScript resources. Servers should not use other JavaScript MIME types for JavaScript resources, and must not use non-JavaScript MIME types.

quoting https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages

This is in contrast with IANA's https://www.iana.org/assignments/media-types/media-types.xhtml#text where it's stated that text/javascript is "OBSOLETED in favor of application/javascript".

# Acceptance criteria

- [x] Page updated to correct this problem
- [x] A few other inconsistencies need to be fixed (like the list of types is missing a few newer ones)

**Comment by a2sheppy** [comment]
This is really interesting. These specifications are in fact in conflict with one another. The HTML specification does in fact specifically say that the media type for JavaScript should always be `text/javascript`, and the IANA Media Types document does in fact say that `text/javascript` is deprecated and that `application/javascript` should be used instead. This is an interesting situation.

Muddying the waters is the MIME sniffing spec, which lists a bunch of MIME types and says they're all acceptable even though many are technically not valid.

Specs that say 180º different things are pretty rare. This is one of those cases, apparently. I'll see what I can work up for this content.

**Comment by a2sheppy** [comment]
Content reworded. Fixed a number of other issues with the page while I was at it.
