### ISSUE TITLE
WebExtension menus ContextType is missing viewType property

### ISSUE THREAD

**Issue by rugk** [mdn/sprints#1049]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData
fired from [an onShown event](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onShown). I also looked at when it is [fired from inside an add-on popup](https://bugzilla.mozilla.org/show_bug.cgi?id=1461115).

So I looked at the `info` object and this is how it actually looks in Firefox 65:

"usual tab":
```js
contexts: Array [ "page", "all" ]
​editable: false
​frameId: 0
​menuIds: Array [] // empty
​viewType: "tab"
```

popup:
```js
contexts: Array [ "page", "all" ]
​editable: false
​frameId: 0
​menuIds: Array [] // empty
​pageUrl: "moz-extension://2dacb47d[...]/popup/qrcode.html"
​targetElementId: 3187
​viewType: "popup"
```

`contexts` and `​menuIds` are documented in [onShown](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onShown), but the following ones are nowhere documented:
* `viewType` (seems to be useful, but undocumented)

**Comment by irenesmith** [comment]
There is already a page for ViewType, but I've added it to the OnClickData page in the appropriate place as:

viewType {{optional_inline}}
    {{WebExtAPIRef("extension.ViewType", "ViewType")}}. The type of extension view.
