### ISSUE TITLE
Write overview page for the HTML DOM API

### ISSUE THREAD

**Issue by sdlins** [mdn/sprints#1052]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
1. Access https://developer.mozilla.org/en-US/docs/Web/API; 
2. Click on "HTML DOM";
3. The page "https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM" **does not exist**.

**Comment by a2sheppy** [comment]
This is documentation that hasn't been written yet.

**Comment by jmswisher** [comment]
@a2sheppy The page still has the {{draft}} macro on it.

**Comment by chrisdavidmills** [comment]
@a2sheppy did anyone review this? I can do so if required.

**Comment by a2sheppy** [comment]
@chrisdavidmills That would be fantastic, actually. I totally blanked and didn't think to ask if anyone would review it.

**Comment by chrisdavidmills** [comment]
@a2sheppy I've had a loook over the new page, given it a copy edit, and made a few comments. In short, this is excellent work, well done that man.

My comments are as follows:

* "An {{Glossary("HTML")}} document is a DOM tree in which each of the nodes is an HTML element, represented by the {{domxref("HTMLElement")}} interface."

-- not all of them, surely? Some of them are text nodes.

* "HTML element interfaces"

-- this list is on the large side, and could probably do with breaking down into multiple lists of related functionality elements, to make it easier to find something you want.

* "Web components interfaces"

-- what about ShadowRoot? That represents a node, kind of.

**Comment by jmswisher** [comment]
@a2sheppy Moving this back to Review/Test due to @chrisdavidmills's review comments. Please update the issue when they're addressed.
