### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Utilisation_des_web_workers

### ISSUE THREAD

**Issue by letochagone** [mdn/sprints#1053]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

la phrase suivante: 
"L'algorithme clônage structuré peut accepter JSON et quelques choses qui échappent à JSON comme les références circulaires."
est une traduction incompréhensible ? on dirait le résultat d'un mauvais traducteur automatique.

**Comment by SphinxKnight** [comment]
I'm taking this one to review/improve/update the whole page.
@chrisdavidmills / @jmswisher if you can assign me, please do. If not that's not a big deal.
I'll let you know once done.

@letochagone 
fr: sur ce dépôt, pouvez-vous rédiger les problèmes rencontrés en anglais ? S'il s'agit de corriger du contenu francophone, mieux vaudra éditer le contenu du wiki :) (ce que chacun peut faire avec un compte). Je m'occupe de ce point, n'hésitez pas à me solliciter s'il y a d'autres contenus incorrects.
en-US: regarding this repo, could you please report issues in English please? You can also edit the content itself on MDN (it's a wiki)

**Comment by SphinxKnight** [comment]
Done, I've revamped the fr version of the document.

**Comment by chrisdavidmills** [comment]
That's great; thank you so much @SphinxKnight!
