### ISSUE TITLE
link url error on https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Introduction

### ISSUE THREAD

**Issue by Qinzhehan52** [mdn/sprints#1054]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

when clicking "下一页" on this page, it redirect to a url which doesn't exist: `https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_Web_API/Manipulating_documents `.

However, the correct url is `https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents`.

 It miss an "s" after "Client-side_web_API" actually.

**Comment by duduindo** [comment]
URL Next fixed. Thank you, @Qinzhehan52

**Comment by chrisdavidmills** [comment]
Thanks for the fix!
