### ISSUE TITLE
Check/update docs for webRequest.HttpHeaders.binaryValue

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1055]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/HttpHeaders

Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1528609. We need to figure out whether Firefox supports this, and document if it doesn't.

**Comment by jmswisher** [comment]
Unassigned, anyone can take it
