### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/parseInt

### ISSUE THREAD

**Issue by littleHiuman** [mdn/sprints#1057]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**In Examples**
1. In the vicinity of the 'The following examples all return 4:' sentence, you should add 'If the number greater than 1e+21 (includes) or less than 1e-7 (includes), it will return only one number.(When radix is 10)'

eg: 
```JavaScript
parseInt(0.0000001,10); // 1
parseInt(0.000000123,10); // 1
parseInt(1e-7,10); // 1
parseInt(1000000000000000000000,10); // 1
parseInt(123000000000000000000000,10); // 1
parseInt(1e+21,10); // 1
```

**Comment by Elchi3** [comment]
I've added this to https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt. For the zh-CN version, we will need someone from that language community to chime in. Thanks for reporting!
