### ISSUE TITLE
Where'd the JS Debugger API pages go?

### ISSUE THREAD

**Issue by asutherland** [mdn/sprints#1058]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The in-tree docs at https://searchfox.org/mozilla-central/source/devtools/docs/backend/debugger-api.md link to https://developer.mozilla.org/en-US/docs/Tools/Debugger-API which is now missing.  Searching for "spidermonkey debugger api" on Google still currently also links to the now-missing page.  Viewing https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey I also see a "Debugger-API" on the left-hand side that I click on and get a "Not Found" page.

I understand Gecko internals stuff is being moved off of MDN, so I wouldn't be surprised if this is intentional, but I'm not sure how to figure out where the information went.  Normally on a wiki page there's some way to view the history so I can find a log entry that says something like "moved to URL" and then follow that URL.  But I don't get any option like that, presumably because deletion is special.  But it would be very handy if there was a "tombstone" that explained where the info went.

**Comment by asutherland** [comment]
Ah, so I found the page on the internet archive at https://web.archive.org/web/20190116190524/https://developer.mozilla.org/en-US/docs/Tools/Debugger-API and scrolled down and found out the page came from in-tree `js/src/doc/Debugger/Debugger-API.md` which I can view at https://searchfox.org/mozilla-central/source/js/src/doc/Debugger/Debugger-API.md and probably elsewhere.

It'd still be great to have some kind of tombstone and/or clean up the other links from within MDN to now point to where the info is accessible in a rendered form, etc.  Thanks!

**Comment by chrisdavidmills** [comment]
Apologies. I've reinstated them now.
