### ISSUE TITLE
React Spike: set up i18n

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#1059]
# User story
As a frontend developer using React, I want to be able to localize strings in my code.

# Acceptance criteria
- [x] I can use gettext() or similar in my React code
- [x] `make localeextract` finds strings that need translation in my React code
- [x] Once translations have been made, they actually appear on the site.

One way I've seen l10n done in React is to replace gettext() wiht a an `<I18N>` component to mark strings that need translation. And a `<DoNotTranslate>` component to mark strings that do not need translation, used in conjunction with a linter that ensures that all strings are marked with one or the other.  There may be better ways to do it, but a linter for our strings would be nice-to-have.

**Comment by jwhitlock** [comment]
My preference would be to continue using [Puente](https://github.com/mozilla/puente) / [Babel](http://babel.pocoo.org/en/latest/) to extract these strings. We can tune the [Puente rules](https://github.com/mozilla/kuma/blob/2b5a6a5211c7d4ace244ce207fcd51a6aa866d65/kuma/settings/common.py#L645-L669) to scan ``.jsx`` files, into the ``javascript`` catalog or a new one. However, I'm not familiar with the standard for l10n in React, so I could be convinced by a widely supported React workflow.

**Comment by davidflanagan** [comment]
I was assuming we'd continue to use Puente for this, and this user story is intended to just be about customization of the rules to make something work. And also, I suppose, to investigate whether there are established best practices for l10n in React (that are easily supported by our existing backend tools).

**Comment by davidflanagan** [comment]
https://github.com/mozilla/kuma/pull/5279 configures Puente to find the React files in kuma/javascript/src and allows `make localeextract` to extract gettext() strings from those files.

I've been able to test this and verify that this simple change satisfies the first two acceptance criteria. For the third one, though, we could deploy this, wait for translations to come in, and then see if my kuma/javascript/src/gettext.js shim does the right thing. But that would cause unnecessary work for translators, so maybe I'll just make some manual changes to my local build/locale/jsi18n/es/javascript.js  file and make sure that they get picked up by the react components...

**Comment by davidflanagan** [comment]
Okay, so on top of PR #5277 I edited build/locale/jsi18n/es/javascript.js to add this line:
```
      "Sign in": "Sigñ iñ",
```

Then when I ran the Kuma locally and visited http://localhost:8000/es/ducks/Web/CSS I saw this rendered by my React login.jsx component:

<img width="109" alt="screen shot 2019-02-28 at 4 50 21 pm" src="https://user-images.githubusercontent.com/516914/53608888-5e425d80-3b79-11e9-88d8-2f03ce136dc2.png">

So that confirms that the gettext.js module in Kuma PR #5277 is working correctly.

I can't do a full end-to-end test of this without causing a non-trivial amount of work for localizers, and I don't think we should do that just yet, but I think that I've validated that localization will work for our React components, so this basically done, much sooner than expected.

(Keeping the issue open for now, since the PRs have not landed.)

**Comment by davidflanagan** [comment]
Also: I spent some time researching localization with React. There doesn't seem to any one dominant technique for doing it. I was surprised how many of the l10n solutions were not based on gettext(). I thought that was universal! Seems like there are a lot of half-baked npm packages out there, but not anthing really solid that is based on gettext(). And I couldn't find the kind of eslint plugin I'd been hoping for to ensure that strings are either passed to gettext() or marked as not needing localization. I still like that idea, but I don't think it is worth building our own eslint plugin for it.

**Comment by jwhitlock** [comment]
When I looked two years ago to upgrade translations in KumaScript ([bug 1340342](https://bugzilla.mozilla.org/show_bug.cgi?id=1340342#c4)), I was similarly underwhelmed by the node ecosystem around translations. At the time, my favorites were [Jed](https://github.com/messageformat/Jed), [po2json](https://github.com/mikeedwards/po2json), and [sprintf-js](https://www.npmjs.com/package/sprintf-js).
