### ISSUE TITLE
Add KumaScript test for data JSON

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#1062]
# User story
As MDN staff, I want testing of JSON data in the KumaScript repo, so that I can be unblocked from making changes and reviewing data PRs.

# Acceptance criteria
* Sample test or schema validator for data JSON, such as ``InterfaceData.json``

# References
This task was part of the time-boxed work in #940.

**Comment by ExE-Boss** [comment]
#1694 will make this redundant for `InterfaceData.json`.
