### ISSUE TITLE
Example on <details> page does not work in german

### ISSUE THREAD

**Issue by kaljak** [mdn/sprints#1064]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The example for the <detail>-tag does not work on the german page: https://developer.mozilla.org/de/docs/Web/HTML/Element/details#Live_Beispiel

**Comment by chrisdavidmills** [comment]
Fixed; the ID passed into the live sample macro call was incorrect because it was still using the English "Example:, rather thsn the German "Beispiel"
