### ISSUE TITLE
Write a gentle guide to what specs are, how they can be used, how they are created, etc.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1065]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

From a Daniel Beck email:

> are web developers equipped to make the most of specifications?

> Before working on BCD, I'd pretty much only ever glanced at specs long enough to feel intimidated by them. Even now that I know specs contain things I want to know, I still feel like there are lots of things about them I don't understand (especially the processes that produce them). My hunch is that web developers might get more use from the spec tables and calls for feedback if there was content that said to them, this is what a spec is, this is why they're relevant to you, and here's how you read and give feedback on a spec.

**Comment by Elchi3** [comment]
This was written: https://wpc.guide/

if this question comes up again anywhere, we can link to that site.
