### ISSUE TITLE
https://developer.mozilla.org/en-US/?utm_campaign=welcome&utm_medium=email&utm_source=developer.mozilla.org

### ISSUE THREAD

**Issue by Frank7779** [mdn/sprints#1066]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Hello 
It is impossible to close the MDN-account. I did not do any changes and reports, just would like to close the account.
Christoph

**Comment by jwhitlock** [comment]
To delete your account:

* Go to your profile page on MDN
* Edit your profile
* Near the bottom "Publish" button, select the link "Delete your account"
* Fill the form, and select "File a bug to close your account"
* Complete a bugzilla bug
* We'll close your account when we verify ownership.

I've deleted Frank7779.
