### ISSUE TITLE
parameter in docs but missing in actual object

### ISSUE THREAD

**Issue by MichaelOdumosu57** [mdn/sprints#1069]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

if you look at MouseEvent.region there is a description but I pulled the object and found that this was not a key in the object(check for all browsers I just found this problem in Google Chrome)

**Comment by irenesmith** [comment]
If you look at the browser compatibility table at the bottom of the page, you will see that you have to change a setting in order for it to be available in Chrome:

This feature is behind the Experimental Web Platform Features preference (needs to be set to true). To change preferences in Chrome, visit chrome://flags.
