### ISSUE TITLE
Could not found page of MVC patten

### ISSUE THREAD

**Issue by ss4f** [mdn/sprints#1070]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Please check it: [Setting up a Node development environment
](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment)

The problem is in the part of 'Express development environment overview', the third paragraph of 'What is the Express development environment?'. Clicking the MVC patten page and it shows could not found. May you guys fix it.

Thanks.

**Comment by chrisdavidmills** [comment]
Ah yes. I deleted that article last week because it is getting very out of date, and very few people are looking at it. I moved the useful content to https://developer.mozilla.org/en-US/docs/Glossary/MVC, so I've linked to that instead.
