### ISSUE TITLE
content not found

### ISSUE THREAD

**Issue by coow6005** [mdn/sprints#1071]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update
This URL's content not found https://developer.mozilla.org/zh-TW/Learn/Getting_started_with_the_web/What_should_your_web_site_be_like

I think this https://developer.mozilla.org/zh-TW/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like
can be that content

# Details

**Comment by chrisdavidmills** [comment]
I don't understand the prioblem here.

https://developer.mozilla.org/zh-TW/Learn/Getting_started_with_the_web/What_should_your_web_site_be_like is not found, but it is the wrong URL anyway. Where did you find this link?

https://developer.mozilla.org/zh-TW/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like is correct, and is the page linked in the navigation menus.
