### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output

### ISSUE THREAD

**Issue by wfentress** [mdn/sprints#1077]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The [description of the `form` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output#attr-form) says that "[i]f [the `form`] attribute is not specified, the output element must be a descendant of a form element." I can find no support for this claim in the linked specifications. [`null` appears to be a perfectly valid value for the form owner](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner), and both specifications include [an example with a bare `<output>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-output-element:the-output-element-6).

**Comment by jmswisher** [comment]
Looks like @a2sheppy fixed this.
