### ISSUE TITLE
"Good First Bug" documentation

### ISSUE THREAD

**Issue by emceeaich** [mdn/sprints#1083]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

Originally, https://bugzilla.mozilla.org/show_bug.cgi?id=1529434

The "good-first-bug" keyword in Bugzilla is intended for bugs which are good first contributions for people, and have support from contributors (and staff). 

There's [a Mozilla Wiki entry on how to work on a good-first-bug](https://wiki.mozilla.org/Good_first_bug), but not one on what we need to do to have a bug be a good-first-bug.

I don't think we have good documentation for this and the main thing I've seen on this is [a post by David Humphrey](https://blog.humphd.org/why-good-first-bugs-often-arent/). 

This would be some great content for our Developer Documentation on MDN.

For now I'm going to link the wiki to the keyword description so I have something for people to follow.

**Comment by chrisdavidmills** [comment]
Hi @emceeaich ! Eventually we want to get non-web platform docs moved off MDN, but with our current priorities I don't see that happening any time soon. Therefore, I'd recommend that such a piece of documentation get put the [Mozilla developer guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide) somewhere, so at least such docs are kept together.

However, this bug will be given a P5 priority. It is not web platform docs, so our team will not work on it. But we will accept new docs from other contributors.

**Comment by Elchi3** [comment]
Closing. We're not planning to work on this.
