### ISSUE TITLE
Should MDN host Triage Documentation for Firefox?

### ISSUE THREAD

**Issue by emceeaich** [mdn/sprints#1084]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

Firefox-specific triage documentation is at https://mozilla.github.io/bug-handling/triage-bugzilla. 

Should this be on MDN?

**Comment by a2sheppy** [comment]
@emceeaich - We are no longer putting Firefox/Mozilla internal content on MDN. The stuff we already have is intended to be moved off of MDN at some point in the future, once decisions are made where to put it.
