### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/transition

### ISSUE THREAD

**Issue by sergiykoshay** [mdn/sprints#1088]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![screencapture-developer-mozilla-org-en-us-docs-web-css-transition-2019-02-26-13_53_32](https://user-images.githubusercontent.com/22473913/53410978-087d8200-39ce-11e9-96dc-565c258a4e93.png)

**Comment by chrisdavidmills** [comment]
Fixed.

**Comment by wbamberg** [comment]
Assuming this report is about the misalignedlne numbers, this is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1529886.
