### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings

### ISSUE THREAD

**Issue by tinymachine** [mdn/sprints#1093]
The second note on https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings is currently:

> font characteristics set using font-variation-settings will always override those set using the corresponding basic font properties, e.g. font-weight, no matter where they appear in the cascade.

This is true in Firefox, but, as of this writing, in the current versions of Chrome and Safari this is only true when the `@font-face` declaration includes a `font-weight` range. It might be helpful to include this detail. (At least, it would have spared me some time spent troubleshooting this!)

* [X] - Edit text on https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings
(BTW thanks for sharing this incredible resource!)

Acceptance criteria: 

* [X] Task complete

**Comment by estelle** [comment]
Thank you!
