### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/eval()

### ISSUE THREAD

**Issue by biandeshen** [mdn/sprints#1094]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The first eval () on this page **404 Not Found**
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Functions

Old Link
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/eval()

_The new link might already be here_
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval

**Comment by chrisdavidmills** [comment]
I have fixed this. Thanks for reporting!
