### ISSUE TITLE
Document Reporting API

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1095]
# User story
As a web developer, I want to read about the Reporting API, so I can use it to gather better reporting information about my web sites

# Acceptance criteria

1. - [ ] `Report-To` header documented
2. - [x] `ReportingObserver` interface documented
3. - [x] `Report` interface documented
4. - [x] `ReportingObserverOptions` dictionary documented
5. - [x] `DeprecationReportBody` documented
6. - [x] `InterventionReportBody` documented
7. - [x] `CrashReportBody` documented
8. - [ ] GroupData.json entry added for Reporting API
9. - [ ] BCD added for Reporting API features
10. - [ ] Write "Using the Reporting API" guide

**Comment by Elchi3** [comment]
Report-To header BCD was done in https://github.com/mdn/browser-compat-data/pull/3550

**Comment by chrisdavidmills** [comment]
Update: All of the work is done, except for `Report-To` docs, which I'm still trying to get from engineering on, and BCD, and writing a short guide to teach people about it.

I also need to check when this is going to be finally enabled. Incould defer it to later on, if it isn't going to hit 67.

**Comment by chrisdavidmills** [comment]
New estimate set for remaining work — 1.5 points.

**Comment by jmswisher** [comment]
@chrisdavidmills This had an EOS comment of "Probably done this week, really" at the end of Q1 Sprint 3. Is it actually done?

**Comment by chrisdavidmills** [comment]
This is still not done; I've hit a brick wall as the engineer reponsible for it has become unresponsive. 

I was going to put it into the next sprint as a task to get to if I get time.
