### ISSUE TITLE
Archive deprecated, obsolete, nonstandard events

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1102]
This lists pages for events that are deprecated, obsolete, or nonstandard.

I propose that we archive these events rather than try to fix them.

https://developer.mozilla.org/en-US/docs/Web/Events/afterscriptexecute  (nonstandard, fx-only?)
https://developer.mozilla.org/en-US/docs/Web/Events/beforescriptexecute (nonstandard, fx-only?)
https://developer.mozilla.org/en-US/docs/Web/Events/cached (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/chargingchange (battery status)
https://developer.mozilla.org/en-US/docs/Web/Events/chargingtimechange (battery status)
https://developer.mozilla.org/en-US/docs/Web/Events/checking (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/dischargingtimechange (battery status)
https://developer.mozilla.org/en-US/docs/Web/Events/DOMSubtreeModified (deprecated but supported)
https://developer.mozilla.org/en-US/docs/Web/Events/downloading (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/error_(appcache_event) (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/levelchange (battery status)
https://developer.mozilla.org/en-US/docs/Web/Events/MozAudioAvailable (obsolete, only ever Firefox only)
https://developer.mozilla.org/en-US/docs/Web/Events/MozBeforeResize (obsolete, only ever Firefox only, apparently not supported in Firefox either)
https://developer.mozilla.org/en-US/docs/Web/Events/MozOrientation (Firefox-only, removed in Fx 6)
https://developer.mozilla.org/en-US/docs/Web/Events/MSManipulationStateChanged (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSInertiaStart (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureTap (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureStart (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureHold (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureEnd (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureChange (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/msContentZoom (MS IE & Edge only)
https://developer.mozilla.org/en-US/docs/Web/Events/noupdate (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/obsolete (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/overflow (nonstandard, Moz-specific)
https://developer.mozilla.org/en-US/docs/Web/Events/underflow (nonstandard, Moz-specific)
https://developer.mozilla.org/en-US/docs/Web/Events/progress_(appcache_event) (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/updateready (app cache)
https://developer.mozilla.org/en-US/docs/Web/Events/gesturechange (nonstandard,  Safari only)
https://developer.mozilla.org/en-US/docs/Web/Events/gestureend (nonstandard,  Safari only)
https://developer.mozilla.org/en-US/docs/Web/Events/gesturestart (nonstandard,  Safari only)

**Comment by wbamberg** [comment]
@chrisdavidmills we discussed by email what to do about these and we concluded that it's OK to archive them all.

The only events I think where this might be questionable is the proprietary events that are still supported, which I think covers:

https://developer.mozilla.org/en-US/docs/Web/Events/afterscriptexecute
https://developer.mozilla.org/en-US/docs/Web/Events/beforescriptexecute
https://developer.mozilla.org/en-US/docs/Web/Events/MSManipulationStateChanged
https://developer.mozilla.org/en-US/docs/Web/Events/MSInertiaStart
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureTap
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureStart
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureHold
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureEnd
https://developer.mozilla.org/en-US/docs/Web/Events/MSGestureChange
https://developer.mozilla.org/en-US/docs/Web/Events/msContentZoom
https://developer.mozilla.org/en-US/docs/Web/Events/overflow
https://developer.mozilla.org/en-US/docs/Web/Events/underflow
https://developer.mozilla.org/en-US/docs/Web/Events/gesturechange
https://developer.mozilla.org/en-US/docs/Web/Events/gestureend
https://developer.mozilla.org/en-US/docs/Web/Events/gesturestart

I'm on the fence about these. We could do a pretty minimal migration, just fixing up the structure and relocating them, possibly BCD, but not adding examples.

@Elchi3 referred to the [MSPointerHover event](https://github.com/mdn/sprints/issues/949#issuecomment-464733445) as a precedent, but actually it's not, quite, since that event is deprecated.

What do you think?

**Comment by chrisdavidmills** [comment]
I think this is reasonable — if they are proprietary but still supported, then we should keep them. I also agree with your minimal migration idea — fix up structure, add BCD (versions if listed on page, true if not, don't spend time hunting), and Add an example section  if an example already exists, but if not don't bother.

Did you want to attempt to do these next sprint? I'd be OK to do them if you want to spend some time on the structured content experiment stuff. Or we could share them. I'll put them into the sprint anyway, as I've decided we ought to do so.

**Comment by wbamberg** [comment]
> I'll put them into the sprint anyway, as I've decided we ought to do so.

Sounds good. I have bumped the estimate to 2, to reflect this. I think it is the right call.

**Comment by chrisdavidmills** [comment]
> Edited to add: I will take these for the next sprint.

OK, cool. Let me know if you need some help with them at any point. I'll move the spreadsheet row down to your items.

**Comment by wbamberg** [comment]
I've archived all pages except the [15 listed above](https://github.com/mdn/sprints/issues/1102#issuecomment-481913154) : https://developer.mozilla.org/en-US/docs/Archive/Events

**Comment by wbamberg** [comment]
I've moved the other 15 pages and they are ready for review @chrisdavidmills:

https://developer.mozilla.org/en-US/docs/Web/API/Element/gesturechange_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/gestureend_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/gesturestart_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureChange_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureEnd_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureHold_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureStart_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureTap_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSInertiaStart_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/msContentZoom_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/overflow_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/underflow_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/afterscriptexecute_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/beforescriptexecute_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/MSManipulationStateChanged_event

BCD is on its way.

**Comment by chrisdavidmills** [comment]
@wbamberg OK, review comments!

* In general these look fine — they are a bit less complete than other event pages, but my gut feeling is that the action we agreed for these is a good compromise in terms of not wasting too much time on proprietary event pages. Volunteers can always add examples, etc., if they want to. I just made a few small copy edit changes, nothing really worth mentioning.

* One thing I noticed is that the https://developer.mozilla.org/en-US/docs/Web/API/Element/msContentZoom_event seems to be inconsistent with all other MS-specific events in that the `ms` prefix is lower case. But I guess you've just left the event names as you found them, and you don't know if this is correct or not? This being the case, I'm OK to leave it as-is, but I just thought I'd mention it anyway.

* On the WebKit-specific evet pages you've got "...is a proprietary WebKit-specific event...", but you don't have "...is a proprietary IE/Edge-specific event..." or "...is a proprietary Firefox-specific event..." on the other pages. Should this be made consistent? I think it would be useful to state this at the top for all pages.

* In the "Browser compatibility" sections on all the pages (I think), you've got a sentence that lists the browser compat as well as the macro call. I take it you're gonna remove these once the new BCD is deployed?

Apart from any changes you make as a result of the above comments, I think the only thing left to do here is the BCD for those three events you didn't put in the first batch because of the weird diffs?

**Comment by wbamberg** [comment]
Thanks (again) for all the reviews!

> * One thing I noticed is that the https://developer.mozilla.org/en-US/docs/Web/API/Element/msContentZoom_event seems to be inconsistent with all other MS-specific events in that the `ms` prefix is lower case. But I guess you've just left the event names as you found them, and you don't know if this is correct or not? This being the case, I'm OK to leave it as-is, but I just thought I'd mention it anyway.

Yeah, I just kept this as I found it.

> * On the WebKit-specific event pages you've got "...is a proprietary WebKit-specific event...", but you don't have "...is a proprietary IE/Edge-specific event..." or "...is a proprietary Firefox-specific event..." on the other pages. Should this be made consistent? I think it would be useful to state this at the top for all pages.

That's a good suggestion. I've added a line at the top (after the first sentence) for every page.

> * In the "Browser compatibility" sections on all the pages (I think), you've got a sentence that lists the browser compat as well as the macro call. I take it you're gonna remove these once the new BCD is deployed?

Yes, I was just keeping these as a reminder for writing the BCD.

> Apart from any changes you make as a result of the above comments, I think the only thing left to do here is the BCD for those three events you didn't put in the first batch because of the weird diffs?

Yes, I think so. This follow-up is now filed: https://github.com/mdn/browser-compat-data/pull/3870.

**Comment by chrisdavidmills** [comment]
The changes look perfect, and I've also reviewed and merged the latest BCD PR.

I think this one can be set to done when all the BCD shows up on the pages.

**Comment by wbamberg** [comment]
BCD is now deployed, I've refreshed and checked these pages.
