### ISSUE TITLE
 Refactor print, clipboard, load/unload events

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1103]
This is a work item for #685.

print:

- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/afterprint
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/beforeprint

clipboard:

- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/copy
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/cut
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/paste

load/unload

- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/abort
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/load
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/unload

AC:
* all pages migrated and reviewed
* BCD updated

**Comment by wbamberg** [comment]
I reckon these are ready for review now. For events that bubble, I've tried making the "event target" page the main one and pointing to it from the other targets.

## print events:

https://developer.mozilla.org/en-US/docs/Web/API/Window#Print_events

## clipboard events:

https://developer.mozilla.org/en-US/docs/Web/API/Element#Clipboard_events
https://developer.mozilla.org/en-US/docs/Web/API/Document#Clipboard_events
https://developer.mozilla.org/en-US/docs/Web/API/Window#Clipboard_events

But I'm not sure whether these events are defined on Element or HTMLElement, or where the `on-` properties are defined for the other targets.

## load/unload events:

https://developer.mozilla.org/en-US/docs/Web/API/Document#Load_unload_events
https://developer.mozilla.org/en-US/docs/Web/API/Window#Load_unload_events

**Comment by chrisdavidmills** [comment]
OK, here's a review!

The events here look mostly really good.

The cut/copy/paste ones feel a little weird because of the different interface placing of the events and handler property pages, but I remember the discussions, and think the outcome works OK.

The abort event page still seems to be at the old location: https://developer.mozilla.org/en-US/docs/Web/Events/abort. Did you not create this one for a particular reason?

On https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event, the spec table points to an odd place. Wouldn't it be better to point to https://html.spec.whatwg.org/multipage/indices.html#event-domcontentloaded ?

https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event — there's a mention of DOMContentLoaded in the intro para that should be turned into a link, code font, or both.

https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event - the corresponding onreadystatechange handler property page doesn't exist. I take it you are just leaving this for now? I think that's what we agreed.

BCD looks to be there.

**Comment by wbamberg** [comment]
Thanks for the review @chrisdavidmills ! 

> The abort event page still seems to be at the old location: https://developer.mozilla.org/en-US/docs/Web/Events/abort. Did you not create this one for a particular reason?

I did look into this, but never wrote it down and then forgot about it. There are I think a few different `abort` event, including IndexedDB's [abort](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/abort_event), HTMLMediaElement's [abort](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/abort_event), and XMLHttpRequest's [abort](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort_event), all of which I've migrated already.

There's also according to the spec one that fires on `Window` targets when the document load is aborted (https://html.spec.whatwg.org/multipage/browsing-the-web.html#aborting-a-document-load). However it seems as if no browsers support this event properly (https://github.com/whatwg/html/issues/3525). So I think maybe we should just delete this page. Or I could try migrating it if you think its worth doing.

> On https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event, the spec table points to an odd place. Wouldn't it be better to point to https://html.spec.whatwg.org/multipage/indices.html#event-domcontentloaded ?

Thanks, this is kind of done. This was an error in the original page that I didn't double-check. I couldn't find a reference for this event in the W3C specs so I just deleted that row.

> https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event — there's a mention of DOMContentLoaded in the intro para that should be turned into a link, code font, or both.

Done, thanks.

> https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event - the corresponding onreadystatechange handler property page doesn't exist. I take it you are just leaving this for now? I think that's what we agreed.

Yes.

**Comment by chrisdavidmills** [comment]
> I did look into this, but never wrote it down and then forgot about it. There are I think a few different abort event, including IndexedDB's abort, HTMLMediaElement's abort, and XMLHttpRequest's abort, all of which I've migrated already.

> There's also according to the spec one that fires on Window targets when the document load is aborted (https://html.spec.whatwg.org/multipage/browsing-the-web.html#aborting-a-document-load). However it seems as if no browsers support this event properly (whatwg/html#3525). So I think maybe we should just delete this page. Or I could try migrating it if you think its worth doing.

I'd support just deleting it for now; we can come back to it if a problem is revealed.

> Thanks, this is kind of done. This was an error in the original page that I didn't double-check. I couldn't find a reference for this event in the W3C specs so I just deleted that row.

Looks better now, thanks!

OK, I think we can call this done.

**Comment by wbamberg** [comment]
Thanks Chris. I made abort redirect to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/abort_event.
