### ISSUE TITLE
Network Monitor Enhancements

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1107]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Work described in [Documentation Roadmap Trello Card](https://trello.com/c/dE8tJ7my/87-network-monitor-enhancements-fx-66) and Bugzilla #[1495797](https://bugzilla.mozilla.org/show_bug.cgi?id=1495797)

# Acceptance Criteria
- [x] Images updated to show new UI
- [x] Updates to descriptive text, if necessary

**Comment by chrisdavidmills** [comment]
@irenesmith what work was done on this? There is nothing to say what was done,  either in this issue or in the bug (the bug also needs dev-doc-complete, and a review request to an engineer). Can you give us some more info on this?
