### ISSUE TITLE
A link is missing on the "HTMLInputElement.value" page

### ISSUE THREAD

**Issue by ashishjpm** [mdn/sprints#1116]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Link on page "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input" for HTMLInputElement.value (ie. "https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/value") is broken

**Comment by chrisdavidmills** [comment]
I've updated it to point at the HTMLInputElement page for now, and describe it a bit differently. We don't have a separate page for the value property right now, and it'll be a while before we have time to work on this.
