### ISSUE TITLE
[P1] Document Autoplay Policy API

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1118]
There's no spec yet. See https://github.com/WICG/autoplay/issues/1

**Bug:** https://bugzilla.mozilla.org/show_bug.cgi?id=1506289
**Trello:** https://trello.com/c/4emMB6Y8/146-autoplay-api-fx-66

# Acceptance criteria

- [ ] New APIs' pages are added
- [ ] Indexes and overview pages are updated to include the new members
- [ ] At least one usable example provided
- [ ] BCD updated
- [ ] Submitted to engineers for review

**Comment by chrisdavidmills** [comment]
@a2sheppy this was slated for Fx66, but in the end I seem to recall that you didn't do most of the work on the trello card. Can you remind me what happened for this one?

**Comment by a2sheppy** [comment]
Yeah, it wasn't done for 66 in the end. One bit of it was, and that bit is
documented, but the rest slipped to 67 at soonest.

-- 
Eric Shepherd
Senior Technical Writer
Mozilla Developer Network
https://developer.mozilla.org/
Blog: http://www bitstampede.com/
Twitter: https://twitter.com/sheppy

**Comment by chrisdavidmills** [comment]
OK, thanks. I've put this into the Firefox 67 epic, and we'll reevaluate it when we get to the next sprint planning.

**Comment by a2sheppy** [comment]
This is still not done and is not likely to ship in 67. I will keep an eye on it.

**Comment by a2sheppy** [comment]
There are still decisions to be made before this API gets implemented further than we've already documented it. This will not ship in 67.

**Comment by jmswisher** [comment]
Taking it out of the Fx67 epic and the Jessye Norman milestone.
