### ISSUE TITLE
Refactor multiple event pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1119]
This is a work item for #685.

These pages all cover multiple events on interfaces belonging to different APIs. These will typically be quite complex to unravel.

- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/addtrack
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/change
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/close
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/error
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/message
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/messageerror
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/open
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/removetrack

AC:
* all pages migrated and reviewed
* BCD updated

**Comment by wbamberg** [comment]
## addtrack, removetrack, change

`addtrack` and `removetrack` can fire on [`VideoTrackList`](https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList/), [`AudioTrackList`](https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList/), and [`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/) targets:

* https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList/addtrack_event
* https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList/addtrack_event
* https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/addtrack_event
* https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList/removetrack_event
* https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList/removetrack_event
* https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/removetrack_event

`change` can fire on can fire on [`VideoTrackList`](https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList/) and [`AudioTrackList`](https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList/):

* https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList/change_event
* https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList/change_event

## close

The [original page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event$revision/1464493) pointed to 5 targets:

* IndexedDB, but this is [already documented](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close_event) as [part of a previous story](https://github.com/mdn/sprints/issues/926).

* WebRTC, but this is [already documented](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/close_event) as [part of a previous story](https://github.com/mdn/sprints/issues/952).

* WebSocket, but this is [already documented](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close_event) as [part of a previous story](https://github.com/mdn/sprints/issues/1104).

* Web Workers, but this is obsolete so I suggest not migrating it.

Leaving us with only the `dialog` close event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

**Comment by wbamberg** [comment]
@chrisdavidmills , I've finished migrating and writing new pages for these events. This one was a bit complicated to untangle so I've written up some analysis just above ^ . Each section there describes what I think is needed, then lists all pages that need review under the heading "New pages to review".

**Comment by chrisdavidmills** [comment]
@wbamberg 

OK, so I've reviewed all of the BCD submissions.

I've also looked over your rationale from above, and all of the new event pages. Generally these look good. I made a few small changes (corrected a couple of titles, improved the odd bit of grammar), but apart from that I think these are done.

Most of the pages seem to be lacking in the tags department, but that is only a minor issue.

As for the worries with getting mediarecorder/messageerror to work, I'm not sure if I can help you there. Maybe it's worth pinging a couple of engineers about them? IIRC, baku (Andrea Marchesini) did quite a bit of work on DOM stuff around workers, and Paul Adenot worked on MediaRecorder.

**Comment by wbamberg** [comment]
Thanks for all the reviews, @chrisdavidmills ! I'll leave this open until BCD is deployed and the tables are all showing.

> Most of the pages seem to be lacking in the tags department, but that is only a minor issue.

Honestly I feel that our tag situation is a mess, and without a real plan for all the things we want to use tags for, and some mechanism or process to ensure tags get used properly, there doesn't seem much point in adding a lot of tags. I've been adding "Event" so these pages can get picked up by the APIRef macro when we update that, but I don't know what else we need tags for here.

> Maybe it's worth pinging a couple of engineers about them? 

Thanks for the pointers, maybe I will do that. But I don't think it should block this issue.

**Comment by chrisdavidmills** [comment]
OK, agreed and agreed.

**Comment by wbamberg** [comment]
After today's BCD release I've refreshed all these pages and checked that the tables looks OK, and they do, so I'm closing this one.
