### ISSUE TITLE
Document CSS scroll anchoring

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1120]
# Request type

- [*] New documentation
- [ ] Correction or update

# Details

Firefox 66 has implemented scroll anchoring. See Trello card for details https://trello.com/c/Utcvz7Kv/90-scroll-anchoring-fx-66

# Tasks

- [x] Property page
- [x] BCD
- [x] Guide to the functionality

**Comment by rachelandrew** [comment]
BCD PR: https://github.com/mdn/browser-compat-data/pull/3576

**Comment by rachelandrew** [comment]
The property page is correct as is.

**Comment by chrisdavidmills** [comment]
> The property page is correct as is.

It doesn't have an "Examples" section; could you add one? I don't think an interactive example or full fledged big example would make sense for this property, but just something small that gives an idea of usage would be good.

**Comment by rachelandrew** [comment]
Hi Chris

the property is an opt out, I'm not really sure how we demo that. You have to try quite hard to create the scenario where you see the jumping. It's not something we can really do in a demo. I've clarified the property page to note that this is a new behaviour for browsers, and added an example of the property in use.

Also, a guide/explainer: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring

**Comment by chrisdavidmills** [comment]
All sounds good Rachel. And the guide is great. I edited it a bit; let me know if you are happy with the result, then I think we can close this one.
