### ISSUE TITLE
Refactor keyboard, selection, server-sent events, online/offline

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1123]
This is a work item for #685.

keyboard:

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/keydown
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/keypress
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/keyup

selection:

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/selectstart

server sent events:

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/error_serversentevents
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/message_serversentevents
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/open_serversentevents

on/offline:

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/offline
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/online

# Acceptance criteria
- [ ] all pages migrated and reviewed
- [ ] BCD updated

**Comment by irenesmith** [comment]
@chrisdavidmills Except for the keypress event, which has been deprecated, these events have all been refactored and are ready for review.

**Comment by Elchi3** [comment]
There are still open BCD PRs that relate to this task:
https://github.com/mdn/browser-compat-data/pull/3948
https://github.com/mdn/browser-compat-data/pull/3949

**Comment by wbamberg** [comment]
@irenesmith , I think @a2sheppy is down to review this one?

Also I'm not sure omitting keypress is the right call. It is deprecated but still supported, and looking at https://bugzilla.mozilla.org/show_bug.cgi?id=968056, for example, seems to be still quite widely used. So it does seem quite likely that Web developers will want information about it when working with legacy code.

**Comment by chrisdavidmills** [comment]
@wbamberg it's fine; I'm in the middle of reviewing this one. @a2sheppy can get on with other things.

**Comment by irenesmith** [comment]
I don’t think this was sheppy but I’m likely wrong. Sorry for any confusion.

**Comment by chrisdavidmills** [comment]
@wbamberg as my first port of call, I added in the keypress event on document and element:

https://github.com/mdn/browser-compat-data/pull/3980
https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event
https://developer.mozilla.org/en-US/docs/Web/API/Element#Keyboard_events
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event
https://developer.mozilla.org/en-US/docs/Web/API/Document#Keyboard_events

**Comment by chrisdavidmills** [comment]
All event pages now checked:

https://developer.mozilla.org/en-US/docs/Web/API/Document#Keyboard_events
https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event
https://developer.mozilla.org/en-US/docs/Web/API/Document/keyup_event

https://developer.mozilla.org/en-US/docs/Web/API/Element#Keyboard_events
https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/keyup_event

https://developer.mozilla.org/en-US/docs/Web/API/Document#Selection_events
https://developer.mozilla.org/en-US/docs/Web/API/Document/selectionchange_event
https://developer.mozilla.org/en-US/docs/Web/API/Document/selectstart_event

https://developer.mozilla.org/en-US/docs/Web/API/EventSource#Events
https://developer.mozilla.org/en-US/docs/Web/API/EventSource/error_event
https://developer.mozilla.org/en-US/docs/Web/API/EventSource/message_event
https://developer.mozilla.org/en-US/docs/Web/API/EventSource/open_event

https://developer.mozilla.org/en-US/docs/Web/API/Window#Connection_events
https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event
https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event

**Comment by chrisdavidmills** [comment]
I've now reviewed vinyl's BCD PRs too.

Looks like no BCD was submitted for this one either, so I'll do that next. The selection events are already submitted in PRs, as well as Document.keypress and Element.keypress.

**Comment by chrisdavidmills** [comment]
BCD for remaining events: https://github.com/mdn/browser-compat-data/pull/3982

**Comment by wbamberg** [comment]
@chrisdavidmills , shall I review that BCD?

**Comment by chrisdavidmills** [comment]
@wbamberg that would be great; cheers man.

**Comment by wbamberg** [comment]
BCD is all merged. @chrisdavidmills , if/when you are happy with this story we can close it.

**Comment by chrisdavidmills** [comment]
@wbamberg woo hoo! Closing ;-)
