### ISSUE TITLE
Refactor: payment, promise rejection, page hide/show, push, mute/unmute events

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1124]
This is a work item for #685.

payment request:

https://developer.mozilla.org/en-US/docs/Web/Events/paymentmethodchange
https://developer.mozilla.org/en-US/docs/Web/Events/shippingaddresschange
https://developer.mozilla.org/en-US/docs/Web/Events/shippingoptionchange

promise rejection:

https://developer.mozilla.org/en-US/docs/Web/Events/rejectionhandled
https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection

page hide/show:

https://developer.mozilla.org/en-US/docs/Web/Events/pagehide
https://developer.mozilla.org/en-US/docs/Web/Events/pageshow

push:

https://developer.mozilla.org/en-US/docs/Web/Events/push
https://developer.mozilla.org/en-US/docs/Web/Events/pushsubscriptionchange

mute/unmute:

https://developer.mozilla.org/en-US/docs/Web/Events/mute
https://developer.mozilla.org/en-US/docs/Web/Events/unmute

AC:
* all pages migrated and reviewed
* BCD updated

**Comment by a2sheppy** [comment]
BCD updates have been completed and merged: https://github.com/mdn/browser-compat-data/pull/3764

**Comment by a2sheppy** [comment]
Documentation added or updated:

https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/merchantvalidation_event
https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequestUpdateEvent
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Promise_rejection_events
https://developer.mozilla.org/en-US/docs/Web/API/Window#Promise_rejection_events
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack#Events
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event
https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/push_event
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event
https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/shippingaddresschange_event
https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/shippingoptionchange_event
https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/paymentmethodchange_event
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/unmute_event

**Comment by a2sheppy** [comment]
@chrisdavidmills -- I've added links to the documents added and updated above.

**Comment by chrisdavidmills** [comment]
@a2sheppy ok, some comments for you! Nothing too major; this looks mostly good. Once you've responded to these comments and the BCD data has shown up on the pages, we can signal to @wbamberg to close this.

https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/merchantvalidation_event

Needs an Examples section.

https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/shippingaddresschange_event#Example

Should be "Examples"

https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/shippingoptionchange_event#Example

Should be "Examples"

https://developer.mozilla.org/en-US/docs/Web/API/Window#Promise_rejection_events

This is great, but should a similar section be added to the Worker interface page too, given that they also be thrown on that context?

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event

In the intro you say "You listen for the mute event using the MediaStreamTrack.onmute event handler, or by calling addEventListener() with mute as the event type." which seems a bit repetitive, given that this is covered in detail in the "Examples" section.

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/unmute_event

In the intro you say "You can establish a listener for the unmute event using the MediaStreamTrack.onunmute event handler, or with addEventListener()." which seems a bit repetitive, given that this is covered in detail in the "Examples" section.

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event#Example

Should be "Examples"

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/push_event

No "Specifications" or "Browser compatibility" sections

**Comment by a2sheppy** [comment]
1.  Fixed: https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/merchantvalidation_event#Examples

2. Fixed: https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/onmerchantvalidation#Examples

3. Fixed, and added sample using the event handler property: https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/shippingoptionchange_event#Examples

4. Fixed: https://developer.mozilla.org/en-US/docs/Web/API/Worker#Events

5. https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event

6. Fixed. https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/unmute_event

7. Fixed: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event#Examples

8. Fixed: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/push_event#Specifications

**Comment by chrisdavidmills** [comment]
@a2sheppy great stuff; these all look fine to me now.

**Comment by wbamberg** [comment]
Thanks for the updates and the review!

I just checked through the pages looking at the BCD tables. Some of the pages had an error in the argument to Compat (they were passing `event.interface.event` instead of `api.interface.event`. I fixed these and most of the tables are showing up.

However a couple are not showing up, because the BCD didn't use the `_event` suffix for the identifier:
https://github.com/mdn/browser-compat-data/blob/master/api/Window.json#L6720
https://github.com/mdn/browser-compat-data/blob/master/api/Window.json#L9478

-> https://developer.mozilla.org/en-US/docs/Web/API/Window/rejectionhandled_event#Browser_compatibility
-> https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#Browser_compatibility

I think it would be good to fix these before closing the story.

**Comment by a2sheppy** [comment]
@wbamberg: I've submitted PR #3934 on BCD to fix those.

**Comment by a2sheppy** [comment]
That last PR has been merged and this is now done.

**Comment by wbamberg** [comment]
Sorry, also: the note for Firefox and Firefox for Android here: https://github.com/mdn/browser-compat-data/blob/master/api/Window.json#L6789-L6796 is missing a closing `<code>` tag, as you can see in the note attached to the table: https://developer.mozilla.org/en-US/docs/Web/API/Window/rejectionhandled_event#Browser_compatibility.

**Comment by wbamberg** [comment]
https://github.com/mdn/browser-compat-data/pull/3978 is merged and just waiting for deployment, so let's close this story.
