### ISSUE TITLE
Refactor events: a mixed bag, part 1

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1125]
This is a work item for #685.

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/abort_(dom_abort_api)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/appinstalled
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/cancel
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/cuechange
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/devicechange
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/hashchange
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/languagechange
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/message_(ServiceWorker)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/message_webworker
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/notificationclick
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/orientationchange

AC:
* all pages migrated and reviewed
* BCD updated

**Comment by Elchi3** [comment]
Except for the `message` events, the above pages have been moved and are ready for review. 

For BCD, please see these open PRs that are in need of review https://github.com/mdn/browser-compat-data/pulls?q=is%3Aopen+is%3Apr+author%3AElchi3+label%3A%22data%3Aapi+%3Arabbit2%3A%22

**Comment by wbamberg** [comment]
Thanks @Elchi3 !

Some general comments on examples: I think bare-bones examples like:

```js
target.addEventListener('thing', function() {
  console.log('the thing happened');
});
```

...are only a bit better than nothing. All they are really telling us is the syntax of `addEventListener`, and we probably know that already. I don't think we should mandate live examples - in many cases it's not possible or practical to have one, and in such cases bare-bones examples are OK - but where it is practical I think live examples are very much more useful (and also much less likely to rot than static code, because people will try them out and file bugs when they don't work). I appreciate that it's substantially more work but I do think it adds a big benefit.

Some specific comments:

> https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/abort_event

In the opening para it looks like `FetchController` should be `AbortController`.

> https://developer.mozilla.org/en-US/docs/Web/API/Window/appinstalled_event

The "Event handler" link is incorrect.

The fragment for the specifications link doesn't seem to exist.

> https://developer.mozilla.org/en-US/docs/Web/API/Element/cancel_event

Since this only fires for dialogs, it seems more helpful to have this page under [HTMLDialogElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/). I've done this for the corresponding [`close` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event).

The `close` event has a live example which could be mostly reused for this page.

"See also" can link to [`close`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event) as a related event.

> https://developer.mozilla.org/en-US/docs/Web/API/TextTrack/cuechange_event

Not sure how pedantic to be but single quotes for strings is our standard in code samples (https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#General_JavaScript_guidelines). Also I'm not sure what we expect `this` to be here.

> https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/devicechange_event

> https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event

The polyfill looks mad to me, can't we just delete that section? Surely this event is well enough supported by now.

> https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event

From the original page it looks as if this fires on Worker targets as well as Window.

> https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/notificationclick_event

I don't think these examples are very helpful. It's not at all clear to me what they are doing and there's quite a lot of unexplained complexity that seems accidental to the event being documented here.

> https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event

"You can use the abort event" copy/paste error.

The original page says the target here is [`Screen`](https://developer.mozilla.org/en-US/docs/Web/API/Screen), not `Window`.

Not sure how pedantic to be but single quotes for strings is our standard in code samples (https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#General_JavaScript_guidelines). Also I'm not sure what we expect `this` to be here.

**Comment by wbamberg** [comment]
Also I wasn't sure whether you just hadn't migrated the event pages yet, or whether there was another reason not to migrate them.

**Comment by Elchi3** [comment]
> Some general comments on examples: I think bare-bones examples like [...] are only a bit better than nothing

I whole-heartily agree with what you're saying here. I think it is sometimes difficult to come up with good examples, especially when you're not familiar with an API. It is a also a bit of a problem with the mixed bag I think. You don't really deep dive into each of these events or their corresponding API, because they are all very different and you want to get them done in time. I will see what I can do to improve the examples.

> (onlanguagechange) From the original page it looks as if this fires on Worker targets as well as Window.

Thanks, I forgot this. I think it would be WorkerGlobalScope as we already have https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/onlanguagechange as well.

> (notificationclick) I don't think these examples are very helpful. It's not at all clear to me what they are doing and there's quite a lot of unexplained complexity that seems accidental to the event being documented here.

Yeah, I think i need to dig into this and make a better example. I think this was just copied out of a larger code example in the API docs.

> (orientationchange) The original page says the target here is Screen, not Window.

The spec has it on window, https://compat.spec.whatwg.org/#event-orientationchange.
I saw there is https://developer.mozilla.org/en-US/docs/Web/API/Screen/onorientationchange but it seems to be wrong also. I can't find this in the Screen spec. I think it is very confusing and there seem to be multiple specs and implementations thereof when it comes to orientation. Would probably  require a deep dive to figure this out properly. It is kind of a mess it seems in terms of the specs and our docs.

> Not sure how pedantic to be but single quotes for strings is our standard in code samples 

Please be pedantic :) I think I've fixed this.

> Also I wasn't sure whether you just hadn't migrated the [message?] event pages yet, or whether there was another reason not to migrate them.

No reason, just not enough time. I wanted to get the majority of the work submitted for you to have a look at. I will continue addressing the review comments and migrate the remaining two events here. Thanks for your feedback so far! :+1:

**Comment by wbamberg** [comment]
By the way, for the worker message events, I migrated a bunch of [message](url) events in https://github.com/mdn/sprints/issues/1119, including [`Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker#Events) and [`DedicatedWorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope#Events).

I'm not sure if there's any overlap with the events here. Not for service workers maybe, but according to [the spec](https://www.w3.org/TR/workers/#communicating-with-a-dedicated-worker), perhaps [message_webworker](https://developer.mozilla.org/en-US/docs/Web/Events/message_webworker) is actually covered by  [`DedicatedWorkerGlobalScope.message`](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/message_event)?

**Comment by Elchi3** [comment]
> I'm not sure if there's any overlap with the events here. Not for service workers maybe, but according to the spec, perhaps message_webworker is actually covered by DedicatedWorkerGlobalScope.message?

I think you're right. I've made https://developer.mozilla.org/en-US/docs/Web/Events/message_webworker a redirect to https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/message_event

**Comment by Elchi3** [comment]
So, I think I have most issues addressed here and remaining BCD was merged and is deployed. So yay!

But the message events stuff is still weird to me.

ServiceWorkerGlobalScope IDL: https://w3c.github.io/ServiceWorker/#serviceworkerglobalscope
ServiceWorkerGlobalScope events: https://w3c.github.io/ServiceWorker/#execution-context-events

ServiceWorkerContainer IDL: https://w3c.github.io/ServiceWorker/#serviceworkercontainer
ServiceWorkerContainer events: https://w3c.github.io/ServiceWorker/#document-context-events

As you can see, in the IDLs both have the onmessage event handler. But then only ServiceWorkerGlobalScope has the message event listed. Also, I don't understand the differences between these two interfaces nor the difference of these events if there is any.

In fact, I know nothing about Service Workers, I'm somewhat frustrated, and I want to get this bag of events over the finish line finally. :cry:  Anyone willing to do some hand-holding with me here? :)

**Comment by wbamberg** [comment]
I had thought that `ServiceWorkerContainer` and `ServiceWorkerGlobalScope` represent the opposite ends of the app<->worker communication channel: so `ServiceWorkerGlobalScope.onmessage` is how the service worker code gets messages from the app that's using it, and `ServiceWorkerContainer.onmessage` is how the app gets messages from the service worker code.

But I might be totally wrong about that. I will take a look :)

**Comment by chrisdavidmills** [comment]
From my understanding:

ServiceWorkerGlobalScope represents the scope in which code is run inside the service worker, i.e. inside the sw.js file or whatever you call it.

This is where we can use an onmessage handler to respond to messages sent from the page that is being controlled by the service worker. See https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/post-message/service-worker.js#L78 for a good example.

Looking at the example on https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/message_event, this looks wrong because this is showing the code on the controlled page, which sends messages TO the service worker global scope.

--

The ServiceworkerContainer kind of represents the service worker as an object in the overall page ecosystem, allowing it to be registered so it can start controlling a page, etc. You cna access a page's ServiceWorkerContainer using https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker

To retrieve messages back from the SW global scope, you need to use ServiceWorkerContainer.onmessage, as shown at https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/post-message/demo.js#L72

HTH

**Comment by wbamberg** [comment]
Here's what I think we should do.

(1) have `message` under `ServiceWorkerContainer`, and document that this is used in a page controlled by a SW to receive messages from the SW. I think probably the easiest way to send the message from the SW is to get the client's ID from a `fetch` event and use Client.postMessage:

```js
// in the service worker
async function messageClient(clientId) {
    const client = await clients.get(clientId);
    client.postMessage(Received a fetch event from you);
}

addEventListener('fetch', (event) => {
    messageClient(event.clientId);
    event.respondWith(() => {
      // ...
    });
});
```

```js
// in the page being controlled
navigator.serviceWorker.addEventListener('message', (message) => {
    console.log(message);
});
```
The event is a [`MessageEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent).

However I haven't been able to get this to work because my service worker isn't getting `fetch` events :(. So this example is untested.
 
(2) have `message` under `ServiceWorkerGlobalScope`, and document that this is used in the SW code to receive messages from a page that the SW is controlling. The messages can be sent in various ways but perhaps the simplest is: the page gets a handle to the `ServiceWorker` object via`ServiceWorkerRegistration.active`, and then calls its `postMessage` function. Like this:

```js
// in the page being controlled
const swPath = 'static/scripts/sw.js';

function handleServiceWorkerActive(registration) {
    if (registration.active) {
        const serviceWorker = registration.active;
        const button = document.querySelector('#worker-message');
        button.addEventListener('click', ()  => {
            serviceWorker.postMessage('Hi service worker');
        });
    }
}

navigator.serviceWorker.register(swPath).then(handleServiceWorkerActive);
```

```js
// in the service worker
addEventListener('message', (event) => {
    console.log(`The client sent me a message: ${event.data}`);
});
```

I have tested this and it works!

Again, the event is a [`MessageEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent).

In both directions it's possible to use [channel messaging](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging) and that's probably a more realistic real-world choice, but it's a pain to set up so I would advocate using `postMessage` for a simpler example.

>  But then only ServiceWorkerGlobalScope has the message event listed.

I don't know if `ServiceWorkerContainer` actually supports `message` as well as `onmessage` because I haven't been able to get it working in that direction. But it would be weird if it didn't.

**Comment by chrisdavidmills** [comment]
I've tried playing with this stuff too, and just can't get any joy from it. The stuff I found was actually examples using messageClient along with SWs, and that stuff worked ok, but it's not the same.

I wouldn't block the whole bit of work on this one example — maybe just include a trivial example for now.

**Comment by Elchi3** [comment]
I've also tried to play with ServiceWorkers and I find it really confusing to get this to work. I didn't try to go down the channel messaging route, as I didn't want to spend more time on this, but I've added in Will's example code for now. Maybe this is enough and hopefully people will improve these events docs some more over time?

Here's the `message` events pages now:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer#Events
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/message_event

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope#Events
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/message_event

What do we think?

**Comment by chrisdavidmills** [comment]
I think this is OK for now; you have other things to do and have already spent enough time on it. Maybe we should follow up separately with an engineer to ask about why this isn't working and why?

Yaron Tausky might be a good person to ask.

**Comment by Elchi3** [comment]
Okay, sounds good to me. Will, could have a look as well and let me know if there is anything you want me to do to get this over the finish line? Otherwise, I'd be more than happy to declare this done.

**Comment by wbamberg** [comment]
Yes, I've checked that you addressed all the review feedback above and the service worker pages look good.

Thanks @Elchi3 !
