### ISSUE TITLE
<url> page needs updating

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1128]
https://developer.mozilla.org/en-US/docs/Web/CSS/url is scant. 

[ ] - add rules associated with escape characters
[ ] - remove the note about the bug fixed 7 years ago.

**Comment by workingwriter** [comment]
Added this text to add the escape character rules: "If you choose to write the URL without quotes, use a backslash (\) before any parentheses, whitespace characters, single quotes (') and double quotes ("). "

Removed the note on this page.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've reviewed the changes on this, and fixed a typo but looks to be completed.

**Comment by chrisdavidmills** [comment]
Yup, this looks good. Thanks @rachelandrew , and thanks @workingwriter !
