### ISSUE TITLE
CSS translate demos do not appear to work

### ISSUE THREAD

**Issue by bkdotcom** [mdn/sprints#1131]
https://developer.mozilla.org/en-US/docs/Web/CSS/translate

# Request type
* [x] Correction or update

https://developer.mozilla.org/en-US/docs/Web/CSS/translate

It appears something is supposed to happen on hover in the CodePen / JSFiddle demos, but nothing happens for me (Firefox 65 & Chrome on OSX)

**Comment by chrisdavidmills** [comment]
Hrm, interesting. I wrote these demos originally, and they definitely worked at some point. We'll have to investigate why.

**Comment by estelle** [comment]
They work in FF, not in chrome.
Need to check syntax, then change BCD if necessary.

**Comment by estelle** [comment]
They are supported with a flag in FF 60+
Only translate, scale, and rotate are in the spec (not skew)
No other browsers support this yet.

Updated pages. 
Updating BCDs
