### ISSUE TITLE
setTimeout this binding code doesn't work? 

### ISSUE THREAD

**Issue by fzpijl** [mdn/sprints#1135]
# Request type

- [x ] Correction or update

# Details
in the documentation of setTimeout has code like below to bind the right 'this' to the vCallback, but I think it does work.
<img width="954" alt="2019-03-02 11 32 51" src="https://user-images.githubusercontent.com/24666740/53676595-a1b6dc00-3cdf-11e9-91b7-ab4c79b160c4.png">

**Comment by fzpijl** [comment]
```
var arr = [1, 2, , 3]
var arr1 = arr.forEach((item) => console.log(item))
     
```

**Comment by fzpijl** [comment]
1.   4

2. 
```js
arr1 = arr.filter(function(item){return item})
```

3.
```js
arr2 = [1, 2, NaN, 3]
```
4.
```js
arr3 = [].push.apply(arr, arr2)
```
5.
```js
arr3 = Array.from(new Set(arr3))
```

**Comment by chrisdavidmills** [comment]
What page is this code on?
