### ISSUE TITLE
Document `print` console helper

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1136]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Bugzilla #[1523129](https://bugzilla.mozilla.org/show_bug.cgi?id=1523129)

## Information in bug:
Steps to reproduce:

I noticed that this page documents a pprint command:

https://developer.mozilla.org/Tools/Web_Console/Helpers

However I have noticed that both the Web Console and the Browser Console also
have not one, but two print commands:

https://i.stack.imgur.com/Qi24S.png

what are these commands, and are they documented somewhere?

**Comment by jmswisher** [comment]
The `pprint()` helper is marked as deprecated since Fx74 (maybe actually obsolete?), and the consoles now offer only one `print()` function (i.e., `window.print()`). Nothing left to document, I think.
