### ISSUE TITLE
CustomElementRegistry.upgrade() documentation is missing

### ISSUE THREAD

**Issue by ruphin** [mdn/sprints#1140]
# Request type
- [x] New documentation

# Details

The CustomElementRegistry.upgrade() method is missing from documentation.

https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-upgrade

I can write up a draft for this documentation page, but I do not have the required rights to create new pages.

**Comment by chrisdavidmills** [comment]
This is actually one of my next tasks. I'll be getting to this in the next few days.

**Comment by chrisdavidmills** [comment]
Unless you'd like to give it a shot, of course. I'm happy to mentor you if needed.

**Comment by chrisdavidmills** [comment]
I have written documentation for `upgrade()`; let me know what you think — https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/upgrade.

The example could be better. Feel free to submit a better example if you have time.

Thanks for reporting!

**Comment by ruphin** [comment]
I made a small correction to the description, but I'm not sure if the wording is correct.

**Comment by chrisdavidmills** [comment]
thanks @ruphin, good spot! I've changed the description a little bit more, but I think we are on the right track now.
