### ISSUE TITLE
[Debugger] Add a new map scopes page

### ISSUE THREAD

**Issue by jasonLaster** [mdn/sprints#1141]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

It would be great to add a new debugger sub page to describe the "Map Scopes" feature. The feature lets users opt-in to using source maps to map the scopes when they pause. This helps developers because they can see the original variables that they used in their code as opposed to the variables that their build tool produced

**Comment by irenesmith** [comment]
I've created a placeholder for the page: [Using the debugger map scopes featre](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Using_the_Debugger_map_scopes_feature)

Currently, it is just a note that the page is a placeholder for the documentation, but I have not linked to it from anywhere.

**Comment by irenesmith** [comment]
The page has been created. This item should be considered done. There is a separate issue for adding the information.

**Comment by chrisdavidmills** [comment]
@irenesmith Where is the issue for adding the content? It feels a little weird to me to have "add page x" as a different task to "write the initial content for page x" — the former is not very useful without the latter, and this could lead to stub pages being created that are then forgotten about and rot.

In future, can you combine such tasks together?
