### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Using_images

### ISSUE THREAD

**Issue by sarusama** [mdn/sprints#1147]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

[The Page has a problem.](https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Using_images)
由零开始创建图像|Creating an image from scratch
In the end of the last paragraph's URL is broken.

**Comment by chrisdavidmills** [comment]
That page is just not there any more. It was deletd from the English version, so I've just deleted it from the Chinese version too.
