### ISSUE TITLE
Incorrect locale for SVG image content

### ISSUE THREAD

**Issue by gsouquet** [mdn/sprints#1148]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details

On the page [Basic concepts behind Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API) in all the locales, the SVG describing the positioning vectors is displaying text in French.

I amended the SVG and tried to upload it again, however [SVG upload has been disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1530619) for non staff.

You will find attached the new [SVG](https://s3-eu-west-1.amazonaws.com/grabyo-germain/listener_en.svg) here, sorry GitHub does not support SVG upload. 

I think we could update the Japanese, Korean and Chinese version as it is more likely that they understand english compared to French.

**Comment by chrisdavidmills** [comment]
I don't know if I'm able to upload SVG images either, but I did manage to find the location of the Engish version, and link to that instead.
