### ISSUE TITLE
Web Audio Event Pages

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1150]
Pages:
Web Audio API Events

* [ ] https://developer.mozilla.org/en-US/docs/Web/Events/audioprocess
* [ ] https://developer.mozilla.org/en-US/docs/Web/Events/complete

Acceptance Criteria:
* [ ] Both pages moved and updated

**Comment by wbamberg** [comment]
I just saw this story: I think these events were originally part of https://github.com/mdn/sprints/issues/956, but they were removed from that story and added to this one.

@estelle , are you planning to work on these events in the next sprint?

**Comment by estelle** [comment]
It's not in my user stories, but I can add it.
They were removed because they weren't part of htmlmediaelement events IIRC.
And then i forgot about them.

**Comment by chrisdavidmills** [comment]
I've noted this one down in the scratch pad for the next sprint so we don't forget it.

**Comment by chrisdavidmills** [comment]
OK, event pages moved:

audioprocess:

Event page moved to the right place: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/audioprocess

Structure sorted out, and "Events" section added to https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode#Events

complete:

Event page moved to the right place: https://developer.mozilla.org/en-US/docs/Web/Events/complete

Structure sorted out, and "Events" section added to https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext#Events

Now on to the BCD.

**Comment by chrisdavidmills** [comment]
BCD PR now written; see https://github.com/mdn/browser-compat-data/pull/3892.

Can I get a review on these please @estelle? Thanks!

**Comment by estelle** [comment]
Looks good. I just added "let offlineAudioCtx = new OfflineAudioContext();" and fixed a broken link.

**Comment by chrisdavidmills** [comment]
Thanks, much appreciated!

> Spec read audioProcessingEvent, with an 'ing', but since it's deprecated, i didn't dig deeper.

The event object is AudioProcessingEvent, but the actual object looks to be audioprocess; see https://webaudio.github.io/web-audio-api/#dom-scriptprocessornode-onaudioprocess

@wbamberg , i think this one is ready for final check and signoff.

**Comment by wbamberg** [comment]
Thanks @estelle , @chrisdavidmills , this one looks to be done.
