### ISSUE TITLE
ended and pause events

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1151]
Additional ended events
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/ended_event
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/ended_event

Additional pause events
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/pause_event

**Comment by wbamberg** [comment]
As for https://github.com/mdn/sprints/issues/1150, I just saw this story: I think these events were originally part of https://github.com/mdn/sprints/issues/956, but they were removed from that story and added to this one.

@estelle , are you planning to work on these events in the next sprint?

**Comment by chrisdavidmills** [comment]
I'm assuming that these are events that you've already created on HTMLMediaElement, which are also fired in these other places? I can take this one on if you like.

**Comment by chrisdavidmills** [comment]
OK, so I've dealt with the new pages first:

# Media Streams API ended event

This looks to be fired on the MediaStreamTrack object type, so I've moved it here:

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event

I've updated the page to the correct structure, and made sure it is represented at https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack#Events

# Web Audio API ended event

This looks to be fired on the AudioScheduledSourceNode type, so I've moved it here:

https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/ended_event

I've updated the page to the correct structure, and created an "Events" section on its parent page:

https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode#Events

# Web Audio API pause event

The link you provided above doesn't seem to point annywhere, but I did check, and it looks like the event page you are referring to was created as part of a different user story:

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pause_event

?

OK, now on to BCD for the first two.

**Comment by chrisdavidmills** [comment]
BCD now done; see https://github.com/mdn/browser-compat-data/pull/3891

@estelle , can I have a review of this please?

**Comment by estelle** [comment]
I like the 'usage notes'. Thinking I should change 'other properties' to 'usage notes' in the events that had additional properties.

Did you add a link to the relevant HTML media content pages?

@wbamberg  - are these in the correct location? the other events are on DOM nodes and not on interfaces. 

Only comment that may lead to added test is on the examples: would be good to add the HTML for the targeted DOM not, add how 'track/node' is accessed via JS, and make it a live codepen/jsfiddle.

**Comment by chrisdavidmills** [comment]
Thanks Estelle. I don't think you need to make any other changes to your pages now;  there are certainly a few bits of inconsistency littered about in these pages, but we can fix those as we get to them.

I know what you mean by the examples. I just didn't have the time to go over those APIs, relearn how they all work, and then try to write something realistic but compact to demonstrate usage. I've added a link to the web audio one to an example we have on github of onended being used in context.

**Comment by wbamberg** [comment]
> @wbamberg - are these in the correct location? 

I don't know but they seem to be:

> https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event

[From the spec](https://w3c.github.io/mediacapture-main/#event-mediastreamtrack-ended) "The following events fire on MediaStreamTrack objects ... ended"

> https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/ended_event#Specifications

[From the spec](https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-onended): "the ended event that is dispatched to AudioScheduledSourceNode node types"

> https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pause_event

[From the spec](https://w3c.github.io/speech-api/#utterance-events): "SpeechSynthesisUtterance Events... pause event "
