### ISSUE TITLE
BCD incorrect: mask-position-x and y

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1153]
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-position-x
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-position-y

mask-position-x and maski-position-y are supported in FF, both with and without the webkit prefix.

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/issues/4649
