### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/zh-CN/docs/Learn/JavaScript/First_steps/Variables

### ISSUE THREAD

**Issue by SamoZ** [mdn/sprints#1154]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update
![image](https://user-images.githubusercontent.com/25240164/53862903-c2569d00-4023-11e9-96ba-2d5efaacef3e.png)

# Details

关于 let 和 var 之间的区别 原文链接失效。

**Comment by chrisdavidmills** [comment]
Sorry, what is the problem here?

**Comment by SamoZ** [comment]
@chrisdavidmills The link pointed at by the arrow is invalid

**Comment by chrisdavidmills** [comment]
@SamoZ Can you confirm what page this bad link is found on? I couldn't find it.

**Comment by SamoZ** [comment]
@chrisdavidmills 
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/A_first_splash#%E6%B7%BB%E5%8A%A0%E5%8F%98%E9%87%8F%E4%BB%A5%E4%BF%9D%E5%AD%98%E6%95%B0%E6%8D%AE

**Comment by SamoZ** [comment]
@chrisdavidmills 
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/A_first_splash#%E6%B7%BB%E5%8A%A0%E5%8F%98%E9%87%8F%E4%BB%A5%E4%BF%9D%E5%AD%98%E6%95%B0%E6%8D%AE
![image](https://user-images.githubusercontent.com/25240164/54002007-30b47000-4188-11e9-9439-4083b746cd9c.png)

**Comment by chrisdavidmills** [comment]
Great, thank you.

I have found the broken link and fixed it.
