### ISSUE TITLE
CSS attr() formal syntax

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#1155]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/attr#Formal_syntax

The `integer` type is included twice.

![attr](https://user-images.githubusercontent.com/576623/53898671-33f11400-4041-11e9-954d-f75f63dca652.png)

**Comment by chrisdavidmills** [comment]
Hey there!

I've submitted a PR to fix this, and I've also added a few missing values.

**Comment by chrisdavidmills** [comment]
Ooops, the PR is here: https://github.com/mdn/data/pull/364

**Comment by ramiy** [comment]
Thanks @chrisdavidmills !
