### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient

### ISSUE THREAD

**Issue by enricolam** [mdn/sprints#1156]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x]  Correction or update

# Details
On conic gradient page, the understanding conic gradients section, at the very beginning, which describes the differences between radial and conic gradient.

A circle consist of 2Pi Rad, not 2 Radians.

**Comment by chrisdavidmills** [comment]
Good point — thanks for pointing this out! I have fixed this now.
