### ISSUE TITLE
Debugger Updates for Firefox 67

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1157]
# User story
As a developer, I want to make the most of the Firefox debugger, so I can use the latest features to make debugging my applications easier.

# Acceptance criteria
TBD

# Tasks
- [ ] Determine what documentation needs to be created (by feature).
- [ ] Create issues for each feature

**Comment by jasonLaster** [comment]
Here are four features that should be documented:

- [ ] Log Points
- [ ] Map Scopes
- [ ] Worker Debugging
- [ ] Column Breakpoints

**Comment by irenesmith** [comment]
All of the features listed have been documented.
