### ISSUE TITLE
CSS `display` page should list the keywords from each of the categories, not just the categories

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1159]
Having the list of categories under [Syntax on this page](https://developer.mozilla.org/en-US/docs/Web/CSS/display#Syntax) is not useful. Instead, the page should be transcluding the lists of keywords from each of those pages by doing something like...

The display property is specified using keyword values. Keyword values are grouped into six value categories:

{{page("/en-US/docs/Web/CSS/display-outside", "Syntax")}}
{{page("/en-US/docs/Web/CSS/display-inside", "Syntax")}}
... etc...

By then rewording the intro paragraph under "Syntax" on each of those subpages from something like "The `<display-inside>` value is defined using a keyword from the list below" to "Valid `<display-inside>` values", the output will look pretty good.

Another option would be to change the "Syntax" heading on the `<display-*> pages to "Legal &lt;display-*&gr; values", then using those titles instead of "Syntax" in each of the `{{page}}` macro calls.

The result: a nice, neatly-formatted list of all of the possible values for the `display` property.

**Comment by dominicegginton** [comment]
Hi, following the recommendation above I have updated this [page](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display) page to display a much better list of values for the CSS display property. Using an updated summery on each of child pages for each category the list is much easier to understand. Can this issue be closed ?

**Comment by chrisdavidmills** [comment]
yup, this looks good!
