### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### ISSUE THREAD

**Issue by ghost** [mdn/sprints#1161]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

One of the notes said:

> Note: Sanitizers run during validation do not modify the request. That is why we have to call trim() in both steps above!

But according to [the doc](https://express-validator.github.io/docs/sanitization.html):

> In the example above, we are validating email and text fields, so we may take advantage of the same chain to apply some sanitization, like e-mail normalization and trimming/HTML escaping.

Based on simple test, I assume sanitization during validation do modify the request.

**Comment by hamishwillee** [comment]
You're right. The behaviour changes in the validator in 5.0, but the docs and code were not updated properly to match this. All done now in both the docs and github example repo.

**Comment by hamishwillee** [comment]
PS Thanks for posting!
