### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

### ISSUE THREAD

**Issue by bobOnGitHub** [mdn/sprints#1163]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

Current content : "When an HTML document has been switched to designMode, its document object exposes an execCommand method "

Testing today on Chrome,Firefox and MS Edge and designMode has no effect ie. execCommand is available both when designMode = "on" and when designMode = "off"

**Comment by chrisdavidmills** [comment]
You are right; this makes no sense. I have updated the description to remove this part.
