### ISSUE TITLE
Page not found: https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Offline

### ISSUE THREAD

**Issue by lucacesarini** [mdn/sprints#1165]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Following page is not found: https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Offline

I arrived there via a link on this section: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API#Key_concepts_and_usage (third point)

**Comment by chrisdavidmills** [comment]
This page was deleted because it awas very out of date. I've updated the link to something more suitable.
