### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/tag/Security

### ISSUE THREAD

**Issue by Srichon-Boontharikwong** [mdn/sprints#1168]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

**Comment by chrisdavidmills** [comment]
No details as to what is wrong with the page, so closing.

**Comment by Srichon-Boontharikwong** [comment]
@Srichon-Boontharikwong
