### ISSUE TITLE
BCD: border-block-end

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1173]
https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end is supported in Chrome. I assume all the associated border-block properties are too. We need to check all and update the BCD

**Comment by rachelandrew** [comment]
I've been going round these recently so I can do these ones as well.

**Comment by rachelandrew** [comment]
PR for this data: https://github.com/mdn/browser-compat-data/pull/3717

**Comment by rachelandrew** [comment]
PR is merged so I think this is all done.
