### ISSUE TITLE
Firefox OS references in "H.264 support in Firefox"

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1176]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
The [H.264 support in Firefox](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/H.264_support_in_Firefox) page has a big section on Firefox OS, and other mentions throughout the article. These should all be removed.

**Comment by jmswisher** [comment]
Via Slack from @callahad

**Comment by chrisdavidmills** [comment]
I deleted all the Firefox OS content and saved it, but then it seemed like somewhat of a stub, and some of it was still out of date.

So instead, I decided to redirect it to a more useful page — https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery.
