### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by deqq1** [mdn/sprints#1179]
https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial

There is a link leading to 404

The end of the first section. The link is labeled as "(и не очень)"
https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Web/API/Canvas_API/A_basic_ray-caster

**Comment by chrisdavidmills** [comment]
It looks like the problem is that there is no Russian version of the raycaster tutorial. I've replaced it with a link to the English version.
