### ISSUE TITLE
FormDataEntryValue

### ISSUE THREAD

**Issue by 243** [mdn/sprints#1181]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

Hello, 
On [the documentation page for FormData.getAll()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/getAll) there's a dead link to the [FormDataEntryValue](https://developer.mozilla.org/en-US/docs/Web/API/FormDataEntryValue) class documentation, which returns a 404.

**Comment by irenesmith** [comment]
Created a page to define the FormDataEntryValue as follows:

A string which represents a single value from a set of FormData key and value pairs.

This type is returned by the FormData.get() and FormData.getAll() methods. The FormData.get() mthod returns a single value while FormData.getAll() returns an array of FormDataEntryValues.

**Comment by chrisdavidmills** [comment]
We don't really have a set page structure for type pages, and tend to just put the information on the interface member that returns/uses them, since generally they are only used in one or two places.

I think this is OK for now, but we'll have to think more about this in future.

**Comment by TomasHubelbauer** [comment]
Hey, could anyone please updated the page for `FormDataEntryValue`? I believe it should be a union of string, `Blob` and `File` interfaces, but I want to make sure.

**Comment by jmswisher** [comment]
Hi @TomasHubelbauer:

The [spec](https://xhr.spec.whatwg.org/#formdataentryvalue) says it is a string or a File. Blob is not part of the type definition. You can append() a blob, but it gets turned into a File in the process. I'll update the page.

**Comment by TomasHubelbauer** [comment]
I didn't know that, thanks!
