### ISSUE TITLE
Documentation missing for HTML5 video textTracks

### ISSUE THREAD

**Issue by pra5h** [mdn/sprints#1185]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

URLs: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/textTracks, and
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList
Results In: 404 (Not found)

Navigation links for these are available on the following URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by estelle** [comment]
New Pages:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/textTracks
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/change_event
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/onchange
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/addtrack_event
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/onaddtrack
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/removeTrack
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/onremovetrack_event
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/getTrackById
https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList/length

Next:
https://developer.mozilla.org/en-US/docs/Web/API/TextTrack
