### ISSUE TITLE
The "counters" link in "Using CSS counters" documentation page is broken

### ISSUE THREAD

**Issue by CDT** [mdn/sprints#1188]
Reading [Using CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) page and the [link ](https://developer.mozilla.org/en-US/docs/Web/CSS/counters())here redirects me to a 404 page:
![image](https://user-images.githubusercontent.com/3616970/54401447-b09b8680-4702-11e9-9997-04330e803a17.png)

[counters](https://developer.mozilla.org/en-US/docs/Web/CSS/counters()) link: 
![image](https://user-images.githubusercontent.com/3616970/54401512-ed677d80-4702-11e9-82ec-9639db7bc858.png)

**Comment by estelle** [comment]
Tasks:

* [X] - disable links until pages are created
* [X] - create cursor() page
* [ ] - link cursors to cursor
* [X] - example
* [ ] - BCD
* [X] - Syntax
* [ ] - link from function page
* [ ] - re-link from how to use cursor page
* [ ]  - link from counter-reset
* [ ]  - link from counter-increment
* [ ] - link from genterated style page

* [ ] - update BCD on counter-increment


* [ ] - counter-style page
