### ISSUE TITLE
Link to dive in accessibility is pointing to a wrong website

### ISSUE THREAD

**Issue by fawmi** [mdn/sprints#1189]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The page https://developer.mozilla.org/de/docs/Web/Barrierefreiheit/Webentwicklung has a link called "Dive into Accessibility" which is supposed to be a guid on accessibility but it is a company website in som other langauge (I think spanish).

**Comment by chrisdavidmills** [comment]
I've deleted it; it doesn't seem to exist anymore.

the English version of the accessibility page on MDN has bene updated; it'd be great to find a German community member to do the same for the German version.
