### ISSUE TITLE
"Other content in SVG article" missing an image

### ISSUE THREAD

**Issue by brunnock** [mdn/sprints#1193]
# Request type
- Correction or update

# Details
On https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Other_content_in_SVG,
there is live code that references a missing image.

https://developer.mozilla.org/media/img/mdn-logo.png

**Comment by jwhitlock** [comment]
Thanks for the report. This was an [old version of our logo](https://github.com/mozilla/kuma/blob/master/assets/legacy/img/mdn-logo.png) that I recently removed from the website. I've updated it to our [largest favicon](https://github.com/mozilla/kuma/blob/master/assets/static/img/favicon144.png), and uploaded a new screenshot to [Other content in SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Other_content_in_SVG#Embedding_raster_images).
