### ISSUE TITLE
Write guide articles for related events

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1194]
(note: this story is just a placeholder for now and needs more definition)

Many events form closely related groups. For example:

* transition events
* animation events
* clipboard events

In the event reference we have a docs page for each event, but we don't have a place to talk about how the different events fit together: for example, the order they go in and which events in a group fire in different situations.

We should have guide pages for groups of events that covers this kind of stuff, that we can link to from the event reference pages. They don't have to be super-detailed.

**Comment by irenesmith** [comment]
Also mouse events and touch events.
