### ISSUE TITLE
[dead_link]

### ISSUE THREAD

**Issue by stanpetit** [mdn/sprints#1195]
Hi *  
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Database#History_tables
 at bottom of §, offers a reference, as :
>See [Bookmarks service design](https://developer.mozilla.org/en-US/Places/Bookmarks_Service/Design) for more information.  

this is a dead link :  
https://developer.mozilla.org/en-US/Places/Bookmarks_Service/Design

this is the nice expected link :  
https://developer.mozilla.org/en-US/Places/Bookmarks_Service/

best.

**Comment by jmswisher** [comment]
Thanks for reporting this, and for finding the correct page to link to. The original link was for a design document that never got added to MDN. I fixed the link to use the current page title.

I also removed a link to that non-existent design document (and another one) from the [Places landing page](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places). 

BTW, MDN is a wiki, so if you find a problem that you know how to fix, you can login with your GitHub credentials and fix it yourself.
