### ISSUE TITLE
Setting up a Node development environment - Using NPM section

### ISSUE THREAD

**Issue by MJay1982** [mdn/sprints#1196]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details
I may be missing something - I'm very new.  In step 5 of the section Using NPM on the "Setting Up a Node development environment" page, it mentions adding a require statement to "your index.js file."  However, if you follow the steps from the beginning, an index.js file is never generated.

**Comment by MJay1982** [comment]
Oh, I see.  The direction to create the file is below the instruction to add the require to the file.  Pretty confusing!

**Comment by chrisdavidmills** [comment]
I can see how this could trip people up. I've changed the order around so that it tells you to create the index.js file above the code block instead. Is this better now?
