### ISSUE TITLE
Dead link to WebGL learn page

### ISSUE THREAD

**Issue by AdelMahjoub** [mdn/sprints#1199]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

404 error on https://developer.mozilla.org/fr/docs/Learn/WebGL

**Comment by chrisdavidmills** [comment]
Where did you find the link to this page? We removed it a while ago; any links to it should also be gone, but we probably missed some.

**Comment by AdelMahjoub** [comment]
In the french language page.

**Comment by chrisdavidmills** [comment]
We deleted that section of pages as they weren't useful. I have removed the dead link.
