### ISSUE TITLE
Firefox 61 Layout DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#12]
As a Web developer I want to know about the latest Layout features in Firefox 61, so that I can test and make use of new technologies.

**Comment by chrisdavidmills** [comment]
1. - [ ] [Toggle the pref to disable @-moz-document in content pages on release](https://bugzilla.mozilla.org/show_bug.cgi?id=1422245)

**Comment by jmswisher** [comment]
Re task 12, see also https://github.com/mdn/browser-compat-data/pull/1990
