### ISSUE TITLE
Docs: X-Frame-Options have inconsistent values

### ISSUE THREAD

**Issue by flowl** [mdn/sprints#1200]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

On the following site, some values are uppercase and later lowercase and it is not apparent which one is correct or which one should be used (aka best practice) when they are mixed like that.

https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options

    X-Frame-Options: DENY
    X-Frame-Options: SAMEORIGIN
    X-Frame-Options: ALLOW-FROM https://example.com/

On the english version there is strictly lower case writing:

    X-Frame-Options: deny
    X-Frame-Options: sameorigin
    X-Frame-Options: allow-from https://example.com/

**Comment by Elchi3** [comment]
The header fields are case-insensitive and I've updated the translation to follow the English version here. Thanks for your report!
