### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by SetTrend** [mdn/sprints#1204]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The MDN page [Node::getRootNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) states that this function returns an object of type `Node`. Yet, shouldn't it state, instead, that this function returns an object of type `ShadowRoot`?

**Comment by chrisdavidmills** [comment]
No; it's not specific to shadow DOM. See getRootNode()  under https://dom.spec.whatwg.org/#interface-node

**Comment by SetTrend** [comment]
@chrisdavidmills:

There is no `host` property in the [`Node`](https://dom.spec.whatwg.org/#interface-node) interface.

Please verify. Probably the WhatWG spec is wrong here?

**Comment by chrisdavidmills** [comment]
Now I'm confused. The WHATWG DOM spec doesn't state that the `Node` interface has a `host` property. And [neither do we](https://developer.mozilla.org/en-US/docs/Web/API/Node).

host is on [`ShadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/host).

**Comment by SetTrend** [comment]
The fog seems to be lifting ... I got a very helpful reply from the WhatWG group:

**Comment by chrisdavidmills** [comment]
Ah, now I understand the source of your confusion; thanks for linking this thread! Yes, the inheritance of objects inside the DOM API world can be very confusing. On MDN we stick to a structure based on the inheritance of these objects just to keep things manageable, but I appreciate that many people have been tripped up by it (you are by no means the first).

I tried adding a better explainer of the getRootNode() return value; does this make things clearer?

https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode#Returns

**Comment by SetTrend** [comment]
Excellent amendment! I think this will avoid a lot of confusion on the return value of this function in the future.

Thanks a lot, @chrisdavidmills

**Comment by chrisdavidmills** [comment]
@SetTrend you're welcome; thanks for reporting this, and working with me to reach a good conclusion!
