### ISSUE TITLE
hidden attribute guidance is misleading

### ISSUE THREAD

**Issue by Kuzcoo** [mdn/sprints#1216]
# Request type
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

In the documentation it says that we can't use *hidden* attribute for tab element, as such as a role tablist element.

> For example, it is incorrect to use hidden to hide panels in a tabbed dialog (...)

I read through the [HTML 5.1 recommendation](https://www.w3.org/TR/html51/editing.html#the-hidden-attribute) linked at the end of the page, and this is not what I understand.

Note that I first came from the French translation of this mdn page, where it explicitly states that we do not have to use it for "onglets" (litterally a tab element with role tablist).

Furthermore the [w3c tabs example](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) uses it.

Could we have a little explanation about this statement ?

Thank you :+1:

**Comment by wbamberg** [comment]
You are right! This bit of advice was apparently copied from an old version of the spec, compare:

* https://www.w3.org/TR/2016/WD-html51-20160412/editing.html#the-hidden-attribute (April 2016)
* https://www.w3.org/TR/2016/WD-html51-20160602/editing.html#the-hidden-attribute (June 2016)

Specifically, it was removed in https://github.com/w3c/html/commit/7ca629598e29c564ffa73dccf02d9614ba70f2e5, in response to this issue: https://github.com/w3c/html/issues/203, which also reference this more enlightening issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=19159.

I've just removed that bit from the page.
