### ISSUE TITLE
Page maintenance: Choose criteria for Tier 1 pages

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1217]
# User story
As an MDN writer, I want to know which pages are most important so I can make informaed choices about which ones should be given regular maintennce.

# Acceptance criteria

1. - [x] Write suggestions on what criteria we need, share them with the team, get agreement.
2. - [x] Work out how we could feasibly measure those criteria and represent them in the spreadsheet.
3. - [x] Work out what the cutoff point is for Tier 1, for each content category.
4. - [x] Work out what should happen to Tier 2 pages.

**Comment by chrisdavidmills** [comment]
The maintenance plan is here: https://docs.google.com/document/d/1_ryTfwcvLOr1b75ekVh590BaJfz_rUo-E_f-jTbSbUU/edit#heading=h.7s2y58o36i1n

**Comment by chrisdavidmills** [comment]
The maintenance spreadsheet as it stands is here: https://docs.google.com/spreadsheets/d/1M1eD9jdqAKnR6Mx-CTqKnoD2Wlr3e1IRtQDE_i4EdYM/edit#gid=1783999067

**Comment by chrisdavidmills** [comment]
@a2sheppy r?

**Comment by a2sheppy** [comment]
I added some comments with questions and thoughts to the doc, and one note to the spreadsheet. Otherwise this looks great to me.

**Comment by chrisdavidmills** [comment]
Thanks mate.
