### ISSUE TITLE
Learn CSS Rewrite: Backgrounds and Borders

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1219]
Covering some of the interesting backgrounds and borders things which don't really sit neatly anywhere else.

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Backgrounds_and_Borders

First draft, this has become an exercise in what to leave out really as I could head down any number of rabbit holes. So if you think I have missed something you think is important let me know.

Two things I haven't covered and wanted your thoughts on:

1. border-images: my thinking is to leave this out as it gets a bit fiddly.
2. Shadows: which might be an interesting one to add.

**Comment by chrisdavidmills** [comment]
Hey there!

I've read through this one and made some edits. I think it looks really good overall; you've done a pretty good job of choosing the most vital bits to cover.

A couple of comments:

1. background-position: 4 value syntax needs explaining; afaict, the only way you can use 4 values is with two lots of keyword followed by length/percentage. You are in effect saying "this far from one edge, and this far from another edge". The text in the article doesn't seem to adequately explain this. Or have I got this confused?
2. border-radius syntax needs more explanation. What about all the varied shorthand stuff? 

I'm happy for you to leave out border-images, as they are definitely on the advanced side; you don't need them at the beginner level, and it makes me wonder how many people have used them full stop really.

For box-shadows, I've got them covered in the Advanced box effects article — https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_boxes/Advanced_box_effects

I wondered if we could keep this one, to cover that, plus the other interesting bits it covers?

**Comment by chrisdavidmills** [comment]
> I'm not really sure what you are asking for here, that detail is all fairly clear on the property page and I haven't broken down any other properties to that extent. Can you explain more about what you think is missing?

Hrm, I suppose so; it just seems to be missing a bit of detail. To solve this, maybe during the exercise bit where they are asked to change the corners on the box, we could invite them to  check out the border-radius reference page to see more syntax options?

> I'm not sure I understand this statement, it's an offset. I have added a sentence to indicate that it is an offset.

I think it was the 4-value nature of the syntax I was concerned about (the previous examples were two). I have made a couple more changes,  and now I'm happy.

**Comment by rachelandrew** [comment]
I've added a link to the property page. I looked at this again and I really don't see the point of essentially reiterating the property page here. The only time you need to use the syntax with the slash is if you want to use the shorthand to set all four values AND are using elliptical borders. I don't think I've ever come across anyone doing it in the wild, I certainly haven't. So it seems to me we would be adding something that looked very complex at this stage, that people just don't use a lot. We haven't done this for other things, and we do have it all nicely detailed on the property page.

**Comment by chrisdavidmills** [comment]
OK, makes sense. I think we are good to go on this one.
