### ISSUE TITLE
 Bug 1518482 Google is reporting 38,811 server errors during crawling

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1224]
# Description
We removed a bunch of docs from being indexed by Google which helped with bug 1518482, but since they are also in robot.txt, they can't be crawled, so will still index them, just without any content. 

# Original report
See https://bugzilla.mozilla.org/show_bug.cgi?id=1518482 for activity and discussion

# Acceptance Criteria
- [ ] zero errors in search console for docs that are indexed, but not allowed to be crawled

**Comment by jwhitlock** [comment]
Google has switched to the new Search Console, and it appears the 38,811 error report was on the "old" console and no longer available.

The current error count is 337 errors on submitted page, and 369 on all known pages.

**Comment by tobinmori** [comment]
closing. superceded by other more specific issues handling this.
