### ISSUE TITLE
Convert "beta" endpoint to React

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1225]
# Original Description
We'd like to move towards a React-based frontend for MDN, but we need to figure out how to get there.

I'm filing this bug to track some experimental work we'll do to figure out whether we can incrementally convert Kuma to use React or if we need to start from scratch.

This experimental work will probably look like this:

-  Create a new Kuma endpoint en-US/beta/ that does exactly the same thing as en-US/docs/ (but that only works on the staging server and is never visible to end users).

- Modify that new endpoint so that it uses React in some small way (like displaying the MDN logo). As part of this we'll also set up the webpack/babel toolchain, and get flow and jest snapshot tests working. Then we'll measure the performance of this new part-React, part-jQuery page and compare it to the existing /docs endpoint to get baseline data on the performance impact of adding React. (We'll have to decide whether to use React libraries from a CDN or not)

-  Do more substantial work with React, perhaps replacing the navigation header at the top of the page, and removing the jQueryUI library that it depends on. And see what the performance impact of that is.

-  Attempt to set up client-side navigation (possibly using react-router) to see how fast we can load new documents when we don't have to do a complete page load.

-  Investigate server-side rendering of our React content to see what the performance impact of that is and to figure out how to do that for both the logged-out and the logged-in case.

# Original report
https://bugzilla.mozilla.org/show_bug.cgi?id=1525719

**Comment by davidflanagan** [comment]
Bug 1525719 is roughly equivalent to the Kuma.Next epic. So all of my tasks this sprint are part of this one bug. But We don't need a separate issue for this because, https://github.com/mdn/sprints/issues/766 is this issue. So I'm going to close it.
