### ISSUE TITLE
Old CSScoverage MDN page to be removed

### ISSUE THREAD

**Issue by captainbrosset** [mdn/sprints#1227]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This MDN page is outdated and should be deleted: https://developer.mozilla.org/en-US/docs/Tools/CSS_Coverage 

It refers to a GCLI command that a) was never really available by default and, b) doesn't work anymore since GCLI got removed.

**Comment by chrisdavidmills** [comment]
Deleted!
