### ISSUE TITLE
Dead link https://developer.mozilla.org/en-US/docs/Web/API/RequestCredentials

### ISSUE THREAD

**Issue by FredrikOhrn** [mdn/sprints#1228]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
From page https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials under section "Syntax" the link to "RequestCredentials" (https://developer.mozilla.org/en-US/docs/Web/API/RequestCredentials) is dead.

**Comment by chrisdavidmills** [comment]
Fixed — I've switched the page around so that it doesn't require a link to a separate dictionary page to explain this.
