### ISSUE TITLE
Write a document to help guide structured content experiments

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1229]
We'd like to understand better whether and how we can change MDN content from unstructured HTML into a structured format. This would:

1. enable us to present content in different contexts (editors, devtools),
2. free writers from spending time on presentational aspects such as formatting tables, and
3. ensure docs are presented consistently.

We have an idea of what we might like the final state to be, but:
1. we haven't tested whether this final state is really practical, and
2. getting there from here is difficult.

In this story we will outline the proposed final state and talk a bit about how we might try to get there.

We will also describe questions and risks that we'd like to understand better. In subsequent stories we will design and run experiments to try to address these questions and risks.

******

AC: document is written and reviewed by @chrisdavidmills , @atopal , @escattone @Elchi3 .

**Comment by jmswisher** [comment]
This was marked as "continue in next sprint" in India.Arie, but wasn't added to the tab for Jessye Norman (or Koko Taylor). Is it still a valid issue?

**Comment by wbamberg** [comment]
>  Is it still a valid issue?

I can't even remember. I think we should just close it.
