### ISSUE TITLE
This page does not exist anymore

### ISSUE THREAD

**Issue by Zinavolia** [mdn/sprints#1233]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This page does not exist anymore : 
https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_to_HTML/Structuring_a_page_of_content

**Comment by chrisdavidmills** [comment]
The correct URL for this page is https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_%C3%A0_HTML/Structuring_a_page_of_content.

Have you found the incorrect link uaed somewhere?

**Comment by Zinavolia** [comment]
On this page when we click on next it does not work : https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_%C3%A0_HTML/Marking_up_a_letter

**Comment by chrisdavidmills** [comment]
OK, thanks!

I have fixed the broken link.

**Comment by Zinavolia** [comment]
ok thank's

**Comment by Zinavolia** [comment]
Ce n’est toujours pas à jour...

**Comment by chrisdavidmills** [comment]
Just to check — we are talking about the "Suivant" button, correct?
