### ISSUE TITLE
dead link https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint/fromPoint

### ISSUE THREAD

**Issue by Christopher-Hayes** [mdn/sprints#1235]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
The left navigation bar at https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint has a section for functions with the function fromPoint(). This function should be a link to a mozilla web docs page at https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint/fromPoint about the function fromPoint(); however, it is a deadlink. In the content of the page there is a link to the same function found at https://developer.mozilla.org/en-US/docs/Web/API/DOMPointReadOnly/fromPoint It should be noted that DOMPoint inherits functions from DOMPointReadOnly so I'm assuming https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint/fromPoint should redirect to https://developer.mozilla.org/en-US/docs/Web/API/DOMPointReadOnly/fromPoint

**Comment by jmswisher** [comment]
The sidebar link on the DOMPoint page now works properly, and leads to DOMPoint.fromPoint(), which has unique content different from DOMPointReadOnly.fromPoint().
