### ISSUE TITLE
Dark mode for MDN

### ISSUE THREAD

**Issue by Nabeegh-Ahmed** [mdn/sprints#1236]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

why there is no dark mode?
# Details

**Comment by wbamberg** [comment]
Thanks for filing. This request comes up from time to time (see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1427452) but unless something has changed, we're not planning to support a dark mode in MDN.

Pinging @atopal anyway just to confirm that this is still the position (and to register this request).

**Comment by atopal** [comment]
Yes, confirming that we don't have plans for a dark mode at this time.
