### ISSUE TITLE
Broken link to XPI installation module

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/sprints#1238]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[XPI | MDN](https://developer.mozilla.org/de/docs/XPI) links to [XPI-Installationsmodule erzeugen](https://developer.mozilla.org/de/XPI-Installationsmodule_erzeugen) (create XPI installation module).

I looked into XPI in conjunction with [Splinter docs](https://splinter.readthedocs.io/en/latest/drivers/firefox.html#how-to-use-specific-extensions-for-firefox).

**Comment by irenesmith** [comment]
I'm sorry for any inconvenience, but apparently, this page is a translation of a page that has been archived due to the fact that it is outdated.

**Comment by Ryuno-Ki** [comment]
Hi @irenesmith,
fair enough.

Could it be a symptom for other outdated content / broken references?
I found what I need, just wanted to bring it up so you could do some spring cleaning :-)

**Comment by irenesmith** [comment]
Thank you for bringing up the subject. We are working on removing outdated extension documentation but it's nice when readers take the time to comment on these things.
