### ISSUE TITLE
when we scroll on the page we have a div that comes put it on top in sticky I guess and we distinguish that it's border

### ISSUE THREAD

**Issue by Zinavolia** [mdn/sprints#1239]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

on this page : 
https://developer.mozilla.org/fr/docs/Apprendre/HTML/Comment/Ajouter_des_images_adaptatives_%C3%A0_une_page_web

when we scroll on the page we have a div that comes put it on top in sticky I guess and we distinguish that it's border

**Comment by boxa6** [comment]
This problem is only in the English version of the page.

**Comment by Zinavolia** [comment]
no, the french version too because I'm french and I noticed on this page

**Comment by jwhitlock** [comment]
I did not see the sticky div on the English version, only the French. It appears to be a div that has classes used by CKEditor for editing mode. 

I removed it in Source / HTML mode, from the bottom of the page. There were some other issues I noticed in Source editing mode, such as ``<pre>`` blocks copied with JS-generated style spans. It makes for a [big diff between versions](https://developer.mozilla.org/fr/docs/Apprendre/HTML/Comment/Ajouter_des_images_adaptatives_%C3%A0_une_page_web$compare?locale=fr&to=1530216&from=1500625), but I believe the content is the same, minus that sticky border div.

**Comment by estelle** [comment]
Is anyone still seeing this? i can not replicate. Please let me know or close as fixed. thanks.

**Comment by chrisdavidmills** [comment]
I believe this is fixed; closing. We can always reopen if anyone is still the problem.
