### ISSUE TITLE
Wrapped js object .  Link https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/en/How_to_Build_an_XPCOM_Component_in_Javascript

### ISSUE THREAD

**Issue by roni5** [mdn/sprints#1241]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update
Wrapped js object .  Link https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/en/How_to_Build_an_XPCOM_Component_in_Javascript

# Details

**Comment by 24-X** [comment]
24
