### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

### ISSUE THREAD

**Issue by xubres** [mdn/sprints#1243]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

The Active learning in quotations does not work.
![Screenshot from 2019-03-25 22-56-30](https://user-images.githubusercontent.com/47870434/54953591-49c36c00-4f51-11e9-8304-dd21f08c4160.png)
I think I have found what the problem is.
In the var htmlSolution in the javascript there is a single quote after Confucius which messes up the whole formatting.
But I am too scared of editing and trying it out in case I make a mistake, because I am just learning and haven't done this before.
Hope this helps.

**Comment by chrisdavidmills** [comment]
You are correct — someone has gone and broken the example by unescaping the single quote. I have added the escape character back in, and now irt works again. Thanks for reporting!
