### ISSUE TITLE
touch events are 404

### ISSUE THREAD

**Issue by Coopersamjohn** [mdn/sprints#1244]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/Events#Touch_events
clicked MozEdgeUIGesture (https://developer.mozilla.org/en-US/docs/Web/Reference/Events/MozEdgeUIGesture) and it said not found and to report it, so I reported it
same with MozMagnifyGesture and the rest, it seems.
.https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Events/MozMagnifyGesture

**Comment by irenesmith** [comment]
The page actually says that it was deleted: "Event out of date — relates to an obsolete add-ons system that is no longer available." Closing issue.
