### ISSUE TITLE
<video> element: add duration and currentTime attributes

### ISSUE THREAD

**Issue by JunoVW** [mdn/sprints#1249]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the Events section, two events mention that they do something with either the `currentTime` or `duration` attribute, however neither of these two are described in the attributes section.

**Comment by estelle** [comment]
Please advise what issues you found so we know what to update. Thank you.

**Comment by a2sheppy** [comment]
These missing attributes have now been added to the <video> element page, as well as to <audio>. Also reviewed the other pages that are part of documenting these two properties across these elements and `HTMLMediaElement`:

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
