### ISSUE TITLE
Promise example problems

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1251]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
See https://github.com/mdn/interactive-examples/issues/1330 for details.

**Comment by jadjoubran** [comment]
Happy to take this one 🙋🏻‍♂️

**Comment by jadjoubran** [comment]
This can be closed now ✅

**Comment by chrisdavidmills** [comment]
cheers @jadjoubran !
