### ISSUE TITLE
In CSS docs, properties are missing in left nav panel.

### ISSUE THREAD

**Issue by estaub** [mdn/sprints#1260]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

- At https://developer.mozilla.org/en-US/docs/Web/CSS/background , property `background-size` is missing from the left nav panel.
- At https://developer.mozilla.org/en-US/docs/Web/CSS/flex , flexbox properties `justify-content`, `align-items`, `align-self`, and `align-content`are missing from the left panel.

# Notes

This may be a content problem or a code (auto content generation) problem, it's hard to guess.

Apologies in advance if I'm misfiling this in some way.  It's my first.

**Comment by jmswisher** [comment]
P2 to investigate the scope of the problem.

**Comment by a2sheppy** [comment]
For `background`, `background-size` is in fact there; it's up at the top with a much longer name: "CSS background-size — Set size of an element's background image". This is an unfortunate side effect of an experiment we are running for the next three weeks or so. These titles will be fixed back to their expected names when the experiment is over.

If we decide to follow up by renaming all CSS reference pages, we will first update the code that generates things like the sidebars to make sure the sidebar contents are as expected.

**Comment by rachelandrew** [comment]
The 'flexbox' properties actually belong to CSS Box Alignment, which is why they are defined there:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Alignment

**Comment by estaub** [comment]
@rachelandrew Is there perhaps a "See also" mechanism for linking to that from the nav property list for flex?

**Comment by estaub** [comment]
@rachelandrew Also consider adding a link from the flexbox "guides" list in the left nav to the "CSS Box Alignment" page.

Separately, I should point out that the [CSS Flexible Box Layout
](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout) lists the "missing" properties in its body, so if you meant to say that these properties should _only_ be listed under "CSS Box Alignment", this seems inconsistent.  My preference, FWLIW, would be to simply add them to the flex property list too, redundantly.
