### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Testing/ASan_Nightly_Project

### ISSUE THREAD

**Issue by rugk** [mdn/sprints#1261]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Download links on https://developer.mozilla.org/en-US/docs/Mozilla/Testing/ASan_Nightly_Project#Requirements are broken.

You likely just need to replace the v57 with v68. (and possibly keep it up-to-date, or use a symbolic link/redirection or so, so it does not break again.)

**Comment by wbamberg** [comment]
@choller, the docs under /Mozilla are no longer maintained by the MDN team, but since I saw you've updated this page recently, I thought you might want to be aware of this bug report.

**Comment by choller** [comment]
Thanks for pinging me on this. It looks like Kwan already changed the page to directly link to TC, so this should be fixed.
