### ISSUE TITLE
"JavaScript performance best practices" needs to be written

### ISSUE THREAD

**Issue by MateYCode** [mdn/sprints#1262]
On this page:
https://developer.mozilla.org/en-US/docs/Learn/Performance?utm_campaign=mar28-2019&utm_medium=email&utm_source=dev-newsletter&utm_content=performance

there is a link to JavaScript performance best practices: https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript, whose response is 404.

# Details

**Comment by 24-X** [comment]
301:dopeniz.net
