### ISSUE TITLE
Keyboard.Event code missing keys for MacOS

### ISSUE THREAD

**Issue by jameswilddev** [mdn/sprints#1263]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The section in https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code for MacOS seems to be missing a few keys:

- `KeyN`
- `KeyM`
- `Backslash`
- `Comma`
- `Period`
- `Slash`

However, I do not have access to a Mac to confirm.

**Comment by irenesmith** [comment]
These are the values that need to be added:

  kVK_ANSI_Backslash (0x2A)
  kVK_ANSI_Comma     (0x2B)
  kVK_ANSI_Slash     (0x2C)
  kVK_ANSI_N         (0x2D)
  kVK_ANSI_M         (0x2E)
  kVK_ANSI_Period    (0x2F)

**Comment by irenesmith** [comment]
I have broken the page into two pages. The new page [KeyboardEvent: code values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values) contains the tables with the items listed above added to the macOS table.

The original page: [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) has a link to the tables near the top of the page under the heading [Code values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#Code_values).
