### ISSUE TITLE
L10n and i18n page can not found

### ISSUE THREAD

**Issue by berrynana** [mdn/sprints#1265]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

https://developer.mozilla.org/ko/docs/Web/Localization
can not found page

**Comment by chrisdavidmills** [comment]
This page does not exist; did you find it linked from somewhere?

**Comment by jmswisher** [comment]
The English page has been deleted, so there should not be a Korean page either. If there is a link to it somewhere, that needs to be fixed.
