### ISSUE TITLE
broken "Creating and editing apps" link on WebIDE page

### ISSUE THREAD

**Issue by skierpage** [mdn/sprints#1267]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link "Creating and editing apps" on the MDN page https://developer.mozilla.org/en-US/docs/Tools/WebIDE is a 404, at least on mobile. It goes to https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Creating_and_editing_apps

**Comment by irenesmith** [comment]
This content no longer exists because WebIDE is scheduled for removal from Firefox. See [Deprecated tools](https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools) for details about WebIDE, the Connect... page, and other deprecated DevTools.
