### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

### ISSUE THREAD

**Issue by vouser** [mdn/sprints#1269]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On 

	https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

search for

	can more results

I believe you are missing a verb. And I am not sure that 'results' is the right word. I suggest

	can match a wider range of strings

But I will be happy with any wording that is accurate and clear

**Comment by irenesmith** [comment]
Thank you for pointing that out to us. I have updated the text to:

"Patterns can include special characters so they can match a wider range of values than would a literal string."

**Comment by vouser** [comment]
Good change. In this context, 'values' is a better word than 'strings'. And probably would be even if there were not a conflicting use of 'string' later in the sentence.

I had a feeling there was a reason that Mozilla has you 🧠✍️ writing the documentation instead of me!

**Comment by irenesmith** [comment]
Thanks! Compliments always appreciated.
