### ISSUE TITLE
Add intent to unship WebIDE and Connect to Deprecated Tools

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1270]
Add the contents of the following document to the Deprecated Tools page:

[Intent to Unship WebIDE and Connect](https://docs.google.com/document/d/1IkspRylsZGSccGrZDKYFyPHXFCaGIMOtqkGh0BTpz14/edit#heading=h.sbwd7bvlk39w)

# Acceptance Criteria
- [x] Information has been added to [Deprecated tools](https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools)
- [x] Deprecation notice added to Firefox 67 Release notes

**Comment by juliandescottes** [comment]
Thanks Irene!

Some comments on the current text:

> The existing WebIDE and Connect... tools will provide a deprecation notice as of Firefox 68

The deprecation notice is only on WebIDE. Reasoning is that Connect... page has very little usage.

> The new tools on the about: debugging

"about: debugging" should be `about:debugging` 

> The Connect Page is by selecting Tools > Web Developer > Connect…

The Connect Page ~is~ by selecting [...] ?

> The ability to to change the preferences

to to -> to

Looking at the sections for the other deprecated tools, they feel more compact. Maybe we should follow the same pattern here? Toolname, current status, description, screenshot, alternative. I don't know if we need to give that many details (the information might also need to be updated as we port some missing features over).

Took a stab at this for WebIDE, but feel free to ignore it :)

> ## WebIDE
> 
> WebIDE is currently deprecated, will be disabled by default in Firefox 69, completely removed in Firefox 70.
> 
> WebIDE allowed you to connect the Firefox Developer Tools to other remote browsers, such as Firefox for Android. It was also intended to support application development for Firefox OS.
> 
> [Screenshot]
> 
> **Alternatives** : Remote debugging is available in `about:debugging` as of Firefox 68. Features not ported to about:debugging are: WiFi debugging for Firefox for Android, application development. Features that are planned but not ported yet: remote browser screenshots and edit remote browser configuration. More details on the [mailing-list thread](https://groups.google.com/forum/#!topic/mozilla.dev.developer-tools/aWA7JJ-TpRw).

**Comment by jmswisher** [comment]
@irenesmith I'm adding this to the next sprint, so you can respond to Julian's comments.

**Comment by irenesmith** [comment]
@juliandescottes I took your advice and used your suggestion. I did provide the deprecated, disable, and removed notice as in the others. I also took a screenshot of WebIDE from Nightly to show the deprecation notice.

**Comment by irenesmith** [comment]
This should be considered done now. In addition to making the suggested edits, I have also added links to the bugs for disabling and removing the tools.

**Comment by chrisdavidmills** [comment]
Page is looking great, nice work @irenesmith. I sneaked in and promoted the tool titles to h2s, so they would appear in the jump menu at the top of the page. Hope that's OK.

So for this one, we're just waiting for @juliandescottes to OK the updates, then we can close.

**Comment by juliandescottes** [comment]
Looks great @irenesmith thanks! Could we just make "mailing-list thread" a link pointing to https://groups.google.com/forum/#!topic/mozilla.dev.developer-tools/aWA7JJ-TpRw ?

**Comment by irenesmith** [comment]
Done. I also added a level 3 header "Description" to match the other entries.

**Comment by irenesmith** [comment]
@chrisdavidmills I added the requested link. Thank you for promoting those headers. It looks better anyway. So I think we're done here. :D

**Comment by chrisdavidmills** [comment]
Perfect; closing!

**Comment by chrisdavidmills** [comment]
oops.

**Comment by irenesmith** [comment]
Per this bug: [Bugzilla 1553033](https://bugzilla.mozilla.org/show_bug.cgi?id=1553033) these changes were moved back one release from 68, 69, 70 to 69, 70, 71.
