### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

### ISSUE THREAD

**Issue by vouser** [mdn/sprints#1271]
On

	https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

search for

	The Hashbang Grammer

'Grammer' is a misspelling. The title should be 

	The Hashbang Grammar

**Comment by irenesmith** [comment]
Thanks, fixed!

**Comment by vouser** [comment]
I see the corrected version. Thank you.

This is a serious question, not a snide rhetorical question.

In the GitHub ecosystem is there a way to have the Document Save process automatically spellcheck the document?
