### ISSUE TITLE
Replace "extremely special" with a more descriptive modifier

### ISSUE THREAD

**Issue by vouser** [mdn/sprints#1273]
The Mozilla documentation section

	https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#The_Hashbang_Grammer

starts with

	An extremely special third comment syntax

I am not sure how to distinguish gradations of specialness. If you are wedded to 'extremely', I would use an adjective different from 'special'. Maybe 'specific'. Maybe 'restricted'. If  'extremely' is expendable, I would dump 'extremely' and keep 'special'. In the form of the phrase 'special-purpose'. Leading me to change

	An extremely special third comment syntax

to

	A special-purpose third comment syntax

**Comment by vouser** [comment]
I think I selected all the text in your template and replaced it, deleting the checkbox with the type of documentation request. Sorry.

**Comment by chrisdavidmills** [comment]
This page was updated to use "specialized" rather than "extremely special". I think this is better, so closing this now.
