### ISSUE TITLE
Help learn html, css and javascript

### ISSUE THREAD

**Issue by Ezequias-ks** [mdn/sprints#1275]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

I need to create project in HTML, CSS and JS, please help me in this.

**Comment by chrisdavidmills** [comment]
The MDN learning area has plenty of articles to help you learn HTML, CSS, and JavaScript, and more!

Head over to https://developer.mozilla.org/en-US/docs/Learn to get started.
