### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/What_went_wrong

### ISSUE THREAD

**Issue by BakaRice** [mdn/sprints#1277]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On [What went wrong](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/What_went_wrong), this is a wrong spelling.
‘查找并解决 JavsScript 代码的错误’
What is javspcrit？

**Comment by jwhitlock** [comment]
Thanks, I've fixed it in the lasted version.
