### ISSUE TITLE
Go through new Learn modules for consistency

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1278]
Once all of the modules are complete this is a task to review the whole lot as one complete piece of work for consistency.

Tasks:

- [ ] Cross link modules where appropriate
- [x] Check I haven't repeated myself between lessons
- [x] Make sure all of the tasks make sense when performed in sequence
- [x] Make sure any tasks have a solution listed

Modules to complete:

- [x] What is CSS?
- [x] Getting started with CSS
- [x] How CSS is structured
- [x] How does CSS work?
- [x] The Cascade and Inheritance
- [x] CSS Selectors
- [x] Type, class and ID selectors
- [x] Attribute Selectors
- [x] Pseudo-classes and pseudo-elements
- [x] Combinators
- [x] The Box Model
- [x] Backgrounds and Borders
- [x] Writing Mode and Logical Properties
- [x] Overflow
- [x] Values and Units
- [x] Sizing
- [x] Images, media and form elements
- [x] Inspecting CSS
- [x] Organizing your CSS

**Comment by rachelandrew** [comment]
@chrisdavidmills I can't crosslink articles while they aren't in the right place - shall I put the link in the document with a TODO so we can find them when you move them?

**Comment by chrisdavidmills** [comment]
Yes, sounds good for now.

**Comment by rachelandrew** [comment]
ok, so I have been through all of these and I think we are in good shape. The things that need doing once they are in place is to find the (fairly few) TODO bits to link to other parts of the guides, and to link to previous and next links at the top and bottom to the next guide.

**Comment by chrisdavidmills** [comment]
OK, great. I'll get to loading them onto the learning area fairly soon, after I've done next bit of work.

Just one thing I noticed — one of your building blocks articles covers backgrounds and borders. We already cover this in our Styling boxes module:

* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_boxes/Borders
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_boxes/Backgrounds

The easiest thing for me to avoid repetition would be to not include your backgrounds and borders article in the building blocks module, but I think your work is better/more modern/more accurate than mine so instead I might take your material and replace my articles with it in the other module.

Do you see any problems with doing this, beyond making sure that references take this into account, etc.?

Another, smaller point — I was thinking of calling the first module "CSS first steps", to keep it consistent with the "JavaScript first steps" module title. Does that work for you?

**Comment by rachelandrew** [comment]
Is there anything in Styling Boxes that wouldn't make more sense to be just included in these building blocks? Looking through it, I've covered most of it and "styling boxes" is pretty much a description of most of CSS.

Would it not make more sense to put the styling boxes stuff, if there is any that I didn't include into the building blocks?

CSS first steps is good.

**Comment by chrisdavidmills** [comment]
> "styling boxes" is pretty much a description of most of CSS.

@rachelandrew I suppose you're right, yes ;-)

So the only worry I have about just putting it all into "Building blocks" is that the module feels really long.

In the existing building blocks module you have 11 articles.

In the existing styling boxes module I've got the following:

1. Box model recap
2. Backgrounds
3. Borders
4. Styling tables
5. Advanced box effects
6. Assessment: Creating fancy letterheaded paper
7. Assessment: A cool-looking box

We can get rid of 1, 2, and 3 straight away - you cover those. 4-7 are all useful, but if we added them to building blocks, we'd end up with a total of 15 articles, which is double the length of most of my modules.

Do you think there's a sensible way to split it into 2, or do you not think this is a problem? I just worry that 15 articles might seem a bit intimidating to beginners.

**Comment by rachelandrew** [comment]
I wonder if the stuff in Advanced Box effects could just be rolled into background and borders.

Tables is probably its own thing.

And the assessments? We could just add those on as end of section pieces maybe. Essentially I'm wondering if I could just roll much of this into the existing pieces rather than them being standalone. It would make it all more consistent.

I could switch tack and do that this week if you like, I've only got one other ticket as part of the sprint anyway.

**Comment by chrisdavidmills** [comment]
> I could switch tack and do that this week if you like, I've only got one other ticket as part of the sprint anyway.

Sure thing, that would be really cool if you could do that!

**Comment by chrisdavidmills** [comment]
So let's say it officially then — the building blocks and styling boxes modules will be merged.

**Comment by rachelandrew** [comment]
ok - I shall move onto that!

**Comment by rachelandrew** [comment]
@chrisdavidmills the two assessments are a bit different to anything I've done in Learn. There are tasks in Learn but they aren't listed as assessments, and the answers are available on that page I made in the repo.

So we could keep these as assessements, even if they are something of an anomoly. If we take that approach maybe an enhancement to the material I've done is to create some more formal assessment type pieces. But that could happen once it is live.

Or make them more like the others with the answers in the repo?

I'm leaning towards the second approach but I don't know how useful assessments like this are to people.

**Comment by rachelandrew** [comment]
and, I was just putting tables into the list and reading through it occurs to me it is a better for the Layout Module. As there we are talking about the various values of `display`, and that would be a better intro to the fact there is default table styling. Seems a bit early to have it in here.

So I'm proposing to move tables into layout, probably after multicol, and introduce it more as a special layout method for tabular data, which is what it is.

**Comment by rachelandrew** [comment]
I had already covered filters in images, so I added the additional example there.
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Images,_media_and_form_elements#Filters

I then added background-blend-mode and mix-blend-mode to where it made sense in Backgrounds and Borders, for all of them I converted the examples so they would be the same as the others pulled from GitHub.
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Backgrounds_and_Borders

Once you let me know about the tables page and assessments I can get this finished off.

**Comment by chrisdavidmills** [comment]
> the two assessments are a bit different to anything I've done in Learn. There are tasks in Learn but they aren't listed as assessments, and the answers are available on that page I made in the repo.
>
> So we could keep these as assessements, even if they are something of an anomoly. If we take that approach maybe an enhancement to the material I've done is to create some more formal assessment type pieces. But that could happen once it is live.
>
> Or make them more like the others with the answers in the repo?
>
> I'm leaning towards the second approach but I don't know how useful assessments like this are to people.

I think one important research task that we will need to do asap is to have a discussion and ask some experts and learners  questions to find out exactly what constitutes a useful assessment.

I'd like you to include the assessments for now, as well as your inline ones, and we can then go forward and think about hw we really want to do this.

**Comment by chrisdavidmills** [comment]
> and, I was just putting tables into the list and reading through it occurs to me it is a better for the Layout Module. As there we are talking about the various values of display, and that would be a better intro to the fact there is default table styling. Seems a bit early to have it in here.
>
> So I'm proposing to move tables into layout, probably after multicol, and introduce it more as a special layout method for tabular data, which is what it is.

Yes, I agree. Let's do that.

**Comment by rachelandrew** [comment]
> I'd like you to include the assessments for now, as well as your inline ones, and we can then go forward and think about hw we really want to do this.

ok - in the Backgrounds and Borders lesson?

**Comment by chrisdavidmills** [comment]
> ok - in the Backgrounds and Borders lesson?

Just as separate articles at the end for now; we'll probably need more assessments too.

**Comment by rachelandrew** [comment]
> Yes, I agree. Let's do that.

in that case we could probably just move the page into place and I'll then make some edits so it makes sense in Layout.

**Comment by rachelandrew** [comment]
> Just as separate articles at the end for now; we'll probably need more assessments too.

So, we could just move those pages then when you rejig everything else, unless you want me to redo the code so it is like the others?

**Comment by chrisdavidmills** [comment]
> I had already covered filters in images, so I added the additional example there.
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Images,_media_and_form_elements#Filters
>
> I then added background-blend-mode and mix-blend-mode to where it made sense in Backgrounds and Borders, for all of them I converted the examples so they would be the same as the others pulled from GitHub.
> https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Backgrounds_and_Borders

Great, thanks!

**Comment by chrisdavidmills** [comment]
> in that case we could probably just move the page into place and I'll then make some edits so it makes sense in Layout.

Yup, WFM.

> So, we could just move those pages then when you rejig everything else, unless you want me to redo the code so it is like the others?

Good point. You can leave them where they are for now, but can you rejig the code examples?

**Comment by rachelandrew** [comment]
> Good point. You can leave them where they are for now, but can you rejig the code examples?

yup, I'll do that next and then I think we are probably ready to move this stuff.

**Comment by rachelandrew** [comment]
So I have been moving these, and I have some concerns about the "cool looking box" one.

Essentially it is making something that looks like a button out of an element that isn't a button. This doesn't seem a fantastic precedent to set. Also, the almost unreadable text is problematic. 

I was thinking to have the code in the page sopeople could build the example there, but then that maybe doesn't make a lot of sense if these are to be marked? They would have to download and save them.

**Comment by chrisdavidmills** [comment]
You've got good points here. Maybe we should change it so that it is more like a placard, or some other nice looking information box with more text, not just like a button? And yes, the contrast needs to be better.

Maybe just do minimal fixes for now? In the next sprint, I've got a task to do some research on assessments - what makes an effective assessment, how should we structure them , etc. I'd love to get your input on that.

**Comment by rachelandrew** [comment]
ok so they are moved into place, if we are going to change them shortly, maybe it is worth adding a note saying they are to be updated.

I'm just thinking that if we say this is all new material, someone is bound to look at those and be concerned about the same thing I am.

It would definitely be good to work out what is useful for assessments and make a nice set that cover all the material, with a marking guide. Perhaps something to add to my next contract?

**Comment by chrisdavidmills** [comment]
> ok so they are moved into place, if we are going to change them shortly, maybe it is worth adding a note saying they are to be updated.

Yes, I think so.

> It would definitely be good to work out what is useful for assessments and make a nice set that cover all the material, with a marking guide. Perhaps something to add to my next contract?

I would love that. I'll definitely add it.

**Comment by karlhorky** [comment]
Not sure if this is the right place for me to write this or if I should open a new issue for it, but I'm writing course material for complete beginners that references MDN right now and it seems like ["sequence of simple selectors"](https://www.w3.org/TR/selectors-3/#selector-syntax) is not covered on the [Simple Selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Simple_selectors) page:

> A sequence of simple selectors is a chain of simple selectors that are not separated by a combinator.

I tried searching on Google for an appropriate page on MDN, but it appears to be implicit knowledge not presented explicitly...

**Comment by karlhorky** [comment]
Ok, opened https://github.com/mdn/sprints/issues/2030 to track this.
