### ISSUE TITLE
https://developer.mozilla.org/en-US/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=developers

### ISSUE THREAD

**Issue by carlislejuggler** [mdn/sprints#1279]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

An unbalanced tree was written using document.write() causing data from the network to be reparsed.

# Details

An unbalanced tree was written using document.write() causing data from the network to be reparsed.

_Running Quantum - Windows - using an integration tool with grant-making software and also a form_ 

The form returns the following ugly red and black error on the bar -
![SAfetyPAGEGmail_462019](https://user-images.githubusercontent.com/49401853/55727448-043a8080-59e0-11e9-9e8a-03eb8b7d0856.PNG)

https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsin

**Comment by chrisdavidmills** [comment]
No form seems to exist on this page. Please list the steps to reproduce the error.
