### ISSUE TITLE
ExtendableEvent page: install and activate event links point to wrong places

### ISSUE THREAD

**Issue by tlhunter** [mdn/sprints#1281]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [ExtendableEvent](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent) page refers to two events, namely the `install` and `activate` events used in Service Workers.

* * *

The page links to this `install` event URL:
https://developer.mozilla.org/en-US/docs/Web/Events/install

Which, I believe incorrectly, redirects to:
https://developer.mozilla.org/en-US/docs/Web/API/Window/appinstalled_event

The page should probably link to the existing Service Worker `install` page:
https://developer.mozilla.org/en-US/docs/Web/API/InstallEvent

* * *

The document also links to the following `activate` event:
https://developer.mozilla.org/en-US/docs/Web/Events/activate

However, that page redirects to a different page, which contains unrelated information about the DOM:
https://developer.mozilla.org/en-US/docs/Web/API/Element/Activate_event

I believe that a new page about the `activate` event should be created. Such a page should probably live at this URL for consistency:
https://developer.mozilla.org/en-US/docs/Web/API/ActivateEvent

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @tlhunter ! I ended up fixing this by creating new pages for the activate and install events:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/activate
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/install

I also filed a PR to add compat data for both of them:
https://github.com/mdn/browser-compat-data/pull/3907
