### ISSUE TITLE
[P1] Console updates for Firefox 67 (Irene)

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1285]
- [x] Dynamic import in the Console (67)
  The user can import existing modules into the current page (using import)
  Might be good for testing

- [x] Fix link to debugger (67)
  Better handling to missing sources
  Clicking the source link in the Console panel navigates to the Debugger (if debugger knows the file) or it’s using view-source:// url

- [x] Allow to copy link location (67)
  The user has new context menu item “Copy Link Location”
  Will be improved in 68 (so, it could work for learn link too, bug reported)

- [x] console.timeLog & console.timeEnd are different now
  The user can have more timers
   timeLog & timeEnd have different output in the Console
  
- [x] Opening link should be better
  Following the same patterns/principles as Firefox (when the user clicks any link)
  
- [x] Better accessibility with added role=main on the console output container
  Tabbing goes directly to the Console output and messages (for screen-readers)

- [x] when clearing the console, we clear the error messages cache
  This relates to errors that happened before the user opens the Toolbox (they were repeatedly appearing again after reopeing the Toolbox)
  Just quality thing

- [x] Clear button added to the filter input
  There is a new icon in the Filter output (at the top of the panel) allowing the user to clear its content (only visible when there is something in the Filter output)
  We could have learn-more icon in the Filter output too (just like the Net monitor, bug reported)

# Acceptance criteria
- [x] Dynamic import in the Console (67)
- [x] Fix link to debugger (67)
- [ ] New material reviewed
- [x] All new Console features added to the Firefox 67 release notes.

**Comment by irenesmith** [comment]
For filtering text, I added an image and description to the [Filtering by text](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Filtering_by_text) section of the Console messages page.

**Comment by irenesmith** [comment]
Moved to next sprint. About 0.25 points left.

**Comment by irenesmith** [comment]
I will update after the standup with links to the changes made.

**Comment by jmswisher** [comment]
> I will update after the standup with links to the changes made.

@irenesmith Do you have those links?

**Comment by irenesmith** [comment]
Some of the information only needed to go into the release notes as they are improvements, not changes to the old behavior. These include:

- Fix link to debugger (67)
- Opening link should be better
- Better accessibility with added role=main

The following items have new or updated sections in the console documentation:

- [Copy link location](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Network) - New content shows the context menu and describes the new menu item "Copy link location".

- timeLog and timeEnd are different - The two event descriptions use the same example: [timeLog](https://developer.mozilla.org/en-US/docs/Web/API/Console/timeLog#Examples), [timeEnd](https://developer.mozilla.org/en-US/docs/Web/API/Console/timeEnd#Examples)

- [Clearing the console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Clearing_the_log)

- [Clear button added](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Filtering_by_text) to filter textbox

**Comment by jmswisher** [comment]
Thanks @irenesmith !
