### ISSUE TITLE
Debugger - Column breakpoints

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1287]
# User story
As a developer, I want to be able to select the point in a line of code were I want a breakpoint, so I have more control over where the debugger will pause.

# Acceptance criteria
- [x] Description of column breakpoints added to debugger
- [x] Images of a line with multiple possible column breakpoints added
- [x] New material reviewed
- [x] Column breakpoints added to 67 release notes

**Comment by janodvarko** [comment]
The last paragraph on the following page looks good to me.
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint

Honza
