### ISSUE TITLE
[P1] Debugger - Worker Debugging (Irene)

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1288]
# User story
As a developer, I want to be able to use the debugger, so I can more easily see all running worker sources

# Acceptance criteria
- [x] New documentation section has been added to Debugger documentation
- [x] Images showing the new Debugger UI have been added
- [ ] New information has been reviewed
- [x] Added to the 67 release notes

**Comment by irenesmith** [comment]
Looking for a good example with which to make the screenshots.

**Comment by irenesmith** [comment]
The page has been created because Harald needed a link for a Hax post. But I need to edit the content and create new screen captures for it.

**Comment by irenesmith** [comment]
Example: [dbg-workers](https://glitch.com/edit/#!/dbg-workers?path=README.md:1:0)

**Comment by irenesmith** [comment]
Moving remaining work to Koko Taylor

**Comment by jmswisher** [comment]
@irenesmith Remaining work is still 0.5?

**Comment by irenesmith** [comment]
Sorry, I forgot to change it. I’ll update it in the morning.

**Comment by irenesmith** [comment]
[Debugging Worker Threads](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Debug_worker_threads)
