### ISSUE TITLE
Hack on MDN: Performance

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1292]
* [X] Review all the docs created during the Hack on MDN
See https://docs.google.com/spreadsheets/d/18WqWoTAf3bx7fZI-qki2ihqqcT7M5Vm4egmfa79tZXM/edit#gid=0
* [X] Identify what was actually written
* [X] review for completeness
* [X] Make notes of who needs to be asked to finish
* [X] Send thank you notes to everyone, with request to finish when appropriate

Acceptance Criteria:
* [X] Emails sent

**Comment by jpmedley** [comment]
Gang,

There are articles listed I can't find on MDN. Did someone folks forget to
upload their drafts?

Joe
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by estelle** [comment]
Yes. That's why I have as a ticket to go thru all of them. I'll be emailing everyone to say thanks, but also emailing those with an article listed that is either missing or not complete, about whether they plan on finishing the project.
