### ISSUE TITLE
Page Not found Error

### ISSUE THREAD

**Issue by arckingpin** [mdn/sprints#1293]
![bug](https://user-images.githubusercontent.com/42000966/55859787-6639e800-5b90-11e9-8089-408386c3923d.png)
Page not found error for "Plotting yourself on the map" under the "See also" section in the [maps documentation page!](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

**Comment by chrisdavidmills** [comment]
Ah yes, we deleted that tutorial because it was really out of date and the examples had been lost. I've deleted the link now; thanks for reporting!
