### ISSUE TITLE
Replace Layout Debugging survey banner with a 'Build in the Browser' banner

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1299]
# User story

A couple of weeks back we [replaced the build in the browser banner with the layout debugging banner](https://bugzilla.mozilla.org/show_bug.cgi?id=1524354). It is now time to do a switcheroo and bring back the build in the browser banner.

Bugzilla reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1524354

# Acceptance criteria

- [x] Layout debugging banner is replaced by the build in the browser banner

# Tasks

1. - [x] Replace Layout debugging banner with build in the browser banner
2. - [x] Remove assets as appropriate

**Comment by violasong** [comment]
Thanks Schalk! We got 373 complete responses from the MDN link, with lots of useful comments.

**Comment by schalkneethling** [comment]
Deployed to production
