### ISSUE TITLE
Page often loads with a different font

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1300]
# User story

What did you do?
1. Visit any MDN page, no need to clear your cache, just click a link to open another part of MDN and there is like 20% chance, the page will load with some strange font.
See this thread for more info:
https://discourse.mozilla.org/t/pages-load-with-different-fonts/35071

What happened?
It seems that the bad font is:
"Palatino Linotype"
And the expected font is:
zillaslab
(I think, when I inspect the element, I see it's underlined)

What should have happened?
The fonts should be cached - so this should not happen when navigating between pages in the same session.

Is there anything else we should know?
I can see this bug very often now (every day). It was introduced only recently, maybe few months.

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1534911

# Acceptance criteria

- [ ] Font display behaviour is as intended, or an explanation for the current behaviour is documented on the relevant issue and bug

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] Investigate and diagnose font display bug
2. - [ ] Implement solution based on the above
3. - [ ] If current behaviour is by design, document behaviour citing relevant resources.

**Comment by jmswisher** [comment]
@schalkneethling @atopal This issue isn't listed in the User Story spreadsheet, and I don't think it was discussed in the final sprint planning meeting. Should it be added to the spreadsheet, or removed from the sprint milestone?

**Comment by atopal** [comment]
We had to move this out. Not enough time.
