### ISSUE TITLE
External-link icon used to be (and still should be) part of the link but is not

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1301]
# User story

From Bugzilla:

> Until fairly recently, the external-link icon was part of the link. This changed, and now it no longer is. But it ought to be.
> See the second paragraph of https://developer.mozilla.org/en-US/docs/Web/CSS/:has for example.

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1539160

# Acceptance criteria

- [ ] The icon and link text form a unit and share the same colour
- [ ] External link icon is placed after the link text

# Tasks

1. - [ ] Update CSS rules to match above acceptance criteria

**Comment by jmswisher** [comment]
@schalkneethling @atopal This issue isn't listed in the User Story spreadsheet, and I don't think it was discussed in the final sprint planning meeting. Should it be added to the spreadsheet, or removed from the sprint milestone?

**Comment by atopal** [comment]
We had to move this out. Not enough time.
