### ISSUE TITLE
How to read and parse an xml file through jquery or any server side languages?

### ISSUE THREAD

**Issue by digitalharesh** [mdn/sprints#1302]
I have an xml file wth product data, I used xmldocument class to read xml and display products in html format. It it always throw path error to read xml. Any idea or sample to read an xml file?
Thank you

**Comment by chrisdavidmills** [comment]
This isn't a general help forum, so I'm closing this. I don't know if we have anything to help with this on MDN. See if you can search for something.

**Comment by digitalharesh** [comment]
Hello Chris
Thanks for your response. I got one good resource from here [read xml file with jquery](https://www.stoodq.com/article/read-xml-file-using-jquery-3) and it fixed my problem. This saved my time lost. Thank you so much for your followup.
