### ISSUE TITLE
Update BCD data for logical properties to add Safari 12.1 support

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1303]
# User story
As a web developer I want to understand the support for logical properties in Safari.

# Acceptance criteria

BCD Data for logical properties updated.

See: https://github.com/mdn/browser-compat-data/issues/3788

**Comment by rachelandrew** [comment]
PR: https://github.com/mdn/browser-compat-data/pull/3930

**Comment by rachelandrew** [comment]
PR approved.

**Comment by rachelandrew** [comment]
The data is now showing on the pages so I think this is all done now.

**Comment by connorshea** [comment]
Yup, I think this can be closed :)
