### ISSUE TITLE
Document print media emulation (Fx68)

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1305]
# User story
As a developer, I want to be able to view my page as it would look using a print media query, so I can fine-tune the CSS in my media query.

This feature adds a button to the Rules pane of the Inspector. When clicked, it will switch to the CSS associated with any print media queries.

## Related Bugzilla issue
[#1534984](https://bugzilla.mozilla.org/show_bug.cgi?id=1534984)

# Acceptance criteria
- [x] Documentation for print media emulation has been added to in Rules View documentation
- [x] Appropriate images have been added to the page
- [ ] New material has been reviewed

## Reviewer
Micah Tigley

**Comment by chrisdavidmills** [comment]
Is this something you are intendig to do next sprint? If so, it needs acceptance criteria. If not, it should be recorded in the content roadmap first.

**Comment by irenesmith** [comment]
@chrisdavidmills This is not for the next sprint, it is for the one after. I was just told about it yesterday and wanted to create the issue before I forget.

**Comment by chrisdavidmills** [comment]
OK. But we did discuss you recording this stuff in the roadmap in our meeting yesterday. I know it's a pain, but I don't really have visiblity of what is coming up if it is  all put straight into GitHub.

**Comment by irenesmith** [comment]
Just added 7 new cards to your roadmap. After the Network Monitor updates meeting today, I will probably add at least one more.

**Comment by chrisdavidmills** [comment]
That's great - thanks!

**Comment by chrisdavidmills** [comment]
Sorry, this is now being tracked in https://github.com/mdn/sprints/issues/1572
