### ISSUE TITLE
Develop a detailed plan for fast rendering of documents

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1306]
User story

As a staff developer, I want to be able to render MDN documents quickly so we can re-render large chunks (if not all) of the documents on a regular schedule or on demand. For example, it's common to occasionally re-render all of documents that use the `compat` macro, or, less frequently, all of the documents. I'd like to do some research and testing in order to formulate a plan for accomplishing this.

Acceptance criteria

A detailed plan, documented within this issue, for doing fast document rendering has been reviewed and shared.

**Comment by tobinmori** [comment]
low priority but still necessary to improve perf.

**Comment by tobinmori** [comment]
closin' it!
