### ISSUE TITLE
Update InterfaceOverview and GroupData for new event organisation

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1315]
This is a work item for #685, and was originally discussed in https://github.com/mdn/sprints/issues/906.

This item also depends on https://github.com/mdn/sprints/issues/1314 and https://github.com/mdn/sprints/issues/1313.

Currently, events are listed in the [GroupData](https://github.com/mdn/kumascript/blob/master/macros/GroupData.json) JSON macro. and are referenced from there by other macros for building sidebars and other content.

After the event ref work, events will live directly under APIs, and should instead be treated more like properties and methods of those APIs.

In this user story we will:

* update the [InterfaceOverview](https://github.com/mdn/kumascript/blob/master/macros/InterfaceOverview.ejs) macro to remove its dependency on GroupData
* update GroupData itself to remove the event listings

AC are that both those changes are committed to KumaScript, deployed, and verified.

**Comment by ExE-Boss** [comment]
I’m&nbsp;removing the&nbsp;`{{InterfaceOverview}}` GroupData dependency in&nbps;https://github.com/mdn/kumascript/pull/1073.

**Comment by wbamberg** [comment]
Thanks @ExE-Boss . But removing the GroupData dependency from InterfaceOverview is a 6-line change, and https://github.com/mdn/kumascript/pull/1073 adds 6000 lines. I'd really much rather we do this in small pieces.

**Comment by ExE-Boss** [comment]
That’s because https://github.com/mdn/kumascript/pull/1073, depends on https://github.com/mdn/kumascript/pull/1093, which adds the necessary utility functions to write the tests for `{{InterfaceOverview}}`.

In fact, most of those lines are from the test fixtures.

**Comment by wbamberg** [comment]
When I wrote this I had expected to be removing events from GroupData: now I understand it better I won't be doing that.

See https://github.com/mdn/sprints/issues/1314#issuecomment-487251021 for a description of what I am intending to do to GroupData, and https://github.com/mdn/kumascript/pull/1136 for the PR that does it.

Since `group.events` will still exist, there's now no need to update `InterfaceOverview` as part of this work.

**Comment by ExE-Boss** [comment]
Actually, `{{InterfaceOverview}}` will still need to&nbsp;be&nbsp;updated to&nbsp;properly handle event subpages.

**Comment by wbamberg** [comment]
The work I am doing here is the minimum needed to stop `InterfaceOverview` from breaking as a result of the event refactoring work. For various reasons, I'm not adding extra features to `InterfaceOverview`.

As far as I can see, `InterfaceOverview` would not be broken by the event refactoring so the "minimum needed" is nothing. In particular I don't think I need to update it to "properly handle event subpages" in order for it not to be broken by the event refactoring.

If I'm wrong I'd love to know just how the event refactoring would break it and which changes are needed to fix that (although given that this macro has `*** EXPERIMENTAL - DO NOT USE! ***` across the top I'm reluctant to spend much time on it).

**Comment by wbamberg** [comment]
This is merged and deployed, see https://github.com/mdn/sprints/issues/1314#issuecomment-491064000.
