### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText

### ISSUE THREAD

**Issue by krisztianb** [mdn/sprints#1321]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The description of the Y parameter states:

> The y-axis coordinate of the point at which to begin drawing the text, in pixels.

This is not clear enough as the Y parameter defines the position of the baseline on which the text is drawn. So a better description would be imho:

> The y-axis coordinate of the baseline on which to begin drawing the text, in pixels.

**Comment by krisztianb** [comment]
Only a few words to be replaced and it takes so long for it to happen. I guess you have too few people working on the site, right?

**Comment by chrisdavidmills** [comment]
Fixed, after nearly 2 years ;-)

https://github.com/mdn/content/commit/7c4defad3e8e91a14be178121251ccc408eda951
