### ISSUE TITLE
[P1] revert keyword docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1325]
See https://trello.com/c/WQ9fnb6V/184-revert-keyword-fx-67 for content roadmap Trello  card

# Acceptance criteria

1. - [x] `revert` keyword documented and related tasks done as appropriate.

**Comment by a2sheppy** [comment]
The docs were there already, and BCD up to date. I made enhancements as covered in the bug, and added a glossary entry for a new term.

We need to figure out what we're going to do about getting `revert` listed on all the pages it needs to be included on in the reference.
