### ISSUE TITLE
[P2] JS dynamic module import() docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1327]
See https://trello.com/c/tJhhikiN/122-js-modules-fx-67 for content roadmap Trello card.

# Acceptance criteria

1. - [x] BCD for dynamic module `import()` updated as appropriate
2. - [x] Make sure [import page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is cleaned up as appropriate.
3. - [x] Make sure [export page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) is cleaned up as appropriate.
4. - [x] Update [script type="module"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) to to show better usage.
5. - [x] Write proper tutorial covering JS modules.

**Comment by a2sheppy** [comment]
@chrisdavidmills - I agree that we should have a tutorial around importing code, using libraries and modules, stuff like that.

**Comment by a2sheppy** [comment]
Though a guide to importing code and using libraries and the like should be a separate work item, instead of glommming it onto the updates for Firefox 67 for `import()`.

**Comment by chrisdavidmills** [comment]
Heh, I've nearly finished writing such a guide ;-)

**Comment by chrisdavidmills** [comment]
OK, so I've cleaned up the existing pages on `export`, `import`, and `<script>` (`type="module"`), including testing some rather strange assertions they contained that turned out not to be true.

I've added my new shiny JS modules guide to the JS guides:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

I think I've added references to it in all the places that matter.

I've also submitted a PR to add it ot the JsSidebar macro:
https://github.com/mdn/kumascript/pull/1151

**Comment by chrisdavidmills** [comment]
@Elchi3, do you fancy reviewing this work, when you can find a spare moment?
