### ISSUE TITLE
[P2] MediaStream API docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1334]
See https://trello.com/c/2ALfaJHp/100-mediastream-api-fx-67 for content roadmap trello card.

# Acceptance criteria

1. - [ ] `MediaDeviceInfo.groupId` is documented as appropriate.

**Comment by a2sheppy** [comment]
### groupId
* Filed [PR 4093](https://github.com/mdn/browser-compat-data/pull/4093) to update BCD
* Added an example to the article for [`MediaDeviceInfo.groupId`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/groupId); enhanced the text to be a little more specific, and provided a solid explanation of things in the example as well
