### ISSUE TITLE
[P1] feature-policy docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1335]
See https://trello.com/c/1NkwWH1e/88-feature-policy-fx-67 for content roadmap trello card.

# Acceptance criteria

1. - [x] `FeaturePolicy: display-capture` documented as appropriate.
2. - [x] BCD updated, if feature policy is enabled in Fx

**Comment by a2sheppy** [comment]
### display-capture updates
* Added reference page for [Feature-Policy: display-capture](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/display-capture)
* Submitted [BCD PR 4109](https://github.com/mdn/browser-compat-data/pull/4109) to add `display-capture` to feature policy
* Improvements and example added to [getDisplayMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) page
* Improvements to [Using the Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture)
* Expanded information provided in the main [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API
