### ISSUE TITLE
[P2] Cross-Origin related docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1336]
See https://trello.com/c/ZQjg0cm4/175-cross-origin-related-bugs-fx-67 for content roadmap Trello card.

# Acceptance criteria

1. - [ ] `Cross-Origin-Opener-Policy` documented as appropriate.

**Comment by a2sheppy** [comment]
I always feel a little dodgy when asked to document something that hasn't even been merged into the spec yet. Writing docs for something that's been implemented based on a spec update that's still open on GitHub makes me nervous. :)

**Comment by chrisdavidmills** [comment]
@a2sheppy It looks like this is supported in multiple browsers, so ready for documenting, in spite of the spec confusion.

**Comment by Elchi3** [comment]
I've removed https://bugzilla.mozilla.org/show_bug.cgi?id=1525036 from this task as it is not shipping in 67.

**Comment by Elchi3** [comment]
The second header here, COOP, is also not shipping in 67 and is implemented nowhere else either.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1521808#c20

I think thus this 67 ticket is invalid. I'm closing this and updated the trello card to do this work later when things actually ship and specs have stabilized.
