### ISSUE TITLE
[P1] WebExtension private browsing (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1338]
See https://trello.com/c/2gu3gHO4/169-webext-and-private-browsing-fx-67 for bugs list

# Acceptance criteria

Private browsing for WebExts documented as appropriate.

1. - [x] incognito manifest key documented and added to the release notes
2. - [x] behavior of an extension that is not allowed in private windows/tabs documented and added to the release notes
3. - [x] document that proxy.settings.set requires private window access and add to release notes.

**Comment by irenesmith** [comment]
The [incognito manifest key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) for the manifest has been documented.

Added the following note to the [incognito manifest key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) page:

Note: Firefox 67 also adds a new setting in about:config, extensions.allowPrivateBrowsingByDefault, which defaults to false. This means that the default for a newly installed extension would be "not_allowed" meaning that the extension would not be able to run in a private window or tab. See this support article: Extensions in Private Browsing for details from the user's perspective.

Added incognito to the 67 release notes.

**Comment by irenesmith** [comment]
Added this note:

Note: The ability to change proxy settings when running in a private window or tab requires private window access.

to [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) page as there is not page for proxy.settings.set()

Also added to release notes.

**Comment by chrisdavidmills** [comment]
Everything else looks good; you just need to add the note to release notes. Thanks Irene.

**Comment by irenesmith** [comment]
Done.

**Comment by chrisdavidmills** [comment]
Where did you add these? I can't see any additions at https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#Changes_for_add-on_developers.

**Comment by irenesmith** [comment]
It really helps when you're adding things to the release notes to save it. Sorry! If you look now, you will see the changes.
