### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Doc_status

### ISSUE THREAD

**Issue by jnegron357** [mdn/sprints#1340]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update
- [x] Feature request

# Details

Can you give us the option of choosing which version of ECMAScript to view your examples in? You're currently using ES6 but older browsers aren't compatible and polyfills add too much overhead. Giving us the option to choose an older version of ECMAScript would be very convenient.

**Comment by chrisdavidmills** [comment]
Closing this here, as it's not really the right place for it. I've suggested it to the MDN devs as a potential future enhancement.
