### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript

### ISSUE THREAD

**Issue by Ursi** [mdn/sprints#1341]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

As far as I can tell there's nothing on the site that talks about how to name regex groups. This whole time I've been thinking it was impossible till I saw it referenced on the `String.prototype.match()` page.

**Comment by chrisdavidmills** [comment]
@jpmedley was working on some updates to our regex guide pages; perhaps he could cover this?

**Comment by jpmedley** [comment]
Got it on my list. Look for it later today or tomorrow. 

(I don't suppose you ever assign sprint tickets to non-Mozzillians.)

**Comment by jpmedley** [comment]
Link here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match
Explanation here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

**Comment by chrisdavidmills** [comment]
Nice one; thanks Joe!
