### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions/Adding_items_to_the_Folder_Pane

### ISSUE THREAD

**Issue by seekM** [mdn/sprints#1342]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[This section](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions/Adding_items_to_the_Folder_Pane#Putting_it_all_together) says 
> Right now, clicking on these additional items has no effect. However, the complete [example file](https://developer.mozilla.org/en-US/Extensions/Thunderbird/Adding_items_to_the_Folder_Pane/Code) includes code to display the number selected in Thunderbird's main viewing pane, when such a number is selected in the Folder Pane.

The `example file` link does not work.

**Comment by seekM** [comment]
Why was this closed? The issue still exists.

**Comment by Elchi3** [comment]
Thanks for filing the issue. Please note that the MDN team doesn't update Thunderbird docs. Please file it with the Thunderbird issue tracker or feel free to edit the wiki page.
