### ISSUE TITLE
Documentation link 404

### ISSUE THREAD

**Issue by zxhycxq** [mdn/sprints#1344]
# Request type

- [ ] Correction or update

# Details
this page was 404 , [https://developer.mozilla.org/zh-CN/docs/Web/API/History/state](https://developer.mozilla.org/zh-CN/docs/Web/API/History/state)

**Comment by chrisdavidmills** [comment]
This is probably just a page that has not been created yet. Where did you find this link?

**Comment by zxhycxq** [comment]
![image](https://user-images.githubusercontent.com/11674203/56182315-27021000-6044-11e9-9c09-6dcd346c24f8.png)
