### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by solaomosola** [mdn/sprints#1345]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/new?slug=CSSMathMax&parent=66089 does not exist.

**Comment by chrisdavidmills** [comment]
This will probably be just a page that has not been written yet. Did you find a link to it somewhere?
