### ISSUE TITLE
Documentation Links for new about:debugging

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1346]
We currently have the following links in the UI:

1. [Troubleshooting](https://developer.mozilla.org/docs/Tools/WebIDE/Troubleshooting)
        **where:** in the Runtime pages, in the backward compatibility warnings displayed when connecting to a too old or too recent browser as "Troubleshooting"
        **comments:**
        We don't currently have such links in WebIDE, so the current page is really irrelevant.
        We should have a section in our documentation that talks about the backward compatibility policy (and exceptions) in DevTools.

2. [Enabling add-on debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Enabling_add-on_debugging)
        **where:** in This Nightly / This Firefox, next to the "Enable extension debugging" as "Learn more"
        **comments:**
        The url is still relevant, as it explains the technical details about what the checkbox does, even though it is lost in a huge page that documents the old about:debugging UI.

3. [Service workers not compatible](https://developer.mozilla.org/en-US/docs/Tools/about%3Adebugging#Service_workers_not_compatible)
        **where:** in the Runtime pages, if the configuration of the browser is not compatible with Service Workers
        **comments:**
        Same as for addon debugging, the explanations found at the URL are still relevant, but the screenshot is outdated.

4. [Setting up the Android device](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE#Setting_up_the_Android_device)
        **where:** in the Setup page, when "USB Debugging" is enabled, in the USB section as "Learn how" links next to each step.
        **comments:**
        This section of the content is relevant for Firefox for Android, but all the rest of the page is only about WebIDE. This is probably the most important resource to create: a new landing page that explains how to handle USB connection with a device running Firefox for Android.

5. [WebExtensions_and_the_Add-on_ID](https://developer.mozilla.org/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID)
        **where:** in This Nightly / This Firefox, in the "Temporary Extension" category when a Temporary Extension is loaded
        **comments:** this page barely mentions about:debugging, and can mostly be reused as is
    https://developer.mozilla.org/en-US/docs/Tools/about:debugging
        where: "Debugging Support" in the bottom left of the application, always displayed
        comments: The whole page talks about the old about:debugging UI and is mostly outdated.

From the quick review above, it seems like we need two new resources:

- [x] one documentation page to document USB debugging (Debugging Firefox for Android over USB?)
- [x] one documentation page for the updated about:debugging UI (TBD)

with the necessary anchors to get the detailed info about serviceworkers, addondebugging, backward compatibility policy etc...

The main priority between the two is the updated page for USB debugging. The current page is called [Debugging_Firefox_for_Android_with_WebIDE](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE) and since we will both have WebIDE and the new remote debugging side by side in Fx68, we will probably need to keep the two pages around for some time.

**Comment by irenesmith** [comment]
Created the following placeholders:

[Debugging over a network](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_over_a_network)
[Debugging over USB](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_over_USB)

I think we can simply edit the existing about:debugging page but let me know if you feel differently.

 Please let me know if you need any other new pages.

**Comment by irenesmith** [comment]
We have create a copy of the [old about:debugging page](https://developer.mozilla.org/en-US/docs/Tools/about:debugging/about:debugging_before_Firefox_68) and made it a child of the current page. The top of the [current page](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) has a link to the old page with the comment that it is for Firefox before Firefox 68.

**Comment by jmswisher** [comment]
Assigning this to myself, so I can familiarize with these pages.
