### ISSUE TITLE
Multiple broken links for Remote Debugging documentation

### ISSUE THREAD

**Issue by benjibee** [mdn/sprints#1350]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Follow either link for remote debugging from Firefox OS (via USB or WiFi) results in a 404 error. These two links can be found on the [Remote Debugging page](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging) and the two broken links have the following URLs:

- https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_USB
- https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_Wifi

Additionally, there's no mention of debugging for Firefox on iOS, or it's just not clear enough to know what options are availible. This page needs some love!

**Comment by rctgamer3** [comment]
These pages are still broken. Even if Firefox OS itself is dead, pages describing how to remote debug the browser on Firefox OS are still very useful when working on responsive design, and having an actual device to test on is super useful.

**Comment by SphinxKnight** [comment]
I've taken the liberty of restoring the content under the Archives:
* https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Debugging/Debugging_Firefox_OS_over_Wifi
* https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Debugging/Debugging_Firefox_OS_over_USB

@chrisdavidmills / @irenesmith if there is a better rationale to keep them deleted, please indicate it here.

**Comment by irenesmith** [comment]
These pages will be replaced by newer content.

**Comment by irenesmith** [comment]
This appears to be a resolved issue but that's up to you.

**Comment by SphinxKnight** [comment]
@irenesmith thanks for the heads up, sorry. I cannot close issues on this repo. Could you do it please? :s 

Thanks :)
