### ISSUE TITLE
Rename `<timing-function>` to `<easing-function>`

### ISSUE THREAD

**Issue by SebastianZ** [mdn/sprints#1351]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

The `<timing-function>` value in the CSS Easing Functions spec. was renamed to `<easing-function>` to reflect the fact that the easing functions are used by more than just timing-related properties now. For example, they are also used within the color gradient functions.

This update requires several changes on MDN side:

- [x] Rename/move the `<timing-function>` page to `<easing-function>`
- [x] Generalize the description of the function so that it talks about easing instead of timing
- [x] Rename the function in BCD
- [x] Update the pages referring to `<timing-function>`/`<single-transition-timing-function>` to `<easing-function>`
  - [x] [animation](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)
  - [x] [animation-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function)
  - [x] [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition)
  - [x] [transition-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function)

Note: The specifications referring to the CSS Easing Functions spec. are not updated yet because the Working Draft did not get updated yet.

Sebastian

**Comment by rachelandrew** [comment]
@chrisdavidmills The first three of these had already been done, so I checked the redirection, page content and BCD.

The listed pages which use the function hadn't been updated so I have done those.

**Comment by chrisdavidmills** [comment]
@rachelandrew awesome, thanks! I think this looks done now, so closing, but please let me know if I've missed anything.

**Comment by SebastianZ** [comment]
The description at the `<easing-function>` page was still referring to animations and timings. I've updated the text now but the images still relate to timing.

Similarily, the animation and transition pages still refer to `<timing-function>`. I'll provide a patch to change that.

It looks like I don't have the rights (anymore) to reopen an issue, though as long as those points above are not done, it should be opened again.

Sebastian

**Comment by rachelandrew** [comment]
ah of course, it's in the formal syntax. I'll need to open a PR for that. I'd searched but I was editing the page at the time so of course that didn't show up.

I'll reopen and fix that next week.

**Comment by SebastianZ** [comment]
Almost a month too late writing this but thank you for fixing this, @rachelandrew! 😄 

Sebastian
