### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Django/Introduction

### ISSUE THREAD

**Issue by criedge** [mdn/sprints#1352]
# Request type
- [ ] Correction or update

# Details
https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Django/Introduction#Django%E6%98%AF%E4%BB%80%E4%B9%88

发现一处同音字错误。

在"Django是什么"这一标题下的段落"安全性"中，第二段内的一句话

> **即时**存储的哈希值受到威胁，攻击者也难以解决原始密码。（但其实有彩虹表-译者观点）

中，**即时**或应改为**即使**。

谢谢。

**Comment by chrisdavidmills** [comment]
I'm really sorry, but I can't read Chinese. Looking at this in Google translate, it says that there is a wrong word that needs to be changed.

What is the wrong word?

And what is the word I need to change it to?

Alternatively, would you be able to sign into MDN and fix it yourself?
