### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by twhitt14** [mdn/sprints#1354]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The first example code block on the page below is missing a closing `)` to close the event listener parameters.

https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView/popstate_event

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
