### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices$compare?locale=en-US&to=1542729&from=1499091

### ISSUE THREAD

**Issue by ESA-Security-Group** [mdn/sprints#1363]
![4EF63273-0947-47A1-A6BA-0B25BA3C6A83](https://user-images.githubusercontent.com/47658682/56435752-e15e7500-62d9-11e9-9d25-5f5ec648792e.png)
![6A7E519D-264F-4968-A365-6AB9BEFCA471](https://user-images.githubusercontent.com/47658682/56435753-e15e7500-62d9-11e9-8c3a-adabe459f7e0.png)
![4EB0F446-051A-4CD1-9C12-5CA7E0D64B59](https://user-images.githubusercontent.com/47658682/56435755-e1f70b80-62d9-11e9-8f4a-85b4cc9d9deb.png)
![D7EF0214-952C-43C9-A8B0-07B49E2EC55B](https://user-images.githubusercontent.com/47658682/56435758-e1f70b80-62d9-11e9-8ba2-a5446ce9d8c4.png)
![8D026437-F267-4DF8-AC07-32A0F677B6E7](https://user-images.githubusercontent.com/47658682/56435759-e1f70b80-62d9-11e9-855f-38b447b9147f.png)

What is all this about? Can someone please give a good explanation??

Thank you in advance!! ⚖️➰⚡️

// Ambjoern 

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

**Comment by ESA-Security-Group** [comment]
#1000 
Not a mistake as it was before so it’s not a “close” please....

**Comment by chrisdavidmills** [comment]
@ESA-Security-Group I am not really sure what you are commenting on here — the layout of the history is not very good on mobile; is that what you are referring to?

The actual change highlighted in the diff looks OK to me?
