### ISSUE TITLE
Warn of deprecated WebExtension proxy APIs

### ISSUE THREAD

**Issue by mconca** [mdn/sprints#1364]
# Request type
- [ ] New documentation
- [X] Correction or update

# Details
The proxy.register() and proxy.unregister() APIs are being deprecated in Firefox 68 and will be removed in Firefox 71.  MDN should immediately mark those API as deprecated.  The following pages need updating:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/register
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/unregister

The progress of this issue for Firefox can be followed on bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1545811

# Acceptance criteria
- [x] Deprecation notice added to register and unregister
- [x] Main proxy page updated mark only the deprecated API as deprecated
- [x] proxy.onError page updated as described in the comment below
- [x] Changes reviewed
- [x] Two related issues created for Firefox 68 and Firefox 71 to mention the deprecated API (Fx 68) and the fact that the API has been removed (Fx 71)

**Comment by mconca** [comment]
In addition to marking these API as deprecated, the content near the top of the main [proxy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy) page will need to be cleaned up so as to only refer to the proxy.onRequest API.

**Comment by mconca** [comment]
The content at the top of the proxy.onError page as well as the example at the bottom of the page also refer to the deprecated API (PAC script).   We need to explain that the error can be triggered by throwing or returning an invalid value in the proxy.onRequest event handler.

**Comment by irenesmith** [comment]
@mconca I have updated the pages appropriately. I removed the example from the proxy.onError page since it only refers to the deprecated methods and I also added the comment that the error can be triggered by throwing or returning an invalid value in the proxy.onRequest event handler.

**Comment by irenesmith** [comment]
I have created an [Epic](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/1510) which includes this issue and the two related issues mentioned in the acceptance criteria for release notes for Firefox 68 and Firefox 71.

**Comment by mconca** [comment]
Looks good.
