### ISSUE TITLE
MDN Revisions are not being applied

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/sprints#1366]
See https://discourse.mozilla.org/t/my-revisions-are-not-being-applied/38443

This has been confirmed by @wbamberg.

The current workaround is to revert to the new revision.

The regression occurred sometime between the [mozilla/kuma@`a52efbe...4b10c3b`](https://github.com/mozilla/kuma/compare/a52efbe0510e36ab5dd06806b6d623ad82644924...4b10c3bb1737e2fbf8171d695477ada7abc3466a) commits.

---

/cc @escattone, @jmswisher, @wbamberg

**Comment by jpmedley** [comment]
Here's another example. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control$history

**Comment by escattone** [comment]
Just noticed this, thanks for letting us know @ExE-Boss and @jpmedley. I'll look into this ASAP.

**Comment by a2sheppy** [comment]
Yeah, I see this too. Not great. :)

**Comment by escattone** [comment]
This should be fixed now, but please let me know if you’re still seeing problems. The PR https://github.com/mozilla/kuma/pull/5348 was the culprit (although I still don’t know the detailed failure mechanism as I couldn’t reproduce it locally or on stage). I deployed https://github.com/mozilla/kuma/pull/5366 to fix the issue.

Again, I’m sorry for the inconvenience this has caused. Thanks for your patience, and special thanks to ExE-Boss for creating this issue and for:

> The regression occurred sometime between the [mozilla/kuma@`a52efbe...4b10c3b`](https://github.com/mozilla/kuma/compare/a52efbe0510e36ab5dd06806b6d623ad82644924...4b10c3bb1737e2fbf8171d695477ada7abc3466a) commits.

which saved me some time when digging into this.

**Comment by escattone** [comment]
I've confirmed with @a2sheppy that this is fixed. I'm going to close this, but please re-open if needed.

**Comment by wbamberg** [comment]
Thanks for the quick fix @escattone !
