### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID

### ISSUE THREAD

**Issue by lindseyspratt** [mdn/sprints#1367]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
This is a comment on the documentation for NavigatorID: I think this could be documented as a 'mixin' and Navigator can be documented as 'inheriting' from the NavigatorID mixin. This seems like it would make it consistent with the structure of the organization of the HTMLElement and WindowEventHandlers documentation, where WindowEventHandlers is documented as a 'mixin'.

**Comment by chrisdavidmills** [comment]
You are right that this would be good for consistency, however we are currently considering getting rid of documenting mixins separately, and probably doing something like having the items defined on mixins appear in all places that implement those mixins.

Reason being that mixins are an internal spec device, and there is evidence that talking about mixins on MDN docs pages tends to confuse readers.

**Comment by a2sheppy** [comment]
I think the main sticking point remains that it would be nice to have a way to avoid documenting things repeatedly when the mixin is used in multiple classes.

**Comment by lindseyspratt** [comment]
The mixin nicely mirrors the documentation in the standard where it uses the [NoInterfaceObject] interface definitions, such GlobalEventHandlers:
https://www.w3.org/TR/2017/REC-html51-20171003/webappapis.html#globaleventhandlers-globaleventhandlers <https://www.w3.org/TR/2017/REC-html51-20171003/webappapis.html#globaleventhandlers-globaleventhandlers>
