### ISSUE TITLE
Houdini: Miscellaneous APIs

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1376]
<a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/computedStyleMap">Web/API/Element/computedStyleMap</a> 
Element.computedStyleMap() method returns a StylePropertyMapReadOnly
* [ ] Add example
* [ ] Add method to HTMLElement 
* [ ] Add See Also (tutorial and houdini APIs)
.

<a href="https://developer.mozilla.org/en-US/docs/Web/API/CSSImageValue">Web/API/CSSImageValue</a> 
CSS Typed Object Model API values
* [ ] Add example
* [ ] Add See Also (tutorial and houdini APIs)

**Comment by jpmedley** [comment]
I know, they're kind of anemic so far.
