### ISSUE TITLE
Add @font-face property: font-stretch

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/sprints#1378]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details

Something that I noticed while updating the BCD for the `font-stretch` CSS property is that [Chrome requires `font-stretch`](https://bugs.chromium.org/p/chromium/issues/detail?id=331119#c20) defined as "{min-percent} {max-percent}" on the `@font-face` declaration.  There seems to be no documentation on this feature.

**Comment by rachelandrew** [comment]
@chrisdavidmills @vinyldarkscratch in the time since this was raised the page seems to have been created https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-stretch

**Comment by chrisdavidmills** [comment]
Cool, thanks for bringing it up @rachelandrew ! Can you give it a quick review, and then maybe we can look to close it?

**Comment by rachelandrew** [comment]
@chrisdavidmills looks good to me, it's got the additional info about percentages from the L4 spec.

**Comment by chrisdavidmills** [comment]
Great, thanks. Closing.
