### ISSUE TITLE
Add Save-Data HTTP Header

### ISSUE THREAD

**Issue by boramalper** [mdn/sprints#1379]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

There is currently no documentation for HTTP header `Save-Data`, described below:

- https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-7
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/

I believe it can be a serious standards-compliant alternative to current proprietary solutions such as Google's AMP, and documenting it would be the first step in encouraging the community to adopt it.

I'd be happy to do my best to supply the content too, if needed.

Thanks!

**Comment by chrisdavidmills** [comment]
Hi @boramalper ! We'd love some help with writing this page; you'd basically just need to copy the existing structure from another header page and replicate it for this one.

How would you like to play this? Shall I create the blank page and then you can add the content?

**Comment by boramalper** [comment]
> How would you like to play this? Shall I create the blank page and then you can add the content?

That'd work for me.

**Comment by jmswisher** [comment]
Thanks @boramalper  for taking this on!

I'm assigning this to @chrisdavidmills for bookkeeping purposes; he'll keep track of it and close it when it's done.

**Comment by chrisdavidmills** [comment]
@boramalper OK, your page is all ready to add content to:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data

We'll also need an appropriate entry adding to the parent page: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

Let me know if you've got any questions. I'd also be happy to review the page for you.

**Comment by boramalper** [comment]
Done!

Just to note, I've copy-pasted from [draft-grigorik-http-client-hints-03](https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-7); I think the license allows that but IANAL. =)

**Comment by chrisdavidmills** [comment]
Cool, nince work @boramalper !

I have gone through it, given it a copy edit and made sure the structure is consistent with other header pages. It is a bit different now anyway ;-)

A couple of comments:

* The spec suggests that the value used is 0/1 rather than Off/On, so I've changed those values. Hope that's OK.
* I added an Examples section: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data#Examples. I don't know if you want to add in something a bit more interesting and useful to show how it might be used?

**Comment by boramalper** [comment]
Thanks! =)

> The spec suggests that the value used is 0/1 rather than Off/On, so I've changed those values. Hope that's OK.

Does it? I think it should be `on`, see https://wicg.github.io/netinfo/#save-data-request-header-field.

> The SaveData [CLIENT-HINTS] request header field consists of one or more tokens that indicate user agent's preference for reduced data usage.
>
> ```
> Save-Data = sd-token \*( OWS ";" OWS [sd-token] )
> sd-token = token
> ```
>
> This specification defines the "on" sd-token value, [...]

----

> I added an Examples section: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data#Examples. I don't know if you want to add in something a bit more interesting and useful to show how it might be used?

Hmm, I might reuse some examples from CSS tricks then (mentioned in further reading). =)

**Comment by chrisdavidmills** [comment]
> Does it? I think it should be on, see https://wicg.github.io/netinfo/#save-data-request-header-field.

Oh, ok. It says 1 at https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-7, but I'm happy to go with the official draft report. I've changed them to "Off/On".

Providing an example borrowed from CSS Tricks is probably OK, yes.

**Comment by boramalper** [comment]
Done! =)

Feel free to close the issue if you think it's done.

**Comment by chrisdavidmills** [comment]
Yup, we can close this. Thanks so much for you help!
