### ISSUE TITLE
History State Link 404

### ISSUE THREAD

**Issue by typeoh** [mdn/sprints#1380]
# Request type
- [x] Correction or update

# Details
In https://developer.mozilla.org/en-US/docs/Web/API/History#Browser_compatibility section, selecting the `state` link routes to https://developer.mozilla.org/en-US/docs/Web/API/History/state with a 404 response.

**Comment by jmswisher** [comment]
That property hasn't been documented.

**Comment by irenesmith** [comment]
It has now. [history.state](https://wiki.developer.mozilla.org/en-US/docs/Web/API/History/state)
