### ISSUE TITLE
SVGRect page seems to describe about SVGRectElement but SVGRect is not SVGRectElement.

### ISSUE THREAD

**Issue by luncheon** [mdn/sprints#1381]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`SVGRect` page seems to describe about `SVGRectElement` but `SVGRect` is not `SVGRectElement`.

    This interface also inherits properties from its parent, SVGGeometryElement.

https://developer.mozilla.org/en-US/docs/Web/API/SVGRect

**Comment by jmswisher** [comment]
This appears to be fixed (see https://wiki.developer.mozilla.org/en-US/docs/Web/API/SVGRect$compare?locale=en-US&to=1561874&from=1526996)
