### ISSUE TITLE
HOUDINI: Intro: Tutorial home page (page 1)

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1383]
URL:  https://developer.mozilla.org/en-US/docs/Web/Houdini/learn (already created)

References
CSS & HTML - These reference pages cover Houdini features for web developers.
APIs - These reference pages cover the APIs that fall under the Houdini umbrella

Guide sections (Placeholders present, content and links need to be added):
1) intro
2) brief history
3) overview of the features:
 * CSS Parser API (page 2)
 * CSS Properties and Values API  (page 3)
 * CSS Typed OM  (page 4)
 * CSS Layout API  (page 5)
 * CSS Paint API  (page 6)
 * Worklets  (page 7)
 * Composite Scrolling and Animation  (page 8)
The above should include a brief paragraph of the APIs, linking to 'learning' for those APIs, which are each a page later in this section.

**Comment by chrisdavidmills** [comment]
Just another quick check — you're not plannig on putting the Learning stuff in the actual learning area, are you?

**Comment by estelle** [comment]
This is the outline for the 'tutorial'. Where is the best place to put it?

**Comment by chrisdavidmills** [comment]
I would put the tutorials as subpages of the main Houdini landing page. 

Where that goes of course is a good question. Houdini is a bunch of APIs, but it is also CSS related; kind of in it's own league really. I'd probably lean towards putting it under Web/API/ over Web/CSS/. Or we could even argue for putting it difrectly under Web/Houdini perhaps?

**Comment by estelle** [comment]
I was thinking web/css/houdini, but that's not really it, 
so web/houdini seemed more appropriate, but that would be like elevating it to web/performance or web/accessibility, which is a bit higher than it needs to be, but i think ok.
It bothered me to elevate it to web/css and web/html, but realizing we have web/media, web/http, web/security (we need to add privacy and i18n) etc, makes web/houdini seem ok

**Comment by rachelandrew** [comment]
Jumping in thinking that the tutorials seem like the "Guides" we have done for bits of CSS (such as Grid) so making them subpages of the main Houdini page seems ideal.

> "It bothered me to elevate it to web/css and web/html, but realizing we have web/media, web/http, web/security (we need to add privacy and i18n) etc, makes web/houdini seem ok"

I'd agree, if we only had css and html it would seem a weird elevation, but alongside other things I think it works ok, as it is a thing unto itself really.

**Comment by chrisdavidmills** [comment]
Yup, I think Web/Houdini is fine. Let's go with that.
