### ISSUE TITLE
HOUDINI: Intro: Tutorial on Composite Scrolling and Animation (8)

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1390]
Composite Scrolling and Animation
Create the learn section for Composite Scrolling and Animation (this is an API landing page. Rather, it's in the learn section)
Page 8 of learning section for houdini

    Intro (page 1)
    CSS Parser API (page 2)
    CSS Properties and Values API (page 3)
    CSS Typed OM (page 4)
    CSS Layout API (page 5)
    CSS Paint API (page 6)
    Worklets (page 7)
    Composite Scrolling and Animation (page 8)
    Summary/Conclusion/who knows (page 9)

**Comment by chrisdavidmills** [comment]
I'd be a bit wary about putting Houdinni stuff in the Learning Area of MDN. Sure, you are writing tutorials about it, but it's not really a beginner's topic.
