### ISSUE TITLE
Developer Needs Survey - Update with final copy

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1393]
# User story

As a product owner, I want to update the design and copy for the developer needs survey banner, so I can deploy it to production by the 6th of May 2019.

# Acceptance criteria

- [x] Final copy added
- [x] Deployed to production behind a waffle flag(developer_needs)

# Tasks

2. - [x] New copy provided (@atopal responsible)
3. - [x] Implement final copy
4. - [x] Open PR for review
5. - [x] Push to production

**Comment by schalkneethling** [comment]
Nic has presented the following design proposals for review:

## Wide viewport

![proposed](https://user-images.githubusercontent.com/10350960/56791923-9926e180-6808-11e9-8f47-8ffaa51bd768.png)

## Smaller desktop viewport

![proposed-smaller screen](https://user-images.githubusercontent.com/10350960/56791937-a774fd80-6808-11e9-86e0-948c1ab9892d.png)

## Alternate design option

![proposed-outlined](https://user-images.githubusercontent.com/10350960/56791951-b22f9280-6808-11e9-86e5-b4c638db97b2.png)

**Comment by schalkneethling** [comment]
A couple of thoughts from my end:

*The left-hand icon* I would personally not use the image of the dino head behind the clipboard icon. The clipboard by itself would work better I believe. With regards to colour contrast, I would suggest we use either `#222` or a deep blue(`#161e65`) for the stroke colour.

*layout for wide viewports* The spacing feels awkward to me. The button feels a little all by it's lonesome there at the far right ;) Perhaps instead of trying to use all of the horizontal space, we can constrain the content to a max width?

Alternatively, we could explore bumping the font size of the heading and the main copy and keep it stacked as in the smaller viewport layout? As well as constrain the overall width of the content.

*CTA button* I prefer the solid over the outlined button. I am wondering whether here, we should also go with a darker/deeper blue(`#161e65`)?

*the curve* I like the idea of the curve creating a nice flow and sense of movement. I do wonder whether we can make it a bit more deliberate. I'm thinking a little more of an extended S-shaped curve.

Thanks so much for these Nic!

**Comment by nickbrandt** [comment]
Thanks for the feedback @schalkneethling! 

I've updated the concept to reflect some of the things you talked about.

**left-hand icon** no longer contains the dino head logo and has a darker stroke for contrast

**layout**: this was initially designed to work with the current max width of the site (larger version was its max width), though I understand what you are saying about the empty space between elements that this causes. I reduced the max width to 1024 with some padding.

I don't think it makes sense to increase the font size much for the heading or copy, as this banner shouldn't be as prominent as an H2 on the page. 

I updated the CTA button with the hex value provided, though I'm curious if we use that button color anywhere else on the site. One of my tasks will be helping put together a pattern library for MDN, and I don't want to get to the point where we have a lot of 1-off styles on the site. Either way, once we get to the point where we have a pattern library we can clean up a lot of that sort of thing.

Let me know if you have any other thoughts on the design.

![proposed-updated](https://user-images.githubusercontent.com/5185090/56816681-4a297e00-6801-11e9-87e9-193df12a7d70.png)

**Comment by schalkneethling** [comment]
Thanks so much, @nickbrandt, this looks great!

>  though I'm curious if we use that button color anywhere else on the site

No, but I am rethinking some aspects of our current colour scheme, and this button colour to me seems like an improvement over what we have for CTA style buttons.

> One of my tasks will be helping put together a pattern library for MDN

You don't say ;) I am working on a similar thing using a combination of [Storybook](https://storybook.js.org/) and some basic HTML pages. We should talk.

The first iteration, which is now out of date, lives here https://github.com/mdn/mdn-fiori/. This will also be the home of the next version. So far everything is still locally on my machine and in my head. But is going to change very soon.

**Comment by nickbrandt** [comment]
![Screen Shot 2019-04-30 at 9 56 42 AM](https://user-images.githubusercontent.com/5185090/56975624-70fff100-6b2e-11e9-9f14-cecc8f6071b2.png)

I'm thinking something like this for mobile, probably just doing the full background gradient to keep things simple. Any thoughts @atopal @schalkneethling ?

> You don't say ;) I am working on a similar thing using a combination of Storybook and some basic HTML pages. We should talk.
Awesome, I'd love to chat about it. Perhaps we can discuss this a bit on the 1:1 you scheduled with me for Thursday

**Comment by schalkneethling** [comment]
> probably just doing the full background gradient to keep things simple

Yup, I agree

> Perhaps we can discuss this a bit on the 1:1 you scheduled with me for Thursday

:+1:

**Comment by schalkneethling** [comment]
@nickbrandt One thing I would suggest is that the button placement changes a bit for the mobile phone view. With the "S" curve its placements make sense, but without it, I kinda feel that the left edge should line up with the copy. Thoughts?

**Comment by nickbrandt** [comment]
![Screen Shot 2019-04-30 at 10 33 20 AM](https://user-images.githubusercontent.com/5185090/56977961-a3f8b380-6b33-11e9-9029-46842f8db20a.png)

@schalkneethling I played a bit with the button placement, though I felt having it aligned with the copy felt a bit odd (see above, though removing some padding on the btn helps). Otherwise we can just center it, or we just lose the survey icon on mobile and keep the button left aligned. Let me know your thoughts.

**Comment by schalkneethling** [comment]
@nickbrandt Yeah, this is a tough one. With the circular nature of the icon and the square of the copy, it is hard to find a natural happy place. I am hesitant to do the old centre all the things but, can you do

1. Just centre everything without centre aligning the content
2. Literally, centre everything.

Meh, that was hard to explain, and I believe I did a not to great of a job ;) We should share source files @nickbrandt

**Comment by nickbrandt** [comment]
![Screen Shot 2019-04-30 at 11 51 58 AM](https://user-images.githubusercontent.com/5185090/56982546-cf34d000-6b3e-11e9-8476-9d3f2595aa5f.png)

I understand what you're saying @schalkneethling . I think one of the above would work for our needs, the ones on the left and right being the strongest IMO. Centering the content (but not the copy) also seems a bit weird to me in this case.

**Comment by schalkneethling** [comment]
@nickbrandt I would vote for the one on the far right. Thanks!

**Comment by peterbe** [comment]
I personally prefer the one on the far right too. The icon isn't helping me (is it a todo-list icon??) and centered looks great on mobile.

**Comment by jmswisher** [comment]
Updated the issue title to reflect discussion in the Dev sprint planning meeting today. Design is to be a separate issue.

**Comment by atopal** [comment]
Text:

Header: MDN survey
body: Help us understand the top 10 needs of Web developers and designers.
button: Take the survey

We might add another sentence tot he body: Get early access to results.

**Comment by atopal** [comment]
So, this is the design user story and we have a separate implementation user story?

Re design for mobile: I prefer the middle one, but I don't feel strongly about it. Your call, Nick. Besides: 95% of users will see it on desktop, and more than that are going to take it on desktop, so I wouldn't over-rotate on it ;)

**Comment by schalkneethling** [comment]
> So, this is the design user story and we have a separate implementation user story?

It might seem a little confusing at the moment but, this did cover the design and copy, but now we have this for the copy and the one below for the design.

https://github.com/mdn/sprints/issues/1466

**Comment by atopal** [comment]
Yeah, since it seems like we discussed and agreed on design in this issue. Can we update the acceptance criteria then? What else is necessary to calk this issue done?

**Comment by schalkneethling** [comment]
> Yeah, since it seems like we discussed and agreed on design in this issue. Can we update the acceptance criteria then? What else is necessary to calk this issue done?

For me to add the new copy, open a PR and have it merged. After that, this one is good to go. We then need to be sure that these new strings get into Pontoon and perhaps reach out to some of the most active community members and let them know about the new strings that require localization.

**Comment by peterbe** [comment]
> We then need to be sure that these new strings get into Pontoon

Who knows about this more specifically?

As of right now, it's May 2nd. I think @escattone is doing a release today but it won't have this copy change in it. Suppose we make the PR, get it to `master`, wait till we do another release so it makes it into Pontoon, then we have to wait for some days until what's in Pontoon can be "dragged" back into the build that goes out. That's going to be tight!
