### ISSUE TITLE
Document HTMLImageElement complete

### ISSUE THREAD

**Issue by joybee007** [mdn/sprints#1394]
Complete the subpages for HTMLImageElement:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement

## Acceptance criteria

- [x] Each subpage has been created and meets our standards for content and layout
- [x] Pages submitted for tech review as needed

**Comment by jmswisher** [comment]
This topic has not been documented in English, and therefore has not been translated into Chinese.

**Comment by joybee007** [comment]
What can I do for it?

**Comment by chrisdavidmills** [comment]
If you look at https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement, you'll see that there are a nunmber of red links — these pages that have not been written yet. If you are interested, I could givee you page creation permission and you could create a page for complete, and others too if you wish ;-)

**Comment by a2sheppy** [comment]
Working on this actively.
