### ISSUE TITLE
Missing documentation for touch events

### ISSUE THREAD

**Issue by ende124** [mdn/sprints#1395]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
Some links under Touch Events in the Event reference are missing, found here: https://developer.mozilla.org/en-US/docs/Web/Events#Touch_events

Pages for the following events are missing:
* MozEdgeUIGesture
* MozMagnifyGesture
* MozMagnifyGestureStart
* MozMagnifyGestureUpdate
* MozPressTapGesture
* MozRotateGesture
* MozRotateGestureStart
* MozRotateGestureUpdate
* MozSwipeGesture
* MozTapGesture

**Comment by irenesmith** [comment]
If you look at the reason for the pages not existing, you will see the reason that the pages were deleted:

"Event out of date — relates to an obsolete add-ons system that is no longer available."

**Comment by irenesmith** [comment]
As these pages were deleted because the content was obsolete, closing the issue.
