### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript

### ISSUE THREAD

**Issue by subhajitbanerjee1989** [mdn/sprints#1409]
# Request type
Content Presentation

# Details
I just visited MDN - didn't look at the content but the navigation is old style boring. we don't read java from oracle docs because that's not navigation friendly but we do read from angular.io.
1. Please create a horizontal / header style navigation that leads in/out documentation
2. Please create vertical left nav for topics(html, css, js, ts) with dropdown for sub-sections(for js - basic, objects, ds, new, best practices etc)
3. Please create vertical right nav for attributes under sub-section (for JS objects - array, map, set etc)
[don't keep these objects on left to uplift their value - people working in these technologies switch to different topics very quickly - they don't stay long like java]
4. please make sure user can see which option is selected - make it bold or grayscale but make it something - when i click on browser compatibility page goes down but left nav shouldn't

[i had seen it in ionic 2 years back - saw they don't follow it anymore - the way ionic represented then is far better than even angular]

# Thanks
it's a good thing what you are doing - most of us are busy in earning bread - passing nights - waiting for uncle death - not you - keep changing the world - lets provide others opportunity to follow something new

**Comment by chrisdavidmills** [comment]
We appreciate the feedback, but we can't update our website's layout significantly just like that. I'll close this one.

**Comment by jmswisher** [comment]
Feedback to consider when revamping sidebars.
