### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

### ISSUE THREAD

**Issue by andrefelix** [mdn/sprints#1413]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

When run the first example in the page, the message error is showing: Error: str.matchAll is not a function.

**Comment by chrisdavidmills** [comment]
It works fine for me; are you using Nightly or Beta Firefox, or release Firefox? `matchAll()` is really new (was only implemented in Fx67) so your browser might not be new enough.

**Comment by andrefelix** [comment]
You're right, my Firefox version is 66.0.3 and need be updated. Thanks for
answering me.

Em seg, 29 de abr de 2019 às 05:32, Chris Mills <notifications@github.com>
escreveu:

**Comment by chrisdavidmills** [comment]
You're welcome.
