### ISSUE TITLE
Connect Page documentation for Metro apps to update or remove

### ISSUE THREAD

**Issue by juliandescottes** [mdn/sprints#1415]
Just found the following page on MDN:

https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Firefox_for_Metro#Set_up_Firefox_for_desktop

It documents a flow relying on the Connect page. The Connect page will be disabled in Firefox 69 and removed in Firefox 70. We could migrate the content to a flow using the new Remote Debugging, but I don't know if it's still relevant (Metro applications?).

**Comment by juliandescottes** [comment]
cc @irenesmith

**Comment by irenesmith** [comment]
This definitely doesn't need to exist. I've decided to archive it.

**Comment by irenesmith** [comment]
I have archived the [English page](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Remote_debugging/Firefox_for_Metro) and removed the translations.
