### ISSUE TITLE
Replace Sauce Labs Banner with Survey Banner

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#142]
Dear Team,

We would like to replace the Home Page Sauce Labs Banner with a new Survey Banner. 

We would like to collect 500 - 1500 responses, which we estimate will take about 1 - 1.5 months. 

See attached creative, the copy would read:
Do you like creating things things for the web? We'd love to hear form you.

Link to the survey:
https://www.surveygizmo.com/s3/4300575/39f3e6f3d824

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1462835

**Comment by chrisdavidmills** [comment]
Sounds OK to me.

**Comment by schalkneethling** [comment]
PR: https://github.com/mozilla/kuma/pull/4815

**Comment by schalkneethling** [comment]
Merged and pushed to production
