### ISSUE TITLE
[P1] WebRTC updates for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1424]
See https://trello.com/c/ejryeYyB/73-webrtc-10-fx-66 for list of bugs

# Acceptance criteria

1. - [x] Support RTCIceCandidate.usernameFragment —  documented appropriately

**Comment by a2sheppy** [comment]
### RTCIceCandidate.usernameFragment
* [Submitted PR](https://github.com/mdn/browser-compat-data/pull/4086)
* Talked to jib and others about the use cases for this property; there aren't really many and there will be fewer in the future as it's mostly dealt with internally
* Added example to the [reference](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/usernameFragment)
