### ISSUE TITLE
[P2] WebGL-related docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1426]
See https://trello.com/c/mhsKKnNY/170-webgl-api-fx-67 for bugs list

# Acceptance criteria

1. - [x] EXT_float_blend restrictions break some content — documented appropriately

**Comment by a2sheppy** [comment]
### `EXT_float_blend`
Question out to Jeff Gilbert for verification, but pretty sure this isn't about no longer being experimental, but about the extension being enabled by default in WebGL contexts
