### ISSUE TITLE
[P2] Touch event docs tasks for Firefox 67

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1427]
See https://trello.com/c/tOxWV0Jo/48-pointer-touch-events-fx-67 for bugs list

# Acceptance criteria

1. - [ ] Consider removing some parts of touch event APIs on desktop — documented appropriately.

**Comment by wbamberg** [comment]
As I understood it this amounts to https://bugzilla.mozilla.org/show_bug.cgi?id=1412485, which is dev-doc-complete, so I guess this can be closed?

**Comment by chrisdavidmills** [comment]
Yes, definitely.
