### ISSUE TITLE
invalid link in DataTransferItem/webkitGetAsEntry doc page

### ISSUE THREAD

**Issue by frudman** [mdn/sprints#1429]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[This page](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry) has an invalid link pointing to a [non-existent page](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/createReader).

I suspect the correct link should be: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry/createReader

**Comment by jmswisher** [comment]
Fixed, thanks.
