### ISSUE TITLE
Write RUM utility

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#143]
One of our first to-dos for the performance audit and related work is to write a general utility to gather RUM data using the various timing APIs, see below. Schalk and Tim will work together on the utility and then integrate it into the interactive examples and MDN.

[1] https://www.w3.org/TR/user-timing/
[2] https://www.w3.org/TR/resource-timing-2/
[3] https://www.w3.org/TR/navigation-timing/

**Comment by jwhitlock** [comment]
Reported as done in sprint review
