### ISSUE TITLE
Write documentation for CSS Grid Level 2 subgrid

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1431]
# User story

As a web developer I want to understand the subgrid feature of CSS Grid Level 2, which is being implemented in Firefox Nightly.

# Acceptance criteria

- Guide written
- BCD updated to add subgrid feature

# Tasks

1. - [ ] Add subgrid as a value to BCD data for grid-template-rows and grid-template-columns
2. - [x] Write an additional guide for the grid section covering subgrid

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid

Once the Grid Inspector is updated I think it would be nice to add a couple of use cases at the end, however I would like to be able to show line numbers and so on in the Inspector, at the moment that's a bit broken. This I think gives me enough to link to from the Hacks post.

**Comment by chrisdavidmills** [comment]
Nice work Rachel. I've given the article a copy edit, but didn't change anything significant. I also added a link to it from the main grid page and tried to make the sidebar display the subgrid article link, although it is being a bit slow to update.

I'm assuming you're waiting till subgrid lands in nightly and the devtools are working properly before updating the devtools grid page, or grid-template-columns/grid-template-rows.

**Comment by rachelandrew** [comment]
Yeah, I thought it was useful to have this as something to link from the Hacks post and ready for people who might be interested as soon as it lands. I think it might be a bit confusing to update the other bits right now. Once it lands I'll do that though.

**Comment by chrisdavidmills** [comment]
Sounds perfect to me.

**Comment by rachelandrew** [comment]
This is kind of as done as it can be - so I moved it to done for the purpose of this sprint but it will need reviving sooner or later :)
