### ISSUE TITLE
LearnSidebar macro: Fix spelling of "Object building practise"

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1433]
The title of the article "Object building practice" is listed in `LearnSidebar` using the British spelling "Object building practise". This needs to be corrected to match the style guide usage of American spellings.

**Comment by chrisdavidmills** [comment]
Done: https://github.com/mdn/kumascript/pull/1138

Can I get a review, please?

**Comment by chrisdavidmills** [comment]
@a2sheppy
