### ISSUE TITLE
Close payments experiment and clean up

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1441]
The payments experiment has been completed. We are not rolling out a contribution based solution in the near future, so we need to close the current flows and clean up.

**Comment by peterbe** [comment]
@schalkneethling What's remaining here?

**Comment by schalkneethling** [comment]
> @schalkneethling What's remaining here?

Essentially the pieces that allow people to cancel their contribution. Not sure at what point we will have to remove this as well.

**Comment by peterbe** [comment]
How does it correlate to the new React front-end? Suppose we switch to that in August already, are we ready to NOT port any of the lingering pieces to React?

**Comment by schalkneethling** [comment]
> How does it correlate to the new React front-end? Suppose we switch to that in August already, are we ready to NOT port any of the lingering pieces to React?

Good question. For the most part, these are static pages. The one thing that is not is part of the profile so, should we convert the profile(which I believe we will be), then the cancellation of subscriptions will need to be ported I am guessing.

@atopal Thoughts?
