### ISSUE TITLE
Stop submitting URLs being marked as no-index to sitemap

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1443]
# User story
As a Product Manager I want us to stop submitting URLs being marked as no-index to the sitemap, so they don't appear as false positives in search console

# Acceptance criteria
- [ ] Any document submitted to sitemap is indexable

# Tasks

1. - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1551968

Note! There might still be some obscure documents that might get included in the sitemap but later found to have `<meta name="robots" content="noindex, nofollow">` when Googlebot visits.

**Comment by Elchi3** [comment]
Please re-file as kuma issue if still valid
