### ISSUE TITLE
Remove sign in pages from robots.txt so the crawler can remove them from the index

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1444]
# User story
As PM I want sign in pages to be removed from robots.txt, so the crawler can remove them from the index and they don't show up as false positives in Search Console

# Acceptance criteria
- [ ] users/signin doesn't show up in SC as "Indexed, though blocked by robots.txt"
- [ ] users/github/login doesn't show up in SC as "Indexed, though blocked by robots.txt"

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by Elchi3** [comment]
Please re-file as kuma issue if still valid.
