### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods$edit

### ISSUE THREAD

**Issue by Pointy** [mdn/sprints#1447]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The opening paragraphs of this article erroneously (yet stridently) make the claim that "everything in JavaScript is an object".  That is factually incorrect: primitive values most certainly are not objects. It's misleading and it conflicts with information elsewhere in MDN.

**Comment by chrisdavidmills** [comment]
Well, it's one of those things that people say that is accepted as an advantage of JS. But strictly speaking you are right. I've edited that sentence.
