### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by tsongas** [mdn/sprints#1449]
Why does MDN have literally the worst, most useless search feature of any site on the Internet?

**Comment by chrisdavidmills** [comment]
We agree it is not great. But we have a very limited size dev team that always has other, higher priority things to work on. And it is not as if MDN is unsearchable — everybody just uses a search engine rather than the on site search.

We are hoping to revisit this soon.
