### ISSUE TITLE
Set up speed curve tests for beta.developer.mozilla.org

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#1450]
# User story
As an MDN engineer, I want to measure the page load and time-to-interactive performance for the static beta site so that I can be sure we won't regress performance by making it the default.

# Acceptance criteria
- speedcurve tests are set up and collecting synthetic perf data for beta.developer.mozilla.org.  
- if it hasn't already been done: the old tests for the "ducks" urls have been removed
- we have compared the beta pages to the regular non-beta pages to determine whether performance is acceptable or if there is still performance work to be done before the beta pages can become the default.

**Comment by atopal** [comment]
Is this a subset of https://github.com/mdn/sprints/issues/1419 ?

**Comment by davidflanagan** [comment]
Yes, this is a subset.

I've now edited the speedcurve config to change the old react test so it is using the beta subdomain instead of the fake /ducks/ url. And I've also asked it to run the react comparison tests 3 times a day instead of once. (But I was careful to ensure that the other tests are still only running once a day.)

**Comment by davidflanagan** [comment]
Looking at the speedcurve results, it appears that the react pages are not correctly doing the performance/timing mark thing when the interactive examples are ready.  There is some js code that needs to run for that, and maybe I don't have it set up.  That's something to look into for this user story.

**Comment by davidflanagan** [comment]
The interactive examples performance data is going to be harder to fix than I expected.

The interactive examples code in the iframe does a postMessage() to send its timing data to the containing window where it can be reported to GA. But, for security (which may not be necessary) it puts a domain in the postMessage() call, and the postMessage() only succeeds if the domain matches the domain of the document the iframe is embedded in.

By default, the postMessage() is targeted at developer.mozilla.org.  On staging, the container page passes an extra query parameter to the interactive examples server specifying that it should use developer.allizom.org instead. The problem is that now that we have our React version on beta.developer.allizom.org, the domains don't match, so the postMessage() fails, and we never report this timing data to GA.

And the reason that this is not easy to fix is that the extra query parameter used to tell interactive examples where to direct the postMessage to is hardcoded into the URL by KumaScript. Both our beta and non-beta domains share one set of KumaScript rendered documents, so we can't fix this just by telling KumaScript about our new beta domain.

We could fix this by changing the KumaScript EmbedInteractiveExamples macro to use '*' as the domain. But the documentation of postMessage() is full of security warnings about what a bad idea it is to use a wildcard in postMessage(). In this case, since it is just timing data, I think it would be fine to just use a '*' wildcard.  This would involve changing the macro and then rerendering all of our documents, which would be a pain.

Alternatively, we could just modify the mdn/bob repo (which builds the interactive examples) to change its postMessage() code to always use '*', and then redeploy all of the interactive examples.

Or, alternatively, we could modify the communication protocol so that the containing window has to post a message to the iframe first, and then the iframe response with the timing data. That would at least let it know which domain to post to. This would involve a new version of Kuma, and involve regenerating all of the interactive examples.

If we do nothing, we won't get any interactive examples timing data from our beta domain until we go live and start serving the react version of the pages on developer.mozilla.org.

@schalkneethling @wbamberg: can you think of other ways to fix this issue? And how do you feel about using '*' as the postMessage() target?

**Comment by davidflanagan** [comment]
I think that interactive examples are served out of an s3 bucket. So a quick fix for this might be to hand-edit the S3 files for the three documents that we're tracking on speedcurve to change the postMessage to use `*`. That would get us the data we need right away without requiring a bigger change that would no longer be needed once the beta domain goes away...

The downside is that we'd have to re-do the hand edit any time the interactive examples are regenerated, if we wanted to continue to collect data...

**Comment by wbamberg** [comment]
@davidflanagan , thanks for asking, but I don't really have the expertise to answer this, and since this doesn't seem affect the user experience, I don't really have an opinion either, so I'd be happy with whatever you and @schalkneethling come up with :).

**Comment by schalkneethling** [comment]
@davidflanagan Good question. Let me think about it. Will get back to you ASAP.

**Comment by schalkneethling** [comment]
@davidflanagan Perhaps this is a happy middleground between the current and a wildcard?

```
const origin = window.parent.location.origin;
if (origin && (origin.includes('mozilla.org') || origin.includes('allizom.org'))) {
    window.ieConfig = {
        origin: origin
    };
}
```

In reference to this function:
https://github.com/mdn/bob/blob/master/editor/js/editor-libs/perf.js#L11

**Comment by davidflanagan** [comment]
@schalkneethling: If we're going to look at window.parent to get the origin, we shouldn't have to special case mozilla.org and allizom.org: we can just always use the parent origin. But it seems to me that is the same as using '*'.

How much work is it to change the bob repo and regenerate all the example files? Is this routine, or would it be easier to just hand-edit the three relevant S3 files that we're testing against?

**Comment by schalkneethling** [comment]
> @schalkneethling: If we're going to look at window.parent to get the origin, we shouldn't have to special case mozilla.org and allizom.org: we can just always use the parent origin. But it seems to me that is the same as using '*'.
> 

Yup, that is very true.

> How much work is it to change the bob repo and regenerate all the example files? Is this routine, or would it be easier to just hand-edit the three relevant S3 files that we're testing against?

That is not a big deal, as it is all automated. Once the change is merged in BoB, Renovate will automatically open a PR against interactive examples. Once that PR is merged, the pages will automatically be rebuilt and copied to S3.

**Comment by davidflanagan** [comment]
Here's what Schalk and I decided on for the interactive examples: https://github.com/mdn/bob/pull/235

**Comment by davidflanagan** [comment]
The change in the BoB repo has now propagated (thanks to Schalk) to the interactive examples.

If I visit beta.developer.mozilla.org, I can verify that timing data is being received by typing:

```
performance.getEntriesByName('ie-time-to-interactive')[0].duration
performance.getEntriesByName('ie-time-to-complete')[0].duration
```
The data is not showing up in Speedcurve yet... Maybe there isn't enough data to draw a curve yet? But I'm pretty sure it is being sent there, so I'm going to call this closed.

**Comment by atopal** [comment]
Hey David, I looked into it. What we need is js-ie-load-event-end-measure and css-ie-load-event-end-measure. That's available in the non-react version, but missing in the react version

**Comment by davidflanagan** [comment]
Thanks @atopal. I'll copy that information into the new user story. Those measures must be based on the ie-time-to-complete measure that I got working in this user story, so hopefully it will be easy to take the next step and get the others sent, too.
