### ISSUE TITLE
Developer Needs Survey - Update with final design

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1466]
# User story

As a product owner, I want to update the design for the developer needs survey banner, so I can deploy it to production by the 6th of May 2019.

Initial discussion on the design can be followed in the following user story:
https://github.com/mdn/sprints/issues/1393#issuecomment-486962939

Discussion, approvals etc. related to the design to be continued here.

# Acceptance criteria

- [x] New design implemented
- [ ] Deployed to production behind a waffle flag(developer_needs)

# Tasks

1. - [x] New design approved (@nickbrandt responsible for the design, @atopal for approval)
3. - [x] Implement final design
4. - [x] Open PR for review
5. - [ ] Push to production

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1552481

**Comment by schalkneethling** [comment]
The tentative final design can be seen here, on the far right:
https://github.com/mdn/sprints/issues/1393#issuecomment-488051476

**Comment by nickbrandt** [comment]
Below are the current designs for the banner. @atopal let us know if these are approved by you.

![survey-banner](https://user-images.githubusercontent.com/5185090/57150098-95f0a000-6d8a-11e9-878d-6bcd6cc611f3.png)

![survey-banner-mobile](https://user-images.githubusercontent.com/5185090/57150099-95f0a000-6d8a-11e9-8e33-c4901d635b6c.png)

**Comment by atopal** [comment]
Thanks Nick, the header should be "MDN Survey", but other than that: :+1:

**Comment by jmswisher** [comment]
Is this Done? It was marked Done in the spreadsheet, but the Bugzilla issue is still open.

**Comment by schalkneethling** [comment]
> Is this Done? It was marked Done in the spreadsheet, but the Bugzilla issue is still open.

Yes, this is done. Will close all the things.
