### ISSUE TITLE
Payments: Copy update request

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1467]
# User story

As a product owner I want to prevent unnecessary emails to mdn-support@, and therefore want the following copy change request implemented:

> Please change:
> 
> "Please contact mdn-support@ to cancel. " to
> something that links to
> https://developer.mozilla.org/en-US/payments/recurring/management
> 
> in order to prevent unnecessary emails to: mdn-support@

Original Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1547771

# Acceptance criteria

- [x] Copy updated to point a user to the recurring payment management page as opposed to the support email address

# Tasks

1. - [x] Update copy as per request
2. - [x] Open PR
3. - [ ] Deploy to production

**Comment by jmswisher** [comment]
This appears to be live in production, so closing.
