### ISSUE TITLE
Identify customers for MDN compat data

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1468]
# User story
As a Product Manager I want to identify customers for MDN's BCD, so we can identify needs and prioritize the work on BCD

# Acceptance criteria
- [ ] 10 customers are identified
- [ ] All customers have contact info

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
