### ISSUE TITLE
Interview 2 potential BCD customers

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1469]
As a PM I want to interview potential BCD customers to understand whether they are likely customers and what their needs are, so we can prioritize the work on BCD

# Acceptance criteria
- [ ] 2 customers interviewed
- [ ] Interviews documented

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
