### ISSUE TITLE
unclear instructions: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Mercurial/Bundles

### ISSUE THREAD

**Issue by Dani3lNL** [mdn/sprints#1473]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It reads
> "To use the below command in Windows, export the \path\to\hg and invoke the command from command prompt."

in the article, where it's unclear to users how they "export the \path\to\hg" and how they "invoke" the command. Please add a better understandable instruction.

**Comment by Elchi3** [comment]
Thanks for your issue. This doc set isn't maintained and will be archived soon. Closing this issue.
You might want to checkout new docs at https://firefox-source-docs.mozilla.org/
