### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

### ISSUE THREAD

**Issue by ngoodwin14** [mdn/sprints#1480]
# Request type
- [x ] Correction or update

# Details
The data is serialized using the structured clone algorithm.

Data is plural, datum is singular. The sentence should read:

The data **are** serialized using the structured clone algorithm.

**Comment by jmswisher** [comment]
The [MDN writing style guide](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Other_references) defers to the Microsoft Style Guide for issues it does not explicitly cover. [That guide says](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/data-datum): "Use _data_ as both a singular and plural noun. Don't use _datum_. Always use _data_ with a singular verb, even if you're talking about more than one data set. Don't use _the data are_."
