### ISSUE TITLE
Incorrect GroupData info for Long Tasks API

### ISSUE THREAD

**Issue by leshields** [mdn/sprints#1483]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API

# Details
The "Long Tasks" link under "Specifications" is broken. It goes to `https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks` (404 error), but it should instead go to `https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks_API`

**Comment by jmswisher** [comment]
The API list on that page is generated by the [ListGroups](https://github.com/mdn/kumascript/blob/master/macros/ListGroups.ejs) macro, which grabs info from [GroupData.json](https://github.com/mdn/kumascript/blob/master/macros/GroupData.json). The info in that file for the Long Tasks API is incorrect. I think it's missing an "overview", but need to double-check.

**Comment by wbamberg** [comment]
Yes, @jmswisher , you are right I think. I've filed https://github.com/mdn/kumascript/pull/1147.

**Comment by wbamberg** [comment]
This change is merged and deployed, and "Long Tasks API" is now appearing on https://developer.mozilla.org/en-US/docs/Web/API.

Thanks for filing @leshields and for finding the problem @jmswisher !
