### ISSUE TITLE
Mozilla/Firefox-ESR/Releases/60.6.1-Update-Addon Verification Issue

### ISSUE THREAD

**Issue by cxbignekoc** [mdn/sprints#1484]
# Request type
- [x] Please close this issue, I accidentally submitted it without adding any details

# Details

All Addons/Plugins are deactivated/ old, because no Verification, after Update on:
FF.60.6.1 ESR
Window 7-64bit

Screen:
https://www.screencast.com/t/yHI8yeyQ2diq

Similar to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by chrisdavidmills** [comment]
This should have been fixed with the new Fx release.

**Comment by wbamberg** [comment]
@cxbignekoc , please see this post: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ which should explain about this situation and how to get your Firefox add-ons working again.
