### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by ubaid-dev** [mdn/sprints#1485]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Setting up runtimes
[https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Setting_up_runtimes](url)
Following link do not work.
![broken](https://user-images.githubusercontent.com/38039843/57193776-8ff3ee00-6f47-11e9-9c82-fcc2eb848ee2.JPG)

**Comment by chrisdavidmills** [comment]
This functionality is obsolete, so many of the docs no longer exist. I've deleted that section for now. Soon, WebIDE won't exist anymore, so this page will be deleted altogether.
