### ISSUE TITLE
Default values for flex-grow and flex-basis

### ISSUE THREAD

**Issue by fkoji** [mdn/sprints#1496]
# Request type
- [ ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

> <'flex-grow'>
Defines the flex-grow of the flex item. Negative values are considered invalid. Defaults to 0 when omitted.

"When omitted, it is set to 1."  is the correct specification.

> <'flex-basis'>
Defines the flex-basis of the flex item. A preferred size of 0 must have a unit to avoid being interpreted as a flexibility. Defaults to auto when omitted.

"When omitted from the flex shorthand, its specified value is 0." is the correct specification.

see: https://www.w3.org/TR/css-flexbox-1/#flex-property

**Comment by irenesmith** [comment]
The page has been updated. I also updated the individual pages for flex-grow and flex-basis.

**Comment by fkoji** [comment]
Thank you for updating the page!
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

But, according to https://www.w3.org/TR/css-flexbox-1/#flex-property

> When omitted from the flex shorthand, its specified value is 0.

Default flex-basis value seems to be `0`.
