### ISSUE TITLE
Page Not Found on -webkit-line-clamp

### ISSUE THREAD

**Issue by ramwin** [mdn/sprints#1497]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I'm viewing the [webkit css extensions](https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions) page, and click the [-webkit-line-clamp button](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp), the link got to [https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) but a page Not Found error occured.

**Comment by chrisdavidmills** [comment]
This has now been documented, so closing.
