### ISSUE TITLE
Serve HTML <video> element page built from structured content from beta.d.m.o

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1499]
As part of our structured content experiment, we want to build a single page from the experimental structured content repository, and serve it from beta.developer.mozilla.org.

The page chosen is the page for the HTML \<video> element, since that's a reasonably complex page.

***********

Acceptance criteria: we are serving the page for the HTML \<video> element from  beta.developer.mozilla.org. The page will contain most of the pieces of the current page - examples, BCD, attributes, prose. It will not contain a sidebar at this point.

**Comment by jmswisher** [comment]
Updated this epic based on the stories assigned to Koko Taylor. @wbamberg Please adjust if this is not correct.

**Comment by jmswisher** [comment]
Oops, realized that #1638 is the new epic for these stories. Closing this one.
