### ISSUE TITLE
Add CSS Color Adjust spec to SpecData

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1506]
From @dholbert on IRC:

> Page in question in https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust and the property now lives at https://drafts.csswg.org/css-color-adjust-1/#propdef-color-adjust

> That MDN page has a link to https://drafts.csswg.org/css-color/#color-adjust which is a broken anchor, since the property has moved out of that spec & into the other one that I linked

> The current obsolete link seems to be generated from this MDN markup: {{SpecName('CSS4 Colors', '#color-adjust', 'color-adjust')}}

It looks like we need to add https://drafts.csswg.org/css-color-adjust-1 to https://github.com/mdn/kumascript/blob/master/macros/SpecData.json, then reference it from https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust.

**Comment by chrisdavidmills** [comment]
Spec added to GroupData.json; see https://github.com/mdn/kumascript/pull/1205

**Comment by chrisdavidmills** [comment]
Ref page also updated so that when the above change is merged and pushed, it will show up correctly.

**Comment by chrisdavidmills** [comment]
See https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust#Specifications

**Comment by jmswisher** [comment]
Closing since the change was merged; still needs a push to show up on the site, though.
