### ISSUE TITLE
TextEncoder.prototype.encode has an invalid polyfill

### ISSUE THREAD

**Issue by lpd-au** [mdn/sprints#1507]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
[This page](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encode#Polyfill) has the following invalid polyfill for encoding a string as UTF-8:

```
function CustomTextEncoder(str) {
    var buf       = new ArrayBuffer(str.length);
    var bufView8  = new Uint8Array(buf);
    for (var i=0, strLen=str.length; i < strLen; i++) {
        bufView8[i] = str.charCodeAt(i);
    }
    return bufView8;
}
```

This will not work correctly for inputs such as `\u6553`:

- Expected: `[230, 149, 147]`
- Actual: `[83]`

The [top level page for TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Polyfill) has a different polyfill that appears to work correctly.

**Comment by wbamberg** [comment]
Thanks for filing!

We don't want MDN to be a provider of polyfills. See the thread at https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500 for more details.

We would like ultimately to have a systematic way to link to a good polyfill service, but the polyfills we have in the Wiki aren't in general suitable even if they appear to work. So I've removed the polyfills from both the pages you linked to.

**Comment by lpd-au** [comment]
Thanks, I totally understand removing them from the wiki, but how disappointing that valid ones aren't being preserved anywhere beforehand or the page updated to point to some "good polyfill service"’s implementation. Now I feel like I encouraged the vandalism of MDN and should have kept my mouth shut about the working one :(

**Comment by wbamberg** [comment]
I have reverted the edit, for now. My opinion though is that hosting untested blobs of rather complicated code on a publicly editable Wiki isn't a very reliable way to distribute polyfills.

We also have lots of history of people posting half-working polyfills, people editing existing polyfills and introducing bugs, &c.

@chrisdavidmills , what would you like to do here?

**Comment by chrisdavidmills** [comment]
We need a general plan to tidy all these up. Lets put a work item into a work sprint soon to write a plan on what to do about polyfills.

My thoughts would be, for each polyfill on MDN:

1. Check whether the polyfill works. If it is totally broken, just delete it.
2. Check whether polyfill.io already includes a polyfill for the feature it polyfills
3. If not, file an issue on the polyfillio GitHub repo suggesting they add it, or even just add it yourself via a PR. If so, go to step 4.
4. Delete the polyfill.
5. Somewhere on MDN, document how we recommend handling polyfills
6. Write a blog post announcing our change in handling polyfills.

But this needs more discusson and plannig first.
