### ISSUE TITLE
Add a basic polyfill to the TextDecoder page

### ISSUE THREAD

**Issue by lpd-au** [mdn/sprints#1508]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
The [TextEncoder page](TextEncoder.prototype.encode) has a working polyfill to encode a string as UTF-8. It would be great if the [TextDecoder page](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) had a matching polyfill to reverse the operation for UTF-8 inputs.

**Comment by wbamberg** [comment]
Thanks for filing!

But we don't want MDN to be a distributor of polyfills. See https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500. As soon as we have a plan for it we will remove existing polyfills from MDN and point people at a service like polyfill.io.

In the meantime we shouldn't be adding new polyfills.
