### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file

### ISSUE THREAD

**Issue by Bartolomeus-649** [mdn/sprints#1509]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details
**Prettify does not work / exsists**
1.  This icon: ![image](https://user-images.githubusercontent.com/7513795/57523936-aa9edc00-7326-11e9-9051-8d7eacb674ff.png) does not exists
2. Double clicking has no effect
3. There is no option on the context menu either

![image](https://user-images.githubusercontent.com/7513795/57524211-6f50dd00-7327-11e9-8c66-14e42940cd00.png)

**Comment by irenesmith** [comment]
Thanks for reporting this issue. The icon still exists but has been moved from what was shown in the existing images. I have updated the page to show the new layout and the results.

[Pretty print a minified file](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file)

**Comment by Bartolomeus-649** [comment]
well, as you can see in the screen shot, it's not on  the left side either, it's just not there at all.

**Comment by irenesmith** [comment]
You mean this screenshot? It is located on the bottom left.
![Debugger with pretty-print icon](https://mdn.mozillademos.org/files/16639/pretty_print_source.png)

**Comment by Bartolomeus-649** [comment]
No, obviously I meant the one I submitted, as you can see there's nothing below the horizontal scrollbar and the border of the window. The blue you see at the bottom is the taskbar in windows.

**Comment by irenesmith** [comment]
I was asking because the one I inserted here is the new screenshot I added to the documentation, made today, and so that leads me to wonder what version of Firefox you are using and on what OS?

**Comment by Bartolomeus-649** [comment]
I have: 66.0.5
![image](https://user-images.githubusercontent.com/7513795/57806141-d4a93180-775e-11e9-9813-10c4ef7a8df8.png)

And here is another screen shot where there are no prettify-icon anywhere.
![image](https://user-images.githubusercontent.com/7513795/57806315-29e54300-775f-11e9-8f67-3a64e98bbf33.png)

**Comment by irenesmith** [comment]
Nuts! Using the same version of Firefox on Windows I still have the icon. I don't see a setting that could be changing its availability either. I will see what I can find out and get back to you.

**Comment by Bartolomeus-649** [comment]
<pre>FireFox V 67.0.4 x64</pre>

@irenesmith, @chrisdavidmills, Here's another page where the prettify feature in the debugger is missing for a minified script.
_ht<span>tps://login</span>.microsoftonline.com/common/oauth2/authorize?client_id=****& . . ._

script file:
https://aadcdn.msauth.net/ests/2.1/content/cdnbundles/ux.converged.login.pcore.min_4myuo72mlhdkjc9hn1du5g2.js

![image](https://user-images.githubusercontent.com/7513795/60756136-37e67000-9ffa-11e9-81d7-757e0c5cabb8.png)

**Comment by jmswisher** [comment]
@Bartolomeus-649 Are you still seeing this problem in a current version of Firefox? And what platform are you running it on?

**Comment by Bartolomeus-649** [comment]
There is a black-box icon there now, but nothing else.

![image](https://user-images.githubusercontent.com/7513795/68026750-db961300-fcb0-11e9-8fb6-407c0a2a4a81.png)

**Comment by juliandescottes** [comment]
Not all sources can be pretty printed. 
I think it applies in particular to source mapped files. The logic seems to be at https://searchfox.org/mozilla-central/rev/e878e5b81bb319c141900ce9cfcde732df5c8449/devtools/client/debugger/src/reducers/sources.js#935-957

Would be nice to still display the icon, but disabled with a message explaining why pretty printing is not available. cc @jasonLaster

**Comment by jmswisher** [comment]
I added a sentence explaining when the icon is or is not available.
