### ISSUE TITLE
Add notice of removed WebExtension proxy APIs to release notes

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1512]
The proxy.register() and proxy.unregister() functions will be removed from Firefox 71

- [ ] Notice of the removal added to the Firefox 71 release notes.

**Comment by irenesmith** [comment]
This is a 71 task. All that has to be done is add a note to the release notes about it. Here is the original deprecation notice:

The The proxy.register() and proxy.unregister() functions have been deprecated and will be removed from Firefox 71 (bug 1545811).

I suppose you should confirm that it is gone, but I haven't heard anything to the contrary. I suppose it won't even take a quarter of a point of time.

**Comment by chrisdavidmills** [comment]
Rel note was already added:

https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Changes_for_add-on_developers

BCD is already done.

I went in and updated the wording on the pages to make it more past tense, for when 71 actually comes out. Thanks @irenesmith!
