### ISSUE TITLE
Mismatch in attributes in two different pages

### ISSUE THREAD

**Issue by mercmobily** [mdn/sprints#1521]
# Request type
- [ ]  Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

[This page](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) has 

    formnovalidate | <button>

However, [this page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) which relates to the `<INPUT>` element lists `formNoValidate` as one of the properties (which reflects on `formnovalidate`.

The former page seems be be lacking `<input>` in the list of affected elements. it also seems to lack `formEncType`, `formMethod`, `formTarget` as possible attributes.

Mind you, I am sleep deprived and I might be missing something very obvious.

**Comment by chrisdavidmills** [comment]
Sleep deprivation aside, you are right. These attributes apply to button and input elements of type submit. I've updated this for formnovalidate, and also added rows for the other attributes you mention.

Thanks for reporting! I'm closing this now, but feel free to let me know if you notice anything else that's not quite right.

**Comment by mercmobily** [comment]
I slept... and am glad I could be of help here!
I noticed that those docs are like a giant Wiki and that maybe I could have made the changes myself. However, I wasn't 100% sure I wasn't missing something -- thanks for fixing them!

**Comment by chrisdavidmills** [comment]
You're welcome. It is always good to check if you are not sure. I'm happy to guide you if you feel like having a go at editing the wiki in future.

**Comment by mercmobily** [comment]
OK thank you!
