### ISSUE TITLE
SprintBummingTmobile

### ISSUE THREAD

**Issue by JointTaskForce210** [mdn/sprints#1522]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

[](url)

**Comment by JointTaskForce210** [comment]
Files  are being uploaded on Windows and Explorer only.

**Comment by chrisdavidmills** [comment]
No idea how this relates to MDN documentation, so closing.
