### ISSUE TITLE
Localization (L10n) and Internationalization (I18n) not found

### ISSUE THREAD

**Issue by Compotation** [mdn/sprints#1523]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

When visiting https://developer.mozilla.org/en-US/docs/Web, I clicked on the Localization (L10n) and Internationalization (I18n) under other topics. The link, https://developer.mozilla.org/en-US/docs/Web/Localization, doesn't work and returns a Not Found error.

**Comment by wbamberg** [comment]
Thanks for filing!

The l10n page was deleted because it contained no useful content, so I removed the link to it from the /Web page.
