### ISSUE TITLE
CSS scale() article doesn't address accessibility issues

### ISSUE THREAD

**Issue by MarjaE2** [mdn/sprints#1524]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The CSS scale() article here does not discuss accessibility issues, or ways for users to protect ourselves against transform: scale():

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale#See_also

I doubt I'm the only one to get migraines from transform: scale() and other zooming animation. (Although most of the online reports concern iOS 7). I think a warning in the header would be appropriate.

**Comment by chrisdavidmills** [comment]
Hi there @MarjaE2 ,

Thanks for reportig this issue; I have just got around to focusing on it.

I have written a standard "Accessibility concerns" section and placed it on the page you highlighted:

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale#Accessibility_concerns

and also the transform property page:

https://developer.mozilla.org/en-US/docs/Web/CSS/transform#Accessibility_concerns

Give it a read and let me know if you think this provides sufficient information.
