### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by rommilg** [mdn/sprints#1525]
every thing is right to left in hebrew

**Comment by jmswisher** [comment]
@rommilg On what page are you seeing this problem?

**Comment by rommilg** [comment]
Didn’t save it

The page in Hebrew show

+=

Like

=+

And

!==

Like

==!

It’s wrong

 

Everything is right to left

**Comment by jmswisher** [comment]
Unfortunately, we can't fix a page if we don't know which one it is. It's probably a case of somebody incorrectly putting translated content into an English page. 

Any logged-in user can revert to an earlier revision of a page. 

1. Go to the **Advanced** menu (click the gear icon), and click **History**. 
2. On the **Revision History** page, find the last good revision, and click **Revert to this revision** next to it.
3. On the **Revert Revision** page, review the source of the selected revision to make sure it's good, enter an explanatory comment (such as "misplaced translation"), and click **Revert**.
