### ISSUE TITLE
Broken links for deprecated HTMLTableCellElement properties

### ISSUE THREAD

**Issue by jake-reece** [mdn/sprints#1527]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The links under the "Deprecated Properties" section of the [HTMLTableCellElement page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement) are broken.

**Comment by chrisdavidmills** [comment]
It looks like none of the property pages have been written yet, hence them all appearing as red links.  This is not a particularly high priority task, and I can't see any of our staff getting to it any time soon. We might have to open this issue up to the community to see if anyone fancies taking it.

**Comment by jake-reece** [comment]
Ah, I was unaware that red meant the linked page was unwritten. I see the tooltip now.

Perhaps known links to broken/unwritten pages could be removed? The absence of a link might provide a better signal to readers than a 404 that MDN doesn't have any further information about the property.

**Comment by chrisdavidmills** [comment]
That is not a bad idea. We'll definitely consider that for the future.
