### ISSUE TITLE
Bug 1413825 - Express Part 6 has errors in using validation for FORM elements that are arrays (Genre)

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#153]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1413825

## Acceptance criteria

* Hamish responds to query about the referenced article.
* The claimed problem is proved or disproved.
* Updates are made to the text as necessary.

**Comment by chrisdavidmills** [comment]
This is now fixed; see the bug.
