### ISSUE TITLE
Blocked: All third-party storage access requests

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/sprints#1531]
# Request type
- [x] New documentation
- [x] Correction or update

# Details
I followed a link from my developer tools to [Blocked: All third-party storage access requests](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign?utm_source=devtools&utm_medium=firefox-cookie-errors&utm_campaign=default) and all it says is "content goes here".

**Comment by chrisdavidmills** [comment]
Hrm, someone was supposed to put some content up here, and they ... haven't ;-|

I have chased them up and will hopefully have it resolved soon. Cheers Stephanie!

**Comment by chrisdavidmills** [comment]
We've now got the information filled in on those SAP error pages, so closing. Thanks again for reporting.
