### ISSUE TITLE
As a PM I want to know whether we are blocking Google Crawler or Google Translate so we can plan to stop it

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1532]
# User story
As a PM I wnat to know whether we are blocking Google Crawler or Google Translate so we can plan to stop it

# Acceptance criteria
- [ ] documented rate of blocking via django rate limit for Google Crwaler and Google Translate

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by limed** [comment]
Data sent to @atopal via email

**Comment by atopal** [comment]
According to that data we blocked Google crawler 6 times in the last month, and Google translate more than 300 times. @escattone I'd suggest that we double the rate limit threshold from 400 to 800 pages for the [documents listed here](https://docs.google.com/document/d/1v0TcFDmR4DDJsEXSuRbvTWXjU20vABeY6DJT4-NZw4Q/edit?ts=5c7ec2a5#), assuming that won't require additional work to make it work.

Also, Ed, can you attach the list of URLs that they were accessing when they were blocked?

**Comment by escattone** [comment]
When I re-ran the Athena query against the production CDN logs to get the URI paths that experienced 429's in the past month, the majority were paths to the document view (e.g., `/zh-TW/docs/Web`), but there were a significant number of `$compare` and `$history` paths as well (e.g., `/en-US/docs/Tools$compare` and `/en-US/docs/Web$history`). The `$compare` and `$history` paths are disallowed by `robots.txt` however, so I assume I don't need to increase the rate-limiting thresholds on those views (which are 15 rpm and 20 rpm respectively)?

**Comment by atopal** [comment]
Yes, just the 3 views that already have a 400 page limit, please.
