### ISSUE TITLE
Update MDN page: Limitations of the new debugger

### ISSUE THREAD

**Issue by janodvarko** [mdn/sprints#1533]
# Request type
Correction or update

# Details
The following page should be updated:
https://developer.mozilla.org/en-US/docs/Tools/Debugger/Limitations_of_the_new_debugger

* Broken link: Breaking on DOM events
* Broken link: Highlighting and inspecting DOM nodes
* The debugger is now enabled everywhere (text should be reworded)

But, the old debugger is gone and we only have the Debugger now, so perhaps the page can be removed entirely?

WDYT? @jasonLaster @darkwing @digitarald 

Honza

**Comment by digitarald** [comment]
I removed the reference from  https://developer.mozilla.org/en-US/docs/Tools/Debugger, removing the page would be the last remaining step.

**Comment by irenesmith** [comment]
The page has been deleted.
