### ISSUE TITLE
DevTools sidebar has broken design and bad links

### ISSUE THREAD

**Issue by digitarald** [mdn/sprints#1536]
# Request type

Correction or update

# Details

DevTools sidebar can expand `Core Tools > Network Monitor` section, which has a broken layout:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/8599/57790320-5c575780-76ef-11e9-9199-e60f1ca29088.png">

Clicking the links leads to URLs like `https://developer.mozilla.org/en-US/docs/Tools/%3C=%=baseURLNetwork_Monitor/request_list`

<img width="760" alt="image" src="https://user-images.githubusercontent.com/8599/57790410-8a3c9c00-76ef-11e9-8b33-cf82e5dfaedc.png">

**Comment by digitarald** [comment]
Pinged @irenesmith about this as well.

**Comment by chrisdavidmills** [comment]
I took a quick look, and noticed the problem, so submitted a PR to fix it: https://github.com/mdn/kumascript/pull/1152

**Comment by chrisdavidmills** [comment]
The above PR has been reviewed, fixed up, and merged. One the next Kuma release happens and the changes actually go live on the site, we'll close this issue.

**Comment by chrisdavidmills** [comment]
I can confirm this is now fixed on the live site. If you see any pages where the sidebar is still broken, try a Shift + Refresh.
