### ISSUE TITLE
Resolve missing API overview pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1537]
As per https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/18, the following APIs listed in GroupData.json seem to be missing overview pages:

* <strike>Console API</strike> - this was done in https://github.com/mdn/sprints/issues/1582
* Device Orientation Events
* File API
* Geometry Interfaces
* <strike>Resize Observer API</strike> - this has been done
* SVG
* Web MIDI API

We should write overview pages for them, with the exception of:

* <strike>CSSOM View - fold into CSSOM</strike> - this is done
* DOM Events - merge into DOM
* XDomain - delete the group

Also these APIs do now have overview pages, but need their GroupData.json entries to be updated:

* Screen Orientation API
* URL API

**Comment by wbamberg** [comment]
See also https://github.com/mdn/sprints/issues/1516 where someone has encountered this problem for the URL API.

**Comment by jmswisher** [comment]
@wbamberg Are you planning on adding more stories to this, or can it be closed?

**Comment by wbamberg** [comment]
@jmswisher , I'm not currently planning to work on this but it is still relevant, so I think it should be kept open.

We should probably make a decision on how important it is, so we can get someone to look at it. Let's ask @chrisdavidmills about that. I'm happy to file issues for the different APIs (some might be more important than others).

FWIW I think having good API overview pages is quite important, more so if the API itself is important of course.

**Comment by chrisdavidmills** [comment]
I'd really like to get this done at some point, totally agree on the rationale. Maybe we could get these done as P1 bugs, over the course of a little while? When you do the USes, tag them with P1...

**Comment by wbamberg** [comment]
@chrisdavidmills , I've filed issues for all these, as far as I can work out :).

**Comment by chrisdavidmills** [comment]
@wbamberg good work. I'll find them, and triage them so we can start dealing with these.

**Comment by jmswisher** [comment]
@chrisdavidmills and I talked about using the Writing Day at WTD Portland to attack these.

**Comment by chrisdavidmills** [comment]
@jmswisher yup, perfect fodder for that day.
