### ISSUE TITLE
Logpoints or Log Points

### ISSUE THREAD

**Issue by digitarald** [mdn/sprints#1538]
# Request type

Correction or update

# Details

We need to decide if we want to use `Logpoints` or `Log Points`.

Chrome and [VSCode](https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach) use Logpoints consistently and seems to have even convinced [Google Search](https://www.google.com/search?client=firefox-b-1-d&q=chrome+log+points):

<img width="412" alt="image" src="https://user-images.githubusercontent.com/8599/57797459-59646300-76ff-11e9-8bb1-beb240529939.png">

**Comment by janodvarko** [comment]
I vote for oneword (parity with VSCode and Chrome)

Honza

**Comment by chrisdavidmills** [comment]
I'd also vote for Logpoints. Consistency is always good, particularly in tech writing and UI design ;-)

And Logpoint is also consistent with other single word versus double word debates, and the general trend of recent years (website, sidebar, checklist)

**Comment by irenesmith** [comment]
I have already updated the content to use logpoints and changed the tip for last week's newsletter to use logpoints as well. I marked this as in review because I will check to make sure I didn't miss any instances of log points that need to be changed.

**Comment by irenesmith** [comment]
It seems that the changes were successful. I haven't found any references to log points, so I think we can close this.
