### ISSUE TITLE
Bug 1418372 - Essential data missing in the text: where to find the templates

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#154]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1418372

## Acceptance criteria

* https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Home_page is updated to clarify where to find the templates

**Comment by chrisdavidmills** [comment]
This is fixed, but not how you might expect. See my comments in the bug.
