### ISSUE TITLE
Page "https://developer.mozilla.org/en-US/docs/Web/Media/Overview" not found

### ISSUE THREAD

**Issue by cschuller** [mdn/sprints#1540]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
On the "[Web technology for developers](https://developer.mozilla.org/en-US/docs/Web )" page the link "[Overview of media technology on the web](https://developer.mozilla.org/en-US/docs/Web/Media/Overview)" results in a 404-page.

**Comment by chrisdavidmills** [comment]
I've removed this link for now, as the page isn't written yet.
