### ISSUE TITLE
Contradictory explanations about "let" variable hoisting

### ISSUE THREAD

**Issue by dcompcoder** [mdn/sprints#1542]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the JavaScript Reference for `let`, the first sentence under the heading "[Temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone)" states as follows:

> **let** bindings are created at the top of the (block) scope containing the declaration, commonly referred to as "hoisting"

However, in the chapter entitled "Grammar and types", under the heading "[Variable hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variable_hoisting)" there is a sentence that states as follows:

> In ECMAScript 2015, `let (const)` **does not hoist** the variable to the top of the block.

1. The two sentences appear to contradict each other. Are variables declared using `let` hoisted or not? I don't know which is correct.

2. What exactly is "`let (const)`"? Is this a typographical error? Should it be "`let` and `const`"?

Thank you for your help.

**Comment by Elchi3** [comment]
> The two sentences appear to contradict each other. Are variables declared using let hoisted or not? I don't know which is correct.

let and const are hoisted but not initialized, so you can't access them until they are evaluated. This is called the temporal dead zone. I've change the confusing/contradictory wording on both pages and I hope this is better now.

> What exactly is "let (const)"? Is this a typographical error? Should it be "let and const"?

Yeah, that was weird style. I've changed it to "let and const". 

Thanks for your report!
