### ISSUE TITLE
<meta> element docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1544]
See https://trello.com/c/xMWeNiAh/156-html-meta-element-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Remove `<meta http-equiv=set-cookie>` support](https://bugzilla.mozilla.org/show_bug.cgi?id=1457503) - documented appropriately.

**Comment by a2sheppy** [comment]
Updated the meta page and filed the PR https://github.com/mdn/browser-compat-data/pull/4342
