### ISSUE TITLE
<link> element docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1546]
See https://trello.com/c/6YAMGL3B/132-html-link-element-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] ["disabled=true" not working in link for stylesheet at initial load](https://bugzilla.mozilla.org/show_bug.cgi?id=1281135): documented appropriately. (see also [Intent to Implement and Ship: <link rel="stylesheet" disabled>, reflected by HTMLLinkElement.disabled](https://groups.google.com/forum/#!topic/mozilla.dev.platform/BdgNaChHnpY))

**Comment by a2sheppy** [comment]
For disabled=true, the update to content is done and BCD update is pending review. See the bug for details.
