### ISSUE TITLE
Proprietary -webkit-/-moz- feature docs tasks for Fx 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1548]
See https://trello.com/c/ylLyrwja/12-proprietary-webkit-moz-features-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Consider simplifying -moz-linear-gradient parsing](https://bugzilla.mozilla.org/show_bug.cgi?id=1547939) — documented appropriately
2. - [x] [Implement and Ship: CSSStyleSheet.rules, CSSStyleSheet.removeRule, CSSStyleSheet.addRule](https://bugzilla.mozilla.org/show_bug.cgi?id=1545823) — documented appropriately

**Comment by a2sheppy** [comment]
* Cleanup and updates to [CSSStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) overview page including additions for bug 1545823
* Documented [CSSStyleSheet.cssRules](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/cssRules)
* Documented [CSSStyleSheet.rules](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/rules)
* Documented [CSSStyleSheet.ownerRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/ownerRule)
* Documented [CSSStyleSheet.addRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule)
* Documented [CSSStyleSheet.removeRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/removeRule)
* Updated [CSSStyleSheet.deleteRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/deleteRule)
* Updated [CSSStyleSheet.insertRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule)
* Submitted [BCD PR 4380](https://github.com/mdn/browser-compat-data/pull/4380)

**Comment by a2sheppy** [comment]
Added info about the gradient change to Firefox 68 for developers. Since we have no documentation about the old prefixed versions of the these, that's all we really need.
