### ISSUE TITLE
CSS scroll-snap docs tasks for Fx 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1549]
See https://trello.com/c/oNitf87p/69-css-scroll-snap-level-1-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Update 'scroll-snap-type' to the latest specification and drop support for 'scroll-snap-type-x' and 'scroll-snap-type-y'](https://bugzilla.mozilla.org/show_bug.cgi?id=1312163) — documented appropriately
2. - [x] [Implement scroll-padding-* properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1373832) — documented appropriately
3. - [x] [Implement scroll-snap-margin-* properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1373833) — documented appropriately
4. - [x] [Implement scroll-snap-align property](https://bugzilla.mozilla.org/show_bug.cgi?id=1373835) — documented appropriately
5. - [x] [Enable the new scroll snap v1 by default on nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1531228) — documented appropriately
6. - [x] [Ship the new scroll snap](https://bugzilla.mozilla.org/show_bug.cgi?id=1544136) — documented appropriately
7. - [x] Write a hacks post about scroll snap to introduce the new spec, show a quick example or two, and annouce its release in Firefox.

**Comment by rachelandrew** [comment]
PR for compat data done and already merged https://github.com/mdn/browser-compat-data/pull/4172

**Comment by rachelandrew** [comment]
We have live examples for the properties which were not added to the pages, I guess it is now time to do so?

**Comment by chrisdavidmills** [comment]
Yeah, I think that sounds like a good idea.

**Comment by rachelandrew** [comment]
Examples are all now on pages, property pages have been checked to make sure they are correct in terms of the 68 release.

Found a missing example and made a PR to add it https://github.com/mdn/interactive-examples/pull/1361

Still waiting for the BCD to show up on these pages.

**Comment by rachelandrew** [comment]
@chrisdavidmills although these properties are being removed from Firefox in 68 it seems a bit soon to just drop them from the docs, do you think?

eg. https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type-x

I've made sure they have the deprecated header, is there anything else we should do about them?

**Comment by rachelandrew** [comment]
PR for data: https://github.com/mdn/data/pull/370

**Comment by rachelandrew** [comment]
Updated the two guides which referred to Firefox having the old spec.

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat

**Comment by chrisdavidmills** [comment]
Thanks @rachelandrew ! the guide updates look good, and I think you've taken the right approach in keeping the old property pages around for now and marking them as deprecated.

**Comment by rachelandrew** [comment]
Hacks post is here, didn't want to reiterate the entire guide, so provided a couple of examples and will link up the stuff on MDN once I put it into WP. 

https://docs.google.com/document/d/1ROtLu873LK4X2ApQFAaKDQEjsfGqywZ5s8SgOq8woH8/edit?usp=sharing

**Comment by chrisdavidmills** [comment]
@rachelandrew thanks for writing the hacks post. I've reviewed it, tested the demos, and added a few comments.

It looks like this work is mostly finished now; could you confirm this by going through the acceptance criteria, checking that the work items are done, and checking them off if so?

For the linked bugzilla bugs, can you go in to each one, leave a comment saying what docs have completed for each one, and then set each one to dev-doc-complete?

Also, make sure that an entry has been added to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68 to cover this work.

Thanks!

**Comment by rachelandrew** [comment]
I've edited the post, although you seem to be seeing something other to what I'm seeing in my examples so I'm a little confused.

**Comment by rachelandrew** [comment]
The bugs have all been updated and release notes written. I think other than actually publishing the post, this is all done.

**Comment by chrisdavidmills** [comment]
I think we're OK on the demos now.

For the release of the hacks post, we discussed this earlier thie week, and thought that since scroll snap is available to test now and has been available in Chrome for a while, that we could release to post sooner rather than later.

Would this week or the next work for you?

**Comment by rachelandrew** [comment]
Absolutely - just let me know if you are happy for me to put it into WP, and then it can go out whenever.

**Comment by chrisdavidmills** [comment]
Yes, please do. I'll let Havi know too.
