### ISSUE TITLE
CSS transforms docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1550]
See https://trello.com/c/9W1Z49lD/142-css-transforms-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [CSS transforms are not supported in indirectly rendered things such as masks, markers, patterns or clip-paths](https://bugzilla.mozilla.org/show_bug.cgi?id=1323962) — documented appropriately.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think this is just a line in the release notes to say this now works. We don't say anywhere in the docs, or in the compat data that this wasn't supported, there seem to just be a few duplicate bugs reporting it.

**Comment by chrisdavidmills** [comment]
@rachelandrew OK, WFM.
