### ISSUE TITLE
CSS lists docs tasks for Fx 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1551]
See https://trello.com/c/ihoF34ET/172-css-lists-level-3-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [[css-lists] Implement list numbering using a built-in 'list-item' counter](https://bugzilla.mozilla.org/show_bug.cgi?id=288704) — documented appropriately
2. - [x] [[css-lists] Implement the counter-set property](https://bugzilla.mozilla.org/show_bug.cgi?id=1518201) — documented appropriately
3. - [x] [Support ::marker pseudo-element](https://bugzilla.mozilla.org/show_bug.cgi?id=205202) — documented appropriately
4. - [x] [[css-pseudo] implement animation support for ::marker pseudos](https://bugzilla.mozilla.org/show_bug.cgi?id=1538618) — documented appropriately
5. - [ ] Write short hacks post about ::marker and what it can be used for

**Comment by rachelandrew** [comment]
PR for counter-set data https://github.com/mdn/data/pull/373

**Comment by rachelandrew** [comment]
PR for ::marker data https://github.com/mdn/data/pull/374

**Comment by rachelandrew** [comment]
"list numbering using a built in list-item counter" appears to be internal, rather than something developers need to be aware of.

I don't think there is anything additional to do for the animations of ::marker, looks like it was split out as a separate task in terms of implementation.

**Comment by chrisdavidmills** [comment]
Sounds fine to me. Just make sure the bugs are all set to dev-doc-complete and commented appropriately to say what the docs decision was.

**Comment by rachelandrew** [comment]
PR for `counter-set` compat data https://github.com/mdn/browser-compat-data/pull/4286

**Comment by rachelandrew** [comment]
Property page for `counter-set` https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set

**Comment by rachelandrew** [comment]
Added note to release notes, bug and marked dev-doc-complete on [288704](https://bugzilla.mozilla.org/show_bug.cgi?id=288704)

**Comment by rachelandrew** [comment]
- PR for a counter-set example https://github.com/mdn/interactive-examples/pull/1373
- Added note to bug [1518201](https://bugzilla.mozilla.org/show_bug.cgi?id=1518201) and set dev-doc-complete
- Updated page for [::marker](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker) and checked that compat data and so on was up to date
- Added note to bug [205202](https://bugzilla.mozilla.org/show_bug.cgi?id=205202) and set dev-doc-complete
- Added note to bug [1538618](https://bugzilla.mozilla.org/show_bug.cgi?id=1538618) and set dev-doc-complete

There are still some things waiting to be merged but otherwise the MDN side of things is in good shape.

**Comment by chrisdavidmills** [comment]
Great stuff!

**Comment by rachelandrew** [comment]
With a hacks post for this were you just thinking an announcement that this is exists and a couple of examples? I'm finding it hard to come up with anything spectacularly useful.

**Comment by chrisdavidmills** [comment]
If it's not really worthy of a whole hacks posts, then i'm happy for you to leave it. I guess it would be a bit short.

**Comment by rachelandrew** [comment]
yeah - I couldn't think up much. Maybe instead, in the next sprint I round up a few of these small things and write a post about "things you might miss" in 68, as there are a few bits and pieces that might make a more interesting post than one on their own?

**Comment by chrisdavidmills** [comment]
Yeah, that would be an nice idea; havi would love that

**Comment by rachelandrew** [comment]
ok cool - well I'll mark this as done and create a task for the next sprint to do that.
