### ISSUE TITLE
VisualViewport tasks for Fx68 release

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1552]
See https://trello.com/c/bqZxGmXt/96-viewport-handling-including-viewport-visualviewport-api-etc-fx-68 for the original trello card 

# Acceptance criteria

1. - [x] [Enable Visual Viewport API by default on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1512813) — documented appropriately.

**Comment by a2sheppy** [comment]
Submitted [BCD PR 4347)(https://github.com/mdn/browser-compat-data/pull/4347) noting that `VisualViewport` is now enabled by default on Android Firefox.
