### ISSUE TITLE
CSS values and units tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1553]
See https://trello.com/c/99AKTpVj/186-css-values-and-units-level-4-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [change 'currentColor' keyword to be a computed value (except for 'color' property)](https://bugzilla.mozilla.org/show_bug.cgi?id=760345) — documented appropriately.
2. - [x] [Fix support for the 'ch' length unit to match spec (fallback for no '0' glyph, vertical metrics)](https://bugzilla.mozilla.org/show_bug.cgi?id=282126) — documented appropriately.

**Comment by rachelandrew** [comment]
@chrisdavidmills Maybe I'm wrong but these seem to be internal changes that don't really get represented in our docs.

I added a line about the fallback size for when the size of the 0 glyph can't be calculated to the length page https://developer.mozilla.org/en-US/docs/Web/CSS/length

I'm not sure there is any change to make with regard to currentColor, but if you think there is let me know.

**Comment by chrisdavidmills** [comment]
That is a reasonable conclusion to come to; it happens sometimes. I am OK with that.

**Comment by rachelandrew** [comment]
ok - so I've now added these to the 68 for developers notes. Unless we can think of anything that needs documenting this is probably done.

**Comment by chrisdavidmills** [comment]
Again, set bugs to dev-doc-complete, and add a quick comment saying what docs work you did, even if is just a quick note in the Fx68 rel notes..

**Comment by rachelandrew** [comment]
- set dev-doc-complete on [760385](https://bugzilla.mozilla.org/show_bug.cgi?id=760345)
- set dev-doc-complete on [282126](https://bugzilla.mozilla.org/show_bug.cgi?id=282126)

**Comment by chrisdavidmills** [comment]
Perfect; we can close this now.
