### ISSUE TITLE
CSS shadow parts docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1554]
See https://trello.com/c/SUWuKgHm/176-css-shadow-parts-fx-68 for the original trello card

# Acceptance criteria

1. - [x] [Implement selector matching for `::part()`.](https://bugzilla.mozilla.org/show_bug.cgi?id=1545430) — documented appropriately
2. - [x] [Implement parsing support for the `::part()` pseudo.](https://bugzilla.mozilla.org/show_bug.cgi?id=1545425) — documented appropriately
3. - [ ] write short hacks post about this?

**Comment by rachelandrew** [comment]
Looks like exeboss has started on the data, their changes look fine, though I believe this is supported in Chrome so I have added a note. Either they could update the PR or we could merge and I will.

https://github.com/mdn/browser-compat-data/pull/4293

**Comment by rachelandrew** [comment]
This is also actually landing in 69, but nice to have a head start.

**Comment by rachelandrew** [comment]
Spec: https://github.com/mdn/kumascript/pull/1188
Data: https://github.com/mdn/data/pull/375

**Comment by rachelandrew** [comment]
The spec PR still needs merging for this one: https://github.com/mdn/kumascript/pull/1188

**Comment by chrisdavidmills** [comment]
> The spec PR still needs merging for this one: mdn/kumascript#1188

Merged; sorry for the delay!

**Comment by rachelandrew** [comment]
So I think the work in 68 is the parsing work, I don't think this is being enabled until 69 as far as I could tell. So this probably needs a revisit, by which point the various bits of data should be showing up on that page. I think most of the work is essentially done.

**Comment by jmswisher** [comment]
I'm assuming a Hacks post will be a separate issue.

**Comment by chrisdavidmills** [comment]
::part() doc also written:

https://developer.mozilla.org/en-US/docs/Web/CSS/::part
