### ISSUE TITLE
CSS containment docs tasks for Fx69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1555]
See https://trello.com/c/AQOpkXpT/3-css-containment-fx-68 for the original trello card

# Acceptance criteria

1. - [ ] [Let CSS Containment ride the trains to early beta](https://bugzilla.mozilla.org/show_bug.cgi?id=1532471) — documented appropriately

**Comment by rachelandrew** [comment]
@chrisdavidmills  This appears to be enabled all the way in 69 if I am reading this correctly. https://groups.google.com/d/msg/mozilla.dev.platform/lcGPwhu1Bcg/1S_vG8prAwAJ

**Comment by chrisdavidmills** [comment]
@rachelandrew ah yes, looks like it. So let's defer this until the Firefox 69 work. I've updated it as appropriate.
