### ISSUE TITLE
JS numeric separators docs task for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1556]
See https://trello.com/c/ZJ6IVDrd/206-numeric-separators-fx-68 for the original trello card.

# Acceptance criteria

1. - [ ] [Implement Numeric Separators](https://bugzilla.mozilla.org/show_bug.cgi?id=1421400) — documented appropriately

**Comment by a2sheppy** [comment]
This is another one that is only available in Nightly builds right now, so documenting it as part of Firefox 68 is not urgent.

**Comment by chrisdavidmills** [comment]
Closing this one; this is going to actually be enabled in Fx 70.
