### ISSUE TITLE
Promise-related docs tasks for Fx 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1557]
See https://trello.com/c/0SiTrQJ2/201-promise-related-bugs-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Implement Promise.allSettled](https://bugzilla.mozilla.org/show_bug.cgi?id=1539694) (See https://github.com/tc39/proposal-promise-allSettled for proposal.) — documented appropriately.
2. - [x] [Implement notifying of rejected promises (PromiseRejectionEvent)](https://bugzilla.mozilla.org/show_bug.cgi?id=1362272) — documented appropriately.

**Comment by wbamberg** [comment]
Please note that @MarkBennett has already contributed an interactive example for `allSettled()` over in https://github.com/mdn/interactive-examples/pull/1377.

**Comment by MarkBennett** [comment]
> Please note that @MarkBennett has already contributed an interactive example for `allSettled()` over in [mdn/interactive-examples#1377](https://github.com/mdn/interactive-examples/pull/1377).

I've linked to the sample on the MDN site now too:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by a2sheppy** [comment]
* Added an entry to Firefox 68 for developers mentioning the addition of `allSettled()`
* Updated the [allSettled()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) doc, adding the browser compat section etc.
* Submitted [BCD PR 4385](https://github.com/mdn/browser-compat-data/pull/4385) to add `allSettled()` information
* Added to Firefox 68 for developers

**Comment by a2sheppy** [comment]
So, the rejection events are in but disabled by default until 69. The docs are updated and the database for BCD has a patch reflecting all of that.

allSettled() has not been enabled by default yet. I've removed it from Firefox 68 for devs.
