### ISSUE TITLE
WebVTT docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1558]
See https://trello.com/c/POeJebj7/177-webvtt-api-fx-68 for original trello card. 

# Acceptance criteria

1. - [x] [[webvtt] Cue's positionAlign should be `auto` by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1528420) — documented appropriately. This was actually in 67, but didn't make it into the 67 tasks list.
2. - [x] [Support `cuechange` event](https://bugzilla.mozilla.org/show_bug.cgi?id=1548731) — documented appropriately.

**Comment by a2sheppy** [comment]
I've started some work on this; just some cleanup so far, will get into the meat of it in the morning.

**Comment by a2sheppy** [comment]
* Added sentence mentioning the default to the `positionAlign` entry in the [Properties section](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue#Properties) on the `VTTCue` page
* Cleaned up and improved [VTTCue()](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/VTTCue) page
* Rewrote the note in Firefox 67 for developers to be more detailed, and moved it from the DOM section to [Media, Web Audio, and WebRTC](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#Media_Web_Audio_and_WebRTC)

* Updated [TextTrack cuechange event](https://developer.mozilla.org/en-US/docs/Web/API/TextTrack/cuechange_event)
* Added `cuechange` event to [HTMLTrackElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTrackElement#Events)
* Created page for [HTMLTrackElement's cuechange event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTrackElement/cuechange_event) which simply embeds the contents of the article on `TextTrack`'s `cuechange` event
* Added `cuechange` event to `<track>` and `HTMLTrackElement` in BCD
* Submitted [BCD PR 4400](https://github.com/mdn/browser-compat-data/pull/4400) with `cuechange` updates
* Added an entry on Firefox 68 for developers
