### ISSUE TITLE
General DOM docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1559]
See https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-68 for the original trello card.

# Acceptance criteria

1. - [ ] [Make target=_blank on a/area elements imply rel=noopener by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1522083) (will be put behind a pref?) — documented appropriately. **HAS NOT LANDED FOR 68 AS OF JUNE 21**
2. - [x] [Consider adding support for customizing scrolling behavior with Element.focus](https://bugzilla.mozilla.org/show_bug.cgi?id=1374045) (`FocusOptions` / `preventScroll`) — documented appropriately.
3. - [x] [support `document.cookie` for all documents](https://bugzilla.mozilla.org/show_bug.cgi?id=144795) — documented appropriately.
4. - [x] [Support "noreferrer" for window.open()](https://bugzilla.mozilla.org/show_bug.cgi?id=1527287) — documented appropriately.
5. - [x] [Fennec and Geckoview fire resize events on page-load while Chromium does not](https://bugzilla.mozilla.org/show_bug.cgi?id=1528052) — documented appropriately.
6. - [x] [Remove MouseEvent.mozPressure.](https://bugzilla.mozilla.org/show_bug.cgi?id=1165211) — documented appropriately.
7. - [x] [Inconsistent popup-blocker behavior with document.addEventListener document.body.addEventListener onclick auxclick](https://bugzilla.mozilla.org/show_bug.cgi?id=1379466) — documented appropriately.

**Comment by jmswisher** [comment]
Created #1804 for the item that has not landed yet. Closing this one.
