### ISSUE TITLE
WebGL docs tasks for Fx69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1560]
See https://trello.com/c/mhsKKnNY/170-webgl-api-fx-68 for original trello card.

# Acceptance criteria

1. - [ ] [Implement webgl2 draft ext OVR_multiview2](https://bugzilla.mozilla.org/show_bug.cgi?id=1536672) — documented appropriately.

**Comment by Elchi3** [comment]
fwiw, this seems to be behind the `webgl.enable-draft-extensions` pref and doesn't ride the 69 train.

**Comment by chrisdavidmills** [comment]
OK. We'll close this for now in that case, and look at it again when it is enabled.
