### ISSUE TITLE
img.decode() API docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1562]
See https://trello.com/c/i9NyX7bR/141-imgdecode-api-fx-68 for the original trello card. 

# Acceptance criteria

1. - [x] [support the img.decode() API](https://bugzilla.mozilla.org/show_bug.cgi?id=1501794) — documented appropriately.

**Comment by a2sheppy** [comment]
Submitted [BCD PR 4345](https://github.com/mdn/browser-compat-data/pull/4345) to note Image.decode() was added to Firefox 68. It's already documented.
