### ISSUE TITLE
Resize Observer API docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1564]
See https://trello.com/c/ez5jtSt5/134-resize-observer-api-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] Landing page created for Resize observer API
3. - [x] ResizeObserver ref docs cleaned up as needed, examples added, etc. 
4. - [x] [Update ResizeObserver API to match the up-to-date spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1545239) — documented appropriately
5. - [x] [Implement Resize Observer API](https://bugzilla.mozilla.org/show_bug.cgi?id=1272409) — documented appropriately
6. - [x] Hacks post written about Resize Observer

**Comment by chrisdavidmills** [comment]
This is behind a pref in Firefox 68, not enabled till 69.

However, it is supported in Chrome since 64, so worth documenting.

**Comment by a2sheppy** [comment]
Worth noting that Joe Medley has already written a lot of this material. It should be given a quick once-over while putting htis together but should help speed things up.

**Comment by a2sheppy** [comment]
I'll start working on this today.

**Comment by a2sheppy** [comment]
I'm adding it to Experimental features for now; we'll add it to the 69 release doc plan.

**Comment by a2sheppy** [comment]
I've also created a quick outline at the main overview page location for the API, just to serve as a jumping-to point.

**Comment by chrisdavidmills** [comment]
Resize observer docs finished — see https://github.com/mdn/sprints/issues/1905#issuecomment-526296951
