### ISSUE TITLE
XMLDocument docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1565]
See https://trello.com/c/k2IHMWDY/202-xmldocument-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Drop XMLDocument.load() support](https://bugzilla.mozilla.org/show_bug.cgi?id=332175) — documented appropriately
2. - [x] [Remove XMLDocument's async IDL attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1328138) — documented appropriately

**Comment by a2sheppy** [comment]
These were already done.
