### ISSUE TITLE
Clear-Site-Data header docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1568]
See https://trello.com/c/nOqHAAgZ/181-clear-site-data-header-fx-68 for original trello card.

# Acceptance criteria

1. - [x] [Navigation to Clear-Site-Data page refreshes the current page](https://bugzilla.mozilla.org/show_bug.cgi?id=1548034) — documented appropriately

**Comment by a2sheppy** [comment]
* Submitted [BCD PR 4372](https://github.com/mdn/browser-compat-data/pull/4372) adding entries into the database for each directive, with `executionContexts` noted as being removed in Firefox 68
* Updated [Firefox 68 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68#HTTP)
