### ISSUE TITLE
CSP docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1569]
See https://trello.com/c/cp2ES11r/120-csp-general-enhancements-fx-68 for original trello c ard.

# Acceptance criteria

1. - [x] [Remove require-sri from the CSP-Module](https://bugzilla.mozilla.org/show_bug.cgi?id=1386214) — documented appropriately.

**Comment by a2sheppy** [comment]
* Submitted [BCD PR 4373](https://github.com/mdn/browser-compat-data/pull/4373) to both note this removed directive and to fix a structural error in the JSON
* Added to [Firefox 68 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68#HTTP)
