### ISSUE TITLE
Network Monitor tasks for Firefox 68 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1570]
See https://trello.com/c/dE8tJ7my/87-network-monitor-enhancements-fx-67 for original trello card.

# Acceptance criteria

1. - [x] [Response headers are in small case](https://bugzilla.mozilla.org/show_bug.cgi?id=1539423) — documented appropriately
2. - [x] [Block some specific resources in Network Panel across reloads](https://bugzilla.mozilla.org/show_bug.cgi?id=1151368) — documented appropriately
3. - [x] Resend option is like the edit and resent but just sends the same query without changes — documented appropriately
4. - [x] Resizable columns — documented appropriately
5. - [x] Copy action for HTTP data — documented appropriately

**Comment by irenesmith** [comment]
The following statement was added to the []() page:

If you noticed that the keys in the response header are all in lowercase, while the request headers keys are not, that is by design.

I considered going into the details about how it is required for HTTP/2 but decided against it because it might confuse the issue. Perhaps it should be added somewhere in the HTTP documentation?

**Comment by irenesmith** [comment]
For the item about blocking requests across reloads, I have requested more information in the related Bugzilla bug.

**Comment by irenesmith** [comment]
Added the following item to the description of the context menu items:

Resend

The Resend context menu option allows you to resend the request as it was originally sent with no changes made.

and added to the release notes as well:

You can now resend a network request without editing the method, URL, parameters, and headers, using the Resend command on the context menu.

Still need a bugzilla number!

**Comment by irenesmith** [comment]
Added:

You can also change the width of the columns to help make the information you are looking for easier to view. The Reset Columns command on the context menu also resets the width of the columns to the default values.

Made a video showing the feature and uploaded to YouTube.

Added the feature to the release notes as well but still need a Bugzilla bug for this.

**Comment by irenesmith** [comment]
Directly under the [headers section](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Headers) of the Network monitor request details page, I've added information about copying all or part of the headers as json.

Also added to the release notes for 68.
