### ISSUE TITLE
Storage inspector docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1571]
See https://trello.com/c/tYrUGqOG/211-storage-inspector-updates-fx-68 for the original trello card

# Acceptance criteria

1. - [x] [Users should be able to delete storage items via Backspace key](https://bugzilla.mozilla.org/show_bug.cgi?id=1522893) — documented appropriately.

**Comment by irenesmith** [comment]
This was added to the Storage inspector page:

In Firefox 68 and later, you can also delete local and session storage entries by selecting the item and pressing the backspace key.

And this to the release notes:
You can delete [local and session storage](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector#Local_storage_Session_storage) entries by selecting the item in the storage inspector and pressing the backspace key (bug 1522893).
