### ISSUE TITLE
RDM docs tasks for Firefox 68 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1573]
See https://trello.com/c/Sq0ZrM9l/118-responsive-design-mode-update-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Implement redesigned settings panel with edit functionality](https://bugzilla.mozilla.org/show_bug.cgi?id=1487857) — documented appropriately.
2. - [x] Added to release notes as appropriate

**Comment by irenesmith** [comment]
I have created new images for the UI and updated the text to match on [Responsive Design Mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode)

Please review and let me k now if I missed anything!
