### ISSUE TITLE
Remote debugging docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1574]
See https://trello.com/c/ZLneh5mV/10-new-remote-debugging-aboutdebugging-fx-68 for original trello card

# Acceptance criteria

1. - [ ] [[remote-dbg-next] about:debugging lists search webextensions by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1544372) — documented appropriately.

**Comment by irenesmith** [comment]
Closing this as a duplicate of [Sprints #1392](https://app.zenhub.com/workspace/o/mdn/sprints/issues/1392)
