### ISSUE TITLE
WebExtension blacklist Group Policy for Firefox 69 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1576]
See https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-68 for the original trello card.

# Acceptance criteria

1. - [x] [Missing Group Policy Option to blacklist ALL extension except whitelisted/allowed](https://bugzilla.mozilla.org/show_bug.cgi?id=1522823) — documented appropriately.
2. - [x] Added to release notes.

**Comment by irenesmith** [comment]
There doesn't seem to be any existing documentation framework for this issue on MDN. This is the existing page:

[Enterprise Deployment](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment)

The links on that page lead to support.mozilla.org, like this: [How is Firefox Enterprise different from normal Firefox?](https://support.mozilla.org/en-US/kb/firefox-enterprise-vs-normal-firefox)

**Comment by irenesmith** [comment]
This has been moved to Firefox 69

**Comment by irenesmith** [comment]
Removed this comment:

There is now a Group Policy option to blacklist all extensions except the ones that have been whitelisted ({{bug(1522823)}}).

from the release notes and will add it to the 69 release notes once the related bug has been resolved.

**Comment by chrisdavidmills** [comment]
* Note added to Fx 69 rel notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#Other_changes.
* Relevant bug (listed above) set to dev-doc-complete
