### ISSUE TITLE
WebExt bookmarks API docs tasks for Fx 68 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1578]
See https://trello.com/c/n7bNG8wh/210-bookmarks-enhancements-fx-68 for original trello card. 

# Acceptance criteria

1. - [x] [provide better error message when attempt is made to add bookmark folder to root folder](https://bugzilla.mozilla.org/show_bug.cgi?id=1512171) — documented appropriately.
2. - [x] Information added to 68 release notes

**Comment by irenesmith** [comment]
Here are the updates I made. I'm not entirely sure it needs to be formatted as a warning. Let me know if you would like to change that or make it a note instead. Also, please review my changes and let me know if I missed anything!

- Added the following warning to [Bookmarks API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks):

  Extensions cannot create, modify, or delete bookmarks in the root node of the bookmarks tree. Doing so causes an error with the message: "The bookmark root cannot be modified"

- Added the following warning to the [bookmarks.create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/create) method:

  If your extension tries to create a new bookmark in the bookmark tree's root node, it raises an error: "The bookmark root cannot be modified" and the bookmark won't be created.

- Added the following warning to [bookmarks.move](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/move) method:

  If your extension attempts to move a bookmark into the bookmarks tree root node, the call will raise an error with the message: "The bookmark root cannot be modified" and the move won't be completed.

- Added the following to warning [bookmarks.remove](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/remove):

  If your extension attempts to remove a bookmark from the bookmarks tree root node, the call will raise an error with the message: "The bookmark root cannot be modified" and the bookmark won't be removed.

- Added the following message to [bookmarks.removeTree](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/removeTree):

  If your extension attempts to remove a bookmark tree from the bookmarks tree root node, the call will raise an error with the message: "The bookmark root cannot be modified" and the bookmark won't be removed.

- Added the following message to [bookmarks.update](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/update):

  If your extension attempts to update a bookmark in the bookmarks tree root node, the call will raise an error with the message: "The bookmark root cannot be modified" and the bookmark won't be updated.

**Comment by irenesmith** [comment]
LGTM from Rob Wu on Bugzilla [1512171](https://bugzilla.mozilla.org/show_bug.cgi?id=1512171)
