### ISSUE TITLE
Write an overview page for the Console API

### ISSUE THREAD

**Issue by amygori** [mdn/sprints#1582]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The link to the Console API documentation from the [Web APIs page](https://developer.mozilla.org/en-US/docs/Web/API) results in a 404.

The valid link is: https://developer.mozilla.org/en-US/docs/Web/API/console

**Comment by wbamberg** [comment]
Thanks for filing!

The Console API is one of several APIs that's missing an "overview page", which is what the link there expects to be pointing to.

I filed https://github.com/mdn/sprints/issues/1537 to add all the missing overview pages so will attach this one to that.

**Comment by chrisdavidmills** [comment]
I've created a console API landing page - see https://developer.mozilla.org/en-US/docs/Web/API/Console_API

Can you review it please @a2sheppy ?

One thing I'm not sure about ishow to get it to show up on https://developer.mozilla.org/en-US/docs/Web/API

**Comment by a2sheppy** [comment]
I'm on it

**Comment by a2sheppy** [comment]
To get it to appear on the API list page, you need to add the "Console API" page to the GroupData file:

```
        "Console API": {
            "overview": [ "Console API" ],
            "interfaces": [ "console" ],
  ...
```

Since you're in there anyway might be worth fixing the name of the `console` interface, which is actually lowercase.

**Comment by a2sheppy** [comment]
Reviewed and minor copy edits made. Looks good!

**Comment by chrisdavidmills** [comment]
> To get it to appear on the API list page, you need to add the "Console API" page to the GroupData file:

Ah, cool, thanks for that. I've done it in https://github.com/mdn/kumascript/pull/1207. Can you give that a quick review too?

> Since you're in there anyway might be worth fixing the name of the console interface, which is actually lowercase.

When I first read this, I didn't believe you, but sure enough, it is like this in the spec ;-) Yup, I've fixed that too.

Thanks for the copy edits; much appreciated.

**Comment by a2sheppy** [comment]
Yeah, it’s a weird thing. The `console` interface is the lone exception in
all of the Web APIs — an interface whose name isn’t capitalized.

I wonder how the {{domxref}} macro does with it. I think it automatically
capitalizes. We may need to add code to do an exception if it doesn’t
already.

On July 29, 2019 at 7:50:21 AM, Chris Mills (notifications@github.com)
wrote:

When I first read this, I didn't believe you, but sure enough, it is like
this in the spec ;-) Yup, I've fixed that too.


Eric Shepherd
Senior Technical Writer
MDN Web Docs <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/
