### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging

### ISSUE THREAD

**Issue by Bartolomeus-649** [mdn/sprints#1583]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
![image](https://user-images.githubusercontent.com/7513795/57929831-9f165c80-78b4-11e9-98df-9dff0be6dd0c.png)
Source: [https://www.youtube.com/watch?v=hzwnR8qoz2I](https://www.youtube.com/watch?v=hzwnR8qoz2I&time_continue=6) and referenced in the [Debugging popups](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging#Debugging_popups) section.

This button ![image](https://user-images.githubusercontent.com/7513795/57929242-0c28f280-78b3-11e9-9db5-77ab39649faa.png) appear at the top of the GUI for the add-on debugger in many of the videos on this page, and in some of them this button is used/clicked as part of the operation/task being illustrated.
But that button does not appear in any of the screen shots of the Add-On debugger on the page, and as far as I can tell it is not present in the latest version of the add-on debugger in FF.
There is no textual explanation of this buttons role or what it used for.
All the other steps done in the videos are possible to do with the GUI currently available.

There need to be some clarification what that button does and how to get it in the current version of FF.
- Are there any assumptions made that need to be clarified and pointed out?
- Any setting that need to be in a specific way?
- Any specific criterias that must be met by the add-on you are debugging to get the button?
- Anything else that might affect whether this button is visible or not?

**Comment by jmswisher** [comment]
That page has moved to https://extensionworkshop.com/documentation/develop/debugging which is now maintained by the Add-ons team. It longer contains the videos showing that button, which was eliminated from the UI some time ago.
