### ISSUE TITLE
Do SSR as part of the document publish task

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#1587]
# User story
As an MDN engineer, I want to pre-render (pre-SSR) document HTML pages every time they are edited, saving them to S3, so that they are available to users more quickly.

Issue #1460 investigated this. This new story is to implement it. After talking with Ryan, we think we'll render HTML documents for all of our most important locales that do not have translations of their own.

# Acceptance criteria

- The publish task has been modified to generate html files as well as json files and to store them to S3
- The S3 bucket has been configured (if it isn't already) so that 404s for HTML documents are redirected to Kuma.

**Comment by davidflanagan** [comment]
@escattone and I had a couple of long conversations about this issue and decided to put it off for now.

The blocking issue is that it is not enough to pre-render each time a document is rendered. We would also have to re-render everything any time we deploy a UX change in our frontend code. So until we have a system in place that allows us to trivially rebuild all the document as part of the deploy process, it doesn't make sense to work on pre-rendering after content changes.

It may well still make sense to pursue this later where we pre-render all documents to S3 on every deploy (or every deploy that touches the frontend, perhaps) and then re-render individual documents on every edit.  (Note that this would not necessarily have to involve kumascript rendering on deploy: it would probably be fine to assume that the HTML in the database is up-to-date when we deploy.)

For now, maybe we can just increase the CDN cache time to get the benefits of pre-rendering even if it means that UX changes won't always show up for a few hours after a deploy.

**Comment by jmswisher** [comment]
So, should this issue be "parked" and worked on in the future? Or just closed?

**Comment by escattone** [comment]
@jmswisher I would say it should be "parked", although I wouldn't mind if we just closed it. As David suggested, I think that once we deploy CDN cache invalidation (https://github.com/mozilla/kuma/pull/5472), we'll be able to significantly increase the CDN cache time, which would, in turn, significantly reduce the need for this.

**Comment by jmswisher** [comment]
Closing; reopen or create a new issue if this work turns out to be needed.
