### ISSUE TITLE
Remove jQuery from beta pages, port the minimal amount of required JS

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#1593]
# User story
As an MDN engineer, I want to reduce the amount of JS running on MDN pages to minimize maintenance and improve performance. 

In particular, I want to remove our dependency on jQuery.

This is a follow up to issue #1309. The team has agreed on a JavaScript strategy for the beta site, and this user story is for executing on that strategy. Basically: rip out all the old JS and port and put back just the parts that are needed.

This will involve fixing things (like soft hypenation) that are currently broken on the beta site. And, hopefully, it will improve site performance by reducing the amount of JS that runs.

# Acceptance criteria

- jQuery is no longer used on beta pages
- the JS modules that are loaded into beta pages are integrated with React and bundled with webpack
- the JS modules on the beta pages are documented and we know exactly why we're running them.

**Comment by jmswisher** [comment]
@davidflanagan This issue never got added to the tracking spreadsheet, so it wasn't on my radar. Will it be worked on in Lena Horne?
