### ISSUE TITLE
contenteditable docs are incorrect

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1596]
See https://github.com/mdn/interactive-examples/pull/1333: our docs say it's incorrect to use [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) without a value:

> This attribute is an enumerated one and not a Boolean one. This means that the explicit usage of one of the values true, false or the empty string is mandatory and that a shorthand like <label contenteditable>Example Label</label> is not allowed. The correct usage is <label contenteditable="true">Example Label</label>.

But it seems our docs are wrong, and it is correct to use it without a value:

>  Attributes can be specified in four different ways:
>      1. Empty attribute syntax
>      Just the attribute name. The value is implicitly the empty string.

(https://www.w3.org/TR/html/syntax.html#elements-attributes)

> The contenteditable content attribute is an enumerated attribute whose keywords are the empty string, true, and false. The empty string and the true keyword map to the true state. The false keyword maps to the false state. In addition, there is a third state, the inherit state, which is the missing value default (and the invalid value default).

(https://www.w3.org/TR/html/editing.html#element-attrdef-global-contenteditable)

**Comment by wbamberg** [comment]
@chrisdavidmills , we we discussed, I have updated the page: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable$compare?locale=en-US&to=1599970&from=1540016 . Let me know if it makes sense to you.

**Comment by chrisdavidmills** [comment]
Reviewed, and yup this looks fine. Nice work @wbamberg !
