### ISSUE TITLE
text direction tutorial

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1598]
we need internationalization content on text direction

We should also consider tutorials on 
character sets, units of measure (currency, °C/°F, km/miles, etc.), localized, time and date formats, keyboard layouts, text directions

**Comment by rachelandrew** [comment]
@chrisdavidmills where would this live on the site. It's touched on in various layout guides (grid, flexbox etc.) and also logical properties and values.

**Comment by chrisdavidmills** [comment]
@rachelandrew for the text direction stuff, I was thinking maybe add some content to https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions ?

Or if it is likely to be an entire tutorial, maybe just put it under the main Web/CSS page?
