### ISSUE TITLE
Remove all "yes" lines in <a> BDC

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1599]
html.elements.a for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a does not need to have lines for name, href, or target. These have always been supported and are supported everywhere, so don't need to have their own lines. 

rel, rev, charselt, hreflang and name can also be removed. Those are supported everywhere, so their presence makes the table more overwhelming.

**Comment by jpmedley** [comment]
I would state that explicitly somehow. This seems obvious to us, but see potential for people just learning web development to be confused by the lack of data about individual members.

**Comment by jmswisher** [comment]
This brings up a larger issue, which should probably be discussed in [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (attn: @Elchi3). The BCD for most HTML elements (and probably most of everything on MDN) now contains explicit items for each member, even when they're all the same, or mostly the same. 

In the [discussion about replacing "basic support" with the feature name](https://discourse.mozilla.org/t/getting-rid-of-basic-support-in-compatibility-tables/36240), "squashing" rows was determined to be out of scope for that change. Having lots of redundant rows is an issue for lots of elements, not just `<a>` (e.g., [`<body>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body)). 

Deleting info from the BCD store is probably not desirable. In terms of how it's displayed on MDN, there's two issues: (1) figuring out how to hide redundant rows, and (2) providing an explanation for the first row like "All features of `<a>` not mentioned below".

**Comment by Elchi3** [comment]
I agree with Joe, not everyone knows what has been supported since forever, so we should keep these rows. Implementing row squashing to better summarize this is not currently planned.
