### ISSUE TITLE
Bug 1461951 - PushManager.subscribe() csrf missing from all examples.

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#160]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1461951

## Acceptance criteria

1. Add suitable warnings to the relevant pages.

**Comment by irenesmith** [comment]
As I have no ability to edit the push manager cookbook examples, I have added a warning and a link to appropriate articles to the top of the PushManager API page.

**Comment by jmswisher** [comment]
@irenesmith @chrisdavidmills Should this issue be kept open, pending a response from Jan Klopper in the Bugzilla bug? Or closed, with a new issue to be created once there's more info?

**Comment by chrisdavidmills** [comment]
I'd say keep it open for now, as more work probably needs doing here. 

We should be getting control of the Service Worker cookbook soon (which is what I think he is talking about), so we should be able to do something about it then.

**Comment by irenesmith** [comment]
Adding to this sprint (Fantasia). I have to follow up on a request from Chris for some sample code. That is all this bug is waiting for in order to be done but it's been sitting around for a long time. I am not going to close the Bugzilla bug until I know what is going to happen with it.

**Comment by chrisdavidmills** [comment]
I'd put this back to the icebox for now, and choose another P1 bug to do in the next sprint, unless you feel like you know what to do to write this bit of isolated code (I certainly don't ;-) ). What we need is a proper full plan for improving service worker and push api docs, with research and bells and whistles. I've aded that to my to do list for actioning sometime soon.

**Comment by irenesmith** [comment]
Following advice from Chris, I have moved this out of the Fantasia sprint.

**Comment by irenesmith** [comment]
The associated Bugzilla bug has been closed, so closing this issue as well.
