### ISSUE TITLE
単純ヘッダー and simple headers are broken links

### ISSUE THREAD

**Issue by znz** [mdn/sprints#1600]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`単純ヘッダー` in https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Directives and `simple headers` in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Directives are broken links.

**Comment by wbamberg** [comment]
Thanks for filing! I think these should be fixed now (the link was pointing to "simple_headers" not "simple_header").
