### ISSUE TITLE
checkbox removed from about:debugging Firefox 68 (Irene)

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1602]
The "Enable add-on debugging" checkbox has been removed from the about:debugging page. Need to create new screenshots that don't show this checkbox as well as remove the section that discusses it.

# Acceptance criteria
- [x] New screenshots created without checkbox

**Comment by Rob--W** [comment]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1544813, only https://developer.mozilla.org/en-US/docs/Tools/about:debugging was mentioned.

The following page should however also be updated: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging

It may make sense to preserve the current content in a new article "Debugging (before Firefox 68)" (we already have a ["Debugging (before Firefox 50)"](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging_(before_Firefox_50))), and then update the "Debugging" article to match Firefox 68's behavior.

**Comment by irenesmith** [comment]
All images on the aboug:debugging page show the correct version of the page without the checkbox.
