### ISSUE TITLE
Houdini: API landing page: CSS Paint API

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1614]
Landing page for the CSS Paint API
https://drafts.css-houdini.org/css-paint-api-1/

Acceptance Criteria:

The following sections are complete:

[ ] -  Overview
[ ] -  Interfaces
[ ] -  Specifications
[ ] -  Browser compatibility
[ ] -  See Also

**Comment by jmswisher** [comment]
[CSS Painting API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API) landing page
