### ISSUE TITLE
Prepare integration tests for switch of `beta` to main

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1630]
# User story
As a developer, I need to run integration tests against the stage and production instances of MDN for the `beta` (soon to be main) domain endpoints as well as the `wiki` endpoints. Currently, the integration tests assume they're testing the `wiki` endpoints, so there will be a large number of failures when run against the `beta` endpoints (after they become the main endpoints).

# Acceptance criteria

- [ ] The integration tests successfully run against both the `wiki` and `beta` (main) domain endpoints.

**Comment by tobinmori** [comment]
work folded into sprints #1637
