### ISSUE TITLE
About HTTP document content

### ISSUE THREAD

**Issue by fed-gren** [mdn/sprints#1631]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/HTTP

I couldn't understand what was included in the link above.
```
Though often based on a TCP/IP layer, it can be used on any reliable transport layer; 
that is, a protocol that doesn't lose messages silently, such as UDP.
```
As far as I know, UDP is unreliable protocol. Is the contents of this document wrong?

**Comment by chrisdavidmills** [comment]
I had a go at making this bit easier to understand. Let me know if it's better now.

**Comment by chrisdavidmills** [comment]
I think we can close this. We've had no reply in a week, and I'm pretty sure this is correct.
