### ISSUE TITLE
Prepare kuma/infra for switch of `beta` to main

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1637]
# User story
As a developer, I want to prepare MDN Web Docs for the switch of `beta` to main. In other words, the new React-based, read-only endpoints now available on `beta.developer.mozilla.org` become the main endpoints available on `developer.mozilla.org`.

# Acceptance criteria

- [ ] An approved Kuma PR that when merged and deployed will effectively make the current `beta` endpoints the main endpoints, and thereafter the current main endpoints will only be available via the `wiki` domain.
- [ ] The integration tests successfully run against the new views.
- [ ] A Kumascript and/or Infra PR that ensures that Kumascript makes API calls (e.g., the `$history` and `$revision` endpoints) via the `wiki` domain to avoid redirects
- [x] The master branch of https://github.com/mdn/infra configures the SSR deployment up to at least 10 pods (it is currently 4).

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/5639 and https://github.com/mdn/infra/pull/283

**Comment by escattone** [comment]
See https://github.com/mdn/infra/pull/284

**Comment by tobinmori** [comment]
was pushed to stage.

**Comment by jmswisher** [comment]
Done!
