### ISSUE TITLE
Render body HTML for <video> from stumptown JSON

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1638]
From the Stumptown JSON, produce rendered HTML for the "body content" of the MDN page for the `<video>` HTML element.

This would be, _more or less_, what you see at view-source:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video?raw&macros.

It's not going to be exactly the same. For example, the Kuma source for live samples expects further post-processing by JavaScript running in the Kuma page (https://github.com/mozilla/kuma/blob/master/kuma/static/js/wiki-samples.js). In general, anywhere there's client-side Kuma JS that the page expects to run, we have to think about whether and how to replicate that outside Kuma.

There is some room for manuva about how much of the MDN page needs to be included, but as a first attempt, it should include:

* all the main prose sections (attributes, usage notes, accessibility, etc)
* interactive example
* all examples, including functional live samples
* the "technical summary" box, as far as that's possible given the data we have for it
* BCD table

After that we'll see what it looks like.

For now it will be implemented as a standalone CLI tool, using Node.

# Acceptance criteria

We have a tool that can render the above HTML from stumptown JSON for the `<video>` element.

**Comment by jmswisher** [comment]
@wbamberg @ddbeck Can this epic be closed?

**Comment by wbamberg** [comment]
Yes.
