### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Cryptography_functions

### ISSUE THREAD

**Issue by jpfreyen** [mdn/sprints#1640]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details

The url 

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Cryptography_functions 

doesn't have any information on the functions and the MXR links for each function is broken.  It would be nice to at least get descriptions of these functions, is there a timeline this will get fixed?

Thank you!

**Comment by estelle** [comment]
Not open web, so MDN team is not likely to address.

**Comment by jpfreyen** [comment]
I don't quite get the answer.  Will all the methods listed get documented?  Be nice to have a fully documented API.

**Comment by jmswisher** [comment]
@jpfreyen The focus of the MDN staff team is on documenting web standards, rather than Mozilla-internal projects. Updating/completing this article would be up to either the NSS engineering team, or interested volunteers.
