### ISSUE TITLE
page "https://developer.mozilla.org/zh-CN/docs/Web/API/cn/DOM/document" is missed

### ISSUE THREAD

**Issue by yonghu6666** [mdn/sprints#1646]
The URL in the title is Missed. It's a link from page "https://developer.mozilla.org/zh-CN/docs/Web/API/Window". See the Snapshots.
![image](https://user-images.githubusercontent.com/5063955/58222584-1c285280-7d49-11e9-994f-2eba0e712964.png)

**Comment by chrisdavidmills** [comment]
The link was pointig to the wrong place. I've fixed it now. 

Thanks for reporting it!
