### ISSUE TITLE
https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Operators/Operatori_Aritmetici

### ISSUE THREAD

**Issue by Terestian87** [mdn/sprints#1647]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
the word "incremento" is a title and shoud inherit the different font like other titles <was looking for it couple of minute>
![Cattura](https://user-images.githubusercontent.com/50947015/58240465-50047780-7d4b-11e9-9827-3fd27d313734.JPG)

**Comment by chrisdavidmills** [comment]
Fixed! Thank you for reporting this.
