### ISSUE TITLE
Bug 1459745 - Docs for <bdi> are misleading

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#165]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1459745

**Comment by jmswisher** [comment]
Removing from Sprint 2

**Comment by irenesmith** [comment]
Just checked on why this is still open and apparently the work has been done to clarify the purpose of the <bdi> element.

**Comment by chrisdavidmills** [comment]
Cool, closing then. Thanks Irene!
