### ISSUE TITLE
Fix pages with earlier revisions displayed

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1653]
# Acceptance criteria

- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1551999

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by tobinmori** [comment]
Parking this until we can determine a way to access the Prod DB for testing/dev purposes.

**Comment by peterbe** [comment]
Time was not nice to us. It was a horrendously tricky thing to debug too. We can only hope for a Yari future where the source of truth is in git and not a RDBMS system that has some sneaky bug that we can never reproduce. Also, the underlying content has changed too much.
