### ISSUE TITLE
add article tags to page content

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#1655]
# User story
As an MDN writer, I want the tags I add to documents to appear in React version of the site, so that they contribute to SEO.

Tags will continue to display as they always have on the wiki.d.m.o version of the site. I took them out of the readonly version because I didn't think they were valuable to readers.

This user story is to put them back. This will require a backend change to the document API as well as a trivial change to the front end.

# Acceptance criteria

- tags appear on document pages once again.

**Comment by tobinmori** [comment]
We do not display tags on the React side. Closing.
