### ISSUE TITLE
Top level API page needs work

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1656]
If you go to https://developer.mozilla.org/ and select "web technologies" then click the web API header link, you get to

https://developer.mozilla.org/en-US/docs/Web/Reference/API

This page needs work both in terms of content and UX.

**Comment by jmswisher** [comment]
Or it could be replaced in most cases with https://developer.mozilla.org/en-US/docs/Web/API which has its own issues, but probably does a better job of getting users to what they're looking for.

**Comment by jmswisher** [comment]
And let's not forget about https://bugzilla.mozilla.org/show_bug.cgi?id=1387131 which I consider a major embarrassment, but which is prioritized as a P5.
