### ISSUE TITLE
https://developer.mozilla.org/ko/docs/XMLHttpRequest

### ISSUE THREAD

**Issue by alattalatta** [mdn/sprints#1657]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The doc's URL is of old format. Please move it under `/ko/docs/Web/API`. (/ko/docs/Web/API/XMLHttpRequest)

**Comment by jmswisher** [comment]
Done. Thanks for reporting!
