### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

### ISSUE THREAD

**Issue by sstenchever** [mdn/sprints#1658]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The language displayed on this page is not in English even when the English language is selected. See the explanation next to repeat() in the screenshot...

<img width="1431" alt="Screen Shot 2019-05-25 at 7 35 17 PM" src="https://user-images.githubusercontent.com/30671118/58375586-41bd8380-7f24-11e9-9ea4-7715d2a8030a.png">

**Comment by alattalatta** [comment]
I've reverted the last edit, so now the doc is in English again.

**Comment by jmswisher** [comment]
Thanks @alattalatta !
