### ISSUE TITLE
404 Link to missing extension on MDN page

### ISSUE THREAD

**Issue by cpriest** [mdn/sprints#1659]
# Request type
- [X] Correction or update

# Details
The MDN web page [Measuring add-on startup performance](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Measuring_add-on_startup_performance) has this link to [About Startup](https://addons.mozilla.org/en-US/firefox/addon/about-startup/) which is no longer available.  

I looked for a suitable replacement to recommend but came up empty-handed.

**Comment by irenesmith** [comment]
Determining whether there is another extension to refer to here.

**Comment by irenesmith** [comment]
Sent a message to Mike Conca last week. Following up today (Monday, 6/10)

**Comment by irenesmith** [comment]
On reply from Caitlin Neiman, I have archived the article as it is out-dated.
