### ISSUE TITLE
TinderBox link is broken

### ISSUE THREAD

**Issue by fgarbin** [mdn/sprints#1662]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
The link TinderBox (https://developer.mozilla.org/en/Tinderbox) in page https://developer.mozilla.org/pt-BR/docs/Mozilla/Developer_guide/Intrucoes_Build, is broken, redirected to Not Found page (https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Tinderbox).

**Comment by chrisdavidmills** [comment]
I believe Treeherder is the replacement for Tinderbox, so I've changed the pagte to link to it instead. Let me know if that sounds ok.

**Comment by fgarbin** [comment]
> 
> 
> I believe Treeherder is the replacement for Tinderbox, so I've changed the page to link to it instead. Let me know if that sounds ok.

Thanks @chrisdavidmills. It is ok.
