### ISSUE TITLE
Differing browser alignment of "Developer info" link on Firefox 67 changelog

### ISSUE THREAD

**Issue by wisniewskit** [mdn/sprints#1663]
As per https://github.com/webcompat/web-bugs/issues/31777, desktop Firefox aligns the "Developer information" links to the right of the screen on the [Firefox for Android 67 release notes](https://www.mozilla.org/en-US/firefox/android/67.0/releasenotes/) page, while Chrome aligns them on the left. This is caused by the link having a CSS property applied to it on Firefox which does not apply on Chrome: `justify-content: end`.

**Comment by a2sheppy** [comment]
Since this is a mozilla.org issue, not an MDN one, and there's a link to a Bugzilla bug for it provided above, this is closed.

**Comment by wisniewskit** [comment]
Oops, pardon my brainfart and the spam.

**Comment by ioana-chiorean** [comment]
@a2sheppy where is the bugzilla link?
Now both the webcompat issue and this one are closed so i guess there is no tracking for the issue at the end of the day. Should I fill a bug as I am the initial reporter?

**Comment by wisniewskit** [comment]
@ioana-chiorean, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1555469

**Comment by ioana-chiorean** [comment]
Awesome!! I did not saw it linked before
