### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics

### ISSUE THREAD

**Issue by chiamakaikeanyi** [mdn/sprints#1664]
# Request type

- [x] Correction or update

# Details

I noticed a typographical error in the documentation. Instead of useful, userful was written.
I hope this gets fixed.

<img width="723" alt="Screen Shot 2019-05-27 at 8 40 01 PM" src="https://user-images.githubusercontent.com/22685689/58436971-cdb7e280-80bf-11e9-897e-fc8aa614e0a5.png">

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
