### ISSUE TITLE
Let users opt in to a default browser set

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1666]
# User story
Let users opt in to a default browser set

# Acceptance criteria

- [ ] the banner that notifies them about a new BCD feature lets them opt in to it
- [ ] opt in is only shown to beta user

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by schalkneethling** [comment]
To clarify after the initial discussion, the idea here is as follows:

We update the notification banner to have an enable button

![enable](https://user-images.githubusercontent.com/10350960/59330089-c3692b80-8cf0-11e9-864f-53947fca4d83.png)

Perhaps a checkbox as well?

![enable-checkbox](https://user-images.githubusercontent.com/10350960/59330510-f65fef00-8cf1-11e9-80e0-46eafe29506f.png)

One idea was that, once the user clicks `enable`, we scroll to the top of the page and load in(With React we do not have to reload the entire page) the feature. Now here, we need to somehow tell the user how they go about disabling the feature if they do not find it useful.

One idea is to add a message just below the support bar:

![disable-header](https://user-images.githubusercontent.com/10350960/59330644-5191e180-8cf2-11e9-8548-b0c0460e0675.png)

Something like, "Thank you for enabling browser sets. To disable the features, go to the browser sets section of your profile page."

Alternatively, we could add a button inside the browser set "sidebar":

![disable-header-2](https://user-images.githubusercontent.com/10350960/59330684-6bcbbf80-8cf2-11e9-8a20-c758dcb57011.png)

The problem with this second option, for me, is that it could be unclear whether it refers to the browser set, or the entire feature.

Another option is to have different messaging that points the user back to the compatibility table to disable the feature:

![disable-header-alternate](https://user-images.githubusercontent.com/10350960/59331389-21e3d900-8cf4-11e9-9d49-21f19ddee3c3.png)

Something like, "Thank you for enabling browser sets. You can disable the features by unchecking the box above the compatibility table."

![bcd-on-top-disable](https://user-images.githubusercontent.com/10350960/59331405-2c05d780-8cf4-11e9-8ecd-3f25d5460c47.png)

**Comment by schalkneethling** [comment]
For this iteration, we also need to update the language in the below as the user will get a default set, and not a configurable set.

![enable](https://user-images.githubusercontent.com/10350960/59343703-bce8ad00-8d0c-11e9-94b1-414e28ec51a8.png)

**Comment by atopal** [comment]
This is taking it way too far for an MVP that's supposed to be seen only by beta users. Let's just do the opt-in as initially discussed. When we ask beta users to try this out we can document the opt-in, and let them know there is no opt-out for now. And one sprint after this we implement the opt-in and opt out as specced.

**Comment by atopal** [comment]
Agreed re the language change
