### ISSUE TITLE
<img> and <picture> need to be updated to point to new image type guide

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1670]
Now that we have a good source of information on MDN for image formats, the pages for the image-related tags should be updated to point to that information instead of Wikipedia.

## Acceptance criteria

- [x] All references to other older pages about image formats have been replaced
- [x] Removed all in-place descriptions and replaced with either links or transclusion of the new content

**Comment by a2sheppy** [comment]
Oops, not done after all.
