### ISSUE TITLE
Suggestion to stop linking to W3C specs for HTML/DOM

### ISSUE THREAD

**Issue by mozfreddyb** [mdn/sprints#1671]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
[As of today](https://www.w3.org/blog/news/archives/7753), the W3C and WHATWG will publishjoint standards and stop publishing conflicting standards for HTML and DOM.

It would be nice if MDN stopped linking to the HTML/DOM standards of W3C and link to the WHATWG Living Standard for the respective articles.

Example article: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Specifications

**Comment by a2sheppy** [comment]
Agreed.

**Comment by mozfreddyb** [comment]
The example article listed above still shows the original behavior.
I guess there's a reason why you link to HTML (WHATWG), HTML5 (W3C) and HTML 4.01, but I don't understand it.
What else, besides a joint public statement from W3C & WHATWG is needed to make everyone converge on just one standard? :-)

Thanks for your time!

**Comment by chrisdavidmills** [comment]
@mozfreddyb sorry, I should have explained this better. We have started a workstream to include spec urls for all the features covered on mdn over in the [browser-compat-data](https://github.com/mdn/browser-compat-data). Once that is done, we'll automate generation of the spec tables from that data, so the tables will just list the one canonical URL that devs are interested in (1 should work in most cases), and not the confusing mess that you see in all too many cases.

**Comment by mozfreddyb** [comment]
Thanks @chrisdavidmills! Appreciate the quick response
