### ISSUE TITLE
Template Literals documentation appears in Russian even though I have English selected as my language

### ISSUE THREAD

**Issue by JoshuaWalsh** [mdn/sprints#1673]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
When I view [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) with my language set to en-US, it seems to be in Russian. Other pages appear correctly in English.

Here's a screenshot including the address bar and the language dropdown:

![image](https://user-images.githubusercontent.com/2290576/58534625-20fc7300-822f-11e9-82f2-b6154d281a2b.png)

The Google Cached version of the page from 4 days ago appears in English.

**Comment by chrisdavidmills** [comment]
Argh! That's because someone incorrectly put a Russian translation over the top of the English version. I've reverted it now, so you should see the English text again.

Thanks for reporting this.
