### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

### ISSUE THREAD

**Issue by inetphantom** [mdn/sprints#1674]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The example for `datetime-local` is wrong (the calculation of leap years is a bit more tricky than just `%4`) It could be solved using JavaScript's Date() instead of manual/hardcoded validations.

**Comment by inetphantom** [comment]
You could use https://stackoverflow.com/questions/8175521/javascript-to-find-leap-year as example

**Comment by chrisdavidmills** [comment]
Hi there!

I am glad you've pulled me up on this. I ended up opting for an approximation rather than researching how to do it properly ;-)

I've updated this code so it is now correct.

**Comment by inetphantom** [comment]
NIce Thanks!
