### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by raedon707** [mdn/sprints#1675]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

when dividing a number with '0' it gives infinity. which is mathematically wrong, it should give 'undefined' and not 'infinity'.
like:-
1/0 = Infinity ----> (i 
and 
-1/0 = -Infinity -----> (ii

or
1/0 = infinity --------> (iii
and 
2/0 = infinity ---------> (iv

from eq i and ii
Infinity = -Infinity
-Infinity should be equal to -Infinity which is wrong, and impossible

or from eq iii and iv
1 = 2 
which is also mathematically wrong. so, we can't declare 'n/0' as infinity

but the opposite is quite different.
like if we divide a number "n" with "Infinity" it will always give 0.
n/Infinity = 0
and 
n/(-Infinity) = 0

since, "0" have no sign, it's neutral.
so,
"n/0" should be "undefined".

**Comment by chrisdavidmills** [comment]
@raedon707 can you comment on what page this problem is found on?

**Comment by Elchi3** [comment]
No answer. Closing.
