### ISSUE TITLE
https://developer.mozilla.org/ko/docs/HTML/Block-level_elements

### ISSUE THREAD

**Issue by alattalatta** [mdn/sprints#1677]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The doc is under an old URL. Please move the page to `/ko/docs/Web/HTML/Block-level_elements`.

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
