### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Document/location

### ISSUE THREAD

**Issue by satsukikorin** [mdn/sprints#1679]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On https://developer.mozilla.org/en-US/docs/Web/API/Document/location the Example shows 
```
dump(document.location);
```
Since ```dump``` is a very non-standard command, I recommend revising to use something standard like ```console.log``` instead.

**Comment by chrisdavidmills** [comment]
Yes, I totally agree. Updated.

Thanks for reporting!
