### ISSUE TITLE
Make MDN more reliable by separating the service of file attachments, which uses AWS EFS, from the rest of MDN.

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#168]
#### General
From experience we know that a majority of the pods for the `web` deployment within the MDN Kubernetes cluster are required simply to handle the requests for file attachments (e.g., `/files/2767/hut.jpg`). The actual file attachments are stored within an AWS EFS instance, so any pod serving a request for a file attachment depends upon EFS.
#### Problem
We recently experienced downtime which seemed to be due to significantly increased latency with our EFS instance. The increased latency caused the pods that were serving file attachments to take longer, which in turn did two things. First, it forced more and more pods to occupy themselves with serving the load of incoming requests for file attachments, rather than MDN documents. Second, more of the pods trying to serve file attachments, since they were waiting on EFS, started to fail their `liveness` and `readiness` probes, which then made matters even worse since those pods were restarted or removed from the incoming traffic. In the end, this vicious cycle left a dwindling number of pods available to handle actual MDN document requests, and users began to see huge page-load times.
#### Proposed Solution
This current vulnerability of MDN can be mitigated by serving file attachments with a separate group of pods. With that in place, if EFS were to have latency issues again, the requests for file attachments would have problems, but since the requests for MDN documents would be served by a separate group of pods, they would not be affected. MDN pages would load, but they might be missing their file attachments.

### User Story
As an MDN user, I want MDN to avoid downtime or latency based on serving file attachments, so that I can quickly access the information I need. 

### Acceptance Criteria
1. Create a new certificate with domains `mdn.mozillademos.org` and `mdn-demos-origin.moz.works` for prod.
1. A new certificate exists with domain `stage-files.mdn.moz.works` for stage.
1. An "attachments" K8s service exists.
    - This would be exactly the same as the current "web" service (built upon https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/k8s/cert.svc.yaml.j2), but with a `SERVICE_NAME` of `attachments` and the certificate from above.
    - A new `Makefile` target (`k8s-attachments-svc`) exists, modeled after `k8s-web-svc` to create the service, and add it as a dependency to the `k8s-services` target.
    - The appropriate environment variables exist in the setup scripts under https://github.com/mozmeao/infra/tree/master/apps/mdn/mdn-aws/k8s/regions.
1. An "attachments" K8s deployment exists.
    - This would be exactly the same as the current "web" deployment (built upon https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/k8s/kuma.deploy.yaml.j2), but with a different name.
    -A new `Makefile` target (`k8s-attachments`) exists, modeled after `k8s-web` to create the deployment, and add it as a dependency to the `k8s-kuma-deployments` target.
    - The appropriate environment variables exist in the setup scripts under https://github.com/mozmeao/infra/tree/master/apps/mdn/mdn-aws/k8s/regions.
    - This deployment is configured to use a separate New Relic label for reporting purposes.
1.The new "attachments" service and deployment are deployed to the `mdn-stage` namespace.
1. The DNS for `stage-files.mdn.moz.works` is updated from the ELB for the "web" service to the new ELB for the "attachments" service.
1. Tests pass on stage.
1. The new "attachments" service and deployment are deployed to the `mdn-prod` namespace.
1. The DNS for `mdn-demos-origin.moz.works` is updated from `prod.mdn.moz.works` to the new ELB created as part of creating the K8s "attachments" service above.
1. Tests pass on prod.

**Comment by tobinmori** [comment]
This has been completed.
