### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### ISSUE THREAD

**Issue by nitramrelpmur** [mdn/sprints#1683]
# Request type

[ ] Please close this issue, I accidentally submitted it without adding any details
[ ] New documentation
[x] Correction or update

# Details

The example code in the section [External JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#External_JavaScript) is not correct. The script is loaded and executed asychronously (with async). Therefore the button might not have been added to the DOM when the following line is exsecuted: `const buttons = document.querySelectorAll('button');`  
It is easy to force this situation if the DOM loading is blocked by an alert message:
```
  <body>
    <script>
      alert("Delay parsing HTML...");
    </script>
    <button>Click me</button>
  </body>
```
In my opinion, the correct solution would be to use defer instead of async.

**Comment by chrisdavidmills** [comment]
Might be an issue, yes. I've updated it. Thanks!
