### ISSUE TITLE
Update or Archive? CSS3 & Mozilla Support Chart

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1684]
https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_support_chart

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3

Last updated in 2017. Should we keep, keep and update, archive or toss?

**Comment by jmswisher** [comment]
My votes: 

1. DELETE "Mozilla support chart". Nobody wonders "What CSS features does Firefox support?" They wonder "Does Firefox support _this_ CSS feature?" and they can get that from the BCD table for the feature.

2. ARCHIVE "CSS3". We're not maintaining it, so it shouldn't be in the main tree. But it may contain some information that's useful to somebody.

**Comment by chrisdavidmills** [comment]
I'd agree with both of Janet's comments here.

**Comment by estelle** [comment]
We all agreee (during meeting)

**Comment by chrisdavidmills** [comment]
"Mozilla support chart", and all its translations, deleted (https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_support_chart)

**Comment by chrisdavidmills** [comment]
"CSS3", and all its translations, now archied (see https://developer.mozilla.org/en-US/docs/Archive/CSS3)
