### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/How_to_contribute

### ISSUE THREAD

**Issue by colourbound** [mdn/sprints#1685]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Within the CSS introduction module for [Groups of selectors on one rule](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Combinators_and_multiple_selectors#Groups_of_selectors_on_one_rule) there is an important note that states: 

> Important: If a single selector is not supported by the browser, then the whole selector list gets ignored. The :is()  pseudo-class is not subject to this limitation, but isn't yet widely supported at the time of writing.

However,

In the [CSS selectors and rules](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax#CSS_selectors_and_rules) section earlier in the module there is an important note that seems to contradict or at least confuse a new learner about the difference between the two.

>Important: If a single basic selector in a chain or group is invalid, like when using an unknown pseudo-element or pseudo-class, the group of selectors is still valid, except for the invalid selector which is ignored.

One of these stating that the whole group will be ignored and the other stating the only the invalid selector will be ignored.

As a new learner the distinction between these two is unclear.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this!

> Within the CSS introduction module for Groups of selectors on one rule there is an important note that states:

Yeah, this one was correct, although I did remove the bit about the `:is()` pseudo-class as I didn't think it was hugely helpful to beginners.

> Important: If a single basic selector in a chain or group is invalid, like when using an unknown pseudo-element or pseudo-class, the group of selectors is still valid, except for the invalid selector which is ignored.

This bit on the other hand was confusing and kinda wrong. I've removed it because it is just plain confusing for beginners
