### ISSUE TITLE
CSS Selectors: create these pages

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1686]
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

There are several selectors in red (since I added them). These pages need to be created. 
:future & :past are supported in Chrome
None of the other red one (:current, :local-link, :focus-within) are supported in Ch or FF. I think drop is being dropped.

Should we create the pages? Delete the links I added? Leave as is?

**Comment by rachelandrew** [comment]
The `:drop` pseudo-class was indeed dropped in https://github.com/w3c/csswg-drafts/issues/2257

**Comment by rachelandrew** [comment]
@chrisdavidmills we don't have a page for `:user-invalid` however we do have the similar `-moz` property https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-invalid

I think other things have had the page moved and then the non-standard property also listed. The moz property name would be an alternate name then for Firefox in the BCD. The alternative would be to create a new page but already it looks like someone has updated the content to link the two.

(I just thought I'd bundle up a load of these selector-related issues and deal with them together as there is some overlap)

**Comment by chrisdavidmills** [comment]
@rachelandrew sounds reasonable, thanks!

**Comment by rachelandrew** [comment]
I've been trying to figure out exactly what the status of `:future` and `:past` is and drawing a blank. 

They exist a long way back in Chrome, I can see that they are in 30, and can find them in the Chrome source code. They are tied to the [Video Track](https://developer.mozilla.org/en-US/docs/Web/API/VideoTrack) functionality in WebKit source, so I think they probably shipped in Safari 6.1, and it's likely they then came across to Blink with the fork. @ddbeck any ideas? Would be good to make the BCD. 

Anyway I have made the pages for them, I tried to make some examples but I'm not actually sure if there is a way to really demo these. The only place they occur is with WebVTT and when the browser plays the video it hides the past and future ones captions anyway. Though I'm no expert on WebVTT so if someone knows how to get something visible going on let me know!

**Comment by ddbeck** [comment]
> They exist a long way back in Chrome, I can see that they are in 30, and can find them in the Chrome source code. They are tied to the Video Track functionality in WebKit source, so I think they probably shipped in Safari 6.1, and it's likely they then came across to Blink with the fork. @ddbeck any ideas?

Yeah, that seems likely to me too (ex: https://bugs.webkit.org/show_bug.cgi?id=105473). If you want to open a PR with details for Safari, we can probably just follow BCD's own data for Safari→Chrome, based on the WebKit version numbers.

**Comment by rachelandrew** [comment]
@ddbeck PR here: https://github.com/mdn/browser-compat-data/pull/7555

**Comment by chrisdavidmills** [comment]
I think these got added, so I'm closing this.
