### ISSUE TITLE
New Page: UI Selectors, 

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1687]
We've broken down some of the selectors into named groups, like attribute selectors, but the pseudo classes is one large brain dump on https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes given only one line on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

I suggest breaking some of the pseudo classes into named subgroups, including:
Linguistic
Location
user action
time-dimensional
resource-state
input
tree structural
grid structural

as done in the specification. This may help make it more manageable for people to learn.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think this makes sense for the pseudo-classes page, should we replace the index or have it as well as the index?

**Comment by chrisdavidmills** [comment]
@rachelandrew I think it makes sense to have the categories listed up the top of the page as @estelle suggested, and then have the alphabetical index down the bottom of the page.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've made it so: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

**Comment by chrisdavidmills** [comment]
This looks really good, thanks @rachelandrew . I think all I'd like to see here now is a single sentence at the top of each of the new sections to describe what each class of pseudo represents.

**Comment by rachelandrew** [comment]
@chrisdavidmills done, and also added the missing two `:playing` and `:paused`. The data for them was included in the additions I did earlier so should show up at some point.

**Comment by chrisdavidmills** [comment]
Looks great, thanks! I think we can close this now.
