### ISSUE TITLE
:has() - is page accurate?

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1688]
https://developer.mozilla.org/en-US/docs/Web/CSS/:has

states :has() is only to be used in JS.
https://drafts.csswg.org/selectors-4/#relational makes no mention of this.

where was this info garnered? Is it right?

Acceptance Criteria: addressed.

**Comment by estelle** [comment]
see comments in spec.

**Comment by ExE-Boss** [comment]
This is correct, see: https://drafts.csswg.org/selectors-4/#profiles

**Comment by a2sheppy** [comment]
Agreed, this is correct as stated in the doc.
