### ISSUE TITLE
"Modifying Preferences from Developer Toolbar" was supposed to appear, but doesn't

### ISSUE THREAD

**Issue by JJJoseph** [mdn/sprints#1689]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

Editing "Developer Toolbar" section in Mozillazine was supposed to be here, but the link doesn't go anywhere

**Comment by irenesmith** [comment]
@JJJoseph -- It would be helpful if you could tell me the page that includes the link so I can fix or remove the reference.
