### ISSUE TITLE
Invalid documentation link

### ISSUE THREAD

**Issue by olivier65** [mdn/sprints#1692]
This [page](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) contains two invalid links (first one under "Worker context" and second one under "Browser compatibility") to  https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/sendBeacon

**Comment by chrisdavidmills** [comment]
I've changed them to point to Navigator.sendBeacon(). The WorkerNavigator version is obsolete and nno longer exists in browsers.
