### ISSUE TITLE
Broken SVG sandboxes

### ISSUE THREAD

**Issue by clozach** [mdn/sprints#1696]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
While it renders fine in the MDN docs, the Pen and Fiddle for [this section](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#MoveTo_path_commands) render only the top SVG line.

# Browsers tested (macOS only)
Safari Version 12.1.1 (14607.2.6.1.1)
Chrome Version 75.0.3770.80 (Official Build) (64-bit)

# Screenshot
![image](https://user-images.githubusercontent.com/124952/59154379-1d829c00-8a26-11e9-96e7-9f08755681e2.png)

**Comment by clozach** [comment]
P.S. macOS version: Mojave 10.14.5 (18F203)

**Comment by chrisdavidmills** [comment]
Would be good to look into this, just to see if it is a dev problem, and also scope of problem.
