### ISSUE TITLE
::backdrop fullscreen API needs a local example

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1697]
https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop needs a local example

Instead of a glitch example, we need a local / codepen / jsfiddle example as the full screen functionality doesn't work with Glitch (at least for me) in the two browsers tested (FF and Chrome), so user can't play with code and effect change.

**Comment by rachelandrew** [comment]
@chrisdavidmills I moved this to our css-examples repo. I could get it working on Glitch but Glitch is so slow and often broken having it on our site seems better anyway. I couldn't get it to work as an embedded live example.

**Comment by chrisdavidmills** [comment]
I had a similar conversation with someone else recently about embedded examples not working well with things like fullscreen API. They ended up just showing snippets for the example on the MDN page and then linking to an example on GitHub: https://wiki.developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Examples

Maybe you could follow that same pattern here?

**Comment by rachelandrew** [comment]
@chrisdavidmills this shows the image and CSS on the page and links to the live example (which works standalone)

**Comment by chrisdavidmills** [comment]
looking good!
