### ISSUE TITLE
Several constraints described in "Using Screen Capture" have no effect

### ISSUE THREAD

**Issue by lucifer1004** [mdn/sprints#1698]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the [Using Screen Capture](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) Doc:

```js
var displayMediaOptions = {
  video: {
    cursor: "never"
  },
  audio: false
};
```

`cursor` is set to `never`, but this does not work in the live example below!

When I shared my monitor, the cursor still existed, and the log was like

```txt
Track settings:
{
  "aspectRatio": 1.6,
  "deviceId": "screen:2077750265:0",
  "frameRate": 30,
  "height": 1050,
  "resizeMode": "crop-and-scale",
  "width": 1680,
  "cursor": "always",
  "displaySurface": "monitor",
  "logicalSurface": true
}
Track constraints:
{}
```

Is this because constraints like `cursor`, `displaySurface` have not been implemented yet?

A finding is that when I use Google Meet, I am able to choose from only `monitor`, or only `window`, which appears to be related to the `displaySurface` constraint. But I cannot achieve that by simply using `navigator.mediaDevices.getDisplayMedia(video: {displaySurface: 'monitor'})`

**Comment by SphinxKnight** [comment]
@lucifer1004 Thanks for the report. as far as you, the [compat data](https://github.com/mdn/browser-compat-data/blob/master/api/MediaTrackConstraints.json#L194-L238) and I can tell, the `cursor` property is not supported except by Opera. 

This data is displayed on the page of the [`cursor` property](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/cursor) but there was no notes in [Using Screen Capture](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture)

I've added some notes to clarify the gap between the examples intent and the reality of implementations.

Please do reopen this issue if you think this is not sufficient.
