### ISSUE TITLE
Firefox 61 SVG DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#17]
As a Web developer I want to know about the latest SVG features in Firefox 61, so that I can test and make use of new technologies.

**Comment by chrisdavidmills** [comment]
1. - [ ] [Support SVG 2 path attribute for textPath](https://bugzilla.mozilla.org/show_bug.cgi?id=1446617)
2. - [ ] [Support SVGGeometryElement for other elements than path](https://bugzilla.mozilla.org/show_bug.cgi?id=1325320)
3. - [ ] [Support ping, rel, referrerPolicy, relList, hreflang, type and text properties on SVG <a> elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1451823)
4. - [ ] [Support SVG2 side attribute for textPath](https://bugzilla.mozilla.org/show_bug.cgi?id=1446650)

**Comment by Elchi3** [comment]
This is done now :)

**Comment by Elchi3** [comment]
Not sure why re-opened. It got done.
