### ISSUE TITLE
Write a proposal for Web API interactive examples, first phase

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#170]
Write a proposal outlining:

* which Web APIs we could cover in the first phase
* what kind of editor we might want
* how we might run the process of adding these examples

# Acceptance criteria

* proposal is written and approved by Product Manager

**Comment by jmswisher** [comment]
If I understand correctly [this is the proposal](https://docs.google.com/document/d/1rHSMMyM4RSFjttXvWLwaqWDQiVzPlAQRqnchhLfp0tg/edit?usp=sharing). @atopal: Is this approved by you? (per the AC)
