### ISSUE TITLE
Need docs for XHR onloadend and ontimeout events

### ISSUE THREAD

**Issue by olivier65** [mdn/sprints#1701]
The link to onloadend in https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest (under "Events") is broken.

**Comment by chrisdavidmills** [comment]
ontimeout is also missing. I've updated the issue title to reflect this.

We will get round to this in due course. Let me know if you would like to help out by contributing to these pages ;-)

**Comment by chrisdavidmills** [comment]
We have pages for the loadend and timeout events, So I'm going to close this for now.
