### ISSUE TITLE
StorageEstimate.usageDetails

### ISSUE THREAD

**Issue by jarryd999** [mdn/sprints#1702]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
I've gone ahead and added `usageDetails` to the `StorageEstimate` top-level page but need to create a subpage for it, just as there is a subpage for `StorageEstimate.quota` and `StorageEstimate.usage`.

Spec PR: https://github.com/whatwg/storage/pull/69
Explainer: https://jarryd999.github.io/quota-usage-details/
IDL: https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/quota/storage_usage_details.idl

**Comment by chrisdavidmills** [comment]
Hi @jarryd999 , thanks for adding this to the page. This is a little early for our core team to work on, given that it's not in the spec yet (although it looks like it will be soon).

Once it is, I'd be happy for you to add the necessary new pages to MDN (looks like we'd want a separate page for the StorageUsageDetails dict too). What is your MDN username? I'd be cool with giving you the ecessary permissions so youo can create these yourself.
