### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveBits

### ISSUE THREAD

**Issue by Sc00bz** [mdn/sprints#1704]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Description of length parameter is wrong "`length` is a number representing the number of **bits** to derive." It's suppose to say bytes not bits. Either that or FireFox and Chrome implemented it wrong.

**Comment by wbamberg** [comment]
What makes you say this? From the spec:

"Return an octet string containing the first *length* bits of *secret*."
(https://www.w3.org/TR/WebCryptoAPI/#ecdh-operations)

In the example, we pass `256` as length (https://github.com/mdn/dom-examples/blob/master/web-crypto/derive-bits/ecdh.js#L11) and [if you try the example](https://mdn.github.io/dom-examples/web-crypto/derive-bits/index.html) is reports a result of 32 bytes.

So this all indicates that `length` is bits.

**Comment by Sc00bz** [comment]
Wait I'm an idiot. I was using the function I wrote that takes byte length and calls deriveBits.
