### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by yifeiyin** [mdn/sprints#1714]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the page about Date (section: User notes > Date format and time zone conversionsSection), [direct link to the section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Date_format_and_time_zone_conversions), the hyperlink for the last word is broken:

> ... and ***setUTCHours()***.

It should link to [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCHours). The last part of the url incorrectly has `setHoursUTC` instead of `setUTCHours`.

**Comment by chrisdavidmills** [comment]
Fixed! Thanks for reporting this.
