### ISSUE TITLE
Hacks Blog post detailing the smaller CSS things in Firefox 68

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1717]
Rounding up some of the things shipping in 68.

# Acceptance criteria

- [ ] Post added to WordPress for publication

# Tasks

1. - [x] Hacks post first daft written
2. - [x] Post reviewed
3. - [x] Post added to WordPress

**Comment by rachelandrew** [comment]
@chrisdavidmills First draft here https://docs.google.com/document/d/1kxnG8ka_ApiM7_MPyHDNHvi6O1hQvomuVsIn0p66QAg/edit?usp=sharing

It may be there are other bits I can add in before we make it live around the release date, but let me know if you think of anything obvious to add immediately.

**Comment by chrisdavidmills** [comment]
Looking good, @rachelandrew  — thanks for this! I have given it a swift copy edit and made a couple of minor fixes.

Anything else to add? I think we got counter-set in 68; worth mentioning?

Apart from that, I think we are good to put this on hacks.

**Comment by rachelandrew** [comment]
I'm not sure how many web developers will have run into the need for `counter-set`, I had to fiddle around to work out the difference. Essentially counter-reset will create a new nested counter if there is already a counter of that name, counter-set only creates a new counter if there is no counter of that name already (so you don't get the nesting.) I am assuming counter-set was needed internally for the fixing list counting stuff that has happened. Webdevs don't tend to do much with counters (we use them a lot for books). So I could add something but I would struggle to come up with a good use case that isn't something we can already do with counter-reset.

**Comment by chrisdavidmills** [comment]
OK, that makes sense. Leave it in that case.

**Comment by rachelandrew** [comment]
This is now in WP for approval.
