### ISSUE TITLE
Update one or two HTML pages to proposed new structure, solicit feedack

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#172]
I have updated the [plan document I wrote detailing the proposed new structure of HTML pages](https://docs.google.com/document/d/17R-jyS2WVQ9_OIfErRZWRdPSAVYYauF3wfkJUeG07PI/edit#heading=h.xl00281b668q). My proposal is to take one or two HTML element pages this sprint, update them to this new structure, and then solicit more feedack. If we (editors, community) are happy with this, we can then start the updates over the course of future sprints.

Acceptance criteria:

1. Enough HTML reference pages updated to new structure to carry out SEO experiment.
2. Control pages chosen
3. Feedback gained from at least two team members.
4. Feedback gained from at least two community members
5. Pages updated according to feedback
6. SEO experiment running successfully by end of sprint.

**Comment by chrisdavidmills** [comment]
1. - [ ] Update one HTML page to new structure
2. - [ ] Update another HTML page to new structure
3. - [ ] Get reviews/feedback from team
4. - [ ] Get reviews/feedback from wider community, e.g. via discourse.

**Comment by atopal** [comment]
Hey Chris, since this is a pretty big change, what do you think about adding this as an SEO experiment? I'd also suggest user testing, but it it's probably less straightforward to set that up (eg. what exactly to test).

**Comment by chrisdavidmills** [comment]
@atopal I'd certainly like to do an SEO experiment. I've adjusted the tasks and acceptance criteria as appropriate.

**Comment by jwhitlock** [comment]
Where will the SEO experiment be tracked?

**Comment by chrisdavidmills** [comment]
I'm setting this to done; we'll track the SEO experiment set up in a different issue.
