### ISSUE TITLE
Integrate the new media type and codec guides into media articles on MDN

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1720]
In addition to the issue as originally filed, below, this issue is being used to cover the overall integration of the new guides into MDN content.

The MediaRecorder API currently has nothing about how to use the MIME type to configure codecs and profiles when constructing the MediaRecorder. This needs to be corrected and tied into the new media formats documentation.

My proposed plan is to first add the pages for the `MediaRecorderOptions` dictionary and its properties, then update the `MediaRecorder()` constructor page to transclude the basic information about the properties.

Then a page should be added to the media formats guide to describe how you specify codecs and profiles in a MIME type. This should be referred to, with an example or two given, in the MediaRecording docs, on the constructor page and in the overview page.

Doing all of this will take probably about a day and a half to two days, between the rearranging, the adding of pages to MediaRecording API, and the added page to the formats docs are all taken into account -- as well as the added links needed to hook the new stuff all in where appropriate.

The information for this will come from [RFC 6381](https://tools.ietf.org/html/rfc6381).

Places this will be referenced include (but aren't limited to):
* MediaRecorder() constructor
* MediaRecording API overview page
* Using the MediaRecording API
* Guide to video codecs used on the web (especially in the section on recommendations, esp. the archival and remixing subsection)

## Acceptance criteria

- [ ] Links to the codec guides added as necessary
- [ ] Any useful text added to the relevant pages

**Comment by a2sheppy** [comment]
This is basically integration with the new codecs parameter and codec guide.

**Comment by a2sheppy** [comment]
Updated https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types to reference the new content for image and media types

**Comment by a2sheppy** [comment]
Gradually making these updates.

**Comment by chrisdavidmills** [comment]
@a2sheppy is this the one you said you were probably finishing this week?

**Comment by a2sheppy** [comment]
@chrisdavidmills: yessir

**Comment by chrisdavidmills** [comment]
OK; let me know in sprint planning meetings what progress is like; I'd really like you to focus on Fx 70 DDNs next sprint.

**Comment by jmswisher** [comment]
I am guessing from comments in IRC that this is now done. If I'm wrong, please reopen and move to the QL milestone
