### ISSUE TITLE
formdata Event page and FormDataEvent interface

### ISSUE THREAD

**Issue by paulirwin** [mdn/sprints#1722]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details
The `formdata` event was recently added to the HTML spec, as an event on `form` elements that provides access to the form data constructed as if it were to be sent to the server. This is missing a page, as well as a page for the `FormDataEvent` interface.

References:
https://html.spec.whatwg.org/multipage/indices.html#event-formdata
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set (step 7)
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#formdataevent

**Comment by chrisdavidmills** [comment]
This now exist; see:

* https://developer.mozilla.org/en-US/docs/Web/API/FormDataEvent
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event
