### ISSUE TITLE
Documentation missing for image

### ISSUE THREAD

**Issue by narzb** [mdn/sprints#1727]
# Request type

- [X] Correction

# Details
Missing page :
https://developer.mozilla.org/fr/docs/Apprendre/HTML/Howto/Add_responsive_image_to_a_webpage

Referenced page here : 
https://developer.mozilla.org/fr/docs/Apprendre/HTML/Comment/Ajouter_des_images_%C3%A0_une_page_web#En_savoir_plus

**Comment by chrisdavidmills** [comment]
Translation available here: https://developer.mozilla.org/fr/docs/Apprendre/HTML/Comment/Ajouter_des_images_adaptatives_%C3%A0_une_page_web

Something wrong here.

**Comment by chrisdavidmills** [comment]
The link was incorrectl. I have fixed it now.
