### ISSUE TITLE
Write a plan for next steps for SEO

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#173]
Acceptance Criteria:
- [ ] Q3 goals are formulated
- [ ] issues are broken down into user stories

**Comment by a2sheppy** [comment]
Each of the errors has at least basic documentation now. Most are reasonably complete. One or two are barely better than stubs and I aam iterating on them.  Security team will be reviewing, hopefully by early next week.

**Comment by atopal** [comment]
@a2sheppy assuming this was meant for https://github.com/mdn/sprints/issues/64 ?
