### ISSUE TITLE
Question: is it possible to interact with the contents of MDN (the articles) via git?

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#1733]
# User story
Editing MDN online is very inconvenient, I'd like to do it on a local server with grep and real-time page refresh. Also, I want to make a lot of semi-automatic editing but do not want to do it directly on MDN (in case something goes wrong). So I'd like to download all MDN content via git and write scripts to edit the content and run a local MDN website to verify my edits are error free.

For example, I'd like to:
1. Ensure the page tags are applied consistently.
    I'll just extract all tags from all pages and look at how tags are applied. E.g., if a only a single article is tagged with a given tag, may be that tag is not useful at all. Also, the same header can be spelled in two different ways or misspelled, then we should pick a standard spelling and apply  it to all corresponding articles.
2. In translations, make sure that section headers are translated the same way.
3. Make sure that the articles and the compatibility tables agree on what is obsolete/non-standard/experimental.
    If a page has a record in `browser-compat-data` with `__compat` object that has `mdn_url` with page's url, then most likely this page documents the feature from that `__compat` object, therefore the `__compat.status` and the page header should agree. So a page should have `{{SeeCompatTable}}` on top of it if and only if it has `"status.experimental": true`, because both mean "this is an experimental feature". Similar logic applies to `{{obsolete_header}}` and `obsolete: true`, and `[another macro I don't remember]`and `standards_track: false`. I would need to cross-check a lot of articles and their JSONs and add headers or change JSONs where appropriate (determined manually, I think).
3. Similarly to the last one, make sure that inline badges also match `__compat.status`.

All these tasks would be mindbogglingly slow and boring to do manually but scripts would quickly produce a list of potential edits.

Of course I could just fetch articles source code from the site, but that would be error-prone and inefficient.

# Acceptance criteria
- [ ] Article content is downloadable and can be searched/processed offline.

Edit: punctuation.

**Comment by wbamberg** [comment]
This is not really possible at the moment although some of the bits are available.

* You can fetch page content using something like https://developer.mozilla.org/en-US/docs/Web/CSS/margin?raw and can then work on it offline.

* You can run a local MDN server following the instructions in https://kuma.readthedocs.io/en/latest/installation.html, but this basically just gets you an almost empty database. You can scrape documents from the production site into the database using commands like:

    docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Geolocation --depth 10

...but AFAIK you couldn't import documents from just a local file into the database in that way.

* You *can't* automate pushing of updates to the prod site. MDN does have a PUT API but it's broken and will probably never be fixed: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/PUT_API. So once you've made your changes you are stuck with updating them manually using CKEditor anyway.

>  mindbogglingly slow and boring

Welcome to our world! I would love so much for us to be able to make offline changes using regexes and grep, and create changelists that can be reviewed and applied in a single operation.

We've been talking for a while about using Git for our content. There's a rather experimental project under way to look into this, although it's hardly in good enough shape to be even worth sharing at this point: https://github.com/mdn/stumptown-content (we've not been particularly focused on writing project documentation). This project is also a kind of "solve everything" project, but it's possible we'll be able to move incrementally towards it, starting with moving the content more or less as-is into Git, to make mass-editing more feasible, and then massaging the content into a more structured form. But this is all a long way off.

So...don't hold your breath for this but it is coming, and if you are interested in helping to make it happen we'd be very happy to have the help.

**Comment by bershanskiy** [comment]
Thank you for the detailed explanation.
> if you are interested in helping to make it happen we'd be very happy to have the help.

I'll look into what I can do.
