### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

### ISSUE THREAD

**Issue by Ursi** [mdn/sprints#1734]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the [aggregating modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Aggregating_modules) section, there's a note that mentions that the `export from` statement must use an absolute path. It should at least talk about the use of relative paths with `./` and should probably use them in the example. I'm relatively new to all of this and not knowing about that caused me a decent amount of grief today.

**Comment by chrisdavidmills** [comment]
Hi @Ursi ,

Thanks for reporting this. This was definitely an oversight, and I'm sorry that it caused you such frustration.

I have rewritten all the examples to use relative paths  with `./`, and updated the explanations in the accompanying article. In particular, I have explained the path issues at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Importing_features_into_your_script.

Have a look and let me know if you think this needs further improvement. Thanks again!

**Comment by Ursi** [comment]
Looks good!
