### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

### ISSUE THREAD

**Issue by danielcovill** [mdn/sprints#1735]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I attempted to copy the "edge" browser specific setting exactly as listed in the site and I get the error shown in the attached screenshot:

```
There was an error during installation: Extension is invalid
Reading manifest: Error processing browser_specific_settings: Unexpected property "edge"
```

<img width="1194" alt="Screen Shot 2019-06-18 at 9 30 06 PM" src="https://user-images.githubusercontent.com/4174948/59734854-4b2ec880-9210-11e9-82f2-a331e9a9b2ad.png">

My manifest has the following:

```
	"browser_specific_settings": {
		"gecko": {
			"id": "{7e366839-2b7f-4235-bf7c-367450c69285}"
		},
		"edge": {
			"browser_action_next_to_addressbar": true
		}
	}
```

Removing the edge section eliminates the issue.

**Comment by danielcovill** [comment]
To clarify, I'm not sure if this is a documentation issue or a bug, but following the documentation doesn't seem to work so I went this way? Apologies if this should be filed elsewhere.

**Comment by irenesmith** [comment]
This is a known bug in Firefox 68.

This is the notice I have added to the page:

Warning: Adding Edge-specific properties to the manifest causes an error in Firefox 68 which can prevent an extension from installing. This is a known bug ({{bug(1542351)}}) in Firefox 68. It has been fixed in Firefox 69 and the fix will be uplifted to Firefox 68.

**Comment by irenesmith** [comment]
This has been reviewed now.
