### ISSUE TITLE
sendBeacon() is obsolete

### ISSUE THREAD

**Issue by tristangio** [mdn/sprints#1736]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details
The canceled [WorkerNavigator.sendBeacon()](https://github.com/w3c/beacon/commit/95e6a1f0efb7f374ab8fae20f30b79ce412deed4) has some entries in MDN doc : 

- https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API/Using_the_Beacon_API#WorkerNavigator.sendBeacon()

- https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API#Worker_context

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/content/pull/211
