### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines

### ISSUE THREAD

**Issue by neerajpradhan** [mdn/sprints#1737]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the **Nesting Articles and Sections**
at line number 14 there is a closing aside tag is used.
attaching the screenshot.
![bug](https://user-images.githubusercontent.com/52041155/59855558-d2a44500-9392-11e9-89ab-4d5356e3cf81.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this! I have removed the unnecessary aside, and cleaned up the rest of the article.
