### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions

### ISSUE THREAD

**Issue by tomquas** [mdn/sprints#1740]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
there is a _permission_ called _search_ in manifest.json which is listed but does not appear in the browser compatibility table.
i don't have details on version support so no PR this time.

**Comment by rebloor** [comment]
@chrisdavidmills Do you have any advice about how to track down the release number for this feature? I have checked the release notes and it's not mentioned there. I have looked at the source code, but can't immediately see where a definition of this parameter value might live.

**Comment by chrisdavidmills** [comment]
@rebloor I'd probably just ask one of the engineers responsible for this stuff; it can be really tricky and be a massive rabbit hole to find such data. Someone like Rob Wu or Shane C, maybe?

**Comment by rebloor** [comment]
Confirmed with Rob Wu that this was introduced in version 63.

**Comment by rebloor** [comment]
See https://github.com/mdn/browser-compat-data/pull/4976
