### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

### ISSUE THREAD

**Issue by Jonasdoubleyou** [mdn/sprints#1741]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
It is `Promise.allSettled` not `Promise.prototype.allSettled`.

**Comment by chrisdavidmills** [comment]
It looks to be documented in the correct place: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

Where are you seeing the issue?

**Comment by Jonasdoubleyou** [comment]
Looks like it was fixed already ...
