### ISSUE TITLE
Figure not rendering correctly in MDN documentation, for "Using CSS custom properties" page.

### ISSUE THREAD

**Issue by tedz2usa** [mdn/sprints#1743]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I really love the MDN documentation, I'm learning a lot.

I discovered however an issue on this page: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

That one of the 'css/html' previews are not rendering or showing up properly, it is just a blank white space. It is the first preview figure, right above the text "Notice the repetition in the CSS."

I want to report that the intended example figure is not showing up on my MacOS, on Chrome, Firefox, or Safari.

![Screenshot](https://i.imgur.com/WTsXsLl.png)

Regards,
Ted

**Comment by chrisdavidmills** [comment]
Fixed; the ID reference in the macro that generates that live example was wrong, so it couldn't  find the source code. Thanks  for reporting!

**Comment by tedz2usa** [comment]
Thank you Chris, for the rapid response and fix of this issue!!
