### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Aggregating_modules

### ISSUE THREAD

**Issue by Ursi** [mdn/sprints#1747]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is a note that says:

*This* (referring to `export from`) *is actually shorthand for ~~a~~ **an** import followed by an export, i.e. "I am importing module x.js, then re-exporting some or all of its exports".*

This is incorrect. If you use `export {module} from '/module.js'` is `main.js` you do not get access to `module` in `main.js`, i.e., it has not been imported.

**Comment by chrisdavidmills** [comment]
You've got a point here. I think the note was kind of correct, but it also implies things that are wrong, such as what you said. And It's not really that helpful anyway. I've deleted it.
