### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

### ISSUE THREAD

**Issue by guest271314** [mdn/sprints#1748]
# Request type

- [x] Correction or update

# Details

Bad link to Matroska (http://corecodec.com/products/matroska) at https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#WebM

**Comment by chrisdavidmills** [comment]
Fixed; I've replaced it with a link to https://matroska.org/
