### ISSUE TITLE
Suspend cache invalidation for an experiment

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#175]
To-Dos:
- [x] Experiment page set up
- [x] Baseline established
- [x] Cache invalidation is on hold for more than 24 hours
- [x] Data is collected
- [x] Data is analyzed
- [x] Results are shared

Acceptance Criteria:
- [x] Experiment setup is shared
- [x] Results from experiment are shared

**Comment by jwhitlock** [comment]
@atopal @escattone have the acceptance criteria for this experiment been met?

**Comment by atopal** [comment]
No, not yet. 
Sharing the draft of the experiment setup now: https://docs.google.com/document/d/1UO3a5HBDFqUciM9IQfZUToHe5uNnnsEcKcA9UUIfsEs

**Comment by jwhitlock** [comment]
With https://github.com/mozilla/kuma/pull/4871 and https://github.com/mdn/interactive-examples/pull/977 deployed, @atopal has the data needed for the 90% KPI metric. He'll let @escattone know when he's established a baseline, and we can re-run the 24-hour CDN timeout experiment.

**Comment by jwhitlock** [comment]
https://github.com/mozilla/kuma/pull/4873 will reset the performance metrics from ``fetchStart`` to ``navigationStart`` (see https://github.com/mozilla/kuma/pull/4873#discussion_r198859547). Current measures are invalid, we'll have to re-establish the baseline after this ships.
