### ISSUE TITLE
Unfound page in "OVP" link

### ISSUE THREAD

**Issue by UnorthodoxThing** [mdn/sprints#1751]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I found a link "OVP" that opens a 404 (page not found). I thought maybe that there should be a document on it. It is under _Learn Web Development_, _HTML Structuring the Web_, Multimedia and embedding, Video and audio content, Audio and Video on the web - see following link (https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#Audio_and_video_on_the_web). You can find it at the "Note" highlight in its first sentence. "OVP" is highlighted red. 

Im not sure if the term "OVP" was suddenly coined, or the link is broken. Please have a look.

Thanks in advanced.

-Caroline R

**Comment by chrisdavidmills** [comment]
Hi there @UnorthodoxThing — thanks for pointing this out. I wrote that article, and don't remember why I put a broken glossary link in there. I don't think it needs a separate page to explain the term — it is just a video provider that exists online. I think I probably just created the acronym to save a little  bit of space.

I've just removed the link from OVP, but let me know if you think something else would help.
