### ISSUE TITLE
All links on the page https://developer.mozilla.org/en-US/docs/Archive/RSS_elements are broken

### ISSUE THREAD

**Issue by Siemenskun** [mdn/sprints#1753]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Archive/RSS_elements
All links to the element's pages are broken: all of these shows Not Found page, but it all has blue color except <author> which red one, so I assume there are some articles that aren't displayed.

**Comment by chrisdavidmills** [comment]
It is strange that only one displays in red; afaik, these were never created. In any case, this content is archived, so it won't be made a priority.
