### ISSUE TITLE
Need doc for SVG AnimateMotion's 'origin' attribute

### ISSUE THREAD

**Issue by stelovsky** [mdn/sprints#1755]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On page https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
the following attribute links in section "Specific attributes" are bad:
path
  https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path
rotate
  https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rotate
origin
  https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/origin

**Comment by jmswisher** [comment]
`[path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path)` and `[rotate](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rotate)` are now documented, leaving only `origin`, which needs to documented on its own page and added to the animateMotion article.
