### ISSUE TITLE
Work towards updating Kuma to Python 3

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1756]
# User story

As an MDN developer, I want Kuma to run under Python 3, so it's on a current Python release and ready for Django 2.2.

# Acceptance criteria

Time-box the work towards this goal to 5 ideal days.

# Tasks

Continue working on the tasks outlined in this issue's [epic](https://github.com/mdn/sprints/issues/230).

**Comment by tobinmori** [comment]
It's important to note that the reason for doing this is not that just 2.7 is dying, but that 2.7 will no longer be supported as of Jan 1. 2020. This means bugs will no longer be fixed, and dependent libs may/will drop support, and most importantly security vulnerabilities will no longer be tended to. 

For more info:

https://pythonclock.org/
https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/
