### ISSUE TITLE
Document CSS Inline Formatting Context

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1757]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

## Details

Submitted over on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=904680

> From here: https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model

> Follow the 'inline formatting context' link to https://developer.mozilla.org/en-US/docs/CSS/Inline_formatting_context 404s.

**Comment by rachelandrew** [comment]
So, I think this is a bigger job as that page on the Visual Formatting Model really needs rewriting.

This page is describing the model defined in CSS2. Level 3 specs do still refer to this definition, for example if we look for the definition of the inline formatting context in Display Level 3 we read,

> "Block and inline formatting contexts are defined in CSS 2.1 Section 9.4."

I'm going to finish up writing about the inline formatting context as it is useful to have, but I'll add another ticket regarding reworking the visual rendering page.

**Comment by rachelandrew** [comment]
First draft here https://developer.mozilla.org/en-US/docs/Web/CSS/Inline_formatting_context

**Comment by chrisdavidmills** [comment]
Hi Rachel!

This is mostly looking really good. I gave it a light copy edit, and added some headings to give the article a bit more structure. I just had one comment:

> "If there is a float within the same block formatting context however, the float will cause the line boxes that wrap the float to become shorter."

In this example below this line, wouldn't it be a good idea to not set a width on the floated box, so that it doesn't look like it is just the width causing the line boxes to become shorter?

**Comment by rachelandrew** [comment]
> In this example below this line, wouldn't it be a good idea to not set a width on the floated box, so that it doesn't look like it is just the width causing the line boxes to become shorter?

maybe, but typically floated things have widths, I don't see why the width is an issue as it's not on the containing block.

**Comment by rachelandrew** [comment]
Also, having the width, with this being a live example, allows them to change the width on the float and see the change to the line boxes. Which seems useful.

**Comment by chrisdavidmills** [comment]
OK, good points. In that case I'm happy to change this to done.
