### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/MDN/Feedback

### ISSUE THREAD

**Issue by SuperLadyR** [mdn/sprints#1760]
reducer 函数接收4个参数:

Accumulator (acc) (累计器)
Current Value (cur) (当前值)
Current Index (idx) (当前索引)
Source Array (src) (源数组)
您的 reducer 函数的返回值分配给累计器，该返回值在数组的每个迭代中被记住，并最后成为最终的单个结果值。

这个应该是reduce

**Comment by wbamberg** [comment]
I'm not sure, but I think you mean that "reducer" here should be "reduce". If so I don't think it should: this is referring to the "reducer" function, which itself is an argument to the `array.reduce()` function.
