### ISSUE TITLE
Update "Basic concepts of CSS Scroll Snap" code example

### ISSUE THREAD

**Issue by arrienc** [mdn/sprints#1761]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

Article _Basic concepts of CSS Scroll Snap_ at 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts

Needs updated code shown in this article to work.
_Browser compatibility and Scroll Snap_ at
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat

Styles should be changed from:

.scroller {
    height: 300px;
    overflow-y: scroll;
    scroll-snap-type: y mandatory;
}

to:

.scroller {
    height: 300px;
    overflow-y: scroll;
    scroll-snap-points-y: repeat(320px);
    scroll-snap-destination: 0 0;
    scroll-snap-type: y mandatory;
    scroll-snap-type: mandatory;
}

**Comment by chrisdavidmills** [comment]
Hi @arrienc!

I assume you are on about the example seen in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts#Basics_of_Scroll_Snap?

I am not sure what needs to be done here. It seems to work OK without the addition you suggested, as well as with, and  I am not sure it is needed here  — this is supposed to be a basic beginner's example.

Can you explain more about why you think this is needed? Thanks.

**Comment by rachelandrew** [comment]
It looks like @arrienc wants to add the compat code for Firefox to the example for the new spec, I would suggest not doing so given that these properties have been removed from Firefox now, and as from 68 the example on that page works cross browser with no fallback needed. If people need the old code we are currently maintaining that information.

**Comment by rachelandrew** [comment]
Compat note here https://www.fxsitecompat.dev/en-CA/docs/2019/legacy-css-scroll-snap-syntax-support-has-been-dropped/

**Comment by arrienc** [comment]
I see that this issue has been resolved in FF.

Please close.

Thank you.

.c
