### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D

### ISSUE THREAD

**Issue by anlumo** [mdn/sprints#1763]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The list of texture types on this page has a few issues:

* `gl.RGUI` doesn't exist, maybe it should be `gl.RG8UI`
* `gl.SRGB_APLHA8` should be `gl.SRGB8_ALPHA8`
* `gl.RGBA4444` should be `gl.RGBA4`
* Section 5.37 of the WebGL2 spec says that all of the formats starting with `COMPRESSED_` aren't supported, they're part of the extension `WEBGL_compressed_texture_etc`.

**Comment by Elchi3** [comment]
Thanks for your report! I've fixed the typos you've mentioned and I've changed the doc about the compressed format. They used to be supported natively but that's not the case anymore, see https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_etc#Compatibility_notes

Diff https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D$compare?locale=en-US&to=1564231&from=1553600
