### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/right

### ISSUE THREAD

**Issue by ilyagr** [mdn/sprints#1764]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details

The explanation of what happens when both `left` and `right` are specified looks confusing and likely incorrect. I would really like an explanation of what's really going on. The test says:

> When both left and right are defined, the position of the element is overspecified.
When this is the case, the left value has precedence when the container is left-to-right (thus, the computed value of right is set to -left)

I have two problems with this:

1. Setting `left: 10px` is very different than setting `right: -10px` if `width` is not 100% and `position` is `absolute`. The former puts the *left* edge 10px to the right of the containing block's left edge. The latter puts the *right* edge 10px to the right of the containing block's right edge. 

2. I have code where both `left` and `right` are specified, but removing `right` changes the result. I put the code here: https://jsfiddle.net/1f0ujz2a/2/. Without `right=0`, the overlay is left-aligned (don't forget to click 'Run' in jsfiddle). The key parts seem to be `left:0; right:0; marign-left: auto; margin-right: auto;width:20%;` and the nesting. 

It's possible I misunderstand something (is this not valid CSS?), but it makes no sense currently. I'm not qualified to fix it, but I'd love for the MDN docs to have enough information to explain to me how the example in 2. works.

If these are real issues, they are also present in several other MDN pages (the pages on `position` and `left` at least).

Thank you very much!

**UPDATE**: Updated point 1 above to clarify that I'm thinking of `position:absolute`. For `position:relative`, the documentation as it was makes more sense.

Acceptance criteria:

[] - mark as resolved

**Comment by ilyagr** [comment]
I did my best to fix this. My edits:

https://developer.mozilla.org/en-US/docs/Web/CSS/left$compare?locale=en-US&to=1560602&from=1528236

https://developer.mozilla.org/en-US/docs/Web/CSS/right$compare?locale=en-US&to=1560600&from=1528277

**Comment by ilyagr** [comment]
Adding more info to those pages on how this all relates to `margin` would be appreciated from someone more knowledgeable. It seems that the `left` and `right` refer to the size of the the element *including* margins, which is different from how `width` behaves.

**Comment by estelle** [comment]
Thank you @ilyagr for your edits. The 'lay' speak is much easier to understand. I added an extra example to illustrate the issue.
