### ISSUE TITLE
Old WebIDE pages to remove/deprecate

### ISSUE THREAD

**Issue by juliandescottes** [mdn/sprints#1765]
Hi,

Found some more WebIDE-related pages that should be removed or deprecated :)

- https://developer.mozilla.org/en-US/docs/Tools/WebIDE (a lot of deprecated information, and not linked from anywhere else?)
- https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Setting_up_runtimes (no longer supported)
- https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Opening_WebIDE (deprecated information, eg mentions of runtimes, of the WebIDE toolbar icon...)
- https://developer.mozilla.org/en-US/docs/Tools/WebIDE/The_runtime_menu (permissions table is already gone, all the rest is WebIDE specific so will be deprecated soon)

Let's discuss whether those should be removed or deprecated.

cc @irenesmith 

- [x] Talk to Julian and determine whether to delete or archive content

# Acceptance criteria
- [x] Pages are deleted or archived as determined above

**Comment by irenesmith** [comment]
Pages have been archived and also marked as deprecated.
