### ISSUE TITLE
https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/A_first_splash

### ISSUE THREAD

**Issue by ivanseibel** [mdn/sprints#1768]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There are some significant differences between the "pt-BR" and "en" documents, especially in the part dealing with variables and constants. In the "en" version is suggested to use *let* and *const* to store the references and in the "pt-BR" version is suggested to use only *var*.

**Comment by chrisdavidmills** [comment]
This is because we rely on community to do most of our translations; we don't have Brazilian Portugese language skills on our team. When the English version got updated to include `let` and `const` information, no one updated the `pt-BR` version.

Are you interested in helping us update it? ;-)

**Comment by ivanseibel** [comment]
Of course I want! What I have to do?

---
Ivan L. Seibel

Linkedin: https://www.linkedin.com/in/ivanseibel/

Em ter, 2 de jul de 2019 04:19, Chris Mills <notifications@github.com>
escreveu:

**Comment by chrisdavidmills** [comment]
Well, to edit a page you need to be logged into MDN. Our logins use GitHub authentication, so to Login you'll need a GitHub account (we hope to provide other login mechanisms in the future).

Once you are logged in, you can go to https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/A_first_splash and press the "Editar" button.

You'll then see the translation window, with the English version on the left, and the pt-BR version on the right. You'll need to write updates to the pt-BR version in the right hand window and then press the "Publicar" button to save them.
