### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

### ISSUE THREAD

**Issue by andrewcowley** [mdn/sprints#1769]
# Request type
- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The embeded example for the thresholds section when opened in CodePen or JSFiddle has an incorrect title. This is due to the code for the example on the Wiki being hidden in a div with an id `threshold-example`. 

When the buttons are created with `createSampleButtons` the section argument is used to create the title of the CodePen/JSFiddle: 
```
var title = doc.getElementById(section);
title = title ? title.textContent : '';
```

This is expecting a heading like `<h1 id="threshold_example">Threshold example</h1>` to extract the `textContext` from, but as I said above on this page the id with `threshold-example` is a div containing the hidden code and the CodePen/JSFiddle is created with a title of this embeded code.
![2019-07-02_15h22_29](https://user-images.githubusercontent.com/1101541/60484474-39075c80-9cdd-11e9-88b3-cd9981781d24.png)

I'm sure this can be done another way with the wiki to ensure this issue doesn't happen. I didn't have time to figure it out though sorry.

**Comment by chrisdavidmills** [comment]
This sure looks ugly; thanks for pointing it out!

So, I've fixed this by putting  the id for the example section on a hidden heading inside the hidden `<div>`, rather than on the hidden `<div>` itself.
