### ISSUE TITLE
Error 404 with link

### ISSUE THREAD

**Issue by adriendesart** [mdn/sprints#1771]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Error 404 on this URL : https://developer.mozilla.org/fr/docs/Apprendre/Upload_files_to_a_web_server

I can't acces to this page by the link on this [URL](https://developer.mozilla.org/fr/docs/Apprendre/Qu_est-ce_qu_un_serveur_web)

**Comment by jmswisher** [comment]
Fixed a bad link; let me know if I missed anything.
