### ISSUE TITLE
"Debugger (before Firefox 52)" is 404 

### ISSUE THREAD

**Issue by nickolay** [mdn/sprints#1773]
(the template makes no sense, so I deleted it.)

https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Break_on_a_DOM_event says "To see the docs for the old debugger, please visit Debugger (before Firefox 52)", but https://developer.mozilla.org/en-US/docs/Tools/Debugger_%28before_Firefox_52%29 is 404 with no way to find what it used to refer to.

I got here by trying to answer https://stackoverflow.com/questions/56841442/firefox-quantum-event-pane-does-not-appear-on-developer-tab-in-developer-editio

I'd expect the legacy documentation to provide info on whether it's available in modern Firefox by setting about:config variables.

I expected the MDN platform to make it possible to find the page that got moved/deleted since.

**Comment by irenesmith** [comment]
Actually, the entire page about breaking on DOM events is no longer valid and will be removed or archived soon.

Starting in Firefox 69, the Debugger will include the ability to select an event and automatically add a breakpoint that will fire when the handler for that event is hit. If you want to play with it, you can download [Firefox Developer](https://www.mozilla.org/en-US/firefox/developer/) edition.

**Comment by nickolay** [comment]
Thanks!
