### ISSUE TITLE
Downloadable mirror (tarball) referencing CSS/JS on a CDN - 404 errors

### ISSUE THREAD

**Issue by p0lar-bear** [mdn/sprints#1776]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
I downloaded the static mirror tarball (from https://developer.mozilla.org/en-US/docs/MDN/About#Downloading_content) and extracted it, and the first thing I noticed is that the styles weren't working. On looking at my browser's request traffic, I see it trying and failing to pull CSS and JS from `developer.cdn.mozilla.net`:

![image](https://user-images.githubusercontent.com/4573881/60675257-ec8d5f80-9e49-11e9-832e-ad69b8238315.png)

First glaring problem: the needed files are missing from the CDN.

Second, I'm looking to put this mirror up on a web server running in a closed computing facility, thus people browsing the docs there wouldn't be able to reach the CDN anyway. Shouldn't these supporting files be included with the tarball?

EDIT 1: Added link to source of my download.

**Comment by chrisdavidmills** [comment]
Where did you find the link to this tarball?

**Comment by p0lar-bear** [comment]
@chrisdavidmills On MDN's About page: https://developer.mozilla.org/en-US/docs/MDN/About#Downloading_content

**Comment by chrisdavidmills** [comment]
Oh, that thing. We haven't actively maintained it for ages, so the docs are likely to be very out of date, so I wouldn't recommend it. I've removed it from the page.

You'd be better off using the other things listed for using offline-MDN.

And we have some better mechanisms for offline MDN coming in the future.
