### ISSUE TITLE
Missing infomation in the docs

### ISSUE THREAD

**Issue by ghost** [mdn/sprints#1777]
I got the following Server Code Error in Firefox Nightly:

```
Status Code 527: No Reason Phrase
```

See screenshot as proof Firefox is saying this:

![error](https://user-images.githubusercontent.com/17784082/60759270-35940e00-a01a-11e9-9d65-5513ae3dda53.png)

So I click on the help icon, which takes me to the following webpage: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Now do a search for this Server Status code and you will get zero infomation about it.

Plus doing a search in Google turns up no infomation! So MDN really needs to add some kind of infomation at least.

**Comment by irenesmith** [comment]
The status code above (527) is a code returned by Cloudflare. See [Cloudflare HTTP Status Codes](https://support.cloudflare.com/hc/en-us/articles/115003014432-HTTP-Status-Codes) for further information on their status codes.

**Comment by jmswisher** [comment]
Oh, I see. Dev Tools is linking to MDN for all HTTP status codes, standard or not. I added a note to the overview page that codes not listed are non-standard.
