### ISSUE TITLE
Improve description of VRPose.orientation

### ISSUE THREAD

**Issue by Sgeo** [mdn/sprints#1778]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The page states that the orientation is a quaternion with pitch, yaw, roll, and w.

The components of a quaternion aren't as easily described as that. Either those aren't quite pitch/roll/yaw, or it's potentially misleading to call this a quaternion.

**Comment by jmswisher** [comment]
The spec [calls it a quaternion](https://immersive-web.github.io/webvr/spec/1.1/#dom-vrpose-orientation), so the misleadingness is deeper than MDN. @a2sheppy Any thoughts?
