### ISSUE TITLE
FileReader.onabort 404

### ISSUE THREAD

**Issue by NandoMB** [mdn/sprints#1782]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

FileReader.onabort is returning 404

**Comment by NandoMB** [comment]
FileReader.onload is returning 404

**Comment by jmswisher** [comment]
The [onabort](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onabort) page exists, so it's probably a bad link. @NandoMB On what page were you clicking a link?
