### ISSUE TITLE
Draft recipes for all page types

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1790]
This issue is part of https://github.com/mdn/sprints/issues/1787.

For the purposes of this issue a "page type" is a specific type of reference page with its own structure, defined by a recipe. For example "CSS property", "HTML element", "HTML attribute" are all page types. A "recipe" is a specification for the things that need to exist in a given type (for example, BCD, interactive examples, CSS formal syntax...).

https://github.com/mdn/sprints/issues/1789 should get us a list of all the page types we will need to support. In this issue we will draft recipes for each type.

These are just draft recipes and we would expect to adjust them as we do deeper work on each one. But this should give us an idea of how many different recipes they are and how much they diverge.

******

AC:
* we have a list of all the draft recipes for all the page types we need to handle in stumptown, reviewed and approved by a content peer.

**Comment by jmswisher** [comment]
@wbamberg Is this issue still relevant? Can it be closed?

**Comment by wbamberg** [comment]
Yes let's close this.
