### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/MDN/Feedback

### ISSUE THREAD

**Issue by AllanJian** [mdn/sprints#1796]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

I received a questionnaire from MDN web. The options of "Country" include "China", "Hong Kong,China", but "Taiwan" does not been written right.

**Comment by chrisdavidmills** [comment]
@schalkneethling this was reported to us, but sounds like a dev issue involving the DNA. Can you look into this?

**Comment by schalkneethling** [comment]
> @schalkneethling this was reported to us, but sounds like a dev issue involving the DNA. Can you look into this?

Thanks for the heads up @chrisdavidmills - This is on the survey itself so @atopal would be the best person for this. Thanks for reporting this @AllanJian

**Comment by atopal** [comment]
Thanks for reporting this. I'll have a look
