### ISSUE TITLE
Remaining DOM tasks for Fx 68

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1804]
See https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-68 for the original trello card.

# Acceptance criteria

- [ ] [Make target=_blank on a/area elements imply rel=noopener by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1522083) (will be put behind a pref?) — documented appropriately. **HAS NOT LANDED FOR 68 AS OF JUNE 21**

**Comment by chrisdavidmills** [comment]
Closing this; this is not looking like it will be fixed anytime soon, so I've moved it back to the backlog in the content roadmap until we get any other news.
