### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

### ISSUE THREAD

**Issue by icl7126** [mdn/sprints#1809]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I'm looking for more information about behavior when multiple listeners is registered, especially in what order they will fire.
Right now, the only info in this regard is:

> If you have more than one onMessage listener in the same document, then only one may send a response.

This is consistent with the [Chrome documentation](https://developer.chrome.com/extensions/runtime#event-onMessage).

1. issue - **this means the order in which they will fire is important** - but it's not mentioned that it will be in the order they were registered (which would make most sense)
1. issue - **it's not clear what happens to the other listeners** - I think the first one that returns a `Promise` / `true` or calls `sendResponse` will stop execution of the other listeners, right?

# Acceptance criteria
- [ ] onMessage page is updated to clarify what happens when multiple event listeners have been registered.

**Comment by rebloor** [comment]
Thanks! I'm here.

**Comment by rebloor** [comment]
Pinged Tom, Rob, and Luca for advice on the answer to this query.

**Comment by zombie** [comment]
The whole extensions messaging system is one of the worst API designs I've had the displeasure of working with.

Because of this, we're purposefully not specifying API details missing from Chrome's public docs, as their own implementation and/or docs might change at any point to contradict us, which could introduce incompatibilities we might not be able to address without breaking existing Firefox extensions.

Therefore, the order of listeners invoked is implementation detail, and may change in the future.

> 2. issue - **it's not clear what happens to the other listeners** - I think the first one that returns a `Promise` / `true` or calls `sendResponse` will stop execution of the other listeners, right?

Last time we tested in Chrome (and how we currently implemented in Firefox), this was not the case.  All listeners which received the message could respond, but only the first result was returned to the caller.

...

Our general recommendation, one which might be worth including in our docs, is that extensions generally shouldn't be listening and responding to same kinds of messages in multiple places.

**Comment by icl7126** [comment]
Thanks @zombie for the explanation. It makes sense.
But let's add this info to the docs:
1) order in which multiple listeners will fire is not guaranteed
2) make sure only one callback send response - here maybe **advice users NOT to use `async` function** as this will always return a Promise which will prevent other listeners to handle the message. This is what cased some hard to find bugs in my addon.

**Comment by rebloor** [comment]
@irenesmith 

> Maybe we should consider raising that number as well, since we're working on 70.

 We probably want to stick to version 60, I understand this to be the current ESR version.

**Comment by rebloor** [comment]
I have added a note to the page:

>Avoid creating multiple onMessage listener for the same type of message, as the order in which multiple listeners will fire is not guaranteed. Where you want to guarantee the delivery of a message to a specific end point, use the connection-based approach to exchange messages.

Please let me know if this addresses the issue of further changes are needed. Thank you!

**Comment by irenesmith** [comment]
I think that’s fine but listener in the first sentence should be plural.
(Nitpicking, I know)

**Comment by icl7126** [comment]
> > Returning a Promise is now preferred as sendResponse will be removed from W3C spec. The popular webextension-polyfill library has already removed the sendResponse function from its implementation.
> 
> this seems to be contrary to your suggested change, or am I missing something?

Actually I'm the author of those lines :)
But it's not what I meant. Returning a Promise is totally fine - for the cases when response is expected. But making the whole function `async` will return Promise every time (**!!!**) which will prevent other message handlers from responding. 
This can happen even if you have only one message handler per context, for example if content script tries to send message to the pop-up script but instead receives empty message from background script.
Maybe not the best example, but there is multiple others (I had an iframe loaded in pop-up which needed communicate with the parent pop-up and it wasn't working because background script was capturing all those messages with its `async` function.

**Comment by rebloor** [comment]
> I think that’s fine but listener in the first sentence should be plural. (Nitpicking, I know)

@irenesmith hardly a nitpick! Thanks for picking up

**Comment by rebloor** [comment]
@icl7126 I am slightly confused by your references to "`async` function" as I don't think there is such a function in method, do you just mean "while it's behaving asynchronously"? I'm afraid I am struggling to understand what you mean, I'm wondering if it makes the most sense to ask you to suggest any changes needed to the current documentation.

**Comment by icl7126** [comment]
@rebloor sorry for the confusion :)
This is what I mean:
```
browser.runtime.onMessage.addListener(async (data, sender) => {
  if (data.type === 'handle_me') return 'done';
  // WARNING: this event handler will consume every message it receives, because the function is defined as `async`
});
```

Whereas:
```
browser.runtime.onMessage.addListener(data, sender) => {
  if (data.type === 'handle_me') return Promise.resolve('done');
  // no surprises here, this method returns a Promise ONLY when needed
});
```
Will not consume messages meant for other handlers.

I hope it makes sense now :)

**Comment by rebloor** [comment]
@icl7126 So, at the end of the [addListener syntax](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#addListener syntax) we could add a warning:

Do not call `addListener` using the `async` function, as in:

``` 
browser.runtime.onMessage.addListener(async (data, sender) => {
  if (data.type === 'handle_me') return 'done';
});
```
as the listener will consume every message it receives, effectively blocking all other listeners from receiving and processing messages.

If you want to take an asynchronous approach, use a promise instead, as in:

```
browser.runtime.onMessage.addListener(data, sender) => {
  if (data.type === 'handle_me') return Promise.resolve('done');
});
```

**Comment by icl7126** [comment]
@rebloor Yes, sounds good.

**Comment by rebloor** [comment]
@icl7126  I have added the note to the documentation, have all the documentation items on this issue been addressed?

**Comment by icl7126** [comment]
@rebloor yes, thank you for your help!
