### ISSUE TITLE
E - Document WebXR

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1829]
# Summary

WebXR (WebVR, WebAR) is a hot technology that a lot of people are interested in learning about.

_**Note:** This epic currently mostly just covers the WebXR Device API, though there are some items that were added here before the spec was broken up. Issues will be added for the other specs as they are finalized._

We want to document it to attract more users to MDN, and keeping our web platform docs as complete as possible, thereby contributing to our KR of increasing traffic by 5% y/y.

# General task list

We want to have logical high-level page structure to allow people to easily find and navigate the documentation. This would include:

* Making sure there is a WebXR landing page in place that links off to all other related content.

We want to provide complete reference material for WebXR. This would include:

* Documenting navigator.xr()
* Documenting XRSystem
* Documenting XRSession
* Documenting XRFrame
* Documenting XRReferenceSpace
* Documenting XRBoundedReferenceSpace
* Documenting XRInputSourceArray
* Documenting XRInputSource
* Documenting XRView
* Documenting XRViewport
* Documenting XRSpace
* Documenting XRRigidTransform
* Documenting XRPose
* Documenting XRViewerPose
* Documenting XRWebGLLayer
* Documenting all WebXR events
* Making sure all reference pages have code examples in place.

Finally, we want to create guides to teach all the essential concepts and coding techniques required for developers to use WebXR. This includes articles on:

* Spatial tracking in WebXR
* Inputs and input sources
* WebXR fundamentals
* WebXR performance guide
* Lighting in WebXR
* Perspective in WebXR/WebGL
* Setting up and shutting down a WebXR session
* WebXR rendering loop
* Cameras in WebGL and WebXR
* Geometry in WebXR

And:

* Making sure all required diagrams are in place
* Adding an example of object-first order rendering to Rendering in WebXR article

**Comment by a2sheppy** [comment]
Sorry, I really need the word "epic" in the name of this thing because otherwise search-for-tab or search-for-bookmark doesn't find "webxr epic" or the like, and that's awfully useful.
