### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

### ISSUE THREAD

**Issue by swpease** [mdn/sprints#1841]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I am looking to update an addon I made last year. It uses `storage.sync`, which requires an ID. This ID used to be specified in the `manifest.json`'s `"applications"` key, but is now in `"browser_specific_settings"`.

Unless it's been so long that I just missed it, it seems like there should be an indicator somewhere that `"applications"` has been deprecated and replaced by `"browser_specific_settings"`. There are still a few odd references to it, such as in the [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) page, which I suppose could easily be updated, but it was confusing how `"applications"` just kinda fell off the map.

**Comment by rebloor** [comment]
@chrisdavidmills Any idea when this change took place, I can't find it by searching the release notes or Bugzilla.  I'm guessing we should include something in the release notes. Also, any thoughts on a convenient way to find all the page copy that need updating?

**Comment by chrisdavidmills** [comment]
@rebloor hmmm, not sure. Might be good to ask the engineer's advice on this.

**Comment by rebloor** [comment]
Sorry @chrisdavidmills, and who might the engineer be?

**Comment by chrisdavidmills** [comment]
@rebloor I'm not sure; you might want to check with Caitlin, or Rob, or whoever else you could contact.

**Comment by zombie** [comment]
> around April of 2016, which I believe was even before we officially released "1.0" of Web Extensions in Firefox. 

By a hair.
https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/

**Comment by rebloor** [comment]
@zombie So, if I understand you correctly, you're saying the change was made so close to the launch of web extensions that we can consider "applications" never to have existed and change any remaining references to browser_specific_settings. Correct?
One supplementary question, any thoughts on a reliable way of finding all references to "applications" in MDN?

**Comment by zombie** [comment]
Correct, we kept support in code for backward compatibility (it was the only way to specify the ID for half a year before Firefox 48), but we don't need to reference it anymore.

> One supplementary question, any thoughts on a reliable way of finding all references to "applications" in MDN?

Sorry, I don't really have any insight here, I'm not that familiar with MDN.

**Comment by zombie** [comment]
>  zombie unassigned irenesmith 21 seconds ago

I didn't mean to do this, nor do I have any idea why it happened.  🤷‍♂

**Comment by rebloor** [comment]
@zombie Thanks for your help, as Irene is no longer with us the change doesn't matter. There is one other thing you might be able to help with: in the update manifest there is also an "applications" property, is this too replaced by "browser_specific_settings"? (see https://extensionworkshop.com/documentation/manage/updating-your-extension/)

**Comment by zombie** [comment]
Yes, `applications.gecko` and `browser_specific_settings.gecko` manifest keys are equivalent and treated the same, see the JSON schema:
https://searchfox.org/mozilla-central/rev/b2b0077c/toolkit/components/extensions/schemas/manifest.json#22,33,460

The whole `applications` and `browser_specific_settings` keys are almost the same, and any new docs should reference the latter.

**Comment by rebloor** [comment]
Changes to Extension Workshop have been merged: https://github.com/mozilla/extension-workshop/pull/527
