### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by ankitharendra** [mdn/sprints#1845]
# Request type
The page of APIs/DOM is not showing all the contents.
![image](https://user-images.githubusercontent.com/50439257/61290726-2d8e5800-a7ea-11e9-836d-48571778092d.png)

**Comment by Elchi3** [comment]
Thanks for your report! I've re-rendered this page and it seems to be back now. Might have been a transient rendering error. Let us know if you see this again.
