### ISSUE TITLE
absent Learn/Performance/JavaScript page

### ISSUE THREAD

**Issue by davojta** [mdn/sprints#1846]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I am trying to open https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript
from that page - https://developer.mozilla.org/en-US/docs/Web/Performance

**Comment by chrisdavidmills** [comment]
This page does not exist yet; it is marked as a page yet to be written. We will write it in the future.

**Comment by davojta** [comment]
@chrisdavidmills thank you for closing that - I have missed the section title!
