### ISSUE TITLE
Incorrect info on article about JavaScript keyword undefined

### ISSUE THREAD

**Issue by bobOnGitHub** [mdn/sprints#1848]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#Typeof_operator_and_undefined

In relation to 

```
// x has not been declared before
if (typeof x === 'undefined') { // evaluates to true without errors
   // these statements execute
}

if (x === undefined) { // throws a ReferenceError

}
```

it says;

"However, this kind of technique should be avoided. .....checking the existence of a variable in the global context can be done by checking the existence of a property on the global object (using the in operator, for instance)."

However,

where the var abc is not declared....

`(abc in window)` ( browser )

or 

`(abc in global)` (node)

throws 

`ReferenceError: abc is not defined`

**Comment by chrisdavidmills** [comment]
I've investigated this, and found that it does work as described, but the item you are checking the existence of using the `in` operator needs to be put in quotes for it to work. For example:

```
if ('x' in window) {
  // these statements execute only if x is defined globally 
}
```

This works as you'd expect. The text on the page wasn't very clear orignally, so I've expended it to make things clearer.

Thanks for reporting!

**Comment by bobOnGitHub** [comment]
Yeah, my bad ; I should have checked on the "in" syntax.  

The text is obviously clearer now though and it may save someone else scratching their head in the future.

However,......

I'm always a bit needled when I see "don't do this" coding practice comments* ; there is very often an edge case where whatever is being dismissed is in fact the right if not only way to go.

So, in the article it says "However, this kind of technique should be avoided." but it doesn't say _why_ it should be avoided. What are the possible negative consequences of using  

```
if (typeof x === 'undefined') { // evaluates to true without errors
   // these statements execute
}
```
which don't arise with

```
if( !("x" in window)){
{
```
besides the first not being specific about where exactly x was declared/defined ?

Note that you can have the case where x is declared but undefined ; `window.x = undefined`
which makes each of the above checks appropriate in different circumstances. 

(*which is what will have initially goaded me into action.)

**Comment by chrisdavidmills** [comment]
@bobOnGitHub yeah, you've got a good point here. It didn't offer any reason for it being not the way to go, so doesn't come across as great advice. I've updated the wording, so the `"x" in window` version is presented as another alternative.
