### ISSUE TITLE
mouseleave is missing in the "Related topics" sidebar

### ISSUE THREAD

**Issue by p-himik** [mdn/sprints#1849]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Take a look at e.g. this page: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event
It mentions `mouseleave` and even links to it, however `mouseleave` is not present in the left side panel under the "Events" section. I tried to edit the page for `mouseleave` event but apparently the "Related topics" panel is set up somewhere else, hence this issue.

**Comment by jmswisher** [comment]
`mouseleave` is now present in that sidebar.
