### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

### ISSUE THREAD

**Issue by SongJuXin** [mdn/sprints#1853]
# Request type

- [ ] Correction or update

# Details

On this [page ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)/Description
>Unlike Promise.resolve(2).then(() => {}, () => {}) (which will be resolved with undefined), Promise.resolve(2).finally(() => {}) will be resolved with 2.
Similarly, unlike Promise.reject(3).then(() => {}, () => {}) (which will be fulfilled with undefined), Promise.reject(3).finally(() => {}) will be rejected with 3.

I'm a noob.I think the current answer is incorrect.It should be as follows:
Unlike Promise.resolve(2).then(() => {}, () => {}) (which will be resolved with **2**), Promise.resolve(2).finally(() => {}) will be resolved with **undefined**.
Similarly, unlike Promise.reject(3).then(() => {}, () => {}) (which will be fulfilled with **3**), Promise.reject(3).finally(() => {}) will be rejected with **undefined**.

**Comment by Elchi3** [comment]
Can you provide a code example that shows the behavior?

**Comment by SongJuXin** [comment]
Actually,I don't really understand the description.
In my opinion,I think `Promise.resolve(2).then((result) => {console.log(result)}, () => {})` will be printed `2`,and `Promise.resolve(2).finally((result) => {console.log(result)})` will be printed `undefined`.It is different between what I said and the offcal document.

**Comment by Elchi3** [comment]
Thanks! I'm afraid I don't understand this description or the comparison it tries to draw either. I will see if the original author is contactable or if someone else might know.

**Comment by chrisdavidmills** [comment]
The text on the page looks correct to me. It is basically saying that the examples that use `.then()` won't return anything because you are not passing a value through to the `then()` block to return. But the examples that use `finally()` do return a value because they will always return the end state of the promise chain, regardless of what that is, so therefore you don't need to return an explicit value.

I put together a quick example to demonstrate this in action; see if this clears things up for you:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Promise finally test</title>
  </head>
  <body>

  </body>
  <script>
    function test1() {
      return Promise.resolve(2).then(() => {}, () => {});
    }

    test1().then((result) => ( console.log('test 1 result: ' + result)));

    function test2() {
      return Promise.resolve(2).finally(() => {});
    }

    test2().then((result) => ( console.log('test 2 result: ' + result)));

    function test3() {
      return Promise.reject(3).then(() => {}, () => {});
    }

    test3().then((result) => ( console.log('test 3 result: ' + result)));

    function test4() {
      return Promise.reject(3).finally(() => {});
    }

    test4().catch((result) => ( console.log('test 4 result: ' + result)));
  </script>
</html>
```

**Comment by SongJuXin** [comment]
@chrisdavidmills Thank you for your code.You’re the greatest! The key of my puzzle is  that I don' understand  what is promise .

I just knew promise could return a promise before I saw your code. Now I know promise own two  property ,one is 'status' and the other is 'value'.The value will be deliverd next promise.

The problem isn't exist.I'll close the issue.
Thanks again.
