### ISSUE TITLE
https://www.mozilla.org/en-US/firefox/organizations/all/

### ISSUE THREAD

**Issue by jozsefvolgyi** [mdn/sprints#1854]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details
Hello,
The "data-esr-versions" tag contains incorrect data:
"html class="windows x86 no-js" lang="en" dir="ltr" data-latest-firefox="68.0.1" data-esr-versions="**60.8.0 68.0.1**" data-gtm-container-id="GTM-MW3R8V"  data-stub-attribution-rate="1.0""

**Comment by chrisdavidmills** [comment]
This is a place to file bugs about MDN content; the correct place to file bugs about mozilla.org is https://bugzilla.mozilla.org. Please refile there. Thanks!
