### ISSUE TITLE
Bad link for "Spread syntax" article

### ISSUE THREAD

**Issue by threecleartones** [mdn/sprints#1861]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

While reading the article on the `apply` function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

I saw the link in the second intro note to the "Spread syntax" article, which currently points to a "Not found" page at:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Spread%20syntax

but a Google search for the article shows it exists at:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. A simple bad link; I've fixed it, and cleaned up the note slightly.
