### ISSUE TITLE
Outdated images on Debugger UI Tour

### ISSUE THREAD

**Issue by johnsmith098096** [mdn/sprints#1862]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The "button to control whether to (1) ignore all exceptions, (2) break on uncaught exceptions, or (3) break on all exceptions." in the page https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Toolbar is deleted in versions 64+, but still exists in this guide.

**Comment by irenesmith** [comment]
Thank you for letting us know. A full page update has been planned.

**Comment by irenesmith** [comment]
Thank you for your comments. The page has been updated to show only the new UI features.
