### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Traversing_an_HTML_table_with_JavaScript_and_DOM_Interfaces

### ISSUE THREAD

**Issue by arshag** [mdn/sprints#1863]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

In the "Hiding a column ..." code at the bottom of the page, I think the row and column indexes are reversed, resulting in displaying the first row, not the first column. I flipped ```"cell is:" + j + i ``` in the inner for loop as one way to get desired effect. Apologize if I misinterpreted the lesson.

**Comment by irenesmith** [comment]
I changed the variable names in the example to row and col to make it clear what is happening. In the original code, j represented the row and i the column.

The example creates a table with two rows and two columns. As it does so, if column is 1, the background is defined as red. Column 2 is defined with display: none, making it invisible.

Run the code and use the page inspector (press Ctrl + Shift + C on Windows or Linux or Cmd + Shift + C on macOS) to look at the contents of the generated table and you will see that there are two rows and two columns.

Does the change make it easier to see what is going on?

**Comment by irenesmith** [comment]
The rest of the page could probably use an update as well, so keeping this open for now.
