### ISSUE TITLE
content-box and border-box definitions swapped?

### ISSUE THREAD

**Issue by ritiksingla** [mdn/sprints#1865]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
I think that content-box and border-box definitions are swapped!

Acceptance criteria:
[] mark as resolved

**Comment by estelle** [comment]
I added examples in the text to hopefully help clarify.
