### ISSUE TITLE
WebExt Theme updates

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1867]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
There was some incorrect information on those MDN pages, notably that:

    you needed to use frame and frame_inactive instead of accentcolor when only the latter is needed
    the alias for textcolor was tab_text when it's actually tab_background_text

Please put me/someone familiar with the topic in the loop for technical review next time these docs are updated.

It also mentioned the following incorrect info, but that's our fault for the short notice:

    The properties were removed in Firefox 70 as opposed to 69
    toolbar_text is no longer deprecated/removed

Anyway, I've updated the doc regarding manifest.json to fix this incorrect info. Chris, would it be possible to get an editorial review ? Also, the 2 other docs I mentioned (and potentially others) have to be updated as well.

Need to update the following pages as well:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes/Theme_concepts
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme

See [Bugzilla #1567684](https://bugzilla.mozilla.org/show_bug.cgi?id=1567684) for more details.

# Acceptance criteria
- [ ] All pages listed above have been appropriately updated
- [ ] Changes have been reviewed

**Comment by nt1m** [comment]
@irenesmith Some of these examples need to be updated to use the new properties too: https://github.com/mdn/webextensions-examples

**Comment by caitmuenster** [comment]
@irenesmith, we're going to reference these docs in a blog post that goes live tomorrow at 8am PST; can they be updated by then? @ntim is the technical reviewer for these docs. 

@reblooor, would you be able to update the examples?

**Comment by irenesmith** [comment]
I'm sorry but I didn't even see this message until now (11:15EDT) so no,
but I had planned on working on it today anyway, so I will do as much as I
can.

Irene

**Comment by irenesmith** [comment]
This issue is no longer valid. Because I couldn't accommodate them sooner, the web extensions team has updated the documentation and reviewed the change. Closing this issue.

**Comment by nt1m** [comment]
@irenesmith While I did make most corrections, there might be some that I missed. 
Post-reviewing again, this section still contains inaccurate info about `frame_inactive` and `accentcolor`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Aliases 
The line in question in the table can simply be removed.

More importantly, the examples+the docs all need to be updated to use new property names. I browsed around a bit and I still see some docs with the old property names (accentcolor, textcolor, headerURL) mentioned:

* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes/Using_the_AMO_theme_generator
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes/Theme_concepts
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/update
* https://github.com/mdn/webextensions-examples (there are some theme related examples in there)
* I might have missed some...

For all of these you can simply do a find and replace with the new properties (frame, tab_background_text, theme_frame).

Please let me know if you've got any questions.

**Comment by nt1m** [comment]
Rob made a list of things to update: https://bugzilla.mozilla.org/show_bug.cgi?id=1472740#c34

**Comment by caitmuenster** [comment]
Hi all, Richard Bloor is taking care of this.
