### ISSUE TITLE
NotificationAction objects page not found

### ISSUE THREAD

**Issue by abdvel** [mdn/sprints#1870]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update
- [x] Bug

# Details

URL: https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction
Referance URL: https://developer.mozilla.org/en-US/docs/Web/API/Notification/actions
Problem: Resource not found.

**Comment by chrisdavidmills** [comment]
There are a number of red links on this page, pointing to pages that haven't been written yet. This isn't currently a hight priority, so I'm clising this for now.
