### ISSUE TITLE
Hyperlinks not working on AJAX page

### ISSUE THREAD

**Issue by SiddharthaAnand** [mdn/sprints#1872]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The "Ajax Chat Tutorial" and the "RSS Ticker with AJAX" links under the Examples section do not work. They throw a 404 Not Found pages once clicked.

- [Ajax Chat Tutorial](http://www.ajaxprojects.com/ajax/tutorialdetails.php?itemid=9)
- [RSS Ticker with AJAX](http://www.ajaxprojects.com/ajax/tutorialdetails.php?itemid=13)

The same links have been copied above. Screenshot of the page has been attached.
<img width="1597" alt="Screen Shot 2019-07-25 at 11 59 34 AM" src="https://user-images.githubusercontent.com/11496456/61851344-4f679900-aed4-11e9-865c-fe7af48b8775.png">

Can I go ahead and remove these links from the page?

**Comment by chrisdavidmills** [comment]
I've removed them. Thanks for spotting!
