### ISSUE TITLE
BigInt page does not mention interaction with JSON

### ISSUE THREAD

**Issue by apaprocki** [mdn/sprints#1874]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) page does not mention or provide any warning that `JSON.stringify()` of any `BigInt` property will raise a `TypeError`. The specification *does* allow, however, for users to opt-in to string encoding of the numbers by specifying a `BigInt.prototype.toJSON()` function:

```
> JSON.stringify(BigInt(1))
TypeError: Do not know how to serialize a BigInt
> BigInt.prototype.toJSON = function() { return this.toString(); }
> JSON.stringify(BigInt(1))
'"1"'
```

This capability was explicitly asked for and [standardized](https://tc39.es/proposal-bigint/#sec-serializejsonproperty) in modification of Step 2. of the `SerializeJSONProperty` algorithm.

This is important enough that it should be clearly stated otherwise many might hit this pitfall when attempting to integrate `BigInt` into their existing applications.

**Comment by Elchi3** [comment]
This is already mentioned on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify but you're right, let's also put this on the main BigInt page, so it has higher chances to be seen.
I've put it here now: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Usage_recommendations

Let me know if there is more we should fix here.
