### ISSUE TITLE
parseFromString link at DOMParser page

### ISSUE THREAD

**Issue by Codereamp** [mdn/sprints#1876]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The link to parseFromString at the page
  https://developer.mozilla.org/en-US/docs/Web/API/DOMParser
at the table below is
  https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString
and leads to "not found page"

**Comment by jmswisher** [comment]
That page has not been written yet. You're welcome to contribute if you're interested!

**Comment by Codereamp** [comment]
> 
> 
> That page has not been written yet. You're welcome to contribute if you're interested!

Thanks, I don't think I'm qualified to contribute. Just as a note, I think that "in progress" page (even a blank one) might contain some neutral content different to "not found" page that appears due to a wrong link. Though I'm not sure it's technically possible.

**Comment by chrisdavidmills** [comment]
This isn't going to be a high priority docs task for the MDN content team any time soon, so I'm closing this for now.
