### ISSUE TITLE
/Web/API/MediaRecorder/mimeType is lacking detail

### ISSUE THREAD

**Issue by amundo** [mdn/sprints#1878]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Currently this page doesn’t:

1. Explain what `mimeType`s are available to authors (The example of `'audio/ogg; codecs=opus'` is very opaque: What is the structure of this? Is there a reference somewhere?)
2. Give examples of creating files of different types using MediaRecorder (if that is possible?)

I have tried (and failed) to create a .wav file using MediaRecorder, but I feel like I’m swinging in the dark because I can’t find explanation as to whether that’s even possible.

**Comment by a2sheppy** [comment]
In issue #1871, I already have plans to write documentation about the `codecs` portion of the MIME type string. This can then tie right into that content. Win-win!

**Comment by a2sheppy** [comment]
Updated the [MediaRecorder.mimeType](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/mimeType) page to provide more information about the `codecs` parameter, with a link to the new article (P1 doc bug)
