### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe says fallback content is allowed

### ISSUE THREAD

**Issue by marcvangend** [mdn/sprints#1883]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
The MDN documentation page says:

> Permitted content: Fallback content, i.e. content that is normally not rendered, but that browsers not supporting the <iframe> element will render. (RSS readers and email clients often show the fallback content instead.)

However the W3 and whatwg standards say:

> An iframe element never has fallback content, as it will always create a nested browsing context, regardless of whether the specified initial contents are successfully used.

As a result, the [W3 validator](https://validator.w3.org) sees fallback content as an error: "Text not allowed in element iframe in this context."

I didn't dare to go and edit the page myself because I'm not sure if it is intentional that fallback content is documented, even if it goes against standards.

**Comment by ExE-Boss** [comment]
The fallback content only applies to&nbsp;really old&nbsp;browsers or&nbsp;some email&nbsp;clients that don’t understand the&nbsp;`<iframe>`&nbsp;tag, which was added in&nbsp;**HTML&nbsp;4**.

If you were to&nbsp;use the&nbsp;W3C validator with HTML&nbsp;3.2 or&nbsp;older, it&nbsp;will tell you that the&nbsp;`<iframe>` element doesn’t exist.

**Comment by marcvangend** [comment]
Fair point. So the question is: what does MDN intend to document? HTML3.2? HTML4? HTML5? All of them? 

In any case, I seems wrong to state that there is permitted content for the iframe element. If fallback content happens to work in older browsers that's a nice trick for those who need it, but should it be listed as if it were part of the standard? IMHO the paragraph about permitted content should at least mention that this goes against the standard.

**Comment by a2sheppy** [comment]
The article should state that fallback content is not allowed, perhaps with a note that older browsers may have once supported it.

**Comment by ExE-Boss** [comment]
Well, that list would only include browsers that are&nbsp;older than **HTML&nbsp;4**, and&nbsp;therefore don’t have an&nbsp;`<iframe>` implementation, which results in&nbsp;them treating it&nbsp;as&nbsp;an&nbsp;unknown element.

**Comment by chrisdavidmills** [comment]
I've just updated the permitted content to "None" — I think it is confusing to state what the behavior was in an old version of HTML that browsers don't support any more.
