### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### ISSUE THREAD

**Issue by alvint** [mdn/sprints#1884]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

The documentation for `Array.map()` correctly mentions that this has been supported since very early browser versions, but the examples use code that won't work in those early browser versions. For example, the below example uses `=>` which came much later and doesn't enjoy universal support:

```
// pass a function to map
const map1 = array1.map(x => x * 2);
```

It's reasonable to assume that many people searching for documentation on how something works will model their own code on the examples, so the example code should match the compatibility of the item described. Examples which don't achieve the same level of compatibility should be clearly marked.

This is probably a systemic issue with the documentation.

**Comment by chrisdavidmills** [comment]
We do cover browser support information back to early versions, but also get a lot of pressure to use more modern JavaScript features in our examples, as we are supposed to be a modern documentation site. We held off updating our examples to use ES6 features until very recently.

It is only IE that doesn't support these features. Most professional web developers that use MDN know about this problem, and we do have information in our beginner's learning articles about using a modern browser when you are learning, but also pointing out why such features might cause compat problems if you are working on a project that needs IE support.

It's a difficult path to tread.
