### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XPIDL

### ISSUE THREAD

**Issue by sigiesec** [mdn/sprints#1886]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The page is marked as obsolete. There is a note at the top stating that the xpidl *tool* has been replaced by the pyxpidl *tool*, however the page is about the XPIDL *syntax*, which, as far as I understand it, is still used. So marking the whole page as obsolete appears not appropriate to me. Or has the XPIDL syntax documentation moved somewhere else? Then this should probably be noted there.

**Comment by marcoscaceres** [comment]
Agree. XPIDL is still in wide use. This shouldn't get the current styling.

**Comment by chrisdavidmills** [comment]
OK, I've moved this back under https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPIDL for now.

**Comment by marcoscaceres** [comment]
Thanks @chrisdavidmills!
