### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by shirish212** [mdn/sprints#1887]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web

this page seems displayed in other language.

![Capture](https://user-images.githubusercontent.com/50163760/62133665-cc43aa00-b2fc-11e9-9594-10eed44c4b23.PNG)

**Comment by chrisdavidmills** [comment]
Fixed; incorrect translation. Thanks for reporting!
