### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/GC_Rooting_Guide

### ISSUE THREAD

**Issue by sigiesec** [mdn/sprints#1888]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Static analysis disallows constructing JS::Rooted<T> as temporaries. This should be mentioned, and ideally explained in some detail, on this page.

**Comment by Elchi3** [comment]
Thanks for your issue. The MDN team doesn't maintain mozilla internal docs anymore and they will disappear from the site once we've migrated to a new platform. Please file this request with the Spidermonkey team.
