### ISSUE TITLE
Update proxy-blocker example

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1891]
Support for PAC-style proxy scripts is going away in Firefox 71 as proxy.register, proxy.unregister and proxy.onProxyError are removed (see bugzilla).

The proxy-blocker example should be updated to no longer use the removed API, and instead use the recommended proxy.onRequest API.

Related to [Webextenstions-examples 410](https://github.com/mdn/webextensions-examples/issues/410)

# Acceptance criteria
- [x] Example has been updated
- [x] PR has been created
- [ ] Changes have been approved and merged

**Comment by irenesmith** [comment]
It turns out that Richard Bloor has already created the updated. The only reason I haven't closed the issue is that I'm waiting for the PR, which I will review and merge. I have also reduced the points to reflect the fact that I'm not updating the code, only reviewing it.

**Comment by jmswisher** [comment]
@irenesmith What's the link to the PR for this?
