### ISSUE TITLE
HTML keygen element Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1893]
See https://trello.com/c/PVBIbVHA/217-html-keygen-element-fx-69 for original trello card

# Acceptance criteria

1. - [x] [Remove support for HTML Keygen](https://bugzilla.mozilla.org/show_bug.cgi?id=1315460) (more useful info available in the [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/SAh1b1R5lrY))

**Comment by a2sheppy** [comment]
* Submitted [BCD PR 4605](https://github.com/mdn/browser-compat-data/pull/4605) labeling `<keygen>` as removed in Firefox 69
