### ISSUE TITLE
CSS display property Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1894]
See https://trello.com/c/d1jXQ7VJ/92-the-display-property-fx-69 for original trello card

# Acceptance criteria

1. - [ ] [[css-display] Implement the multi-keyword syntax for the 'display' property](https://bugzilla.mozilla.org/show_bug.cgi?id=1038294)

**Comment by rachelandrew** [comment]
This is now landing in 70 https://bugzilla.mozilla.org/show_bug.cgi?id=1038294#c29

**Comment by chrisdavidmills** [comment]
Yup, closing this one too ;-)
