### ISSUE TITLE
Proprietary -webkit-/-moz- features Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1895]
See https://trello.com/c/ylLyrwja/12-proprietary-webkit-moz-features-fx-69 for original trello card.

# Acceptance criteria

1. - [x] [Consider unprefixing -moz-user-select](https://bugzilla.mozilla.org/show_bug.cgi?id=1492739) (see also [Intent to ship mail](https://groups.google.com/forum/#!topic/mozilla.dev.platform/XfKl9Jt7ZQ8) for more useful details)

**Comment by a2sheppy** [comment]
BCD was already updated, but I added a mention of the change to Fx69 for devs.
