### ISSUE TITLE
CSS Logical Properties Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1896]
See https://trello.com/c/1CtY17he/51-css-logical-properties-level-1-fx-69 for original trello card

# Acceptance criteria

1. - [x] [Implement overflow-block and overflow-inline properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1470695)

**Comment by rachelandrew** [comment]
I had already partly documented these when I did the logical properties work. ExE Boss has updated the compat data table.

I have submitted a PR for two interactive examples for these pages: https://github.com/mdn/interactive-examples/pull/1415

I have added the line to to the release notes, and flagged the bug as dev-doc-complete.
