### ISSUE TITLE
CSS Containment Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1897]
See https://trello.com/c/AQOpkXpT/3-css-containment-fx-69 for original trello card

# Acceptance criteria

1. - [ ] [Enable pref for CSS Containment (layout.css.contain.enabled)](https://bugzilla.mozilla.org/show_bug.cgi?id=1487493)
2. - [ ] Investigate the other items on the trello card to see if anything else needs doing
3. - [ ] Write short tutorial covering using containment?

Slightly higher points estimate here thhan you might expect, because I think maybe we need to investigate the oter bugs on the trello card, see if anything else needs doing, maybe write a short tutorial about containment?

**Comment by rachelandrew** [comment]
@chrisdavidmills I've been poking around this to try and figure out the status  and I note that here it is listed as being Firefox 70 https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#contain-property.

There is also another ticket for the work open #1555 

Other things on the Trello card which relate to containment are as yet open, and not flagged for Fx 69 or 70.

So, I'm a bit confused as to what is actually shipping. Is there some more information anywhere I'm missing?

**Comment by chrisdavidmills** [comment]
Ah, looks like this one slipped to 70 since I put it in our sprint system!

I'll close this one, and re-add it when we get round to Fx70
