### ISSUE TITLE
CSS Text Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1898]
See https://trello.com/c/FdS8hdQo/97-css-text-eg-text-text-decoration-fx-69 for the original trello card

1. - [x] [Implement line-break property of CSS3 Text](https://bugzilla.mozilla.org/show_bug.cgi?id=1011369) (page exists, BCD needs updating, example/interactive example needs adding, data needs updating to add anywhere value)
2. - [x] [Implement line-break: anywhere](https://bugzilla.mozilla.org/show_bug.cgi?id=1531715) (see above also)
3. - [x] [[css-text-decor-4] Implement text-underline-offset](https://bugzilla.mozilla.org/show_bug.cgi?id=1552062) (page doesn't yet exist)
4. - [x] [[css-text-decor-4] Implement text-decoration-width for controlling underline thickness](https://bugzilla.mozilla.org/show_bug.cgi?id=1440014) — renamed text-decoration-thickness, see https://github.com/w3c/csswg-drafts/commit/ffbfa0685c9a1714411b19c0b4abab6a01d5bd48 (page doesn't yet exist)
5. - [x] [Implement locale-specific casing behavior for Lithuanian](https://bugzilla.mozilla.org/show_bug.cgi?id=1322992) — it makes sense to add an example to the `text-transform` page to demonstrate this; not sure about other places. (needs an example adding)
6. - [x] [Implement the break-spaces value of the white-space property](https://bugzilla.mozilla.org/show_bug.cgi?id=1351432) (page exists, small updates needed, including BCD)

**Comment by rachelandrew** [comment]
PR for Compat data for white-space: break-spaces: https://github.com/mdn/browser-compat-data/pull/4624

**Comment by rachelandrew** [comment]
PR for compat data line-break: https://github.com/mdn/browser-compat-data/pull/4646

**Comment by rachelandrew** [comment]
PR to add new properties of `line-break` and `white-space` https://github.com/mdn/data/pull/381

**Comment by rachelandrew** [comment]
Added the Lithuanian example to text-transform https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#lowercase_lithuanian and updated the release docs.

**Comment by rachelandrew** [comment]
Updated release docs to add the line-break and break-spaces info.

**Comment by chrisdavidmills** [comment]
As a note — `text-underline-offset` and `text-decoration-thickness` were added to BCD in https://github.com/mdn/browser-compat-data/pull/4612/files, and show that they were added in Fx 69 and 70 respectively, but both behind a pref. As a result, neither have been aded to the 69 rel notes.
