### ISSUE TITLE
CSS Lists Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1900]
See https://trello.com/c/ihoF34ET/172-css-lists-level-3-fx-69 for original trello card.

# Acceptance criteria

1. - [ ] [Restrict the properties that apply to ::marker for now.](https://bugzilla.mozilla.org/show_bug.cgi?id=1552578) (probably just small updates)

**Comment by rachelandrew** [comment]
Looking through the changeset I believe this is restricting to the properties defined in the spec, which I already documented for `::marker`: https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#Allowable_properties so I don't think we need change anything.
