### ISSUE TITLE
Public and private instance fields Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1901]
See https://trello.com/c/zWPwWg3y/126-public-and-private-instance-fields-fx69 for original trello card.

# Acceptance criteria

1. - [x] [Implement public and private instance fields proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1499448)
2. - [x] [Turn the pref for public fields on by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1555464) see also (intent to ship)[https://groups.google.com/forum/#!topic/mozilla.dev.platform/GhSNChVLgZQ]. This is enabled in Chrome since v72, so probably worth documenting soon.

Seems pretty simple, but high estimate set, as I know there are usually a lot of places in the JS ref docs to update references to things.

**Comment by chrisdavidmills** [comment]
While writing the Fx 69 release post, I was doing some testing. It turns out that only public instance fields are supported in Firefox at the moment, with private ones to follow some time later.

Jason Orendorff explains it nicely here: https://bugzilla.mozilla.org/show_bug.cgi?id=1555464#c3

I wrote the following example, which doesn't currently work in Firefox, but does in Chrome. If you remove the hash symbols and make the private fields public, it does work in Firefox.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ES class tests</title>
  </head>
  <body>
    <script>
    class Product {
      name;
      #tax = 0.2;
      #basePrice;
      price;

      constructor(name, basePrice) {
        this.name = name;
        this.#basePrice = basePrice;
        this.price = (basePrice * (1 + this.#tax)).toFixed(2);
      }
    }

    let bakedBeans = new Product('Baked Beans', 0.59);
    console.log(`${bakedBeans.name} cost $${bakedBeans.price}.`);

    </script>
  </body>
</html>
```

**Comment by Elchi3** [comment]
Thank you, Chris! The docs are on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_elements. I will add a compat table to take that info into account.

**Comment by Elchi3** [comment]
Compat data: https://github.com/mdn/browser-compat-data/pull/4711

**Comment by Elchi3** [comment]
Compat data was merged and I've added the table to the MDN pages.

Also added to release notes https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#JavaScript

Classes page mentions it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Field_declarations

New page on class elements https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_elements

**Comment by Elchi3** [comment]
I've marked the bugs as dev-doc-complete. Let me know if I've forgotten anything. Closing.

**Comment by chrisdavidmills** [comment]
Nice one @Elchi3 ! So, quick review:

>  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_elements

Looks fine; just fixed a couple of typos. My only thoughts — I see these referred to as fields everywhere, but you call them elements in the page title and slug. Wouldn't fields be more intuitive?

Everything else looked fine, but may need a little changing *if* you make the change suggested above.

> https://bugzilla.mozilla.org/show_bug.cgi?id=1555464#c15

You probably don't need to repeat this all here. Just say something like "Documentation completed; see <link to GH issue comment> for the specifics of what has been done. Please could you give the docs a review?" ?

**Comment by Elchi3** [comment]
> Looks fine; just fixed a couple of typos. My only thoughts — I see these referred to as fields everywhere, but you call them elements in the page title and slug. Wouldn't fields be more intuitive?

I'm not the main author of this page but I've renamed it now. It makes sense so that people find it better.

> You probably don't need to repeat this all here. Just say something like "Documentation completed; see for the specifics of what has been done. Please could you give the docs a review?" ?

OK
