### ISSUE TITLE
Promise-related bugs Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1902]
See https://trello.com/c/0SiTrQJ2/201-promise-related-bugs-fx-69 for original trello card

# Acceptance criteria

1. - [ ] [Enable promise rejection event](https://bugzilla.mozilla.org/show_bug.cgi?id=1525554)

**Comment by Elchi3** [comment]
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1525554#c32
