### ISSUE TITLE
DOM general enhancements Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1904]
See https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-69 for original trello card

# Acceptance criteria

1. - [x] **(sheppy)** [Consider moving document.open/write/close from HTMLDocument to Document](https://bugzilla.mozilla.org/show_bug.cgi?id=1549560) (probably just needs a rel note)
2. - [x] **(sheppy)** [Implement Blob.text()/Blob.arrayBuffer()/Blob.stream()](https://bugzilla.mozilla.org/show_bug.cgi?id=1557121) (pages exist, but need cleaning up, examples writing, etc.)
3. - [x] **(sheppy)** [Move HTMLDocument color properties to Document](https://bugzilla.mozilla.org/show_bug.cgi?id=1555980) (see also [Intent to implement & ship](https://mail.google.com/mail/u/0/#inbox/FMfcgxwCgzDLKBtQZWZqwCmMlqvmSlzq)) (just needs a rel note)
4. - [x] **sheppy** [Implement AbstractRange and StaticRange](https://bugzilla.mozilla.org/show_bug.cgi?id=1444847) (Range is already documented; this would require AbstractRange to be created, and the bits that are defined on there moved there, and a StaticRange page created, with links to the AbstractRange features)
5. - [x] **(sheppy)** [User-Agent string needn't reveal a user is running 32-bit Firefox on a 64-bit OS](https://bugzilla.mozilla.org/show_bug.cgi?id=1559747) (minor update)
6. - [x] **(sheppy)** [Change DOMQuad bounds to getBounds() as per specification](https://bugzilla.mozilla.org/show_bug.cgi?id=1454622) (create getBounds page, update BCD to indicate alternative name?)
7. - [X] **sheppy** [Remove DOMMatrix.prototype.scaleNonUniformSelf()](https://bugzilla.mozilla.org/show_bug.cgi?id=1560119) (minor update)
8. - [x] **(sheppy)** [Consider moving execCommand, queryCommand* and designMode from HTMLDocument to Document](https://bugzilla.mozilla.org/show_bug.cgi?id=1415270) (just needs a rel note?)
9. - [X] **sheppy** [DOMMatrix.prototype.translate doesn't work with one argument](https://bugzilla.mozilla.org/show_bug.cgi?id=1397949) (minor syntax update)
10. - [X] ~[Implement [LegacyWindowAlias] extended attribute (for WebKitCSSMatrix, webkitURL)](https://bugzilla.mozilla.org/show_bug.cgi?id=1366738) (a bit obscure; might need help working it out)~
11. - [X] **sheppy** [Support six-parameter version of DOMMatrix scale method](https://bugzilla.mozilla.org/show_bug.cgi?id=1397945) (minor update, possibly just a rel note)
12. - [X] **sheppy** [Add DOMMatrix/DOMPoint, etc. support in web workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1420580) (minor updates)
13. - [X] **sheppy** [Implement DOMMatrix.fromMatrix](https://bugzilla.mozilla.org/show_bug.cgi?id=1560462) (page needs creating; update BCD?)

**Comment by chrisdavidmills** [comment]
Note: rel notes added for:

* Implement Blob.text()/Blob.arrayBuffer()/Blob.stream()
* Implement DOMMatrix.fromMatrix
* Support six-parameter version of DOMMatrix scale method
* DOMMatrix.prototype.translate doesn't work with one argument
* Remove DOMMatrix.prototype.scaleNonUniformSelf()
* User-Agent string needn't reveal a user is running 32-bit Firefox on a 64-bit OS
* Implement AbstractRange and StaticRange

See https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#APIs I added these early so that they would be there in time for the 69 release. Rest of the work still needs doing.

**Comment by a2sheppy** [comment]
@chrisdavidmills I'm not convinced we need to do anything here. The changes are so esoterical in general in terms of how they impact web developers. It's basically a way to streamline defining these legacy types in specifications so that they can be easily declared as aliases of the true interfaces rather than as copies of those interfaces.

**Comment by chrisdavidmills** [comment]
@a2sheppy I wasn't sure, so I wanted someone to offer a second opinion. If you don't think anything needs doing, then that's fine by me. Just remove the DDN from the bug.
