### ISSUE TITLE
SVG-related changes Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1906]
See https://trello.com/c/g2gJFbtM/205-svg-related-changes-fx-69 for original trello card

# Acceptance criteria

1. - [x] [Implement isPointInFill() and isPointInStroke() methods of SVGGeometryElement](https://bugzilla.mozilla.org/show_bug.cgi?id=1325319) (already documented, need examples adding and BCD updating)

**Comment by chrisdavidmills** [comment]
Note: rel note added to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#SVG, so it was there in time for the 69 release. Other work still needs doing.

**Comment by SebastianZ** [comment]
I've added a [PR to update the BCD data](https://github.com/mdn/browser-compat-data/pull/4767). Examples will follow.

Sebastian

**Comment by SebastianZ** [comment]
Both [`isPointInFill()`](https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInFill#Example) and [`isPointInStroke()`](https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInStroke#Example) now also have live samples.

Sebastian

**Comment by chrisdavidmills** [comment]
@SebastianZ thanks Sebastian, you are super-awesome!
