### ISSUE TITLE
Microtask API Firefox 69 (sheppy)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1907]
See https://trello.com/c/KpUS9HAC/215-microtask-api-fx-69 for original trello card.

# Acceptance criteria

- [x] [Implement queueMicrotask()](https://bugzilla.mozilla.org/show_bug.cgi?id=1480236)
- [x] Add something to cover it at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous? Or maybe a short tutorial somewhere else?
- [ ] anything else needed?

**Comment by chrisdavidmills** [comment]
@a2sheppy I ended up doing the ref page and BCD myself, because I need them for tomorrow's release, given that I'm mentioned this in the 69 release blog post:

* https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask (actually mostly written already by another contributor; I just filled it out a bit.)
* https://github.com/mdn/browser-compat-data/pull/4754

**Comment by chrisdavidmills** [comment]
Rel note added to Fx 69 too: 1480236

**Comment by a2sheppy** [comment]
I've written the microtask guide, and there's a subpage that has more detailed information about the internals, but that's labeled and rightly so a draft.

https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

**Comment by a2sheppy** [comment]
I've also asked for a review in #jsapi

**Comment by a2sheppy** [comment]
Added a section [to the end of Using promises](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#When_promises_and_tasks_collide) to cover how microtasks can be used to help with promises. This mostly just transcludes content form the microtask guide, but with an intro specific to this page.
