### ISSUE TITLE
WebVTT API Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1908]
See https://trello.com/c/POeJebj7/177-webvtt-api-fx-69 for original trello card

# Acceptance criteria

1. - [ ] [[webvtt] HTMLTrackElement should not load resource when its text track is disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1550633) (minor update)
2. - [x] [[webvtt] Restrict css attributes in ::cue.](https://bugzilla.mozilla.org/show_bug.cgi?id=1321488) (minor update)

**Comment by a2sheppy** [comment]
* Minor cleanup to the [::cue](https://developer.mozilla.org/en-US/docs/Web/CSS/::cue) page to improve flow of the content and to alphabetize the names of the permitted CSS properties.
* Submitted [BCD PR 4571](https://github.com/mdn/browser-compat-data/pull/4571) to add indication to `::cue` that Firefox 69 now enforces the spec-defined limits on which CSS properties can be used in cues ([bug 1321488](https://bugzilla.mozilla.org/show_bug.cgi?id=1321488)).
