### ISSUE TITLE
Cross-Origin related bugs Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1912]
See https://trello.com/c/ZQjg0cm4/175-cross-origin-related-bugs-fx-69 for original trello card

# Acceptance criteria

1. - [x] [Support Cross Origin Resource Policy (CORP) (Previously From-Origin)](https://bugzilla.mozilla.org/show_bug.cgi?id=1459573).
2. - [x] [[CORS] Add wildcard to Access-Control-Expose-Headers, Access-Control-Allow-Methods, and Access-Control-Allow-Headers](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)

**Comment by Elchi3** [comment]
This is all done now.
