### ISSUE TITLE
Primary DevTool updates [Irene] (e.g. Console, CSS pane, JS debugger) Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1913]
See https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-js-debugger-fx-69 for orginal trello card

# Acceptance criteria

1. - [x] [Change panel order to reflect popularity](https://bugzilla.mozilla.org/show_bug.cgi?id=1558630)
3. - [x] [In the sources list, extension entries should have their name instead of their uuid](https://bugzilla.mozilla.org/show_bug.cgi?id=1486416)

**Comment by chrisdavidmills** [comment]
Items 1 and 3 above have had a note added to the rel notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#Developer_tools

I wasn't sure about 2, because AFAIK subgrid is still not enabled by default...?

**Comment by irenesmith** [comment]
Removing the subgrid entry. As Chris commented above, this has been pushed out past 69 because of a bug. I am going to create a separate subgrid issue.

**Comment by irenesmith** [comment]
Added a paragraph to the [Debugger UI tour](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour) section describing the [source list pane](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Source_pane) mentioning that extensions will be listed by name in the source list pane from Firefox 69 on. Also added a new image to the page.
