### ISSUE TITLE
General WebExtension API enhancements [Irene]

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1914]
See https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-69 for original trello card

# Acceptance criteria

1. - [x] [Improve the TopSites WebExtension API](https://bugzilla.mozilla.org/show_bug.cgi?id=1547669)

**Comment by chrisdavidmills** [comment]
I've added a rel note for this one — https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#Changes_for_add-on_developers — so it is available for the 69 release. The rest of the work still needs doing.

**Comment by irenesmith** [comment]
Updated [topSites.get](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/topSites/get) to include the new parameters.
