### ISSUE TITLE
Page actions bugs Firefox 69 [Irene]

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1915]
See https://trello.com/c/vsKZdybA/115-page-actions-fx-69 for oroginal trello card

# Acceptance criteria

1. - [ ] [Enable userScripts API on release channels](Enable userScripts API on release channels)

**Comment by irenesmith** [comment]
I have added a notice to the 69 release notes that the UserScripts API is now enabled by default.
