### ISSUE TITLE
Get a decision about "using GitHub" strategy

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1921]
In https://github.com/mdn/sprints/issues/1795 we wrote a document outlining options for moving the MDN docs to Git/GitHub.

In this issue we'd like to reach a decision about which option(s) to pursue.

This will involve:

* writing a proposal that outlines the different available options and provides a tentative proposal of which one to choose. 
* Getting feedback on the proposal from all the stakeholders, and refining the document to make it as cohesive as possible. 
* scheduling a meeting with decision makers, verify the outlined decision.  
* getting agreement on a proposal.

AC: we have agreement on a proposal for which migration option(s) to explore, and in what order.

**Comment by jmswisher** [comment]
@wbamberg @atopal Is this issue still relevant? Can it be closed?

**Comment by atopal** [comment]
I'm closing this as we have broken the work here down already into more useful chunks
