### ISSUE TITLE
U - Account deletion for users who have not made contributions on MDN

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1922]
# User Story
As a user, I want to be able to easily delete my account, so that I can have all of my personal information deleted from the system if I choose.

# Acceptance Criteria
- [ ] Link to delete account from profile page
- [ ] Overlay when link is clicked that asks about account deletion
- [ ] Upon confirming to delete their account, the user's account and profile page is deleted from the system.
- [ ] Modal is accessible on all devices

# Design

InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705983_Account_-_Profile_-_Delete_Account_-no_Contrib-
Zeplin: https://zpl.io/anL4B0Y

**Comment by peterbe** [comment]
I would prefer if we don't distinguish between "have made contributions" and those that "have not made contributions". A user is a user. Whether or not they've made contributions is a small detail as far as the UI goes. 
In https://github.com/mdn/kuma/pull/6149 what I did was this:
```jinja
        <form action="" method="post">

          {# If the user no revisions, there's nothing to ask. #}
          {% if revisions.exists() %}
          {{ form }}
          {% endif %}

          <button type="submit" class="button positive">{{ _('Delete my account') }}</button>
        </form>
```

So, before it renders the form it first figures out the number of contributions you have. If that number is 0 it hides the whole part radio-buttons part of the form. 

I believe we should implement it the same way in the new read-only site. 

Also, with Yari there'll soon be a point where all of this needs to change anyway. 
The day when the Wiki is gone, a user might still want to delete hes account and then it won't make sense to ask our server "How many revisions does this user have in our database?"
That day, we just need to make this diff:

```diff
        <form action="" method="post">

-         {# If the user no revisions, there's nothing to ask. #}
-         {% if revisions.exists() %}
-         {{ form }}
-         {% endif %}

          <button type="submit" class="button positive">{{ _('Delete my account') }}</button>
        </form>
```

**Comment by peterbe** [comment]
@atopal Do you know why this is still open? The only thing we haven't done is "Modal is accessible on all devices".

**Comment by schalkneethling** [comment]
> @atopal Do you know why this is still open? The only thing we haven't done is "Modal is accessible on all devices".

No idea. Also, we have decided for it to not be a modal on mobile so, those acceptance criteria need to be changed. Perhaps it was just overlooked? @chinikes

**Comment by peterbe** [comment]
I think the only thing was about mentioning your username in the radio select choices. https://github.com/mdn/kuma/pull/6517 which was merged into master. 
So I can't think of any more work that's need for this sprint epic *or* for https://github.com/mdn/sprints/issues/1947 either. 

Close this and #1947?

**Comment by atopal** [comment]
Yeah, I think we can close this
