### ISSUE TITLE
Write an article on the philosophy behind RWD

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#1923]
# User story
As a web developer I want to understand what is meant by responsive web design and understand what other materials there are on MDN that relate to it.

# Acceptance criteria

- [ ]  Article on RWD written
- [ ] Article reviewed
- [x] Tickets raised for any material that needs adding to MDN to support this page

**Comment by chrisdavidmills** [comment]
In my front end development learning pathway, I had a loose outline for this, along the lines of:

* Theory of responsive web design (20-25 hrs)
  * Overview of RWD: How we used to build sites (e.g. fixed width, separate mobi site), the modern device landscape and why it changed things. For actual practical coverage, link to articles in the CSS layout module that explain the technologies indolved. 
  * Fluid / liquid layouts, and other responsive staples
  * Media queries
  * Responsive media (keeping file sizes down, using <picture>, etc.)
  * Responsive typography
  * Etc.

As the early comment says, we'll need to think about what needs adding to the rest of the CSS course to cover the actual practice stuff behind the theory.

**Comment by rachelandrew** [comment]
So I thought we were just doing an overview page ... do you want a module as outlined above or an overview page as we discussed. Just making sure I'm not confused!

**Comment by chrisdavidmills** [comment]
Sorry, that was confusing! To be clear — for now let's just write the overview as discuss (which I thought would cover the topics listed above, plus whatever else you thought)

After you've written it, let's have a think about what gaps we have in the CSS modules, i.e. what features mentioned in the overview are not covered.

**Comment by rachelandrew** [comment]
no problem, just wanted to check. I have just got off a redeye from DC so it's not going to take much to confuse me.

**Comment by rachelandrew** [comment]
@chrisdavidmills  Here is a first pass at an overview page. I wanted to try and set responsive design in place with a bit of history and then to explain it really is just a term to describe an approach, which is pretty much the default now. I've then linked to various things around the docs.

I think the main thing we could do with adding to Learn would be an nice easy intro to media queries and approaches to building a responsive site, I created a ticket for that.

I was going to put in more of the embedded examples but these don't work so well when trying to demo responsiveness, so I thought perhaps each of the small examples I could perhaps add a screenshot at mobile size and one at desktop, to show how flex, grid, multicol items behave? Let me know what you think.

**Comment by chrisdavidmills** [comment]
Here you go!

Feedback on https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

Historic website layout section

* Sounds good to me.
* I wonder if you could create a very simple fixed width and liquid site example, and link to them from the section, so readers can go and play with them and understand better what we mean.

Responsive typography

* What is here so far is good. I'd like to see some mention of using viewport units for responsive typography, you know, this kind of stuff: https://zellwk.com/blog/viewport-based-typography/#using-viewport-units-for-typography. This is pretty popular, and very interesting technique.

General

* Reads really well, thanks!
* It would be nice for there to be more examples available, yes. I think it is OK if you create examples on GitHub and link to them, letting the ereader know they need to see them on a separate page for them to understand how they work. Providing screenshots would also be good, yes.

**Comment by rachelandrew** [comment]
@chrisdavidmills this now has a bunch of screenshots and examples placed throughout. I was hesitant to show the vw approach as it has a11y issues. Checked with some a11y folk however and it seems that as long as you always do it with calc from a base font size it is fine. So I have stressed that as key to the technique.

**Comment by chrisdavidmills** [comment]
This looks super @rachelandrew , thanks for the updates! I've given it another light copy edit, and tweaked a few bits, plus I've added the sidebar menu, previous and next buttons, etc.

The only other thing I need to do is file a PR to add this article to the sidebar menu. I'll do that next.

**Comment by chrisdavidmills** [comment]
PR filed to add this to learn sidebar: https://github.com/mdn/kumascript/pull/1217
