### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ntsliyang** [mdn/sprints#1932]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Under [User-defined iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#User-defined_iterables), the link redirected by **computed property** is currently 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

Instead, I think it should be 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

**Comment by chrisdavidmills** [comment]
Fixed, thanks for reporting! This was all caused by a single missing fwd slash causing the URL to resolve incorrectly ;-)
