### ISSUE TITLE
broken link!

### ISSUE THREAD

**Issue by ciskogollo** [mdn/sprints#1933]
https://developer.mozilla.org/es/docs/Web/CSS/Transiciones_de_CSS

On the page attached above, go to visit the following link: https://developer.mozilla.org/samples/cssref/transitions/sample3/
which does not exist!

**Comment by chrisdavidmills** [comment]
Yeah, this demo no longer seems to exist. I've removed the paragraph for now. If you look at the English version, you'll see that the example section is now quite different:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#Examples
