### ISSUE TITLE
Source authors for parts of the learning pathway

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1940]
# User story
As an MDN writer, I want to find authors to help me write the missing parts of the learning pathway, so I can still sleep at night.

Refer to the learning pathways docs spec for more information about each topic:

https://docs.google.com/document/d/1ScMaXxYV01g_5CQx9CuV5ef8h3_L8g-8d2oHFF4guH4/edit?ts=5d3f224b

# Acceptance criteria

1. - [ ] Find author(s) for "Understanding frameworks"
2. - [x] Find author(s) for "Modern tools"
3. - [x] Find author(s) for "HTML Forms"

**Comment by jmswisher** [comment]
@chrisdavidmills says the sourcing is done, so closing.
