### ISSUE TITLE
Research around new Learning Pathways section

### ISSUE THREAD

**Issue by shilili** [mdn/sprints#1943]
To test how users will react to linking to external sites on pathways 

# Acceptance criteria

- [x] Recruiter screener
- [x] Interview/Usability Test Plan
- [x] Recruit 5-8 participants
- [ ] Conduct usability test sessions
- [ ] Share results

# Prototype Link
https://mozilla.invisionapp.com/share/H4TBESKJFRX#/377509960_Pathways_Front-End_Developer

**Comment by jmswisher** [comment]
Parking this for now, until we have researcher again.
