### ISSUE TITLE
Clarify confusing comment in CSS color examples

### ISSUE THREAD

**Issue by dev-nicolaos** [mdn/sprints#1948]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Issue in question: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

The RGB syntax examples contain the following:
```
rgb(255, 0, 153.0) /* ERROR! Don't use fractions. */
```
but further down in the examples...
```
rgb(255, 0, 153.6, 1)
```
...is cited as a valid example.

Furthermore, adding the supposedly buggy line of code to a page works in modern versions of both Chrome and Firefox (it appears they round the decimal value to the nearest integer).

Why does the example in question have an ERROR comment? If this is actually against the spec, I would think that comment should be added to the second example cited as well. If it is merely considered bad practice, I feel the comment should be changed to reflect that.

**Comment by chrisdavidmills** [comment]
You're right, this does seem to work. I've removed the confusing comment. I also can't find anything in the spec to say this shouldn't work. Thanks for reporting.
