### ISSUE TITLE
Archive WeakMap clear function docs?

### ISSUE THREAD

**Issue by zouxiaomingya** [mdn/sprints#1954]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

new WeakMap is not have clear function

**Comment by Elchi3** [comment]
Our removal / archiving policy says to only retire docs when there is no browser implementing the feature anymore, but here IE11 is still supporting WeakMap.clear. 

https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features

We might want to think about our policy. You're right that WeakMap.clear is no longer relevant.
