### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by JamesC01** [mdn/sprints#1955]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Some of the HTML output boxes don't show anything on this page: https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Simple_selectors

The attribute selectors page: https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors has missing info, it shows the usage of the square bracket syntax, but not attaching it to a specific element (it might only show [href], instead of a[href], for example). Also the input code and output of the Substring value attribute selectors section is wrong.

**Comment by chrisdavidmills** [comment]
We've got an all-new set of beginner's CSS docs covering selectors now; see https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors. I think this should fix these issues.
