### ISSUE TITLE
Correction for: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_the_rest_of_an_array_to_a_variable

### ISSUE THREAD

**Issue by amorssy** [mdn/sprints#1959]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details

In the [linked documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_the_rest_of_an_array_to_a_variable), there is the following paragraph:

> Be aware that a SyntaxError will be thrown if a trailing comma is used on the left-hand side with a rest element:

I think this should say "right-hand side" instead of "left-hand side", unless I'm misunderstanding something.

**Comment by Elchi3** [comment]
Left-hand side seems to be correct to me. The rest element on the left side of the "=" sign is the one that can't have the trailing comma.
