### ISSUE TITLE
CSS motion path Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1961]
See https://trello.com/c/Ef3V38Yh/212-css-motion-path-fx-69 for original trello card.

# Acceptance criteria

1. - [ ] [Implement offset-distance for motion path](https://bugzilla.mozilla.org/show_bug.cgi?id=1429299)
2. - [ ] [Implement offset-rotate for motion path](https://bugzilla.mozilla.org/show_bug.cgi?id=1429301)
3. - [ ] [Make offset-rotate animatable](https://bugzilla.mozilla.org/show_bug.cgi?id=1429303)

**Comment by chrisdavidmills** [comment]
I think this stuff is only enabled in Nightly, and hidden behind a pref in Beta/release — I've asked Boris for clarification on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1429299#c14

**Comment by chrisdavidmills** [comment]
Yes, for clarification, this stuff is only enabled in Nightly, and hidden behind the layout.css.motion-path.enabled pref in beta/release. 

I've added BCD at https://github.com/mdn/browser-compat-data/pull/4708. Note sure if there is much mroe work to do on this.

**Comment by chrisdavidmills** [comment]
I have gone on to make sure the rest of the documentation is as complete as it needs to be for now:

1. Filled in the landing page with a bit more detail: https://developer.mozilla.org/en-US/docs/Web/CSS/Motion_Path
2. Made sure the existing property pages are as complete as they can be for now. See https://developer.mozilla.org/en-US/docs/Web/CSS/Motion_Path#Reference
3. There are interactive examples missing from offset, offset-distance, and offset-rotate. I'm not that fussed about them for now because they are only supposrted by default one browser currently. We can add those later on.

**Comment by BorisChiou** [comment]
I checked the mdn pages of `offset-distance` and `offset-rotate`, and they look good to me. Thanks for updating these and adding the examples.

**Comment by BorisChiou** [comment]
And motion-path page as well. :)

**Comment by chrisdavidmills** [comment]
@BorisChiou thanks for the review!
