### ISSUE TITLE
Update HTTP status 400 page to broaden coverage

### ISSUE THREAD

**Issue by bobOnGitHub** [mdn/sprints#1963]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

[HTTP Error 400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) has since been changed to significantly broaden it's coverage - in particular see https://stackoverflow.com/a/3290198/4779501

**Comment by hamishwillee** [comment]
Closing as "someone has already done the work".

The [current version of the documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) is up to date with the [spec](https://tools.ietf.org/html/rfc7231#section-6.5.1) (there is an line that was removed in the new spec which is still true, and which I am leaving: *The client should not repeat this request without modification*).
