### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by franciscof5** [mdn/sprints#1965]
At this page

https://developer.mozilla.org/pt-BR/docs/Mozilla/Projects

Spider monkeys recent releases link are no working

(https://developer.mozilla.org/pt-BR/docs/Mozilla/SpiderMonkey/Releases)

**Comment by jmswisher** [comment]
Thanks for reporting this. The link was incorrect on the SpiderMonkey page (pulled in via the LandingPageListSubpages macro). I corrected it and updated the Projects page.
