### ISSUE TITLE
Debugging over USB

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1967]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
This page: [Debugging over USB](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_over_USB) was created as a placeholder and needs to have content (updated) from the archived pages.

**Comment by irenesmith** [comment]
The content has been created and reviewed by Julian.

**Comment by irenesmith** [comment]
Reviewed the document with Julian and made a few small updates. There is more work planned for this page in the future, but for now it is done.

**Comment by chrisdavidmills** [comment]
The debugging over USB page you've linked to on here still has a draft banner on it. Is it finished?

Also, is this actually new functionality available in Firefox 69, or is it just an update you've been asked to do? If it is new in 69, what's new about it?

**Comment by chrisdavidmills** [comment]
@irenesmith can you respond to the above comment?

**Comment by irenesmith** [comment]
I've removed the draft banner. My understanding is that this page is complete for now but changes will be needed in the future.
