### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor

### ISSUE THREAD

**Issue by makeitstatic** [mdn/sprints#1969]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Is this still non-standard experimental technology?
W3Schools recommends it as standard.

Perhaps all the info on this page needs a thorough update.

**Comment by chrisdavidmills** [comment]
We'll track it on your other related bug.
