### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/MDN/Feedback

### ISSUE THREAD

**Issue by huangyin2018** [mdn/sprints#1971]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [√] New documentation
- [ ] Correction or update

# Details

There is a mistake in the 6th question:"which country / region do you live in" in the questionnaire for developers and designers from Mdn Web Docs (language:Chinese simplified).You called "中国澳门"（Macau China）as "澳门"（Macau),But Macau is an inherent territory of China,So please correct your mistake immediately  and apologize, I will continue to pay attention, thank you！
![001](https://user-images.githubusercontent.com/38528114/62620426-dfcdc100-b94b-11e9-8340-0f9000cb1724.png)

**Comment by chrisdavidmills** [comment]
@schalkneethling another one abut the survey.

**Comment by schalkneethling** [comment]
I reckon @atopal is the best person for this. Thanks @chrisdavidmills
