### ISSUE TITLE
@font-face descriptors need to be written

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1973]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight (started - was just a copy of the font-weight property, but i got it 33% of the way done.)
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant (needs to be created)
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-stretch (needs to be created)

While the latter two should be created, the font-weight one is beyond necessary.

**Comment by estelle** [comment]
Wrote a draft of https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-stretch

**Comment by rachelandrew** [comment]
Put together a draft for the last missing one: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant

PR for BCD: https://github.com/mdn/browser-compat-data/pull/7042

**Comment by rachelandrew** [comment]
@chrisdavidmills BCD is now showing up for this one

**Comment by chrisdavidmills** [comment]
Great stuff; closing.
