### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Community

### ISSUE THREAD

**Issue by vansjyo** [mdn/sprints#1974]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details
**Subject:** Proposal for a feature

The Mozilla firefox browser does not offer an option to move a tab to a different window session. For example, I have two windows of the browser open, and I want to transfer one tab to the other session. Does the browser tracks sessions or currently open windows for the browser? Is it possible. I have attached a screenshot for reference. Would like to know what the community here thinks about this!
Cheers.

![Screenshot from rec mkv](https://user-images.githubusercontent.com/25532570/62687758-0a1f8d00-b9e5-11e9-8464-ba71fcc8fdcc.png)

**Comment by vansjyo** [comment]
Also, please direct me to the correct place to put up this issue if I have landed at the wrong one.

**Comment by jmswisher** [comment]
Hi @vansjyo! The place to submit feature requests for the Firefox browser is [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox). You will need to create a Bugzilla account in order to submit an issue.
