### ISSUE TITLE
Update slug of article 229510 PaymentRequestEvent.topLevelOrigin -> PaymentRequestEvent.topOrigin

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#1975]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Summary
Move article with URL
`https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequestEvent/topLevelOrigin`
to
`https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequestEvent/topOrigin`

That is, update slug of the article with number `229510` from `topLevelOrigin` to `topOrigin`.

# Details
The spec authors [renamed](https://github.com/w3c/payment-handler/commit/16e9e5ba692240054fe884b8a9feae6e73056163) one attribute from
from `PaymentRequestEvent.topLevelOrigin` to `PaymentRequestEvent.topOrigin`. BCD already has the [new name](https://github.com/mdn/browser-compat-data/blob/65740c63cb8c861f4511f29b3fa3cb75365f6878/api/PaymentRequestEvent.json#L563). I updated the MDN article (content, title), but could not update the slug.

This means MDN has the page, but everything that links to it has a broken link.

**Comment by chrisdavidmills** [comment]
Page moved to https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequestEvent/topOrigin

Thanks for reporting!
