### ISSUE TITLE
Spammer Violapark-droid

### ISSUE THREAD

**Issue by benbucksch** [mdn/sprints#1978]
# Request type
- [x] User conduct: Spam

# Details
https://developer.mozilla.org/en-US/dashboards/revisions?user=Violapark-droid

**Comment by benbucksch** [comment]
He replaced "SSL" with `<a href="https://hosting.review/web-hosting-glossary/#12)">SSL</a>`

**Comment by jmswisher** [comment]
Thanks for the report, and for cleaning up the spam edits you found. This user later made some actually useful edits, so it's possible they thought the link to the glossary on that site was helpful. (I've never previously seen a user start as a spammer and then turn to the light side.) In any case, I will keep an eye on this user.

**Comment by benbucksch** [comment]
Thanks, Janet.
