### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods

### ISSUE THREAD

**Issue by JacksonMalloy** [mdn/sprints#1988]
I am submitting this request to notify MDN of a UX issue regarding the languages drop down on mobile devices. 

Could you please float the drop down on the left side or center of the screen so that people don't accidentally click it while scrolling. 

Thanks, 

Jackson

**Comment by chrisdavidmills** [comment]
@schalkneethling useful feedback here?

**Comment by schalkneethling** [comment]
> I am submitting this request to notify MDN of a UX issue regarding the languages drop down on mobile devices.
> 
> Could you please float the drop down on the left side or center of the screen so that people don't accidentally click it while scrolling.
> 
> Thanks,
> 
> Jackson

Thanks @JacksonMalloy, we are working on our mobile experience which is currently... not great ;) I will copy this feedback to our issues here: https://github.com/mozilla/kuma/issues

**Comment by schalkneethling** [comment]
For reference: https://github.com/mozilla/kuma/issues/5724
