### ISSUE TITLE
Broken link on "getting started on MDN" page

### ISSUE THREAD

**Issue by niekvb** [mdn/sprints#1989]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link "_Update API page layout (30 minutes)_" on the page [Getting started on MDN](https://developer.mozilla.org/en-US/docs/MDN/Getting_started#Option_3_I_like_both_words_and_code) (under Option 3) refers to a page that doesn't exist.

**Comment by chrisdavidmills** [comment]
I've fixed the broken links on this page. Thanks for reporting!
