### ISSUE TITLE
Example of font-variant-east-asian doesn't show anything

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1997]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian
The example is just an exclamation point, which doesn't show what the property does.

**Comment by Mookiepiece** [comment]
I don't know whether I could put some additions here. 
I read some examples from Specifications 
from my tests, I use Win10 and proved "Yu Gothic" Japanese font-family will support ruby(use some katagana) and jis78(use “麹町”) ,  and [traditional] and [simplified]keywords (use “大学”), tests passed on Chrome and Firefox

Here I have two questions:
"Yu Gothic" may not exists on other platforms like Android OSX Linux!
[traditional] and [simplified] keywords do not work in Chinese fonts I tested:宋体 微软雅黑 黑体 maybe those don't support OpenType features

I will try to edit that page later, but wish someone could fix or give some suggestions to the problem I figured

**Comment by chrisdavidmills** [comment]
Looks like this example was fixed. Thanks @Mookiepiece !
