### ISSUE TITLE
text-align-all: create page or not?

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#1998]
text-align is a shorthand for text-align-all and text-align-last. The latter is supported in FF, the former is not. Should we create a page for this property that is in the spec, but not really used?

https://drafts.csswg.org/css-text-3/#propdef-text-align-all

**Comment by rachelandrew** [comment]
@chrisdavidmills this doesn't appear to be supported anywhere, and there is a note in the spec that authors should use `text-align` instead. I think at most we should pop a note on the `text-align` page.

**Comment by chrisdavidmills** [comment]
@rachelandrew let's close this one.
