### ISSUE TITLE
https://developer.mozilla.org/zh-CN/XUL_%E6%95%99%E7%A8%8B/%E8%A1%A8%E6%A0%BC

### ISSUE THREAD

**Issue by 2577873863** [mdn/sprints#1999]
not found 404

**Comment by stonegrape** [comment]
点击按钮“下一页”不能正常跳转到新页面

**Comment by chrisdavidmills** [comment]
What page did you find the broken link on?

**Comment by stonegrape** [comment]
https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/%E5%BC%82%E6%AD%A5/%E7%AE%80%E4%BB%8B

**Comment by stonegrape** [comment]
page:https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/%E5%BC%82%E6%AD%A5/%E7%AE%80%E4%BB%8B

**Comment by stonegrape** [comment]
this page:https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/%E5%BC%82%E6%AD%A5/%E7%AE%80%E4%BB%8B




------------------ 原始邮件 ------------------
发件人: "Chris Mills"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 凌晨4:28
收件人: "mdn/sprints"<sprints@noreply.github.com>;
抄送: "1622313352"<1622313352@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mdn/sprints]https://developer.mozilla.org/zh-CN/XUL_%E6%95%99%E7%A8%8B/%E8%A1%A8%E6%A0%BC(#1999)




What page did you find the broken link on?

**Comment by 2577873863** [comment]
I looked at the form tutorial in the XUL tutorial.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"stonegrape"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月5日(星期四) 上午7:39
收件人:&nbsp;"mdn/sprints"<sprints@noreply.github.com&gt;;
抄送:&nbsp;"张泽豪"<2577873863@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mdn/sprints] https://developer.mozilla.org/zh-CN/XUL_%E6%95%99%E7%A8%8B/%E8%A1%A8%E6%A0%BC (#1999)



this page:https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/%E5%BC%82%E6%AD%A5/%E7%AE%80%E4%BB%8B 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Chris Mills"<notifications@github.com&gt;; 
 发送时间: 2019年8月29日(星期四) 凌晨4:28 
 收件人: "mdn/sprints"<sprints@noreply.github.com&gt;; 
 抄送: "1622313352"<1622313352@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [mdn/sprints]https://developer.mozilla.org/zh-CN/XUL_%E6%95%99%E7%A8%8B/%E8%A1%A8%E6%A0%BC(#1999) 
 
 
 
 
 What page did you find the broken link on?

**Comment by stonegrape** [comment]
已经查看，没有解决



---Original---
