### ISSUE TITLE
Docs: Broken links in Error documentation - Spanish site

### ISSUE THREAD

**Issue by jsk7** [mdn/sprints#2002]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
There're some broken links for the js [Error](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Error) docs.  

<img width="1440" alt="Captura de pantalla 2019-08-11 a la(s) 11 53 13" src="https://user-images.githubusercontent.com/8615216/62835414-a7213680-bc2e-11e9-880a-f163b1f88ed6.png">

If it helps I also notice the spanish version seems quite different compared to [the english version](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**Comment by chrisdavidmills** [comment]
This is because we don't have an active Spanish translation community. I'm clsoing this for now, as we don't have any resources to fix this.

**Comment by jsk7** [comment]
Hi Chris! Is there any way I could contribute to that?

**Comment by chrisdavidmills** [comment]
@jsk7 so, at the moment, our l10n strategy is broken. A couple of locales are OK as we have really passionate community members that keep them up to date, but many others are marred by out of date content. And we don't have the community/resources to keep them up-to-date.

In the next generation of MDN (called stumptown, current at a very early stage), we are attempting to have a proper l10n strategy, which at a high level will involve only supporting locales that have the proper resources to maintain them, and also only including "tier 1" pages — the most important parts of MDN — and dropping all of the other stuff we have lying around.

There is a useful issue on the stumptown repo that is where we are starting to discuss the future l10n strategy in more detail: https://github.com/mdn/stumptown-content/issues/30

**Comment by jsk7** [comment]
@chrisdavidmills great, I'll check it out and try to contribute there, thanks for the insight 👍
