### ISSUE TITLE
More useful CSS setPropertyValue() needed

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2005]
The example on https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty just randomly sets a border on a rule without knowing which rule it's hitting. While we want mimum use case examples, this is too minimum. Let's add a way to determine which property it's being added to, or at least direct someone to how that can be done.

I dont' know off the top of my head how to do that, hence creating a ticket instead of editing.

**Comment by chrisdavidmills** [comment]
I've written a quick example that is more useful than the previous one: 

https://wiki.developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty#Examples

Does that work, @estelle ?
