### ISSUE TITLE
[IPDL] The tutorial is outdated

### ISSUE THREAD

**Issue by saschanaz** [mdn/sprints#2006]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[The tutorial](https://developer.mozilla.org/en-US/docs/Mozilla/IPDL/Tutorial) has these problems:

1. Nearly all of the examples lack explicit prefix before message names. Messages are required to have `async` or `sync` before them since [Bug 1240871](https://bugzilla.mozilla.org/show_bug.cgi?id=1240871).

2. The document still mentions `rpc` semantics which is replaced by `prio()` in [Bug 1049879](https://bugzilla.mozilla.org/show_bug.cgi?id=1049879).

3. Contents about `intr`, `prio`, `nested`, and `refcounted` are missing.

**Comment by Elchi3** [comment]
The MDN team doesn't maintain mozilla internal docs and legacy content will soon be archived. Please file this in bugzilla or at https://firefox-source-docs.mozilla.org/
