### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Extension_Versioning,_Update_and_Compatibility

### ISSUE THREAD

**Issue by TBAIKamine** [mdn/sprints#2009]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

the link for HashTab : http://implbits.com/HashTab.aspx returns 404 response page not found

**Comment by chrisdavidmills** [comment]
This is archived documentation. We won't be making any fixes here.
