### ISSUE TITLE
 404 error while trying to access a page

### ISSUE THREAD

**Issue by babethkelly** [mdn/sprints#2013]
# Request type

- [ ] Correction or update
Bug

# Details
I got a 404 error while trying to access this page
https://developer.mozilla.org/fr/Learn/HTML/Write_a_simple_page_in_HTML

**Comment by chrisdavidmills** [comment]
What page did you find the broken link on?

**Comment by SphinxKnight** [comment]
Bonjour @babethkelly, pouvez-vous nous dire d'où venait ce lien afin que nous le corrigions ? :)

**Comment by SphinxKnight** [comment]
@babethkelly sans plus de détails, je ferme cette _issue_ pour le moment, n'hésitez pas à la rouvrir si vous avez plus d'infos (notamment la page sur laquelle vous avez trouvé ces liens)

---

Without further details, there is not much we can do, I'm closing this issue but feel free to reopen it with more info (esp. the URL of the page where you found those links)
