### ISSUE TITLE
Review notes on background-size

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2017]
background-size has several notes which should be checked and likely updated. For example, "in Firefox 43, as opposed to Chrome 52" - has one browser implementation won out, are they both still conflicting, or has something changed altogether.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by chrisdavidmills** [comment]
Note content fixed; closing: https://github.com/mdn/content/commit/462142b2b8f9fc58c7b0aad3defb914ec91b5635
