### ISSUE TITLE
Add screen reader support table

### ISSUE THREAD

**Issue by MarcHaunschild** [mdn/sprints#2018]
# User story
As a developer, I want to know which screen reader support a certain technique, so I can decide to use techniques accessible to more users.

# Acceptance criteria

- [ ] Screen reader support table next to browser support table

**Comment by chrisdavidmills** [comment]
This is a really great idea. It would also be a huge amount of work ;-)

This has been discussed before at a browser compat data workshop, I'm sure of it. I don't know where this discussion might be; perhaps you could ask over at https://github.com/mdn/browser-compat-data/issues?
