### ISSUE TITLE
BCD for "clip" value of "overflow"

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2022]
Do we need to add 'clip' as an extra line on:
https://developer.mozilla.org/en-US/docs/web/css/overflow
https://developer.mozilla.org/en-US/docs/web/css/overflow-x
https://developer.mozilla.org/en-US/docs/web/css/overflow-y

**Comment by chrisdavidmills** [comment]
I've made sure it is included consistently in the reference pages' Syntax/Values sections, and also filed a PR to add it to BCD:

https://github.com/mdn/browser-compat-data/pull/5351

I think this is done?
