### ISSUE TITLE
Requesting feedback by survey - when you follow the link, survey is no longer taking feedback

### ISSUE THREAD

**Issue by aiherder78** [mdn/sprints#2023]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**Comment by aiherder78** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by aiherder78** [comment]
Survey should be removed.

**Comment by chrisdavidmills** [comment]
@atopal another bug report about the survey

**Comment by atopal** [comment]
The survey was removed last week.
