### ISSUE TITLE
Sort out the difference between Array.length and Array.prototype.length

### ISSUE THREAD

**Issue by zvuv** [mdn/sprints#2025]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length

# Details

Under Array/properties there's a link  for

**Array.length.**

The link navigates to a description of the the length property of an Array  _instance_.  This is confusing.    Array has its own length property by inheritance from Function, it has AFAIK nothing to do with  length property of an instance.

So, for the very first time ever, I decided to edit this, but the source page it brings up shows an accurate description of the Array.length property.

Somebody who knows what he's doing might sort this out?

**Comment by Elchi3** [comment]
The Array page doesn't talk about the static Array.length anymore, given it is not very useful.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Static_properties

For instances, it is listed under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Instance_properties

Note that we've also recently introduced "Static" and "Instance" when we list members of a class to further avoid confusion. I think we can close this.
