### ISSUE TITLE
Update code in Express tutorial, Create_book_form article

### ISSUE THREAD

**Issue by corvalanlara** [mdn/sprints#2026]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The site suggests to add the following lines in [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form), [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form), [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form) and [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms).
`const { body,validationResult } = require('express-validator/check');
const { sanitizeBody } = require('express-validator/filter');` 

As shown in this screenshot: ![screenshot-developer mozilla org-2019 08 16-17_04_41](https://user-images.githubusercontent.com/8869572/63198376-89960780-c048-11e9-987d-c1812ca903dd.png)

Even though it isn't a critical error, using 'express-validator/check' and 'express-validator/filter' is deprecated. As the message shows:
![screenshot](https://user-images.githubusercontent.com/8869572/63198826-f9f15880-c049-11e9-97c7-7de66d3cdbdb.jpg)
> express-validator: requires to express-validator/check are deprecated.You should just use require ("express-validator") instead.

> express-validator: requires to express-validator/filter are deprecated.You should just use require("express-validator") instead.

The solution would be to put this code instead:
`const { body,validationResult, sanitizeBody } = require('express-validator');`

**Comment by sideshowbarker** [comment]
Thanks for reporting this, and sorry for the delay in any update on this so far.

It seems all the code examples all already got fixed some time back on October last year, before the move to the new backend.

However, I found one leftover mention in the https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms article prose — so I opened https://github.com/mdn/content/pull/2411 with a fix for that.
