### ISSUE TITLE
Formatting error for Java and Javascript code examples in article "Details of the object model"

### ISSUE THREAD

**Issue by j13ag0** [mdn/sprints#2027]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On this MDN page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model

in the section:
More flexible constructors

The layout of the Java and Javascript code examples is not correct. They seem to be somehow jumbled.

Chrome:  76.0.3809.100

**Comment by chrisdavidmills** [comment]
I fixed this earlier on today.
