### ISSUE TITLE
Cover CSS Compound Selectors Explicitly

### ISSUE THREAD

**Issue by karlhorky** [mdn/sprints#2030]
# Request type

- [x] New documentation
- [ ] Correction or update

# Details

I'm writing course material for complete beginners that references MDN right now and it seems like ["compound selectors"](https://www.w3.org/TR/selectors/#syntax) such as `h1.title` or `.title.heading-title` are not covered on the [Simple Selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Simple_selectors) page, or anywhere else:

> A compound selector is a sequence of simple selectors that are not separated by a combinator, and represents a set of simultaneous conditions on a single element.

I tried also searching on Google for any other pages on MDN, but it appears to be implicit knowledge not presented explicitly...

Previously submitted as a comment here: https://github.com/mdn/sprints/issues/1278#issuecomment-521689045

**Comment by chrisdavidmills** [comment]
Hi there!

So, we are about to publish an awesome new set of beginner's CSS material, written by @rachelandrew . It isn't linked to from the sidebar yet, but you can find it here:

* https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks

If I am understanding your query correctly, we do cover compound selectors at https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#Adding_a_class, but only in passing, basically saying that it is not such a good idea (this is the current best practice thinking).

We also have a deep dive into selectors, starting at https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors and going on for a few articles after that. We don't really mention it at all here. @rachelandrew do you think we should add something there about it?

**Comment by karlhorky** [comment]
> If I am understanding your query correctly, we do cover compound selectors at https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#Adding_a_class, but only in passing, basically saying that it is not such a good idea (this is the current best practice thinking).

Ah, kind of - they are partially shown in passing, but only one certain type (type selector with class selector) and it's not explained what they are or that they can be used in many other situations (multiple class selectors, class selectors with id selectors, class selectors with attribute selectors, etc.).

Being able to combine selectors like this to further refine the elements to style is powerful and valuable for developers to know in the process of learning CSS (in my opinion, in the first few modules about selectors).

**Comment by rachelandrew** [comment]
As someone who audits other people's CSS a heavy use of complex selectors tends to ring alarm bells. What usually follows is a lot of repetitive CSS as by making the selectors that specific you need to write a new selector each time. Often a very simple way to improve consistency, and reduce lines of code is simply to turn those complex selectors into simple classes.

I'm happy that we explain that compound selectors are a thing, I don't see what more we could say without making it look like a suggestion that people write CSS in an overly-specific way. It is incredibly useful we can target specific things in this way, but it should be used as the exception and not the rule in my opinion, and I think generally industry opinion at this point if the popularity of OO CSS and things like BEM is anything to go on.

**Comment by chrisdavidmills** [comment]
I think we could still do with mentioning it in the selectors deep dive, even if it is only to reiterate that it is possible, but not a great idea unless you really have to. People will still come across it in the wild.

**Comment by rachelandrew** [comment]
We already mention it though ... https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators#Using_combinators

**Comment by karlhorky** [comment]
> As someone who audits other people's CSS a heavy use of complex selectors tends to ring alarm bells. What usually follows is a lot of repetitive CSS as by making the selectors that specific you need to write a new selector each time.

> I'm happy that we explain that compound selectors are a thing, I don't see what more we could say without making it look like a suggestion that people write CSS in an overly-specific way.

Good point. I understand this perspective, and I think it's valuable to hear about it in the documentation.

What about maybe a section on them with a caveat and "our recommendation" paragraph along the lines of "use sparingly, along with other complex selectors"? 
Kind of like your note here?

> Often a very simple way to improve consistency, and reduce lines of code is simply to turn those complex selectors into simple classes.

**Comment by chrisdavidmills** [comment]
> We already mention it though

Ah, missed that bit, sorry! I was probably thinking of combinations like li.className, which we mention in the first steps articles, but don't seem to mention in the deeper dives of the building blocks. Maybe worth adding an example of one of those too?

**Comment by rachelandrew** [comment]
This is a very old thread but we have an example of multiple classes here https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors#Target_an_element_if_it_has_more_than_one_class_applied

I don't think we need to show every possible permutation as we don't do that for anything else.

**Comment by karlhorky** [comment]
I think the example content is good now! Before there were no examples of multiple classes. Now there is:

- an example of multiple classes
- an example of a tag with an id

Ideally, the concept and name of "compound selectors" would be actually explained before that in a separate short paragraph, but in practice it's true that it's not super important to know this (as long as you know that you can put multiple selectors together).

**Comment by rachelandrew** [comment]
ok I think this is probably done now then :) cc: @chrisdavidmills

**Comment by karlhorky** [comment]
Alright, then I'm closing this. Thanks!
