### ISSUE TITLE
Bad Title in "Open in CodePen" & "Open in JS Fiddle" Buttons 

### ISSUE THREAD

**Issue by shshaw** [mdn/sprints#2031]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Clicking the "Open in CodePen" or "Open in JS Fiddle" links populates the title with what seems to be the HTML from the example.

It happens for sure on this page, but others may be affected: https://developer.mozilla.org/en-US/docs/Web/CSS/filter

**Comment by chrisdavidmills** [comment]
I agree that this is not great, but this is hard to avoid with some of the live examples, because of the way it works. For now, I've just removed the codepen/jsfiddle buttons from the examples ;-)

**Comment by chrisdavidmills** [comment]
The live samples are generated by the EmbedLiveSample macro, the code of which is at

https://github.com/mdn/kumascript/blob/master/macros/EmbedLiveSample.ejs

This in turn calls https://github.com/mdn/kumascript/blob/master/macros/LiveSampleURL.ejs to generate the URL of the live sample to embed.
