### ISSUE TITLE
Consider noting Number.parseFloat can accept a number

### ISSUE THREAD

**Issue by dev-nicolaos** [mdn/sprints#2032]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Issue in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat

The syntax documentation states that the parameter `Number.parseFloat` accepts should be a string, and that any value that cannot be converted to a number will result in `NaN` being returned. This is the case for other data types such as booleans, null, undefined, and objects. However, when the method is passed a number, it simply returns that number, giving no indication that anything went wrong. 

Though it may seem silly to call `parseFloat` with a parameter that is already a number, it is a valid use case. Because JS is a dynamically typed language, a developer might not be sure of the type of the value they are passing into this method, and therefore may pass a value that under some circumstances is a string, and other circumstances is already a number.

Another reason to do this is for consistency. The description section says "This method has the same functionality as the global parseFloat() function". The examples for that function shows it parsing a number.

### I recommend either:
- Changing the word "string" to "value" (or something similar) and explaining in the description that it can be a string or number.
![image](https://user-images.githubusercontent.com/29005473/63203656-ca405180-c045-11e9-8e46-622165accfbe.png)

### OR

- Add a note explaining this nuance below either the "Parameters" or "Return value" section, whichever is more consistent across MDN. 
    - Example note style:
![image](https://user-images.githubusercontent.com/29005473/63204046-d37eed80-c048-11e9-856b-2495167c6b55.png)

**Comment by wbamberg** [comment]
@dev-nicolaos , thanks for such a clear and useful bug report.

I've updated the page for [Number.parseFloat()](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat) and also that for the global [parseFloat()](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) function, which seems to have the same behaviour.

Please let me know if this works for you. Also @Elchi3 , does this look good to you too?

**Comment by Elchi3** [comment]
LGTM, thanks Will! :+1:

**Comment by dev-nicolaos** [comment]
@wbamberg Looks great, thanks for this!
