### ISSUE TITLE
setInterval minimum delay

### ISSUE THREAD

**Issue by wfentress** [mdn/sprints#2033]
The [documentation for `setInterval`'s `delay` argument](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#Arguments) reads, in part,

> If this argument is less than 10, a value of 10 is used.

**Is this still the case?** [WHATWG's spec](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-initialisation-steps) seems to limit the delay to 4 ms:

> 9. If the currently running task is a task that was created by this algorithm, then let *nesting level* be the task's timer nesting level. Otherwise, let *nesting level* be zero.
> 
> Note: The task's timer nesting level is used both for nested calls to setTimeout(), and for the repeating timers created by setInterval(). (Or, indeed, for any combination of the two.) In other words, it represents nested invocations of this algorithm, not of a particular method.
> 
> 10. If *timeout* is less than 0, then set *timeout* to 0.
> 
> 11. If *nesting level* is greater than 5, and *timeout* is less than 4, then set *timeout* to 4.

## Acceptance criteria

- [x] Necessary changes have been made, if warranted following research

**Comment by a2sheppy** [comment]
https://wiki.developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#Delay_restrictions
