### ISSUE TITLE
Documantation - html onClick leads to click in DOM which leads to a 404

### ISSUE THREAD

**Issue by Flamesh90** [mdn/sprints#2034]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/onclick

go to: "see also"

![image](https://user-images.githubusercontent.com/44932812/63338587-bea5a100-c34b-11e9-91a3-a188f47be05a.png)

get 404 page not found

**Comment by Elchi3** [comment]
This content is archived and no longer maintained.
