### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents

### ISSUE THREAD

**Issue by TedYadeta** [mdn/sprints#2035]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

**Comment by TedYadeta** [comment]
On the Manipulating Documents section of the Client-Side Web API Module, the section "Active learning: Getting useful information from the Window object" has a dead link to a "maps.example.html."

**Comment by chrisdavidmills** [comment]
Ah yes, the previous article got rewritten and no longer includes the maps example I was talking about here. I've taken the rather cheap approach of just removing that line altogether.

Thanks for reporting this!
