### ISSUE TITLE
Design for main navigation improvements on mobile devices

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#2043]
# User story
As a user, I want to be able to easily navigate MDN on my mobile device, so that I can access the information I need wherever I am.

# Acceptance criteria

- [x] Updated main navigation menu for mobile
- [x] Updated search (in header) for mobile

# Tasks

# Design
**InVision**
Home: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724008_home_-_Mobile
Search: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724007_home_-_Mobile_-_Search
Menu: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724006_home_-_Mobile_-main_Menu_Open-
Menu - expanded: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724005_home_-_Mobile_-sub_Menu_Open-
Menu - signed in: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724004_home_-_Mobile_-_Signed_In_-main_Menu_Open-

**Comment by jmswisher** [comment]
@atopal Looks like these designs need review?

**Comment by atopal** [comment]
We did review these, all good.
