### ISSUE TITLE
Write stumptown future plan/justification

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2046]
We need to decide what plan option we are going to go forward with for stumptown (e.g. just migrate content to GitHub for now, or keep migrating content to structured data, or both?), then we need to create a business justification along with what resources we will need to realise that plan in 2020.

# Acceptance criteria

1. - [x] Write high-level general template for what a business justification plan needs. Both to use now, and for future projects. Kadir's rough slides might be useful here (https://docs.google.com/presentation/d/1j4-qys9d4JojaGQbIiebQPMFtjcAXor32iHOo1uCq0U/edit?ts=5d5d37bc#slide=id.p)
2. - [x] Write plan that compares the different Stumptown options in terms of user, developer, and writer outcomes, risks and mitigations, and relative costs. From this, write a conclusion that states with option we will go for.
3. - [x] Liaise with Will, devs, and Kadir to see if this is what we need, if it makes sense, and if I've missed anything. 
4. - [ ] Write hopefully final draft, which hopefully justifies settling on a single most viable option for proceeding.
5. - [x] From this justification doc, produce a business plan/justification that also sets out what we need in terms of resourcing for this project.

**Comment by chrisdavidmills** [comment]
Useful info from Will (from 1794), relating to simpler GitHub alternatives to stumptown:

"This epic is to investigate a simpler alternative to the "stumptown" project in which we don't structure the MDN reference content, but just move it from the Wiki into GitHub.

The main motivation here is: with the new React front-end, we now have 2 different Kuma front ends. One for users of the docs and a different one (wiki.dmo) for contributors. Supporting both front ends and keeping them in sync increases the maintenance burden. So this makes getting away from the Wiki more urgent. Since stumptown will take a long time, perhaps we could move our docs (and contribution workflow) out of the Wiki more quickly by not tackling structuring the content (yet)."

**Comment by jmswisher** [comment]
@chrisdavidmills Is there a link available to this document?

**Comment by chrisdavidmills** [comment]
The document draft is here: https://docs.google.com/document/d/1tXBnvfnFu9l5ERbxJThI7z1fmWKPdfW4Uw1reVYEnfc/edit#

**Comment by jmswisher** [comment]
@chrisdavidmills @wbamberg Can this be closed?
