### ISSUE TITLE
Design for sidebar navigation improvements on mobile devices

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#2047]
# User story
As a user, I want to be able to easily navigate MDN on my mobile device, so that I can access the information I need wherever I am.

# Acceptance criteria
- [x] Revise "On this page" links location and design for mobile
- [x] Revise "Related topics"/sidebar links design for mobile

# Tasks

# Design
**InVision**
Reference Page: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724021_reference_-_Mobile
Article Menu: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382724020_reference_-_Mobile_-article_Menu-
Article Menu - Related Topics: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382786356_reference_-_Mobile_-article_Menu_-_Related_Topics-
Article Menu - Related Topics - Expanded: https://mozilla.invisionapp.com/share/UETT54FKXRJ#/382788017_reference_-_Mobile_-article_Menu_-_Related_Topics_-_Expanded-

**Comment by jmswisher** [comment]
@atopal Looks like these designs need review?

**Comment by atopal** [comment]
Yeah, unfortunately we didn't get to review this anymore. I'm good with it, except for the design of the bread crumbs, the breadcrumbs will break into the next line when they are too long and they duplicate the title, which is okay on a desktop, but not great on mobile. I suggest we shorten the top level to something like a house icon, and leave out the title of the page, that way it should work out in most cases without breaking the line and without duplicating the title

**Comment by jmswisher** [comment]
Closing this and assuming we can create a new issue for the tweaks you mention, when we get a designer back on board.
