### ISSUE TITLE
grid line names

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2051]
Add 'linename' explanation in the values list on https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns#line-names and https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows

**Comment by rachelandrew** [comment]
I was looking at this and realised the BCD was out of data for these properties. So here is a PR for that https://github.com/mdn/browser-compat-data/pull/7041

**Comment by rachelandrew** [comment]
Updated:

- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows

To add a line-name definition.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think this is probably done, pending BCD merge.

**Comment by chrisdavidmills** [comment]
@rachelandrew pages reviewed, so we're just waiting for BCD now.

**Comment by rachelandrew** [comment]
@chrisdavidmills BCD updated for these now.

**Comment by chrisdavidmills** [comment]
@rachelandrew great! Let's close it.
