### ISSUE TITLE
min-content, max-content

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2052]
Should pages for these two?

**Comment by rachelandrew** [comment]
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/max-content
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/min-content

Did these as I have those grid bits to tidy up so I can link them where appropriate, as they are a value I don't think they are really suitable for a live example.

cc: @chrisdavidmills

**Comment by chrisdavidmills** [comment]
These look good, thanks @rachelandrew !

I think we can close this one now.
