### ISSUE TITLE
Broken link on the page "Déboguer de l'HTML"

### ISSUE THREAD

**Issue by abarel** [mdn/sprints#2055]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Load the page [Déboguer de l'HTML](https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_%C3%A0_HTML/Debugging_HTML).
Click on the broken link [Découverte des outils de développement du navigateur](https://developer.mozilla.org/fr/docs/Apprendre/Discover_browser_developer_tools).
Got a "not found" error

**Comment by chrisdavidmills** [comment]
Link now fixed. Thanks for reporting!
