### ISSUE TITLE
https://developer.mozilla.org/de/SpiderMonkey_Garbage_Collection_Tipps

### ISSUE THREAD

**Issue by phu9Suop** [mdn/sprints#2056]
# Request type

- [ ] New documentation
- [ x] Correction or update
https://developer.mozilla.org/de/SpiderMonkey_Garbage_Collection_Tipps
# Details
Above link creates a 404 error. 

Documentation once existing must have gone eleswhere, maybe to /dev/null
Please correct

**Comment by chrisdavidmills** [comment]
On what page did you find this broken link?

**Comment by phu9Suop** [comment]
Hi
Look here against the bottom:
https://developer.mozilla.org/de/docs/SpiderMonkey
2nd link after 
Tipps, Tricks und Philosophie
best regards

**Comment by chrisdavidmills** [comment]
Ah, right. I think this is a bigger problem, and the spidermonkey docs will probably be archived soon as they are out of date (the in-tree docs are better). I'm going to WONFIX this.
