### ISSUE TITLE
Update BCD for Themes

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#2061]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
BCD Data needs to be updated now that some of the deprecated values are no longer deprecated.
Related Bugzilla Bug #[1472740](https://bugzilla.mozilla.org/show_bug.cgi?id=1472740)

# Acceptance criteria
- [ ] BCD data has been updated
- [ ] PR has been created
- [ ] Correct content appears on the page.

**Comment by rebloor** [comment]
This work has been completed, this is the PR containing the changes: https://github.com/mdn/sprints/issues/2142
