### ISSUE TITLE
[DevTools] A11y inspector docs tasks, Fx 70

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2062]
Trello: https://trello.com/c/7jPEPyc0/14-accessibility-inspector-fx-70

## Acceptance criteria:

1. - [x] [Add UI for keyboard accessibility audit/check.](https://bugzilla.mozilla.org/show_bug.cgi?id=1564968)
2. - [x] [Adding color contrast information to the color picker](https://bugzilla.mozilla.org/show_bug.cgi?id=1478156)
3. - [x] [Implement accessible relations within the accessibility inspector sidebar.](https://bugzilla.mozilla.org/show_bug.cgi?id=1492866) (historic one, but can you check to see if this has been documented?)

**Comment by chrisdavidmills** [comment]
@jmswisher updated to cover all the a11y stuff in Fx 70, and to adopt standard style

**Comment by jmswisher** [comment]
- Wrote [Keyboard check messages](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard)
- Updated text and screenshots in [Inspect and select colors](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Inspect_and_select_colors) re contrast info
- "relations" is already mentioned in [Features of the Accessibility panel](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Features_of_the_Accessibility_panel)

**Comment by chrisdavidmills** [comment]
Is this one done. @jmswisher ?

**Comment by jmswisher** [comment]
Yes, it is done.
