### ISSUE TITLE
Math.round(): Demonstrative Implementation is off by -1 in case of negative numbers

### ISSUE THREAD

**Issue by gheja** [mdn/sprints#2063]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The [Math.round()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) documentation's Demonstrative Implementation works differently than Math.round().

It looks like it is off by -1 when using negative numbers.

See here:
![20190830_00000002](https://user-images.githubusercontent.com/1894642/63982733-ffc45080-cac3-11e9-9190-c11760da8e57.png)

**Comment by chrisdavidmills** [comment]
I've had a play with this, and it looks like the following works:

```
function vanilla_round(x) {
    var y = Math.abs(x) + 0.5; // so that less than 1/2 rounds down; greater rounds up
    var sign_multiplier = x / Math.abs(x); // 1 or -1, depending whether x is +ive or -ive
    return (y - (y % 1)) * sign_multiplier;
}
```

Not sure if it could be done more simply though.
