### ISSUE TITLE
projects/mathml/fonts/ leads to a 404

### ISSUE THREAD

**Issue by ewen-lbh** [mdn/sprints#2066]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link to download fonts from the [MathML Basics page](https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/Basics) seems to be dead. I got a 404 upon trying to reach the link where it should lead to, which is exactly: `http://www.mozilla.org/projects/mathml/fonts/`

**Comment by chrisdavidmills** [comment]
Seems to work for me.
