### ISSUE TITLE
user-select not listed on MDN CSS reference

### ISSUE THREAD

**Issue by ursi** [mdn/sprints#2068]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[`user-select`](https://beta.developer.mozilla.org/en-US/docs/Web/CSS/user-select) is not listed on [CSS reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference).

**Comment by rachelandrew** [comment]
@chrisdavidmills various other properties don't appear either, I spotted `appearance` and `aspect-ratio` are missing just doing a quick check. How do I get things to show up in the list?

**Comment by ursi** [comment]
https://www.w3.org/Style/CSS/all-properties.en.json could maybe be used to automate it. This is what I use to create my CSS reference that links to the spec. However, it's not a *perfect* solution as it doesn't include `pointer-events` (presumably this is because it comes from the SVG spec and not CSS) and there may be other properties like this as well that I just haven't found.

**Comment by escattone** [comment]
Now that @sideshowbarker's https://github.com/mdn/yari/pull/2338 has been merged, we should see things like `appearance` and `aspect-ratio` show up within the next 48 hours. I'm also going to publish a new version of `mdn-data`, which should take care of `user-select` (which was updated to `standard` in the repo, but hasn't yet been published).

**Comment by escattone** [comment]
This is resolved (`user-select` is now present on https://developer.mozilla.org/en-US/docs/Web/CSS/Reference).
