### ISSUE TITLE
Compat data for the CSS API seems to include unrelated data

### ISSUE THREAD

**Issue by stof** [mdn/sprints#2076]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/API/CSS is about documenting the JS API of the `CSS` global variable. But its [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/CSS#Browser_compatibility) also includes rows about the different CSS units. I don't think these make sense in this table.

**Comment by chrisdavidmills** [comment]
Assigning to @estelle , as this is Houdini-related.

**Comment by estelle** [comment]
Added in https://github.com/mdn/browser-compat-data/commit/6cadd1d9d4f680e3293b13a2aa8859c7da0e49b7#diff-d8b4d058a3e9bc5849b515e97b415da2

**Comment by stof** [comment]
OK, these method actually exist as part of the Typed OM. so having them in the support data on the page is indeed right. What is confusing is that the content of the page does not list these methods.

So rather than an issue in the compat data of this page, it is an issue in the content of this page.

**Comment by estelle** [comment]
https://drafts.css-houdini.org/css-typed-om/#numeric-factory

**Comment by estelle** [comment]
created https://developer.mozilla.org/en-US/docs/Web/API/CSS/factory_functions

Still have to update BCD

**Comment by estelle** [comment]
https://github.com/mdn/browser-compat-data/pull/4921

**Comment by jmswisher** [comment]
Leaving this issue open in Peppermint until the PR is merged.
