### ISSUE TITLE
Document Grid Inspector subgrid behavior

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#2077]
[Show a translucent parent highlight when a subgrid is highlighted](https://bugzilla.mozilla.org/show_bug.cgi?id=1550519)

# Acceptance criteria

- [x] Grid Inspector documentation updated to document behavior when the grid includes a subgrid.
- [x] Images captured for subgrid
- [x] Information added to release notes

**Comment by irenesmith** [comment]
Looks as though this is about to happen for 71.

**Comment by jmswisher** [comment]
Added a section on subgrids, with screenshot, to the [grid inspector](https://wiki.developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts) article.
