### ISSUE TITLE
Document color vision simulator

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2079]
Placeholder: https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector/Simulation

AC:
- [x] Documentation for color vision simulator meets Definition of Done

**Comment by chrisdavidmills** [comment]
Where are we on this one, @jmswisher ?

**Comment by jmswisher** [comment]
Done. [Simulation](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector/Simulation) article is no longer a placeholder.
