### ISSUE TITLE
Implement the aspect-ratio property from CSS Sizing 4

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2083]
# Acceptance criteria

- [ ] BCD created
- [ ] Property page created
- [ ] Live example
- [ ] Additional data as needed

The aspect-ratio property spec: https://drafts.csswg.org/css-sizing-4/#aspect-ratio

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1528375

**Comment by chrisdavidmills** [comment]
Closing this bug, and grouping the task together with similar bugs at https://github.com/mdn/sprints/issues/2084
