### ISSUE TITLE
[CSS] Values, units, and box-sizing docs tasks, Fx 70

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2084]
https://trello.com/c/99AKTpVj/186-css-values-and-units-level-4-box-sizing-level-4-fx-70

# Acceptance criteria

1. - [x] [[fill-stroke] [filter-effects] [css-color] percentage opacity](https://bugzilla.mozilla.org/show_bug.cgi?id=1562086)
2. - [x] [Implement the aspect-ratio property from CSS Sizing 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1528375)
3. - [x] [Retiring support for 3-valued <position> (excluding background)](https://bugzilla.mozilla.org/show_bug.cgi?id=1559276)

**Comment by rachelandrew** [comment]
In researching the opacity issue it looks like shape-image-threshold is also included: https://bugzilla.mozilla.org/show_bug.cgi?id=1568615

**Comment by rachelandrew** [comment]
data PR: https://github.com/mdn/data/pull/390

**Comment by rachelandrew** [comment]
compat data for opacity and shape-image-threshold: https://github.com/mdn/browser-compat-data/pull/4881

**Comment by rachelandrew** [comment]
The aspect ratio issue, I can't see that being included in 70. There is the mapping of width and height (https://bugzilla.mozilla.org/show_bug.cgi?id=1547231) which seems to to be in Nightly. Do you have any other info @chrisdavidmills ?

**Comment by chrisdavidmills** [comment]
@rachelandrew right, so this is related to https://github.com/mdn/sprints/issues/2100, correct? I wrote an article that explains it, after chatting to Emilio.

AFAIU, it is internal only, so probably doesn't need documenting anyway, at least not for the moment.

Have I misunderstood here?

**Comment by rachelandrew** [comment]
yeah I know what it is - I was wondering if anything needed doing about it now as it's on the list for documenting :)

**Comment by chrisdavidmills** [comment]
> yeah I know what it is

Oh I wasn't questioning that — I was verifying that I've got the correct understanding of what we are talking about ;-)

So I think we can leave that for now.

**Comment by rachelandrew** [comment]
A fiddly PR for the changes to compat for position: https://github.com/mdn/browser-compat-data/pull/4882

**Comment by rachelandrew** [comment]
Updated the page for <position> to add a note about the difference between position generally and in background-position.

**Comment by rachelandrew** [comment]
So I think, pending merging compat data, these are done. Moving to in review.

**Comment by chrisdavidmills** [comment]
Looks good to me, thanks!

Only couple of things I can think of are:

* Updating the related bugs to dev-doc-complete, and explainin what you did on them so the engineers can give us a review.
* Adding notes about these changes to the Fx70 rel notes, if you haven't already.
