### ISSUE TITLE
[CSS], Fx 70: Implement the multi keyword syntax for the display property (high priority)

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2086]
# Acceptance criteria

- [x] BCD updated
- [x] The display page updated
- [x] Relevant pages for various values of display (grid, flex etc.) checked for potential changes

# Bugs

1. - [x] [[css-display] Implement the multi-keyword syntax for the 'display' property](https://bugzilla.mozilla.org/show_bug.cgi?id=1038294)
2. - [x] [[css-display] Implement 'display: block ruby'](https://bugzilla.mozilla.org/show_bug.cgi?id=1557825)
3. - [x] [Support 'display: inline list-item' and 'display: inline flow-root list-item'](https://bugzilla.mozilla.org/show_bug.cgi?id=1105868)
4. - [x] [Implement layout for 'display: flow-root list-item'](https://bugzilla.mozilla.org/show_bug.cgi?id=1574060)

This would be a good candidate for a hacks post.

**Comment by rachelandrew** [comment]
For the individual display types pages, the formal syntax returns value not found in db https://developer.mozilla.org/en-US/docs/Web/CSS/display-inside

These exist in css/syntaxes.json in data but that's looking for things in properties - however these aren't properties. Suggestions as to what to do here?

**Comment by rachelandrew** [comment]
@chrisdavidmills Other than the above query about the individual display types pages I don't think there is a lot to do here over what I already did when writing the Learn stuff and more recently. I've checked BCD, it's already in the 70 release notes. I don't think we need to add more about two values to MDN right now as in reality everyone is going to be using single values for a long time yet.

I definitely think this would be a good candidate for the hacks blog so I could do that if you think.

**Comment by chrisdavidmills** [comment]
For other things that aren't properties, we have sometimes just put the formal syntax in the page as straight content; [`<position>`](https://developer.mozilla.org/en-US/docs/Web/CSS/position_value#Formal_syntax), for example.

In this case, I'd just delete the csssyntax and cssinfo calls from the display subpages. After all, you've got those sections in the main [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display) page for people to look at if they need them.

So yeah, I agree that there is not much more to do here. Just set the related bugs to `dev-doc-complete`, and maybe link them back here so they can read the explanation of what's been done.

Yes, I agree a hacks post explaining these new display values would be really interesting.

**Comment by rachelandrew** [comment]
I think this is all done now, I'll make an issue for a hacks post as I could write that prior to 70 being released.

**Comment by chrisdavidmills** [comment]
Cool, thanks Rachel. Hacks post sounds good too.
