### ISSUE TITLE
Incomplete ARIA:_tabpanel_role document

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#2088]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I'm submitting this on behalf of the user that created https://bugzilla.mozilla.org/show_bug.cgi?id=1578990. That user wanted to point out that the https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/ARIA:_tabpanel_role page is incomplete.

**Comment by tonytino** [comment]
Was going to open a ticket for the same reason, but found this and thought I'd call it out again here instead. Thanks for all the great docs!
