### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/mediaDevices

### ISSUE THREAD

**Issue by webdq** [mdn/sprints#2089]
hello, my firefox's version is 68, I can get the 'navigator.mozGetUserMedia' object.
but my firefox's version is 69 today, I can't get the object.
and I see the link https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
but I get the 'navigator.mediaDevices' is undefined.
what should I do?
thanks.

**Comment by chrisdavidmills** [comment]
`navigator.mediaDevices` is only available through a secure context, i.e. over HTTPS. Try running your code over HTTPS on a web server (not localhost or file://).
