### ISSUE TITLE
Replace broken link in SpiderMonkey documentation page

### ISSUE THREAD

**Issue by meerasndr** [mdn/sprints#2090]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey#Hacking_on_SpiderMonkey has a broken link called 'Contributing to Spider Monkey'.  
The author of the slidecast has it uploaded on YouTube as well: https://www.youtube.com/watch?v=LaFbvPBr6GE

**Comment by chrisdavidmills** [comment]
I've updated it to point to the YouTube video.
