### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

### ISSUE THREAD

**Issue by nfasarakis** [mdn/sprints#2093]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello!

In the [Promise.prototype.catch web doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch), the example "**Demonstration of the internal call**" contains a typo. The IIFY is called with **this.Promise** instead of **Promise**. Unless I'm missing something? 

Thanks for your time and all the work with the docs!

![promise_catch](https://user-images.githubusercontent.com/35574596/64491725-52e09500-d274-11e9-9d20-edae2d1bd1cb.jpg)

**Comment by BruceWilliams** [comment]
It would probably be clearer, and possibly more correct, to use `globalThis.Promise`. See:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by chrisdavidmills** [comment]
I've tested this, and it seems to work correctly as-is.
