### ISSUE TITLE
[HTML] <input> element docs tasks for Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2095]
Trello: https://trello.com/c/KZ1QBGnm/30-input-element-improvements-fx-70

# Acceptance criteria

1. - [x] [Make available and enable password generation on desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1565407)

**Comment by jmswisher** [comment]
Added to [Fx 70 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#HTML)

**Comment by jmswisher** [comment]
Added Fx70 info to [Turning off form autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password)

**Comment by jmswisher** [comment]
Does not affect BCD, as this attribute value was supported as of Fx67. This new behavior is not part of the spec.
