### ISSUE TITLE
Firefox 61 JS DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#21]
As a Web developer I want to know about the latest JavaScript features in Firefox 61, so that I can test and make use of new technologies.

**Comment by chrisdavidmills** [comment]
1. - [ ] [Implement String.prototype.trimStart and String.prototype.trimEnd](https://bugzilla.mozilla.org/show_bug.cgi?id=1434007)

**Comment by Elchi3** [comment]
All done :)

**Comment by Elchi3** [comment]
Not sure why this was re-opened. I think it is done.
