### ISSUE TITLE
[CSS] Map the width and height attribute of images to aspect-ratio

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2100]
This is the change Jen was talking about in the dev content coordination meeting; see:

*  [Chrome Intent to Implement: Compute img/video aspect ratio from width and height HTML attributes](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/hbhKRuBzZ4o) 
* [Jen's tweet about this](https://twitter.com/jensimmons/status/1169815679244963841)

Feel free also to ask Jen about this if you need clarification. Essentially we need to say why this is a good thing, and that because of this is it extra good that you specify `width` and `height` attribute on `<img>`.

Note: This was enabled in Fx69, but we really need to do this as a priority.

# Acceptance criteria

1. - [x] [Map the width and height attribute of images to aspect-ratio](https://bugzilla.mozilla.org/show_bug.cgi?id=1547231)

**Comment by chrisdavidmills** [comment]
More info here in particular: https://twitter.com/jensimmons/status/1173293500563165186

**Comment by chrisdavidmills** [comment]
First draft of main explaner page here: https://docs.google.com/document/d/1RAqaONrO7Zka2Q7IL3yyGDskwycBATS46SeE167PDdY/edit#

**Comment by chrisdavidmills** [comment]
Articles that I think this might need to be mentioned on:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image
* The DOM interface equivalents of the above elements?
* https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

**Comment by chrisdavidmills** [comment]
Adding @a2sheppy as an assignee as he mentioned he'd help out with getitng the content placed correctly.

**Comment by chrisdavidmills** [comment]
@a2sheppy OK, this has been reviewed by Jen Simmons and Emilio, and they both seme to like it:

https://docs.google.com/document/d/1RAqaONrO7Zka2Q7IL3yyGDskwycBATS46SeE167PDdY/edit

This is ready to put on MDN.

**Comment by chrisdavidmills** [comment]
@a2sheppy just pinging you about this one to make sure you don't forget about it.

**Comment by a2sheppy** [comment]
Transferred to Rachel since she's doing this work now.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think we've pretty much got this covered now?

**Comment by chrisdavidmills** [comment]
Yup, this is done.
