### ISSUE TITLE
[HTML/XML] MathML updates, Fx 70 (low priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2103]
Trello: https://trello.com/c/LMs5lI6w/228-mathml-updates-fx-70

# Acceptance criteria

1. - [x] [Remove attributes deprecated from MathML3](https://bugzilla.mozilla.org/show_bug.cgi?id=1548524)
2. - [x] [Remove "small" "normal" "big" values of mathsize](https://bugzilla.mozilla.org/show_bug.cgi?id=1548527)
3. - [x] [Remove values "thin", "thick", "medium" values of mfrac@linethickness](https://bugzilla.mozilla.org/show_bug.cgi?id=1548529)
4. - [x] [Remove <math>'s mode attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1573438)
5. - [x] [Remove support for nonzero unitless lengths](https://bugzilla.mozilla.org/show_bug.cgi?id=1574749)
6. - [x] [Remove support for MathML length values thinmathspace, mediummathspace, thickmathspace, etc](https://bugzilla.mozilla.org/show_bug.cgi?id=1574750)
7. - [x] [MathML Lengths: Do not accept numbers ending with a dot](https://bugzilla.mozilla.org/show_bug.cgi?id=1575596)

**Comment by Elchi3** [comment]
This is all done now.
