### ISSUE TITLE
[CSS] Motion Path docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2105]
Trello: https://trello.com/c/Ef3V38Yh/212-css-motion-path-fx-70

# Acceptance criteria

1. - [x] [[motion-1] Support `<offset-anchor>`](https://bugzilla.mozilla.org/show_bug.cgi?id=1559231)

**Comment by chrisdavidmills** [comment]
offset-anchor page created: https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor

**Comment by chrisdavidmills** [comment]
Note added to Fx 70 rel notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#CSS

**Comment by chrisdavidmills** [comment]
MDN Group Name for "CSS Motion" changed to "CSS Motion Path", as I believe this more correct, and it stops the landing page links in the sidebar breaking: https://github.com/mdn/data/pull/388

**Comment by chrisdavidmills** [comment]
Other updates:

* compat data added: https://github.com/mdn/browser-compat-data/pull/4837
* interactive example added: https://github.com/mdn/interactive-examples/pull/1442
* group name fixed, to stop some links breaking: https://github.com/mdn/data/pull/388
* aforementioned release note removed again because I then realised it is behind a pref!

**Comment by BorisChiou** [comment]
One thing to note: for `<position>` value, we retire the 3 value syntax already (except for `<background-position>`), in [Bug 1559276](https://bugzilla.mozilla.org/show_bug.cgi?id=1559276).

The resolved spec issue is https://github.com/w3c/csswg-drafts/issues/2140.

**Comment by BorisChiou** [comment]
This means these examples:
```
offset-anchor: bottom 10px right;
offset-anchor: top right 10px;
```
may need to be updated.

For other parts, looks good to me. Thanks for the documentation.

**Comment by chrisdavidmills** [comment]
Cool, thanks for the review @BorisChiou !

I've removed the 3-value examples, and added a note to https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor#Values.

We are actually documenting that change separately, as part of https://github.com/mdn/sprints/issues/2084

**Comment by BorisChiou** [comment]
Cool! Thanks!

**Comment by jmswisher** [comment]
Should have been closed a while ago
