### ISSUE TITLE
[JavaScript] BigInt docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2110]
Trello: https://trello.com/c/toqiqtQ1/17-bigint-fx-70

# Acceptance criteria

1. - [x] [Implement BigInt support to Intl.NumberFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1543677)
2. - [x] [Disallow BigInt literals for Annex-B non-octal digits](https://bugzilla.mozilla.org/show_bug.cgi?id=1568619)

**Comment by Elchi3** [comment]
First one is pending review: https://bugzilla.mozilla.org/show_bug.cgi?id=1543677#c7
Second is done: https://bugzilla.mozilla.org/show_bug.cgi?id=1568619#c7 ff.

**Comment by Elchi3** [comment]
Done and reviewed
