### ISSUE TITLE
[JavaScript] Numeric separators docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2111]
Trello: https://trello.com/c/ZJ6IVDrd/206-numeric-separators-fx-70

# Acceptance criteria

1. - [x] [Enable numeric separators in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1435818)
2. - [x] Also need to set DDC on [Implement Numeric Separators](https://bugzilla.mozilla.org/show_bug.cgi?id=1421400), once it is all done.

**Comment by Elchi3** [comment]
Pending review https://bugzilla.mozilla.org/show_bug.cgi?id=1435818#c11

**Comment by Elchi3** [comment]
All done!

**Comment by ExE-Boss** [comment]
https://github.com/mdn/kuma/pull/6012 is needed to enable syntax highlighting in code blocks.
