### ISSUE TITLE
Update Debugger Shortcuts

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#2114]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Acceptance criteria
- [ ] Update the shortcut list for the Debugger to include Ctrl + Shift + L or Cmd + Opt + L to open the debugger.

**Comment by jmswisher** [comment]
Updated https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts#Debugger and https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Open_the_debugger
