### ISSUE TITLE
[WebAPI] web components docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2117]
Trello: https://trello.com/c/M46uVg89/24-web-components-related-updates-fx-70

# Acceptance criteria

1. - [x] [Can we do some sort of sharing across <style> in different instantiations of a shadow DOM component?](https://bugzilla.mozilla.org/show_bug.cgi?id=1480146)

**Comment by justinfagnani** [comment]
@chrisdavidmills is the note about recommending external styles new? This might not be a universally agreed on recommendation. On the Polymer team we generally recommend internal styles because they prevent a FOUC, and they're visible to the ShadyCSS scoping polyfill. With the change to Firefox 70 to dedupe identical `<style>` tags is there a reason not to recommend internal sheets?

Ultimately Constructible Stylesheets and CSS modules will be the best way, when those are available.

Also, is there a more appropriate place to ask this question? Should I make an edit to the page and ask for editorial review? Thanks!

**Comment by justinfagnani** [comment]
@chrisdavidmills I made an edit to "Using Shadow DOM" and checked the technical review flag, but I guess there's no review step or proposed edit, so it looks like the change is going live 😬

Here's the diff: https://wiki.developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM$compare?locale=en-US&to=1585884&from=1581626

Can you tag in whoever asked you to make the change so they can see?

**Comment by chrisdavidmills** [comment]
@justinfagnani yeah, that's the way we roll on MDN, for better or for worse ;-\

I also made the change to the similar section in the custom elements article.

@emilio suggested this change initially; Emilio what do you think about Justin's change to our best practice concerning internal versus external styles in shadow dom?

**Comment by emilio** [comment]
Well, I tend to disagree with that comment. There are ways to load components with `<link>` without causing FOUC, and `<link>` can be parsed off the main thread, unlike `<style>`.

Firefox doesn't have the `<style>` element optimization until Firefox 70, note (https://bugzilla.mozilla.org/show_bug.cgi?id=1480146), but even with that `<link>` is faster.

**Comment by justinfagnani** [comment]
Hey @emilio. What's the technique to avoid FOUC with link? In https://github.com/Polymer/lit-element/pull/762 you mentioned that link doesn't block.

There are other factors to consider between the two approaches. Inline styles tend to have their contents described and inserted in JS, which naturally works well with bundlers. Bundling link tags, especially dynamically created link tags, seems like it'll need more configuration.

Could we leave it without a recommendation?

**Comment by emilio** [comment]
You can avoid the FOUC if the link is loaded before injecting the webcomponent. So something like:

```js
// After this promise resolves, using `<link rel="stylesheet" href=${linkURL}>` in a component will never produce FOUC.
function componentStylesReady(linkURL) {
  return new Promise(resolve => {
    let link = document.createElement("link");
    link.rel = "alternate stylesheet"; // Download it, but never apply it to the page.
    link.onload = function() {
      resolve();
      link.onload = null;
    };
    document.body.appendChild(link);
  });
}
```

With constructable stylesheets, you can do the same with `CSSStyleSheet.replace()`, rather than `replaceSync()`, and that doesn't have the bundler problem I guess.
