### ISSUE TITLE
[WebAPI] History API docs tasks, Firefox 70 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2119]
Trello: https://trello.com/c/r3ruThJ3/44-history-api-fx-70

# Acceptance criteria

1. - [x] [Make history navigations asynchronous](https://bugzilla.mozilla.org/show_bug.cgi?id=1563587)
2. - [x] Check the other tasks listed on the trello card, to  make sure they have been done, as required.

**Comment by chrisdavidmills** [comment]
Assigning to @irenesmith , as she just did some work on the History API.

**Comment by irenesmith** [comment]
- Updated the Fx 70 release notes to mention that the back, forward, and go methods are asynchronous.
- Updated the History page to mention that go, back, and forward methods are asynchronous.
- Added a discussion on each of the method's pages to mention that it is asynchronous and that the popstate method needs to be handled to determine when the navigation has completed.

See also section for each of the back, forward, and go methods includes a link to the popstate event.
