### ISSUE TITLE
Broken link and inaccurate link on "Advanced styling for HTML forms" page

### ISSUE THREAD

**Issue by jfhector** [mdn/sprints#2122]
## Request type
- [ ] New documentation
- [x ] Correction or update

## Details of the issue

On this page, under this section: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Advanced_styling_for_HTML_forms#Controlling_the_appearance_of_form_elements

... there are currently two links:
1. one named 'webkit-appearance'
2. the other name '-moz-appearance'

The first one ('webkit-appearance') points to a missing page.
The second one ('-moz-appearance') points to a page titled "appearance (-moz-appearance, -webkit-appearance)", which deals with both versions of the 'appearance' property.

The first (broken) link should be removed. The name of the second link should reflect the fact that it describes both 'webkit-appearance' and '-moz-appearance'

## Sidenote: thanks

Thanks for all your great content, MDN has been invaluable to me.

**Comment by chrisdavidmills** [comment]
Hey, thanks for reporting this, and I'm so glad you are finding MDN so useful.

I've updated that article section to fix the broken link, and to explain the current situation with appearance more accurately.

As a note, we are intending to give the HTML Forms learning module a full update very soon, to improve and modernize it. Let me know if you see anything else that you really think could be improved about it.

Best regards.

**Comment by jfhector** [comment]
Thanks a lot, the change looks great.
