### ISSUE TITLE
[WebAPI] Web Audio API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2124]
Trello: https://trello.com/c/z7uW1xc5/103-web-audio-api-fx-70

# Acceptance criteria

1. - [x] [Implement AudioContext getOutputTimestamp()](https://bugzilla.mozilla.org/show_bug.cgi?id=1324545)
2. - [x] [Implement BaseAudioContext baseLatency and outputLatency attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1324552)
3. - [x] [Implement new attributes MediaStreamAudioSourceNode and MediaElementAudioSourceNode](https://bugzilla.mozilla.org/show_bug.cgi?id=1350973)
4. - [x] [ChannelMergerNode constructor should throw errors](https://bugzilla.mozilla.org/show_bug.cgi?id=1456263)

**Comment by chrisdavidmills** [comment]
getOutputTimestamp() covered:

* https://wiki.developer.mozilla.org/en-US/docs/Web/API/AudioContext
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/AudioContext/getOutputTimestamp
* https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#APIs
* BCD added: https://github.com/mdn/browser-compat-data/pull/5013

**Comment by padenot** [comment]
Chris, this documentation looks good to me, thanks!

**Comment by chrisdavidmills** [comment]
cheers @padenot! I'll finish off the rest of these docs tasks on Monday.

**Comment by chrisdavidmills** [comment]
`baseLatency` and `outputLatency` covered:

* https://developer.mozilla.org/en-US/docs/Web/API/AudioContext
* https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/baseLatency
* https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/outputLatency
* Compat data updated: https://github.com/mdn/browser-compat-data/pull/5019

**Comment by chrisdavidmills** [comment]
`ChannelMergerNode` docs completed:

* Rel note added to https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#APIs
* Exceptions section added to the constructor page: https://wiki.developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode/ChannelMergerNode#Exceptions

**Comment by chrisdavidmills** [comment]
`mediaStream` and `mediaElement` docs sorted out:

* BCD updated: https://github.com/mdn/browser-compat-data/pull/5096
* Rel notes: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#APIs
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioSourceNode
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioSourceNode/mediaStream
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode/mediaElement
