### ISSUE TITLE
[WebAPI] WebRTC docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2125]
Trello: https://trello.com/c/ejryeYyB/73-webrtc-10-fx-70

# Acceptance criteria
_Crossed-out rows have slipped out of 70 and will not arrive until later. No-parameter setLocalDescription() might happen in 71; the other will not come until 72 earliest._

1. - [x] [Add pc.restartIce() method](https://bugzilla.mozilla.org/show_bug.cgi?id=1551316) (`RTCPeerConnection.restartIce()`)
2. - [x] Add [implicit rollback to `setRemoteDescription()`](https://bugzilla.mozilla.org/show_bug.cgi?id=1567951) per updated spec
~3. - [ ] [Allow `setLocalDescription()` to be called with no arguments](https://bugzilla.mozilla.org/show_bug.cgi?id=1568292) per updated spec~
~4. - [ ] [Support `RTCRtpTransceiver` interface's `stopping` attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1568296) and the `stopping` value for `direction` and `currentDirection`.~
5. - [x] [Support groupId in constraints](https://bugzilla.mozilla.org/show_bug.cgi?id=1561254)
6. - [x] [Update webRTCIPHandlingPolicy to match Chrome behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1452713)

**Comment by a2sheppy** [comment]
Fortunately, I know a lot of this work is already done. They're just not marked off because we didn't know a release version yet to update BCD and such. I will go through them and make sure content is in place and BCD is GTG.
