### ISSUE TITLE
[HTTP] feature-policy docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2126]
Trello: https://trello.com/c/1NkwWH1e/88-feature-policy-fx-70

# Acceptance criteria

1. - [x] [Implement FeaturePolicy.features()](https://bugzilla.mozilla.org/show_bug.cgi?id=1514474)
2. - [x] [Disallow notification permission requests from cross-origin iframes](https://bugzilla.mozilla.org/show_bug.cgi?id=1560741)

**Comment by Elchi3** [comment]
> Implement FeaturePolicy.features()

The compat data has been updated for this, but the whole FeaturePolicy API seems to be behind a pref still. So, I don't think it is worth adding this to any release notes yet.

https://developer.mozilla.org/en-US/docs/Web/API/FeaturePolicy

**Comment by chrisdavidmills** [comment]
@Elchi3 what was the latest status of this one? FeaturePolicy.features() is documented but is still showing as supported by defailt in Fx 70. Does this need to be updated?

And what about for the 2nd AC?

**Comment by Elchi3** [comment]
@chrisdavidmills yes, I think the compat data for featurepolicy needs fixing as it is a bit confusing as is.

For the second AC, the change is described here https://www.fxsitecompat.dev/en-CA/docs/2019/notification-permission-requests-from-cross-origin-iframe-are-now-disallowed/ It seems to me that we should note this in the Notification docs rather than in the http docs. Do you want to deal with that or should I?

**Comment by chrisdavidmills** [comment]
If you could have a go at that, I'd really appreciate it. Thanks mate!

**Comment by Elchi3** [comment]
For FeaturePolicy.features: I've sent a BCD PR.

For the second item: I'm not really familiar with the Notifcation API or its docs and it seems like there is some doc work happening soon in https://github.com/mdn/sprints/issues/2464. Would you mind doing this work together with the other notification changes, @chrisdavidmills ? It has nothing to do with FeaturePolicy, as far as I can tell.

**Comment by chrisdavidmills** [comment]
@Elchi3 yeah, you are right that it isn't really relevant; sorry about that!

And yes, I think it fits in with the cited issue. I've moved it to there, so we can consider this one done.

**Comment by Elchi3** [comment]
No worries and thanks for reviewing the BCD PR! 
Let's call this whole issue done then. I've marked the FeaturePolicy bug as dev-doc-complete.
