### ISSUE TITLE
[HTTP] CSP docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2127]
Trello: https://trello.com/c/cp2ES11r/120-csp-general-enhancements-fx-70

# Acceptance criteria

1. - [x] [Misleading console message for X-Frame-Options Allow-From mismatch (remove X-Frame-Options: allow-from)](https://bugzilla.mozilla.org/show_bug.cgi?id=1301529) (sort of CSP-related, so I put it here)

**Comment by Elchi3** [comment]
Doc work done and reviewed by jkt, see https://bugzilla.mozilla.org/show_bug.cgi?id=1301529#c10
