### ISSUE TITLE
[HTTP] CORS docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2128]
Trello: https://trello.com/c/0QD3sJXc/151-cors-enhancements-fx-70

# Acceptance criteria

1. - [x] [[CORS] Add wildcard to Access-Control-Expose-Headers, Access-Control-Allow-Methods, and Access-Control-Allow-Header](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)

**Comment by Elchi3** [comment]
This was shipped in 69 and I've documented it already. See https://bugzilla.mozilla.org/show_bug.cgi?id=1309358#c28 ff.
