### ISSUE TITLE
[HTTP] HTTP cache docs tasks, Fx 70 (legacy task, needs doing)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2130]
Trello: https://trello.com/c/KidbXf70/226-http-cache-fx-70

# Acceptance criteria

1. - [ ] [Partition the HTTP cache per the top-level document's origin](https://bugzilla.mozilla.org/show_bug.cgi?id=1536058)

**Comment by Elchi3** [comment]
Intent to ship contains some explanations about this thing: https://groups.google.com/d/msg/mozilla.dev.platform/eFx-93iBPpU/Hs4jUZRgDgAJ

However, this has not yet landed. It is not in 72! See https://bugzilla.mozilla.org/show_bug.cgi?id=1594004 which is still open.

Should we document this already?

**Comment by chrisdavidmills** [comment]
Thanks for the analysis @Elchi3 ; I've un-DDNed the original referred bug, and will now close this. I'll monitor the other bug to see if it lands again at any point.
