### ISSUE TITLE
[DevTools] Primary tool updates docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2131]
Trello: https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-js-debugger-fx-70

# Acceptance criteria

1. - [x] [DOM Mutation Breakpoints: Enable by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1576219)
2. - [ ] [Enable Inline Preview for all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1576679)

**Comment by irenesmith** [comment]
Created page: [Break on DOM Mutation](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Break_on_DOM_mutation) and added it to the Debugger landing page.

**Comment by irenesmith** [comment]
Need to confirm that I've created the correct images for inline preview. It doesn't look any different than what is in Firefox 69 and I have not enabled it on the release version, even if it existed behind a preference.

**Comment by irenesmith** [comment]
It turns out that Inline Preview is behind a pref in 70 and may or may not be on by default in 71. Need to recreate my image and then add it to the document with information about how to turn it on.
