### ISSUE TITLE
[DevTools] New remote debugging docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2132]
Trello: https://trello.com/c/ZLneh5mV/10-new-remote-debugging-aboutdebugging-fx-70

# Acceptance criteria

1. - [x] [[remote-dbg-next] Disable WebIDE and the Connect... page by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1539451)
2. All tasks completed as outlined at the top of our [remote debugging planing doc](https://docs.google.com/document/d/1s9Mlk4M6VNfxNHnsP4rgUfQRuLMI4PT40o3g-yFXzzY/edit#); this includes:
- [x] Document "Connect a device (USB)" on [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) page
- [x] Document "Network Location" on [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) page
- [x] [Remote debugging](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging) page needs outdated content removed
- [x] Remove 37 notes, Connect page and WebIDE from [debugging firefox desktop page](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop), update page with latest way of doing things
- [x] Remove [Valence](https://developer.mozilla.org/en-US/docs/Tools/Valence) page
- [x] Remove [WebIDE debugging](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE) page
- [x] Remove [Debugging FxA over Wifi](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_over_Wifi) page
- [x] Replace debugging over wi-fi with with a Debugging FxA via USB page
- [x] Remove [WebIDE troubleshooting](https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Troubleshooting) page, create new troubleshooting page for about:debugging
3. - [ ] Update the tools sidebar, as per below instructions
* Put main tools at top level
* Put other tools under a menu item
* Accessibility inspector is in core tools and other tools. Just put in core tools, at the top level
* Remove deprecated tools (just mention it on the main page text somewhere)
* The "Connecting the devtools" section in the "Related Topics" needs updating:
  * about:debugging -> is fine
  * Add link to new connecting to Firefox Desktop page you'll create
  * Connecting to Firefox for Android -> directly points to the WiFi documentation, should probably point to the new FxA page you'll create instead
  * Connecting to iframes -> this is a toolbox feature
  * Connecting to other browsers -> we are not supporting this, remove

**Comment by chrisdavidmills** [comment]
@irenesmith I was in the middle of creating all the docs tasks for the next sprint, so I just created this one for you.

**Comment by chrisdavidmills** [comment]
This supercedes https://github.com/mdn/sprints/issues/1976

**Comment by chrisdavidmills** [comment]
This also supercedes https://github.com/mdn/sprints/issues/1967

**Comment by irenesmith** [comment]
These are the three items that remain here:

Document "Network Location" on [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) page
Remove 37 notes, Connect page and WebIDE from [debugging firefox desktop page](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop), update page with latest way of doing things
Replace debugging over wi-fi with with a Debugging FxA via USB page

I expect to finish them by the end of Tuesday, October 22, 2019.

**Comment by jmswisher** [comment]
Adding myself to review

**Comment by jmswisher** [comment]
This is all done except for the sidebar changes; Irene's PR has requested changes that haven't been made. Probably needs a new issue and a new PR to deal with that.

**Comment by chrisdavidmills** [comment]
Will said he'd sort this PR situation out; I've given him a nudge in the PR.
