### ISSUE TITLE
[WebExt] Tabs API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2133]
Trello: https://trello.com/c/FaVjhDCL/117-tabs-api-enhancements-fx-70

# Acceptance criteria

1. - [x] [Zoom API's in chrome.tabs don't work correctly](https://bugzilla.mozilla.org/show_bug.cgi?id=1286953) (I think the docs work here is to basically add a note to BCD to say that these APIs don't work properly, and link to the bug, until they are fixed.)
2. - [x] ['Property "muted" is unsupported by Firefox' (Android)](https://bugzilla.mozilla.org/show_bug.cgi?id=1373035) (quick compat data update)
3. - [x] [tabs.Tab.audible returns incorrect result for muted tabs that are playing sound](https://bugzilla.mozilla.org/show_bug.cgi?id=1379858) (historical, small docs update)
4. - [x] [Document insertCSS interaction with page styles](https://bugzilla.mozilla.org/show_bug.cgi?id=1428398) (historic, see [comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1428398#c4))
5. - [x] [Support the "discarded" property inside browser.tabs.create()](https://bugzilla.mozilla.org/show_bug.cgi?id=1378647) (historic)

**Comment by rebloor** [comment]
Zoom API's in chrome.tabs don't work correctly:  it would appear that the compatibility data was updated for tabs.setZoomSettings in December 2017.  [Flagged the reporter needinfo](https://bugzilla.mozilla.org/show_bug.cgi?id=1286953#c8) to confirm whether dev-doc-done.

**Comment by rebloor** [comment]
Zoom API's in chrome.tabs don't work correctly: I have removed the dev-doc-needed for this bug as it appears the documentation correctly shows that this feature is not supported, the bug appears to be requesting its implementation.

**Comment by rebloor** [comment]
Support the "discarded" property inside browser.tabs.create() (historic): developer approved documentation changes 12/5
