### ISSUE TITLE
[WebExt] Menu API docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2135]
Trello: https://trello.com/c/aMjyfOir/105-menus-api-enhancements-fx-70

# Acceptance criteria

1. - [x] [browser.menus.update() does not support updating icon](https://bugzilla.mozilla.org/show_bug.cgi?id=1414566) (this never got done, even thought it was on this before. I think that makes it a high priority)
2. - [x] [contextMenus.OnClickData should provide selector of the clicked element](https://bugzilla.mozilla.org/show_bug.cgi?id=1325814) (you worked on this, then Rob Wu gave you feedback, then it looks like you never acted on the feedback; see [comment 65](https://bugzilla.mozilla.org/show_bug.cgi?id=1325814))
3. - [x] [Always use documentUrlPatterns to match the document URL in extension views, even when menus.overrideContext is used](https://bugzilla.mozilla.org/show_bug.cgi?id=1498896) (historic, should probably get it fixed up)

**Comment by irenesmith** [comment]
Changed the existing statement on the [update method](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/update) to state:

 In addition, icons can only be changed on menu commands, not on the top-level context menu. The top-level icon matches the extension's primary icon as declared in the extension's manifest file.

**Comment by irenesmith** [comment]
All comments from [Bugzilla 1325814](https://bugzilla.mozilla.org/show_bug.cgi?id=1325814) have been incorporated into the documentation. I discovered that most of this was already done.

**Comment by irenesmith** [comment]
Copying my response from [Bugzilla ](https://bugzilla.mozilla.org/show_bug.cgi?id=1498896) along with the comments which prompted the changes:

> After bug 1367160, bug 1280347, bug 1416839 is documented, the change from
> this bug should also be documented on MDN, at the following places:
> - documentUrlPatterns property in the parameter for the menus.create and
> menus.update methods

Documented as part of the createProperties/updateProperties objects of [create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create) and [update](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/update).

> - viewTypes property in the parameter for the menus.create and menus.update
> methods

Documented as part of the createProperties/updateProperties objects of [create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create) and [update](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/update)

> - the frameUrl property of menus.OnClickData

Added to [OnClickData](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData):
frameUrl Optional
    string. The URL of the frame of the element where the context menu was clicked, if it was in a frame.

> - the menus.overrideContext method
[overrideContext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/overrideContext)
