### ISSUE TITLE
[WebExt] Downloads API docs tasks, Fx 70 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2137]
Trello: https://trello.com/c/STmpS11A/111-downloads-api-enhancements-fx-70

# Acceptance criteria

1. - [x] [Support endTime in DownloadItem](https://bugzilla.mozilla.org/show_bug.cgi?id=1256269) (looks like we just need to update the BCD to say that `webextensions.api.downloads.DownloadItem.estimatedEndTime` is not yet supported in Fx)
2. - [x] [browser.downloads.download() should allow setting Referer (and others)](https://bugzilla.mozilla.org/show_bug.cgi?id=1367626)

**Comment by irenesmith** [comment]
Created [PR 4979](https://github.com/mdn/browser-compat-data/pull/4979) to update BCD for estimatedEndTime

**Comment by irenesmith** [comment]
It looks as though the work for referrer was done by Richard Bloor a month ago. Was this part of a different issue?
