### ISSUE TITLE
[WebExt] browser API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2138]
Trello: https://trello.com/c/LBJWI3hD/229-browser-api-enhancements-fx-70

# Acceptance criteria

1. - [x] [Expose captive portal status](https://bugzilla.mozilla.org/show_bug.cgi?id=1545159) (historic)
2. - [x] ["encoding" parameter not parsed in custom search engine overrides](https://bugzilla.mozilla.org/show_bug.cgi?id=1500741) (looks like a pretty quick fix) (historic)

**Comment by irenesmith** [comment]
It looks as though the issue was fixed, that the encoding parameter is now parsed and validated, and there is a merged pull request for BCD. Am I missing something here? What else needs to be documented?

**Comment by jmswisher** [comment]
@chrisdavidmills If the AC are satisfied, please close this issue.

**Comment by chrisdavidmills** [comment]
Assigning @rebloor so he can check this.

**Comment by rebloor** [comment]
Made an information needed request for Expose captive portal status (historic).

**Comment by rebloor** [comment]
@chrisdavidmills  I have written a draft of the MDN content for Expose captive portal status (historic) [here](https://docs.google.com/document/d/1gxGi6uqJku0HJDwRF56uuBZR1-Gts93HxOT7Uxn0Ps0/edit#) and made a request for information on the bug.  Do you think this API warrants a new example web extension? Could it be incorporated into any of the existing ones? I've not had any inspiration in that regard.

**Comment by chrisdavidmills** [comment]
@rebloor it'd be best to ask the associated engineers for advice on this — I'm not hugely knowledgeable on WebExtensions. If it makes sense to create a new one (even a really simple template that users can build on?), that would be fine with me.

**Comment by rebloor** [comment]
Pinged the developer on the Bugzilla ticket re the need for an example

**Comment by rebloor** [comment]
Documentation for [captivePortal](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/captivePortal) is now up, pending approval of compatibility data.

**Comment by rebloor** [comment]
Compatibility data for captivePortal has now been published.
