### ISSUE TITLE
[WebExt] General API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2139]
Trello: https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-70

# Acceptance criteria

1. - [x] [Extend the top sites API to optionally return TopSitesFeed sites for small history](https://bugzilla.mozilla.org/show_bug.cgi?id=1568617)
2. - [x] [URLs with ports should either be rejected as "matches" patterns, or be matched properly](https://bugzilla.mozilla.org/show_bug.cgi?id=1362809) (pretty small update to our [Match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns) docs)

**Comment by irenesmith** [comment]
For Bugzilla [1362809](https://bugzilla.mozilla.org/show_bug.cgi?id=1362809), I added the following note in the path section of [Match patterns in extension manifests](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns):

**Note:** The path pattern string should not include a port number. Adding a port, as in: "http://localhost:1234/*" causes the match pattern to be ignored. However, "http://localhost:1234" will match with "http://localhost/*"

Please let me know if I misinterpreted the comments above. Thanks!

**Comment by irenesmith** [comment]
Added the following to []():

newtab Optional
    Boolean. If included, the method returns the list of pages returned when the user opens a new tab. If included, and set to true, the method ignores all other parameters except limit and includeFavicon. Defaults to false.

And this paragraph to the release notes:

Added a new parameter to the topSites.get() method that causes the method to return the list of pages that appear when the user opens a new tab (bug 1568617).
