### ISSUE TITLE
[WebExt] Storage API docs tasks, Fx 70 (high priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2140]
Trello: https://trello.com/c/Pw66h6fb/56-storage-api-related-tasks-fx-70

# Acceptance criteria

1. - [ ] [Implement "chrome.storage.managed"](https://bugzilla.mozilla.org/show_bug.cgi?id=1230802) (originally worked on in 67 cycle, but documentation needs improvement; see [Will's comments](https://github.com/mdn/browser-compat-data/pull/4763#pullrequestreview-283789197))
2. - [ ] Recreate the PR for BCD

**Comment by Elchi3** [comment]
https://github.com/mdn/browser-compat-data/pull/4763 was closed due to inactivity. Please open a new PR.

**Comment by irenesmith** [comment]
Thank you. I was going to do that myself so that I could start fresh on this one.

**Comment by irenesmith** [comment]
Sent a meeting request to Mike Ratcliffe for Tuesday morning, 8 October, (the earliest I could get) to discuss the feature and make sure I am presenting it properly.

**Comment by irenesmith** [comment]
Even after meeting with Mike Ratcliffe, I don't have a clear message here. I sent an email to Amy Tsay last week for which I have not received a reply. I sent a follow-up email today Oct. 14.

**Comment by irenesmith** [comment]
I moved this back into the backlog because I haven't had a response yet. I will send another followup today.

**Comment by irenesmith** [comment]
I've begun a discussion with Philipp Kewisch about how to discuss the differences between the two methods and what message we should be giving about deciding what method to use.

**Comment by irenesmith** [comment]
On the advice of Chris, I'm backing out the changes I made and closing this task.

**Comment by irenesmith** [comment]
Reverted to the version of the page from before I started making changes. I did change the spelling of colour to color but otherwise it is as it was before.
