### ISSUE TITLE
[WebExt] Cookie API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2141]
Trello: https://trello.com/c/AObljdHp/112-cookie-api-enhancements-fx-70

# Acceptance criteria

1. - [ ] [Make sure test_ext_privacy.js doesn't depend on the default value of the network.cookie.cookieBehavior preference](https://bugzilla.mozilla.org/show_bug.cgi?id=1493057) (this was marked as done, but it looks like the browser compat-data still needs updating. So I've reopened it)

**Comment by rebloor** [comment]
@chrisdavidmills The compat-data doesn't break down `cookieConfig` to provide information on its properties and therefore it doesn't provide any information about the values that `behavior` can take.  The `reject_trackers` value is documented on [privacy.websites](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites), although there is no mention of the browser version it was introduced in, this would seem to be the extent to which we can document this feature.

**Comment by chrisdavidmills** [comment]
@rebloor even though we don't have individual BCD for most properties, it would be nice to add a sub-feature for the new value(s). That way, you can look at the data and assume that all other values were supported when cookieConfig started to be supported, and then the ones specifically mentioned started being supported some time after. Does that seem reasonable?

The only other thing to do would be to add a rel note to mention its addition:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70

**Comment by rebloor** [comment]
This is already mentioned in the 64 release notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/64#Changes_for_add-on_developers.  I'll look at adding a sub-feature to the compatibility data.

**Comment by rebloor** [comment]
@chrisdavidmills unless I am missing something, to add sub-features for the values in `behavior` I would need to add 2 subtables to the compatibility data, so we would end up with you.

* H1: Browser compatibility >  table
* H2: cookieConfig >  table ( showing behavior and nonPersistentCookies)
* H3: cookieConfig behavior values>  table

which seems excessive just to note the addition of a value. I have, therefore, submitted a PR for a change with the value's addition detailed in a note. However, if you would prefer the more extensive breakdown please let me know.

**Comment by chrisdavidmills** [comment]
Hrm, it is a bit excessive. OK, let's leave it like that for now, and see if anyone else has any thoughts ;-)

**Comment by rebloor** [comment]
I've submitted a PR to add a note: https://github.com/mdn/browser-compat-data/pull/4932

**Comment by rebloor** [comment]
@chrisdavidmills The compatibility data with the note about the introduction of `reject_trackers` has been merged.
