### ISSUE TITLE
[WebExt] theme API docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2142]
Trello: https://trello.com/c/xcCA0745/107-theming-enhancements-fx-70

# Acceptance criteria

1. - [x] [Remove aliased property names from themes](https://bugzilla.mozilla.org/show_bug.cgi?id=1472740)
2. - [x] [Implement theme experiments](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207) (historic)

**Comment by rebloor** [comment]
Re [Implement theme experiments](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207): I have been unable to find a functional description of the change, so I've drafted a best guess set of content for the MDN update, included it in the bug, and narked it as an information request for Tim Nguyen.

**Comment by rebloor** [comment]
@chrisdavidmills  I have now completed all these changes, incorporating comments and feedback from Tim Nguyen into the information about theme_experiment. A request for review of the MDN page went out from the original Bugzilla to Jared and Mike. Are you happy if I close this issue, or would you like it double checked by anybody?

**Comment by chrisdavidmills** [comment]
I think you can close this now, @rebloor. Can you just provide a summary of all pages touched/work done in this issue? Also:

* Did you put a note in the Fx 70 rel notes about it?
* You also need to update the "dev-doc-needed" keyword inside each related bugzilla bug to "dev-doc-complete".
* Usually we also put a note in the bug saying something like "docs work has been done; see [link to issue] for a description of exactly what we did. Please can I have a review?". But you say you already reuqested a review and got feedback, so that's OK.

**Comment by rebloor** [comment]
@chrisdavidmills  I will get those things done. Regarding the release notes: 

- I'll add details about the alias removal to Fx 70
- for theme_experiment my information is that that was introduced in 63 (bug marked the fixed version as 63 and I reiterated this in the discussions with Tim, although he didn't explicitly confirm it). Do you want to go back to 63 and add or include in 70 on the basis that's the version we documented it?

**Comment by chrisdavidmills** [comment]
For the stuff introduced in 63, add a note to the 63 rel notes. There's no point putting a note in the 70 notes, as it would just be confusing.

**Comment by rebloor** [comment]
@chrisdavidmills I have updated the release notes and the bugs, so now closing this one

**Comment by nt1m** [comment]
@rebloor Sorry for the delay. I just saw your comment on bugzilla regarding reviewing the changes now. :/

It looks like some examples are still using old property names:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes/Theme_concepts
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/update
https://github.com/mdn/webextensions-examples (there are some theme related examples in there)

A simple find/replace should probably suffice :)

(from https://github.com/mdn/sprints/issues/1867#issuecomment-517551897 )

**Comment by rebloor** [comment]
@nt1m  Story about overlooking these changes. The 3 pages are updated and the changes for the theme examples submitted under https://github.com/mdn/webextensions-examples/pull/430.
