### ISSUE TITLE
Math/round page missing

### ISSUE THREAD

**Issue by anewlink** [mdn/sprints#2144]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

**Comment by anewlink** [comment]
Missing url: https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Global_Objects/Math/round 
From
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Math

**Comment by chrisdavidmills** [comment]
The page is not missing, as such; it just hasn't been translated yet. We don't have any resources to translate pages on the MDN team, so rely on volunteers for such work. I'm clsing this one, but if you are interested in translating the page, please let me know.
