### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/en/Build_Documentation

### ISSUE THREAD

**Issue by Halamix2** [mdn/sprints#2154]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

When following first link on https://developer.mozilla.org/en-US/docs/Mozilla/Building_Mozilla it redirects to https://developer.mozilla.org/en-US/docs/Mozilla/en/Build_Documentation, which is a 404 page
I don't know what was on build_documentation page, maybe link could be changed to https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions ?

**Comment by chrisdavidmills** [comment]
Done; thanks for reporting!
