### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_OpenGL

### ISSUE THREAD

**Issue by forderud** [mdn/sprints#2158]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The "When running a debug build" sentence on https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_OpenGL contains a link to http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/ . It's unclear to me how to find a recent Firefox Win64 debug build from this FTP link.

Issues with the FTP link:
* I have no clue on which folder to navigate to for the most relevant win64 debug build (alder, ash, autoland, birch,..)
* Most files on the FTP share seem to be from 2017 or older.

**Comment by chrisdavidmills** [comment]
Hrm, this page looks very old. I've never seen it before. I've never heard of debug builds. I wonder if they are just something we did in the past, the functionality of which is now available in [Nightly builds](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)?

Did you try following these instructions in Nightly?

**Comment by forderud** [comment]
> Hrm, this page looks very old. I've never seen it before. I've never heard of debug builds. I wonder if they are just something we did in the past, the functionality of which is now available in [Nightly builds](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)?
> 
> Did you try following these instructions in Nightly?

Nightly builds seem to be something different than debug builds. What I'm trying to debug is a WebGL issue in my own code. I'm not trying to debug a Firefox issue. I therefore don't see how a nightly build would help me.

If you take a look at the Firefox sourcecode, then you'll see that there's a [MOZ_GL_DEBUG](https://github.com/mozilla/gecko-dev/blob/master/gfx/gl/GLContext.h#L29) preprocessor define being set when building in debug. This define enables GL debugging in https://github.com/mozilla/gecko-dev/blob/master/gfx/gl/GLContext.cpp#L236

**Comment by chrisdavidmills** [comment]
Right, OK. I'll ask some of our engineers to see if they can point us in the direction of more up-to-date debug builds, or a way to turn on this debugging.

**Comment by chrisdavidmills** [comment]
Turns out the place to go to find up-to-date debug builds is Mozilla Taskcluster: https://tools.taskcluster.net/index/gecko.v2.mozilla-central.latest.firefox

I've updated the instructions on that page.

**Comment by forderud** [comment]
Thanks a lot for being so helpful @chrisdavidmills :-)
