### ISSUE TITLE
input attributes

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2159]
Create attribute pages for the following:
* [ ] accept  

* [ ] alt    

* [ ] autocomplete    

* [ ] autofocus  

* [ ] capture 

* [ ] checked  

* [ ] dirname 

* [ ] disabled 

* [ ] formaction 

* [ ] formenctype    

* [ ] formmethod 

* [ ] formnovalidate 

* [ ] formtarget 

* [ ] id    (already exist. update)

* [ ] inputmode  

* [ ] list    

* [X] max    

* [ ] maxlength  

* [X] min  

* [ ] minlength 

* [ ] multiple  

* [ ] name   

* [ ] pattern  

* [ ] placeholder 

* [ ] readonly  

* [ ] required 

* [ ] size 

* [ ] src  

* [X] step  

* [ ] tabindex 

* [ ] title   (already exist. update)

* [ ] type   

* [ ] value 

* [ ] width

While there is a BCD for the values of the &lt;input>'s type attribute, there is no BCD for the other attributes, such as step, form, readonly, etc.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Browser_compatibility

**Comment by estelle** [comment]
I updated https://www.wufoo.com/html5/ in 2013. Time to update that on MDN

**Comment by jmswisher** [comment]
@estelle Is 9 the amount of work still remaining? If so, this _really_ needs to be broken into smaller chunks.
