### ISSUE TITLE
Add path() function page to CSS ref

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2162]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1486094#c43:

On https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path there's also just an example for animating offset-distance, which is not implemented yet. So  there is no page yet showing how to animate this function.

What's actually needed is a separate page for the path() function, i.e. https://developer.mozilla.org/en-US/docs/Web/CSS/path resp. https://developer.mozilla.org/en-US/docs/Web/CSS/path, like for other CSS functions.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've added a page for path() https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/path() which is defined in CSS Shapes. I wasn't sure what you meant about animation though.

**Comment by chrisdavidmills** [comment]
I'm not sure what's meant to mean either ;-)

It would be nice to have a slightly more complete example, something working/live.

**Comment by rachelandrew** [comment]
@chrisdavidmills I added a better example to this page which is now showing up.

https://developer.mozilla.org/en-US/docs/Web/CSS/path()

**Comment by chrisdavidmills** [comment]
Looks good; let's close this.
