### ISSUE TITLE
links dont work

### ISSUE THREAD

**Issue by kenhen1017** [mdn/sprints#2163]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ x] New documentation
- [ ] Correction or update

# Details

The following links don't work:

- https://developer.mozilla.org/en-US/docs/Tools/Adding_a_panel_to_the_toolbox

- https://developer.mozilla.org/en-US/docs/Tools/Example_add-ons
- https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Custom_output

**Comment by chrisdavidmills** [comment]
We deleted these pages, because the APIs they describe are no available. Where did you find the links?

If you found them in a sidebar, try doing Ctrl/Cmd + Shift + R to do a hard refresh, and it should force the page to be regenerated. The links shouldn't exist in a sidebar any more.
