### ISSUE TITLE
[CSS] Comma Combinator

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#2164]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I've updates the [CSS selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) page. One of the changes was to a missing "Comma Combinator" that selects all the elements. This one exists since CSS Level 1 ([reference](https://www.w3.org/TR/CSS1/#grouping)), but it had no page in MDN.

Please create a new page, I will add the content to the page.

**Comment by rachelandrew** [comment]
There isn't a comma combinator in CSS. You can see the list of Combinators in the CSS Selectors Spec Level 3 https://www.w3.org/TR/selectors-3/#combinators

What you are describing is a group of individual selectors as a comma separated list https://www.w3.org/TR/selectors-3/#grouping

**Comment by chrisdavidmills** [comment]
I've reverted the changes.

**Comment by ramiy** [comment]
@chrisdavidmills Why did you reverted all the changes? you could remove only the wrong one.

**Comment by chrisdavidmills** [comment]
@ramiy my apologies; I was a bit hasty there. I'll revert back, and then just remove the bit about "comma combinator"

**Comment by ramiy** [comment]
@rachelandrew @chrisdavidmills I've opened a new issue to create a page for the "Grouping Selectors". Please review.
