### ISSUE TITLE
Someone trashed https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

### ISSUE THREAD

**Issue by EmpireJones** [mdn/sprints#2165]
# Request type
- [x] Correction or update

# Details
It looks like this user's change intentionally trashed some of the code/text on 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

change:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent$compare?locale=en-US&to=1572244&from=1572243

![image](https://user-images.githubusercontent.com/15959998/65363376-67038b00-dbc0-11e9-8741-9f0d13f6ba36.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting. Some of the changes were good, but I'vereverted the strange-looking code change. Let me know if you think this needs anything else.
