### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

### ISSUE THREAD

**Issue by lborgman** [mdn/sprints#2170]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

Please see this question:
https://stackoverflow.com/questions/58062685/can-i-get-json-stringify-to-include-keys-with-value-undefined

All properties on the object are not listed. 

# Details

**Comment by chrisdavidmills** [comment]
I'm not sure what needs to be updated here, can you give me some more details?

**Comment by lborgman** [comment]
For example a property that has the value undefined will not be listed.

The reason is that this is not part of a json object. (See the thread.)

It is however a part of a JavaScript object.

Quite confusing.

**Comment by chrisdavidmills** [comment]
Ah, I understand now. Yes, JSON has some annoying quirks like this (another good example is that fact that you can't put comments in JSON).

So, the undefined thing is covered, see third bullet point at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description, but I've edited it to make it clearer.
