### ISSUE TITLE
Please correct the Japanese translation slug on the "CSS selectors" page.

### ISSUE THREAD

**Issue by snakada** [mdn/sprints#2174]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I started translating the English version of the original "CSS Selectors" into Japanese, but I also translated and registered the slug by mistake.

How can I correct it to the correct slug?

* ja(wrong): https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/%E3%82%BB%E3%83%AC%E3%82%AF%E3%82%BF
* ja(correnct): https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Selectors
* en-US(original): https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors

**Comment by chrisdavidmills** [comment]
Hi there!

There is a move page functionality available, but you have to have special permissions to do this.

I have fixed the URL for you, see https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Selectors

**Comment by snakada** [comment]
I was able to confirm that the Japanese version was linked correctly.

Thank you for your immediate response!

**Comment by chrisdavidmills** [comment]
You are welcome - happy to help!
