### ISSUE TITLE
https://developer.mozilla.org/en-US/users/account/email/confirm

### ISSUE THREAD

**Issue by njohnst** [mdn/sprints#2176]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Hi there -

Two issues:

1) Documentation

Native messaging doesn't specify that content scripts are not able to connect - need to use background script

And

2) my github verification email is not coming (because it is being sent to the wrong address, so I'm unable to fix the docs myself)

-nickjoh@protonmail.ch (Correct) / nickjoh@github.com (Wrong)

**Comment by chrisdavidmills** [comment]
> Native messaging doesn't specify that content scripts are not able to connect - need to use background script

Which page are you seeing this problem on?

> my github verification email is not coming (because it is being sent to the wrong address, so I'm unable to fix the docs myself)

Let me guess - is this an account that you haven't logged into since we did the GitHub login switchover? What is your username? I'm not sure how to fix this, but I can probably get someone from the MDN dev team to help.

**Comment by njohnst** [comment]
> 
> 
> > Native messaging doesn't specify that content scripts are not able to connect - need to use background script
> 
> Which page are you seeing this problem on?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

The example shows a background script being used - it doesn't mention that content scripts are disallowed though.  As a WebExtensions newbie, I didn't know that, and needed to use content scripts to access the DOM in my use-case
> 
> > my github verification email is not coming (because it is being sent to the wrong address, so I'm unable to fix the docs myself)
> 
> Let me guess - is this an account that you haven't logged into since we did the GitHub login switchover? What is your username? I'm not sure how to fix this, but I can probably get someone from the MDN dev team to help.

It's a new account, I have multiple emails associated to my Github profile for commit purposes - one or two of which are not valid addresses. - I clicked on the invalid one because I thought the email would be public / not used for verification purposes - and wanted to avoid spam.

It seems like there's no option to change the verification email to the correct one (nickjoh@protonmail.ch)

My profile name is `njohnst`.

**Comment by chrisdavidmills** [comment]
> > > Native messaging doesn't specify that content scripts are not able to connect - need to use background script
> > 
> > 
> > Which page are you seeing this problem on?
> > https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
> 
> The example shows a background script being used - it doesn't mention that content scripts are disallowed though. As a WebExtensions newbie, I didn't know that, and needed to use content scripts to access the DOM in my use-case

This was kind of hinted at, but not said explicitly, in this section:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#Extension_side

I've had a go at improving the wording; is this better now? I'm not hugely familiar with WebExt, so apologies if I've misunderstood this.

> 
> > > my github verification email is not coming (because it is being sent to the wrong address, so I'm unable to fix the docs myself)
> > 
> > 
> > Let me guess - is this an account that you haven't logged into since we did the GitHub login switchover? What is your username? I'm not sure how to fix this, but I can probably get someone from the MDN dev team to help.
> 
> It's a new account, I have multiple emails associated to my Github profile for commit purposes - one or two of which are not valid addresses. - I clicked on the invalid one because I thought the email would be public / not used for verification purposes - and wanted to avoid spam.
> 
> It seems like there's no option to change the verification email to the correct one ([nickjoh@protonmail.ch](mailto:nickjoh@protonmail.ch))
> 
> My profile name is `njohnst`.

Thanks. I'll talk to the devs about this one.

**Comment by schalkneethling** [comment]
> 1. my github verification email is not coming (because it is being sent to the wrong address, so I'm unable to fix the docs myself)
> 
> [-nic...@....ch] (Correct) / [nic...@....com] (Wrong)

Hey there @njohnst - Can you log into MDN at all?

If you can, you can take the following steps:

1. Log in an then click on edit profile

![Screenshot 2019-09-26 at 15 19 43](https://user-images.githubusercontent.com/10350960/65691447-22209e00-e071-11e9-8788-912209eeb743.png)

2. On the next view, click on `Edit email`

![Screenshot 2019-09-26 at 15 20 29](https://user-images.githubusercontent.com/10350960/65691520-454b4d80-e071-11e9-961f-a2fe84e6e818.png)

3. Under "Add an email address", enter your desired email address and click `Add Email`.

![Screenshot 2019-09-26 at 15 21 20](https://user-images.githubusercontent.com/10350960/65691627-73c92880-e071-11e9-8126-1e582979f55c.png)

This will send a verification email to the new email address you just added. You can then follow the link to verify your new email. Once you have done that, go to "Edit Profile > Edit email" again.

You can now set this new email address as your primary email address. Once that is done, go ahead and delete the previous email address:

![Screenshot 2019-09-26 at 15 25 44](https://user-images.githubusercontent.com/10350960/65691941-036ed700-e072-11e9-865a-801a45a7d491.png)

Hope that helps.

**Comment by njohnst** [comment]
![image](https://user-images.githubusercontent.com/1574745/65796100-cd952580-e139-11e9-9f84-3681a8a3b884.png)

Thanks for getting back to me.

In the top right corner here - it still shows the 'Sign in' button, appears that I can't access the account options - I can't find an account/profile link anywhere either.

**Comment by schalkneethling** [comment]
> ![image](https://user-images.githubusercontent.com/1574745/65796100-cd952580-e139-11e9-9f84-3681a8a3b884.png)
> 
> Thanks for getting back to me.
> 
> In the top right corner here - it still shows the 'Sign in' button, appears that I can't access the account options - I can't find an account/profile link anywhere either.

So, when you are redirected back to MDN from Github after clicking `Sign in`, are you not presented with an option to choose from more than one email address?

Also, do you have both the email addresses mentioned configured and active on Github? If not, I would suggest that you also add the Proton Mail email address to Github and then do the `Sign in` process on MDN again.

Let me know how it goes.
