### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API

### ISSUE THREAD

**Issue by svewag** [mdn/sprints#2184]
# Request type
- [ ] Correction or update

# Details
In the `Specifications` section the  `Credential Management API` should have the `experimental` icon as it is currently an experimental technology as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API).

**Comment by chrisdavidmills** [comment]
According to our definition of experimental, an API isn't experimental if more than one browser supports it.

I  think Chromium and Gecko both support it,so. therefore we should probably get rid fo the experimental banners instead.

As an aside, we are currently discussing whether to get rid of the experimental banners altogether, as they are ambiguous and not consistently used. People could infer such things from the browser compatdata instead.
