### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

### ISSUE THREAD

**Issue by govind46** [mdn/sprints#2185]
There is no problem with the content here. But I want to suggest a that it would be helpful if you provide the bookmark button with everypage, so that if the reader finds it important/ for future reference. He will have easy access to it, without going through plethora of webpages.
I just created github account, expecting that bookmark tool will appear.

I couldn't find the page where i could suggest this in this mozilla network. so I am writing to this, Please forward to the concern department/ person

**Comment by chrisdavidmills** [comment]
I don't really understand this. Every browser has a bookmark function?

**Comment by govind46** [comment]
Required Bookmark for every topic.

Example: we can mark star to the question we like in stackoverflow, so we can by logging in the account, can easily go to the starred question. 

Same functionality I was asking, to be  implement for the mozilla documentation for each topic. 

⁣Sent from BlueMail ​

**Comment by chrisdavidmills** [comment]
@govind46 OK, I understand what you mean now. This is a nice feature request, but more of a platform thing than a content issue. 

@schalkneethling , where would be best to refile this feature request?

**Comment by schalkneethling** [comment]
> @govind46 OK, I understand what you mean now. This is a nice feature request, but more of a platform thing than a content issue.
> 
> @schalkneethling , where would be best to refile this feature request?

Over here https://github.com/mozilla/kuma/issues/new/choose using the feature request issue template. Thanks!
