### ISSUE TITLE
Missing Documentation for Upgrade

### ISSUE THREAD

**Issue by mohamedanees6** [mdn/sprints#2186]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details
Documentation of Upgrade is missing

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade

**Comment by Elchi3** [comment]
Duplicate of https://github.com/mdn/sprints/issues/1283
