### ISSUE TITLE
Accesskey on search box missing

### ISSUE THREAD

**Issue by whyalwayscreateaccounts** [mdn/sprints#2188]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

See subject. The search box should be accessible via keyboard.
I would suggest to use accesskey="f"

Have a nice day

**Comment by chrisdavidmills** [comment]
@schalkneethling worth moving over to your sprint tracker?

**Comment by schalkneethling** [comment]
> @schalkneethling worth moving over to your sprint tracker?

Yeah, this makes sense to me.

**Comment by schalkneethling** [comment]
Issue filed here: https://github.com/mozilla/kuma/issues/5917
