### ISSUE TITLE
по линке пустой контент

### ISSUE THREAD

**Issue by dnshark** [mdn/sprints#2193]
если зайти на https://developer.mozilla.org/ru/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript

и там клацнуть по любой линке из раздела Терминология. Например "Метод". То будет редирект на несуществующую страницу.

# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

**Comment by chrisdavidmills** [comment]
Russian versions of the glossary pages don't exist, hence these links being red.
