### ISSUE TITLE
Link to GitHub learning material 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2194]
# User story
As a web developer, I want to learn about GitHub, so I can effectively use version control in my web projects.

# Acceptance criteria

1. - [x] Choose articles to link to
2. - [x] Chooose how to link to them (e.g. separate article? What format?)
3. - [x] Link to them from Learning Pathway

**Comment by chrisdavidmills** [comment]
Git and GitHub article created, at https://developer.mozilla.org/en-US/docs/Learn/GitHub.

Link added, to https://wiki.developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer#Modern_tooling

**Comment by chrisdavidmills** [comment]
@escattone Hey man, can you give me some thoughts on this?

**Comment by escattone** [comment]
@chrisdavidmills I thought it was really well done! Maybe one small thing I would suggest modifying, within the overview here:

> Different team members will commonly want to create their own separate versions of the code (called branches in Git), work on a new feature in that version, and **then get it merged with the master version when they are done with it.**

to something like:

> ...**then get it merged in a controlled manner (in GitHub these would be "pull requests") with the master version when they are done with it.**

It just felt important to talk about how these tools are so important to share work in a controlled manner, or something to that effect.

**Comment by chrisdavidmills** [comment]
@escattone great, thanks mate — that's a really good suggestion. I've used your words nearly verbatim. That means I now owe you royalries on the vast profits we're gonna make with this one.
