### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/repeat#Formal_syntax

### ISSUE THREAD

**Issue by GargantulaKon** [mdn/sprints#2195]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The Formal Syntax is missing on this page. I see an error that states, "Syntax not found in DB!"

**Comment by jmswisher** [comment]
Formal Syntax section was removed from the article.
