### ISSUE TITLE
Example's video has possibly offensive language

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2197]
The third example in this learning area page:

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

not only includes the phrase "OMG hell yeah" but that phrase is on the poster frame for the video, and is in the screen shot shown on the article page. We should find a different video to use here, because this is potentially offensive to various people, and not appropriate for any kids that might be using MDN to learn.

**Comment by chrisdavidmills** [comment]
I've fixed this one; the post now says "Lovely rabbit video"
