### ISSUE TITLE
HTML autocomplete attribute - MDN web documents

### ISSUE THREAD

**Issue by guyhickling** [mdn/sprints#2198]
[This repeats an issue entered a few minutes ago, which someone closed before I had finished editing it.]

Please can you correct the page on the HTML autocomplete attribute athttps://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete. In the "Administrative levels in addresses" section, the United Kingdom information is wrong.

The highest administrative level in a UK address is the county, and this is still regularly used in addresses by many people, perhaps the majority still. Either from choice, or sometimes where a "post town" may have similarly named towns. For instance there are two Newcastles (On Tyne and Under Lyme).

More to the point, web and software designers will almost always include the "County" address field on an input form, (or else allow enough ordinary address lines for it to be entered) though normally as an optional field, because they know too many people expect the County field to be there and some users will be disconcerted if it is not present for them to complete. (I am testing one such input form right know, which is how I come to be writing this issue report.)

The county is optional, it does not have to be included - but then the entire address is optional - the UK Post Office can work entirely from a street number and the postcode (and in fact they originally intended people to just use that when postcodes were introduced last century, though they never implemented that idea in the end).

Most people (including developers) still would expect the county to be considered as the highest level in the address even if they don't bother to include it themselves in addresses they write. So the County should be address-level1, the Town should be address-level2, and we don't include a field for the level 3 locality - most people would put that in the address lines (usually address-line2, following the street, or miss out the locality completely. Many people, if there are not enough address lines on a form for a their address, will include the county and omit the low level locality within their town.

**Comment by chrisdavidmills** [comment]
Apologies @guyhickling; that was me who closed the original. Bit of an itchy trigger finger there, but we get load of submissions that have no information in them, and it looked like one of those ;-)

I've had a go at updating the section; let me know if you think this is OK. I consider this to be the ideal for UK addresses.

**Comment by guyhickling** [comment]
@chrisdavidmills Yes, your changes for the county and town levels to use address-level1 and address-level2 are exactly right, so thank you for doing that. The house number and street name however, and any local area within a town, should be in the address lines, as they aren't an administrative level, so a small amendment is still needed. 

I've copied a screen shot of a form from a government website, below, which is very typical of many common address forms. Only the town and county need the administrative level values, the other three fields are address lines.

So please could you make some further small amendments to the UK section of the page, as follows:

1) In the first paragraph change "The UK typically uses two or three address levels, ...." to "Address input forms in the UK typically contain two address levels, and one, two or three address lines.....".

2) In the 3rd bullet in the bullet list change "address-level3" to "address-line1"

3) In the paragraph below that, in the sentence starting "Note that you can.....", again amend "address-level3" to "address-line1"

![address form 2](https://user-images.githubusercontent.com/30391059/66245655-3adf2280-e707-11e9-8260-4ad85fe7a9b1.jpg)

**Comment by chrisdavidmills** [comment]
OK, changes make. Thanks for helping me work through the particulars of this.
