### ISSUE TITLE
Talk about entities on HTTP methods page

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2203]
(cross-posted from https://github.com/mozilla/kuma/issues/5912)

As mentioned a few times on https://restfulapi.net/http-methods/, our https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods documentation should probably mention the entities created by various types of HTTP method.

**Comment by hamishwillee** [comment]
@chrisdavidmills (+ original poster @tamtm)

The [HTTP/1.0](https://tools.ietf.org/html/rfc1945#section-7) spec and early versions of [HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7) mention entities and entity headers, which essentially mean "payload" and payload metadata (content-encoding, etc.). 

However the [current spec of HTTP/1.1](https://tools.ietf.org/html/rfc7231#section-3) no longer uses the "entity" terminology. Instead it refers to representations for most of the "formerly-entity" fields. This still means "content of the payload", but there is very much more clarity around the idea that a resource can have multiple representations (e.g. types of encoding etc) and also some kind of temporal variation.

We talk about the returned representation in topics like [Content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation). I'm not sure it makes any sense to talk about them at the level of [HTTP request methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) as suggested, or even at individual method level. Certainly not further than we do - i.e. a GET message doesn't send a payload.

I propose that we close this as "Won't fix" as I am not sure it would be helpful - whether we call it entity or representation. Open to the idea of changing my mind if given an example where a developer would find it useful to say more?

----

FYI, I did make updates to these docs to reflect that the categorisations are no longer in use. 
- [Glossary > Entity header](https://developer.mozilla.org/en-US/docs/Glossary/Entity_header) - added a note that this terminology is no longer in the spec.
- [Request headers](https://wiki.developer.mozilla.org/en-US/docs/Glossary/Request_header) - Improved description to make it more clear what these are about and also add link to spec for the "list"
- [Glossary: > HTTP header](https://developer.mozilla.org/en-US/docs/Glossary/HTTP_header) - made it clear that entity header and glossary are no longer in the spec. I don't comment on how useful they are.
- [Glossary > Response header](https://wiki.developer.mozilla.org/en-US/docs/Glossary/Response_header) - tidied up. One thing I wasn't clear on was a statement that in a response context entity headers can be referred to as response headers. That doens't really make sense so I changed it to:
  > However, "conversationally" all headers are usually referred to as responses headers in a response message.

**Comment by hamishwillee** [comment]
@chrisdavidmills Can I close this?

Do we need a "Ready for review" column in https://github.com/mdn/sprints/projects/10 ?

**Comment by chrisdavidmills** [comment]
Yes, I think we can close this. 

A ready for review column might be nice, yes.
