### ISSUE TITLE
Layout causes unreadable text

### ISSUE THREAD

**Issue by Alex-Jongman** [mdn/sprints#2205]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

At https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model#More_flexible_constructors
just below the first image and before the note, a code example is given. The layout of the code however flows over the text, which make that the text can not be seen / read.

I experience this issue with the browser I'm using is Chrome 77 and haven't checkt if the problem remains with other browsers / versions.

**Comment by chrisdavidmills** [comment]
We had some strange floating going on; I've removed the floats to simplify the layout and hopefully fix the problems in Chrome.
