### ISSUE TITLE
Create a simple experimental project to get a feel for the WebXR API

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2206]
In order to get familiar with how the WebXR Device API is actually used, create and experiment with a simple experimental project. It should minimally create an object and present it in 3D space, allowing you to move around it. Something like that, anyway.

## Acceptance criteria
- [ ] Project created and a working test  program created
- [ ] Learned lots about WebXR by doing

**Comment by a2sheppy** [comment]
Got delayed by unscheduled work on WebRTC updates for Firefox 70, which took about three days to complete.

**Comment by jmswisher** [comment]
To be continued
