### ISSUE TITLE
Review and complete the XR interface reference

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2208]
Ensure that this documentation is complete, including the interface page and the pages for any members.

## Acceptance criteria

- [x] All pages are complete and match our structure guidelines
- [x] Each page is thorough and any errors are listed
- [ ] Samples are included where it makes sense to have them
- [x] BCD is up to date and complete
- [x] GroupData is up to date and complete

**Comment by jmswisher** [comment]
Samples work has been moved to a [separate issue](https://github.com/mdn/sprints/issues/2292).
