### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web/JavaScript_basics

### ISSUE THREAD

**Issue by Username-Adrian** [mdn/sprints#2211]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![FireShot Capture 002 - JavaScript basics - Learn web development - MDN - developer.mozilla.org.png](https://i.loli.net/2019/10/04/q7TEmRhduyLbJeO.png)

link_1:
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics#Adding_a_personalized_welcome_message

link_2:
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics#Conclusion

    As shown in the figure: In the first point of the section "Adding a personalized welcome message", the original text: "In index.html, add the following line just before the <script> element" has a problem. If you put <button> before the <script> element, the button will appear above the page instead of below. If you want the button to appear below the page, <button> should be placed at the bottom of the <body> element.

**Comment by chrisdavidmills** [comment]
Hi @Username-Adrian !

The `<script>` element is at the bottom of the body (just above the `</body>` tag), so this instruction is correct — we are asking the reader to put the `<button>` element just above the `<script>` element, which is at the bottom of the body.

**Comment by Username-Adrian** [comment]
> @chrisdavidmills 
> Thank you chrisdavidmills for helping me solve this problem. I mistakenly put <script> in front of 
> body  to cause this problem.
