### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/API/Performance/measure

### ISSUE THREAD

**Issue by XXXMrG** [mdn/sprints#2214]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

this page's code format seems to have some problems.
it all look like `({domxref("Performance.getEntries","getEntries()")}`

**Comment by chrisdavidmills** [comment]
This got broken; I've reverted it to before the breakage.
