### ISSUE TITLE
DOMSettableTokenList Page Does Not Exist

### ISSUE THREAD

**Issue by DiminutiveRex** [mdn/sprints#2216]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

[This page](https://developer.mozilla.org/en-US/docs/Web/API/DOMSettableTokenList) which seems like it is supposed to explain what a DOMSettableTokenList is does not exist (or maybe the link is just broken and there is an explanation somewhere?)

[This page](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList) indicates in a hidden footnote that DOMSettableTokenList is a deprecated child interface:

![image](https://user-images.githubusercontent.com/18077518/66282276-bdddb580-e88c-11e9-89e8-128aebed4baf.png)

It is referred to in the following locations:
- [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement), under the Properties heading, in the explanation of the property HTMLTableCellElement.headers.
- [here](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList#See_also)
- [and in eight other places in the documentation](https://developer.mozilla.org/en-US/search?q=domsettabletokenlist)

Thanks for taking a look!

**Comment by chrisdavidmills** [comment]
This is just a page that hasn't been created yet. We'll do this at some point in the future.
