### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/offsetParent

### ISSUE THREAD

**Issue by NvanYu** [mdn/sprints#2217]
# Request type
Translation Error

# Details
Chinese Edition
![1](https://user-images.githubusercontent.com/49123717/66295577-42c4df80-e91e-11e9-9c1f-2961f2f48309.PNG)

English Edition
![2](https://user-images.githubusercontent.com/49123717/66295598-4e180b00-e91e-11e9-9921-36667707c8d1.PNG)

According to the official English document, if there is no positioned element, offsetParent is the nearest table, table cell or body, but the Chinese version is translated as the root element, the root element is html instead of body, is this translation wrong?

**Comment by chrisdavidmills** [comment]
Yes, the translation is wrong. I jst tested this and rewrote the english version of the page to make it a bit clearer:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent
