### ISSUE TITLE
Houdini: add registerProperty to CSS API page

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2218]
Add the new method to:

https://developer.mozilla.org/en-US/docs/Web/API/CSS

after the bcd and spec have been populated on 

https://developer.mozilla.org/en-US/docs/Web/API/CSS/registerProperty

**Comment by santimirandarp** [comment]
Hello there,
I've filled up the info (spec) but get the a 'permission denied' when publishing. 
Not sure how to proceed... Any ideas? It's the first time I try though.

**Comment by estelle** [comment]
Thank you santimirandarp 
Let me add @chrisdavidmills. He may know why your account isn't working.
Also, the BCD has populated, so I think this ticket can otherwise be closed.

**Comment by chrisdavidmills** [comment]
I've finished off the above linked pages; yup, we can close this now!

@santimirandarp Are you saying that you made a change to an article, but then when you pressed Publish, you got an access denied error? This does happen sometimes...can you try editing another page, and letting me know if the error persists?
