### ISSUE TITLE
[JS] Return of SharedArrayBuffer

### ISSUE THREAD

**Issue by annevk** [mdn/sprints#2219]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
`SharedArrayBuffer` is coming back, but using it with `postMessage()` will be more involved. https://docs.google.com/document/d/1zDlfvfTJ_9e8Jdc8ehuV4zMEu9ySMCiTGMS9y0GU92k/edit has a detailed explanation. In short, use HTTPS and add some HTTP headers.

There are four preferences on Nightly that enable this:

* dom.postMessage.sharedArrayBuffer.withCOOP_COEP
* javascript.options.shared_memory
* browser.tabs.remote.useCrossOriginOpenerPolicy
* browser.tabs.remote.useCrossOriginEmbedderPolicy

This is considered relatively stable at this point and we'll hopefully have this enabled by default on non-Release channels soon. It would be good to document it so we have a reference point that tells the whole story to developers who might need to adjust their code.

cc @arturjanc @mikewest @cdumez

**Comment by Elchi3** [comment]
Need at least a few new HTTP reference pages:
- COOP
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
  - Compat data was added in https://github.com/mdn/browser-compat-data/pull/4220
- COEP
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
  - Not compat data yet
- CORP
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy
  - Compat data: https://github.com/mdn/browser-compat-data/blob/master/http/headers/cross-origin-resource-policy.json

The SharedArrayBuffer reference docs are here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

> It would be good to document it so we have a reference point that tells the whole story to developers who might need to adjust their code.

We then probably want a new MDN guide page that talks about how to use all the bits together. 
(not sure where to hang this under exactly yet, maybe in the HTTP docs, maybe under SAB). 

> This is considered relatively stable at this point and we'll hopefully have this enabled by default on non-Release channels soon.

A hacks blog post could announce this at that point probably.

**Comment by annevk** [comment]
Target for this is 72 (beta), for which code soft-freezes early December. We might ship selective bits before that, in particular making `SharedArrayBuffer` available everywhere, while not allowing it to be used with `postMessage()`.

**Comment by chrisdavidmills** [comment]
Also see https://github.com/mdn/sprints/issues/2940

**Comment by Elchi3** [comment]
Looks like this is happening now, see https://bugzilla.mozilla.org/show_bug.cgi?id=1606624

**Comment by annevk** [comment]
Note that it's very limited still and does not include cross-origin isolation (result of COOP+COEP). In particular:

* `globalThis.SharedArrayBuffer` is undefined.
* `Atomics` is now available (but not that useful without shared memory across threads)
* `WebAssembly.Memory` now supports `shared: true` in its constructor. (This can be used to get an instance of the `SharedArrayBuffer` constructor.)

**Comment by Elchi3** [comment]
> * `Atomics` is now available (but not that useful without shared memory across threads)
> 
> * `WebAssembly.Memory` now supports `shared: true` in its constructor. (This can be used to get an instance of the `SharedArrayBuffer` constructor.)

@annevk, do you think it makes sense to update the docs for these two items for Firefox 78? Or should we wait?

**Comment by annevk** [comment]
Yeah, they have shipped after all and the documentation should reflect that I think. I expect that we'll send an intent for the remainder shortly by the way, hopefully 79.

**Comment by Elchi3** [comment]
> Yeah, they have shipped after all and the documentation should reflect that I think. 

Ok cool, I opened https://github.com/mdn/browser-compat-data/pull/6297 for compat table updates.
Should we announce anything on Fx78 release notes at all? I guess this isn't really shipping, so maybe wait and put it on release notes once we have an intent?

**Comment by annevk** [comment]
The two items you mentioned above are shipping as far as I know. They're not super noteworthy without `postMessage()` support though.

**Comment by Elchi3** [comment]
Thank you! Let's continue this story in the next cycle then.

**Comment by Elchi3** [comment]
There is now an intent to ship https://groups.google.com/g/mozilla.dev.platform/c/-hYWoob95LI

It says "We would like to ship this in Firefox 79 or 80.", so it remains unclear if we should assign this doc work in July for Fx79 or in August for Fx80. @annevk, what do you think?

In Fx79, at least https://bugzilla.mozilla.org/show_bug.cgi?id=1619649 is shipping. So, maybe document that?

**Comment by annevk** [comment]
Thanks for the reminder, we made 79 so 79 it is. (Unless the unexpected happens.)

**Comment by Elchi3** [comment]
Compat data PRs:
- SAB returns in Firefox 79: https://github.com/mdn/browser-compat-data/pull/6356
- COOP+COEP ship in Firefox: 79: https://github.com/mdn/browser-compat-data/pull/6357

**Comment by annevk** [comment]
I suspect that eventually we want to write an article on "cross-origin isolated" (shipping in Fx 79 and now also part of the HTML standard), once that's done, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes could redirect to it.

**Comment by Elchi3** [comment]
HTTP header reference docs are now here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy

**Comment by Elchi3** [comment]
Added a security section to postMessage:
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Security_concerns

And another to SharedArrayBuffer:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Security_requirements

**Comment by arturjanc** [comment]
Thanks for putting these together! I filed https://github.com/mdn/sprints/issues/3492 with a few nits for the COOP documentation.

**Comment by Elchi3** [comment]
I think this is somewhat complete now, but a page explaining cross-origin isolation would be useful. Maybe a glossary entry at least.

Once we have that page, it should be linked to from the various places where we talk about this now:
- https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Security_requirements
- https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Security_concerns
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
- https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/crossOriginIsolated

Anne proposed this earlier, too:

> I suspect that eventually we want to write an article on "cross-origin isolated" (shipping in Fx 79 and now also part of the HTML standard), once that's done, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes could redirect to it.

**Comment by Sjord** [comment]
Some feedback on the COOP page:

> potential attackers can't access to your global object if they were to open it in a popup

"to" should be removed here. Also, it is unclear to me what my "global object" is exactly.

> the opening document will lost a reference to it

"lost" should be "lose". However, since the opening document never gets a reference in the first place, it is not really lost.

> its property will be null

It's not clear to me what property this refers to. 

> This header allows you to have more control over references to a window than ,

Here seems to be something missing. Or is this mistakenly copy-pasted from the previous section?

> unless the opener itself has a COOP of `same-origin`

Doesn't this also include `same-origin-allow-popups`?

> same-origin-allow-popups ... Retains references to popups

This does not explain the "same-origin" part, only the "allow-popups" part. Is popups sufficiently clear? Should this be "newly opened windows or tabs"?

> same-origin ... Shares the same browsing context group with same-origin documents 

The point is that the browsing context is exclusive to same-origin documents, and that cross-origin documents are not loaded in the same browsing context.

> You can only access powerful features like SharedArrayBuffer

I don't think the fact that these features are powerful is what restricts them to COOP. I would rewrite this as "Certain features such as SharedArrayBuffer are only available on ..."

**Comment by Elchi3** [comment]
> Some feedback on the COOP page

Thank you so much @Sjord :+1: 

> Here seems to be something missing. Or is this mistakenly copy-pasted from the previous section?

Oh yeah, no idea what I was doing there. Some copy pasting and no cleaning up. Fixed this now.

> Doesn't this also include `same-origin-allow-popups`?

As far as I understand it you are right. Added.

> I don't think the fact that these features are powerful is what restricts them to COOP. I would rewrite this as "Certain features such as SharedArrayBuffer are only available on ..."

Both chromestatus and somewhere in mozilla bugs/messages I saw them referred to as "powerful features" :smile:, but yeah, I changed this to something more neutral.

I think I addressed your comments, thanks again! 
Let me know if there is more feedback (from you or from anyone cc'ed here!)

**Comment by chrisdavidmills** [comment]
Looks like this is finished for now. @Elchi3 I'd suggest opening a new issue for future work around this stuff.

**Comment by geeknik** [comment]
How does this jive with users that have `privacy.resistFingerprinting` enabled?
