### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn

### ISSUE THREAD

**Issue by kruschk** [mdn/sprints#2220]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Hello,

I'm nearly done working through the "CSS - Styling the Web" topic. Just like the "HTML - Structuring the Web" topic, it's very well done. I've tried to learn CSS a few times before, but it never really stuck; these articles are changing that! The mixture of theory, examples, and exercises make it a great learning resource, and it's very easy to reference later on.

There is a pervasive and very confusing issue with how the articles are linked. From some articles, the navigation menu will look like this:
![First form of navigation bar: "CSS First Steps", "CSS Building Blocks", "Styling Text", "CSS Layout"](https://user-images.githubusercontent.com/21323694/66358204-f25e7980-e93f-11e9-87ea-5707132a993c.png).

From others, it will look like this:
![Second form of navigation bar: "Introduction to CSS", "Styling Text", "Styling Boxes", "CSS Layout"](https://user-images.githubusercontent.com/21323694/66358221-03a78600-e940-11e9-8b2f-4fda00d0964b.png).

It might not look like much, but the articles within are also jumbled, making it very difficult to understand the intended organization (I suspect there was an original version that was changed at some point, and the changes weren't properly propagated throughout). Reading through, I was often afraid I was missing articles!

The files in the [MDN learning-area repository](https://github.com/mdn/learning-area/tree/master/css) match the structure of the second screenshot, so I guess this is the intended structure that should be used throughout.

Thanks for all of your hard work on this wonderful resource!

**Comment by chrisdavidmills** [comment]
Hi there!

I am so glad you are finding our articles useful.

As for this problem, it is actually the first screenshot that shows the correct menu. We updated the first two CSS modules to a new sstructure containing completely new articles recently that teach CSS basics in a proper modern way, and updated the menu as a result.

The problem is that when you make changes like this to MDN, it takes a while for the pages to all regenerate so the changes are live. So you are still seeing the outdated menu on some pages.

On pages where you see the outdated menu, try pressing Ctrl (Cmd on macOS) + Shift + R, and it will do a "force reload" which forces the page to be regnerated, at least it does on Firefox ;-)

If you still find confusing things after doing this, obviously let me know and I'll work on fixing them.

**Comment by kruschk** [comment]
Well I'll be, that's fixed it! Thanks, I never even considered that it might be a problem on my end!

In the CSS building blocks section, may I suggest that links to the assessments ("[Fundamental CSS comprehension](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Fundamental_CSS_comprehension)", "[Creating fancy letterheaded paper](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper)", "[A cool looking box](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box)") also be placed in the navigation menu? They're currently only listed under the "[CSS building blocks overview](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks)" article. As a learner, I would hate to miss them by mistake because they force me to work with the material I've just learned, and really help me grasp it. I also think the "[Advanced Styling Effects](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Advanced_styling_effects)" article should be placed earlier in the module instead of in the "See also" section, because "[A cool looking box](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box)" requires knowledge from this article in order to complete it. Here's what the navigation menu currently looks like:
![image](https://user-images.githubusercontent.com/21323694/66442222-e807b280-ea07-11e9-9085-980f1f34086a.png)

There are some other modules where miscellaneous "See also" articles that are listed in the module introduction aren't listed in the navigation menu, such as "[CSS layout overview](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout)". I think it would be a bit easier if everything was included in the navigation menu, but that may just be personal preference.

Thanks for reading my ravings! 😄

**Comment by chrisdavidmills** [comment]
Thanks for the further input.

So, the reason we haven't put the assessments in the sidebar yet is that we were thinking of maybe changing them to something different, depending on the research I am currently doing. But soon, probably...

When I next update the menu, I'll consider adding these other missing things to it.
