### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

### ISSUE THREAD

**Issue by TonyBenedetti** [mdn/sprints#2221]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

The Syntax and Description sections don't agree about the number of export types.  _Syntax_ says there are **three** and _Description_ says there are **two**.  BTW, Syntax's third bullet uses the word "Hybrid" ... but that is the only time it appears on the page.

**Comment by chrisdavidmills** [comment]
I've fixed this by upating the syntax section to only mention the two. I can't find a reference to hybrid exports anywhere else...
