### ISSUE TITLE
a question about Margin collapsing

### ISSUE THREAD

**Issue by gm-automata** [mdn/sprints#2222]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/53073454/66464332-5b193380-eab1-11e9-9a58-04fa01cb86db.png)
If margin-top is less than 0, the actual margin between the boxes is the total of the two margins.
In that case,the description is not correct.

**Comment by chrisdavidmills** [comment]
Good point. What page did you find this issue on?

**Comment by gm-automata** [comment]
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
"Margin collapsing"

@chrisdavidmills

**Comment by chrisdavidmills** [comment]
@gm-automata Great, thanks! I've fixed the description.
