### ISSUE TITLE
Document is not display properly.

### ISSUE THREAD

**Issue by ve3** [mdn/sprints#2226]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This page ( https://developer.mozilla.org/th/docs/Web/API/XMLHttpRequest ) there is no link to any properties, methods compare to this page ( https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest ).
For example: The heading about **Constructor**, on en-us page it display **XMLHttpRequest() **word and link but on th page it display `{{domxref("XMLHttpRequest.XMLHttpRequest", "XMLHttpRequest()")}}` without link.

**Comment by chrisdavidmills** [comment]
The translation is not finished, so yeah, it is not really usable. We don't have any resources to update this, so it'll have to stay like it is for now.
