### ISSUE TITLE
Bad error in /fr/docs/Web/HTTP/Status/301

### ISSUE THREAD

**Issue by ledahulevogyre** [mdn/sprints#2227]
# Request type

- [x] Correction or update

# Details
The following sentence is in contradiction with the one in English.
fr : "Il est donc recommandé de ne pas utiliser le code 301 pour répondre à une requête GET ou HEAD [...]"
en : "It is therefore recommended to use the 301 code only as a response for GET or HEAD methods [...]"

I suggest : "Il est donc recommandé d'utiliser le code 301 uniquement pour répondre à une requête GET ou HEAD [...]"

**Comment by ledahulevogyre** [comment]
I consider this fix as very high in priority. Because the French-speaking web dev community is not small, and the feature (301 redirection) is very common. Its impact could lead to a global bad practice spreading in that community.

**Comment by SphinxKnight** [comment]
@ledahulevogyre, vous pouvez éditer la page afin de la corriger (MDN est un wiki), ce sera sans doute le plus rapide :)
J'essaierai de revoir la page dès que possible pour corriger.

**Comment by ledahulevogyre** [comment]
@SphinxKnight c'est fait. Merci beaucoup.
Je me suis contenté de traduire l'anglais. Mais je trouve que cette page pourrais être étoffée, pour préciser ce qui est recommandé pour les autres méthodes (PUT, DELETE, PATCH...) par exemple. Mais il faudrait peut-être commencer par le faire dans la page en anglais.

**Comment by SphinxKnight** [comment]
@ledahulevogyre merci beaucoup pour cette correction. Effectivement, pour les corrections qui ne sont pas en anglais, mieux vaut les apporter en amont.
Je pense que cette _issue_ peut être fermée.
