### ISSUE TITLE
Wrong speech Time recognition

### ISSUE THREAD

**Issue by bircastri** [mdn/sprints#2228]
Hi all, I'm new user.

I'm try to use your library to speech text (in italian language). But there are some problem about of the Time recognition. Sometimes it works correctly, and sometimes it doesn't words correctly.

For example if I try to speach "tre meno un quarto " the correct time should be "02:45" but the library write "03:45".
If I try to speach "quattro meno un quarto", the library correctly recognize "03:45".

Is there a way to correct this bug or disable time recognition ?

**Comment by chrisdavidmills** [comment]
I'm not sure what library you are on about.
