### ISSUE TITLE
-moz-focus-inner { } referenced but doesn't exist

### ISSUE THREAD

**Issue by AnnaYuS** [mdn/sprints#2229]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the button page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes . there is a paragraph that includes a link to non-existing page about `-moz-focus-inner { }` 
Also I find the information on overriding the focus styles with `-moz-focus-inner { }` confusing because usually people do it differently.

Can there be some sort of update?

**Comment by estelle** [comment]
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::-moz-focus-inner - it's very rarely displayed, but a resource exists so those who seek it can find it.

**Comment by chrisdavidmills** [comment]
The link now clearly links to that page, so I think we can close this.
