### ISSUE TITLE
/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

### ISSUE THREAD

**Issue by InfiniteLee** [mdn/sprints#2231]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The example codepen and jsfiddle links on the "Using Screen Capture" documentation are incomplete. They are missing the definitions for `startCapture`, `endCapture` and `dumpOptionsInfo`.

**Comment by chrisdavidmills** [comment]
I don'tthink thes
