### ISSUE TITLE
[CSS] Grouping Selectors

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#2233]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I've updates the [CSS selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) page. One of the changes was to a missing "Grouping Selectors" that selects all the elements. This one exists since CSS Level 1 ([reference](https://www.w3.org/TR/CSS1/#grouping)), but it had no page in MDN.

Please create a new page, I will add the content to the page.

Related: #2164

**Comment by chrisdavidmills** [comment]
That makes more sense; thanks!

I've added the page for your to add content to:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Grouping_selectors

**Comment by ramiy** [comment]
@chrisdavidmills 

I've added the content.

Where can I update the sidebar links? to show "CSS Selectors" links.

**Comment by ramiy** [comment]
Also: the browser compatibility data will be displayed when the https://github.com/mdn/browser-compat-data/pull/4995 PR will be merged.

**Comment by ExE-Boss** [comment]
They’re not “grouping selectors” anymore, they’re “selector lists”.

**Comment by chrisdavidmills** [comment]
@ramiy it will be automatically picked up and added to the sidebar when you add the correct group to the data

**Comment by ExE-Boss** [comment]
We still need to do https://github.com/mdn/kumascript/pull/1256.

Otherwise, it will be placed under properties because of: https://github.com/mdn/kumascript/blob/ee1307feacccb57254456bb2cbe9893e37c31ff3/macros/CSSRef.ejs#L134-L136
