### ISSUE TITLE
HTML tree of nodes

### ISSUE THREAD

**Issue by maximkrouk** [mdn/sprints#2239]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

_Couldn't find this anywhere in the internet...(_
_But [this](https://javascript.info/dom-nodes) seems like a demo of what I'd like to see c:_

It would be great to have an ability to see how the html should be structured _(I see it as a large tree)_. The tree should contain every tag and show what can be included into other tags and what should not...

If you don't like trees, or the tree will be too large, it'll be ok to present info like:

#### contained in: 
 - document
#### may contain: 
 - head
 - body
...

----
_I won't be able to do this now, but if there is any html-ninja, it would be cool to see such a page_ 😅

**Comment by chrisdavidmills** [comment]
I don't think this is something we'll have time for any time soon, but it is a nice idea!
