### ISSUE TITLE
Broken example for Math.round()

### ISSUE THREAD

**Issue by dsletten** [mdn/sprints#2240]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

The sample function vanilla_round() in this page is broken: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round
It returns the value y - (y % 1), where y = x + 0.5 for the function parameter x.
However, y - (y % 1) is equivalent to Math.trunc(y). It should instead be Math.floor(y).
The function fails for negative values "past" 0.5 in the negative direction, e.g., -1.8. The actual Math.round() function returns -2 for this value whereas vanilla_round() returns -1. Since Math.trunc is essentially Math.ceil for negative arguments, the value is rounded up rather than to the nearest integer. The correct equivalence is Math.round(x) === Math.floor(x + 0.5) (aside from trivial differences between 0, -0)

**Comment by lukeecart** [comment]
function vanilla_round(x) {
    var y = Math.abs(x) + 0.5; // so that less than 1/2 rounds down; greater rounds up
    return Math.floor(x+0.5)
}
This works as he says, I will change that now to the above

**Comment by chrisdavidmills** [comment]
Sounds good; thanks @lukeecart — I had a play with this one recently, but am happy for you to improve it further.
