### ISSUE TITLE
Missing search result filters 

### ISSUE THREAD

**Issue by SyntaxErrol** [mdn/sprints#2241]
# User story
So, MDN has been my go-to reference since I-can't-even-remember-when. I went to see about the <script> tag attributes and typed in "script" to my search bar and hit the MDN search plugin button, knowing full well the search would yield a ton of results but also that I could just narrow the results down to the HTML reference to get the page I want.

But it seems I can't do that anymore because the big list of filters on the right-hand side of the results page is now missing.

Where did they go? Are they coming back?

**Comment by chrisdavidmills** [comment]
This is one for the MDN dev team.

cc/ @schalkneethling

**Comment by schalkneethling** [comment]
> Where did they go? Are they coming back?

Thank you for getting in touch @SyntaxErrol. This is temporary and they will definitely be making a comeback. Here is the issue where we are tracking this https://github.com/mozilla/kuma/issues/5754
