### ISSUE TITLE
/fr/docs/Accessibilité/ARIA

### ISSUE THREAD

**Issue by EvoWebFrance** [mdn/sprints#2242]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the page https://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA
The link to the page "Use ARIA with HTML" doesn't work : https://specs.webplatform.org/html-aria/webspecs/master/

**Comment by SphinxKnight** [comment]
Bonjour, merci pour ce retour.
Je ne trouve pas le lien sur la page mais je constate que son contenu n'est pas à jour (relativement à la version anglaise). Je la mettrai à jour dès que possible.

**Comment by SphinxKnight** [comment]
J'ai refondu la traduction de cette page afin qu'elle soit à jour (par rapport à la page anglaise).

Si vous rencontrez des fautes, n'hésitez pas à réouvrir cette _issue_ ou à en ouvrir une autre.
N'hésitez pas à éditer MDN si vous le voulez :) (c'est un wiki)
