### ISSUE TITLE
Notification API example doesn't work in Chromium in cross-origin iframe.

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2243]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**transferred from https://github.com/mdn/interactive-examples/issues/1457**

## 🐛 Bug Description

I've given the permission, but the notification doesn't appear. I've found following deprecation message in the console.

> Example?revision=1583240:39 [Deprecation] Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.

CodePen and JSFiddle have the same problem. I suppose linking to the demo and describing why would be an okayish workaround.

## 📃 Steps to reproduce

- visit https://developer.mozilla.org/en-US/docs/Web/API/notification
- click <kbd>Notify me</kbd> button

**Comment by chrisdavidmills** [comment]
I've referenced this from https://trello.com/c/ivi4m7SR/179-notifications-api-fx-72; we'll fix it along with that stream of work.

**Comment by Elchi3** [comment]
I guess this is also related to the Fx70 DDN here? https://github.com/mdn/sprints/issues/2126

**Comment by chrisdavidmills** [comment]
Hrm, that is a good point. Maybe this will be fixed by your work here instead then?

**Comment by Elchi3** [comment]
I guess this is rather hinting that this only shipped in Fx72. I will investigate.

**Comment by Elchi3** [comment]
https://hacks.mozilla.org/2019/11/upcoming-notification-permission-changes-in-firefox-72/ :-)

**Comment by chrisdavidmills** [comment]
I've fixed this by removing the live examples on the affected pages, and simply linking to another example hosted on GitHub.
