### ISSUE TITLE
Strict MIME checking broke the demos style

### ISSUE THREAD

**Issue by NGrossman** [mdn/sprints#2244]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Error loading https://developer.mozilla.org/en-US/docs/Web/CSS/resize et al.:

"Refused to apply style from 'https://mdn.mozillademos.org/static/build/styles/samples.37902ba3b7fe.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

**Comment by chrisdavidmills** [comment]
@schalkneethling looks like strict MIME type checking is stopping the application of global page styles to the live example IFrames. Do we need this reporting somewhere else?

**Comment by chrisdavidmills** [comment]
(Tested in both Chrome and Fx)

**Comment by schalkneethling** [comment]
> @schalkneethling looks like strict MIME type checking is stopping the application of global page styles to the live example IFrames. Do we need this reporting somewhere else?

Good questions :) Perhaps look it over on Kuma and we can take it from there?

**Comment by chrisdavidmills** [comment]
@schalkneethling I've refiled this at https://trello.com/c/jtyroCSH/15-strict-mime-checking-broke-the-demos-style. Can you make this one a priority?

**Comment by schalkneethling** [comment]
> @schalkneethling I've refiled this at https://trello.com/c/jtyroCSH/15-strict-mime-checking-broke-the-demos-style. Can you make this one a priority?

@atopal @tobinmori ?

**Comment by atopal** [comment]
@chrisdavidmills can you provide a bit more context? What's broken on the page because of this? And is this specific to the page you mentioned or have you seen this on other pages too?
