### ISSUE TITLE
/en-US/docs/Web/CSS/flex

### ISSUE THREAD

**Issue by Eric-Dilcher** [mdn/sprints#2246]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
<img width="712" alt="Screenshot 2019-10-16 at 20 49 41" src="https://user-images.githubusercontent.com/14944310/66949277-87572600-f056-11e9-8675-3e771476fd4e.png">

It says under in the section "Values", sub-section "<'flex-basis'>", that flex-basis defaults to 1.  This is not true.

It is (correctly) written in the note below that flex-basis defaults to 0 in certain scenarios.  In my opinion, the contents of the note should be included in the description of the sub-section "<'flex-basis'>", instead of as a note.

**Comment by chrisdavidmills** [comment]
It does default to 1 when omitted — basically, it is saying that if you don't specify a flex-basis value inside your flex shorthand, the value used will default at 1 ... except for a couple of specific circumstances.

You can prove this by setting a value like `flex: 50px;`, and then looking at the longhand equivalents that are set in the DevTools:

![Screen Shot 2019-10-17 at 9 46 27 AM](https://user-images.githubusercontent.com/47647/66993751-0afb2c00-f0c4-11e9-9f9f-95b24f2115ea.png)

I've updated the description to "Defines the flex-basis of the flex item. A preferred size of 0 must have a unit to avoid being interpreted as a flexibility. Defaults to 1 when omitted, unless the initial or none keywords or used."

I also removed the note, as I thought it was really confusing.

Thoughts?
