### ISSUE TITLE
Broken math annotation for math.log in JavaScript Reference

### ISSUE THREAD

**Issue by viratius** [mdn/sprints#2247]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update
- [x] Bug report

# Details
Hi there, not sure if this has been brought to your attention already (if so, I apologize). Not a fan of the new React re-design, but either way, there is a bug with the display of a math calculation (?) at the [`math.log` reference page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log). I'm not sure if it's specific to that page or if it's a site wide issue. To reproduce, just visit the page. See below. Thanks

![Bug](https://user-images.githubusercontent.com/54339514/66962447-ffb1ed00-f03e-11e9-8273-3d757437634b.png)

**Comment by chrisdavidmills** [comment]
@schalkneethling the new front-end seems to be doing funny things to our MathML usage. I'll file this as a content P1/papercut.

**Comment by schalkneethling** [comment]
> @schalkneethling the new front-end seems to be doing funny things to our MathML usage. I'll file this as a content P1/papercut.

We no longer have jQuery on the new frontend and as such, I bet we no longer load this JS file:
`https://github.com/mozilla/kuma/blob/master/kuma/static/js/wiki.js`

That means the following code is never run, and this is why the `MathML` pieces do not display correctly in browsers that does not natively support `MathML`

`https://github.com/mozilla/kuma/blob/master/kuma/static/js/wiki.js#L245`

We will need to rewrite this function sans jQuery and get it into our new frontend bundle.

**Comment by chrisdavidmills** [comment]
OK, makes sense. I've added these details to https://trello.com/c/1nM3Wka7/14-mathml-seems-to-be-broken-in-react-front-end

**Comment by viratius** [comment]
@chrisdavidmills FYI, the website still shows a broken MathML.

**Comment by schalkneethling** [comment]
> @chrisdavidmills FYI, the website still shows a broken MathML.

On my todo list for this sprint :) ~ https://github.com/mdn/kuma/issues/6391
