### ISSUE TITLE
Code being displayed in French

### ISSUE THREAD

**Issue by Madriax** [mdn/sprints#2249]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the French documentation page about [Objects](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Utiliser_les_objets#Utiliser_this), there's a piece of code that is being translated in French and which is incorrect
Category "**Using this**":
![image](https://user-images.githubusercontent.com/23656170/66988573-0eda7e80-f0c3-11e9-84ec-59fd1d669368.png)

**`obj.valeur` should be `obj.value`**

**Comment by chrisdavidmills** [comment]
Fixed! Thanks for reporting.
