### ISSUE TITLE
WebRtc getUserMedia frameRate is not supported

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2250]
Original post at https://github.com/mozilla/kuma/issues/5994

Hello:
 I called Firfox's webrtc api, and MDN showed support, but I made a mistake when I called it.
https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints
https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia
1.webRtc getuserMedia frameRate:

image
2.my code

  navigator.mediaDevices.getUserMedia({
      // audio: this.config.audio,
      video: {
        width: { min: 640, ideal: 1920 },
        height: { min: 400, ideal: 1080 },
        aspectRatio: { ideal: 1.7777777778 },
        frameRate: { max: 15},
      },
    }).then((stream) => {
      this.successCb(stream);
    })

3.error in firefox

image
UA

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0"
other

When I wrote like this, he returned a dynamic bit rate.

    navigator.mediaDevices.getUserMedia({
      // audio: this.config.audio,
      video: {
        width: { min: 640, ideal: 1920 },
        height: { min: 400, ideal: 1080 },
        aspectRatio: { ideal: 1.7777777778 },
        frameRate: 15
      },
    }).then((stream) => {
      this.successCb(stream);
    })

I wonder why this happens？

**Comment by a2sheppy** [comment]
This behavior is exactly as expected. If you specify `frameRate: 15`, you're saying "I would like 15 but will accept whatever you can give me." If you specify `frameRate: {max: 15}`, you're saying "I will not accept a frame rate higher than 15 FPS."

At least on my Mac, my camera will not produce a stream at 15 FPS, so the latter (max: 15) fails with an `OverConstrainedError`.

Give the "constraint exerciser" a try on this page:

https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#Example_Constraint_exerciser

Keep in mind this uses JSON so you need to format the constraint strings in JSON format:

```
{
  "width": 320,
  "height": 240,
  "frameRate": { "max": 15 }
}
```

(For example)

Let me know if I've misunderstood your ticket; if not, then there isn't any documentation update required for this.
