### ISSUE TITLE
[MathML] Firefox 71 changes (low priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2252]
Trello: https://trello.com/c/LMs5lI6w/228-mathml-updates-fx-71

# Acceptance criteria

1. - [x] [Implement MathML DOM](https://bugzilla.mozilla.org/show_bug.cgi?id=1571487)
2. - [x] [Remove support for numalign/denomalign/align attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1548530)
3. - [x] [Remove support for the menclose's "radical" notation](https://bugzilla.mozilla.org/show_bug.cgi?id=1548522)
4. - [x] [Remove support for the subscriptshift and superscriptshift attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1587570)
5. - [x] [Remove support for XLink on MathML elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1575870)
6. - [x] [Remove support for the mfrac@bevelled attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1587572)
7. - [x] [Remove support for the mfenced element](https://bugzilla.mozilla.org/show_bug.cgi?id=1587577)

**Comment by Elchi3** [comment]
All done!
