### ISSUE TITLE
[CSS] box sizing, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2253]
Trello: https://trello.com/c/99AKTpVj/186-css-values-and-units-level-4-box-sizing-level-4-fx-71

1. - [x] [Ship the mapping of img width and height to aspect-ratio.](https://bugzilla.mozilla.org/show_bug.cgi?id=1585637)

Note that I wrote a related guide that needs publishing at some point:https://docs.google.com/document/d/1RAqaONrO7Zka2Q7IL3yyGDskwycBATS46SeE167PDdY/edit

**Comment by rachelandrew** [comment]
@chrisdavidmills do you want me to publish the guide as part of this?

**Comment by rachelandrew** [comment]
Chrome are shipping too https://www.chromestatus.com/feature/5695266130755584

**Comment by chrisdavidmills** [comment]
> do you want me to publish the guide as part of this?

Ah yes, that would be really nice thanks. Jen is very interested in getting it published.

**Comment by rachelandrew** [comment]
@chrisdavidmills where should the guide go do you think? Poking around I realise that the properties which should be under the CSS Box Sizing Spec are listed under "box model" which is suboptimal at this point.

**Comment by chrisdavidmills** [comment]
@rachelandrew that's a good question. We do have a replaced elements page — https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element — which is related, but maybe just put it under the main CSS page for now, until we decide what to do with it?

@a2sheppy I think you also had some ideas about this. What were your thoughts on where it should go?

**Comment by a2sheppy** [comment]
So, I feel like this should go under Web/Media, perhaps at https://developer.mozilla.org/en-US/docs/Web/Media/Aspect_ratio_mapping or something similar. Then it should be added to the "Guides" list in the second column of the page at Web/Media.

That's my opinion, anyway.

**Comment by a2sheppy** [comment]
I suppose we could also consider if it would make sense to add a Web/Media/Images subtree for content specific to images, like the image type documents, the aspect ratio document, and other articles about using images and things like that.

**Comment by chrisdavidmills** [comment]
Maybe later, but I think for now we should concentrate on this page. I'm happy to put it where you suggest; we can always move it later if a good reason pops up. @rachelandrew , this ok?

**Comment by rachelandrew** [comment]
@chrisdavidmills ah, I just built that images page as it seemed to make sense! Was just coming to comment as such. I can remove it again but:

- https://wiki.developer.mozilla.org/en-US/docs/Web/Media/images
- https://wiki.developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping

**Comment by rachelandrew** [comment]
I'm making an `aspect-ratio` property page even though this is currently only being implemented internally for the mapping.

Compat data PR, if there is a better way to indicate this internal-mapping-without-full-implementation let me know!

https://github.com/mdn/browser-compat-data/pull/5114

**Comment by a2sheppy** [comment]
@rachelandrew Once created, might as well just leave it. :)

**Comment by chrisdavidmills** [comment]
Yup, that's fine! Great minds think alike and all that ;-)

**Comment by chrisdavidmills** [comment]
I've given the new pages a small edit, and I think we can call this done now. Thanks!

**Comment by rachelandrew** [comment]
Page here: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

Added to release notes for 71 and flagged the bug.

**Comment by chrisdavidmills** [comment]
Reviewed; LGTM!
