### ISSUE TITLE
[CSS] Shapes, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2254]
Trello: https://trello.com/c/UfIugYRS/102-css-shapes-fx-71

# Acceptance criteria

1. - [ ] [Ship |clip-path:path()|](https://bugzilla.mozilla.org/show_bug.cgi?id=1488530)

**Comment by rachelandrew** [comment]
compat data PR for `clip-path` https://github.com/mdn/browser-compat-data/pull/5024

**Comment by rachelandrew** [comment]
PR to add Shapes Level 2 https://github.com/mdn/kumascript/pull/1272

**Comment by rachelandrew** [comment]
This is complete, added to release notes, bug flagged. Just waiting for the merged PR to show up to make the spec link correct.
