### ISSUE TITLE
[CSS] Motion Path, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2255]
Trello: https://trello.com/c/Ef3V38Yh/212-css-motion-path-fx-71

# Acceptance criteria

1. - [x] [[motion-1] support offset shorthand](https://bugzilla.mozilla.org/show_bug.cgi?id=1567330)
2. - [x] [[motion-1] Implement ray() function for offset-path](https://bugzilla.mozilla.org/show_bug.cgi?id=1480665)

**Comment by rachelandrew** [comment]
PR for the compat data https://github.com/mdn/browser-compat-data/pull/5045

**Comment by rachelandrew** [comment]
Working on this has highlighted we are missing an overview page for Motion Path, and docs for `offset-position`. I've raised issues for those, and can always go back and add them if I get these other things done.

**Comment by chrisdavidmills** [comment]
We do have a landing page for [Motion Path](https://developer.mozilla.org/en-US/docs/Web/CSS/Motion_Path), but we do need a `offset-position` page.

Cheers Rachel!

**Comment by rachelandrew** [comment]
ah the issue is that the link in the sidebar is wrong - see https://developer.mozilla.org/en-US/docs/Web/CSS/offset
