### ISSUE TITLE
[CSS] Scroll anchoring, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2258]
# Trello

https://trello.com/c/Utcvz7Kv/90-scroll-anchoring-fx-71

# Acceptance criteria

1. - [ ] [Add a pref to disable scroll anchoring suppression triggers on Nightly.](https://bugzilla.mozilla.org/show_bug.cgi?id=1584285) (we really ought to at least cover this in experimental features)

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm not sure what best to do here, add a note to the docs under Supression triggers detailing the flag?

**Comment by chrisdavidmills** [comment]
Sounds good. Also add an entry in the Experimental features page?

**Comment by rachelandrew** [comment]
ok, done and done.
