### ISSUE TITLE
[CSS] Multi-col, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2260]
# Trello

https://trello.com/c/X0vhUJhk/2-css-multi-col-fx-71

# Acceptance criteria

1. - [x] [Enable pref for column-span (layout.css.column-span.enabled) by default for Nightly only.](https://bugzilla.mozilla.org/show_bug.cgi?id=1423383)
2. - [x] [Enable pref for column-span (layout.css.column-span.enabled) by default on release.](https://bugzilla.mozilla.org/show_bug.cgi?id=1426010) (just needs setting to DDC when done)
3. - [x] Check what needs updating for the `column-fill` property to support this
4. - [x] Maybe write a hacks post about the latest on multi-col?

**Comment by rachelandrew** [comment]
I think that `column-fill` will also need updating as the spec has changed around this recently mostly due to questions during the `column-span` implementation for Firefox https://developer.mozilla.org/en-US/docs/Web/CSS/column-fill

**Comment by rachelandrew** [comment]
Note added to release notes, marked bug. I'll do the hacks post once I've done the other Firefox 71 issues.

**Comment by rachelandrew** [comment]
Updated the column-fill page with details of the current state of interop, this is my spec so once that gets resolved I'll know about it so I can update it.

**Comment by rachelandrew** [comment]
@chrisdavidmills shared a lnk with you and Havi for a gdoc on column-span for the Hacks Blog.

**Comment by rachelandrew** [comment]
@chrisdavidmills I heard back form Havi on this, so once you've had chance to have a look I will get it into wp so she can publish it when she thinks it is a good time.

**Comment by chrisdavidmills** [comment]
@rachelandrew read and edited (only a few small changes needed). I really like how you've handled this — the tech explanation is short, succinct and useful, and the extra info about the spec working process is really interesting and gives a nice insight into why sometimes things happen as they do. Very happy for you to move this forward into hacks.

**Comment by rachelandrew** [comment]
@chrisdavidmills this is now on Hacks
