### ISSUE TITLE
[JS] Promises, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2262]
# Trello

https://trello.com/c/0SiTrQJ2/201-promise-related-bugs-fx-71

# Acceptance criteria

1. - [x] [Ship Promise.allSettled](https://bugzilla.mozilla.org/show_bug.cgi?id=1549176) (page is all written, BCD is done, could do with an "Examples" section)

**Comment by Elchi3** [comment]
This is dev-doc-complete
