### ISSUE TITLE
[JS] Arrays, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2263]
# Trello

https://trello.com/c/yGbpmda3/216-js-arrays-fx-71

# Acceptance criteria

1. - [x] [Disable Array generics in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1558914) (just needs setting to DDC?)
2. - [x] [Remove Array generics](https://bugzilla.mozilla.org/show_bug.cgi?id=1222547)

**Comment by Elchi3** [comment]
Done! this was just the removal of array generics.
