### ISSUE TITLE
[Media] Media Session API, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2267]
# Trello

https://trello.com/c/dcuwxwSu/232-media-session-api-fx-71

# Acceptance criteria

1. - [x] [Implement basic MediaSession API](https://bugzilla.mozilla.org/show_bug.cgi?id=1580602) (docs already written, need checking over, BCD needs updating, this is behind a pref at present)

**Comment by kngako** [comment]
Hello, the [docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) say the Media Session API was added in Firefox 71. But when I when I run it on my browser (72.0.1 (64-bit)) I can't access the mediaSession from navigator as documented:
```
>> 'mediaSession' in navigator
<- false
```

Could the problem be that I'm running Ubuntu 18.0.4?

**Comment by kngako** [comment]
Looks like the code for this feature got reverted?

https://hg.mozilla.org/integration/autoland/rev/4be89f6d00fa

**Comment by chrisdavidmills** [comment]
@a2sheppy can you have a look into this? thanks!

**Comment by kngako** [comment]
Hello, is this gonna get reopened?
