### ISSUE TITLE
[WebAPI] Web Share, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2271]
# Trello

https://trello.com/c/1oaEikAt/218-web-share-api-fx-71

# Acceptance criteria

1. - [x] [DOM implementation of Web Share API](https://bugzilla.mozilla.org/show_bug.cgi?id=1312422) (very small API, `Navigator.share()` already documented, won't be available in Fx until Fenix comes out, maybe nothing to do now?)

**Comment by chrisdavidmills** [comment]
Actions for Web Share, for now:

* Tidied up https://wiki.developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* Tidied up https://wiki.developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare
* Created an example, and added it to GitHub and to the first page above:https://mdn.github.io/dom-examples/web-share/
* Did some testing and confirmed the current browser support status and being pretty much right.
* Corrected the spec URLs recorded in MDN: https://github.com/mdn/kumascript/pull/1282

That's it for now; will update the BCD when  https://bugzilla.mozilla.org/show_bug.cgi?id=1402369 lands.

**Comment by marcoscaceres** [comment]
The docs are great. Just a heads up the `canShare()` might change (it's marked as "experimental" on MDN already, so no big deal).

**Comment by chrisdavidmills** [comment]
@marcoscaceres cool, thanks mate! Yeah, we'll update that if needed.
