### ISSUE TITLE
[WebAPI] WebGL, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2272]
# Trello

https://trello.com/c/mhsKKnNY/170-webgl-api-fx-71

# Acceptance criteria

1. - [x] [Expose WebGL OVR_multiview2 (remove draft-ext gate)](https://bugzilla.mozilla.org/show_bug.cgi?id=1583878) (will fix the bug 3 too)
2. - [x] [Expose WebGL OES_fbo_render_mipmap](https://bugzilla.mozilla.org/show_bug.cgi?id=1584277)
3. - [x] [Implement webgl2 draft ext OVR_multiview2](https://bugzilla.mozilla.org/show_bug.cgi?id=1536672) (happened in 68, can probably set this to DDC now)

**Comment by Elchi3** [comment]
OES_fbo_render_mipmap is done and dev-doc-complete, see https://bugzilla.mozilla.org/show_bug.cgi?id=1584277#c4

OVR_multiview is in review:
Docs: https://bugzilla.mozilla.org/show_bug.cgi?id=1583878#c6
BCD: https://github.com/mdn/browser-compat-data/pull/5216

**Comment by Elchi3** [comment]
Reviewed by Fernando now, see https://bugzilla.mozilla.org/show_bug.cgi?id=1583878#c7

@chrisdavidmills if you give Fernando access to the hacks blog post draft, he will review the WebGL section there, too.

I think we're done here otherwise. Closing
