### ISSUE TITLE
[HTTP] CSP, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2274]
# Trello

https://trello.com/c/cp2ES11r/120-csp-general-enhancements-fx-71

# Acceptance criteria

1. - [ ] [Implement CSP 'navigate-to' directive](https://bugzilla.mozilla.org/show_bug.cgi?id=1529068)

**Comment by Elchi3** [comment]
I think this is not shipping. Asked to verify: https://bugzilla.mozilla.org/show_bug.cgi?id=1529068#c18

**Comment by chrisdavidmills** [comment]
Yup, this is preffed off for now, so closing this. Will revisit when it is being enabled by default.
