### ISSUE TITLE
[DevTools] Primary tool updates

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2276]
# Trello

https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-js-debugger-fx-71

# Acceptance criteria

1. - [x] [[meta] Console Editor M1](https://bugzilla.mozilla.org/show_bug.cgi?id=1519128) (recording in 71 for now, might be 70)
2. - [x] [Log on Events (aka monitorEvents/Event Tracing)](https://bugzilla.mozilla.org/show_bug.cgi?id=1110276)
3. - [x] [Show a color swatch next to CSS variable definitions that have color values](https://bugzilla.mozilla.org/show_bug.cgi?id=1456167)
5.  - [x] [:visited styles not shown in Properties or Rule view](https://bugzilla.mozilla.org/show_bug.cgi?id=713106)
6. - [x] [Debugger paused overlay is too obtrusive and can't be disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1579768)
7. - [x] [Enable Inline Preview for all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1576679)

**Comment by digitarald** [comment]
@chrisdavidmills just for context, these are undocumented features linked from the _What's New_ panel that we should document and prominently feature on the docs (for discovery, as we didn't link to sections):

**Block URLs in the Network monitor**: https://developer.mozilla.org/docs/Tools/Network_Monitor/request_list#Block_a_specific_URL
We have a whole sidebar for this now, not just right-click "Block URL". [PRD](https://docs.google.com/document/d/1TSwKVb5ioF0I_i3OWLSML53ZEEod9CzHOsSSVeDxdN0/edit?ts=5d792112#heading=h.juuk2wdvc8bv)

**New multi-line editor mode in Console**: https://developer.mozilla.org/docs/Tools/Web_Console/The_command_line_interpreter
[PRD](https://docs.google.com/document/d/18E5QvlKd6vxupq-hVFMtDaNS43zSREWyiZjQ1qjdeFw/edit#heading=h.y5oza67gq2l3)

**Search across all Network Headers and Content**: https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Search_Requests
Added a stub section here that could need screenshots.

**Log on Events** and **Quick search in Event Listeners Breakpoints**: https://developer.mozilla.org/docs/Tools/Debugger/Set_event_listener_breakpoints
Document new _Log_ checkbox and filter input.

**New in 70: Color contrast information in the color picker**: https://developer.mozilla.org/docs/Tools/Page_Inspector/How_to/Inspect_and_select_colors
Maybe move "_Starting in Firefox 70 …_" section up as this is GA now?

Secondary features that currently link to hacks as they are missing documentation:

**New WebSocket Messages Inspector**: https://hacks.mozilla.org/2019/10/firefoxs-new-websocket-inspector/

**New in 70: Inactive CSS rules indicator in rules panel**: https://hacks.mozilla.org/2019/10/firefox-70-a-bountiful-release-for-all/#developertools

**Comment by jmswisher** [comment]
**Block URLs in the Network monitor**: Updated the [request list](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list) page with a new section and screenshot.

**Comment by chrisdavidmills** [comment]
Note: Firefox 71 post is written at https://docs.google.com/document/d/1vkxMrCaZMBZhF3SIZLs7BDD7mpU1DTDzNgpYxPxkox8/edit#, and might be helpful for writing some of the above items.

This covers: 

* Web socket inspector
* Network full-text search
* console multi-line editor mode
* Inline preview for variables in debugger
* Event Listeners Breakpoint logging and filtering

**Comment by jmswisher** [comment]
**New multi-line editor mode in Console**: updated [The command line interpreter](https://wiki.developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter) with a new section on the multi-line mode, and updated as needed throughout. ("Command line interpreter" is now kind of a misnomer; I've changed it in most places except the article title.)

**Comment by chrisdavidmills** [comment]
Nice work @jmswisher ! I've given it a light copy edit, and made a couple of minor corrections; looks fine.

> "Command line interpreter" is now kind of a misnomer; I've changed it in most places except the article title.

I'd be happy to have you change it to something more relevant; redirects will handle any references we miss.

**Comment by jmswisher** [comment]
**Search across all Network Headers and Content**: https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Search_Requests -- Filled in the stub section with screentshots and description. (Also condensed some other sections of this article into tables.)

**Comment by digitarald** [comment]
@jmswisher the hash seems to have changed to `#Search_in_requests`, so the URL changed. I manually added `Search_Requests` as anchor to the search section.

**Comment by jmswisher** [comment]
> **New in 70: Color contrast information in the color picker:** https://developer.mozilla.org/docs/Tools/Page_Inspector/How_to/Inspect_and_select_colors
> Maybe move "Starting in Firefox 70 …" section up as this is GA now?

I removed the old screenshot, and the "Starting in Firefox 70" phrase, but I did not move the section. The flow of the article is:

1. See a color sample.
2. Click the sample to get the color picker.
3. Notice the contrast info in the color picker.

It doesn't make sense to move #3 any earlier.

**Comment by digitarald** [comment]
> It doesn't make sense to move #3 any earlier.

@jmswisher SGTM, the article is short enough to discover the contrast in the early screenshots.

**Comment by chrisdavidmills** [comment]
I've documented inline preview for variables:

* Updated this significantly: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint
* Added a specific section for inline variables: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint#Inline_variable_preview

I've also added a small section to each of these that links through to the above section:

* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_an_XHR_breakpoint
* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints
* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code
* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Break_on_DOM_mutation

In addition, rel notes and bug updated:

* https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools
* https://bugzilla.mozilla.org/show_bug.cgi?id=1576679

**Comment by chrisdavidmills** [comment]
I've documented logging on events and filter by event type:

* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints#Logging_on_events
* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints#Filter_by_event_type

Also, rel notes and bug updated:

* https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Changes_for_web_developers
* https://bugzilla.mozilla.org/show_bug.cgi?id=1110276

**Comment by jmswisher** [comment]
**Inactive CSS rules indicator in rules panel** -- I added a description of this (but no screenshot) to  https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Rule_display

**Comment by jmswisher** [comment]
**:visited styles not shown in Properties or Rule view** -- This didn't require any doc updates, per se, since it now just works as developers expect it to.  I added :focus-within and :visited to the section on the [pseudo-class toggles](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Viewing_common_pseudo-classes), and changed that section's heading, since there are now 5 of them. I'm also adding them to the [HTML element context menu](https://wiki.developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML#Element_popup_context_menu) and updating that in general to match the current version of the menu.

**Comment by chrisdavidmills** [comment]
@jmswisher just as a reminder, when you've documented these you need to add a description of these additions to the rel notes (https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools), and update the relevant bugs to dev-doc-complete, along with a comment saying what you did.

**Comment by chrisdavidmills** [comment]
I've now documented the web sockets inspector:

https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_web_sockets

I've also added a rel note, and filed a PR to add it to the devtools sidebar:

* https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools
* https://github.com/mdn/kumascript/pull/1290

**Comment by chrisdavidmills** [comment]
I've documented the debugger breakpoints pause overlay, and the fact it can be disabled:

* https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code#Pause_on_breakpoints_overlay
* https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools

**Comment by chrisdavidmills** [comment]
OK, the only thing not done on this card now is "Add UI support for setting watchpoints", and this is because I can't for the life of me find the feature the bug is talking about. I've need info'd to ask for help on https://bugzilla.mozilla.org/show_bug.cgi?id=1574192.

**Comment by chrisdavidmills** [comment]
@jmswisher @digitarald I've had a go at adding all the new features to the 71 rel notes:

https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools

Have a look and let me know if I've missed any.

**Comment by jmswisher** [comment]
I moved the "setting watchpoints" item into #2468, since it won't be on by default until Fx72.

**Comment by chrisdavidmills** [comment]
@jmswisher perfect, thanks!

**Comment by izogfif** [comment]
> I've documented the debugger breakpoints pause overlay, and the fact it can be disabled:
> 
>     * https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code#Pause_on_breakpoints_overlay
> 
>     * https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#Developer_tools

The relevant part about disabling:
> If you want to turn this feature off, since Firefox 71 you can do so by going to about:config in a new tab, setting the devtools.debugger.features.overlay pref to false, and restarting the browser.

is no longer present in current version (as of 2023-12-18) at https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/step_through_code/index.html#Pause_on_breakpoints_overlay page (that's where the [first link](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code#Pause_on_breakpoints_overlay) redirects nowadays).
