### ISSUE TITLE
[WebExt] proxy/webRequest, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2278]
# Trello

# Acceptance criteria

1. - [x] [Remove "ip" from proxy.json](https://bugzilla.mozilla.org/show_bug.cgi?id=1580274)
2. - [x] [Remove proxy.register/unregister](https://bugzilla.mozilla.org/show_bug.cgi?id=1443259)

**Comment by rebloor** [comment]
Changes made for [Remove "ip" from proxy.json](https://bugzilla.mozilla.org/show_bug.cgi?id=1580274) to [proxy.RequestDetails](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/RequestDetails) and pinged Shane Caraveo for review. Also queried whether `urlClassification`, which is included in the `proxy.json` definition, needs to be added to proxy.RequestDetails?

**Comment by rebloor** [comment]
@chrisdavidmills could I get some advice for [Remove proxy.register/unregister](https://bugzilla.mozilla.org/show_bug.cgi?id=1443259): we have notes in [proxy](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy) and each of the API pages about the removal of proxy.register/unregister and the compatibility data is updated. Given that these APIs will still be "available" at least until the ESR version goes beyond 71, should we be doing any more now?

**Comment by chrisdavidmills** [comment]
@rebloor yeah, this looks sufficiently covered. Does this need any rel notes? If not, then I think we can consider this done.

**Comment by rebloor** [comment]
@chrisdavidmills thanks, it probably does need a release note to be clear about the removal of proxy.register() and proxy.unregister(), and I have added one.
