### ISSUE TITLE
[WebExt] Downloads API, Fx 71 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2279]
# Trello

https://trello.com/c/STmpS11A/111-downloads-api-enhancements-fx-71

# Acceptance criteria

1. - [x] [downloads API compat: Handle HTTP Errors [SERVER_FORBIDDEN, SERVER_UNAUTHORIZED, SERVER_BAD_CONTENT, SERVER_FAILED]](https://bugzilla.mozilla.org/show_bug.cgi?id=1576333)
2. - [x] [downloads API: Allow extensions a way to download ignoring HTTP errors](https://bugzilla.mozilla.org/show_bug.cgi?id=1578955)

**Comment by rebloor** [comment]
Added a link in the return values section of https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download to provide a hyperlink to https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/InterruptReason from the reference to the returned error message’s content.

**Comment by rebloor** [comment]
@chrisdavidmills for [Handle HTTP Errors [SERVER_FORBIDDEN, SERVER_UNAUTHORIZED, SERVER_BAD_CONTENT, SERVER_FAILED]](https://bugzilla.mozilla.org/show_bug.cgi?id=1576333) it would appear that these errors are documented on [downloads.InterruptReason](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/InterruptReason$revision/1099435), and were included when the page was created in 2016.  I have posted a request for clarification on the documentation needed on the bug, but it would appear that none is needed.

**Comment by rebloor** [comment]
@chrisdavidmills for Handle HTTP Errors [SERVER_FORBIDDEN, SERVER_UNAUTHORIZED, SERVER_BAD_CONTENT, SERVER_FAILED] Nils confirm that this was just a bug fix, so a note in the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#API_changes) seems the most appropriate documentation. Pinged Nils by the bug.

**Comment by rebloor** [comment]
For [downloads API: Allow extensions a way to download ignoring HTTP errors](https://bugzilla.mozilla.org/show_bug.cgi?id=1578955):

* compatibility table data, the addition of the`allowHttpErrors` property, see pull request https://github.com/mdn/browser-compat-data/pull/5042.
* [downloads.download()](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) added documentation of the `allowHttpErrors` property.
* [Release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#API_changes) noted the addition of the `allowHttpErrors` property with basic description of features.

The developer has been pinged on the bug for review and feedback.

**Comment by rebloor** [comment]
@chrisdavidmills for Handle HTTP Errors [SERVER_FORBIDDEN, SERVER_UNAUTHORIZED, SERVER_BAD_CONTENT, SERVER_FAILED] Nils Maier is suggesting the inclusion of a note in the compatibility table to identify that these errors were not being reported prior to version 71. His argument being that ESR 68 will be around for some time and developers may run across this issue. My inclination is not to do this. Any comments?

**Comment by rebloor** [comment]
Information about the fix for handling HTTP Errors SERVER_FORBIDDEN, SERVER_UNAUTHORIZED, SERVER_BAD_CONTENT, SERVER_FAILED  is included in the Fx 71 release notes
