### ISSUE TITLE
Prototype new assessments for learning pathways

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2283]
# User story

NB: Find Chris's online assessments research/thoughts here: https://docs.google.com/document/d/1qvvJxDQoqztyxmtWCJUysy7LIeePy5Bg7URUz0mwbpQ/edit#

# Acceptance criteria

1. - [x] Create at least two new assessments, in the style suggested in the research.
2. - [ ] Update an existing assessment, in the style suggested in the research/in comments below.

**Comment by rachelandrew** [comment]
I've written a sample for Flexbox along with a marking guide: https://wiki.developer.mozilla.org/en-US/docs/user:chrisdavidmills/New_CSS_Tasks

Not everything will suit being broken into small tasks like this but I wonder if doing this with the things we can will help to make it easier to support too, as it won't be a giant thing to unpick. Anyway, I'd appreciate thoughts on this approach.

**Comment by rachelandrew** [comment]
@chrisdavidmills I wondered if you had chance to have a look at this and see if it is headed in the right direction before I do another.

**Comment by chrisdavidmills** [comment]
@rachelandrew sorry for the delay!

I think this is looking good so far. A few bits of feedback:

* You are calling it a task - I was thinking "assessment". Do you think this should be something else?
* It seems to me that it is valuable to test the reader's understanding of basic design patterns they'll need to use flexbox, but that we should also test using the patterns together in the context of an actual project. Would this be a separate assessment that would go at the end of the module, in the same kind of way as the layout fundamentals one you've already written? I guess I'm thinking about how granular these assessments should go.
* There are a few obvious recipes I thought were missing from the tasks you've got here — making items different widths using different flex values (maybe you could add this as another step to task 2?) and using order to make sure a certain item is always at the start of the main axis? I think the first one is needed...maybe the second one is used too rarely to bother with?
* I like the way you've pointed people towards using codepen/jsfiddle for sharing examples. I wonder if we need to be more explicit about the success criteria for the assessment - how does the reader know if they have passed it? Do they need to explicitly send us passing versions written in codepen, or should they just self-assess? Should we add a new section to make this explicit? I'd like something like this.
* Making the tasks in the assessment smaller and more granular certainly makes it a lot quicker and easier to assess (both self-assessment and peer assessment)

**Comment by rachelandrew** [comment]
-  I was thinking "task" was less like "Mozilla is marking you", which I thought we wanted to get away from, but it's your call.
- if we do something in the context of an actual project this naturally becomes harder for you to mark (as in your last point) which was kind of my question in the first place, "Not everything will suit being broken into small tasks like this but I wonder if doing this with the things we can will help to make it easier to support too, as it won't be a giant thing to unpick."
- I don't want to encourage people to use order, I strongly suggest we don't include it in a task.
- I don't think they _can_ know they have passed it without someone marking it, which brings us round again to your original issue. Once you have decided how you want to deal with them let me know, I can write the works I just don't know what you want.

**Comment by chrisdavidmills** [comment]
> I was thinking "task" was less like "Mozilla is marking you", which I thought we wanted to get away from, but it's your call.

Yeah, this is a good point. So how about calling them "Tasks" inside the body of the content, but then having something more friendly in the title of the doc, like "Test your skills: Flexbox".

> if we do something in the context of an actual project this naturally becomes harder for you to mark (as in your last point) which was kind of my question in the first place

I appreciate that, but I think we still need at least one assessment that shows using a few things together in context. How about for each module, we have multiple "Test your skills" ones, for each different major tech or group of features, and then one final assessment, like the one you've already got?

> I don't want to encourage people to use order, I strongly suggest we don't include it in a task.

OK, that's fine by me.

> I don't think they can know they have passed it without someone marking it, which brings us round again to your original issue.

Again, good point. OK, let's write that section like this then — when working through the article, try each one in the editable example to test your skill. To get them assessed, add each one to a new Codepen or JSFiddle and ask for an assessment at the MDN Discourse forum. Add the "learning" tag to your post so we are more able to find it.

**Comment by rachelandrew** [comment]
Hi @chrisdavidmills I made some changes to the flexbox one, and then did one for backgrounds and borders.

We already had a small task that I did for backgrounds and borders so I reused that and added a second one. With the second one I then pulled in a couple of properties that are covered in previous lessons. Maybe this is a thing to do, if we assume people follow this as a course? Adding in stuff they already covered to help reinforce it. That would then ultimately build up to being able to do some slightly larger examples in the later lessons once we have the background to do them.

I do think that more granular examples are useful however as they allow people to figure out individual bits without just getting lost in so much stuff (which is likely to lead them either not doing the task or needing help).

With the marking guides I have assumed these might be used by poeple using the material in a course, or by folk helping in Discourse so have tried to explain why various things are covered.

**Comment by chrisdavidmills** [comment]
Thanks @rachelandrew — this looks pretty good to me.

I have made some changes to both skill test pages to get them how I think they should look, and be consistent with each other. These include:

* Making the intro and top note consistent with each other
* Making each individual task have a consistent set of instructions at the top
* Preceding each finished example image with "The finished example should look like the image below."
* Preceding each live example with "Try updating the live code below to recreate the finished example:"
* Preceding any additional questions (as seen in "Flex layout two") with "Additional questions:"
* Starting the notes that contain the starter file download links with "For assessment or further work purposes,"
* Updating the last section to provide more detailed instructions on how to ask for assessment or help.

I think I am pretty happy with the form of these now, and if you agree with the latest updates, I'd be more than happy for you to go forth and create Skill test pages as you feel are required for the other modules (CSS, and others, as much as you feel comfortable with).

The only other question then is how to update the larger existing assessments. I think they will basically just need updating to be in a form more similar to these ones, where the reader is told to submit code in an online form (e.g. codepen) and not just paste their raw code into the discourse forum ;-)

Would you be OK to try updating one of your bigger assessments too?

Don't worry abour replying to all of this here in great detail; we can always discuss it in our 1:1.

**Comment by chrisdavidmills** [comment]
I've added an acceptance criterion about updating an existing assessment, as discussed.

**Comment by chrisdavidmills** [comment]
I think we can close this one now. I've already created some further "Test your skills" pages (and put them in place) and updated some existing assessments, in https://github.com/mdn/sprints/issues/2481.
