### ISSUE TITLE
Document all WebXR events

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2284]
Document all of the events used by WebXR. Some already have pages; these need to be reviewed and updated.

## Event types
- [x] XRSessionEvent
- [x] XRInputSourceEvent
- [x] XRInputSourcesChangeEvent
- [x] XRReferenceSpaceEvent

### XR
- [x] devicechange

### XRSession
- [x] end
- [x] inputsourceschange
- [x] select
- [x] selectstart
- [x] selectend
- [x] squeeze
- [x] squeezestart
- [x] squeezeend
- [x] visibilitychange

### XRSpace
- [x] reset

**Comment by jpmedley** [comment]
@a2sheppy When do you plan to do this. I can send you some boilerplates.

**Comment by a2sheppy** [comment]
@jpmedley Not sure yet. Probably in the sprint after next (though some may happen in context with other work); maybe sooner but can't say for sure.

**Comment by a2sheppy** [comment]
Complete.
