### ISSUE TITLE
Finalize existing learning pathway content: Misc tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2285]
The point of this user story is to go through all the existing content in the [FED learning pathway](https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer) and make sure it is high enough quality for the pathway to be launched.

Note: This is quite large, and probably needs breaking down further.

# Acceptance criteria
1. - [x] Make sure the [Responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) article is in good working order. We have got some reports that the srcset examples weren't working as expected, so it needs investigation.
2. - [x] Review what Estelle has done so far with the [HTML Forms module](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms), and provide feedback. If ready to use, the next step would be to move it out of the HTML topic and into its own topic, in a similar fashion to the [accessibility module](https://developer.mozilla.org/en-US/docs/Learn/Accessibility)
3. - [x] Review the [Styling text module](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text) to see if it could do with some additions, for example should we add information on variable fonts, or is it not really beginner enough?
4. - [x] Review [Third-party APIs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs) to see if all the API examples still work.
5. - [x] Look for links to Thimble, and replace them with links to Glitch?
6. - [x] Looks over https://developer.mozilla.org/en-US/docs/Learn/Performance, decide what needs keeping on there, make suitable for beginners, put anything not suitable hanging off of https://developer.mozilla.org/en-US/docs/Web/Performance

**Comment by jmswisher** [comment]
@chrisdavidmills Can this be split out into stories of smaller than 8 points?

**Comment by chrisdavidmills** [comment]
@jmswisher I've split this into two stories; see here for the other one - https://github.com/mdn/sprints/issues/2375

Does that work better?

**Comment by chrisdavidmills** [comment]
Responsive images `srcset` code simplified/fixed. The code wasn't working on Chrome when set to a narrow viewport width, because it was actually only going down to `495px` in width, when the media query is `max-width: 480px`. Setting a higher `max-width` made it work.

**Comment by chrisdavidmills** [comment]
Styling text module finished:

* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals updated to improve text and examples.
* Mention of variable fonts added to https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts

**Comment by chrisdavidmills** [comment]
Thorough search done; all instances of Thimble removed from MDN.

**Comment by chrisdavidmills** [comment]
Third party API article investigated:

https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

I've made sure all the examples still work, made some minor improvements, and added some instructions on how to get the YouTube example working.
