### ISSUE TITLE
/zh-CN/docs/Web/CSS/var

### ISSUE THREAD

**Issue by zkytech** [mdn/sprints#2288]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The translation of “fallback value” is “回退值” in this document. Which is hard to understand in chinese. Better translation is “后备值” or “备选值” .

**Comment by chrisdavidmills** [comment]
I've tried to fix this. I've replaced the string of characters where they appear as a separate word.
