### ISSUE TITLE
Evaluate BCD signal data

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#2289]
# User story
As the BCD project lead, I want to evaluate BCD signal data, so I know the quality of the compat data and can decide on next steps to further improve compat data quality.

# Acceptance criteria

- [x] A report is created that analyzes a relevant portion of the BCD signals

# Tasks

1. - [x] Get BCD signal data out of the Kuma DB
2. - [x] Analyze data
3. - [x] Draw conclusions

**Comment by Elchi3** [comment]
The sheet lives here: https://docs.google.com/spreadsheets/d/1UqRiXQIg8JLxf-Jo2wCpwpiXQnrkCU8AoEW9fI7BJtg/edit?ts=5dadf1db#gid=0

Data evaluation is ongoing and continues next sprint.

**Comment by Elchi3** [comment]
Some conclusions looking at about 300 signals:

### Signal quality

Overall | abs | percent
-- | -- | --
Total signals | 309 | 100%
Invalid signals | 98 | 31.72%

This means that about 1/3 of feedback submitted is not really meaningful or usable for us. It might be due to the fact that BCD signalling is the only feedback mechanism on MDN pages that every MDN user (without login or anything) is able to see and use at any time (it is shown to 100% of the popularity).


### Which browsers are reported most?

Browser breakdown | abs | percent
-- | -- | --
Firefox / Firefox Android | 100 | 32.36%
Internet Explorer | 94 | 30.42%
Chrome / Chrome Android | 136 | 44.01%
Edge | 78 | 25.24%
Opera / Opera Mobile | 74 | 23.95%
Safari / Safari Mobile | 95 | 30.74%
Android | 99 | 32.04%
Samsung | 57 | 18.45%
Node.js | 9 | 2.91%

Of course, nodejs only appears on ECMAScript features currently, so it less reported. Samsung and Operas are a little less than average, maybe because users do not care enough about these browsers. Due to marketshare, many people obviously care about Chrome/Chrome Android and here we've got the most feedback, but it also hints that we need to get better at Chrome data.

### Which categories are reported most?

Categories (where possible) | abs | percent
-- | -- | --
total | 214 | 69.26%
CSS | 35 | 16.36%
HTML | 15 | 7.01%
JS | 23 | 10.75%
API | 101 | 47.20%
HTTP | 12 | 5.61%
SVG | 5 | 2.34%
WebExtensions | 5 | 2.34%

This of course also needs to be seen with the number of tables we have in each category. We have thousands of tables for APIs and a lot less for e.g. WebExtensions. 

Although, we just made an effort on completing CSS data, we have quite some feedback there. It is mostly about compat data not being up to date or wrong. On the other hand, this also confirms our assumption that CSS compat is by far more relevant to web developers than compat data in other categories. So, I would say more feedback hints to more interest.


### Other observations

- Even though we are asking "What are we missing?", people usually report when things are wrong and not so much when compat data is missing (when the "?" is shown in the tables).
- A few different people had the feedback that things are supported in Edge on Chromium. I would be good to get data for this browser in when it is released.

### Suggestions to improve evaluation

- Add page slug to a column in the sheet
- Regularly export signals, triage, and then file BCD issues?

**Comment by Elchi3** [comment]
@atopal I've posted my evaluation above. Do you have suggestions to further evaluate the data or is this good enough for now?

**Comment by atopal** [comment]
@Elchi3 
Thank you, that's a great summary.
Are there any correlations between usable data and the fields that people have completed? Anything we can make mandatory to increase the signal to noise ratio?

What are your thoughts on APIs? My thinking is that it doesn't matter as much how many pages we have on a technology, but how many people see those pages when it comes to feedback. There seems to be an inverse relationship here between JS and APIs. JS makes up 40% of our traffic, but 11% of feedback, whereas APIs make up 20% of our traffic and 47% of the feedback. CSS on the other hand is a relatively close match between traffic and feedback.

**Comment by atopal** [comment]
Recommendation is to have at least 10 characters in the explanation. Also, aggregation by category

**Comment by Elchi3** [comment]
Presented the evaluation today today Open Innovation as well. There weren't no further needs expressed into what we should analyze.

Regular aggregation by category is useful (in order to see where we should improve) and also by browser (in order to hand feedback on compat data to browser vendors).

> Are there any correlations between usable data and the fields that people have completed? Anything we can make mandatory to increase the signal to noise ratio?
> Recommendation is to have at least 10 characters in the explanation.

Yes. Lets do this and see if the noise goes down. I will file an issue against kuma.

**Comment by Elchi3** [comment]
> What are your thoughts on APIs? My thinking is that it doesn't matter as much how many pages we have on a technology, but how many people see those pages when it comes to feedback. There seems to be an inverse relationship here between JS and APIs. JS makes up 40% of our traffic, but 11% of feedback, whereas APIs make up 20% of our traffic and 47% of the feedback. CSS on the other hand is a relatively close match between traffic and feedback.

Yes, this is interesting and also why I think the category aggregation is good to have going forward. This hints that we should improve API compat data. It would be interesting to have the 1000 most trafficked URLs in web/api/ and then see how much feedback signals we've got on those to prioritize work on API compat data next year. Ideally we have a close match like for CSS or we are better like for JS.

**Comment by Elchi3** [comment]
To me, the AC of this ticket is met. Please re-open if there is more work that should be done here this sprint.
