### ISSUE TITLE
/fr/docs/Web/JavaScript/Guide/Modules TYPO

### ISSUE THREAD

**Issue by michelTho** [mdn/sprints#2290]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

TYPO
In the section "Différences entre les modules et les scripts « classiques »" of the french translation, in the 4th bullet point, at line 2, you wrote "manipulabe" instead of "manipulable".

**Comment by SphinxKnight** [comment]
@michelTho vous pouvez éditer MDN en cliquant sur le bouton "Modifier". La correction de cette coquille devrait prendre quelques instants.

S'il y a besoin d'aide sur la façon de procéder, n'hésitez pas à me demander.

Je repasserai sur cette page dans quelques jours afin de la corriger si ce n'est déjà fait.

**Comment by SphinxKnight** [comment]
fixed w/ https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules$revision/1589892
