### ISSUE TITLE
/fr/docs/Web/JavaScript/Guide/Modules TYPO

### ISSUE THREAD

**Issue by michelTho** [mdn/sprints#2291]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

TYPO
In the "Gestion des conflits de nommage" section, in the "Renommage des imports et des exports" subsection, in the last paragraph, at line 2, you wrote "improt" in the french translation instead of "import"

**Comment by SphinxKnight** [comment]
@michelTho vous pouvez éditer MDN en cliquant sur le bouton "Modifier". La correction de cette coquille devrait prendre quelques instants.

S'il y a besoin d'aide sur la façon de procéder, n'hésitez pas à me demander.

Je repasserai sur cette page dans quelques jours afin de la corriger si ce n'est déjà fait.

**Comment by SphinxKnight** [comment]
fixed w/ https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules$revision/1589892
