### ISSUE TITLE
WebXR: Write (finish) article Spatial tracking in WebXR [MVP]

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2294]
This guide should help the reader learn how everything involving positioning, orientation, tracking, motion, and correlating the positions among objects in virtual space is handled.

Topics include (but may not be limited to):
* Spaces and reference spaces
* Poses and viewer poses
* How poses and spaces work together to establish positions of objects relative to one another
* More

**Comment by a2sheppy** [comment]
While work remains to do on this article, it's mostly down to detail work such as getting final diagrams and adding some code samples, which will come later as other content is fleshed out.

**Comment by Elchi3** [comment]
This was marked as done for the "Golf Hotel" sprint, so I'm closing this.
