### ISSUE TITLE
WebXR: Finish article "Inputs and input sources" [MVP] -> Finished but awaiting final artwork

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2295]
A guide to using input controllers with the WebXR world. In addition to the [specification](https://immersive-web.github.io/webxr/), consider content from the [WebXR input explainer document](https://github.com/immersive-web/webxr/blob/master/input-explainer.md).

# Content needed

- [x] Lead-in (before first heading) (What inputs are used for, why dedicated API, what types of inputs are there, etc)
- [x] [Input sources](#Input_sources)
- [x] [Targeting and tracking](#Targeting)
- [x] [Actions](#Actions)
- [x] [Handling WebXR inputs](#Handling_WebXR_inputs)
- [x] [Using Gamepads](#Using_Gamepads)
- [x] [Applying non-WebXR inputs to WebXR contexts](#Applying_non-WebXR_inputs_to_WebXR_contexts)

## Input sources
* Intro
  * Position
  * Orientation
  * Degrees of freedom
* Input device types
* Input sources
  * Enumeration
  * Detecting input source addition/removal
  * Transient input sources (concepts; usage follows below)

## Facing and targeting
* Directionality (vectors in WebXR)
* Representing facing direction
* Targeting in 3D space
* The targeting ray
  * Target ray space
  * Target ray mode

## Actions
* Intro (what are they, why are they separate from other inputs, etc)
* Concepts and terms
* Primary (select) actions
  * Input device types (button presses, etc)
  * The events and firing order
* Primary squeeze actions
  * What they are and are used for typically
  * Events and event firing order

## Handling WebXR inputs
 * Summary
 * Enumerating input sources (xrSession.inputSources etc)
 * Finding targeted objects (hit testing?)
 * Handling select events
 * Handling squeezes
 * Transient input sources
   * Reasons for inputs to be transient
   * Handling transient inputs

## Using Gamepads
 * The Gamepad API
 * Updating the scene using gamepad inputs

## Applying non-WebXR inputs to WebXR contexts
 * Collecting data
 * Applying inputs to the scene

**Comment by a2sheppy** [comment]
Finished though awaiting some final artwork resources from contributor.

**Comment by Elchi3** [comment]
@a2sheppy, is this now completed?
