### ISSUE TITLE
/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Linux_Prerequisites

### ISSUE THREAD

**Issue by HSorensen** [mdn/sprints#2297]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The `./mach build` failed with an error during compilation stating `libclang.so` was not found on my system.
This is probably something that can be proper detected during the configure checks.

Also to make build work I had to add
`ac_add_options --with-libclang-path="/usr/lib64/"` to the `mozconfig` file.

**Comment by chrisdavidmills** [comment]
This is non-web platform docs, and not something we would prioritise in our docs team. Are you interesting in fixing this?
