### ISSUE TITLE
/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content

### ISSUE THREAD

**Issue by snakada** [mdn/sprints#2298]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It may be necessary to mention the difference in how `overflow: scroll` looks depending on the OS.

There are the following sentences in the article.
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content

> Perhaps you would instead like to add scrollbars when content overflows? If you use overflow: scroll then your browser will always display scrollbars — even if there is not enough content to overflow. You may want this, as it prevents scrollbars appearing and disappearing depending on content.

However, as shown in the capture below, this is true on Windows, but not necessarily on macOS.

In the first place, there is no implementation that scroll bar is always displayed in macOS, and I think that it is displayed only while scrolling.

![overflow-scroll](https://user-images.githubusercontent.com/12525768/67153922-35035700-f32d-11e9-89a3-eac0b52c110f.png)

I wanted to modify the article directly, but I wasn't confident that I fully understood the intention of this sentence, so I first sent a request.

**Comment by chrisdavidmills** [comment]
I've tested this on macOS, and found that with `overflow: scroll;` set, the scrollbars don't remain when there is nothing to scroll, but the scrollbar tracks still remain (this was the case on Firefox and Chrome).

I've therefore ammended the text to 

"If you remove some of the content from the box below, you'll see that the scrollbars still remain even with nothing to scroll (or at least just the scrollbar tracks)."

**Comment by snakada** [comment]
Thank you for quick response:)
I noticed this in the Japanese version, so I will correct it.
