### ISSUE TITLE
Write Jinja helper for SVG titles

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#23]
Some background on the work involved provided by @jwhitlock 

How
---

Keep SVG as SVG, and add the titles at render time. You'd define a helper method like:

```
def include_svg(path, title=None):
    full_path = get_full_path(path)
    svg_raw = open(full_path).read()
    if title:
        parsed = parse_xml(svg_raw)
        title_elem = parsed.find('svg title')
        if not title_elem:
            svg_elem = parsed.find('svg')
            title_elem = svg_elem.add_child('title')
        title_elem.content = title
        svg_raw = parsed.serialize()
    return jinja2.Markup(svg_raw)
```

and then use it like:

```
<li class="footer-social">
    <a href="https://github.com/mdn/">
        {{ include_svg('includes/icons/social/github.svg', _('GitHub')) }}
    </a>
</li>
```

Examples of jinja2 helper methods:

https://github.com/mozilla/kuma/blob/master/kuma/wiki/templatetags/jinja_helpers.py

### Advantages:

Python has a lot more power than Jinja2 macros, so you use SVGO to optimize the SVG as SVG, then modify it how you'd like. The SVG would be viewable as such, and could be used in other ways.

### Disadvantages:

I'm not exactly sure how to implement those placeholder functions:

get_full_path - Django or Jinja2, probably undocumented code
parse_xml - libxml2 or pyquery

I'm also not sure exactly how to find and customize the XML.  I'm pretty sure all this is possible, it would just take some digging to figure out how, plus tests.

# Acceptance Criteria
* SVG titles are translated per locale
* Standard "Done" criteria for development tasks

**Comment by jwhitlock** [comment]
Deployed to production. https://developer.mozilla.org/ar/ is a good example of translated titles, which can be viewed by hovering over the icon.
