### ISSUE TITLE
popstate event description is missing information about when it is fired in page lifecycle

### ISSUE THREAD

**Issue by SetTrend** [mdn/sprints#2301]
The `popstate` event description doesn't give information about *when* this event is getting fired in a page's lifecycle.

See: [/en-US/docs/Web/API/Window/popstate_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event)

# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Using JavaScript modules, it's critical to know when a `popstate` event handler needs to be registered on page load for it to be reliably getting called by the browser.

This is particularly important to know as modules are mainly loaded from the end of a HTML page and their initialization takes place in a cycle occuring after the HTML page has been fully loaded.

Currently, that important information is missing from the documentation.

**Comment by a2sheppy** [comment]
I've added a detailed section covering the process of switching pages in history traversal, so the reader can understand the state of the page when the event is delivered.

https://wiki.developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#When_popstate_is_sent

**Comment by SetTrend** [comment]
@a2sheppy: 👍 

Excellent work!!!

While reading I found a minor typo and corrected it on the fly.

One more question: In the sequence you wrote, the following events don't occur:

- DOMContentLoaded
- readystatechange
- load

Is this by intention?

**Comment by a2sheppy** [comment]
I wrote down what the spec says happens; I suspect this is only covering the events explicitly sent by the state popping; things like DOMContentLoaded and load are going to be fired by the page loading code, which is another area. I'll add a sentence or two explaining the situation.

**Comment by SetTrend** [comment]
@a2sheppy 👍 

Just to be sure, is it safe then to assume that, according to the list's item 6, all above three events have been fired (if they fire at all) before `popstate` event occurs? (i.e. `readystate === "complete"`)

This information is crucial because programmers might add `popstate` event handlers in asynchronously loaded JavaScript files.

So, I tend to believe that the most crucial (and unfortunately still missing) information for JavaScript programmers in regard to this topic is: "Where can I add a `popstate` event handler?"
<hr/>

#### Please find down below 11 different places where to add an `popstate` event handler. Which will be called - and which won't?

```html
<html>

  <head>
    <title></title>
    <script>
     var cnt = 0;
     document.addEventListener(“popstate”, function () {console.log(++cnt);});
    </script>
    <script src=”a.js”></script>
    <script src=”a.js” defer=”defer”></script>
    <script src=”a.js” async=”async”></script>
  </head>

  <body>
    <script>
     document.addEventListener(“popstate”, function () {console.log(++cnt);});

     document.addEventListener(“DOMContentLoaded”, function ()
     {
       document.addEventListener(“popstate”, function () {console.log(++cnt);});
     });

     document.addEventListener(“readystatechange”, function ()
     {
       document.addEventListener(“popstate”, function () {console.log(++cnt);});
     });

     document.addEventListener(“load”, function ()
     {
       document.addEventListener(“popstate”, function () {console.log(++cnt);});
     });
    </script>
    <script src=”a.js”></script>
    <script src=”a.js” defer=”defer”></script>
    <script src=”a.js” async=”async”></script>
  </body>

</html>
```

```js
     document.addEventListener(“popstate”, function () {console.log(++cnt);});
```
<hr/>

If you think you won't be able to answer these safely, please reopen.
