### ISSUE TITLE
Faulty BigInt documentation

### ISSUE THREAD

**Issue by dsletten** [mdn/sprints#2302]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
The page documenting the BigInt type states that BigInt's and Number's may be combined in the same array and sorted as expected: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
However, the code example disregards the default sorting behavior of the array sort() method. The example indicates that the array [4n, 6, -12n, 10, 4, 0, 0n] will sort as [-12n, 0, 0n, 4n, 4, 6, 10]. But the default sort() behavior relies on toString() and actually produces this result [ -12n, 0, 0n, 10, 4n, 4, 6 ].

The sort() function must be provided an appropriate numeric comparator: sort((a, b) => (a < b) ? -1 : ((a > b) ? 1 : 0)

Furthermore, it would be worthwhile for the documentation to emphasize why a simpler comparator would not work: sort((a, b) => a - b)

That would require a homogeneous array since subtraction will not work with mixed types.

**Comment by Elchi3** [comment]
Thanks! I've updated this.
