### ISSUE TITLE
/fr/docs/Apprendre/JavaScript/Client-side_web_APIs/Third_party_APIs TYPO

### ISSUE THREAD

**Issue by michelTho** [mdn/sprints#2303]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

TYPO
In the "C'est quoi une API tierce?" section, in the "Les permissions sont gérées différemment" sub section, in the 6th paragraph (counting the code space as a paragraph), at line 3, you wrote "s'il l'utilise**e** à des fins malveillantes" instead of "s'il l'utilise à des fins malveillantes"

**Comment by SphinxKnight** [comment]
Bonjour @michelTho, je vais revoir / refondre cette page dès que possible. Merci de l'alerte et désolé pour la réponse tardive :)

**Comment by SphinxKnight** [comment]
J'ai refondu la traduction et j'ai passé un coup de Grammalecte. Ça devrait être bon.
