### ISSUE TITLE
单词拼写问题说明

### ISSUE THREAD

**Issue by wenwen234** [mdn/sprints#2304]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/%E5%BC%82%E6%AD%A5/Promises%E8%AF%AD%E6%B3%95
该网页正文部分第五行“objectives：理解并使用学习如何使用Promies“  的promise单词拼写错误

**Comment by chrisdavidmills** [comment]
I don't know what the problem is here, sorry. Can you fix it yourself?
