### ISSUE TITLE
Dead links on 'Asynchronous flow control using async' page

### ISSUE THREAD

**Issue by CharlieDieter** [mdn/sprints#2305]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details

I found a few dead/conflicting links on the [`Asynchronous flow control using async`](`https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/flow_control_using_async.`) page.  The links at the top are correct and direct to the v3 documentation, but the same links under each subheading go to old docs that do not redirect (for example http://caolan.github.io/async/docs.html#parallel instead of http://caolan.github.io/async/v3/docs.html#parallel).

**Comment by leela52452** [comment]
fixed w/[Revision 1588921](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/flow_control_using_async$revision/1588921)
thank you for reporting

**Comment by chrisdavidmills** [comment]
Closing; thanks for fixing @leela52452 !
