### ISSUE TITLE
/en-US/docs/Web/CSS/flex

### ISSUE THREAD

**Issue by aleksaa01** [mdn/sprints#2309]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
A small error in description of how **flex-basis** works.
![msdn_docs_error](https://user-images.githubusercontent.com/33311811/67313626-911fd400-f503-11e9-9832-2cebdbe9f62d.png)
Last sentence says _keywords or used_ instead of _keywords are used_.

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
