### ISSUE TITLE
dead link crash-analysis.mozilla.com

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2311]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

issue wiki URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Crash_reporting

**section** Reports and queries
[404 error URL](https://crash-analysis.mozilla.com/crash_analysis/)

is this website shut down ? if yes, what is the replacement ?

i found that [prior to 2017 are purged](https://groups.google.com/forum/m/#!topic/mozilla.tools.socorro/HUHGTgbS0JU)

**Comment by chrisdavidmills** [comment]
Again, out-of-date, should be archived; not a priority for now.
