### ISSUE TITLE
dead link of file ThreeWayTreeMerger.swift

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2312]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Firefox_Sync

`issue` : **ios** there are some extensive comments here and [here](https://github.com/mozilla-mobile/firefox-ios/blob/master/Sync/Synchronizers/Bookmarks/ThreeWayTreeMerger.swift#L24)

this file was removed with [commit](https://github.com/mozilla-mobile/firefox-ios/commit/d554c9b944d139274cb500424e883de7325bef3c#diff-93e7d2f9730edcbf50e561d4ed5a26c6)

how should i proceed ?

**Comment by chrisdavidmills** [comment]
I'd just remove the link
