### ISSUE TITLE
android Firefox Sync Documentation

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2314]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Firefox_Sync

Documentation -> Android

can you please make google document public OR move to wiki, if it is still relevant

There are also some notes in a [google document](https://docs.google.com/a/mozilla.com/document/d/17njXz0MryGT7_KdXgHGM0VIv3PDtvhV479tatxa6fcM/edit?usp=sharing) (that we really must move to its own Wiki page)

**Comment by chrisdavidmills** [comment]
Feel free to do this if you want to; this is a not a priority for the staff docs team.
