### ISSUE TITLE
Searchfox 404 links of the storage layer and main sync code on Firefox Sync wiki

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2315]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Firefox_Sync

**android sub heading**

broken searchfox links
- [the storage layer](https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/db)
- [main sync code](https://searchfox.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko)

**Comment by chrisdavidmills** [comment]
Closing for now; will archive later.
