### ISSUE TITLE
unmaintained and 404 error of Leak Monitor addon on developer wiki

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2316]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Projects/Leak_Monitor

Leak Monitor addon is unmaintaned since 8 years.
[404 addon page](https://addons.mozilla.org/en-US/firefox/addon/2490) according to [addon creator](http://dbaron.org/mozilla/leak-monitor/)

**Comment by chrisdavidmills** [comment]
Closing for now; will archive later.
