### ISSUE TITLE
Writers' guide to stumptown

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2319]
We should have a document describing what stumptown-content looks like from the point of view of a technical writer. This should explain:

* at a high level, what stumptown-content and stumptown-renderer are, and how they relate
* at a high level, which bits of the stumptown-content repo are of interest to writers
* what kind of files these bits contain
* what recipes are for
* how reference pages are written
* how guide pages are written
* how landing pages are written
* how sidebars are specified
* what all the currently designed ingredients are, and how they are to be written (e.g. `browser_compatibility`, `examples`, etc etc)
* how to run stumptown-renderer to see the rendered version of the documentation pages

It does not need to go into the details of build-json or what the JSON interface looks like.

******

**Acceptance criteria**:

* doc is written and reviewed by stumptown-content team

**Comment by jmswisher** [comment]
Parking until strategy is clearer.

**Comment by wbamberg** [comment]
FWIW this is done: https://github.com/mdn/stumptown-content/pull/197.
