### ISSUE TITLE
404 links on project Mochitest wiki

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2320]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL` https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Mochitest/

`404 links`
- [a set of command line arguments](https://mozbase.readthedocs.io/en/latest/mozlog.html#example-output)
- [test_CrossSiteXHR.html](https://dxr.mozilla.org/mozilla-central/source/content/base/test/test_CrossSiteXHR.html)
- [gen_template.pl](https://dxr.mozilla.org/mozilla-central/source/testing/mochitest/gen_template.pl)
- [Modifying Mochitest SSL behavior](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Mozilla/Projects/Mochitest/Modifying_Mochitest_SSL_behavior)

**Comment by chrisdavidmills** [comment]
Same story as Shumway; I'll leave this for now.
