### ISSUE TITLE
shumway project is closed and archived is not updated in wiki

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2322]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[shumway github](https://github.com/mozilla/shumway) is archived.

it is not updated in [shumway wiki](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Shumway)

**Comment by chrisdavidmills** [comment]
We'll leave this for now; we are going to mass archive a load of outdated stuff soon, but not yet.
