### ISSUE TITLE
404 mozilla blog URLs on pork wiki

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2323]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL` https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Pork

`404 mozilla blog URLs`
- [Taras Glek](http://blog.mozilla.com/tglek)
- [David Mandelin](http://blog.mozilla.com/dmandelin)

**Comment by chrisdavidmills** [comment]
This is really outdated stuff anyway, but yeah, I've deleted the 404s
