### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

### ISSUE THREAD

**Issue by AdirNoyman** [mdn/sprints#2325]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi,
In the exmple of the "Warning for Deep Clone" section, lines 4 - 6, isn't the expected output suppose to be {"a":0,"b":{"c":0}} instead of { a: 0, b: { c: 0}} ?

Thank you in advance
Adir Noyman

**Comment by chrisdavidmills** [comment]
Ah, in terms of the output you get?

I think I've fixed this as wished. Let me know what you think now.

**Comment by AdirNoyman** [comment]
Hi Chris,
Yep. Looks great.

Thank you :)
Adir
