### ISSUE TITLE
Agreement on github based contribution workflow that doesn't require structured content

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2327]
Who is this for? The content team, the dev team and the PM

Why? We want to remove the wiki based contribution workflow as it would remove more than 80% of the code that the dev team needs to maintain today. We'd like to accomplish that without having to convert all documentation to a structured format first, and whatever solution we come up with has to be acceptable to the editorial team.

What? Agreement by the main stakeholders on preliminary plan for 2020

**Comment by bershanskiy** [comment]
Does this entail complete move from using a database as a version control system to git and GitHub with GitHub tooling?

**Comment by atopal** [comment]
@bershanskiy that's what we need to find out, but yeah it's the most likely outcome at this point

**Comment by bershanskiy** [comment]
@atopal Was there any public announcements yet regarding this transition like ETA or milestones?

**Comment by atopal** [comment]
No, we don't have anything we can share at this point, it's in a very early discovery process.
