### ISSUE TITLE
Setup a staging deployment in IT cluster

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#233]
# User story
As an MDN developer, I want a staging deployment in the IT cluster, so I can better estimate the work for feature parity with the MozMEAO cluster

# Acceptance criteria
* A staging deployment (database, files, backing services, etc) is running in the IT cluster
* The manual staging checklist is complete
* Follow-on tasks are documented with the migration team

# Tasks

Tracked in [MDN migration project](https://waffle.io/mozilla-itcloud/mdn-migration-project), [Staging Cluster milestone](https://github.com/mozilla-itcloud/mdn-migration-project/milestone/4).

**Comment by escattone** [comment]
This is done:
- A stage instance is running in the IT-owned cluster: https://developer.mozilla-mdn.nubis.allizom.org/en-US/
- All tests within the manual stage checklist have been successfully completed.
- One follow-on task (https://github.com/mozilla-itcloud/mdn-migration-project/issues/39) has been added to the "Metrics & Monitoring" milestone for the migration tam.

The details are documented in https://github.com/mozilla-itcloud/mdn-migration-project/issues/29.
