### ISSUE TITLE
Document how to use and adapt to two-value display in CSS

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2341]
We need to add content about how to make use of the two-value syntax for `display`. This should cover both how to write CSS using this syntax, but also how to update existing CSS to use the new syntax, where possible and/or appropriate. Should also cover the value of the new syntax, how it's different/better, and so forth.

This probably ought to be part of a larger guide article or set of articles on using `display`.

## Acceptance criteria:

* Guide added to display docs to show how to use the two value syntax

**Comment by chrisdavidmills** [comment]
@rachelandrew this'd be a great one for you to do in the next sprint, if you feel like a break from learning area assessments.

You could crib a lot of it from your two value display syntax hacks post.

**Comment by rachelandrew** [comment]
@chrisdavidmills sure, there are a few things we've discussed regarding `display` as ultimately the display spec is key to pretty much all of layout. So the property page is a bit weird as the minute you say `display: grid` you are off to the grid spec (which has loads of docs), `display: flex` same for flexbox. Then there is a bunch of stuff which I think the new values make clearer (what `inline-block` really means etc.)

I've also written a lot of stuff about `display` in the Learn Layout section.

**Comment by rachelandrew** [comment]
I have written a new article on the two value syntax with some live examples: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display/two-value_syntax_of_display

Also updated the property page for display to link to it. https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by chrisdavidmills** [comment]
@rachelandrew awesome, thanks!

To neaten things up, I've put the info you added to the display ref page under a new heading:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display#Which_syntax_should_you_use_now

I've also copy edited the new article, and it looks fine, so closing this now.
