### ISSUE TITLE
source code link incorrectly to global.html on en-US/docs/WebAssembly/Using_the_JavaScript_API

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2342]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL` https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API

In Globals [source code](https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/global.html) URL seems to be incorrect

please look into it

**Comment by chrisdavidmills** [comment]
The globals source code link works for me.
