### ISSUE TITLE
/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

### ISSUE THREAD

**Issue by yeahan** [mdn/sprints#2343]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the below section

```
## Audio and video on the web

###    Using multiple source formats to improve compatibility

####      Media file support in browsers

The codecs described in the previous section exist to 
compress video and audio into manageable files, 
since raw audio and video are both exceedingly large; 
see our (raw video and audio is very large).  
...
```
where
> see our (raw video and audio is very large) 

should be a valid link but at present is seems to be a raw markdown snip.

**Comment by chrisdavidmills** [comment]
Ah yes, this was a mistake. I have just deleted the text; thanks for reporting.
