### ISSUE TITLE
removed wasm-utils.js in github repo, how should i proceed ?

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2344]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

wasm-utils.js link is given in following wiki pages
- https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format
- https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules

however it was deleted with [commit](https://github.com/mdn/webassembly-examples/commit/48f1cbfaf095c2a251c46e15b21ad8e4e3b1a866)

should i edit or remove link ?

**Comment by chrisdavidmills** [comment]
Remove the links — these utils are no longer needed now we have the `compileStreaming()`/`instantiateStreaming()` methods available.

**Comment by leela52452** [comment]
removed links, details :
- `/en-US/docs/WebAssembly/Understanding_the_text_format` [Revision 1589325](https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format$revision/1589325)
- `/en-US/docs/WebAssembly/Caching_modules` [Revision 1589327](https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules$revision/1589327)
