### ISSUE TITLE
is github webassembly gc repo is correct

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2345]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

i am making small changes in wiki, i found 404 error link on https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

Mutating tables and dynamic linking -> When WebAssembly gets [reference types](http://webassembly.org/docs/gc/)...

is it OK to update [this github repo link](https://github.com/WebAssembly/gc) ?

**Comment by chrisdavidmills** [comment]
I've updated it; thanks for reporting!
