### ISSUE TITLE
inappropriate images on /en-US/docs/Web/Security/Insecure_passwords

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2346]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL`  https://developer.mozilla.org/en-US/docs/Web/Security/Insecure_passwords

Firefox password security indicators
`paragraph one` **lock icon** https://support.cdn.mozilla.net/media/uploads/gallery/images/2017-04-21-23-52-53-ba340d.png

`paragraph two` **warning** https://support.cdn.mozilla.net/media/uploads/gallery/images/2015-11-17-12-13-18-2faa61.png

**Comment by chrisdavidmills** [comment]
I've deleted the images altogether. Thanks for reporting.
