### ISSUE TITLE
cant load and could not resolve error of chromium link at /en-US/docs/Web/Security/Mixed_content

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2347]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL` https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Active content examples**
[as they are in Chromium](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/loader/MixedContentChecker.cpp&q=MixedContentChecker::contextTypeFromContext%20f:cpp&sq=package:chromium&type=cs) redirects to [chromium.org](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/loader/MixedContentChecker.cpp?q=MixedContentChecker::contextTypeFromContext+f:cpp&sq=package:chromium&type=cs)

it shows the following error
> Can't load 'chromium/src/third_party/WebKit/Source/core/loader/MixedContentChecker.cpp':
Could not resolve path src/third_party/WebKit/Source/core/loader/MixedContentChecker.cpp.

**Comment by chrisdavidmills** [comment]
Hrm, I've just removed the link.
