### ISSUE TITLE
outdated yslow addon info on /en-US/docs/Web/Performance/Fundamentals

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2349]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`URL` https://wiki.developer.mozilla.org/en-US/docs/Web/Performance/Fundamentals

[yslow](http://yslow.org/) addon seems to be no longer maintained. [yslow github repo](https://github.com/marcelduran/yslow/) commit was in 2014.

**Comment by chrisdavidmills** [comment]
I've removed the reference. Thanks for reporting this!
