### ISSUE TITLE
/en-US/docs/Web/API/Document/fullscreenchange_event

### ISSUE THREAD

**Issue by SDP190** [mdn/sprints#2351]
This documentation seams to indicate that 2 events are fired for each fullscreen change, 1 on the Element it self and 2 on the owning document, but in fact its not true only 1 event is raised on the element which is then bubbling up, however if you stopPropagation, no event will be fired on the owning document.

**Comment by chrisdavidmills** [comment]
I see what you mean. I've tried editing the text on the page to give a more accurate picture — do you think this is better now? In which case we've made this mistake with a few similar pages ;-)

**Comment by SDP190** [comment]
@chrisdavidmills thanks for your quick response!

> I've tried editing the text on the page to give a more accurate picture — do you think this is better now?

So I checked your changes on the documentation:

---
![Capture3](https://user-images.githubusercontent.com/16751213/68823392-a0f18a80-0661-11ea-8c67-f5cec7266a39.PNG)
---

So still not happy, as I marked on the image, it still seems to indicate that there is a special behavior  with fullscreenchange event that it bubbles up to the **Document**, so again this isn't true, just that event bubbles up to all ancestor elements as usual behavior of any dom event which implements bubbling and not just to the owning document!

So there is no difference between the "fullscreenchange" event and all other DOM events!

You can verify that, by hooking an event listener for the  'fullscreenchange' event  on an intermediate ancaster element and the handler should call event.stopPropagation, you will see that no event will be fired up to the owning document.

**Comment by chrisdavidmills** [comment]
Ah yes, point taken; I messed up the wording there.

But there is a bigger discussion to have here; we also have an Element/fullscreenchange_event:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/fullscreenchange_event

Surely we should just redirect the Document/fullscreenchange_event to the Element one, and just refer to that?

Probably the same story for fullscreenerror, and maybe other events that are listed on document too. You can find the full list here:

https://developer.mozilla.org/en-US/docs/Web/API/Document#Events

**Comment by SDP190** [comment]
Hi @chrisdavidmills, I saw your changes for Element/fullscreenchange_event in here:
https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/fullscreenchange_event, now it looks great! No more indicates any special meanings on bubbling!

However about your concern _'we should just redirect the Document/fullscreenchange_event to the Element one, and just refer to that'_, I hear your point, but I guess that probably the reason behind that separation, is because, I think that the Document object is not an implementation of html 'Element' interface (at least to my understanding), and although it has a lot of same properties it still has its own characteristics.
Am I right?

**Comment by SDP190** [comment]
And as a continuation, to make things clear, we should differentiate between 3 kinds of events:
1) Events which are specific to Document interface only.
2) Events which are specific to Element interfaces only, and has no meaning on the Document and always originate from an contained element but is just bubbling up to the Document interface. (I think for example the 'click' event, 'fullscreenchange' event etc.
3) Events which may originate from both either an Element either Document interface.
