### ISSUE TITLE
/zh-CN/docs/Web/API/Window/setTimeout

### ISSUE THREAD

**Issue by barnett617** [mdn/sprints#2352]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link of "Reasons for delays longer than specified" is the current page again, so I can't know why the delay is longer than specified

![image](https://user-images.githubusercontent.com/23159565/67652305-3d880d00-f97f-11e9-9697-99e69349a51d.png)

![image](https://user-images.githubusercontent.com/23159565/67652287-2e08c400-f97f-11e9-8bb4-ca1ef8931894.png)

I find the answer in the after content and I check the html element of this part, it indeed has an anchor which id is "实际延时比设定值更久的原因：最小延迟时间", so I confirm this is a mistake.

![image](https://user-images.githubusercontent.com/23159565/67657307-55688c80-f991-11e9-93f7-64d864e320f4.png)

By the way, I think it is a little problem, so just modify the href to "#实际延时比设定值更久的原因：最小延迟时间" of the a tag where I find this problem like the picture after, it should work well.

![image](https://user-images.githubusercontent.com/23159565/67657642-4cc48600-f992-11e9-83a9-b7558e5a277b.png)

**Comment by chrisdavidmills** [comment]
I think I've fixed this now. Thank you for reporting it!
