### ISSUE TITLE
simple correction

### ISSUE THREAD

**Issue by atwak** [mdn/sprints#2354]
- [ ] Correction or update

/ In document https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB
/ referenced link https://developer.mozilla.org/en-US/en/IndexedDB/IDBKeyRange
/ is invalid (404)

**Comment by leela52452** [comment]
fixed w/[Revision 1588915](https://wiki.developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB$revision/1588915)
thank you for reporting
