### ISSUE TITLE
/en-US/docs/Web/XML/XML_introduction

### ISSUE THREAD

**Issue by dencoSeca** [mdn/sprints#2355]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Grammar mistakes/Odd grammar in the section on the XML documentation page attached in the screenshot:

<img width="1121" alt="2019-10-29 (2)" src="https://user-images.githubusercontent.com/57146772/67784909-67ffc600-fa64-11e9-9ca1-3169518740e9.png">

An example of better readability:

For an XML document to be correct the following conditions must be fulfilled:

  It must be well-formed.
  It must conform to all XML syntax rules.
  It must conform to semantic rules which are usually set in an XML schema or a 
  DTD (Document Type Definition).

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
