### ISSUE TITLE
/ru/docs/Web/API/ParentNode/append

### ISSUE THREAD

**Issue by zonzujiro** [mdn/sprints#2359]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In English version example of string which is used for appending is `"Some text"`.
But in the Russian version:
1. In section `Appending text` is `"Вася ест ноздри"` which translates as: "Ivan eats nostrils"
2. In the section `Appending an element and text` is `"Вася уже съел ноздри"` which translates as "Ivan ate nostrils".

I don't think that eating nostrils is a good idea for learning program development :)
Also, it is a not good idea in general, so I believe that examples should be changed to "Любой текст", which is translation of "Some text".

**Comment by chrisdavidmills** [comment]
Fixed. No more nostril eating here!

Thanks for reporting ;-)

**Comment by zonzujiro** [comment]
Thx!
