### ISSUE TITLE
overflow-inline documentation

### ISSUE THREAD

**Issue by bobOnGitHub** [mdn/sprints#2360]
# Request type
- [x ] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-inline

The documentation states "The overflow-inline CSS property sets what shows when content overflows an inline element's start and end edges"  but then gives an example which uses elements (divs) which are display:block.

If applying display:inline to the divs (in the provided jsFiddle) the overflow-inline (currently /Firefox 71.0b5 (64-bit) ) then has no effect. (possibly because width is ignored in inline elements - looks like overflow-inline hasn't been completely thought through yet)

The only effect I can see is with overflow-inline:scroll on a block element where it results in just a horizontal scrollbar while overflow:scroll results in both scrollbars.

**Comment by rachelandrew** [comment]
ah I think that description is just wrong, it's not *inline element* but inline edges, so the example is correct the prose is not. I can fix if you like.

**Comment by chrisdavidmills** [comment]
That would be great, cheers @rachelandrew !

**Comment by bobOnGitHub** [comment]
Ok, so I thought (reading the MDN doc) that this was bringing scroll to inline elements. If it's not and 

#div1 { overflow-inline: hidden;}
#div2 { overflow-inline: scroll;}
#div3 { overflow-inline: visible;}
#div4 { overflow-inline: auto;}

from the example has the same as effect as

#div1 { overflow: hidden;}
#div2 { overflow-x: scroll;}
#div3 { overflow: visible;}
#div4 { overflow: auto;}

then why is it needed ? - an example which shows how it adds functionality which is not available/possible with overflow would help.

**Comment by rachelandrew** [comment]
@bobOnGitHub these are part of implementing flow relative, logical properties in CSS, rather than the physical ones you are describing.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts

**Comment by rachelandrew** [comment]
That's now fixed, I made the same update to `overflow-block` as it had the same error.

**Comment by bobOnGitHub** [comment]
@rachelandrew cheers for that; I hadn't come across "writing mode" / logical css before and it didn't register when I read the doc.
