### ISSUE TITLE
Web API reference and Web API reference clone wiki pages

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2361]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

is there any specific reason for existence of Web API reference clone ? perhaps it was created unintentionally.

- [Web API reference](https://wiki.developer.mozilla.org/en-US/docs/Web/Reference/API)
- [Web API reference clone](https://wiki.developer.mozilla.org/en-US/docs/Web/Reference/API_clone)

**Comment by SphinxKnight** [comment]
@leela52452 Thanks for spotting this one :) I'm not finding any explanation in the revision comments and the history of the "API_clone" page is pretty poor compared to the canonic one.
I've deleted it (though it's still reversible)).

I'm closing this issue and pinging @chrisdavidmills to know if he knows more about this :)
