### ISSUE TITLE
/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

### ISSUE THREAD

**Issue by khangsfdc** [mdn/sprints#2362]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

From the doc: 

> Things that don't work with structured clone
Error and Function objects cannot be duplicated by the structured clone algorithm; attempting to do so will throw a DATA_CLONE_ERR exception.

Structured clone algorithm now supports Error objects, and is implemented in [Chrome](https://www.chromestatus.com/feature/5745988251680768) and WIP in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1556604)

**Comment by chrisdavidmills** [comment]
Thaks for reporting this. I've updated the page.
