### ISSUE TITLE
Improve the flex shorthand property documentation

### ISSUE THREAD

**Issue by Oromis** [mdn/sprints#2363]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Currently the section describing the flex property syntax looks like this: 

![image](https://user-images.githubusercontent.com/1381990/67939638-46bce800-fbd2-11e9-8d4a-5a5623b17986.png)

I think the bullet points describing the one-value and two-value syntax can be improved as they're misleading at the moment: 

When passing a single number to the one-value syntax, the documentation says 

> then it is interpreted as `<flex-grow>`. 

This can be interpreted as 

> The statement `flex: 1;` is equivalent to `flex-grow: 1;`

which is not correct according to the W3C spec: https://www.w3.org/TR/css-flexbox-1/#flex-common . Actually it is equivalent to specifying `flex: 1 1 0;`.

Suggestion: Explicitly specify the equivalent expression. I think for once the W3C spec does a better job at explaining it in this case: 

> `flex: <positive-number>`
>   Equivalent to `flex: <positive-number> 1 0`.

**Comment by lukeecart** [comment]
I've had a go at fixing the flex shorthand section. What do you think?
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/flex$compare?locale=en-US&to=1593173&from=1590432

**Comment by chrisdavidmills** [comment]
@lukeecart This was not looking too bad — I've cleaned up the sentence a bit. You need to be careful with values written inside angle brackets in CSS, as these are specific datatypes, e.g. <number>. There is no such CSS datatype as <positive-number>.

I think we can close this one now. Thakns for your help!
