### ISSUE TITLE
WCAG reference on accessibility guidelines

### ISSUE THREAD

**Issue by ploafmaster** [mdn/sprints#2364]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I was reading this page:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard

Since the documentation (reached from the Accessibility inspector in the dev tools (FF Dev Edition v.71 ob3 on macOS Mojave 10.14.6) references WCAG, it would probably be helpful for users if there were links to the relevant guidelines in the W3C site so we could know which principals/guidelines/success criteria apply.

**Comment by chrisdavidmills** [comment]
This is a pretty good idea @jmswisher . In the same way as we do on the text labels page, perhaps?

https://wiki.developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#Related_WCAG_success_criteria
