### ISSUE TITLE
Create an Overview page for CSS Motion Path

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2370]
# Request type

- [*] New documentation
- [ ] Correction or update

# Details

We have most of the properties from this spec documented but don't have an overview page for the specification yet.

https://www.w3.org/TR/motion-1/

**Comment by chrisdavidmills** [comment]
We have one:

https://developer.mozilla.org/en-US/docs/Web/CSS/Motion_Path

So I guess this can be closed
