### ISSUE TITLE
/en-US/docs/Learn/Server-side/Django/Admin_site

### ISSUE THREAD

**Issue by an-ba** [mdn/sprints#2372]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On [Django Tutorial Part 4: Django admin site](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site) under section _Registering models_
The following instructions are given
```python
from catalog.models import Author, Genre, Book, BookInstance
```
However, since models.py and admin.py reside in the same directory, the import statement need to be changed to reflect this relationship, i.e 
```python
from .models import Author, Genre, Book, BookInstance
```

**Comment by hamishwillee** [comment]
Thanks. Yes this was valid. Fixed.

**Comment by chrisdavidmills** [comment]
@hamishwillee thanks! Closing.
