### ISSUE TITLE
/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page

### ISSUE THREAD

**Issue by Spikatrix** [mdn/sprints#2373]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The screenshot at the end of the [page](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page) under 'What does it look like?' is incorrect. As seen in the code in that page,

    - book_list.sort(function(a, b) {let textA = a.title.toUpperCase(); let textB = b.title.toUpperCase(); return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;});

The list of books should be sorted in the screenshot. And as expected, I got the output sorted as follows:

```
Book List

- Apes and Angels (Bova, Ben)
- Death Wave (Bova, Ben)
- Test Book 1 (Jones, Jim)
- Test Book 2 (Jones, Jim)
- The Name of the Wind (The Kingkiller Chronicle, #1) (Rothfuss, Patrick)
- The Slow Regard of Silent Things (Kingkiller Chronicle) (Rothfuss, Patrick)
- The Wise Man's Fear (The Kingkiller Chronicle, #2) (Rothfuss, Patrick)
```

**Comment by chrisdavidmills** [comment]
Can you provide me with an updated screenshot? I can then update it.

**Comment by chrisdavidmills** [comment]
I have tested it, and sure enough, you are right. I've updated the screenshot. Thanks for reporting!

**Comment by Spikatrix** [comment]
@chrisdavidmills Thank you for testing and correcting it!

Sorry that I couldn't provide you the corrected screenshot on time as I was away from my laptop
