### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

### ISSUE THREAD

**Issue by goplayerjuggler** [mdn/sprints#2374]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

This page could do with some details about string literals using ticks, eg
``` javascript
var foo =  `this
is a 
multiline string literal`
```

**Comment by chrisdavidmills** [comment]
Template literals are mentioned, here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Template_literals
