### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

### ISSUE THREAD

**Issue by dotnetCarpenter** [mdn/sprints#2378]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Looking at `Math.trunc`, I realized that it does what I have always used `|0` for.
`|0` does not work for `Infinity`, `String` `undefined`, so `Math.trunc` has its place.
What I don't get is the elaborate polyfill examples. It seems to me that they are over complicated to get the effect of `|0` (bitwise or).

> Bitwise ORing any number x with 0 yields x.
> <sub>source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_OR</sub>

```js
function trunc (v) {
	v = +v // turns String and undefined into NaN
	if (!isFinite(v)) return v // handles Infinity and NaN
	return v|0 // handles all numbers and null
}

console.log(
  	Math.trunc(NaN),
  	Math.trunc(),
	Math.trunc('foo'),
	trunc(NaN),
  	trunc(),
	trunc('foo'),
	trunc(0) === Math.trunc(0),
	trunc(-0) === Math.trunc(-0),
	trunc(0.2) === Math.trunc(0.2),
	trunc(0.7) === Math.trunc(0.7),
	trunc(-0.7) === Math.trunc(-0.7),
	trunc(Infinity) === Math.trunc(Infinity),
	trunc(-Infinity) === Math.trunc(-Infinity),
	trunc(null) === Math.trunc(null)
)
```

Please compare these two polyfills which does the exact same:
```js
if (!Math.trunc) {
	Math.trunc = function (v) {
		return v < 0 ? Math.ceil(v) : Math.floor(v);
	};
}
```

```js
if (!Math.trunc) {
	Math.trunc = function (v) {
		return isFinite(v) ? v|0 : +v
	}
}
```

**Comment by dotnetCarpenter** [comment]
Bitwise ORing was made popular by asm.js.
https://stackoverflow.com/questions/33367264/what-does-0-do-in-javascript

**Comment by spazmodius** [comment]
`v | 0` is definitely _not_ the same as `Math.trunc(v)`. Try:

```js
var v = 4294967296.1
console.log(v, Math.trunc(v), v | 0)
```

Output: `4294967296.1 4294967296 0`

**Comment by dotnetCarpenter** [comment]
@spazmodius nice! Can you share a little more information to why that is? It seems that `4294967296` is a threshold number. But a threshold model of what?

**Comment by spazmodius** [comment]
`Math.trunc` returns the input number without its fractional part.  That's not what the bitwise-OR operator does... it converts it's operands to 32-bit signed integers.

`4294967296` (that is, 2^32) won't fit into a 32-bit integer. But neither does `2147483648.1`.

**Comment by dotnetCarpenter** [comment]
Got it - thanks!
I was puzzled since I didn't recognized `4294967296` as being close to
`2147483647`. Too many digits for my brain.
