### ISSUE TITLE
Fx62 DDNs (unassigned; DO NOT work off this issue)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#238]
## Process description

At the start of each major Fx release, Chris will go through the list of DDN bugs and add them to a issue like this. This is a repository to store the backlog of DDN bugs for the Fx 62 release, and it is expected that these will be done in the sprints leading up to Fx62 going into beta.

Don't work directly off this card. Instead, before the first sprint of the 62 period starts, look through the bugs in your area of responsibility, and give them a time estimate. Put it after the link to the bug, in the same row. Use the following estimate scores:

*   A really short bug, will probably only take an hour or two — 0.25 points. We could get 4 of these done in a day without too many problems.
*   A shortish bug which will take half a day — 0.5 points.
*   A longer bug, but still doable in a reasonable amount of time — 1-2 points.
*   Anything longer than that — tell Chris about it, and he will pull it out of DDN land and file it in the roadmap as a separate item of work to be scheduled for later.

If you come across multiple bugs that are closely related, treat them all as one item, tell Chris about it, and we will review this area and write a plan, checking to see what else needs to be done around this area. Again, it will be scheduled in later.

After we have done this, Chris can then work out how many of these items will fit in the next sprint, and put them in a separate issue, to be put in the sprint.

Areas of responsibility:

*   DOM — Chris/Sheppy (can we do half each for now?)
*   Layout — Will
*   HTML — Chris
*   WebExt — Will/Irene (will transition to Irene slowly but surely)
*   DevTools — Chris/Irene (will transition to Irene slowly but surely)
*   JavaScript — Florian
*   Media — Sheppy
*   General — Chris

## DOM DDNs

1.  - [ ] [deprecating the "referrer" directive in CSP](https://bugzilla.mozilla.org/show_bug.cgi?id=1302449): 0.25 points, mostly done, but needs some checking and BCD data updates. BCD PR is already in.
2.  - [ ] <s>[Change navigator.registerContentHandler to throw on at least the blocklisted types](https://bugzilla.mozilla.org/show_bug.cgi?id=1266492)</s>: This is actually a WONTFIX, nothing to do here
3.  - [ ] [registerProtocolHandler require SecureContext in stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1460506): 0.25 points
4.  - [ ] [Allow setting KeyframeEffect.target](https://bugzilla.mozilla.org/show_bug.cgi?id=1067769): 0.5 points.
5.  - [ ] [Disable registerContentHandler() in stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1460481): 0.25 points
6.  - [ ] [Remove *ReadOnly and AnimationEffectTiming animation interfaces](https://bugzilla.mozilla.org/show_bug.cgi?id=1456394): 2 points
7.  - [ ] [Implement the Navigation Timing 2 spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1043083): 1 point. Looks like we documented most of this already, but we ought to check that we got it right.
8.  - [ ] [convert inIDOMUtils to Web IDL](https://bugzilla.mozilla.org/show_bug.cgi?id=1427419): 1 point. This is an internals thing, so not really our remit. Throw it back to the engineers?
9.  - [ ] [Disable devicelight, deviceproximity and userproximity events from stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1462308): 0.25 points
10.  - [ ] [unresponsive visiting login page on eqbank.ca](https://bugzilla.mozilla.org/show_bug.cgi?id=1460295): 0.25 points.
11.  - [ ] [enable Shadow DOM in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1460069): 0.25 points
12.  - [ ] [Implement the DataTransfer constructor](https://bugzilla.mozilla.org/show_bug.cgi?id=1351193): 0.25 points
13.  - [ ] [Remove DOMPoint{,ReadOnly}(DOMPointInit) constructor, implement DOMPoint{,ReadOnly}.fromPoint](https://bugzilla.mozilla.org/show_bug.cgi?id=1186265): 2 points
14.  - [ ] [Should we stop returning null from document.domain?](https://bugzilla.mozilla.org/show_bug.cgi?id=819475): 0.25 points
15.  - [ ] [document.domain throws wrong exception](https://bugzilla.mozilla.org/show_bug.cgi?id=1457689): 0.25 points
16.  - [ ] [Enable W3C Pointer Events and touch-action CSS property by default](https://bugzilla.mozilla.org/show_bug.cgi?id=960316): 0.5 points

TOTAL: 8.25 points

## Layout DDNs

1.  - [ ] [Remove the -moz prefix from ::selection](https://bugzilla.mozilla.org/show_bug.cgi?id=509958) 0 points (done already)
2.  - [ ] [Support 'x' as a resolution unit.](https://bugzilla.mozilla.org/show_bug.cgi?id=1460655) 0.25 points
3.  - [ ] [unship CSSStyleDeclaration::getPropertyCSSValue](https://bugzilla.mozilla.org/show_bug.cgi?id=1408301) 0 points (done already)
4.  - [ ] [Remove other getPropertyCssValue-related interfaces.](https://bugzilla.mozilla.org/show_bug.cgi?id=1459871) 0.5 points
5.  - [ ] [Add some scrollbar color properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1460456): 2 points; Two new properties added.
6.  - [ ] [Hide -moz-prefixed display values from web content](https://bugzilla.mozilla.org/show_bug.cgi?id=1288572) 0.25 points
7.  - [ ] [Make internal -moz-window-opacity and -moz-window-transform transitionable even when the properties are hidden from content pages.](https://bugzilla.mozilla.org/show_bug.cgi?id=1419695) 0 points — these are non-standard, and not even available to web content, so don't bother.
8.  - [ ] [Implement 'shape-margin' for polygon](https://bugzilla.mozilla.org/show_bug.cgi?id=1451499) 0.25 points
9.  - [ ] [Enable shape-outside for all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1457297) 0.25 points
10.  - [ ] [[css-grid] calc() function doesn't work inside repeat() function and grid line/span](https://bugzilla.mozilla.org/show_bug.cgi?id=1350069) 0.25 points
 11. - [ ] [Support calc() in CSS properties that take values](https://bugzilla.mozilla.org/show_bug.cgi?id=1296209) 0.25 points - I think there is nothing to do here but we should check.
12.  - [ ] [Don't return null from getComputedStyle when there's no presentation.](https://bugzilla.mozilla.org/show_bug.cgi?id=1467722) 0.25 points

TOTAL: 3.25 points

## HTML DDNs

1.  - [ ] [HTML5 `<ruby>` support](https://bugzilla.mozilla.org/show_bug.cgi?id=33339): 0.25 points. Looks like we already have this documented, but we might want to check.

TOTAL: 0.25 points

## WebExt DDNs

1.  - [ ] [Expose API to customize where new tabs open](https://bugzilla.mozilla.org/show_bug.cgi?id=1344749) 0.25 points
2.  - [ ] [Remove support for unpacked side-loaded extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1385057) 0.5 points
3.  - [ ] [deprecate windowTypes for windows.get, windows.getCurrent and windows.getLastFocused](https://bugzilla.mozilla.org/show_bug.cgi?id=1419132) 0.25 points
4.  - [ ] [webRequest.onBeforeRequest fetch redirect gets blocked due to bogus CORS error](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) 0.5 points
5.  - [ ] [Consider allowing to modify browserAction per window](https://bugzilla.mozilla.org/show_bug.cgi?id=1419893) 0.5 points
6.  - [ ] [Reconsider opening sidebar on install of an extension](https://bugzilla.mozilla.org/show_bug.cgi?id=1460910) 0.25 points
7.  - [ ] [Web extensions: SSL (TLS) status API request](https://bugzilla.mozilla.org/show_bug.cgi?id=1322748) 2 points
8.  - [ ] [Allow changing the tab separator color](https://bugzilla.mozilla.org/show_bug.cgi?id=1459455): 0 points, Irene already did this, just waiting for review.
9.  - [ ] [remove browser_style warnings](https://bugzilla.mozilla.org/show_bug.cgi?id=1404724) 0.25 points
10.  - [ ] [Change nsIContentPolicy shouldLoad to take an nsILoadInfo instead of the various arguments](https://bugzilla.mozilla.org/show_bug.cgi?id=1439713) 0 points, not a WE bug

TOTAL: 4.75 points

## DevTools DDNs

1.  - [ ] [Add support for same-site cookie attribute to "Cookies" side-panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1452715): 0.25 points
2.  - [ ] [Provide an easier way to close a split console](https://bugzilla.mozilla.org/show_bug.cgi?id=1444302): 0.25 points
3.  - [ ] <s>[Add toggle for --fullpage screenshots to Options Panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1282462)</s>: this is actually INVALID, so nothing to do here.
4.  - [ ] [Console API: Implement console.countReset()](https://bugzilla.mozilla.org/show_bug.cgi?id=1459279): 0.5 points
5.  - [ ] [Implement frontend for console.timeLog](https://bugzilla.mozilla.org/show_bug.cgi?id=1461001): 0.5 points
6.  - [ ] [Implement frontend for console.countReset()](https://bugzilla.mozilla.org/show_bug.cgi?id=1463525): 0 points, will probably be done as part of number 4.
7.  - [ ] [ability to dock firefox developer toolbar left, for large screen resolutions](https://bugzilla.mozilla.org/show_bug.cgi?id=1192642): 0.5 points
8.  - [ ] [Add support for container tabs to RDM](https://bugzilla.mozilla.org/show_bug.cgi?id=1306975); 0.25 points
9.  - [ ] [The buttons on the right of the DevTools tab bar are unclear](https://bugzilla.mozilla.org/show_bug.cgi?id=1444301): 0.25 points
10.  - [ ] [Always display the Frame picker button if the user is on the Options panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1456069): 0.25 points
11.  - [ ] [Top-Down Stack](https://bugzilla.mozilla.org/show_bug.cgi?id=1471167): 0.25 points
12.  - [ ] [Remove Firebug theme](https://bugzilla.mozilla.org/show_bug.cgi?id=1378108): 0.25 points
13.  - [ ] [Remove gcli UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1461970): 1 point
14.  - [ ] [Implement Console.timeLog(optional DOMString label = "default")](https://bugzilla.mozilla.org/show_bug.cgi?id=1458466): 0 points, will be done along with number 5.

TOTAL: 4.25 points

## JavaScript DDNs

1.  - [ ] [Implement import.meta](https://bugzilla.mozilla.org/show_bug.cgi?id=1427610) 0.5 points
2.  - [ ] <s>[Remove js_GetterOnlyPropertyStub](https://bugzilla.mozilla.org/show_bug.cgi?id=688017)</s> This is SpiderMonkey and not web docs.
3.  - [ ] [Enable WebAssembly.Global by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1464656) 0.25 points
4.  - [ ] <s>[Implement milestone 0 <script type="module">](https://bugzilla.mozilla.org/show_bug.cgi?id=1240072)</s> This is just a tracking bug.
5.  - [ ] [Implement JSON superset proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1435828) 0.25 points
6.  - [ ] [Enable Array.prototype.flat (was flatten) and Array.prototype.flatMap in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1435813) 0.25 points
7.  - [ ] [Object.defineProperty needs to be able to return false in some cases](https://bugzilla.mozilla.org/show_bug.cgi?id=1329321) 0.25 points
8.  - [ ] [WebGL - implement powerPreference](https://bugzilla.mozilla.org/show_bug.cgi?id=1349799) 0.25 points

TOTAL: 1.75 points

## Media DDNs

1.  - [ ] [Update AudioWorkletGlobalScope definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1460896) 0 points, done along with number 5.
2.  - [ ] [[MSE] Have appendBuffer and remove return a promise](https://bugzilla.mozilla.org/show_bug.cgi?id=1280613) 1 point
3.  - [ ] [Implement AudioParamMap definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1460907) 0.5 points
4.  - [ ] [Add AudioWorkletNode interface definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1458446) 1 point
5.  - [ ] [Implement AudioWorkletGlobalScope](https://bugzilla.mozilla.org/show_bug.cgi?id=1322858): 1 point.

TOTAL: 2.5 points

## General DDNs

1.  - [ ] [Implement Clear-Site-Data response header to reset origin storage](https://bugzilla.mozilla.org/show_bug.cgi?id=1268889): 0.5 points; new HTTP header
2.  - [ ] <s>[TTL issue tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1250547)</s>: This is a large piece of work, and needs to be discussed and prioritised separately. Removing from DDNs.

TOTAL: 0.5 points

**Comment by jmswisher** [comment]
@chrisdavidmills Can this epic be closed?

**Comment by chrisdavidmills** [comment]
Yup!
