### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Trailing_commas

### ISSUE THREAD

**Issue by jasonsrogers** [mdn/sprints#2380]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Small issue but going through the Trailing commas, class C is not defined correctly

```
class C {

  one(a,) {},

  two(a, b,) {},

}
```
Classes don't have `,` after the methods {}
Otherwise it throws 

> Uncaught SyntaxError: Unexpected token ','

if should be 
```
class C {

  one(a,) {}

  two(a, b,) {}

}
```

**Comment by Elchi3** [comment]
Yup, you are correct! Thanks for reporting! I've fixed the docs.
