### ISSUE TITLE
/fr/docs/Web/JavaScript/Reference/Instructions/async_function

### ISSUE THREAD

**Issue by algumugla** [mdn/sprints#2381]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

French translation issue : 

"Avec concurrentStart, si l'un des deux appels échoue, l'exception sera immédiatement interceptée et l'exécution de la fonction asynchrone sera interrompu**e**." instead of "interrompu".

**Comment by SphinxKnight** [comment]
@algumugla : could you please elaborate a little or shoud we close this issue as accidental?
Pouvez-vous en dire plus sur le problème rencontré sur cette page ? Sans information, nous ne pouvons pas faire grand chose et devrons fermer cette *issue*.

**Comment by algumugla** [comment]
> @algumugla : could you please elaborate a little or shoud we close this issue as accidental?
> Pouvez-vous en dire plus sur le problème rencontré sur cette page ? Sans information, nous ne pouvons pas faire grand chose et devrons fermer cette _issue_.

J'ai malencontreusement laissé ma description entre balises commentaires. C'est maintenant corrigé.

**Comment by SphinxKnight** [comment]
Merci ! J'ai corrigé cette faute avec https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/async_function$revision/1589895

N'hésitez pas à éditer vous-même les documents quand vous décelez une telle coquille :) MDN est un wiki et n'importe qui (sous réserve d'avoir un compte GitHub) peut l'éditer !
