### ISSUE TITLE
/en-US/docs/Web/CSS

### ISSUE THREAD

**Issue by snakada** [mdn/sprints#2382]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It looks like there are incorrect or old link in the tutorial section of [/en-US/docs/Web/CSS](https://developer.mozilla.org/en-US/docs/Web/CSS).

There is a link to the [Styling boxes](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_boxes), and a paragraph, but it seems that they are now redirected to [CSS building blocks](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks).

![CSS__Cascading_Style_Sheets___MDN](https://user-images.githubusercontent.com/12525768/68410528-34dbd600-01cc-11ea-9a4f-8672cea18b36.png)

I imagine that it was probably correct in the past, but the contents of the link source and link destination may be mismatched. I think that it will be good to be corrected, so please check.

I always learn a lot at MDN from Japan. Thank you.

**Comment by chrisdavidmills** [comment]
@snakada Thank you so much for reporting this problem!

I have now fixed it with the correct links and descriptions of the updated CSS tutorials.

**Comment by snakada** [comment]
Thank you for quick response.

The Japanese version of [/ja/docs/Web/CSS](https://developer.mozilla.org/ja/docs/Web/CSS) and [/ja/docs/Learn/CSS](https://developer.mozilla.org/ja/docs/Learn/CSS) have been modified in the same way.

I will continue to learn. Thank you.
