### ISSUE TITLE
Incorrect wording on Map global object page

### ISSUE THREAD

**Issue by spazmodius** [mdn/sprints#2384]
# Request type
[x] Correction or update

# Details
> Each key-value pair is added to the new Map; **null values are treated as undefined.**

I can't think of any interpretation that makes this statement true. Maps can have values (and keys, for that matter) of both `null` and `undefined`, and they remain distinct.

**Comment by chrisdavidmills** [comment]
Page in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by chrisdavidmills** [comment]
I've had a good look through the spec, and can't find any evidence of where this might have come from. What you say sounds right to me.

I've deleted it for the moment, but we can always add it back in if necessary!
