### ISSUE TITLE
Contradiction in "Infallible Memory Allocation" page

### ISSUE THREAD

**Issue by phoddie** [mdn/sprints#2385]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The page on [Infallible Memory Allocatioin](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Infallible_memory_allocation) contains the following:
- "Eventually, however, the generic memory allocators (malloc() and realloc()) will become infallible."
- "These memory allocators are explicitly fallible, and will remain so" followed by a list that begins with malloc and realloc.

These two statements appear to be inconsistent with each other. I did not attempt to correct it as I don't have knowledge of Mozilla's intention regarding the long term (in)fallibility of malloc and realloc.

**Comment by Elchi3** [comment]
Thanks for your issue. This doc set isn't maintained and will be archived soon. Closing this issue.
You might want to checkout new docs at https://firefox-source-docs.mozilla.org/
