### ISSUE TITLE
/fr/docs/Web/CSS/Pseudo-éléments  -  /fr/docs/Web/CSS/Pseudo-classes

### ISSUE THREAD

**Issue by Totokoutonio** [mdn/sprints#2387]
# Request type

- [x] Correction or update

# Details

Hello, 
In the French version I think there is an inversion between the page "Pseudo-éléments" and "Pseudo-classes" at the end of the 1st paragraph. 

in the Pseudo-classes page it say : 
>À la différence des pseudo-classes, les pseudo-éléments peuvent être utilisés afin d'appliquer un style sur une certaine partie d'un élément.
 
and in the Pseudo-éléments page it say 
>À la différence des pseudo-éléments, les pseudo-classes peuvent être utilisées afin de mettre en forme un élément en fonction de son état.

I think it's a little bit confusing...

**Comment by SphinxKnight** [comment]
@Totokoutonio Merci pour ce retour ! Je vais tenter, dans les prochains jours, une reformulation pour expliciter/clarifier tout ça.
Si vous le souhaitez, vous pouvez aussi éditer la page pour améliorer la formulation, je me ferai une joie de relire :) après tout MDN est un wiki.

**Comment by Totokoutonio** [comment]
J'ai fait une modification  :-). 
Après avoir vue la version US je me suis rendu compte qu'il manquais simplement un cadre "Note" qui permet de voir qu'il est question d'autre chose...

**Comment by SphinxKnight** [comment]
Merci beaucoup @Totokoutonio pour cette contribution !
