### ISSUE TITLE
/en-US/docs/Web/Media/Formats/Audio_codecs

### ISSUE THREAD

**Issue by skz169** [mdn/sprints#2388]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Supported bit rates of [MP3](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#MP3) listed in khz instead of kbps.

**Comment by SphinxKnight** [comment]
This is [now fixed](https://wiki.developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs$compare?locale=en-US&to=1590385&from=1588936) 

Do not hesitate to edit MDN to fix such typos, it's a wiki and anyone will benefit from less typos like this :)
