### ISSUE TITLE
/zh-CN/docs/Web/CSS/@font-face/font-stretch

### ISSUE THREAD

**Issue by paultyh** [mdn/sprints#2389]
# Request type
- [x] Correction or update
No support in Chorme 74 and Firefox68 and so on.

# Details

**Comment by SphinxKnight** [comment]
Hello @paultyh, could you please open an issue on the [browser-compat-data repo](https://github.com/mdn/browser-compat-data/). Please provide a test case to explain why the data is incorrect.

The file that produces the table you can see for @font-face/font-stretch is this one: https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/font-face.json#L386
