### ISSUE TITLE
Incorrect string.indexOf description

### ISSUE THREAD

**Issue by Joaos98** [mdn/sprints#2392]
# Request type

- [ ] Correction or update

# Details

The description of the fromIndex parameter says that if the parameter is >= than str.length the method returns -1, but that is false.

**Comment by Leokuma** [comment]
That is actually correct.

Having a `fromIndex` equal or greater than `length` means that the search will start after the last character of the string, which doesn't make sense. Remember that `fromIndex` starts at 0.

![image](https://user-images.githubusercontent.com/9329952/68610761-43a9dd80-0497-11ea-9aec-1ea410537876.png)

**Comment by Joaos98** [comment]
Oh, sorry, i initially thought it worked like that, but then i got confused because of this one example where it returned 10 even though `fromIndex `was > than `length`, and after some testing i now understand that it didn't return -1 because the string it was looking for is an empty string, and in that case apparently it just returns the length of the string. Thanks for the answer!
![image](https://user-images.githubusercontent.com/33532434/68613013-92a64180-049c-11ea-8304-a5576e4eb402.png)

**Comment by Leokuma** [comment]
Hum, you do have a point, though:

![image](https://user-images.githubusercontent.com/9329952/68615671-507ffe80-04a2-11ea-8bc2-4480dfc96664.png)
So, when searching for an empty string, it behaves somewhat unpredictably.

**Comment by Joaos98** [comment]
Yeah, i guess there is some sort of an error after all! Well, thanks again for the answers!

**Comment by chrisdavidmills** [comment]
This is an interesting case — I do agree that the behavior and wording here is a little confusing.

I've done some testing and added some wording to 

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf#Syntax

Does this help?

**Comment by Leokuma** [comment]
For me it's perfect.

I can try to update the Portuguese version myself, or I can leave that with you specialists :+1:.

**Comment by chrisdavidmills** [comment]
@Leokuma cool, I'm glad it is helpful!

For the pt-BR, I'm sure you write much better Portuguese than any of us ;-) We have no Portuguese speakers on the team.

**Comment by Leokuma** [comment]
I updated the pt-BR page.
