### ISSUE TITLE
form cannot submit while url with hash part

### ISSUE THREAD

**Issue by molihub** [mdn/sprints#2393]
**Summary**
_form cannot submit while url with hash part_

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Create any local web page with a form,  that include a text field named t and a input type="submit". In windows system, like "C:\foo.html"
```html
<form>
    <input type="text" name="t">
    <input type="submit" value="OK">
</form>
```
2. Access the web page using url "file:///C:/foo.html?t=#anything"
3. Clear the value of text field t，then click the submit button of the form. 

**Actual behavior**
_no submit action occur._

**Expected behavior**
_form will be submit and file access will occur_

**Additional context**
_nothing_

**Comment by chrisdavidmills** [comment]
This is probably some kind of expected behavior; I've not really got an answer for you here. Maybe try asking some of the Firefox engineers over on a list such as dev-platform?
