### ISSUE TITLE
HTMLMediaElement API error

### ISSUE THREAD

**Issue by jessuni** [mdn/sprints#2395]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On [HTMLMediaElement API page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement ), `HTMLMediaElement.duration` is stated to return `0` when media is not available. However, [HTMLMediaElement.duration page]( https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration) says:

> If no media data is available, the value NaN is returned.

The two description does not match.

If source is unavailable, `HTMLMediaElement.duration` returns `NaN`.

**Comment by chrisdavidmills** [comment]
You are right — the main page description should say `NaN`, not 0, as per the specification.

I've updated this now; thanks for reporting!
