### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by xaverfleer** [mdn/sprints#2397]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

According to [\<div\>: The Content Division element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div) "both the starting and ending tag are mandatory."

In the first code sample of [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) the ending tag is missing.

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!

**Comment by xaverfleer** [comment]
Awesome, thank you so much!
