### ISSUE TITLE
WebXR: Complete content about the rendering loop

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2398]
Make sure we have complete content about the rendering loop. This should be a simple guide about the loop itself, with links out to the material about specifics of rendering WebXR models, camera movement, etc.

- [x] The physiology of human vision should be touched upon, especially where the span between the eyes, field of view, and similar notions are concerned
- [x] Creating a render loop
- [x] The role of viewers, views, and poses
- [x] Handling inputs (both XR and non-XR)
- [x] Determining the current relative placement of all visible objects
- [x] Drawing objects using WebGL
- [x] Timing

Consider where diagrams will make things easier to understand. Possible candidates include:

* Physiology and viewer position
* How views and poses relate to objects in the world; may also involve reference spaces

# Acceptance criteria
- [x] Written and complete
- [x] Submitted for review

**Comment by a2sheppy** [comment]
This probably should be split into 2-3 issues.

**Comment by a2sheppy** [comment]
A lot of this has already been written in other articles. This is now reduced to just an article about the functionality of the render loop specifically, with references out to the related content in other articles.

**Comment by a2sheppy** [comment]
Content is complete and I've asked on Slack's #mr channel for review.

**Comment by chrisdavidmills** [comment]
@a2sheppy did you get a review of this article?
