### ISSUE TITLE
E - Maintain MDN code and infrastructure

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#240]
# User story
As a MDN developer, I want to be on recent versions of libraries and backing services, to avoid downtime and security issues, to benefit and participate in open source development, and to make it faster to implement new features.

# Acceptance criteria
This will only be complete when MDN is shut down and deleted. Some health metrics:

* We upgrade frameworks, like Django, when a new LTS is released
* We upgrade language runtimes, like Python and node.js, when a new stable version is released
* We upgrade operating systems and backing services when a new stable version is released
* We update 3rd-party libraries within a month of release

**Comment by tobinmori** [comment]
Closing because this is old.
