### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype

### ISSUE THREAD

**Issue by mybells** [mdn/sprints#2400]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Property attributes of Object.prototype
Writable | no
Enumerable | no
Configurable | no

but Chinese translation is:
writable | true
enumerable | false
configurable | true

**Comment by SphinxKnight** [comment]
Fixed w/ https://wiki.developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype$revision/1590382
