### ISSUE TITLE
Minor update to "Your first web extension" installation instructions

### ISSUE THREAD

**Issue by swebb** [mdn/sprints#2401]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

System: Linux (Fedora)
Firefox: 70

On this page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

The installation instructions are out of date. It says:

> Open "about:debugging" in Firefox, click "Load Temporary Add-on" and select any file in your extension's directory:

I believe it should read:

> Open "about:debugging" in Firefox, click "Load Temporary Add-on", click "This Firefox", and select any file in your extension's directory:

What I'm seeing:

![Screenshot from 2019-11-13 12-01-12](https://user-images.githubusercontent.com/543166/68732138-50504200-060d-11ea-8e5f-57f3f1254600.png)

Also the youtube video is out of date.

**Comment by chrisdavidmills** [comment]
Thanks for reporting! I've updated the sentence to reflect the new page layout, and the fact that "This Firefox" exists only in newer versions of Firefox.

I've left the video for now, as I don't have the facilities to update it.
