### ISSUE TITLE
Create Epic and sub-stories detailing what assessments need to be created/updated

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2403]
# User story

We have basically decided what the form of new assessments should be on the learning area. Now we need to create new assessments, and update old assessments.

# Acceptance criteria

1. - [x] Create an Epic under which to put all user stories for assessments to be created or updated
2. Create user stories for all the assessments that need to be created in the different areas of the learning area. These areas are most important, and will do for now:
* - [x] HTML
* - [x] CSS
* - [x] JavaScript
* - [x] Forms
* - [x] Testing
* - [x] a11y

**Comment by chrisdavidmills** [comment]
Epic to put user stories under: https://github.com/mdn/sprints/issues/2477

**Comment by chrisdavidmills** [comment]
I've written user stories for all the modules listed above, except for the CSS ones. I think @rachelandrew  is better equipped to write those.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've been through the CSS ones, I followed what you had done in terms of batching them up in the modules but the building blocks and layout sets got pretty big. We could split them into individual tasks to add to a sprint though.

**Comment by chrisdavidmills** [comment]
Yup, we sure can. That all looks OK to me, so I'm closing this now. Thanks for the great work!
