### ISSUE TITLE
Plan for getting MDN docs into structured Markdown

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2405]
We have a very high-level idea of how we can migrate our docs into structured Markdown (stumptown) but need to break it down to a point where we can write epics and eventually user stories for it, and can see how all the pieces fit together to deliver the goal.

****

**Acceptance criteria:**

* plan is written as a doc in stumptown-content, and reviewed by team members
* epics for the main components are filed in stumptown-content

**Comment by wbamberg** [comment]
I think this is done enough :).

Plan written: https://docs.google.com/document/d/1in5hunkSUs1eTZ9ZjPe6ZJFH-MVVAKYVxxeMXv2VQ8U/edit#heading=h.23c4cqowjc0w
Epic for the first piece written: https://github.com/mdn/sprints/issues/2517

**Comment by ExE-Boss** [comment]
@wbamberg Why&nbsp;is that&nbsp;document set&nbsp;to&nbsp;private?

**Comment by wbamberg** [comment]
@ExE-Boss , I've made it public.
