### ISSUE TITLE
Is defineProperties() description correct?

### ISSUE THREAD

**Issue by mybells** [mdn/sprints#2406]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Object.defineProperties, in essence, defines all properties corresponding to **the enumerable own properties of props** on the object obj object.

![image](https://user-images.githubusercontent.com/23007275/68819769-0aa28080-06c4-11ea-887f-7c3f1fdbde4d.png)

obj.a enumerable is false,but obj.a can be defined. is the description correct?

**Comment by chrisdavidmills** [comment]
Page in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties

**Comment by Elchi3** [comment]
I've removed this section. I don't think it adds any benefit and it seems to rather confuse.
