### ISSUE TITLE
/fr/docs/Web/API/XMLHttpRequest

### ISSUE THREAD

**Issue by Lyokolux** [mdn/sprints#2407]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
There is a problem with the **french translation** on the [XMLHttpRequest](https://developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest) for the method  `XMLHttpRequest.setRequestHeader()`.
>Définit la valeur d'un en-tête de requête HTTP. Cette méthode doit être appelée *avant* open() mais *après* send().

Should be : 
>Définit la valeur d'un en-tête de requête HTTP. Cette méthode doit être appelée **après** open() mais **avant** send().

The [doc for setRequestHeader](https://developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest/setRequestHeader) describe it well:
>Vous devez appeler la méthode setRequestHeader(), **après la méthode open()**, et **avant send()**.

**Comment by SphinxKnight** [comment]
Merci pour ce signalement :) 
Je voulais corriger mais ça a déjà été modifié  https://wiki.developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest$compare?locale=fr&to=1591207&from=1587997 :D

@Lyokolux: MDN est un wiki, n'hésitez pas à l'éditer afin de corriger ces erreurs !
