### ISSUE TITLE
Titles of "Index of standard pseudo-elements" elements say that documentation has not been written

### ISSUE THREAD

**Issue by midgleyc** [mdn/sprints#2409]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the [Web/CSS/Pseudo-elements](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements#Index_of_standard_pseudo-elements) page, the titles of "Index of standard pseudo-elements" elements say that documentation has not been written for ::after, ::before, ::first-letter, ::first-line, ::part and ::slotted. On the left side-bar, under pseudo-elements, the titles of those elements are present.

Also, a question: is there a page which shows the elements together with their summaries, without having to hover over them? I find it useful as an overview.

**Comment by chrisdavidmills** [comment]
This is a bug, and I'm not sure if we'll get around to fixing it any time soon.

This page lists pseudo-classes and pseudo-elements along with their descriptions:

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements
