### ISSUE TITLE
Lint and scrape a JS built-in class

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#2410]
# User story
As a JS doc tech writer, I want to have JS docs migrated to markdown as fast as possible, so I can update documentation effectively after MDN docs have been dumped in raw HTML on a GitHub repo (project yari).

# Acceptance criteria

A JS built-in class (say BigInt) is linted and scraped successfully from the wiki into stumptown markdown and passes tests for surface structure. The content is fixed upstream in the wiki to allow scraping again at any time. Storing markdown now is not important, but being able to scrape, lint, and store structured markdown at any time going forward is important.

# Tasks

1. - [ ] Have content models/page structures for JS class, JS method, JS properties.
2. - [ ] Write a linter that checks if scraped wiki content aligns with content models
3. - [ ] Fix wiki content upstream if necessary 
4. - [ ] Successfully scrape a JS class (BigInt) that passes linting tests and that fits into stumptown markdown.

**Comment by Elchi3** [comment]
@wbamberg @ddbeck Does this story sound good to you?

**Comment by ddbeck** [comment]
This looks reasonable to me. I wrote #2411 to try to draw a line between what you're doing this sprint and my part of it.

**Comment by Elchi3** [comment]
Will has written a much more defined and useful epic that we will actually go forward with. That means that this story is now obsolete. Please see https://github.com/mdn/sprints/issues/2517 and sub tasks about how we will proceed.
