### ISSUE TITLE
CSS font-weight contradiction

### ISSUE THREAD

**Issue by acicali** [mdn/sprints#2413]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**Relevant documentation page:**
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

**Issue:**
This page states that the keyword values "_bolder_" and "_lighter_" for the CSS font-weight property are "_One font weight heavier than the parent element_" and "_One font weight lighter than the parent element_" respectively. These statements disagree with the table on the same page labelled "_Meaning of relative weights_".

**Further confusion:**
The spec ([https://www.w3.org/TR/css-fonts-3/#bolder](https://www.w3.org/TR/css-fonts-3/#bolder)) shows the exact same tabular data as MDN, but states "_The table above is equivalent to selecting the next relative bolder or lighter face, given a font family containing normal and bold faces along with a thin and a heavy face. Authors who desire finer control over the exact weight values used for a given element may use numerical values instead of relative weights._". This *seems* to agree with the statements on MDN regarding "one font weight heavier / lighter", although somewhat more ambiguously.

**Testing:**
The latest Google Chrome follows the behaviors described in the table. Including all 9 weights of Roboto from Google Web Fonts and setting the body element's font-weight (with one child set to "bolder" and one to "lighter" confirms the tabular data to be accurate.

**Comment by chrisdavidmills** [comment]
This is a bit confusingly-stated, but it makes sense to me. I think the key point here is the quote form the spec — "given a font family containing normal and bold faces along with a thin and a heavy face".

So basically when using relative weights, only 4 absolute font weights are considered, and moved between. I've tried updating the page to make this clear:

* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Values
* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Meaning_of_relative_weights

Does this work for you?

**Comment by acicali** [comment]
Yes... this is perfect. Thank you!

**Comment by chrisdavidmills** [comment]
Super, glad that worked. Another issue closed ;-)
