### ISSUE TITLE
/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/sprints#2414]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x ] Correction or update

# Details

At least two CodePens for the examples don't work.  The code in the pen is incomplete.

**Comment by chrisdavidmills** [comment]
I've tested these in both Fx and Chrome, and they all seem to work fine to me. What browser/OS combination are you using?

**Comment by Leokuma** [comment]
@chrisdavidmills All the examples work under the wiki URL, but not all of them work under the "visitor" URL.

This is probably related: #2376.

**Comment by chrisdavidmills** [comment]
I've tried implementing the same fix; just waiting for the live page to update...
