### ISSUE TITLE
https://wiki.developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/offsetParent$history

### ISSUE THREAD

**Issue by hehos** [mdn/sprints#2415]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details
HTMLElement.offsetParent 是一个只读属性，返回一个指向最近的（closest，指包含层级上的最近）包含该元素的定位元素。如果没有定位的元素，则 offsetParent 为最近的 table, td, th或body元素。

上面这段话表述有误或者不准确。
其中部分应该改为：包含该元素的定位元素 改为 包含该元素的定位元素或者table, td, th或body元素。

运行示例：https://codepen.io/hehos/pen/xxxQxOX

**Comment by hehos** [comment]
> I recently did some testing and updated the English version of the page to be more accurate. Since I don't write chinese, can you make an update to the page?

I have changed it. I have a worry. Does this document need to be reviewed?

**Comment by chrisdavidmills** [comment]
We don't normally review changes to translations because we have no-one who can review them. If you could find someone to review your change, then that would be great. I'm sorry we can't help you more.
