### ISSUE TITLE
https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Guide/M%C3%A9taprogrammation$history

### ISSUE THREAD

**Issue by SerkiWeb** [mdn/sprints#2416]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
on this url [https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/M%C3%A9taprogrammation#R.C3.A9flexion](url) On french Métaprogrammation page, at the bottom (Reflexion part) maybe a mistake  it should be "un constructeur" and not "une constructeur".
![image](https://user-images.githubusercontent.com/9366790/68974983-5b17fc00-07f2-11ea-810f-40839f1baa8c.png)

**Comment by SphinxKnight** [comment]
Fixed w/ https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Guide/M%C3%A9taprogrammation$compare?locale=fr&to=1590807&from=1567965
Thanks @chrisdavidmills :)

@SerkiWeb thanks for reporting this! If you encounter such typos again, please know that you can edit MDN :) it's a wiki and there is no need of any approval before editing a page so feel free to fix :) If you need help or a discussion, open an issue like you did.
