### ISSUE TITLE
/ru/docs/Web/JavaScript/Reference/Operators/new

### ISSUE THREAD

**Issue by Selicium** [mdn/sprints#2417]
# Request type

- [x ] Correction or update

Вместо строковых или численных значений можно передать **обект** как параметр. Чтобы узнать имя владельца car2, получим доступ к свойству:

# Details

**Comment by chrisdavidmills** [comment]
Feel free to fix this yourself; there is noone on the team who knows Russian, so we can't really make the fix. Thanks!
