### ISSUE TITLE
Correct bookmarks.search() re multiple-word phrases

### ISSUE THREAD

**Issue by rebloor** [mdn/sprints#2418]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
See [browser.bookmarks.search fails to support quoted search tokens](https://bugzilla.mozilla.org/show_bug.cgi?id=1595081): It's The documentation says that bookmarks.search() supports multiword phrases surrounded by quotes, however, this appears not to work.

**Comment by rebloor** [comment]
@chrisdavidmills in a case like this, would we open an issue ticket here?

**Comment by chrisdavidmills** [comment]
Yup, that's perfect; I've just added the correct labels and status. You cna then deal with this next sprint, or later in the P1/P2 bugs cycle.

**Comment by rebloor** [comment]
As I was being pinged for needinfo on the ticket I have updated the MDN page. Now waiting for Shane C to confirm that this is complete.

**Comment by rebloor** [comment]
Documentation updated and reviewed by Shane C.
