### ISSUE TITLE
Incorrect information on JavaScript building blocks tutorial?  

### ISSUE THREAD

**Issue by msalzr91** [mdn/sprints#2419]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [X] Correction or update

Hello,  I copy/pasted the code from at least 2 examples in the JavaScript tutorial that used document.QuerySelector to link the <script> to the HTML but each time didn't work offsite, ie my Chrome browser saved locally.  When I FINALLY changed to document.getElementById( ) the Javascript did begin to work.  I'm new, please excuse me, but does document.querySelector work?   My concern is that incorrect information is on the tutorial.

**Comment by Leokuma** [comment]
What page and examples are you talking about specifically?

**Comment by chrisdavidmills** [comment]
@msalzr91 yeah, it definitely works — see here for browser compat data: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#Browser_compatibility

Give us an example of some code that doesn't appear to be working for you, and we'll help to debug it. It's probably something quite simple, but when you are just starting out it is easy to go wrong.

No worries though; happy to help you!

**Comment by msalzr91** [comment]
Thanks, Chris.
