### ISSUE TITLE
Update web extensions menu to use external links for pages moved to Extension Workshop

### ISSUE THREAD

**Issue by rebloor** [mdn/sprints#2420]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

Pages moved to the Extension Workshop are present in the Web Extension section menu.  Pages have been redirected but the menu items point to the original MDN location. This means there is no indication that the user is about to leave MDN when they select the menu item.

Update the menu to link those items pointing to material on the Extension Workshop using external URLs, which will mark them with an external link indicator.

**Comment by Elchi3** [comment]
@rebloor has this happened? Is it still a valid task?

**Comment by Elchi3** [comment]
It seems https://github.com/mdn/sprints/issues/3272 is related to this?

**Comment by rebloor** [comment]
@Elchi3 This is underway, I have revised menus ready to submit but I'm waiting to see if there's an easy way to update multiple pages.

**Comment by rebloor** [comment]
@Elchi3 this will not help https://github.com/mdn/sprints/issues/3272 as the issue there is that we don't have translated pages on extension workshop to link to. I'll mention this to Caitlin.
