### ISSUE TITLE
Element header doesn't seem correct.

### ISSUE THREAD

**Issue by Kaiido** [mdn/sprints#2424]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [Element page](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element) states in the header 

> `Element` is the most general base class from which all objects in a `Document` inherit.

I'm not really sure how to understand this, but for me this seems completely wrong.  
Maybe the author was thinking about `Node`?  But then, `Document` inheriting itself from `Node` that wouldn't make too much sense either to say this...  

I think a complete rephrase is needed, though I fail to find the proper one.

**Comment by chrisdavidmills** [comment]
I think you've got a point here. 

If you look at the specs, `Element` inherits from `Node`, and everything else inherits from `Node`. FRom the spec:

> Node is an abstract interface and does not exist as node. It is used by all nodes (Document, DocumentType, DocumentFragment, Element, Text, ProcessingInstruction, and Comment). 

So I think they oare on about element objects, not all objects. I've updated the description to reflect this — do you think it is better now?

**Comment by Kaiido** [comment]
Yes thanks.
