### ISSUE TITLE
HTMLDataListElement.add()?

### ISSUE THREAD

**Issue by ParkhomenkoDmitry** [mdn/sprints#2426]

**Comment by atopal** [comment]
@chrisdavidmills can you take a look?

**Comment by chrisdavidmills** [comment]
@ParkhomenkoDmitry I can't see any evidence of an `add()` method existing on the `HTMLDataListElement` interface. It is not mentioned on MDN, or in the HTML spec. Where did you see this?

**Comment by ParkhomenkoDmitry** [comment]
I ment the method add() exists in HTMLSelectElement, so it’s a little bit strange it is absent in similar element

  
>Вторник, 19 ноября 2019, 16:05 +03:00 от Chris Mills <notifications@github.com>:
> 
>@ParkhomenkoDmitry I can't see any evidence of an add() method existing on the HTMLDataListElement interface. It is not mentioned on MDN, or in the HTML spec. Where did you see this?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Пархоменко Дмитрий

**Comment by chrisdavidmills** [comment]
@ParkhomenkoDmitry ah, I see what you mean now. I think you've got a point — it would make sense to have this method available there too.

Maybe you could [file an issue](https://github.com/whatwg/html/issues) against the [HTML spec](https://html.spec.whatwg.org/) to ask if it can be added?
