### ISSUE TITLE
Q3 S1 Fx62 DOM DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#243]
## Acceptance criteria

1. - [x] All required documentation changes done
2. - [x] Reviews requested from engineers.

## Chris

1.  - [x] [registerProtocolHandler require SecureContext in stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1460506): 0.25 points
2.  - [x] [Allow setting KeyframeEffect.target](https://bugzilla.mozilla.org/show_bug.cgi?id=1067769): 0.5 points.
3.  - [x] [Disable registerContentHandler() in stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1460481): 0.25 points
4.  - [x] [Disable devicelight, deviceproximity and userproximity events from stable](https://bugzilla.mozilla.org/show_bug.cgi?id=1462308): 0.25 points
5.  - [x] [convert inIDOMUtils to Web IDL](https://bugzilla.mozilla.org/show_bug.cgi?id=1427419): 1 point. This is an internals thing, so not really our remit. I've asked in the bug how much it involves as I don't really understand it

## Florian

1.  - [x] [Remove *ReadOnly and AnimationEffectTiming animation interfaces](https://bugzilla.mozilla.org/show_bug.cgi?id=1456394): 2 points
2.  - [x] [Implement the Navigation Timing 2 spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1043083): 1 point. Looks like we documented most of this already, but we ought to check that we got it right.
3.  - [x] [deprecating the "referrer" directive in CSP](https://bugzilla.mozilla.org/show_bug.cgi?id=1302449): 0.25 points, mostly done, but needs some checking and BCD data updates. BCD PR is already in.

## Irene

1.  - [x] [unresponsive visiting login page on eqbank.ca](https://bugzilla.mozilla.org/show_bug.cgi?id=1460295): 0.25 points.
2.  - [x] [enable Shadow DOM in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1460069): 0.25 points
3.  - [x] [Implement the DataTransfer constructor](https://bugzilla.mozilla.org/show_bug.cgi?id=1351193): 0.25 points
4.  - [x] [Should we stop returning null from document.domain?](https://bugzilla.mozilla.org/show_bug.cgi?id=819475): 0.25 points
5.  - [x] [document.domain throws wrong exception](https://bugzilla.mozilla.org/show_bug.cgi?id=1457689): 0.25 points
6.  - [x] [Enable W3C Pointer Events and touch-action CSS property by default](https://bugzilla.mozilla.org/show_bug.cgi?id=960316): 0.5 points — LOOKS LIKE THIS IS ALREADY DONE, SO HAVE REMOVED DDN FROM THE BUG

## Sheppy

1.  - [x] [Remove DOMPoint{,ReadOnly}(DOMPointInit) constructor, implement DOMPoint{,ReadOnly}.fromPoint](https://bugzilla.mozilla.org/show_bug.cgi?id=1186265): 2 points

**Comment by a2sheppy** [comment]
For DOMPoint/DOMPointReadOnly:

- [x] Update DOMPointReadOnly overview
- [ ] Document DOMPointReadOnly()
- [ ] Document DOMPointReadOnly.fromPoint()
- [ ] Update DOMPoint overview
- [ ] Update DOMPoint()
- [ ] Remove “Experimental” tag and {{SeeCompatTable}} from all pages

**Comment by a2sheppy** [comment]
Chris — I think the inlDOMUtils stuff goes to Irene; this is all stuff being moved from XPIDL into WebIDL but it’s all still chrome-only stuf for use by the dev tools UI implementation, really.

**Comment by Elchi3** [comment]
For "Implement the Navigation Timing 2 spec" I have analyzed the state of the docs here: https://bugzilla.mozilla.org/show_bug.cgi?id=1043083#c6 and filed a bug for the remaining doc work: https://bugzilla.mozilla.org/show_bug.cgi?id=1476558
