### ISSUE TITLE
Design: Landing page with FAQ

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2432]
Recreating https://github.com/mdn/browser-compat-data/issues/5164 which was created in the wrong repo

Mock-ups:
- [InVision prototype](https://mozilla.invisionapp.com/share/8RUYG0UX29D#/screens/394630897)

Acceptance criteria:
- [x] Developer sign-off: "all required information for engineering to implement solution are documented"
- [x] Kadir sign-off: "all business and user needs have been considered"
- [x] Legal sign-off: "all required legal information is included"
- [x] User tested: "simple user-tests have been conducted to ensure users will be able to navigate"
- [x] Mock-ups are uploaded on Abstract: "all necessary mock-ups and assets are uploaded"

**Comment by jmswisher** [comment]
@atopal @malqinneh This is marked as done in the spreadsheet. Are the first 2 AC satisfied?

**Comment by atopal** [comment]
Good to go on my end
