### ISSUE TITLE
Design: Thank you/confirmation page

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2433]
Recreating https://github.com/mdn/browser-compat-data/issues/5165 which was created in the wrong repo

Mock-ups:
- [Dedicated page (if you subscribe from the FAQ page)](https://mozilla.invisionapp.com/share/8RUYG0UX29D#/screens/394630899)
- [Modal (if you subscribe from the banner CTA)](https://mozilla.invisionapp.com/share/8RUYG0UX29D#/screens/394630418)

Acceptance criteria:
- [x] Developer sign-off: "all required information for engineering to implement solution are documented"
- [x] Kadir sign-off: "all business and user needs have been considered"
- [x] Legal sign-off: "all required legal information is included"
- [x] User tested: "simple user-tests have been conducted to ensure users will be able to navigate"
- [x] Mock-ups are uploaded on Abstract: "all necessary mock-ups and assets are uploaded"

**Comment by jmswisher** [comment]
@atopal @malqinneh This is marked as done in the spreadsheet. Are the first 2 AC satisfied?

**Comment by atopal** [comment]
Done on my end.
