### ISSUE TITLE
Design: Receipt Email

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2434]
Recreating https://github.com/mdn/browser-compat-data/issues/5166 which was created in the wrong repo

Acceptance criterion:
(Legal obligation to inform users in an email)
- [x] Receipt
- [x] Cancellation policy
- [x] How to cancel

[Stripe's pre-built receipt](https://stripe.com/docs/terminal/checkout/receipts#pre-built) is a good option to launch with.
- [x] Engineering: look into customizing the content section from "If you have any question..." to "Cancel any time. To cancel your subscription, please [contact support]. If you have questions, please read the [FAQ] or you can also contact support."
![terminal-pre-built-receipt.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/0d9e1ca4-f111-43aa-aa4e-f6785f3a4a9a)

**Comment by malqinneh** [comment]
@atopal updated the issue description. Let me know if we can make any improvements to the email receipt copy.

**Comment by malqinneh** [comment]
@escattone took a look at this, will need to ping @tobinmori when he's back next week since we need a Stripe account to confirm if content us customizable.

**Comment by tobinmori** [comment]
Looks very do-able @malqinneh.

For tech reference (when we create a user story for this):
https://stripe.com/docs/recipes/sending-custom-email-receipts
