### ISSUE TITLE
Invalid Russian translation /ru/docs/Web/HTTP/Заголовки/If-Modified-Since

### ISSUE THREAD

**Issue by vladogol** [mdn/sprints#2438]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The phrase
> When used in combination with If-None-Match, it is ignored, unless the server doesn't support If-None-Match.

is translated into Russian as

> При использовании в сочетании с If-None-Match заголовок If-Modified-Since игнорируется, если сервер не поддерживает If-None-Match.

which is incorrect and has the opposite meaning of what is written in English.
Suggested translation is
> При использовании в сочетании с If-None-Match заголовок If-Modified-Since игнорируется, ~если~ **кроме тех случаев, когда** сервер не поддерживает If-None-Match.

**Comment by chrisdavidmills** [comment]
@vladogol thanks for reporting this. Are you able and willing to log into MDN and fix Russian language issues yourself?

We don't have any dedicated Russian team members to handle such work, and I would happy if you just fixed such problems, rather than needing to report them here.

**Comment by chrisdavidmills** [comment]
I've made the update
