### ISSUE TITLE
/fr/docs/Web/HTTP/CSP

### ISSUE THREAD

**Issue by AO-LocLab** [mdn/sprints#2439]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The French translation of the Content Security Policy on MDN web docs needs to be properly reviewed. It contains a lot anglicisms, untranslated English terms, typographical errors, an is not always faithful to the English text.

**Comment by SphinxKnight** [comment]
@chrisdavidmills thanks for the heads up :)
@AO-Loclab this page needed some fixes but it did not contain a lot of anglicism. Could you please describe the terms and errors if you report them?
I did a rewrite of some parts of the page and it looks OK to me. I used Grammalecte to check for errors too.

Also, please note that MDN is open for everyone to contribute and fix typos/errors so feel free to improve/fix any content! If you have questions or need help doing so, please do not hesitate to reach out.
