### ISSUE TITLE
Q3 S1 Fx62 JavaScript DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#244]
## Acceptance criteria

- [x] Appropriate changes made to fix all DDNs
- [x] Reviews requested from engineers

## The DDNs

1.  - [x] [Implement import.meta](https://bugzilla.mozilla.org/show_bug.cgi?id=1427610) 0.5 points
2.  - [ ] [Enable WebAssembly.Global by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1464656) 0.25 points ---> Chris ; BEING MOVED TO ITS OWN USER STORY AS THE WORK IS GREATER THAN EXPECTED
3.  - [x] [Implement JSON superset proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1435828) 0.25 points
4.  - [x] [Enable Array.prototype.flat (was flatten) and Array.prototype.flatMap in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1435813) 0.25 points
5.  - [x] [Object.defineProperty needs to be able to return false in some cases](https://bugzilla.mozilla.org/show_bug.cgi?id=1329321) 0.25 points
6.  - [x] [WebGL - implement powerPreference](https://bugzilla.mozilla.org/show_bug.cgi?id=1349799) 0.25 points
7.  - [x] [[[DefineOwnProperty]] and [[Set]] don't fail for TypeArrays](https://bugzilla.mozilla.org/show_bug.cgi?id=1308735) 0.25 points

**Comment by Elchi3** [comment]
@chrisdavidmills 
This got all done, except Wasm.Global. I've done preparation work for that one, though: 
https://github.com/mdn/browser-compat-data/pull/2402
https://github.com/mdn/kumascript/pull/743
