### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/places.sqlite_Database_Troubleshooting

### ISSUE THREAD

**Issue by KWierso** [mdn/sprints#2440]
# missing linked content

- [x] Correction or update

# Details
The Places Maintenance extension linked [here](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/places.sqlite_Database_Troubleshooting) has been removed from AMO,as far as I can tell.

**Comment by chrisdavidmills** [comment]
Yeah, looks like it. I've deleted that section.
