### ISSUE TITLE
Update slug of article https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/webauthn

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#2441]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Feature Policy directive `webauthn` was renamed to `publickey-credentials` before it was implemented by any browser. Unfortunately, MDN article uses the old name and therefore should be moved.

Original URL:
https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/webauthn
Desired URL:
https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/publickey-credentials

I will update the article itself, but I can not move it to a new address.

At the time of writing, the article does not have any translations, but please check it is still the case when you move it.

## Sources
 - [Web Authentication API Feature Policy integration](https://w3c.github.io/webauthn/#sctn-feature-policy)
 - [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=993007)
 - [List of standard features](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md#standardized-features) with `publickey-credentials` identifier

**Comment by chrisdavidmills** [comment]
Thanks for your work on this @bershanskiy !

I have moved the page as requested; remember to also update the parent page to point to the correct subpage.

**Comment by bershanskiy** [comment]
@chrisdavidmills Thanks for the prompt fix!

I already updated all the other stuff on MDN (page title, content, and parent's link) and will force-refresh other pages to ensure the sidebar has the right name. The only thing left is the BCD entry, which has it's own issue, so I'm closing this issue as resolved.

**Comment by chrisdavidmills** [comment]
Sounds perfect. Thanks again!
