### ISSUE TITLE
/en-US/docs/Tools/Performance/Waterfall

### ISSUE THREAD

**Issue by himanshugarg** [mdn/sprints#2442]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Possible Typo in "A string the indicating the reason GC was performed"
Should be "A string indicating the reason GC was performed"

![image](https://user-images.githubusercontent.com/2392803/69388557-338fca80-0cef-11ea-904a-5a0a0c5197c4.png)

**Comment by bershanskiy** [comment]
@himanshugarg I fixed it.

**Comment by chrisdavidmills** [comment]
@bershanskiy thanks! Closing.
