### ISSUE TITLE
NSS 3.37.3 release notes are missing

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2443]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL : https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Releases

for some reason NSS 3.37.3 release notes are missing

**Comment by chrisdavidmills** [comment]
I don't think this is a big deal; also, this is not web platform docs, so our team wouldn't make this a priority. I'm gonna close this.
