### ISSUE TITLE
french language mistakes

### ISSUE THREAD

**Issue by RolandGautier** [mdn/sprints#2444]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

first sentence :

> L'interface HTMLDivElement **fourni** des propriétés particulières (au-delà **du** l'interface régulière HTMLElement **d'ont-il** hérite) pour manipuler des éléments div.

 3 mistakes corrected in french language :

> L'interface HTMLDivElement fournit des propriétés particulières (au-delà de l'interface régulière HTMLElement dont il hérite) pour manipuler des éléments div.

**Comment by SphinxKnight** [comment]
@RolandGautier merci d'avoir rapporté ces erreurs. La page nécessitait une bonne mise à jour, que je viens d'appliquer.
N'hésitez pas à rouvrir cette _issue_ s'il restait des coquilles. Sinon, vous pouvez aussi contribuer en éditant la page pour corriger ce qui ne va pas : MDN est un wiki que tout le monde peut éditer :) 

N.B. Attention à laisser l'URL dans le nom ou dans le corps de l'_issue_. J'ai pu deviner la page grâce aux paragraphes mais ce n'était pas gagné.

Encore merci !
(Thanks @chrisdavidmills :))

**Comment by RolandGautier** [comment]
Hello Chris,

Vu la qualité du français que tu pratiques (so far away my englilsh 
language), je continue en français ;-).

Suite à ta réponse circonstancié, je me suis ( petitement) lancé dans la 
traduction de page 
(https://wiki.developer.mozilla.org/fr/docs/Web/API/DocumentOrShadowRoot/elementsFromPoint), 
histoire de participer à mon niveau.
Je tombe sur une colle :
Cette page en anglais 
https://wiki.developer.mozilla.org/en-US/docs/Web/API/ShadowRoot mise à 
jour le 23 avril 2019, ras,

traduite en français 
https://wiki.developer.mozilla.org/fr/docs/Web/API/ShadowRoot 
<https://wiki.developer.mozilla.org/fr/docs/Web/API/ShadowRoot>mise à 
jour le 23 mars 2019, ou est annoncé la disparition prochaine de 
ShadowRoot......:'(

Ce qui m'ennuierait vraiment, vu le nombre de webcompornents que je suis 
en train de mettre en oeuvre !

Ais-je loupé quelque chose ?

Comment vérifier la véracité des éléments contenus dans une page enn 
français très différente de son origine anglophone ?

Merci par avance de ton retour


Roland Gautier

RolandGautier dans MDN.

**Comment by chrisdavidmills** [comment]
Mon Francais c'est terrible ;-)

@SphinxKnight , can you help me to translate? thanks!

**Comment by SphinxKnight** [comment]
Bonjour @RolandGautier, (moi c'est Julien, @chrisdavidmills ne parle que peu français à ma connaissance).

Pour commencer, je réponds à la dernière question : MDN est un wiki et l'équipe employée qui maintient le cœur de la documentation le fait en anglais (/en-US/). Dans le doute sur la version fr, c'est donc la version en-US qui fait foi.
La version fr est purement le fruit des contributeurs et il peut y avoir des fautes ou des pages abandonnées malheureusement. (la version en-US n'est pas exempte de tels défauts mais ils sont moins marqués).

Pour le cas que tu mentionnes (la page sur l'API `ShadowRoot`, le dernier édit en français date de 2016 où la techno était sans doute encore expérimentale. Vu qu'il n'y a pas eu de mise à jour depuis, c'est du contenu incorrect sur le fond.

Pour les pages que tu détectes ainsi, plusieurs solutions : 
* ouvrir une issue comme tu l'as fait ici
* et/ou ajouter un commentaire en français sur la page comme quoi mieux vaut aller voir la page en-US (c'est un peu bête comme méthode de contournement mais en attendant, ça évite la confusion à d'autres)
* __si tu as le temps et l'envie__ : améliorer (voire retraduire) la page fr pour les futurs visiteurs

Enfin, et j'aurais dû commencer par là : merci beaucoup pour tes contributions :) je vais relire et peut être ajouté quelques édits pour homogénéiser :)

**Comment by SphinxKnight** [comment]
@chrisdavidmills just questions about how come that the French content is sometimes out of date/misleading.
I just cried a little inside and replied about how to help :)

**Comment by SphinxKnight** [comment]
@RolandGautier Je reprends la page de ShadowRoot pour la remettre à jour

**Comment by chrisdavidmills** [comment]
> I just cried a little inside and replied about how to help :)

Awwww! I just keep telling myself it's a Wiki ;-)

**Comment by RolandGautier** [comment]
Bonjour Julien,

Écœuré je suis !
Je viens de passer plus d'une heure à traduire la page 
https://developer.mozilla.org/fr/docs/Web/API/MutationObserver/MutationObserver 
et, arrivé à la fin, je voulais faire un copier coller d'un des tags et 
ai, par inadvertance, cliquer dessus.
J'ai tout perdu en me retrouvant sur la page originale.

Serait-il possible d'avoir un autosave permanent pendant la saisie des 
traductions ? Les liens de la version originale à gauche n'étant pas 
désactivés, le piège me semble permanent ...

Sinon existe-t-il une méthode de sauvegarde intermédiaire avant la 
publication ?

Merci par avance de ton retour.
Cordialement
Roland



Le 25/11/2019 à 12:21, SphinxKnight a écrit :
