### ISSUE TITLE
Question: What is Paid memberships?

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#2445]
If this is the wrong place for this posting, please direct me to the right one.

# User story
I saw a few issues labeled [Paid memberships](https://github.com/mdn/sprints/issues?utf8=%E2%9C%93&q=label%3A%22KR%3A+Paid+memberships%22+) and would like to learn more about the upcoming changes.

I'm all for MDN recovering the investments Mozilla made into it, but I worry improperly implemented paywalls might harm the community in the long term.

1. Was there a public announcement (e.g., email or a blog post)?
2. What is the extent of the membership? Will it be "pay what you want" donation (e.g., donate directly to MDN projects and not overall Mozilla Foundation)? Will some of the existing content be "paywalled"?
3. If content is paywalled, the long-term harm to MDN, community, and Firefox market-share might be greater than the short-term monetary gains.
   - If MDN is paywalled, will Google and Microsoft direct their developers to MDN or will they come up with their own solutions?
   - If MDN is paywalled, will average web developers even bother developing for Firefox compatibility? Currently, developer can view BCD tables and read through browser-agnostic examples; if MDN is paywalled, developers will consult Medium articles or blogs that don't get updated and frequently target only Chrome.

**Comment by chrisdavidmills** [comment]
At the moment, this is at the experimental stage, and we are going to proceed carefully to make sure we don't alienate our current user base.

It is my understanding that we are not going to do anything that affects our free offering — this is, content that is currently free won't suddenly be put behind a paywall or anything like that. We are have already experimented with a "pay what you want if you want to support MDN" type idea, and will be going further with this, but we also want to look at what other kinds of content or services might be attractive enough to people to become members of MDN for and/or pay for.

I'm not going to provide any more detail as I don't want to misrepresent the work here or its intentions.

But I will flag this thread to @atopal so he can think about what we should do in terms of communicating  our intentions here.

**Comment by atopal** [comment]
@bershanskiy Chris already outlined the core of the program. We has also talked about it publicly last year here: https://hacks.mozilla.org/2018/10/a-new-way-to-support-mdn/

**Comment by bershanskiy** [comment]
@atopal Thank you for the explanation.

Someone in the comments suggested micro-transaction platforms like Flattr. Do you plan to use them?

**Comment by atopal** [comment]
@bershanskiy We haven't made a decision for or against that yet, but we do want to leverage Mozilla's subscription services for this
