### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Statements/block

### ISSUE THREAD

**Issue by tombflylee** [mdn/sprints#2446]
# Request type
- [ ] Correction or update

# Details
I find this 👇in this article, and couldn't find any english version of it.

使用function
函数声明同样被限制在声明他的语句块内:
foo('outside');  // TypeError: foo is not a function
{
  function foo(location) {
   console.log('foo is called ' + location);
  }
  foo('inside'); // 正常工作并且打印 'foo is called inside' 
}

**Comment by chrisdavidmills** [comment]
The Chinese version could easily have got out of date with the English version, as we don't have any staff regularly updating the Chinese version. We rely on volunteers for localization work.

I'm not sure if there is much followup to do here, unless you are interested in updating the Chinese version in some way.
