### ISSUE TITLE
/zh-CN/docs/Web/HTTP/Access_control_CORS

### ISSUE THREAD

**Issue by Wana-Fly-Boy** [mdn/sprints#2447]
预检请求的案例中自定义字段Content-Type是application/xml，还是text/xml？内容表述有歧义。

**Comment by chrisdavidmills** [comment]
I think this bit on the English version answers your question:

https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

Looks like it is `application/xml`. Are you OK to update the Chinese version to make this clearer?

**Comment by Wana-Fly-Boy** [comment]
There is a problem with the preflight request example in the English version, the text and code section is "application / xml", and the picture is "text / xml".

**Comment by Wana-Fly-Boy** [comment]
The request header field of the code part is "Ping-Other", but the text part and the picture are "X-PINGOHTHER".

**Comment by Elchi3** [comment]
Duplicate of https://github.com/mdn/sprints/issues/2487
