### ISSUE TITLE
[CSS] Motion Path, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2451]
# Trello

https://trello.com/c/Ef3V38Yh/212-css-motion-path-fx-72

# Acceptance criteria

1. - [[motion-1] Ship motion-path](https://bugzilla.mozilla.org/show_bug.cgi?id=1582554) (see also [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/nOOIRsuxvuc))

**Comment by rachelandrew** [comment]
I think this is probably mostly BCD, and making sure the pages are correct.

**Comment by rachelandrew** [comment]
BCD https://github.com/mdn/browser-compat-data/pull/5328

Updated thse pages to remove the seecompattable macro.

Added to release notes.
