### ISSUE TITLE
[CSS] transforms, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2452]
# Trello

https://trello.com/c/9W1Z49lD/142-css-transforms-fx-72

# Acceptance criteria

1. - [x] [Enable "layout.css.individual-transform.enabled" by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1424900) (see also [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/4oyeCHOqt4I))
2. - [x] [[css-transforms] Have scale function and scale property accept percentage value](https://bugzilla.mozilla.org/show_bug.cgi?id=1597642)

**Comment by rachelandrew** [comment]
PR for compat data Individual Transforms: https://github.com/mdn/browser-compat-data/pull/5329

Added individual transforms to the release notes.

The PR for the update to the Transforms spec for the addition of percentage hasn't yet been merged, so it doesn't appear in the ED https://github.com/w3c/csswg-drafts/pull/4396

@chrisdavidmills are we happy to update syntax and so on before the change is appearing in a spec?

**Comment by chrisdavidmills** [comment]
@rachelandrew hrm, I think we'd probably better wait until it's in the spec. Any thoughts on how long this usually takes?

**Comment by rachelandrew** [comment]
@chrisdavidmills no idea, but it looks like the requested changes were made. I'll keep an eye on it, I know what needs to be done anyway once it is.

**Comment by chrisdavidmills** [comment]
OK, cool.

**Comment by chrisdavidmills** [comment]
@rachelandrew has the spec been updated yet to include the syntax change?

**Comment by rachelandrew** [comment]
@chrisdavidmills nope, I do keep checking it https://github.com/w3c/csswg-drafts/pull/4396

**Comment by chrisdavidmills** [comment]
@rachelandrew no worries, and thanks for checking!

**Comment by jmswisher** [comment]
Can this issue be closed?

**Comment by rachelandrew** [comment]
not really, as once the PR is merged I can do the work, maybe reassign it to this sprint and I'll continue keeping an eye on it.

**Comment by jmswisher** [comment]
OK, did that. Is the remaining estimate still 1 pt?

**Comment by rachelandrew** [comment]
I'd put it as .5 as I did part of this ticket earlier.
