### ISSUE TITLE
[CSS] proprietary CSS, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2453]
# Trello

https://trello.com/c/ylLyrwja/12-proprietary-webkit-moz-features-fx-72

# Acceptance criteria

1. - [ ] [Implement <stack> using CSS Grid and remove nsStackFrame](https://bugzilla.mozilla.org/show_bug.cgi?id=1576946) ([intent to unship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/zAAHQYDyuQw) is more useful)

**Comment by rachelandrew** [comment]
I'm not sure what we do here. Are we leaving these in the BCD table at this point?

**Comment by chrisdavidmills** [comment]
I'd say this just needs:

* marking of https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-stack-sizing with a deprecated notice
* Updating of the -moz-stack data at https://developer.mozilla.org/en-US/docs/Web/CSS/display to say it is completely removed in 72. We probably better keep it for now, until we make a decision about what else to do with it.

**Comment by rachelandrew** [comment]
Cool, just wanted to check I wasn't missing anything as I don't know much about these specific properties.

**Comment by rachelandrew** [comment]
It looks like this might be reverted, looking at the bug https://www.dropbox.com/sh/1sor2llz3wbaq67/AADCRI1R8Yscmg4Xegv91Z0Sa?dl=0  so I'll hold fire for now and check it in a few days.

**Comment by rachelandrew** [comment]
@chrisdavidmills this seems to have been reverted https://bugzilla.mozilla.org/show_bug.cgi?id=1576946#c33

**Comment by chrisdavidmills** [comment]
> this seems to have been reverted

Yup, looks like it. Let's close this for now in that case; nothing to do here.
