### ISSUE TITLE
[CSS] SVG CSS, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2454]
# Trello

https://trello.com/c/5JYSjHmH/241-css-svg-stuff-fx-72

# Acceptance criteria

1. - [ ] [Support the 'letter-spacing' and 'word-spacing' properties in SVG](https://bugzilla.mozilla.org/show_bug.cgi?id=371787)

**Comment by rachelandrew** [comment]
The compat data on the page for both of these is all unknown:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/word-spacing

However for SVG support under the CSS property letter-spacing it is completed

https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing

Not for word-spacing:

https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing

So some work I think in figuring out what gets documented where and fixing that.

**Comment by rachelandrew** [comment]
PR for data here: https://github.com/mdn/browser-compat-data/pull/5331

Added to release notes, and updated pages.
