### ISSUE TITLE
[JS], nullish coalescing operator, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2456]
# Trello

https://trello.com/c/vk722rBC/237-nullish-coalescing-operator-fx-72

# Acceptance criteria

1. - [ ] [Implement the Nullish Coalescing operator (??) proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1566141)

**Comment by Elchi3** [comment]
This is mostly done already thanks to @SphinxKnight 
I think we need to list the operator on 
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators
Then mention it in release notes
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72
and update BCD.

Julien, do you want to do that?

**Comment by Elchi3** [comment]
BCD: https://github.com/mdn/browser-compat-data/pull/5312

**Comment by Elchi3** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator 

This is now pending the BCD PR, but I feel like we can call this done. The PR will get merged and deployed soon, likely.

**Comment by SphinxKnight** [comment]
> 
> 
> This is mostly done already thanks to @SphinxKnight
> I think we need to list the operator on
> https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators
> Then mention it in release notes
> https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72
> and update BCD.
> 
> Julien, do you want to do that?

Sorry, I don't know how I come to have missed this that question/notification :s :/
