### ISSUE TITLE
[JS] Promises, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2457]
# Trello

https://trello.com/c/0SiTrQJ2/201-promise-related-bugs-fx-72

# Acceptance criteria

1. - [ ] [Implement the Promise.any proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1568903)

**Comment by Elchi3** [comment]
So, this is not shipping yet. See https://bugzilla.mozilla.org/show_bug.cgi?id=1599769.

We have a page already, though: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any

It also introduces a new error type, `AggregatError`, which we will have to document, too.

Given the spec isn't stable yet, I propose we wait until https://bugzilla.mozilla.org/show_bug.cgi?id=1599769 happens.
