### ISSUE TITLE
[JS] Strings, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2458]
# Trello

https://trello.com/c/66fGk6Xm/167-js-strings-fx-72

# Acceptance criteria

1. - [ ] [Implement the String.prototype.replaceAll proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1540021)

**Comment by Elchi3** [comment]
Nighty only for now. Not implemented in Chrome either. I propose we wait for it to be shipping somewhere.
