### ISSUE TITLE
[Web Security] HPKP, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2463]
# Trello

https://trello.com/c/PoSdJAUO/78-web-crypto-api-fx-72

# Acceptance criteria

1. - [ ] [consider removal of HTTP Public Key Pinning (HPKP)](https://bugzilla.mozilla.org/show_bug.cgi?id=1412438)

**Comment by wbamberg** [comment]
As far as I can tell the only update needed here is for Firefox compat, and @bershanskiy [already updated that](https://github.com/mdn/browser-compat-data/pull/5170), and it's showing up on the pages: https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#Browser_compatibility.

So thanks to @bershanskiy , I think this can be closed :).
