### ISSUE TITLE
[API] Notifications, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2464]
# Trello

https://trello.com/c/ivi4m7SR/179-notifications-api-fx-72

# Acceptance criteria

1. - [x] [Enable dom.webnotifications.requireuserinteraction on Release](https://bugzilla.mozilla.org/show_bug.cgi?id=1593644) (probably Fx72; see also the [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/Mezd5pLjnJU))
2. -  [x] Also need to fix [Notification API example doesn't work in Chromium in cross-origin iframe](https://github.com/mdn/sprints/issues/2243)
3. - [x] [Disallow notification permission requests from cross-origin iframes](https://bugzilla.mozilla.org/show_bug.cgi?id=1560741) (legacy item, Fx 70)

**Comment by Elchi3** [comment]
See also https://hacks.mozilla.org/2019/11/upcoming-notification-permission-changes-in-firefox-72/

**Comment by chrisdavidmills** [comment]
"notification/push user interaction required" docs done:
* Pages updated to add in information about it:
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notifications_API
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notification
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Push_API
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe 
* Example updated so that it gives an idea of how to use it in the new world: https://mdn.github.io/to-do-notifications/
* Notes added to compat data: https://github.com/mdn/browser-compat-data/pull/5316
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72#DOM

**Comment by chrisdavidmills** [comment]
"Cross-origin IFrame disallowed" bits documented:

Pages updated to mention this new behavior:
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notification
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission
  * https://wiki.developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#APIs
* New note added to compat data to cover Firefox
