### ISSUE TITLE
[HTTP] XCTO, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2467]
# Trello

https://trello.com/c/K25OXvQT/234-x-content-type-options-fx-72

# Acceptance criteria

1. - [x] [Disable Pref respect_document_nosniff for Firefox 71](https://bugzilla.mozilla.org/show_bug.cgi?id=1592651)
2. - [x] [Enable Content-Type Sniffing when no Type is provided and Xtco-Nosniff is set](https://bugzilla.mozilla.org/show_bug.cgi?id=1591932)

**Comment by Elchi3** [comment]
Added to: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72#Security
Updated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
