### ISSUE TITLE
[DevTools] Primary tool updates, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2468]
# Trello

https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-js-debugger-fx-72

# Acceptance criteria

1. - [x] [Add keyboard shortcut to save and load files from the console input](https://bugzilla.mozilla.org/show_bug.cgi?id=1592308)
2. - [x] [Captured stack trace doesn't show async separator anymore](https://bugzilla.mozilla.org/show_bug.cgi?id=1592969)
3. - [x] [Add color scheme simulation to the inspector](https://bugzilla.mozilla.org/show_bug.cgi?id=1550804)
4. - [x] [Add UI support for setting watchpoints](https://bugzilla.mozilla.org/show_bug.cgi?id=1574192)

**Comment by jmswisher** [comment]
- Keyboard shortcuts: Added to [Multi-line mode](https://wiki.developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter#Multi-line_mode) section.
- Async separator: Added subsection and screenshot for [Async stack traces](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Async_stack_frames)

**Comment by chrisdavidmills** [comment]
@jmswisher you need to remember to add notes about the new features to the relevant rel notes document, in this case https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72. Thanks!

**Comment by jmswisher** [comment]
- Add color scheme simulator to the inspector: Added info, screenshots and a new section to [Examine and edit CSS](https://wiki.developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS)

**Comment by jmswisher** [comment]
- Add UI support for setting watchpoints: Created how-to [Use watchpoints](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_watchpoints), cribbed liberally from Miriam's Hacks post.
