### ISSUE TITLE
[DevTools] Scratchpad, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2470]
# Trello

https://trello.com/c/vymVtGYd/238-scratchpad-related-tasks-fx-72

# Acceptance criteria

1. - [x] [Remove Scratchpad panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1519103)
2. - [x] [Add keyboard shortcut to save and load files from the console input](https://bugzilla.mozilla.org/show_bug.cgi?id=1592308)

**Comment by jmswisher** [comment]
Removed info about Scratchpad from:

- https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript
- https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Using_js-ctypes/Debugging_Tips
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction

**Comment by jmswisher** [comment]
Also removed from:
 - https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set'
- https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/NsITraceableChannel
- https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/JNI.jsm/Port_Java_code_to_JNI.jsm
- https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Examples/Using_COM_from_js-ctypes
- https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError 
- https://developer.mozilla.org/en-US/docs/Tools
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Shells
- https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Examples/Using_Objective-C_from_js-ctypes

Not sure whether to bother with pages that have code examples where the comments include return values with reference to Scratchpad. [This one, for example.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) On the one hand, they're now wrong; on the other hand, those comments are not essential to the content of the page, and fixing up all of them seems like it expands the scope of this issue significantly. Leaving them untouched for now.

Also ignoring anything under /Archive or in "Firefox X for developers"
