### ISSUE TITLE
[WebExt] Browser API, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2471]
# Trello

https://trello.com/c/LBJWI3hD/229-browser-api-enhancements-fx-72

# Acceptance criteria

1. - [x] [browser.bookmarks.search fails to support quoted search tokens](https://bugzilla.mozilla.org/show_bug.cgi?id=1595081)

**Comment by rebloor** [comment]
browser.bookmarks.search fails to support quoted search tokens: developer has reviewed the documentation update and approved
