### ISSUE TITLE
[WebExt] general, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2472]
# Trello

https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-72

# Acceptance criteria

1. - [x] [Expose ftp protocol enabled/disabled via browserSettings](https://bugzilla.mozilla.org/show_bug.cgi?id=1592687)
2. - [x] [Expose canonical URL in the captive portal API](https://bugzilla.mozilla.org/show_bug.cgi?id=1592932)
3. - [x] [Implement BrowserSetting.onChange](https://bugzilla.mozilla.org/show_bug.cgi?id=1410412)
4. - [ ] [thirdParty state in WebRequest and proxy onRequest details](https://bugzilla.mozilla.org/show_bug.cgi?id=1591900)

**Comment by rebloor** [comment]
Adding Implement BrowserSetting.onChange, 1410412

**Comment by chrisdavidmills** [comment]
Looks like this is in progress, so I've set it as such.

@rebloor , how close is this one to completion? I'm trying to get the Fx72 release finished off this week. It would be great if you got this finished off asap; please also make sure that any of the WebExt bugs in the Fx72 list have notes added to the Fx72 rel notes pages as required.

Thanks!

**Comment by chrisdavidmills** [comment]
@rebloor 

> please also make sure that any of the WebExt bugs in the Fx72 list have notes added to the Fx72 rel notes pages as required.

Don't worry about this bit; I've added the rel notes.

**Comment by rebloor** [comment]
@chrisdavidmills a pull request for the compatibility data is now awaiting @wbamberg 's review:  [For 1410412 Implement BrowserSetting.onChange #5437](https://github.com/mdn/browser-compat-data/pull/5437)

**Comment by rebloor** [comment]
@chrisdavidmills, @wbamberg has merged the PR for the BrowserSetting.onChange compatibility data update, this item is complete.

**Comment by rebloor** [comment]
All items complete

**Comment by rebloor** [comment]
For thirdParty state in WebRequest and proxy onRequest details: 

'thirdParty` is now documented on:
* [`proxy.RequestDetails`](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/RequestDetails).
* the `details` property of `callback` for all of the events in [`webRequest`](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest).

A pull request is pending for updates to the compatibility table data:  [5582](https://github.com/mdn/browser-compat-data/pull/5582)

Please let me know if any changes are needed.

**Comment by rebloor** [comment]
For thirdParty state in WebRequest and proxy onRequest details: Developer cleared the information age flag on the bug, now waiting for compatibility data to be merged

**Comment by jmswisher** [comment]
@rebloor @chrisdavidmills The [BCD PR](https://github.com/mdn/browser-compat-data/pull/5437) has been merged. Can the issue be closed?
