### ISSUE TITLE
[WebExt] page actions and user scripts, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2473]
# Trello

https://trello.com/c/vsKZdybA/115-page-actions-and-userscripts-fx-72

# Acceptance criteria

1. - [x]  [Support additional click events for browserAction and pageAction](https://bugzilla.mozilla.org/show_bug.cgi?id=1405031)

**Comment by rebloor** [comment]
Support additional click events for browserAction and pageAction: compatibility data has been merged and developer has review documentation update.
