### ISSUE TITLE
/en-US/docs/Web/HTTP/Cookies

### ISSUE THREAD

**Issue by david-nader** [mdn/sprints#2475]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under [Cookie prefixes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes), the description of `__Host` says:

> If a cookie name has this prefix, it will only be accepted in a Set-Cookie directive if it is marked Secure, does not include a Domain attribute and was sent from a secure origin. In this way, these cookies can be seen as "domain-locked".

It is missing that the cookie should also have the "Path" attribute set to "/".

**Comment by chrisdavidmills** [comment]
Added; let me know if you think the wording looks OK.

**Comment by david-nader** [comment]
I suggest the following to emphasize that the `Path` attribute is one of the conditions:

If a cookie name has this prefix, it will only be accepted in a `Set-Cookie`
directive if it is marked `Secure`, was sent from a secure origin, does _not_
include a `Domain` attribute, and has the `Path` attribute set to `/`. In
this way, these cookies can be seen as "domain-locked".

**Comment by chrisdavidmills** [comment]
Sounds better to me; I've updated it as suggested.
