### ISSUE TITLE
The margin-trim property page needs completing

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2476]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

As part of my work figuring out what is and isn't experimental I found this page which needs a bit of work to add the relevant data. Adding this issue to go back and fix it up later.

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/margin-trim

**Comment by rachelandrew** [comment]
This was moved to Level 4 of the Box Model spec in the recent CSSWG meeting. That spec doesn't appear to exist yet so I think I need to wait until it does and then I'll do this work.

See: https://github.com/w3c/csswg-drafts/issues/4662#issuecomment-577648182

**Comment by chrisdavidmills** [comment]
Closing this for now, as it isn't supported anywhere. We'll revisit when it starts to appear in browsers.
