### ISSUE TITLE
navigator.connection doesn't give Cellular or Wi-fi type.

### ISSUE THREAD

**Issue by jahnviss** [mdn/sprints#2479]
In javascript I am looking for network conenction type like :Cellular", "wifi", "ethernet" etc... and I found that navigator.connection.type gives such information. I checked in Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) . 

console.log(navigator.connection) gives output : 
NetworkInformation {
downlink: 8.15
effectiveType: "4g"
onchange: null
rtt: 100
saveData: false
}
I don't see Type property in the output ? How can I get network type like "Cellular","wifi","ethernet"etc...

**Comment by jahnviss** [comment]
Any update on this? why I am not getting Type in Windows chrome or Ubuntu 18.04 Chrome browsers?

**Comment by chrisdavidmills** [comment]
Reading the `NetworkInformation` object compat data, you'll see that the type property is only supported on Chromebook/Chrome OS: https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation#Browser_compatibility
