### ISSUE TITLE
Q3 S1 Fx62 DevTools DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#248]
## Acceptance criteria

- [x] Changes made to fix all DDNs
- [x] Reviews requested from engineers

## Chris

- [x] [Add support for same-site cookie attribute to "Cookies" side-panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1452715): 0.25 points
- [x] [Provide an easier way to close a split console](https://bugzilla.mozilla.org/show_bug.cgi?id=1444302): 0.25 points

## Irene

- [ ] <s>[Add toggle for --fullpage screenshots to Options Panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1282462)</s>: this is actually INVALID, so nothing to do here.
- [x] [Console API: Implement console.countReset()](https://bugzilla.mozilla.org/show_bug.cgi?id=1459279): 0.5 points
- [x] [Implement frontend for console.timeLog](https://bugzilla.mozilla.org/show_bug.cgi?id=1461001): 0.5 points
- [x] [Implement frontend for console.countReset()](https://bugzilla.mozilla.org/show_bug.cgi?id=1463525): 0 points, will probably be done as part of number 4.
- [x] [ability to dock firefox developer toolbar left, for large screen resolutions](https://bugzilla.mozilla.org/show_bug.cgi?id=1192642): 0.5 points
- [x] [Add support for container tabs to RDM](https://bugzilla.mozilla.org/show_bug.cgi?id=1306975); 0.25 points
- [x] [The buttons on the right of the DevTools tab bar are unclear](https://bugzilla.mozilla.org/show_bug.cgi?id=1444301): 0.25 points
- [x] [Always display the Frame picker button if the user is on the Options panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1456069): 0.25 points
- [x] [Top-Down Stack](https://bugzilla.mozilla.org/show_bug.cgi?id=1471167): 0.25 points
- [x] [Remove Firebug theme](https://bugzilla.mozilla.org/show_bug.cgi?id=1378108): 0.25 points
- [x] [Remove gcli UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1461970): 1 point
- [x] [Implement Console.timeLog(optional DOMString label = "default")](https://bugzilla.mozilla.org/show_bug.cgi?id=1458466): 0 points, will be done along with number 5.

**Comment by chrisdavidmills** [comment]
Reopening, as @irenesmith still has yet to finish commenting the bugs/dealing with followups/setting them bugs to dev-doc-domplete when ready.

**Comment by irenesmith** [comment]
All edits have been made, all updates added to release notes as needed, and all Buzilla issues have been marked as dev-docs-complete. Closing this issue.
