### ISSUE TITLE
Array.prototype.flat() 中文事例有个问题

### ISSUE THREAD

**Issue by zcdzfd797** [mdn/sprints#2480]
// 使用 reduce、concat 和递归展开无限多层嵌套的数组
var arr1 = [1,2,3,[1,2,3,4, [2,3,4]]];

function flatDeep(arr, d = 1) {
   return d > 0 ? arr.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatDeep(val, d - 1) : val), [])
                : arr.slice();
};

flattenDeep(arr1, Infinity);
// [1, 2, 3, 1, 2, 3, 4, 2, 3, 4]

// flattenDeep

**Comment by chrisdavidmills** [comment]
We don't have any Chinese team members, so it is hard to understand the problem. Can you fix this yourself, or offer some English explanation?
