### ISSUE TITLE
Create/Update Introduction to HTML assessments

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2481]
Create or update assessments for the [Introduction to HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML) module 

# Acceptance criteria

Create/update the following.

## New "test your skills" pages to create

1. - [x] Basic HTML page structure - head, p, headings, lists, emphasis and importance
2. - [x] Hyperlinks
3. - [x] Description lists, quotes, abbreviations, address, sub and sup
4. - [x] Page structure

## Existing assessments to update

For each one, we need to make sure the assessment instructions are updated to tell people to put their code in an online editor, and make sure the assessment is best practice and still current.

1. - [x] https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
2. - [x] https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Structuring_a_page_of_content

**Comment by chrisdavidmills** [comment]
New test your skills articles created:

* https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics (linked to from [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#Test_your_skills!)).
* https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Links (linked to from [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#Test_your_skills!)).
* https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text (linked to from [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting#Test_your_skills!)).
* I decided not to write an extra test your skills page to test HTML page structure, as we already test this appropriately in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Structuring_a_page_of_content. Instead, I've linked to this from [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#Test_your_skills!).

**Comment by chrisdavidmills** [comment]
@rachelandrew I've completed one of my bits of new assessment articles work. Thought you might be interested in seeing how I've done this, to make sure it measures up with your expectations.

**Comment by rachelandrew** [comment]
@chrisdavidmills this looks good - thanks for showing me, I'll make sure we try and keep them generally consistent as I go through the CSS ones.

**Comment by chrisdavidmills** [comment]
@rachelandrew cool!
