### ISSUE TITLE
 Create/Update HTML tables/HTML forms assessments

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2483]
Create or update assessments for the [HTML tables](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables) and [HTML forms](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms) modules 

# Acceptance criteria

Create/update the following.

## New "test your skills" pages to create

1. - [x] basic form - structure, text input, submit, textarea
2. - [x] radios and checkboxes
3. - [x] select and datalist
4. - [x] slider, progres, meter
5. - [x] Advanced widgets - date, time, number, search, file
6. - [x] validation
7. - [x] Form styling

## Existing assessments to update

For each one, we need to make sure the assessment instructions are updated to tell people to put their code in an online editor, and make sure the assessment is best practice and still current.

1. - [x] https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Structuring_planet_data

**Comment by PasinduDushan** [comment]
HERE IS MY BASIC HTML PROJECT
![Annotation 2019-11-26 165957](https://user-images.githubusercontent.com/57533877/69626219-36cbe300-106e-11ea-939c-b168c86bcf6f.jpg)

**Comment by chrisdavidmills** [comment]
Basic form structure skill test created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Form_structure, along with GitHub files.

Also linked from article: https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#Test_your_skills!

**Comment by chrisdavidmills** [comment]
Basic form control types skills tests created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Basic_controls

And linked to: https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls#Test_your_skills!

**Comment by chrisdavidmills** [comment]
HTML form control types skill tests created: https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types#Test_your_skills!

And linked to: https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types#Test_your_skills!

**Comment by chrisdavidmills** [comment]
Other form control types skill tests created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Other_controls

And linked to: https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#Test_your_skills!

**Comment by chrisdavidmills** [comment]
Form styling basics skill test created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Styling_basics

And linked to: https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms#Test_your_skills!

**Comment by chrisdavidmills** [comment]
Advanced form styling skills tests created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Advanced_styling

And linked to:

* https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling#Test_your_skills!

**Comment by chrisdavidmills** [comment]
Validation skill tests created: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Form_validation

And linked to: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#Test_your_skills!
