### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

### ISSUE THREAD

**Issue by smacpherson64** [mdn/sprints#2484]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Code example on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Using_style_and_unit has a typo (missing closing parenthesis):

```
console.log((16).toLocaleString('en-GB', {
    style: "unit",
    unit: "liter",
    unitDisplay: "long"
});
```

Should be:

```
console.log((16).toLocaleString('en-GB', {
    style: "unit",
    unit: "liter",
    unitDisplay: "long"
}));
```

**Comment by chrisdavidmills** [comment]
Looks like this has already been fixed; thanks for reporting this anyway!
