### ISSUE TITLE
Clarification of the this documentation

### ISSUE THREAD

**Issue by jasonsrogers** [mdn/sprints#2485]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the documentation for the `this -> The bind method`, following the flow of the page, it wasn't clear why the `o.f()` would return 37.

As I'm just brushing up, I know that in the context of the call of a method against an object, `this` will be the the object, but for a beginner, I don't think it wouldn't be clear at all.

It is actually covered further down `As an object method`

I think it would be worth an extra comment or rearranging the sections so that it is easier to follow as a beginner

Keep up the good work ;)

```
function f() {
  return this.a;
}

var g = f.bind({a: 'azerty'});
console.log(g()); // azerty

var h = g.bind({a: 'yoo'}); // bind only works once!
console.log(h()); // azerty

var o = {a: 37, f: f, g: g, h: h};
console.log(o.a, o.f(), o.g(), o.h()); // 37,37, azerty, azerty
```

**Comment by chrisdavidmills** [comment]
Relevant MDN doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
