### ISSUE TITLE
Offline service workers article: need to check code viability

### ISSUE THREAD

**Issue by jmorahan** [mdn/sprints#2486]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
This line in the "activate" example seems a bit odd:
`if(cacheName.indexOf(key) === -1) {`
Why not simply `if (key !== cacheName) {` ?

I suspect this was copied and modified from https://developers.google.com/web/fundamentals/primers/service-workers#update-a-service-worker which uses `indexOf` for a different, and clearly valid, reason. But in this case it doesn't seem to make sense?

**Comment by chrisdavidmills** [comment]
Article in question: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

**Comment by chrisdavidmills** [comment]
Having investigated this, yes, I thinkthis does make sense. I've updated the article!
