### ISSUE TITLE
/en-US/docs/Web/HTTP/CORS

### ISSUE THREAD

**Issue by Wana-Fly-Boy** [mdn/sprints#2487]
There is a problem with the [preflight request example](https://github.com/mdn/sprints/issues/2487#issue-528466092) in the English version, the text and code section is "application / xml", and the picture is "text / xml".

The request header field of the code part is "Ping-Other", but the text part and the picture are "X-PINGOHTHER".

**Comment by jmswisher** [comment]
Taking this, as it relates to the other work on security docs I'm doing.

**Comment by hamishwillee** [comment]
This appears to have been fixed:
-"... code part is "Ping-Other", but the text part and the picture are "X-PINGOHTHER"." - not present
- "text and code section is "application / xml", and the picture is "text / xml". - both picture and text now say "text /xml".

Thanks!
