### ISSUE TITLE
Q3 S1 Fx62 General DDNs 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#249]
## Acceptance criteria

- [x] Changes made to fix all DDNs
- [x] Reviews requested from engineers

## General DDNs

1.  - [x] [Implement Clear-Site-Data response header to reset origin storage](https://bugzilla.mozilla.org/show_bug.cgi?id=1268889): 0.5 points; new HTTP header

**Comment by Elchi3** [comment]
Wrote https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data and https://github.com/mdn/browser-compat-data/pull/2457. This is behind a pref though, so no Firefox 62 announcement. Added ddn to https://bugzilla.mozilla.org/show_bug.cgi?id=1470111.

**Comment by jmswisher** [comment]
@chrisdavidmills Can this be closed?

**Comment by chrisdavidmills** [comment]
Yes. Closing.
