### ISSUE TITLE
E - WebRTC: Long-term project to complete the documentation

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#25]
The documentation of WebRTC is incomplete. Both reference and guide/tutorial content is either missing or incomplete. This epic involves completing that work; see the user stories within for details.

**Comment by a2sheppy** [comment]
Notes from conversation with jib on IRC about priorities

* None of the transport stuff is really implemented in Firefox
* An example showing how to use WebRTC using transceivers would be helpful. jib wrote a blog post about this: https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/
* Stats would be useful. RTCStatsReport etc. But we don’t implement all of it yet. You can see what each browser implements here: https://webrtc-stats.callstats.io/verify

**Comment by jmswisher** [comment]
Does [RTCCertificate](https://bugzilla.mozilla.org/show_bug.cgi?id=1257999) need to be included in this Epic?

**Comment by jmswisher** [comment]
Also [removal of RTCIdentityEvent](https://bugzilla.mozilla.org/show_bug.cgi?id=1258400)?
