### ISSUE TITLE
Q3 S1 Fx62 Media DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#250]
**I’ve left the points below as determined before the sprint, but have subtracted 1 from the “Estimate” for the entire card because of the effect of the eventual realization these shouldn’t be documented yet.**

## Acceptance criteria

- [x] Changes made to fix all DDNs
- [ ] All changes reviewed by engineers

## Media DDNs

- [x] [Update AudioWorkletGlobalScope definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1460896) 0 points, done along with number 5.
- [x] [[MSE] Have appendBuffer and remove return a promise](https://bugzilla.mozilla.org/show_bug.cgi?id=1280613) 1 point
- [x] [Implement AudioParamMap definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1460907) 0.5 points
- [x] [Add AudioWorkletNode interface definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1458446) 1 point
- [x] [Implement AudioWorkletGlobalScope](https://bugzilla.mozilla.org/show_bug.cgi?id=1322858): 1 point.

**Comment by a2sheppy** [comment]
The AudioWorklet stuff is tricky. The API is fine, but our implementation is a little weird at the moment. We have modernized parts of it, while the actual audioWorklet attribute isn’t moving from Window to AudioContext until Firefox 63. So no demos out there currently work.

**Comment by a2sheppy** [comment]
Per discussion on Discourse, and the [AudioWorklet Doc Plan & Status](https://docs.google.com/document/d/1VJamuSBOlqGdBBcUGq06Ez34Rjf-k6M-05cDaGFhKPI/edit) document, we are putting work on this document on hold fo not to let the API stabilize a litle

I’ve added [bug 1473176](https://bugzilla.mozilla.org/show_bug.cgi?id=1473176) to Bugzilla to track documenting AudioWorklet, and have put notes on each of the bugs pointing to that, along with appropriate dependencies.

I am checking these off here, but leaving them dev-doc-needed on Bugzilla.

**Comment by chrisdavidmills** [comment]
The MSE bug has been completed, and the AudioWorklets stuff has all been added to sheppy's plan for put in the roadmap for future work by me.

I am therefore closing this card.
