### ISSUE TITLE
Firefox learn more links point to the wrong places to learn more about remote debugging

### ISSUE THREAD

**Issue by beshur** [mdn/sprints#2501]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The above mentioned page is missing, 404, while it is linked to from the mobile FF (the remote debugging over wi-fi Learn more link), and also it's still shows in internet search engines. 

I'm interested what's there.
Thanks.

**Comment by beshur** [comment]
Looks like there was an issue with this one before,  #1350

**Comment by chrisdavidmills** [comment]
For example: https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_over_Wifi is linked to from Android Fx "Learn more" link.

**Comment by chrisdavidmills** [comment]
I've also noticed that the "Troubleshoot" links on the about:debugging page of desktop Firefox go to the wrong places.

They should be linking to sections of https://developer.mozilla.org/en-US/docs/Tools/about:debugging, correct?

**Comment by chrisdavidmills** [comment]
@digitarald, have you already got this issue on the devtools team's radar?

**Comment by digitarald** [comment]
> mobile FF (the remote debugging over wi-fi Learn more link)

Can we add a redirect, as Fennec probably won't update those links for while?

> They should be linking to sections of https://developer.mozilla.org/en-US/docs/Tools/about:debugging, correct?

Could we add a redirect as well? I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1600980 to update them.

**Comment by chrisdavidmills** [comment]
OK, I have now redirected the three links mentioned here. I know the desktop ones are working correctly; are there any more pages that need redirecting on the Android interface?

**Comment by Elchi3** [comment]
Seems stalled. Closing.
