### ISSUE TITLE
/en-US/docs/Web/API/PaymentResponse/retry

### ISSUE THREAD

**Issue by ForTheJim** [mdn/sprints#2502]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

On this page, 
https://developer.mozilla.org/en-US/docs/Web/API/PaymentResponse/retry
it references a reply() method, think this is supposed to be retry() ?

**Comment by SphinxKnight** [comment]
@ForTheJim thanks for the report :) this was a typo indeed! I edited the page and fixed this.
As MDN is a wiki and the only prerequisite to edit a page being having a GitHub account, do not hesitate to fix such typos if you encounter any again/have time :) 
Feel free to open issues as well if you feel your changes need discussion :)
