### ISSUE TITLE
/de/docs/MDN/Feedback

### ISSUE THREAD

**Issue by carabas77** [mdn/sprints#2503]
# Request type

- [X ] Correction or update

# Details

There is a wrong German text at the following Page in German language: https://www.mozilla.org/de/firefox/privacy/products/

Below "Unsichtbar für die Top-Tracker" the following text "Das sind die vier häufigsten Kategorien von Trackern, die **nicht** nun nicht mehr verfolgen." probably should be "Das sind die vier häufigsten Kategorien von Trackern, die **dich** nun nicht mehr verfolgen."

**Comment by chrisdavidmills** [comment]
We have nothing to do with mozilla.org; this is for bugs associated with developer.mozilla.org.

A better place for this would be https://bugzilla.mozilla.org/enter_bug.cgi, under the mozilla.org product.
