### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Statements/export

### ISSUE THREAD

**Issue by vonPetrov** [mdn/sprints#2505]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Hi
In the section below, where one reads 'export (...) from (...)', it should (naturally) read 'import (...) from (...)'.

![exportArticle](https://user-images.githubusercontent.com/15346703/69893421-1b303900-1309-11ea-913c-27bcd4337436.png)

Regards

**Comment by SphinxKnight** [comment]
I think this is correct. The example illustrates reexporting with the following structure (please bear my ASCII-drawing skills):

* `childModule1.js`: exports `myFunction` and `myVariable
* `childModule2.js`: exports `myClass`
  * `parentModule.js` simply "aggregates" the exports from `childModule1.js` and `childModule2.js` using the `export ... from ...` syntax. Here, `parentModule.js` acts as a kind of "concentrator". Using `export foo from bar` is equivalent to `import foo from bar; export foo;`
    * top level module: imports all that have been aggregated by `parentModule.js` (not even "knowing" that those exports come from distinct modules`

I've added some code blocks in the article to explain the intent a bit better I hope .

@vonPetrov Do not hesitate to reopen this issue if I have not answered your concerns.

poking @Elchi3 for review.
N.B. [A nice article about this from Axel Rauschmayer](https://2ality.com/2014/09/es6-modules-final.html#re-exporting)

**Comment by Elchi3** [comment]
Yes. Thanks for adding the comment about re-exporting, Sphinx!

**Comment by vonPetrov** [comment]
Thanks for the reply and the explanation, @SphinxKnight! I didn't know about re-exports, really thought it had been a mistake that had slipped unnoticed :)
