### ISSUE TITLE
JS_SetGCParameter is repeated twice in same paragraph

### ISSUE THREAD

**Issue by leela52452** [mdn/sprints#2508]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL : https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell

function `JS_SetGCParameter` is repeated twice in same paragraph

**Comment by SphinxKnight** [comment]
This was most probably a typo and I think the original was to point to both the getter and setter. I fixed the typo in the text (replaced the first text to `JS_GetGCParameter`)
The link for both function is the same though as both are described on [a single page](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS_GetGCParameter).
