### ISSUE TITLE
/ko/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods

### ISSUE THREAD

**Issue by Hwan-Woong-Lee** [mdn/sprints#2509]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

when I visit [a page](https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods), I get a message saying that there is no translation page for me to read. even though I summit a translation for that page quite a long time age. at that time I got an error so that I file the issue to MDN for help, but I had no feedback or fix.

![image](https://user-images.githubusercontent.com/46808867/69908408-2334c980-142c-11ea-9544-06151991857b.png)

when I click the link which read like "Help us translate this article!" and select a language for translation, in my case for Korean, then I finally get a message that reads:

> "Internal Server Error
> 
> An unhandled error occurred in the application. The error has been logged and an administrator was notified. We apologize for the inconvenience!"

I hope you can fix this bug. for your information, you don't need to restore the page for me because I have the file of translation source so that you can safely remove that page for the reset. 

Thanks for helping me out in advance.

**Comment by SphinxKnight** [comment]
thanks for the report @Hwan-Woong-Lee, I'll look into it.
can you confirm you still have the content of the translated document and that I can delete broken pages (if and only if necessary)?

**Comment by SphinxKnight** [comment]
@Hwan-Woong-Lee I managed to delete the "localization" link between the broken children page and the English one but I was not able to change/remove the corresponding slug.

Thus: https://wiki.developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods is available now but https://wiki.developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/%EB%A0%88%EA%B1%B0%EC%8B%9C_%EC%A1%B0%ED%8C%90_%EB%A9%94%EC%84%9C%EB%93%9C still is locked (I don't know why)

@Hwan-Woong-Lee Can you confirm you can translate the page? If yes, I'll close this and I'll open a bug on [mdn/kuma](https://github.com/mdn/kuma)

Sorry for the inconvenience :s

**Comment by Hwan-Woong-Lee** [comment]
Thanks for helping me out. Translated files are kept securely in the form
of files with the original files Because I use a software called OmegaT to
translate, if the original file has not been changed, there is no reason to
translate it again.

2019년 12월 2일 (월) 오후 9:35, SphinxKnight <notifications@github.com>님이 작성:

**Comment by Hwan-Woong-Lee** [comment]
I uploaded the file with no problem. thanks a lot.

2019년 12월 2일 (월) 오후 9:35, SphinxKnight <notifications@github.com>님이 작성:
