### ISSUE TITLE
/en-US/docs/Web/API/Crypto/getRandomValues

### ISSUE THREAD

**Issue by somec** [mdn/sprints#2510]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example of secureMathRandom returns a value in the range 0–1 (inclusive of 0 AND 1).
The built in Math.random() returns a number in the range 0–1 (inclusive of 0, but NOT 1)

I suggest that the example:
```
function secureMathRandom() {
  // Divide a random UInt32 by the maximum value (2^32 -1) to get a result between 0 and 1
  return window.crypto.getRandomValues(new Uint32Array(1))[0] / 4294967295;
}
```
should be changed to:
```
function secureMathRandom() {
  // Divide a random UInt32 by the maximum value (2^32) to get a result between 0 and 1 (inclusive of 0, but not 1)
  return window.crypto.getRandomValues(new Uint32Array(1))[0] / 4294967296;
}
```

or that a note will be added that the secureMathRandom differs from the built in Math.random in this regard.

**Comment by mattborja** [comment]
FYI, this page has been updated ([see revision](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues$compare?locale=en-US&to=1593209&from=1592635))

**Comment by SphinxKnight** [comment]
Thanks for the edit it looks like it takes care of the suggested change.
