### ISSUE TITLE
/en-US/docs/Web/API/HTMLTableElement/tBodies

### ISSUE THREAD

**Issue by deant** [mdn/sprints#2514]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Your example code says:

This snippet gets the number of bodies in a table.
`length(mytable.tBodies);`

But I'm pretty sure there's no `length()` function; the code should actually read:
`mytable.tBodies.length;`

**Comment by wbamberg** [comment]
I think you are right; I've updated the page.

(this example appears to have survived for more than 15 years! https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/tBodies$revision/203211)

**Comment by SphinxKnight** [comment]
I think this can safely be closed :)
