### ISSUE TITLE
Firefox improvement 

### ISSUE THREAD

**Issue by schalykh** [mdn/sprints#2515]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I wanted to send you a feedback/suggestion to improve. I use Firefox on multiple computers (linux/windows based and Android phone) and sometimes I have to re-install it. I usually keep my settings the same across all the devices and would like my settings to be saved in my firefox account. the settings are: Search engine and notifications in general (I always disable them and don't like browser popping up 100 times a day and prompting me to enable). Buy this might be applied to any other settings that other users use and apply. I use DuckDuckGo Search engine and by default it comes up with Google and I have to make changes. Recently I've lost my cell phone and replaced it and I had to make all these changes and at work my laptop has been replaced and I had to do it over and over. This is annoying. Maybe you can enable feature/checkbox to sync settings across devices where user is signed in with Firefox account.

Thank you,

**Comment by chrisdavidmills** [comment]
This is a place to submit problems with MDN content, not Firefox. You could submit feedback at the general user feedback link: https://qsurvey.mozilla.com/s3/FirefoxInput/

Or another good place might be on the firefox-dev mailing list: https://groups.google.com/forum/#!forum/firefox-dev

**Comment by schalykh** [comment]
Chris,

Submitted it there. I was under impression that it was for Firefox. Sorry
for the confusion.

Thank you,
