### ISSUE TITLE
Browsing with older browser is not handled as described in datetime documentation

### ISSUE THREAD

**Issue by SatheesA** [mdn/sprints#2516]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
Under Handling browser support there are different scenarios where older browser that doesn't support it should be handled.. For example this referred example: https://codepen.io/pen/?&editable=true does not work in IE11 (11.1130.17134.0)

Edit: ehm the link to codepen didn't give link to a saved pen. I meant the example where you either get a native input or for older browsers get set of five <select> elements

**Comment by chrisdavidmills** [comment]
Argh, I fixed the demo in our demos repo, but then I thought someone else was going to fix the page, then they didn't.

I've had a go at fixing the code, and it should work now.
