### ISSUE TITLE
Lint a tree of pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2518]
https://github.com/mdn/sprints/issues/2411 provides the foundation for a linter that can check our Kuma content for certain features.

At the moment it only checks a single page at a time. We need it to be able to check "all pages under the given URL".

## Acceptance criteria
The linter can accept a URL, like https://developer.mozilla.org/en-US/docs/Web/JavaScript, and lint and report on all pages under that URL.

**Comment by ddbeck** [comment]
Is there a way to get an authoritative list of all the pages under a given MDN page?

**Comment by Elchi3** [comment]
Yes: https://developer.mozilla.org/en-US/docs/Web/JavaScript$children
See also https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Document_parameters

**Comment by ddbeck** [comment]
@Elchi3 perfect, thanks! This looks pretty doable (which I guess means I'm volunteering to do it).

**Comment by ddbeck** [comment]
This was resolved by https://github.com/mdn/stumptown-content/pull/259.
