### ISSUE TITLE
MDN Performance Improvements

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#252]
This Epic tracks the implementation of recommendations as a result of the MDN performance audit conducted by Tim Kadlec.

# Resources

* [MDN Key Performance Metrics and Goals](https://github.com/mdn/mdn-fiori/wiki)
* [KPI Dashboard](https://speedcurve.com/mozilla-add-ons/mdn/status/?share=71hfcbvl6zc1j8v1bojr5m6l28doql) on SpeedCurve
* [Bug 1503916](https://bugzilla.mozilla.org/show_bug.cgi?id=1503916) - Tracking bug, open blockers for individual tasks.

# Priorities

Priorities were assigned as follows:

user story | Priority (1-5) highest to lowest
-- | --
Consider removing some fonts/variations | 1
Add cross origin to resources | 1
Use the Font Loading API | 1
Subset the ZillaSlab and OpenSans fonts for different language support | 1
Create side bar based on HTML5 | 2
remove unused styles | 2
automated process for processing user generated content | 2
Inline dnthelper | 3
Inline the contents of locale-*.css | 3
increase cache load time for interactive examples | 4

**Comment by Elchi3** [comment]
Looks stalled. Closing
