### ISSUE TITLE
Update the CSS Building Blocks Assessments

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2529]
New assessments to create:

- [x] CSS Selectors: Type, class and ID selectors
- [x] CSS Selectors: Pseudo-classes and pseudo-elements
- [x] CSS Selectors: Combinators
- [x] The Box Model
- [x] Writing Modes
- [x] Overflow
- [x] Values and units
- [x] Sizing items in CSS
- [x] Images and Media
- [x] Styling tables

Existing assessments that can be updated:

- [x] https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#Active_learning_playing_with_the_cascade
- [x] https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors#Try_it_out
- [x] https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders#Playing_with_backgrounds_and_borders

**Comment by rachelandrew** [comment]
Ok, these are all done and linked up!

**Comment by chrisdavidmills** [comment]
These look good, so this can be closed.
