### ISSUE TITLE
Example on Atomics.store() page doesn't actually use Atomics.store()

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2530]
The example in the Examples section on the reference page for [Atomics.store()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/store) does not actually use the `Atomics.store()` method. Oops.

**Comment by Elchi3** [comment]
I put back the original example. Don't know why the contributor changed it to this other typedarray code. If it would have been a pull request against the content, I could have asked.
