### ISSUE TITLE
Update the CSS Styling Text Assessment

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2531]
There is already an assessment for the styling text module.

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Typesetting_a_homepage

1. - [x] Create in new format to match other assessments
2. - [x] Check and update for modern best practices
3. - [x] Encourage students to use an online code editor if they want to share their work or ask questions.

**Comment by chrisdavidmills** [comment]
All the above ACs have been fulfilled, and I've added in test your skills sections to the articles:

* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_lists#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#Test_your_skills!

There was not much point adding in more separate tests, as each article has active learning sections that fulfill the same role, and the assessment at the end does a nice job of covering all the essentials.
