### ISSUE TITLE
Create / update CSS Assessments for Layout module

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2532]
New assessments to complete:

- [x] Flexbox (I already created these as a test for the new format)
- [x] Grid (similar to the flex examples)
- [x] Larger flex and grid assessment using both layout methods
- [x] Floats
- [x] Positioning (probably a couple of smaller tasks to be able to assess abspos, and sticky)
- [x] Multicol
- [x] Media Queries (there is an active learning section here but it is more a guided walkthrough)

Existing assessments to update:

- [x] https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Fundamental_Layout_Comprehension

**Comment by rachelandrew** [comment]
@chrisdavidmills do you want me to put these directly into place, or shall I continue to build them in your sandbox?

https://wiki.developer.mozilla.org/en-US/docs/user:chrisdavidmills/New_CSS_Tasks

**Comment by chrisdavidmills** [comment]
@rachelandrew now we are agreed on the format, I am happy for you to put them in place.

**Comment by rachelandrew** [comment]
@chrisdavidmills cool - I'll move the flexbox one then and put the grid ones I am doing right now straight into the section.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've now updated the flex and grid tasks as discussed - sorry for confusion! Also added the floats one.

**Comment by chrisdavidmills** [comment]
Looking great, thanks @rachelandrew

**Comment by rachelandrew** [comment]
You thought we should have a flex and grid example which combines both. Should I just add that to the end of the ones I have done for grid (as at that point they have also done flex) or create a new page?

**Comment by chrisdavidmills** [comment]
I'd say add it to the one that comes later in the series, which is Grid, right?

**Comment by rachelandrew** [comment]
OK, done - this is example 4: https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills

**Comment by rachelandrew** [comment]
While doing the task for multicol, I realised the learn page for multicol doesn't mention the column-span property as it wasn't implemented in Firefox when I wrote this. So I added an example to the main Learn page in addition to using it in a task.

**Comment by rachelandrew** [comment]
I have now added all of these to the learn section and linked them to the appropriate tutorials.
