### ISSUE TITLE
`add` method is not included in the methods for `Element.classList`

### ISSUE THREAD

**Issue by jordanmoore753** [mdn/sprints#2533]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello. I'm not sure if this is an error or not, but the `add` method is not included in the list of methods available for `Element.classList`. The reference article makes several references to `add` but there is no individual link to look at the `add` method in particular.

Here's a link to the page: [Element.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)
Thank you for reading this!

**Comment by chrisdavidmills** [comment]
The page for `add()` is here:

https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add

This is correct, as `Element.classList` actually returns a `DOMTokenList` object, which is what the `add()` method is actually available on. The method pages are all linked to from here:

https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList

I've removed the methods list from https://wiki.developer.mozilla.org/en-US/docs/Web/API/Element/classList, and updated the wording so it is clearer where the methods are available. Hope this helps.
