### ISSUE TITLE
typo in Express/Node introduction

### ISSUE THREAD

**Issue by hgholab76** [mdn/sprints#2534]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Hello MDN team. I was surfing MDN when I ran into a typo. On the page that I will provide the link, there is a typo in paragraph 2, in the first item of the unordered list under "Introducing NODE" section. Unfortunately "throughout" is spelled incorrectly "throughput". Please fix that.

The URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

I've been using MDN for a while and I have to say it's the best resource for learning web development. Thank you guys for providing such precious documentation for free.

**Comment by chrisdavidmills** [comment]
That's not a typo - throughput basically means progess or flow of work or material through something. So here, we mean that node can produce apps that have data flowing through them rapidly/efficiently.
