### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart

### ISSUE THREAD

**Issue by s-e1** [mdn/sprints#2538]
# Request type

- [x] Correction or update

# Details

> Specification | Status | Comment
> -- | -- | --
> String.prototype.{trimStart,trimEnd} proposal | Stage 4 | Expected to be part of ES2019
ES2019 already come out, it's part of it.

**Comment by chrisdavidmills** [comment]
Thanks for reporting! I've updated the spec tables for `trimStart()`/`trimEnd()`
