### ISSUE TITLE
i found a dead link on this page https://developer.mozilla.org/en-US/docs/MDN/Community/Working_in_community

### ISSUE THREAD

**Issue by abbasalamin12** [mdn/sprints#2540]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I found a dead link on this page: https://developer.mozilla.org/en-US/docs/MDN/Community/Working_in_community

The link: 'Getting Started with IRC' in the section: 'The writing community' leads to https://quality.mozilla.org/docs/misc/getting-started-with-irc/ which is a 404 page.
![image](https://user-images.githubusercontent.com/1357468/70167738-488d3600-16bf-11ea-90ce-1bfacb4b023a.png)

A similar link on the same page leads to a web archive of the 404 page. (https://web.archive.org/web/20121127040127/https://quality.mozilla.org/docs/misc/getting-started-with-irc/)
![image](https://user-images.githubusercontent.com/1357468/70168785-73788980-16c1-11ea-8ab6-3dc5f7d3741e.png)

I'm not certain on what the correct link is supposed to be, but I have seen this link which might be the correct resource.  https://wiki.mozilla.org/IRC?utm_campaign=welcome&utm_medium=email&utm_source=developer.mozilla.org#Getting_Started

**Comment by chrisdavidmills** [comment]
Ah, this page is out of date. Updated!
