### ISSUE TITLE
As the PM, I want to know whether we can use our current user profiles on MDN so that we can prepare future product work in the roadmap

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2541]
# User story
As the PM, I want to know whether we can use our current user profiles on MDN so that we can prepare future product work in the roadmap

# Acceptance criteria

- [x] We have consensus as a team on how to design MDN user profiles

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] Discuss current implementation with the MDN team (and future roadmap) to understand JTBD of user profiles
2. - [x] Document goals and key decisions from team sync
3. - [ ] Align with Kadir and get sign off on proposed implementation plan for user profiles
4. - [x] Scope out any new workflow(s) for implementation plan (ie. any required screens we don't have based on proposal)

**Comment by malqinneh** [comment]
Updated the project document with team's meeting notes, decisions, and proposed solution.
Project doc is here: https://docs.google.com/document/d/1e5W8sJnL2nITUxPMQIVVM6LXs040e3ovwWoEeXNoAEA/edit?usp=sharing
And proposed solution here: https://share.goabstract.com/c17745e7-11af-4f5d-bc57-3b90846475e2?collectionLayerId=523f8c6a-85ec-491d-b221-6bfbe037b42b&mode=design

Incorporated team feedback. @atopal, with the exception of Browsers Sets, looking for your sign-off on the proposed MDN user account flow.

**Comment by atopal** [comment]
@malqinneh  I think the profile looks good. Were there any changes after our December 19 meeting that I should be aware of?

**Comment by malqinneh** [comment]
@atopal only small items, nothing major. We're launching the UserZoom test today. I'll walk you through it during our meeting tomorrow (Jan 9). Hopefully we'll have some results by then.
