### ISSUE TITLE
Meaning of "enabled" is reversed in our article on Feature-Policy

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2542]
From jib in IRC this afternoon:

Wanted to point out the use of "enabled" seems backwards in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy. For instance for "camera" it says:

>> Controls whether the current document is allowed to use video input devices. When this policy is enabled, the Promise returned by getUserMedia() will reject with a NotAllowedError DOMException.

>"enabled=NotAllowedError" seems backwards—it appears consistently wrong in every case, as if policies are restrictions, which they're not. At least with the allow="" attribute the default is disabled, and you have to specify policies to explicitly enable the features, not limit them. This is inconsistent with the use of the words enabled/disabled in the Syntax section on the same page (which uses it correctly AFAIK): E.g. "The values * (enable for all origins) or 'none' (disable for all origins)"

>E.g. taken literally one might deduce (wrongly) that you need "none" to make camera access succeed. To complicate matters, each policy has its own default. e.g. for camera the default is "self" https://w3c.github.io/mediacapture-main/getusermedia.html#feature-policy-integration-0 default=default-allowlist meaning top-level page only (since iframes require explicit delegation with allow=)

Basically, this sentence:

> Controls whether the current document is allowed to use video input devices. When this policy is enabled, the Promise returned by getUserMedia() will reject with a NotAllowedError DOMException.

Should instead be:

> Controls whether the current document is allowed to use video input devices. When this policy is disabled, the Promise returned by getUserMedia() will reject with a NotAllowedError DOMException.

And then all other places that have similar mistakes need to be fixed. This seems like a pretty substantial error to me; we should try to fix it soon.

**Comment by chrisdavidmills** [comment]
@a2sheppy agreed. And well-volunteered!

**Comment by a2sheppy** [comment]
Wait... what? :)

**Comment by jpmedley** [comment]
This may be my fault. I had this whole big argument with the guys who designed this wherein an absent policy header meant that restriction was in place and that constituted "enabled". Made me want to bash my own head in. 

I should have written around it. I don't know if I did and somebody changed it back or what. Regardless I apologize.

**Comment by a2sheppy** [comment]
No worries, Joe. These things happen.

**Comment by jpmedley** [comment]
I was thinking that this issue could be written around. Instead of referring to enabled or disabled policies you could refer to restriction in place when there's no policy and refer to the policy as removing the restriction (or something similar to this).

**Comment by a2sheppy** [comment]
I've done a couple of passes through and I think I've got this fixed up now. Would appreciate if someone could check me on it. @jpmedley? Do you have time?
