### ISSUE TITLE
MDN user profile and settings updated workflow

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2543]
# User story
As a user I want MDN to remember my browser sets (so that I can know whether the code is useful for the project I'm working on) and a place to manage my subscription (so that I can cancel or modify it).

# Acceptance criteria

- [x] We have solutions (ie. InVision mock-ups) for the above use-cases outlined ready for engineering
- [ ] Engineering sign off 
- [ ] PM sign off

**Comment by malqinneh** [comment]
Updated the project document with team's meeting notes, decisions, and proposed solution. 
Project doc is here: https://docs.google.com/document/d/1e5W8sJnL2nITUxPMQIVVM6LXs040e3ovwWoEeXNoAEA/edit?usp=sharing
And proposed solution here: https://share.goabstract.com/c17745e7-11af-4f5d-bc57-3b90846475e2?collectionLayerId=523f8c6a-85ec-491d-b221-6bfbe037b42b&mode=design

Browser sets UX/UI flow coming soon.

**Comment by atopal** [comment]
Looks good to me, but same question: Any changes I should be aware of after our December 19 session?

**Comment by malqinneh** [comment]
@atopal only small items, nothing major. We're launching the UserZoom test today. I'll walk you through it during our meeting tomorrow (Jan 9). Hopefully we'll have some results by then.
