### ISSUE TITLE
mistranslation to japanese. 'propagation'→伝播

### ISSUE THREAD

**Issue by terasyterasy** [mdn/sprints#2545]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

mistranslation to japanese
'propagation'
伝搬 : incorrect ( not exist )
伝播 : correct

this page
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Using_promises#Error_propagation

sorry for not being able to fix it.

**Comment by chrisdavidmills** [comment]
I have changed the wrong version to the correct version — does it look OK now?

Let me know if you think it needs anything else. Thank you for reporting!

**Comment by terasyterasy** [comment]
thank you for your response!
i confirmed that it was fixed.

i respect the people who edit MDN! thank you!
