### ISSUE TITLE
Create page: <python framework>

### ISSUE THREAD

**Issue by zhaoy88** [mdn/sprints#2547]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

**Comment by SphinxKnight** [comment]
Please do provide more context/information.

MDN is a place to document web technologies and I'm not sure any Python framework fits in this frame.

**Comment by zhaoy88** [comment]
just want to create a new page and write an article about python test framework

**Comment by SphinxKnight** [comment]
As I wrote above, MDN's purpose is not to document any technology. There might be other platform/tools to document a Python test framework.

I'll close this issue but if you have more input/rationale about how/why this should be on MDN, please reopen.
