### ISSUE TITLE
Forms: Updating "Sending form data"

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2549]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

This one is OK, but could do with its screenshots updating to modern Firefox, etc.
Also, we should move this to later in the series, as it's the most likely to not be understood, given what other knowledge the readership is likely to have?

# Acceptance criteria

1. - [ ] Screenshots updated
* GET - do a screen shot of the get header instead of listing what it reads (confusing to readers)
* The "localhost:8888" image: make the URL visible.
* check MAMP links
2. - [ ] Other updates required
* give example of XSS and CSRF
* give example of zombie
* look into best practices and update them
* add a sentence about how client side validation is not enough.
3. - [X] Article moved to a suitable place later in series. This article should be put just before https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_forms_through_JavaScript, and they should both be put near the end of the article series.

**Comment by estelle** [comment]
Moved sending data toward the end of the series.
Move the sending via JS to an advanced section and out of the tutorial flow.

**Comment by chrisdavidmills** [comment]
This is done.
