### ISSUE TITLE
General work related to reordering of form articles

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2550]
# User story

https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Advanced_styling_for_HTML_forms is generally interesting and OK, but you see what I mean about the ordering of the articles? This article features a section called "Dealing with the select nightmare", which talks about how hard it is to style selects, and is followed by some advice on trying to use libraries.

 Really, a better order would be to have:

 * This article, which keeps the select nightmare section and then says "for an example solution, see the next article."
 * Then have "How to build custom form widgets", which is currently article 6.
 * Move the stuff about using JS libraries to the end of "How to build custom form widgets", and phrase it like "you can build a custom solution if you like, but using a JS library is a quicker solution."

# Acceptance criteria

1. - [ ] Move content around as described above.

**Comment by estelle** [comment]
Created a couple new articles and separated the 'advanced' articles.
