### ISSUE TITLE
Move "Property compatibility table"

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2551]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Property_compatibility_table_for_form_widgets

This is pretty useful, but I'm not sure it should be part of the learning area. Maybe put it under the input element reference instead?

# Acceptance criteria

1. - [ ] Article moved as appropriate

**Comment by estelle** [comment]
Updated the page/
Move it and all the "advanced" tutorials to an "other" topic section
Added links to that file from all the non-deprecated input pages.
