### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

### ISSUE THREAD

**Issue by simplast** [mdn/sprints#2554]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

“即使从末尾开始往前跳 fromIndex 的绝对值个索引，然后往后搜寻”  => "即从末尾开始往前跳 fromIndex 的绝对值个索引，然后往后搜寻"

**Comment by SphinxKnight** [comment]
Hello @simplast, could you translate your details in English? I'm not sure I understand what I got from an automatic translation tool :s
