### ISSUE TITLE
Named capture groups example needs update

### ISSUE THREAD

**Issue by gregorybleiker** [mdn/sprints#2555]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
The docs section about named capture groups example is missing the capture group name

Using named capturing groups
In browsers which support named capturing groups, the following code:

var paragraph = 'The quick brown fox jumps over the lazy dog. It barked.';

var capturingRegex = /(?fox|cat) jumps over/;
>> `This should probably be /?<animal>fox|cat) jumps over/`

found = paragraph.match(capturingRegex);
console.log(found.groups); // {animal: "fox"}

**Comment by chrisdavidmills** [comment]
Thanks for reporting! Which MDN page is this content on?

**Comment by gregorybleiker** [comment]
Sorry, should have included that:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

**Comment by jmswisher** [comment]
That section was actively being worked on at the time this issue was submitted. @gregorybleiker Does it look satisfactory to you now?

**Comment by jadjoubran** [comment]
Indeed this seems to be resolved now, maybe let's close it and then @gregorybleiker can re-open if it's not solved?

**Comment by chrisdavidmills** [comment]
Closing; thanks for looking at this.
