### ISSUE TITLE
UI selectors resource

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2556]
We currently have pages for 
    Type selectors
    Class selectors
    ID selectors
    Universal selectors
    Attribute selectors
We should add a page for 
   UI selectors

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm assuming this would cover the things under Input Pseudos in the Level 4 specification. I don't think we use the term UI Selectors anywhere.

https://www.w3.org/TR/selectors-4/#input-pseudos

**Comment by chrisdavidmills** [comment]
Yes, agreed.

**Comment by rachelandrew** [comment]
I'm not sure having done https://github.com/mdn/sprints/issues/1687 if we need this, or where it would go. The spec doesn't have "UI Selectors" as a thing, so I'm assuming that what Estelle was referring to are the Input Pseudos from that list. However they don't fit as a distinct thing in the list mentioned.

I think if anything maybe some guide as to their use, although I think we already have some of that dotted around. Let me know what you think @chrisdavidmills

**Comment by chrisdavidmills** [comment]
I think you're right. Let's close this now.
