### ISSUE TITLE
/en-US/docs/Web/CSS/flex

### ISSUE THREAD

**Issue by fkoji** [mdn/sprints#2558]
# Request type
- [x] Correction or update

# Details

I reported it before in https://github.com/mdn/sprints/issues/1496#issuecomment-501118508 , but I am reporting it again because it has not been corrected to the correct specification.

## Syntax - Values - <'flex-basis'>

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

Here.

> Defines the flex-basis of the flex item. A preferred size of 0 must have a unit to avoid being interpreted as a flexibility. **Defaults to 1 when omitted**, unless the initial or none keywords are used.

"Defaults to 1 when omitted" is incorrect. The correct on is "**Defaults to 0 when omitted**".

see:
- https://drafts.csswg.org/css-flexbox-1/#flex-property
- https://www.w3.org/TR/css-flexbox-1/#flex-property

**Comment by chrisdavidmills** [comment]
Ah yes; the others have a default of 1, but this has a default of 0. Fixed.
