### ISSUE TITLE
If-None-Match header: "two pages that differ only by the date of generation in the footer are identical"

### ISSUE THREAD

**Issue by verhovsky** [mdn/sprints#2561]
# Request type
- [ ] New documentation
- [X] Correction or update

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match says:

> The comparison with the stored ETag uses the weak comparison algorithm, meaning two files are considered identical not only if they are identical byte to byte, but if the content is equivalent. For example, **two pages that would differ only by the date of generation in the footer would be considered as identical**.

Shouldn't it be the opposite? Not identical?

**Comment by chrisdavidmills** [comment]
> Shouldn't it be the opposite? Not identical?

No, I think they are considered identical; I just think the wording is confusing here. I've updated the wording to the following:

"The comparison with the stored ETag uses the weak comparison algorithm, meaning two files are considered identical if the content is equivalent — they don't have to be identical byte for byte. For example, two pages that differ by the date of generation in the footer would still be considered as identical."

Do you think this is clearer now?

**Comment by verhovsky** [comment]
Thanks. I missed the "not" in "not only if they are identical byte to byte"
