### ISSUE TITLE
/en-US/docs/Web/API/HTML_Drag_and_Drop_API

### ISSUE THREAD

**Issue by AlexSHoffman** [mdn/sprints#2562]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Specify on the following pages that `drop` event requires `dragover` event to work:

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event

By now, [21,000 people](https://stackoverflow.com/questions/8414154/html5-drop-event-doesnt-work-unless-dragover-is-handled), including me, wasted hours of our lives trying to figure out why you cannot drop any files when you have `dragenter` and `drop` event listeners created. Turns out you have to have `dragover` event to be able to drop files.

**Comment by chrisdavidmills** [comment]
Looks like the `dragover` event is covered here:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Define_a_drop_zone

And used in the demos linked to from that page, for example:

https://mdn.github.io/dom-examples/drag-and-drop/copy-move-DataTransfer.html

Do you think more needs to be done to highlight it? What would you add?

**Comment by AlexSHoffman** [comment]
@chrisdavidmills thanks for clarifying it. Now that I spent so much time figuring out why it didn't work, I understand that this paragraph in the docs actually means the `drop` event requires `dragover` and will not work without it at all.

I don't know why so many people, including me, didn't understand what it meant, I mean, just [that one issue](https://stackoverflow.com/questions/8414154/html5-drop-event-doesnt-work-unless-dragover-is-handled) on stackoverflow has over 21,000 views. Maybe we all just got used to having such important details to be put in a warning or something. I don't know why it's so unclear, even though the paragraph clearly explains it.

I'm closing the issue then. Thank you
