### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Guide/Keyed_collections

### ISSUE THREAD

**Issue by bojowa** [mdn/sprints#2563]
# Map()

sth about Map,when i do followed codes,explore throws this:
Uncaught ReferenceError: saying is not defined
    at <anonymous>
var sayings = new Map();
sayings.set('dog', 'woof');
sayings.set('cat', 'meow');
sayings.set('elephant', 'toot');

so why this?

**Comment by chrisdavidmills** [comment]
This works fine for me.

What browser are you using?

**Comment by bojowa** [comment]
> This works fine for me.
> 
> What browser are you using?

var sayings = new Map();
        sayings.set('dog', 'woof');
        sayings.set('cat', 'meow');
        sayings.set('elephant', 'toot');
        console.log(sayings.size);

both chrome and firfox  can' t work,

**Comment by chrisdavidmills** [comment]
I don't know what to suggest really. Your code is working fine in both Firefox and Chrome for me.

Are you just trying to run it in a console, or in an IDE, or inside a web framework, or ... ?

**Comment by SphinxKnight** [comment]
> Uncaught ReferenceError: saying is not defined

I don't know if this message was written by hand or copied/pasted but please be aware that `saying` and `sayings` are not the same identifier (note the `s` at the end). This might be an explanation to this error.

Also, as @chrisdavidmills stated, could you indicate the browser version you are using and post a Codepen / JSFiddle / Live example to share the exact snippet/environment where this is failing?
