### ISSUE TITLE
Example of ES6/7 code transpilation

### ISSUE THREAD

**Issue by rebloor** [mdn/sprints#2564]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

See https://github.com/mdn/webextensions-examples/issues/97

**Comment by rebloor** [comment]
@chrisdavidmills Given the rationale for removing react/ES6 examples in [398]( https://github.com/mdn/webextensions-examples/issues/398) I'm thinking that we shouldn't proceed with this one. Agree?

**Comment by chrisdavidmills** [comment]
@rebloor I don't think we need a specific example of modern ES feature transpilation using babel, etc., or separate examples just for demonstrating JS feature usage in extensions, as those features are now all supported in Firefox, and we don't have cross-browser concerns with extensions.

Saying that however, I do think it'd be nice to include some example usage of those modern features in some of the extension examples, if possible. Can you start by looking at the examples and seeing if there is any example usage of async/wait, importants, etc.?

**Comment by rebloor** [comment]
@chrisdavidmills there do appear to be some example using these features, such as commands/options.js:
``` 
      */
      async function updateUI() {
       let commands = await browser.commands.getAll();
        for (command of commands) {
          if (command.name === commandName) {
```
Perhaps update the descriptions in examples.json to note something such as "includes uses of ES6/7 programming features.” Aside from async/wait and importance what else should I be looking out for all, where could I find a list of commands to check for?  I found this: https://www.w3schools.com/js/js_es6.asp but it doesn't mention those features. Nor are they mentioned in https://www.freecodecamp.org/news/ecmascript-2016-es7-features-86903c5cab70/  Thoughts?

**Comment by chrisdavidmills** [comment]
These lists aere useful:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_2015_support_in_Mozilla
* https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/ECMAScript_Next_support_in_Mozilla

Although I'm not sure why the later is archived. async/await is part of ES2017, IIRC.

I don't think you even need to put an explicit note on them, as it'd be annoying to maintain for future examples. Maybe it would be nice to show an example that uses imports, and then see if anything else is causing people specific difficulties in terms of their usage in extensions?
