### ISSUE TITLE
About the background-style CSS property

### ISSUE THREAD

**Issue by m32po** [mdn/sprints#2569]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

As stated in the title, it's about the `background-style` CSS property. I found out it was used in some code examples in the following MDN documents:

1. [https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax)
2. [https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured)

In the first one (titled "_Syntax_") the `background-style` property is present in a couple of images:

- [https://mdn.mozillademos.org/files/3667/css%20syntax%20-%20declarations%20block.png](https://mdn.mozillademos.org/files/3667/css%20syntax%20-%20declarations%20block.png)
![](https://mdn.mozillademos.org/files/3668/css%20syntax%20-%20ruleset.png)

- [https://mdn.mozillademos.org/files/3668/css%20syntax%20-%20ruleset.png](https://mdn.mozillademos.org/files/3668/css%20syntax%20-%20ruleset.png)
![](https://mdn.mozillademos.org/files/3667/css%20syntax%20-%20declarations%20block.png)

In the second document (titled "_How CSS is structured_") the `background-style` property is present in three code examples:

- the one in the Comments section
[https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured#Comments](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured#Comments)

- the two in the Whitespace section
[https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured#Whitespace](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured#Whitespace)

But I searched the web about `background-style` property and I found nothing. I'm a little puzzled, the two mentioned documents have been written in different times and by different authors, at least at a quick glance looking at the corresponding two revision history pages.

It very odd that this unknown proprerty has been used in two different documents. Moreover it seems nobody has ever spotted it out till now, and maybe corrected it.

So I wonder if there is a reason... is there one?

**Comment by chrisdavidmills** [comment]
@m32po this is really interesting. `background-style` doesn't exist, and I'm amazed that no-one has noticed it! It seems like one of our contributors is trolling us ;-)

In any case, I can see how this could be confusing, so I'll remove mentions of it from the code, and create some new graphics.

Thanks for pointing this out!

**Comment by chrisdavidmills** [comment]
OK, textual mentions of the imaginary property removed, and diagrms updated. Let me know if you think anything else needs to be done.

**Comment by m32po** [comment]
@chrisdavidmills thank you for your prompt correction, I would have did it myself, but I wanted to be sure that there were no particular reasons before intervening.

I must confess you I hadn't even noticed it myself. The other day, while I was in class teaching, I was advising my students to refer to MDN articles about everything about web stuff. So I was showing them the above mentioned CSS Syntax MDN article, scrolling down right where the CSS ruleset example image is. So it happened: one student sees it and asks me what `background-style` property does and I relized that that property did make no sense. Amazing! :-)

I'm sorry to have bothered you for a small thing like this. Thanks!

**Comment by chrisdavidmills** [comment]
No need to apologise - I am really glad you mentioned it, because otherwise it would have been there for probably a few more years ;-)
