### ISSUE TITLE
JS docs: Have constructor pages instead of prototype pages

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#2571]
In #2537 @wbamberg and @Elchi3 proposed to completely separate object constructors (that are callable with `new` keyword) from the objects they construct. This is a meta issue to track which pages still need to be separated and updated.

Update (by @Elchi3): This was actually discussed in London at the stumptown work week. The JS docs should follow the API docs and have pages for constructors instead of pages for prototypes. The prototype pages are mostly useless (and introduce weird usage of the page macro). Having pages for constructors instead seems more useful and consistent with API docs.

An update to BCD is also needed, see e.g. https://github.com/mdn/browser-compat-data/pull/5440.

## Pages (might not be complete)

- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
- [x] https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
- [x] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet

**Comment by Elchi3** [comment]
Thanks for filing this issue @bershanskiy! I've updated the description a bit here to give more context.

**Comment by Elchi3** [comment]
Hey @SphinxKnight, just a heads-up that this is happening. Some restructuring in the JS docs, see above. I hope it won't be too much of a hassle for locales.

**Comment by SphinxKnight** [comment]
@Elchi3 Thanks a lot :) I've seen it coming, I don't think it is too painful and I (personnally) appreciate the distinction between constructors and types. Thanks again (and happy 2020 :))

**Comment by Elchi3** [comment]
The BCD updates are merged and should be on the site this Thursday.

I'm going to leave a comment here with the list of pages again, but this time only listing those that I've refactored already and that are ready for review. Please tick the box if you've reviewed it and/or leave your feedback :-)
- [ ] ArrayBuffer
- [ ] BigInt

**Comment by ExE-Boss** [comment]
Don’t forget about:
- [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator

**Comment by sideshowbarker** [comment]
Since some `mdn_url` values added in https://github.com/mdn/browser-compat-data/pull/5471 are for MDN articles that don’t exist yet, the following are all 404 at this point:

    Function: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function
    Object: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object
    RegExp: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp
    Set: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/Set
    SharedArrayBuffer: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer
    String: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/String
    Symbol: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/Symbol
    WeakMap: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/WeakMap
    WeakSet: 404 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet/WeakSet

**Comment by Elchi3** [comment]
Thanks @sideshowbarker, that's because I haven't finished this task yet as it was quite difficult to focus on work last week. I hope I will finish this thing this week and then the 404s should be gone.

**Comment by wbamberg** [comment]
The compat table at https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility lists "Promise() constructor" but it's not linked. I don't understand why. The data looks all right: https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Promise.json#L55-L58.

**Comment by wbamberg** [comment]
The opening para of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer looks like it needs to be updated to be talking about the constructor rather than the object. It goes: 

> The `SharedArrayBuffer` object is used to represent...

...where I would have expected something like:

> The `SharedArrayBuffer()` constructor is used to create...

**Comment by wbamberg** [comment]
The other "Object" pages, like [`Map`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), say, get an H2 "Constructor" linking to the constructor page.

But the page for [`Object`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) doesn't, and still have H2 sections called things like "Properties of the Object constructor".

Is this an intentional difference?

**Comment by wbamberg** [comment]
> The following error type pages had prototype pages but no further sub pages. Instead they are referring to the pages of the main Error object. I've now merged the prototype page with the main page of these, but did not create constructor pages.

 A motivation for this issue is to be clear which sorts of objects different pages describe: in particular to split pages that describe _objects_ and pages that describe _constructors_.

So from this perspective, one question seems to be: what sorts of things do pages like [`ReferenceError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError) describe?

They seem to describe `ReferenceError` objects, and are structured with H2 sections called "Methods" and "Properties" (following this pattern: https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-class.yaml). But they also have an H2 "Syntax" section, which is more appropriate for pages that describe constructors and methods (cf. https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-constructor.yaml)

So that makes it look like it is worth having separate, new, "constructor" pages for these `Error` subtypes, and these page should get the "Syntax" H2 from the existing pages.

>  I guess either we create sub pages for all things (methods, properties, constructors) or no sub pages at all.

I don't think we need subpages for all the methods and properties. For one thing, from the structured content point of view it's fine for docs to be incomplete. For another, most of them seem to be just derived from the base `Error`, and so the links at, say, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError#Methods point to the corresponding page under `Error` which seems like a reasonable thing to do.

Anyway. That's just my opinion, and maybe I misunderstand it :).

**Comment by wbamberg** [comment]
@Elchi3 , I looked through all the pages referenced under https://github.com/mdn/sprints/issues/2571#issuecomment-573709527, checking things like BCD, whether "object" pages have a "Constructor" H2, whether the content looks sensible and whether the links work properly, and it generally looks great. I made a few comments above.

**Comment by sideshowbarker** [comment]
FYI, today I created new constructor pages for `Intl.PluralRules` & `Intl.RelativeTimeFormat`.

* https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules/PluralRules
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/RelativeTimeFormat

I hope I got it right, as far as the separation between those pages and the pages for their objects.

I’m happy to help with getting new constructor separated out for other objects. I just did these two today because they are two specific ones that I’ve run into some particular annoyances with.

**Comment by Elchi3** [comment]
> The compat table at https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility lists "Promise() constructor" but it's not linked. I don't understand why. The data looks all right: https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Promise.json#L55-L58.

I've noticed this too earlier this week and corrected it in a follow-up PR that made it into yesterday's BCD release, but apparently that release was not pushed prod yet.

> The opening para of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer looks like it needs to be updated to be talking about the constructor rather than the object

Thanks, corrected.

> But the page for Object doesn't, and still has H2 sections called things like "Properties of the Object constructor".
> Is this an intentional difference?

No, just oversight from my part. I think once we start linting content against recipes we will have to pay attention to sections more carefully.

> A motivation for this issue is to be clear which sorts of objects different pages describe: in particular to split pages that describe objects and pages that describe constructors.

Yes, thanks for elaborating this some more. I think you are right in fact. I will look into creating constructor pages for error objects. It makes sense when looking at this from the content type perspective.

**Comment by Elchi3** [comment]
@wbamberg thank you very much for your review! I've done some corrections and also finished String.

Remaining are the error constructors and WebAssembly and Intl.

For WebAssembly and Intl we have "namespaces" and there is a proposed reorg of this content (#2537). I think "namespace" might be a new content type and the reorg should probably be split out from the constructor work. So, I think, I will go ahead like @sideshowbarker did with PluralRules and RelativeTimeFormat and then we need to talk about how to reorg this with namespaces in mind.

**Comment by Elchi3** [comment]
Also, I just realized, if we create constructor pages for the error objects, we would also need to create constructor pages for typed arrays. So make https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array about the object and have a separate page for the constructor there as well.

**Comment by wbamberg** [comment]
> > The compat table at https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility lists "Promise() constructor" but it's not linked. I don't understand why. The data looks all right: https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/Promise.json#L55-L58.
> 
> I've noticed this too earlier this week and corrected it in a follow-up PR that made it into yesterday's BCD release, but apparently that release was not pushed prod yet.
> 
> > The opening para of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer looks like it needs to be updated to be talking about the constructor rather than the object
> 
> Thanks, corrected.
> 
> > But the page for Object doesn't, and still has H2 sections called things like "Properties of the Object constructor".
> > Is this an intentional difference?
> 
> No, just oversight from my part. I think once we start linting content against recipes we will have to pay attention to sections more carefully.

Thanks @Elchi3 , I've verified that these three points are fixed, and checked off the corresponding items in https://github.com/mdn/sprints/issues/2571#issuecomment-573709527 👍

**Comment by Elchi3** [comment]
Another thing before I forget this: Some compat data is about the constructor but currently lives under the object. See, e.g. 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Browser_compatibility

**Comment by bershanskiy** [comment]
Other constructor data that might be moved:
 - https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility
 - All the `*Array` constructors, obviously.

**Comment by Elchi3** [comment]
To do list for remaining constructor work:

TypedArrays:
- [ ] Int8Array
- [ ] Uint8Array
- [ ] Uint8ClampedArray
- [ ] Int16Array
- [ ] Uint16Array
- [ ] Int32Array
- [ ] Uint32Array
- [ ] Float32Array
- [ ] Float64Array
- [ ] BigInt64Array
- [ ] BigUint64Array

Errors:
- [ ] EvalError
- [ ] InternalError
- [ ] RangeError
- [ ] ReferenceError
- [ ] SyntaxError
- [ ] TypeError
- [ ] URIError

WebAssembly:
- [ ] WebAssembly.Global
- [ ] WebAssembly.Module
- [ ] WebAssembly.Instance
- [ ] WebAssembly.Memory
- [ ] WebAssembly.Table
- [ ] WebAssembly.CompileError
- [ ] WebAssembly.LinkError
- [x] [WebAssembly.RuntimeError](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/RuntimeError)

Intl:
- [ ] tbd

**Comment by Elchi3** [comment]
This took longer than I thought, but I think it is all done now.
(if not, we will probably notice when we match recipes and pages in the stumptown linter soon).
