### ISSUE TITLE
Access-Control-Allow-Origin  origin documentation seems wrong

### ISSUE THREAD

**Issue by bn3t** [mdn/sprints#2572]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

The MDN Documentations states that:

     <origin> Specifies an origin. Only a single origin can be specified. 

I don't think this is correct as the spec here:

   https://www.w3.org/TR/cors/#access-control-allow-origin-response-header

Indicates:

    Access-Control-Allow-Origin = "Access-Control-Allow-Origin" ":" origin-list-or-null | "*"

origin-list-or-null is:

   origin-list-or-null = %x6E %x75 %x6C %x6C / origin-list
   origin-list         = serialized-origin *( SP serialized-origin )
   serialized-origin   = scheme "://" host [ ":" port ]
                       ; <scheme>, <host>, <port> from RFC 3986

This allows for a space separated list of origins.

**Comment by chrisdavidmills** [comment]
Yes, but in the spec  it also says 

> In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null". 

I think that is why the MDN docs are written as they are.

**Comment by bn3t** [comment]
Indeed you are right. Do you have any insight on how it is implemented in Firefox?

**Comment by chrisdavidmills** [comment]
I don't, I'm afraid. You could maybe try asking on the dev-platform list (https://lists.mozilla.org/listinfo/dev-platform)

**Comment by bn3t** [comment]
Thanks for your answers.
