### ISSUE TITLE
/zh-CN/docs/Web/JavaScript

### ISSUE THREAD

**Issue by XieWuHen** [mdn/sprints#2573]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

### **中文文档内容错误**
文本错误内容的链接:
https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/arc

其中的：
anticlockwise 可选
可选的Boolean值 ，如果为 true，逆时针绘制圆弧，反之，顺时针绘制。
 
应该是：
anticlockwise 可选
可选的Boolean值 ，如果为 true，顺时针绘制圆弧，反之，逆时针绘制。

**Comment by SphinxKnight** [comment]
I'm not a Chinese speaker but it seems to me that the Chinese version (translated with some automatic translation tools) matches the English content and that the latter is correct to me.
Could you add some more details to explain why you think this needs fixing?
