### ISSUE TITLE
[CSS] shadow parts, 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2574]
# Trello

https://trello.com/c/SUWuKgHm/176-css-shadow-parts-fx-72

# Acceptance criteria

1. - [x] [Enable shadow parts for release and beta channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1559074) (make sure BCD is updated for the `part` attribute, and the `::part()` pseudo)

**Comment by chrisdavidmills** [comment]
@rachelandrew I just noticed this 72 item. Let me know if you'll have time to get to it; if not, I'm happy to help with some 72 CSS stuff later in the month.

**Comment by rachelandrew** [comment]
yep that looks fine, don't think it should be a huge amount of work

**Comment by rachelandrew** [comment]
PR for the data: https://github.com/mdn/browser-compat-data/pull/5327

**Comment by rachelandrew** [comment]
Also added to the release notes.
