### ISSUE TITLE
/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

### ISSUE THREAD

**Issue by darioscattolini** [mdn/sprints#2575]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Em property is defined as "Font size of the parent element". While this is true for values assigned to typography, it's incorrect for properties of the box model such as width, where the relevant font-size is of the element being modified and not its parent's.

This definition and the way the example is formulated is misleading, because it seems that the width of the third box specified in ems depends on the "font size of 1em on the containing div, which has a class of .wrapper". This is true only because the child "box em" inherits the font-size from "wrapper". If one specifies a different font-size for the child box, its width changes accordingly. One can see it very clearly in the example if the text inside de box is reduced to one character, and one experiments with different em lengths for width.

Sorry for just pointing this out and not correcting it myself. I'm just starting to get a grip on this issue and I suspect there are some more details to check out in this document, perhaps in a couple of days I can make a contribution.

**Comment by chrisdavidmills** [comment]
@darioscattolini I've had a go at updating the text to make this less misleading. Please met know if you if it needs further improvement.

Thanks!
