### ISSUE TITLE
/it/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

### ISSUE THREAD

**Issue by polikurov** [mdn/sprints#2576]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
in the Italian version of the documentation the syntax is written as `arr.reduce(callback(accumulator, currentValue[, index[, array]]), [, initialValue])` , when it should be written `arr.reduce(callback(accumulator, currentValue[, index[, array]])[, initialValue])` as in the English version. Notice the comma in between `index[, array]])` and `[, initialValue]`

**Comment by SphinxKnight** [comment]
fixed w/ https://wiki.developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce$compare?locale=it&to=1596141&from=1564794

@polikurov thanks for reporting, please do not hesitate to edit a page when you encounter such typos, MDN is a wiki anyone can edit :)
