### ISSUE TITLE
/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/sprints#2577]
# Request type
- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
One of the examples says:
"In this next example, we have added two empty strings using the ::before and ::after pseudo-elements."
But, there is only a ::after pseudo-element in the example.  The descriptive text and the code are incongruent.

**Comment by chrisdavidmills** [comment]
You are quite right ;-)

I've updated the article text to accurately reflect what is happening in the example. Thanks for reporting!
