### ISSUE TITLE
/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

### ISSUE THREAD

**Issue by Kartik1397** [mdn/sprints#2578]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Typo in second paragraph of conclusion 

"If you've worked your way these tutorials in order, you now **now** how to markup, style, and sumbit a form..."

Expected:
"If you've worked your way these tutorials in order, you now **know** how to markup, style, and sumbit a form..."

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
