### ISSUE TITLE
/en-US/docs/Learn/HTML/Forms/Form_validation

### ISSUE THREAD

**Issue by Kartik1397** [mdn/sprints#2579]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Example given in "Constraining the values of your entries" is not running.
![Screenshot from 2019-12-16 00-39-40](https://user-images.githubusercontent.com/24036721/70867550-939b2900-1f9c-11ea-9369-53d0cf87ef07.png)
**Possible solution**:
Value of `src` attribute in `<iframe>` is wrong.
may be the correct value is [https://mdn.mozillademos.org/en-US/docs/Learn/HTML/Forms/Form_validation$samples/Constraining_the_values_of_your_entries?revision=1595354](url)

**Comment by chrisdavidmills** [comment]
The macro call that generates each live example has the id of the heading that the example code is found under passed to it. In these cases, the heading was changed, so the reference in the macro calls was now wrong.

I've fixed them now. Thanks for reporting!
