### ISSUE TITLE
Problem in the Russian Lessons Javascript Internal

### ISSUE THREAD

**Issue by sirartemis** [mdn/sprints#2581]
In the Javascript First Steps on Russian bad link to second Lesson "The first Splash into Javascript",
because she send to first Lesson "What is Javascript". Сertainly, i'm understand how open the Lesson, you just need to change language to English, open necessary lesson and change to Russian conversely, but other begginers may don't know about it and miss important knowledge part.
Please, change with link in Russian part. Thank you!

**Comment by chrisdavidmills** [comment]
OK, this is now fixed!
