### ISSUE TITLE
/en-US/docs/Web/API/Node/replaceChild has identical descriptions for two different parameters

### ISSUE THREAD

**Issue by jmalk** [mdn/sprints#2582]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the [parameter definitions for replaceChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild#Syntax), both `newChild` and `oldChild` have the exact same description. I'm assuming this is a copy-paste error and they should have different descriptions.

![image](https://user-images.githubusercontent.com/6491332/70930656-98f48400-202d-11ea-9750-ad2618932da4.png)

I'd be happy to help fix it but haven't contributed to mdn before so would appreciate guidance with it please.

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
