### ISSUE TITLE
:focus-within supported in Edge, but BCD says it isn't

### ISSUE THREAD

**Issue by Neha** [mdn/sprints#2585]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within

In the browser support , table is showing no support on the Edge. However, the support is now available in the Edge too.

https://caniuse.com/#search=focus%20within

Thank you

**Comment by Elchi3** [comment]
This got fixed https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within#Browser_compatibility
