### ISSUE TITLE
/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

### ISSUE THREAD

**Issue by viRingbells** [mdn/sprints#2586]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

there's a typo.

section: 存储复杂数据 — IndexedDB / 数据库初始设置

> 要在IndexedDB中处理此问题，您需要创建一个请求对象（可以随意命名 - _命名为reques_，可以表明它的用途）。然后，在请求完成或者失败时，使用事件处理程序来运行代码，您将在下面看到这些代码。

the italic part should be  '命名为request' (missing 't')

**Comment by SphinxKnight** [comment]
Fixed with https://wiki.developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage$compare?locale=zh-CN&to=1596140&from=1588512

@viRingbells thanks for reporting! do not hesitate the page (mdn is a wiki anyone can contribute to) to fix such typos :)
