### ISSUE TITLE
/en-US/docs/Learn/Performance/dns-prefetch

### ISSUE THREAD

**Issue by srus** [mdn/sprints#2587]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

All the examples given on this page are using a wrong domain: https://fonts.googleapis.com/. The right domain is https://fonts.gstatic.com, which is the domain the fonts will fetch once the CSS is parsed.

The last paragraph is also not very accurate:

> You can set the crossorigin attribute to both elements optionly, it lets you configure the CORS requests for the element's fetched data.

The `crossorigin` attribute shouldn't be optional with this particular example, since it's required by the [font-face specification](http://www.w3.org/TR/css3-fonts/#font-fetching-requirements). I suggest to replace that paragraph with this one taken from the References:

> Some types of resources, such as fonts, are loaded in anonymous mode. For those you must set the crossorigin attribute with the preconnect hint. If you omit the crossorigin attribute, the browser only performs the DNS lookup.

On the Best Practices section, there's a paragraph suggesting to use DNS-preconnect with all cross-origin requests, which is counterproductive:

> Third, consider pairing dns-prefetch with the preconnect hint. While dns-prefetch only performs a DNS lookup, preconnect establishes a connection to a server. This process includes DNS resolution, as well as establishing the TCP connection, and performing the TLS handshake—if a site is served over HTTPS. Combining the two provides an opportunity to further reduce the perceived latency of cross-origin requests.

So I suggest to add a note at the end of the paragraph to clarify that point. This note is taken from the the References:

> If a page needs to make connections to many third-party domains, preconnecting all of them is counterproductive. The `preconnect` hint is best used for only the most critical connections. For all the rest, use `<link rel=dns-prefetch>` to save time on the first step, the DNS lookup, which usually takes around 20–120 ms.

References:

- https://web.dev/preconnect-and-dns-prefetch/
- https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/

**Comment by chrisdavidmills** [comment]
I've made all the suggested changes. thanks for the advice here, it all sounds good.
