### ISSUE TITLE
/en-US/docs/Web/JavaScript/Guide/Using_promises

### ISSUE THREAD

**Issue by sidewaysgravity** [mdn/sprints#2589]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is typo on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Error_propagation. The second paragraph states "Basically, if there's an exception, promise chain will looking down the chain for catch handlers or onRejected. This is very much modeled after how synchronous code works:" 

Looking should be changed to look.

Thanks for creating and maintaining these docs. They are extremely helpful!

**Comment by chrisdavidmills** [comment]
Ah yes, that sentence was a bit scrappy; I've sorted it out.

Thanks for reporting, and I'm really glad to hear you are finding the docs helpful!
