### ISSUE TITLE
/en-US/docs/Web/API/HTML_Drag_and_Drop_API

### ISSUE THREAD

**Issue by rlovtangen** [mdn/sprints#2590]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

`ev.target.innerText` should probably be `ev.target.id` in the first example, to match the comment "Add the target element's id to the data transfer object"

```
<script>
function dragstart_handler(ev) {
 // Add the target element's id to the data transfer object
 ev.dataTransfer.setData("text/plain", ev.target.innerText);
}
</script>

<p id="p1" draggable="true" ondragstart="dragstart_handler(event)">This element is draggable.</p>
```
Page: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

**Comment by chrisdavidmills** [comment]
Ah yes, the first instance should be changed, you're right.

Fixed. Thanks for reporting!
