### ISSUE TITLE
ARIA 'link' role example contains invalid HTML: <span href ="..."

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2591]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
In [Using the link role](https://wiki.developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_link_role), Example 2 contains the following code:

`<span href="http://www.w3c.org" onkeydown="navigateLink(event)" onclick="navigateLink(event)" tabindex="0" id="link1" role="link" class="link">
`

@youriwims used this in a [Mozilla Developer video](https://youtu.be/mwF-PpJOjMs) and got called out for the invalid code.

Thing is, I can't easily think of a good, currently-valid use case for `role="link"`.

**Comment by chrisdavidmills** [comment]
This seemed like an interesting one, so I've had a fiddle with it:

https://wiki.developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_link_role#Examples

I've rewritten it to be a live example, get rid of several bad practices inside the JS code, add some CSS to style it to look like a link, update the HTML to get rid of the inline event handler attributes and replace `href` with `data-href` as included on the YouTube comments, and include some explanatory text on why this is such a bad idea but you can do it if you really need to.

AFAIUI, this is basically what `role="link"` is for. Does this seem better now, or are there still problems here to be addressed?
