### ISSUE TITLE
Missing word "through" in "Conclusion" paragraph && "submit" misspelled

### ISSUE THREAD

**Issue by ckashby** [mdn/sprints#2592]
# Request type

- [ ] New documentation
- [X] Correction or update

# Details
URL:
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

Grammer: missing word "through" in "Conclusion" paragraph && "submit" misspelled
"If you've worked your way ##through## these tutorials in order, you now know how to markup, style, and ##sumbit## a form.

hth,

C K Ashby

**Comment by chrisdavidmills** [comment]
Fixed, and fixed ... thanks for reporting!
