### ISSUE TITLE
Either the documentation of the following specified topic is not present or there is incorrect address is linked

### ISSUE THREAD

**Issue by Ajitesh13** [mdn/sprints#2595]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

In the documentation of [Writing xpcshell based unit tests](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Writing_xpcshell-based_unit_tests) under the topic ``` Test case registration and execution ``` there is a line ``` Adding conditions through the add_test function ``` which holds the link: (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Writing_xpcshell-based_unit_tests#Adding_conditions_through_the_add_test_function) but upon clicking it doesn't get redirected to the desired topic "Adding Conditions through the add test function" either the documentation of the desired topic doesn't exist or a wrong link is provided

**Comment by chrisdavidmills** [comment]
The heading changed, so the links became wrong. I've fixed it now; thanks for reporting!
