### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

### ISSUE THREAD

**Issue by cleverchao** [mdn/sprints#2597]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
all "Promise.prototype.allSettled()"  should be "Promise.allSettled()"

**Comment by chrisdavidmills** [comment]
The title on the page was wrong, and this was being picked up in the sidebar too. I've fixed it now; thanks for reporting!
