### ISSUE TITLE
Incorrect value informed for array.filter() result

### ISSUE THREAD

**Issue by vinibaum** [mdn/sprints#2598]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

In the page:
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filtro#Exemplo_Filtrando_entradas_inv%C3%A1lidas_para_JSON

In the example "Exemplo: Filtrando entradas inválidas para JSON", the number of entries on the new array should be 4 (four), instead of 5 (five).

...
console.log('Number of Invalid Entries = ', invalidEntries); 
// Number of Invalid Entries = 5
#####

This last "number 5" informed is wrong. The .filter() on the informed array returns a new array with 4 values (length of 4, so 4 entries...).

Thanks.

**Comment by chrisdavidmills** [comment]
I've tested it and ... yes, you are right!

I've updated it now; thanks for reporting it.
