### ISSUE TITLE
referrerPolicy Fetch fixation was published immediately

### ISSUE THREAD

**Issue by nwtgck** [mdn/sprints#2599]
Hi MDN team,

Thank you very much for your wonderful project!

I made a simple change in the "Using Fetch": diff <https://wiki.developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch$compare?from=1591724&to=1596523>. The change above is `referrer` => `referrerPolicy` But, I needed the review, so I clicked "Technical" in "Review needed?" like the following. However, my change was published immediately. I'm not sure the review was done or not.

![image](https://user-images.githubusercontent.com/10933561/71304641-00834880-240d-11ea-9eb2-15e7e62a2e2a.png)

Could you tell me whether the change: <https://wiki.developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch$compare?from=1591724&to=1596523> is correct or not? And, what should I have done to have a review?

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

**Comment by chrisdavidmills** [comment]
Hi there!

Thank you for your contribution — yes, this looks more correct than the previous text.

Changes made to MDN always go live immediately; this is the way it has always worked (although future iterations will look to change this). The review needed flags don't really do very much, except we can use them to pull up a list of all things needing a review. But we never really use this, to be honest.

**Comment by nwtgck** [comment]
@chrisdavidmills Thanks for your explanation!
