### ISSUE TITLE
/en-US/docs/Learn/HTML/Forms/Styling_HTML_forms

### ISSUE THREAD

**Issue by FabianAlvaradoDotCom** [mdn/sprints#2601]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
It is a minor thing, I believe you wanted to write "styleability" but instead you wrote "styability". Easy to find by searching with ctrl + F in the browser.

**Comment by wbamberg** [comment]
Thanks for filing! I think "styleability" is not really a word, so I rearranged it a little: https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Styling_HTML_forms$compare?locale=en-US&to=1596629&from=1596085.
