### ISSUE TITLE
/en-US/docs/Learn/HTML/Forms/UI_pseudo-classes

### ISSUE THREAD

**Issue by FabianAlvaradoDotCom** [mdn/sprints#2602]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x ] Correction or update

# Details

It is a minor thing, I believe you wanted to write "enable" but instead you wrote "ensabled". Easy to find by searching with ctrl + F in the browser.

**Comment by wbamberg** [comment]
Thanks for filing, this is fixed: https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Forms/UI_pseudo-classes$compare?locale=en-US&to=1596627&from=1596083.
