### ISSUE TITLE
/en-US/docs/Learn/HTML/Forms/Form_validation

### ISSUE THREAD

**Issue by FabianAlvaradoDotCom** [mdn/sprints#2603]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

It is a minor thing, the page is using the word "underFlow" instead of "rangeUnderFlow", in this sentence: "There are several errors that will prevent... a rangeOverflow or underFlow, a stepMismatch... "

Thanks.

**Comment by chrisdavidmills** [comment]
Thanks for pointing this out; I've just fixed it!
