### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/tab-size

### ISSUE THREAD

**Issue by BoQsc** [mdn/sprints#2608]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I would like to know the **reason and origin** behind why **initial** tab-size is chosen 8 spaces.

**Comment by chrisdavidmills** [comment]
I honestly don't know; I tried searching for the answer but couldn't find anything. I think some  search engine fu is required...or maybe ask the CSS working group?
