### ISSUE TITLE
Double downloads: Remove pre-loading of interactive example scripts

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#261]
Tasks:
- [ ] benchmark page load with preloading removed
- [ ] measure and record performance impact

Acceptance Criteria:
- [ ] pre-loading removed if a net-loss
- [ ] performance impact reported

**Comment by schalkneethling** [comment]
@atopal This has already been done and pushed to production some time ago:
https://github.com/mozilla/kuma/pull/4878

**Comment by atopal** [comment]
Hey Schalk, can you make sure the acceptance criteria are met? If not, we can leave that to next sprint.

**Comment by schalkneethling** [comment]
I reckon we will have to gather this data by looking an GA or Speedcurve around the time this PR was merged and pushed. Unfortunately I was not aware of this issue and so, I did not record any data pre or post the deployment :-/

**Comment by atopal** [comment]
There is a benchmark feature in Speedcurve that lets you compare two deployments. I'd suggest using that feature to see a diff. Hopefully there was a separate deployment for this PR alone.

**Comment by schalkneethling** [comment]
@atopal Oh neat, I was not aware of this. Will take a look.

**Comment by schalkneethling** [comment]
@atopal wondering, is this still something we want to dig into in terms of data, or should we close this and move forward? Let me know, thanks!

**Comment by atopal** [comment]
We can move on. Noting here that the real world impact as measured by 90th percentile was zero (same for median).
