### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

### ISSUE THREAD

**Issue by umarmuha** [mdn/sprints#2612]
# Request type

- [ ] Correction or update

# Details

Hi Team!
The first Example listed under the **Set** object webpage, *"Using the Set Object"*, shows that the `console.log(mySet)` in the last line outputs an array in the comments `// Set [ 1, "some text", Object {a: 1, b: 2}, Object {a: 1, b: 2} ]` . 

When I run the same code it outputs an Object {} and not an array `Set { 1, 'some text', { a: 1, b: 2 }, { a: 1, b: 2 } }` . 

What also helped is the next example going over `// convert Set object to an Array object, with Array.from` which kind of gave away that it should be an object and not array. 

Hope this correction helps. Thank you for all the hard work that goes into making this amazing documentation.

**Comment by chrisdavidmills** [comment]
I've just tested this, and from my test it returns the result of `console.log(mySet)` as `Set(4) [ 1, "some text", {…}, {…} ]`.

So it does seem to use square brackets and not curly braces from what I've seen.

I've updated the comment on the page to give a more up-to-date output, but I don't think anything else is needed here?

**Comment by umarmuha** [comment]
Hi @chrisdavidmills , thanks so much for looking into it. That's strange because when I run the Set example, listed on the [Set MDN doc page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), in Chrome dev console and VS code using node, I get the output with curly braces. Is there something that I might be doing wrong? Please advise. Yes, the comments look great and don't think anything there needs to be added.  

<img width="697" alt="Screenshot 2019-12-30 10 42 29" src="https://user-images.githubusercontent.com/21365827/71591279-5f258200-2af1-11ea-9604-8f380123c175.png">

Here is the output in VScode with node v13.5.0

<img width="465" alt="Screenshot 2019-12-30 10 43 03" src="https://user-images.githubusercontent.com/21365827/71591283-63519f80-2af1-11ea-9498-78763d9baf90.png">

Thanks!

**Comment by chrisdavidmills** [comment]
Ah, interesting. I've updated it to say that the log output is different in Chrome versus Firefox, just in case others get confused by this. I'm not sure which was is better really — it isn't an array, but then again it isn't an object literal either.
