### ISSUE TITLE
/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### ISSUE THREAD

**Issue by jjpiv** [mdn/sprints#2613]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the [Creating Hyperlinks](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks) article from the MDN Web Docs, there's a screenshot of the BBC homepage. In that image, one of the stories refers to "The tragedy of the US journalist who shot herself on TV." I've never felt triggered about the content in documentation before, and that image helped to create such a situation. Would it be possible to replace the image in question with another that doesn't contain such a morbid topic?

**Comment by chrisdavidmills** [comment]
> Would it be possible to replace the image in question with another that doesn't contain such a morbid topic?

Certainly; I've updated the screenshot.

Please accept our sincerest apologies for any hurt caused.
