### ISSUE TITLE
Broken Link in What will your website look like? page

### ISSUE THREAD

**Issue by FriedFries** [mdn/sprints#2614]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Within the [Getting started with the Web](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web) tutorial series, under the page [What will your website look like?](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like) a link to [Firefox OS Guidelines](https://developer.mozilla.org/en-US/styleguide/products/firefox-os/) page is broken and gives Error **`Not Found`** on following the link.

**Page with broken link:**

![image](https://user-images.githubusercontent.com/21522165/71446186-90dfc700-2746-11ea-8819-421d0dcd5720.png)

**Error displayed on following the link:**

![image](https://user-images.githubusercontent.com/21522165/71446200-b2d94980-2746-11ea-9280-cb27d9ce9b89.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this! I've updated it to link to the new Firefox browser design guidelines instead.
