### ISSUE TITLE
Get method description update needed?

### ISSUE THREAD

**Issue by XuHe1** [mdn/sprints#2616]
According to the result I tested, GET can contain Request body,  how to explain it ?

**Comment by chrisdavidmills** [comment]
Relevant page: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/GET

**Comment by hamishwillee** [comment]
@XuHe1 This case is actually mentioned in the [spec](https://tools.ietf.org/html/rfc7231#section-4.3.1):

> A payload within a GET request message has no defined semantics;  sending a payload body on a GET request might cause some existing implementations to reject the request.

This is much the same as saying "a GET request that has a body doesn't have any sensible meaning, so we haven't defined it. As a result, some systems will allow this and others won't.".

To my mind the docs saying `Request has body=no` is correct. I don't _think_ we should add a note about this in the docs, but happy for it to be reopened if you feel strongly that it should.

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI, I was in two minds about adding the note - some people would argue that saying you shouldn't send data in a GET request as per the sentence above is enough. If you think we should remove it let me know.

**Comment by chrisdavidmills** [comment]
@hamishwillee I think the note is useful; I've updated it a bit.

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills . You're more verbose than me, but all good :-)
