### ISSUE TITLE
/ru/docs/Web/Progressive_web_apps/Installable_PWAs

### ISSUE THREAD

**Issue by agoryachev89** [mdn/sprints#2617]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
There is a mistake:
> Эта информация **необзодима** браузеру для правильного

Instead of:
> Эта информация **необходима** браузеру для правильного

**Comment by chrisdavidmills** [comment]
Updated!
