### ISSUE TITLE
Grammar issue "nothing happen"

### ISSUE THREAD

**Issue by peterbe** [mdn/sprints#2618]
@volter commented on [Mon Dec 23 2019](https://github.com/mdn/kuma/issues/6276)

https://media.prod.mdn.mozit.cloud/attachments/2016/08/20/13779/66fccb7016e4c5dd189b35649c2bdd9f/HTTPRevved.png -- "nothing happen" in the second graph should probably read "nothing happens" (Used on https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching)

**Comment by hamishwillee** [comment]
Thanks. Fixed.
