### ISSUE TITLE
/en-US/docs/Learn/CSS/CSS_layout/Introduction

### ISSUE THREAD

**Issue by FabianAlvaradoDotCom** [mdn/sprints#2619]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [X ] Correction or update

# Details
It is a minor thing, maybe not even a real content issue. Anyway, on the page it is being explained the flex-direction, and as a total ignorant that I am, I understood by the context that the property is by default set to the flex items (children): "_**...This is due to them becoming flex items and using some initial values that flexbox gives them. They are displayed as a row, because the initial value of flex-direction is row...**_". Then in the "Flexbox" tutorial I learned that it is a property of the parent.

Thanks guys for the light you bring to the world!

**Comment by chrisdavidmills** [comment]
You've got a point here; this text is somewhat ambiguous as it was.

I've had a go at improving it; let me know what you think now.

**Comment by FabianAlvaradoDotCom** [comment]
Thanks Chris! In my humble opinion that's perfect.

**Comment by chrisdavidmills** [comment]
@FabianAlvaradoDotCom cool; lets close this one then ;-)
