### ISSUE TITLE
Nullish coalescing operator description problem?

### ISSUE THREAD

**Issue by snortblt** [mdn/sprints#2622]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The description of the [nullish coelescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) says the following:

> Contrary to the logical OR (||) operator, the left operand is returned if it is a falsy value which is not null or undefined. 

That is incorrectly worded. The logical OR operator _has_ the described behavior. The null coalescing operator works _contrary_ to that. Additionally, the way the behavior is described is also a little ambiguous; the logical OR operator returns the left operand for _any_ falsy value, not just one that isn't null or undefined.

**Comment by jadjoubran** [comment]
Was this corrected? I can't find the issue above in the live version

**Comment by chrisdavidmills** [comment]
Let's close it then
