### ISSUE TITLE
Typo in "Resizing background images with background-size" - defauilt instead of default

### ISSUE THREAD

**Issue by EdmundasD** [mdn/sprints#2625]
# Request type

- [ ] Correction or update

# Details

Link to document: [Resizing background images with background-size
](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Resizing_background_images)

First paragraph reads...

> The background-size CSS property lets you resize the background image of an element, overriding the defauilt behavior of tiling the image at its full size by specifying the width and/or height of the image. By doing so, you can scale the image upward or downward as desired.

"... overriding the **defauilt** behavior of ..."

_Expected:_ default
_Actual:_ defauilt

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
