### ISSUE TITLE
Error in onMessage page?

### ISSUE THREAD

**Issue by geajack** [mdn/sprints#2626]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This page implies that the second argument to `onMessage`, the `sender` object, is always of type `MessageSender`, but that doesn't seem to be the case anymore. If a message is sent to the runtime from the popup of a page action button with this code using `browser.runtime.sendMessage()`, then the sender object, on Firefox 71, looks like this:
```
{
  "id": "example@example.com",
  "url": "moz-extension://f4e1d77d-959c-4009-8bbd-d82a27aed1e3/popup/index.html",
  "envType": "addon_child",
  "extensionId": "example@example.com",
  "contextId": 274877912826
}
```
This does not fit the schema described in the [MessageSender](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/MessageSender) docs, which doesn't mention the `envType` or `contextId` fields, and which describes a field called `id` which seems to be called `extensionId` in practice.

**Comment by chrisdavidmills** [comment]
Relevant page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

**Comment by rpl** [comment]
@rebloor I just noticed this issue and `envType`, `extensionId` and `contextId` are properties only used internally (as part of the WebExtension framework's messaging internals), they are not part of the schema and they should ideally not be send to the extension.

In my opinion we should not document them explicitly as part of the API reference (on the contrary it may be more reasonable to file an issue on bugzilla to look into removing them from the data sent to the extension code), they are an implementation detail that is subject to change and we should not suggest the extension developers to use them.

**Comment by rebloor** [comment]
Thanks, @rpl, do you concur @chrisdavidmills? Should I raise the Bugzilla to remove these items? Or do we need to consult with anybody else?

**Comment by chrisdavidmills** [comment]
@rpl knows this stuff much better than I do ;-)

**Comment by rebloor** [comment]
@rpl Sorry for the delay on this one, I've now created [1628178](https://bugzilla.mozilla.org/show_bug.cgi?id=1628178).
@chrisdavidmills Are you happy for me to close this one, as it is not a documentation issue?

**Comment by chrisdavidmills** [comment]
@rebloor , yup, let's close.

**Comment by Nickwiz** [comment]
My 50¢. As people likely log this on occasion the API documentation on `developer.mozilla.org` should include some note about them *until they are removed*.

As it is now; seeing the properties one are likely to navigate to the runtime.MessageSender documentation looking for what they are – only to find nothing about it. Perhaps double checking if one are looking at the correct object in the documentation, checking code once more, then search the web for why and what it is - only to (hopefully) find that *it should not be sent, but it is* … i.e. this or linked bug.

That's a rather long and messy route for something that could be stated with one simple sentence in the API documentation.

E.g. at bottom of *Type* after *tlsChannelId*, something in the direction of:

*- Note: other properties might be present, but these are for internal use, can change or be removed at any time and should not be used. [#BUGNR]*
