### ISSUE TITLE
Organizing your CSS: Missing CSS Class in Non-OOCSS Example Code

### ISSUE THREAD

**Issue by marklchaves** [mdn/sprints#2627]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi,

## Issue 

In the [Organizing your CSS article](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Organizing), the **non-OOCSS** example code seems to be missing a class.

`
.list-item img {
  font-size: .8rem;
}
`

## Fix

Add the code snippet above to the example at the spot highlighted in the attached screen grab.

![mdn-oocss-example-missing-class-2jan2020](https://user-images.githubusercontent.com/4658423/71647958-e3b61180-2d38-11ea-930c-f4ed96c4f219.png)

**Comment by chrisdavidmills** [comment]
I think what's there is correct already. The previous text says

> The differences between these two components is that the list-item has a bottom border, and images in comments have a border whereas list-item images do not.

So `.list-item img` specifically does **not** have a rule setting a `border` on it (which I think is what you meant, rather than a `font-size`?)

**Comment by marklchaves** [comment]
Yikes. Thanks for the quick reply, @chrisdavidmills. My mistake. Apologies for the trouble. Keep up the great work.

mark

**Comment by chrisdavidmills** [comment]
> Yikes. Thanks for the quick reply, @chrisdavidmills. My mistake. Apologies for the trouble. Keep up the great work.

No worries, if you are unsure, then it's always good to check!
