### ISSUE TITLE
/en-US/docs/Web/HTML/Element/a

### ISSUE THREAD

**Issue by pmpinto** [mdn/sprints#2629]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
There's a space missing between `address.` and `Content`. Screenshot attached.

![Screen Shot 2020-01-02 at 14 29 06](https://user-images.githubusercontent.com/4265830/71671920-4379e000-2d6c-11ea-9890-391104e3ce91.png)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
