### ISSUE TITLE
Queries about wording on parseInt page

### ISSUE THREAD

**Issue by Lebosk** [mdn/sprints#2630]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello

I have some remarks for the documentation of the **parseInt** function. I am quite new to Javascript, so I hope there is no misunderstanding on my side.

The _Return value_ is described as follows:

> An integer parsed from the given string.
> 
> If the radix is smaller than 11, and the first non-whitespace character cannot be converted to a number, NaN is returned.

Well, this is not wrong, but if I am not mistaken, this is not as precise as it could be. Actually, NaN is _always_ returned, if the first non-whitespace character cannot be converted to a number, regardless if the radix is smaller than 11 or not. It only depends on whether the character can be interpreted as a number according to the given radix or not.
For example:
```
parseInt('8F', 6)  → NaN
parseInt('F1', 12) → NaN
```
and
`parseInt('F1', 16) → 241`

For the same reason I consider the following sentence, which can be found in the _description_ part, to be wrong:

> If the first character cannot be converted to a number, parseInt returns NaN unless the radix is bigger than 10.

Again, I believe the "unless the radix is bigger than 10" is wrong and misleading.

BTW, the German version describes this part better. However, the German version misses some other details which the English version includes:
- English: "If parseInt encounters a character that is not a numeral in the specified radix, it ignores it and all succeeding characters and returns the integer value parsed up to that point."
German: "Wenn parseInt ein Zeichen findet, welches keine Ziffer im spezifizierten Zahlensystem ist wird dieses und alle folgenden Zeichen ignoriert.". So, the German Version misses the part "and returns the integer value parsed up to that point."
- The part with the signs (+-) is missing completely.
- I find "If not NaN, the return value will be the integer that is the first argument taken as a number in the specified radix." better understandable than the German "Wenn nicht NaN zurückgegeben wird, ist der Wert des ersten Arguments eine gültige ganze Zahl im entsprechenden Zahlensystem.".

Best regards,
_Jochen_

**Comment by chrisdavidmills** [comment]
Relevant page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by Elchi3** [comment]
Thanks for filing this issue against MDN wiki content. I did some updates, but everyone is welcome to improve the page in the wiki directly.

> Well, this is not wrong, but if I am not mistaken, this is not as precise as it could be. Actually, NaN is always returned, if the first non-whitespace character cannot be converted to a number, regardless if the radix is smaller than 11 or not. It only depends on whether the character can be interpreted as a number according to the given radix or not.

Updated the section to be a bit less ambiguous https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Return_value

> For the same reason I consider the following sentence, which can be found in the description part, to be wrong
> Again, I believe the "unless the radix is bigger than 10" is wrong and misleading.

I've removed that bit of the sentence.

> BTW, the German version describes this part better. However, the German version misses some other details which the English version includes:

We (MDN staff) don't have the bandwidth or the knowledge to look after localizations. Feel free to improve the translation yourself.

Thanks for your issue!
