### ISSUE TITLE
[MathML] Fx 73 updates (low priority)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2631]
# Trello

https://trello.com/c/LMs5lI6w/228-mathml-updates-fx-73

# Acceptance criteria

1. - [ ] [Disable the MathML mfenced element by default in all builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1603773)

**Comment by Elchi3** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/73#MathML
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced
https://github.com/mdn/browser-compat-data/pull/5458
