### ISSUE TITLE
[CSS] Proprietary features, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2632]
# Trello

https://trello.com/c/ylLyrwja/12-proprietary-webkit-moz-features-fx-73

# Acceptance criteria

1. - [ ] [Drop -moz-touch-enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1486964)

**Comment by jmswisher** [comment]
Updated (-moz-touch-enabled)[https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-moz-touch-enabled] with a warning that it's unsupported as of 73, and to use pointer: coarse (linked) instead.
