### ISSUE TITLE
[CSS] SVG features, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2633]
# Trello

https://trello.com/c/5JYSjHmH/241-css-svg-stuff-fx-73

# Acceptance criteria

1. - [x] [make SVGTextFrame avoid getting glyph advances that cross text frames, and re-enable letter/word-spacing](https://bugzilla.mozilla.org/show_bug.cgi?id=1600855) (same thing that was added to Fx 72, but then backed out)

**Comment by rachelandrew** [comment]
https://github.com/mdn/browser-compat-data/pull/5469 for the BCD, have also moved the mention from the 72 notes to the 73 notes.

**Comment by chrisdavidmills** [comment]
I've chcked the rel note, and reviewed and merged the PR, plus I see you've set the bug to DDC. We can close this; thanks!
