### ISSUE TITLE
[CSS] text, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2634]
# Trello

https://trello.com/c/FdS8hdQo/97-css-text-eg-text-text-decoration-fx-73

# Acceptance criteria

1. - [ ] [Implement CSS3 text module text-underline-position](https://bugzilla.mozilla.org/show_bug.cgi?id=770780)
2. - [ ] [Let CSS text-underline-position property ride the train to release](https://bugzilla.mozilla.org/show_bug.cgi?id=1606997) (says fixed in Fx 74, but the plan is to uplift it to Fx 73, according to the [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/FgKLdwRhCyA))

**Comment by jmswisher** [comment]
According to [this Bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1606997#c9) this feature is being deferred to 74.

**Comment by chrisdavidmills** [comment]
> According to this Bugzilla comment this feature is being deferred to 74.

Ah, cool. I've updated the MDN content roadmap accordingly

**Comment by chrisdavidmills** [comment]
@jmswisher I wrote https://github.com/mdn/sprints/issues/2741, which supercedes this, therefore I'll close this and assign you to the new one.
