### ISSUE TITLE
[CSS] Logical properties, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2635]
# Trello

https://trello.com/c/1CtY17he/51-css-logical-properties-level-1-fx-73

# Acceptance criteria

1. - [x] [Add overscroll-behavior-{block,inline} properties in addition to overscroll-behavior-{x,y}](https://bugzilla.mozilla.org/show_bug.cgi?id=1453472) (behind a pref, but probably worth documenting anyway)

**Comment by rachelandrew** [comment]
Looks like the compat data doesn't recognise Firefox 73 as a thing yet https://github.com/mdn/browser-compat-data/pull/5460

**Comment by rachelandrew** [comment]
I've also updated the other overscroll behavior property pages as they were showing out of date info.

**Comment by chrisdavidmills** [comment]
Thanks!

for the BCD check fail, you'll have to add the new browser versions to the files at https://github.com/mdn/browser-compat-data/tree/master/browsers so the system recognises them

**Comment by chrisdavidmills** [comment]
@rachelandrew just a small ping about this one, to see if you looked at getting that BCD PR sorted out, and if there are any other page updates to do?

**Comment by chrisdavidmills** [comment]
@rachelandrew oooh, and did you submit an update to the https://github.com/mdn/data data repo for these properties?

**Comment by rachelandrew** [comment]
yeah, this was the one that ended up a mess so I redid it: https://github.com/mdn/browser-compat-data/pull/5510 already merged.

**Comment by rachelandrew** [comment]
and the data one you merged: https://github.com/mdn/data/pull/406

or am I confused?

**Comment by chrisdavidmills** [comment]
> or am I confused?

No, not at all — it's more that I am forgetful ;-)

So this is fine then. I need to do an mdn-data npm package release so we can get the /data updates showing on MDN, but apart from that we are all good.
