### ISSUE TITLE
[WebAPI] Form-related features, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2637]
# Trello

# Acceptance criteria

1. - [x] [Implement form.requestSubmit()](https://bugzilla.mozilla.org/show_bug.cgi?id=1552301)

**Comment by a2sheppy** [comment]
The documentation is now written for this:

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit

I also updated the main page for the interface to include it:

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement

Needs a BCD update but my BCD repo is borked and I can't figure out how to fix it. Will update the BCD data asap.

**Comment by a2sheppy** [comment]
Submitted [PR 5488](https://github.com/mdn/browser-compat-data/pull/5488)
