### ISSUE TITLE
[WebAPI] ReadableStreams, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2638]
# Trello

https://trello.com/c/MJpfsY0x/28-readablestreams-api-fx-73

# Acceptance criteria

1. - [x] [Implement ReadableStream.prototype.pipeTo and pipeThrough](https://bugzilla.mozilla.org/show_bug.cgi?id=1502355) (this was documented a while ago, but not much work, especially if it is currently behind a pref ;-) )

**Comment by a2sheppy** [comment]
Issue #1 (pipeTo and pipeThrough) was removed from 73 around three weeks ago, as the patch turned out to only be a stub. I don't know if they expect to complete it or not, but currently it's state is REOPENED.

**Comment by chrisdavidmills** [comment]
Right; we'll cancel this one off then. Closing.
