### ISSUE TITLE
[WebAPI] DOM general tasks, Fx 73

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2639]
# Trello

https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-73

# Acceptance criteria

1. - [x] [window.innerWidth/innerHeight should return the dimensions of the layout viewport](https://bugzilla.mozilla.org/show_bug.cgi?id=1514429)
2. - [x] [Should we make default of "wheel" (and "DOMMouseScroll", "MozPixelMouseScroll") event listeners on root "passive"?](https://bugzilla.mozilla.org/show_bug.cgi?id=1526725)
3. - [x] [VideoPlaybackQuality corruptedFrames deprecated](https://bugzilla.mozilla.org/show_bug.cgi?id=1602163)

**Comment by a2sheppy** [comment]
The first one looks pretty easy; half a day tops.

The second one is nightly-only, so would just get a mention on the experimental features page for now. Even if it were shipping in 73 release, it would only need a quick mention in release notes and a BCD update to add a note to the affected events. Quarter day or so tops, if so.

**Comment by chrisdavidmills** [comment]
Updating estimate, as I reckon you are the king of fast ;-)

**Comment by Elchi3** [comment]
I think https://bugzilla.mozilla.org/show_bug.cgi?id=1602163 should be added to this task.

**Comment by chrisdavidmills** [comment]
> I think https://bugzilla.mozilla.org/show_bug.cgi?id=1602163 should be added to this task.

Added. Thanks; I missed this one. I've put the estimate back up to 1 too, just in case.
