### ISSUE TITLE
[HTTP] feature policy, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2640]
# Trello

https://trello.com/c/1NkwWH1e/88-feature-policy-fx-73

# Acceptance criteria

1. - [x] [Enable Feature Policy & Permission Delegation for Release 74](https://bugzilla.mozilla.org/show_bug.cgi?id=1617219)

Previous ACs before revert happened in Fx 73:

1. - [x] [Restrict nested permission requests (camera/microphone/geolocation/screensharing) with Feature Policy](https://bugzilla.mozilla.org/show_bug.cgi?id=1483631)
2. - [x] [[Bug 1600883] Enable Feature Policy allow attribute and permission delegation by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1600883)

**Comment by a2sheppy** [comment]
I take it this means I have to learn more about Feature Policy now. :)

**Comment by a2sheppy** [comment]
If I read things correctly, this will require no changes for #1, and #2 will require only a release note entry and a BCD update to note that the Feature Policy `allow` attribute is finally available by default in Firefox 73.

**Comment by chrisdavidmills** [comment]
Estimate updated;  if you need any help on this, I think @Elchi3 did the previous  work on it  ;-)

**Comment by chrisdavidmills** [comment]
@a2sheppy sorry sheppy, but it looks like this has been backed out due to regressions, and will probably actually be enabled in 74: see https://bugzilla.mozilla.org/show_bug.cgi?id=1610572.

I've removed mention of it from the Fx 73 release post, and moved the rel note you added to the 73 rel notes, to 74.

Can you scout around and revert any other changes you made as part of this US?

Thanks!

**Comment by a2sheppy** [comment]
Yep. Fortunately there were very few changes made for this; just need to remove the version from Firefox in the BCD records and remove it from Fx for devs. And I guess put it back on the experimental features page, if I remembered to remove it. :)

**Comment by jmswisher** [comment]
@a2sheppy @chrisdavidmills : Keep this issue open, or make a new one for re-adding stuff when the feature ships?

**Comment by chrisdavidmills** [comment]
Once @a2sheppy has reverted the above mentioned bits, I'd prefer to close this one, and then open a new US once it is actually shipping.

**Comment by a2sheppy** [comment]
Reverted: https://github.com/mdn/browser-compat-data/pull/5661

**Comment by chrisdavidmills** [comment]
Turns out feature policy is being turned on in Fx 74. @a2sheppy, since you already did this work, can you reapply your BCD changes and stuff, but for support starting in Fx 74? The rel note is already in the right place, I think it is mainly BCD that needs a bit of work. See the top of the issues for the new bugzilla bug.

**Comment by a2sheppy** [comment]
You want this done this sprint?

**Comment by chrisdavidmills** [comment]
Yes. The 74 release is at the end of this sprint.

**Comment by chrisdavidmills** [comment]
@a2sheppy
