### ISSUE TITLE
[HTTP] CORS, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2641]
# Trello

https://trello.com/c/0QD3sJXc/151-cors-enhancements-fx-73

# Acceptance criteria

1. - [x] [Make CORS errors errors, not warnings, in the console](https://bugzilla.mozilla.org/show_bug.cgi?id=1602093)

**Comment by Elchi3** [comment]
I've completed this, see https://bugzilla.mozilla.org/show_bug.cgi?id=1602093#c4
