### ISSUE TITLE
[WebExt] Storage, legacy tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2643]
# Trello

https://trello.com/c/Pw66h6fb/56-storage-api-related-tasks-fx-71

# Acceptance criteria

1. - [x] [Enable Extension Storage actor in Addon Debugger Toolbox by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1585499) (landed in Fx 71)
2. - [x] [Implement "chrome.storage.managed"](https://bugzilla.mozilla.org/show_bug.cgi?id=1230802) (originally worked on in 67 cycle, but documentation needs improvement; see [Will's comments](https://github.com/mdn/browser-compat-data/pull/4763#pullrequestreview-283789197)) (landed in Fx 70, but there seemed to be a lot of difficulty in working out how to document this)

**Comment by rebloor** [comment]
For Implement "chrome.storage.managed" the following changes have been made:

* details added to the [Fx 70 release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70#Developer_tools)
* note added to the [Storage API page](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage)—last paragraph in the introduction
* section added to the [Extension Workshop Debugging page](https://extensionworkshop.com/documentation/develop/debugging/#debugging-sidebars)—pending publication, see [pull request](https://github.com/mozilla/extension-workshop/pull/552)

**Comment by rebloor** [comment]
@chrisdavidmills for _Implement "chrome.storage.managed"_  it would appear that "all" we need is new manifest key page for `storage` (which defines the location of a schema file defining the content of managed storage).  Then update the `stored.managed` API page to indicate that, optionally, you can define the content of manage storage using a schema to provide compatibility with Chrome. To be sure, I've got a information needed requesting with Mike Kaply on the Bugzilla to confirm.

**Comment by chrisdavidmills** [comment]
@rebloor great progress, thanks! I am really relieved that we've got this one moving forward.

**Comment by rebloor** [comment]
@chrisdavidmills I have confirmed with Mike Kaply that "we have no need to add any documentation about managed_schema except, perhaps, to update the compatibility tables to make it clear that we don't support it." However, to do this I would need to create a manifest key page for 'storage'. OK, or leave it out completely?

**Comment by chrisdavidmills** [comment]
It seems to me that we should mention it. We aren't necessarily just documenting Fx's implementation  of WebExt, and if people creating Chrome extensions come looking at our pages, they might get confused at its absence? I'd create a page for it.

**Comment by rebloor** [comment]
I will do so.

**Comment by chrisdavidmills** [comment]
@rebloor thanks!

**Comment by rebloor** [comment]
@chrisdavidmills  A new page has been added to MDN to describe the [storage](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/storage) manifest key, with compatibility data pending in [PR 5575](https://github.com/mdn/browser-compat-data/pull/5575). Waiting on feedback from Mike Kaply that changes are sufficient/complete.

**Comment by rebloor** [comment]
Mike K has confirmed the changes for _Implement "chrome.storage.managed"_  via comment on the bug, now waiting for compatibility data PR to be merged.
