### ISSUE TITLE
[WebExt] Sidebar API, Fx 73 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2645]
# Trello

https://trello.com/c/kpSpr7Fv/243-sidebar-api-enhancements-fx-73

# Acceptance criteria

1. - [ ] [add sidebar.toggle api](https://bugzilla.mozilla.org/show_bug.cgi?id=1453355)

**Comment by rebloor** [comment]
For "add sidebar.toggle api": compatibility data changes submitted ([Add toggle to the sidebarAction API](https://github.com/mdn/browser-compat-data/pull/5474)), function added to the [sidebarAction](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction) API page and [sidebarAction.toggle()](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/toggle) page created, and details added to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/73#API_changes). Pinged Shane Caraveo to request review.

**Comment by rebloor** [comment]
Shane Caraveo has okayed the "add sidebar.toggle api" changes on MDN, now waiting for the compatibility data PR to be approved.

**Comment by rebloor** [comment]
The compatibility data PR has been merged, completing add sidebar.toggle api and this issue.
