### ISSUE TITLE
/en-US/docs/Web/CSS/Containing_block

### ISSUE THREAD

**Issue by alattalatta** [mdn/sprints#2648]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
An image it had is broken:

![주석 2020-01-05 005250](https://user-images.githubusercontent.com/9212605/71768025-d75ad000-2f55-11ea-9a4e-51e740513441.png)

Based on the context (and if my memory is correct), the image was for a diagram of CSS box model.
This is affecting other localized versions as well.

**Comment by chrisdavidmills** [comment]
Thanks for reporting!

I've replaced it with a non-broken image.
