### ISSUE TITLE
/ru/docs/Learn/JavaScript/Первые_шаги/A_first_splash

### ISSUE THREAD

**Issue by artby04** [mdn/sprints#2650]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

In Russia version in JS Tutorial a href dont work( same as next page and others)

**Comment by SphinxKnight** [comment]
Thanks for reporting, I fixed the links (the issue was due to the URL fragment being different between English and Russian)
