### ISSUE TITLE
request for navigation user media api documentation page

### ISSUE THREAD

**Issue by whizyrel** [mdn/sprints#2652]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

on hover the tooltip says documentation has not yet been written... consider contributing...
[link](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)

![Screenshot from 2020-01-05 16-50-22](https://user-images.githubusercontent.com/38155356/71782549-8097d980-2fdb-11ea-92da-2ecfaf7b227e.png)

**Comment by chrisdavidmills** [comment]
That's because it hasn't been written yet.

**Comment by whizyrel** [comment]
I requested to write it and not to complain
