### ISSUE TITLE
[WebExt] Mention in the content scripts docs some additional Chrome incompatibilities 

### ISSUE THREAD

**Issue by rpl** [mdn/sprints#2656]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There are some incompatibilities between Firefox and Chrome related to the WebExtensions content scripts implementation which are often source of confusion for the extension developers.

We do have docs that mention and provide advice for some of those incompatibilities (e.g.  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts for the incompatibilities between the Firefox's "Xray wrappers" vs. the Chrome's "isolated worlds"), but it seems that some other incompatibilities are not mentioned explicily (or not linked and/or easily reachable from [WebExtensions/Chrome_incompatibilities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities) and [WebExtensions/Content_scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts)). 

In particular I took a look to the WebExtensions docs on MDN but I wasn't able to find any reference to the following ones:

- `this !== window` (the issue tracked by [Bug 1208775](https://bugzilla.mozilla.org/show_bug.cgi?id=1208775))

- properties added to the `window` object from the content script may be lost during navigation (the issue tracked [Bug 1525400](https://bugzilla.mozilla.org/show_bug.cgi?id=1525400))

- the content scripts are not destroyed and re-injected when a webpage is going back and forth the history and so the content script may have to listen for the `"pageshow"`/`"pagehide"` events
 (this is often surprising because on Chrome the content scripts are always destroyed when the webpage is navigated away, and then re-injected again if the the user navigated back to it through the history, as a side note this doesn't have an Bugzilla issue, it is mentioned in some of the other bugzilla issues related to content scripts as the intended behavior on Firefox for that scenario)

**Comment by rebloor** [comment]
@rpl  I have added 2 items to the [Miscellaneous incompatibilities](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#Miscellaneous_incompatibilities) section on the Chrome incompatibilities page. These cover "Sharing variables between content scripts" (point 1 from your list) and "Content script lifecycle during navigation" (points 2 and 3 from the list). Please let me know if these changes are suitable or if you think further updates are needed. Thanks!

**Comment by rebloor** [comment]
@rpl A reminder about this one, do you have any comments on the changes?

**Comment by rpl** [comment]
> @rpl A reminder about this one, do you have any comments on the changes?

:+1: lgtm, thanks!

**Comment by rebloor** [comment]
Thanks for the confirmation @rpl
