### ISSUE TITLE
Replace mdn-compat-data-helper with GitHub Actions

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2662]
As a maintainer of BCD, I want to replace the repo's labeling bot with GitHub Actions and [actions/labeler](https://github.com/actions/labeler), so I don't have to manage a long-running process for assigning labels.

## Acceptance criteria

- [ ] GitHub Actions assigns labels to BCD PRs based on their file name and in-repo configuration
- [ ] compat-data-helper app is removed from Glitch
- [ ] [compat-data-helper](https://github.com/mdn/browser-compat-data/tree/master/.github/compat-data-helper) code is removed from the BCD repo

## Notes

In 2019, I experimented with wrapping our Probot app with GitHub Actions. It's messy and I've written this user story assuming that we just don't do that. Cutting out Probot and going with GitHub Actions directly will be more maintainable.

The current app comments when a PR contains 300 or more files, warning that it can't guarantee that all applicable labels have been applied. The GitHub Actions file labeler doesn't support this feature yet, so completing this user story would cause us to lose that feature.

Upon completion of this user story, I'll need to open an issue on BCD to make some follow up decisions about next steps with our BCD automation, namely: 1) whether we should fork the official actions/labeler or make our own follow-up actions and 2) whether we need separate repo(s) for BCD-specific actions (GitHub Actions encourages separate repos, for a bunch of interesting reasons).

Completing this user story will supersede https://github.com/mdn/browser-compat-data/issues/5119.

**Comment by ddbeck** [comment]
Following https://github.com/mdn/browser-compat-data/pull/5493 and https://github.com/mdn/browser-compat-data/pull/5496, I've discovered that GitHub Actions doesn't support this particular use case well (or perhaps at all). There's some good news in general about the future of GitHub Actions for BCD, but some bad news when it comes to automating our GitHub PR or issues workflow.

## The problem

I tested the changes for https://github.com/mdn/browser-compat-data/pull/5493 on my fork of BCD, where the GitHub Actions workflow ran flawlessly. After #5493 was merged however, the workflow ended prematurely with an error: `Resource not accessible by integration` ([see in context](https://github.com/mdn/browser-compat-data/pull/5495/checks?check_run_id=389286632#step:2:5)). After a short investigation, I learned the immediate cause of the problem: the GitHub API token used by the workflow did not have the permissions required to write changes to the PR (i.e., it does not have the permission to assign a label).

For workflows associated with pull requests, the workflow gets different permissions depending on whether the branch to be merged is on the repo or on a fork of the repo. If the branch is on the repo, then the workflow has full API access to the repo. If the branch is on a fork, then the workflow has read-only API access to the repo. In other words, a PR for `repo:topic-branch` merging into `repo:master` has write access, but a PR for `fork:topic-branch` merging into `repo:master` has read-only access.

Other users of the `actions/labeler` action reported this problem as well (see https://github.com/actions/labeler/issues/12), further confirming the problem.

## Notes on GitHub Actions (bad news, good news)

This section is mostly for background. If you're not interested in learning more about the ins-and-outs of GitHub Actions, skip ahead to _Next steps_.

I spent the better part of yesterday morning _closely_ reading the GitHub actions documentation and issues that seemed to address our problem. Unfortunately, it doesn't look like there's a _good_ option yet. There's a few areas that show promise, though only a few are actionable today.

Some notes follow on potential workarounds and their discontents:

* While it's possible to use a personal access token to grant full permissions to all forks, you can't safely do this, as the token could be trivially exfiltrated for malicious use. For instance, you could write a script to print the token in clear text, add that script to a workflow, open a pull request, recover the token, and then do literally whatever you want to the repo, including merging malicious code. If there were labels-only permissions, this might be a reasonable risk to accept, but repo permissions are not that fine grained and there's no indication this is forthcoming.
* You can persist data in workflow runs with artifacts, but you can't share that data between workflows yet. Though the docs imply that this is a forthcoming feature, but it's not there yet. If it were the case, we could save an artifact with a list of files modified in the PR and the PR number, then use a cron workflow on the repo to update PRs every few minutes. Doing this now would require S3 or similar, some new custom code, and S3 permissions risk; generally, it'd be substantially more complicated than just running the Probot app. See [_Sharing data between workflow runs_](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#sharing-data-between-workflow-runs) to learn more about this.
* There's a lot of agitation for [some kind of "trusted workflow" mode](https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/m-p/33839), where forks could get full write permissions to use pre-approved workflows. This would be the ideal thing, but not only does this feature not exist, as far as I can tell there have been no signals from GitHub that they're even considering such a thing.
* In https://github.com/actions/labeler/issues/12, there's a suggestion to use an alternative action that runs periodically to check PRs and apply labels. Unfortunately, that action has some additional limitations and doesn't seem to be maintained particularly actively. It would be a distinct step backward from the Probot solution we use today, though it does demonstrate a _pattern_ for hosting repo automation in GitHub Actions, even if we can't use the pull request events.

My general takeaway here is that GitHub Actions is, ironically, not built with the fork-and-PR open source model in mind, when it comes to repo automation. It's well suited to PRs within repos, but not across them.

The good news is that GitHub Actions will probably work very well for BCD tasks that don't require write-access to the repo. For example, parallelizing linting and testing with GitHub Actions would be a snap, since it doesn't require anything other than read access to the source.

## Next steps

As written, this user story cannot be completed. To complete this work for the sprint, I think we should change the scope. Instead, we should make a decision about what to do with compat-data-helper, write a follow-up user story, and plan that work in one or more future sprints.

There are a few alternative approaches that I think are worth considering:

1. Continue to use the Probot app as-is. The Probot app code requires some minor updates, but it's otherwise fine. We can continue to run it on Glitch and let it be. It's possible that simply delaying (waiting for improvements to GitHub Actions) might lead to an easier resolution later.
2. Regularize the Probot app's deployment. For example, we could work with the MDN dev team to move it off Glitch and onto some more formally managed service (e.g., AWS Lambda or EC2). Unfortunately, this would require the already too-limited time of the dev team.
3. Write our own scheduled GitHub Actions action and workflow to periodically update PRs with labels. This would be less responsive than something that relies on PR events (i.e., label assignment would take some minutes), but it would replace the Glitch deployment. This would require some new code to be written, but some of the Probot code could be reused.

And that's what I've got. A bit disappointing, but at the same time, I'm glad we tried this out on something low stakes before attempting something more complex.

**Comment by jmswisher** [comment]
@ddbeck Can you write a new user story, per your comments?

**Comment by ddbeck** [comment]
I can do that, yes.

@Elchi3, did you want to respond to my write up? Or should I make a decision on my own?

**Comment by Elchi3** [comment]
> Continue to use the Probot app as-is. The Probot app code requires some minor updates, but it's otherwise fine. We can continue to run it on Glitch and let it be. It's possible that simply delaying (waiting for improvements to GitHub Actions) might lead to an easier resolution later.

I think this is the way forward that makes sense to me for now. If nothing moves on the GitHub Action side of things, we can consider your other options. For the updates, a new user story would be good I think.

**Comment by ddbeck** [comment]
OK, I've opened https://github.com/mdn/sprints/issues/2779 for Alfa-Bravo. This issue is _done_ done.
