### ISSUE TITLE
MDN content error: Srcset attribute can be used with both picture and video elements?

### ISSUE THREAD

**Issue by aliasflavius** [mdn/sprints#2664]
[*] Correction or update

# Details
The MDN page for the source element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) says:

> The srcset attribute has an effect only when the <source> element is the direct child of a \<picture\> or \<video\> element.

I have checked the specification of the video element ( [https://html.spec.whatwg.org/multipage/media.html#the-video-element](url) ) but I cannot find any mention of a `srcset` attribute for the `source` element when it's a child of a `video` parent.

In fact, if you check the specification of the source element (https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element) they clearly state that `srcset` can only be used with a picture element:

> The srcset attribute contributes the image sources to the source set, if the source element is selected.

Unless I misunderstood something, I think the MDN page for the `source` element needs to have this statement corrected, to put it in line with the specification, by making it clear that the `srcset` attribute can only be used with picture elements, not video elements too.

**Comment by chrisdavidmills** [comment]
>  I think the MDN page for the source element needs to have this statement corrected, to put it in line with the specification, by making it clear that the srcset attribute can only be used with picture elements, not video elements too.

Ah yes, you are absolutely right! I've updated the offending line to only mention `<picture>`.

Thanks for reporting!
