### ISSUE TITLE
Math.round() examples still need some work

### ISSUE THREAD

**Issue by jcottrell** [mdn/sprints#2665]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Under *Demonstrative Implementation* the `vanilla_round` function calculates `y` but does not use it. Further, the function does not accurately reflect how Math.round works, as the description states it should.

Instead I would suggest the following for the implementation of `vanilla_round`:

```
function vanilla_round(x) {
  if (x > 0) {
    var y = Math.floor(x + 0.5);
  } else {
    var y = Math.ceil(x - 0.5);
  }
  return Math.floor(y);
}
```
Although this could be streamlined or updated, I thought this best reflected the simple teaching style of the previous example's claim to explain Math.round.

In the description after `vanilla_round` there is a reference to the modulus operator. Neither the current or my suggested implementation uses it so I suggest that the sentence mentioning modulus be removed.

The `round_to_precision` implementation does not consider rounding of negative numbers. Either that should be clarified or the following may serve to also implement precision rounding for negative numbers:

```
function round_to_precision(x, precision) {
  if (x > 0) {
    var y = +x + (precision === undefined ? 0.5 : precision / 2);
  } else {
    var y = +x - (precision === undefined ? 0.5 : precision / 2);
  }
  return y - (y % (precision === undefined ? 1 : +precision));
}
```

Lastly, it may be helpful to mention that there are different rounding standards and the emphasis here is to offer examples consistent with the current implementation of Math.round.

**Comment by chrisdavidmills** [comment]
Example in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round#Demonstrative_Implementation

**Comment by jadjoubran** [comment]
@chrisdavidmills  I'll take this one too 👋

**Comment by chrisdavidmills** [comment]
Assigned; thanks @jadjoubran !

**Comment by jadjoubran** [comment]
I can see that the **demonstrative example** has been removed on May 8, 2020, 1:18:46 AM

Do you think we should bring it back with the changes? The current text already offers explanation of how the function works
I would be worried to have the example and having people copy paste that into their code instead of using Math.round. What do you think?

**Comment by chrisdavidmills** [comment]
@jadjoubran sounds reasonable.

**Comment by jadjoubran** [comment]
Just to double check, you mean the page is good the way it is?

**Comment by chrisdavidmills** [comment]
Yes, I mean leave it as is. The demonstrative example was complex and confusing, imo.

Which means we can close, I think? W00t!
