### ISSUE TITLE
Sending form data, Python Example. Another suggestion for beginners?

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#2666]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

Reference the"<a href="https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#On_the_server_side_retrieving_the_data">Sending form data</a>" article, sub-section "Example: Python", ending Note box.
Another suggestion to help beginning students. 

For this example to work, with python-flask, the files "[form.html](https://github.com/mdn/learning-area/blob/master/html/forms/sending-form-data/templates/form.html)" and "[greeting.html](https://github.com/mdn/learning-area/blob/master/html/forms/sending-form-data/templates/greeting.html)" must be in a sub-folder named "templates" of the folder containing the "[python-example.py](https://github.com/mdn/learning-area/blob/master/html/forms/sending-form-data/python-example.py)" file.

Again, it took me some time researching and reading, to "realize" what should have been obvious to me, but if you don't know, you don't know. A short sentence added may benefit other students after me. 
Again thanks, these mdn web docs tutorials are amazing!

_BTW, I got the "free" MAMP to work without the MAMP PRO, [see comment here](https://github.com/mdn/sprints/issues/2660#issuecomment-572179257)._

**Comment by chrisdavidmills** [comment]
No problem with being explicit about this; I've added a note in parens just above where it mentions to template files to cover this.

Thanks again!
