### ISSUE TITLE
/ru/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Полный_список_типов_MIME

### ISSUE THREAD

**Issue by Trunutslover** [mdn/sprints#2669]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

application/x-rar-compressed MIME type is deprecated, IANA displays application/vnd.rar is valid for .RAR now

**Comment by SphinxKnight** [comment]
for context: found authoritative source in https://www.iana.org/assignments/media-types/application/vnd.rar

**Comment by SphinxKnight** [comment]
Thanks for reporting, I've edited both the Russian and English page.

Do not hesitate to edit pages by yourself as MDN is a wiki :)
