### ISSUE TITLE
/en-US/docs/Web/CSS/repeating-conic-gradient - the frame with MDN's usual best habit of providing CSS demo isn't on that page

### ISSUE THREAD

**Issue by on-slm** [mdn/sprints#2672]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I think that probably somebody already noticed it a while ago, because before cca 1-2 hours, there were no notice "Draft This page is not complete.". The issue is simple, my very beloved Demo frame isn't working on the given page, as you can see in the following screen:

![Screenshot_2020-01-09_23-17-19](https://user-images.githubusercontent.com/32340478/72109493-3d6c9c00-3336-11ea-8f88-91eb0e1ee709.png)

By the way how it looks, I would guess it's some problem with the backend (but I'm no in any way expert!).

Anyway, I've tried it in these browsers:
- FF Developer edition
- Opera (Wasn't able to find the version, but it's probably latest stable version from Ubuntu/Mint repos.)
- Chromium ver. 79.0.3945.79 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

You can aslo see my platform in the last item of the list above. (HW is very very old HP laptop EliteBook 2540p).

I'm aware it's not in any way some kind of a big issue, I just wanna let you know in the case you haven't noticed so far. But take your time, I'll be able to figure out, how it works without the demo on my own.

Cheers
Ondrej

**Comment by chrisdavidmills** [comment]
This is not working because there is no repeating conic gradient example inside the interactive examples repo:

https://github.com/mdn/interactive-examples/tree/4f6e4f1518d2d1e2fa3f56f09dac5144f9cb0fdc/live-examples/css-examples/images

I don't have time to add one now, so I've just escaped the macro call for now so it doesn't render the broken iframe.
