### ISSUE TITLE
/de/docs/Web/CSS/@page

### ISSUE THREAD

**Issue by p-strobl** [mdn/sprints#2673]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update (German version)

# Details
Hi, what does this words do in this article?

![Screenshot_1](https://user-images.githubusercontent.com/37811399/72117077-9d6e3d00-334c-11ea-9431-5f1e7eee3012.png)

**Comment by chrisdavidmills** [comment]
Hrm. From using Google translate, it looks like these are inappropriate words/links.

The sentence in English says "You can only change the margins, orphans, widows, and page breaks of the document." What would be the correct German equivalent?

**Comment by p-strobl** [comment]
Hi Chris,

I would suggest to combine “orphans and widows” for the german translation.

 

Die @page CSS At-Regel wird verwendet, um einige CSS Eigenschaften zu ändern, wenn ein Dokument gedruckt wird. Es können nicht alle CSS Eigenschaften mit @page geändert werden. Es können nur Seitenränder, Absatzkontrolle: oben (widow); unten (orphans) und Seitenumbrüche des Dokuments verändert werden. Versuche, andere CSS Eigenschaften zu ändern, werden ignoriert.

 

I hope this will help.

 

Best regards,

Philipp Strobl

 

 

Von: Chris Mills <notifications@github.com> 
Gesendet: Freitag, 10. Januar 2020 09:51
An: mdn/sprints <sprints@noreply.github.com>
Cc: P. Strobl <p.str.hh@icloud.com>; Author <author@noreply.github.com>
Betreff: Re: [mdn/sprints] /de/docs/Web/CSS/@page (#2673)

 

Hrm. From using Google translate, it looks like these are inappropriate words/links.

The sentence in English says "You can only change the margins, orphans, widows, and page breaks of the document." What would be the correct German equivalent?

**Comment by chrisdavidmills** [comment]
OK, change made as suggested. Thanks for your help @p-strobl !
