### ISSUE TITLE
The image in z-index documentation could not be loaded

### ISSUE THREAD

**Issue by dangdien-tiki** [mdn/sprints#2674]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
The image in z-index documentation could not be loaded. Here's the screenshot:
![Screen Shot 2020-01-10 at 5 28 39 PM](https://user-images.githubusercontent.com/54924312/72146321-c59e8000-33ce-11ea-8612-5a7461126c31.png)

Url to the doc: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_2

same issue with https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_3

**Comment by chrisdavidmills** [comment]
Fixed; the macro call that generates the live examples wasn't set up properly.
