### ISSUE TITLE
Delete page: /docs/Web/HTTP/Headers/Feature-Policy/speaker

### ISSUE THREAD

**Issue by jpchase** [mdn/sprints#2675]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

As in https://github.com/w3c/webappsec-feature-policy/pull/360, the speaker policy is not going to be pursued. The corresponding doc page should be removed to avoid confusion:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/speaker

**Comment by chrisdavidmills** [comment]
Removed!

I've also filed a PR to remove the corresponding compat-data: https://github.com/mdn/browser-compat-data/pull/5485

Closing this now, but feel free to follow up if there's anything else you need.
