### ISSUE TITLE
/ru/docs/Web/JavaScript/Guide/Regular_Expressions

### ISSUE THREAD

**Issue by leksiq** [mdn/sprints#2683]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

at "#special-quantifier-range" ancor there is an error: "m и n - положительные целые. Соответствует как минимум n и максимум m вхождениям предыдущего символа. При **m=n=0** пропускается.
...", correct: **m=n=1**

**Comment by SphinxKnight** [comment]
Hello, thanks for reporting.

I've changed this bit but I'm not a Russian speaker/writer and the "parent" English page has been revamped (the Russian counterpart is now behind) so this typo is fixed but the content overall would need an update.

As MDN is a wiki and anyone can contribute, if you're enclined to help, that would be super great :) 

I'm closing this one but feel free to open it if you think this needs some more work.
