### ISSUE TITLE
/en-US/docs/Web/API/DocumentFragment/querySelectorAll

### ISSUE THREAD

**Issue by andersthorbeck** [mdn/sprints#2684]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

Typo:
documentframgment -> documentfragment

<img width="625" alt="typo_framgment" src="https://user-images.githubusercontent.com/7239065/72263314-e8bc7000-3618-11ea-825e-99c9e0014333.png">

**Comment by wbamberg** [comment]
Fixed, thanks for filing!
