### ISSUE TITLE
Improve our guidance on (not) using H1 more than once per page

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2685]
See https://github.com/mdn/interactive-examples/pull/1519. This PR updates the interactive example for [`<section>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) because it currently uses multiple H1 headings. The PR quotes [our own docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) in support of this:

> You should consider avoiding using `<h1>` more than once on a page. See [Defining sections](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#Defining_sections) for more information.

It's unhelpful for docs to say "you should consider..." without explaining what the considerations are, and  the linked page ([Using HTML sections and outlines](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#Defining_sections)) doesn't provide any clear guidance.

**Comment by chrisdavidmills** [comment]
@wbamberg I've had a go at doing this:

https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes

Let me know what you think.

**Comment by wbamberg** [comment]
Thanks @chrisdavidmills ! I'm happy that this page gives clear guidance now.

**Comment by participator** [comment]
@wbamberg and @chrisdavidmills that's a really clear update and thanks for merging my PR!
