### ISSUE TITLE
/en-US/docs/Web/API/HTML_Drag_and_Drop_API note error

### ISSUE THREAD

**Issue by kushudai** [mdn/sprints#2686]
# Request type
- [x] Correction or update

# Details
The note on https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API is plain wrong.
```
Note: Neither dragstart nor dragend events are not fired when dragging a file into the browser from the OS.
```

It should say: 
```
Note: Neither dragstart nor dragend events are fired when dragging a file into the browser from the OS.
```

**Comment by chrisdavidmills** [comment]
Changed - thanks for reporting! The double negative did seem very strange...
