### ISSUE TITLE
Forms data validation article, html example, "/" missing in closing tag?

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#2690]
# Request type

- [x] Correction or update

# Details

Ref MDN web docs, article "Form data validation",
section "[Validating forms without a built-in API](https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#Validating_forms_without_a_built-in_API)",
sub-section "An example that doesn't use the constraint validation API"
in the html example code box, line number 8, the "/" is missing from the paragraph ending tag?

**Comment by SphinxKnight** [comment]
@RisingThunder thanks for the report, I've fixed it!
Do not hesitate to edit MDN if you encounter such typos :) it's a wiki.
