### ISSUE TITLE
/en-US/docs/Web/API/IDBTransaction

### ISSUE THREAD

**Issue by mikeiz404** [mdn/sprints#2691]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Minor typo in the first paragraph last line: `You can also use an IDBTransaction object it to abort transactions.` Either `it` or `IDBTransaction object` will need to be removed to make the sentence grammatically correct. I'm guessing one of these words forgot to be removed when the sentence was updated.

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
