### ISSUE TITLE
/en-US/docs/Web/HTML/Element/label

### ISSUE THREAD

**Issue by mathiasha** [mdn/sprints#2692]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

Link to HTML5 definition of label element is broken.
![Screenshot 2020-01-15 at 11 33 57](https://user-images.githubusercontent.com/8741691/72427036-33f69000-378b-11ea-9661-71ac240b0b7a.png)

**Comment by chrisdavidmills** [comment]
Fixed; for some reason the forms subpage in the W3C spec has changed from `forms.html` to  `sec-forms.html`. I've fixed this on this page and the input eement page, but if you find any other instances, feel free to fix them!
