### ISSUE TITLE
Remove third party library code and documentation from MDN

### ISSUE THREAD

**Issue by danny-loh** [mdn/sprints#2693]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There are some third party library documentation in MDN

Examples:
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#Using_relative_URLs_in_the_path_parameter
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie/Simple_document.cookie_framework

As third party library are not official standards, their code and usage should be documented in external website but not MDN.

**Comment by SphinxKnight** [comment]
I removed the second page and could not find anything obivoulsy wrong within the first link you provided. Please reopen and send me details if you think I was incorrect doing so.

Thanks a lot for reporting :)
