### ISSUE TITLE
ip-location correction

### ISSUE THREAD

**Issue by horvgb** [mdn/sprints#2696]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details
193.224.195.1/24 ip address range is in Tihany/Veszprém county, not Heves county!
https://whatismyipaddress.com/ip/193.224.195.76

Thank you!
Gábor Horváth

**Comment by chrisdavidmills** [comment]
Hi there.

What page did you see this error on?

**Comment by horvgb** [comment]
Hi, Chris,

I use Graylog with Geolocation. You can see the ip address
(193.224.195.180) on the bottom of this picture. This ip and this range
has the Balaton Limonological Research Institute at *Tihany*, not /Eger/.

regards,
Gábor

**
**

*Ökológiai Kutatóközpont
*2163 Vácrátót, Alkotmány u. 2-4.
+36 28 360 122/104
horvath.gabor@okologia.mta.hu <mailto:horvath.gabor@okologia.mta.hu>
www.okologia.mta.hu <http://www.okologia.mta.hu>

2020.01.17. 16:44 keltezéssel, Chris Mills írta:

**Comment by chrisdavidmills** [comment]
I mean — what MDN page has incorrect IP address information on it? I'm assuming this is what you are trying to report?

**Comment by horvgb** [comment]
Sorry, I have missed the list.
Close, or delete my thread.
Thank you.

regards,

Gábor


Üdvözlettel:
*Horváth Gábor*
rendszergazda

*
Ökológiai Kutatóközpont
*2163 Vácrátót, Alkotmány u. 2-4.
+36 28 360 122/104
horvath.gabor@okologia.mta.hu <mailto:horvath.gabor@okologia.mta.hu>
www.okologia.mta.hu <http://www.okologia.mta.hu>

2020.01.20. 8:51 keltezéssel, Chris Mills írta:
