### ISSUE TITLE
WebDriver doc WIP has been published

### ISSUE THREAD

**Issue by ninofiliu** [mdn/sprints#2697]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In [this page](https://developer.mozilla.org/en-US/docs/Web/WebDriver), the Concepts section reads:

> Concepts
>
> To use WebDriver, you need to ... give high level description of how it is used, rather than low-level specifics, then link to further page(s) providing installation specifics.
> 
> WebDriver involves four main things:
>
> - a
> - b
> - c
> - d
>
> These things work together like so ... explain workflow of how commands, actions, etc. do stuff.

It looks like someone accidentally published a draft!

<sub>This is my first time bringing up an issue with MDN, please tell me if I'm doing something wrong, I'm still learning! :baby: </sub>

**Comment by chrisdavidmills** [comment]
Thanks for reminding me about this!

On MDN we don't have a concept of unpublished drafts — everything is put live immediately. But in this case, there are some placeholders left that never got filled in.

I've removed them, so the page looks a bit neater now.
