### ISSUE TITLE
Javascript Demo editor does not recognize nullish coalescing operator

### ISSUE THREAD

**Issue by valgrimm** [mdn/sprints#2698]
Referred by Melissa Thermidor.
Source: Tweet https://twitter.com/sliqric/status/1218106831152852992?s=21

Poster says "I think the editor does not currently recognize the nullish coalescing operator (??) "
in regard to 
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/4a8cd751-e0ba-4070-9d92-68d2c10172c2)

**Comment by chrisdavidmills** [comment]
I've tested this in Firefox and Chrome Canary, and it works as expected in both.

It could be that they are trying it in the current Chrome release version, or Safari, or some other non-supporting browser. In which case they'll see the reported output.

**Comment by wbamberg** [comment]
We make a call about when to add an interactive example to a page based on current support in browsers. More or less, if it is supported in current Chrome and Firefox we will include it.

We could have a more conservative policy, or we could somehow make the system cleverer so it checks for support and hides the editor if the feature isn't supported. We've had a similar discussion in the past about doing this with the CSS examples. But this I think would be quite complicated, and we've not been investing in the interactive editor code for a while now.

**Comment by valgrimm** [comment]
I'll pass this information on to Melissa.

**Comment by peterbe** [comment]
On a page like that, there's probably a BCD table below. It would be awesome if MDN could combine my current browser (vendor + version) and combine that with the BCD data, in runtime, to warn me that my current browser probably won't support the interactive example. How cool would that be?!
