### ISSUE TITLE
RSS feed support here: https://www.mozilla.org/en-US/firefox/releases/ 

### ISSUE THREAD

**Issue by Codman90** [mdn/sprints#2699]
# Request type

- [x] New function
- [ ] New documentation
- [ ] Correction or update

# Details
A RSS feed for https://www.mozilla.org/en-US/firefox/releases/ would be nice so that my work can stay on top of updates please and thank you!

**Comment by Elchi3** [comment]
This issue tracker is about MDN, please file against the issue tracker for mozilla.org.
