### ISSUE TITLE
Broken Links on Page about Mobile Extension Development

### ISSUE THREAD

**Issue by blueCat11** [mdn/sprints#2701]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Multiple links on [this page about mobile extension development](https://developer.mozilla.org/en-US/docs/Extensions/Firefox_on_Android ) lead to Not Found Errors, including the links in the bullet-points on _Code snippets for mobile_ and _Firefox on Android add-ons developer guide_

**Comment by chrisdavidmills** [comment]
Thanks for highlighting this. I think this is a really out of date that really needs to be retired. I've redirected it to the main webextensions page.
