### ISSUE TITLE
Typo in documentation example: querySelector

### ISSUE THREAD

**Issue by dmu029018** [mdn/sprints#2703]
# Request type
- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In Spanish version of [Javascript DOM query selector reference](https://developer.mozilla.org/es/docs/Web/API/Document/querySelectorAll) I found wrong syntax on query selector examples related to querying by attributes: quotes are missing on attribute values.

**Comment by chrisdavidmills** [comment]
I see what you mean. I've fixed it; thanks for reporting!

I also made sure the quote marks in the JS were consistent throughout, i.e. single quotes, as per our guidelines.
