### ISSUE TITLE
/en-US/docs/Web/XML/XML_introduction

### ISSUE THREAD

**Issue by bronsonavila** [mdn/sprints#2704]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The section entitled ["Correct" XML (valid and well-formed)](https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction#Correct_XML_valid_and_well-formed) begins as follows:

> For an XML document to be correct it the following conditions must be fulfilled:

This is grammatically incorrect and should likely be modified as follows:

> For an XML document to be correct, the following conditions must be fulfilled:

Thank you.

**Comment by bronsonavila** [comment]
I apologize. I see that I can directly edit the documentation myself. The issue has now been resolved. Thank you.

**Comment by chrisdavidmills** [comment]
@bronsonavila Thanks for your help!
