### ISSUE TITLE
<blockquote> tag being specified incorrectly

### ISSUE THREAD

**Issue by Glenn-Domin** [mdn/sprints#2705]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I think [your first example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) of a `<blockquote>` is incorrect.
![image](https://user-images.githubusercontent.com/17334100/72863363-13df4780-3d1c-11ea-8b08-376e5348a254.png)
[The spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) for `<blockquote>` states:
> Attribution for the quotation, if any, must be placed outside the blockquote element.

They have an example of how you can correctly use an attribution with a `<blockquote>` by using a `<figcaption>`:
```
<figure>
 <blockquote>
  <p>The truth may be puzzling. It may take some work to grapple with.
  It may be counterintuitive. It may contradict deeply held
  prejudices. It may not be consonant with what we desperately want to
  be true. But our preferences do not determine what's true. We have a
  method, and that method helps us to reach not absolute truth, only
  asymptotic approaches to the truth — never there, just closer
  and closer, always finding vast new oceans of undiscovered
  possibilities. Cleverly designed experiments are the key.</p>
 </blockquote>
 <figcaption>Carl Sagan, in "<cite>Wonder and Skepticism</cite>", from
 the <cite>Skeptical Inquirer</cite> Volume 19, Issue 1 (January-February
 1995)</figcaption>
</figure>
```

To be clear, the `<footer>` element _can_ be used inside a `<blockquote>`, but not for the purpose of attribution.

**Comment by mikoMK** [comment]
@chrisdavidmills Could you assign me to this issue? I'm interested in contributing to the interactive example. I think it would be best to update the interactive example to reflect the semantics of the spec example as quoted by @Glenn-Domin. Any thoughts?

**Comment by chrisdavidmills** [comment]
@mikoMK yeah, I think this makes sense.

I'll assign you; thanks for all the help!
