### ISSUE TITLE
/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

### ISSUE THREAD

**Issue by Dboingue** [mdn/sprints#2706]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The English page, had a title in apparently non alphabetical language, not English, that is clear.

**Comment by chrisdavidmills** [comment]
Fixed. Someone put some translation test over the top of the English version.

Thanks for reporting!
