### ISSUE TITLE
probleme dans les listes des evenement de javascript

### ISSUE THREAD

**Issue by aatillah98** [mdn/sprints#2707]
Voir aussi
mousedown
mouseup
mousemove
click
dblclick
mouseover
mouseout
mouseenter
mouseleave
contextmenu
this problem is sems like this cliquable not cliquable he need to on a title by href 

https://developer.mozilla.org/fr/docs/Web/API/Element/mouseover_event

**Comment by SphinxKnight** [comment]
Bonjour @aatillah98,

J'ai corrigé l'article et effectué une PR pour le problème sur le fond (https://github.com/mdn/kumascript/pull/1320)

Respectueusement,
Julien

**Comment by aatillah98** [comment]
Ur welcome friend 👍

Le jeu. 23 janv. 2020 11:51, SphinxKnight <notifications@github.com> a
écrit :

**Comment by SphinxKnight** [comment]
N.B. J'ai revu l'ensemble des pages pour les évènements liés à la souris
