### ISSUE TITLE
/en-US/docs/Web/HTML/Element/input

### ISSUE THREAD

**Issue by stenci** [mdn/sprints#2708]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
Grammatical error [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete).
Please remove this apostrophe: `takes as it's value a space`

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
