### ISSUE TITLE
Range Input drag handle, is possible to customize (stated as impossible)

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#2709]
# Request type

- [ ] New documentation
- [X] Correction or update

# Details

Ref "[Advanced form styling](https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling)" article, "[Range input types](https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling#Range_input_types)" section, it is stated 

> " it is impossible to customize the style of the range control's drag handle — this will always be the same, and will sit on top of the track, centered."

However, I was able to customize the drag handle as follows )(viewed using Firefox only though); 

`input[type=range]::-moz-range-thumb {
  box-shadow: 1px 1px 1px #000000, 0px 0px 1px #0d0d0d;
  border: 1px solid blue;
  height: 36px;
  width: 16px;
  border-radius: 3px;
  background: lightgreen;
  cursor: pointer;
}`

Could this be corrected, please, for future MDN web doc students?
It appears it is possible, but will vary per browser, found this article at CSS-TRICKS for more information, "[Styling Cross-Browser Compatible Range Inputs with CSS](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/)"
Thanks!

**Comment by chrisdavidmills** [comment]
@RisingThunder thanks for bringing this up.

I've updated the wording on the page, and provided a link to the CSS tricks article. I don't see the point of repeating it all.
