### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Examine,_modify,_and_watch_variables 

### ISSUE THREAD

**Issue by juliandescottes** [mdn/sprints#2710]
The following page https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Examine,_modify,_and_watch_variables refers to the old DevTools debugger which is no longer available in any Firefox version. The code has been removed, so even toggling the suggested preference will not help.

Could we remove this page?

**Comment by chrisdavidmills** [comment]
@jmswisher a small job (probably), but can you get to this one asap? Thanks! Probably just check to make sure that this isn't linked anywhere else, and doesn't contain anything that should be kept.

**Comment by hamishwillee** [comment]
@chrisdavidmills I did a search on MDN and a visual scan through pages that I thought might link this, but couldn't find anything obvious. Is there a more methodical approach for finding links to this.

As to the content, this covers Examine,_modify,_and_watch_variables.

My understanding is that 
- watching variables is covered by https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_Watch_Expressions AND https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Watch_expressions
- Examining variables is done either the [Scopes section](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Scopes) or [variable tooltip](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Variable_tooltip). While debugging you can also get some inline preview.
- Modifying variables can be done in scopes or watches or whatever. However you can't do it in a variable tooltip. 

So if the above understanding is correct then there is no need for this topic as-is. It could be deleted, or repopulated just as links to the above information. Thoughts?

**Comment by chrisdavidmills** [comment]
@hamishwillee there isn't really a better way to investigate this; I'd say you've done exactly the right thing. I'd put in a redirect from that page to the Set watch expressions page.

**Comment by hamishwillee** [comment]
Redirect created! Thanks
