### ISSUE TITLE
Javascript try catch conditional catch blocks could be hidden by default

### ISSUE THREAD

**Issue by Relequestual** [mdn/sprints#2712]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the [page for Javascript try / catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) there is a section for "Conditional catch-blocks", however this notes that it is non standard and not supported by most browsers (inc FF).

Would it not be better to either move any non production useable information to the end of the document or hide it by default?

**Comment by chrisdavidmills** [comment]
@Relequestual I agree that it is a bit strange leading with information about a non-standard feature that doesn't work in any modern browser.

But I don't think we should hide it completely — it is still useful for users that can remember such a feature existing at some point, and are wondering why it isn't working when they try it in their code today. It is also a nice detail for web archaeologist types (of which there are quite a few).

So, I've updated the section to talk about conditional try/catch, how to do that, and why you might want to do it. Then at the bottom I've included the information about the non-standard syntax that is no longer available in a note, and made it clear that it no longer works anywhere. The browser compat data at the end of the article also makes this clear.

Do you think this is better now?

**Comment by Elchi3** [comment]
I've removed obsolete conditional clauses now per our new policy of "irrelevant features": https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features

The compat data will be removed soon, too: https://github.com/mdn/browser-compat-data/pull/6192
