### ISSUE TITLE
/en-US/docs/Web/Accessibility/Mobile_accessibility_checklist

### ISSUE THREAD

**Issue by amberjones** [mdn/sprints#2713]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x ] Correction or update

# Details

The link in the Focus section for aria roles goes to a 404 -  
https://www.w3.org/TR/wai-aria/roles

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting @amberjones !
