### ISSUE TITLE
Wrong translation uploaded under English text

### ISSUE THREAD

**Issue by DanielFlidr** [mdn/sprints#2715]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface 
English text version actually contains different language (seems Turkish).
![bugReport](https://user-images.githubusercontent.com/36476597/73053276-9df7ef00-3e87-11ea-85c9-2e27d5759e8a.PNG)

**Comment by chrisdavidmills** [comment]
Reverted; thanks for reporting!
