### ISSUE TITLE
/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by LukasSiemermann** [mdn/sprints#2716]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x ] Correction or update

# Details

Hello,

i've one question. Is i possible that you'll fix one html5 input issue? Me and my Company need the input type="datetime-local" like the input type="date". I would very much like to use the graphical selection on the "Datetime" option just like the "Date function".

Lukas Siemermann

![24-01-2020 12-05-15](https://user-images.githubusercontent.com/60257356/73064606-e91efb80-3ea1-11ea-81dc-dad03ab8153a.png)
![24-01-2020 12-05-52](https://user-images.githubusercontent.com/60257356/73064607-e91efb80-3ea1-11ea-89b0-53050f62541c.png)

**Comment by chrisdavidmills** [comment]
This is not the right place to suggest additions/updates to the Firefox browser; this is for bugs concerning MDN documentation.

There is already an open bug for datetime-local; see https://bugzilla.mozilla.org/show_bug.cgi?id=1306217

You could go there and ask about it.

Best regards.
