### ISSUE TITLE
/hu

### ISSUE THREAD

**Issue by Zola-github** [mdn/sprints#2718]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

**Comment by hobbsjeremys** [comment]
I'm just trying to stop all the emails and cancel my membership with y'all or delete my account

**Comment by chrisdavidmills** [comment]
@hobbsjeremys We can help you with that. So you want to delete your MDN account? Are there any other things you need, like stopping GitHub mails, or is it just mails from the MDN site?

This is actually for issues about MDN content. I'm going to close this one now, but could you please open a request at https://github.com/mdn/kuma/issues, and we'll help you with deleting your account. Thanks!
