### ISSUE TITLE
/ko/docs/ Clean up

### ISSUE THREAD

**Issue by alattalatta** [mdn/sprints#2720]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
As per "[How to request mass docs relocation for a locale](https://discourse.mozilla.org/t/how-to-request-mass-docs-relocation-for-a-locale/51876)",

(These are not a "complete" list)

## Relocation
I've collected some of the severely misplaced documents while localizing, and by using the `without-parent` page.

Subpages should be moved too.
- /ko/docs/Web/HTML/Element/캔버스
  - /ko/docs/Web/HTML/Element/canvas
  - Interfering with macros
- /ko/docs/Web/API/RandomSource/getRandomValues
  - /ko/docs/Web/API/Crypto/getRandomValues
- /ko/docs/Web/HTTP/Access_control_CORS
  - /ko/docs/Web/HTTP/CORS
- /ko/docs/Web/CSS/Understanding_z-index
  - /ko/docs/Web/CSS/CSS_Positioning/Understanding_z_index
- /ko/docs/Developer_Guide
  - /ko/docs/Mozilla/Developer_guide
- /ko/docs/Download_Mozilla_Source_Code
  - /ko/docs/Mozilla/Developer_guide/Source_Code/Downloading_Source_Archives
  - Previous one (/ko/docs/Developer_Guide) should be moved first, maybe?
- /ko/docs/Mozilla/애드온들
  - /ko/docs/Mozilla/Add-ons
  - Does not match with its title
- /ko/docs/도구들
  - /ko/docs/Tools
  - Does not match with its title
- /ko/docs/MDN/커뮤니티
  - /ko/docs/MDN/Community
  - This one isn't "severe", but still...

## Archive or removal
- /ko/docs/Code_snippets
  - /ko/docs/Archive/Add-ons/Code_snippets
  - Too old, but I do see its upstream in archive-land.

## Removal
I made quite a few redirect pages, but these are all a simple mistake, am sure of its removal from upstream, or way too old / hard to track to find a proper parent or redirect target.
- /ko/docs/DOM/WRONG_DOCUMENT_ERR_note
- /ko/docs/A_Basic_RayCaster/input.js
- /ko/docs/XPCNativeWrapper
- /ko/docs/Functions
- /ko/docs/Install_Manifests
- /ko/docs/Learn/CSS/CSS_layout/레거시_조판_메서드
- /ko/docs/지역의_코드를_씁니다.
- /ko/docs/XPCOM_components_list
- /ko/docs/XTF
- /ko/docs/자바스크립트의_이벤트

**Comment by SphinxKnight** [comment]
Creating a checklist here for progress tracking

### Moving

- [ ] https://wiki.developer.mozilla.org/ko/docs/Web/HTML/Element/캔버스 to https://wiki.developer.mozilla.org/ko/docs/Web/HTML/Element/canvas
- [ ] https://wiki.developer.mozilla.org/ko/docs/Web/API/RandomSource/getRandomValues to https://wiki.developer.mozilla.org/ko/docs/Web/API/Crypto/getRandomValues
- [ ] https://wiki.developer.mozilla.org/ko/docs/Web/HTTP/Access_control_CORS to https://wiki.developer.mozilla.org/ko/docs/Web/HTTP/CORS
- [ ] https://wiki.developer.mozilla.org/ko/docs/Web/CSS/Understanding_z-index to https://wiki.developer.mozilla.org/ko/docs/Web/CSS/CSS_Positioning/Understanding_z_index
- [ ] https://wiki.developer.mozilla.org/ko/docs/Developer_Guide to https://wiki.developer.mozilla.org/ko/docs/Mozilla/Developer_guide
- [ ] https://wiki.developer.mozilla.org/ko/docs/Download_Mozilla_Source_Code to https://wiki.developer.mozilla.org/ko/docs/Mozilla/Developer_guide/Source_Code/Downloading_Source_Archives
- [ ] https://wiki.developer.mozilla.org/ko/docs/Mozilla/애드온들 to https://wiki.developer.mozilla.org/ko/docs/Mozilla/Add-ons
- [ ] https://wiki.developer.mozilla.org/ko/docs/도구들 to https://wiki.developer.mozilla.org/ko/docs/Tools
- [ ] https://wiki.developer.mozilla.org/ko/docs/MDN/커뮤니티 to https://wiki.developer.mozilla.org/ko/docs/MDN/Community

### Archiving
- [ ] https://wiki.developer.mozilla.org/ko/docs/Code_snippets to     https://wiki.developer.mozilla.org/ko/docs/Archive/Add-ons/Code_snippets
### Removal
- [x] https://wiki.developer.mozilla.org/ko/docs/DOM/WRONG_DOCUMENT_ERR_note
- [ ] https://wiki.developer.mozilla.org/ko/docs/A_Basic_RayCaster/input.js
- [ ] https://wiki.developer.mozilla.org/ko/docs/XPCNativeWrapper
- [ ] https://wiki.developer.mozilla.org/ko/docs/Functions
- [ ] https://wiki.developer.mozilla.org/ko/docs/Install_Manifests
- [ ] https://wiki.developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/레거시_조판_메서드
- [ ] https://wiki.developer.mozilla.org/ko/docs/지역의_코드를_씁니다.
- [ ] https://wiki.developer.mozilla.org/ko/docs/XPCOM_components_list
- [ ] https://wiki.developer.mozilla.org/ko/docs/XTF
- [ ] https://wiki.developer.mozilla.org/ko/docs/자바스크립트의_이벤트

**Comment by SphinxKnight** [comment]
@alattalatta I've done most of it, the only item left for removal is due to https://github.com/mdn/kuma/issues/6191

Can you check that everyting is OK for you and close the issue accordingly? :)

**Comment by alattalatta** [comment]
Everything looks good, thank you!
