### ISSUE TITLE
/en-US/docs/Web/API/Element/classList

### ISSUE THREAD

**Issue by stepanvolf** [mdn/sprints#2721]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The docs state that the classList property returns:

> A DOMTokenList representing the contents of the element's class attribute. If the class attribute is not set or empty, it returns 0.

I don't believe the second sentence is true. Perhaps it should say something like this instead:

> ... If the class attribute is not set or empty, it returns an empty DOMTokenList, ie. a DOMTokenList with the length property equal to 0.

But maybe I'm missing something. Cheers!

**Comment by chrisdavidmills** [comment]
@stepanvolf thanks for bringing this up! You are correct; I've updated the page to use your wording.
