### ISSUE TITLE
WebXR/WebGL: Article about perspective [MVP]

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2726]
We need an article talking about perspective: what it is, why it's used, and how to apply it, as well as the various types of perspective and how perspective is represented in transforms.

## Topics
- [x] Intro: what is perspective?
- [x] Perspective concepts
- [x] Why perspective matters
- [x] Types of perspective
- [x] Fitting into reality in an AR scene

## Resources
* https://en.wikipedia.org/wiki/3D_projection
* https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection

## Acceptance criteria
- [ ] Content complete and accurate
- [ ] Submitted for review as deemed necessary

**Comment by Elchi3** [comment]
It was decided to not move this into next sprint. Removing the milestone.

**Comment by a2sheppy** [comment]
Aaaand this is now back into the India-Juliett sprint, since the security work I was going to be doing is pushed back due to the unavailability of the security team to help until July sometime.

**Comment by a2sheppy** [comment]
https://wiki.developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Perspective

Some of the information included in the task list have been added to the previously-existing article on the topic of perspective:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection
