### ISSUE TITLE
Nullish coalescing operator overview document

### ISSUE THREAD

**Issue by rugk** [mdn/sprints#2727]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[That operator](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) is new and thus not yet documented in a good way and linked everywhere.

I've added it to the [overview of operators here](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Short-Circuit_Evaluation), but is this enough?

Maybe also include it [on the learning page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals) (that looks quite like a duplicate somewhat, just with more explanation)?

**Comment by chrisdavidmills** [comment]
> That operator is new and thus not yet documented in a good way and linked everywhere.

I think the documentation we've got is OK for now on here.

> I've added it to the overview of operators here, but is this enough?

This was definitely helpful, thanks!

> Maybe also include it on the learning page (that looks quite like a duplicate somewhat, just with more explanation)?

I deliberately didn't put this on the learning pages, because I consider it advanced, and not really vital for a beginner to know about.

But please let me know if you see any other places that you think it should be included on.

**Comment by rugk** [comment]
Well then… everything is done, I guess. :smile: 

Yeah, with the first sentence I mostly just meant some "See also" links or references that could be added. I also added one somewhere.

Anyway, closing.
