### ISSUE TITLE
Documentation is truncated.

### ISSUE THREAD

**Issue by mavinog** [mdn/sprints#2729]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the documentation:

Web technology for developers > JavaScript > JavaScript Guide > JavaScript modules

on the page:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

you have truncated text:

First of all, you need to include type="module" in the

**Comment by a2sheppy** [comment]
The edit that removed the remainder of the article is this one:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules$compare?locale=en-US&to=1604476&from=1604475

I'm investigating why this edit was made so I can determine the correct action to take.

**Comment by chrisdavidmills** [comment]
@mavinog This was deleted by mistake, sorry about that!

I've restored it now.

**Comment by mavinog** [comment]
Thank you very much!
