### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

### ISSUE THREAD

**Issue by jessepav** [mdn/sprints#2730]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The latest edits (1/31/20 by chrisdavidmills) deleted the second half of the page, past *Applying the module to your HTML*

**Comment by chrisdavidmills** [comment]
@jessepav Fixed now; sorry about that!
