### ISSUE TITLE
Fix typo in HTML attribute reference for dropzone

### ISSUE THREAD

**Issue by mndeal** [mdn/sprints#2732]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is a typo in the documentation for the `dropzone` attribute in the [HTML attribute reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes).

![image](https://user-images.githubusercontent.com/29898243/73584876-d2604200-4469-11ea-81ae-2b4a81b9aa9c.png)

```
Indicates that the element accept the dropping of content on it.
```
should be
```
Indicates that the element accepts the dropping of content on it.
```
The change is `accept` -> `accepts`.

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
