### ISSUE TITLE
Javascript Building Blocks - Looping Code Issues

### ISSUE THREAD

**Issue by PatrikKozak** [mdn/sprints#2737]
The Looping Code page does not load properly and I cannot go through the Active Learning parts. The scroll icon on the right doesn't show up and the tab showing the Looping Code page at the top says it's still loading.

**Comment by chrisdavidmills** [comment]
@PatrikKozak what page do you mean?

I just went to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#Active_learning_Launch_countdown!, and the Active Learning sections work fine for me.

**Comment by PatrikKozak** [comment]
It works now for me as well! It may have been a network issue on my end. Thanks for getting back to me nonetheless!
