### ISSUE TITLE
[CSS] multi-col, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2739]
# Trello

https://trello.com/c/X0vhUJhk/2-css-multi-col-fx-74

# Acceptance criteria

1. - [x] [Remove support for -moz-prefixed CSS multi-column properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1308636)

**Comment by rachelandrew** [comment]
I don't think this is mentioned much anywhere as they were deprecated a long time ago, so I've updated the compat data in this PR https://github.com/mdn/browser-compat-data/pull/5676 and updated the 74 release notes.

**Comment by chrisdavidmills** [comment]
I've reviewed this one, and it looks fine, so setting to done.
