### ISSUE TITLE
[CSS] box model/UI, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2740]
# Trello

https://trello.com/c/aW1yKtfb/149-css-box-model-module-level-3-ui-related-fx-74

# Acceptance criteria

1. - [x] [Enable rendering of outline-style:auto by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1031664)

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm not sure why on this page we have the value not in db message  https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style

It's the same for other outline- properties though.

**Comment by chrisdavidmills** [comment]
It'll be because the data required for that information is not in the mdn-data npm package, which is generated from the data repo. Is the data already in the data repo?

**Comment by chrisdavidmills** [comment]
I just got a notification that a new mdn-data package was released. I think @Elchi3 / @wbamberg  were working on it. So hopefully that will sort it out.

**Comment by rachelandrew** [comment]
ah ok - it looked like it was, which was why I was confused. Well we'll see if it fixes itself I guess.
