### ISSUE TITLE
[CSS] text, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2741]
# Trello

https://trello.com/c/FdS8hdQo/97-css-text-eg-text-text-decoration-fx-74

# Acceptance criteria

1. - [x] [Implement CSS3 text module text-underline-position](https://bugzilla.mozilla.org/show_bug.cgi?id=770780)
2. - [x] [`text-underline-offset` and `text-decoration-thickness` should accept percentage values](https://bugzilla.mozilla.org/show_bug.cgi?id=1607534)
3. - [x] [Let CSS text-underline-position property ride the train to release](https://bugzilla.mozilla.org/show_bug.cgi?id=1606997)
4. - [x] [wrong text-underline-offset zero position with text-underline-position:under](https://bugzilla.mozilla.org/show_bug.cgi?id=1607308) ([intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/Rxnb4jD5gU8) is probably more useful)

**Comment by jmswisher** [comment]
- Updated wiki pages for [text-underline-position](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position), [text-underline-offset](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset) and [text-decoration-thickness](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness).
- Updated BCD for all three properties, including features for percentages and `from-font`.
- Updated CSS syntax in mdn/data for all three properties (moving `from-font` and adding percentage)

**Comment by chrisdavidmills** [comment]
@jmswisher The pages, data, and BCD look pretty good for these. 

Do we have interactive examples for these?

**Comment by jmswisher** [comment]
@chrisdavidmills  Interactive examples exist, but haven't been added to the pages due to poor browser support. According to WillB, once Fx74 is out, we can examples to text-underline-position. Support is still not broad enough to show examples for text-underline-offset or text-decoration-thickness.

**Comment by chrisdavidmills** [comment]
@jmswisher sounds reasonable to me. We can call this done, in that case.

**Comment by chrisdavidmills** [comment]
@jmswisher ah, wait. You still need to set all the related bugs to dev-doc-complete, and include a comment on them to say what you did to complete the docs.

Linking to https://github.com/mdn/sprints/issues/2741#issuecomment-593703537 fmor the bug for the full details should be enough.
