### ISSUE TITLE
[JS] optional chaining operator, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2742]
# Trello

https://trello.com/c/Z7QTudD6/245-optional-chaining-operator-fx-74

# Acceptance criteria

1. - [x] [Implement the Optional Chaining operator (?.) proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1566143)

**Comment by Elchi3** [comment]
This was already written mostly by @SphinxKnight :) Thank you!

**Comment by SphinxKnight** [comment]
✌️
