### ISSUE TITLE
[WebAPI] CSSOM, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2745]
# Trello

https://trello.com/c/eiqOUxYH/244-cssom-fx-74

# Acceptance criteria

1. - [ ] [Implement CSSStyleSheet Constructor](https://bugzilla.mozilla.org/show_bug.cgi?id=1606727)

**Comment by rachelandrew** [comment]
@chrisdavidmills I've not really looked into what we have for CSSOM, but at this point this spec isn't merged into the CSSOM spec https://github.com/w3c/csswg-drafts/issues/3433. Therefore I'm wondering what to do re documenting it.

**Comment by chrisdavidmills** [comment]
Hrm, we ought to leave this until it's actually in the standard.Put this on the backburner for now, and check back in on it in a while.
