### ISSUE TITLE
/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

### ISSUE THREAD

**Issue by pmpinto** [mdn/sprints#2750]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
Some small typos and text inconsistencies I noticed while reading through this article:

> Github

Should be:
GitHub

> (zoom out )

Should be:
(zoom out)

> pinch out  (zoom in)

Should be (double space after 'out' removed):
pinch out (zoom in)

> the taget element's background

Should be:
the target element's background

Thanks!

**Comment by chrisdavidmills** [comment]
All fixed; thanks for reporting!
