### ISSUE TITLE
[HTTP] Cross-Origin, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2751]
# Trello

https://trello.com/c/ZQjg0cm4/175-cross-origin-related-bugs-fx-74

# Acceptance criteria

1. - [x] [Let Cross-Origin-Resource-Policy ride the trains](https://bugzilla.mozilla.org/show_bug.cgi?id=1602363)

**Comment by Elchi3** [comment]
BCD https://github.com/mdn/browser-compat-data/pull/5756

**Comment by Elchi3** [comment]
done https://bugzilla.mozilla.org/show_bug.cgi?id=1602363#c12
