### ISSUE TITLE
[WebExt] General APIs, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2753]
# Trello

https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-74

# Acceptance criteria

1. - [ ] [make webrequest urlclassification a part of the public api](https://bugzilla.mozilla.org/show_bug.cgi?id=1589494)
2. - [x] [Allow commands.update() to un-set a shortcut, disabling the command](https://bugzilla.mozilla.org/show_bug.cgi?id=1475043)

**Comment by rebloor** [comment]
@chrisdavidmills commands.update() is done, urlClassification I'm waiting on one clarification for the MDN text (which is otherwise all done) and merging of the compatibility data. Release notes are updated for both

**Comment by rebloor** [comment]
@chrisdavidmills Got confirmation from Shane Caraveo regarding removal of socialtracking flag, this completes "make webrequest urlclassification a part of the public api"
