### ISSUE TITLE
Most examples do not work in chrome due to "The AudioContext was not allowed to start." error

### ISSUE THREAD

**Issue by aeschylus** [mdn/sprints#2756]
<img width="367" alt="Screenshot 2020-01-04 at 4 23 06 PM" src="https://user-images.githubusercontent.com/145874/71772297-c5a20a00-2f0e-11ea-8663-b82ea117cd7a.png">

Here are a few related resources I ran across:
- Similar issue in the pixijs queue: https://github.com/pixijs/pixi-sound/issues/65
- Docs explaining the chrome policy changes (2018) that may be responsible: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

**Comment by chrisdavidmills** [comment]
This relates to the examples in https://github.com/mdn/webaudio-examples/

But related MDN pages would also need their code updating; see https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API, possibly as a followup task.

**Comment by chrisdavidmills** [comment]
I've made a commit to fix this problem (and update `var` to `let`/`const` as appropriate) for all the examples that were relatively simple to fix.

https://github.com/mdn/webaudio-examples/commit/b2c121bfa5f7c77384face662f1d9daaab8a729d

I fear that the others might require more rewriting to fix, so perhaps we should split these out into separate tasks?

**Comment by chrisdavidmills** [comment]
The demos that still need attention:

* iirfilter-node
* offline-audio-context
* offline-audio-context-promise
* step-sequencer

**Comment by chrisdavidmills** [comment]
Any thoughts @aeschylus?
