### ISSUE TITLE
Change the "Applies to" field in CSS gap specification section

### ISSUE THREAD

**Issue by aethanyc** [mdn/sprints#2757]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the blue box under "Specification" in [CSS gap](
https://developer.mozilla.org/en-US/docs/Web/CSS/gap). It says the "gap" properties **Applies to** "grid containers". It should be changed to "multi-column containers, flex containers, grid containers" to match the spec in https://drafts.csswg.org/css-align-3/#propdef-gap

**Comment by rachelandrew** [comment]
Thanks for the report.

PR for the data which should fix this: https://github.com/mdn/data/pull/407
