### ISSUE TITLE
HTML Tags link to html5 w3 spec broken

### ISSUE THREAD

**Issue by SamuelleMollard** [mdn/sprints#2760]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**Comment by chrisdavidmills** [comment]
@SamuelleMollard Can you give me a couple of examples of pages that have broken spec links? Is it all HTML element pages, or just a few?

**Comment by SamuelleMollard** [comment]
It's not all the pages, since the a element one (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) works, thought there are a few of them. Here are a few examples : 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
https://www.w3.org/TR/html52/text-level-semantics.html#the-code-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data
Furthermore, it seems only the "html5" link is broken, but i'am not sure i didn't test it all

**Comment by chrisdavidmills** [comment]
@SamuelleMollard it looks like the URL structure of the W3C spec has changed, which has broken a number of these links. "textlevel-semantics" has changed to "text-level-semantics".

I'll do a sweep through and fix as many of these as I can, but please let me know if you find more, or feel free to update them yourself if you want to.

**Comment by chrisdavidmills** [comment]
> "textlevel-semantics" has changed to "text-level-semantics".

Ooops, I meant the other way around — "text-level-semantics" has changed to "textlevel-semantics"

**Comment by chrisdavidmills** [comment]
Right. I've been through all the HTML element pages and made sure all the W3C spec links work ;-)

**Comment by SamuelleMollard** [comment]
Thank you a lot for your work

**Comment by chrisdavidmills** [comment]
> Thank you a lot for your work

You're welcome! It really bugs we when we have mass broken links on pages.
