### ISSUE TITLE
Epic: Publish Modern web tooling module

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2761]
# User story
As an aspiring web developer, I want to learn about modern web tooling, so I can make my workflow more efficient and powerful, and work effectively on a modern web dev team.

This is an Epic to track all the work involved in publishing our "Understanding modern web tooling" module (see the [document spec here](https://docs.google.com/document/d/1T4s2R_aLefiNWxeC4g-dbEXXfBw_tGw5NdSOS6OCRvM/edit#heading=h.ch025wvepiyy)).

# Acceptance criteria

1. - [x] All articles are published
2. - [x] All finalization work has been done. This includes:
  * All links in place
  * LearnSidebar macro updated so module appears in it.

**Comment by chinikes** [comment]
Hi @chrisdavidmills , @atopal - Please add in the Acceptance Criteria for this Epic. Thanks!

**Comment by atopal** [comment]
I think this is on @chrisdavidmills, but happy to review
