### ISSUE TITLE
Information about TIFF compression is incorrect

### ISSUE THREAD

**Issue by lwchkg** [mdn/sprints#2777]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The information about compression in TIFF files in https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#TIFF is incorrect.

The current page reads "Most TIFF files are uncompressed, but lossless PackBits and LZW compression are supported, as is lossy JPEG compression.".

The mistakes are as follows:
- Most Bilevel TIFFs, as appearing in fax documents, are compressed by "CCITT Group 4 fax encoding" instead of uncompressed. (Some earlier fax software use CCITT Group 3 fax encoding" instead.)
- The sentence implied that there are only two compression methods in TIFF files, but in fact there are a lot.

I recommend changing to the following:
Many different loseless and lossy compression schemes are supported by TIFF images. However, with the exception of bilevel images, TIFF image are most commonly uncompressed.

Reference:
https://en.wikipedia.org/wiki/TIFF#TIFF/IT_compression

**Comment by a2sheppy** [comment]
Someone had already taken a whack at this, but I re-whacked it to be better.
