### ISSUE TITLE
Update and redeploy BCD's Probot app

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2779]
As a BCD maintainer, I want to update BCD's Probot app, so I can be sure that there are no more security warnings from `npm` and that the latest version is running.

For background on this, see https://github.com/mdn/sprints/issues/2662.

**Comment by ddbeck** [comment]
@Elchi3 just to be explicit here, I have just deployed the new version of the bot. Let me know if you run into any problems.

**Comment by Elchi3** [comment]
Thank you @ddbeck! New PRs will surely come in at some point today or this week :)
