### ISSUE TITLE
Change IRC links and mentions to Matrix, or delete 

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2781]
# User story
As a reader of MDN, I want to find only valid links to online chat (for MDN or other Mozilla groups), so I am not led down a 

# Acceptance criteria

- [ ] No mentions of, or links to, IRC remain on MDN in English. They have all been converted to Matrix links, where possible, or deleted if a corresponding Matrix room cannot be found.

# Tasks

1. - [x] Search to create an inventory of IRC links and mentions on MDN English pages.
2. - [x] For each linked IRC channel, try to find a corresponding Matrix room. 
3. - [x] Replace mentions of IRC with mentions of Matrix.
4. - [x] Replace or delete links to IRC channels.

**Comment by jmswisher** [comment]
This issue is dependent on the general announcement of chat.mozilla.org for public use. According to Mike Hoye, that is waiting on one specific bugfix from the Matrix/Riot team, and should happen Real Soon Now.

**Comment by Elchi3** [comment]
For BCD, a change from IRC to Matrix is proposed in this PR: https://github.com/mdn/browser-compat-data/pull/5556.

**Comment by jmswisher** [comment]
For English pages, [the only links to irc.mozilla.org are in the /Archive section](https://wiki.developer.mozilla.org/en-US/search?q=IRC). I believe that all uses of {{IRCLink}} have been removed, but waiting for the search index to update, to be certain.

**Comment by chrisdavidmills** [comment]
@jmswisher I've had a look at this, and the only mentions of IRC that I can see are in `/archive`.

Except, we still have this page:

https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Getting_started_with_IRC

Which is also linked to from 

https://wiki.developer.mozilla.org/en-US/docs/Mozilla

I'd guess we should probably delete this doc, and instead include a link to https://wiki.mozilla.org/Matrix ?

Apart form that, this one looks GTG.

**Comment by jmswisher** [comment]
Mike Hoye added the note at the top (which I've now formatted as a Warning), and added text about the CPG. That suggests to me that he wants to keep the article. The note links to the wiki.mo Matrix page.

I've also changed the title to "Getting started with chat", so that it won't get as many search hits for "IRC".
