### ISSUE TITLE
Request for same directory blocked by CORS with setting disabled

### ISSUE THREAD

**Issue by carlin-q-scott** [mdn/sprints#2782]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp says I can disable the feature by toggling the privacy.file_unique_origin setting. I did that, and I'm still getting the CORS error for a local file in the same directory as the HTML page that I'm loading.

I restarted Firefox, and that had no effect.

**Comment by hamishwillee** [comment]
Hi @carlin-q-scott 

I tried this using a test "evil site" on FF82 as per these instructions: https://ptvb.sy.gs/evilXHR/. This failed until I set the pref to false and rebooted - and then succeeded.

Can you tell me what version of Firefox you tested this on. Also, can you supply test code I can use to verify this?

**Comment by carlin-q-scott** [comment]
@hamishwillee Did you need to reboot for the setting to take effect?

**Comment by hamishwillee** [comment]
@carlin-q-scott I wasn't sure, so I tried this again using Nightly (85). This time I definitely did not need to reboot.

**Comment by hamishwillee** [comment]
Hi Carlin, I'm closing this as "cannot verify" - which means docs are correct. But if you can find a situation in which we can reproduce then I'd say we should raise a bug against the product, not the docs.
