### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

### ISSUE THREAD

**Issue by RichardLidstone** [mdn/sprints#2783]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Unlike similar pages this one doesn't include a Polyfill for Array.includes().

An example page that does include a polyfill is:
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

A polyfill for includes() exists here:
[https://mariusschulz.com/blog/ecmascript-2016-array-prototype-includes](https://mariusschulz.com/blog/ecmascript-2016-array-prototype-includes) 

And this article refers to that polyfill being available on the MDN Array.includes page , and reproduces it, so it seems it has been removed for some reason?:
[https://mariusschulz.com/blog/ecmascript-2016-array-prototype-includes](https://mariusschulz.com/blog/ecmascript-2016-array-prototype-includes)

Many thanks.

**Comment by SphinxKnight** [comment]
Since this RFC (https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500 ), polyfills should not be directly distributed from MDN (a link to some external polyfill might be a good thing though)

There have been "almost flame war" edits and reverts about this which explains why some page still have them.

**Comment by chrisdavidmills** [comment]
@SphinxKnight I was just trying to find that link....thanks!

So there is not really any more to do here. Any polyfills that still remain are only there because people keep putting them back, even though we've told them not to. Closing for now.
