### ISSUE TITLE
Lint en-US JS wiki pages against stumptown recipes

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2784]
As a wiki editor, I want to use the stumptown linter to find JS pages that don't match their corresponding recipes, so I can find out which pages are misidentified or unscrapable.

# Acceptance criteria

- [x] Running `scraper-ng` produces errors for missing content sections

**Comment by SphinxKnight** [comment]
Will this encompass all pages or just en-US ones?

**Comment by ddbeck** [comment]
Good catch, @SphinxKnight. I'm only working on en-US. The plan right now is to do this stuff to the en-US JS docs, and only then figure how to translate (pardon the pun) that process to other content areas and locales.

I'll update the issue title accordingly.

**Comment by SphinxKnight** [comment]
Thanks @ddbeck :), I'll submit other issues where relevant after having read the code/ figured out solutions for the rest.

**Comment by ddbeck** [comment]
This has been resolved by by https://github.com/mdn/stumptown-content/pull/320/
