### ISSUE TITLE
Mistake in the Block-level elements page, pt-BR version

### ISSUE THREAD

**Issue by rcsilvadev** [mdn/sprints#2789]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is a mistake in the title of the **Block-level elements** page in the **pt-BR** version.

How the URL is now (**n**lock instead of **b**lock):
https://wiki.developer.mozilla.org/pt-BR/docs/Web/HTML/Elementos_nlock-level

How it should be:
https://wiki.developer.mozilla.org/pt-BR/docs/Web/HTML/Elementos_block-level

Thank you!

**Comment by SphinxKnight** [comment]
Thanks for reporting :) 
I fixed it and it looks ok now.

Do not hesitate to reopen if necessary.
