### ISSUE TITLE
error in example /en-US/docs/Web/API/Touch_events 

### ISSUE THREAD

**Issue by BANOnotIT** [mdn/sprints#2790]
# Request type
- [x] Correction or update

# Details
Error in example: Example:27 Uncaught SyntaxError: Unexpected token 'var'
Code context
```javascipr
...
 el.addEventListener("touchend", handleEnd, false);
  el.addEventListener("touchcancel", handleCancel, false);
  el.addEventListener("touchmove", handleMove, false);
}
document.addEventListener("DOMContentLoaded", startup) var ongoingTouches = [];
 function handleStart(evt) {
  evt.preventDefault();
  console.log("touchstart.");
...
```
`var` token should be on separate line or should be prependended with `;`

**Comment by chrisdavidmills** [comment]
The code doesn't appear like this on the page, but I've add a semi colon to the end of  `document.addEventListener("DOMContentLoaded", startup)`, to make sure the end of the line is recognised.

I think that is all there is to do here, so I'm closing it for now, but let me know if you think there is something more to do.
