### ISSUE TITLE
Add MIDIMessageEvent page

### ISSUE THREAD

**Issue by waterplea** [mdn/sprints#2791]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

My MDN user name is `waterplea`. I'm working on a Web MIDI API library and wanted to link my README.md to MDN docs. Page for MIDIMessageEvent is there in the navigation but it is red, indicating it is missing. I'd like to fill it out, using sister https://developer.mozilla.org/en-US/docs/Web/API/MIDIConnectionEvent page and w3c specs:
https://www.w3.org/TR/webmidi/#midimessageevent-interface

**Comment by chrisdavidmills** [comment]
Hi there!

I am excited by your issue — I love WebMIDI and would love to get it properly documented. Unfortunately, for various reasons (including lack of Firefox support), it is always fairly low down on the MDN priority list.

If you want to try your hand at creating some of the missing documentation, I would be happy to guide you and provide technical reviews. Maybe we could also write a plan of ideally what needs to be done, and get a community group together to work on it?

But obviously I don't want to push you into something you don't have time for. 

Shall we start by giving you editing/page creation permission and getting you working on the `MIDIMessageEvent` page?

**Comment by waterplea** [comment]
Right now there are 4 pages listed that are missing, `MIDIOutput`, `MIDIMessageEvent`, `MIDIPort` and `Navigator.requestMIDIAccess()`. Also, there is general page for `Web MIDI API` that is missing (it is also not listed in Web APIs overview page. I can start with `MIDIMessageEvent` and we will see.

**Comment by chrisdavidmills** [comment]
@waterplea ok, cool, let's do that. I've given you the necessary permissions you need to create the page(s). Let me know if you need any help, or want a review of work.

**Comment by waterplea** [comment]
I've made the page:
https://wiki.developer.mozilla.org/en-US/docs/Web/API/MIDIMessageEvent

Will try to find time to add more pages to MIDI section of the MDN.

**Comment by chrisdavidmills** [comment]
> I've made the page:

Thanks so much @waterplea ! This is looking pretty good; I just gave it a small copy edit and fixed a few styles.
