### ISSUE TITLE
/ja/docs/Web/CSS/box-sizing

### ISSUE THREAD

**Issue by y-nakata** [mdn/sprints#2792]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example displays no result. I should display the same result as the en-US box-sizing page.
https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

**Comment by SphinxKnight** [comment]
I've fixed it and it looks good from here.
Please do reopen if necessary
