### ISSUE TITLE
/en-US/docs/Web/HTML/Global_attributes/tabindex

### ISSUE THREAD

**Issue by alattalatta** [mdn/sprints#2793]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The "Tabindex Accessibility" has a few problems.

- `<button>` can't have interactive contents as its content. "Phrasing content but there must be no Interactive content."
- Pressing the button itself (the area of its padding, outside the `<label>`) doesn't trigger the file input.
- I can't trigger the file input with my keyboard, as the button (focusable) has nothing to do with the input, only the label (non-focusable).
- The input has `tabindex=-1` but it doesn't use `focus()` anywhere and has no visual, which contradicts "could be focused with Javascript or visually." Is `tabindex` necessary for screen readers?

I would remove the part, but it's quite a big part of the document and I'm no expert at accessibility - requesting corrections.

**Comment by chrisdavidmills** [comment]
Yeah, I think you're totally right here. The example is quite fun, and an interesting use of the FileReader API. However, the `tabindex` is no use at all, as the element it is applied to is then hidden using `visibility: hidden`, which makes it invisible to both sighted users and non-sighted screenreader users. Plus all the problems you've highlighted.

I've removed it.
