### ISSUE TITLE
/ru/docs/Web/API/Worker/postMessage

### ISSUE THREAD

**Issue by Quake11** [mdn/sprints#2794]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Wrong russian translation
**date** should be replaced with **data**

![image](https://user-images.githubusercontent.com/11279501/74086175-71e88a80-4a91-11ea-94e1-cfcdc0872c25.png)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
