### ISSUE TITLE
Automate recording deployments in CI

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#280]
# User story
As a MDN developer, I want to automatically record deployments in New Relic and Speedcurve, to avoid human error and forgetfulness.

# References

* [bug 1445641](https://bugzilla.mozilla.org/show_bug.cgi?id=1445641) - Record deployments in New Relic and Speedcurve

# Acceptance criteria
* Stage and production deployments are automatically recorded in New Relic and Speedcurve

**Comment by escattone** [comment]
Other than an initial hiccup with the first run on production, this has been working reliably for several days now for both stage and production.
