### ISSUE TITLE
For the Date constructor with component values, should make it clear that these are local time.

### ISSUE THREAD

**Issue by richardejc** [mdn/sprints#2801]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
For the constructor of `Date` with [Individual date and time component values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#Individual_date_and_time_component_values), the docs don't make it clear that the values represent local time, rather than UTC. Please clarify in the docs that they represent local time.

(This is particularly confusing as every other example on the page is shown to be UTC.)

**Comment by jadjoubran** [comment]
@chrisdavidmills I would like to take this one ✋

**Comment by chrisdavidmills** [comment]
Assigned. Thanks @jadjoubran !

**Comment by sideshowbarker** [comment]
@richardejc If you confirm the change at https://github.com/mdn/content/commit/f46cbf3 resolves this to your satisfaction, then this can be closed.

**Comment by Elchi3** [comment]
Let's close this. Thanks!
