### ISSUE TITLE
/ko/docs/Web/HTML/Inline_elements

### ISSUE THREAD

**Issue by junseol86** [mdn/sprints#2803]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/8084586/74295672-149c5400-4d85-11ea-89d0-067673776688.png)
There is a space missing between 'p' and 'class'.

**Comment by SphinxKnight** [comment]
I've fixed it.
Don't hesitate to click the edit button and fix such typos :) (I can identify typos in code but I cannot intervene for Korean)
