### ISSUE TITLE
Change the word 'layout' to 'delay'

### ISSUE THREAD

**Issue by imthiazSD** [mdn/sprints#2805]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/Performance/Critical_rendering_path

In the documentation for CRP, there is an improper usage of a word in the 'Layout' section, 4th paragraph, 3rd line. It should be  *While a 20ms delay on load*, instead it is  *While a 20ms layout on load*

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
