### ISSUE TITLE
E - Cover the most common web dev security problems

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2809]
# Epic
As a web developer, I want up-to-date, thorough resources on web security so that I can ensure my sites are developed with best practices in security.

# Acceptance criteria

- [ ] Web security docs have been updated and expanded. 

# Tasks

1. - [x] Audit current security docs to see what we have, and how up-to-date it is.
2. - [x] Discuss audit with Moz security folks, to find out what they think would be ideal/desirable to have.
3. - [x] Make a plan for updating/expanding sec docs.
4. - [ ] Update and expand sec docs. (Will be multiple user stories.)

**Comment by chinikes** [comment]
NOTE - Epic no longer needed as per updated approach
