### ISSUE TITLE
PWA page link list: possible spam

### ISSUE THREAD

**Issue by valgrimm** [mdn/sprints#2813]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Should this Pokedex link be on the PWAs page?

![image](https://user-images.githubusercontent.com/56933147/74558585-d52b5e80-4f62-11ea-9358-2e5c121e653a.png)

**Comment by chrisdavidmills** [comment]
Yup, it's a good example of a PWA.
