### ISSUE TITLE
/en-US/docs/Web/API/Document/cookie

### ISSUE THREAD

**Issue by cseepe** [mdn/sprints#2814]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
Page: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
Section: Write a new cookie > ;path=path
Text: The path must be absolute (see RFC 6265). For more information on how to use relative paths, see **this paragraph**.

Problem: "this paragraph" in the above text links to: 
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#Using_relative_URLs_in_the_path_parameter
The anchor "Using_relative_URLs_in_the_path_parameter" does not exist on that page.

**Comment by chrisdavidmills** [comment]
@cseepe thanks for bringing this up. I've actually just deleted the whole sentence, because it seems confusing to me - "you must use absolute paths, oh but wait here's a link to a section that tells you how to use relative paths..." ?
