### ISSUE TITLE
/en-US/docs/Web/CSS/scrollbar-width

### ISSUE THREAD

**Issue by WebMechanic** [mdn/sprints#2816]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Accessibility
IMHO this page / property is in serious need of an Accessibility notice. Setting the `scrollbar-width` to "thin" or "none" makes content hard or impossible to scroll if the author does not provide alternative means of scrolling. While swiping or mouse wheeling over such areas might work, some pentablets have no scroll alternative e.g. "jog shuttles".

On HD screens "thin" is also hard to hit with a mouse cursor.

Thanks.

**Comment by chrisdavidmills** [comment]
@WebMechanic I agree with you; what do you think of this:

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#Accessibility_concerns

?

**Comment by WebMechanic** [comment]
Nice one! :) that was quick!
And thank you for adding the guideline links.

There's a typo in "mechnism".

With ragard to Retina/HD screens: "thin" and the recommended 44px (~ 1.12cm?) don't really match up, right? Should this be mentioned near the last sentence about the recommended target size?
I can't tell how thin "thin" appears on Apple devices. They're definitely a tad too slim on Win10 and Android.

---- 
Unfortunately there appears to be no browser setting (or general OS feature) to define a minimum scrollbar width or a "prefers-" MQ property.

I personally hate this "design trend" and find thin scrollbars very hard to hit with my pen even on 1dpr screens. On touch screens there's always an issue with the parallax view that turns these tiny scrubbers in a constant hit and miss experience.

**Comment by chrisdavidmills** [comment]
Cool, I've fixed the typo and added some additional info advising thorough testing, as the problem coujld be worse on high res screens.

I'd rather not add too much more, as the whole thing tends to get complex and subjective after a while. I'd prefer to leave this up to devs to do their testing properly; at least we are including some info to make them think about it.

Yes, it might be an interesting MQ to have available, but then again this would be adding a very specific feature to the platform to mitigate the harm done by another very specific feature. I think we should have just left it alone in the first place ;-)

Thanks again for your help.

**Comment by WebMechanic** [comment]
great job @chrisdavidmills ! thank you!

> I think we should have just left it alone in the first place ;-)

Fully agree! When IE4+ supported custom scrollbars there where loads of horribly coloured and partially visible bars roaming the web. I remember that at some point early Chrome had some of these proprietary properties too, but it seems like they're gone with Blink -- for good I hope.
