### ISSUE TITLE
Please update the doc to indicate that glmatrix needs to be included for the examples to work

### ISSUE THREAD

**Issue by Vaporbook** [mdn/sprints#2817]
Hi,

The doc at https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context doesn't mention the dependency on glmatrix as an external script (except for one oblique reference to it in a comment that I saw after debugging extensively and googling about this).

As it stands, most folks will run into the issue of mat4 being undefined, which is confusing in particular because it's a type in the gl scripts. I added a script src to https://mdn.github.io/webgl-examples/tutorial/gl-matrix.js in order to resolve the dependency. I think the doc just needs to mention it more explicitly as a basic requirement for the tutorial.

Thanks,
Aaron

**Comment by davidgilbertson** [comment]
For npm users:
```
npm i gl-matrix
```

Then in your code:
```js
import { mat4 } from 'gl-matrix';
```

Optionally, get the TypeScript type definitions:
```
npm i @types/gl-matrix -D
```

**Comment by a2sheppy** [comment]
@Elchi3 I can take this over for you if you like. I've been working with glMatrix and WebGL a lot lately doing WebXR, so this would be pretty trivial for me to handle.

**Comment by Elchi3** [comment]
@a2sheppy That would be so fantastic! I haven't had the time to get to this :(

**Comment by Elchi3** [comment]
As sheppy says, there is a PR submitted for this now https://github.com/mdn/webgl-examples/pull/29. 

Anyone wants to review?

**Comment by a2sheppy** [comment]
This doc is updated and I've merged the code updates, so this issue should now be completed.
