### ISSUE TITLE
Issues on the aria label page

### ISSUE THREAD

**Issue by domoritz** [mdn/sprints#2818]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
 
At https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

The icon is missing

<img width="692" alt="Screen Shot 2020-02-16 at 14 25 12" src="https://user-images.githubusercontent.com/589034/74614053-66b4e080-50c9-11ea-9b3d-9d2d91f7ab06.png">

And the working example isn't on the page. 

<img width="1102" alt="Screen Shot 2020-02-16 at 14 24 39" src="https://user-images.githubusercontent.com/589034/74614055-687ea400-50c9-11ea-8df1-d00ffff505b7.png">

**Comment by chrisdavidmills** [comment]
Hrm, this page has been in draft form for a very long time, and I don't know when we'll ever get round to finishing it off. It's been hanging around in this state for 8 years now!

Anyway, thanks for bringing it up. I've removed the weirder bits that you mention, and added a draft notice to the top of it.

**Comment by domoritz** [comment]
Thanks for the quick update.
