### ISSUE TITLE
/ru/docs/Web/API/Document/designMode

### ISSUE THREAD

**Issue by Quake11** [mdn/sprints#2819]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/11279501/74615156-0bb5d480-512f-11ea-83b3-ca958599f80a.png)

Typo. Should be "off"

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
