### ISSUE TITLE
Do not prompt to re-remember the preferred language

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#282]
# User story
As a MDN visitor, when I say that I prefer English, I don't want to be asked again.

# References

* [bug 1471829](https://bugzilla.mozilla.org/show_bug.cgi?id=1471829) - Do not prompt to remember the language that is already the preferred language

# Acceptance criteria
* If the user has a ``django_language`` cookie set to ``en-US``, don't show the dialog asking them if they prefer English.

**Note**: This is currently assigned to @safwanrahman, @jwhitlock is mentor / backup.

**Comment by safwanrahman** [comment]
I am working on this. Figuring out how to pass the `cookie` name from the backend to frontend javascript. I dont want the name to be hardcoded

**Comment by jwhitlock** [comment]
Deployed to production.
