### ISSUE TITLE
/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

### ISSUE THREAD

**Issue by DanSmaR** [mdn/sprints#2820]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
 the following element, from the "Track sizing and minmax()"
           "<iframe class="live-sample-frame sample-code-frame" id="frame_Track_sizing_and_minmax()" src="https://mdn.mozillademos.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout$samples/Track_sizing_and_minmax()?revision=1473793" width="240" height="470" frameborder="0"></iframe>"

    is not working correctly. Nothing appears in the screen.
![Screenshot_2020-02-16 Basic Concepts of grid layout](https://user-images.githubusercontent.com/58406436/74616738-5e2fca80-5108-11ea-98ec-14ce8ef70ae8.png)

By the way, great tutorials, enjoying!

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
