### ISSUE TITLE
/fr/docs/Web/JavaScript/Guide/iterateurs_et_generateurs

### ISSUE THREAD

**Issue by lamoi-ch** [mdn/sprints#2821]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
in chapter "Itérateurs et générateurs" (https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/iterateurs_et_generateurs), first example, use of result.value (undefined) instead of resultat.value
>

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately, we only maintain the English MDN docs. Feel free to sign up for an account and fix the French wiki page yourself.
