### ISSUE TITLE
JavaScript Demo: JSON.stringify() does not print valid JSON in the live example output window

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2822]
@SherylHohman commented on [Sat Feb 15 2020](https://github.com/mdn/kuma/issues/6510)

re page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

The live example demonstrating `JSON.stringify()` does NOT display a valid JSON string.   
It's neither a string, nor JSON. 
This is what the return window displays as the results of 4 `JSON.stringify()` example commands:  

 > "{"x":5,"y":6}"
> "[3,"false",false]"
> "{"x":[10,null,null,null]}"
> ""2006-01-02T23:04:05.000Z""

Clearly, his is incorrect.    
And it's very confusing.   

The double quotes are incorrectly paired.  Each line should be wrapped in single quotes instead.  
Or removed altogether.

It could print:  
> {"x":5,"y":6}
>[3,"false",false]
>{"x":[10,null,null,null]}
>"2006-01-02T23:04:05.000Z"  
so that the quotes properly pair off.

Better yet, it could (should) print the above, but wrap each result in single quotes, to indicate that the result is a string, not an object:  
> '{"x":5,"y":6}'
>'[3,"false",false]'
>'{"x":[10,null,null,null]}'
>'"2006-01-02T23:04:05.000Z" ' 

One has to have a good understanding of `JSON.stringify()` already and then correctly interpret what caused the buggy-looking output, in order to make sense of the bizarre results, as currently displayed.  
Trying to learn about this function from looking at the results of this live example, increases confusion, and hinders learning.   

The routine used to write the output for this window needs to be modified to wrap the results in single quotes instead of double quotes.   

Or, if that cannot be done, 
REMOVE the example RUN window altogether, for this page.  That example output is hurtful, not helpful.   

It's better for visitors to never see this misleading, confusing, live example output.   
Instead they can learn it by reviewing the code later on the page, where the correct format of `JSON.stringify()` results is properly, and clearly, shown in the code comments.

**Comment by jadjoubran** [comment]
Hey @chrisdavidmills 
I'd be happy to take a look at this, I might have some experience as I've built something similar for my courses
Can you please give me a pointer as there where I should look? Thanks!

**Comment by chrisdavidmills** [comment]
Sure thing Jad. The corresponding source for this page is at https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/stringify/index.html

In each case, you can find it via the "Source on GitHub" link at the botto of each page.

**Comment by chrisdavidmills** [comment]
Hi @jadjoubran ! Did you get round to looking at this?

**Comment by jadjoubran** [comment]
Not yet, will try to do so very soon!

**Comment by jadjoubran** [comment]
Just opened a PR 👍 
If you ever feel that the console needs major improvements, let me know! While reading the source code I realised that it is _very_ similar to the one I have on [Learn JavaScript](https://learnjavascript.online). I do have color-coding for the different primite types (String, Number, Boolean, etc.)

**Comment by jadjoubran** [comment]
Hey @chrisdavidmills, just double checking this [PR](https://github.com/mdn/bob/pull/552), maybe we should ping someone specific to review it? (I am not sure who reviews mdn/bob)

Thanks!

**Comment by jadjoubran** [comment]
I think this can be closed now? Though the new version of mdn/bob is not live (as tested on [JSON.stringify mdn page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify))

**Comment by chrisdavidmills** [comment]
It'll be live soon, so yeah, let's close!
