### ISSUE TITLE
/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

### ISSUE THREAD

**Issue by Qoaiaely** [mdn/sprints#2823]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Just a tiny typo spotted in the Grid guides section. Cheers, love you guys!

![image](https://user-images.githubusercontent.com/55412073/74667342-67ba4080-51a3-11ea-822b-c425c786f6cc.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting! I've fixed it on the page you cite, but it still seems wrong on some of the other grid tutorial pages. I think we need to wait for the change to filter through the system.
