### ISSUE TITLE
How CSS is structured Lesson - Possible Typo

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#2824]
# Request type

- [X] Correction or update

# Details

Ref: "[How CSS is structured - Shorthands](https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured#Shorthands)" lesson, in the fourth code example box under "Does the same thing as all these together:", line 5 of the code example,
Should not `background-scroll: fixed;`, be wrote as `background-attachment: fixed;`?
I could not get  `background-scroll: fixed;` to work as expected, or at all really. However, `background-attachment: fixed;` will work as expected.
Ref: MDN web docs "[background-attachment](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment)"

As always, a big thanks to the mozilla MDN web docs team!
These tutorials are just amazing!

**Comment by chrisdavidmills** [comment]
You are absolutely correct, 10 points to Gryffindor ;-)

I've fixed it, thanks for reporting.
