### ISSUE TITLE
/en-US/docs/Web/API/History/pushState

### ISSUE THREAD

**Issue by Grantsirian** [mdn/sprints#2825]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

bracket is on the wrong side of the comma

![image](https://user-images.githubusercontent.com/19785283/74713675-b7474d80-5231-11ea-875d-e06ffc18d8f4.png)

**Comment by chrisdavidmills** [comment]
It isn't. The `url` is an optional parameter, and if it isn't included, you wouldn't include the comma separator either, so therefore the comma is optional too.

**Comment by Grantsirian** [comment]
> It isn't. The `url` is an optional parameter, and if it isn't included, you wouldn't include the comma separator either, so therefore the comma is optional too.

Thanks for explaining that. I will note that going forward.
