### ISSUE TITLE
A minor issue. https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_lists

### ISSUE THREAD

**Issue by Gorm2303** [mdn/sprints#2826]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Just a minor issue. When you're on the page "styling lists" under "Learn Web Development", the menus to the left show a different version of the original menu. Check the images if you don't understand what i'm saying. 

It happens that "Styling Boxes" and "Introduction to CSS" appears and "CSS first steps" and "CSS building blocks" disappears.

![image](https://user-images.githubusercontent.com/61201593/74759330-eaf99600-5278-11ea-876a-4544f68bb4fc.png)
<hr><hr>

![image](https://user-images.githubusercontent.com/61201593/74759924-dd90db80-5279-11ea-8d09-7e4bbaa7812d.png)

**Comment by chrisdavidmills** [comment]
Hrm, this shouldn't be happening, as I updated the Learning area sidebar structure a while ago. It should look like it does here on every page: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps.

@escattone, is there an easy way to regenerate all the pages under https://developer.mozilla.org/en-US/docs/Learn/, so we can make sure the correct sidebar is being shown in all places?

**Comment by escattone** [comment]
> @escattone, is there an easy way to regenerate all the pages under https://developer.mozilla.org/en-US/docs/Learn/, so we can make sure the correct sidebar is being shown in all places?

@chrisdavidmills I created [this issue](https://github.com/mdn/kuma/issues/6532) and I'll talk to @tobinmori and @atopal about getting that work triaged.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I created this issue and I'll talk to @tobinmori and @atopal about getting that work triaged.

cheers mate! I'll close this issue then, since it is now being tracked over there.
