### ISSUE TITLE
/en-US/docs/Glossary/Syntax

### ISSUE THREAD

**Issue by hazim** [mdn/sprints#2829]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I believe there is an error with the Wikipedia link towards the bottom of this section found at, Learn more > General knowledge > Syntax (programming language)  

Currently, it is pointing to, 
https://en.wikipedia.org/wiki/Syntax_(programming_language)
instead, I believe it should be this one, 
https://en.wikipedia.org/wiki/Syntax_(programming_languages)
It is missing the **"s"** at the end of **"language"**

Hope this helps!

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
