### ISSUE TITLE
Add "Link to this Paragraph" elements to section headers

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#283]
# User story
As an MDN Visitor, I would like an easy way to get the anchor for a section, so that I can link directly to the content.

# References
* [bug 1307217](https://bugzilla.mozilla.org/show_bug.cgi?id=1307217) - Add "Link to this Paragraph" elements to section headers

# Acceptance criteria
* There is an easy way to get the full URL with anchor for a section. The ReadTheDocs solution is the benchmark (A "¶" symbol that links to the anchor that appears on hover).

**Comment by jmswisher** [comment]
This was not added to the Q3S2 P1 dev bugs epic (#276), so I'm removing this from the Sprint 2 milestone.

**Comment by jwhitlock** [comment]
Thanks @jmswisher, I missed this one. Added to goals doc and stories sheet as well

**Comment by jmswisher** [comment]
@schalkneethling It's part of the current sprint, based on @jwhitlock 's comment above.
