### ISSUE TITLE
I set default language english in profile, but site's language always my local.

### ISSUE THREAD

**Issue by hzx** [mdn/sprints#2837]
# Request type

- [ ] Show site in language I set in my profile. In addition even after selecting default language in popup.

# Details
I set default language english in profile, but site's language always my local.
<img width="1790" alt="Screen Shot 2020-02-21 at 02 34 40" src="https://user-images.githubusercontent.com/869203/74990065-45e6e500-5453-11ea-9e0d-015dcb6fa4f8.png">

<img width="1781" alt="Screen Shot 2020-02-21 at 02 35 22" src="https://user-images.githubusercontent.com/869203/74990066-4a130280-5453-11ea-8f05-76d781c4002b.png">

<img width="627" alt="Screen Shot 2020-02-21 at 02 40 17" src="https://user-images.githubusercontent.com/869203/74990160-8e9e9e00-5453-11ea-994f-132b3340c13e.png">

<img width="1792" alt="Screen Shot 2020-02-21 at 02 41 51" src="https://user-images.githubusercontent.com/869203/74990386-3caa4800-5454-11ea-940c-bc176e10f08a.png">

**Comment by chrisdavidmills** [comment]
This is more of a platform issue, so I'll move this over to the kuma repo.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #6550](https://github.com/mdn/kuma/issues/6550) via [**ZenHub**](https://www.zenhub.com/)
