### ISSUE TITLE
/zh-CN/docs/Web/CSS/filter

### ISSUE THREAD

**Issue by TheVoidsteppers** [mdn/sprints#2838]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

对于 函数->blur() 的介绍
“给图像设置高斯模糊。“radius”一值设定高斯函数的标准差”这句，'radius' 应改为 'length'

**Comment by chrisdavidmills** [comment]
I'm not sure if this change is needed. The value given is a length value, but the value is commonly referred to as the blur radius.
