### ISSUE TITLE
Provide documentation for `Disable Framework Grouping` feature in Firefox DevTools

### ISSUE THREAD

**Issue by janodvarko** [mdn/sprints#2839]
# Request type
- New documentation

# Details

`Disable Framework Grouping` is a feature in the Debugger panel (Firefox DevTools). This feature automatically groups  JS stack-trace frames coming from known framework. The user is usually not interested in stack frames coming from frameworks so, this greatly simplifies the content of the `Call Stack` panel.

Some STR to check out this feature:
1. Load `https://ahfarmer.github.io/calculator/`
2. Open DevTools and select the Debugger panel
3. Create BP in `ahfarmer.github.io/calculator/static/js/component/Button.js` on line 11 (in the render 4. method)
5. Click a button on the page, the debugger should hit the BP
6. Check out the `Call Stack` panel, you should see one expandable entry for React frames (with 9 frames)

-

More info
* Nice post about the Call stack panel: https://hacks.mozilla.org/2017/05/debugger-html-call-stack-improvements/ (but grouping not there)
* Not sure where the doc should go on MDN but here is a note about the Call Stack panel
https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Call_stack

Honza

**Comment by janodvarko** [comment]
Screenshot of the feature

![image](https://user-images.githubusercontent.com/37785/75034496-9a1eb300-54ad-11ea-9ce3-33c7f010fae9.png)

Stack frames coming from React library collapsed on the first screenshot and expanded on the second screenshot.

**Comment by chrisdavidmills** [comment]
@janodvarko what Fx version did this land in?

If it is very new, then we can get it done in due course as part of our Firefox releases work. If it landed a few versions ago, then I'll get @jmswisher to fold it into the Fx75 new features work, so we can get it done in the next sprint.

**Comment by janodvarko** [comment]
@jasonLaster when `Disable Framework Grouping` landed (what Fx version)?

**Comment by hamishwillee** [comment]
Thanks very much for this @janodvarko - in particular for the link to the useful information about what this feature "means":  [doc provided by jano](https://hacks.mozilla.org/2017/05/debugger-html-call-stack-improvements/)

@chrisdavidmills Some of this was implied by the right-context section at the end of [Debugger > UI_Tour > Call stack](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Call_stack). I've updated the whole section to additionally:
- Explain what a call stack is, and hence why this whole tool is useful
- Adds a para about why framework grouping is useful (and points to how it is disabled). This is specific response to this defect report:
  > Lines for framework libraries used by your code (e.g. React, jQuery, Webpack, Backbone etc.) are grouped by default, and represented by a framework-specific icon (see the jQuery frame in the screenshot above). Generally you won't want to debug into the code of framework libraries, so grouping these reduces the complexity of the call stack list. You can still expand and inspect the grouped frames if needed, or disable framework grouping using a right-click context menu option: Disable framework grouping. 
- Add a para about ignoring source - also useful for skipping framework libraries.

Would appreciate quick review when you have time.

**Comment by chrisdavidmills** [comment]
Reads pretty well to me, @hamishwillee . I think we can close this now.
