### ISSUE TITLE
Update doc for the Network panel (DevTools)

### ISSUE THREAD

**Issue by janodvarko** [mdn/sprints#2841]
# Request type
- Correction or update

# Details

This is a follow up for bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1614115#c4

The following page on MDN already contains a note about why response headers are all in lowercase:
`If you noticed that the keys in the response header are all in lowercase, while the request headers keys are not, that is by design.`

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details

It would be great to extend the note and mention the following:

* In http/2 all response headers are in small case.
* See: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Headers
* RFC: https://tools.ietf.org/html/rfc7540#section-8.1.2
* There might be exception like `X-Firefox-Spdy` header, which is added by Firefox [1] (not sent by the server)
Honza

[1] https://searchfox.org/mozilla-central/rev/b1e51ad5613ad3d911cf42e3e525885ce2278915/netwerk/protocol/http/Http2Stream.cpp#1084

**Comment by jmswisher** [comment]
@janodvarko : Can you tell me more about why this difference in design/display of the response vs. request headers? If the standard requires that they all be lower-case, why show the request headers in title case?

**Comment by jmswisher** [comment]
Expanded the note in the [Response headers](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Response_headers) section. I explained the difference as "response headers are shown as they are received from the server" -- hope that's correct.

**Comment by Elchi3** [comment]
@janodvarko Can you answer Janet's question? Do the changes look good to you?
