### ISSUE TITLE
/en-US/docs/Web/CSS/min-width

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [mdn/sprints#2842]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The `Values` section defines the `<percentage>` value as:

```
<percentage>
    Defines the min-width as a percentage of the containing block's height.
```

That should be "...as a percentage of the containing block's **width**", no?

**Comment by chrisdavidmills** [comment]
You are correct - thanks for reporting this!

Fixed now.
