### ISSUE TITLE
/en-US/docs/Web/CSS/Using_CSS_custom_properties

### ISSUE THREAD

**Issue by ElvinGarcia** [mdn/sprints#2846]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The description needs to be more clearly define.
Explicit telling the reader that variables needs to be declared with a scope would help clarify this article. 
"Variables in CSS should be declared within a define CSS selector scope"
" Variables are case sensitive"

**Comment by chrisdavidmills** [comment]
I agree with you here; I've expanded this section to include the details that you specified:

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Basic_usage

Does this look OK?

**Comment by ElvinGarcia** [comment]
Looks amazing. Thank you for considering the changes.

**Comment by chrisdavidmills** [comment]
@ElvinGarcia and thank you for helping to make our docs better.
