### ISSUE TITLE
/ru/docs/Learn/Server-side/First_steps

### ISSUE THREAD

**Issue by prodocik** [mdn/sprints#2847]
# Request type

in Russian documentation
For now: Делаем решения в вашем годе — Условия
Needs to be: Делаем решения в вашем коде — Условия

# Details

В разделе: Java Script - Блоки в Javascript - Делаем решения в вашем коде — Условия
Ошибка в слове "коде"

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately, we only maintain the English MDN docs. Feel free to sign up for an account and fix the Russian wiki page yourself.
