### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

### ISSUE THREAD

**Issue by dimitarget** [mdn/sprints#2849]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details
in Examples->Classical inheritance with Object.create()->line 22 :"if You dont set Object.prototype.
constructor..." must be "if You dont set Rectangle.prototype.constructor..."

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
