### ISSUE TITLE
Add URL API overview page to GroupData.json

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#2855]
https://github.com/mdn/sprints/issues/1047 wrote [an overview page for the URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL_API), but it's not listed in the "overview" property of the  [GroupData.json](https://github.com/mdn/kumascript/blob/master/macros/GroupData.json) entry:

```json
        "URL API": {
            "interfaces": [ "URL",
                            "URLSearchParams",
                            "HTMLHyperlinkElementUtils",
                            "URLUtilsReadOnly" ],
            "methods":    [],
            "properties": [],
            "events":     []
        },
```

We need to add an "overview" property to this entry like:

```json
        "URL API": {
            "overview":   [ "URL API" ], 
            "interfaces": [ "URL",
                            "URLSearchParams",
                            "HTMLHyperlinkElementUtils",
                            "URLUtilsReadOnly" ],
            "methods":    [],
            "properties": [],
            "events":     []
        },
```

Then we will get a link to the overview page in the list at https://developer.mozilla.org/en-US/docs/Web/API#Specifications and in API sidebars generated using [APIRef.ejs](https://github.com/mdn/kumascript/blob/master/macros/APIRef.ejs).

**Comment by chrisdavidmills** [comment]
PR created to fix issue: https://github.com/mdn/kumascript/pull/1344

Waiting on review from @wbamberg.
