### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams$revision/1215549

### ISSUE THREAD

**Issue by ryan-codingintrigue** [mdn/sprints#2856]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Revision [1215549](https://wiki.developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams$revision/1215549) of `URLSearchParams()` by @chrisdavidmills states:

> Note that using a `URLSearchParams` instance is deprecated; soon browsers will just use a `USVString` for the init.

Is this information correct? I cannot find a source for this anywhere and seems contrary to the spec.

If it is correct, the examples on the parent [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) page should probably be updated too, right?

**Comment by chrisdavidmills** [comment]
Hrm, I can't remember what led to me making that change ;-)

Looking at the spec, it seems like this proposed change didn't happen, so I've just removed this line and cleaned up the surrounding text a bit. Thanks for bringing this up.

**Comment by ryan-codingintrigue** [comment]
Ahh, phew! Thanks very much for clarifying Chris & so quickly too 😁

**Comment by chrisdavidmills** [comment]
@ryan-codingintrigue you are welcome.
