### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

### ISSUE THREAD

**Issue by senocular** [mdn/sprints#2858]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Two code examples contain classes with constructors missing the required calls to super:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super#Super-calling_static_methods

```
class Square extends Rectangle {
  constructor() {}
  // ...
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super#Deleting_super_properties_will_throw_an_error

```
class Derived extends Base {
  constructor() {}
  // ...
```

In the case of the Derived example especially, the missing `super` will throw before the expected error from the delete method that the example is trying to demonstrate.

Expected constructor functions (in both cases) for the derived classes:

```
  constructor() {
    super();
  }
```

**Comment by MendyBerger** [comment]
I removed the constructors from these classes all together since they were empty anyway, and the [default constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Description) does call super, which fixes this issue

**Comment by chrisdavidmills** [comment]
Thanks @MendyBerger ! I think this fixes the issue, so closing now, but please jump in @senocular if you think anything else is needed here.
