### ISSUE TITLE
Define remaining work to remove Font Awesome

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#286]
# User story
As a front-end developer, I want to know the remaining uses of Font Awesome, so that I can replace them and remove the font.

# Resources
* [bug 1451261](https://bugzilla.mozilla.org/show_bug.cgi?id=1451261) - Replace FontAwesome with SVG icons

# Acceptance criteria
* Remaining uses of Font Awesome are identified
* Remaining tasks are estimated

**Comment by jwhitlock** [comment]
@schalkneethling I'll put my notes on [bug 1451261](https://bugzilla.mozilla.org/show_bug.cgi?id=1451261), unless you already have a document. I'm not sure if there is enough remaining work for an epic + issues, or if an issue would cover the remaining work.

**Comment by schalkneethling** [comment]
Thanks @jwhitlock I reckon an issue will do the trick.

**Comment by schalkneethling** [comment]
@jwhitlock Do you want me to close this one and then open separate issue(s) for the actual work? I want to see if I can break this into either two 2 pointers or maybe even four 1 pointers. Let me know.

**Comment by jwhitlock** [comment]
Let's leave the investigation in Sprint 2 and open new implementation issue(s) for sprint 3.
