### ISSUE TITLE
Typo in pt-PT "document.cookie" article

### ISSUE THREAD

**Issue by saturnian99** [mdn/sprints#2864]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

At the "document.cookie" article, there is a typo in the text of the "Security" section.

![screenshot-article-correction](https://user-images.githubusercontent.com/60621615/75470537-95f00b00-596f-11ea-8e1a-b267fd108d09.png)

**Comment by chrisdavidmills** [comment]
@saturnian99 Can you give me the exact URL of the page you are seeing this typo on? I can't seem to see this section when I look at our document.cookie page.

Thanks!

**Comment by saturnian99** [comment]
Hey @chrisdavidmills, sorry. Forgot to reference the link, it's the portuguese translated version of the site:
https://developer.mozilla.org/pt-PT/docs/DOM/document.cookie
