### ISSUE TITLE
/en-US/docs/Learn/Forms/HTML5_input_types

### ISSUE THREAD

**Issue by luisgiraldov** [mdn/sprints#2873]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/46464109/75486493-9cd04b00-597a-11ea-85b8-9bf182fe1967.png)

Hi, I was reading the content, and I found a typo. 
It is a quick fix. I believe it is supposed to say Libraries and not libraies.

https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types

**Comment by chrisdavidmills** [comment]
@luisgiraldov fixed; thanks for reporting!
