### ISSUE TITLE
/en-US/docs/Web/HTML/Element/form

### ISSUE THREAD

**Issue by ptemrz** [mdn/sprints#2874]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
Please check the code block in the _examples_ section. It looks like label tags are closed prematurely on lines 3 and 11. The code examples, when wrapped in appropriate boilerplate code, do not pass the W3C html validator because of the stray label tags.

**Comment by chrisdavidmills** [comment]
You are correct - those first two examples are using implicit association of `<label>` and `<input>`, when `<label>` wraps both the label text and `<input>`. So the first closing `</label>` tag needed removing in each case.

I've removed them now; thanks for reporting!
