### ISSUE TITLE
/en-US/docs/Learn/JavaScript/Asynchronous/Introducing

### ISSUE THREAD

**Issue by Lennerados** [mdn/sprints#2875]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On [Introducing asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing) in the second paragraph of the section "Synchronous JavaScript", the "([see it live here](https://mdn.github.io/learning-area/javascript/asynchronous/introducing/simple-sync.html), and [see the source](https://github.com/mdn/learning-area/blob/master/javascript/asynchronous/introducing/simple-sync.html))" links go to the example of the previous [Concept site](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts), although the entire section is about the code in the code snippet without any reference to the previous example. The colons behind the sentence enhances the impression that the example behind these links is the same as in the following code snippet.

So I think it would make more sense to either (1) remove both links or (2) link it to a demo website and the code containing the example in the code snippet.

**Comment by chrisdavidmills** [comment]
Argh, how embarrassing! I am sorry if this wasted your time.

I have now changed the links to point to the correct code example.

Thanks for reporting this!
