### ISSUE TITLE
Discrepency in Page Title vs Link

### ISSUE THREAD

**Issue by gscanlon21** [mdn/sprints#2876]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On this page: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
the last path segment in the link ("Complete_list_of_MIME_types") is contrary to what is actually on the page, which is the "Incomplete" list of Mime Types

Thanks

**Comment by chrisdavidmills** [comment]
I've changed the page title and slug to "Common MIME types", as I think it's more accurate, and "Incomplete..." sounds like a weird thing to write.
