### ISSUE TITLE
/en-US/docs/Web/Performance/Fundamentals

### ISSUE THREAD

**Issue by NeuTrix** [mdn/sprints#2878]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

Typo. Repeated the word “through”.

> What is performance?
> 
> Ultimately, user-perceived performance is the only performance that matters. Users provide inputs to the system through through touch, movement, and speech. In

**Comment by NeuTrix** [comment]
Caught a typo

**Comment by chrisdavidmills** [comment]
fixed; thanks for reporting!
