### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

### ISSUE THREAD

**Issue by robertcdawson** [mdn/sprints#2879]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the Examples section of the [Object.values() page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values), line 5 contains a variable named `arrayLikeObj1`, while line 6 refers to one named `arrayLikeObj`.

**Comment by chrisdavidmills** [comment]
Thanks for reporting!

I've updated line 6 so the two object names match.
