### ISSUE TITLE
Correction needed to Comparison_Operators page

### ISSUE THREAD

**Issue by Hypher** [mdn/sprints#2881]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This page says that "The strict equality operators (=== and !==) use the Strict Equality Comparison Algorithm and are intended for performing equality comparisons on operands of the same type. If the operands are of different types, the result is always false so 5 !== '5'."

The last sentence is wrong. Especially 5 !== '5' is true.

**Comment by Elchi3** [comment]
Yes, I think this is worded confusingly, but it's not outright wrong.

"If the operands are of different types, the result is always `false`" 
The `5  !== '5'` example is then meant to support that statement.

**Comment by Hypher** [comment]
How `5 !== '5'` could support the statement "is always `false`" since, precisely, `5 !== '5'` *is* `true`?

Did I miss something?

**Comment by Elchi3** [comment]
Updated the sentence to be more clear. https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators$compare?locale=en-US&to=1611007&from=1600926

What do you think about that?
