### ISSUE TITLE
Get process for content triage working

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#289]
# User story
As a writer, I want to have priorities sensibly managed for content bugs, so I can know what I need to work on next

# Acceptance criteria
* Priority system investigated and put in place

# Tasks
1. - [x] Explore Estelle's idea for managing content bugs.
2. - [x] Write up a short plan and discuss it with the team
3. - [x] Get agreement and move forward.

**Comment by chrisdavidmills** [comment]
Estelle's comment to me over mail:

> The general idea I have is, during triage, to assign most of what we now assign as p1s as p2s instead. There may be some true P1s: something that urgently needs to be fixed. But most things aren't true P1s. Then we add these new p2s to the bottom of the p2 list, and start with the oldest p2s first. 

> We can set a soft rule of no more than 10, 5, 3, or even 1 new P1s at any triage, or something similar. A p1 really means 'urgently needing fixing', as in docs are usable, but have broken functionality, until fixed. 

> If a P2 at the top of the list really doesn't need to get get done, we downgrade it. But at least we're hitting long abandoned p2s instead of favoring new bugs of simmilar importance just because they're new, and therefore "hawt", this week.

**Comment by chrisdavidmills** [comment]
So as I understand it, a P1 in our terminology really means "needs fixing this quarter", and a P2 really means "we will fix next quarter", with P3 being somewhere below that, and P5 meaning "we'll accept community edits, but we'll not fix this ourselves".

Am I correct here? 

I am thinking that we need to add in a category for "Need to fix urgently". We've currently been doing this on an adhoc basis, along with trivial ones that are really quick to fix (e.g. a broken link or a typo). I'd suggest this should be "P1 Major" or "P1 Critical", and should only apply to important things such as  content that suggests something problematic in terms of security.

The alternative would be to simply make that P1 and demote everything else , but this wouldn't work with how other teams do things in Mozilla, such as the MDN dev team. Better to keep it consistent?

In terms of Estelle's advice, I think a maximum of 12 new P1s per triage would be good. We have 6 full time team writers (if we include me), and we are ideally expected to fix 2 P1 bugs per sprint. So this means that at maximum, we'll refill the P1s for each sprint requirements.

IIRC, we said that in the final triage meeting of each quarter, we would go through the new bugs for that week, then look at the P2s list and see which ones we wanted to promote to P1s. I think we should do that in the triage that happens in each final sprint week.

Estelle's other really good points was always working from the bottom of the P2 list, so things don't get as outdated.

**Comment by chrisdavidmills** [comment]
The above said, I've written a plan that I'm hoping will fix the issues we encountered with the conten triage in the past: https://docs.google.com/document/d/1QTOxOni_fbgZmmMmczFBS2f3c7B-tiKafTIj4Hxumag/edit.

Comments please!

Your comments please!

**Comment by jwhitlock** [comment]
> The alternative would be to simply make that P1 and demote everything else , but this wouldn't work with how other teams do things in Mozilla, such as the MDN dev team. Better to keep it consistent?

On the development team, we also had issues with the priority definitions. We noticed that having a quarter's worth of P1 bugs meant that we often had the same bugs open and unworked at the end of the quarter. We've been trying out a new P1 definition on the dev side, which we may not have documented yet. It's something like:

- P1 - Being worked on the current sprint, or to be started in the next sprint.
- P2 - Candidates for being moved to P1, and evaluated at least once a quarter
- P3 - Staff is required, and we may get to this in the next two years
- P5 - We don't plan for staff to work on this in the next two years, but we're not ready to WONTFIX

Bugs also get a points estimate, using a system like ``[points:2]`` in the Whiteboard. This helps me populate the sprint board without involving the whole team in a Vidyo meeting.

At sprint planning, we create a ZenHub epic (such as https://github.com/mdn/sprints/issues/276) for the open P1 bugs, adding issues in mdn/sprints for new P1s and moving unfinished issues from the last sprint. Issues get estimates and confidence, and the epic totals up the estimates. Bugs are assigned in Bugzilla (status ASSIGNED) and in GitHub.  ZenHub issue linking is used to link PRs to issues, and there is often multiple PRs for a single issue. We manually close bugs and issues when the work is done (shipped, working in production, no critical issues, and follow-on work filed as bugs).

I find it much clearer to decide "Next sprint, next three months, next two years, or maybe never??" then "This quarter or next quarter?", especially when we're near the end of a quarter. 

I don't think it is very important to have the same definitions of priorities on the content and development side. Development bugs are usually sticky messes that require multiple iterations to understand the issue. The important thing is to say "we're going to start work on this and keep going until it is fixed", and limit the number of those open commitments at any time. It feels like content issues could have more agreement on estimates and completion criteria, and more chances for parallel work. Or maybe I'm wrong, and content is as much of a sticky mess as our old creaky code base 😁

**Comment by chrisdavidmills** [comment]
Cool, thank you @jwhitlock and @jmswisher. I really like the dev definitions of P1, etc. listed here, so would be willing to try something at least similar.

I've taken some useful nuggets out of John's post, and updated the following in my draft process document:

1. Making the P* definitions very similar to the dev ones.
2. Providing point estimates for each triages task
3. Creating an epic for each sprint's set of P1 content bugs.

Any more thoughts?

**Comment by jmswisher** [comment]
I added a couple of comments in the document, based on my understanding of the dev team's process.
