### ISSUE TITLE
/en-US/docs/Web/API/Document/getElementsByClassName

### ISSUE THREAD

**Issue by ynyyn** [mdn/sprints#2903]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In `Multiple Classes Example` section, it's said that _querySelector only selects full complete matches_. However, I do not notice any significant difference in the code running results from `getElementsByClassName` and `querySelector` on various browser, including FireFox, Chromium, IE.

**Comment by chrisdavidmills** [comment]
I see what you are saying here - the thing about "partial matches" in the code example is confusing, because it doesn't select partial matches, only elements that have both classes. I've cleaned this up a bit, and changed the comment to something less confusing.
