### ISSUE TITLE
Demo of example not working

### ISSUE THREAD

**Issue by romikzo** [mdn/sprints#2904]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
**Page:** https://developer.mozilla.org/en-US/docs/Web/API/Element/mousemove_event
**OS:** Mac OS Catalina 10.15.3
**Browser:** Google Chrome 80.0.3987.122

**Comment by chrisdavidmills** [comment]
This seems to work fine to me. I've also tested in Chrome 80 on macOS 10.15.

To be clear, it just draws a black line on the canvas when you hold the mouse button down over it.
