### ISSUE TITLE
Clarification on the Promise Constructor syntax for one of the examples

### ISSUE THREAD

**Issue by sushaanttb** [mdn/sprints#2908]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This is reg. the promise constructor syntax described in :
Doc : Using Promises
Section : Creating a Promise around an old callback API
Link : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

From the MDN Promises Spec , we understand that the Promise constructor takes an  "executor function" i.e. a function with 2 arguments: resolve,reject & a task def(most commonly an async task) & we call resolve ,reject accordingly based on if the task executes successfully or not.

But in the subjected section, we find that the example(shared below) uses only 1 arg. i.e "resolve" in it's constructor def.

const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

& Surprisingly this syntax works but This doesn't seems in line with the constructor spec i.e. both (resolve,reject) arguments are required thus, Request for clarification on same.

**Comment by jadjoubran** [comment]
Hey @sushaanttb 
Thanks for reporting the issue!
I can see that the documentation has this note after the `setTimeout` example: 

> Basically, the promise constructor takes an executor function that lets us resolve or reject a promise manually. Since setTimeout() doesn't really fail, we left out reject in this case.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Creating_a_Promise_around_an_old_callback_API (at the end of this paragraph)

Does that answer your question or do you feel it should be better clarified?
