### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy

### ISSUE THREAD

**Issue by 840326521** [mdn/sprints#2909]
内容问题地址：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy

问题：代码中未曾设置 product 变量，却使用了 product 变量，导致例子不够正确。

错误内容：
通过属性查找数组中的特定对象
以下代理为数组扩展了一些实用工具。可以看到，你可以灵活地“定义”属性，而不需要使用 Object.defineProperties方法。以下例子可以用于通过单元格来查找表格中的一行。在这种情况下，target 是table.rows。

let products = new Proxy([
  { name: 'Firefox', type: 'browser' },
  { name: 'SeaMonkey', type: 'browser' },
  { name: 'Thunderbird', type: 'mailer' }
],
{
  get: function(obj, prop) {
    // 缺省行为是返回属性值， prop ?通常是一个整数
    if (prop in obj) {
      return obj[prop];
    }

    // 获取 products 的 number; 它是 products.length 的别名
    if (prop === 'number') {
      return obj.length;
    }

    let result, types = {};

    for (let product of obj) {
      if (product.name === prop) {
        result = product;
      }
      if (types[product.type]) {
        types[product.type].push(product);
      } else {
        types[product.type] = [product];
      }
    }

    // 通过 name 获取 product
    if (result) {
      return result;
    }

    // 通过 type 获取 products
    if (prop in types) {
      return types[prop];
    }

    // 获取 product type
    if (prop === 'types') {
      return Object.keys(types);
    }

    return undefined;
  }
});

**Comment by 840326521** [comment]
123

**Comment by 840326521** [comment]
I'm really sorry that I read it wrong!

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately, we only maintain the English MDN docs. Feel free to sign up for an account and fix the Chinese wiki page yourself.
