### ISSUE TITLE
/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

### ISSUE THREAD

**Issue by CodeCommander** [mdn/sprints#2910]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the last code snippet of this section of the page: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Recovering_failed_requests

I'm pretty sure the "catch" is in the wrong place. The snippet shows it on the "match" promise:

```
self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((resp) => {
      return resp || fetch(event.request).then((response) => {
        let responseClone = response.clone();
        caches.open('v1').then((cache) => {
          cache.put(event.request, responseClone);
        });

        return response;
      });
    }).catch(() => {
      return caches.match('./sw-test/gallery/myLittleVader.jpg');
    })
  );
});
```

But I think it should be on the "fetch" promise:

```
self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((resp) => {
      return resp || fetch(event.request).then((response) => {
        let responseClone = response.clone();
        caches.open('v1').then((cache) => {
          cache.put(event.request, responseClone);
        });

        return response;
      }).catch(() => {
        return caches.match('./sw-test/gallery/myLittleVader.jpg');
      });
    })
  );
});
```

My correction would match the logic used in the actual sample code here: https://github.com/mdn/sw-test/blob/gh-pages/sw.js

**Comment by Rumyra** [comment]
Ah the promise catch position :) fixed 👍  https://wiki.developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
