### ISSUE TITLE
Documentation on storing sensitive information in cookies

### ISSUE THREAD

**Issue by yissachar** [mdn/sprints#2914]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The guidance at https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies states:

>A secure cookie is only sent to the server with an encrypted request over the HTTPS protocol. Even with Secure, sensitive information should never be stored in cookies, as they are inherently insecure and this flag can't offer real protection. Starting with Chrome 52 and Firefox 52, insecure sites (http:) can't set cookies with the Secure directive.

This statement is very strong ("sensitive information should never be stored in cookies,"!) but at the same time quite vague as to what is meant by "sensitive information" and why cookies are "inherently insecure" and why the flag "can't offer real protection". I belief this section would benefit from a cleanup. In the current state one can walk away with the impression that Mozilla is saying that cookies should not be used for storing session information even if other protection mechanisms (httpOnly, sameSite) are implemented, which I do not believe is the case. 

Note that https://en.wikipedia.org/wiki/Secure_cookie quotes this section as well.

Elsewhere on Mozilla (https://infosec.mozilla.org/guidelines/web_security#cookies) there is a section devoted to securing cookies that describes the exact approach to take and explicitly calls out that "these cookies often contain session identifiers or other sensitive information", and this should perhaps be linked to instead of the current guidance.

I believe the intent of https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly is to encourage users to not rely on secure cookies alone and the wording should be updated to reflect that with other protections on top of the secure flag cookies can be used to store sensitive information such as session identifiers. If this section is referring to something else, that should be clarified as well.

**Comment by hamishwillee** [comment]
The section in question was modified to correct this issue
