### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_detail_page$history

### ISSUE THREAD

**Issue by JHCover** [mdn/sprints#2917]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

![image](https://user-images.githubusercontent.com/32579276/76172381-5a64f600-6152-11ea-84fa-faba80df2eed.png)
The 'next' argument in exports.author_detail = function(req, res, next) { ... }
should be in bold text because it was added to the code. It was not included as an argument for the detail functions in the controller files you have us make originally in Express Tutorial Part 4: Routes and controllers. Same thing on the Genre detail page, and the Book detail page.

**Comment by chrisdavidmills** [comment]
@JHCover thanks for reporting!

I have had a go at adding `<strong>` around all the relevant `next` instances, but the wiki final desiplay seems to be a bit slow in updating the display in some cases. Let me know if you spot any others.
