### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Closures

### ISSUE THREAD

**Issue by liuyji** [mdn/sprints#2918]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

”词法作用域“部分最后一段最后一句，原文：

> Nested functions have access to variables declared in their outer scope.

翻译：

> 嵌套函数可获取声明于外部作用域的函数。

应更正为：

> 嵌套函数可以访问声明于外部作用域的变量。

另外这篇文章的第一段最后一句：

> In JavaScript, closures are created every time a function is created, at function creation time.

翻译为：

> 在JavaScript，函数在每次创建时生成闭包。

改为：

> 在 JavaScript 中，每次创建函数都会在函数创建时生成闭包。

是不是更好些？

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately, we only maintain the English MDN docs. Feel free to sign up for an account and fix the Chinese wiki page yourself.
