### ISSUE TITLE
Issues -moz-box-flex documentation

### ISSUE THREAD

**Issue by WildnerDesigner** [mdn/sprints#2919]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Someone posted a telephone number inside the examples: https://developer.mozilla.org/de/docs/Web/CSS/-moz-box-flex
And there is a wrong css value: -whats-app;
And problems with showing the examples: „Wert nicht in der DB gefunden!“ (Not found in database)

**Comment by chrisdavidmills** [comment]
Thanks for reporting. I have removed the phone number and corrected the incorrect css code.

I'm not sure why the CSSInfo boxes are showing as "not found in database", as the data is there, and it works in the Engish version. I've just deleted them for now.

**Comment by WildnerDesigner** [comment]
Thank you. In the example box, there is still the telephone number (between head and body). And in the title tag, there is “-whats-app”.

**Comment by chrisdavidmills** [comment]
Hrm, I did fix those, but it seems to be taking a while to update them in the final display.
