### ISSUE TITLE
/en-US/docs/Web/API/Element/innerHTML: spelling error "elment's".

### ISSUE THREAD

**Issue by adstr123** [mdn/sprints#2921]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the section "Usage Notes" -> "Reading the HTML contents of an element" there is a spelling error:

In the sentence:
> Reading innerHTML causes the user agent to serialize the HTML or XML fragment comprised of the **elment's** descendants.

... the word **elment's** should be **element's**.

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
