### ISSUE TITLE
U — [HTML] <style> element, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2923]
# Trello

https://trello.com/c/LYjL2m6K/248-html-style-element-fx-75

# Acceptance criteria

1. - [x] [style element's type attribute isn't parsed per the HTML spec rules](https://bugzilla.mozilla.org/show_bug.cgi?id=1614329)

**Comment by chrisdavidmills** [comment]
Looks like this is probably pretty small — maybe a mention on the rel notes, possibly a note on the `<style>` page.

**Comment by jmswisher** [comment]
- Updated description of the `type` attribute in the [<style>](https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/style) article
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/5889) with a note about the change

**Comment by chrisdavidmills** [comment]
@jmswisher:

* I've add a note to the Fx 75 rel notes about this: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#HTML
* I've also set the bug in question to DDC, and pointed the engineers to the changes you made: https://bugzilla.mozilla.org/show_bug.cgi?id=1614329#c8

Can you make sure that these are done in future? Thanks.
