### ISSUE TITLE
U — [HTML] lazy-loading images, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2924]
# Trello

https://trello.com/c/CcQ99rtf/247-html-img-element-fx-75

# Acceptance criteria

1. - [x] [Support <img loading="lazy"> lazy-loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784)
2. - [x] [Enable the preference for lazy load images by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1613611)

**Comment by chrisdavidmills** [comment]
Probably 1.5 points here — the usual changes on the element page, BCD, etc., but it would also be worth writing a short guide + demo that explains why this is needed, how it works, and shows what the effect is.

**Comment by rugk** [comment]
Problem with MDN doc:
* [here in the listing](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) the attribute is not marked as "experimental"
* in the [browser comp table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#bcd:html.elements.img) it is still shown as experimental

So is this standardized or is it still experimental??

**Comment by chrisdavidmills** [comment]
> So is this standardized or is it still experimental??

Thanks for calling this out @rugk. @a2sheppy , can you look into this?

**Comment by a2sheppy** [comment]
Yeah, it's not experimental. I'll submit a BCD update shortly.

**Comment by a2sheppy** [comment]
Aaaaand... submitted [BCD PR 5964](https://github.com/mdn/browser-compat-data/pull/5964).

**Comment by Elchi3** [comment]
The BCD is not yet merged and needs your input, @a2sheppy.
