### ISSUE TITLE
U — [HTML] inputmode attribute, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2925]
# Trello

https://trello.com/c/1R0RDeMW/161-inputmode-attribute-fx-75

# Acceptance criteria

1. - [x] [Update the values supported by our 'inputmode' implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1509527)

**Comment by chrisdavidmills** [comment]
Fairly small change — one attribute's worth of information. Might require a bit of explaining as to what each value does.

**Comment by jmswisher** [comment]
This is already documented per the spec. Just need to update the BCD info for Fx.

**Comment by jmswisher** [comment]
Firefox:
- First implemented in [17](https://bugzilla.mozilla.org/show_bug.cgi?id=746142)
- Put behind dom.forms.inputmode pref in [23](https://bugzilla.mozilla.org/show_bug.cgi?id=857355)
- [Still not unpreffed](https://bugzilla.mozilla.org/show_bug.cgi?id=1205133)
- Updated values to match the spec in [75](https://bugzilla.mozilla.org/show_bug.cgi?id=1509527) 

Chrome:
- [implemented for forms in 56, and globally in 66](https://www.chromestatus.com/feature/6225984592281600); should I try to represent that difference?

Spec:
- How to express the version of the spec that we're matching?
- Not sure I've found all the [WHATWG issues/PRs](https://github.com/whatwg/html/issues?q=is%3Aissue+inputmode+is%3Aclosed) for spec changes
- [Refine inputmode, exposing it on contenteditable](https://github.com/whatwg/html/pull/3260/files); Firefox is not yet addressing [contenteditable](https://bugzilla.mozilla.org/show_bug.cgi?id=1424284)

**Comment by chrisdavidmills** [comment]
@jmswisher:

* rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#HTML
* bug set to DDC: https://bugzilla.mozilla.org/show_bug.cgi?id=1509527#c15

**Comment by SebastianZ** [comment]
>     * rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#HTML

As Janet pointed out, [`inputmode` still didn't ship](https://bugzilla.mozilla.org/show_bug.cgi?id=1205133). So it should rather be removed from the release notes and be added to the [experimental features page](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) instead to avoid confusion.

Sebastian

**Comment by chrisdavidmills** [comment]
@SebastianZ ack, dammnit, I misunderstood the status of this one. Thanks man!

I've removed it from the 75 rel notes, and rtried to capture it here instead: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#HTML

Does that read ok?
