### ISSUE TITLE
U — [CSS] text, Fx 75 features

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2926]
# Trello

https://trello.com/c/FdS8hdQo/97-css-text-eg-text-text-decoration-fx-75

# Acceptance criteria

1. - [x] [Add support for the new `all` value to text-decoration-skip-ink](https://bugzilla.mozilla.org/show_bug.cgi?id=1611965)

**Comment by chrisdavidmills** [comment]
Looks like a small one — a single property addition, which will require syntax update, small page updates, a small demo perhaps, BCD. Shouldn't take too long.

**Comment by jmswisher** [comment]
Added [PR](https://github.com/mdn/data/pull/411) for the data change.

**Comment by jmswisher** [comment]
[PR](https://github.com/mdn/browser-compat-data/pull/5819) for BCD update.

**Comment by jmswisher** [comment]
Added a definition of `all` to [text-decoration-skip-ink](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink) and added lines to the live example to demo `all`. Not adding it to the interactive example, as I don't know if it's supported in other browsers.
