### ISSUE TITLE
U — [CSS] values and units, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2927]
# Trello

https://trello.com/c/99AKTpVj/186-css-values-and-units-level-4-box-sizing-level-4-fx-75

# Acceptance criteria

1. - [x] [[css-values] support CSS min() / max() / clamp() functions.](https://bugzilla.mozilla.org/show_bug.cgi?id=1519519) (also see [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/i6V9W5XJjpA))

**Comment by chrisdavidmills** [comment]
I've estimated 1.5 points — the pages all exist, but they do need a bit of cleanup, BCD updating, accessibility concerns sections filling in, and interactive examples creating.

**Comment by jmswisher** [comment]
[BCD PR](https://github.com/mdn/browser-compat-data/pull/5821)

**Comment by jmswisher** [comment]
[Interactive example for min()](https://github.com/mdn/interactive-examples/pull/1552)

**Comment by jmswisher** [comment]
Interactive examples for [max()](https://github.com/mdn/interactive-examples/pull/1553) and [clamp()](https://github.com/mdn/interactive-examples/pull/1554)
