### ISSUE TITLE
U — [CSS] images, Fx 76 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2928]
# Trello

https://trello.com/c/oiUALAeb/33-css-images-level-3-4-fx-75

# Acceptance criteria

1. - [ ] [[css-images] Consider changing initial value of 'image-orientation' to from-image](https://bugzilla.mozilla.org/show_bug.cgi?id=1607667)

**Comment by chrisdavidmills** [comment]
Looks to be fairly small, probably only needs data updates and a rel note.

**Comment by jmswisher** [comment]
@chrisdavidmills Do we have a Fx76 epic to move this to?

**Comment by jmswisher** [comment]
For future reference: [PR](https://github.com/mdn/data/pull/414) for /data

**Comment by chrisdavidmills** [comment]
> Do we have a Fx76 epic to move this to?

I didn't before, but I do now: https://github.com/mdn/sprints/issues/2991

I've updated this one to Fx76 on the content roadmap too.

**Comment by jmswisher** [comment]
Moved to Echo Foxtrot milestone

**Comment by jmswisher** [comment]
And now it's 77? Based on whiteboard value `[layout:backlog:77]` in the Bugzilla bug.

**Comment by chrisdavidmills** [comment]
@jmswisher the tracking flags say fixed in 76, but I think this is only in Nightly for now.

Let's close this for now, and wait for it to resurface later on.
