### ISSUE TITLE
U — [JS] Intl, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2929]
# Trello

https://trello.com/c/qs3x49mf/138-intl-updates-fx-75

# Acceptance criteria

1. - [x] [Ship Intl.Locale](https://bugzilla.mozilla.org/show_bug.cgi?id=1613713)
2. - [x] Check whether [Enable the relatedYear field in Intl.DateTimeFormat.prototype.formatToParts output](https://bugzilla.mozilla.org/show_bug.cgi?id=1591664) should be documented yet

**Comment by chrisdavidmills** [comment]
Shouldn't take too long to do — the features are nicely documented already, so this is mostly a matter of BCD updates and rel notes.

**Comment by Elchi3** [comment]
For `relatedYear`, docs are already done awhile ago. Marked as ddc in https://bugzilla.mozilla.org/show_bug.cgi?id=1591664#c5

For, Intl.Locale, there is:
- https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#JavaScript
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Locale and sub pages.
- BCD: https://github.com/mdn/browser-compat-data/pull/5817 (review needed)
Will mark as ddc once the BCD is there.

**Comment by Elchi3** [comment]
Done!
