### ISSUE TITLE
U — [JS] Functions and objects, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2930]
# Trello

https://trello.com/c/TJf4CE2x/101-js-functions-and-objects-fx-75

# Acceptance criteria

1. - [x] [Restrict functions returned by Function#caller](https://bugzilla.mozilla.org/show_bug.cgi?id=1610206)

**Comment by chrisdavidmills** [comment]
Fairly small bit of detail to add.

**Comment by Elchi3** [comment]
This is very minor I think. Added a release notes entry and updated the reference doc page. https://bugzilla.mozilla.org/show_bug.cgi?id=1610206#c8
