### ISSUE TITLE
U — [JS] ES classes, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2931]
# Trello

https://trello.com/c/zWPwWg3y/126-es-class-features-fx-75

# Acceptance criteria

1. - [ ] [Implement the Static class features proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1535804)

**Comment by chrisdavidmills** [comment]
Not that much to add here, but it will be nice to give this a proper treatment, with some nice examples, etc.

**Comment by Elchi3** [comment]
BCD: https://github.com/mdn/browser-compat-data/pull/5823

**Comment by Elchi3** [comment]
Docs: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields#Public_static_fields
Release notes: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#JavaScript

**Comment by Elchi3** [comment]
dev-doc-complete https://bugzilla.mozilla.org/show_bug.cgi?id=1535804#c21
