### ISSUE TITLE
U — [WebAPI] Web animations API, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2933]
# Trello

https://trello.com/c/uEQjvuN9/250-web-animations-api-fx-75

# Acceptance criteria

1. - [ ] [Turn on dom.animations-api.implicit-keyframes.enabled and dom.animations-api.autoremove.enabled in release channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1618773) (also see [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/dhMQ7m2V7AY)).
2. - [ ] [Turn on dom.animations-api.timelines.enabled in release channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1619178) (also see [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/pm3qlPUdO4o)).
3. - [ ] [Turn on dom.animations-api.getAnimations.enabled in release channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1619821)

**Comment by chrisdavidmills** [comment]
Could potentially be a fair bit to update here.

**Comment by chrisdavidmills** [comment]
List of things to update here:

* Update https://developer.mozilla.org/en-US/docs/Web/API/Animation/timeline compat data to say it is available by default in Firefox 75.
* Update https://developer.mozilla.org/en-US/docs/Web/API/Document/timeline compat data to say it is available by default in Firefox 75.
* Update https://developer.mozilla.org/en-US/docs/Web/API/DocumentTimeline compat data to say it is available by default in Firefox 75.
* Update https://developer.mozilla.org/en-US/docs/Web/API/AnimationTimeline compat data to say it is available by default in Firefox 75.

It would probably make sense to update the other compat data too while I am at it; see what I can find out.

Also:

* Implicit to/from keyframes (e.g. elem.animate({ opacity: 0 }, 500) to
fade out an element) are now supported in Firefox 75. For this I probably ought to add an example to https://developer.mozilla.org/en-US/docs/Web/API/Element/animate, and add a new entry to Elem.animate's compat data to say this is available
* Automatically removing filling animations that have been replaced by
other indefinitely filling animations. To fulfill this need, I probably need to mention this on the elem.animate page, and provide a specific rel note to cover it.
* Add notes about the above changes to https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API in appropriate places.
* Add a note to https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Keyframe_Formats about the first change.

Other:

* While we're at it, let's update this section: https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Web_Animations_API_Concepts#Support_status to be a bit more up-to-date

**Comment by birtles** [comment]
> * Update https://developer.mozilla.org/en-US/docs/Web/API/Animation/timeline compat data to say it is available by default in Firefox 75.

Note that we're only shipping the getter in release channels. `Animation.timeline` will be mutable in Nightly and read-only in beta/release for the foreseeable future.

Also, @lpd-au has done a number of PRs for BCD recently updating various Web Animations features.

Furthermore, the Safari release from ~2 weeks ago (13.1?) should ship support for pretty much all the features we're shipping in Firefox 75 minus, I think, the pseudo-element features `KeyframeEffect.pseudoElement` (which probable also deserves an MDN page). I expect @graouts can provide specifics on Safari support if needed.

> * Automatically removing filling animations that have been replaced by other indefinitely filling animations. To fulfill this need, I probably need to mention this on the elem.animate page, and provide a specific rel note to cover it.

Right. I guess we need a page for `Animation.replaceState`, `Animation.commitStyles()`, `Animation.persist()` and `Animation.onremove` if we don't already have them.

**Comment by chrisdavidmills** [comment]
Thanks @birtles for all the useful information.

@graouts I'd love Safari/iOS support specifics for these features, if you've got the time, so I can update these in the compat database.

**Comment by lpd-au** [comment]
Please note I have another BCD PR in progress for `DocumentOrShadowRoot.getAnimations()`, which I intend to submit this week.

**Comment by graouts** [comment]
As it turns out, I just went through MDN and filled the feedback form at the bottom of the pages I found with information about Safari. I should have read my GitHub notifications first! Sorry about that @chrisdavidmills.

Apple just released watchOS 6.2, iOS and iPadOS 13.4, and Safari 13.1 for macOS Catalina 10.15.4, macOS Mojave 10.14.6 and macOS High Sierra 10.13.6. All these releases have the same level of Web Animations support which essentially complete with a few exceptions:

1. [effect composition](https://drafts.csswg.org/web-animations-1/#effect-composition) is not supported, so the `composite` property is not exposed on any of the objects that would support it such that this is feature-detectable.
1. we don't support targeting pseudo-elements yet using `Element.animate()`
1. mutables timelines (ie. setting `Animation.timeline`) is disabled by default and can be activated using the "Web Animations mutable timelines" menu item under Develop > Experimental Features.

These are the main issues, anything else would be considered a bug.

**Comment by graouts** [comment]
Note that I have filed https://github.com/Fyrd/caniuse/pull/5332 so that caniuse.com lists up-to-date information.

**Comment by birtles** [comment]
> 1. [effect composition](https://drafts.csswg.org/web-animations-1/#effect-composition) is not supported, so the `composite` property is not exposed on any of the objects that would support it such that this is feature-detectable,

@chrisdavidmills FWIW, this is true for Firefox too for release versions. That is, we're not shipping `composite` (or `iterationComposite`) to release channels yet although it is fully supported in Nightly builds.

> 2. we don't support targeting pseudo-elements yet using `Element.animate()`

@graouts Is the `KeyframeEffect.pseudoElement` attribute supported and writeable?

**Comment by graouts** [comment]
> > 1. we don't support targeting pseudo-elements yet using `Element.animate()`
> 
> @graouts Is the `KeyframeEffect.pseudoElement` attribute supported and writeable?

It's not either. We will add support for both at once when we support pseudo-element targeting for JS-originated animations.

**Comment by chrisdavidmills** [comment]
OK, all changes described above have been made. In addition, I've made these additions to cover the "removing filling animations" stuff:

* https://developer.mozilla.org/en-US/docs/Web/API/Animation#Automatically_removing_filling_animations
* https://developer.mozilla.org/en-US/docs/Web/API/Animation/persist
* https://developer.mozilla.org/en-US/docs/Web/API/Animation/replaceState
* https://developer.mozilla.org/en-US/docs/Web/API/Animation/commitStyles
* https://developer.mozilla.org/en-US/docs/Web/API/Animation/onremove

See demos also: https://github.com/mdn/dom-examples/blob/master/web-animations-api/README.md

**Comment by chrisdavidmills** [comment]
Also see PR to update browser compat data accordingly: https://github.com/mdn/browser-compat-data/pull/5963
