### ISSUE TITLE
U — [WebAPI] WebXR, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2934]
# Trello

https://trello.com/c/4IKxDEfN/47-webxr-fx-75

# Acceptance criteria

1. - [x] [Restrict access to WebVR to HTTPS only sites.](https://bugzilla.mozilla.org/show_bug.cgi?id=1381645)

**Comment by a2sheppy** [comment]
(This was actually a 73 issue but... it's done now)
