### ISSUE TITLE
U — [WebAPI] Web Workers, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2935]
# Trello

https://trello.com/c/BGRBpa8m/160-dedicated-shared-worker-apis-fx-75

# Acceptance criteria

1. - [ ] [Re-enable strict MIME type checking for Worker/SharedWorker](https://bugzilla.mozilla.org/show_bug.cgi?id=1569123)

**Comment by chrisdavidmills** [comment]
Probably rather small.

**Comment by a2sheppy** [comment]
This issue (1569123) was reverted for 75; they're going to try again to land it in 76.
