### ISSUE TITLE
U — [WebAPI] Web Crypto API, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2937]
# Trello

https://trello.com/c/PoSdJAUO/78-web-crypto-api-fx-75

# Acceptance criteria

1. - [x] [Require [SecureContext] for Web Crypto](https://bugzilla.mozilla.org/show_bug.cgi?id=1333140)

**Comment by chrisdavidmills** [comment]
Fairly short simple tasks, requires secure context, etc.

**Comment by a2sheppy** [comment]
I've nearly finished this work, aside from waiting for info from Samsung about when/if this change was made in Samsung Internet.
