### ISSUE TITLE
Finalize Firefox 62 release materials

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#294]
# User story
As a web developer, I want to know all the new features available in Firefox 62, so I can use them in my work.

# Acceptance criteria
* All below tasks completed

# Tasks
1. -[x] Copy edit [Firefox 62 rel notes](https://developer.mozilla.org/en-US/Firefox/Releases/62).
2. -[x] Mail writers and make sure they haven't forgotten to add any relevant notes.
3. -[x] Make sure there are no outstanding DDNs
4. -[x] Make sure [platform-status](https://platform-status.mozilla.org/) has relevant information added
5. -[x] Make sure [experimental features page](https://developer.mozilla.org/en-US/Firefox/Experimental_features) has relevant features added
6. -[x] Write Firefox 62 tweets for Danielle

**Comment by chrisdavidmills** [comment]
Tweets written for Danielle:

* The Page inspector 3-pane mode has been introduced in Firefox 62: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/3-pane_mode. This allows the CSS rules view to be viewed in a separate pane to other CSS features, enabling some useful new workflows/interactions.
* The Grid inspector has updated features in Firefox 62: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts
* As of Firefox 62, the The Network Monitor's Cookies tab now shows the cookie samesite attribute: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#Cookies
* Great progress on CSS Shapes! Firefox 62 sees the shape-margin, shape-outside and shape-image-threshold properties all enabled by default (for example https://developer.mozilla.org/en-US/docs/Web/CSS/shape-margin )
* In Firefox 62, The import.meta property has been implemented to expose context-specific metadata to a JavaScript module: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta 
* Firefox 62 sees the Array.flat() and Array.flatMap() method enabled by default:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
* The https://developer.mozilla.org/en-US/docs/Web/API/Console/countReset method has bene added into Firefox 62 to allow counter resets.
* The https://developer.mozilla.org/en-US/docs/Web/API/Console/timeLog method has been added to Firefox 62, to allow logging of timer values.
* In Firefox 62, the Speech Synthesis API has ben enabled by default on Android; see https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API 
* In Firefox 62 browser extensions, the webRequest.getSecurityInfo() API has bene added to examine details of TLS connections.
* Firefox 62 browser extensions now sees browserSettings.newTabPosition added to customize where new tabs open.
* In Firefox 62, windowTypes has been deprecated in windows.get(), windows.getCurrent() and windows.getLastFocused().
* It's now possible to modify a browser action on a per-window basis in Firefox 62 browser extensions.

**Comment by jmswisher** [comment]
@chrisdavidmills @atopal Can this issue be closed?

**Comment by chrisdavidmills** [comment]
Yes; done.
