### ISSUE TITLE
U — [HTTP] Cross origin-related bugs, Fx 75

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2940]
# Trello

https://trello.com/c/ZQjg0cm4/175-cross-origin-related-bugs-fx-75

# Acceptance criteria

1. - [ ] [Align with Cross-Origin-Opener-Policy changes](https://bugzilla.mozilla.org/show_bug.cgi?id=1607460) (not sure if this is enabled by default yet)

**Comment by Elchi3** [comment]
I don't think we should document this yet. 

This particular bug is just one piece of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes which is also tracked in https://github.com/mdn/sprints/issues/2219.

Once the return of SAB is really landing in release, we should make https://github.com/mdn/sprints/issues/2219 a proper user story and document the headers and things needed for SAB.

Does that make sense to you, @chrisdavidmills? If so, I propose to close this issue.

**Comment by chrisdavidmills** [comment]
Yup, works for me. 

I've added the above DDN bug to #2219 , so we don't forget about it. But we can close this one.
