### ISSUE TITLE
U — [HTTP] CSP, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2941]
# Trello

# Acceptance criteria

1. - [x] [child-src is no longer deprecated, remove warning?](https://bugzilla.mozilla.org/show_bug.cgi?id=1486331)
2. - [x] [CSP: Hide nonce values from the DOM](https://bugzilla.mozilla.org/show_bug.cgi?id=1374612)

**Comment by Elchi3** [comment]
>  child-src is no longer deprecated, remove warning?

This was dealt with in https://github.com/mdn/sprints/issues/998

**Comment by Elchi3** [comment]
For "CSP: Hide nonce values from the DOM", I've also mentioned this in the add-on section, see https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#Changes_for_add-on_developers per the discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1374612#c24

Heads up to @rebloor: this thing affects add-on developers.

**Comment by rebloor** [comment]
Thanks @Elchi3 aside from the release notes, any thoughts on documentation requirements. I've done a search and we don't mention nonce explicitly in the web extension content.

**Comment by Elchi3** [comment]
@rebloor I think this has an impact when people try to deal with content scripts and their CSP, see https://bugzilla.mozilla.org/show_bug.cgi?id=1374612#c21. I think the heads up in the release notes might be enough, though. If you publish release notes elsewhere for WebExtensions, you might want to mention this, too.

**Comment by Elchi3** [comment]
This is all done now. (The BCD update for the CSP nonce change will land later this week)
