### ISSUE TITLE
U — [DevTools] Minor tools, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2943]
# Trello

https://trello.com/c/IzhhiELs/252-minor-tools-eg-ruler-color-picker-fx-75

# Acceptance criteria

1. - [x] [Allow resizing the area selected by measuring tool via mouse](https://bugzilla.mozilla.org/show_bug.cgi?id=1152321)

**Comment by jmswisher** [comment]
Thanks to Sebastian for updating [Measuring a portion of the page](https://wiki.developer.mozilla.org/en-US/docs/Tools/Measure_a_portion_of_the_page).
