### ISSUE TITLE
U — [WebExt] General API, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2944]
# Trello

https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-75

# Acceptance criteria

1. - [x] (now not landing in 75) [Implement discovery of search extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1562657) (see also the [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/mc-JJFw85HM) for more useful info.)
2. - [x] [make privacy permission an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1618399)

**Comment by rebloor** [comment]
Update:  A PR has been created for compatibility data for "make privacy permission an optional permission"

**Comment by rebloor** [comment]
@chrisdavidmills  For "Implement discovery of search extensions" do you have any suggestions/recommendations on how this is documented—if we followed the template of the closely related OpenSearch description format, the content would end up in the [Web technology for developers](https://developer.mozilla.org/en-US/docs/Web) section. Perhaps a "how to" article in browser extension section?

**Comment by rebloor** [comment]
Update:  Updated MDN for "make privacy permission an optional permission"—added privacy to the list of optional positions on the optional_permissions key page. Also, added details to the release notes. Made a needinfo request on the bug to confirm the documentation is complete and accurate.

**Comment by rebloor** [comment]
Update: "make privacy permission an optional permission" got the OK from Shane Caraveo via needinfo request.
