### ISSUE TITLE
U — [WebExt] Browser API, Fx 75 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2945]
# Trello

https://trello.com/c/LBJWI3hD/229-browser-api-enhancements-fx-75

# Acceptance criteria

1. - [x] [Add new zoomSiteSpecific and zoomFullPage settings in browserSettings API](https://bugzilla.mozilla.org/show_bug.cgi?id=1286953)
2. - [x] [Add optional 'fileName' property to the 'pageSettings' passed into tabs.saveAsPDF()](https://bugzilla.mozilla.org/show_bug.cgi?id=1483590)

**Comment by rebloor** [comment]
Update: both bugs have had their compatibility data changes merged, MDN pages updated, and details added to the release notes. Both are waiting on needinfo responses to requests to review the compatibility and MDN changes.

**Comment by rebloor** [comment]
Update:  I've had a response to both needinfo requests confirming the content is complete and accurate, so marking these as done.
