### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let$history

### ISSUE THREAD

**Issue by klossner** [mdn/sprints#2946]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The edit on Sep 9, 2019 by Zhang-Junzhi, comment 'Took out necessary "if (true)"s', leaves the section "Another example of temporal dead zone combined with lexical scoping" confusing: the description refers to the if block in the code, but there is no longer an if block in the code.

**Comment by chrisdavidmills** [comment]
It refers specifically to an if block with a foo; I've tried to fix that section by adding in if(foo) - you you think that fixes it?

**Comment by klossner** [comment]
Yes, that fixes the problem, so long as nobody comes along and "optimizes" the code again.

I recommend that a space be inserted between if and ( for consistency with the other code examples on this page.
