### ISSUE TITLE
Scrape BigInt pages into stumptown-content-formatted Markdown

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2949]
mdn/stumptown-content's `scraper-ng` should be able to scrape JavaScript pages into Markdown files that can be processed by `build-json`. To demonstrate this, we want to scrape all of the `BigInt` pages (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt and the pages below it in the tree).

**Comment by Elchi3** [comment]
This isn't a goal anymore. Closing
