### ISSUE TITLE
Scrape a JavaScript page to minimally useful Stumptown Markdown

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2950]
## User story

As an author, I want to run `scraper-ng` on a JavaScript page and get some minimally useful Markdown that works with `build-json`, so I can start scraping the wiki, author in Markdown, and render scraped-and-modified content with stumptown-renderer.

## Acceptance criteria

Running `scraper-ng` does the following, for at least one JS page:
- [ ] A Markdown file is written to `/content/` based on the page's URL path (e.g., scraping `/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt` writes out `/content/en-US/javascript/reference/global_objects/bigint/bigint.md`)
- [ ] The Markdown file has frontmatter with these fields:
  - [ ] `recipe`
  - [ ] `title`
  - [ ] `mdn_url`
  - [ ] `browser_compatibility`
- [ ] The Markdown file contains at least one required prose section

**Comment by ddbeck** [comment]
@wbamberg @chinikes since we're not doing this, what's the bookkeeping procedure here? Do I close it (and "complete" it for the sprint)? Or do I remove it from the sprint and then close it?

**Comment by chinikes** [comment]
@ddbeck - The process would be to remove it from the current sprint backlog. If it's a task that the team still plans to handle in future, then I suggest you place it back into the backlog:refined pipeline on the board

**Comment by ddbeck** [comment]
OK, I don't think we're going to come back to this in this specific form. I have removed it from the milestone and closing the issue now.
