### ISSUE TITLE
/ru/docs/Web/Манифест: compat table links look as nonexistent

### ISSUE THREAD

**Issue by almaceleste** [mdn/sprints#2951]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The links in the Compat Table of the article 
https://wiki.developer.mozilla.org/ru/docs/Web/Манифест 
look as nonexistent, although they exist.
It happens cause they are looking for the wrong url, such as:
https://wiki.developer.mozilla.org/ru/docs/Web/Manifest/background_color
but they are really located at, for example:
https://wiki.developer.mozilla.org/ru/docs/Web/Манифест/background_color
Probably, someone accidentally changed URL of the parent article, but the script, that makes Compat Table, uses original english URL.
![image](https://user-images.githubusercontent.com/36765595/76379272-b8ffbf00-6360-11ea-8452-e575a5cc507d.png)
![image](https://user-images.githubusercontent.com/36765595/76379316-d5036080-6360-11ea-9e58-815f98ad3532.png)

**Comment by chrisdavidmills** [comment]
I've moved the Russian version to https://wiki.developer.mozilla.org/ru/docs/Web/Manifest; looks like it has fixed the links. Thanks for reporting!

**Comment by almaceleste** [comment]
Thank you very much.
it looks fine
