### ISSUE TITLE
/ru/docs/Web/HTML/Общие_атрибуты: the children links look like nonexistent, but they exist

### ISSUE THREAD

**Issue by almaceleste** [mdn/sprints#2952]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Please move the article
wiki.developer.mozilla.org/ru/docs/Web/HTML/Общие_атрибуты
to the
wiki.developer.mozilla.org/ru/docs/Web/HTML/Global_attributes
cause of this the children links look like nonexistent, but they exist
![image](https://user-images.githubusercontent.com/36765595/76413513-9e503900-63a6-11ea-9cdc-71485b7b5538.png)

**Comment by chrisdavidmills** [comment]
Done! ;-)

**Comment by almaceleste** [comment]
Thank you
