### ISSUE TITLE
/en-US/docs/Web/CSS/align-content

### ISSUE THREAD

**Issue by deepharshsri** [mdn/sprints#2955]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[] Correction: (align-content: space between) The items are evenly distributed within the alignment container along the cross axis. The spacing between each pair of adjacent items is the same. The first item is flush with the main-start edge, and the last item is flush with the main-end edge.

Here you have written that the "The first item is flush with the main-start edge, and the last item is flush with the main-end edge" but I think it is not correct.

[] Update: (align-content: space between) The items are evenly distributed within the alignment container along the cross axis. The spacing between each pair of adjacent items is the same. The first main-axis is flush with the cross-start edge, and the last item is flush with the cross-end edge.

**Comment by chrisdavidmills** [comment]
They weren't altogether wrong, but I think it is easy to get main start confused with main axis. I've tried updating the language on the page - does it seem better now?

**Comment by deepharshsri** [comment]
> They weren't altogether wrong, but I think it is easy to get main start confused with main axis. I've tried updating the language on the page - does it seem better now?

.....Yes, it is now clear to understand.
