### ISSUE TITLE
/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

### ISSUE THREAD

**Issue by w-disheng** [mdn/sprints#2958]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

<h2>Translation incorrect for Chinese version.</h2>

<p>Under the <strong>Project Brief</strong> section:</p>

<p>The two addresses should be put inside <address> elements. Each line of the address should sit on a new line, but not be in a new paragraph. <br />
<em>Chinese Translation</em>:
两个地址可以直接放在段落中，<address> 元素不适合它们（想一下为什么）。此外，地址的每一行都应该另开新行，而不是新段落。</p>

<p>They are conflicting each other, in English, the instruction is saying that we should put it inside the <address> element. However, in Chinese it's saying that we should put it in p element instead of address element. I think the correct translation for Chinese is: </p>

两个地址应该放在address元素下. 每行的地址应该放在新的一行而不是新的段落.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this! I have tried updating it; does it look OK now?
