### ISSUE TITLE
/en-US/docs/Web/SVG/Tutorial/Getting_Started

### ISSUE THREAD

**Issue by EccentricVamp** [mdn/sprints#2960]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The "Namespaces Crash Course" anchor on this page doesn't seem to be functioning, due to a missing href.
![image](https://user-images.githubusercontent.com/6740013/76529878-e754cb80-6440-11ea-80cc-1e9623a34b12.png)
Link to page: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started

This is especially strange since the seems to work if I open up the editable version of the web docs.
![image](https://user-images.githubusercontent.com/6740013/76530262-78c43d80-6441-11ea-85b2-6fdc0274df4a.png)
Link to page: https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started

I'm using Chrome Version 80.0.3987.132 on Windows 10. My ad blocker is off, and I don't have any other extensions installed which would modify the page. So I'm not sure what's causing this discrepancy.

It's not a huge issue. I'm smart enough to find the page on my own. It's just a bit annoying, and a less-experienced user might have difficulty navigating to the page. Let me know if you have anymore questions.

**Comment by chrisdavidmills** [comment]
Thanks for pointing this out; link fixed!
