### ISSUE TITLE
/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by defnull** [mdn/sprints#2967]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the [Example preflight request](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Example_preflight_request) section, the example request contains an `Access-Control-Request-Headers: origin, ...` header, which I find odd at last. The `Origin` header is always sent and never set-able from scripts, so why include it in ACRH?
In the same Section, the example response does not contain an `Access-Control-Allow-Headers` header at all, which is also quite strange for an example that is supposed to explain that header.

**Comment by hamishwillee** [comment]
Agreed  and fixed:
- removed `origin` with `Content-Type` in `Access-Control-Request-Headers` and also added `Access-Control-Allow-Headers` with same values in the response.
- Slight subedit to fix some of the other wording and make it clear in the introduction  that safelisted headers don't need to be listed (it is also mentioned further down but IMO important enough to have at top). [Changes here](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers$compare?locale=en-US&to=1652987&from=1617495).

**Comment by hamishwillee** [comment]
@chrisdavidmills Sanity check welcome, otherwise I'll review and close this next time I look at the issue.

**Comment by chrisdavidmills** [comment]
@hamishwillee I think these fixes look pretty good. I'll close this now, but please jump in @defnull if you think this needs any more work.

Thanks all.
