### ISSUE TITLE
/en-US/docs/Web/SVG/Attribute/marker-mid

### ISSUE THREAD

**Issue by RubyCC** [mdn/sprints#2969]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Description is wrong. Seems to be copied from marker-end:
The marker-mid attribute defines the arrowhead or polymarker that will be drawn at ~the final vertex~ **all interior vertices** of the given shape.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this; I've updated it in the Wiki version of the page, but it might take a little while to get through to the final page version.
