### ISSUE TITLE
/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

### ISSUE THREAD

**Issue by pvonglehn** [mdn/sprints#2970]
# Request type

- [x] Correction or update

# Details

Unfinished sentence

The paragraph "Escape potentially dangerous characters" ends with the unfinished sentence "Things to watch out for are character strings that"

This is found hunder heading:

https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#Be_paranoid_Never_trust_your_users

**Comment by chrisdavidmills** [comment]
Thanks for reporting this! I've finished the sentence; it is updated on the Wiki version, but sometimes takes a while to update on the user-facing pages.
