### ISSUE TITLE
linear-gradient Formal syntax bug

### ISSUE THREAD

**Issue by SeifESlimene** [mdn/sprints#2972]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

```
linear-gradient(
  [ <angle> | to <side-or-corner> ,]? <color-stop-list> )
  \---------------------------------/ \----------------------------/
    Definition of the gradient line        List of color stops  

where <side-or-corner> = [ left | right ] || [ top | bottom ]
  and <color-stop-list> = [ <linear-color-stop> [, <color-hint>? ]? ]#, <linear-color-stop>
  and <linear-color-stop> = <color> [ <color-stop-length> ]?
  and <color-stop-length> = [ <percentage> | <length> ]{1,2}
  and <color-hint> = [ <percentage> | <length> ]
```

[Link to the MDN source page](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient)

Here `[ <linear-color-stop> [, <color-hint>? ]? ]#,` must be `[ <linear-color-stop> [, <color-hint> ]? ]#,` otherwise `background: linear-gradient(#f00 , , #ff0);` should be true!

**Comment by wbamberg** [comment]
Note that the syntax for `<color-stop-list>` in the spec is different: https://drafts.csswg.org/css-images-4/#color-stop-syntax:

```
<color-stop-list> =
  <linear-color-stop> , [ <linear-color-hint>? , <linear-color-stop> ]#
```
