### ISSUE TITLE
/en-US/docs/Web/HTML/Global_attributes/tabindex

### ISSUE THREAD

**Issue by mariepw** [mdn/sprints#2973]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In specifications section, _HTML 4.01 Specification_ , in Comment part, the list is missing `<Input> ` which is in the list in https://www.w3.org/TR/html401/interact/forms.html#adef-tabindex

**Comment by chrisdavidmills** [comment]
Updated; thanks for pointing this out!
