### ISSUE TITLE
Two of the "Pixel manipulation with canvas" examples are not working

### ISSUE THREAD

**Issue by drvdw** [mdn/sprints#2974]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On the page:
[https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutori](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas)

The first two javascript examples with the rhino image ("A color picker" and "Grayscaling and inverting colors") are not working on:
Firefox 74.0 (64-bit)
or
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit).

For some reason only the last example "Zooming and anti-aliasing" is working.

**Comment by gsouquet** [comment]
This looks like a duplicate of #3548 that I just fixed yesterday

**Comment by chrisdavidmills** [comment]
@gsouquet yup, looks like it. I'll close this one then.
