### ISSUE TITLE
Link hedaer, how to specify multiple uris

### ISSUE THREAD

**Issue by nu111** [mdn/sprints#2975]
# Request type
Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link
I think you should say how to specify multiple uris.

Based on this answer
https://stackoverflow.com/questions/25369191/http-response-headers-multiple-link-values
I belive this would be the right way
```
Link <https://one.example.com>; rel=preconnect, <https://two.example.com>; rel=preconnect, <https://three.example.com>; rel=preconnect
```

**Comment by chrisdavidmills** [comment]
Good idea; added: https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link#Examples

Do you think this looks OK?
