### ISSUE TITLE
Documentation Typo for String.prototype.indexOf() 

### ISSUE THREAD

**Issue by dougouk** [mdn/sprints#2983]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Inside the `String.prototype.indexOf()` documentation, there is an error in the **Parameters - `searchValue`** section:

> So, for example: 'undefined'.indexOf() will return 0, as undefined is found at position 0, but 'undefine'.indexOf() will return -1, as the string "undefine" is not found.

"undefine" should be "undefined". So the result should be

> So, for example: 'undefined'.indexOf() will return 0, as undefined is found at position 0, but 'undefine'.indexOf() will return -1, as the string "undefined" is not found.

Link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

**Comment by chrisdavidmills** [comment]
Hi @dougouk , thanks for reporting this!

I thought the wording in general was a bit confusing, so I've changed it as seen here:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

Do you think that works?

It'll take a little while for the change to propagate through to the final MDN page (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf)

**Comment by dougouk** [comment]
@chrisdavidmills that looks great! thank you :)
