### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

### ISSUE THREAD

**Issue by asell22** [mdn/sprints#2984]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This appears in **Assigning the rest of an array to a variable** section:

> Be aware that a SyntaxError will be thrown if a trailing comma is used on the _left-hand_  side with a rest element:

Small correction: 
Trailing comma appears on _right-hand_  side of the rest element.

<img width="1017" alt="Screen Shot 2020-03-21 at 3 02 57 PM" src="https://user-images.githubusercontent.com/9015024/77237396-1972d580-6b85-11ea-8a98-8b4ec2021219.png">

**Comment by asell22** [comment]
This appears in **Assigning the rest of an array to a variable** section

**Comment by chrisdavidmills** [comment]
This looks correct to me. The comma the text refers to is the second comma inside this bit:

`[a, ...b,]`

And this appears on the left hand side of the assignment.
