### ISSUE TITLE
/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange

### ISSUE THREAD

**Issue by outfoxer** [mdn/sprints#2986]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Typo in example: https://take.ms/g2tzO

**Comment by chrisdavidmills** [comment]
Thanks for reporting. I've updated it to `status >= 200`, which is what I think it is supposed to say ;-)
