### ISSUE TITLE
Bug in Javascript tutorial

### ISSUE THREAD

**Issue by Jpeg-XIV** [mdn/sprints#2988]
This link in JS tutorial [http://docs.webplatform.org/wiki/concepts/programming/programming_basics](http://docs.webplatform.org/wiki/concepts/programming/programming_basics), ( it's a link of parts of the introduction JS "Programming - The real fundamental" )  dismissal an error 404:

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by schalkneethling** [comment]
@chrisdavidmills ^

**Comment by chrisdavidmills** [comment]
Hi @Jpeg-XIV - what page are you finding the 404 link on?

**Comment by Jpeg-XIV** [comment]
Hello, sorry I'm french student in scientific terminal so I have a lot of work, I finding 404 in this page:
https://developer.mozilla.org/fr/docs/Web/Tutoriels, but now it works again.
