### ISSUE TITLE
/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

### ISSUE THREAD

**Issue by Honeybyte** [mdn/sprints#2992]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Following the described examples on the page is not possible anymore. Loading the local verseX.txt files is recently [prohibited](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default).

**Comment by chrisdavidmills** [comment]
I do clearly state that you should run your examples through a server: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data#Serving_your_example_from_a_server

I updated the wording a bit, to say that _all_ modern browsers won't allow you to run them from local files.

**Comment by Honeybyte** [comment]
Thanks, I missed reading the next paragraph. Perhaps moving the note above the example could help others as well :slightly_smiling_face:
