### ISSUE TITLE
Broken links on Parameter page

### ISSUE THREAD

**Issue by TheChandler** [mdn/sprints#2994]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The second and third links in the "Technical reference" section on this page don't work.
https://developer.mozilla.org/en-US/docs/Glossary/Parameter

**Comment by chrisdavidmills** [comment]
I've removed the broken links; thanks for reporting.
