### ISSUE TITLE
/en-US/docs/Learn/JavaScript/Objects/Object_building_practice

### ISSUE THREAD

**Issue by janina213** [mdn/sprints#2995]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

This portion of the docs under "Updating the ball's data", might need a correction
> In the four cases, we are checking to see:
>    if the x coordinate is greater than the width of the canvas (the ball is going off the right edge).
>    if the x coordinate is smaller than 0 (the ball is going off the left edge).
>    if the y coordinate is greater than the height of the canvas (the ball is going off the top edge).
>    if the y coordinate is smaller than 0 (the ball is going off the bottom edge).

According to the [Canvas API docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics) the y axis runs from top to bottom.  So it seems like the statement in the parentheses of the y coordinate bullets should be swapped

**Comment by chrisdavidmills** [comment]
Ah, you are correct! I've updated it now; thanks for reporting!
