### ISSUE TITLE
/en-US/docs/Web/HTTP/Headers

### ISSUE THREAD

**Issue by Caramel-Pudding** [mdn/sprints#2996]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

The link 'MIME type' in 'Entity headers contain information about the body of the resource, like its content length or MIME type.' is leading to https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type instead of for example https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types . It seems to be a mistake for me. Thanks.
![Снимок](https://user-images.githubusercontent.com/21342453/77537125-9d42ff80-6eae-11ea-8d0e-4a6b30c2d24f.PNG)

**Comment by chrisdavidmills** [comment]
@Caramel-Pudding that is a really strange bug in the page ;-)

Thank you for reporting it — I have fixed it now!
