### ISSUE TITLE
KR: Put a CDN in front of developer.mozilla.org

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3]
The goals are that a CDN in front of developer.mozilla.org will:

- improve response times since endpoints will mostly be served from a cached response and because the cached response will come from a server that is closer to the user
- greatly reduce the load on MDN, which will in turn reduce downtime events due to scrapers and other issues
- automatically provide a better level of protection against DDoS attacks (e.g., via AWS Shield)

*See:* [This epic in Taiga](https://tree.taiga.io/project/viya-mdn-durable-team/epic/4512)

**Comment by peterbe** [comment]
(Sorry for butting in but I'm curious and trying to grok the sprint process)

developer.mozilla.org now *is* behind a CDN. CloudFront in fact. 

On a personal note, I'd love for this KR to "morph". I haven't actually seen the code or the config, but the expiration time is currently tiny. (~5 minutes). That means that anybody unlucky outside that window will be forced to rely on the origin (Django?) which is comparatively slower. 

The KR should be to have a hefty expiration time (e.g. 24h or 7 days) with  functionality to purge/refresh the CDN on a per-URI basis.

**Comment by Elchi3** [comment]
Looks stalled. Closing
