### ISSUE TITLE
As a writer I need to know what format to offer the short descriptions in, so we can start the migration

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#300]
Acceptance Criteria
- [x] Format documented
- [x] VS Code has accepted format
- [ ] Fx Devtools has accepted format

**Comment by atopal** [comment]
Acceptance Criteria
- [ ] Format documented
- [ ] VS Code has accepted format
- [ ] Fx Devtools has accepted format

**Comment by jmswisher** [comment]
@atopal @wbamberg Can this be closed?

**Comment by wbamberg** [comment]
I think so, yes.

**Comment by atopal** [comment]
The acceptance criteria haven't been met yet as far as I can tell. @wbamberg do we think those are not relevant anymore, or are we tracking them somewhere else?

**Comment by wbamberg** [comment]
VS Code has accepted the format but we haven't asked for feedback from Fx Devtools. I suppose we should. I'll do this.

**Comment by jmswisher** [comment]
Should this be moved forward to an upcoming sprint, since its AC are not yet met?

**Comment by chrisdavidmills** [comment]
@wbamberg shall I ask devtools for a review of the format? Is this still relevant, since we are moving ahead? Close it?

**Comment by jmswisher** [comment]
Closing this since work has moved ahead on short descriptions, regardless of what Fx DevTools may think.
