### ISSUE TITLE
https://wiki.developer.mozilla.org/fr/docs/Games/Workflows/2D_Breakout_game_pure_JavaScript/Move_the_ball

### ISSUE THREAD

**Issue by Git-de-Nicolas** [mdn/sprints#3001]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello, just wanted to say that you have to change the : 

`<a class="new" href="/fr/docs/Games/Workflows/2D_Breakout_game_pure_JavaScript/Bounce_off_the_walls" rel="nofollow">Suivant  »</a>`

with 

`<a class="new" href="**https://developer.mozilla.org/fr/docs/Games/Workflows/2D_Breakout_game_pure_JavaScript/Faire_rebondir_la_balle_sur_les_murs**" rel="nofollow">Suivant  »</a>`

And so on, I can't change your source link

**Comment by SphinxKnight** [comment]
@Git-de-Nicolas merci pour ce retour, j'ai fait le nécessaire en corrigeant les "macros" qui génèrent ces liens. J'en ai également profité pour améliorer légèrement la page sur certaines tournures.

@chrisdavidmills links fixed, page updated/reworded. thanks for sending :)

**Comment by chrisdavidmills** [comment]
@SphinxKnight thank you!
