### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by Dewke** [mdn/sprints#3002]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Both in the "What is JavaScript?" page (under ["Script loading strategies" paragraph](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#Script_loading_strategies)) and  the "JavaScript Basics" page (under ["A 'Hello world!' example" section](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics#A_Hello_world!_example)), the reader is advised to include their `<script>` at the very end of `<body>` element.
![image](https://user-images.githubusercontent.com/25594858/77855828-4e210580-71f3-11ea-89a2-3910906a2fad.png)

However,  according to ["What is JavaScript doing on your page?" paragraph](What_is_JavaScript_doing_on_your_page) on the "What is JavaScript?" page:
_"The JavaScript is executed by the browser's JavaScript engine, **after** the HTML and CSS have been assembled and put together into a web page. This ensures that the structure and style of the page are already in place by the time the JavaScript starts to run."_

This is really confusing to me. If the JavaScript is executed **after** HTML and CSS are loded, do we really have to link it just before `</body>` closing tag?

**Comment by chrisdavidmills** [comment]
Hi @Dewke ! Thanks for pointing this out - it looks like you are right, something has got confused here.

> However, according to "What is JavaScript doing on your page?" paragraph on the "What is JavaScript?" page:

I updated the text in this section to be consistent with the other bits.
