### ISSUE TITLE
/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

### ISSUE THREAD

**Issue by pmpinto** [mdn/sprints#3006]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
> A stacking context is formed, anywhere in the document, by any element in the following scenarios:
> * ...
> * Element with a position value absolute or relative and z-index value other than auto.
> * ...

According to this example, `z-index` doesn't seem to be needed at all:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index

There seems to be some contradiction here. Is it just me?

**Comment by rachelandrew** [comment]
@pmpinto The second article is just demonstrating how things stack naturally, if they do not create a stacking context. The article you referenced is specifically describing the things which create a new stacking context. So I don't think there is a contradiction there.

**Comment by pmpinto** [comment]
> @pmpinto The second article is just demonstrating how things stack naturally, if they do not create a stacking context. The article you referenced is specifically describing the things which create a new stacking context. So I don't think there is a contradiction there.

@rachelandrew thanks for looking into this. It does make sense from that perspective 👍

**Comment by chrisdavidmills** [comment]
Cool, looks like we can close this one then.
