### ISSUE TITLE
Suggestion emendation for "ID" text

### ISSUE THREAD

**Issue by Retired-of-Cornwall** [mdn/sprints#3007]
# Request type

- [x] Correction or update

# Details

At https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id, the prose reads (in part) "(i) This attribute's value is an opaque string: this means that web authors must not use it to convey human-readable information".  "Must not", in my opinion, is incorrect, and might lead a reader to believe that a page that uses meaningful IDs is (a) wrong, and (b) would fail formal validation.  I believe that a better formulation would be "(c) This attribute's value is an opaque string: this means that web authors may not rely on it to convey human-readable information".

**Comment by chrisdavidmills** [comment]
@Retired-of-Cornwall yes, I completely agree with you. I've actually gone a little further, and used the following text:

> This attribute's value is an opaque string: this means that web authors should not rely on it to convey human-readable information (although having your IDs somewhat human-readable can be useful for code comprehension, e.g. consider ticket-18659 versus r45tgfe-freds&$@).

Thanks very much for pointing this out.
