### ISSUE TITLE
/en-US/docs/Web/API/ParentNode/childElementCount

### ISSUE THREAD

**Issue by GodModus** [mdn/sprints#3008]
# Request type
- [x] Correction or update

# Details

An important detail is missing on the functionality of childElementCount. It only counts non-text/comment node types. In contrast with childNodes.length which counts all nodes types including text- and comments nodes.

This also aplies to parent.childNodes and parent.children. The one contains all nodes (incl comments and text nodes) while the other excludes the text-comment nodes.

**Comment by Rumyra** [comment]
Temporary list of pages

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/childElementCount
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Document
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children
