### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

### ISSUE THREAD

**Issue by dimitarget** [mdn/sprints#3010]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
If after this code (which is in the paragraph "Using call to invoke an anonymous function "):
const animals = [
  { species: 'Lion', name: 'King' },
  { species: 'Whale', name: 'Fail' }
];

for (let i = 0; i < animals.length; i++) {
  (function(i) {
    this.print = function() {
      console.log('#' + i + ' ' + this.species
                  + ': ' + this.name);
    }
    this.print();
  }).call(animals[i], i);
}
i add   
animals[0].print.call(animals[1]) 
the result would be: // #0 Whale: Fail
which is no good.Must be : //#1 Whale:Fail
It would be better if
function(i) {
    this.print = function() {
      console.log('#' + i + ' ' + this.species
                  + ': ' + this.name);
    }
    this.print();}
becomes
function(i) {this.q=i;
    this.print = function() {
      console.log('#' + this.q + ' ' + this.species
                  + ': ' + this.name);
    }
    this.print();}
Just adding property "q",which contains the index of the element,(which is an object),in the array.

**Comment by jadjoubran** [comment]
Happy to take this one 🙋🏻‍♂️

**Comment by jadjoubran** [comment]
Re-writing and rephrasing issue with code-blocks for better visibility:

```javascript
const animals = [
  { species: 'Lion', name: 'King' },
  { species: 'Whale', name: 'Fail' }
];

for (let i = 0; i < animals.length; i++) {
  (function(i) {
    this.print = function() {
      console.log('#' + i + ' ' + this.species + ': ' + this.name);
    }
    this.print();
  }).call(animals[i], i);
}
```

If we add after the code above:  

```javascript
animals[0].print.call(animals[1])
```

Then we get: `#0 Whale: Fail`. However, I expect to get `#1 Whale:Fail`

Thus, it would be better if rewrite the inner function as following:

```javascript
function(i) {
  this.q = i;
  this.print = function() {
    console.log('#' + this.q + ' ' + this.species + ': ' + this.name);
  }
  this.print();
}
```

**Comment by jadjoubran** [comment]
Hey @dimitarget, thanks for opening this issue
As far as I can tell, this behaviour makes sense because the value of `i` in `animals[0]` is 0. So when you call `animals[0].print.call(animals[1])`, you're ending up with a value of `i=0` and `thisArg=animals[1]` hence the conflicting results.

A better way to fix it would be to give `id`s for every animal so then you won't have this issue:

```javascript
const animals = [
   { id: 1, species: 'Lion', name: 'King' },
   { id: 2, species: 'Whale', name: 'Fail' }
];

for (let i = 0; i < animals.length; i++) {
  (function(i) {
    this.print = function() {
      console.log('#' + this.id + ' ' + this.species + ': ' + this.name);
    }
    this.print();
  }).call(animals[i], i);
}
```

Thus, I recommend that we close the issue without updating the documentation considering that the result is correct and expected considering the different values of `i` and `this` cc/ @chrisdavidmills

**Comment by chrisdavidmills** [comment]
Thanks @jadjoubran , yes, let's leave this one.
