### ISSUE TITLE
/fr/docs/Web/CSS/background-attachment

### ISSUE THREAD

**Issue by qexat** [mdn/sprints#3011]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
:fr: **Français :** Je voudrais apporter une petite correction dans la documentation, car il me semble qu'elle est nécessaire.
En effet, il y est écrit que `background-clip:text` ne supporte pas `background-attachment:fixed`. Cependant, il semblerait que Chrome 76+ va à l'encontre de cette affirmation, en supportant la combinaison des deux.

:gb: **English:** I would like to make a small correction in the documentation, because it seems to me that it is necessary.
Indeed, it says that the CSS property `background-clip: text` does not support `background-attachment: fixed`. However, it would appear that Chrome 76+ goes against this claim, supporting the combination of both.

**Comment by SphinxKnight** [comment]
@qexat thanks for the report. this is also stated in the English version which is considered "the source of truth" for translations and the edit responsible for this dates from 01/2018.

I'll fiddle with this and will update accordingly.

**Comment by SphinxKnight** [comment]
@qexat Could you share an example/pastebin/codepen of this combination working?
I've tried (https://codepen.io/SphinxKnight/pen/gOaGENr ) and that's not really working neither on Fx 75 (background is clipped to the text and quickly appear after scrolling but disappears right after) nor on Chrome 81 (background is not clipped at all)

N.B. It works indeed when prefixed with `-webkit`.

**Comment by Elchi3** [comment]
Closing this given no answer. Compat data issues can always be filed against https://github.com/mdn/browser-compat-data/
