### ISSUE TITLE
/en-US/docs/Web/API/ServiceWorkerGlobalScope/message_event

### ISSUE THREAD

**Issue by Syul968** [mdn/sprints#3012]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[Typo?](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/message_event#Examples)
"In thie example a page" [...]

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting.
