### ISSUE TITLE
/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics

### ISSUE THREAD

**Issue by goransipic** [mdn/sprints#3013]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Macbook Pro 13
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

Hi there is problem with not showing images.

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics#Conclusion

![Screenshot 2020-04-01 at 09 40 42](https://user-images.githubusercontent.com/6122624/78112043-eb4f8a00-73fd-11ea-9be7-4eda67b073b4.png)

**Comment by chrisdavidmills** [comment]
Hi @goransipic ,

I've just tested this on macOS, with Chrome 80 and Firefox 75 - works fine for me.

Are you seeing this problem all the time, or just sometimes? And is it on all MDN pages, or just some? I wonder if we are doing some kind of clever image loading for performance that sometimes results in this.

**Comment by goransipic** [comment]
Hi @chrisdavidmills,

This is also problem on other pages.

[CSS basics - Learn web development](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
 
![Screenshot 2020-04-01 at 10 03 17](https://user-images.githubusercontent.com/6122624/78113495-1dfa8200-7400-11ea-8db0-126e637877c3.png)

**Comment by chrisdavidmills** [comment]
@goransipic OK, thanks. Do you experience the same problem on other browsers? Do you have any kind of extension installed that might be causing this problem? (try disabling all your extensions and then see if the problem remains)

@schalkneethling , do you know of any clever image loading techniques we are using that might be causing an intermittent problem like this?

**Comment by goransipic** [comment]
@chrisdavidmills  I have make same request with **_safari_**.  On safari i not using any kind of extensions.

OK - https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics#Conclusion

NOK - [CSS basics - Learn web development](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)

![Screenshot 2020-04-01 at 10 23 41](https://user-images.githubusercontent.com/6122624/78115297-e17c5580-7402-11ea-94e6-14ee7ddcd03f.png)

**Comment by schalkneethling** [comment]
> @schalkneethling , do you know of any clever image loading techniques we are using that might be causing an intermittent problem like this?

None that I am aware of. Will take a look.

**Comment by schalkneethling** [comment]
So far I have not been able to reproduce this in any browser. Will keep poking at it though.

I notice that these load from a different domain. Not sure if there may be a security restriction blocking the images but, I would expect that to be consistent across all images then. Throwing it out there anyway. :)

**Comment by goransipic** [comment]
Hi @schalkneethling @chrisdavidmills. 

I have checked on my home wifi its working OK. So there must be something with security restriction on my job.

Thx 👍

**Comment by schalkneethling** [comment]
> Hi @schalkneethling @chrisdavidmills.
> 
> I have checked on my home wifi its working OK. So there must be something with security restriction on my job.
> 
> Thx 👍

Thank you for letting us know! Much appreciated.
