### ISSUE TITLE
/en-US/docs/Web/API/DeviceOrientationEvent - deprecated or not?

### ISSUE THREAD

**Issue by WebMechanic** [mdn/sprints#3015]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent

# Details
Running the code below in current Firefoxes (74+up) results in a console message: **"Use of the orientation sensor is deprecated."**
```js
window.addEventListener("deviceorientation", function(event) {
	console.log("deviceorientation", event);
});
```
How so? 
According to MDN the API is still _experimental_ and as of March 2020 the [Spec](https://w3c.github.io/deviceorientation/) is in ED. Then there's #2870 with a request for enhancing the API doc.

There is no notion of this API being deprecated on the MDN page or its Working Group and if so what the recommended replacement would be. 

Maybe someone should have a chat with the Firefox developers? :)

Stay healthy! 😷

**Comment by chrisdavidmills** [comment]
Hrm, there was definitely something about this functionality being deprecated a while ago, but I can't remember where we got to with it. It would make sense to update our pages appropriately.

**Comment by WebMechanic** [comment]
anything to do with Fingerprinting & Permisions?
- https://w3c.github.io/sensors/#feature-policy-api
- https://bugzilla.mozilla.org/show_bug.cgi?id=1536382
- https://arxiv.org/abs/1408.1416 Sensor Fingerprinting
