### ISSUE TITLE
/zh-CN/docs/Learn/Getting_started_with_the_web/JavaScript_basics

### ISSUE THREAD

**Issue by Cotory** [mdn/sprints#3019]
# Request type

- [ ] Correction or update

# Details

https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web/JavaScript_basics
In the "添加个性化欢迎信息" part

"1.打开 index.html， 在 <script> 标签前添加以下代码"
should be changed into
"1.打开 index.html， 在 `<body>`标签前添加以下代码 "

**Comment by chrisdavidmills** [comment]
Hi @Cotory !

I appreciate you trying to report an error, but I can't seem to find this bit of text on the page. Can you log into MDN and fix this yourself? I would be more than happy for you to do that, and it would be really helpful ;-)
