### ISSUE TITLE
Misspelling of the word "and"

### ISSUE THREAD

**Issue by overthemike** [mdn/sprints#3020]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Simple misspelling of the word "and" on this page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture. It is located in the media attribute section in the second paragraph. Text below

If the <source>'s media condition evaluates to false, the browser skips it *an* evaluates the next element inside <picture>.

should be

If the <source>'s media condition evaluates to false, the browser skips it *and* evaluates the next element inside <picture>.

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
