### ISSUE TITLE
Re-render pages for fresh compat data (April 2020 edition)

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3024]
Please re-render all pages with the compat macro, so that users see the latest data.

cc @escattone

**Comment by escattone** [comment]
Thanks for creating this issue @Elchi3!

### Summary
I run [this gist](https://gist.github.com/escattone/2f1a27a16ebd4233b0f1197a58eb9c0a) within a `./manage.py shell_plus` on a celery-worker pod, and scale-up the **api** and **kumascript** pods to six (6) pods each before I make the run. It usually takes about 1-2 hours to render about 20K documents.

### Acceptance Criteria
- [ ] All documents that use the `compat` macro have been successfully re-rendered on prod

**Comment by escattone** [comment]
I re-rendered 21,160 documents that contain the `compat` macro in about 68 minutes.
