### ISSUE TITLE
A page on ScreenOrientation.lock() is faulty

### ISSUE THREAD

**Issue by 123survesh** [mdn/sprints#3025]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock
The above link is about a feature called **ScreenOrientation.lock(orientation)**. It suggests ScreenOrientation.lock as an alternative for screen.lock. And it says ScreenOrientation.lock is supported in Firefox, Chrome and and some more browsers.
When I tested, I found that the object **ScreenOrientation** is present in both Firefox and Chromium, but the method **lock** is missing on both platforms.

Test Data:
OS: Debian 10 x64
Browsers Tested in: Firefox 68.6.0esr (64-bit) and Chromium Version 80.0.3987.149

How to Test:
1. Open any one of the above browsers
2. Open developer console. (CTRL + SHIFT + I)
3. type ScreenOrientation.lock

Expected Result:
**function lock()**

Result Got:
**undefined**

**Comment by MendyBerger** [comment]
ScreenOrientation is just a class not an instance.

If you want access to an instantiated ScreenOrientation object checkout [screen.orientation](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation).

So, `screen.orientation.lock` should be a function.

**Comment by MendyBerger** [comment]
I've updated the [ScreenOrientation](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation) docs with a link to `screen.orientation` so that future viewers know where to find a ScreenOrientation instance.

I think that this can now be closed.

**Comment by chrisdavidmills** [comment]
Thanks for adding this @MendyBerger. This does highlight an issue with our current docs —  that static members and instance members are not clearly differentiated in many cases, and the page titles of the member pages kind of imply that they are all static members.

This is a project we'll have to do at some point after we move to Yari — it will be a lot easier then, once we can do mass edits.
