### ISSUE TITLE
/fr/docs/Web/JavaScript/Reference/Objets_globaux/AsyncFunction

### ISSUE THREAD

**Issue by ent47** [mdn/sprints#3026]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Fix typo error: the word "**ellee**" should be rewriten to "**elles**"

![2020-04-03_09h29_17](https://user-images.githubusercontent.com/26608715/78335398-d570cf00-758d-11ea-8f1c-eb8c71cc89c0.png)

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately, we only maintain the English MDN docs. Feel free to sign up for an account and fix the French wiki page yourself.
