### ISSUE TITLE
HTTP caching problem with Vary: User-Agent

### ISSUE THREAD

**Issue by frncmx** [mdn/sprints#3027]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
[HTTP caching](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Caching) article suggests - in the last section - using `Vary: User-Agent` to serve different versions to mobile and desktop users. That will work, however, that probably defeats the purpose of caching. As there are thousands of different user-agents. So I believe the suggestion is problematic without mentioning normalization and the problem behind it.

For more explanation see: https://www.fastly.com/blog/best-practices-using-vary-header (section: `Vary: User-Agent`)

**Comment by hamishwillee** [comment]
@frncmx Thanks for this - makes sense.

I have given the section [Varying responses](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Caching#Varying_responses) a significant subedit and added a new section at the end on normalisation. 

@chrisdavidmills Can you please sanity check that section, and close this if you are happy.

**Comment by chrisdavidmills** [comment]
@hamishwillee these updates looks good, thanks! I just made a couple of small tweaks.
