### ISSUE TITLE
/en-US/docs/Web/CSS/border-radius

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/sprints#3029]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The Examples have a bug.  The right border is missing.

![image](https://user-images.githubusercontent.com/40804543/78406727-d8d57c00-75c8-11ea-9335-04976235c99d.png)

**Comment by chrisdavidmills** [comment]
Examples fixed - thanks for pointing this out! The default MDN styles for the `<pre>` blocks were clashing with these border blocks, so I had to do a bit of fiddling and adding in of  `!important`. Felt pretty dirty, but it worked ;-)
