### ISSUE TITLE
/ru/docs/Web/CSS/:any

### ISSUE THREAD

**Issue by ZerDriden** [mdn/sprints#3031]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

"Это альтернатива для прописывания комбинаций селекторов для одного элемента, который может находится в разных родителях." - нужно "находитЬся" (может что делаТЬ? находитТЬСЯ)
![image](https://user-images.githubusercontent.com/16036488/78457223-52e13000-76b1-11ea-9c50-b94a8aa3cf21.png)

**Comment by Elchi3** [comment]
Thanks for your issue. Unfortunately, we don't speak Russian and don't work on fixing MDN translations.
