### ISSUE TITLE
Selected english but still in spanish

### ISSUE THREAD

**Issue by nikodg** [mdn/sprints#3032]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Please visit this link - https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types
English is selected as the language but the page is in Spanish.
Please see attached image.

<img width="1440" alt="Screen Shot 2020-04-05 at 4 32 20 pm" src="https://user-images.githubusercontent.com/10623915/78470368-909a9300-775b-11ea-9e4c-1c9fbec9cd5a.png">

Thank you MDN!

**Comment by nikodg** [comment]
Also the I am not sure what to follow because the sidebar links and the **In This Module** section is different (Please see attached images)

Sidebar Links Image
<img width="1440" alt="Screen Shot 2020-04-05 at 5 04 08 pm" src="https://user-images.githubusercontent.com/10623915/78470935-d22d3d00-775f-11ea-968a-965621db6043.png">

In This Module section links
<img width="1440" alt="Screen Shot 2020-04-05 at 5 03 23 pm" src="https://user-images.githubusercontent.com/10623915/78470940-d8bbb480-775f-11ea-89d5-cbb13ede9146.png">

Thanks again MDN

**Comment by chrisdavidmills** [comment]
Thanks for reporting this; someone translated some of that page into Spanish, so I've reverted it.

As for the sidebar, I did submit a pull request to update it to the new structure in January, but it has bene forgotten about. I've asked for a review on it now. The list in the page is the correct one.

**Comment by nikodg** [comment]
Thank you @chrisdavidmills , truly appreciate the quick response.
