### ISSUE TITLE
Basic math in JavaScript & Test your skills: Math 2

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#3037]
# Request type

- [x] New documentation

# Details

Reference:
The "[Basic math in JavaScript — numbers and operators](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math)" tutorial and the
"[Test your skills: Math 2](https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math#Math_2)" exercise.
Two items or subjects are not really covered in the referenced tutorial, which are apart of the associated Math 2 exercise;

1. The [toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) method.
2. The [Number JavaScript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number).

Could additional materials/examples/references to the "[toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)" method and the "[Number JavaScript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)" be added to the "[Basic math in JavaScript — numbers and operators](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math)" tutorial, such to help future students, please?
Separate sub articles explaining what these items are, and when to use them would be really helpful, or a reference link to such articles.
Thanks again for the great tutorials.!

**Comment by chrisdavidmills** [comment]
@RisingThunder you've got a good point here; I've added a couple of extra subsections below here:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math#Everybody_loves_math

Let me know if you think this works at providing the missing information.

**Comment by RisingThunder** [comment]
Yeah, those are really good! An eloquent and simple introduction to the subjects.
I did have a related question to the Skill Math Test 2 though, which I posted in the "Learn" forum.
Maybe you could look at it when you have time?
[Test your skills: Math2: I have a Question](url)
Thanks!!

**Comment by chrisdavidmills** [comment]
OK, cool. I'll close this for now, and then reply to your question in the forum.
