### ISSUE TITLE
U - Refresh docs related to secure data management

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3052]
# User story
As a web developer, I want current information about securely managing data, so I can implement best practices on my site.

# Acceptance criteria
- [x] The [article on Cookies](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) is up to date, especially info about same-site, secure, and HttpOnly cookies.
- [x] The [article on localStorage](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Local_storage) is up to date with current best practices.

**Comment by jmswisher** [comment]
Renamed and revamped the [Using HTTP cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) guide article.

**Comment by jmswisher** [comment]
Once I deleted the no-longer-needed polyfills from the [localStorage guide](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Local_storage), there wasn't much meat left. So I made sure all the same info was covered in the [localStorage reference article](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), and redirected the guide URL to there. 

Submitted [this PR](https://github.com/mdn/kumascript/pull/1382) to remove the localStorage guide from the Web Storage API sidebar.

**Comment by Elchi3** [comment]
The PR was merged and the AC items here are met. Closing this.
