### ISSUE TITLE
U - Refresh docs on clickjacking protection

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3054]
# User story
As a web developer, I want current information on clickjacking protection, so I can securely configure my site.

# Acceptance criteria
- [x] The article on [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) is up to date with current best practices.
- [x] The reference page on [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) is up to date.

**Comment by jmswisher** [comment]
Reviewed the [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) reference page; verified that the instructions for setting it in various web servers seem to be up-to-date.

**Comment by jmswisher** [comment]
Reviewed and edited the [CSP guide](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) as well as the [CSP header reference article](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy), [default-src](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src) and glossary articles about types of CSP directives (which were unnecessarily transcluding sections of the CSP header article).

**Comment by Elchi3** [comment]
Thanks Janet! Looks like the AC items are met. Closing this.
