### ISSUE TITLE
U - Document best practices for access control

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3059]
# User story
As a web developer, I want to know best practices for access control, so I can securely configure my site.

# Acceptance criteria
- [ ] Best practices for access control have been documented, including passwords and session tokens.

**Comment by chrisdavidmills** [comment]
@jmswisher could this section of docs also include CSP best practices and errors? We have this issue from a while ago that the dev toosl team would love us to work on: https://github.com/mdn/sprints/issues/316
