### ISSUE TITLE
[CSS] Color, Fx 76 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3061]
# Trello

https://trello.com/c/8lDSXVTL/257-css-colors-fx-76

# Acceptance criteria

1. - [ ] [Need to support CSS4 system colors](https://bugzilla.mozilla.org/show_bug.cgi?id=1590894)

**Comment by jmswisher** [comment]
Updated the [System colors](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#System_Colors) section of the color data type page, and moved the old values into a "deprecated" subsection. Linked to the system colors section from the [forced-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) page.

**Comment by chrisdavidmills** [comment]
Rel note added: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/76#CSS.

@jmswisher, can you please add these in future?
