### ISSUE TITLE
[JS] Regexes, Fx 78 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3062]
## Story

Iain Ireland on the SpiderMonkey team just completed a major upgrade of our JavaScript regular expression engine. The net result is a major improvement in Firefox compatibility. 

https://trello.com/c/Ndn0NQgz/3666-js-lang-update-regular-expression-engine-regexpr

## Acceptance criteria

Dev-doc-complete the following bugs, write release notes, add it to the hacks blog post about Firefox 78:

1. - [x] [Enable new regexp engine in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1634135) (it is Nightly, but I think this is important, so it is probably worth documenting early; also see the [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/oHXLYkUKWGo))
2. - [x] Bug 1361876 - Implement RegExp Unicode Property Escapes
3. - [x] Bug 1361856 - Implement RegExp s (dotAll) flag
4. - [x] Bug 1225665 - Implement RegExp lookbehind
5. - [x] Bug 1362154 - Implement RegExp named groups

**Comment by chrisdavidmills** [comment]
@Elchi3 heads up — I'm not sure if this is relevant to the Fx 76 cycle. The bug says 76 affected, but the bug it is dependent on is not fixed, and this one is not fixed either.

**Comment by Elchi3** [comment]
Yes, this is for Firefox 78 per https://groups.google.com/forum/#!topic/mozilla.dev.platform/oHXLYkUKWGo

Move to a later sprint?

**Comment by chrisdavidmills** [comment]
@Elchi3 moveed! I've cfreated an Epic for the 78 DDNs and put it in there.

**Comment by Elchi3** [comment]
All bugs set to dev-doc complete. See https://bugzilla.mozilla.org/show_bug.cgi?id=1634135#c36 for links to all relevant docs here.
