### ISSUE TITLE
[DevTools] Primary tool updates, Fx76 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3069]
# Trello

https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-js-debugger-fx-76

# Acceptance criteria

1. - [x] [Enable/disable blackbox of source groups by context menu?](https://bugzilla.mozilla.org/show_bug.cgi?id=1118152)
2. - [x] [Copy as cURL should include --globoff](https://bugzilla.mozilla.org/show_bug.cgi?id=1549773)
3. - [x] [Have option to hide WS control frames](https://bugzilla.mozilla.org/show_bug.cgi?id=1566780)
4. - [x] [Limit the number of chars of commands in the output and allow them to be expanded](https://bugzilla.mozilla.org/show_bug.cgi?id=1578212)
5. - [x] [Add "Reveal in Inspector" context menu entry on elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1612276)
6. - [x] [Double-clicking table resizes handles should resize column to fit content](https://bugzilla.mozilla.org/show_bug.cgi?id=1615102)
7. - [x] [Stack Trace's "Copy Stack Trace" Menu should copy full URL](https://bugzilla.mozilla.org/show_bug.cgi?id=1619039)

**Comment by jmswisher** [comment]
In documenting the first item, I discovered that blackboxing was covered only in [Set event listener breakpoints](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints), which is too limited in scope for this feature. So I documented all the file- and folder-level context menu options of the Source List pane in the [Source List section of the Debugger UI Tour](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Source_list_pane).

**Comment by jmswisher** [comment]
Added `--globoff` to the [Copy as cURL](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Copy_as_cURL) table in the Network Request List article.

**Comment by jmswisher** [comment]
Item #5: Context menu options in the console were not documented at all (that I could find). So I added the general ones to the intro of [Console messages](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages) and this to the [Interpreter input/output](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Interpreter_inputoutput) subsection.

**Comment by jmswisher** [comment]
Item 4: Added a paragraph about this feature to the [Multi-line mode](https://wiki.developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter#Multi-line_mode) section of the interpreter article.

**Comment by jmswisher** [comment]
Item 6: Added a description of this to the [Network request columns](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Network_request_columns) section of the "Network request list" article; added a little context so it makes sense.

**Comment by jmswisher** [comment]
Item 7: The context menu for the Call Stack pane was not documented, so I added it to the [Call stack](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Call_stack) section of the debugger UI tour article.

**Comment by jmswisher** [comment]
Item 3: The Messages tab was not documented, so I added a [Messages](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Messages) section to the "Network request details" article. Sorry, I don't have a good example to use for screen shots, so I didn't add any.

**Comment by chrisdavidmills** [comment]
Rel notes added for all of these: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/76#Developer_tools

**Comment by jmswisher** [comment]
I had not realized there was a page on [Inspecting web sockets](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_web_sockets). I move the description of the message filter menu into the [Filtering web socket frames](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_web_sockets#Filtering_web_socket_frames) section of that page, and added a screenshot. I replaced that info on the [Monitor request details](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details) page with a link to the "Inspecting" page.
