### ISSUE TITLE
[DevTools] RDM, Fx 76 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3070]
# Trello

https://trello.com/c/yhX2isxm/260-responsive-design-mode-fx-76

# Acceptance criteria

1. - [x] [Support double-tap-to-zoom in Responsive Design Mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1489653)

**Comment by jmswisher** [comment]
Added a sentence about simulating double-tap with double-click, in [Using Responsive Design Mode](https://wiki.developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode#Using_Responsive_Design_Mode), under the bullet about Touch Support.

**Comment by jmswisher** [comment]
And then reverted, based on [Sebo's comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1489653#c26). Added the feature and preference flag to the [Developer Tools section of Experimental Features in Firefox](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Developer_Tools).
