### ISSUE TITLE
[DevTools] Remote debugging, Fx 76 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3071]
# Trello

https://trello.com/c/ZLneh5mV/10-remote-debugging-aboutdebugging-fx-76

# Acceptance criteria

1. - [x] [Show dedicated warning to users trying to connect to Firefox for Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1625906)

**Comment by jmswisher** [comment]
[Draft for MDN from Julian Descottes](https://bugzilla.mozilla.org/show_bug.cgi?id=1625906#c8)

**Comment by jmswisher** [comment]
Created the [new section](https://wiki.developer.mozilla.org/en-US/docs/Tools/about:debugging#Connection_to_Firefox_for_Android_68). There was already a note about version disparities under [Connecting to a remote device](https://wiki.developer.mozilla.org/en-US/docs/Tools/about:debugging#Connecting_to_a_remote_device), so I put the info about the error message there.

**Comment by chrisdavidmills** [comment]
Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/76#Remote_debugging
