### ISSUE TITLE
/en-US/docs/Learn/Forms/HTML5_input_types

### ISSUE THREAD

**Issue by Vjyanca** [mdn/sprints#3072]
# Request type
- [ ] Correction or update

# Details
The first half of the page except the examples is in Spanish including the title at title bar and the remaining half in English. It has to be translated in English for it to be read.
[https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types](url)

# Screenshots
[html5 input types.docx](https://github.com/mdn/sprints/files/4446325/html5.input.types.docx)

**Comment by wbamberg** [comment]
Thanks for filing, this seems to have been fixed.

**Comment by Vjyanca** [comment]
Thanks a lot.
