### ISSUE TITLE
/en-US/docs/Tools/Web_Console/Helpers#pprint

### ISSUE THREAD

**Issue by mrwensveen** [mdn/sprints#3077]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The pprint helper has been removed as per https://bugzilla.mozilla.org/show_bug.cgi?id=1613843.  

I actually only found out about this helper when reading the What's New pages for FF 75, only to find out that it doesn't work anymore. The rationale for removing this helper is flimsy at best, but who am I to argue?

# Acceptance criteria
- [ ] The documentation and example for pprint should therefore be removed.
- [ ] If possible, an equivalent example should be provided.

**Comment by mrwensveen** [comment]
Also here: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter#Helper_commands

**Comment by jmswisher** [comment]
Marked as Obsolete inline in the article

**Comment by jmswisher** [comment]
The list in the  "interpreter" article is transcluded from the "Helpers" article. Force-refreshed it to get the update.
