### ISSUE TITLE
documentation for Date doesn't list the parameters for the constructor

### ISSUE THREAD

**Issue by timrobinson33** [mdn/sprints#3078]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I wanted to find out about the parameters for the Date constructor. The obvious place to look was here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Constructor

but it doesn't even mention passing parameters. Just underneath in a different section it says "The value of Date.length is 7. This is the number of arguments handled by the constructor", but even the examples at the bottom only go up to a mxmimum of 6.

Specifically I wanted to find out what would happen if I passed in null or undefined. By experiment, the answer seems to be that passing in null is the same as passing in no parameters, but passing undefined throws an error)

**Comment by chrisdavidmills** [comment]
The parameters of the `Date()` constructor are talked about in a lot more detail on the actual constructor page:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

Does that give you the information you need? Always happy to add more details if you think something is missing.

**Comment by timrobinson33** [comment]
Ah sorry, I think I was confused by the fact that the constructor's own page isn't listed in the left-hand navigator so I didn't originally find it.

so my main feedback is that it would be useful to include constructors in the navigator alongside the methods. This is what Microsoft do (e.g. https://docs.microsoft.com/en-us/dotnet/api/system.web.httpcontext), but I appreciate that's probably just the style of the MDN documentation so it would be a huge effort to update it all.

In terms of the actual constructor page, I don't see any problems. The fact that it links directly to the ECMAScript spec means it's perfect for pedants like me to find out what would happen if you pass in things like null or undefined.

**Comment by chrisdavidmills** [comment]
Ah, I think it should be included in the sidebar. We'll have to look into that.

Glad we were able to help you in the end. I'll close this for now.
