### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by coolheinze** [mdn/sprints#3079]
On the page for Array.prototype.reduce(), the `console.log(array1.reduce(reducer, 5));` example states `// expected output: 15`, which is wrong; the expected output is `20`.

The accumulated value of the array contents is 15, but the example includes the optional `initialValue=5`.

(Link to page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

**Comment by chrisdavidmills** [comment]
The example is correct — the accumulated value of the array contents is 10 (1 + 2 + 3 + 4), and the second returns 15 because it has the initial value added onto that (5 + 1 + 2 + 3 + 4)

**Comment by coolheinze** [comment]
D’oh... I see it now. Sorry, my bad.
