### ISSUE TITLE
"Introduction to formatting contexts" appears to contradict itself

### ISSUE THREAD

**Issue by anno1985** [mdn/sprints#3085]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[The page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/Intro_to_formatting_contexts) currently states:
> Any element that defaults to block layout also creates a block formatting context for its descendant elements.

From my understanding, a [`div` is a block-level element](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements), thus should default to block layout as per that sentence.

The first example on the page seems to contradict that, though:
```
<div class="box">
    <div class="float">I am a floated box!</div>
    <p>I am content inside the container.</p>
</div>
```
The `.box` div should create a BCF, containing any floats, yet the `div.float` overflows its `div.box` container.

The example then goes on to explicitly create a BCF by setting `overflow` of `.box` to `auto` (which one wouldn't have to do if a block-level element like `div` actually created a BCF by virtue of defaulting to block layout). 

I'm not sure a `div` is (still) considered an "element that defaults to block layout" as per current specs?

**Comment by chrisdavidmills** [comment]
@anno1985 To my knowledge, it does still default to block layout, so this is a good question. 

@rachelandrew, would you have time to have a quick look at this, and suggest an answer here?

**Comment by rachelandrew** [comment]
A div is block-level, but doesn't create a new BFC. Everything is either a block-level or inline-level box. Those block-level boxes don't create a BFC. This has been extensively edited since my original though, and I think that line is incorrect.

**Comment by chrisdavidmills** [comment]
> A div is block-level, but doesn't create a new BFC. Everything is either a block-level or inline-level box. Those block-level boxes don't create a BFC. This has been extensively edited since my original though, and I think that line is incorrect.

OK, thanks Rachel! I've updated it a bit, in particular changing the line in question to read like this:

"The {{HTMLElement("html")}} element is not the only element capable of creating a block formatting context. Any block-level element can be made to create a BFC by the application of certain CSS properties."

Is this better?

**Comment by rachelandrew** [comment]
yeah I think that's more accurate, somewhere on MDN I did write a more complete explanation of what block boxes, block-level boxes and block formatting contexts are.
