### ISSUE TITLE
/en-US/docs/Web/API/SubtleCrypto/exportKey

### ISSUE THREAD

**Issue by davidcallanan** [mdn/sprints#3090]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The documentation says:

> result is a Promise that fulfills with an `ArrayBuffer` containing the key in the requested export format.

This is incorrect, the return value is **not** always an ArrayBuffer. As shown in the example later on in the page, when `jwk` is specified for the `format`, the return value is a JSON-serializable JavaScript object. It also may be incorrect with some of the other formats but I haven't checked those.

I've waisted a lot of time assuming the return value was an ArrayBuffer, so this should be fixed.

**Comment by wbamberg** [comment]
Thank you for pointing this our. I've updated https://wiki.developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/exportKey#Return_value.
