### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Glossary/Tratando_Formul%C3%A1rios_com_PHP

### ISSUE THREAD

**Issue by mfuji09** [mdn/sprints#3092]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This article is just a copy from https://www.php.net/manual/pt_BR/tutorial.forms.php (and its English version).
Also, I think this article is not appropriate as a glossary.

**Comment by chrisdavidmills** [comment]
Agreed; I've deleted it. Thanks for reporting!
