### ISSUE TITLE
/en-US/docs/Web/API/Intersection_Observer_API

### ISSUE THREAD

**Issue by choyg** [mdn/sprints#3094]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The following text is used to describe the `isIntersecting` property:

>You can tell which direction the visibility changed in (that is, whether the element became more visible or less visible) by checking the value of the isIntersecting property on the IntersectionObserverEntry passed into the callback function at the time of the visibility change. **If isIntersecting is true, the target element has become at least as visible as the threshold that was passed. If it's false, the target is no longer as visible as the given threshold.**

However in reality and as stated by the w3c spec, `isIntersecting` merely indicates any intersection has occurred between the target and root elements regardless of the specified thresholds.

https://w3c.github.io/IntersectionObserver/#update-intersection-observations-algo
>Let isIntersecting be true if targetRect and rootBounds intersect or are edge-adjacent, even if the intersection has zero area (because rootBounds or targetRect have zero area); otherwise, let isIntersecting be false.

Instead, the [IntersectionRatio](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/intersectionRatio) should be used to determine the visibility of the target element.

**Comment by Rumyra** [comment]
I'm unable to find the referenced text within the Intersection Observer docs - the page mentioned is https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API and I can't find it there or on any member pages.

Would someone be able to confirm the url of the page, or infact this issue has been resolved - thanks

**Comment by choyg** [comment]
Looks like that page got updated. It used to be part of the ['Thresholds' section](https://web.archive.org/web/20200413103435/https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

Current version:
>You can see if the target currently intersects the root by looking at the entry's  isIntersecting property; if its value is true, the target is at least partially intersecting the root element or document. This lets you determine whether the entry represents a transition from the elements intersecting to no longer intersecting or a transition from not intersecting to intersecting.

**Comment by Rumyra** [comment]
Brill thank you @choyg - I'll go ahead and close it 👍
