### ISSUE TITLE
/ja/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals

### ISSUE THREAD

**Issue by kei2100** [mdn/sprints#3095]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The `見出し岳` seems to be a typo for `見出しだけ` in Japanese.

|![image](https://user-images.githubusercontent.com/1415655/79067119-38820480-7cf8-11ea-963f-af56a3b5ad95.png)|
|:-:|

**Comment by sideshowbarker** [comment]
> The `見出し岳` seems to be a typo for `見出しだけ` in Japanese.

Yes — fixed

**Comment by kei2100** [comment]
Thank you for your quick response 🚀 
I confirmed that it was fixed.
