### ISSUE TITLE
/en-US/docs/Web/CSS/content#Image_combined_with_text: does not show a result

### ISSUE THREAD

**Issue by almaceleste** [mdn/sprints#3096]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I can not see a result in the section [Image combined with text](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/content#Image_combined_with_text) of the [css/content](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/content) page. 
I can't imagine, what's wrong here.
help, please.

![image](https://user-images.githubusercontent.com/36765595/79077483-c830ae80-7d0a-11ea-93a1-97052cb27f61.png)

**Comment by chrisdavidmills** [comment]
This seems to work fine for me. You are talking about the live example result a https://developer.mozilla.org/en-US/docs/Web/CSS/content#Image_combined_with_text, correct?
