### ISSUE TITLE
Conflicting message regarding custom elements

### ISSUE THREAD

**Issue by mag911** [mdn/sprints#3097]
# Request type

- [x] Correction or update

# Details

On this page:
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

It states:

There are two types of custom elements:

- **Autonomous custom elements** are standalone — they **don't inherit** from standard HTML elements. ...

- **Customized built-in elements** inherit from basic HTML elements. ...

Confusingly, just a few sentences/paragraphs away in the "**Working through some simple examples**", it states:

"To begin with, the JavaScript file defines a class called PopUpInfo, which extends HTMLElement. **Autonomous custom elements nearly always extend HTMLElement**."

At the top of the page in the "High-level view", it states:

- Optionally, an options object containing an **extends property**, which specifies the built-in element **your element inherits from** if any.

Note: I think your MDN documentation is first-class and brilliant. I just wanted to highlight this anomaly that I found, which is less than clear and comes across as contradictory.

If _autonomous custom elements are standalone and don't inherit_, it's confusing to then say "_autonomous custom elements nearly always extend HTMLElement_". Thoughts?

Regards.

**Comment by chrisdavidmills** [comment]
Hi there @mag911 ! Thanks for voicing your concerns here. I have tweaked the wording here, to make things a bit clearer, but I think this is largely OK.

It is saying that customized built-ins inherit their behavior and semaitcs from existing built-in HTML elements. The bit that seems to contradict that — "which extends HTMLElement" — is taking about Autonomous custom elements, yes, but this is saying that in the JavaScript class definition, the class for your Autonomous custom element inherits from the generic HTMLElement DOM class, which all HTML elements inherit from. So this isn't an actual HTML element — this is just a generic class that defines any DOM element.
