### ISSUE TITLE
Create HTML Global Attribute interactive examples

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#310]
# User story
As a web developer, I want to see interactive examples on the HTML global attributes, so I can learn how to use them

# Acceptance criteria

* All interactive examples submitted to interactive-examples repo as PRs (all that make sense)
* Discussion had about attributes for which interactive examples don't make sense.
* All PRs reviewed and merged
* All examples added to the relevant reference pages

# Tasks

Complete examples for the attributes listed in the Attributes tab of https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/

**Comment by wbamberg** [comment]
All done! -> https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=806634615
