### ISSUE TITLE
Accessing Form Elements: Names to Avoid

### ISSUE THREAD

**Issue by manngo** [mdn/sprints#3101]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The section in https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Accessing_the_forms_elements  states:

> You can also get the form's element by using its `name` attribute as a key of the `form`, but using `elements` is a better approach—it contains _only_ the form's elements, and it cannot be mixed with other attributes of the `form`.

It should be noted that some names will interfere with normal access to the form’s properties and elements.

For example:

- `name="id"` will take precedence over the form’s `id` attribute when referencing `form.id`. This would be true of any other form properties.
- `name="elements"` will render the form’s `elements` collection inaccessible, as `form.elements` will now reference one particular element only.

To avoid such problems with element names:

- Always use the `elements` collection to avoid ambiguity
- _Never_ use `elements` as an element name.

I would be happy to add this myself if it’s OK.

**Comment by chrisdavidmills** [comment]
@manngo this would be a useful addition, and I'd be happy for you to add it. Thanks!

**Comment by manngo** [comment]
@chrisdavidmills Thanks for your comment. I have submitted the addition, but have requested a review as I’m new at doing this sort of thing.

**Comment by chrisdavidmills** [comment]
@manngo I've reviewed it, and it looks fine. Thanks for the contribution!
