### ISSUE TITLE
/en-US/docs/Web/CSS/:hover

### ISSUE THREAD

**Issue by dirkf** [mdn/sprints#3102]
# Request type
- [X] Correction or update

# Details
The anchor for the WHATWG HTML section specifying :hover is now #pseudo-classes, not #selector-hover.

**Comment by chrisdavidmills** [comment]
AFAIK, the page is correct. #pseudo-classes points to the overall section on pseudo-classes, whereas #selector-hover points to the :hover subsection inside that.

**Comment by dirkf** [comment]
No, you're right, but the root URL linked from the MDN :hover page is `https://html.spec.whatwg.org/multipage/scripting.html`, which was a level of breakage I hadn't considered. It should be `https://html.spec.whatwg.org/multipage/semantics-other.html`.

**Comment by chrisdavidmills** [comment]
@dirkf ah, I see, it redirects, making me think it was right ;-)

I've had another go at fixing it.

**Comment by dirkf** [comment]
Thanks, that's good.

**Comment by chrisdavidmills** [comment]
cool ;-)
