### ISSUE TITLE
Scroll documentation bug in Safari

### ISSUE THREAD

**Issue by lee-leonardo** [mdn/sprints#3103]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

- [https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)
- The page is not displaying the interactive iframe properly in Desktop and Mobile Safari.
- This interactive iframe works as intended on other pages.

**Comment by chrisdavidmills** [comment]
Hi there @lee-leonardo ! This is because scroll-behavior is not currently supported by the desktop Safari/iOS browsers. At the moment, this is what our site does when a non-supporting browser tries to look at a live example. Could be better, but this is what we have for now.
