### ISSUE TITLE
Translation of "Library" into Spanish

### ISSUE THREAD

**Issue by gjmananag** [mdn/sprints#3104]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

1. First things first: great documentation!
2. However, I have seen on many pages that "Library" has been translated into Spanish as "Librería". This is what in Spanish is known as an "anglicismo" or anglicism: a word from the English language used in another. I understand that the correct translation should be "Biblioteca", like in "biblioteca de clases" o "biblioteca de funciones". WIthout further ado, I congratulate you on the work done.

**Comment by Elchi3** [comment]
Thanks for filing this issue! The MDN team doesn't maintain the translations, feel free to update the wiki pages for the Spanish translation yourself.
