### ISSUE TITLE
August does not work properly in the practice at the bottom.

### ISSUE THREAD

**Issue by Tarzeus** [mdn/sprints#3105]
# Request type
- [x] New documentation

# Details
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

in the Practice calender at the bottom the August month does not work properly to me, I can not get the number of days to change the way it should even in the solution shown, the live code does not respond as it should. After spending 30 minutes trying to debug my code I realized there is some issue behind the scenes it appears.

**Comment by chrisdavidmills** [comment]
I'm not sure what the problem is here — when I press "Show solution" and then select August from the drop down, it shows 31 days, as intended. What behavior are you seeing?

**Comment by Tarzeus** [comment]
Maybe something is wrong with my code then, I had checked each month and at August it had repeated the same days as July or September and I couldn’t get it to change by my own code.

**Comment by Tarzeus** [comment]
> I'm not sure what the problem is here — when I press "Show solution" and then select August from the drop down, it shows 31 days, as intended. What behavior are you seeing?

I went down to the code and pressed Show Solution, July and August both have 31 days and they shouldn't be the same.
