### ISSUE TITLE
The object's properties in subnav(aside) don't need translation

### ISSUE THREAD

**Issue by pagemarks** [mdn/sprints#3106]
see the red area in screenshots:

https://wiki.developer.mozilla.org/zh-CN/docs/Web/API/URL/URL

![image](https://user-images.githubusercontent.com/48759702/79341573-9adc3e80-7f5e-11ea-9a55-c9d5a8b4b692.png)

https://wiki.developer.mozilla.org/zh-CN/docs/Web/API/URL

![image](https://user-images.githubusercontent.com/48759702/79341653-b8a9a380-7f5e-11ea-9502-82209c0852cf.png)

**Comment by Elchi3** [comment]
This really depends on the translation title. The MDN team doesn't maintain that translation, but feel free to update the translated title back to English in the wiki.
