### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

### ISSUE THREAD

**Issue by joewinger** [mdn/sprints#3108]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Hello! This is such a tiny typo but I wanted to submit it anyway.

The 3rd line in the 5th code block under the heading "Chained Promises" currently reads  
`const promiseC = promiseA.then(handleFulfille2, handleRejected2);`  
but should read  
`const promiseC = promiseA.then(handleFulfilled2, handleRejected2); `

**Comment by wbamberg** [comment]
Fixed: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Thanks for filing!
