### ISSUE TITLE
Create Page: Web/HTML/Global_attributes/enterkeyhint

### ISSUE THREAD

**Issue by eps1lon** [mdn/sprints#3109]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

[`enterkeyhint`](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute) in the WHATWG spec. [Chrome platform status of `enterkeyhint` (firefox, safari, chrome are supporting)](https://www.chromestatus.com/feature/5654529808793600)

**Comment by chrisdavidmills** [comment]
Looks like this exists now: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/enterKeyHint
