### ISSUE TITLE
MDN page showing non-English content on English language page

### ISSUE THREAD

**Issue by AndyC9** [mdn/sprints#3115]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
 https://developer.mozilla.org/en-US/docs/Web site is showing non-English in body copy
<img width="1556" alt="Screen Shot 2020-04-17 at 11 50 43 AM" src="https://user-images.githubusercontent.com/63866277/79588295-b69c2d80-80a1-11ea-9540-04a2a8b979ff.png">

**Comment by chrisdavidmills** [comment]
Fixed! Thanks for reporting.
