### ISSUE TITLE
`String.prototype.concat` docs are not clear about alternatives

### ISSUE THREAD

**Issue by gioragutt** [mdn/sprints#3116]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I came to see a colleague of mine use the `concat` method on a string.
This is the first time I saw someone use it, and I was curios to understand how he came to use this method.

Of course this was the result of googling `Concat strings nodejs`.

Having never have seen or used this method, I was curios as to what the docs say about it.

Everything seems good until the [performance section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat#Performance):

```
It is strongly recommended that the assignment operators (+, +=) are used instead of the concat() method. 
According to this performance test, the assignment operators are several times faster.
```

This is written in the bottom of the page, and isn't marked as something special (as in, it's not bold or shown as a warning or something).

I think that the least that should be done is to have the explanation of the performance section, as a general warning to use other concatenation methods (`+`, `+=`, or string templates).

I'm not familiar with the implementation details, and why it's not deprecated, but I would at least like to know what people think about this.

**Comment by chrisdavidmills** [comment]
I'm not sure this really needs extra explanation — the evidence is listed, the alternatives are linked to, and it is put underneath its own `<h2>`, which suggests a degree of importance.

I have moved it up the page, to right underneath the description, so it will be seen sooner. Do you think that improves things?

**Comment by gioragutt** [comment]
I guess it's better, but it all depend on why `concat` even exists, and whether users should use it at all.

I'm not sure who to discuss this about with, but what is the real use case of `concat`?
If there's no real reason to use it, and it's discouraged, I'd expect the page to have a warning on the top.

The fact that it has an `<h2>` indeed suggests a degree of importance, but the way it exists does not indicate anything "negative" about the method, as in - this looks just like any other part that provides information, when in fact - it practically provides a warning, and should show as such.

**Comment by chrisdavidmills** [comment]
I'd imagine concat probably exists because it was implemented, but then they made the other methods way faster, but they can't get rid of concat because of backwards compatibility. The age-old story of web platform.

**Comment by gioragutt** [comment]
Exactly what I had in mind. But I imagine this is not the only such method that is old and it's usage is discouraged...

I can't seem to find another such example in MDN, but if in fact you know of such one, isn't there a way to make this mark? It's practically what `Deprecated` is for, but the method is probably not officially deprecated 😕
