### ISSUE TITLE
Correction: Remove myHeading reassignment

### ISSUE THREAD

**Issue by everetr** [mdn/sprints#3117]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In [JavaScript Basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics), in the "Supercharging our example website" section, we're told to add these two lines to the bottom of `main.js`:

```javascript
let myButton = document.querySelector('button');  // line 1
let myHeading = document.querySelector('h1');    // line 2
```
However, I believe that Line 2 in the above snippet, `let myHeading = document.querySelector('h1');`, causes the example site to not behave as intended.

If I include Line 2 in `main.js`, the example site looks like this:

![image](https://user-images.githubusercontent.com/9023041/79641655-dfd2c180-8166-11ea-9e6a-8f2456e5955c.png)

The heading no longer says, "Hello world!", I'm not prompted for my name when the page loads, and the image no longer changes when clicked.

If I do not include Line 2 in `main.js`, the example site works as intended. I'm prompted for my name and the image changes when clicked. It looks like this:

![image](https://user-images.githubusercontent.com/9023041/79641686-16104100-8167-11ea-8db9-0df71fbdc87d.png)

Here's my `main.js` with "Line 2" from above (line 18 in the code below) commented out:

```javascript
const myHeading = document.querySelector('h1');
myHeading.textContent = 'Hello world!';

// Event: Change image when clicked
let myImage = document.querySelector('img');
// Assign anonymous function
myImage.onclick = function() {
    let mySrc = myImage.getAttribute('src');
    if(mySrc === 'images/firefox-icon.png') {
        myImage.setAttribute ('src','images/firefox2.png');
    } else {
        myImage.setAttribute ('src','images/firefox-icon.png');
    }
}

// Event: Personalized greeting when button clicked
let myButton = document.querySelector('button');
// let myHeading = document.querySelector('h1');
function setUserName() {
    let myName = prompt('Please enter your name.');
    if(!myName || myName === null) {
        setUserName();
    } else {
        localStorage.setItem('name', myName);
        myHeading.innerHTML = 'Mozilla is cool, ' + myName;
    }
}

if(!localStorage.getItem('name')) {
    setUserName();
} else {
    let storedName = localStorage.getItem('name');
    myHeading.textContent = 'Mozilla is cool, ' + storedName;
}

myButton.onclick = function() {
    setUserName();
}

```
Here's `index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="styles/style.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <h1>Mozilla is cool</h1>
    <img src="images/firefox-icon.png" alt="The Firefox logo: a flaming fox surrounding the Earth.">

    <p>At Mozilla, we’re a global community of</p>

    <ul> <!-- changed to list in the tutorial -->
      <li>technologists</li>
      <li>thinkers</li>
      <li>builders</li>
    </ul>

    <p>working together to keep the Internet alive and accessible, so people worldwide can be informed contributors and creators of the Web. We believe this act of human collaboration across an open platform is essential to individual growth and our collective future.</p>

    <p>Read the <a href="https://www.mozilla.org/en-US/about/manifesto/">Mozilla Manifesto</a> to learn even more about the values and principles that guide the pursuit of our mission.</p>
  <button>Change user</button>
  <script src="scripts/main.js"></script>
  </body>
</html>

```

**Comment by chrisdavidmills** [comment]
Hi @everetr !

This issue is occuring because you didn't remove the "Hello world" example code from the main.js file before starting to implement the examples at the bottom of the article. In the "adding an image changer" section, it says "(If your "Hello world!" JavaScript is still there, delete it.)".

Maybe I could pull that instruction out to its own bullet point, so it is more obvious. What do you think?
