### ISSUE TITLE
Update DevTools Landing Page

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#312]
As a user of the Firefox Developer Tools, I want the landing page to give me a concise, organized introduction to the development tools.

Rewrite/reorganize the landing page at [Firefox Developer Tools](https://developer.mozilla.org/en-US/docs/Tools) to present a better introduction to the developer tools.

Acceptance Criteria
- [x] Create outline for updated page
- [x] Outline has been reviewed and approved
- [x] Page has been edited to better reflect the content available for Developer Tools
- [ ] Changes have been reviewed by the DevTools team
- [ ] Changes to the page have been approved

**Comment by irenesmith** [comment]
Starting an outline for a new landing page which I will review with Harald before making extensive changes that might not be what is required.

**Comment by violasong** [comment]
Awesome, this is sorely needed :). 

Might be nice to get some of the community info from here onto the page: https://firefox-dev.tools/

For reference, a tiny homepage-like post I made for the Discourse: https://discourse.mozilla.org/t/getting-started-with-firefox-devtools

**Comment by irenesmith** [comment]
I agree. Community Information would be a welcome addition to the page.
Thanks.

**Comment by digitarald** [comment]
Looks great, this box would make the footer of devtools look consistently.

Let's prioritize the top tier panel docs work for 63, to ensure users coming through the new in-tools menu landed to have a streamlined experience. Right now 74% of users clicking through that menu don't go to a second page and only stay for ~10sec.

**Comment by Danieldavi** [comment]
I want to chat you do you can explain something for me

**Comment by irenesmith** [comment]
Sure, no problem. How did you want to connect?

**Comment by irenesmith** [comment]
Since I have received no negative comments on my outline, I am going to proceed with the first draft of the changed page.

**Comment by jmswisher** [comment]
Closing this on the assumption that if there were any feedback on the page, it would have been given by now.

**Comment by digitarald** [comment]
> Since I have received no negative comments on my outline, I am going to proceed with the first draft of the changed page.

I don't understand which feedback this refers to. No updates have been made to https://developer.mozilla.org/en-US/docs/Tools

**Comment by digitarald** [comment]
@irenesmith where do we track to clean up the above the fold content for https://developer.mozilla.org/en-US/docs/Tools ; removing the 2 empty paragraphs, move down the menu documentation and feature the core tools?
