### ISSUE TITLE
/en-US/docs/Web/CSS/opacity

### ISSUE THREAD

**Issue by redeyes2015** [mdn/sprints#3120]
# Request type

- [x] Correction or update

# Details

This page includes the information about percentage opacity values, but links to CSS Color 4, where percentage opacity values are defined, is not included.

* https://www.w3.org/TR/css-color-4/#transparency
* https://www.w3.org/TR/css-color-4/#typedef-alpha-value

**Comment by chrisdavidmills** [comment]
Added; thanks for reporting!
