### ISSUE TITLE
Accelerometer webAPI example error

### ISSUE THREAD

**Issue by Mkassabov** [mdn/sprints#3121]
# Request type
- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
In the example `event.acceleration.x` should be  `accelerometer.x` this follows true for y and z in the example as well. The data being read from the sensor is not contained in the event, it is contained in the Accelerometer object. Other sensors, such as the magnetometer, have correct documentation.

**Comment by chrisdavidmills** [comment]
@Mkassabov what page are you finding the problematic example on?

**Comment by Mkassabov** [comment]
@chrisdavidmills the accelerometer webAPI documentation page:
https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer

**Comment by chrisdavidmills** [comment]
Ah yes, what you are saying is correct, looking at the example at https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer#Example.

I've updates the code accordingly. Thanks for reporting this!

**Comment by Mkassabov** [comment]
@chrisdavidmills Your welcome!
P.S. You missed changing accelerometer to acl on the event listener.

**Comment by chrisdavidmills** [comment]
>  P.S. You missed changing accelerometer to acl on the event listener.

oops! Fixed that one too now ;-)
