### ISSUE TITLE
/it/docs/Learn/Server-side/Django/Models

### ISSUE THREAD

**Issue by scaluca** [mdn/sprints#3122]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
on the page linked " https://developer.mozilla.org/it/docs/Learn/Server-side/Django/Models " there is a translation error that makes the concept opposite to the truth, you have to change the article "al" with the article "il" also send screenshot of the paragraph.

# Image screen shot
![Err_of_translation](https://user-images.githubusercontent.com/50717870/79741948-640d7c00-8302-11ea-9c52-3e4a3e7e2650.JPG)

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortuntely, the MDN team doesn't update translations. If you like, create an account and correct the wiki page yourself.
