### ISSUE TITLE
Javascript affectation for arrays

### ISSUE THREAD

**Issue by Philo58** [mdn/sprints#3124]
Hello,
I discovered a strange behaviour or javascript : the affectation operator =, when used with an array, does not simply affects the value but the reference too.
I found this testing a program in which an array is duplicated with = before it is modified, and I did not want these changes to be transmitted with the original array that must stay as it is.
The code is like this : 

var copyArray = originalArray;
copyArray.push(newElement);

// from here, the original array was also pushed, not ontly the copyArray
// It seems that JS considers that copyArray and originalArray are the same variable
// which is very surprising for me and caused a difficult bug difficult to be understood

I think it would be useful to add a warning on this very unusual behaviour
In french : 
J'ai découvert un comportement étrange de javascript : l'opérateur d'affectation =, utilisé avec un tableau, ne se contente pas de transmettre la valeur mais la référence aussi.
J'ai trouvé cela en testant un programme où un tableau est recopié avec = avant des modifications, car je ne voulais pas que ces modifications soient intégrées au tableau original qui devait rester intact pour la suite du code.
Je pense qu'il serait utile d'ajouter un avertissement sur ce comportement très inhabituel.

**Comment by peterbe** [comment]
Do you have a particular URL that you're referring to?

**Comment by Philo58** [comment]
No, I found that  because a script I wrote was not behaving as I believed. To me, a=b in almost any langage means that a is a distinct entity from b. What happens to a should not touch b.

You can just try the following :
var tab1 = new Array(1,2,3);
var tab2 = tab1;
tab2.push(4);
alert (tab1); // which shows the table 1,2,3,4

To obtain a table distinct from the original one, I found I shoud use slice(). If the second line of my example is : 
var tab2 = tab2.slice();
Then, things return to normal for me ie : tab1 is 1,2,3 and tab 2 is 1,2,3,4

**Comment by peterbe** [comment]
Ah! That's how JavaScript is implemented in SpiderMonkey and V8. Arrays and objects are mutable. I can't explain why but I know it's a core fundamental thing. It's the same in Python by the way:
```
>>> tab1 = [1, 2, 3]
>>> tab2 = tab1
>>> tab2.append(4)
>>> tab1
[1, 2, 3, 4]
```
That's because tab2 (in either language) is a reference, not a complete deep clone.
