### ISSUE TITLE
/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

### ISSUE THREAD

**Issue by Ivany95** [mdn/sprints#3127]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Dear Sirs,

I am Ivany Mateus (a MDN articles reader) and I would like to report a content issue.
In "Learn web development" area, more especific in the "HTML - Estruturing the web" module: "HTML - Forms" I have seen some errors between the articles and the articles list of the module (upper left list on the page). In some cases the respective article aren't in the list and in other cases when using the "next" button (button on the start and end of the article) dosen't follow the list, and also one time the "HTML - Forms" module just was not there.

My best regards.

P.s.: I'm sorry about the english errors, I do not speak fluent english.

**Comment by chrisdavidmills** [comment]
Hi @Ivany95 !

Sorry for the problems here. The next/previous links at the top of each article go to the right places.

And the lists at the end of each article are correct, for example https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form#In_this_module

But the left hand sidebar is currently wrong. IT should be updated soon!
