### ISSUE TITLE
U - As a user I want to be able to opt into MDN marketing emails (during account creation and later) so that I can find out about MDN related news

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#3128]
# User story
U - As a user I want to be able to opt into MDN marketing emails (during account creation and later) so that I can find out about MDN related news

# Acceptance criteria
- [x] People can subscribe during account creation
- [x] People can subscribe after account creations
- [x] People can unsubscribe
- [x] UX is approved by legal

**Comment by chinikes** [comment]
Hi @malqinneh - Can you create a task under this user story for the task you'll be working on in foxtrott instead?

**Comment by chinikes** [comment]
@atopal, @tobinmori - With all technical steps completed, can we confirm the acceptance criteria are met at this point? Is this story good to be done?

**Comment by atopal** [comment]
Yes, I think we can call this done.
