### ISSUE TITLE
Typo in /en-US/docs/Web/HTML/Element/title

### ISSUE THREAD

**Issue by Ists-Cilveks** [mdn/sprints#3129]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title has a typo under "Example". The text is 

> This example establishes a page whose title (as displayed at the top of the window or in the window's tab) as "Awesome interesting stuff").

but should be something like 

> This example establishes a page whose title (as displayed at the top of the window or in the window's tab) is "Awesome interesting stuff".

**Comment by Elchi3** [comment]
Fixed
