### ISSUE TITLE
/en-US/docs/Web/Tutorials

### ISSUE THREAD

**Issue by spencermathews** [mdn/sprints#3132]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The information under Introductory Level CSS Tutorials on https://developer.mozilla.org/en-US/docs/Web/Tutorials is outdated and not current with https://developer.mozilla.org/en-US/docs/Web/CSS and https://developer.mozilla.org/en-US/docs/Learn/CSS.

Namely, the **Introduction to CSS** link should be updated to **CSS first steps**, and **Styling boxes** should be updated to **CSS building blocks**. Both links currently redirect to the new modules but it would help avoid confusion to be consistent across the site. I considered making the edits myself but wasn't sure if the descriptions on the Tutorials page are intentionally different than the more current pages mentioned above, or if it should be copied over from them.

**Comment by chrisdavidmills** [comment]
Yup, this needed updating. Thanks for reporting this; I've sorted it out.
