### ISSUE TITLE
Document the ability to disable pausing button

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#314]
*This is a placeholder for a proper description and user story for the new feature. Need more information before I can write it properly.*

## Acceptance Criteria
- [ ] Documentation has been added to the appropriate content page
- [ ] Changes reviewed and approved by the DevTools team

**Comment by jmswisher** [comment]
What's the status of this issue? Was it completed, or abandoned?

**Comment by chrisdavidmills** [comment]
@irenesmith what's the status here? Can this be closed?

**Comment by irenesmith** [comment]
The document has been updated to describe how to temporarily disable breakpoints. There is no equivalent to the disable pausing.
