### ISSUE TITLE
Correct compat data and/or merge pagehide/pageshow/PageTransitionEvent

### ISSUE THREAD

**Issue by gijsk** [mdn/sprints#3141]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
There are three docs pages:

https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event
https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent

The pagehide/pageshow events are page transition events, and specced as such ( https://html.spec.whatwg.org/multipage/browsing-the-web.html#the-pagetransitionevent-interface ; https://html.spec.whatwg.org/multipage/indices.html#event-pagehide ; https://html.spec.whatwg.org/multipage/indices.html#event-pageshow ) and the page transition event page and its corresponding caniuse.com entry have correct compat data.

However, the pagehide/pageshow pages do not have correct compat data, and neither do their caniuse.com counterparts.

There are no links from the PageTransitionEvent page back to pagehide/pageshow.

The pagehide/pageshow ones look older and like they should be updated to match the PageTransitionEvent page, instead of having their own compat data, and it should be easy to see how the 3 pages relate (if indeed they stay as 3 separate pages).

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @gijsk . To help here, I've done some updates to the pages to make them more useful (e.g. cross linking, improving code examples), and updated the compat data for the event pages so it matches the event object data (see https://github.com/mdn/browser-compat-data/pull/6187)

Let me know if there's anything else you'd like to see here.
