### ISSUE TITLE
/pt-BR/docs/Web/HTTP/Status

### ISSUE THREAD

**Issue by hjxkyw** [mdn/sprints#3142]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Grammatical error in the Portuguese translation: In response code "504", where it's written "à tempo" should be "a tempo", without the accented "a" ("á")

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately the MDN team doesn't update translations. It is a community effort. Feel free to update the wiki page.
