### ISSUE TITLE
The "Upgrade" link has proper page to go

### ISSUE THREAD

**Issue by Thor-x86** [mdn/sprints#3147]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On [this documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers), there is an "Upgrade" labeled link which is informs us that the page is unavailable yet. However, I found [appropriate page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism) for the link.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. I've added a link to the guide page separately after the red reference page link, as we'd like to try to get that page created too, eventually. Leave the red link there can help as a reminder ;-)
