### ISSUE TITLE
Low accuracy Math.log1p polyfill

### ISSUE THREAD

**Issue by edgar-bonet** [mdn/sprints#3148]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This is similar to issue #3146 about `Math.expm1()`.

The [MDN documentation of `Math.log1p()`][log1p] contains this section:

> ## Polyfill
>
> This can be emulated with the following function:
>
> ```javascript
> Math.log1p = Math.log1p || function(x) {
>   return Math.log(1 + x);
> };
> ```

As explained in the documentation page itself, this suffers loss of accuracy when |x| is very small. Since the whole purpose of `Math.log1p()` is to provide decent accuracy even for very small |x|, I suggest using a better approximation.

I experimentally found that a 4<sup>th</sup> order Taylor polynomial is better than the direct formula below about 8.8×10<sup>−4</sup>:

```javascript
Math.log1p = Math.log1p || function(x) {
  return Math.abs(x) < 8.8e-4 ? x*(1 - x*(1/2 - x*(1/3 - x/4))) :
         Math.log(1 + x);
};
```

[log1p]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log1p

**Comment by chrisdavidmills** [comment]
I've removed the polyfill from the page source. We decided a long time ago that we were no longer carrying polyfills on MDN.
