### ISSUE TITLE
/en-US/docs/Learn/Performance/CSS

### ISSUE THREAD

**Issue by RolandSzaboDesign** [mdn/sprints#3154]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS
First paragraph:
"Browsers follow a specific rendering path: paint only occurs after layout, which occurs after the render tree is created, _[with]_ **which** requires both the DOM and the CSSOM trees."

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
