### ISSUE TITLE
/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

### ISSUE THREAD

**Issue by wangxiaoyao** [mdn/sprints#3156]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ✔️] Correction or update

# Details

URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Object.defineProperty()  has the “configurable”  property 。 its default is  "true"  but  on this page it write "false"。

**Comment by Elchi3** [comment]
configurable: false as written in the doc is correct
