### ISSUE TITLE
Missing Page - ES Stage 3 Firefox Nightly's Feature - Logical Assignment Operator

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/sprints#3160]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

ES Stage 3, Firefox Nightly Feature: Logical Assignment Operator in Firefox

```JavaScript
let a;
a ||= "";
console.log(a)
``` 
return "" in FF Nightly

this is a new feature in ES

https://github.com/tc39/proposal-logical-assignment
<img width="130" alt="Firefox Nightly" src="https://user-images.githubusercontent.com/41184947/80299534-be598180-87c7-11ea-9ec6-8dc9834296c3.png">

**Comment by PassionPenguin** [comment]
https://tc39.es/proposal-logical-assignment/

**Comment by PassionPenguin** [comment]
https://github.com/tc39/proposal-logical-assignment#status

**Comment by chrisdavidmills** [comment]
Thanks for the note. We already have this scheduled to be documented when it apears in Firefox (version 77) — see our roadmap here: https://trello.com/c/qaDzhO1m/262-logical-assignment-operators-fx-77.

This will happen next month.
