### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter$history

### ISSUE THREAD

**Issue by taiwoayanleye** [mdn/sprints#3161]
# Request type

- [x] Correction or update

# Details

There's a grammatical glitch here "...(they should be 10 to the power **or** 3 and 4, respectively)..." . It should be "to the power **of**" and not "to the power **or**".

[URL of the page](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter)

**Comment by chrisdavidmills** [comment]
fixed; thanks for reporting!
