### ISSUE TITLE
Create Document.rootElement

### ISSUE THREAD

**Issue by lucaswerkmeister** [mdn/sprints#3162]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

SVG2 extends the `Document` interface with a `rootElement` attribute in [§ 5.13.1. Extensions to the Document interface](https://svgwg.org/svg2-draft/struct.html#InterfaceDocumentExtensions). I tried to create documentation for it (it’s deprecated in favor of `documentElement`, but still implemented in modern browsers), but I don’t have permission to create a new page.

https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document/rootElement → https://wiki.developer.mozilla.org/en-US/docs/new?parent=612&slug=rootElement

**Comment by chrisdavidmills** [comment]
@lucaswerkmeister what is your MDN account name? I can give you that permission, if you like.

**Comment by lucaswerkmeister** [comment]
That would be great, thanks! It’s [lucaswerkmeister](https://developer.mozilla.org/en-US/profiles/lucaswerkmeister) :)

**Comment by chrisdavidmills** [comment]
@lucaswerkmeister thanks! You should now have the permissions you need to create the page. Let me know if you want a review.

**Comment by lucaswerkmeister** [comment]
Hm, I still get a permission error on that page… (I also tried logging out and back in, doesn’t seem to have made a difference.)

**Comment by chrisdavidmills** [comment]
@lucaswerkmeister oops, looks like I didn't save the permission updates properly. Try again and let me know if it is OK now ;-)

**Comment by lucaswerkmeister** [comment]
Now it’s working, yes :) I hope I can properly write the page this evening!

**Comment by lucaswerkmeister** [comment]
Alright, I created [Document.rootElement](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document/rootElement) and linked it at [Document § Deprecated properties](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document#Deprecated_properties). Thanks!
