### ISSUE TITLE
/en-US/docs/Web/HTML/Element/input

### ISSUE THREAD

**Issue by jkshapiro** [mdn/sprints#3163]
# Request type
- [X] Correction or update

# Details
On the page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input, in the section on `inputmode`, should the value "none" be styled the same as the other values, i.e. "text", "tel", "url", etc.?

Also, in the section on `size`, should the value "text" be styled the same as the other values i.e.  "email", "password" and "tel"?

**Comment by chrisdavidmills** [comment]
Yup; I've fixed them now; thanks for reporting.
