### ISSUE TITLE
/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

### ISSUE THREAD

**Issue by s427** [mdn/sprints#3165]
# Request type
Correction or update

# Details
The "[Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)" page gives "text/javascript" as the value that should be served for JavaScript content. However the [official IANA registry](http://www.iana.org/assignments/media-types/media-types.xhtml#text) (linked at the beginning of the article) states that this is obsolete and that "application/javascript" should be preferred.

**Comment by chrisdavidmills** [comment]
Updated; thanks for reporting!

**Comment by sideshowbarker** [comment]
I reverted the change after discussion with @chrisdavidmills 

`text/javascript` isn’t obsolete. This is just a case where the IANA registry isn’t up to date with the relevant specs.

https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/
> current implementations should use text/javascript as the only JavaScript/ECMAScript media type

https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages
> Servers should use `text/javascript` for JavaScript resources. Servers should not use other JavaScript MIME types for JavaScript resources, and must not use non-JavaScript MIME types

https://html.spec.whatwg.org/multipage/infrastructure.html#dependencies:willful-violation
> the MIME type used to refer to JavaScript in this specification is `text/javascript`, since that is the most commonly used type, despite it being an officially obsoleted type according to RFC 4329
