### ISSUE TITLE
E - Refresh existing security docs

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3167]
# Epic 
Refresh existing docs

# Acceptance criteria
- [ ]

**Comment by jmswisher** [comment]
@chinikes @Elchi3 How is this different from #3227 ? This issue seems like it should be closed, since it has no content.

**Comment by Elchi3** [comment]
No idea, was probably an earlier placeholder.
Closing as duplicate of https://github.com/mdn/sprints/issues/3227
