### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript$history

### ISSUE THREAD

**Issue by taiwoayanleye** [mdn/sprints#3169]
# Request type
- [x] Correction or update

# Details

There's a grammatical glitch in the first sentence of the **Browser Security** section. It should be "Each browser tab **has** its own separate bucket..." and not "Each browser tab **is** its own separate bucket...". 

[URL to the page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting this!

**Comment by digitalforus** [comment]
Wow! I really love this. Can you mentor me on how to contribute to open source as a Designer | Developer | Writer @taiwoayanleye
