### ISSUE TITLE
Document RTCAnswerOptions

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#317]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399757

## Acceptance criteria
- [x] `RTCAnswerOptions` page written and complete
- [x] All members of `RTCAnswerOptions` documented
- [x] BCD updates submitted
- [x] BCD updates approved and merged
- [x] Changes submitted for review by media team

**Comment by a2sheppy** [comment]
I've actually also documented as part of this `RTCOfferAnswerOptions` and `RTCOfferOptions` and their members, and  the BCD PR includes those.

The BCD PR has been submitted: https://github.com/mdn/browser-compat-data/pull/2730

**Comment by a2sheppy** [comment]
While I was at it, I also finished updating the docs for ICE restarts, which was never finished back when it landed.

**Comment by chrisdavidmills** [comment]
Nice work sheppy. For ICE restarts, I'm assuming you mean the stuff at https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ICE_restart?

It'd be lovely to see the rest of that page completed soon. Do you think you can slot that in during the next couple of sprints, or are there other higher priority bits to do for WebRTC?

**Comment by a2sheppy** [comment]
I can do that if you like. It's a worthwhile goal.

**Comment by chrisdavidmills** [comment]
Cool; slot it in where it makes sense.
