### ISSUE TITLE
Error in max() documentation

### ISSUE THREAD

**Issue by timprint** [mdn/sprints#3172]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Ther is an error on the the css max() documentation page
[https://developer.mozilla.org/en-US/docs/Web/CSS/max](https://developer.mozilla.org/en-US/docs/Web/CSS/max)

`width: max(20vw, 400px); `

> In the first above example, the width will be at least 400px, but will be wider if the viewport is more than 800px wide.

800px should say 2000px

20vw of an 800px wide viewport is 160px not 400px.

**Comment by chrisdavidmills** [comment]
Thanks for pointing this out! I've fixed it now.

**Comment by gidansau69** [comment]
вт, 28 апр. 2020 г., 13:26 Chris Mills <notifications@github.com>:
