### ISSUE TITLE
 Test your skills: Strings 1

### ISSUE THREAD

**Issue by RisingThunder** [mdn/sprints#3173]
# Request type

- [x] Correction or update
# Details
Reference: 
[Test your skills: Strings 1](https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings#Strings_1) & [Download the starting point for this task](https://github.com/mdn/learning-area/blob/master/javascript/introduction-to-js-1/tasks/strings/strings1-download.html).
Sub-objective 2 of this task is for the student is to;

> Concatenate the two strings together to make a single string containing the complete quote. Save the result inside a variable called finalQuote.

However, if the student uses the linked downloadable version of this task to work with in the students code editor of choice, this line of code is already there! Which kinda defeats the purpose of objective 2 to test the student, so to speak.
_It is not in the interactive editor._
`let finalQuote = quoteStart + quoteEnd;`

**Comment by chrisdavidmills** [comment]
Oooops!

Yes, this is a problem. I've fixed it now — thanks for reporting it!
