### ISSUE TITLE
Error in CORS documentation

### ISSUE THREAD

**Issue by andoks** [mdn/sprints#3174]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[Image](https://mdn.mozillademos.org/files/14293/simple_req.png) refers to origin in request headers being "Server-b.com", but the text around it is referring to it as "foo.example".

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. There were a couple of images with the same problem — I've updated them both so that they now say `foo.example` rather than `Server-b.com`
