### ISSUE TITLE
/en-US/docs/Web/Media/Formats/Video_codecs

### ISSUE THREAD

**Issue by swpalmer** [mdn/sprints#3175]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
In the AVC section there is a part in the browser compatibility table where it is referred to as AVC/H.265 instead of AVC/H.264.

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#AVC_H.264

**Comment by chrisdavidmills** [comment]
Pretty sure this got fixed.
