### ISSUE TITLE
Navigation Timing API doesn't include any description of units

### ISSUE THREAD

**Issue by glyph** [mdn/sprints#3176]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The navigation timing API talks about numbers, but it doesn't ever say what they are.  Minutes? Femtoseconds? Weeks maybe?  Also, are they epoch timestamps or are they performance counters?  Monotonic time or wall-clock?  It would be helpful to know these things.

https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API

**Comment by chrisdavidmills** [comment]
When you drill down to the individual property pages, such as https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/navigationStart, it tells you that values are given are millisecond unix epoch timestamps. But I agree it could be clearer at this level? What do you think? Would a short note on the main API page suffice?

**Comment by jchimene** [comment]
@chrisdavidmills I think this can be closed by https://github.com/mdn/content/pull/841
