### ISSUE TITLE
Window.innerHeight Graphical example is not correct

### ISSUE THREAD

**Issue by ychong** [mdn/sprints#3177]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Window.innerHeight documentation of the Graphical example might not be correct (https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight). The Window.innerHeight think it should be equal to the height of the scroll bar, not the Window itself or offsetHeight. Tried this in my Python program.

**Comment by chrisdavidmills** [comment]
I think the graphic as it stands is correct — `window.innerHeight` is the height of the viewport, and the value stays the same regardless of whether it contains scroll bars or not.

I wrote a quick example to test this:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>outerHeight and innerHeight test</title>
    <style>
      div {
        width: 1000px;
        height: 500px;
        background-color: red;
      }
    </style>
  </head>
  <body>
    <div>
    </div>
    <script>
      const divElem = document.querySelector('div');
      window.onresize = logHeights;
      function logHeights() {
        console.log(`outerHeight is ${window.outerHeight}, innerHeight is ${window.innerHeight}.`);
      }
    </script>
  </body>
</html>
```
