### ISSUE TITLE
CSS <color> page has no compatibility information for different color syntaxes

### ISSUE THREAD

**Issue by fvsch** [mdn/sprints#3178]
## Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

## Details

I was trying to find information on the browser support for comma-less `rgb()` and `hsl()` syntaxes, which are described on this page:
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

The page has a compatibility table for a feature named `color`, and the feature name links to this page:
https://developer.mozilla.org/en-US/docs/Web/CSS/color
which seems to have the exact same compatibility table

It looks like `mdn/browser-compat-data` does have the information I'm looking for, and it can be found with a careful search on Can I Use:
https://caniuse.com/#feat=mdn-css_types_color_space_separated_functional_notation

Should https://developer.mozilla.org/en-US/docs/Web/CSS/color_value have compatibility rows for each feature in https://github.com/mdn/browser-compat-data/blob/master/css/types/color.json ?

I'm seeing the following features:

- `css.types.color` (`<color>`)
- `css.types.color.alpha`
- `css.types.color.alpha_hexadecimal_notation`
- `css.types.color.currentcolor`
- `css.types.color.floats_in_rgb_rgba`
- `css.types.color.hsl`
- `css.types.color.hsl_function_accepts_alpha`
- `css.types.color.keyword_color_values`
- `css.types.color.rebeccapurple`
- `css.types.color.rgb_function_accepts_alpha`
- `css.types.color.rgb_functional_notation`
- `css.types.color.rgb_hexadecimal_notation`
- `css.types.color.space_separated_functional_notation`
- `css.types.color.transparent`

I would expect a table with a row for each feature.
Does that sound sensible?

**Comment by chrisdavidmills** [comment]
This is a good point — the information in the `types.color` BCD is a lot more useful than the information in  `properties.color`. I've updated the macro calls to change the dataset shown on these two pages to the former. Does this fix the problem?

**Comment by fvsch** [comment]
Yes, it's the fix I had in mind :)
Thanks for the update.
