### ISSUE TITLE
/en-US/docs/Web/HTML/Element/input/checkbox

### ISSUE THREAD

**Issue by sakthivelsekar33** [mdn/sprints#3179]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
as per the docs, for input type checkbox with readonly attribute enabled, should show background and border with grey color if unchecked, but this is not happening and the background is still the same white.

reference - https://jsbin.com/vagadik/edit?html,output

**Comment by chrisdavidmills** [comment]
This is because `<input type="checkbox">` does not support the readonly attribute. The spec says this pretty clearly. So....I don't know how we ended up saying it does ;-)

Thanks for reporting this error — I've removed the parts about readonly form the checkbox page!
