### ISSUE TITLE
/fr/docs/Web/HTTP/Headers/Referer

### ISSUE THREAD

**Issue by vlrmt** [mdn/sprints#3180]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Extrait de la page https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Referer :
"_ce qui peut présenter des problèmes de confidentialité**s**._"
-> "confidentialité" devrait s'écrire au singulier (on ne parle pas ici "**des** confidentialité**s**", mais "**de** confidentialité").

**Comment by SphinxKnight** [comment]
Bonjour @vlrmt, j'ai corrigé en reprenant la traduction dans son intégralité.
Toutefois, n'hésitez pas à corriger les coquilles que vous pourriez rencontrer comme celle-ci. Chacun peut contribuer à MDN :)

Merci en tout cas pour le rapport.
-----
Hello, I've updated the whole page.
Do not hesitate to edit the page for such minor typos, MDN is a wiki anyone can edit.

Thanks for the report.

**Comment by vlrmt** [comment]
> Toutefois, n'hésitez pas à corriger les coquilles que vous pourriez rencontrer comme celle-ci. Chacun peut contribuer à MDN :)
> Do not hesitate to edit the page for such minor typos, MDN is a wiki anyone can edit.

Thanks a lot for your quick fix! And sure I will do it on my own in the future, I just didn't know it was possible :)

MDN account now "created" (too bad the only way to authenticate to MDN is an external identity... belonging either to Microsoft or Google - aka my dear "friends". I would have expected more autonomy from Mozilla - but that's another story).
