### ISSUE TITLE
/ja/docs/Glossary/Public-key_cryptography

### ISSUE THREAD

**Issue by kazutaka-matsuzaki** [mdn/sprints#3181]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/ja/docs/Glossary/Public-key_cryptography
"懸賞" in the second paragraph should be updated to "検証".

**Comment by sideshowbarker** [comment]
Yes, thanks — fixed
