### ISSUE TITLE
/en-US/docs/Web/API/Window/devicePixelRatio: canvas.width/height should be integer

### ISSUE THREAD

**Issue by belm0** [mdn/sprints#3182]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the `devicePixelRatio` example, devicePixelRation can be fractional, while canvas.width/height are required to be integer.  So truncation is necessary.

Suggestion:
```
canvas.width = canvas.height = Math.floor(size * scale);
```

**Comment by chrisdavidmills** [comment]
Good spot, thanks for pointing this out. I've updated the code.
