### ISSUE TITLE
/en-US/docs/Web/CSS/border-style

### ISSUE THREAD

**Issue by AvinashSoorineedi** [mdn/sprints#3186]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I think the vertical and horizontal are not used properly for the border-style syntax.

/* vertical | horizontal */
border-style: dotted solid;

/* top | horizontal | bottom */
border-style: hidden double dashed;

https://developer.mozilla.org/en-US/docs/Web/CSS/border-style#Syntax

**Comment by chrisdavidmills** [comment]
These look correct to me. Are you concerned that the orientation of the broders doesn't seem to match up to the words being used? For example, `horizontal` is used, but the solid borders are pointing vertically?

This has to do with the block/inline nature of the sides being styled. It makes sense in terms of CSS terminology. The `horizontal` borders are the borders that exist in an inline direction, e.g. `left` and `right`, or `inline-start` and `inline-end` in the case of logical equivalents.

However, this only works when the writing mode is set to a horizontal language. When it is set to `tb` (top to bottom), as it would be for a language like Japanese, then the solid borders would be on the top and bottom instead. 

So maybe this does need revisiting?

**Comment by rachelandrew** [comment]
@chrisdavidmills they were the wrong way round in the code comments. This property is also only physical, because the WG haven't decided what to do about the four value shorthands in a logical world. 

The details below were correct. I've changed the code comments to refer to top and bottom, left and right as that's what the spec uses.

Per spec: 

> "If there are two values, the top and bottom are set to the first value and the right and left are set to the second. If there are three values, the top is set to the first value, the left and right are set to the second, and the bottom is set to the third. If there are four values they apply to the top, right, bottom, and left, respectively."

**Comment by chrisdavidmills** [comment]
@rachelandrew ah yes, I get it now ;-)

Fix looks good, thanks Rachel. I'll close this now.
