### ISSUE TITLE
[HTML] form inputs, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3187]
# Trello

https://trello.com/c/KZ1QBGnm/30-form-input-element-improvements-fx-77

# Acceptance criteria

1. - [x] [LABELs don't work for OPTIONs (<option label> in selects) (standards mode only!)](https://bugzilla.mozilla.org/show_bug.cgi?id=40545)

**Comment by jmswisher** [comment]
[BCD PR](https://github.com/mdn/browser-compat-data/pull/6140)

**Comment by Elchi3** [comment]
This is mentioned on the release notes https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77 and the compat data has been updated on https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/option#Browser_compatibility

@jmswisher can you set the bug to dev-doc-complete and close this issue?

**Comment by jmswisher** [comment]
Done.
