### ISSUE TITLE
[HTML] iframes, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3188]
# Trello

https://trello.com/c/rUonlSLg/190-html-iframe-element-fx-77

# Acceptance criteria

1. - [x] [Remove support for <iframe mozbrowser> in content](https://bugzilla.mozilla.org/show_bug.cgi?id=1614462)

**Comment by jmswisher** [comment]
[BCD PR](https://github.com/mdn/browser-compat-data/pull/6149) -- removes the feature entirely

**Comment by Elchi3** [comment]
@jmswisher can we set dev-doc-complete on the bugzilla bug now and close this issue?

**Comment by jmswisher** [comment]
Done
