### ISSUE TITLE
[SVG] Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3189]
# Trello

https://trello.com/c/tKOmHAzq/264-svg-markup-related-bugs-fx-77

# Acceptance criteria

1. - [x] [add a presentation attribute for transform-origin](https://bugzilla.mozilla.org/show_bug.cgi?id=1581691)

**Comment by jmswisher** [comment]
Upping the estimate, since transform-origin is not documented, and so needs a page from scratch.

**Comment by jmswisher** [comment]
Added reference article for [SVG transform-origin](https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin). Added links to it from [SVG Attributes index page](https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Attribute).

**Comment by Elchi3** [comment]
Looks done to me. Also appears on the release notes: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#SVG
