### ISSUE TITLE
[CSS] Selectors, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3190]
# Trello

https://trello.com/c/ZHrUvxzS/29-selectors-fx-77

# Acceptance criteria

1. - [x] [Implement `:is()` and `:where()` selectors](https://bugzilla.mozilla.org/show_bug.cgi?id=1509418) (see also [intent to ship](https://groups.google.com/forum/#!topic/mozilla.dev.platform/_f8gYPevIQw); also, this may be behind a flag for now; see below bug)
2. - [x] [Enable :is() / :where() on all release channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1632646)

**Comment by chrisdavidmills** [comment]
Actions taken here:

* :where() page completed — https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:where. Example added, and page cleaned up.
* :is() page updated, to link to example on :where() that explains the difference: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:is#Difference_between_is_and_where
* Entry added to Experimental features pages: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#CSS
* PR added, for BCD update: https://github.com/mdn/browser-compat-data/pull/6179
* No rel note for now, as it is not enabled in release yet.

**Comment by Elchi3** [comment]
Thanks Chris! 
We will have a new story on this for https://bugzilla.mozilla.org/show_bug.cgi?id=1632646 so that we can talk about it in the Firefox 78 cycle.
