### ISSUE TITLE
[JS] Strings, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3191]
# Trello

https://trello.com/c/66fGk6Xm/167-js-strings-fx-77

# Acceptance criteria

1. - [ ] [Ship String.prototype.replaceAll](https://bugzilla.mozilla.org/show_bug.cgi?id=1608168)
2. - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1540021

**Comment by Elchi3** [comment]
Added to https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#JavaScript
New page: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
BCD was already contributed by amazing contributors.
Interactive example is in progress: https://github.com/mdn/interactive-examples/pull/1592
