### ISSUE TITLE
[JS] Logical assignment operators, Fx 79 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3192]
# Trello

https://trello.com/c/qaDzhO1m/262-logical-assignment-operators-fx-77

# Acceptance criteria

1. - [ ] [Implement Logical Assignment Operators proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1629106) (Nightly only for now; up to you if you want document it or not)
2. - [ ] [Ship logical assignment operators (??=)](https://bugzilla.mozilla.org/show_bug.cgi?id=1639591)

**Comment by Elchi3** [comment]
This is currently targeted for Firefox 78, so I'm moving it to the next sprint given we need more time for the sprint goal (JS content linting).

**Comment by Elchi3** [comment]
Ships in 79, see https://bugzilla.mozilla.org/show_bug.cgi?id=1639591. Moving to next sprint.

**Comment by Elchi3** [comment]
Updated: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#Table
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators

New pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment

Compat data:
https://github.com/mdn/browser-compat-data/pull/6363

Fx79 release notes announcement:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#JavaScript

Working on adding the spec to kumascript and adding interactive examples still.

**Comment by Elchi3** [comment]
Kumascript spec update: https://github.com/mdn/kumascript/pull/1404

**Comment by Elchi3** [comment]
Interactive examples: https://github.com/mdn/interactive-examples/pull/1621

**Comment by Elchi3** [comment]
All done now
