### ISSUE TITLE
[WebAPI] Disable AppCache

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3193]
# Trello

https://trello.com/c/ZLnhgfj6/32-service-worker-api-fx-77

# Acceptance criteria

1. - [ ] [Disable appcache in release](https://bugzilla.mozilla.org/show_bug.cgi?id=1619673) (target 77, also affects the below bug too; however, browser engineering trello boards reckons this may be delayed beyond 77.)

**Comment by Elchi3** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1633567 
"We decided to postpone the disabling of AppCache to Firefox 79. This bug is to re-enabled it in 77.

I've added ddn to https://bugzilla.mozilla.org/show_bug.cgi?id=1619673

I propose we move this out of the sprint.
