### ISSUE TITLE
[a11y] ARIA reflection, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3194]
# Trello

https://trello.com/c/dPuGIYZw/265-aria-reflection-fx-77

# Acceptance criteria

1. - [ ] [implement ARIA reflection](https://bugzilla.mozilla.org/show_bug.cgi?id=1628418)

**Comment by Elchi3** [comment]
This is not actually currently enabled for Firefox 77. Not sure if it will make it
https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#193

**Comment by Elchi3** [comment]
Confirmed by Asa to not ride the trains. Closing. Will come back to this at a later point.
