### ISSUE TITLE
Re-render pages for fresh compat data (May 2020 edition)

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3196]
Please re-render all pages with the compat macro, so that users see the latest data.

cc @escattone

Previously: https://github.com/mdn/sprints/issues/3024

**Comment by escattone** [comment]
### Summary
I run [this gist](https://gist.github.com/escattone/2f1a27a16ebd4233b0f1197a58eb9c0a) within a `./manage.py shell_plus` on a celery-worker pod, and scale-up the **api** and **kumascript** pods to six (6) pods each (`kc scale --replicas=6 deploy api kumascript`) before I make the run. It usually takes about 1-2 hours to render about 20K documents.

### Acceptance Criteria
- [ ] All documents that use the `compat` macro have been successfully re-rendered on prod

**Comment by escattone** [comment]
I re-rendered 21,375 documents that contain the `compat` macro in about 72 minutes.
