### ISSUE TITLE
[WebExt] General WebAPIs, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3197]
# Trello

https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-77

# Acceptance criteria

1. - [x] [Implement permissions API events](https://bugzilla.mozilla.org/show_bug.cgi?id=1444294)
2. - [x] [Make proxy an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1548011)
3. - [x] [make sessions an optionalPermission](https://bugzilla.mozilla.org/show_bug.cgi?id=1630414)
4. - [x] [make browsingData an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1630417)
5. - [x] [make pkcs11 an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1630418)
6. - [x] [Allow WebExtensions to clear IndexedDB by hostname](https://bugzilla.mozilla.org/show_bug.cgi?id=1551301)
7. - [x] [Allow WebExtensions to clear ServiceWorkers by hostname](https://bugzilla.mozilla.org/show_bug.cgi?id=1632990)
8. - [x] [support merging content-security-policy headers provided by multiple extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1462989)
9. - [x] [Add the ability to duplicate tab to a specified index](https://bugzilla.mozilla.org/show_bug.cgi?id=1560218)
10. - [x] [network.cookie.sameSite.laxByDefault breaks my add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1629436)
11. - [x] [support tabs.goForward and tabs.goBack](https://bugzilla.mozilla.org/show_bug.cgi?id=1603796)

**Comment by rebloor** [comment]
A PR has been raised for the changes in optional permissions (browsingData, pkcs11, proxy, and sessions) in the compatibility data ([6112](https://github.com/mdn/browser-compat-data/pull/6112)) and details added to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#Manifest_changes).

**Comment by rebloor** [comment]
A PR has been raised for updates to Extension Workshop for the optional permission changes, see PR[636](https://github.com/mozilla/extension-workshop/pull/636). Developer review has been requested on Bugzilla.

**Comment by rebloor** [comment]
Shane responded to needinfo request regarding permissions to be made optional. These changes are now complete.

**Comment by rebloor** [comment]
For **Implement permissions API events**: these 2 events are documented already in ([onAdded](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/onAdded) and  [onRemoved](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/onRemoved)). Therefore the changes made are:
* added details to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#API_changes)
* amending the compatibility data, submitted in [PR 6131](https://github.com/mdn/browser-compat-data/pull/6131)

A needinfo request has been made on the bug to confirm the changes are complete.

**Comment by rebloor** [comment]
For **Allow WebExtensions to clear IndexedDB by hostname** and **Allow WebExtensions to clear ServiceWorkers by hostname**,  [https://wiki.developer.mozilla.org/en-US/profiles/evilpie]( URL)evilpie has updated the release notes. I've sent a needinfo to confirm whether he's also updating the compatibility data, if indeed we believe it needs to be updated (showing 57 and 53 for the 2 values at the moment).

**Comment by rebloor** [comment]
@chrisdavidmills I'm wondering if we need any changes to the compatibility data for **Allow WebExtensions to clear IndexedDB by hostname** and **Allow WebExtensions to clear ServiceWorkers by hostname**. Reading [browsingData.remove()](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove) it seems to imply that all values of `removalOptions` (where you define hostnames) apply to all `dataTypes` (where you would define IndexedDB or ServiceWorkers). This suggests that the 2 changes now mean the API "works as documented" and no further changes, beyond the release notes, are needed. Agree?

**Comment by chrisdavidmills** [comment]
@rebloor yeah, I think this makes sense. The info obviously needs to be made more granular.

**Comment by rebloor** [comment]
Thanks @chrisdavidmills those are done then  :-)

**Comment by rebloor** [comment]
For **support merging content-security-policy headers provided by multiple extensions**  details have been added to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#API_changes) and [webRequest.onHeadersReceived](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived)  updated with the version of the suggested text. A confirmation request moreinfo be made on the bug.

In addition, clarification has been has been sought on the noted in [webRequest.onHeadersReceived](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived) "From Firefox 52 onwards, instead of returning BlockingResponse, the listener can return a Promise that is resolved with a BlockingResponse. This enables the listener to process the request asynchronously.'  as there doesn't seem to be a way of switching the listener between returning a promise and standard call back.

**Comment by Elchi3** [comment]
I've added a task here "[Add the ability to duplicate tab to a specified index](https://bugzilla.mozilla.org/show_bug.cgi?id=1560218)" which has dev-doc-needed set and seems to also ship in Firefox 77.

**Comment by rebloor** [comment]
For **Add the ability to duplicate tab to a specified index** compatibility data changes have been requested in [6164](https://github.com/mdn/browser-compat-data/pull/6164)

**Comment by rebloor** [comment]
For **Implement permissions API events** completed incidental changes, as recommended by Rob, now complete.

**Comment by rebloor** [comment]
For **Add the ability to duplicate tab to a specified index** documentation changes have now been made:
* compatibility data changes submitted in [PR  #6164](https://github.com/mdn/browser-compat-data/pull/6164)
* [tabs.duplicate](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/duplicate) parameter details updated
* item added to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#API_changes)

Confirmation of changes requested by a needinfo on the bug.

**Comment by rebloor** [comment]
For **Add the ability to duplicate tab to a specified index** documentation changes have now been reviewed and OKed.

**Comment by rebloor** [comment]
For **support merging content-security-policy headers provided by multiple extensions** completing changes in line with suggestion from developers.

**Comment by rebloor** [comment]
@Elchi3 @chrisdavidmills [network.cookie.sameSite.laxByDefault breaks my add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1629436) doesn't look like a Web Extensions API change, although the effect is on Web Extensions (so at least probably needs mentioning in the Web Extensions section of the release notes). Should this be moved elsewhere?

**Comment by rebloor** [comment]
For **support tabs.goForward and tabs.goBack** the following documentation has been updated:
* compatibility data, changes submitted in [6173](https://github.com/mdn/browser-compat-data/pull/6173)
* details added to the [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#API_changes)
* pages for [goForward](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/goForward) and [goBack](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/goBack) added. However, additional information sought from the developer as follows:
  * the schema file included no description for the callback, what do we need to say about this?
  * what does the promise return?
  * are the code examples appropriate?

**Comment by rebloor** [comment]
For **support tabs.goForward and tabs.goBack**  Zombie and Sebastian provided feedback and updates to the API pages. Made minor grammatical changes. Complete pending merge of the compatibility data.

**Comment by Elchi3** [comment]
I've reviewed and merged the compat data changes. Thank you! 


> @Elchi3 @chrisdavidmills [network.cookie.sameSite.laxByDefault breaks my add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1629436) doesn't look like a Web Extensions API change, although the effect is on Web Extensions (so at least probably needs mentioning in the Web Extensions section of the release notes). Should this be moved elsewhere?

I've documented the change [here](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite), but I don't know anything about WebExtensions and how they are affected. I reckon mentioning this in release notes and linking to the SameSite page for general advice could be enough. In the bug Tom says he found a place in the WebExtension docs, so maybe that need updating, too.

**Comment by rebloor** [comment]
For **Implement permissions API events** Shane provided a positive response to the needinfo QA request.

**Comment by Elchi3** [comment]
> @Elchi3 @chrisdavidmills [network.cookie.sameSite.laxByDefault breaks my add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1629436) doesn't look like a Web Extensions API change, although the effect is on Web Extensions (so at least probably needs mentioning in the Web Extensions section of the release notes). Should this be moved elsewhere?

@rebloor Did you see Tom's comment on that bug? And we can add this to the WebExtension release notes section maybe?

**Comment by rebloor** [comment]
@Elchi3 Rob is looking into what other changes might be needed, I hope to finish the updates this week.

**Comment by rebloor** [comment]
@Elchi3 Pending further feedback from Rob, I've updated [host permissions](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions) and [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#Other) based on his feedback so far.

**Comment by rebloor** [comment]
For **network.cookie.sameSite.laxByDefault breaks my add-on** Rob confirmed that the updates to [host permissions](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions) and [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#Other) were the necessary updates and communication.
