### ISSUE TITLE
[WebExt] Storage API, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3198]
# Trello

https://trello.com/c/Pw66h6fb/56-storage-api-related-tasks-fx-77

# Acceptance criteria

1. - [x] [remove unlimitedStorage prompting](https://bugzilla.mozilla.org/show_bug.cgi?id=1630413)

**Comment by rebloor** [comment]
For "remove unlimitedStorage prompting" the information about prompting from unlimitedStorage on the Extension Workshop page [Requesting the right permissions](https://extensionworkshop.com/documentation/develop/request-the-right-permissions/) has been updated in [Removal of unlimitedStorage prompting #633](https://github.com/mozilla/extension-workshop/pull/633). The [release notes](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#Other_2) have also been updated.  Pending developer feedback that these changes are complete and appropriate.

**Comment by rebloor** [comment]
Extension Workshop PR has been merged and developer responded on bug.

**Comment by gidansau69** [comment]
ср, 6 мая 2020 г., 18:45 rebloor <notifications@github.com>:
