### ISSUE TITLE
[WebExt] WebRequest, Fx 77 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3199]
# Trello

https://trello.com/c/khmwRVQp/209-proxy-and-webrequest-api-related-tasks-fx-77

# Acceptance criteria

1. - [x] [filterResponseData from the WebRequest API returns script bytecode cache data](https://bugzilla.mozilla.org/show_bug.cgi?id=1530408)
2. - [x] [Remove or revisit support for data:-URLs in the webRequest API (remove/replace WebRequestContent.js)](https://bugzilla.mozilla.org/show_bug.cgi?id=1631933)

**Comment by rebloor** [comment]
Completed "Remove or revisit support for data:-URLs in the webRequest API (remove/replace WebRequestContent.js)" as per developer feedback by updating [webRequest.RequestFilter](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter) to clarify the pattern matched protocols as follows "Only requests made using HTTP or HTTPS will trigger events, other protocols (such as data: and file:) supported by pattern matching do not trigger events."
As this is a clarification of current functionality, nothing added to the release notes.

**Comment by rebloor** [comment]
Completed **filterResponseData from the WebRequest API returns script bytecode cache data**  with a change to [webRequest.filterResponseData()](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) with confirmation from Shane, via a needinfo request on the bug, that the change is good.
