### ISSUE TITLE
[FTP] FTP, Fx 77 related tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3200]
# Trello

https://trello.com/c/dSFDORyd/263-ftp-fx-77

# Acceptance criteria

1. - [ ] [Put FTP code behind a pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1622409) (Nightly for now; not sure where to mention this yet; experimental features, but also maybe give a heads up that this is coming in the hacks release post?)

**Comment by chrisdavidmills** [comment]
I have added a note to experimental features: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Security.

I think this is all that's neede for now.

**Comment by Elchi3** [comment]
Doesn't look like there is more to be done here.
