### ISSUE TITLE
Missing page: Accept-Post HTTP header

### ISSUE THREAD

**Issue by crabmusket** [mdn/sprints#3202]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

There is a page which documents the [Accept-Patch](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Patch) header. However, there is no page which documents Accept-Post.

The header exists in the [IANA registry](https://www.iana.org/assignments/message-headers/message-headers.xhtml) of message headers, and is defined [here](https://www.w3.org/TR/ldp/#header-accept-post).

**Comment by hamishwillee** [comment]
New page created here: https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Post

@chrisdavidmills 
- Can you please sanity check.
- I THINK this is also used for content negotiation - ie I should be adding this to https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation - but wanted to check if that makes sense to you.
- There is no BCD for Accept-Post or Accept-Patch. I created placeholders https://github.com/mdn/browser-compat-data/pull/7245 . Might need to write test code - but let's see if BCD team can help.

**Comment by chrisdavidmills** [comment]
@hamishwillee page reviewed, and it looks good. It also makes sense to me to add it to the Content negotiation page.

@crabmusket do these updates look good to you?

**Comment by crabmusket** [comment]
Looks fantastic, thanks both of you!

**Comment by chrisdavidmills** [comment]
Cool, thanks for checking it out @crabmusket , and thanks for the great work @hamishwillee .

Closing this one now.

**Comment by hamishwillee** [comment]
Great! FYI, I updated the [content negotiation page](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) (see [patch here](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation$compare?locale=en-US&to=1652318&from=1634095) to note that a server might respond with the header(s) if it can't supply the requested resource (ie expand a _little_ on actual fallback behaviour/reactive content negotation).
