### ISSUE TITLE
Broken link in Array forEach page

### ISSUE THREAD

**Issue by BrunoLad** [mdn/sprints#3204]
In the following [project page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), the following paragraph:
*If elements that are already visited are removed (e.g. using shift()) during the iteration, later elements will be skipped. (**See this example, below.**)*

the bolded part of the text has a broken link.

It's pointing to this invalid href in the document:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#If_the_array_is_modified_during_iteration_other_elements_might_be_skipped.
when it should be pointing to this link:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Modifying_the_array_during_iteration

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting.
