### ISSUE TITLE
Move Document.getAnimations page to DocumentOrShadowRoot.getAnimations

### ISSUE THREAD

**Issue by lpd-au** [mdn/sprints#3205]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/docs/Web/API/Document/getAnimations should be moved to https://developer.mozilla.org/docs/Web/API/DocumentOrShadowRoot/getAnimations as per its definition in [Web Animations 1](https://drafts.csswg.org/web-animations-1/#ref-for-documentorshadowroot%E2%91%A0).

**Comment by Rumyra** [comment]
Page has been moved

https://wiki.developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/getAnimations

Both Document and DocumentOrShadowRoot interface pages have been updated to reflect

https://wiki.developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot
https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document
