### ISSUE TITLE
Documentation example ru/RU error

### ISSUE THREAD

**Issue by Miezaru** [mdn/sprints#3207]
# Request type
- [x] Correction or update

# Details

hello why are you using print instead console.log()?
I think it is an error, therefore I am writing about it.

[MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number)
[screen](https://prnt.sc/s9rgin)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
