### ISSUE TITLE
/en-US/docs/Web/API/MediaDevices/getUserMedia

### ISSUE THREAD

**Issue by maxsbelt** [mdn/sprints#3209]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There is a typo here:

![Screenshot 2020-05-04 at 14 51 11](https://user-images.githubusercontent.com/950216/80962997-c5f7d680-8e16-11ea-87eb-8058be3d091c.png)

If you try to use such configuration you will receive the error:

![Screenshot 2020-05-04 at 14 52 38](https://user-images.githubusercontent.com/950216/80963067-ecb60d00-8e16-11ea-9342-1effc1d4c2fc.png)

It seems like the actual value should be `576`.

**Comment by chrisdavidmills** [comment]
Ah yes, looks like a typo. Fixed now; thanks for reporting!
