### ISSUE TITLE
[Chrome Browser] Missing border-style: solid when border-image fill not used

### ISSUE THREAD

**Issue by strarsis** [mdn/sprints#3210]
**Summary**
The [CSS Border Image Generator](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator) on MDN is very useful.

In the latest Chrome browser, when the fill option is disabled, like in many of the preset examples, the border image is not shown. The reason for this is that the `border-style: solid` is missing.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. With latest Chrome, open the [CSS Border Image Generator](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator) on MDN.
2. Select one of the presets where fill is not used/enabled (many of them).
3. Notice that the border-image is not displayed, only when the fill option is enabled. However, this is neither necessary nor intended as it can occlude the element background for some border-image-sources.

**Actual behavior**
The Border Image Generator tool doesn't set `border-style: solid` neither for preview element nor in final CSS output, resulting in Chrome not showing the border-image but an empty preview element.

**Expected behavior**
A proper `border-style` is set so the border image is shown with fill disabled.

**Additional context**
When you reproduced this issue with one of the examples in the editor, disable the fill option again, then inspect the preview element in web developer tools and assign it `border-style: solid`. Notice how the border-image becomes visible now, without the fill option.

**Comment by chrisdavidmills** [comment]
Hrm. I know what to do to fix this, but I'm not sure how to access this code to make the necessary changes. Can you help me locate the code for this, @peterbe ?

**Comment by wbamberg** [comment]
@chrisdavidmills , it's implemented as a live sample (!!!). Visit https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator$edit and click "View source".

Perhaps it would be a good candidate for breaking out into a separate GitHub-hosted page and embedding as an iframe?

**Comment by chrisdavidmills** [comment]
@wbamberg thanks Will! I though this probably was the case, and I looked in a few places, but for some reason my brain didn't tell me to try looking in the source view of the _actual page itself_ ¯\_(ツ)_/¯

@strarsis so I've added in the necessary CSS, and the tool now seems to work in Chrome! Let me know if you think this needs anything else.

**Comment by strarsis** [comment]
@chrisdavidmills: Yes, I can confirm that it works now in Chrome.
There are some issues with the examples. I open a new issue for these.

**Comment by strarsis** [comment]
Example-related issue: https://github.com/mdn/sprints/issues/3217
