### ISSUE TITLE
Grammatical Glitch

### ISSUE THREAD

**Issue by digitalforus** [mdn/sprints#3215]
**Details**
There's a grammatical glitch in the Note section towards the last paragraph. It should be "In general more comments are usually..." and not "In general more comments is usually...".

`[URL to the page ](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)`

**Comment by chrisdavidmills** [comment]
Updated. Thanks for taking the time to report this to us.
