### ISSUE TITLE
SCRAM-SHA instead of CRAM-MD5

### ISSUE THREAD

**Issue by cmouse** [mdn/sprints#3218]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On this [web page](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo), you are advocating for `CRAM-MD5`. It would make sense to start campaining for SCRAM-SHA1 or SCRAM-SHA256, which is more secure and modern than CRAM-MD5. Please see [RFC 8502](https://tools.ietf.org/html/rfc5802) for more details.

**Comment by Elchi3** [comment]
The MDN team doesn't maintain the Thunderbird docs. If you like feel this with the Thunderbird bug tracker.
