### ISSUE TITLE
/en-US/docs/Web/HTTP/Status/202

### ISSUE THREAD

**Issue by eaydin** [mdn/sprints#3219]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The explanation of the `202 Accepted` HTTP Status in the MDN states that it  _indicates that the request has been received **but not yet acted upon**._

According to the [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.3.3), it _indicates that the request has been accepted for processing, but the processing has **not been completed**. The request **might or might not eventually be acted upon**._

There is a slight wording difference that I was hoping to clarify. What I was looking for is an HTTP Status for a _job_ that
- Might have started and is still running
- Or might have not yet been started but is accepted for processing

According to the RFC, `202 Accepted` can be used in this manner. But the documents in MDN suggests that the _job_ has definitely not been started yet. 

It seems I'm not the only one looking for a representation of ongoing processes via HTTP Status codes as indicated [here](https://stackoverflow.com/questions/14824969/most-appropriate-http-status-code-for-job-in-progress) and [here](https://stackoverflow.com/questions/14824969/most-appropriate-http-status-code-for-job-in-progress), in which, all developers tended to use `202 Accepted` responses for this purpose.

Clarification would improve as it implies a different meaning now.

**Comment by chrisdavidmills** [comment]
I can understand your need for clarification here. I've tried updating the wording on https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Status/202, mostly using the RFC wording, but also adding some clarification of my own. Do you think this is better now?

**Comment by eaydin** [comment]
Thank you, I think anyone else reading the docs will get a clearer picture of the response status now.
