### ISSUE TITLE
Wrong email reference

### ISSUE THREAD

**Issue by taiwoayanleye** [mdn/sprints#3220]
# Request type

- [x] Correction or update

# Details

For [**Loops 2**](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops) example, this line should be "searches an array of objects containing names and **phone numbers**" and not "searches an array of objects containing names and **emails**".

**Comment by chrisdavidmills** [comment]
@taiwoayanleye Thanks for reporting this error. I have fixed it!
