### ISSUE TITLE
Update "Configuring server MIME types" article

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3221]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
The article [Properly configuring server MIME types](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types) has been incrementally updated over the last 15 years, but it is probably out of date in significant ways. It needs to be reviewed and updated.

**Comment by caraya** [comment]
@chrisdavidmills I would like to tackle this one

**Comment by chrisdavidmills** [comment]
@caraya you are assigned; thanks for helping out!

**Comment by caraya** [comment]
In reviewing the file there are a lot of issues that will require discussion and full re-writes and probably discussion on what needs to go in this article.

For example, the sample .htaccess file (https://wiki.developer.mozilla.org/en/Sample_.htaccess_file) is not really a .htaccess file but a discussion on what can go into one.  Should we write a full .htaccess file or just concentrate on mime types?

The page is Apache specific. Should we also address NGINX too?

Do we need to keep the historical note about Firefox loading CSS files even if they had the wrong MIME type?

When I worked on Javascript, I did the edits and adds directly on the Wiki, is that still the way to go?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> 
> In reviewing the file there are a lot of issues that will require discussion and full re-writes and probably discussion on what needs to go in this article.

That is fair enough, @caraya . Some of our articles have gone rather out of date.

> 
> For example, the sample .htaccess file (https://wiki.developer.mozilla.org/en/Sample_.htaccess_file) is not really a .htaccess file but a discussion on what can go into one. Should we write a full .htaccess file or just concentrate on mime types?

I would provide a full sample .htaccess file, which shows the most important things you should include, and then describe what each bit does, why it is important, etc. The current state of things is a bit misleading.

> 
> The page is Apache specific. Should we also address NGINX too?


Probably a good idea, with NGINX being increasing popular.

> Do we need to keep the historical note about Firefox loading CSS files even if they had the wrong MIME type? It may lead to confusion

No. Sounds out of date to me.

 
> When I last worked on MDN, I did the edits and adds directly on the Wiki, is that still the way to go?

Yes, that's fine. I am happy to review it there too.

**Comment by caraya** [comment]
@chrisdavidmills 

Ready for review. Still working on .htaccess and nginx equivalency

**Comment by chrisdavidmills** [comment]
Thanks @caraya , this looks really good. I've given it a copy edit and tightened up the language a bit.

It would also be nice for @hamishwillee to give this a check over.

**Comment by hamishwillee** [comment]
@chrisdavidmills @caraya Subedited. I found the English confusing in several parts about whether we were talking about the server or the browser. 

In particular I changed the titles of the headings about getting MIME types to make it clear that one is what you set in the server and the other is how you check the MIME type of files your recieved. 

There are two **significant** broken links in https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types#How_to_set_up_your_server_to_send_the_correct_MIME_types

> If you're using the Apache web server, simply copy this sample .htaccess file to the directory, which contains the files that you want to work with or the parent directory if there are many such directories.

This says you can copy the htaccess file at the link BUT the link is to an obselete MDN doc. The doc is also not something you can copy - its a kind of guide. This needs to be fixed. 

Further the NGINX link doesn't exist yet. FYI though, I I renamed snipet > snippets

FWIW I think this is a useful doc. However this is about my existing level of knowledge about MIME types already, so I couldn't say if we were missing anything.

**Comment by chrisdavidmills** [comment]
Thanks @hamishwillee !

The two broken links to the example files are because @caraya is still working on them, I believe.

**Comment by hamishwillee** [comment]
Hi @caraya (@chrisdavidmills)

In that case this will need just a little more work:
1. The doc says "If you're using the Apache web server, simply copy this *Apache configuration examples* to the directory, ..."
   - This links to the top of the doc, which is a set of examples (not just one file you can copy)
   - You need to perhaps modify this to link to the specific section - e.g. something like: "If you're using the Apache web server, simply copy the section of the .httacces file here: [Apache .htaccess Configuration Snippets >Serve resources with the proper media types (a.k.a MIME types)](https://wiki.developer.mozilla.org/en-US/docs/Archive/Sample_.htaccess_file#Serve_resources_with_the_proper_media_types_a.k.a_MIME_types) ....

What you might do instead is copy the relevant section into "Configuring Server MIME types" and then have the example files just as "Related links" at the end.

Chris, This page also needs to be "un archived". How does that work?

**Comment by chrisdavidmills** [comment]
> Chris, This page also needs to be "un archived". How does that work?

To unarchive, it just needs to be moved out of `/Archive/` to somewhere else. Should we put this page under `/Server-side/` as well? What do you think we should call it?

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks!

> To unarchive, it just needs to be moved out of /Archive/ to somewhere else.

FYI, I don't think I have necessary rights to do this.

> Should we put this page under /Server-side/ as well? 

You mean under https://developer.mozilla.org/en-US/docs/Learn/Server-side ? That seems sensible.

Further down the track we might want to expand on our docs. We could perhaps put this in a grouping parent - e.g. _/Learn/Server-side_**/Apache** or e.g. _/Learn/Server-side**/Servers**? Maybe too early?

My concern with this doc is that it feels like an orphan. Nowhere do we introduce Apache, Nginx and other alternatives. 
Minimally perhaps we could add a section about popular web servers in https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction ?

> What do you think we should call it?

My preference is **Apache Configuration: .htaccess** (to perhaps one day be accompanied by  **Apache Configuration: httpd.conf**). If you prefer something more verbose: **Apache Server Configuration using .htaccess files**

**Comment by caraya** [comment]
@hamishwillee, @chrisdavidmills 

> * This links to the top of the doc, which is a set of examples (not just one file you can copy)

I was waiting to get the final location before changing the link.  I like the idea of linking directly to the mime type configuration directly.

**Comment by chrisdavidmills** [comment]
OK, article moved:

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Apache_Configuration_htaccess

Thanks folks!

**Comment by chrisdavidmills** [comment]
@caraya did you ever get round to finishing this one?

**Comment by caraya** [comment]
The Apache configuration is done. The Nginx is taking way longer than expected. We can close this one and I'll open a new ticket when the Nginx configuration reference is completed.

**Comment by chrisdavidmills** [comment]
Sounds good. The article update looks great, BTW, thanks @caraya !
