### ISSUE TITLE
/en-US/docs/Web/API/Web_Authentication_API

### ISSUE THREAD

**Issue by equalsJeffH** [mdn/sprints#3222]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [Web_Authentication_API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) page does not pull-in all BCD .json files for the webauthn API.  Presently, it appears to pull-in only: https://github.com/mdn/browser-compat-data/blob/3e5202b66916e5c7970f145169e29600f16c280c/api/PublicKeyCredential.json via this call in its source `{{Compat("api.PublicKeyCredential")}}`

Here are all the BCD .json files for the webauthn API that I can find (am a BCD n00b, not sure if I found them all?):

https://github.com/mdn/browser-compat-data/blob/master/api/AuthenticationAssertion.json
https://github.com/mdn/browser-compat-data/blob/master/api/AuthenticatorAssertionResponse.json
https://github.com/mdn/browser-compat-data/blob/master/api/AuthenticatorAttestationResponse.json
https://github.com/mdn/browser-compat-data/blob/master/api/AuthenticatorResponse.json

https://github.com/mdn/browser-compat-data/blob/master/api/PublicKeyCredential.json
https://github.com/mdn/browser-compat-data/blob/master/api/PublicKeyCredentialCreationOptions.json
https://github.com/mdn/browser-compat-data/blob/master/api/PublicKeyCredentialRequestOptions.json

**Comment by chrisdavidmills** [comment]
Often it doesn't work to have a brower compat section on an API landing page; for this kind of reason. We don't yet have the ability to create tables that aggregate compat data together from separate interfaces.

For now, I've changed that section to this: https://wiki.developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Browser_compatibility

What do you think? Does this allow users to find the info they are after?

**Comment by equalsJeffH** [comment]
> Often it doesn't work to have a brower compat section on an API landing page; for this kind of reason. We don't yet have the ability to create tables that aggregate compat data together from separate interfaces.

ah

> For now, I've changed that section to this: https://wiki.developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Browser_compatibility
> 
> What do you think? 

Seems fine, thx!  suggested wordsmithing:

"For Web Authentication browser compatibility information, view each of the individual interface pages listed in the Interfaces section of this page."

> Does this allow users to find the info they are after?

I think it'll help, thanks again.

**Comment by chrisdavidmills** [comment]
> "For Web Authentication browser compatibility information, view each of the individual interface pages listed in the Interfaces section of this page."

I like it! Page updated.

**Comment by equalsJeffH** [comment]
thx!
