### ISSUE TITLE
WebAuthn spec maturity level 

### ISSUE THREAD

**Issue by equalsJeffH** [mdn/sprints#3229]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Specifications

the page says WebAuthn spec is at CR maturity level, but it is actually at Recommendation.

thx,

=JeffH

**Comment by sideshowbarker** [comment]
OK, made a PR at https://github.com/mdn/kumascript/pull/1369
