### ISSUE TITLE
/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts

### ISSUE THREAD

**Issue by mirisuzanne** [mdn/sprints#3230]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#Browser_support

Under "Browser Support" for logical properties, I saw the quote:

 >  An example would be margin-block, which is a shorthand setting for margin-block-start and margin-block-end. These currently have no browser support.

That seems to be significantly out of date, according to the linked MDN support table:

https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block#Browser_compatibility

**Comment by chrisdavidmills** [comment]
> That seems to be significantly out of date

Oooof, it certainly is! I've removed the bit about there being no support. Thanks for reporting it Miriam!
