### ISSUE TITLE
/en-US/docs/Web/CSS/transform-box

### ISSUE THREAD

**Issue by spollard** [mdn/sprints#3231]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

There seems to be a small typo in the Syntax > Values > content-box portion of the transform-box documentation. https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box. 

This (emphasis mine):
"The reference box of a &lt;table&gt; is the border box of *it stable* wrapper box, not its table box."

Should probably be (emphasis mine):
"The reference box of a &lt;table&gt; is the border box of *its table* wrapper box, not its table box."

I noticed that the next portion Syntax > Values > border-box does have the correct spelling. 

I have not seen this error on other pages, but I have not searched comprehensively.

Thanks!

**Comment by chrisdavidmills** [comment]
Thanks for reporting this — yes, this was a simple typo, but I've fixed it now.
