### ISSUE TITLE
https://wiki.developer.mozilla.org/fr/docs/Web/CSS/:valid$history

### ISSUE THREAD

**Issue by keusta** [mdn/sprints#3233]
string "a@a" is :valid email type
why is this possible without a dot detection after @?

**Comment by chrisdavidmills** [comment]
This is just the way the inbuilt validation works for email addresses. I don't really have an answer for you beyond that.

If you want to create a better validation for email addresses that includes making sure it is of the form a@a.a, then you'd have to create a regular expression and include it in a `pattern` attribute on the input.

This section might be interesting to you as well: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Basic_validation
