### ISSUE TITLE
Responsive Design CSS Syntax Error

### ISSUE THREAD

**Issue by MatyasKriz** [mdn/sprints#3235]
# CSS Syntax Correction

### Details
The example CSS at Responsive Design depicting usage of `max-width: 100%` is terminated by a colon instead of a semicolon.

![image](https://user-images.githubusercontent.com/6033733/81506889-be926a80-92f9-11ea-9092-0aca2854c994.png)

**URL:** https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

**Comment by chrisdavidmills** [comment]
@MatyasKriz oops. I've fixed it now; thanks for reporting!
