### ISSUE TITLE
Bad links in Note

### ISSUE THREAD

**Issue by ekpletto** [mdn/sprints#3236]
# Request type

- [x] Correction or update

# Details

In the first note on the page, the link to OSG.js goes to an adult site and the link to O3D seems outdated or broken.

<img width="551" alt="screenshot" src="https://user-images.githubusercontent.com/64711902/81514722-86812c80-92e5-11ea-8f4c-484a76e3e72f.PNG">

https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/Building_up_a_basic_demo_with_Three.js

**Comment by chrisdavidmills** [comment]
Thanks for pointing out these problems. I've removed these links, and inserted a link to PlayCanvas, which is game-specific, but WebGL-based nevertheless.
