### ISSUE TITLE
Inconsistent Whitespace in "Organizing your CSS"

### ISSUE THREAD

**Issue by MatyasKriz** [mdn/sprints#3237]
# Inconsistent Whitespace Correction

### Details
**Redundant space in section "Other tools that can help"**
![image](https://user-images.githubusercontent.com/6033733/81647404-4036e500-942d-11ea-9c42-42e71cb20fb1.png)
In front of the `.list-item`.

---

**Missing space lower in the same section**
![image](https://user-images.githubusercontent.com/6033733/81647493-6066a400-942d-11ea-8e3b-182c41df00c6.png)
In front of the `<div>`.

**URL:** https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Organizing

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!

Also, did you know that if you get an MDN account and log in, you can edit the pages yourself? If you'd rather still report the problems, then I am perfectly happy to keep fixing them, but I thought that it might be quicker for both of us if you just fixed these things yourself as you notice them.

All the best.
