### ISSUE TITLE
/en-US/docs/Web/XPath/Functions/document

### ISSUE THREAD

**Issue by dshcs2995** [mdn/sprints#3238]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the below URL, the "Arguments" section and "node-set (optional)" subsection, the text "An expression pointing to a node-set the external document that should be returned" seems to be missing the word "in" between "node-set the".  If not missing "in" something else is wrong.

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/document

**Comment by chrisdavidmills** [comment]
I think you're right; I've updated this in the document. 

Thanks for reporting!
