### ISSUE TITLE
/en-US/docs/Web/API/AudioContext/createMediaStreamDestination

### ISSUE THREAD

**Issue by spollard** [mdn/sprints#3239]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I was reading through the createMediaStreamDestinaion documentation (https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamDestination) and I noticed that in the example code under the Example heading, the highlighted line #17 is about the oscillator (var osc = ac.createOscillator();) and does not call createMediaStreamDestination(). Line #18 looks like it should be highlighted instead. 

url: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamDestination

**Comment by chrisdavidmills** [comment]
Thanks for reporting! I've just removed the line highlight, as they are pretty unreliable, and we rarely make use of them.
