### ISSUE TITLE
regular expression documentation makes wrong compatibility assumptions a bit too easy

### ISSUE THREAD

**Issue by obfusk** [mdn/sprints#3240]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I've been bitten twice now by the fact that the documentation about [Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) doesn't make it at all obvious that some features (like lookbehind assertions and unicode property escapes) don't work in all browsers ... until you explicitly look at the compatibility table at the end, which is very easy to forget.

Especially since JavaScript CI often runs on Node.js (which does support those features), it's easy to accidentally use a feature with limited compatibility without noticing.

Many MDN pages warn about features being non-standard. It would be nice to have some warnings about compatibility in the article (and sub-articles) itself, instead of just in the compatibility table.

I'd be happy to help with that.

**Comment by chrisdavidmills** [comment]
I agree that we should point out features with limited support a bit more obviously in the subpages.

Now about in places where such a feature is discussed, we include a note box along the lines of

Note: The <name-of-feature> feature currently has limited browser support. Please check the <a href="">Regular expressions browser support table</a> to find out more information. 

We are rather busy at the moment, and will probably get to this in the next quarter. If you had the time to work on this, I'd be happy for you to make the changes.
