### ISSUE TITLE
Missing example at https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### ISSUE THREAD

**Issue by dcompcoder** [mdn/sprints#3241]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The first sentence after the interactive "HTML Demo" section states "The above examples" (ie plural—more than one example). Also, the rest of the paragraph refers to two examples. The problem is that there's only one example in the interactive HTML Demo.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

**Comment by chrisdavidmills** [comment]
Thanks for reporting this! I think we used to have two examples here, but we ended up deleting one because it was getting too big for the interactive example.

I've altered the text so that it works for the one remaining example.
