### ISSUE TITLE
/en-US/docs/Learn/CSS/Building_blocks/Organizing

### ISSUE THREAD

**Issue by lux-dilettant** [mdn/sprints#3242]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
 

There is a broken link on 

/en-US/docs/Learn/CSS/Building_blocks/Organizing

In the section "Compiling component stylesheets" there is a link to 

You can see how one developer approaches the problem in this blog post (https://www.lauraleeflores.com/blog/how-to-organize-your-css-files) which leads to an 404 error page

**Comment by chrisdavidmills** [comment]
Ah yes, that article no longer seems to exist. That's a shame.

I couldn't really find an appropriate equivalent, so I've just removed it, and added a bit more information on Sass partials.

Thanks for reporting it!
