### ISSUE TITLE
Update CSS url() documentation

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3243]
I've been doing some analysis of our CSS docs, and found that we had two different pages for the `url()` function, one generic and one specific to its use as a value for the `filter` property:

* [`CSS/url()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url())
* [`CSS/filter-function/url`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function/url).

@a2sheppy just made the second of these redirect to the first one, which I think is the right call, but more filter-specific content should be added to the remaining page.

@mindy provided some great detail on this, that we should integrate into https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url():

*******

The most common use of url() is to load an image or font file. For example, if you did a search in kuma's CSS codebase for url , it's almost exclusively used for background images.

So I think that is important to know, since it gives an idea of where most people might be coming from in terms of understanding how url works regarding CSS.

I think using url with the filter property is unique because the value for url needs to be either:

1. the path to an SVG file with the ID of the filter appended
2. the ID of the filter, if the SVG already exists on the page

I made an example here to show what I mean: https://codesandbox.io/s/amazing-engelbart-i4mes?file=/style.css

I copied the SVG filters directly from MDN: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur, https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence :slightly_smiling_face.

**Comment by rachelandrew** [comment]
@chrisdavidmills I have added information about the specific usage in filters as a third example.

**Comment by chrisdavidmills** [comment]
@rachelandrew sorry Rachel, I'm getting a bit confused. Which page have you added that third example to?

**Comment by rachelandrew** [comment]
@chrisdavidmills ah ... I added it to the page for the data type, as we also have a page for the <url> data type, which is essentially the same thing: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url() is correctly defined here as a function.

I don't think we need both of these pages.

**Comment by chrisdavidmills** [comment]
Ah, I see.

> I don't think we need both of these pages.

Yeah, I agree. It is just confusing as is. Although saying that, both pages have some useful content on them. Can you add all the useful content into `/url()`, and then we'll redirect the `/url` page to that? I think `url()` is the more likely thing for developers to identify with than `<url>`.

**Comment by rachelandrew** [comment]
OK, everything that wasn't covered is now part of https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url()

**Comment by chrisdavidmills** [comment]
Looks great @rachelandrew , thanks! And I've put the redirect in place. So I think we can close this now.
