### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by lizyapol** [mdn/sprints#3246]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi, So i was going through the JavaScript as i started learning the language recently and i came across this small typo error on the link below, Third paragraph on the second list the word **even** is misspelled.

<ul><li>What questions should I ask when trying to choose a framework? Do I <b>neven</b> need to use a framework?</li></ul>

[https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks](url)

**Comment by chrisdavidmills** [comment]
Fixed. Thank you for reporting it!
