### ISSUE TITLE
Erroneous Grid Examples

### ISSUE THREAD

**Issue by spencermathews** [mdn/sprints#3247]
# Request type

- [X] Correction or update

# Details

In the first example on the Grids page, in the **Defining a grid** section, the code snippet shown on the page is correct. However, in the linked Codepen and JSFiddle the display and grid-template-columns properties are erroneously set on the grid items, not the grid container.

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids

**Comment by chrisdavidmills** [comment]
They're not; if you look closely at the code on Codepen/JSFiddle, you'll see that the relevant CSS block looks like so:

```
.container > div {
  border-radius: 5px;
  padding: 10px;
  background-color: rgb(207,232,220);
  border: 2px solid rgb(79,185,227);
}          .container {
  display: grid;
  grid-template-columns: 200px 200px 200px;
} 
```

This is two separate CSS rules, even though it doesn't look as such.

I'm afraid there is not much I can do about this, as the codepens/jsfiddles are auto-generated from the code on the mdn page.

**Comment by spencermathews** [comment]
Thanks. I stand corrected. That's confusing though!
