### ISSUE TITLE
BiquadFilterNode AudioParam description (a-rate/k-rate)

### ISSUE THREAD

**Issue by MinuWagner** [mdn/sprints#3248]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the AudioParam examples section it says

> Next, an example showing a BiquadFilterNode having some values set. These are examples of **k-rate AudioParam's**, as the values are set for the entire audio block at once.

But on the BiquadFilterNode page it descipes them as a-rate params.

https://developer.mozilla.org/en-US/docs/Web/API/AudioParam
https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode

**Comment by chrisdavidmills** [comment]
Good spot. I've changed them to `DynamicsCompressorNode` examples, as they are k-rate.
