### ISSUE TITLE
[WebAPI] Ambient Light Events Example Uses an Obsolete Property and Event

### ISSUE THREAD

**Issue by BboyAkers** [mdn/sprints#3249]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
When using the example on the Ambient Light Events API. It looks to currently be using the obsolete property 'ondevicelight' and the obsolete event 'devicelight'. Further investigation shows the devicelight event is disabled by default in Firefox 62, behind the device.sensors.ambientLight.enabled preference.

My questions are:
Can the Ambient Light Events APIs be used with any other stable or not obsolete properties and events? If no, is this API still considered relevant? 
Should this still be labeled as experimental or should it be archived?

The last substantial change to the example was by RockoDev on May 29, 2018.

Ambient Light Events:
https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events

ondevicelight  (obsolete):
https://developer.mozilla.org/en-US/docs/Web/API/Window/ondevicelight

devicelight (obsolete):
https://developer.mozilla.org/en-US/docs/Archive/Web/devicelight_event

Are there updated properties and events someone can recommend? I'd be more than happy to make a pull request and create an updated example! 🙂

**Comment by BboyAkers** [comment]
@Elchi3 @chrisdavidmills Are there any updated properties and events ya'll can recommend to update the example or point me in the direction to? I'd be happy to create an updated one and put in a pull request! 😃 Or is this something to be handled on ya'lls end?

**Comment by chrisdavidmills** [comment]
Hi @BboyAkers ! Basically, we have such a large backog of work to do, that we probably won't get to this task quickly. IIRC correctly, the Ambient light events API is really new, whereas the old way of doing things was made obsolete due to security concerns (e.g. fingerprinting).

We'd need to figure out what the lastest state of support is for such APIs, and what events they use, and update the documentation appropriately.

Would you have time to help on this task?

**Comment by BboyAkers** [comment]
@chrisdavidmills I'd love to help especially if you're talking about the backlog as well! Where would you like for me to start, is there a Discord or slack Channel to join?

**Comment by chrisdavidmills** [comment]
In terms of discussing this particular task, this issue is fine for asking questions or recording details of the work. 

For sync comms, the best place is probably the MDN Web Docs room on our Riot/Matrix server. See https://wiki.mozilla.org/Matrix for more details.
