### ISSUE TITLE
Add startsWith() endsWith() JavaScript Examples to String() methods

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#325]
Add startsWith() and endsWith() JavaScript examples to the startsWith() and endsWith() String method pages

**Comment by jmswisher** [comment]
@irenesmith, @estelle, @chrisdavidmills I see that there are examples in the repo, but not on the corresponding wiki pages. Can this issue be closed?

**Comment by jmswisher** [comment]
Oops, they are in the wiki pages. Closing.
