### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by Melluish** [mdn/sprints#3250]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the second sentence you've got "If a non-null value don't doesn't conform...". You can get rid of the "don't".

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
