### ISSUE TITLE
/zh-TW base64 encoding is not an encryption

### ISSUE THREAD

**Issue by jhihruei** [mdn/sprints#3251]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

- Base64 is an encoding, not an encryption. 
- I think we can replace `加密` with `編碼`
  - `同前者，但經過 base64 編碼。`
  - `以 base64 格式編碼資料`
  - `在 Linux 和 Mac OS X 中，可以在終端機輸入下面的程式碼來進行編碼：`
- https://developer.mozilla.org/zh-TW/docs/Web/HTTP/data_URIs#Encoding_data_into_base64_format

<img width="562" alt="截圖 2020-05-18 上午11 58 39" src="https://user-images.githubusercontent.com/6468997/82173185-ed629f00-98fe-11ea-8b20-79e9797afc67.png">

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately the MDN team doesn't update translations. It is a community effort. Feel free to update the wiki page.

**Comment by jhihruei** [comment]
@Elchi3 Oops! Sorry I misunderstood. 
I'll back to wiki and try to update it. 
Thanks for explanation
