### ISSUE TITLE
The value for each "id" attribute must be unique, so it's wrong to say that the same ID can be used for multiple elements

### ISSUE THREAD

**Issue by dcompcoder** [mdn/sprints#3253]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the table under the heading "Different types of selectors" are the words "it's possible to use the same ID for multiple elements" and the corresponding example shows this. However, the value for each "id" attribute must be unique, which contradicts the statement quoted above.

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics

**Comment by chrisdavidmills** [comment]
I have updated this, thanks for spotting! I really hope I didn't write this originally, when I first created that article ;-)
