### ISSUE TITLE
/en-US Wrong text in the mdn js docs code

### ISSUE THREAD

**Issue by itssiva** [mdn/sprints#3254]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Looks the content of a code block in the doc is containing wrong content. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Class_declarations

It is in the **Super class calls with super** section

![Screen Shot 2020-05-18 at 3 54 12 PM](https://user-images.githubusercontent.com/11580531/82254175-60c8d880-9920-11ea-8bad-8008b33567f9.png)

**Comment by Elchi3** [comment]
Thanks! Removed this
