### ISSUE TITLE
RTCPeerConnection.addTrack page - correction required in code sample

### ISSUE THREAD

**Issue by cyberpirate92** [mdn/sprints#3255]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Page Link: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack#Usage_notes
In the above page the third code sample under **Usage Notes** section has a typo in line 5
```javascript
pc.ontrack = ev => {
  if (ev.streams && ev.streams[0]) {
    videoElem.srcObject = ev.streams[0];
  } else {
    let inboundStream = new MediaStream(track); // track is undefined, should be ev.track instead
    videoElem.srcObject = inboundStream;
  }
}
```

it should be 
```javascript
let inboundStream = new MediaStream(ev.track);
```` 
instead of 
```javascript
let inboundStream = new MediaStream(track);
```

**Comment by chrisdavidmills** [comment]
Updated; thanks for reporting!
