### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

### ISSUE THREAD

**Issue by hanshou101** [mdn/sprints#3256]
# Request type
- [x] Correction or update

# Details
In the [wasm-pack: 0.9.1] library, a bug appeared:

> After the pkg folder is generated, the [files] attribute of the package.json file is missing the following file name:
> 
>"hello_wasm_bg.js", "hello_wasm_bg.d.ts"
> 

<br>
 
This will directly lead to the error 

>Can't resolve './hello_wasm_bg.js'

when pkg is used

[wasm-pack build --target bundler not including *_bg.js file in package.json · Issue #837 · rustwasm/wasm-pack](https://github.com/rustwasm/wasm-pack/issues/837)

<br>

At present, the official has fixed this problem, 
**But no new release package has been released.**
[Corrected files included in package.json for bundler / no target (#837) by lucashorward · Pull Request #839 · rustwasm/wasm-pack](https://github.com/rustwasm/wasm-pack/pull/839)

<br>

# Solutions
We need to manually add these two file names to the package.json in the [pkg] folder.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @hanshou101 . Would you be interested in adding a note to the page to cover this?
