### ISSUE TITLE
[JS] Intl.DisplayNames

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3259]
## Story

Intl.DisplayNames enables the consistent translation of language, region and script display names.
Reference docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames

# Acceptance criteria

1. - [x] Dev-doc-complete [Implement the Intl.DisplayNames proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1557727)
2. - [x] Added to Fx XY for developers
3. - [x] BCD updated

**Comment by Elchi3** [comment]
BCD: https://github.com/mdn/browser-compat-data/pull/6268

**Comment by Elchi3** [comment]
I was wrong about this. Updated the BCD: https://github.com/mdn/browser-compat-data/pull/6312

Sigh, it is way too often not obvious at all what we're shipping and what not.

**Comment by MendyBerger** [comment]
Think that this can be closed, looks like it was taken care of in `mdn/browser-compat-data` already.

**Comment by chrisdavidmills** [comment]
Yup, I'll close this now. We will track finishing off the documentation in https://bugzilla.mozilla.org/show_bug.cgi?id=1654116
