### ISSUE TITLE
Reconsider excluding null from the list of JS primitive types?

### ISSUE THREAD

**Issue by vetvicka** [mdn/sprints#3260]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Please could you reconsider excluding `null` from the list of primitive types? `null` is clearly defined as a primitive value in the ECMAScript specification:

> A primitive value is a member of one of the following built-in types: Undefined, Null, Boolean, Number, BigInt, String, and Symbol;
https://tc39.es/ecma262/#sec-ecmascript-overview

> **null value** primitive value that represents the intentional absence of any object value
https://tc39.es/ecma262/#sec-null-value

The current description of primitives can be quite confusing:

> There are 6 primitive data types: string, number, bigint, boolean, undefined, and symbol. There also is null, which is seemingly primitive, but indeed is a special case for every Object: and any structured type is derived from null by the Prototype Chain.
https://developer.mozilla.org/en-US/docs/Glossary/Primitive

**Comment by chrisdavidmills** [comment]
Fixed via https://github.com/mdn/content/commit/a0f14bbd517379155de8a3bad8133786c41e24f6
