### ISSUE TITLE
Meaning of sentence

### ISSUE THREAD

**Issue by WojtekZalewski** [mdn/sprints#3261]
# Request type
- [ ] Correction or update

The definition of the object contains: "Structural type for any constructed instance instance".
Should I understand this phrase as: Structural type for any instance of the constructed instance ?

Link to page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

![Zrzut ekranu 2020-05-20 o 12 40 50](https://user-images.githubusercontent.com/31951087/82437182-4cf3b280-9a97-11ea-859b-02f9a54d48ea.png)

**Comment by chrisdavidmills** [comment]
This is a bit weird in terms of wording. I've changed it to "any constructed object instance".

thanks for reporting!
