### ISSUE TITLE
标点符号上的小问题，内附链接

### ISSUE THREAD

**Issue by jlcourt** [mdn/sprints#3266]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

SVG除了迄今为止所描述的以外还有其他优点：在这后面多了一个回括号

https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately the MDN team doesn't update translations. It is a community effort. Feel free to update the wiki page.
