### ISSUE TITLE
https://wiki.developer.mozilla.org/fr/docs/Mozilla/Mobile/Balise_meta_viewport$history

### ISSUE THREAD

**Issue by mohican19** [mdn/sprints#3267]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x ] New documentation
- [ ] Correction or update

# Details

le lien proposé ne renvoie nul part
the link is null 

![image](https://user-images.githubusercontent.com/44779222/82534998-76b7e280-9b46-11ea-8ad7-274cc2cc9ec3.png)

url : https://developer.mozilla.org/fr/docs/Mozilla/Mobile/Balise_meta_viewport

**Comment by Elchi3** [comment]
Thanks for your issue! Unfortunately the MDN team doesn't update translations. It is a community effort. Feel free to update the wiki page.
