### ISSUE TITLE
Typo in /ja/docs/Learn/HTML/Forms/HTML5_input_types

### ISSUE THREAD

**Issue by kei2100** [mdn/sprints#3269]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`有効なメールアドレスであす。`  seems to be a typo for `有効なメールアドレスです。`

|![image](https://user-images.githubusercontent.com/1415655/82611023-898bef00-9bfa-11ea-8013-6b87b711f993.png)|
|:-:|

**Comment by sideshowbarker** [comment]
Yes — thanks, fixed now

**Comment by kei2100** [comment]
Thank you!
