### ISSUE TITLE
Link to Mozilla build VM does not work.

### ISSUE THREAD

**Issue by pekp** [mdn/sprints#3270]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
I wanted to try out the Mozilla build VM as documented in https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Using_the_VM .

However, the provided link (http://vmimages.mozilla.net/ovf/FirefoxBuildEnv.ova) does not work.

**Comment by Elchi3** [comment]
The Mozilla build VM is no longer maintained or supported. The content is in the archive now.
