### ISSUE TITLE
Please move devtools.* pages

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#3271]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Please move three pages with slugs `devtools.*` under the page `devtools`. Specifically:

From: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow
To: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/inspectedWindow

From: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network
To: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/network

From: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels
To: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels

**Comment by Elchi3** [comment]
Will this fix https://github.com/mdn/sprints/issues/2423?

**Comment by bershanskiy** [comment]
Are you talking about [`{{WebExtExamples}}`](https://github.com/mdn/kumascript/blob/master/macros/WebExtExamples.ejs)? Yes, moving pages does fixed the script usage. I tested the following URLs:
 - `https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/inspectedWindow`
 - `https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels`

(These would be the new URLs after the move.)

However, it's possible to patch the script and make it work without moving the pages too.
This trivial one-liner for [this line](https://github.com/mdn/kumascript/blob/54cae63f279670405ed117d9a121aece1179ab68/macros/WebExtExamples.ejs#L97) works:
```
 - let pieces = slug.split("/");
 + let pieces = slug.replace("devtools.", "devtools/").split("/");
```

**Comment by Elchi3** [comment]
Ok cool. Seems to me that moving makes a lot of sense then. Will, can you take a look?

**Comment by wbamberg** [comment]
Is there some particular problem than doing this will fix, other than https://github.com/mdn/sprints/issues/2423, for which it seems we have an alternative fix?

I'm struggling a bit to remember the details, as it was a while ago, but there was a reason this devtool.thing hack got done.

Basically in WebExtensions you have 95% of the time a namespace, like `tabs`, say, which is a thing that contains properties, methods, events directly underneath it. So the overall structure of these pages is almost always two-level:

* top-level: namespaces
* next level, under each namespace: types, methods, properties, events belonging to that namespace.

Very occasionally, "types" are things with their own methods, and then that's a three-level hierarchy (e.g. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get).

By moving, say, `network` under `devtools` you create a three-level (and occasionally [four-level](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/ExtensionSidebarPane/setExpression)) hierarchy of namespace/namespace/thing. I'm not sure what implications that would have for various hacky macros, or for the general consistency of the docs. I know at least the sidebar macro already doesn't work properly with devtools.*, so maybe that wouldn't be any more broken.

So... it might be fine, but it might break things. 

>  Will, can you take a look?

This isn't part of any OKR work that I'm on, or a P1 bug, or WebExtensions updates for Firefox 78. I've not estimated any time for it in the current sprint. So I'm not clear on the work "stream" that this should be part of, or how long I should take to dig into this.
