### ISSUE TITLE
empty Document "Introducing a complete toolchain" should be deleted

### ISSUE THREAD

**Issue by MelchiorIm3Tal** [mdn/sprints#3273]
# Request type

- [ ]  Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

fom https://developer.mozilla.org/en-US/docs/MDN/Doc_status/Learn in the 'No tags' chapter, there is a link to https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview/Introducing_complete_toolchain

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview/Introducing_complete_toolchain is empty and it exists a filled version of this site: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

So https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview/Introducing_complete_toolchain should be deleted.

**Comment by chrisdavidmills** [comment]
This empty article was made by mistake, but something went wrong, and now we get an ISE when we try to delete it.

@escattone , can anything be done to manually delete this dud article?

**Comment by escattone** [comment]
@chrisdavidmills 👍 I'll take care of it. I'll let you know when I'm done.

**Comment by escattone** [comment]
@chrisdavidmills I thought it might be more involved, but it wasn't. Done!
