### ISSUE TITLE
Web Component from function?

### ISSUE THREAD

**Issue by abanks-asc** [mdn/sprints#3274]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
On [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components), under **Concepts and usage**, step 1 is:

> Create a class or a function in which you specify your web component functionality.

I was surprised to read that you can base your component on a function. The only examples I have seen are from classes. Is there an example of creating a component from a function instead of a class?

**Comment by chrisdavidmills** [comment]
I've removed the reference to using a function, as I think it is a mistake, or it is at least really confusing. There is very little reason why you'd not define your component functionality using a class. [The spec description of define()](https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-define) says it takes a constructor as its parameter, not a class or function
