### ISSUE TITLE
Correction/Update for en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### ISSUE THREAD

**Issue by smeetthakkar** [mdn/sprints#3275]
# Request type
-  [ ] Please close this issue, I accidentally submitted it without adding any details
-  [ ] New documentation
-  [x] Correction or update

# Details

Hi, while reading the JavaScript first steps I stumbled into a minor error in the first paragraph under the function heading. Hope the below makes it easier to spot:

###Now:
After that we put two curly braces ({ })

###Proposed Correction:
After that we put two curly braces (){}

PS: I am a newbie, feel free to correct me if otherwise. TIA!

[A first splash into JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash)

**Comment by chrisdavidmills** [comment]
Hi there! This is an interesting thought, but the bit in parentheses is showing what the curly braces look like. It is not supposed to be showing what their placement looks like in relation to the parentheses of the function definition. I think the code block nearby shows what the whole thing is supposed to look like well enough, so this is OK as it is.

But don't be afraid to speak up if you see anythign else that you think might need to be changed. Thank you for getitng in touch!
