### ISSUE TITLE
Old OWASP link on Cross-site scripting page

### ISSUE THREAD

**Issue by lfielke** [mdn/sprints#3276]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The "Cross-site scripting" page at https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting has a link "Cross-site scripting on OWASP" that points to https://www.owasp.org/index.php/XSS that is a 404 page the first time I visited it.

Upon subsequent visits to that link, the OWASP server seems to redirect with a 301 Moved Permanently to https://owasp.org/www-community/attacks/xss/

I suggest the link be edited so it points to the redirected page, so the user doesn't think the link is broken.

**Comment by sideshowbarker** [comment]
OK, https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting now updated

**Comment by chrisdavidmills** [comment]
Thanks @sideshowbarker and @lfielke! Closing.
