### ISSUE TITLE
getusermedia audio true "throttles" browser volume

### ISSUE THREAD

**Issue by stevebbs** [mdn/sprints#3279]
I have a problem when with getusermedia when the audio is set to "true".  The browser volume gets "throttled" to about a 30% reduction in volume and frequency range. I've tried changing all the audio constraints but any streaming audio on the browser (even different tabs) still get affected. Is there a solution for this?

**Comment by Elchi3** [comment]
Please consult a forum like Stackoverflow. This bug tracker is about MDN Web Docs.
