### ISSUE TITLE
label or laber/en-US

### ISSUE THREAD

**Issue by haboby** [mdn/sprints#3281]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details
I just written a html file in input type, i mistake between "label" and "laber" but they are still operation, Then I written a css file so run it, but don't operation.

**Comment by chrisdavidmills** [comment]
I don't know what you mean, sorry. 

Have you created a page with the wrong slug, or noticed a typo somewhere? 

What page is the problem on?

**Comment by Elchi3** [comment]
Please reopen if you can provide more info.
