### ISSUE TITLE
[CSS] :read-write and :read-only, Fx 78

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3282]
## Story

As a web developer, I want to know how to style editable content properly using CSS pseudo classes https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write and https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox 78 release notes is added.

1. - [x] [Support :read-only and :read-write pseudoclasses (unprefix)](https://bugzilla.mozilla.org/show_bug.cgi?id=312971)
2. - [x] [:-moz-read-write pseudo-class shouldn't be applied on <input type=text disabled> and <textarea disabled>](https://bugzilla.mozilla.org/show_bug.cgi?id=888884)

**Comment by chrisdavidmills** [comment]
I've completed this documentation now:

* Updated the ref/tutorial pages to have better structure, better examples, and remove some outdated stuff:
  * https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only
  * https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write
  * https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes#Read-only_and_read-write
* Added release note: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#CSS
* Updated BCD: https://github.com/mdn/browser-compat-data/pull/6244

**Comment by Elchi3** [comment]
Looks good to me, thanks Chris! :+1:
