### ISSUE TITLE
[CSS] :is and :where selectors, Fx 78

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3283]
## Story

As a web developer, I want to know how to create complex CSS selectors using https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:is and https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:where

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox 78 release notes is added, experimental features page isupdated.

1. - [x] [Enable :is() / :where() on all release channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1632646)

**Comment by chrisdavidmills** [comment]
I believe I've completed this work:

* Minor updates made to the ref pages themselves:
  * https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:is
  * https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:where
* Entry removed from https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#CSS

I didn't update the browser compat data — the data for Firefox seems up-to-date (I did it in the last release cycle), and no other browser seems to support it yet (Chrome seem to have just added it Canary).

**Comment by Elchi3** [comment]
Nice one! :1st_place_medal: 
Looks all good to me. Just expect a request for a little hacks blog section on this one from me.
