### ISSUE TITLE
https://wiki.developer.mozilla.org/ru/docs/MDN/Feedback

### ISSUE THREAD

**Issue by shade0602** [mdn/sprints#3284]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**Comment by shade0602** [comment]
I've been translating the article and frames stopped working

https://wiki.developer.mozilla.org/ru/docs/Learn/CSS/Styling_text/Styling_links

**Comment by Elchi3** [comment]
You need to use the russian section titles in the EmbedLiveSample macro call. I've fixed this.

**Comment by shade0602** [comment]
Thanks a lot
