### ISSUE TITLE
[WebExt] Firefox 78 updates

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3285]
## Story

As a WebExtensions developer, I want to be informed about the latest API changes and read updated reference docs.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, entries to Firefox release notes are added, and the content has been reviewed as needed.

1. - [x] [Disable window.{external|sidebar}.AddSearchProvider by preference](https://bugzilla.mozilla.org/show_bug.cgi?id=1632447)
2. - [x] [new supported "reject_trackers_and_partition_foreign" value for cookieConfig's behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1634306#c5)
3. - [x] [ChannelWrapper.matches throws on webRequest listeners with "xbl" filter.type](https://bugzilla.mozilla.org/show_bug.cgi?id=1638581)
4. - [x] [Allow accessing the TopSites feed even if Top Sites are disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1634279)
5. - [x] [proxy.onRequest ignores windowId / tabId](https://bugzilla.mozilla.org/show_bug.cgi?id=1641269)

(...probably not complete yet)

**Comment by Elchi3** [comment]
proxy.onRequest ignores windowId / tabId https://bugzilla.mozilla.org/show_bug.cgi?id=1641269 seems like a late Firefox 78 DDN. I've added it.

**Comment by wbamberg** [comment]
I've marked all these dev-doc-complete. I haven't blocked waiting for any engineering reviews, as they all seemed pretty simple.

**Comment by Elchi3** [comment]
Thanks Will! I've added what Caitlin wants to mention in the hacks blog post also to the Firefox 78 for developers page: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#Changes_for_add-on_developers

I think we are done here then.
