### ISSUE TITLE
[DevTools] Firefox 78 updates

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3286]
## Story

As a web developer, I want to know how to use the latest Firefox Developer Tools, so that I can develop and debug apps and websites properly using the latest tools.

## Acceptance criteria

The following bugs are dev-doc-complete, an entry to Firefox release notes is added, experimental features page is updated, and the content has been reviewed as needed.

1. - [x] [See/change remote URL from about:devtools-toolbox](https://bugzilla.mozilla.org/show_bug.cgi?id=1617237)
2. - [x] [UX refactor for the headers sections](https://bugzilla.mozilla.org/show_bug.cgi?id=1631302)
3. - [x] [Switch to lazily turning a11y services on/off when using accessibility panel.](https://bugzilla.mozilla.org/show_bug.cgi?id=1602075)
4. - [x] [Disable and remove accessibility panel "beta" code in release 69](https://bugzilla.mozilla.org/show_bug.cgi?id=1551574)
5. - [x] [Allow resizing on network table border](https://bugzilla.mozilla.org/show_bug.cgi?id=1618409)
6. - [x] [Move Service Workers section to the top](https://bugzilla.mozilla.org/show_bug.cgi?id=1633715)
7. - [x] [Disabling JavaScript still applies to all tabs after DevTools close](https://bugzilla.mozilla.org/show_bug.cgi?id=1640318)
8. - [x] [Refactor the general section of the headers panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1631295)
9. - [x] [Map scopes for log points](https://bugzilla.mozilla.org/show_bug.cgi?id=1536857)
10. - [x] [Show the related Add-on for blocked resources](https://bugzilla.mozilla.org/show_bug.cgi?id=1555057), also [Requests rejected by CORS don't display properly in Network panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1445637) and [Requests blocked by Enhanced Tracking Protection don't display properly in Network panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1556451) -- all the same patch
11. - [ ] [Provide an exception stack for uncaught promises rejections](https://bugzilla.mozilla.org/show_bug.cgi?id=1636590)

**Comment by Elchi3** [comment]
@jmswisher can you estimate this?

**Comment by Elchi3** [comment]
@jmswisher thanks for your estimation. I just added [Disabling JavaScript still applies to all tabs after DevTools close](https://bugzilla.mozilla.org/show_bug.cgi?id=1640318) to the list, so one more here, feel free to re-estimate.

**Comment by Elchi3** [comment]
@jmswisher I just added [Refactor the general section of the headers panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1631295) here since you've added "ddn" to it and it ships in Fx78. Again, feel free to re-estimate this issue, if needed.

**Comment by digitarald** [comment]
Please also track [Rename UI references of "blacklist" to "ignore" in Debugger](https://bugzilla.mozilla.org/show_bug.cgi?id=1642811), which landed in 97 but could be applied as soon as we get to it.

**Comment by jmswisher** [comment]
Item 4: Replaced screenshots that showed the "beta" label:
- [Main screenshot](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Features_of_the_Accessibility_panel)
- [Check for issues menu](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Check_for_accessibility_issues)

**Comment by jmswisher** [comment]
Item 4: Replaced screenshots that showed the "beta" label:
- [Main screenshot](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Features_of_the_Accessibility_panel)
- [Check for issues menu](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Check_for_accessibility_issues)

**Comment by jmswisher** [comment]
Item 3: [Defer to Fx79](https://bugzilla.mozilla.org/show_bug.cgi?id=1602075#c28)

**Comment by jmswisher** [comment]
Item 7: [Updated the UI Tour](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour$compare?locale=en-US&to=1628355&from=1624605) to reflect the corrected behavior.

**Comment by jmswisher** [comment]
Item 5: Deleted "in the table header" from the second paragraph of the [Network request columns](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Network_request_columns) section.

**Comment by jmswisher** [comment]
Item 8: Updated the screenshot for [Network Request details](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details), but holding off on textual updates pending [bug 1645748](https://bugzilla.mozilla.org/show_bug.cgi?id=1645748).

**Comment by jmswisher** [comment]
Item 2: Updated screenshots for the [Request headers](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Request_headers) and [Response headers](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Response_headers). Added description of the Raw toggle.

**Comment by Elchi3** [comment]
Added [Provide an exception stack for uncaught promises rejections](https://bugzilla.mozilla.org/show_bug.cgi?id=1636590) which seems to be Firefox 78.

**Comment by jmswisher** [comment]
Item 6: This is not a simple update, because it appears there are no existing docs for the Application panel. Waiting for feedback from Belen.

**Comment by jmswisher** [comment]
Item 9: Added a note to [Set a logpoint](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_a_logpoint#When_should_you_use_logpoints), pointing out that logpoints can be used with source-mapped code. Also updated the screenshot of the [Scopes](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Scopes) pane to show the Map checkbox.

**Comment by jmswisher** [comment]
Item 10: Updated the [Network request columns](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Network_request_columns) section of the Request List article, including:
- an updated screenshot of the columns menu
- removal of the "Cause" column description
- addition of the "blocked" icon for the "Status" column
- addition of blocked requests for the "Transferred" column
- misc copy-edits

**Comment by Elchi3** [comment]
@jmswisher and @digitarald can you also summarize these changes on https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#Developer_tools?

**Comment by Elchi3** [comment]
Done, thank you! :+1:
