### ISSUE TITLE
link to /ko/docs/Web/API/Document_Object_Model/Examples not works

### ISSUE THREAD

**Issue by 2ssue** [mdn/sprints#3287]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Link to `/ko/docs/Web/API/Document_Object_Model/Examples` doesn't work on [this page](https://developer.mozilla.org/ko/docs/Web/API/Document_Object_Model). Reload to the same location. (/Web/API/Document_Object_Model)

And I tried translating `Examples` document into Korean, but I had some issues when publishing. The issue was 'slug has already existed'. So I changed the slug and published it  [here](https://developer.mozilla.org/ko/docs/Web/API/Document_Object_Model/%EC%98%88%EC%A0%9C). But it should move to '/ko/docs/Web/API/Document_Object_Model/Examples'. 

I hope this issue solved.

**Comment by chrisdavidmills** [comment]
Hi there @2ssue !

I think I have fixed this now:

1. I've put the Examples content onto the `/Examples`page.
2. I've redirected the page you made to that page.
3. The link you mentioned now links to the examples correctly.

Let me know if you need anything else here!
