### ISSUE TITLE
Confusing link on "Viewing and searching Mozilla source code online" page

### ISSUE THREAD

**Issue by ArmsOfSorrow** [mdn/sprints#3288]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I wanted to download a tarball of Firefox source code, as this page suggests: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Viewing_and_searching_Mozilla_source_code_online

However, this was harder than anticipated. There was no description on where to find it within the folder listing at https://ftp.mozilla.org/pub (where I got via clicking the "tarball" link) and only after 5-10 minutes I found [this](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Downloading_Source_Archives) page, which helped me.

Instead of the "download a tarball" paragraph linking to https://ftp.mozilla.org/pub, I'd propose linking to https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Downloading_Source_Archives so that this task may be accomplished easier.
The HTML of that site,
```
download a <a class="external" href="https://ftp.mozilla.org/pub/" rel="noopener" title="En/Developer_Guide/Source_Code/Downloading_Source_Archives">tarball</a>
```
seems to suggest that it maybe used to link to the page I found more helpful to get hold of a source release.

What do you think about this?

**Comment by chrisdavidmills** [comment]
Yup, I totally agree with you here. I've updated the first reference page to remove the direct link to the source archives, and link to the source code download explainer instead. Thanks for reporting!
