### ISSUE TITLE
String.prototype.concat() documentation includes a link that returns a 500 status code

### ISSUE THREAD

**Issue by StephanieCunnane** [mdn/sprints#3289]
# Request type

- Correction or update

# Details

The `String.prototype.concat()` documentation page includes a link that returns a 500 status code:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat

The link is in the Performance section, link text is "performance test". 
Link that returns the 500 server status: https://jsperf.com/concat-vs-plus-vs-join

**Comment by Elchi3** [comment]
Thanks for your issue! We should probably wait and see if jsperf.com will come back. I see it is also referenced from several performance questions on Stackoverflow. 

If it won't come back, we can probably remove the link.

**Comment by Elchi3** [comment]
Thanks for following up on this, I removed this sentence now.
