### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/sprints#3290]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

A couple of typos in the example:
"...  to deal with messages are passed back from the worker."  -> 'that are'
"... an onmessage handler is used the handle messages ..." -> 'to handle the'

Why didn't the referring page populate this GitHub issue like it has in the past?
https://developer.mozilla.org/en-US/docs/Web/API/Worker/onmessage

**Comment by Elchi3** [comment]
Fixed, thanks for reporting!

MDN Web Docs is a wiki, so feel free to fix typos yourself next time.
