### ISSUE TITLE
U — write report detailing FED learning pathway followups.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3295]
We need a report detailing followup work to be done on the FED learning pathway, along with detailed breakdown, milestones/deliverables, schedule, and required resources.

# Acceptance criteria

- [x] Report written

**Comment by Elchi3** [comment]
Dupe of https://github.com/mdn/sprints/issues/3145

**Comment by chrisdavidmills** [comment]
Report available at https://docs.google.com/document/d/1v_10rfJOQhBUFzhAjsaPUQHmr5oRVU5tS7TbNpr46So/edit#heading=h.qwycjiweuztn
