### ISSUE TITLE
U — Preparation work for gathering feedback on FED pathway

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3298]
I want to prepare for collecting feedback on the FED learning pathway, by identifying the key feedback channels to use for collecting feedback (on top of the explicit ones already identified in other user stories), and writing questions to ask people in an interview.

# Tasks

1. - [x] Identify key feedback channels
2. - [x] Write interview questions
3. - [x] Create a questionnaire to use for collecting feedback.

**Comment by chrisdavidmills** [comment]
Preparation work can be found here: https://docs.google.com/document/d/1uruzPWJXF9qB-hU2p0gfrcwHSSLVnn9cc1cyZ88I4HU/edit#

**Comment by chrisdavidmills** [comment]
Questionnaire here: https://docs.google.com/forms/d/e/1FAIpQLScW9qAVwcS5YXHsBPNjkC9CfETrr2pGxmGxpSdt6NUtcSM_Wg/viewform

**Comment by Elchi3** [comment]
done?
