### ISSUE TITLE
CORS page mismatch about Access-Control-Request-* headers in POST request

### ISSUE THREAD

**Issue by myok12** [mdn/sprints#3305]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The document says: "(Note: as described below, the actual POST request does not include the Access-Control-Request-* headers; they are needed only for the OPTIONS request.)". However, the diagram just above (https://mdn.mozillademos.org/files/16753/preflight_correct.png) shows such headers on the actual POST request, to the contrary of the text.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @myok12 . I've created a new diagram that removes the errors, tidied things up a bit, and made the surrounding text more consistent with the example shown.

Let me know if you spot any other errors.
