### ISSUE TITLE
/fr WebSockets typo in doc

### ISSUE THREAD

**Issue by Kayoshi-dev** [mdn/sprints#3306]
# Request type

- [x] Correction or update

# Details

Hi guys! 
There is a typo in the french documentation for WebSockets
![image](https://user-images.githubusercontent.com/28494879/83202060-10831f00-a147-11ea-8e31-edae4c917a43.png)

I can do a PR if you want, I just don't know where are located french repo!

The problem is located on this page :
https://developer.mozilla.org/fr/docs/Web/API/WebSockets_API

**Comment by chrisdavidmills** [comment]
Hi @Kayoshi-dev ! Thanks for highlighting the problem.

To edit this page, you need to [get an MDN account](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Create_an_MDN_account). Once you are logged in, you can press the "edit in wiki" button on any page ("Modifier dans le wiki" for /fr/ pages), which takes you to the editable "Wiki" version of the article.

From there, press the "Edit"/"Modifier" button to get to edit mode, where you can edit the article text.

**Comment by Elchi3** [comment]
Closing per https://github.com/mdn/sprints#mdn-translations

**Comment by Kayoshi-dev** [comment]
Thanks for your comments guys, I fixed it! 👌

**Comment by chrisdavidmills** [comment]
Perfect — thanks!
