### ISSUE TITLE
[DOM] ParentNode.replaceChildren, Fx 78

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3307]
## Story

As a web developer, I want to know how about the latest DOM method ParentNode.replaceChildren that is now implemented in browsers.

Context why it is cool: https://github.com/whatwg/dom/issues/478
Intent to ship https://groups.google.com/forum/#!topic/mozilla.dev.platform/eZ-UZT6rT5g

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated if needed, and the content has been reviewed as needed.

1. - [ ] [Implement ParentNode#replaceChildren](https://bugzilla.mozilla.org/show_bug.cgi?id=1626015)

**Comment by Elchi3** [comment]
@chrisdavidmills please estimate. This landed overnight, but looks like it is still in for Firefox 78.

**Comment by chrisdavidmills** [comment]
This is a pretty simple method. I reckon 0.5 days at the most.

Note to self - would need to add it as a child page of https://developer.mozilla.org/en-US/docs/Web/API/ParentNode

**Comment by chrisdavidmills** [comment]
Ok, documentation done:

* Entry added to the methods list on the `ParentNode` page: https://wiki.developer.mozilla.org/en-US/docs/Web/API/ParentNode
* New page for `replaceChildren()` added: https://wiki.developer.mozilla.org/en-US/docs/Web/API/ParentNode/replaceChildren
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#APIs
* BCD PR filed: https://github.com/mdn/browser-compat-data/pull/6234

In a moment, I'll set the bug to DDC.

**Comment by Elchi3** [comment]
Thanks Chris!
