### ISSUE TITLE
[Wasm] Multi-value in Fx78

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3308]
## Story

As a web developer, I want to know how about the multi-value WASM extension that enables functions to return many values.

Intent to ship: https://groups.google.com/forum/#!msg/mozilla.dev.platform/lh3u-nqbFf8/A3KwV6thAQAJ

More info:
- https://hacks.mozilla.org/2019/11/multi-value-all-the-wasm/
- https://wingolog.org/archives/2020/04/03/multi-value-webassembly-in-firefox-from-1-to-n
- https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md
- https://www.chromestatus.com/feature/5192420329259008

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Multi-value: enable by default on all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1628321)
2. - [x] [[Meta] Implement multi-value](https://bugzilla.mozilla.org/show_bug.cgi?id=1401675)

**Comment by Elchi3** [comment]
@chrisdavidmills I reckon this needs some mentioning in the Wasm docs, but not extensive docs as we don't provide such detailed level of wasm docs on MDN? Should also be mentioned in release notes and post of course.
Please estimate and let me know if you could take this.

**Comment by chrisdavidmills** [comment]
I'll give this a go, but it looks like it could be tricky ;-)

This refers to a new feature of WebAssembly's text format, and doesn't really have anything to do with web-facing stuff like the WebAssembly JS API. We don't keep BCD for text format features (maybe we should?), and I'd expect that this would just need a mention in the release notes, and on our text format explainer page (see https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format).

We are quite behind in documenting WebAssembly features (for about 10 Fx versions or so). I think what we need  is for someone to take on a project to see what we're missing, and think about giving the docs a wholesale update.

**Comment by Elchi3** [comment]
> This refers to a new feature of WebAssembly's text format, and doesn't really have anything to do with web-facing stuff like the WebAssembly JS API. We don't keep BCD for text format features (maybe we should?),

I think it is fine if we only concentrate our efforts on the Web facing JS API. 

> We are quite behind in documenting WebAssembly features (for about 10 Fx versions or so). I think what we need is for someone to take on a project to see what we're missing, and think about giving the docs a wholesale update.

okay, I'm only aware of https://github.com/mdn/sprints/issues/3252. But if we could get more issues filed on this matter, then can make plan for it properly for the sprint after or at a later stage.

**Comment by chrisdavidmills** [comment]
Release note added to https://bugzilla.mozilla.org/show_bug.cgi?id=1628321

After messing around with this for a whole day, I've failed to make a demo that works. The WebAssembly text format language is really hard to figure out when you're not familiar with it, and on top of that, the tools (e.g. wabt) don't seem to be updated to support multi-value yet!

I'll ask some of the WebAssembly folks for some help.

**Comment by chrisdavidmills** [comment]
Luke got back to me very quickly and gave me an idea of how this can currently work. I've added a section about it at the borrom of https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format, which should display when MDN gets it's act together and updates the page content.

**Comment by Elchi3** [comment]
Thanks Chris! This works for me. It will also be mentioned in the hacks blog post for the release, but there we can also link to the in depth hacks article we already have.
