### ISSUE TITLE
/en-US/docs/Glossary/Network_throttling

### ISSUE THREAD

**Issue by joeframbach** [mdn/sprints#3313]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

At https://developer.mozilla.org/en-US/docs/Glossary/Network_throttling, it claims that the Firefox developer tools allows the network connection to be simulated as "offline". Firefox has no such feature.

> In a browser's developer tools, under the network panel, there is generally a drop down list with network speed options including wifi, good 3G, 2G, etc., with a default value of "no throttling".  ~~You can even test 'offline'.~~

**Comment by joeframbach** [comment]
I've filed a feature request: https://bugzilla.mozilla.org/show_bug.cgi?id=1641922

**Comment by chrisdavidmills** [comment]
Hi @joeframbach , thanks for reporting this. I've updated the page to fix the inaccuracy and generally neaten up the text.

And I agree that having "offline" would be a good option in the throttling menus.
