### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by scooby359** [mdn/sprints#3315]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under the _Serving static files_ section, the final line "For more information, see Serving static files in Express." links to `https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Serving%20static%20files%20in%20Express` but this page is not found. Cannot see a matching page across the MDN site.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

**Comment by chrisdavidmills** [comment]
@scooby359 thanks for reporting this! I think this was a placeholder that never got finished ;-)

I've replaced it with a link that works now.
