### ISSUE TITLE
Local Network connection via ssl is not trusted

### ISSUE THREAD

**Issue by f-eliks** [mdn/sprints#3316]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
When logging into my router using its local IP 192... via SSL, I get the error message:

**SEC_ERROR_INADEQUATE_KEY_USAGE** 
which is 1. Not explained in the linked <a href="https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?as=u&utm_source=inproduct">support page</a>
2. Unnecessary because my router cannot obtain a valid SSL-certificate and because Firefox unlike Edge won't let me "continue anyway" I only can connect via http which I don't want to.

**Comment by Elchi3** [comment]
Hey, this issue tracker is about MDN content, you might want to ask your question int the Firefox support forum https://support.mozilla.org/en-US/forums
