### ISSUE TITLE
U - Fix CSS linter errors: data.constituent_properties errors

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3323]
For shorthand properties we've defined a new ingredient "data.constituent_properties". The linter will check that shorthand property pages correctly include this ingredient.

# Acceptance criteria

- [x] There are zero errors reported by the linter for the "data.constituent_properties" ingredient, when run against https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by wbamberg** [comment]
According to the [spreadsheet](https://docs.google.com/spreadsheets/d/1JQIgRB978bEKHFmQoAjY4stddDdbaFAULj_TOK2jYwc/edit#gid=1575104775) there are 58 pages that generate this error. However, this includes prefixed properties, some of which we might want to archive. So, as in all these stories, it makes sense to work on the unprefixed properties first, while we work out which prefixed ones we might want to archive.

In effect this error is because we have introduced a new mandatory section for all CSS shorthand properties. The section is named `data.constituent_properties` and its syntax is defined in the spec: https://github.com/mdn/stumptown-content/blob/master/project-docs/linter-spec.md#dataconstituent_properties.

The section is placed after the interactive example and before the "Syntax" section, as defined in the recipe for CSS shorthand properties: https://github.com/mdn/stumptown-content/blob/master/recipes/css-shorthand-property.yaml.

I've made an example here: https://wiki.developer.mozilla.org/en-US/docs/User:wbamberg/shorthand-property#Constituent_properties of what it might look like.

**Comment by chrisdavidmills** [comment]
@wbamberg these are all done except for:

* `all`, which we'vealready discussed.
* `-moz-outline-radius`, which is a non-standard thing, and therefore we are probably going to archive it?

Do you want me to leave this open, or close and record the stragglers somewhere else?

**Comment by wbamberg** [comment]
Thanks for doing all these Chris!

> @wbamberg these are all done except for:
> 
> * `all`, which we'vealready discussed.

Yes, let's file a separate issue to update the linter for this case.

> 
> * `-moz-outline-radius`, which is a non-standard thing, and therefore we are probably going to archive it?
> 

I don't think just being nonstandard is a reason to archive something. I believe the general rule is that they have to be unavailable to web content in any browsers for at least 2 years (see also https://github.com/mdn/sprints/issues/3491). `-moz-outline-radius` is available to web pages, as the live sample shows.

> Do you want me to leave this open, or close and record the stragglers somewhere else?

I'd like to keep this open until these 2 are addressed.

**Comment by wbamberg** [comment]
I've filed https://github.com/mdn/stumptown-content/issues/526 for dealing with `all`.

**Comment by chrisdavidmills** [comment]
Nice one @wbamberg. Yup, I was a bit hasty on `-moz-outline-radius` — I've fixed that one too now.

**Comment by wbamberg** [comment]
As discussed in https://github.com/mdn/stumptown-content/issues/526, I've re-tagged `all` to be a normal property and removed the "Constituent properties" section. We now get zero "data.constituent_properties" errors and this story can be closed :).
