### ISSUE TITLE
/de X-Frame-Options values outdated?

### ISSUE THREAD

**Issue by NPCGundlach** [mdn/sprints#3331]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

German X-Frame-Options documentation tells that there are three possible values for the X-Frame-Options header, listing the "allow-from ..." value as the third. The english documentation explains that this value is outdated.

German version: https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options
English version: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by Elchi3** [comment]
Unfortunately, translations can be outdated sometimes. We are working on a long term solution.
For now, please note that we're not having the bandwidth to address issues like this. See also https://github.com/mdn/sprints#mdn-translations
