### ISSUE TITLE
/es

### ISSUE THREAD

**Issue by Arhurweb** [mdn/sprints#3333]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

In this link https://developer.mozilla.org/es/docs/M%C3%B3vil/Viewport_meta_tag has a link on the section "Common Viewport Sizes on Mobile Devices and Tablets" to "https://docs.adobe.com/content/help/en/target/using/experiences/vec/mobile-viewports.html" but in Spanish that link are wrong and link to "http://i-skool.co.uk/mobile-development/web-design-for-mobiles-and-tablets-viewport-sizes/" butthat domain is for sale 

https://developer.mozilla.org/es/docs/M%C3%B3vil/Viewport_meta_tag

**Comment by Elchi3** [comment]
Unfortunately, translations can be outdated sometimes. We are working on a long term solution.
For now, please note that we're not having the bandwidth to address issues like this. See also https://github.com/mdn/sprints#mdn-translations
