### ISSUE TITLE
Using Web Audio Api with dash-video source

### ISSUE THREAD

**Issue by MarvinMissingVenlafaxine** [mdn/sprints#3334]
**Summary**
_What support task would you like completed by the team?_

I am trying to use the web audio api to do some processing on the audio included in a dash video.

var audioContext = new AudioContext();
var videoElement = document.getElementbyId('video'); //<- videolement has id="video"
var audioSourceNode = audioContext.createMediaElementSource(videoElement);
audioSourceNode.connect(audioContext.destination);

but doing the appove still seams to result in an empty audioSourceNode - and additional to that it prevents further videoplayback.

commenting the last to lines (mainly: audioContext.createMediaElementSource(videoElement) ) will result in normal playback behavior.

So basicly i am  just searching for help on how to use web audio api with dash video, cause it seams not to work, or it seams that the way i try so implement it is not the right way?

**Due Date**

soon as possible ;)  - please :)

**Additional context**
_Is there anything else we should know?_

I already searched via google, on stackoverflow and contacted the team of shaka-player cause i am using the shaka-player for playback, but they unfortunately also could not help and nowhere i could find tutorials/ help/ or even hints that could help me.

Many THANKS in advance.

**Comment by Elchi3** [comment]
Thanks for your issue! If this code doesn't appear in MDN docs, please consider asking for support on forums like stackoverflow in the future. Closing as I don't see any action to take for MDN docs.
