### ISSUE TITLE
HTML Element keygen has a broken link in the spec section

### ISSUE THREAD

**Issue by devilholk** [mdn/sprints#3337]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The documentation for HTML Element **keygen** have a broken link under the header **Specification**.
The current link is https://www.w3.org/TR/html52/forms.html#the-keygen-element which gives 404.

This is the URL for the page in question.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen

**Comment by mikoMK** [comment]
As <keygen> is obsolete I changed the spec macro to the last version it was include (HTML5.1)

**Comment by mikoMK** [comment]
@chrisdavidmills I think you didn't receive the notification from the above comment, because I added the @mention in a later edit. If I'm wrong I apologize for the double mention 😅

**Comment by chrisdavidmills** [comment]
Looks like a good resolution, thanks @mikoMK . And no worries on the double mention ;-)
