### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/block

### ISSUE THREAD

**Issue by jkimo2** [mdn/sprints#3341]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

on this page :
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions
when we click on the link for "Bloc", it sends us to this 404 page : 
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/block
instead of the correct page : 
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/bloc
without the "k"

**Comment by chrisdavidmills** [comment]
Fixed; the change should show up soon.

Did you know that you can edit MDN? It is a Wiki, so if you create an account and log in, you can fix things like this yourself. I'm just saying this so that if can save you time in future.

Thanks.
