### ISSUE TITLE
New documentation for Intl.DisplayNames

### ISSUE THREAD

**Issue by emwsc** [mdn/sprints#3346]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
Hi!
i want to add documentation for `Intl.DisplayNames` constructor and methods `of` and `resolvedOptions`. There's no existing pages for it.

**Comment by Elchi3** [comment]
Hey @emwsc! Sorry, I didn't see this earlier! Meanwhile the pages were created already.
