### ISSUE TITLE
/ru

### ISSUE THREAD

**Issue by blannamon** [mdn/sprints#3347]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/55991432/83946340-c4a43a00-a818-11ea-80c4-f1ffa4e192fc.png)
Orthographic mistake 

https://developer.mozilla.org/ru/docs/Web/HTTP/Overview

**Comment by Elchi3** [comment]
MDN pages can be edited by anyone, so you can fix this if you like. 
The MDN team doesn't maintain translations unfortunately.
See https://github.com/mdn/sprints#mdn-translations
