### ISSUE TITLE
Add slice(), substr() and substring()  JavaScript Examples 

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#335]
Add slice(), substr() and substring()  JavaScript examples to the slice(), substr() and substring() String method pages

**Comment by jmswisher** [comment]
@estelle @irenesmith @chrisdavidmills Can this be closed?

**Comment by chrisdavidmills** [comment]
I'm pretty sure we can, but I'll leave Irene/Estelle to close these.

**Comment by jmswisher** [comment]
Closing, since the examples are used in wiki pages.
