### ISSUE TITLE
Scrollbar custom style is not working on mac

### ISSUE THREAD

**Issue by oivinds** [mdn/sprints#3350]
<img width="888" alt="Skjermbilde 2020-06-08 kl  11 45 15" src="https://user-images.githubusercontent.com/1736478/84018383-4a8ec500-a980-11ea-88aa-27666b54bfbf.png">
# Request type
- [ X] Correction or update

# Details
Expected scrollbar to be purple and green

 https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

**Comment by wbamberg** [comment]
If you look at the compat table for `scrollbar-color` (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars#scrollbar-color) you'll see a disclosure arrow in the cell for "Firefox": if you click it you'll see this note:

> On macOS, you need to set the General > Show scroll bars setting in System Preferences to "Always" for this property to have any effect.

I just tried doing this and it worked for me then. Does this work for you too?
