### ISSUE TITLE
/en-US/docs/Web/HTML/Element/main

### ISSUE THREAD

**Issue by taliberlo** [mdn/sprints#3352]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
<In the HTML example there is a `<main role="main">` part,
But in the `Permitted ARIA roles` below, there are no roles permitted.
Please remove the role part from the example. Thanks!>

<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main>

**Comment by sideshowbarker** [comment]
Thanks for reporting this, and sorry for the delay in any action having been taken on it so far — but I’ve now opened https://github.com/mdn/content/pull/2410 with a fix.
