### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by ViceVersVice** [mdn/sprints#3353]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello. You have 404 on arithmetic operations chapter.
[link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators)
![404](https://user-images.githubusercontent.com/32034043/84179340-17365e00-aa86-11ea-8bd9-d7b1f803cb18.png)

**Comment by Elchi3** [comment]
Thanks for your issue! We've reorganized these docs to have separate pages for each operator now. This page wasn't redirecting yet, but now it does.
