### ISSUE TITLE
Broken Link in Examples section for WebDoc: Web Workers API 

### ISSUE THREAD

**Issue by HollyHop** [mdn/sprints#3356]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Found a broken link in WebDoc: Web Workers API  Examples 

Found on the Web Workers API page in the 'Examples': https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API#Examples

The broken link is for "Basic blocking/non blocking worker example": https://github.com/a0m0rajab/LearningQuest/JS/webWorkers
NOTE: "(Run the blocking example)" associated link is NOT broken.

.

**Comment by chrisdavidmills** [comment]
I've removed this example anyway. I don't think it is particularly very useful. Thanks for the heads up.
