### ISSUE TITLE
/ru

### ISSUE THREAD

**Issue by RapidRabbit1** [mdn/sprints#3358]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

There is an опечатка in the article on page:
https://developer.mozilla.org/ru/docs/Web/API/Event

 
![report](https://user-images.githubusercontent.com/63639705/84262772-df332780-ab26-11ea-8ce0-f949a9277bf6.jpg)

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
