### ISSUE TITLE
/en-US DATA URLs for images

### ISSUE THREAD

**Issue by yecril71pl** [mdn/sprints#3359]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

You can also use [DATA](https://tools.ietf.org/html/rfc2397) URLs for images.

[What is a URL? - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL)

**Comment by chrisdavidmills** [comment]
You are absolutely right. But this is supposed to be a really basic intro to what URLs are, and I think discussing data URLs would just serve to complicate the issue unnecessarily at this stage in a reader's learning.

**Comment by yecril71pl** [comment]
We give a short list of schemes that make sense in the context of a hypertext document.  We tell the readers that all other schemes should be avoided.  This is not true for the DATA protocol, which is commonly used and reasonably so.  So the reader ends up with false information rather than partial information.

**Comment by chrisdavidmills** [comment]
I've added a link to our Data URLs page in a "See also" section — https://wiki.developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#See_also

Can you direct me to where we say all other scheme should be avoided? I can't see that section. I agree it should be removed.

**Comment by yecril71pl** [comment]
https://wiki.developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#How_to_use_URLs

**Comment by chrisdavidmills** [comment]
Ah, I see it now; wording fixed.

**Comment by yecril71pl** [comment]
But the style is inconsistent.
