### ISSUE TITLE
MDN docs are incorrect about the default step value for seconds

### ISSUE THREAD

**Issue by mfreed7** [mdn/sprints#3360]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
The [MDN docs for the step attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-step) say this:

> The default stepping value for number inputs is 1, allowing only integers to be entered, unless the stepping base is not an integer. The **default stepping value for time is 1 second** (with 900 being equal to 15 minutes).

However, the spec for both [time](https://html.spec.whatwg.org/multipage/input.html#time-state-(type=time)) and [datetime-local](https://html.spec.whatwg.org/multipage/input.html#local-date-and-time-state-(type=datetime-local)) say this:

> The step attribute is expressed in seconds. The step scale factor is 1000 (which converts the seconds to milliseconds, as used in the other algorithms). The **default step is 60 seconds**.

At least Chrome implements 60s. Safari (desktop) doesn't support time or datetime-local, and Firefox doesn't show any pickers for either one, but at least for time, doesn't show seconds. That sort of jives with 60s.

**Comment by MendyBerger** [comment]
This seems to be fixed already

**Comment by chrisdavidmills** [comment]
@MendyBerger thanks for looking into this one. I felt that the existing page copy was a bit repetitious and possibly sounding contradictory, so I've had a go at rewriting it a bit. Can you let me know if you think the new version is any better?

**Comment by MendyBerger** [comment]
Oh no, it wasn't me that fixed it, I just looked into it and saw that its fixed already

**Comment by chrisdavidmills** [comment]
> Oh no, it wasn't myself that fixed it, I just looked into it and saw that its fixed already

Yeah, but it was still you who took the time to look into it ;-)

**Comment by MendyBerger** [comment]
@chrisdavidmills I think your changes are great, its much clearer now.

Also made some minor fixes on top of your changes

**Comment by chrisdavidmills** [comment]
@MendyBerger great, thanks! Looks like we can close this one now then.
