### ISSUE TITLE
[DevTools] Firefox 79 updates

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3362]
## Story

As a web developer, I want to know how to use the latest Firefox Developer Tools, so that I can develop and debug apps and websites properly using the latest tools.

## Acceptance criteria

The following bugs are dev-doc-complete, an entry to Firefox release notes is added, experimental features page is updated, and the content has been reviewed as needed.
1. - [x] [Switch to lazily turning a11y services on/off when using accessibility panel.](https://bugzilla.mozilla.org/show_bug.cgi?id=1602075)
2. - [x] [Style blocked network messages in Console](https://bugzilla.mozilla.org/show_bug.cgi?id=1629875)
3. -  [x] [Consider 4XX and 5XX requests as Error and display them even if the Request/XHR filters are disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1635460)
4. - [x] [Merge Message panel with the response panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1636421)
5. - [x] [Add Back and Forward navigation](https://bugzilla.mozilla.org/show_bug.cgi?id=1639425)
6. - [x] [Support mobile swipe/drag gestures in RDM](https://bugzilla.mozilla.org/show_bug.cgi?id=1621781)
7. - [x] [MDN link missing for status code](https://bugzilla.mozilla.org/show_bug.cgi?id=1645748)

Note: Bugs referenced for updating the What's New panel in Firefox 79: https://bugzilla.mozilla.org/showdependencytree.cgi?id=1646983&hide_resolved=0

**Comment by Elchi3** [comment]
@jmswisher please estimate this issue and indicate which task would be good for your yari test session.

**Comment by jmswisher** [comment]
Awaiting instructions for the Yari test, in order to know what would be a good task for it.

**Comment by jmswisher** [comment]
Split out the Debugger DDNs to make this a smaller US.

**Comment by jmswisher** [comment]
Item 1: Updated [Accessing the Accessibility Inspector](https://wiki.developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Accessing_the_Accessibility_Inspector) to include the information in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1602075#c28).

**Comment by jmswisher** [comment]
Item 5: Updated screenshot and text for Back and Forward buttons in [Connecting to a remote device](https://wiki.developer.mozilla.org/en-US/docs/Tools/about:debugging#Connecting_to_a_remote_device) section.

**Comment by jmswisher** [comment]
Item 4: Updated screenshots and descriptions in [Inspecting web sockets](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_web_sockets). Also deleted section for Messages tab, and merged its content into [Response tab](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Response_tab) section of the Request Details article.

**Comment by jmswisher** [comment]
Item 6: Added mention of drag events under "Enable/Disable touch simulation" in the [Controlling Responsive Design Mode](https://wiki.developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode#Controlling_Responsive_Design_Mode) section. Also, general copy-editing and clean-up of this article.

**Comment by digitarald** [comment]
@jmswisher I added some thoughts on how to document inline error preview: https://bugzilla.mozilla.org/show_bug.cgi?id=1581708#c5

**Comment by Elchi3** [comment]
Adding https://bugzilla.mozilla.org/show_bug.cgi?id=1645748 which is also marked ddn for the Fx79 cycle.

**Comment by jmswisher** [comment]
Item 3: Added a paragraph about this to the [Filtering by category](https://wiki.developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Filtering_by_category) section of Console Messages.

**Comment by jmswisher** [comment]
Item 2: Added blocked icon to the intro description of [Console messages](https://wiki.developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages)

**Comment by jmswisher** [comment]
Item 7: Updated the description about the [Headers tab](https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details#Headers_tab) of the request details.

**Comment by Elchi3** [comment]
Looks all done to me. Thank you, Janet! :+1:
