### ISSUE TITLE
Location Methods Documentaion

### ISSUE THREAD

**Issue by Weber-Frank** [mdn/sprints#3365]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/API/Location
on this page, I read
"Location.reload()
    Reloads the resource from the current URL. Its optional unique parameter is a Boolean, which, when it is true, causes the page to always be reloaded from the server. If it is false or not specified, the browser may reload the page from its cache."

if i follow the link Location.reload() to that page:
https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
I read
...
Syntax
location.reload();
...
without mentioning the optional parameter as described on the previous page.

So the question is which description is correct.

**Comment by Rumyra** [comment]
As per the specification there is no indication a boolean param is allowed to be passed into the `reload()` method... see https://html.spec.whatwg.org/multipage/history.html#location and https://html.spec.whatwg.org/multipage/history.html#dom-location-reload

The text mentioned is also not apparent on the landing page - seems it was updated on Jul 7th https://wiki.developer.mozilla.org/en-US/docs/Web/API/Location$compare?to=1633366&from=1631849

Closing this issue 👍
