### ISSUE TITLE
Getting & Setting classname

### ISSUE THREAD

**Issue by SunbeamRapier** [mdn/sprints#3368]
**Summary**
_What support task would you like completed by the team?_
Info on setting the classname for an element.

I used your code to change the classname on an element.  

[    let el = document.getElementById(tileName);
    console.log("HandleMouseOver: element retrieved with className ]" + el.className + "]");
    console.log("HandleMouseOver: element retrieved with ID ]" + tileName + "]");
    console.log("HandleMouseOver: element retrieved with className ]" + el.className + "]");
    if (el.className === 'linkcontainer'){
      console.log("Setting Element with new className ]" + el.className + "]");
       el.className = 'linkcontainerMouse';
       console.log("HandleMouseOver: element set with className ]" + el.className + "]");
    } else {
      console.log("HandleMouseOver: element did not have className 'LinkContainer'");
      el.className = 'linkcontainer';
      console.log("className set to [" + el.className + "]" );
    } 
]

and I can see in the Chrome development tools that it has changed the classname on the mousedOver tile.  

However, in the reactJS es6 jooks environment there are two issues:

a) the mousover event triggers the handleMouseOver function but does not immediately trigger the Chrome developer tools to show the log - this doesn't happen until I click somewhere.

b) the new classname has no effect at the time and is replaced by the classname in the code when the changes are rendered.

In your explanatory text and the code samples, there is never any context.  I think I may have to move the code to a new component but I am not sure I can prevent the exiting div code from overwriting the modified classname.

Any suggestions warmly received :-)

Rapier
Sydney, Australia

**Rationale**
_What problems would this solve?_

My Navbar would work as intended :-)

**Due Date**
_When would you like this task completed by?_
Everything in web development is always urgent :-)

**Additional context**
_Is there anything else we should know?_

A general comment: I find the language used throughout this site to be quite obtuse.  This is not unusual in the tech-world but it should be avoided.  Not everyone is a PLU (PersonLikeUs) and it is the responsibility of the communicator to convey information in a manner which can be easily understood by the recipient.  And, since you don't know the level of expertise of the recipient, that means assuming no knowledge.

In a development environment, code as you have provided for changing an element, needs to be included within a context which should always include the framework (reactJS in my case, but would be VueJS in my partner's case.  You have provided a straightforward example which I found easy to follow, and that doesn't happen all the time!

However, it doesn't work and that makes the exercise pointless.

The information should also be current (in your case, much of your reactJS code uses the now-deprecated classes) You do have a hooks module, though I think it could be better written, but the rest of the old Classes code will certainly confuse anyone new to the reactJS environment.  Not that the people at react.org are any more incline to maintain the currency of their technical writings :-(

In this setting classname example I imagine there are other modules which need to be included for the changes to take effect, but there is no information in the code sample to suggest what they might be.

**Comment by Elchi3** [comment]
Hi @SunbeamRapier, on which MDN page did you encounter this problem?

**Comment by SunbeamRapier** [comment]
Hi Florian

I am sorry but I don’t recall the article(s) which I thought were out of date.  However, perhaps they are not:  I note in one of your dopcuments that you say that the older “class” approach was srill required for complex functions, though you don’t say any more about this…

In general your documentation for react is very good - much better than the very-out-of-date and somewhat trivial examples on the react.org <http://react.org/> website…

Rapier

**Comment by Elchi3** [comment]
Thanks for following up! If you do encounter a problem with a specific MDN page, feel free to file an issue. General technical support is better suited at forums like Stackoverflow. Cheers!
