### ISSUE TITLE
Use Oxford English when referring to "English"

### ISSUE THREAD

**Issue by getsnoopy** [mdn/sprints#3370]
**Summary**
The label in the language selector that refers to "English" should use the `en` locale which means international English (also known as Oxford English or [Oxford spelling](https://en.wikipedia.org/wiki/Oxford_spelling)).

**Rationale**
On any MDN doc page, the language selector says "English", yet the locale in the address bar reads `en-US`. This is egregious, as English ≠ US English. In fact, US English is the most eccentric and esoteric version of English. The selector is especially editorialized considering the language selector has options for "Portuguese (European)" and "Portuguese (Brazilian)" separately. Practically every other English-speaking country in the world either uses Commonwealth/British English or Oxford English. In addition, people in almost every non-English-speaking country are taught Oxford English, and Oxford English is used by virtually every international organization (e.g., the UN, ISO, NATO, IEC, BIPM, WTO) and millions of people around the world. Given Mozilla's international audience, it only makes sense to use Oxford English.

**Audience**
Everyone who reads MDN in English.

**Proposal**
Users wouldn't have to do anything.

**Additional context**
There are scripts that do this automatically, so this should be a relatively effortless task once the effort of changing the "default language" to the `en` locale from the `en-US` locale is carried out.

**Comment by getsnoopy** [comment]
@atopal Was there a reason `en-US` was necessary compared to `en`? Either way, the locales not matching the content is a big no-no, so I don't think it's merely an issue of a "technical implementation detail".

**Comment by chrisdavidmills** [comment]
When MDN was first created, the decision was made to use US English on the site, to help promote some kind of consistency. This is a reasonable decision — most of the staff who work on MDN are based in the US, and web technologies themselves are also standardized on US English (note the spelling of "color" in CSS, for example).

(MDN won't be perfect US-English everywhere, as it is a wiki, and we have many community contributions from all over the world. Enforcing such consistenty would be very difficult, and also not a great use of time — keeping up with documenting the latest web technology changes and making the content understandable is a better use of our time.)

So given this, `en-US` is the most correct language tag to use for the content.

If anything, for correctness the listed language in the languages menu should be changed to "English (US)", but then again that would probably only serve to confuse people, and imply that we would also include separate UK English, Canadian English, locales, etc.

But they are not different enough to require different versions of an article. In cases like Brazilian Portugese and Portugese Portugese, the languages are different enough that different article versions would be appropriate.

Does this help at all?

**Comment by getsnoopy** [comment]
@chrisdavidmills That helps me understand the historical context. At the very least, however, the label should be changed to **English (US)**, as passing `en-US` off as canonical **English** is incorrect. I don't know that I'd agree it'd be more confusing given the fact that there are variants listed for other languages (such as Portuguese and Chinese).

I see a similar discrepancy with another language as well: Hindi. The label says **Hindi**, but the locale points to `hi-IN`. While there are other variants of Hindi, they're so minute in popularity that the narrowing to `hi-IN` is almost redundant. Anyway, either the label should **Hindi (India)**, or the locale should be changed to simply be `hi`.

**Comment by Elchi3** [comment]
@atopal the discussion now seems to have concluded to "the label should be changed to English (US)" which is a kuma issue (if we want to do this). Shall I move the bug back over?

**Comment by atopal** [comment]
We could for book keeping purposes, but I don't think it adds much value, and has the potential to be confusing, so we'd probably close this anyway.

**Comment by Elchi3** [comment]
Closing then.

**Comment by getsnoopy** [comment]
@atopal There are other locales that have the country variant specified in their labels despite being the only option; "Hindi (India)" is one. I don't know how adding detail to make the label match the actual locale people are going to see makes it confusing. If someone sees "English" from anywhere other than the US, they expect Commonwealth or Oxford English. Seeing anything else is jarring at best and considered to be incorrect at worst.
