### ISSUE TITLE
Typo on the Browser detection using the user agent page

### ISSUE THREAD

**Issue by daven97** [mdn/sprints#3371]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
There is a typo on the `Browser detection using the user agent` page. The word `waisted` should be spelled `wasted`.
![Screen Shot 2020-06-15 at 4 47 36 PM](https://user-images.githubusercontent.com/35749306/84713420-299e1500-af28-11ea-8cfc-838c319a054a.png)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
