### ISSUE TITLE
https://wiki.developer.mozilla.org/es/docs/Web/HTTP/Headers/Accept$history

### ISSUE THREAD

**Issue by mzapataj** [mdn/sprints#3372]
# Typo In Spanish Version
![typo_mozilla](https://user-images.githubusercontent.com/16918921/84723458-3bdd7a80-af4b-11ea-9fd7-31e3de394df4.png)

[In words highlighted](https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Accept#Directivas) would say "Cualquier".

**Comment by Elchi3** [comment]
Thanks for your report! Please note that MDN translations are maintained by the MDN wiki community. The few MDN staff don't speak Spanish. Closing this issue, see also https://github.com/mdn/sprints#mdn-translations
