### ISSUE TITLE
https://wiki.developer.mozilla.org/ru/docs/Learn/Server-side/Django/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5$history

### ISSUE THREAD

**Issue by BurIgor** [mdn/sprints#3374]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ 
![correctTranslation](https://user-images.githubusercontent.com/42617441/84730732-b33cf980-af9f-11ea-97be-5688611b8725.jpg)

] Correction or update

# Details

The sentence in the Russian translation can be translated more correctly.
In the sentence "_contained in the context variable inside the render () function above_", "**context**" is the name of the variable.

https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5

**Comment by Elchi3** [comment]
Thanks for your report! Please note that MDN translations are maintained by the MDN wiki community. The few MDN staff don't speak Russian. Closing this issue, see also https://github.com/mdn/sprints#mdn-translations
