### ISSUE TITLE
Broken link to WebAssembly.Global in the French documentation.

### ISSUE THREAD

**Issue by jonasgrilleres** [mdn/sprints#3375]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The documentation for WebAssembly in French seems to be missing a translation for the **WebAssembly.Global** page:
![image](https://user-images.githubusercontent.com/5982021/84770612-295d5280-afd8-11ea-9ac8-cf000236e1c6.png)

The page is accessible if you go to the English version and turn the locale to French. 
There is an issue in the path of the URL: it says `/Global_Objects/` instead of `/Objets_globaux/`.

The menu correctly links to: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/WebAssembly/Global

Although the actual page URL is: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Global

**Comment by jonasgrilleres** [comment]
Is there anything I can do anything to help fix this issue?

**Comment by Elchi3** [comment]
Thanks for your report!
I moved the page to https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/WebAssembly/Global

Note that we don't usually maintain translations and depend on the community on that, see https://github.com/mdn/sprints#mdn-translations
