### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by MelchiorIm3Tal** [mdn/sprints#3376]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

The article should be deleted.
Reason: The article is a stub without any usefull information. Additional there will not anyone add facts of the outdated Release 1.

https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Releases1

**Comment by chrisdavidmills** [comment]
OK, deleted; thanks for reporting
