### ISSUE TITLE
en-US/docs/Web/HTML/Element/input/date

### ISSUE THREAD

**Issue by peterbe** [mdn/sprints#3377]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
You get a SyntaxError in the Web Console.

<img width="1311" alt="Screen Shot 2020-06-16 at 10 15 33 PM" src="https://user-images.githubusercontent.com/26739/84847331-effc0580-b01e-11ea-9ae5-437390c9e30b.png">

**Comment by Elchi3** [comment]
I can't reproduce. Transient?

**Comment by peterbe** [comment]
I think @chrisdavidmills fixed it manually:
https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date$history
