### ISSUE TITLE
404 found to codePointAt

### ISSUE THREAD

**Issue by JulienPalard** [mdn/sprints#3378]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On this page : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/charCodeAt

In the sentence : vous souhaitez obtenir l'ensemble de la valeur, vous pouvez utiliser la méthode codePointAt().

The codePointAt link is giving a 404, it points to https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/codePointAt()

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
