### ISSUE TITLE
Connection HTTP header now requires all hop-by-hop headers

### ISSUE THREAD

**Issue by bmerry** [mdn/sprints#3380]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The [page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) on the Connection header currently says that the standard hop-by-hop headers do not need to be listed in the `Connection` header. However, the history section of [RFC 7230](https://tools.ietf.org/html/rfc7230#page-80) says (in explaining differences from RFC 2616):

> Exactly when "close" connection options have to be sent has been
   clarified.  Also, "hop-by-hop" header fields are required to appear
   in the Connection header field; just because they're defined as hop-
   by-hop in this specification doesn't exempt them.

**Comment by chrisdavidmills** [comment]
I've updated the description: https://github.com/mdn/content/commit/b5237cb867b2ed07688c4066c56ed9494dd459cc

**Comment by Afaqkhan260** [comment]
[wepcgamer.com](https://wepcgamer.com)
Here is one of the best gaming websites, which provides games in highly compressed size, and 100% working and tested games are here, so you guys just have to come and download your favorite games from this website.

Technology & Reviews and all about latest technology updates and CPU comparisons.
