### ISSUE TITLE
Web video codec guide math error

### ISSUE THREAD

**Issue by tlehman** [mdn/sprints#3383]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On the [Web video codec guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs), this calculation is off by about a factor of 10:

> A single frame of high definition (1920x1080) video in full color (4 bytes per pixel) is 8,294,400 bytes.
At a typical 30 frames per second, each second of HD video would occupy 248,832,000 bytes (~249 MB).
A minute of HD video would need 1.39 GB of storage.

That should be: 
A minute of HD video would need 14.93 GB of storage.

Since `248,832,000 bytes * 60 = 14.93 gigabytes`

**Comment by a2sheppy** [comment]
Fixed. I have _no idea at all_ where the number I came up with came from when I first wrote the article. It's possible I invented a new number system.

Thanks for reporting this!
