### ISSUE TITLE
Array Prototype Object Documentation has dissapeared

### ISSUE THREAD

**Issue by MelvinIdema** [mdn/sprints#3384]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The English version of the Array Prototype documentation has disappeared from the MDN web docs. While other languages are still available. It seems like this is accidental as it's about an important concept in Javascript.

https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype

**Comment by Elchi3** [comment]
Thanks for your issue! This change was made on purpose. See https://github.com/mdn/sprints/issues/2571

Unfortunately we dont maintain translations, so they are a bit behind.
