### ISSUE TITLE
Object.create Exceptions section typo

### ISSUE THREAD

**Issue by alan-jouhar** [mdn/sprints#3386]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The issue is with Exceptions currently it states:
A TypeError exception if the propertiesObject parameter is null or a non-primitive-wrapper object.

where instead it should be:
A TypeError exception if the proto parameter is null or a non-primitive-wrapper object.

the typo was introduced in  [this revision](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create$revision/1217601)

**Comment by Elchi3** [comment]
Hey thanks for your issue. I'm not sure your proposal is correct given `Object.create(null, undefined)` works and `Object.create(null, null)` doesn't. Can you elaborate?

**Comment by alan-jouhar** [comment]
Hello @Elchi3 
Sorry i made a typo as well in my proposal, here is what i think the Exceptions section should be:

A TypeError exception if the proto parameter isn't null or a non-primitive-wrapper object.

which was the correct documentation from[2010](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create$revision/16220) to [Mar 11,2017](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create$revision/1212675).

the current documentation suffers from two typos:

1-the first one was introduced in  [this revision](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create$revision/1217601)  which changed `proto` to `propertiesObject`.

2-the second one was introduced in [this revision](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create$revision/1402746) which deleted `n't` part of `isn't`.

[Here is es specs](https://tc39.es/ecma262/#sec-object.create) for the Object.create() which doesn't pay any attention to second argument.

**Comment by Elchi3** [comment]
Ah okay, that makes more sense, but I think "non-primitive-wrapper object" is very hard to understand and I don't see that mentioned in the ES spec. `proto` can't be just any object?

If it is correct, then slightly more understandable might be this:
A TypeError exception is thrown if the `proto` parameter isn't either [`null`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null) nor one of the [primitive wrapper objects](https://developer.mozilla.org/en-US/docs/Glossary/Primitive#Primitive_wrapper_objects_in_JavaScript).

What do you think?

**Comment by alan-jouhar** [comment]
Hello @Elchi3 

---------------------------------------

Here is my initial interpretation of Es specs:

`proto` has to be either:

1. `null`.
2. `object`.

if `proto` is **neither** of these a `TypeError` is thrown.

**But after experimenting with primitive wrapper objects**

Here is my current interpretation of Es specs:

`proto` has to be either:

1. `null`.
2. `object` excluding `primitive wrapper objects`.

if `proto` is **neither** of these a `TypeError` is thrown.

---------------------------------------

Your proposal:

`A TypeError exception is thrown if the proto parameter isn't either null nor one of the primitive wrapper objects.`

indicates that `proto` has to be:

1.`null`
2.`one of the primitive wrapper objects`

the `null` is correct but the second one `one of the primitive wrapper objects` isn't.

---------------------------------------

It would be very helpful if we could verify our conclusions with a third party.
we can agree on phrasing the sentence but it will be worthless if our interpretation of the specs is incorrect.

**Comment by Elchi3** [comment]
> `proto` has to be either:
> 
>     1. `null`.
> 
>     2. `object` excluding `primitive wrapper objects`.
> 
> 
> if `proto` is **neither** of these a `TypeError` is thrown.

Thanks, I think this is the correct definition. I got confused as well here, but testing proofs that this is the right thing to say. Maybe we can put it just like this in the docs as it was most clear (to me at least)

**Comment by alan-jouhar** [comment]
Perfect and thank you.

**Comment by Elchi3** [comment]
Updated https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Exceptions
