### ISSUE TITLE
URL needs to be update: Vulnerability Scanning Tools

### ISSUE THREAD

**Issue by rknmag** [mdn/sprints#3391]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

Vulnerability scanning Tools link is changed, it needs to be the following
https://owasp.org/www-community/Vulnerability_Scanning_Tools

**Comment by sideshowbarker** [comment]
Thanks — I’ve updated the URL in the https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Website_security article. (If you found it at an article other than that one, please indicate which article.)

**Comment by Elchi3** [comment]
Thanks @sideshowbarker
