### ISSUE TITLE
/de

### ISSUE THREAD

**Issue by fant12** [mdn/sprints#3392]
- [x] Correction or update

Misleading variable name in example script.

# Details
Please take a look at example script for german _onclick_ article page. The variable pointing to _#foo_ element is called _p_.

`var p = document.getElementById("foo");`

But this name is misleading, because _#foo_ is a _span_ element. It is not the paragraph element below.

https://developer.mozilla.org/de/docs/Web/API/GlobalEventHandlers/onclick

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
