### ISSUE TITLE
404 errors in MDN in-links

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#3395]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

We have a list of 20k in-links on MDN that lead to a 404, of those about 400 are on English pages that are not archived or under the /mozilla sub-tree. They still need filtering for relevancy, but using the number of in-links as a proxy, here's the prioritized list: https://docs.google.com/spreadsheets/d/13O8RGwk4gJVXruk3MChPhWHXiQfUWjoof9tldcGyMPw/edit#gid=1293202527

**Comment by Elchi3** [comment]
Thanks for your issue @atopal. I clicked on a few links in the sheet but I can't find the 404 links. 
Can you explain how this spreadsheet works and what exactly is the task to be done? We can maybe ask the community to help here, please try to explain it for a contributor that has no context.

**Comment by atopal** [comment]
Sure thing, I removed irrelevant columns from the linked spreadsheet. There are two that are immediately relevant: "First found at" lists the pages that have links on them that are broken (404). "URL" has the broken URLs. So, what you have to do is look at the source of the "First found at" page for the URL in "URL". 

So, for example, line 4 has the "First found at" page https://developer.mozilla.org/en-US/docs/Games/Anatomy. Looking at the source I search for "en-US/docs/Web/Apps/Fundamentals/User_notifications/Full_screen_api" (careful to leave out the https://developer.mozilla.org/ part, because the links on the page are relative). Now I can see that the broken link is in the sidebar under "APIs for game development". The next step would be to check out the macro and find out why it produces a broken link and ideally to fix it.
