### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by Maxteh** [mdn/sprints#3396]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

```
// The first parameter is the object to use as
// 'this', the second is an array whose
// members are used as the arguments in the function call
add.apply(o, [10, 20]); // 34
```
There must be  the function **'apply'**, instead call

web page
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations

**Comment by Maxteh** [comment]
Thank you for your response, I apologize for giving a bad link, the fact is that the English version has the same "typing error", the description specifies the "call" function, and should be "apply" according to the code. That is why I send you details in English with "typing error", but forgot to give correct link.
"Examples" => "this and object conversion"
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this](url)

**Comment by Elchi3** [comment]
Thanks for following up on this!

"function call" generally refers to how to call the `apply` function. It doesn't mean the `call` function in this sentence. So, I think the description is correct.
