### ISSUE TITLE
Some codes are not highlighted in Gamepad API pages

### ISSUE THREAD

**Issue by Rabios** [mdn/sprints#3399]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In ["Using the Gamepad API"](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) page on MDN docs,Both the complete code example and the code example above it aren't highlighted

Same also goes for ["Implementing controls using the Gamepad API"](https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API) page on MDN docs

Please check all the page and fix it

Links
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API
https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API

That's all,Thanks for reading!!!

**Comment by chrisdavidmills** [comment]
Fixed; the code blocks were not markup up correctly, and some of them had weird styles all over them.

Thanks for reporting.

**Comment by Rabios** [comment]
Welcome.
