### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context$history

### ISSUE THREAD

**Issue by efafelix-multisyscorp** [mdn/sprints#3400]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

The page says "using display: flow-foot" instead of "using display: flow-root"

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context

**Comment by wbamberg** [comment]
Fixed, thanks for filing!
