### ISSUE TITLE
/zh-CN为什么调用了包含两个数的方法，数组的下标值也是正确的，但是就是取不到两边的数

### ISSUE THREAD

**Issue by AndyCheung-Hub** [mdn/sprints#3401]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

[QQ录屏20200623115636.zip](https://github.com/mdn/sprints/files/4817077/QQ.20200623115636.zip)

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
