### ISSUE TITLE
Update @viewport docs to say it's going away

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3404]
As per https://github.com/w3c/csswg-drafts/issues/4766, the [@viewport](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@viewport) at-rule isn't supported in any major browsers at the moment, and is due to be removed from the spec. We should update our docs accordingly.

See also https://github.com/mdn/browser-compat-data/issues/6213.

**Comment by chrisdavidmills** [comment]
To start with, I've had a play with putting the deprecated notice on top of https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@viewport, plus a note to point to the standards track removal discussion.

I'll put this into the next sprint, where I'll finalise that work, and update the BCD accordingly.

**Comment by karlcow** [comment]
This statement is not completely true. Blink has a kind of support for it as they use it in their own default css, **but** I'm not sure this is accessible to web developers. 
> the @viewport at-rule isn't supported in any major browsers at the moment

https://bugs.chromium.org/p/chromium/issues/detail?id=1101182

Probably a test would help understand if it's still active in Chrome or not.

**Comment by rachelandrew** [comment]
I've been looking into this and there is now a note on the Chrome bug referenced above:

> "@viewport was never shipped to authors (apart from via an experimental flag in Chrome) and is only parsed used as an implementation detail for the default viewport on mobile."

Do we need the big BCD table for all the different descriptors? Or would dropping this down to one line for viewport be reasonable at this point. What else needs doing on the MDN page when something is being removed @chrisdavidmills ?

It does still appear to exist in the Editors Draft of the spec, so presumably that update hasn't been made yet.

**Comment by chrisdavidmills** [comment]
@rachelandrew This is a good question. The page already has a deprecated notice up top, and I'd support you replacing the BCD with a single line — the different rows are all pretty similar anyway. I think that would be sufficient, once the removals are actually done.

**Comment by rachelandrew** [comment]
@chrisdavidmills BCD for this is now merged.

**Comment by chrisdavidmills** [comment]
@rachelandrew cool, in that case it should appear soon enough on the page. I'll close this one.
