### ISSUE TITLE
404 https://developer.mozilla.org/zh-CN/docs/Web/Media/Overview

### ISSUE THREAD

**Issue by EHG613** [mdn/sprints#3405]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/zh-CN/docs/Web/Media/Overview
404 ERROR

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
