### ISSUE TITLE
404 Key Not Found error on bitwise operators page

### ISSUE THREAD

**Issue by prov-ShawnChambless** [mdn/sprints#3413]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The expressions-bitwiseoperators.html page appears to be missing. The response is:
```
Code: NoSuchKey
Message: The specified key does not exist.
Key: pages/js/expressions-bitwiseoperators.html
RequestId: BWFY6RFN9M4KEJ5M
HostId: 9PyJwOyWPciSQJ7Q4yk+ZVTra8wTScEf0B2pJkMmM7B+uFKPJz2eqdnjH9SRAsriAERq1zZU4uY=
```
![image](https://user-images.githubusercontent.com/43181270/85580425-91bbbd80-b5f0-11ea-9c16-16bb07e72f2c.png)

Link to the page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators

**Comment by Elchi3** [comment]
Thanks, fixed! This page will soon be split up, because we now organized each operator to have their own page.
