### ISSUE TITLE
[HTML] allow-top-navigation-by-user-activation, Fx 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3414]
## Story

As a web developer, I want to know how to about the new `allow-top-navigation-by-user-activation` iframe sandbox keyword, so that I can properly implement sandboxing of untrusted third-party content.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [ ] [Add attribute allow-top-navigation-by-user-activation to iframe sandbox](https://bugzilla.mozilla.org/show_bug.cgi?id=1359867)

**Comment by Elchi3** [comment]
@chrisdavidmills do you reckon this would be a good ddn for your yari test session?

**Comment by chrisdavidmills** [comment]
@Elchi3 looking at this, it is already documented for the most part, and will probably only require a small BCD change, and a rel note. Would something more substantial be better? Or do you think we should keep it small?

**Comment by Elchi3** [comment]
Oh, I didn't realize it is already documented. I will find something else then. Please estimate this issue, though.

**Comment by chrisdavidmills** [comment]
> Please estimate this issue, though.

Done.

**Comment by chrisdavidmills** [comment]
* PR created to update compat data: https://github.com/mdn/browser-compat-data/pull/6359
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#HTML

**Comment by Elchi3** [comment]
Well done! :+1:
