### ISSUE TITLE
[HTML] Implicit rel="noopener" on links with target="_blank", Fx 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3416]
## Story

As a web developer, I want to know how to request an opener relationship using `rel="opener"` on `<a> `elements that use `target="_blank"` to open the link into a new window or tab.

- https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Implicit_relnoopener_on_links_with_target_blank
- https://www.fxsitecompat.dev/en-CA/docs/2020/target-blank-on-anchors-now-implies-rel-noopener/

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Make target=_blank on a/area elements imply rel=noopener by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1522083)

**Comment by Elchi3** [comment]
@chrisdavidmills please estimate and indicate if this would qualify for a yari test session.

**Comment by chrisdavidmills** [comment]
Estimated.

And yes, I think this is a better tester one for Yari — it includes a BCD update, but also some description changes required to the a and area pages.

**Comment by chrisdavidmills** [comment]
OK, work done:

* Added rel note: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#HTML
* Updated pages that need info on it changing:
  * Removed section about this on our [Experimental features page](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features), now that it is shipped.
  * Added description of the feature to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a ("Attributes", and "Security and privacy" sections)
  * Added description of the feature to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area ("Attributes" section)
* Submitted a PR to add compat data about it: https://github.com/mdn/browser-compat-data/pull/6366

**Comment by annevk** [comment]
Note that I suspect this will impact `Linking to another page with target="_blank" will run the new page in the same process as your page.` too.

**Comment by chrisdavidmills** [comment]
@annevk ah, yes. You think I should indicate that this will no longer happen in newer browsers?

**Comment by annevk** [comment]
Yeah and with Fission / Chrome's site isolation it's different still. Perhaps we shouldn't say much about processes?

**Comment by Elchi3** [comment]
@chrisdavidmills can you follow up on this?

**Comment by chrisdavidmills** [comment]
> Yeah and with Fission / Chrome's site isolation it's different still. Perhaps we shouldn't say much about processes?

Sounds like a proper can of worms. I've just deleted that note.

**Comment by Elchi3** [comment]
Thanks, Chris!
