### ISSUE TITLE
[DevTools] Firefox 79 updates for Debugger

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3423]
# Story

As a web developer, I want to know how to use the latest Firefox Developer Tools, so that I can develop and debug apps and websites properly using the latest tools.

# Acceptance criteria

The following bugs are dev-doc-complete, an entry to Firefox release notes is added, experimental features page is updated, and the content has been reviewed as needed.
1. - [x] [Rename UI references of "blackbox" to "ignore" in Debugger](https://bugzilla.mozilla.org/show_bug.cgi?id=1642811)
2. - [x] [Inline preview for exceptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1581708)
3. - [x] [Provide option to display browser title tooltips for ObjectInspector > Reps](https://bugzilla.mozilla.org/show_bug.cgi?id=1631545)
4. - [x] [Add "Restart frame"](https://bugzilla.mozilla.org/show_bug.cgi?id=1594467)

**Comment by jmswisher** [comment]
For Item 1: Articles that use "blackbox" or "black box":
- https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints
- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Black_box_a_source
(I'm planning to use this for the Yari user testing.)

**Comment by jmswisher** [comment]
Item 1: 
Updated:
- [UI Tour](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour)
- [How to](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to)
- [How to ignore a source](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Black_box_a_source), also changed slug
- [Set event listener breakpoints](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints)

Archived [Debugger settings](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Settings)

**Comment by jmswisher** [comment]
Item 4: Added to the [Call stack](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Call_stack) section of the UI Tour article.

**Comment by jmswisher** [comment]
Item 3: I decided not to explicitly document this feature. It will be easily discoverable by users; nobody's going to learn about it from reading documentation.

**Comment by jmswisher** [comment]
Item 2: Added a screenshot and description of this to [Breaking on exceptions](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Breaking_on_exceptions)

**Comment by Elchi3** [comment]
Thanks Janet! :+1:
