### ISSUE TITLE
Misc changes, Fx 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3424]
## Story

As a web developer, I want to know about latest miscellaneous web platform changes in Firefox.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Add use counter and deprecation warning for STIXGeneral fonts](https://bugzilla.mozilla.org/show_bug.cgi?id=1630935)
2. - [x] [[mediaqueries-5] Remove prefers-color-scheme: no-preference.](https://bugzilla.mozilla.org/show_bug.cgi?id=1643656) and [remove no-preference from inspector color scheme simulation](http://bugzil.la/1642366)
3. - [x] [Don't expose the `DOMWindowClosed` event to content](http://bugzil.la/1557407)
4. - [x] [FileReader should dispatch loadstart asynchronously](http://bugzil.la/1502403)
5. - [x] [CanvasPattern.setTransform does not support DOMMatrix](http://bugzil.la/1565997)

**Comment by Elchi3** [comment]
@chrisdavidmills are you okay with taking this on? Does it seem to be reasonably sized? I reckon these all small items, but please add your estimation. Thank you!

**Comment by chrisdavidmills** [comment]
These are tiny little changes; I reckon 1 point for the lot.

**Comment by chrisdavidmills** [comment]
Not going the STIX general fonts thing. It's a really minor change, and currently behind a pref.

**Comment by chrisdavidmills** [comment]
For `prefers-color-scheme: no-preference`:

* Added a rel note: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#CSS
* Added browser-compat data to signal when the removal happened: https://github.com/mdn/browser-compat-data/pull/6360

**Comment by chrisdavidmills** [comment]
`DOMWindowClose` event (and others) removed:

* Added rel note: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#APIs

**Comment by chrisdavidmills** [comment]
`FileReader loadstart` async dispatch:

* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#APIs 
* Note added to BCD: https://github.com/mdn/browser-compat-data/pull/6364

**Comment by chrisdavidmills** [comment]
`CanvasPattern.setTransform()` `DOMMatrix` support:

* Aded rel note: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#APIs
* Updated pages to add appropriate extra information:
  * https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern
  * https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern/setTransform
* Submitted compat data update: https://github.com/mdn/browser-compat-data/pull/6365

**Comment by Elchi3** [comment]
Well done, Chris!
