### ISSUE TITLE
Example for HTMLImageElement height uses image with weird dimensions that doesn't match up with the text describing what will happen 

### ISSUE THREAD

**Issue by DemiImp** [mdn/sprints#3426]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The example image on the page is 200 x 199 for the small image and 400 x 398 for the large image.  The description on the page talks about setting the width to 200/300/400px (instead of the height?)... but it's extra confusing because the height shown on the page is one off from the text that describes what is going to happen and looks like a bug.  I suggest you either make the image square (200 x 200 and 400 x 400)... or alter the text to talk about the image height being set to 200/300/400 and alter the example to set the height to 200/300/400 instead of the width to those dimensions.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/height

**Comment by leslitagordita** [comment]
Grabbing this one for WTD writing day. Could not easily find where this issue is represented on a sprint board.

**Comment by leslitagordita** [comment]
Added an update that addresses this issue:
* Resized images to have a 1:1 aspect ratio to make the article example easier to understand. https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/height

**Comment by chrisdavidmills** [comment]
LGTM; thanks @leslitagordita
