### ISSUE TITLE
/pt-BR muda cor do Titudo e Paragrafo

### ISSUE THREAD

**Issue by olimpooo** [mdn/sprints#3427]
Não estou conseguindo deixar o título(Minha página de testes) em azul e o parágrafo(Texto do paragrafo) verde ao clicar no Botao criado, nao estou conseguindo criar o codigo para mudar as cores alguem poderia ajudar.

<html>
<head>
<meta charset="utf-8">
<title>Titulo</title>
<style>
p {
font-family : Times New Roman;
font-size : 14px;
}
</style>
<script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(“button”).click(function(){
$(“div”).fadeToggle(1000);
});
document.getElementById('Minha página de testes').style.color ='green';
});
</script>
</head>
<body>
<button>CLIQUE</button><br><br>
<font color="red" size="15px"><b><center><i>Minha página de testes</font>
</center></i></b><h1></h1>
<div style=color:blue; padding:16px;”>
<h2><p>Texto do paragrafo</p></h2>
</div>
</body>
</html>

**Comment by Elchi3** [comment]
Thanks for your issue, unfortunately we don't maintain translations. https://github.com/mdn/sprints#mdn-translations
