### ISSUE TITLE
WebAssembly changes, Fx 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3428]
## Story

As a web developer, I want to know about the latest WASM enhancements, so that I can run code written in multiple languages on the web.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Bulk-memory-operations: Ship it](http://bugzil.la/1528294)
2. - [x] [Reference types: Ship it](http://bugzil.la/1637884)
3. - [x] [WebAssembly threads](https://bugzilla.mozilla.org/show_bug.cgi?id=1389458), see also https://www.chromestatus.com/features/5724132452859904 for an explanation and see https://bugzilla.mozilla.org/show_bug.cgi?id=1648685 that enabled this in Fx79

**Comment by Elchi3** [comment]
@chrisdavidmills Same story as last time: I reckon this needs some mentioning in the Wasm docs, but not extensive docs as we don't provide such detailed level of WebAssembly's text format on MDN. However, it should be mentioned in release notes and hacks post.

Please estimate and let me know if you could take this.

**Comment by chrisdavidmills** [comment]
About a point I reckon.

**Comment by chrisdavidmills** [comment]
Hrm, I've added rel notes for these: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#WebAssembly, but I'm not really sure what to write about them , so I've asked Luke for some help.

**Comment by chrisdavidmills** [comment]
Bulk memory operations:

Small description added to https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#Bulk_memory_operations

**Comment by chrisdavidmills** [comment]
Reference types:

* Rel note added: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#WebAssembly 
* Brief description added to https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#Reference_types

**Comment by chrisdavidmills** [comment]
Threads:

* Rel note added: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#WebAssembly 
* Brief description added to https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#WebAssembly_threads

**Comment by Elchi3** [comment]
Well done! :100:
