### ISSUE TITLE
WebExtensions, Firefox 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3429]
## Story

As a WebExtensions developer, I want to be informed about the latest API changes and read up-to-date reference docs.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [WebExtension API to 'warm up' a tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1402256)
2. - [x] [Flip the preference to enable the new browser.storage.sync implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1634615)

**Comment by Elchi3** [comment]
@caitmuenster and @kewisch can you let us know about the changes to document for Firefox 79 in WebExtensions land?
Also, given Richard isn't contracting with you anymore, who will document/review docs from your side in the future? Thanks!

**Comment by caitmuenster** [comment]
Hey @Elchi3! It looks like we only have one bug tagged dev-doc-needed for the WebExtensions API: https://mzl.la/2VXsOwV

I had talked with @chrisdavidmills about how to handle documentation updates/approvals without Richard. If we maintain a low volume of changes, can @wbamberg or some of the other MDN writers help us out with the writing? Our engineers are happy to review documentation updates. I can also help out where I can but my technical knowledge is fairly limited.

**Comment by wbamberg** [comment]
>  If we maintain a low volume of changes, can @wbamberg or some of the other MDN writers help us out with the writing? 

Yes. [We did this for 78](https://github.com/mdn/sprints/issues/3285) and it was fine for me. Also I asked for and got helpful review feedback from the engineering team for the 78 updates.

If it gets to be more than a few days' work in each release, we'd need to talk about how to resource it.

**Comment by Elchi3** [comment]
Thanks @caitmuenster! 

I haven't looked at the one DDN we have for Fx79. I guess "API" is quite an overloaded term, so maybe "WebExtension API to 'warm up' a tab" isn't about an entire new API that would require a many new pages, etc. If Will is fine to do this work this time around, then let's do this.

Also, I don't know how and when the WebExtension team tags bugs "dev-doc-needed". Sometimes they get added quite late in the cycle, but maybe 79 really is a light cycle and we only have this one change to the public APIs :)

> If it gets to be more than a few days' work in each release, we'd need to talk about how to resource it.

Exactly this is the situation that we will probably face sooner or later.

**Comment by caitmuenster** [comment]
@Elchi3, what schedule would you prefer? I can certainly help coordinate with the engineers.

**Comment by Elchi3** [comment]
@caitmuenster We plan our sprints at the end of every month (or rather at the end of every Firefox cycle). 
So, last week, I collected all ddn items for Fx79 (including this issue). For the next round, I would file user stories and plan time in the week of July 20 (and it would take into account all items for Fx80). If the Fx80 bugs aren't tagged by then, I would miss them for the initial docs planning for the Fx80 cycle.
Does that make sense? Happy to talk this through some more if needed.

**Comment by caitmuenster** [comment]
Quick update: we just added a dev-doc-needed for [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1637166#c6). 

Sorry @Elchi3 I will respond more fully to your comment in a little bit.

**Comment by Elchi3** [comment]
> Quick update: we just added a dev-doc-needed for [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1637166#c6).

More info also here https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/
(we can reference this post from the Fx79 hacks blog on July 28)

**Comment by Elchi3** [comment]
This bug now also shows up as ddn for Fx79: https://bugzilla.mozilla.org/show_bug.cgi?id=1634615

**Comment by wbamberg** [comment]
The storage.sync DDNs are done:
https://bugzilla.mozilla.org/show_bug.cgi?id=1637166#c7

The tabs.warmup() one is waiting for engineering review, but if I don't have it by the time I'm back in the "office" I'll close that one too.

**Comment by wbamberg** [comment]
I got a review from Tomislav for the warmup() one https://bugzilla.mozilla.org/show_bug.cgi?id=1402256), so closing that too.

**Comment by caitmuenster** [comment]
Awesome, thank you @wbamberg! I think that wraps WebExtensions up for 79.
