### ISSUE TITLE
Suggested fix - Beginner's Guide to Media Queries

### ISSUE THREAD

**Issue by kar358** [mdn/sprints#3433]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

 
   On the documentation's CSS Tutorial Article "Beginner's Guide to Media Queries", I had problems with your Active Learning walkthrough for page layout. Specifically, I was unable to recreate the described functionality for responsive viewports (@media screen and (min-width: 40em)) in my developer tools. Changing the em value had no effect on the rendered page.

The problem was fixed by adding a single tag to the html head: <meta name='viewport' content='width=device-width">
For reference, I was using the Chrome Developer tools when the problems occurred. Although I am new to CSS, a few sources suggested that this meta tag is considered a "best practice" for responsive design, so I hope you will consider adding it to the walkthrough.

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries

**Comment by chrisdavidmills** [comment]
@kar358 yes, I agree with you here. I'm actually surprised that we don't already talk about the viewport meta tag in that article.

I've updated the active learning aexamples as suggested, and added a section about it:

https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries#The_viewport_meta_tag

And I've changed a few of the earlier simple media query examples so they are more likely to be viewable on desktop.

do you think this needs anything else?

**Comment by kar358** [comment]
> @kar358 yes, I agree with you here. I'm actually surprised that we don't already talk about the viewport meta tag in that article.
> 
> I've updated the active learning aexamples as suggested, and added a section about it:
> 
> https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries#The_viewport_meta_tag
> 
> And I've changed a few of the earlier simple media query examples so they are more likely to be viewable on desktop.
> 
> do you think this needs anything else?

Chris,
No, it looks great to my (admittedly inexperienced) eyes. Thanks!
