### ISSUE TITLE
U - Fix CSS linter errors: data.examples/missing-example-h3

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3434]
The [linter's spec for data.examples](https://github.com/mdn/stumptown-content/blob/master/project-docs/linter-spec.md#dataexamples) expects that each example under the H2 "Examples" section lives under its own H3 heading.

The linter raises "data.examples/missing-example-h3" if a page doesn't appear to meet this expectation.

Currently we have 87 "data.examples/missing-example-h3" errors. They are listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1JQIgRB978bEKHFmQoAjY4stddDdbaFAULj_TOK2jYwc/edit#gid=1099195239), in the "data.examples/missing-example-h3" tab.

Usually, these are where there is only one example, and it has been placed directly under the "Examples" H2. So to fix it we need to:

* come up with a useful descriptive name for the example
* make that the H3
* move any subheadings to the next level down (preferably following the convention in https://github.com/mdn/sprints/issues/3139#issuecomment-658286594).
* if necessary, adjust the argument to the `{{EmbedLiveSample}}` macro

# Acceptance criteria

- [ ] There are zero "data.examples/missing-example-h3" errors reported by the linter, when run against https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by rachelandrew** [comment]
There are a few in here that direct people to another page for examples (https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/animation-delay). Not sure what to do with these.

**Comment by wbamberg** [comment]
Not sure if my opinion is relevant, but since I filed this: IMO, reference pages shouldn't send people off somewhere else for examples.

If I'm looking at the reference page for an item I want to see directly relevant examples right there, not have to visit another (more generic) page to hunt them down. In the case of `animation-delay`, the linked page https://wiki.developer.mozilla.org/en-US/docs/CSS/CSS_animations doesn't actually include any examples of `animation-delay`, so it would be doubly frustrating.

(This points to another problem with this practice, which is that https://wiki.developer.mozilla.org/en-US/docs/CSS/CSS_animations doesn't know that other pages are relying on it to include particular examples, so it's easy for an author to remove them and inadvertently break the linking page.)

**Comment by rachelandrew** [comment]
@wbamberg I agree. I'll see if there are obvious ones to copy over, if not I'll raise issues to add examples to missing example pages.

**Comment by rachelandrew** [comment]
I have fixed all of these other than a couple of drafts, and a 404 which I've marked in the spreadsheet.

I've made quite a few examples along the way for pages which referred to other pages for examples.

**Comment by rachelandrew** [comment]
@chrisdavidmills there doesn't seem to be any in review status but you can take a look at this.

**Comment by chrisdavidmills** [comment]
This looks great; thanks @rachelandrew !
