### ISSUE TITLE
U - Fix CSS linter errors: prose.see_also/expected_heading

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3435]
Some (most) CSS pages must include "prose.see_also" section, and the linter checks this. The linter doesn't check that this section has any particular structure: just an H2 heading "See also" with a freeform prose description under it. In practice this section tends to consist of a `<ul>` of links to related pages.

It's a very good place to provide cross-links to the Learn area or other tutorial content from the reference documentation.

There are currently 148 pages under Web/CSS that are expected to have a "See also" H2 and that omit it. They are listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1JQIgRB978bEKHFmQoAjY4stddDdbaFAULj_TOK2jYwc/edit#gid=1099195239) in the "prose.see_also/expected-heading" tab.

# Acceptance criteria

- [ ] There are zero "prose.see_also/expected_heading" errors reported by the linter, when run against https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by wbamberg** [comment]
According to the [spreadsheet](https://docs.google.com/spreadsheets/d/1JQIgRB978bEKHFmQoAjY4stddDdbaFAULj_TOK2jYwc/edit#gid=1575104775) there are 255 pages that generate an error about `prose.see_also`.

However, this includes prefixed properties, some of which we might want to archive. So, as in all these stories, it makes sense to work on the unprefixed properties first, while we work out which prefixed ones we might want to archive.

The reason we're seeing this error is that we've asked for almost all page types to contain a section "See also" at the end, that lists useful related links. Most of our pages already do this, but not all.

There's no special structure mandated for this section by the linter, but it ought to be a UL of links to related pages.

This is actually a relatively interesting story, since we'll have to think of relevant links to add. In particular I think this could be a great way to increase cross-linking into the Learn area and tutorial content generally from our reference docs.

It's possible that we will need to make this section optional if there are pages that really legitimately don't have any related links. But in any event it would be worth reviewing the pages that currently omit this section, since I expect that in many cases it would be a useful thing to add.

**Comment by rachelandrew** [comment]
@chrisdavidmills I have an open PR for this https://github.com/mdn/content/pull/286 I thought you had said we could merge our own PRs but don't think that is the case, or I'm failing to GitHub.

I did the other half pre-code freeze in the wiki. This was much faster.

**Comment by chrisdavidmills** [comment]
Nice one Rachel, thanks! Yes, you should be able to self-merge. I don't know what is going wrong here.
