### ISSUE TITLE
U - Fix CSS linter errors: prose.syntax/expected-heading

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3438]
Some (most) CSS pages must include "prose.syntax" section, and the linter checks this. The linter doesn't check that this section has any particular structure: just an H2 heading "Syntax" with a freeform prose description under it. In practice this section does follow some conventions, which tend to vary from one type of page to another.

Currently there are 30 pages under Web/CSS that are expected to have a "Syntax" H2 and that omit it. They are listed in the 
[spreadsheet](https://docs.google.com/spreadsheets/d/1JQIgRB978bEKHFmQoAjY4stddDdbaFAULj_TOK2jYwc/edit#gid=1099195239) in the "prose.syntax/expected-heading" tab.

# Acceptance criteria

- [x] There are zero errors reported by the linter for the "prose.syntax" ingredient, when run against https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by wbamberg** [comment]
I've confirmed that we get 0 of these errors now. Thanks @a2sheppy !

**Comment by a2sheppy** [comment]
I fixed a few other errors along the way; should help other people with their work. Corrected some "node after live example" errors (not all of them I encountered, but later on I got into it a bit), a few other missing heading or incorrect heading level things, stuff like that.
