### ISSUE TITLE
U - Fix CSS linter errors: data.permitted_properties? errors

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3441]
The linter will check that pages correctly include this ingredient.

# Acceptance criteria

- [x] There are zero errors reported by the linter for the "data.permitted_properties?" ingredient, when run against https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by ddbeck** [comment]
This is blocked by https://github.com/mdn/stumptown-content/issues/498.

**Comment by wbamberg** [comment]
This is done.
