### ISSUE TITLE
/en-US

### ISSUE THREAD

**Issue by chrisrob** [mdn/sprints#3442]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

String.prototype.split()

The line: "If limit is 1, [str] is returned" should be removed.

If the limit is 1 then the returned array contains 1 element with the portion of the string up to the 1st occurrence of the separator.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by Elchi3** [comment]
Looks like it was fixed already: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split$compare?locale=en-US&to=1630956&from=1630583
