### ISSUE TITLE
Box model example description does not match content

### ISSUE THREAD

**Issue by adebayo10k** [mdn/sprints#3443]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
It looks like there's some incorrect code for the 'Playing with box models' example. The exercise description refers to two boxes, the code is for some paragraphs. Thanks.
The same issue applies to the 'Margin' example.

**Comment by chrisdavidmills** [comment]
Hi @adebayo10k !

I'm a bit confused by this. The descrition does refere to two boxes, yes, and the HTML source code in the editable example is as follows:

```
<div class="box">I use the standard box model.</div>
<div class="box alternate">I use the alternate box model.</div>
```

Which looks like two boxes to me. So I'm not sure sure what the problem is.

**Comment by adebayo10k** [comment]
Hi @chrisdavidmills ,
Thanks for checking this out. So, the html I see on my laptop is this:
```
<p>I am a paragraph. A short one.</p>
<ul>
  <li>Item One</li>
  <li>Item Two</li>
  <li>Item Three</li>
</ul>
<p>I am another paragraph. Some of the <span class="block">words</span> have been wrapped in a <span>span element</span>.</p>
```
Strangely, on my mobile it _is_ the correct two boxes, as you describe. The URLs are the same.
It's the same code and output that was used correctly earlier on the page under 'Examples of different display types'.
I've attached a screenshot. Hope that helps. Wondering, is different **content** served on these pages based on device type? I know that wouldn't make much sense, but can't think of anything else. Thanks.
![MDN_#3443](https://user-images.githubusercontent.com/48807885/86018911-dba40980-ba1d-11ea-9b58-560f9bb6673a.png)

**Comment by chrisdavidmills** [comment]
Ah, so it looks like it is showing the wrong live example in that position on your browser. That is strange!

What happens when you do a force refresh on the page (Ctrl + Shift + R)?

**Comment by adebayo10k** [comment]
@chrisdavidmills ,

I'm happy to close this issue as resolved. The page is now showing the examples content correctly, following a reboot (sorry).

**Comment by chrisdavidmills** [comment]
OK, cool. I am glad you are now seeing this correctly. I was starting to get worried ;-)

All the best.
