### ISSUE TITLE
beforeunload event documentation: add details about XHR/sendBeacon

### ISSUE THREAD

**Issue by xyz0815** [mdn/sprints#3444]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

beforeunload event:
Add information about not being able to send async XHR and mention/set a link to navigator.sendBeacon()

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by jadjoubran** [comment]
Hey @xyz0815 

On the [Navigator.sendBeacon()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) page, there's now a recommendation to avoid using `sendBeacon` on the **beforeunload** event. The recommendation is to use the `visibilitychange` event.

**Comment by chrisdavidmills** [comment]
I've added notes to the `onbeforeunload` and `beforeunload` pages to mention that you shouldn't use them with `sendBeacon()`, and pointed to the `sendBeacon()` page for more details. I think we can close this now.
