### ISSUE TITLE
Geolocation API altitude reference is WGS84, not mean sea level

### ISSUE THREAD

**Issue by VladimirVLF** [mdn/sprints#3445]
Altitude reference is wrongly given as mean sea level in [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/altitude)

Following the link to the specification, altitude reference there is WGS84, see [specs](https://w3c.github.io/geolocation-api/#dom-geolocationcoordinates-altitude)

MSL and WGS84 are two different reference systems. I think documentation should be updated to avoid misunderstandings.

**Comment by mconca** [comment]
Correct the altitude reference as requested.  Thanks for flagging this.

https://wiki.developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/altitude$compare?locale=en-US&to=1649919&from=1594881

**Comment by mconca** [comment]
@chrisdavidmills This issue can be closed now.

**Comment by chrisdavidmills** [comment]
Great, thanks @mconca !
