### ISSUE TITLE
IntersectionObserver: documentation about isIntersecting respecting threshold

### ISSUE THREAD

**Issue by VladislavStechr** [mdn/sprints#3447]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on: 
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Thresholds

# Details

There is an issue with IntersectionObserver documentation in 'Thresholds' section: 
> If isIntersecting is true, the target element has become at least as visible as the threshold that was passed. If it's false, the target is no longer as visible as the given threshold.

According to https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/isIntersecting `isIntersecting` doesn't respect threshold.

**Comment by jchimene** [comment]
I'm not seeing the issue.
There are 5 instances of the word `isIntersecting`, none of them in the context of the referenced text.
