### ISSUE TITLE
A simple correction in  learning-area/javascript/apis/introduction/web-audio/index.html

### ISSUE THREAD

**Issue by eslamsamiir** [mdn/sprints#3449]
# Request type
- [ ] Correction or update

# Details
In the example for Web Audio API at this link (https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction)

It has this code (https://github.com/mdn/learning-area/blob/master/javascript/apis/introduction/web-audio/index.html)

I think that line 57 of the code should be:
`playBtn.textContent = 'Play';`
instead of:
`this.textContent = 'Play';`

since (this) in this case refers to the _**audioElement**_ constant.

**Comment by chrisdavidmills** [comment]
Ah yes, you are totally right!

I've fixed the error now, in the code file and in the article.

Thanks for reporting.
