### ISSUE TITLE
propertyIsEnumerable for...in Symbol

### ISSUE THREAD

**Issue by Linbubin** [mdn/sprints#3452]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
[propertyIsEnumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable)
> Every object has a propertyIsEnumerable method. This method can determine whether the specified property in an object can be enumerated by a for...in loop, with the exception of properties inherited through the prototype chain. If the object does not have the specified property, this method returns false.

[Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)
> Symbols are not enumerable in for...in iterations. In addition, Object.getOwnPropertyNames() will not return symbol object properties, however, you can use Object.getOwnPropertySymbols() to get these.

so this code how explain
```js
let a = {};
let b = Symbol('key');
a[b] = 'b';

console.log(a.propertyIsEnumerable(b)); // true

for (let i in a) {
  console.log(i) // there not `Symbol` 
}
```

`propertyIsEnumerable` should say `...an object can be enumerated by a for...in loop, but not symbol`

**Comment by vkWeb** [comment]
@chrisdavidmills Hi sir.  

I can work on this to start my contribution journey with MDN. Can this be assigned to me? :rocket:

**Comment by chrisdavidmills** [comment]
@vkWeb absolutely! Thanks so much.

**Comment by vkWeb** [comment]
@chrisdavidmills @Linbubin I have updated the Description of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable.

@chrisdavidmills should we put a code example of this or the description alone will do?

**Comment by chrisdavidmills** [comment]
@vkWeb your added note looks good, thanks! I've given it a small tweak, and put it in a note for more visiblity, but I think this is done now.

Congrats on your first contribution.
