### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

### ISSUE THREAD

**Issue by SanjeevChachra** [mdn/sprints#3454]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link for the nav element displays a 404 page not found page. when I click on the HTML Demo.
![MDN_nav_404](https://user-images.githubusercontent.com/4475947/86264495-38e7b880-bbe0-11ea-811f-04a07d273883.PNG)

**Comment by chrisdavidmills** [comment]
This seems to work fine for me. Can you try again?

**Comment by mikoMK** [comment]
@chrisdavidmills I can reproduce the error when i click on the "Bikes" and "BMX" breadcrumbs. Shall I just change the href attribute to "#"? This way we could keep the look of clickable breadcrumbs, but without the error.

**Comment by chrisdavidmills** [comment]
@mikoMK yes please. That would certainly stop the example from breaking.
