### ISSUE TITLE
:visited selector page doesn't highlight privacy considerations

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#3455]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/CSS/:visited (mainly) and https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector (related)

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
While reviewing https://github.com/mdn/browser-compat-data/pull/6355, I noticed that `:visited` has lots of caveats relating to privacy. As a general matter, the "Privacy and the :visited selector" page covers that for the most part, but the reference page does a poor job of highlighting the complexity. I think this page would benefit from two key changes:

1. Some sort "Privacy" (or similar) section heading (distinct from "styling restrictions", which you might run into on other selector pages)
2. Mention that `<link>` tags are never matched, which (AFAICT) is only mentioned in the compat table

**Comment by rachelandrew** [comment]
@ddbeck that styling restrictions section is pretty much all to do with privacy isn't it? So maybe we just rename the heading and mention the `<link>` tags?

**Comment by ddbeck** [comment]
@rachelandrew Yeah, that sounds like a good fix to me! 👍

**Comment by rachelandrew** [comment]
I've made these updates @ddbeck @chrisdavidmills 

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:visited

**Comment by chrisdavidmills** [comment]
Looks complete, thanks @rachelandrew !
