### ISSUE TITLE
Failed XSS Attempt at https://wiki.developer.mozilla.org/zh-CN/docs/MDN/Feedback

### ISSUE THREAD

**Issue by GalvinGao** [mdn/sprints#3456]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There's code that _seems_ to be a **failed** (not successful; not vulnerable to the user) XSS attempt in the `zh-CN` MDN wiki page `Array.prototype.map()`, specifically at https://wiki.developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map#See_also . Please refer to the screenshot below.

<img width="780" alt="Snipaste_2020-07-02_00-28-46" src="https://user-images.githubusercontent.com/12567059/86268601-04352a80-bbfb-11ea-8aaf-4d5af9539515.png">

By checking the [history records](https://wiki.developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map$history) of the wiki page, it seems the change comes from Revision 1616575 ([diff](https://wiki.developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map$compare?locale=zh-CN&to=1616575&from=1592199)), which is committed by an user named [Jayly](https://wiki.developer.mozilla.org/zh-CN/profiles/Jayly).

## Side Notes
I don't have much of the skill about analyzing malicious JavaScript scripts, but by doing a quick search of `cookie` and `http` in the script `billyjons.net/21db1c5c8b372aecca.js` it seems that it is a real XSS script that might send information including Cookies in browser to the attacker, and may also contain other credentials. This behavior is quite uncommon and suspicious so I decided to report it here ;)

# Affected Page(s)
- [Array.prototype.map()#相关链接](https://wiki.developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map#See_also)

**Comment by Elchi3** [comment]
Thanks! I removed the failed xss attempt and banned the user.
