### ISSUE TITLE
Spread syntax article needs to actually explain how it works

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#3457]
This page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax is about spread syntax (...) but doesn't really explain what it is or how to use it. It vaguely says it's for expanding arrays and stuff but doesn't explain the syntax very well.

The syntax section shows some example syntaxes but doesn't follow up with an explanation of what that syntax means. For example, it lists `myFunction(...iterableObj)` but doesn't say what that actually _does_. This should be corrected, preferably soon, if we want people to be able to learn to use this properly.

Also: if there's an interactive example for this, it isn't displayed or working (at least not in Chrome).

**Comment by prosovskyf** [comment]
please assign, I ll add more initial explanation for using spread and what it actually pass etc. + simple example to understand the use

**Comment by hamishwillee** [comment]
Thanks @prosovskyf - assigned to you :-)

**Comment by Cimeone** [comment]
Hello, if this hasn't been closed yet is it possible to also be assigned to this issue as this is a topic I'm well versed in

**Comment by chrisdavidmills** [comment]
@Cimeone let's just see if @prosovskyf is still working on it first. @prosovskyf have you made progress on this one?

**Comment by prosovskyf** [comment]
@chrisdavidmills yea I am done with that, just need to have it approved as we discussed in the chat.

**Comment by chrisdavidmills** [comment]
@prosovskyf ok cool, thanks for the update. I'll wait for you on this one then.

**Comment by prosovskyf** [comment]
@chrisdavidmills please review

**Comment by chrisdavidmills** [comment]
Your language was ok here, but I've tidied it up, put it in a "Description" section to be consistent with other JS reference pages, and added some more information. I think this looks good now, thanks for helping!
