### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Web/API/Storage/removeItem

### ISSUE THREAD

**Issue by maxngrss** [mdn/sprints#3458]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details

On page [https://developer.mozilla.org/ru/docs/Web/API/Storage/removeItem ](https://developer.mozilla.org/ru/docs/Web/API/Storage/removeItem )
In block "Пример" (example) url to "Web Storage Demo" is [https://github.com/mdn/web-storage-demo](https://github.com/mdn/web-storage-demo) and it's 404 page

it must be [https://mdn.github.io/dom-examples/web-storage/](https://mdn.github.io/dom-examples/web-storage/) ([copied from english version of this page](https://developer.mozilla.org/en-US/docs/Web/API/Storage/removeItem))

https://developer.mozilla.org/ru/docs/Web/API/Storage/removeItem

**Comment by Elchi3** [comment]
Thanks for your issue! However, we don't maintain translations, see https://github.com/mdn/sprints#mdn-translations

I've fixed the link, though.
