### ISSUE TITLE
Document.execCommand() marked obsolete

### ISSUE THREAD

**Issue by jkovzels** [mdn/sprints#3460]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
HI, I wonder why `Document.execCommand()` is marked obsolete. I've tried to find the source of this info and can not find any confirmation that it is obsolete.  Plus, a lot of MDN articles refer to  `execCommand` without a mention that it is obsolete. Can you please clarify if it is ok to so still use it or not?

Link: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by Elchi3** [comment]
Hey, thanks for your issue.

It was marked obsolete in https://github.com/mdn/browser-compat-data/pull/5518 by @sideshowbarker. 
See also the big red banner here https://w3c.github.io/editing/docs/execCommand/
