### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket

### ISSUE THREAD

**Issue by ykrods** [mdn/sprints#3465]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I think I found wrong description about `protocols` param of `new WebSocket()` .

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket  says

```
If you don't specify a protocol string, an empty **string** is assumed.
```

But [whatwg Living Standard](https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface) says

```
protocols is either a string or an array of strings. 
If it is a string, it is equivalent to an array consisting of just that string; 
if it is omitted, it is equivalent to the empty **array**
```

And actually, FIrefox seems to be implemented according to Living Standard (tested on Firefox 77.0.1).

```javascript
const socket = new WebSocket(url, '');
```
It cause `SyntaxError: An invalid or illegal string was specified` 

```javascript
const socket = new WebSocket(url, [])
```

And it works well.

**Comment by prosovskyf** [comment]
To avoid this problem, it should be used as array even if it is only one string inside or empty. Living Standard describes: protocols is either a string or an array of strings. If it is a string, it is **equivalent to an array consisting of just that string**; So you are right, string is just confusing without further explanation. 
Please assign, I'll rewrite it. Thanks

**Comment by hamishwillee** [comment]
Awesome, thankyou @prosovskyf - you're assigned.

**Comment by prosovskyf** [comment]
@chrisdavidmills please review

**Comment by chrisdavidmills** [comment]
@prosovskyf I've simplified your addition down to just "If it is omitted, an empty array is used by default, i.e. []." I don't think we nreally need anything else here?
