### ISSUE TITLE
"Web forms — Working with user data" - Links problem

### ISSUE THREAD

**Issue by ronygozes** [mdn/sprints#3467]
# Request type

- [ ] Correction or update

# Details

Hello,
I am going through the "Web forms — Working with user data" (https://developer.mozilla.org/en-US/docs/Learn/Forms) section and there is an inconsistency with the left menu on the different articles in this section.

On some articles, like "Client-side form validation" (https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation), this section is on the left menu just under the "JavaScript — Dynamic client-side scripting" section.
On other child articles there are no links to this section on the left menu: For example on the "Web forms — Working with user data" (https://developer.mozilla.org/en-US/docs/Learn/Forms) there is no link to itself or any of its child articles on the menu. 
Another example is the "Sending form data" (https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data) where there is no link to be found.

Hope this can be fixed quickly as this causes a lot of confusion,
Thank You

**Comment by chrisdavidmills** [comment]
Hi there @ronygozes — this is because not all of the static pages have been regenerated since I updated the nav menu.

@escattone, please can you refesh everything under /Learn?

**Comment by escattone** [comment]
@chrisdavidmills This is done. I re-rendered all of the documents under (and including) `/Learn`, including all of the translations.

**Comment by chrisdavidmills** [comment]
@escattone thanks so much! And now the sidebars look correct on the cited pages. I think we can close this one now.
