### ISSUE TITLE
String.split refers incorrectly to an ordered set

### ISSUE THREAD

**Issue by shirriff** [mdn/sprints#3469]
# Request type

- [X] Correction or update

# Details

The [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) says:

```The split() method divides a String into an ordered set of substrings,```

However, `split` does not create a set, as entries can appear multiple times in the output, while "set" implies uniqueness. The documentation should refer to an array, rather than a set.

For a concrete example:
```
'abcabc'.split('')
["a", "b", "c", "a", "b", "c"]
```

If `split` acted according to the documentation, it would output `["a", "b", "c"]`.

Suggested change: "The split() method divides a String into substrings..."

The issue was pointed out in [this tweet](https://twitter.com/whitequark/status/1279896021783449603).

**Comment by Elchi3** [comment]
Thanks for your issue! Looks like this was updated in the meantime already https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split$compare?locale=en-US&to=1631592&from=1630956

It now says "list" instead of "set", which I believe should be fine.
