### ISSUE TITLE
Error in code example in page "Rendering a list of Vue components"

### ISSUE THREAD

**Issue by haenf** [mdn/sprints#3472]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

URL of the page:
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_rendering_lists

There is an error in the code example at the end of the page:

In the line between li's the error is : label="item.name". 
This should be: label="item.label".

**Comment by chrisdavidmills** [comment]
Thank you for pointing this out. I've fixed it now.

**Comment by haenf** [comment]
You are quick! Fantastic!

 

Best,

Hans Nederbragt

 

enference  infologica  |  06 - 55 378 352  |  www.enference.nl
