### ISSUE TITLE
A simple correction about fillText() and strokeText()

### ISSUE THREAD

**Issue by eslamsamiir** [mdn/sprints#3473]
## URL(s)
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics

## Request type
- [ ] Correction or update

## Details
In the part talking about drawing texts in canvas, the article said that the second and third attributes of the **_fillText()_** or **strokeText()** methods, represent the cooridinates of the **top left** corner of the text box.

But I think that they represent the **bottom left** corner of the text box, since I treid to draw a text with this line:

`ctx.fillText('HelloWorld', 0, 0);`

but It didn't appear because it was **above** the canvas area.

**Comment by chrisdavidmills** [comment]
Looks like you are totally right, @eslamsamiir ! Thanks for reporting. I have updated this.
