### ISSUE TITLE
Small issue in Date.parse() article

### ISSUE THREAD

**Issue by DimaGashko** [mdn/sprints#3475]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Examples

# Details

There's the following content in the beginning of the Examples section:

> The following call, which does not specify a time zone will be set to 2019-01-01 at 00:00:00 in the local timezone of the system.

```js
Date.parse("2019-01-01T00:00:00")
```

The thing is, it doesn't. It depends on the browser.

Chrome says:

![image](https://user-images.githubusercontent.com/20650419/87024066-4fde6a00-c1e1-11ea-9255-3602926d68e9.png)

But safari doesn't think so:

![image](https://user-images.githubusercontent.com/20650419/87024111-5e2c8600-c1e1-11ea-9586-13211f4eb79d.png)

So I think it should be specified in the article.

p.s. safari was launched thought BrowserStack. Safari versions: 13.1, 12.1, 11.1, 10.1..

**Comment by peterbe** [comment]
It's true. If you use `new Date(Date.parse("2019-01-01T00:00:00")).getTime()` it's more obvious.

```
* In Firefox: 1546318800000
* In Safari:  1546300800000
* In Chrome:  1546318800000
```

**Comment by DimaGashko** [comment]
Yes, that's why I executed it twice:  `Date.parse("2019-01-01T00:00:00")` and `new Date(Date.parse("2019-01-01T00:00:00"))`

**Comment by Elchi3** [comment]
Hey, thanks for your issue! 
The docs say right at the beginning "It is not recommended to use Date.parse as until ES5, parsing of strings was entirely implementation dependent. " -- how do you think we could make this note better? 

The example you found is just one inconsistency of many. There isn't much we can do except hoping that the new Date/Time API will do all this a lot better. (see https://blogs.igalia.com/compilers/2020/06/23/dates-and-times-in-javascript/)

**Comment by DimaGashko** [comment]
@Elchi3 Yes, but since there's "Non-standard date strings" section after "Using Date.parse()" section so, it looks like "use can use things from Using Date.parse() but be careful with things from 'Non-standard date strings' section.

![image](https://user-images.githubusercontent.com/20650419/87138968-ea08e580-c2a7-11ea-84fc-f5c412cd2d1d.png)

**Comment by Elchi3** [comment]
Right, so there is that note box as well in addition to the introductory warning. Do you think we need more notes? At the beginning of the example sections?

**Comment by DimaGashko** [comment]
And one more thing. The docs don't recommend to use Date.parse(), but `new Date(someString)` also uses Date.parse() under the hood. So, we always use it in parsing dates from strings, for example from ISO.


> Do you think we need more notes? At the beginning of the example sections?

The first 3 example in the examples section are correct in any browser. I think it's ok to move `Date.parse("2019-01-01T00:00:00")` part to "Non-standart date strings" section.
