### ISSUE TITLE
Typo in Vue.js tutorial?

### ISSUE THREAD

**Issue by haenf** [mdn/sprints#3476]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

Hi,

 Vue.js tutorial (https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models) 

Section "Passing data to parents with custom events" 

The line "this.$emit("Todo-added");" gives an error. It looks like the capital "T" is causing the problem. Things work okay when it is replaced with a lower "t". This is in line with the text above it.

Best,  
Hans Nederbragt

**Comment by chrisdavidmills** [comment]
@haenf I'm glad you spotted this, and thanks for reporting it.

Fixed now.
