### ISSUE TITLE
Vue.js tutorial - doesn't do what is described

### ISSUE THREAD

**Issue by haenf** [mdn/sprints#3477]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

url: https://github.com/mdn/sprints/issues/new?template=issue-template.md&projects=mdn/sprints/2&labels=user-report
section "Adding the new todo into our data"

problem:
Up to the end of the previous section everything works fine - as is shown in the console. But when I replace the line "console.log('To-do added:', toDoLabel);" with "this.ToDoItems.push({id:uniqueId('todo-'), label: toDoLabel, done: false});" no item is added to the list. I checked my code many times, but I can't find anything that's different from the code in the tutorial. What went wrong?

[ToDo code.zip](https://github.com/mdn/sprints/files/4901639/ToDo.code.zip)

**Comment by chrisdavidmills** [comment]
Hi @haenf, sorry to hear you are having trouble here.

Can you send me the correct URL of the tutorial part you are having trouble with?

and also send me a zip of your project's full `src` directory?

From there I should be able to track the error down.

Thanks!

**Comment by haenf** [comment]
Hi Chris,

 

The url:

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models

 

The part where it doesn't work (for me :- ) anymore: "Adding the new todo into our data". The first code snippet doesn't result in what is described: new ToDo item added to the list.

 

Thank you in advance,

Hans Nederbragt

 

enference  infologica  |  06 - 55 378 352  |  www.enference.nl

**Comment by chrisdavidmills** [comment]
@haenf I've had a look, and the code in the article matches the code in the final app version (https://mdn.github.io/todo-vue/dist/).

Can you send in a zip of your project's `src` directory, for me to have a look at?

**Comment by haenf** [comment]
Hi Chris,

 

I send you  the src directory already last week, by direct reply to your mail. Didn’t you receive it?

 

Best,

Hans Nederbragt

 

 

enference gsm 06 55 378 352  |  https://enference.nl

**Comment by chrisdavidmills** [comment]
@haenf hi there! My apologies — I didn't see it the first time round, but I've found it now.

I've tried running your code, and I can see what the problem is. When you submit the form, it refreshes the entire page, and so you don't get the new todo item added — it just goes back to the initial state of the page. To fix this, you need to run `preventDefault()` in your event handler. This is done in Vue using the `prevent` event modifier on the submit handler, like this (this is inside `ToDoForm.vue`):

```js
<form @submit.prevent="onSubmit">
```

You can read about it in this section: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models#Creating_a_method_binding_it_to_an_event_with_v-on

**Comment by haenf** [comment]
Hi Chris,

 

Yes, that was the thing I had wrong. It is working okay now, thank you for your help. And by the way: I like the tutorial very much, it is very clear! Together with the ‘official’ Vue.js manuals it is the best I have tried so far. When are you going to write a similar tutorial for Vuex ? :- ) 

 

Best,

Hans

 

 

enference gsm 06 55 378 352  |  https://enference.nl

**Comment by chrisdavidmills** [comment]
> And by the way: I like the tutorial very much, it is very clear! Together with the ‘official’ Vue.js manuals it is the best I have tried so far. When are you going to write a similar tutorial for Vuex ? :- )

I am really glad that you are finding them helpful!

We are currently researching what to do next in terms of improvement to our learning material. I'm not sure that we want to add too much more about specific frameworks, as this is only supposed to be a stepping stone to being comfortable enough with the framework to then go and find mroe information at the vendor's sites. It would be impossible for us to maintain all of the things! But we will certainly consider your feedback here.
