### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

### ISSUE THREAD

**Issue by ChrxsCrxss** [mdn/sprints#3479]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

<img width="1242" alt="Screen Shot 2020-07-11 at 10 16 26 AM" src="https://user-images.githubusercontent.com/47887670/87229735-9bb71d80-c35f-11ea-8425-844feb2f3f64.png">

Should read "if a trailing comma is used on the **right-hand** side..."

**Comment by Elchi3** [comment]
Thanks for your issue!

> Should read "if a trailing comma is used on the **right-hand** side..."

If the docs say that and put a trailing comma on the right hand side (`const [a, ...b] = [1, 2, 3,];`), I get no SyntaxError and so the point the example illustrates can't be made.

**Comment by chrisdavidmills** [comment]
Looks like this is fixed, so closing.
