### ISSUE TITLE
Order of elements retuern by querySelectorAll()

### ISSUE THREAD

**Issue by SteveALee** [mdn/sprints#3480]
# Request type
- [x] Correction or update

# Details

it's more a question. Is the order of elerments returned by the `querySelectorAll` methods quarenteed to be in document order?

thanks

**Comment by chrisdavidmills** [comment]
Short answer — I don't know. It doesn't appear to specify this in the spec. I'm guessing this is what would happen, I don't think it would make sense for the selected elements to be looped through in a different order. But I can't say for sure.
