### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site

### ISSUE THREAD

**Issue by FeynmanDNA** [mdn/sprints#3481]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi i refer to this paragraph near the bottom of the page:
![image](https://user-images.githubusercontent.com/26617036/87303055-13926d00-c545-11ea-893d-d18962727c9e.png)
In this sentence, "The first option can be done by setting the extra attribute to 0", the 0 is hard to read as a normal font. Maybe can provide the `0` as an inline code font, or `extra = 0`?

**Comment by chrisdavidmills** [comment]
I've set it to code font, and now it is easier to read. Thanks!
