### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls

### ISSUE THREAD

**Issue by PeterNjeim** [mdn/sprints#3488]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/26418974/87357408-5733a980-c53a-11ea-8ceb-d80651eea1da.png)

https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls#Actual_buttons

"In addition, the \<button\>" is wrong, it should say "In addition, the \<input\>".

**Comment by chrisdavidmills** [comment]
Nah, we do actually mean `<button>` there, but the text is written a bit confusingly. In that paragraph we are talking about the `<button>` equivalents to each `<input>` type. I've rewritten it a bit to make it clearer. Is it better now?

**Comment by PeterNjeim** [comment]
Thank you, I guess I was skimming a little bit and just assumed that those three input types were talking about button types specifically, because the header made me think "actual buttons" could only mean the <button> element. My bad.

**Comment by chrisdavidmills** [comment]
no worries - i think it was definitely a bit confusing.
