### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement

### ISSUE THREAD

**Issue by deant** [mdn/sprints#3490]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In this sentence:

> When in quirks mode, the scrollingElement attribute returns the HTML body element if it exists and is **not** potentially scrollable, otherwise it returns null.

...I think the "not" shouldn't be there.  Surely it returns the body element only when it **is** potentially scrollable?

https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement

**Comment by deant** [comment]
Actually it turns out that the MDN text comes directly from the W3C page:

[CSSOM View Module - scrollingelement](https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement)

But it still looks like a typo to me, not the correct behavior... so I'm submitting an issue report to them as well.

**Comment by chrisdavidmills** [comment]
@deant I think you are right here. Having not there just makes no sense. I've updated the MDN page, but let me know if you heard anything back from the W3C about this ;-)
