### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/function*

### ISSUE THREAD

**Issue by cedricrey** [mdn/sprints#3493]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

Hello, in french version of function* documentation, there is a mistake in the first simple example :
`function* creerID(){
  var index = 0;
  while (true) {
    yield index++;
  }
}

var gen = creerID();

console.log(gen.next().value); // 0
console.log(gen.next().value); // 1
console.log(gen.next().value); // 2
console.log(gen.next().value); // undefined`

The last line logs "3" and not "undefined"

Cédric

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/function*#Exemple_simple

**Comment by Elchi3** [comment]
Thanks for your issue. MDN translations are maintained by the community, so usually these issue don't get fixed here. This seemed simple enough, so I fixed it. Please consider signing up for a wiki account to fix things like this in the future. Thanks!

**Comment by cedricrey** [comment]
Thank you @Elchi3  ! Sorry I did't see that was possible to do it by myself. I signed up for a MDN account to do it in the future. Thank you. Have a good day
