### ISSUE TITLE
Article About Client Storage Has Inaccurate Data About Cookies

### ISSUE THREAD

**Issue by mudgen** [mdn/sprints#3494]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

I noticed that this article has inaccurate/misleading information about cookies: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

I don't want to fix the article myself but I thought it might help to point out that there is some inaccurate information in it in case someone wants to fix it.

See this Reddit thread for info: https://www.reddit.com/r/javascript/comments/hsag4d/cookies_are_the_most_secure_way_to_do/

**Comment by chrisdavidmills** [comment]
Ha, eaten alive on reddit again. I'm turning this into a habit ;-)

Thanks @mudgen for pointing this out. This is totally on me — my original comments were somewhat ignorant, and I've updated that section to provide a more accurate, reasoned description:

https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#Old_school_Cookies

Do you think that fixes things?

**Comment by mudgen** [comment]
@chrisdavidmills Yes, it is fixed and looks good. I feel respect for you.

I am sorry I posted about it to reddit.  Originally I wanted to just contact the author but I didn't know how to, but I wanted to do something about it. 

I deleted the post from Reddit.

**Comment by chrisdavidmills** [comment]
> Yes, it is fixed and looks good. I feel respect for you.

Cool, glad this looks better.

> I am sorry I posted about it to reddit. Originally I wanted to just contact the author but I didn't know how to, but I wanted to do something about it.

> I deleted the post from Reddit. If there is anything else you want me to do about it then let me know.

Honestly, don't worry about it — no harm done. I don't think for a second that you had any kind of malicious thoughts in mind — you had good intensions. And I have pretty thick skin — I can deal with a few reddit curmudgeons ;-)
