### ISSUE TITLE
WebAssembly updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3498]
## Story

As a web developer, I want to know about the latest WASM enhancements, so that I can run code written in multiple languages on the web.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [ ] [Allow atomic operations on non-shared memories](https://bugzilla.mozilla.org/show_bug.cgi?id=1619196)

**Comment by chrisdavidmills** [comment]
* Rel note added: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/80#WebAssembly
* Mention added to MDN: https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#Atomic_memory_accesses
