### ISSUE TITLE
CSS updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3499]
## Story

As a web developer, I want to know about the latest updates to CSS, so that I can style my sites and apps using the latest CSS declarations.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox 80 release notes is added, experimental features page is updated.

1. - [x] [Implement the prefers-contrast media-query](https://bugzilla.mozilla.org/show_bug.cgi?id=1506364) Not yet enabled by default. So only needed to be added to experimental features page.
2. - [x] [Support standard 'appearance' CSS property unprefixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1620467). Intent to ship: https://groups.google.com/g/mozilla.dev.platform/c/x8njjxKySKY, intent to prototype: https://groups.google.com/g/mozilla.dev.platform/c/nlun5QV63Bo/m/xUXCmySGAgAJ
3. - [x] [[css-pseudo-4] Animations on ::marker?](https://bugzilla.mozilla.org/show_bug.cgi?id=1637532)

**Comment by jmswisher** [comment]
Item 1:
- Updated [prefers-contrast](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast) article
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/6502)

**Comment by jmswisher** [comment]
Item 2:
- Updated the [appearance](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/appearance) reference article, including separating out non-standard and obsolete values.
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/6505)
- [Interactive examples PR](https://github.com/mdn/interactive-examples/pull/1656)

**Comment by jmswisher** [comment]
Item 3:
- Updated [::marker](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::marker) article.
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/6506)
