### ISSUE TITLE
WebGL updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3500]
## Story

As a web developer, I want to know about the latest WebGL enhancements, so that I can take advantage of the latest graphic techniques available.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Implement webgl draft ext KHR_parallel_shader_compile](https://bugzilla.mozilla.org/show_bug.cgi?id=1536674)

**Comment by Rumyra** [comment]
A check list for myself

[ ] dev doc
[ ] BCD
[ ] Release notes
[ ] Experimental features
[ ] Needs review

**Comment by Rumyra** [comment]
@chrisdavidmills

**Comment by chrisdavidmills** [comment]
I've set the bug to dev-doc-complete, and asked for a review.

**Comment by Rumyra** [comment]
Oh brill - thanks so much @chrisdavidmills !
