### ISSUE TITLE
Media updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3502]
## Story

As a web developer, I want to know about latest Media, Video, Audio enhancements, so that I can take advantage of new features in my website or app.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Implement SetPositionState API on the key source](https://bugzilla.mozilla.org/show_bug.cgi?id=1643513) -- **1.5 points**
2. - [x] [Implement the "skipad" action in the MediaSession interface](https://bugzilla.mozilla.org/show_bug.cgi?id=1582569) -- **0.5 points**
3. - [x] [Enable AV1 and dav1d by default on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1644566) -- **0.5 points**
4. - [x] [Implement the seekto in the MediaSession interface](https://bugzilla.mozilla.org/show_bug.cgi?id=1621403) -- **0.5 points**

**Comment by chrisdavidmills** [comment]
@a2sheppy hi there! Can you estimate the points for this US, and put the estimate into the sprint spreadsheet also? Thanks.

**Comment by a2sheppy** [comment]
Looks like around 3 points for this stuff. Much of it, if not most of it, is already documented at least in part. I'll go over it quickly to be sure there aren't issues, and apply any needed updates. The majority of the work will be BCD updates.

**Comment by a2sheppy** [comment]
I've made some initial updates for item 4 (the `seekto` changes).

**Comment by a2sheppy** [comment]
AV1 on Android was done in time for Firefox 80 but not in time for the launch of Fenix so it's not actually out yet. I've added a section to the Experimental features page for now as described in the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1644566.

**Comment by a2sheppy** [comment]
The `seekto` and `skipad` changes are holding pending resolution of a discussion I'm having about BCD structure for some of this data.

The `SetPositionState` thing appears to be a chrome-only issue that isn't exposed to the web; if I confirm that, this one will go away.

**Comment by a2sheppy** [comment]
The `SetPositionState` change was internal use only; the public-facing change was previously documented.

**Comment by Elchi3** [comment]
Thanks for confirming! I think next time I will ping you earlier on things where I am not sure if they have to do with Web APIs (especially in RTC land, I'm not so familiar).

**Comment by a2sheppy** [comment]
Submitted [BCD PR 6492](https://github.com/mdn/browser-compat-data/pull/6492) to add the `MediaSessionActionDetails` dictionary which is needed for these updates

**Comment by a2sheppy** [comment]
Last night I submitted [BCD PR 6488](https://github.com/mdn/browser-compat-data/pull/6488) to add the `MediaSessionAction` enum to BCD; this includes the Firefox 80 additions of `skipad` and `seekto`.

**Comment by a2sheppy** [comment]
Updated Firefox 80 for developers to mention `seekto` and `seekad`.

**Comment by a2sheppy** [comment]
This is now complete pending the merging of [BCD PR 6488](https://github.com/mdn/browser-compat-data/pull/6488) and [BCD PR 6492](https://github.com/mdn/browser-compat-data/pull/6492).
