### ISSUE TITLE
DOM updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3503]
## Story

As a web developer, I want to know about latest DOM enhancements, so that I can take advantage of new features in my website or app.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Enable HTML5 dialog in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1645046)
2. - [x] [Problem with allowfullscreen and allow=fullscreen](https://bugzilla.mozilla.org/show_bug.cgi?id=1608358)
3. - [x] [Do not expose outerWidth/outerHeight features of window.open to web content](https://bugzilla.mozilla.org/show_bug.cgi?id=1623826)
4. - [x] [Ship animation compositing to release channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1652676)

**Comment by chrisdavidmills** [comment]
HTML `<dialog>` element

Currently only enabled in Nightly, so we don't yet need to mention it anywhere on MDN, except for the Experimental Features page where it is already mentioned. I just updated "Enabled by default" to "Yes" for Nighytly.

**Comment by chrisdavidmills** [comment]
Fullscreen thingy — see https://bugzilla.mozilla.org/show_bug.cgi?id=1608358#c21

**Comment by chrisdavidmills** [comment]
`outerHeight`/`outerWidth` docs updated; see https://bugzilla.mozilla.org/show_bug.cgi?id=1623826#c11

**Comment by chrisdavidmills** [comment]
animation compositing changes: see https://bugzilla.mozilla.org/show_bug.cgi?id=1652676#c4

**Comment by Elchi3** [comment]
This can be closed if these BCD PRs are merged:

- https://github.com/mdn/browser-compat-data/pull/6494
- https://github.com/mdn/browser-compat-data/pull/6495
- https://github.com/mdn/browser-compat-data/pull/6493
