### ISSUE TITLE
DevTools updates in Firefox 80

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3504]
# User story
As a web developer, I want to know how to use the latest Firefox Developer Tools, so that I can develop and debug apps and websites properly using the latest tools.

# Acceptance criteria

The following bugs are dev-doc-complete, an entry to Firefox release notes is added, experimental features page is updated, and the content has been reviewed as needed. (See also [Update DevTools What's New for 80](https://bugzilla.mozilla.org/show_bug.cgi?id=1652755).)

1. - [x] [Enable SSE on Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1636423) - Network Monitor
2. - [x] [Show an icon for slow requests](https://bugzilla.mozilla.org/show_bug.cgi?id=1648373) - Network Monitor
3. - [x] [Add a `:block <url>` command which matches Netmonitor's "Block URL" context menu entry](https://bugzilla.mozilla.org/show_bug.cgi?id=1546394) - Console
4. - [x] [Add a stack trace to the exception tooltip](https://bugzilla.mozilla.org/show_bug.cgi?id=1643633) - Debugger
5. - [x] [Provide autocompletion when adding a new class to an element](https://bugzilla.mozilla.org/show_bug.cgi?id=1492797) - Inspector

**Comment by jmswisher** [comment]
Item 1: Added to [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Developer_tools)

**Comment by jmswisher** [comment]
Item 3: Added `:block` and `:unblock` to the [Web Console helpers](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers) list. Also added a note about them to the [Blocking specific URLs](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Blocking_specific_URLs) section of the Network Monitor request list article.

**Comment by jmswisher** [comment]
Item 5: The .cls button wasn't really documented at all. I added [a section about it](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Viewing_and_changing_classes_on_an_element) to the "Examine and edit CSS" article, mentioning autocomplete.

**Comment by jmswisher** [comment]
Item 4: Added a screenshot showing the stack trace in the tooltip, to [Breaking on exception](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Breaking_on_exceptions).

**Comment by jmswisher** [comment]
Item 2: Waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1656388 so that the feature actually works.

**Comment by jmswisher** [comment]
Item 2: Added a screenshot and description of the turtle icon under the File column in the [Network request columns](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Network_request_columns) section of the Network request list article.

**Comment by Elchi3** [comment]
Looks good to me. Thanks Janet! I'm cc'ing @digitarald here, but from my side this looks done for Firefox 80.

Thanks for also adding these items to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/80
