### ISSUE TITLE
"Contributing to SpiderMonkey" YouTube video private

### ISSUE THREAD

**Issue by jackbondpreston** [mdn/sprints#3506]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
There is a link on the [SpiderMonkey project page](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey) titled "Contributing to SpiderMonkey". This points to the url [https://www.youtube.com/watch?v=LaFbvPBr6GE](https://www.youtube.com/watch?v=LaFbvPBr6GE), which is a private YouTube video and cannot be viewed.

**Comment by Elchi3** [comment]
I removed the dead link. Thanks for your issue!
