### ISSUE TITLE
Translation issue in flexbox documentation

### ISSUE THREAD

**Issue by patriciocalvo** [mdn/sprints#3510]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
There is a problem in the following code example. the "flex-end" property appears to have been translated to "flex-end"
![2020-07-19_174313](https://user-images.githubusercontent.com/65637369/87884907-e54eda80-c9e7-11ea-82d1-5ccb928c07e9.jpg)

https://developer.mozilla.org/es/docs/Learn/CSS/CSS_layout/Flexbox

**Comment by chrisdavidmills** [comment]
Thanks for reporting. I've fixed this in the source, and the final publication should update soon.
