### ISSUE TITLE
Error in javascript code

### ISSUE THREAD

**Issue by susanneeneroth** [mdn/sprints#3512]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The code example on this page does not work, I get an error in the console. I am not able to fix it since I am a beginner javascript coder. I tested both to write it and to copy/paste it, I get the same error. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement/insertCell

**Comment by chrisdavidmills** [comment]
Hi there @susanneeneroth !

I tried looking at the page, and the example on there works for me absolutely fine, no error. Do you mean that you are getting an error when you go and look at the page? Or are you getting an error when you try to use the code in one of your own examples?

If it is the latter, are you able to put your code in a codepen and then give me the URL so I can have a look at it?

What browser are you using?

**Comment by susanneeneroth** [comment]
Hi @chrisdavidmills !
Sorry, just realized I put the script src in the wrong place... I thought you could put it inside the <head>.
It work when it is in the body. But the strange thing is that I get an error message that you can't insert row of null. Shouldn't the logical error message be that it can't find the source?

**Comment by chrisdavidmills** [comment]
Cool, glad you have figured it out.

> But the strange thing is that I get an error message that you can't insert row of null. Shouldn't the logical error message be that it can't find the source?

Well, it kind of does make sense if you are trying to insert a row, and the reference to the row doesn't exist (e.g. you might have put a typo in the row name variable). "Can't find source" is a kind of vague terminology that means something different depending on context, whereas saying the row is null means something very specific in the context of the JavaScript we are dealing with. There is often a balance with the error messages, between machine-reportable, and huma-readable.

**Comment by susanneeneroth** [comment]
Thanks for the input on that :). 

But I find it illogical in this case, since there wasn't an error in the code, which it made me think it was... and since the source was not rightly put in the HTML-file, the console should not be able to find or read any of the JavaScript at all. At least that is what I think. It would at least be more helpful for a newbie :).
