### ISSUE TITLE
speechSynthesis JS API wrongly interpreting text

### ISSUE THREAD

**Issue by eScriptorium** [mdn/sprints#3513]
**Summary**
_What is the problem?_The speechSynthesis API in operation incorrectly interprets 'May 2020'. Great software. This is the first real problem with interpretation I have found.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Use a demo site such as [https://codesandbox.io/s/mqnx7ypz1y](url)
2. enter 'May 2020' in the input text
3. Listen to what is read out.

**Actual behavior**
_What actually happened?_Read aloud 'The 20th May 20'

**Expected behavior**
_What did you expect to happen?_Read aloud 'May 2020'.

**Additional context**
_Is there anything else we should know?_Voice chosen was Daniel (en-GB)

**Comment by eScriptorium** [comment]
Have just noticed that this problem may be confined to Apple Mac devices as it works OK on Windows.

**Comment by guest271314** [comment]
Does Mac OS ship a speech synthesis engine with the browser? Web Speech API communicates with a local or remote speech synthesis engine. AFAIK Firefox is not shipped with a speech synthesis engine in the browser source code.

**Comment by eScriptorium** [comment]
The plot thickens. The voice Alex (en-US) reads it correct on Mac in Chrome, Safari and Firefox. The voice Daniel (en-UK) gets it wrong on Mac in all three browsers. So it looks as if it might be a language construct issue and independent of the browser.
Microsoft George en-GB as previously mentioned gets it right.

**Comment by chrisdavidmills** [comment]
This is an interesting problem for sure, not something I ever came across when writing the Web Speech API docs on MDN. Saying that, this sounds like more of a platform issue than an docs issue. You'd be better off reporting such problems on Mozilla's bugzilla site. Happy hunting!
