### ISSUE TITLE
Front-end Developer Learning Pathway - Javascript module order

### ISSUE THREAD

**Issue by kevindmclaughlin** [mdn/sprints#3517]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
[The new Front-end Developer learning pathway](https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer) suggests to learn APIs before objects, but the [API module](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs)  suggests learning objects first.

# Front-end Developer Learning Pathway
![Screen Shot 2020-07-20 at 10 42 15 PM](https://user-images.githubusercontent.com/32273256/88006894-bf563280-cada-11ea-9132-0dd98e00a4fb.png)

# API Module
![Screen Shot 2020-07-20 at 10 42 40 PM](https://user-images.githubusercontent.com/32273256/88006886-ba917e80-cada-11ea-9bdc-b82f8f44e39d.png)

**Comment by chrisdavidmills** [comment]
@kevindmclaughlin this is a good point - thanks for bringing this up! Objects should come first, so I've adjusted the order in the learning pathway. It should show up in the published version soon.
