### ISSUE TITLE
Merge MutationObserverInit doc into MutationObserver.observe(), or duplicate it

### ISSUE THREAD

**Issue by kunpw** [mdn/sprints#3518]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It would be better that the documentation of MutationObserverInit be merged into or duplicated in the documentation of MutationObserver.observe(), because knowing the info provided in the latter page is the mental prior requirement of specifiying the options of observe(). These two pages are one integral part. Merging or duplicating would save users a click and allow them to gain the necessary info from a skim.

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit

**Comment by Rumyra** [comment]
I have added the init options to the `observe()` page. I'm inclined to keep the `MutationObserverInit` purely because of the information held on the options subpages.

A tricky one as we're back to documenting dictionaries, but in this case there's quite a bit of info included.
