### ISSUE TITLE
Live code block doesn't match the tutorial description

### ISSUE THREAD

**Issue by hacker-eleos** [mdn/sprints#3521]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In JavaScript section, **Test your skills: Strings** ,all the live code boxes contains same code which is only suitable for the first exercise. You need to update the live code block templates that reflects, the test description. 

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings
![image](https://user-images.githubusercontent.com/63001252/88133446-b8751000-cbff-11ea-86c0-4edfe7ada79c.png)
![image](https://user-images.githubusercontent.com/63001252/88133472-c88cef80-cbff-11ea-9ef9-e675bccd4533.png)

**Comment by chrisdavidmills** [comment]
@hacker-eleos I've just tested this, and it shows me the four different live samples, as expected. Can you try it again?

And if it is still showing you this problem, let me know what browser you are using, and we'll try debugging it.

**Comment by hacker-eleos** [comment]
I am using Firefox developer edition. It seems to okay now. I will close the thread.
