### ISSUE TITLE
live sample for font face has CORS issue. 

### ISSUE THREAD

**Issue by intijk** [mdn/sprints#3522]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

There is a live sample in this page.

Live sample link is https://mdn.mozillademos.org/files/7775/webfont-sample.html
Font file is locate at https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf

Which suppose to work. But the page itself redirects me to:
https://media.prod.mdn.mozit.cloud/attachments/2014/05/07/7775/7ae86b88e08ee1b039fa005524063b70/webfont-sample.html

Thus caused a CORS issue, expected live demo not really present. 

```html
<html>
<head>
  <title>Web Font Sample</title>
  <style type="text/css" media="screen, print">
    @font-face {
      font-family: "Bitstream Vera Serif Bold";
      src: url("https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf");
    }
    
    body { font-family: "Bitstream Vera Serif Bold", serif }
  </style>
</head>
<body>
  This is Bitstream Vera Serif Bold.
</body>
</html>
```

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. I've put the example code on GitHub pages, and embedded that in the page:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@font-face#Specifying_a_downloadable_font
