### ISSUE TITLE
Typo in https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Fonts

### ISSUE THREAD

**Issue by sylozof** [mdn/sprints#3524]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Fonts, section **Guides**, paragraph **Guide sur les polices variables**, there's the word "proenant". I think the intended word was "provenant" (the "v" letter is missing).

![image](https://user-images.githubusercontent.com/7589928/88172879-f2efa480-cc21-11ea-89f8-db1c3e91a327.png)

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
