### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API

### ISSUE THREAD

**Issue by guest271314** [mdn/sprints#3525]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

Is the following information, specifcally "The left and right channels are stored like this:" "LLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRR (for **_a_** buffer of 16 frames)" (emphasis added) true and correct, both technically, and for all cases with regard to web platform and Web Audio API?

> **Planar versus interleaved buffers**
> The Web Audio API uses a planar buffer format. :
> 
> `LLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRR (for a buffer of 16 frames)`
> This is very common in audio processing: it makes it easy to process each channel independent

![Screenshot_2020-07-22_22-21-11](https://user-images.githubusercontent.com/4174848/88235125-b5af0500-cc69-11ea-8504-1a9cee28d071.png)

See What's the interleaved audio ? [closed] https://stackoverflow.com/q/17879933

![Screenshot_2020-07-22_22-26-17](https://user-images.githubusercontent.com/4174848/88235480-77feac00-cc6a-11ea-8948-6039f1bdc413.png)

URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API

Specification issue: https://github.com/WebAudio/web-audio-api/issues/2225#issuecomment-662708900

**Comment by Rumyra** [comment]
The page referenced is correct, there is no need to update any information regarding this issue.

See also "The Web Audio API exposes only planar buffers, because it's made for processing. It works with planar, but converts the audio to interleaved when it is sent to the sound card for playback. Conversely, when an MP3 is decoded, it starts off in interleaved format, but is converted to planar for processing."

**Comment by guest271314** [comment]
@Rumyra 

> The page referenced is correct, there is no need to update any information regarding this issue.

No, it is not. 

The term "planar" is not in the Web Audio API specification text at all. Nor is the term "interleaved" in the specification. Web Audio API removed the term "planar" from the specification entirely https://github.com/WebAudio/web-audio-api/commit/ea35c4a0469f25738dffb7748e4786ea99a1e924, therefore the MDN documentation is not accurate, as it describes technical terms that are not in the actual specification. AFAIK planar buffers are not exposed to the end-user whatsoever.
