### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

### ISSUE THREAD

**Issue by manngo** [mdn/sprints#3526]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update (… or clarification … ?)

# Details

The following section:

> __`form`__
> This attribute takes the value of the `id` attribute of a `<form>` element you want the `<fieldset>` to be part of, even if it is not inside the form.

I know that’s what it says in the specifications, but I’m not sure that it is true, or at least working correctly.

Although you can use `form="…"` with inputs and buttons, using it with a `fieldset` doesn’t appear to work. A button in a separate associated field set doesn’t submit, and inputs in a separate associated field set don’t get submitted.

I have an unanswered question at https://stackoverflow.com/questions/63009762/html-fieldset-form-attribute-not-working.

This also appears to be the case with Safari and Chrome.

It may be that the `form` attribute is not supposed to work that way with field sets, in which case the above is definitely not clear.

**Comment by chrisdavidmills** [comment]
Hi @manngo , thanks for bringing this up. This is confusing — when you run your code snippet, the `<fieldset>` is associated with the `<form>` (you can check this by running `formRef.elements` in the console to get the elements associated with the form), but the inputs inside the `<fieldset>` are not. To make them associated with the `<form>`, you need to explicitly give them the `form` attribute.

Try my updated version, for example:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>for outside fieldset test</title>
  </head>
  <body>
    <form id="test">
        <input name="inside-stuff" value="Inside">
        <button type="submit">Doit Inside</button>
    </form>

    <fieldset form="test">
        <input name="outside-stuff" value="Outside" form="test">
        <button type="submit" form="test">Doit Outside</button>
    </fieldset>

  </body>
</html>
```

I've updated the `form` attribute description in the fieldset page to make this a bit clearer: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#Attributes

I'm closing this now, but please let me know if you think this needs anything else.

**Comment by manngo** [comment]
Hi Chris @chrisdavidmills
Thanks for looking into this. The only other question would be how is this attribute useful?

**Comment by chrisdavidmills** [comment]
I personally don't think it is very useful, @manngo . I can't think of a solid, obvious reason why you'd want to associate a fieldset with a form, but not the input fields inside it, except if maybe the fieldset contains a legend legend that features useful semantic information that you want associated with the form, for some kind of data integrity or benefit to assistive technology?

But that's merely speculation at this point. I'd have to do some more testing to see if there was truth in my thoughts.
