### ISSUE TITLE
https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

### ISSUE THREAD

**Issue by josephhislander** [mdn/sprints#3527]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

    In this evaluation, in the  spanish version, say:
 
//  Preparar las imágenes

Usa tu editor de imágenes favorito, y utiliza medidas de 400px de ancho y 120px de alto para:

    firefox_logo-only_RGB.png
    firefox-addons.jpg
    mozilla-dinosaur-head.png //

  In the english version say: 

// Preparing images

Using your favourite image editor, create 400px wide and 120px wide versions of:

    firefox_logo-only_RGB.png
    firefox-addons.jpg
    mozilla-dinosaur-head.png //

 *** the spanish translation is confusing, its  : "y utiliza medidas de 400px de ancho y 120px de alto para:" ,

!* the correct is , " Crea una verion de 400px   de ancho y otra de 120px de ancho para :"
 
 its two versions 400px and 120px, do not one of 400x120 px

https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
