### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade

### ISSUE THREAD

**Issue by jpear1** [mdn/sprints#3530]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There's a broken link on [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#CSS_animations_and_the_cascade). The "CSS animations" link under the "CSS animations and the cascade" header does not lead anywhere.

https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#CSS_animations_and_the_cascade

**Comment by wbamberg** [comment]
Thanks for filing! That link should go somewhere now.
