### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

### ISSUE THREAD

**Issue by jakopo87** [mdn/sprints#3532]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This section:

> These error events do not bubble up to window, but **(at least in Firefox)** can be handled with a window.addEventListener configured with useCapture set to True.

implies that bubbling of the `error` event works only on Firefox, but both Chrome and Edge propagate the event in the same way, so the part in the parenthesis should be removed.

The code used for the test is:
```
window.addEventListener('error', function (e) {
    console.log("ERROR");
    ...
}, true);
```

**Comment by chrisdavidmills** [comment]
Thanks for reporting! I've fixed this now.
