### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean

### ISSUE THREAD

**Issue by ivanosevitch** [mdn/sprints#3533]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the following part of the page https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean:

> <p>Do not use a <code>Boolean</code> object to convert a non-boolean value to a boolean value. To perform this task, instead, use <code>Boolean</code> as a function, or a <a href="/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Logical_NOT">double NOT operator</a>:</p>

The anchor `Logical_NOT` doesn't exist in the link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#Logical_NOT

It should perhaps link instead to the "Logical NOT" dedicated page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_NOT

**Comment by wbamberg** [comment]
Yes, we gave the logical operators their own pages a month or so back, but obviously didn't find all the places that linked there. Thanks for taking the time to file this, it should be fixed now!
