### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by MikaelNorton** [mdn/sprints#3550]
Hy! Well.. I am a beginner but, it's a wrong exercise from the beginning of courses of JS at title "Supercharging our example website". 
let myImage = document.querySelector('img');

myImage.onclick = function() {
    let mySrc = myImage.getAttribute('src');
    if(mySrc === 'images/firefox-icon.png') {
      myImage.setAttribute('src','images/firefox2.png');
    } else {
      myImage.setAttribute('src','images/firefox-icon.png');
    }
}

THIS IS NOT OK! CHROME SAY NOTHING! I don't debug yet but soon.

**Comment by chrisdavidmills** [comment]
I'm not 100% sure what you're trying to say here. I've just tried the code, and it works fine in Chrome. I wonder if you are missing something else from your code that is needed for it to work??
