### ISSUE TITLE
New page request: Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign

### ISSUE THREAD

**Issue by nhnt11** [mdn/sprints#3551]
# Request type
- [x] New documentation

# Details
The CookiePartitionedForeign subpage (full path in issue title) is a doc page for a new type of error. We'll be linking to this page as a "Learn more" link in certain console messages. I don't have permission to create new pages - so I'm filing this. Please let me know if you need anything else from me! I (and other anti-tracking engineers) can populate it. Thanks!

**Comment by chrisdavidmills** [comment]
Hi @nhnt11 !

Page created as requested: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign

Just copy the content out of an existing SAP error page and use it as a template.

Also, can you:

* suggest an appropriate page title for the page, in the same style as the other pages?
* Add a suitable decriptive link to the new page in the list here: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors

Thanks. Let me know when you've added it, and I'll be happy to edit/review

**Comment by nhnt11** [comment]
I've filled out some basics and updated the list in the Errors parent page. I want to talk to Steve before adding more details.

**Comment by chrisdavidmills** [comment]
@nhnt11 cool, the contents look fine for now. But more detail is always nice.
