### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint$history?page=1

### ISSUE THREAD

**Issue by HelmZalee** [mdn/sprints#3552]
# Request type

- [ ] Correction or update

# Details
As a complete novice & outsider, I'm struggling with how to make a minor comment.  Mea culpa if I've got it all wrong.

My conditional breakpoint (in the FF debugger) wasn't working as I expected.  I learned why at the subject page (how_to/set_a_breakpoint): The  condition is not "==", which I had guessed because hey, this is javascript.  From the lone example, it is instead "=".  So, equality not being what I guessed, what is && (or maybe &)?

Seems like a very brief summary of comparison operators would be useful.  Simply "C-like, and not javascript-like"  would be adequate (if that's correct).

**Comment by chrisdavidmills** [comment]
This is a funny one — the problem has been caused because the comparson operator shown in the screenshot is wrong — it should be `===`, which is JS strict equality. `=` is assignment. I've updated the screenshot so that it shows the correct operator.

**Comment by HelmZalee** [comment]
Actually, at this moment both = and === seem to work (as the comparison op
in a conditional break).  As I recall, when I posted my question the "="
worked (and, I think, not ===)..  Screenshot below ("editing" a debug
condition) was taken maybe 5 minutes ago.  4 minutes ago, === also worked
(but I took no screenshot).  In neither case is anything assigned, which is
reasonable since this is a debug condition.

[image: image.png]

**Comment by chrisdavidmills** [comment]
Yeah, but IIRC assignments equate to true, so it can look like it is working, but you may get inaccurate results.

**Comment by HelmZalee** [comment]
? These aren't statements in the code; they're instructions to the
debugger.

Just my uninformed opinion.  But the condition and log commands are
accessible only via the debugger pop-up menu.  It wb extraordinarily odd if
it affected the executing code.

Sent from the awful Google gmail client (terrible editor) over T-MOBILE's
sketchy network
