### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

### ISSUE THREAD

**Issue by Iainmon** [mdn/sprints#3553]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Possible Typo: Second paragraph, last sentence of the link provided. "like passing an order several times" => "like placing an order several times"

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

**Comment by chrisdavidmills** [comment]
Hi @Iainmon ! Yeah, I think you're probably right here. I've updated the wording — https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT. Better now?
