### ISSUE TITLE
Properly document <size> (instead of <extent-keyword>) for radial-gradient()

### ISSUE THREAD

**Issue by upsuper** [mdn/sprints#3554]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Currently, keywords `{closest,farthest}-{side,corner}` are listed as `<extent-keyword>` in [`radial-gradient()`](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient#Syntax).

However, they are listed as [`<size>`](https://drafts.csswg.org/css-images-3/#valdef-radial-gradient-size) in the spec, and this part actually allows more than just some keywords: `<length>` and `<length-percentage>` are allowed as well, which can be quite useful in some cases.

There should probably also be some examples make use of non-keyword `<size>` values in [Using CSS gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients).

* [`radial-gradient()`](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient)
* [Using CSS gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients)

**Comment by rachelandrew** [comment]
@chrisdavidmills I have updated the radial gradient page so it now matches the spec.

**Comment by chrisdavidmills** [comment]
Looks great, cheers. I've tweaked it a little bit, but this can be closed now.

**Comment by rachelandrew** [comment]
I've also added a couple of examples to the Using CSS gradients page (for ellipse with length-percentage and circle with length)

**Comment by chrisdavidmills** [comment]
nice one.
