### ISSUE TITLE
Accessibility issues should not be present on documentation.

### ISSUE THREAD

**Issue by pavandixit93** [mdn/sprints#3556]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

I was referring https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Complementary_role, documentation. Documentation is great and helpful. One thing i found that there are lots of accessibility issues present in the document when i ran AXE accessibility checker, Can you guys please fix those?

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7532](https://github.com/mdn/kuma/issues/7532) via [**ZenHub**](https://www.zenhub.com/)
