### ISSUE TITLE
border-width link incorrectly links to border-style

### ISSUE THREAD

**Issue by PauliusSasnauskas** [mdn/sprints#3557]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/CSS/border

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

The **border-width** link in **Constituent properties** section links to border-style, while should link to border-width.

![border-width](https://user-images.githubusercontent.com/40543380/88936718-dee41c80-d28b-11ea-8d6d-6c8c72cf591a.png)

Should link to https://developer.mozilla.org/en-US/docs/Web/CSS/border-width

**Comment by chrisdavidmills** [comment]
Fixed: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/border

Thanks for reporting!
