### ISSUE TITLE
A minor typo

### ISSUE THREAD

**Issue by adebayo10k** [mdn/sprints#3558]
## URL(s)

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

![typo_issue](https://user-images.githubusercontent.com/48807885/89025830-6890fa00-d31f-11ea-8c5e-910d6717e7f9.png)

Step 1 on the second maths task (Math 2) reads:
"Write a calculation that multiples result and result2 together and assigns the result back to result...".

I believe (unless it's a 'locale' issue I'm not aware of) that it should read:
"Write a calculation that multiplies result and result2 together and assigns the result back to result..."

So the letter 'i' could be missing from 'multiplies'.

**Comment by chrisdavidmills** [comment]
Well spotted! I've fixed it now; thanks for reporting.
