### ISSUE TITLE
Typo in https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Deployment

### ISSUE THREAD

**Issue by jokedetone** [mdn/sprints#3559]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

There is a typo in https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Deployment. It says "GITHUP", instead of Github
![mozi](https://user-images.githubusercontent.com/31008564/89088593-48852900-d367-11ea-88d3-4d0b3b216bb8.PNG)

**Comment by chrisdavidmills** [comment]
Fixed!
