### ISSUE TITLE
Issue with example code for aspect-ratio media rule

### ISSUE THREAD

**Issue by amalcolm** [mdn/sprints#3560]
## URL(s)
[https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio#Examples](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio#Examples)

## Request type
- [*] Correction or update

## Details
Tiny issue with example code for aspect-ratio media rule.

When the width slider is dragged to 250 (with height set to the default or 165) the three rules are skipped and background colour goes to white.  It's not an error, just makes the example a tad confusing.

No biggie, just made me think something was broken rather than behaviour by design.

Possible fix is to add a comment describing the behaviour.

**Comment by chrisdavidmills** [comment]
I've added a note to the example description to cover this. Thanks for reporting.
