### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

### ISSUE THREAD

**Issue by vishnuasklua** [mdn/sprints#3561]
# Request type
- Correction or update

# Details
Link - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

String.prototype.replaceAll() is not a function error. I am using Chrome(Version 84.0.4147.105 (Official Build) (64-bit))

<img width="1003" alt="Screenshot 2020-08-01 at 9 54 47 AM" src="https://user-images.githubusercontent.com/53731245/89094003-3219b480-d3dd-11ea-98fd-058db3789267.png">

**Comment by sideshowbarker** [comment]
`String. prototype.replaceAll` isn’t in Chrome 84. As https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#Browser_compatibility shows, Chrome 85 is the first Chrome version to support it.

So it’s normal and expected that it’d fail in Chrome 84.

**Comment by vishnuasklua** [comment]
Thank you.
