### ISSUE TITLE
UI Bug on syntax section https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval

### ISSUE THREAD

**Issue by lo2aai** [mdn/sprints#3563]
# Details

There is a UI bug which shows a small box inside the Syntax decryption with no goal and it also block the full view of the syntax.

url: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval
<img width="1035" alt="Screen Shot 2020-08-01 at 7 54 42 PM" src="https://user-images.githubusercontent.com/37731486/89107485-a4b47f80-d431-11ea-8189-2081471b2e4c.png">

**Comment by chrisdavidmills** [comment]
Looks like this is fixed; I've tested it across a wide range of browsers and can't reproduce the problem.
