### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/order

### ISSUE THREAD

**Issue by pepelsbey** [mdn/sprints#3564]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[MDN’s order property page](https://developer.mozilla.org/en-US/docs/Web/CSS/order) states that it works only in Flexbox context:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/105274/89109401-822e6080-d449-11ea-9691-d386c91faac6.png">

DevTools unused code tooltip suggest that the property is not applicable.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/105274/89109321-cc631200-d448-11ea-9087-4ff6768b4719.png">

But it’s not correct: `order` works the same way in Grid Layout context. See [6.3. Reordered Grid Items: the order property](https://www.w3.org/TR/css-grid-1/#order-property) of the CSS Grid Layout Module L1.

**Comment by chrisdavidmills** [comment]
I've submitted a PR to try and fix this: https://github.com/mdn/data/pull/423

Let me know if you think the wording I've used is OK.

Thanks!
