### ISSUE TITLE
Hash example in CSP style-src documentation must use base64 encoded values

### ISSUE THREAD

**Issue by QwertyManiac** [mdn/sprints#3566]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example provided for hash based values is passing the direct computed hash value instead of a base64 value

Example reads:

```
Alternatively, you can create hashes from your inline styles. CSP supports sha256, sha384 and sha512.

Content-Security-Policy: style-src 'sha256-a330698cbe9dc4ef1fb12e2ee9fc06d5d14300262fa4dc5878103ab7347e158f'
```

But should instead read as:

```
Alternatively, you can create hashes from your inline styles. CSP supports sha256, sha384 and sha512 (in base64 form).

Content-Security-Policy: style-src 'sha256-YTMzMDY5OGNiZTlkYzRlZjFmYjEyZTJlZTlmYzA2ZDVkMTQzMDAyNjJmYTRkYzU4NzgxMDNhYjczNDdlMTU4Zg=='
```

(Where `YTMzMDY5OGNiZTlkYzRlZjFmYjEyZTJlZTlmYzA2ZDVkMTQzMDAyNjJmYTRkYzU4NzgxMDNhYjczNDdlMTU4Zg==` is the base64 encoded value of `a330698cbe9dc4ef1fb12e2ee9fc06d5d14300262fa4dc5878103ab7347e158f`)

Page https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#Unsafe_style_expressions, under section `Unsafe_style_expressions`

**Comment by mikoMK** [comment]
The spec confirms that those hashes have to be base64 encoded.
I can take this issue.

**Comment by chrisdavidmills** [comment]
Thanks @mikoMK ; I've assigned it to you.

**Comment by mikoMK** [comment]
While testing the example i found out that the hash also has to be in binary form before encoding it with base64. This doesn't seem obvious from a web developer's perspective. Therefore I clarified this in the article and added the example from the spec how to achieve the correct conversion.

Any feedback is welcome.

**Comment by chrisdavidmills** [comment]
This update looks great, thanks @mikoMK .

I'm going to close this one now, but feel free to jump in @QwertyManiac if you have any other comments or concerns.
