### ISSUE TITLE
Change request on Function example

### ISSUE THREAD

**Issue by heesu07** [mdn/sprints#3569]
**Summary**
https://developer.mozilla.org/ko/docs/A_re-introduction_to_JavaScript

**Rationale**
function avg(...args) {
    var sum = 0;
    for (let value of args) {
        sum += value;
    }
    return sum / arr.length; <= here is bug, need to change args
}

**Audience**
This is only appear korea language.

**Proposal**
arr.length needs to change args.length

**Additional context**
Thanks

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
