### ISSUE TITLE
typo link on spanish a11y page

### ISSUE THREAD

**Issue by megatux** [mdn/sprints#3571]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

page: https://developer.mozilla.org/es/docs/Web/Accesibilidad/Understanding_WCAG/Teclado

Typo on Spanish page link :    "Entendiento el orden del emfoque"   emfoque ---->   eNfoque

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.

**Comment by megatux** [comment]
Oh!, cool. Done! Regards
