### ISSUE TITLE
Typo on ARIA live regions page

### ISSUE THREAD

**Issue by pdong** [mdn/sprints#3572]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Announce is spelled incorrectly in the note at the top of the page

![image](https://user-images.githubusercontent.com/5158502/89325735-1234fb80-d63e-11ea-93f0-6227b210f350.png)

Should be "announce" not "annouce" (missing the third n)

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting.
