### ISSUE TITLE
Need more content and context in Certificate authority glossary article

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3573]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
From a Matrix discussion with @timeless:mozilla.org:

> Fwiw this page is pretty unhelpful: https://developer.mozilla.org/en-US/docs/Glossary/Certificate_authority
> I mean, it isn't technically wrong. But, it doesn't really fit things into context.
> At least a cross link to a diagram or something would probably be helpful.

**Comment by hamishwillee** [comment]
@chrisdavidmills I've updated this, can you please review.

Bit of a challenge to get the right level. Essentially I've done a few paragraphs to explain that the CA validates the content is accurate, what the content is, that it allows browsers to verify website identify and securely connect over SSL.

The most important bit is probably the link at the end to the Wikipedia page on Public Key infrastructure.

**Comment by chrisdavidmills** [comment]
@hamishwillee I'm by no means an expert in this stuff, but it certainly makes a lot more sense now. I've just tweaked a couple of bits of langauge, and I think this cna be closed now.
