### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by Gwenishere** [mdn/sprints#3574]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Hi,
For this page, in English version, there's an example with explanation but not in the french one. 
Could you fix it please ?
Many thanks
Kind Regards

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
