### ISSUE TITLE
Array.from() should have a NodeList example

### ISSUE THREAD

**Issue by ricealexander** [mdn/sprints#3575]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The [Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) page does not have an example of using `Array.from()` to convert a NodeList into an array.

This is one of the most common and practical uses of `Array.from()`, since NodeLists don't have access to most of the Array methods out of the box.

Some examples that could be used:

```javascript
// Filter DOM Elements based on a criteria
const links = Array.from(document.querySelectorAll('a'));
const insecureLinks = links.filter(link => link.href.startsWith('http://'));
```

```javascript
// Create an array based on a property of DOM Elements
const images = document.querySelectorAll('img');
const sources = Array.from(images, image => image.src);
```

```javascript
// Aggregate information found in the DOM
const durations = document.querySelectorAll('time.duration');
const totalDuration = Array.from(durations, duration => duration.textContent)
    .reduce((total, duration) => total + Number(duration), 0);
```

I'd invite other examples and I notice there's no mention of NodeLists on the [Spread Syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) page either.

**Comment by Prerna237** [comment]
@chrisdavidmills Hello! I can work on this

**Comment by chrisdavidmills** [comment]
Great stuff, thanks @Prerna237 ! I've assigned you to the issue. Let us know when you've worked on it, and we'll gladly provide a review.

**Comment by Prerna237** [comment]
Hi @chrisdavidmills. I have fixed this and published it. 
Also, when I select the review options while editing the page, does it automatically send it to you for review on clicking on Publish or is there some other process that I need to follow to get a review?

**Comment by sideshowbarker** [comment]
@ricealexander it would be great to also get your review on the newly-added example:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Array_from_a_NodeList

**Comment by ricealexander** [comment]
Thanks,

It looks like both my first and second examples were combined to make that example. If this was intended, it might make sense to rename `insecureLinks` to `insecureSources`. I think it's a good example though.

I liked my first example because it showed that `Array.from()` can convert a NodeList into an Array. 

The second example uses `Array.from()`'s map function which is a case where `Array.from()` might be more useful than alternatives such as the spread operator `[...document.querySelector('img')]`.

**Comment by Prerna237** [comment]
@ricealexander Those were great examples. Made the task easier. Wanted to combine both the examples so that the reader can also see a situation where one might want to convert a NodeList into Array.

**Comment by chrisdavidmills** [comment]
Thanks again @Prerna237 ! I've checked the example and it looks good.

Thanks also to @ricealexander for providing useful source examples. I've updated `insecureLinks` to `insecureSources` as you suggested.
