### ISSUE TITLE
"Video_and_audio_content" SVG diagram contains multiple typos

### ISSUE THREAD

**Issue by misterybodon** [mdn/sprints#3576]
# Request type
- [x] Correction or update

# Details
The main SVG image on the document contains many typos. I'd be pleased to help out and fix them, though I'm not sure how to do it.

**Comment by chrisdavidmills** [comment]
article in question: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

**Comment by chrisdavidmills** [comment]
@misterybodon you're right; it'd be nice to fix this. Although I'm not sure if this is out and out typos, or some formatting weirdness —it is more spacing issues than incorrect spelling, I think.

@a2sheppy , did you put this diagram on this article?

**Comment by a2sheppy** [comment]
> @misterybodon you're right; it'd be nice to fix this. Although I'm not sure if this is out and out typos, or some formatting weirdness —it is more spacing issues than incorrect spelling, I think.
> 
> @a2sheppy , did you put this diagram on this article?

I did not; if I had, it would be perfect. I will look at it though.

**Comment by a2sheppy** [comment]
That does look like an SVG I created, but I don't believe it looked like that when I made it...

**Comment by a2sheppy** [comment]
Looks like the export from my editor way back then made assumptioms about font spacing that are no longer true. I'll see if I can update the SVG here.
