### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Embedding_tutorial

### ISSUE THREAD

**Issue by fawazahmed0** [mdn/sprints#3577]
When scrolling down on this page, https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Embedding_tutorial#definingHostObjects
a large black index seems to cover the part of page

![-2020-aug-5-001](https://user-images.githubusercontent.com/20347013/89460251-98a92480-d787-11ea-86a8-f96060d1c71d.jpg)

**Steps to reproduce:**
1. Try scrolling down at https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Embedding_tutorial

**Comment by chrisdavidmills** [comment]
@fawazahmed0 hrm, that is weird! I've removed the styling so that you still get the TOC, but it is no longer sticky so therefore doesn't interfere with reading the page. Thanks for reporting.
