### ISSUE TITLE
https://developer.mozilla.org/zh-TW/docs/Learn/Getting_started_with_the_web/HTML_basics

### ISSUE THREAD

**Issue by iamshun** [mdn/sprints#3578]
# Request type

- [X] Correction or update

# Details

in 正體中文 (繁體)

<img width="684" alt="截圖 2020-08-06 下午12 20 59" src="https://user-images.githubusercontent.com/6903063/89490838-5cee7900-d7e0-11ea-9cf9-5d9379e74ed2.png">
<p>below link 404 :</p>
<p>請試試在這裡 What should your website look like? 的圖片（<img> element）下方，加上幾段文字。</p>

-----------------------------------

<img width="590" alt="截圖 2020-08-06 下午12 21 19" src="https://user-images.githubusercontent.com/6903063/89490845-5f50d300-d7e0-11ea-9918-3641e687872c.png">
<p>代表這些項目的順序改變，不影響任何**是**</p>
<p>should be</p>
<p>代表這些項目的順序改變，不影響任何**事** </p>

-----------------------------------

<img width="416" alt="截圖 2020-08-06 下午12 21 49" src="https://user-images.githubusercontent.com/6903063/89490846-60820000-d7e0-11ea-95d9-a017e6b6c845.png">
<p>在&lt;a&gt; element 中加上href attribute這個屬性：</p>
<p>be supposed to</p>
<p>在&lt;a&gt; 元素 中加上href 這個屬性：</p>
--
<p>屬性質就是你要連結網址：</p>
<p>should be</p>
<p>屬性值就是你要連結的網址：</p>

https://developer.mozilla.org/zh-TW/docs/Learn/Getting_started_with_the_web/HTML_basics

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
