### ISSUE TITLE
Potential type mismatch in String.prototype.split() reference

### ISSUE THREAD

**Issue by air-wreck** [mdn/sprints#3581]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the [reference page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) for `String.prototype.split([separator[, limit]])`, the following is stated under the Syntax section for the optional `limit` argument:

> If `limit` is `1`, `str.split(separator)[0]` is returned

However, this is appears to be a string, not a string array:

``` javascript
"foo bar".split(" ", 1);  // ["foo"]
"foo bar".split(" ")[0];  // "foo"
```

Is this intentional, or should the text be changed to reflect this? I feel like the current wording can be misleading if read too quickly.

**Comment by chrisdavidmills** [comment]
This has already been updated. Check the page again.
