### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection - Left column lists incorrect properties and methods.

### ISSUE THREAD

**Issue by parke** [mdn/sprints#3582]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the referenced page, the left "quick navigation" column incorrectly lists:

Properties
item

The correct list would be:

Properties
length

Methods
item()
namedItem()

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7531](https://github.com/mdn/kuma/issues/7531) via [**ZenHub**](https://www.zenhub.com/)
