### ISSUE TITLE
Search returns nothing for known topic  ("?.")

### ISSUE THREAD

**Issue by tshinnic** [mdn/sprints#3583]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

So couldn't remember the magic keyword for new Javascript operator/syntax, though using it. So entered "?." into MDN search. Nothing. Wandered around web and saw 'chaining'. Enter that and see link to topic "Optional chaining (?.)". 

Is it not possible to have search aliases for topics? As search is consistently the weakest feature of MDN documentation, I wouldn't exclude that.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7530](https://github.com/mdn/kuma/issues/7530) via [**ZenHub**](https://www.zenhub.com/)
