### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

### ISSUE THREAD

**Issue by tuorhador** [mdn/sprints#3584]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example listed for explaining the significance of ```initialValue``` seems to be incorrect for the first case. The result NaN is got **_not_** because of lack of ```initialValue``` but because ```maxCallback``` is not returning an object having property ```x```. Please review.
![mdn-reduce-prob](https://user-images.githubusercontent.com/44376511/89613236-6559b900-d89f-11ea-8757-6d112ee3db3e.png)

**Comment by Prerna237** [comment]
@chrisdavidmills : I can pick this up and fix it. Since I am just starting out, could you please let me know what is the process like?

**Comment by chrisdavidmills** [comment]
Hi @Prerna237 !

The following contribute page explains how the process should work for fixing MDN content bugs like these: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Fixing_MDN_content_bugs

Usually you'd first of all say that you want to take on a bug, and then I'd assign it to you to fix. But In this case you've just jumped in and fixed it anyway, which is also fine ;-)

I've reviewed your work and it looks good, and I've also assigned you to this bug so it easier to see which ones you've worked on (credit where credit is due, etc.)

Thanks so much for providing a fix for this; you rock!
