### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

### ISSUE THREAD

**Issue by slk333** [mdn/sprints#3585]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The live sample is not working for following values: end, right, flex-end
see:
https://imgur.com/a/MN6qeZw

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by chrisdavidmills** [comment]
Works for me. They are basically equivalent.
