### ISSUE TITLE
Remove selected MDN Pages

### ISSUE THREAD

**Issue by Emilfs** [mdn/sprints#3586]
**Summary**
_What is the problem?_
These pages doesn't provide interesting information and it's better to delete them (discussed with @sylvestre):
https://developer.mozilla.org/en-US/docs/Mozilla/An_introduction_to_hacking_Mozilla
https://developer.mozilla.org/en-US/docs/Mozilla/Creating_a_localized_Windows_installer_of_SeaMonkey
https://developer.mozilla.org/en-US/docs/Mozilla/Git
https://developer.mozilla.org/en-US/docs/Mozilla/Getting_started_with_IRC
https://developer.mozilla.org/en-US/docs/Mozilla/Mercurial
https://developer.mozilla.org/en-US/docs/Mozilla/Mozilla_SVG_Project
https://developer.mozilla.org/en-US/docs/Mozilla/SeaMonkey
https://developer.mozilla.org/en-US/docs/Mozilla/The_Mozilla_platform
https://developer.mozilla.org/en-US/docs/Mozilla/Using_CXX_in_Mozilla_code
https://developer.mozilla.org/en-US/docs/Mozilla/XMLHttpRequest_changes_for_Gecko_1.8
https://developer.mozilla.org/en-US/docs/Debugging/Coverity
https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Firefox_and_Address_Sanitizer#LeakSanitizer
https://developer.mozilla.org/en-US/docs/Mozilla/Creating_Mercurial_User_Repositories

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. 
2. 
3. 

**Actual behavior**
_What actually happened?_

**Expected behavior**
_What did you expect to happen?_

**Additional context**
_Is there anything else we should know?_

**Comment by peterbe** [comment]
@Emilfs Can you provide any "proof" that @sylvestre has blessed the forever deletion of these URLs? 
Is there an official Bugzilla ticket that lists them. 
And, most importantly, should they redirect rather than just disappear?

**Comment by peterbe** [comment]
By the way, all of these pages will end up in the archive after the Yari migration. 
That means you won't have to see these pages as editable. They'll just be stored in their final rendered form and we might package them once and upload to S3 so they won't 404 at least but they won't be part of the MDN content any more.

**Comment by sylvestre** [comment]
I can sign off from @sylvestre :)

We have been maintaining this list:
https://docs.google.com/spreadsheets/d/1w5WIy_X4vbIWrxH4pC8geqWKgpinj31I9ePwvBcZ9vQ/edit?ts=5f2c0daf#gid=1599531737
to cleanup MDN

We could redirect them to https://firefox-source-docs.mozilla.org/

**Comment by peterbe** [comment]
> We could redirect them to https://firefox-source-docs.mozilla.org/

You said "could". But do you **prefer** redirects? Or do you prefer that they just wither away but still 200 OK?

Because if redirects are preferred, I think we can take care of this nowish and not have to worry about any of those docs forever. We're doing something very similar with a bunch of old WebExtension and [Firefox Accounts for example](https://github.com/mdn/kuma/blob/06f03d3810f173340aa751e47f5a5605339206e2/kuma/redirects/redirects.py#L1160-L1173).

**Comment by sylvestre** [comment]
Whatever is the easier for you :) I don't have a strong opinion here.
Maybe @mhoye has an opinion ?

**Comment by chrisdavidmills** [comment]
Looks like these are all deleted or archived now, so closing.
