### ISSUE TITLE
Deprecated modifier key values of KeyboardEvent.getModifierState()

### ISSUE THREAD

**Issue by hax** [mdn/sprints#3587]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

Current section "Browser compatibility" of https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState list "Accel", "Alt", "AltGraph", "Hyper" and  "Super" as deprecated, but it's not clear why "Alt" and "AltGraph" are deprecated, I can't find any reference about deprecating them in related specs.

On the other hand, "OS" have been [removed](https://github.com/w3c/uievents-key/commit/392450b23ed451effbbb99e5fd2e9c3dfc9c4242) from the [spec](https://w3c.github.io/uievents-key/#keys-modifier) long ago, and as uievents-key spec:
> The Meta key ... is used for the Windows Logo key

So I believe "OS" value should be deprecated.

Also, I think "Specifications" section could be updated to refer to ui-events and uievents-key spec.

**Comment by MendyBerger** [comment]
Not sure exactly how the spec works, but it looks like you're right about "Alt" and "AltGraph" not being deprecated as they are both still listed [here](https://www.w3.org/TR/uievents-key/#keys-modifier), can anyone with experience in spec reading confirm this please?
