### ISSUE TITLE
Not working example: Showing file(s) size

### ISSUE THREAD

**Issue by kamre** [mdn/sprints#3588]
# Request type
- Correction or update

# Details
The example code for "Showing file(s) size" presented on the page https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications is not working!

In particular the problem is that the script is executed before the body, that is why we get null from `document.getElementById("uploadInput")`.

**Comment by chrisdavidmills** [comment]
As a short-term fix, I've put the script element at the bottom of the body. Thanks for reporting.
