### ISSUE TITLE
Turkish and English (US) of Array.prototype documentation page is falsely mapped

### ISSUE THREAD

**Issue by NRockhouse** [mdn/sprints#3589]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The English documentation of the JavaScript `Array.prototype` property is mapped to the Turkish version of the site.
https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype

By clicking on any hyperlinks on that page, I am correctly linked to the Turkish version of the documentations. However, when navigating back to `Array.prototype` from any part of the Turkish site, this English documentation is served.

If I wanted to navigate to the English (US) version of this page by choosing it from the language dropdown, I am directed to this link with a 404 page.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype

This also applies to the history page:
Turkish (200 OK): https://wiki.developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype$history
English (US) (404 Not Found): https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype$history

**Comment by chrisdavidmills** [comment]
I think this basically happens with pages where there is no translation available — it falls back to the english version, rather than showing nothing.
