### ISSUE TITLE
Incorrect statement about not defined object properties access order.

### ISSUE THREAD

**Issue by 4javier** [mdn/sprints#3591]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
This is just one of different pages where it's incorrectly stated that method's accessing order is not defined.
>The ordering of the enumerable properties in the array is consistent with the ordering exposed by a for...in loop (or by Object.keys()) over the properties of the object. The ordering of the non-enumerable properties in the array and the ordering among the enumerable properties is not defined.

Since ES6, situation is different for some Object.prototypes methods:  getOwnPropertyNames, getOwnPropertySymbols, defineProperties, and ownKeys.
As you can read i.e. https://www.ecma-international.org/ecma-262/6.0/#sec-object.getownpropertynames, underlying calls http://www.ecma-international.org/ecma-262/6.0/#sec-getownpropertykeys, that relies on http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys. 
The last one explicitly says
>When the [[OwnPropertyKeys]] internal method of O is called the following steps are taken:

    Let keys be a new empty List.
    For each own property key P of O that is an integer index, in ascending numeric index order
        Add P as the last element of keys.
    For each own property key P of O that is a String but is not an integer index, in property creation order
        Add P as the last element of keys.
    For each own property key P of O that is a Symbol, in property creation order
        Add P as the last element of keys.
    Return keys.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames

**Comment by Prerna237** [comment]
Hello @chrisdavidmills . I can pick this task up :)

**Comment by chrisdavidmills** [comment]
@Prerna237 assigned. Thank you!

**Comment by Prerna237** [comment]
@chrisdavidmills 
Apologies for the delay! Was travelling for a while.

I have added the fix for the page mentioned. However, I couldn't find any mention of 'method's accessing order is not defined' on the pages of common Object methods. @4javier Please do let me know if there are other pages that need similar correction.

**Comment by 4javier** [comment]
Hi @Prerna237. Thanks for corrections.
To be honest, after three months I cannot remind exactly where I see similar statements, and after a quick research I couldn't find them.
I take this opportunity to notify that in ES2020 an access order has been specified for Object.keys and the for...in loop, too.

**Comment by chrisdavidmills** [comment]
@Prerna237 no worries at all; thanks for the fixes!

@4javier so based on your response, is it fair to say that we can close this one now? If there is another improvement or fix to report, then I'd prefer that you did it in a separate issue. Thanks!

**Comment by 4javier** [comment]
@chrisdavidmills 
Yes. I think it can be closed now. Thanks.

**Comment by chrisdavidmills** [comment]
Ok, closing. Thanks @4javier !
