### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new

### ISSUE THREAD

**Issue by ldelaprade** [mdn/sprints#3594]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The **english** version of new operator step 2 is not as clear as in french

The new keyword does the following things:

1. Creates a blank, plain JavaScript object;
**_2. Links (sets the constructor of) this object to another object;_**
3. Passes the newly created object from Step 1 as the this context;
4. Returns this if the function doesn't return an object.

French version

1. Il crée un nouvel objet à partir de zéro
**_2. Il lie cet objet à un autre objet en le définissant comme son prototype._**
3. Le nouvel objet, créé à l'étape 1, est passé comme valeur this à la fonction
4. Si la fonction ne renvoie pas d'objet, c'est la valeur this qui est renvoyée

Well, then, a clearer the English version for step 2 could be
**_2. Links (sets the constructor of) newly created object to the other object by setting the other object as its parent prototype;_**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new

**Comment by chrisdavidmills** [comment]
Wording updated — thanks for the tip!
