### ISSUE TITLE
Wrong byte for HT in "CORS-unsafe request header byte" definition

### ISSUE THREAD

**Issue by Androbin** [mdn/sprints#3595]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Observed:
_CORS-unsafe request header byte_: 0x00-0x1F (except 0x08 (tab)), `"():<>?@[\]{}`, and 0x7F (delete).

Expected:
_CORS-unsafe request header byte_: 0x00-0x1F (except 0x09 (tab)), `"():<>?@[\]{}`, and 0x7F (delete).

Page: [CORS-safelisted request header](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header)
Page: [Accept - HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)
Page: [Content-Type - HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)

Resource: [CORS-unsafe request-header byte](https://fetch.spec.whatwg.org/#cors-unsafe-request-header-byte)

Resource: [ASCII Code](https://www.ascii-code.com/)

**Comment by hamishwillee** [comment]
Thanks. This has been fixed/tidied in the identified places.
