### ISSUE TITLE
Image does not exist.

### ISSUE THREAD

**Issue by benThijssen** [mdn/sprints#3598]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details
url https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture, explaining the `<picture>` tag, is referring to an image that does not exist. 

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: media/examples/surfer-240-200.jpg
    RequestId: 05EDF0AFF338A023
    HostId: hHeQ7VXaLS81qHJGAUJxGRpYEpEZSojoQ5udadP2uFe/RHW08U4NWvKxnow0DLmjv0cLQdGiUdE=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

**Comment by djm2k** [comment]
[plumeria.jpg](https://interactive-examples.mdn.mozilla.net/media/examples/plumeria.jpg) is also missing from the [CSS object-fit docs](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)

**Comment by chrisdavidmills** [comment]
This bug is fixed now.
