### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete

### ISSUE THREAD

**Issue by Artur93gev** [mdn/sprints#3600]
Thanks, for a great job.
# Request type

- [x] Correction or update

# Details

The example is missing the `fixRedEye` function. Can lead to misunderstanding.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete

**Comment by chrisdavidmills** [comment]
There are multiple things missing from this example that stop it being complete, but it is only supposed to be figurative, and it does demonstrate how to use the `complete` property.
