### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms

### ISSUE THREAD

**Issue by markstrefford** [mdn/sprints#3601]
# Request type

[x] Correction or update

# Details

On page [https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms), in the section "Orientation compensation", the link to [demo of orientation compensation](http://fiddle.jshell.net/j9fRj/5/show/) is broken.

**Comment by chrisdavidmills** [comment]
I've deleted the link; I haven't got a replacement link at this time. Thanks for reporting!
