### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

### ISSUE THREAD

**Issue by Elainelele** [mdn/sprints#3602]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

reducer 函数接收4个参数:

Accumulator (acc) (累计器)
Current Value (cur) (当前值)
Current Index (idx) (当前索引)
Source Array (src) (源数组)
您的 reducer 函数的返回值分配给累计器，该返回值在数组的每个迭代中被记住，并最后成为最终的单个结果值。

这里应该是 reduce  而不是 reducer 吧？

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
