### ISSUE TITLE
Firefox Releases

### ISSUE THREAD

**Issue by NargiT** [mdn/sprints#3603]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello,

When accessing the release page, I found that the latest version of firefox on android is 68.11.0 but on my mobile, accessing google play, I can see 79.0.3. This is very confusing

https://www.mozilla.org/en-US/firefox/releases/ 
https://www.mozilla.org/en-US/firefox/android/notes/ redirect to https://www.mozilla.org/en-US/firefox/android/68.11.0/releasenotes/
https://play.google.com/store/apps/details?id=org.mozilla.firefox -> shows 68.11.0 on regular browser

Images:
[Firefox version accessible from the application](https://dl3.pushbulletusercontent.com/q3GblEMzlF31v8rTV1w02jTPpKwVZTIW/Screenshot_20200813-070019_Firefox.jpg)

[Firefox version displayed on google play from the mobile application](https://dl3.pushbulletusercontent.com/FwVjEDHL0NbHZJkMc7KcWgFEZ14QUOFD/Screenshot_20200813-070132_Google%20Play%20Store.jpg)

[Firefox version display on google play from a browser](https://dl3.pushbulletusercontent.com/VuscOlWxywjpDSnYG3huLSs3C8ozPljV/image.png)

**Comment by NargiT** [comment]
Any idea? now i have 79.0.5

**Comment by chrisdavidmills** [comment]
Hi @NargiT, the answer is that Firefox Mobile was not updated for a long time, while they worked on a complete new version. So it was stuck on the old version (fennec) for quite a lot of versions.

AFAIU, the new version (fenix) has just bene released to the app store, hence the version number jumping.

**Comment by NargiT** [comment]
Still does not explain why the website is not up to date. I have a ticket open for an application because the app does not work with my version of firefox. And they rely on the version specified on the website....@chrisdavidmills

**Comment by chrisdavidmills** [comment]
I've just tried firefox mobile release on my Android phone, and the version is showing as 79.0.5.

Are you saying that you've still got 68.0.x installed? Try uninstalling and installing again?

**Comment by NargiT** [comment]
This issue concerns the following link https://www.mozilla.org/en-US/firefox/android/notes/  and understand why it's not up to date with what the play store shows.
