### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Mozilla/Bugzilla

### ISSUE THREAD

**Issue by Jim-Ryna** [mdn/sprints#3604]
# JavaScript embeded inside vxml can't be handled properly in mozjs-52.9.1

- [x] version: mozjs-52.9.1pre1
- [ ] New documentation
[TeActCBA.zip](https://github.com/mdn/sprints/files/5067423/TeActCBA.zip)

- [ ] Correction or update

# Details

when we invoked the api JS_PUBLIC_API JS::Evaluate(JSContext* cx, AutoObjectVector& envChain, const ReadOnlyCompileOptions& optionsArg, const char16_t* chars, size_t length, MutableHandleValue rval) to handle line160 of attachment file,TeActCBA.vxml,ie <assign name="bDecimalNum" expr="IsDecimalNum(Digit)"/>,error happens inside CASE(JSOP_GETNAME), beacuse GetNameOperation return false and then goto error.
static inline bool
GetNameOperation(JSContext* cx, InterpreterFrame* fp, jsbytecode* pc, MutableHandleValue vp)
{
    JSObject* obj = fp->environmentChain();
    PropertyName* name = fp->script()->getName(pc);
    if (IsGlobalOp(JSOp(*pc)) && !fp->script()->hasNonSyntacticScope())
        obj = &obj->global().lexicalEnvironment();
    Shape* shape = nullptr;
    JSObject* env = nullptr;
    JSObject* pobj = nullptr;
    if (LookupNameNoGC(cx, name, obj, &env, &pobj, &shape)) {
        if (FetchNameNoGC(pobj, shape, vp))
            return true;
    }
    RootedObject objRoot(cx, obj), envRoot(cx), pobjRoot(cx);
    RootedPropertyName nameRoot(cx, name);
    RootedShape shapeRoot(cx);
    if (!LookupName(cx, nameRoot, objRoot, &envRoot, &pobjRoot, &shapeRoot))
        return false;
    JSOp op2 = JSOp(pc[JSOP_GETNAME_LENGTH]);
    if (op2 == JSOP_TYPEOF)
        return FetchName<true>(cx, envRoot, pobjRoot, nameRoot, shapeRoot, vp);
    **return FetchName<false>(cx, envRoot, pobjRoot, nameRoot, shapeRoot, vp);**//return 0 in this branch
}

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
