### ISSUE TITLE
https://developer.mozilla.org/ru/

### ISSUE THREAD

**Issue by vcaraseni** [mdn/sprints#3605]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details
Misspelled word - "пРолучить".

<img width="716" alt="Screen Shot 2020-08-13 at 12 50 46" src="https://user-images.githubusercontent.com/29131962/90121001-19f24f80-dd64-11ea-9184-b5a0cce3b837.png">

https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Cache-Control

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
