### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths$history

### ISSUE THREAD

**Issue by pxf3** [mdn/sprints#3607]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the Bezier Curve section example code, line 4, the x2 and x parameters to the cubic curve should be 110 not 120
```
<path d="M 70 10 C 70 20, 120 20, 120 10" stroke="black" fill="transparent"/>
```
should be
```
<path d="M 70 10 C 70 20, 110 20, 110 10" stroke="black" fill="transparent"/>
```
![svgExample](https://user-images.githubusercontent.com/42649284/90141393-169d9a80-dd49-11ea-9e2b-0835f08095f5.png)

https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths$history

**Comment by chrisdavidmills** [comment]
I believe I've fixed it now. Thanks for reporting.
