### ISSUE TITLE
Part of the page content is not displayed

### ISSUE THREAD

**Issue by huge689** [mdn/sprints#3609]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
![image](https://user-images.githubusercontent.com/44516016/90209234-62217880-de1d-11ea-990b-1905d669ce42.png)

**Comment by chrisdavidmills** [comment]
This works for me; can you try it again?

**Comment by chrisdavidmills** [comment]
Hrm, This seems to work fine for me and a couple of my colleagues, so I don't really know what to say. I'm closing this for now, but we'll keep an eye out for any strange behavior.
