### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align - broken image

### ISSUE THREAD

**Issue by Rtzoor** [mdn/sprints#3610]
# Request type

- [x] Correction or update

# Details

In docs/Web/CSS/vertical-align in the CSS Demo: vertical-align the star image is broken :(

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

**Comment by chrisdavidmills** [comment]
This looks to be fixed now. Closing.
