### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

### ISSUE THREAD

**Issue by ienzam** [mdn/sprints#3611]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[String.prototype.split() documentation > Syntax > limit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#:~:text=If%20limit%20is%201,%20str.split(separator)[0]%20is%20returned)

In documentation of parameter `limit`, it says that

> If `limit` is 1, `str.split(separator)[0]` is returned

The text may have a few issues -
* I interpreted this as if limit is 1, `str.split()` returns a string instead of an array.
* Even if I consider this returns array, this gives another false sense that the array will always contain one item, which is not true.
  * `"".split("", 1)` will return empty array

If the documentation has to mention a special case for 1 (which I think is not that important, example below should cover this), we can rephrase a little bit -

> If `limit` is 1, the returned array will contain at most one element - `str.split(separator)[0]`.

**Comment by chrisdavidmills** [comment]
I updated this already in response to another bug, so the text is different now; closing this.

Please let me know if you think this needs more work.
