### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks : Spelling Mistake

### ISSUE THREAD

**Issue by prady39** [mdn/sprints#3612]
## URL(s)
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

## Request type

- [x] Correction or update

## Details

In https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks: 'commonly' is not spelled correctly in the 'Specifying details' section as can be seen from the screenshot below.
![Screenshot from 2020-08-16 10-59-05](https://user-images.githubusercontent.com/51395023/90327348-8497cb00-dfb0-11ea-8f57-2661e9b4c9a9.png)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting.
