### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete

### ISSUE THREAD

**Issue by phasic** [mdn/sprints#3615]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the example line 9 it says: 

```
elem.src = src;
```

But it should be: 

```
elem.src = url;
```

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete

**Comment by chrisdavidmills** [comment]
I think you're right here. Page changed. Thanks for reporting!
