### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions

### ISSUE THREAD

**Issue by zukululushikufu** [mdn/sprints#3622]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
![image](https://user-images.githubusercontent.com/41569772/90741633-3c70f500-e29d-11ea-8e86-19b92bbce2bf.png)

The padding for the physical and logical properties examples are not identical. I am unsure if it was intended to be different or not but if we wanted it to be identical the padding should be padding-inline-end instead of padding-inline-start.

**Comment by chrisdavidmills** [comment]
I think you are correct that this should be the same rendered output. I've changed the embedded example as suggested. Thanks for reporting!
