### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS#Using_the_create_method

### ISSUE THREAD

**Issue by misterybodon** [mdn/sprints#3623]
# Request type

- [ ] Correction or update

I'm linking you to the section in the title. I just wonder...Why do you explain Object.create() instead of Object.assing(target,source) isn't the second one the one fitting the context?

**Comment by gidansau69** [comment]
пт, 21 авг. 2020 г., 6:09 Mister Nobody <notifications@github.com>:
