### ISSUE TITLE
Broken link on Mozilla Source Code page

### ISSUE THREAD

**Issue by jpear1** [mdn/sprints#3626]
# Request type
- [x] Correction or update

# Details
On [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Viewing_and_searching_Mozilla_source_code_online), the "comm-1.9.1" [link](https://hg.mozilla.org/releases/comm-1.9.1/) leads to a blank page with title ": Error".

**Comment by chrisdavidmills** [comment]
I think this got updated already to include the problematic link. Closing.
