### ISSUE TITLE
An invalid documentation link!!!

### ISSUE THREAD

**Issue by sfshf** [mdn/sprints#3628]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I was following [a documentation link](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Negotiating_an_HTTP_version) of [Negotiating an HTTP version section](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP#Articles), but i got a response of 404.

**Comment by sfshf** [comment]
But i want to learn about the section, where could i get the relevant articles? Please help me! :)

**Comment by chrisdavidmills** [comment]
It looks like the article was never written, and I don't have an equivalent to point you to. https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation is related, but not quite the same.

**Comment by sfshf** [comment]
Thank you very much! I got it.
