### ISSUE TITLE
Issues on Using CSS counters page

### ISSUE THREAD

**Issue by kcarmody** [mdn/sprints#3629]
# Request type
- [x] New documentation

# Details

This concerns the following MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

The second sample on this page, the one that uses ol, does not actually work as documented.  Moreover, the way both FF and Chrome render this code appears to be buggy.  I have reported this apparent bug on Bugzilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1606359  

There seems to be a general issue with counters and ol in FF that is now pending.  An example that uses something other than ol would probably be a good idea for this MDN page for now.  If it could also show @counter-style, that would be even better!

I have made a CodePen to demonstrate the browser rendering of the two samples: https://codepen.io/kcarmody/pen/xxVgxjG

The chart below shows the rendering as reported on the MDN page and the actual rendering in Firefox and Chrome.

Documented                 | Actual FF and Chrome   
-------------------------- | -----------------------
Section 1: Introduction    | Section 1: Introduction
Section 2: Body            | Section 2: Body        
Section 3: Conclusion      | Section 3: Conclusion  
 1 item                    | 3.1 item              
 2 item                    | 3.2 item              
   2.1 item                |   3.2.1 item          
   2.2 item                |   3.2.2 item          
   2.3 item                |   3.2.3 item          
     2.3.1 item            |     3.2.3.1 item      
     2.3.2 item            |     3.2.3.2 item      
     2.3.1 item            |     3.2.3.1 item      
     2.3.2 item            |     3.2.3.2 item      
     2.3.3 item            |     3.2.3.3 item      
   2.4 item                |   3.2.3.4 item        
 3 item                    | 3.2.4 item            
 4 item                    | 3.2.5 item            
 1 item                    | 3.1 item              
 2 item                    | 3.2 item

**Comment by rachelandrew** [comment]
I'm looking at this and the example you refer to has HTML comments detailing the expected rendering, which seems to match the rendering in Firefox and Chrome, your CodePen has combined the two demos which is different to what we have documented.

Are you saying the rendering is incorrect as per the spec? As it seems to be right in terms of what we have documented here.

**Comment by kcarmody** [comment]
The MDN page was corrected very soon after I reported the problem.  I should have closed this issue then and am doing so now.  Sorry for the misunderstanding.

**Comment by rachelandrew** [comment]
@kcarmody no problem - glad it is sorted!
