### ISSUE TITLE
Soft-broken links on <abbr> page

### ISSUE THREAD

**Issue by prcmt** [mdn/sprints#3631]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details
The page [`<abbr>`: The Abbreviation element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) twice links to a page named [_How to mark abbreviations and make them understandable_](https://developer.mozilla.org/en-US/Learn/HTML/Howto/Mark_abbreviations_and_make_them_understandable), which no longer exists. It now redirects to a page that does not contain the content implied by the links on the `<abbr>` page.

**Comment by chrisdavidmills** [comment]
I originally put this redirect in place because the original linked page was largely repeating what the redirected to section is saying.

If you feel that it needs improvement, then I'm more than happy to work on that. What additions did you have in mind?

**Comment by prcmt** [comment]
Looking at it again, I'm not sure that the section in the _Advanced text formatting_ page provides any information that isn't already on the _<abbr>_ page. So maybe it's not worth linking from the latter to the former at all.
