### ISSUE TITLE
CSS Contain page has broken images

### ISSUE THREAD

**Issue by DemiImp** [mdn/sprints#3632]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Images on the page have bad URLs:
https://mdn.mozillademos.org/en-US/docs/Web/CSS/contain$samples/graphic.jpg
https://mdn.mozillademos.org/en-US/docs/Web/CSS/contain$samples/i-just-showed-up.jpg

Page:
https://developer.mozilla.org/en-US/docs/Web/CSS/contain

**Comment by chrisdavidmills** [comment]
I don't think this is actually broken — I think this is how the example was written, and it still demonstrates the behavior nicely.

I'll keep this bug open in case someone wants to improve the example by showing actual images. Note that the alt text is actually quite helpful to understand the example.

**Comment by jadjoubran** [comment]
I could take this one ✋
I'll aim to find some plain placeholder images, can I have this task @chrisdavidmills?

**Comment by chrisdavidmills** [comment]
I've assigned you; thanks a lot @jadjoubran !

**Comment by jadjoubran** [comment]
Before I make the edits for this one, I thought I could upload a custom image but that's not possible.
So would it be okay to use a link such as https://via.placeholder.com/150 ?
I'm worried that a few years from now it won't be available (as well as potential cookie issues).
Is there an image on MDN or mozilla's domain that I can use?

**Comment by chrisdavidmills** [comment]
@jadjoubran A better solution might be to upload the to a suitable place on the https://github.com/mdn/css-examples repo, and then embed it using the `{{EmbedGHLiveSample()}}` macro call (see the source of https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills for an example).

This way CORS won't be a problem, and it will be easily available for anyone to edit.

**Comment by jadjoubran** [comment]
Hey @chrisdavidmills would it be possible to look at the PR above so I can continue this task? Thanks!

**Comment by chrisdavidmills** [comment]
@jadjoubran yup, done, and merged.

**Comment by jadjoubran** [comment]
Thanks @chrisdavidmills 
I'm still having issues implementing it because this is a GHLiveSample and in the **preview** all the live samples don't load
Would this work?
![Screenshot 2020-11-09 at 14 23 37](https://user-images.githubusercontent.com/2265232/98546559-2caeee80-2297-11eb-910f-d8a485587d6d.png)
I tried setting the src to `{{EmbedGHLiveSample("css-examples/placeholder-images/placeholder-100.jpg", 100, 100)}}` but then I end up seeing the image rendered in the source code

**Comment by chrisdavidmills** [comment]
@jadjoubran ah, I see what's going on here! So the `EmbedGHLiveSample` macro only works for embedding complete examples into the page via an IFrame — it needs to point to the index HTML file of an example.

I've created new versions of these examples in the repo, and then embedded them on the page.

**Comment by jadjoubran** [comment]
Ah makes sense 
The issue should be done now 👍

**Comment by chrisdavidmills** [comment]
Cool, let's close.
