### ISSUE TITLE
Problem with section: "Creando una Promise"

### ISSUE THREAD

**Issue by Byron2016** [mdn/sprints#3633]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

There are not all the example code. there are a square but no information inside.
![ff_01](https://user-images.githubusercontent.com/15000602/91303469-aee64700-e76d-11ea-85ca-3c310f077d64.JPG)

Page: [https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Promise](url) section: Creando una Promise

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations.
