### ISSUE TITLE
Changing document.domain and different kinds of "same-origin policy"

### ISSUE THREAD

**Issue by deant** [mdn/sprints#3637]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin
https://developer.mozilla.org/en-US/docs/Web/API/Document/domain

## Request type

- [x] New documentation
- [ ] Correction or update

## Details

The page on same-origin policy describes how document.domain can be used to "change the page's origin", but doesn't make it clear that this applies to only _some_ kinds of same-origin checks.  In particular, this section should explain that the **origin** used by `localStorage`, `indexedDB`, `BroadcastChannel`, `SharedWorker`, and perhaps some other features (?) **can NOT be changed** by assignments to `document.domain`.  The document.domain page should also mention this.  Currently this fact is not at all clear, and neither is the reason for it.

While merely mentioning this would be a start, the underlying reason seems to be that there is more than one kind of "same-origin" check, so a better fix would be to describe the different kinds of same-origin check that exist, _why_ they differ, and which ones are affected by changing `document.domain`.

The same-origin policy page should also mention that there are certain cases where `document.domain` can't be changed, as listed on the latter's page:  In particular, that sandboxed iframes and the document-domain `Feature-Policy` can prevent `document.domain` from being changed is worth mentioning on the same-origin page.

**Comment by hamishwillee** [comment]
Fair enough. This limitation of changing origin for web APIs is widely reported, but I can't find any specific reason for it, or any list of which APIs are affected. As `document.domain` is _deprecated_ I don't think it is worth following up in detail exactly what works or does not and why (though I _suspect_ that it is just that given the API is known to have holes, it simply isn't being updated to work with newer API features). What I have done therefore is, as suggested, made this particular limitation clear in both docs.

Specifically:

- Updated [Same origin policy > Changing origin]()https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin) ([change list](https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy$compare?locale=en-US&to=1652975&from=1652316)):
  - Added a warning up to that this mechanism is deprecated
  - At end of section added a subset of limitations (to provide a "flavour") and linked to the Document.domain doc for more exhaustive list.
- [Document.domain > Failures section](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document/domain#Failures)
([changelist](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document/domain$compare?locale=en-US&to=1652974&from=1644382))
  - Appended info that this doesn't work with the web APIs (with list of the ones we know about).

@chrisdavidmills Could you please sanity check.

**Comment by chrisdavidmills** [comment]
Looks pretty decent, thanks @hamishwillee !

I'll close this now, but feel free to jump in @deant if you think anything else is needed here.

**Comment by deant** [comment]
Looks good to me.
Thanks.
