### ISSUE TITLE
an mistake in the article on page:https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Functions

### ISSUE THREAD

**Issue by bronybro** [mdn/sprints#3638]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details

- [ ] New documentation
- [x] Correction or update

# Details

There is an mistake in the article on page:
![image](https://user-images.githubusercontent.com/54715893/91606195-520bac00-e97a-11ea-9fd9-81d475ed21bf.png)

Another mistake:
![image](https://user-images.githubusercontent.com/54715893/91608684-afa1f780-e97e-11ea-914b-2d1ed670d62c.png)

And one more mistake:
![image](https://user-images.githubusercontent.com/54715893/91608806-e0822c80-e97e-11ea-8d9e-bcdf01df4a1e.png)

[Functions](https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Functions)

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; you are more than welcome to edit the page yourself.
