### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Learn/Что_такое_веб_сервер

### ISSUE THREAD

**Issue by PayvinY** [mdn/sprints#3639]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update
On page 
https://developer.mozilla.org/ru/docs/Learn/%D0%A7%D1%82%D0%BE_%D1%82%D0%B0%D0%BA%D0%BE%D0%B5_%D0%B2%D0%B5%D0%B1_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80
with russian language
link https://developer.mozilla.org/en-US/docs/Learn/page_vs_site_vs_server_vs_search_engine
follow to english page
It must be corrected to 
https://developer.mozilla.org/ru/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations.

**Comment by PayvinY** [comment]
But you have target page translation. It is used to see the same language
page on source and link-targed page.

пн, 28 сент. 2020 г. в 17:27, Chris Mills <notifications@github.com>:
