### ISSUE TITLE
Remove outdated information from the DevTools docs

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#364]
This is a tracking issue, used to track changes made to the DevTools docs to remove outdated information only. There are outdated notes throughout the Developer Tools documentation. Messages such as this one that begins:

```This page describes the JavaScript Debugger as it appears in Firefox 52 and above, in Firefox Nightly and Firefox Developer Edition.```

These old notes should be removed as we come across them while working on other tasks.

In addition, there are references to default settings that have changed. These should be updated.

Rather than try to find all of these issues and fix them, this task will track the pages that have been changed and what was changed so we have a collected record.

**Comment by irenesmith** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector -- Removed the fact that the storage inspector is disabled by default. That is no longer the case.

**Comment by irenesmith** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Debugger -- Main page for JavaScript Debugger
I removed the notice about how the documentation is for Firefox 51 and later.

**Comment by digitarald** [comment]
>  I removed the notice about how the documentation is for Firefox 51 and later.

Thanks @irenesmith . As I can't tell the sprints, is this clean up scheduled for the current sprint? It is still across the many sub-pages.

**Comment by irenesmith** [comment]
Removed outdated reference to Firefox 47 from the Fonts page at:

[View Fonts](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/View_fonts)

**Comment by irenesmith** [comment]
@digitarald This is an ongoing task. I want to document what we remove as we do it. Rather than go on a search and destroy mission, I thought that the easiest thing to do would be to delete outdated references on an ad hoc basis.

**Comment by irenesmith** [comment]
Removed the following message:

In Firefox 47 only, the Fonts view is disabled by default. If you want to see the Fonts view in Firefox 47, visit about:config, find the preference devtools.fontinspector.enabled, and set it to true.

Before and after Firefox 47, the Fonts view is enabled by default.

from [UI Tour](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/UI_Tour)

**Comment by irenesmith** [comment]
Removed the version number from the following statement:

From Firefox 39, you can also open it with the Ctrl + Alt +Shift + I  key combination ( Cmd + Opt +Shift + I on a Mac).

on this page: [Browser Toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox)

**Comment by irenesmith** [comment]
Removed the note about the Debugger UI --



This page describes the JavaScript Debugger as it appears in Firefox 52 and above, in Firefox Nightly and Firefox Developer Edition.

To see what it's like in earlier versions of Firefox or in Firefox Beta and Release, see Debugger (before Firefox 52).

If you are getting this version of the Debugger and need to switch back to the old version, you can do so by visiting about:config and setting the "devtools.debugger.new-debugger-frontend" preference to false.

This note was removed because the old debugger is now on by default and the ability to go back to the old UI is slated for removal in the near future.

**Comment by irenesmith** [comment]
Removed the following note from the [Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) page:

Please note the keyboard shortcut was changed in Firefox 55

**Comment by irenesmith** [comment]
Closing this issue. It's not as useful as I thought when I created it.
