### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Learn/Understanding_URLs

### ISSUE THREAD

**Issue by PayvinY** [mdn/sprints#3640]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update
link
https://developer.mozilla.org/ru/docs/Learn/What_is_a_Web_server
is redirects to
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server
It must be corrected to
https://developer.mozilla.org/ru/docs/Learn/Common_questions/What_is_a_web_server

# Details

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations.
