### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### ISSUE THREAD

**Issue by danfranklinusa** [mdn/sprints#3641]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The indicated URL has the line in its example:

    console.log(dateControl.valueAsNumber); // prints 1496275200000, a UNIX timestamp

This is incorrect; UNIX timestamps are in seconds, but this number is in milliseconds.  If you give this number to a UNIX utility that expects a UNIX timestamp, such as the date command, it will produce incorrect results:
    $ date --date=@1496275200000
    Wed Jan 26 19:00:00 EST 49385
The comment should indicate that this is like a UNIX timestamp, but in msec instead of seconds.
Or that it is a standard JavaScript timestamp.

**Comment by chrisdavidmills** [comment]
@danfranklinusa good call; I've updated the comment — does this seem better to you?

https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
