### ISSUE TITLE
Create new page for "content-visibility" and "contain-intrinsic-size" CSS properties

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#3644]
# Request type

- [x] New documentation
- [ ] Correction or update

# Details

Chrome 85 added support for two new CSS properties:
* `content-visibility`
* `contain-intrinsic-size`

Reference:

* https://web.dev/content-visibility/
* https://developers.google.com/web/updates/2020/08/nic85#content-visibility
* https://www.chromestatus.com/feature/4613920211861504

We need to create two new documentation pages:

* https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility
* https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size

And add them to "CSS Reference" page:

* https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

**Comment by ramiy** [comment]
@chrisdavidmills It doesn't have to be a **multiple hour task**. If you create the pages I will add the content. Later you can review the pages to fit MDN style guide. Although I think I know was is expected and it won't be my first contribution to MDN.

**Comment by chrisdavidmills** [comment]
> If you create the pages I will add the content. Later you can review the pages to fit MDN style guide. Although I think I know was is expected and it won't be my first contribution to MDN.

If you want to collaborate and help me create the page content, then I'd be happy to work like that! The "multiple hour task" label is basically a ballpark estimate to give you an idea of the sort of time it'll take you, but it really assumes that the person taking on the task hasn't got any previous experience of MDN content work. For two people who both have previous experience, it'll take less time.

So you want me to create the pages in the correct positions, and you'll then fill in the content, after which I can review them? Sounds like a good plan, but I just wanted to ask — when will you likely to do that work? I don't want to create them and then have them left blank for too long.

Thanks @ramiy , I really appreciate the offer of help.

**Comment by ramiy** [comment]
@chrisdavidmills Next week I'll have time to write the content.

**Comment by chrisdavidmills** [comment]
@ramiy Cool! Give me a ping when you want to start, and I'll create the pages.

**Comment by ramiy** [comment]
@chrisdavidmills I'll be free tomorrow, maybe even today in the evening hours. You can create the page.

**Comment by chrisdavidmills** [comment]
Hi @ramiy . I'm so sorry for being so slow in getting back to you on this. Last week was really busy...

I've just created the two new pages, so you can work on them when you next have some free time. Thanks again for your offer of help.

**Comment by ramiy** [comment]
mdn/browser-compat-data/pull/7016

**Comment by ramiy** [comment]
https://github.com/mdn/browser-compat-data/pull/7318
