### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

### ISSUE THREAD

**Issue by BioRage0** [mdn/sprints#3646]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The section "Where did Node and Express Come From?" of the Express/Node Introduction page has the wrong version numbers for the LTS and CURRENT versions of Node.js. You may already be aware or it may have already been reported but just wanted to send the notice just in case. The current LTS version of Node is 12.8.3 and the CURRENT version is 14.9.0.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

<img width="1904" alt="Screen Shot 2020-08-29 at 10 03 16 PM" src="https://user-images.githubusercontent.com/40360907/91649719-abd8a880-ea44-11ea-9bb7-613daf2836bd.png">
<img width="1904" alt="Screen Shot 2020-08-29 at 10 02 43 PM" src="https://user-images.githubusercontent.com/40360907/91649721-b004c600-ea44-11ea-912f-a14df0dd88e2.png">

**Comment by chrisdavidmills** [comment]
This will be updated soon, we have @hamishwillee working on getting those docs updated again.

**Comment by hamishwillee** [comment]
@BioRage0 Thanks. I have updated this page (Friday). 

The docs are always going to lag updates to Express, node, etc. While I can't fix that, what I have done is clarified that the versions are "at time of writing": https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction#Where_did_Node_and_Express_come_from
