### ISSUE TITLE
I want Account Colors Back in Thunderbird

### ISSUE THREAD

**Issue by TonyK132** [mdn/sprints#3647]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details

In Thunderbird, I just downloaded and installed vers. 78.2.1 23-bit in Win10, and I lost the colors for the accounts.  The developer said he is discontinuing support for Acct Colors because of a change Mozilla made to the APIs.  One of the primary reasons I'm using Thunderbird is to display all my email accounts with different colors so I can tell what message came from what account.  I see 2 options:  1. reinstate the API to allow Colors to work, or 2. Mozilla to take over that add-in and make it a part of Thunderbird using the new API.  If either of these will not happen, then I will be forced to look elsewhere for an email client.

BTW, that add-in is called Account Colors.

**Comment by chrisdavidmills** [comment]
Hi there,

This repo has nothing to do with Thunderbird — this is for issues related to content on the [MDN site](https://developer.mozilla.org/en-US/). A better place to raise your concerns might be  one of the options on here: https://www.thunderbird.net/en-US/contact/.
