### ISSUE TITLE
[`str.split()` docs] Incorrect description of behavior when `limit = 1`

### ISSUE THREAD

**Issue by lobsterkatie** [mdn/sprints#3648]
# Request type

- [x] Correction or update

# Details

On the page about [the `.split()` string method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split), it says 

> If limit is 1, str.split(separator)[0] is returned

However, that does not seem to be the case, in Chrome, Firefox, Safari, or Node. In all cases, an array is still returned, rather than the first (and only) element of the array.

Suggested fix: Remove that bullet point. `limit = 1` behaves no differently than `limit = 2` or `limit = 3`, etc.

**Comment by chrisdavidmills** [comment]
@lobsterkatie thanks for reporting this. Yes, I think you're correct — I've tested it, and `[item]` is returned, not just `item`.

I've removed that bullet and updated the text description a bit.

**Comment by lobsterkatie** [comment]
👍🏻 Thanks for the quick fix!
