### ISSUE TITLE
Content Security Policy directive `img-src` is not nonceable

### ISSUE THREAD

**Issue by compulim** [mdn/sprints#3650]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src, it mentioned `nonce` as a source.

But in fact, `<img>` element is [not nonceable](https://w3c.github.io/webappsec-csp/#is-element-nonceable). This is because the `<img>` element does not have `nonce` attribute.

For example, the following HTML is tested in Edge 87.0.627.0 canary.

```html
<!DOCTYPE html>

<head>
  <meta http-equiv="Content-Security-Policy" content="img-src nonce-a1b2c3" />
</head>

<body>
  <img nonce="a1b2c3" src="https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg" />
</body>

</html>
```

The image will fail to load with the following JavaScript error:

```
Refused to load the image 'https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg' because it violates the following Content Security Policy directive: "img-src nonce-a1b2c3".

localhost/:1 Refused to load the image 'http://localhost:5002/favicon.ico' because it violates the following Content Security Policy directive: "img-src nonce-a1b2c3".
```

Since the article include/import a snippet from another location, I think either:

1. [That snippet](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src) need to be update to state some directives does not support nonce
2. Split `img-src` away from that snippet

(More details at https://github.com/microsoft/BotFramework-WebChat/issues/3445.)

**Comment by hamishwillee** [comment]
I think you're absolutely right. I have adopted your suggestion of updating the included doc [default-src](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src#Syntax) by adding a note as shown:

![image](https://user-images.githubusercontent.com/5368500/97838626-b4937680-1d34-11eb-82a2-f01aeff89180.png)

This propagated to img-src. I don't think it needs to be anywhere else.

Thanks!

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI ^^^^
