### ISSUE TITLE
Documentation on how to mix non wrapping and wrapping text

### ISSUE THREAD

**Issue by jsoref** [mdn/sprints#3653]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
* mdn has https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr
* the web has https://www.hongkiat.com/blog/change-default-text-wrapping-html-css/#:~:text=Browsers%20decide%20where%20to%20wrap,called%20a%20soft%20wrap%20break.
neither is really what i want

I want a page that has good advice on how to fix a line of the form
```html
<input type=checkbox> text/more/text/lots/more/text/that/will/not/split/because/it/has/no/opportunities/to/split/but/it/really/really/should/split/here/and/not/between/that/checkbox/and/that/first/word
```

In principle, sticking `<wbr>` or `&ZeroWidthSpace;` around the `/` will fix the second half
but, it also needs a `&NBSP;` between the checkbox and the text.

I wonder what the recommended practice would be. 

One could do:
```html
<span class="do-not-break"><input type=checkbox> text</span><span class="break-me">/</span>more<span class="break-me">/</span>text<span class="break-me">/</span>lots<span class="break-me">/</span>more<span class="break-me">/</span>text<span class="break-me">/</span>that<span class="break-me">/</span>will<span class="break-me">/</span>not<span class="break-me">/</span>split<span class="break-me">/</span>because<span class="break-me">/</span>it<span class="break-me">/</span>has<span class="break-me">/</span>no<span class="break-me">/</span>opportunities<span class="break-me">/</span>to<span class="break-me">/</span>split<span class="break-me">/</span>but<span class="break-me">/</span>it<span class="break-me">/</span>really<span class="break-me">/</span>really<span class="break-me">/</span>should<span class="break-me">/</span>split<span class="break-me">/</span>here<span class="break-me">/</span>and<span class="break-me">/</span>not<span class="break-me">/</span>between<span class="break-me">/</span>that<span class="break-me">/</span>checkbox<span class="break-me">/</span>and<span class="break-me">/</span>that<span class="break-me">/</span>first<span class="break-me">/</span>word
```
-- with `.break-me` and `.do-not-break` defined to use `white-space: nowrap` / **?** respectively.
(that seems awful)

or is `<wbr>` recommended for the latter and just the silly span for the former? or using `&nbsp;` for the former and `<wbr>` for the latter? or ?

**Comment by jsoref** [comment]
Fwiw, there is an Example of half of this in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr#Example -- but, it only covers half, which isn't really enough.

**Comment by rachelandrew** [comment]
@jsoref I think you want https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap `overflow-wrap: break-word`

**Comment by jsoref** [comment]
@rachelandrew: seems possible. Ideally there would be links from the pages I mentioned to that if it's the answer. And preferably an example closer to mine than the current examples which have spaces between words.

**Comment by rachelandrew** [comment]
@chrisdavidmills perhaps we need a page which details all the possibilities when you have overflowing text?

I could then link to that from each of the various properties, so if the answer wasn't solved by that one the reader could go to a page where the different options were listed.

**Comment by chrisdavidmills** [comment]
@rachelandrew I agree with this; this is exactly the kind of solutions-based text we want to provide more of on MDN.

**Comment by rachelandrew** [comment]
@chrisdavidmills great, I'll write that up.

**Comment by chrisdavidmills** [comment]
Guide added, so I'm closing this; thanks @rachelandrew
