### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### ISSUE THREAD

**Issue by hogpilot** [mdn/sprints#3655]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The first example under **A better way to concatenate arrays** is invalid due to assignment to constant variable:
``` js
const arr1 = [0, 1, 2];
const arr2 = [3, 4, 5]; 

//  Append all items from arr2 onto arr1
arr1 = arr1.concat(arr2);
```
Instead, the example could be:
``` js
let arr1 = [0, 1, 2];
const arr2 = [3, 4, 5]; 

//  Append all items from arr2 onto arr1
arr1 = arr1.concat(arr2);
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by chrisdavidmills** [comment]
Good point. I've updated all the `const` instances to `let` in this example, as the same problem appears in many places.
