### ISSUE TITLE
Correct the srclang attribute in the example for Displaying video text tracks in the Video and Audio Content article

### ISSUE THREAD

**Issue by SnakeWhisperer** [mdn/sprints#3657]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Exactly [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#Displaying_video_text_tracks), in the example use of WebVTT subtitles, the `<track>` element has the `srclang` attribute set to "en", but in the results, the subtitles are in Spanish. The `srclang` attribute should be set to Spanish.

**Comment by chrisdavidmills** [comment]
@SnakeWhisperer that's a good point; I've updated the `en` instances in the `<track>` element to `es`.
