### ISSUE TITLE
Grammitcal Issue - /en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### ISSUE THREAD

**Issue by IonoclastBrigham** [mdn/sprints#3659]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the Parameters section of `Array.prototype.forEach()`, the callback's `index` param description reads:

> The index `currentValue` in the array

...but should include a possessive conjunction...

> The index **of** `currentValue` in the array

**Comment by sideshowbarker** [comment]
Thanks — fixed now

**Comment by IonoclastBrigham** [comment]
Looks like the fix is live. Is the issue reporter usually responsible to closing it, in this project?

**Comment by sideshowbarker** [comment]
> Is the issue reporter usually responsible to closing it, in this project?

I guess usually, issues here get closed by one of the MDN project owners/peers who have write (or maintainer?) access to this repo, after they make a fix.

But sometimes issues get closed by other contributors like me who don’t have write/maintainer access to this repo — and so, who can’t close issues.

So this is one of those cases. Which means you should go ahead and close it yourself, if you are satisfied with the resolution.

**Comment by IonoclastBrigham** [comment]
Accepted.
