### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode

### ISSUE THREAD

**Issue by guest271314** [mdn/sprints#3660]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

Link to Headless SlimerJS with Firefox (https://adriftwith.me/coding/2017/04/21/headless-slimerjs-with-firefox/) is 500 

```
Request URL: https://adriftwith.me/coding/2017/04/21/headless-slimerjs-with-firefox/
Request Method: GET
Status Code: 500 
```

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode

**Comment by chrisdavidmills** [comment]
Yeah, looks like this article is no longer online. I've updated the article structure, removing it in the process. Thanks for reporting.
