### ISSUE TITLE
PLEASE ADD DARK MODE.

### ISSUE THREAD

**Issue by kiran-khanna** [mdn/sprints#3661]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

**Comment by chrisdavidmills** [comment]
This isn't a simple or quick fix, and isn't going to happen any time soon, although I do agree with you that it would be nice.

I'm closing this for now, but rest assured that it will come up again as a suggestion. I think the dev team already have it on their list of future update considerations.
