### ISSUE TITLE
An example of pseudo-class selector and it's explanation don't match

### ISSUE THREAD

**Issue by VahidPouyafar** [mdn/sprints#3662]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**I hope I'm right!!!**
### _Issue 1_
In the paragraph under the title "[Using the universal selector to make your selectors easier to read](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors#Using_the_universal_selector_to_make_your_selectors_easier_to_read)" it reads:

> For example, if I wanted to select the first child **of** any descendant element of `<article>` , no matter what element it was, and make it bold, I could use the `:first-child` selector, which we will learn more about in the lesson on pseudo-classes and pseudo-elements, as a descendant selector along with the `<article>` element selector:
> _article :first-child {_
> _}_

I think either the explanation or example should be changed:

### This should be the correct explanation for the original example (_article :first-child {}_):
if I wanted to select any descendant element of the `<article>` element which is the first child of its parent ...
### Or this should be the correct example for the original explanation:
_article * > :first-child_
(if I wanted to select the first child of any descendant element of `<article>`...)

### _Issue 2_
If in issue 1 I'm right please check the note box here [Simple pseudo-class example](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements#Simple_pseudo-class_example)

**Comment by chrisdavidmills** [comment]
Hi @VahidPouyafar! The code examples were correct, but the explanation was a bit confusing. I've updated the text so that it is more correct. Basically, it does both — it selects any element that is the first-child of an article, and any element that is the first-child of any descendant of an article. 

So in the following snippet:

```
<article>
      <p>one</p>
      <p>two</p>
      <p>three</p>

      <div>
        <p>four</p>
        <p>five</p>
        <p>six</p>
      </div>
    </article>
```

`<p>one</p>` and `<p>four</p>` would both be selected.

Does that make sense now?

**Comment by VahidPouyafar** [comment]
Thank you @chrisdavidmills. Yes now it makes sense. Actually the previous explanation was correct but not that precise I wanted!
Is this sentence correct too?

_article &nbsp; :first-child_
"Select any descendant elements of `<article>`  element _**(including direct children)**_ which are the first child of their parent."

**Comment by chrisdavidmills** [comment]
Yes, that would also work. In fact, this is a useful way to sate it, so I've further updated the first description that appears to be more like this one. Thanks!
