### ISSUE TITLE
Complementary landmark is defined within Main landmark.

### ISSUE THREAD

**Issue by Gouri220** [mdn/sprints#3665]
# Request type

- [ ] Correction or update

# Details

Complementary landmark is defined within Main landmark.

The "complementary" landmark must be at the top level, not nested within other landmarks.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Complementary_role

<img width="957" alt="Complementary landmark is defined within Main landmark" src="https://user-images.githubusercontent.com/61388927/92492434-f6121480-f210-11ea-8634-25833bcd3174.png">

**Comment by chrisdavidmills** [comment]
@Gouri220 Just to clarify, are you commenting on the content of the Comprelentary role page, or the markup of the MDN template itself? Or both?

**Comment by Gouri220** [comment]
@chrisdavidmills I am pointing to the HTML markup of the MDN template for Complementary section in DOM.

**Comment by chrisdavidmills** [comment]
I don't think this is still a problem; feel free to shout if you disagree.
