### ISSUE TITLE
Develop Step-by-Step Launch Plan

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3667]
# Epic 
Develop Step-by-Step Launch Plan

# Acceptance criteria
- [ ] Decision made on separate content repo for beta launch 
@escattone to discuss with team

**Comment by escattone** [comment]
This is done (see https://docs.google.com/document/d/1VvaT5q1uMsoJm2TLmeQAmdXKFfJTBUru0VJTFtQjM3o/edit?usp=sharing).
