### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/install_event

### ISSUE THREAD

**Issue by Mizhashh** [mdn/sprints#3673]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Problem inside Example code snippet on https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/install_event page

```
this.addEventListener('install', function(event) {
  event.waitUntil(
   caches.open('v1').then(function(cache) {
         return cache.add(
        '/sw-test/',
        '/sw-test/index.html',
        '/sw-test/style.css',
        '/sw-test/app.js',
        '/sw-test/image-list.js',
        '/sw-test/star-wars-logo.jpg',
        '/sw-test/gallery/',
        '/sw-test/gallery/bountyHunters.jpg',
        '/sw-test/gallery/myLittleVader.jpg',
        '/sw-test/gallery/snowTroopers.jpg'
     );
   })
   );
});
```

Method of the `Cache` interface `Cache.add()` doesn't support multiple arguments. It takes only one.

**Comment by sideshowbarker** [comment]
OK, updated the article to change the example to use `cache.addAll` rather than `cache.add`.

If that’s an acceptable resolution for you, please feel free to close this issue. (And thanks much for having caught this.)

**Comment by Mizhashh** [comment]
Thanks much
