### ISSUE TITLE
Docs request: Expand `Location.pathname` description

### ISSUE THREAD

**Issue by lobsterkatie** [mdn/sprints#3674]
# Request type

- [x] Correction or update

# Details
On [the page](https://developer.mozilla.org/en-US/docs/Web/API/Location) describing the `Location` interface, it would be great to be more specific about what the `pathname` property does and doesn't include. Something like:

> Is a USVString containing an initial '/' followed by the path of the URL, _not including the query string or fragment_.

Alternatively, perhaps the word "path" in the existing definition could be a link to somewhere which includes the query string and fragment information.

The same change request applies on the [`WorkerLocation` page](https://developer.mozilla.org/en-US/docs/Web/API/WorkerLocation), the [`URLUtilsReadOnly` page](https://developer.mozilla.org/en-US/docs/Web/API/URLUtilsReadOnly), the [`URL` page](https://developer.mozilla.org/en-US/docs/Web/API/URL), the [`HTMLHyperlinkElementUtils` page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils), the [`HTMLAnchorElement` page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement), etc, as well as the `pathname` subpages thereof.

**Comment by Rumyra** [comment]
List of pages

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Location
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/WorkerLocation
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/URLUtilsReadOnly
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/URL
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement

Updated `pathname` property on all pages and subsequent property pages

**Comment by lobsterkatie** [comment]
Thank you!
