### ISSUE TITLE
Styling error on https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

### ISSUE THREAD

**Issue by jienius** [mdn/sprints#3675]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the first line of the Lengths section, `<length>. F` is marked as inline code instead of just `<length>`

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting.
