### ISSUE TITLE
Percentage margins and padding (The explanation is not accurate and implies something wrong).

### ISSUE THREAD

**Issue by VahidPouyafar** [mdn/sprints#3678]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi :)
In the lesson "Sizing Items in the CSS", section "[Percentage margins and padding](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS#Percentage_margins_and_padding)", the point is that the percentage margins and padding is calculated relative to inline size of parent element. But the explanation implies that they're calculated relative to inline size of the element itself.

> You might expect for example the percentage top and bottom margins to be a percentage of the element's height, and the percentage left and right margins to be a percentage of the element's width. However, this is not the case!
> 
> When you use margin and padding set in percentages, the value is calculated from the inline size **#####** — therefore the width when working in a horizontal language. In our example, all of the margins and padding are 10% of the width **#####**. This means you can have equal-sized margins and padding all around the box. This is a fact worth remembering if you do use percentages in this way.

I mean instead of **#####** it's useful to write **(of the parent element)**.
I was wondering why the margins and padding remain the same when I change the element's width.

**Comment by rachelandrew** [comment]
In the section above it does mention that the calculation is from the containing block rather than the item itself, however it would be easy to skip that so I've repeated it in this section too.
