### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_filtering_conditional_rendering

### ISSUE THREAD

**Issue by Charg** [mdn/sprints#3680]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

First and foremost, thanks for creating and maintaining fantastic developer resources!

The code snippet for the **taskList** constant is incorrect and doesn't match the code found in the example repo --> https://github.com/mdn/todo-react/blob/master/src/App.js#L60-L72
```javascript
const taskList = tasks
  .filter(FILTER_MAP[filter](task))
  .map(task => (
    <Todo
      id={task.id}
      name={task.name}
      completed={task.completed}
      key={task.id}
      toggleTaskCompleted={toggleTaskCompleted}
      deleteTask={deleteTask}
      editTask={editTask}
    />
  ));
```

It should instead be:

```javascript
  const taskList = tasks
  .filter(FILTER_MAP[filter])
  .map(task => (
    <Todo
      id={task.id}
      name={task.name}
      completed={task.completed}
      key={task.id}
      toggleTaskCompleted={toggleTaskCompleted}
      deleteTask={deleteTask}
      editTask={editTask}
    />
  ));
```

**Comment by chrisdavidmills** [comment]
Thanks for reporting. I've updated the snippet in the article.

Just to be clear — it was just the indentation that was wrong?

**Comment by Charg** [comment]
Apologies on the late reply, didn't see the update. It was the second line, containing the `filter` that was incorrect.

`.filter(FILTER_MAP[filter](task))` became ` .filter(FILTER_MAP[filter])`

**Comment by chrisdavidmills** [comment]
Ah, ok, updated. Thanks!
