### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#The_POST_method

### ISSUE THREAD

**Issue by misterybodon** [mdn/sprints#3681]
# Request type

- [ x] Correction or update

# Details

Exactly after the link I'm giving in the title (to the element with id the_post_method), the URL seems to have a typo. 

Should be **http** instead of **https**. You can check clicking on each of this ones:

* [http://www.foo.com/](http://www.foo.com/)
* [https://www.foo.com/](https://www.foo.com/) <--- should be http ?

**Comment by chrisdavidmills** [comment]
I don't really see this as a problem necessarily — they are only supposed to be examples, and not real URLs. However, it is nice to be consistent, so I've changed it to http, just like it is in the GET example.

**Comment by misterybodon** [comment]
I believe if you use the second url, it's impossible to see the body of the request (which is the whole point of the section). That's why I saw it as a problem.
