### ISSUE TITLE
A better code example

### ISSUE THREAD

**Issue by LucianIacobBc** [mdn/sprints#3690]
Correction or update

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

"Using thisArg" section, the example is a bit pointless. 

function Counter() {
  this.sum = 0
  this.count = 0
}
Counter.prototype.add = function(array) {
  array.forEach((entry) => {
    this.sum += entry
    ++this.count
  }, this)
  // ^---- Note
}

const obj = new Counter()
obj.add([2, 5, 9])
obj.count
// 3 
obj.sum
// 16

the callback function  

array.forEach((entry) => {
    this.sum += entry
    ++this.count
  }, this)

shouldn't be an arrow function to better understand the using of this parameter in forEach, a
better example will be in my opinion

array.forEach( function addFunction (entry) {
    this.sum += entry
    ++this.count
  }, this)

**Comment by prosovskyf** [comment]
please assign. Thanks

**Comment by chrisdavidmills** [comment]
@prosovskyf assigned. Thanks for your interest in working on this!

**Comment by prosovskyf** [comment]
@chrisdavidmills please review
