### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/API/WakeLockSentinel/released

### ISSUE THREAD

**Issue by rakuco** [mdn/sprints#3691]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
I'm one of the editors of the [Screen Wake Lock API](https://w3c.github.io/screen-wake-lock). We've recently added a new attribute to the WakeLockSentinel object, `released`, that I'm trying to document. Can someone create https://wiki.developer.mozilla.org/en-US/docs/Web/API/WakeLockSentinel/released?

**Comment by chrisdavidmills** [comment]
@rumyra was documenting this recently. Ruth, can you action this one?

**Comment by Rumyra** [comment]
Yes absolutely - doing it now...

@rakuco I'm going to drop you an email with a template you can follow for the page too 👍

**Comment by Rumyra** [comment]
Page has been created with a template (correct macros etc...)

https://wiki.developer.mozilla.org/en-US/docs/Web/API/WakeLockSentinel/released

Feel free to close this issue @chrisdavidmills

**Comment by rakuco** [comment]
Thanks, @Rumyra!

**Comment by chrisdavidmills** [comment]
Thanks @Rumyra ! Shall I leave it open until the bcd has been created for this page, or are you tracking compat data somewhere else?

**Comment by sideshowbarker** [comment]
I reviewed and merged the related BCD PR already — https://github.com/mdn/browser-compat-data/pull/6694

**Comment by Rumyra** [comment]
Hahah - that was easy :) Brill @sideshowbarker !

**Comment by chrisdavidmills** [comment]
Go team ;-)
