### ISSUE TITLE
Missing function definition in a code block on the setTimeout page

### ISSUE THREAD

**Issue by dimitarnestorov** [mdn/sprints#3692]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the `WindowOrWorkerGlobalScope.setTimeout()` page in the "Timeouts throttled to ≥ 4ms" section there is a code example (pasted below this paragraph) referencing a function called `f` twice but that function isn't defined. It doesn't seem like that was the intended example since after it there are mentions about multiple successive callback calls while no definition of that function will result in none.

```js
function cb() { f(); setTimeout(cb, 0); }
setTimeout(cb, 0);
setInterval(f, 0);
```

Link: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Timeouts_throttled_to_%E2%89%A5_4ms

**Comment by chrisdavidmills** [comment]
Hi @dimitarnestorov ! You are right, this does look like there is something wrong with it.

I wonder whether the code is supposed to be something more like this:

```
function cb() { setTimeout(cb, 0); }
function f() { setInterval(f, 0); }
setTimeout(cb, 0);
setInterval(f, 0);
```

?

I've updated the page to use this for now, but could happily update it again.

**Comment by dimitarnestorov** [comment]
I guess. I'm not 100% sure. I was hoping to track down the original author of that section and contact them directly but digging through the history is big pain.
In my opinion without `console.log` it's hard to illustrate the explanation below the code block.

**Comment by jchimene** [comment]
See https://github.com/mdn/content/pull/1062

**Comment by jchimene** [comment]
@chrisdavidmills Please assign this to me. I will close it when https://github.com/mdn/content/pull/1062 merges.
