### ISSUE TITLE
Console error in "Test your skills" page

### ISSUE THREAD

**Issue by Ganeshjadhav221b** [mdn/sprints#3694]
**Summary**
There's a console error in the page ->"Test your skills", [link to it](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Events)

**Steps To Reproduce (STR)**

1. Just to go  the [page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Events)
2. Open the console(ctrl+shift+i)
3. The error says->"Uncaught SyntaxError: Identifier 'section' has already been declared
    at fillCode (playable.js:8)"

**Actual behavior**
![image](https://user-images.githubusercontent.com/35261048/93156664-30eedd80-f726-11ea-9cce-f9fe0ae0c7e6.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/35261048/93156676-3ba97280-f726-11ea-9a79-9b104301eef1.png)
<this happens after i clear the console, ofcourse>

**Additional context**=
0. The root cause of problem is in Events 3.
1.This happens because the variable 'section' is already declared in global level(playable.js), and also it is declared in the live code which is embedded({{EmbedGHLiveSample("learning-area/javascript/building-blocks/tasks/events/events3.html", '100%', 400)}})
2. Since the code is embedded, it cannot be resolved by making changes via 'Edit in Wiki' option; which I tried already.
![image](https://user-images.githubusercontent.com/35261048/93164393-fe99ac00-f736-11ea-83a1-7826e7f260c9.png)

**Comment by chrisdavidmills** [comment]
@Ganeshjadhav221b thanks for reporting this. There was a redeclared variable in one of the embedded examples. I've fixed the source for that now, so the error should stop occurring soon.
