### ISSUE TITLE
Delete https://developer.mozilla.org/en-US/docs/Web/CSS/@media/light-level 

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/sprints#3695]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/light-level  should be completely deleted. `light-level` was never implemented in any browser engines, and it has now been removed from the Media Queries spec:

* https://drafts.csswg.org/mediaqueries-5/#changes-since-2020-07-15
  > Remove the <code>light-level</code> media feature as it is redundant with <span class="css">prefers-contrast</span> and <span class="css">prefers-color-scheme</span>; add examples of how these media features may be automatically inferred by the user agent based on the same factors <code>light-level</code> was expected to respond to.
* https://github.com/w3c/csswg-drafts/commit/f5b663c27d5a2715239633f4916880563969d770
* https://github.com/w3c/csswg-drafts/issues/5359

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/6706 for the corresponding BCD change

**Comment by chrisdavidmills** [comment]
Thanks @sideshowbarker. I've deleted that page and all its translations.
