### ISSUE TITLE
Set.prototype.keys() links to wrong page

### ISSUE THREAD

**Issue by demwong** [mdn/sprints#3696]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the documentation for [Sets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), under Iteration methods, the Set.prototype.keys() link links to the Set.prototype.values() page.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by chrisdavidmills** [comment]
Hi @demwong ! Read the second paragraph on the `values()` page — looks like this has been done deliberately, as they both behave exactly the same.

I've updated the second paragraph to turn it into a note and add some decription of what's happening here.

**Comment by demwong** [comment]
Oh, that's my bad! Thought I was being helpful 😅.

**Comment by chrisdavidmills** [comment]
No worries at all! It was helpful. It is always better to question things than just not say anything.
