### ISSUE TITLE
Delete https://developer.mozilla.org/en-US/docs/Web/API/Document/dragexit_event

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/sprints#3697]
https://developer.mozilla.org/en-US/docs/Web/API/Document/dragexit_event  should be completely deleted.

The `dragexit` event was only ever implemented in Gecko (and never even documented in BCD as being implemented anywhere), and it has now been removed from the HTML spec:

* https://github.com/whatwg/html/commit/40e3868b09f17fc12860596b990bb56bc5cc2a3f
* https://github.com/whatwg/html/issues/2741

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/browser-compat-data/pull/6710 for the corresponding BCD change

**Comment by chrisdavidmills** [comment]
Done; I've also removed mention of it from https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document
