### ISSUE TITLE
https://developer.mozilla.org/id/docs/Web/HTML

### ISSUE THREAD

**Issue by restufauzi697** [mdn/sprints#3699]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

![Screenshot_2020-09-18-23-09-26](https://user-images.githubusercontent.com/71517996/93620954-5a2f9800-f9ca-11ea-92e5-25de122627f7.jpg)

I'm seeing an error in the "<code>&lt;indonesia&gt;</code>" tag which should be written as "<code>&lt;input&gt;</code>" tag.

This error occurs in Indonesian translate.

URL: https://developer.mozilla.org/id/docs/Web/HTML

**Comment by chrisdavidmills** [comment]
This is really strange. I've looked into this, and have no idea why it is doing this. We'll have to investigate when we get the chance
