### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by RaglandCodes** [mdn/sprints#3700]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#Usability

## Request type

- [ ] New documentation
- [x] Correction or update

In [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) page, in the [usability section](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#Usability) it says,

>  This improves usability for sited user.

I think it meant "usability for **sighted** user"

**Comment by sideshowbarker** [comment]
Thanks for catching this. I’ve updated the page to correct the problem you found. If that resolves this issue to your satisfaction, please go ahead and close the issue. (I’m not actually able to close the issue myself, and in general it’s fine for you to close your own issues here whenever you are satisfied with how they’ve been resolved.)
