### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API

### ISSUE THREAD

**Issue by messa** [mdn/sprints#3701]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Hello, I think a [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API) is missing (not listed) in the list of [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API).

**Comment by sideshowbarker** [comment]
Thanks for catching this. The content of that https://developer.mozilla.org/en-US/docs/Web/API page is automatically populated, and I believe the reason the Screen Capture API isn’t showing up there is that the data for it in the file at https://github.com/mdn/kumascript/blob/master/macros/GroupData.json is incomplete.

So I’ve raised https://github.com/mdn/kumascript/pull/1420 to get that file updated.

**Comment by chrisdavidmills** [comment]
Thanks @messa for reporting, and @sideshowbarker for the fix. I've reviewed and merged the PR now, so the site should update after the next MDN production push (these happen weekly)
