### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Description

### ISSUE THREAD

**Issue by paulmeidinger** [mdn/sprints#3706]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Description

In the first two examples in the Description section, the world "yields" is misspelled in the comments. See screenshot.

![screenshot](https://user-images.githubusercontent.com/58787936/93927479-c877a180-fccd-11ea-8037-30ee34034151.png)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
