### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements

### ISSUE THREAD

**Issue by psamovich** [mdn/sprints#3707]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The first paragraph of the [article about block-level elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) contains the following sentence:

> By default, a block-level element occupies the entire space of its parent element (container), thereby creating a "block."

The phrase 'the entire space of its parent element' is confusing as it implies both the horizontal (width) and vertical (height) axes, but that's not correct as the block element occupies the space in horizontal direction only, that is also confirmed in a note one paragraph further down the page.

**Comment by chrisdavidmills** [comment]
Yes, I agree with you that this is confusing. I've updated it to 

> Block-level elements are those which occupy the entire horizontal space of its parent element (container), and vertical space equal to the height of its contents, thereby creating a "block".

Does this sound better?

Thanks for reporting this.

**Comment by chrisdavidmills** [comment]
Hrm, I tried again, because the grammar was problematic. It now looks like this:

> A Block-level element occupies the entire horizontal space of its parent element (container), and vertical space equal to the height of its contents, thereby creating a "block".

**Comment by psamovich** [comment]
It's perfect now, thanks a lot!
