### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder

### ISSUE THREAD

**Issue by dcompcoder** [mdn/sprints#3708]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under the description for the `placeholder` attribute, the start of the second sentence is as follows:

> It should be a word or short phrase that demonstrates the expected type of data

So, for example, if the expected type of data is a name, then `placeholder="name"` is fine. Using the value "name" also makes the `placeholder` attribute act like a prompt.

However, under the heading "Placeholders are not accessible", the fourth sentence is as follows:

> The placeholder is used to show an example input, not an explanation or prompt.

According to this statement, the code `placeholder="eg George"` is more appropriate than `placeholder="name"`.

The statements quoted above are contradictory. Please clarify which statement is correct.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Placeholders_are_not_accessible

**Comment by chrisdavidmills** [comment]
I don't think they are contradictory, but I do agree that they could be clearer, and the description cold be more consistent between the two sections. I'd had a go at rewriting them and providing an example (you might have to wait a little while for the page to regenerate). Let me know if you think it is beter now.
