### ISSUE TITLE
Firefox 63 DOM DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#371]
# User story
As a web developer, I want to learn about the new DOM features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [x] All DDNs complete.
2. - [x] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items

1. - [x] (sheppy) [Implement paymentmethodchange event](https://bugzilla.mozilla.org/show_bug.cgi?id=1468356) [1.5 days]
2. - [x] (sheppy) [Support fine-grained address field errors for PaymentRequest](https://bugzilla.mozilla.org/show_bug.cgi?id=1435157) [2 days]
3. - [x] (Florian) [Add more fine-grained prefs to the Web Animations API](https://bugzilla.mozilla.org/show_bug.cgi?id=1471814) [2 days]
4. - [x] (sheppy) [Implement the Async Clipboard API](https://bugzilla.mozilla.org/show_bug.cgi?id=1461465) [3 days]

## Smaller items estimated together

Total estimate — 8.5 days

1. - [x] (sheppy) [[UI Events] Set key value of keydown/keyup event to "AltGraph" if active keyboard layout actually has AltGr and pressed AltRight key on Windows](https://bugzilla.mozilla.org/show_bug.cgi?id=900750) [probably needs small note somewhere]
2. - [x] (sheppy) [Make sure favicons are governed by CSP](https://bugzilla.mozilla.org/show_bug.cgi?id=1297156) [needs note somewhere?]
3. - [x] (chris) [window.getComputedStyle() returns null inside an iframe with display: none](https://bugzilla.mozilla.org/show_bug.cgi?id=548397)
4. - [x] (sheppy) [PerformanceObserver should not throw on empty/unknown list of entryTypes, but silently ignore the error (with optional console warning).](https://bugzilla.mozilla.org/show_bug.cgi?id=1403027)
5. ~~- [ ] (sheppy) [Implement report-sample support for CSP directives](https://bugzilla.mozilla.org/show_bug.cgi?id=1473218)~~
6. - [x] (chris) [Logical properties should be supported by Web Animation](https://bugzilla.mozilla.org/show_bug.cgi?id=1309752)
7. - [x] (sheppy) [Enable dom.animations-api.core.enabled by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1476158)
8. - [x] (Florian) [Enable Clear-Site-Data header by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1470111)
9. - [x] (Chris) [Update Worklet: s/import/addModule](https://bugzilla.mozilla.org/show_bug.cgi?id=1472324) [docs done, but BCD needs adding, and it needs checking generally]
10. - [x] (sheppy) [Make the noopener window feature not affect whether other window features are enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1419960)
11. - [x] (Florian) [Enable and ship CSP Policy violation events](https://bugzilla.mozilla.org/show_bug.cgi?id=1472661)
12. - [x] (sheppy) [Can we remove the forward() and home() APIs on windows?](https://bugzilla.mozilla.org/show_bug.cgi?id=1479486)
13. - [x] (sheppy) NEW [remove URL.createObjectURL from ServiceWorker](https://bugzilla.mozilla.org/show_bug.cgi?id=1264182)
14. - [x] (sheppy) NEW [Enable async clipboard readText and writeText APIs by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1479935)
15. - [x] (chris) [Enable Shadow DOM in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1471947)
16. - [x] (chris) [Enable Custom Elements in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1471948)
17. - [x] (chris) NEW [Expose the Visual Viewport API to web content](https://bugzilla.mozilla.org/show_bug.cgi?id=1357785)
18. - [x] (chris) NEW [Use 'auto' for unspecified keyframe-specific composite operations](https://bugzilla.mozilla.org/show_bug.cgi?id=1483404)
19. - [x] (sheppy) NEW [Request for window.event object added to DOM to ease cross browser scripting](https://bugzilla.mozilla.org/show_bug.cgi?id=218415)
20. - [x] (sheppy) NEW [Implement Event's returnValue](https://bugzilla.mozilla.org/show_bug.cgi?id=1452569)
21. - [x] (sheppy) NEW [navigator.platform returns "Win64" in Firefox on Win64 OS but "Win32" in Chrome and Edge](https://bugzilla.mozilla.org/show_bug.cgi?id=1472618)

**Comment by a2sheppy** [comment]
Updated KeyboardEvent, KeyboardEvent.key, and Firefox 63 for developers for DDN bug 900750.

**Comment by a2sheppy** [comment]
Updated Window, Window.back(), Window.forward(), and Firefox 63 for devs for bug 1479486.

**Comment by a2sheppy** [comment]
re #5 (CSP `'report-sample'` support) --

I have updated the content, and submitted a PR, but the PR needs to be updated. I need to determine the best way to deal with a case where a feature is also a subfeature of other features, so that all the other features can list that subfeature.

By that I mean, `'report-sample'` is currently in BCD as a top-level feature. But actually it's a keyword that's optionally used by most of the CSP directives. The question is, can I import the info about `'report-sample'` support into those directives' tables, or do I need to duplicate that information into all of those tables?

**Comment by a2sheppy** [comment]
Moved the CSP issue off to issue #463. Closing this.
