### ISSUE TITLE
DevTools updates in Firefox 81

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3711]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Debugger should show TypeScript icon for .TSX files](https://bugzilla.mozilla.org/show_bug.cgi?id=1642769) — this is a very small update, probably just a line in the rel notes plus a small mention somewhere suitable in the debugger documentation.
2. - [x] [[ruleview] Implement the inline CSS compatibility warning in ruleview](https://bugzilla.mozilla.org/show_bug.cgi?id=1649021) — probably fairly small, sounds like it is to do with a new compatibility tooltip in the rules view of the inspector. Needs further investigation.
3. - [ ] [Expose line-wrap as option in the debugger](https://bugzilla.mozilla.org/show_bug.cgi?id=1590885) — Again, small, this is probably referring to the new Linewrap option in the debugger context menu and gear menu. Just needs a rel note, and a small bit of content adding to the debugger docs.
4. - [ ] [Fix color vision deficiency simulations](https://bugzilla.mozilla.org/show_bug.cgi?id=1655053) — needs a bit of updating in the a11y inspector simulation page. [comment 13](https://bugzilla.mozilla.org/show_bug.cgi?id=1655053#c13) explains what is needed.
5. - [x] [Provide autocompletion when adding a new class to an element](https://bugzilla.mozilla.org/show_bug.cgi?id=1492797) — Pretty small. Sebastian's comment at the top explains exactly what is being added, and it works fine, simple to test.

Estimated total: 1.5 days work.

**Comment by chrisdavidmills** [comment]
@hamishwillee can I get you to have a look at these ones please?

**Comment by hamishwillee** [comment]
1. - [ ] [Debugger should show TypeScript icon for .TSX files](https://bugzilla.mozilla.org/show_bug.cgi?id=1642769) — this is a very small update, probably just a line in the rel notes plus a small mention somewhere suitable in the debugger documentation.
   - - [ ] [Release Note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#Developer_Tools) added
   - - [ ] Docs update info on file type icons. Not going to do. This isn't mentioned anywhere and I don't see a need to add any either, as the meaning of the icons is completely obvious when you're in the context.

@chrisdavidmills This is just a release node. Ready for you to review.

**Comment by hamishwillee** [comment]
2. - [ ] [[ruleview] Implement the inline CSS compatibility warning in ruleview](https://bugzilla.mozilla.org/show_bug.cgi?id=1649021) — probably fairly small, sounds like it is to do with a new compatibility tooltip in the rules view of the inspector. Needs further investigation.

Review
- Yes, this is a tooltip that should appear next to CSS rule that has incompatibility. See example
  ![](https://d3kxowhw4s8amj.cloudfront.net/file/data/kvtlewxgmzgscyntw7yg/PHID-FILE-ozfhcumn2t46e5t2l3av/specificity.gif)
- I can't reproduce this on FF81 or FF83 so [waiting on more info here](https://bugzilla.mozilla.org/show_bug.cgi?id=1649021#c12) - in case it needs to be enabled somehow.
- Not clear if this just reflects incompatible current version or specific version. Asked about that too. 


As for documentation, will need:
- - [ ] Release note
- - [ ] Update to [Examine and edit CSS](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Examine_CSS_rules) - probably just update/new image to end of the the first section (Examine CSS rules) 

So, this one is waiting on waiting on more info here](https://bugzilla.mozilla.org/show_bug.cgi?id=1649021#c12)

**Comment by hamishwillee** [comment]
@chrisdavidmills I can't find a topic that says how to set a preference in firefox. What most people seem to do is just assume people know how to set preferences OR duplicate some text "open about:config in URL bar". Is there a topic? If not then propose I create a minimal one below https://wiki.developer.mozilla.org/en-US/docs/Tools and then link to this whenever we refer to a preference. Thoughts?

**Comment by hamishwillee** [comment]
3. - [ ] [Expose line-wrap as option in the debugger](https://bugzilla.mozilla.org/show_bug.cgi?id=1590885) — Again, small, this is probably referring to the new Linewrap option in the debugger context menu and gear menu. Just needs a rel note, and a small bit of content adding to the debugger docs.


   - - [ ] [Debugger UI Tour > Source pane](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Source_pane) added new section on the end (search "The source pane provides the following context menu options")
       - @chrisdavidmills Need info on two items that I don't know what are for (Jump to generated location, Show inline preview)
   - - [ ] [Debugger UI Tour > Source pane](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Toolbar) - updated image of current Settings and added line for info on the Wrap option.
   - - [ ] [Release note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#Developer_Tools) added

@chrisdavidmills Other than point above in Source Pane, this ready for review

**Comment by hamishwillee** [comment]
4. - [ ] [Fix color vision deficiency simulations](https://bugzilla.mozilla.org/show_bug.cgi?id=1655053) — needs a bit of updating in the a11y inspector simulation page. [comment 13](https://bugzilla.mozilla.org/show_bug.cgi?id=1655053#c13) explains what is needed.

- - [ ] Updated [Color vision simulation](https://wiki.developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector/Simulation)
    -  removed the three "omaly" simulations that are no longer in FF81. 
     - Added note explaining that. I chose not to explain why they are not needed (essentially if the remaining simulations are the "worse case" of the condition described by the removed simulations - so if you design for the worse case it works for all cases).
    - Separate note about the source paper for the algorithms used.
    - Updated the example images.
- - [ ] [Release note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#Developer_Tools) added
- - [ ] [Open question on whether webrender needed](https://bugzilla.mozilla.org/show_bug.cgi?id=1655053#c16)

**Comment by hamishwillee** [comment]
5. - [ ] [Provide autocompletion when adding a new class to an element](https://bugzilla.mozilla.org/show_bug.cgi?id=1492797) — Pretty small. Sebastian's comment at the top explains exactly what is being added, and it works fine, simple to test.

   - - [ ] Docs update to [Examine and edit CSS > Viewing and changing classes on an element](https://wiki.developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Viewing_and_changing_classes_on_an_element). In this case was already documented. All I did was add version info. 
   - - [ ] [Release note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#Changes_for_web_developers) added

@chrisdavidmills This one ready for review

**Comment by chrisdavidmills** [comment]
"Debugger should show TypeScript icon for .TSX files " review — yup, looks absolutely fine.

"[ruleview] Implement the inline CSS compatibility warning in ruleview" review:

* Content looks good; I tweaked the "Examine and edit CSS" page a bit a little bit, adding in a couple of headings to break up the content bit.
* I removed the rel note from the 82 page, because it is not currently enabled by default. In such cases, we usually put an entry on the https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features page. Can you add one please?

**Comment by chrisdavidmills** [comment]
"Expose line-wrap as option in the debugger" review — yup, looks fine, apart form the two options we don't know the purpose of ;-)

Did you ping anyone about these?

**Comment by chrisdavidmills** [comment]
"Fix color vision deficiency simulations" review — looks good. I just added a call to the `toolssidebar` macro on the main Color vision simulation page, so that it shows the main sidebar of the section.

**Comment by chrisdavidmills** [comment]
"Provide autocompletion when adding a new class to an element" review — yup, looks fine.

I'm closing this one, as the bits left are very small.

**Comment by hamishwillee** [comment]
> "Expose line-wrap as option in the debugger" review — yup, looks fine, apart form the two options we don't know the purpose of ;-)

Did you ping anyone about these?

@chrisdavidmills No, I was hoping you might know - or know best person to ask :-). 
They aren't related to the specific bugfix so didn't think it right to ask that developer.
Who would you ask?

Thanks for review. I'll chase the minor bits left.

**Comment by chrisdavidmills** [comment]
> > "Expose line-wrap as option in the debugger" review — yup, looks fine, apart form the two options we don't know the purpose of ;-)
> 
> Did you ping anyone about these?
> 
> @chrisdavidmills No, I was hoping you might know - or know best person to ask :-).
> They aren't related to the specific bugfix so didn't think it right to ask that developer.
> Who would you ask?

No worries. I went into the DevTools Matrix room and asked for help, and Nicolas Chevobbe gave me some perfect descriptions, which I've filled in on the page. Problem solved.

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks

> Re "I went into the DevTools Matrix room and asked for help, and Nicolas Chevobbe gave me some perfect descriptions, which I've filled in on the page. Problem solved."

if you want me to be able to do this myself in future you're going to have to tell me where this room is, and get me access :-)

FYI Experimental features
- Added [update](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#CSS_browser_compatibility_tooltips) for "[ruleview] Implement the inline CSS compatibility warning in ruleview" review: bit
- Also removed old section on compatibility view (got added "for real" in 77)

**Comment by chrisdavidmills** [comment]
> if you want me to be able to do this myself in future you're going to have to tell me where this room is, and get me access :-)

Sure thing! You'll find such rooms on the Mozilla Matrix server: https://wiki.mozilla.org/Matrix

Thanks for the other additions too.
