### ISSUE TITLE
https://wiki.developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web

### ISSUE THREAD

**Issue by szz0104** [mdn/sprints#3712]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

https://wiki.developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web
This page is implanted with malicious ads.

**Comment by chrisdavidmills** [comment]
Reverted. Thanks.
