### ISSUE TITLE
CSS updates in Firefox 81

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3713]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [[css-overflow] implement overflow:clip by renaming overflow:-moz-hidden-unscrollable](https://bugzilla.mozilla.org/show_bug.cgi?id=1531609) — looks relatively small, mainly a matter of getting rid of the non-standard value out of the docs, and updating the BCD so that it shows support for the `clip` value from now, and the non-standard value as an alternative name for older versions.
2. - [x] [Unship ::-moz-focus-outer.](https://bugzilla.mozilla.org/show_bug.cgi?id=1655859) — probably very little to do here. We never mentioned it on the site, check that it doesn't have a BCD entry, check that the rel note entry looks correct.
3. - [x] [Implement parsing for cross-fade() from CSS Image Values and Replaced Content Module Level 4](https://bugzilla.mozilla.org/show_bug.cgi?id=546052) — we have a cross-fade page, so we'd need to test where it works (`background`, `background-image`), update BCD, update any pages that need updating, write a better examples section that works on the cross-fade page, and include an interactive example ? 
4. - [x] [Make text-combine-upright non-animatable](https://bugzilla.mozilla.org/show_bug.cgi?id=1654195) — update BCD and formal data; not much work here.
5. - [x] [Implement aspect-ratio for basic blocks and replaced elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1639963) — this will require a bit of investigation to see what will need updating in terms of content and BCD. We already have an aspect-ratio page

Estimated total: 2-3 days work?

**Comment by rachelandrew** [comment]
- `text-combine-upright` data PR: https://github.com/mdn/data/pull/428
- `text-combine-upright` BCD PR: https://github.com/mdn/browser-compat-data/pull/6834

**Comment by rachelandrew** [comment]
The `aspect-ratio` issue relates to this discussion https://github.com/mdn/browser-compat-data/issues/6786 so once that has been decided on I can make the change, it seems to be behind a pref for now anyway.

**Comment by rachelandrew** [comment]
So the cross-fade one, is just for parsing so it's probably a bit early to update as there isn't actually support yet, the bug for adding the feature is here https://bugzilla.mozilla.org/show_bug.cgi?id=1657516

**Comment by chrisdavidmills** [comment]
> The aspect-ratio issue relates to this discussion mdn/browser-compat-data#6786 so once that has been decided on I can make the change, it seems to be behind a pref for now anyway.

OK, cool. Let's keep an eye on that one then.

> So the cross-fade one, is just for parsing so it's probably a bit early to update as there isn't actually support yet, the bug for adding the feature is here https://bugzilla.mozilla.org/show_bug.cgi?id=1657516

Ah, good point. I've updated https://bugzilla.mozilla.org/show_bug.cgi?id=546052#c32 to suit. I guess that means you can check this one completed then.

**Comment by rachelandrew** [comment]
I've added `aspect-ratio` to the Experimental Features page, made a few edits to the page to clear up the confusion between internal mapping and the actual property, and am working with @ddbeck on the BCD side of things (PR is in) so I think this one is probably as done as it needs to be as an experimental feature.

**Comment by chrisdavidmills** [comment]
Reviewed, all is looking good, so closing.
