### ISSUE TITLE
Media updates in Firefox 81

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3715]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Enable MediaControl in release](https://bugzilla.mozilla.org/show_bug.cgi?id=1648100) — looking at our [internal explainer](https://docs.google.com/document/d/1c4FivJpvAjjw9Uw-jn7X1UjGOoWkANXOulNyqDWs83w/edit#heading=h.wsp2v2xk20e), it looks like this is just about making media playable using computer hardware keys, etc., and we only support `<audio>` and `<video>` right now (not other media such as Web Audio API). I suspect we probably want to include a rel note, and mention it on the audio/video pages, and mention it in the MediaSession API documentation, how it is related, etc? [This looks related](https://github.com/feedbee/web-page-media-control-api-spec), but we don't seem to mention this at all. Bit of investigation needed, write an example, etc. Ask the engineer if you are confused.

Estimated total: 1-2 days.

**Comment by Rumyra** [comment]
Happy to have you assign this to me @chrisdavidmills 👍

**Comment by chrisdavidmills** [comment]
@Rumyra done! BTW, I invited you to this repo with write access, so you assign yourself in future.

**Comment by chrisdavidmills** [comment]
Looking at this again, I don't think there is anything to do here. See https://bugzilla.mozilla.org/show_bug.cgi?id=1648100#c10

I added a quick note about it to the top of https://wiki.developer.mozilla.org/en-US/docs/Web/API/Media_Session_API.
