### ISSUE TITLE
General WebAPI updates in Firefox 81

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3716]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Increase threshold of gamepad joystick activation](https://bugzilla.mozilla.org/show_bug.cgi?id=1539178) — I don't think there is anything to mention here, beyond writing a rel note. Ask the engineer to confirm?
2. - [x] [Re-enable strict MIME type checking for Worker/SharedWorker](https://bugzilla.mozilla.org/show_bug.cgi?id=1569123) — this is a fairly small change. It needs a rel note, and BCD updating. The BCD for [Worker()](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Worker/Worker#Browser_compatibility) and [`SharedWorker()`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker#Browser_compatibility) needs updating, and we should remove the note about it from the [70 rel notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70). The [site compat note](https://www.fxsitecompat.dev/en-CA/docs/2020/worker-scripts-with-wrong-mime-type-will-be-blocked-from-loading-with-worker-or-sharedworker/) is also helpful.

Estimated total: half a day?

**Comment by hamishwillee** [comment]
1. - [ ] [Increase threshold of gamepad joystick activation](https://bugzilla.mozilla.org/show_bug.cgi?id=1539178) — I don't think there is anything to mention here, beyond writing a rel note. Ask the engineer to confirm?
   - HamishW : I don't see any other need either - this is more of a compensation for bad joysticks than an actual use of API thing. I asked the question, but can't do it as a request info. Perhaps they left. Anyway, don't see no response as a blocker for this. 

- [ ] Added [release note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#Gamepad)

@chrisdavidmills I think this one is done.

**Comment by hamishwillee** [comment]
2. - [ ] [Re-enable strict MIME type checking for Worker/SharedWorker](https://bugzilla.mozilla.org/show_bug.cgi?id=1569123) — this is a fairly small change. It needs a rel note, and BCD updating. The BCD for [Worker()](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Worker/Worker#Browser_compatibility) and [`SharedWorker()`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker#Browser_compatibility) needs updating, and we should remove the note about it from the [70 rel notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70). The [site compat note](https://www.fxsitecompat.dev/en-CA/docs/2020/worker-scripts-with-wrong-mime-type-will-be-blocked-from-loading-with-worker-or-sharedworker/) is also helpful.

    - Quick Review
      - All above makes sense but I think the Worker/SharedWorker docs also need update for the note below to also include `application/javascript`, and a note that this appears in FF82. I am checking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1569123#c19
          > A NetworkError is raised if the MIME type of the worker script is incorrect. It should always be text/javascript.
   

- [ ] BCD for [Worker()](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Worker/Worker#Browser_compatibility)
- [ ] BCD for [`SharedWorker()`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker#Browser_compatibility) 
- [ ] Remove the note about it from the [70 rel notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70). 
- [ ] [Release note](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/81#WorkersService_workers)
- [ ] Worker/Shared worker docs update as discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1569123#c19

**Comment by hamishwillee** [comment]
@chrisdavidmills Both of these should be good to review now (though BCD not yet accepted)

**Comment by chrisdavidmills** [comment]
Reviewed, looks awesome, can close.
