### ISSUE TITLE
HTML updates in Firefox 81

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3718]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [To block automatic download in sandboxed iframe](https://bugzilla.mozilla.org/show_bug.cgi?id=1558394) — looks like evilpie already added a relnote that explains this nicely. Need to check whether this is documented in the `<iframe>` page, and added to its BCD.
2. - [x] [Remove mozallowfullscreen.](https://bugzilla.mozilla.org/show_bug.cgi?id=1657599) — again, evilpie has added a helpful rel note. Need to check whether this is removed from the `<iframe>` page, and BCD is updated.
3. - [x] [Layout for <input type="search">](https://bugzilla.mozilla.org/show_bug.cgi?id=558594) — I don't think there is much to do here; a rel note for sure, maybe an update to the <input type="search"> page?
4. - [x] [Implement the HTML inert](https://bugzilla.mozilla.org/show_bug.cgi?id=1655722) — a bit of work to do here; we need a page for both the `inert` attribute and the `::inert` pseudo-element, including interactive examples and BCD, make sure related pages like reference lists are updated, and rel note.

Estimated total: 3-4 days.

**Comment by rachelandrew** [comment]
It looks as if the blocking of downloads went into 81, and the allow-downloads flag into 82, so the release note here should be about the blocking and not the flag?

- https://bugzilla.mozilla.org/show_bug.cgi?id=1558394 Firefox 81
- https://bugzilla.mozilla.org/show_bug.cgi?id=1656212 Firefox 82

**Comment by rachelandrew** [comment]
Layout for is still behind the `layout.forms.input-type-search.enabled` flag, the note in the code says it is waiting for tests and a web enabled way to remove the clear button. So I think for now I'll just add a note saying it's behind a flag in 81.

**Comment by chrisdavidmills** [comment]
> So I think for now I'll just add a note saying it's behind a flag in 81.

If it's still behind a flag, the correct place to note it is the [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) page. Sorry if you aready know this, but just checking ;-)

**Comment by rachelandrew** [comment]
So we don't add a release note at all in that case?

**Comment by rachelandrew** [comment]
`inert` also appears to be behind a flag. Here is the BCD PR: https://github.com/mdn/browser-compat-data/pull/6858

It's really hard to tell from the issue if these things have shipped behind a flag. I find out by testing and it not working so I go search for a flag, or look in the commit to the browser code to see if I can see one. Would save a bit of time if a note was left.

**Comment by chrisdavidmills** [comment]
> So we don't add a release note at all in that case?

That's correct, yes. We only add rel notes in the case of features that are enabled in release by default. `inert` should also only be in the exp features page for now.

> It's really hard to tell from the issue if these things have shipped behind a flag. I find out by testing and it not working so I go search for a flag, or look in the commit to the browser code to see if I can see one. Would save a bit of time if a note was left.

Yup, agreed. I basically take the same kind of approach as you. It's always good to ask for this kind of info up front, so I might start doing that when I'm triaging / scoping out the bugs in future.

**Comment by rachelandrew** [comment]
Cool, I've done that for the two things which are still behind a flag, could you see if you agree with me on https://github.com/mdn/sprints/issues/3718#issuecomment-703705106

**Comment by chrisdavidmills** [comment]
> Cool, I've done that for the two things which are still behind a flag, could you see if you agree with me on #3718 (comment)

Yes, I do agree with that.

**Comment by chrisdavidmills** [comment]
reviewed; this all looks good.
