### ISSUE TITLE
Firefox 63 WebExt DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#372]
# User story
As an extensions developer, I want to learn about the new WebExtension/Browser Extension features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [x] All DDNs complete.
2. - [ ] Reviews request from engineers for all documentation work.

# Tasks

## Items for Irene

1. - [x] [Implement Google Chrome New Tab Page color properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1347204) [2 points]
2. **(Moved to a separate Issue, #[503](https://app.zenhub.com/workspace/o/mdn/sprints/issues/503))** [Implement theme experiments](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207) [2 points]
3. - [x] NEW [Allow theming sidebars](https://bugzilla.mozilla.org/show_bug.cgi?id=1418602) [1 point]

(smaller items, total 3.5 points)
1. - [x] [webRequest.getSecurityInfo should not return localised values](https://bugzilla.mozilla.org/show_bug.cgi?id=1470516)
10. - [x] [Add sameSite attribute (no_restriction, lax, strict) to browser.cookies API](https://bugzilla.mozilla.org/show_bug.cgi?id=1351663)
11. - [x] [Implement support for the 'highlighted' API for multiselect tabs with tabs.query](https://bugzilla.mozilla.org/show_bug.cgi?id=1465170)
12. - [x] [Expose multiselected status to "tabs.Tab.highlighted", and allow to change it via "browser.tabs.highlight()"](https://bugzilla.mozilla.org/show_bug.cgi?id=1464862)
13. - [x] [Remove "Open in Sidebar" feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1452645)
14. - [x] NEW [contextMenus do not support other protocols (ex. 'magnet:*', 'acestream:*', 'sop:*')](https://bugzilla.mozilla.org/show_bug.cgi?id=1280370)
15. - [x] NEW [contextMenus.OnClickData should provide selector of the clicked element](https://bugzilla.mozilla.org/show_bug.cgi?id=1325814)
16. - [x] NEW [Implement support for updateProperties.highlighted in browser.tabs.update()](https://bugzilla.mozilla.org/show_bug.cgi?id=1479129)
17. - [x] NEW [Impossible to change multiselection state of tabs by setting "highlighted" attribute of tabs without focus change](https://bugzilla.mozilla.org/show_bug.cgi?id=1486050)
18. - [x] NEW [Allow extensions to access tab's "attention" flag](https://bugzilla.mozilla.org/show_bug.cgi?id=1396684)
19. - [x] NEW [Provide a management.install command for themes only](https://bugzilla.mozilla.org/show_bug.cgi?id=1369209)

## Items for Will

1. - [x] [Add an API to list installed search engines and execute searches using only those engines](https://bugzilla.mozilla.org/show_bug.cgi?id=1352598) [1.5 points — already started, but it needs cleanup; see will's existing comments]
2. - [x] NEW [commands API is not treated as user input](https://bugzilla.mozilla.org/show_bug.cgi?id=1408129) [1 point]
3. - [x] NEW [Implement support for the 'onHighlighted' API for multiselect tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1474440) [1 point]
4. - [x] NEW [Implement "visible" parameter in menus.create and menus.update](https://bugzilla.mozilla.org/show_bug.cgi?id=1482529) [1 point]
5. - [x] NEW [Add ability to set access key to context menu item](https://bugzilla.mozilla.org/show_bug.cgi?id=1320462) [1 point]

(smaller items, total 3.5 points)
1. - [x] [Add speculative connection type for webrequest and proxy](https://bugzilla.mozilla.org/show_bug.cgi?id=1479565)
2. - [x] [activeTab permission not granted for tab on which the contextmenu is used](https://bugzilla.mozilla.org/show_bug.cgi?id=1446956)
3. - [x] [Choose browserAction text color among white and black, maximizing contrast](https://bugzilla.mozilla.org/show_bug.cgi?id=1474110)
4. - [x] [webRequest, add a public documentation about "documentUrl"](https://bugzilla.mozilla.org/show_bug.cgi?id=1386707) [Will did most of this, just needs BCD adding]
5. - [x] [Make accentcolor and textcolor optional](https://bugzilla.mozilla.org/show_bug.cgi?id=1413144)
6. - [x] [tabs.onUpdated filtering uses isarticle, details uses isArticle.](https://bugzilla.mozilla.org/show_bug.cgi?id=1461695)
7. - [x] [Allow to set browserAction badge text color](https://bugzilla.mozilla.org/show_bug.cgi?id=1424620)
8. - [x] [TLS status API should return `null` for certain attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1471959)
8. - [x] [topSites places support](https://bugzilla.mozilla.org/show_bug.cgi?id=1445836)

**Comment by irenesmith** [comment]
New tab colors was much simpler than it appeared. I only had to update browser compatibility since the properties are already defined as a result of Chrome support for them.

**Comment by irenesmith** [comment]
Asked about this one: #[1470516](https://bugzilla.mozilla.org/show_bug.cgi?id=1470516) as I'm not sure that it  needs anything but a release notes comment because none of the existing documentation says anything about localized strings.

**Comment by irenesmith** [comment]
Remaining DDNs:

[1347207](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207) should be done today.
[1418602](https://bugzilla.mozilla.org/show_bug.cgi?id=1418602) asked what changes there are to document here. It isn't clear from reading the bug whether theme creators have to define something in particular to have this work.
[1280370](https://bugzilla.mozilla.org/show_bug.cgi?id=1280370) should be done this afternoon.
[1396684](https://bugzilla.mozilla.org/show_bug.cgi?id=1396684) This one may not be done until tomorrow (Friday) morning.
[1369209](https://bugzilla.mozilla.org/show_bug.cgi?id=1369209) Another one that may not be done until tomorrow (Friday) morning.

**Comment by irenesmith** [comment]
[1369209](https://bugzilla.mozilla.org/show_bug.cgi?id=1369209) - Some of the information in the bug description implies that the management.install method only applies to lightweight themes. It doesn't seem to make sense to document it if LWT is going away.

**Comment by irenesmith** [comment]
#[1347207](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207) - Removing this one from the issue as it is more extensive than a DDN. I will discuss the subject of experimental themes with the team and determine how ready it is for release, then come up with a plan to document it fully.
