### ISSUE TITLE
The popstate event actually occurs even after calling history.pushState()

### ISSUE THREAD

**Issue by tsmd** [mdn/sprints#3721]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the [Working with the History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#Adding_and_modifying_history_entries) page, there is a note that...

> **Note:** Calling `history.back()` normally behaves the same way as clicking the **Back** button. But there is one important exception:
>
> *After* using `history.pushState()`, calling `history.back()` *does not* raise a `popstate` event. Clicking the browser's **Back** button (still) does.

I think this note is simply incorrect.
Actually, `popstate` event occurs even after calling `history.pushState()` in every browser including Internet Explorer.
I have no idea this paragraph come from. I could not find any description from specifications that describes such behavior.

**Comment by chrisdavidmills** [comment]
Looks like this needs a test, and then the page to be updated either way.

**Comment by chrisdavidmills** [comment]
We've got a duplicate of this, at https://github.com/mdn/content/issues/1493. Since we are now using the content repo for MDN content issues, I'm closing this one.
