### ISSUE TITLE
width fit-content not working as documented

### ISSUE THREAD

**Issue by bryanrasmussen** [mdn/sprints#3723]
**Summary**
In the description of width one of the potential values is the fit-content function. Using it in the code editor as documented does not work

**Steps To Reproduce (STR)**
1.  Go to width https://developer.mozilla.org/en-US/docs/Web/CSS/width
2. Go to first code block and enter width: fit-content(5%); 

**Actual behavior**
the field gets yellow border and the example div does not change size. 

**Expected behavior**
normal color border for the currently executing code block and the width to be fitted to 40% 

**Additional context**
the reason why I might expect the expected behavior is the fit-content value is described as 
fit-content(&lt;length-percentage&gt;)
    Uses the fit-content formula with the available space replaced by the specified argument, i.e. min(max-content, max(min-content, &lt;length-percentage&gt;)).

which implies a function. like this one https://caniuse.com/?search=fit-content()
but i thought that the fit-content value was just a value - fit-content like so
width: fit-content and the formula for that should be fit-content = min(max-content, max(min-content, fill-available)) ?

but that doesn't really matter as fit-content as a value doesn't work either.

**Comment by chrisdavidmills** [comment]
From my testing `fit-content()` as a function doesn't work, but `fit-content` as a simple value does work (`-moz-fit-content` on Firefox). So I think perhaps the spec has changed since this page was created, and the descriptions need updating (along with the formal syntax, etc.)

I wasn't able to check the specs, because the site was down.

**Comment by bryanrasmussen** [comment]
I admit I'm a little bit confused as to it as well, I know there is  fit-content function that is for grids, I think that fit-content function is supposed to work for normal width at some point also but there is also the fit-content keyword at width 

https://www.w3.org/TR/css-sizing-4/#sizing-values
3.2. New Sizing Values: the stretch, fit-content, and contain keywords

stretch
    Applies stretch-fit sizing, attempting to match the size of the box’s margin box to the size of its containing block. See § 7.1 Stretch-fit Sizing: filling the containing block. 

fit-content
    Essentially fit-content(stretch) i.e. min(max-content, max(min-content, stretch)). 

So I think in the current applicable spec fit-content keyword is at width, and the fit-content function is the one used in grids 
as per
https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content
but I would like someone to clarify because two things with same name can be confusing.

**Comment by rachelandrew** [comment]
It's defined in sizing 3: https://drafts.csswg.org/css-sizing-3/#valdef-width-fit-content-length-percentage

Sizing 4 defines the value that isn't a function https://www.w3.org/TR/css-sizing-4/#sizing-values but it's a diff spec so my understanding is that the function will be carried over when everything else is. 

So I don't think the page is wrong, although it might be worth updating the compat data to be "supported in grid layout", at some point we need to deal with the non-function `fit-content` I guess.

**Comment by bryanrasmussen** [comment]
yeah but the text of the MDN page describes using the fit-content function
in width, for example the following text:

/* Keyword values */width: max-content;width: min-content;width:
fit-content(20em);width: auto;


, if you use the fit-content function in the css demo area for width it
fails. So I mean you can't use the described function in the demo area, so
I think the text should probably be changed or something?

[image: image.png]

**Comment by rachelandrew** [comment]
That description is correct, in terms of valid use of the property. The fact it isn't supported in browsers yet needs reflecting in the compat data. There are a lot of things documented but not yet supported, these partial implementations are tricky though.

@chrisdavidmills @ddbeck could we do something similar here to what we did for the gap properties? https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap

It's also defined for `flex-basis` which takes any valid width, but again not supported anywhere.

I'm also wondering if we need to rename this, given there is a value without the function part in the L4 spec?

**Comment by bryanrasmussen** [comment]
>That description is correct, in terms of valid use of the property. The
fact it isn't supported in >browsers yet needs reflecting in the compat
data.

exactly, I would just like there to be something that gave a heads up why
it isn't working, since the documentation implies it should. If it is this
is correct, but it is not working right now because of browser
incompatibility, cool. (also because confusing with the keyword and
function)

**Comment by ddbeck** [comment]
@rachelandrew

> could we do something similar here to what we did for the gap properties? https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap

I'm sorry, I don't understand the context enough to answer this question better, but I think I'd like to steer us away from gap as a model. The namespaces for different contexts presented some problems for the Stumptown project. I opened https://github.com/mdn/browser-compat-data/issues/6175 to reexamine how we handle that data. If possible, I'd like to direct efforts toward subfeatures rather than building structures above `fit-content`.

**Comment by rachelandrew** [comment]
It would be good to understand then how you want to deal with partial implementations? The `gap` stuff was done because we had the partial implementation issue (gap being supported in grid and multicol but not flex and block layout). I think we have a similar problem here of partial implementation.

**Comment by rachelandrew** [comment]
OK so I've been looking at this. I think we need two pages, and to disambiguate the BCD data between the level 3 `fit-content()` function, which is really what the existing page is about and the level 4 `fit-content` keyword.

That way the function page can show support in grid layout, and support for `width` etc. for the function. 

I therefore think I need to add to BCD for `width`, `fit-content()` as a function and make sure the support data is correct for both, I think it's mixed up right now. Then I can show two charts as I have done here https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content (except at the moment we have this mixture of compat data for width.) cc: @chrisdavidmills @ddbeck

**Comment by chrisdavidmills** [comment]
@chrisdavidmills this is an interesting one. I'm trying to remember if we've had a previous need to disambiguate two items, and what we did then. Do you have any suggestions that we could investigate?

One that sprints to mind is `opacity` property / `opacity()` function, but that's dealt with like this:

* https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
* https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/opacity

If we don't have a previously decided way of doing this, we ought to decide on something. We could deal with this like wikipedia does...

**Comment by rachelandrew** [comment]
@chrisdavidmills yeah maybe we just have fit-content and fit-content-function and put a note at the top of each page. Likely thing is that people will go to the bare fit-content first so as long as it's clear.

Other CSS functions are listed right under CSS - for example https://developer.mozilla.org/en-US/docs/Web/CSS/calc if this were likely to come up with more functions we could move functions to CSS/functions I guess but I'm not sure this is going to keep coming up.

**Comment by rachelandrew** [comment]
@chrisdavidmills this issue also relates https://github.com/mdn/sprints/issues/3848

**Comment by ramiy** [comment]
I think the solution is to have two articles in MDN:

* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content - for `fit-content` value used by `width`.
* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content() - for `fit-content()` function used by `grid-template-rows` and `grid-template-columns`.

Currently MDN has documentation for the function.

**Comment by chrisdavidmills** [comment]
@ramiy I think your proposal sounds good, and is consistent with what we've discussed in https://github.com/mdn/sprints/issues/3848.

So in this case, we've got the function documented at `/fit-content`. This content should be moved to `/fit-content()`, and then the documentation for the value should be put at `/fit-content`.

Does this sound OK to you, @rachelandrew ? As I said in the other bug, if we later decide on a different convention, we can easily make that change under Yari.

**Comment by rachelandrew** [comment]
@chrisdavidmills yep that's great. I can sort that and as I'm going round all the pages to update the `grid-gap` / `gap` stuff I can make sure they link to the right incarnation of `fit-content()` too.

**Comment by chrisdavidmills** [comment]
@rachelandrew great stuff, thanks!

**Comment by rachelandrew** [comment]
@chrisdavidmills hmm ... so I moved `fit-content` to `fit-content()` but still can't create a new page at `fit-content`, I assume that's because there is a redirect now in place? I've got all the content, just can't make the page.

**Comment by rachelandrew** [comment]
oh, although it said it had been moved (I have the email) it's still redirecting to https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content

**Comment by chrisdavidmills** [comment]
@rachelandrew yeah, I was hoping to move the content of `/fit-content` to `/fit-content()`, not move the page, as then you get exactly the problem you are now experiencing. I've just tried moving the page back to `/fit-content`, in the hope that this would un-create the redirect, but it doesn't. `/fit-content()` now redirects back to `/fit-content`.

I think we'll need an MDN dev to help put this right.

@escattone , can you help us with this? We need two separate pages, at 

* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content
* https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content()

We have an existing page at the former URL, and the latter URL redirects ot the former. Can you update it so that the latter does not redirect to the former, and we can create a separate page at that URL?

**Comment by rachelandrew** [comment]
ah I see, I thought I could just move the page, then make a new page. Sorry if I've made a mess.

**Comment by chrisdavidmills** [comment]
@rachelandrew no worries at all; it is all pretty confusing and non-obvious. I think we'll be able to get this sorted.

**Comment by escattone** [comment]
@chrisdavidmills @rachelandrew Done! I removed the content-based redirect command within https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content(), so now it's basically an empty page, and ready for whatever you'd like to add.

**Comment by chrisdavidmills** [comment]
@escattone ah, so the redirects when you move pages are just put in place via content-based redirects? I'll remember that for next time.

@rachelandrew I've now moved the function content to https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content(), so now https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content is free for you to add the keyword content to.

**Comment by rachelandrew** [comment]
@escattone @chrisdavidmills thanks both, I shall try not to make a mess in future! I've added the content, and a note at the top of fit-content about fit-content() as currently a lot of the grid things will point to the keyword not the function (as may external things). I'll go round and fix our stuff as I do these various grid updates.
