### ISSUE TITLE
https://wiki.developer.mozilla.org/fr/docs/Web/CSS/S%C3%A9lecteurs_de_voisins_g%C3%A9n%C3%A9raux$history

### ISSUE THREAD

**Issue by BrnvrlUoeey** [mdn/sprints#3728]
# Request type

- [ ] Correction or update

# Details

On this page : 
[https://developer.mozilla.org/fr/docs/Web/CSS/S%C3%A9lecteurs_de_voisins_g%C3%A9n%C3%A9raux](https://developer.mozilla.org/fr/docs/Web/CSS/S%C3%A9lecteurs_de_voisins_g%C3%A9n%C3%A9raux)
French translation is not complete, "(though not necessarily immediately)" not being traduced, which makes difficult to understand the difference between the ~ CSS selector and the + (adjacent) CSS selector.

https://developer.mozilla.org/fr/docs/Web/CSS/S%C3%A9lecteurs_de_voisins_g%C3%A9n%C3%A9raux

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations; closing this issue. You are welcome to edit them yourself.
