### ISSUE TITLE
CSS updates for Firefox 82

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3729]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Allow :is() and :where() to have better error recovery.](https://bugzilla.mozilla.org/show_bug.cgi?id=1664718) — not really sure what to do here, needs investigation, but looks like it'll mean a small update to the `:is()`/`:where()` pages, and a BCD update for each. Ask Emilio if you need more help.
2. - [x] [[css-ui] Change appearance: button to only apply to buttons](https://bugzilla.mozilla.org/show_bug.cgi?id=1662703) — not much to do here, small update to appearance page and BCD.
3. - [x] [Remove -moz-user-disabled.](https://bugzilla.mozilla.org/show_bug.cgi?id=1664432) — Not much to do here; maybe just a rel note? There isn't a page about it on MDN; check BCD also?
4. - [x] [Rename file-chooser-button to file-selector-button, and enable in all channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1662478) — looks like a standardized pseudo addition, needs testing, padding adding, demo writing and adding (+ interactive example?), and BCD adding.

Total estimate: 2 days.

**Comment by rachelandrew** [comment]
BCD for `:is()` and `:where()`: https://github.com/mdn/browser-compat-data/pull/6774

The `is()` page could do with some love, it's a bit confusing with regards to the old pseudo name etc.

**Comment by chrisdavidmills** [comment]
> The `is()` page could do with some love, it's a bit confusing with regards to the old pseudo name etc.

It would be great if you could handle that as well, provided you don't think it'll take forever.

**Comment by rachelandrew** [comment]
no problem, I don't think it will take too long, just didn't want to head off down a rabbit hole without checking :D 

I think it was put together at the time the pseudo was renamed but now we have support in two browsers, and it's in Canary too so presumably incoming for Chrome, we can probably dial down the stuff about `:matches()`.

**Comment by chrisdavidmills** [comment]
Sounds good to me. Maybe timebox yourself to say 2-3 hours at the most, and improve it as much as you can in that time?

**Comment by rachelandrew** [comment]
I think that's a bit better now, and the pages for :where() and :is() are now similar, although :where() doesn't have legacy info.

**Comment by rachelandrew** [comment]
Looks like `appearance: button` has already been dealt with in the last few days (not showing on the site yet) https://github.com/mdn/browser-compat-data/pull/6750

**Comment by rachelandrew** [comment]
@chrisdavidmills We have https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-file-upload-button which `::file-selector-button` is a standardized version of. How do we deal with this in terms of the pages and BCD? DO we rename the webkit version to the standard name and then have this as an alternate name?

**Comment by chrisdavidmills** [comment]
I would follow the same pattern as the `appearance` page: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance.

So basically, the slug should be just the standardized name, and the `<h1>` should be the standardized name, with the alternative name in brackets.

In BCD, yes you're right — the overall data point should be the standard name, with the `-webkit-` version listed as an alternative name.

**Comment by rachelandrew** [comment]
cool - so can I rename that page or should I create a new one?

**Comment by chrisdavidmills** [comment]
You can rename that page and move it to the desired new slug, then the old URL will redirect to it automatically. Do you have page move permissions?

**Comment by rachelandrew** [comment]
> Do you have page move permissions?

looks like I do.

**Comment by chrisdavidmills** [comment]
Cool, you're all set then.

**Comment by rachelandrew** [comment]
That's all sorted, I also updated the Webkit extensions page https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

**Comment by chrisdavidmills** [comment]
Looks perfect @rachelandrew , thanks. The only change I made was to change the BCD data reference on the `::file-selector-button` page to `css.selectors.file-selector-button`, as it is now available to display.
