### ISSUE TITLE
Some WebGL API pages source codes not highlighted!

### ISSUE THREAD

**Issue by Rabios** [mdn/sprints#3730]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Here we go again!

Some lines of code and shaders source codes aren't highlighted in WebGL API pages, Links for pages are below.
That's all, Thanks for reading!

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_shaders_to_apply_color_in_WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Lighting_in_WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_objects_with_WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Matrix_math_for_the_web
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

**Comment by chrisdavidmills** [comment]
Looking at this, the unhighlighted code blocks either have the wrong code highlighting selected (in the first one, several blocks were given HTML highlighting), or don't have a highlighting type selected at all.

**Comment by Rabios** [comment]
@chrisdavidmills Thanks! Hope i helped MDN enough, And will continue helping!

**Comment by Cimeone** [comment]
I've gone through all your links, and cannot identify any more lines of code that have not been highlighted, believe all these have now potentially been resolved!

**Comment by chrisdavidmills** [comment]
Yup, let's close.
