### ISSUE TITLE
WebAPI updates for Firefox 82

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3731]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x]  [@hamishwillee] [window.name can be used as an XSS attack vector](https://bugzilla.mozilla.org/show_bug.cgi?id=444222) — looks like a fairly simple update to cross-origin behavior of `window.name`; needs page updating to talk about it, maybe a small example, and a BCD update. Maybe also see if there is anywhere in our security pages that it would warrant a mention?
2. - [ ]  [@hamishwillee]  [Enable MediaSession API](https://bugzilla.mozilla.org/show_bug.cgi?id=1665496) — this is documented already, so it looks like this mostly just needs BCD updates, plus you should also check that the documentation is complete.
3. - [x]  [@hamishwillee] [element.setPointerCapture should throw NotFoundError if the pointer id is invalid](https://bugzilla.mozilla.org/show_bug.cgi?id=1662124) — not really sure what to do for this one; it's probably not big, but needs some investigation.
4. - [x]  [@hamishwillee] [Refuse nested `Document.execCommand()` calls by default in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1634262) — I think this just needs a BCD entry, and nmaking sure this is noted on the `execCommand()` page somewhere sensible.

Total estimate: 2 days

**Comment by hamishwillee** [comment]
4. - [ ] [Refuse nested `Document.execCommand()` calls by default in release builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1634262) — I think this just needs a BCD entry, and making sure this is noted on the `execCommand()` page somewhere sensible.
  
   - - [ ] BCD Entry: https://github.com/mdn/browser-compat-data/pull/6842
   - - [ ] Updated [execCommand page](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document/execCommand$compare?locale=en-US&to=1647386&from=1642313) with note at beginning and against the return value.
   - - [ ] Release note - [added note to DOM section](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#APIs)

@chrisdavidmills This one ready for review.

**Comment by hamishwillee** [comment]
3. - [ ]  [@hamishwillee] [element.setPointerCapture should throw NotFoundError if the pointer id is invalid](https://bugzilla.mozilla.org/show_bug.cgi?id=1662124) — not really sure what to do for this one; it's probably not big, but needs some investigation.
   - Quick review
     - The change appears straightforward - we were throwing wrong error (by spec) now we are throwing correct one. So we need BCD, Release note, and update to docs.
     - Wr.t. docs I think that right places is in [setPointerCapture > Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) (Imo not worth having in higher level doc [Pointer_events#Pointer_capture](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#Pointer_capture))

   - - [x] BCD Entry: https://github.com/mdn/browser-compat-data/pull/6843
   - - [x] Updated [setPointerCapture > Syntax > Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture#Syntax) - In "Exceptions" table changed exception to new value (NotFoundError) and added note about the exception used in earlier versions.
   - - [x] Release note - [added note to DOM  section](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#APIs)

@chrisdavidmills This one ready for review.

**Comment by hamishwillee** [comment]
1. - [ ]  [@hamishwillee] [window.name can be used as an XSS attack vector](https://bugzilla.mozilla.org/show_bug.cgi?id=444222) — looks like a fairly simple update to cross-origin behavior of `window.name`; needs page updating to talk about it, maybe a small example, and a BCD update. Maybe also see if there is anywhere in our security pages that it would warrant a mention?
   - Quick Review - 12 years of history on this one!
     - The problem is that [window.name](https://developer.mozilla.org/en-US/docs/Web/API/Window/name) was shared among all tabs/sites that use the window. This was providing:
       - an uncontrolled/risky mechanism mechanism for cross-domain sharing, which that was leveraged by some frameworks.
       - potential for a bad actor to get information that was stored by sites in window name "for convenience".
       - potential for a bad actor inject information into that value that might then be used by original origin.
     - The relevant change appears to that `window.name` of a new page/tab is reset to an empty string when a page is opened from another origin than the first page. I think that `window.name` is still a global value that just gets reset and restored as needed but it may be I am completely missing something. 
     - I am discussing in https://bugzilla.mozilla.org/show_bug.cgi?id=444222
     - Unlikely I can write a "simple" example for this.

   - - [ ] BCD Entry: TBD
   - - [ ] Update [window.name](https://developer.mozilla.org/en-US/docs/Web/API/Window/name). The docs  - In "Exceptions" table changed exception to new value (NotFoundError) and added note about the exception used in earlier versions.
   - - [ ] Release note - [will need to add note to DOM  section](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#APIs)

**Comment by hamishwillee** [comment]
2. - [ ]  [@hamishwillee]  [Enable MediaSession API](https://bugzilla.mozilla.org/show_bug.cgi?id=1665496) — this is documented already, so it looks like this mostly just needs BCD updates, plus you should also check that the documentation is complete.

   - - [ ] BCD Entry: https://github.com/mdn/browser-compat-data/pull/6845
   - - [ ] Docs
      -  [Spec](https://w3c.github.io/mediasession/#the-mediasession-interface) is still marked draft as is the BCD status of API, so have not modified experimental status notes anywhere. Note however that the bug fix removed it from the "experimental features list".
      - - [ ] Review [Media Session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API)
      - - [ ] Review [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession)
      - - [ ] Review [MediaSessionActionDetails](https://developer.mozilla.org/en-US/docs/Web/API/MediaSessionActionDetails)
      - - [ ] Review [MediaSessionAction](https://developer.mozilla.org/en-US/docs/Web/API/MediaSessionAction)
      - - [ ] ETC!
   - - [ ] Release note - [will need to add note to *Media, WebRTC, and Web Audio* section](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#APIs)

**Comment by chrisdavidmills** [comment]
Thanks @hamishwillee. Looks like most of this has been done fine. I have made a few edits to the pages to tighten up the prose a bit, and made some suggestions on improving the BCD for the MediaSession API.

I think it'd be great if @rumyra looked at the MediaSession docs and thought about if anything is missing, if it needs better examples, etc.

**Comment by hamishwillee** [comment]
@chrisdavidmills Thank you. FYI, have acted on your BCD suggestions for MediaSession API - waiting for review Thanks for tidying prose; I did various changes along the way too, but mostly "to my taste".

Agree, very pleased if @Rumyra look has a look too. @Rumyra note that the BCD for MediaPositionState has now been updated, but until that goes in you'll see the table missing in the docs.

**Comment by Rumyra** [comment]
Thanks both, I'll check out the MediaSession docs now

**Comment by chrisdavidmills** [comment]
Cool, cheers @Rumyra , and thanks @hamishwillee for your continued work.

**Comment by Rumyra** [comment]
Just moved this back whilst I get some good code examples in

**Comment by Rumyra** [comment]
I've written a demo and added a pr to dom-examples for it...

I've updated all of the code examples within the API pages to be consistant and show the relevant code where appropriate.

The task for the future is to write up the demo as a tutorial (added as a task in web apis project), for which I have already made notes 👍

**Comment by chrisdavidmills** [comment]
@Rumyra the demo is great, and works really nicely on Chrome and Firefox. The only thing I was wondering about is — isn't one of the main points of the Media Session API to provide meta data about tracks that can be easily shown in notifications? therefore, would it make sense to add some Notifications API code to the demo so that when a track changes, a system notification is shown to display details the next track?

**Comment by chrisdavidmills** [comment]
@Rumyra hi Ruth! I can't remember exactly what was said when we chatted about this, but I believe that we agree that the MediaSession docs were complete for their basic purpose, right? And that anything left, like adding a basic tutorial and figuring out a more advanced version with notifications or whatever could be left to an advanced tutorial?

In which case, shall we close this one, and then you can submit sprint issues for the tutorials?

**Comment by Rumyra** [comment]
Yes that's it :D I've added an issue to the Web APIs project, so once we've cleared the release issues I can go back and spend some more time making an explainer - see #3797

**Comment by chrisdavidmills** [comment]
@Rumyra perfect, thanks!

**Comment by Rumyra** [comment]
Just moved this to 'done' as it's closed 👍
