### ISSUE TITLE
HTTP updates for Firefox 82

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3733]
## Story

As a web developer, I want to know how to ...

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [`<a download>` does not download the file when a Content-Disposition inline header is returned](https://bugzilla.mozilla.org/show_bug.cgi?id=1658877) — The engineers already made an effort to document this, but I think it needs checking carefully — there's quite a lot of discourse about it. Also make sure a rel note has been included.

Total estimate: a couple of hours?

**Comment by hamishwillee** [comment]
Status update/notes for  [`<a download>` does not download the file when a Content-Disposition inline header is returned](https://bugzilla.mozilla.org/show_bug.cgi?id=1658877)
- [ ] Waiting on [confirmation of the actual change](https://bugzilla.mozilla.org/show_bug.cgi?id=1658877#c19).
- [ ] Note about change in [download attribute docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes) needs review based ^^^.
- New note should be added to end of [Content Disposition > Syntax > As a response header for the main body ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#Syntax) explaining condition under which the header might be ignored.
- [ ] BCD entry here: [http/headers/content-disposition.json](https://github.com/mdn/browser-compat-data/blob/master/http/headers/content-disposition.json). I *THINK* based on the [guide here](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#notes) that this is 
  - probably not going to result in a _significant_ compatibility break so no need to set `partial_implementation:true`
  - change would be to add a note TBD:
    ````
            "firefox": {
              "version_added": true,
              "notes": [
                "From version 82 the inline directive is ignored if the HTML5 'a download' attribute is specified (to match the specification)",
                "Earlier versions respected the header inline directive over the HTML, see <a href='https://bugzil.la/1658877 '>bug 1658877</a>."
              ] 
            },
    ````
- [ ] [Firefox 82 for developers](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#HTTP) - Added, pending final confirmation of first point. 
- [ ] Review: Not yet

**Comment by chrisdavidmills** [comment]
Thanks for the detailed notes @hamishwillee , makes it really easy to follow your work.

I've asked one of our engineers, Anne, to answer your questions in the bug.

the browser compatibility data looks OK; I'd just submit it, and the BCD folks will tell you if they want any change made to the data format.

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills. Ready for review. I have updated https://github.com/mdn/sprints/issues/3733#issuecomment-701933190 above with links to the changes made.

**Comment by chrisdavidmills** [comment]
@hamishwillee this one looks great, nice one Hamish!

**Comment by hamishwillee** [comment]
Great. The BCD entry is in, so I think this is done/complete. @chrisdavidmills I assume you want to close these when you are done with them? Or do you want me to close when I think it is done?

**Comment by chrisdavidmills** [comment]
@hamishwillee in an ideal world, I'd do a formal review process and then close it myself when I'm done, but since I am so busy right now, I'm happy for you to close them ;-)

I'll be reviewing all the bugs for each release version slightly later on anyway, when I come to put together and finalise the release notes, so I'll let you know then if there are any tweaks I think are needed.

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks. Thinking about this I will simply mark the top checkbox as done and leave this open. Because it is probably a little easier for you to check these off as you do final review.

**Comment by chrisdavidmills** [comment]
Reviewed; this looks great, thanks @hamishwillee !
