### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### ISSUE THREAD

**Issue by asbourlotos** [mdn/sprints#3734]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Typo: remove “a” as shown in screenshot: 

![8EA76454-72CD-42FA-A3CA-4DF6C9422928](https://user-images.githubusercontent.com/21349322/94365291-3688e380-0095-11eb-97aa-e4b75ad7f69d.jpeg)

Change 

“the BBC homepage contains “a” many links” 

to 

“the BBC homepage contains many links”

[https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks)

**Comment by chrisdavidmills** [comment]
Fixed; thanks for reporting!
