### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

### ISSUE THREAD

**Issue by santimirandarp** [mdn/sprints#3735]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

This is more of an idea rather. Instead of this code:
```
const select = document.querySelector('select');
const para = document.querySelector('p');
select.addEventListener('change', setWeather);
function setWeather() {
  const choice = select.value;
 ...
}
```

I would write:
```
const select = document.querySelector('select');
const para = document.querySelector('p');
select.addEventListener('change', setWeather);
function setWeather(e) {
  const choice = e.target.value;
 ...
}
```

Not sure if it's right to report it, as it is a matter of taste. 
It can be closed right away.

**Comment by chrisdavidmills** [comment]
@santimirandarp You are absolutely right that you could write it like that. I think the only reason I didn't is that at this stage we haven't really taught events as a dedicated subject, and the version I've used is a bit more obvious/intuitive when you don't know how event objects work.

**Comment by santimirandarp** [comment]
Nice, thank you @chrisdavidmills
