### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/CSS

### ISSUE THREAD

**Issue by asbourlotos** [mdn/sprints#3741]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The Prerequisites section on "Learn to style HTML using CSS" contains some confusing and/or outdated information. See screenshot:

![Screen Shot 2020-09-30 at 3 30 33 PM](https://user-images.githubusercontent.com/21349322/94736689-41ac6f80-0332-11eb-9718-2877ca19609c.png)

The way it's structured states that the **Introduction to HTML** module will contain
- **Introduction to CSS module** (it doesn't, and this has been renamed to "CSS first steps" anyway.
- **JavaScript** (it doesn't)

Please remove the two entries and update the items with the items that are available within the "Introduction to HTML" modules.

https://developer.mozilla.org/en-US/docs/Learn/CSS

**Comment by chrisdavidmills** [comment]
Hi @asbourlotos! Thanks for reporting this; I really don't know how the page ended up like that ;-)

I've edited it to remove the confusion. I think it works much better now.
