### ISSUE TITLE
Access for adding pages in MDN

### ISSUE THREAD

**Issue by codehag** [mdn/sprints#3743]
# Request type

- [X] New documentation
- [ ] Correction or update

# Details
PRIVATE_FIELDS_NOT_SUPPORTED is an error message which we don't have a page for (in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors). The error has been hit 16423 times. I would like to add it but I don't have access. Is there an easy way that contributors can help us with this?

Thanks.

**Comment by chrisdavidmills** [comment]
We could handle this in a variety of ways. I could give you permission to create the page, or I could create the new page and wire it up in the right place, then you could dump some draft content in the page and I could clean it up.

Or we could find a volunteer to help us out, but I don't really have anyone immediately in mind. However saying that, I am just updating our contribution pages in an effort to make these issues much easier to find ;-)

**Comment by codehag** [comment]
For now, either of the first two work for me. Eventually I would like to make this an easy way for people to get involved, but I am not sure exactly how best to do that.

**Comment by chrisdavidmills** [comment]
Cool, that works for me. So, looking at the format of the pages linked at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors#List_of_errors, what title and slug should I give the page?

**Comment by jadjoubran** [comment]
Is this issue resolved now that we have [mdn/content -> Adding a new document](https://github.com/mdn/content#adding-a-new-document) ?

**Comment by chrisdavidmills** [comment]
@jadjoubran the page still needs to be created, and content added. I'm happy to do that still.
