### ISSUE TITLE
Grammar error on Math.random() page

### ISSUE THREAD

**Issue by krankj** [mdn/sprints#3746]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the first JS code demo: Math.random() section, line 12 has a comment "expected output: a number between 0 and 1".

The correction is regarding the usage of word here. 
It should rather be **"expected output: a number from 0 to <1"** since `Math.random() `always returns a value 0 <= x < 1

By definition _between_ does not include either of the end boundaries. 
Eg: _My age is between 20 and 30_ means, I am at least 21 or at most 29, but never 20 or 30.

URL :[ JS MDN Math.random() ]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random)

-kJ

**Comment by chrisdavidmills** [comment]
@krankj thanks for reporting this! The source for this example is at https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/math/math-random.js#L12

Do you fancy fixing this yourself with a simple pull request?

**Comment by krankj** [comment]
Done!

https://github.com/mdn/interactive-examples/pull/1698

**Comment by chrisdavidmills** [comment]
Thanks great, much appreciated!
