### ISSUE TITLE
False positive in null value in number range

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3747]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/CSS/:in-range

## Request type

- [ ] New documentation
- [X] Correction or update

## Details
Empty value is marked as green even if it is not in range, in this case between 1 and 10.

![Screenshot_20201004-183832.png](https://user-images.githubusercontent.com/44380480/95021510-a38e1180-0671-11eb-8976-dfa9043d4f05.png)

**Comment by chrisdavidmills** [comment]
I've added a note to try to address this a bit. I could rewrite the example to work for a more general group of invalid situations, not just out of range, but this is written specifically for demonstrating in-range/out-of-range, so I wasn't sure that woud be a good idea.

**Comment by mattiapontonio** [comment]
@chrisdavidmills thanks. The note is what I was thinking.
