### ISSUE TITLE
Rich-Text editor, a simple correction for the example file

### ISSUE THREAD

**Issue by mhkh8367** [mdn/sprints#3748]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi,
At the bottom of the page "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content#Example_A_simple_but_complete_rich_text_editor", there is a note says: "if you want to see how to standardize the creation and the insertion of your editor in your page, please see our more complete rich-text editor example."
The link for "more complete rich-text editor example" refers to a zip file "https://developer.mozilla.org/@api/deki/files/6243/=rich-text-editor.zip". That zip file should contain a "rich-text editor example", but it just has a form without the least ability of text editing. By submitting the form, page leads to a php page that is not in the zip file!
Is there anything wrong?

**Comment by chrisdavidmills** [comment]
@mhkh8367 You are right, something is wrong here. That zip file example is not helpful at all, so I've just removed it for now. In the future when we've got more time, we'll need to rewrite this page a bit. Closing for now.
