### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

### ISSUE THREAD

**Issue by squelart** [mdn/sprints#3751]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The pages for `let`, `const`, and `var`, only describe the declaration of a naked variable/constant name:
> The names of the variable or variables to declare. Each must be a legal JavaScript identifier.

"identifier" means it's just a name (right?)

After seeing `const { x } = ob;` in the wild, these pages didn't help me understand it. But going through the ECMAScript Language Specification, I finally found out about "destructuring assignment", which has a page on MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

I think all pages that talk about variables/constants should be updated to directly include the destructuring assignment syntax. Or at least point to it near the "legal JavaScript identifier" text, so that people can more easily find it.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types

**Comment by Prerna237** [comment]
Hello @chrisdavidmills . I can pick this task and work on it :)

**Comment by chrisdavidmills** [comment]
@Prerna237 it is yours; thanks so much!

**Comment by Prerna237** [comment]
@chrisdavidmills : The idea of destructuring assignment seems a little advance for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types. What do you think?

**Comment by chrisdavidmills** [comment]
> The idea of destructuring assignment seems a little advanced for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types. What do you think?

Hi @Prerna237 . I don't have a strong opinion here really. The URL you cite is a part of our standard guide, so aimed at intermediate to professional developers, therefore I think it is in scope.

However, there is already a page to cover destructuring. You could just add a note to the page that explains it briefly, and then links to the full page for more details.

**Comment by Prerna237** [comment]
Hello @chrisdavidmills . Was caught up for a while elsewhere. 

Am done with this task. Do let me know if any revisions are required. Thanks :)

**Comment by chrisdavidmills** [comment]
@Prerna237 I've made a few small tweaks, but overall this is looking really good, thanks!

@squelart , does this solve your issue here?

**Comment by squelart** [comment]
Yes, this would certainly have helped me find out about destructuring assignments when I first saw it in a `const` statement. Thank you. 👍

**Comment by chrisdavidmills** [comment]
@squelart great, looks like our work here is done then. I'll close this now, but I think it makes sense for the issue submitter to close it too, if they have verified it fixed.

I've updated the contribution guide to make this a bit clearer: https://wiki.developer.mozilla.org/en-US/docs/MDN/Contribute/Fixing_MDN_content_bugs#How_to_help
