### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/mask-clip

### ISSUE THREAD

**Issue by scheinercc** [mdn/sprints#3752]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example (Examples > Results) does not show in Firefox Dev Edition*, it is just a white field with a select box. Selecting other options doesn't change anything. Tried in Chrome, there is a green field with a purple border.

*Firefox 82.0b6; macOS

https://developer.mozilla.org/en-US/docs/Web/CSS/mask-clip#Result
### Firefox
![image](https://user-images.githubusercontent.com/817856/95161230-52eff300-07ee-11eb-96ff-1ee89061b3bd.png)
### Chrome
![image](https://user-images.githubusercontent.com/817856/95161245-5e431e80-07ee-11eb-92fe-c4db1ce2d5fa.png)

**Comment by rachelandrew** [comment]
@chrisdavidmills this is a CORS issue, that's why the image isn't loading. Is there somewhere else to load the image from?

**Comment by chrisdavidmills** [comment]
@rachelandrew I'd create a new version of the example on GitHub, on the css-examples repo, and then embed it using the macro, like we did for the learning area and grid examples. That'd fix it.

**Comment by rachelandrew** [comment]
I have created this in css-exmples, which also means I can include the -webkit prefixed versions as well, so this will work for Chrome browsers: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/mask-clip#Examples
