### ISSUE TITLE
https://wiki.developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

### ISSUE THREAD

**Issue by oleksandrstarov** [mdn/sprints#3753]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Page> russian version, code example  with header:
_**Пример: Реализация класса WeakMap-like классов с методом .clear()**_

part:
`clear() {
        this._wm = new WeakMap
    }`

brackets are missing :

`clear() {
        this._wm = new WeakMap()
    }`

https://wiki.developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

**Comment by oleksandrstarov** [comment]
Same for ca, es locales

**Comment by chrisdavidmills** [comment]
Apologies, but we just don't have the bandwidth to maintain translations. You are more than welcome to edit these articles yourself.

**Comment by chrisdavidmills** [comment]
Apologies, but we just don't have the bandwidth to maintain translations. You are more than welcome to edit these articles yourself.
