### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/setTransform

### ISSUE THREAD

**Issue by dindy** [mdn/sprints#3754]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the french version of CanvasRenderingContext2D.setTransform() documentation, parameters description is not correct. `b` and `c` are inverted.

https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/setTransform

**Comment by chrisdavidmills** [comment]
Hi @dindy !

My apologies, but I'm afraid we don't have the bandwidth to maintain translations. You are more than welcome to edit the page yourself; let me know if you want some help to do so.
