### ISSUE TITLE
Spanish translation of cite element is outdated

### ISSUE THREAD

**Issue by jagobabarron** [mdn/sprints#3755]
## URL(s)

https://developer.mozilla.org/es/docs/Web/HTML/Elemento/cite

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

The spanish translation of the cite element is outdated, it explains the semantics this element had back in HTML 4.01. It doesn't match the english version, which is up to date with the HTML spec.

**Comment by chrisdavidmills** [comment]
My apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit/update it yourself.

**Comment by jagobabarron** [comment]
I'm sorry, I didn't know I could do it myself.

**Comment by chrisdavidmills** [comment]
No worries! You just need to sign up for an MDN account, and then you can choose to edit the page source. Feel free to ask if you need some help.
