### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by DhairyaBahl** [mdn/sprints#3756]
# Misspelled word

Correction or update

# Details

On the page : https://firefox-source-docs.mozilla.org/setup/windows_build.html
Under Section => Build-Firefox 

https://user-images.githubusercontent.com/71627983/95242045-48544e80-082c-11eb-970d-d3502fdd2cee.jpg

Here Mercuial Must be written as Mercurial

**Comment by chrisdavidmills** [comment]
Hi @DhairyaBahl,

This repo is for submitting bugs related to documentation on https://developer.mozilla.org — we have nothing to do with the Firefox source docs.

They probably have somewhere to submit documentation bugs, but I don't know where that is...
