### ISSUE TITLE
Thoughts on adding direct-links to heading tags within article content?

### ISSUE THREAD

**Issue by tannerdolby** [mdn/sprints#3757]
## URL(s)
[Content Categories - MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories)

## Request type

- [x] Correction or update

## Details

Hello, MDN team. I'm not so sure this is an issue or problem but something I wanted to ask your team about. 

I originally noticed it on this page [Content Categories - MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) but I think it applies to all pages within `/docs/Web/`. I wanted to click on the section heading, [Palpable content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Palpable_content) to get a direct link to this section without having to scroll down from [Content Categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Main_content_categories). I inspected the page and copied the corresponding id selector `#Palpable_content` and pasted it to the end of the page URL to provide a "direct-link" to that sections content.

I do recognize the "On this page" section containing direct links to main headings of the page in that unordered list which is very helpful. But for sections with more content that require the user to scroll further down the page, this is where I think potentially having direct links on some of the subheadings in long categories could be useful for people sharing links to specific sections within MDN docs.

### Proposed update: 
1. Create direct links for section headings that are further down from the "On this page" direct links. Allowing for a direct link to that section heading to be produced in the browsers address bar upon clicking the `.direct-link` element nested in the heading for fast internal linking. I used the hashtag character as the anchors value (which could also be an SVG if there is a specific icon wanting to be used) within the direct link screen shot I attached below.

The `.direct-link` anchor elements could be fully visible or visually hidden from the screen with good ole `visibility: hidden` or potentially a fancier way of visually hiding using absolute positioning and translate. 

The `.direct-link` element could then become visible upon hovering the heading element and allow for a quick click to update the page URL with a direct link to that specific section heading.

```
<h3 id="Palpable_content">Palpable content <a class="direct-link" href="https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Palpable_content">#</a></h3>
```

## Screenshot with direct link visible for Palpable content heading: (no styling or margins currently applied)
<img width="708" alt="Screen Shot 2020-10-06 at 4 02 18 PM" src="https://user-images.githubusercontent.com/48612525/95269038-6c446f80-07ed-11eb-98e6-11cf0c4c73b1.png">

Let me know your thoughts!

**Comment by chrisdavidmills** [comment]
Hi @tannerdolby !

Yes, I agree this would be nice, and in fact we did have this at some point, but I think it was disabled in the "viewer" front-end because of some kind of performance reason. If you look at the "wiki"/"edit" version of the page (https://wiki.developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories), you'll see the feature active there.

I think it'd be good for us to have this feature sorted out again at some point soon in the final UI, therefore I'm going to move your issue over to the platform (kuma) repo so I can add your voice to the discussion. Thanks for speaking up.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7546](https://github.com/mdn/kuma/issues/7546) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tannerdolby** [comment]
Hey, Chris. Ok great. I had a look at the [wiki/edit](https://wiki.developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) version of the page and noticed the direct link feature there. That's exactly what I was thinking of.

I agree, and sounds good. I will make sure and head over to the kuma repo to stay up to date on [mdn/kuma #7546](https://github.com/mdn/kuma/issues/7546).
