### ISSUE TITLE
so stupid using mouse to set gain why not put in a fkin button like normal ppl?>

### ISSUE THREAD

**Issue by jamieduk** [mdn/sprints#3759]
so stupid using mouse to set gain why not put in a fkin button like normal ppl? up arrow button and down arrow button an in the center between both buttons that are on top of each other call it gain with a label / title! idiot! now redo it and publish as a real working draft! reply when done!

**Comment by butimo** [comment]
Hi Jay,
no worries. Feel free to do better. You do not have to use it, if you don't like it.

**Comment by chrisdavidmills** [comment]
@jamieduk I don't know what code or demo you are referring to, but I'm not going to dignify this with a helpful response. Have a think about how you could have communicated better, in time for the next occasion that you decide to reach out to us.
