### ISSUE TITLE
Firefox 63 JavaScript DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#376]
# User story
As a web developer, I want to learn about the new JavaScript features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

- [x] All DDNs complete.
- [x] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items

1. - [x] [Remove SIMD.js](https://bugzilla.mozilla.org/show_bug.cgi?id=1416723) [1 point]
2. - [x] [Implement Object.fromEntries](https://bugzilla.mozilla.org/show_bug.cgi?id=1469019) [1 point]

## Smaller items bundled together

Total points: 1

1. - [x] [Rename Atomics.wake to Atomics.notify per ES standard change](https://bugzilla.mozilla.org/show_bug.cgi?id=1470490)
2. - [x] [Implement Symbol.prototype.description proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1472170)
2. - [ ] [Improve the error message produced when a user attempts to access a property of [something that evaluated to] undefined.](https://bugzilla.mozilla.org/show_bug.cgi?id=1259822)

**Comment by Elchi3** [comment]
This got done, see https://bugzilla.mozilla.org/show_bug.cgi?id=1416723#c22 and https://github.com/mdn/kumascript/pull/761 (pending deployment, but I think that's minor).

**Comment by Elchi3** [comment]
I think it might make sense to wait a bit before documenting https://bugzilla.mozilla.org/show_bug.cgi?id=1259822 as it impacts web compatibility and might be backed out. See https://bugzilla.mozilla.org/show_bug.cgi?id=1490772. I'm following both bugs and will see what will happen.

**Comment by chrisdavidmills** [comment]
OK, makes sense. In this case, it might make sense to remove this DDN from this card so you can close it again, and then file this new one as a separate issue, which you can work on at some point later when it make sense.

**Comment by Elchi3** [comment]
This is done now.
