### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

### ISSUE THREAD

**Issue by sirgregalub** [mdn/sprints#3760]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Array.prototype.reduceRight() has a typo in the description.

![Screen Shot 2020-10-07 at 8 10 21 AM](https://user-images.githubusercontent.com/38589154/95335102-955c1300-0874-11eb-8776-466507102ee9.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by chrisdavidmills** [comment]
@sirgregalub fixed; thanks for reporting!
