### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

### ISSUE THREAD

**Issue by cor3000** [mdn/sprints#3763]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

the section on redirect is a bit misleading (at least sounds promising something it actually doesn't provide):

> redirect
> The redirect mode to use: follow (automatically follow redirects), error (abort with an error if a redirect occurs), or manual (**handle redirects manually**). In Chrome the default is follow (before Chrome 47 it defaulted to manual).

comparing it the actual standard (https://fetch.spec.whatwg.org/#requests) making clear it's not actually useful in the way it sounds:

> "manual"
> Retrieves an opaque-redirect filtered response when a request is met with a redirect, to allow a service worker to replay the redirect offline. The **response is otherwise indistinguishable from a network error**, to not violate atomic HTTP redirect handling.

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

**Comment by jchimene** [comment]
I'll take a look!

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1518](https://github.com/mdn/content/issues/1518) via [**ZenHub**](https://www.zenhub.com/)
