### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Games/Techniques/3D_on_the_web/Building_up_a_basic_demo_with_Three.js

### ISSUE THREAD

**Issue by prettyboyheaven** [mdn/sprints#3765]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details

[osgjs.org](https://osgjs.org/) link to the content 21+

https://developer.mozilla.org/ru/docs/Games/Techniques/3D_on_the_web/Building_up_a_basic_demo_with_Three.js
![image](https://user-images.githubusercontent.com/28684046/95483164-933ea500-0997-11eb-9417-cd782f5d20a8.png)
![image](https://user-images.githubusercontent.com/28684046/95483476-ef092e00-0997-11eb-985e-fb8677647491.png)

**Comment by chrisdavidmills** [comment]
Removed; thanks for reporting.
