### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous

### ISSUE THREAD

**Issue by VanOxy** [mdn/sprints#3767]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link for the "Making asynchronous programming easier with async and await" section is set to 
https://developer.mozilla.org/rudocs/Learn/JavaScript/Asynchronous/Async_await

It should be 
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Async_await
![image](https://user-images.githubusercontent.com/5168848/95521936-16c5b980-09cb-11eb-9e94-bbaeefdd95e6.png)

**Comment by sideshowbarker** [comment]
Thanks for catching that and reporting. I made a change to fix it — so if that resolves this issue to your satisfaction, please go ahead and close the issue.
