### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Объекты

### ISSUE THREAD

**Issue by VanOxy** [mdn/sprints#3768]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Links into following headers doesn't respect language policy. It's like following
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

Should be 
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Objects/Object_prototypes

![image](https://user-images.githubusercontent.com/5168848/95530782-0ddee300-09df-11eb-85ac-6a4ea25505ab.png)
![image](https://user-images.githubusercontent.com/5168848/95530834-2d760b80-09df-11eb-856c-20acaaf54830.png)

**Comment by chrisdavidmills** [comment]
Hi there. My apologies, but we don't have the bandwidth to maintain translations. You are very welcome to edit the page yourself (let me know if you need some help with that)

**Comment by VanOxy** [comment]
Yeah I'd like to have some help with that.
Should I be first a part of MDN community? Thx

**Comment by chrisdavidmills** [comment]
@VanOxy there is not much that you need to do to get started; we welcome anyway to help, and you don't need to join a community in any official way. I recently updated the Contribute docs to explain how to get start: https://wiki.developer.mozilla.org/en-US/docs/MDN/Contribute

This page provides specific help on how to fix content bugs like this one: https://wiki.developer.mozilla.org/en-US/docs/MDN/Contribute/Fixing_MDN_content_bugs
