### ISSUE TITLE
Wrong syntax used in inline Object literal example

### ISSUE THREAD

**Issue by krankj** [mdn/sprints#3770]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under **Object member summary** [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance#Object_member_summary), the 4th point includes an example at the end:
_`let teacher1 = { name = 'Chris' }` and then teacher1.name_

It wrongly uses` { name = 'Chris' }` for an object literal, whereas it should be **`{ name : 'Chris' }`**

PR: https://github.com/mdn/content/pull/42

[Link](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance#Object_member_summary)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this; I think I've fixed this line correctly now. There was a mistake in the constructor version too...

**Comment by krankj** [comment]
That was quick! 👌
