### ISSUE TITLE
'static' keyword could be used for properties too

### ISSUE THREAD

**Issue by krankj** [mdn/sprints#3771]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[This](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) page mentions that:
_The static keyword defines a static method for a class_.

It misses out mentioning that the `static` keyword is applicable to **properties** as well, throughout the page.

Similar explanation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods) provides a sense that `static` keyword could be used for methods _only_.

In addition to having static methods in classes, the following example indicates that static properties are valid too: 
```
class Square { 
  constructor(side) {
    this.side = side;
}
static name = "CustomSquare"; 
static foo = "bar"; 
}

let sq = new Square(10);
sq.name; // returns undefined
sq.someProperty; // returns undefined
Square.name; //  returns "CustomSquare"
Square.foo // returns "bar"
```
The above mentioned [page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) needs to update its examples to include static properties too.

I could add them :)

-kJ

**Comment by chrisdavidmills** [comment]
@krankj looks like you are right; I'd be happy for you to add some content to cover this. Let me know if you need any help at all, or a review. I do wonder whether it was written like this because static methods and properties were supported in browsers at different times?

**Comment by krankj** [comment]
Ah, ok!
I will update the interactive example [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) to include the static property. 
But what about updating the content? I guess you mentioned that they all lie in a MySQL Database.

The following pages I have come across need to be updated:

1. [Classes - Static Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods) - Requires content and example code to be updated.
2. [Classes - Static keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) - Requires content, live example and example code to be updated.

**Comment by krankj** [comment]
@chrisdavidmills I have edited the wiki for:

[Classes - Static Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods) and [Classes - Static keyword](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)
 
[PR](https://github.com/mdn/interactive-examples/pull/1699) for code example.

A quick review would help.

-kJ

**Comment by sideshowbarker** [comment]
> [Classes - Static Methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods) and [Classes - Static keyword](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)

I reviewed those changes and they look great

> [PR](https://github.com/mdn/interactive-examples/pull/1699) for code example.

That looks great too, except that the code style requires the use of single quotes for string values; double quotes will trigger an error for the project code-style linter; see https://travis-ci.org/github/mdn/interactive-examples/builds/734582177#L229

**Comment by krankj** [comment]
@sideshowbarker Thanks for the review.

**Comment by chrisdavidmills** [comment]
I've had a look at your changes too @krankj , and they are really great. Thanks so much for your hard work on this!

And thanks to @sideshowbarker too for helping with the review.

**Comment by krankj** [comment]
@chrisdavidmills You are most welcome 👍🏼
