### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

### ISSUE THREAD

**Issue by janwybe** [mdn/sprints#3774]
# Request type

- [ ] New documentation
- [ ] Correction or update
- [x] Attempt to find out why Safari is not displaying a simple HTML code example from Github correctly

# Details

Hi, 

First of all, thanks and compliments for the Mozilla HTML course which I have started following a few days ago. 

This morning (Sunday October 11, 2020), I started with the section "Document and website structure" and started learning about the basic sections of a document, such as the header, the navigation bar, main content, the sidebar and the footer. 

When I got to the Active learning part, I downloaded the code example from the GitHub repository:

https://github.com/mdn/learning-area/blob/master/html/introduction-to-html/document_and_website_structure/index.html

I copied and pasted the HTML code to a Sublime document, which I then saved to a local folder on my Mac. 

Upon opening the document with Safari, what I got to see was a simple text which did differentiate between Headers and Paragraphs, but which otherwise did not display structural elements such as a header or a navigation bar. 

So far, I've not yet been able to find out whether I've done something wrong, or whether something might be the matter with using Safari to open example HTML documents. 

Thanks in advance,

Warm regards,

Jan Wybe Oosterkamp

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
![Mozilla MDN - Document and website structure - Basic secionts of a document - header - navigation bar - main content - sidebar - footer - sample-website - Active learning - code from Github](https://user-images.githubusercontent.com/72682263/95671308-a15a1480-0b95-11eb-852e-93e388ab10a2.jpg)
![Mozilla MDN - Document and website structure - Basic secionts of a document - header - navigation bar - main content - sidebar - footer - sample-website - Active learning - code from Github - This is what it looked like on Safari](https://user-images.githubusercontent.com/72682263/95671310-a8812280-0b95-11eb-9a9f-f81681d4a37c.jpg)

**Comment by chrisdavidmills** [comment]
Hi @janwybe !

Thanks for getting in touch, and I hope you are finding our content useful!

So to be clear, structural elements like header, nav, section, etc. are not styled in any way by default. They do provide useful semantics that are good for accessibility, but to style them you've got to provide your own CSS.

In this example, the HTML page references a CSS file (see the link element on line 8). This can be found at https://github.com/mdn/learning-area/blob/master/html/introduction-to-html/document_and_website_structure/style.css

Save this in same directory as your HTML file and you see clearer styling of the structural elements.

**Comment by janwybe** [comment]
Thanks for your kind and helpful response, @chrisdavidmills !

After having followed your instruction, the page opened correctly. Then, when I went over de page again to see whether I had missed it somewhere, I realised that I had been getting ahead of myself and that CSS only comes later in the course. 

And yes, I'm finding your content most useful; I'm enjoying the course a lot!

Thanks again - Jan Wybe.

**Comment by chrisdavidmills** [comment]
@janwybe always glad to help. 

Yeah, it was hard to write this course — HTML and CSS are two separate disciplines, but they are so closely related that you can't help but include parts of them in each other's courses. For now, the important thing is to know that you don't have to know CSS right now in the HTML course, but it does help ;-)
