### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet

### ISSUE THREAD

**Issue by jakekre8** [mdn/sprints#3775]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Min frequency value in description does not match that in code snippet (missing decimal).

Description text says:
> The second parameter is named frequency and defaults to 440.0, with a range from 275 to 4186.009, inclusively.

While the code snippet says:
`{
      name: "frequency",
      defaultValue: 440.0;
      minValue: 27.5,
      maxValue: 4186.009
    }`

![image](https://user-images.githubusercontent.com/48039785/95673659-545a5a80-0bf6-11eb-94b2-9a2b7330d1f6.png)

URL:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet#Supporting_audio_parameters

**Comment by hamishwillee** [comment]
Thanks very much. I added the decimal point in the text. If you see issues where you're sure of the solution feel free to fix yourself. As long as you add an explanation in the comment so it is obvious why the change was made we'll be eternally grateful :-)
