### ISSUE TITLE
"The desktop version of Android, however, does not support HLS"

### ISSUE THREAD

**Issue by Sean4u** [mdn/sprints#3776]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

sentence before starts "Firefox for Android does", so shouldn't this be "The desktop version of Firefox, however, ..."?

https://developer.mozilla.org/en-US/docs/Web/Media/Streaming

**Comment by fredster33** [comment]
This seems already fixed.

**Comment by krankj** [comment]
@fredster33 It doesn't look like it is yet.

**Comment by krankj** [comment]
I've updated the wiki now.

**Comment by krankj** [comment]
I've updated the wiki. Thanks @Sean4u for the heads up.

**Comment by chrisdavidmills** [comment]
Perfect fix, thanks @krankj
