### ISSUE TITLE
Grammar error 

### ISSUE THREAD

**Issue by krankj** [mdn/sprints#3777]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Although this issue is trivial, it does need a minor correction:

In [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Binding_this_with_prototype_and_static_methods) page, under _Binding this with prototye and static methods_, after the first example, the line reads:
"_If we rewrite the above using traditional function-based syntax in non–strict mode, then this method calls **_is_** automatically bound to the initial this value,..._"

It must rather be: "then this method calls _**are**_ automatically bound..."

-kJ

**Comment by hamishwillee** [comment]
Thanks - you're absolutely right. Can you make the correction? (this is a wiki, so you're welcome to fix problems if you're sure of your solution).

**Comment by fredster33** [comment]
I'd just like to say that I just edited the wiki to fix the problem.

**Comment by hamishwillee** [comment]
Thank you very much!
