### ISSUE TITLE
Developer Guide capitalization

### ISSUE THREAD

**Issue by fredster33** [mdn/sprints#3778]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Under the table for the section "What skills do I need", iOS is capitalized incorrectly. It currently displays iOs, but it should be corrected to iOS.

Here is the URL:
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction#What_skills_do_I_need

A screenshot: 

![Screenshot of page](https://user-images.githubusercontent.com/64927044/95689764-d67f5a80-0bc7-11eb-8940-35971f839953.png)

On the picky side, I would also say that Javascript should be corrected to JavaScript, according to the capitalization [here.](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

Thanks!

**Comment by hamishwillee** [comment]
@fredster33 Cool. This is a wiki, so if you see things that are obviously incorrect just log in an fix them. I did this case :-)

**Comment by fredster33** [comment]
Thanks 👍
