### ISSUE TITLE
Discord Developers Portal problem

### ISSUE THREAD

**Issue by DevAndriev** [mdn/sprints#3780]
After proceeding to https://discord.com/login?redirect_to=%2Fdevelopers%2Fapplications, the screen starts to flash

**Comment by fredster33** [comment]
Can you please include the link in which you followed?

**Comment by xdorxble** [comment]
It is right there.

**Comment by xdorxble** [comment]
https://discord.com/login?redirect_to=%2Fdevelopers%2Fapplications

**Comment by chrisdavidmills** [comment]
Hi there,

This hasn't got anything to do with MDN content, so I'm going to close this. I'd suggest you find out how to contact the Discord developers about this problem.
