### ISSUE TITLE
Examples of using Atomics has wrong return value comment

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3782]
@Zavtramen commented on [Mon Oct 12 2020](https://github.com/mdn/kuma/issues/7550)

# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics

# Details

Examples of using Atomics has wrong return value comment:
```
Atomics.compareExchange(ta, 0, 5, 12);
Atomics.load(ta, 0); // 12
```
result here should be 1, not 12, cause previously stored value is 1 not 5
and, another one:
```
Atomics.store(ta, 0, 12); // 12

Atomics.sub(ta, 0, 2);
Atomics.load(ta, 0); // 3
```
result here should be 10, not 3

and where is another error with 'or'
examples should be revised

**Comment by mikoMK** [comment]
I corrected the return value comments and added some more for clarfication.

**Comment by chrisdavidmills** [comment]
Fixes look good; thanks @mikoMK !
