### ISSUE TITLE
Sorting tables

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3783]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

## Request type

- [X] New documentation
- [ ] Correction or update

## Details
Explain that there are no native methods for sorting the `tr` of a `tbody` or `thead` or `tfoot` and eventually provide a kind of Vanilla solution to this issue.
For reference now I know this solution for sorting an `HTMLCollection` preserving event listeners.
https://jsfiddle.net/p0v9uowr/1/
I will come back if I will have a good complete solution.
Extra note: should be good if the logic of sorting is the same ad `Array.sort` so with an optional callback function that passes `tr` to be compared.

Best regards

**Comment by mattiapontonio** [comment]
This solution works in my local env (Chrome)
https://gist.github.com/mattiapontonio/41ba0e2ab2ab04b130aff1edbc2d0969

**Comment by chrisdavidmills** [comment]
@mattiapontonio I'd be happy to add a sorting example into the Examples section of this page — it's a fun and often requested technique. Would you be willing to add the example into the page yourself?

**Comment by mattiapontonio** [comment]
I'll try.

**Comment by chrisdavidmills** [comment]
Thanks! Feel free to ask if you need some help.

**Comment by mattiapontonio** [comment]
![image](https://user-images.githubusercontent.com/44380480/95768729-17a26800-0cb7-11eb-9ea2-1a530410fec6.png)

Actually mdn.mozillademos.org refused to connect.
I'm investigating.

**Comment by mattiapontonio** [comment]
@chrisdavidmills can i preview EmbedLiveSample or has to be published?
Here  the draft code:
```
<h2>Sorting</h2>

<h3 id="Sorting_rows">Sorting rows</h3>

<p>There are no native methods for sorting the th of a tbody, thead or tfoot. You can sort an&nbsp;<code>HTMLCollection</code>&nbsp;preserving event listeners using <code>Array.prototype.slice()</code>, <code>Array.sort()</code>,&nbsp;<code>Node.removeChild()</code>,&nbsp;<code>Node.appendChild()</code>.</p>

<p>The sorting function can be an event handler, for example, <code>onclick</code> on a <code>th</code>.</p>

<h4>HTML</h4>

<pre class="brush: html">
&lt;table&gt;
  &lt;tbody&gt;
    &lt;tr&gt;
      &lt;td&gt;3&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;2&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;1&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/tbody&gt;
&lt;/table&gt;
</pre>
<h4>JavaScript</h4>
<pre class="brush: js">
HTMLTableSectionElement.prototype.sort=function(cb){
        Array
            .prototype
            .slice
            .call(this.rows)
            .sort(cb)
            .forEach((e,i,a)=&gt;{
                this.appendChild(this.removeChild(e));
            },this);
    }
    const callback = function(a, b){
        return a.textContent.localeCompare(b.textContent);
    }
    document.querySelector('table').tHead.sort(callback);
    document.querySelector('table').tBodies[0].sort(callback);
    document.querySelector('table').tFoot.sort(callback);
</pre>
<h4>Result</h4>
<p>{{EmbedLiveSample('Sorting_rows', '100%', '700', '', 'Web/HTML/Element/table')}}</p>
```

**Comment by mattiapontonio** [comment]
@chrisdavidmills ok I've published the text / sample.
I still can't show this Sample in a result section.
https://mdn.mozillademos.org/en-US/docs/Web/HTML/Element/table$samples/Sorting_rows
Can You please take a look?

**Comment by mattiapontonio** [comment]
@chrisdavidmills Ok,my contrib is Ok for now.
Thanks.
https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/table

**Comment by chrisdavidmills** [comment]
Thanks @mattiapontonio — these examples are really good. I've moved the section to be a subsection of the Examples section, copy edited it a bit, and wired up the live sample embeds so they work. I'm really pleased with this; have a read through to make sure you are happy with everything I've done.

**Comment by mattiapontonio** [comment]
@chrisdavidmills everiting fine. Thanks for Your native editing 🙂👍👌

**Comment by chrisdavidmills** [comment]
@mattiapontonio you're welcome! Thanks for your excellent content ;-)
