### ISSUE TITLE
Object.seal() interactive example is incorrectly titled — it is a static method, not an instance method.

### ISSUE THREAD

**Issue by adamjaro99** [mdn/sprints#3785]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the first code example, the title says: _JavaScript Demo: Object.prototype.seal()_, but it's wrong, because `Object.seal()` isn't on the `Object` prototype, it is on the `Object` constructor function.

**Screenshot:**
![object_seal](https://user-images.githubusercontent.com/47431853/95761815-2126d280-0cad-11eb-8a94-2a98ae2bb20c.png)

**Comment by chrisdavidmills** [comment]
Thanks for pointing this out @adamjaro99.

The actual example code is contained in https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/object/object-prototype-seal.js

The metadata for the example is here: https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/object/meta.json#L123

1. The short fix would just be to change the pge title in the metadata. 
2. However, the example code file is also named incorrectly, so a more complete fix would be to correct this and also then fix the references to it in the metadata, and the metadata member name. 

Would you be willing to submit a PR to fix these? ;-)

**Comment by chrisdavidmills** [comment]
Related MDN reference page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal

**Comment by adamjaro99** [comment]
Thank you for your hints, I'm working on it! :)

**Comment by adamjaro99** [comment]
Pull request created: [pr](https://github.com/mdn/interactive-examples/pull/1702). :)

**Comment by chrisdavidmills** [comment]
Perfect, thanks @adamjaro99 !

**Comment by adamjaro99** [comment]
> 
> 
> Perfect, thanks @adamjaro99 !

I visited the page once again, and the live example page is missing. This probably happned because the name of the generated HTML file had not been updated. Should I open a new issue for this?

Error message:
<img width="689" alt="object_seal" src="https://user-images.githubusercontent.com/47431853/95985089-720d0700-0e24-11eb-9db1-6c7500f89700.png">

**Comment by chrisdavidmills** [comment]
@adamjaro99 ah, thanks for pointing that out! Yes, because you changed the name of the example, the reference to it on the page was then wrong. I've updated it now, so it works!
