### ISSUE TITLE
<datalist> styling

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3786]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

## Request type

- [X] New documentation
- [ ] Correction or update

## Details
- Note about the fact that datalist and options are platform dependant and less customizable than others elements.
- Add label attribuite to the example
- Vanilla Custom implementation...?

**Comment by mattiapontonio** [comment]
Added Customize section.
https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by mattiapontonio** [comment]
Mention
https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms
https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

**Comment by sideshowbarker** [comment]
> Added Customize section.
> https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

I reviewed what you added there, and made some follow-up copy edits to it. It looks great to me. 👍

**Comment by chrisdavidmills** [comment]
Wonderful work, thanks @mattiapontonio ! I've improved the styling a bit, rekigged the HTML slightly, improved formatting, and added a bit more explanation. Let me know if you are happy with it.

**Comment by mattiapontonio** [comment]
@chrisdavidmills yes I am 👌🙏

**Comment by diegolsarmiento** [comment]
Not sure is me, but the styled datalist doesn't allow selecting an element from the list (there is no value for `this.value`).
