### ISSUE TITLE
getBoundingRect example error

### ISSUE THREAD

**Issue by AfonsoTsukamoto** [mdn/sprints#3788]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The `getBoundingRect` example is showing all values as 0. 

Print of the error: 
![Screenshot 2020-10-14 at 13 54 20](https://user-images.githubusercontent.com/999374/95945566-b51baa00-0e25-11eb-8c22-b84dbcc6ab5a.png)

Pen with an example of the right results: https://codepen.io/afonsotsukamoto/pen/qBNOvOz

Console error: 
`getBoundingClientRect:71 The PerformanceObserver does not support buffered flag with the entryTypes argument.`

Browser: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
Seems to work fine on Safari 

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by chrisdavidmills** [comment]
Hi @AfonsoTsukamoto !

I've just tested this example, and it seems to work fine across the browsers I've got available. What browser did you have this problem on?

**Comment by AfonsoTsukamoto** [comment]
Hi Chris, 

I updated the issue description with my browser version and the console error.

I just tested in incognito to ensure the error persists and it is actually more complicated than I thought - navigating to the [page](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) will show the correct results, but if I reload the page, the results will be all 0 again:
![mdn](https://user-images.githubusercontent.com/999374/95974902-78b17380-0e50-11eb-9727-b2a19565ddd4.gif)

The same happens without incognito. 
Also tried Chrome Canary [Version 88.0.4291.2 (Official Build) canary (x86_64)] and Safari [Version 13.1.2 (15609.3.5.1.3)] -  but both worked fine ¯\_(ツ)_/¯

It doesn't look like a big issue, more like a corner case, but in my initial visit it was happening all the time so I thought it was worth reporting. 

Thanks Chris

**Comment by chrisdavidmills** [comment]
@AfonsoTsukamoto ah, now you've said that, I can reproduce it — loads OK the first time on Chrome, but then when you refresh it it returns zeroes. This is really weird!

And I'm not really sure what to do about it. IT just seems to happen on Chrome,not Fx/Safari, so perhaps a Chrome bug?
