### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices

### ISSUE THREAD

**Issue by winklerrr** [mdn/sprints#3790]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

## Problem

In the first paragraph of the localization best practices ([Note on localizers](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Note_on_localizers)), it says at the end:

> VCS systems

but VCS stands for `version control system` and already has the word `system` included. So written-out it actually says:

> version control system systems

which makes no sense unless the text is really referring to systems of version control systems but I doubt that.

## Suggested solution

Replace that part with:

> version control systems (VCSs)

**Comment by chrisdavidmills** [comment]
@winklerrr thanks for reporting. I've fixed this now.
