### ISSUE TITLE
Custom <select> Component for styling

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3791]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

## Request type

- [X] New documentation
- [ ] Correction or update

## Details
Provide a custom basic vanilla workaround example for customizing the style of the select element.
A similar approach as done here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

## Sub issues

- [X] Adding a bit of description on how it works. 
- [x] Fixing the width of the select to be as wide as the widest option. Currently, when you select the shortest option, the overall box changes to be as wide as that one, and the wider options get cut off.
- [ ] Is <datalist> the correct element for the list?
- [ ] Fixing the issue whereby you have to click twice to select an option in the drop-down in Firefox (it works in Chrome ;-) )
- [x] Looking at keyboard accessibility — this solution is currently not keyboard accessible at all.
- [x] Looking at making it so that you can close the options list again by clicking the select itself.
- [ ] No multiselect supported
- [ ] No optgroup supported
- [ ] Probably others features are not supported
- [ ] Mention Web Components?

**Comment by mattiapontonio** [comment]
I've edited the page with a custom solution possible similar to the native.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
https://github.com/mattiapontonio/select/blob/main/index.html

**Comment by chrisdavidmills** [comment]
Hi @mattiapontonio !

Thanks again for another great example. I've moved it to be part of the examples section, improved the formatting a bit, and added a little bit of description at the top.

I was wondering if you could look at:

* Adding a bit of description on how it works. The addition of the `<datalist>` element via JS is interesting; I also wonder how accessible that is.
* Fixing the width of the select to be as wide as the widest option. Currently, when you select the shortest option, the overall box changes to be as wide as that one, and the wider options get cut off.
* Fixing the issue whereby you have to click twice to select an option in the drop down in Firefox (it works in Chrome ;-) )
* Looking at keyboard accessibility — this solution is currently not keyboard accessible at all.
* Looking at making it so that you can close the options list again by clicking the select itself.

**Comment by mattiapontonio** [comment]
I don't know of this can scale 🙂
I'm joking. Thank You, yes I Will look at It.

**Comment by chrisdavidmills** [comment]
> I don't know if this can scale 🙂
I'm joking. Thank You, yes I Will look at It.

It's all good ;-)

Obviously, there's no tight timescale for this, just some things to think about to make it even better.

**Comment by mattiapontonio** [comment]
- [X] Adding a bit of description on how it works. 
- [ ] The addition of the <datalist> element via JS is interesting; I also wonder how accessible that is. @chrisdavidmills seems be the permitted parent for the option. Which is the issue? Even I was not really sure about using it.
- [X] Fixing the width of the select to be as wide as the widest option. Currently, when you select the shortest option, the overall box changes to be as wide as that one, and the wider options get cut off.
- [ ] Fixing the issue whereby you have to click twice to select an option in the drop down in Firefox (it works in Chrome ;-) )
- [ ] Looking at keyboard accessibility — this solution is currently not keyboard accessible at all.
- [ ] Looking at making it so that you can close the options list again by clicking the select itself.

**Comment by mattiapontonio** [comment]
@chrisdavidmills new editing. I will improve the solution.
I want to better  explain my goal:
Why use select and add via JS? A want a standard initial DOM and do not force backend to serve my custom structure. I want to stay "connected" with forms features and others, reinvent the weel less possible, just be ok with designers that want rounded corners, transitions, and stuff like that :)

**Comment by chrisdavidmills** [comment]
I've had another look at this, and it works pretty well now, @mattiapontonio . The main things for me were keyboard accessibility and maintaining a fixed width. I think this is good enough to leave as is for now, although I'm obviously not going to stop you for adding more improvements!

**Comment by mattiapontonio** [comment]
@chrisdavidmills thank You.
Deployed this: https://github.com/mattiapontonio/select/tree/0.0.1
