### ISSUE TITLE
Responsive <table>

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3792]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

## Request type

- [X] New documentation
- [ ] Correction or update

## Details
Provide an example for the CSS needed to made the table fit the parent and scroll orizzontally.

Note: think It can be done with no wrappers.
Note about the fact that for hiding scrollbar use the rule in a media query.

**Comment by mattiapontonio** [comment]
https://stackoverflow.com/a/30423904/3579536

**Comment by brookjordan** [comment]
Hey, how would I go about picking this up?

**Comment by chrisdavidmills** [comment]
Hi @brookjordan !

You get assigned to an issue by just asking in the issue,and then we can assign you to it. I've already done that, so we are all good there.

One thing though — the interactive examples are only for the examples that appear at the top of each page, and we can only have one of those per page. Your example looks good, but we'd like it added to the page as a regular live example. See this page, for example https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Examples, and view the source to see how it's handled.

Let me know if you have any more questions.

**Comment by mattiapontonio** [comment]
I'm not sure about that but maybe You have to specify the responsive meta tag in the sample so You have to put all the HTML in the `pre` for HTML.

**Comment by brookjordan** [comment]
How does this look?
There are a lot of rows and columns so I’ve hidden the HTML.
https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/table

**Comment by chrisdavidmills** [comment]
@brookjordan this is looking really nice, thanks for the great work!

I've tweaked the wording of the explanation a little bit, and moved the example to inside of the "Examples" section, as I felt tht its purpose goes beyond traditional accessibility concerns, into usability, layout, etc.

@mattiapontonio , do you have any other thoughts on this one? If not, then I think we can close it.

**Comment by mattiapontonio** [comment]
@brookjordan @chrisdavidmills 

It's ok.
Thanks everyone, this would have saved me hours long ago when I was looking for this solution 🙂👌
