### ISSUE TITLE
Logical shorthands should not be marked experimental

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#3793]
## URL(s)

- https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
- https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline

(and related, margin, border properties).

## Request type

- [ ] New documentation
- [*] Correction or update

## Details

The logical shorthands are in Chrome 87 (https://web.dev/logical-property-shorthands/) they are still marked as experimental in the MDN docs. I think with two implementations (I believe they are also in WebKit though not shipped in Safari, but I'll check) it's time to make these not experimental. BCD also needs updating.

**Comment by chrisdavidmills** [comment]
I totally agree @rachelandrew . I've gone through and removed the experimental banner from any logical property reference pages that still have them. Can you handle the BCD update please?

**Comment by rachelandrew** [comment]
@chrisdavidmills will do

**Comment by rachelandrew** [comment]
@chrisdavidmills BCD has now been merged for this one
