### ISSUE TITLE
inconsistency in code example :: <radialGradient> - SVG

### ISSUE THREAD

**Issue by ianfabs** [mdn/sprints#3794]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On this page in the first code example, a comment incorrectly refers to the radialGradient being demonstrated as a **linerGradient**

![image](https://user-images.githubusercontent.com/16561284/96014459-69143980-0e14-11eb-9494-b82fa8547c3a.png)
*Please forgive my darkreader*

page link: [<radialGradient> - SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient)

It should be `radialGradient`

---

<details>
    <summary>full page link</summary>
    
    https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient
</details>

**Comment by chrisdavidmills** [comment]
@ianfabs fixed; thanks for reporting!
