### ISSUE TITLE
Piratespeak in https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/compressedTexImage2D

### ISSUE THREAD

**Issue by RenaKunisaki** [mdn/sprints#3795]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/compressedTexImage2D

> pixels
> An ArrayBufferView that be used as a data store for the compressed image data in memory.

"That be" should probably be "that will be" or some such.

**Comment by chrisdavidmills** [comment]
Oi be fixing that for you. Yarrrrr.
