### ISSUE TITLE
Using Set to assert uniqness of iterabile's elements

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3796]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

## Request type

- [X] New documentation
- [ ] Correction or update

## Details
If You want to `console.assert` that all `id`s in a document are unique You can `querySelectorAll` elements that have an `id`, `map` to an `Array` and then compare the `length` of the  `Array` with the `size` of a `new Set` from it.
It could be a good use case example.

**Comment by chrisdavidmills** [comment]
@mattiapontonio great idea. Keep them coming!

**Comment by mattiapontonio** [comment]
Editing done: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by chrisdavidmills** [comment]
@mattiapontonio thanks a lot.
