### ISSUE TITLE
Web API updates for Firefox 83

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3799]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x]  [[UI Events][Input Events] Ship "beforeinput" event and `InputEvent.getTargetRanges()` in Nightly (and early beta) channel](https://bugzilla.mozilla.org/show_bug.cgi?id=1609291) — Only enabled in Nightly right now, so this won't need a release note, but you'll need to see if the expermental features page needs updating, and check whether these features have been documented properly and have good examples, whether BCD needs an update, etc.
2. - [x]  [[Input Events] Set "affected" ranges to the result of `getTargetRanges()` at dispatching `beforeinput` event](https://bugzilla.mozilla.org/show_bug.cgi?id=1658702) — Related to the above bug, probably just requires that you make sure this behavior is decribed appropriately.

Total estimate: 1-2 days

**Comment by Rumyra** [comment]
Temporary check list for myself - I'll update

- [ ] beforeinput experimental features page check/update
- [ ] beforeinput BCD
- [ ] beforeinput code example
- [ ] more beforeinput explainer

- [ ] getTargetRanges experimental features page check/update
- [ ] getTargetRanges BCD
- [ ] getTargetRanges code example
- [ ] getTargetRanges explainer
- [ ] getTargetRanges affected ranges description

**Comment by Rumyra** [comment]
After a long period of getting my head around what was needed everything is up to date all works expectedly, aside from BCD

I haven't done any BCD PRs yet, looking into it this morning I'd like to spend a bit of time reading the contributing and schema pages, as although I think this update is relatively straight forward, it's going to be benificial in the future if I get familiar with the json 👍

**Comment by chrisdavidmills** [comment]
Thanks @Rumyra ! Can you give me a list of the page URLs you have changed, and PRs you have submitted?? I'll go forward and review them.

**Comment by Rumyra** [comment]
So far:

https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/getTargetRanges
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features

Reviewed and seemed all good:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/InputEvent
https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event

**Comment by chrisdavidmills** [comment]
Thanks @Rumyra , these look good. I've made a few tweaks, and removed the "Experimental" banner from the tops of these pages, as they are no longer experimental.

**Comment by Rumyra** [comment]
OK added a PR for browser compat https://github.com/mdn/browser-compat-data/pull/7279

Moving into review as this is the final thing on the list 👍

**Comment by chrisdavidmills** [comment]
@Rumyra all looks good to me.

So the final thing to do then is go to the bugs listed at the top of the issue, set the "dev-doc-needed" keyword to "dev-doc-complete", and add a comment saying that the documentation is complete, and state what you did. You cna just link to this issue if you like, rather than repeating yourself.

**Comment by masayuki-nakano** [comment]
Could you add an example of feature detection for `beforeinput`? Since Blink has not implemented `onbeforeinput` attribute yet, checking `InputEvent.getTargetRanges` is the only way to detect it (it's available only with `beforeinput`).  So, there should be something like:
```
function isBeforeInputEventAvailable() {
  return typeof InputEvent.prototype.getTargetRanges === "function";
}
```

**Comment by chrisdavidmills** [comment]
Thanks for the review, @masayuki-nakano !

@Rumyra can you handle this one please?

**Comment by Rumyra** [comment]
Picking this up now @chrisdavidmills - re our discussion yesterday, this page https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement does not contain a subpage for `onbeforeinput` as a property and from what I can tell one doesn't exist. Can you confirm and I shall add

@masayuki-nakano thank you - just to confirm the `onbeforeinput` handler has not been implemented, but the `beforeinput` event has? I have some code running here which appears to confirm this is the case...

**Comment by masayuki-nakano** [comment]
Gecko and WebKit supports `onbeforeinput`, but Blink does not.
https://bugs.chromium.org/p/chromium/issues/detail?id=947408

`getTargetRanges` returns meaningful result only when `beforeinput` event. Therefore, it's enabled only when `beforeinput` event is enabled by the pref on Gecko so that it can be used for feature detection.

**Comment by Rumyra** [comment]
Feature detection added to https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event and https://wiki.developer.mozilla.org/en-US/docs/Web/API/InputEvent/getTargetRanges 👍

**Comment by Rumyra** [comment]
Also BCD PR accepted https://github.com/mdn/browser-compat-data/pull/7279#event-3989566683

**Comment by chrisdavidmills** [comment]
Great, looks like we can close this. Thanks @Rumyra
