### ISSUE TITLE
JavaScript updates for Firefox 83

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3801]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x]  [Intl[Symbol.toStringTag] should exist with value "Intl"](https://bugzilla.mozilla.org/show_bug.cgi?id=1670053) — Not really sure about this one, investigation needed.

Total estimate: an hour

**Comment by hamishwillee** [comment]
This looks like "nearly" a carbon copy of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/@@toStringTag except that you can't create an object of type Intl. So change is addition of page, example and BCD.

- - [ ] [Intl.prototype[@@toStringTag]](
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/@@toStringTag) - need to make sure it is correctly in prototype of parent. Also still working on BCD and Example that it links.
- - [ ] BCD Entry - not yet done
- - [ ] [Interactive example](https://github.com/mdn/interactive-examples/pull/1706)
- - [ ] Release note - not sure if justified - very minor thing.

**Comment by chrisdavidmills** [comment]
BCD was approved and merged, and I've set the bug to dev-doc-complete. This can be closed.
