### ISSUE TITLE
HTML updates for Firefox 83

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3802]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Implement support for the autocapitalize atttribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1425291) — added to appropriate pages where it s supported, write a demo, update BCD, etc.
2. - [x] [crossorigin attribute is not honored for [rel=icon] links](https://bugzilla.mozilla.org/show_bug.cgi?id=1661075) — probably not much to do here; small update, BCD, and rel note?
3. - [x] [Implement displaystyle attribute on all MathML elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1666075) — could mean quite a lot of page and BCD updates. Let me know if you want some support on this one.

Total estimate: 3-4 days

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm not sure where to make note of the `[rel=icon]` stuff, or which BCD to update. There are various candidates.

- page for `rel`: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
- crossorigin: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
- https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/CORS_Enabled_Image
- link: https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by rachelandrew** [comment]
All of the MathML element pages and the one for the `displaystyle` attribute are updated. Looking at the BCD now.

**Comment by rachelandrew** [comment]
BCD: https://github.com/mdn/browser-compat-data/pull/7025

**Comment by chrisdavidmills** [comment]
> I'm not sure where to make note of the `[rel=icon]` stuff, or which BCD to update.

Bleh, this is a bit of a mess. I would put a note on the first two pages, and add a note into the Fx support for 1, 2, and 4. I'd ignore 3.

**Comment by chrisdavidmills** [comment]
Hi @rachelandrew ! Did you get round to doing the BCD for the `[rel=icon]` stuff?

**Comment by rachelandrew** [comment]
@chrisdavidmills ah sorry, I think I lost track of this, I'll do it tomorrow.

**Comment by rachelandrew** [comment]
@chrisdavidmills ok have added a note and also updated BCD. Raised another issue about these various link rel values as it's all a bit untidy, I think there is probably quite a rabbit hole there.

**Comment by chrisdavidmills** [comment]
Looks good for now though; I think we can close this one.

The rel notes look good too: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/83#HTML
