### ISSUE TITLE
DevTools updates for Firefox 83

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3803]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Enable devtools.overflow.debugging.enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1669129) — small new feature to document; work needed nicely summarized in [comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1669129#c4).

Total estimate: 0.5 days

**Comment by hamishwillee** [comment]
- [ ] [Enable devtools.overflow.debugging.enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1669129) — small new feature to document; work needed nicely summarized in [comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1669129#c4).

- - [ ]  Content updates
    - - [ ] [Examine and edit HTML > HTML tree](https://wiki.developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML#HTML_tree) - add tool to table of markers (badges)
    - - [ ] [Scroll container](https://wiki.developer.mozilla.org/en-US/docs/Glossary/scroll_container) - maybe add info on scroll and overflow badges. TBD
    - - [ ]  [CSS Overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Overflow) - maybe info on debugging - pointer to new debug doc
    - - [ ]  Maybe dedicated topic like [CSS Flexbox Inspector: Examine Flexbox layouts](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_Flexbox_layouts). With brief outline of how to debug.
- - [ ] BCD is updated - IS THERE A BCD for tools? I found devtools, but that is all about enabling devtools and devtools API, not specific cases.
- - [ ] Release note 
- - [ ] experimental features page is updated
- - [ ] Review

**Comment by chrisdavidmills** [comment]
All sounds pretty good, thanks @hamishwillee 

> IS THERE A BCD for tools?

No, we don't keep BCD for Firefox DevTools features — they are not part of the web platform (like HTML, CSS), and there is no real drive to try to keep parity across browsers (like with the cross-browser subset of WebExt APIs)

**Comment by hamishwillee** [comment]
@chrisdavidmills I think this one is ready for review when you are. We could do a minor tweek after release, but leaving it alone would not break anything

**Comment by chrisdavidmills** [comment]
OK, I think we can close this one now.
