### ISSUE TITLE
Misc updates for Firefox 83

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3804]
## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [ ] [Implement support for AV1 Still Image File Format (AVIF)](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863) — I've read reports that suggest this is going to be enabled in Firefox 83. If so, probably wants to be mentioned in places like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img and https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types, BCD updated, etc. Needs some investigation.

Total estimate: 1 day

**Comment by hamishwillee** [comment]
Review
- Enabled in Chrome 85 and later
- Enabled in FF80 by `about.config` preference = `image.avif.enable`. There is a good quick test URL: http://188.121.162.14/avif/
- MIME type should be `image/avif` but does not appear to be registered yet: https://www.iana.org/assignments/media-types/media-types.xhtml#image
- It works but there appear to be some bugs outstanding

Docs that may well need update:
- - [ ] [Image file type and format guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)
- - [ ] [`img`: The Image Embed element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)
- - [ ] [HTTP > List of default Accept values](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#Values_for_an_image)
- - [ ]  [`picture` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
- - [ ]  Maybe mention it here:  [Use modern image formats boldly](https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Use_modern_image_formats_boldly)

Other 
- - [ ] BCD updated 
  - There does not appear to be any documentation of supported media formats in the BCD. I looked at where there might be "impacts" and that is things like https://developer.mozilla.org/en-US/docs/Web/API/Document/images and clipboard etc. Again though, these pretty much either will require specific support for the type OR assume all types. 
  - @chrisdavidmills Am I missing something? I think if I just update the docs you identified I do capture the important browser compatibility.

Questions:
- [Apparently](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#Values_for_an_image) the `about:config` key of `image.http.accept` can be used to set new image MIME types. Does not appear to work by adding image/png - tested on a number of sites like https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending

**Comment by chrisdavidmills** [comment]
@hamishwillee there are a couple of outstanding bits here, I believe. Can you finish them off?

**Comment by hamishwillee** [comment]
@chrisdavidmills The docs are all done except for the release note. BUT right now this is not in release 83 - ie the origin bug is still open.

 I'll ask if this is going in - but presumably if not we just push this whole item to become misc updates for firefox 84?

**Comment by chrisdavidmills** [comment]
@hamishwillee OK, for now let's assume it isn't being enabled in 83, and:

* Not add a release note
* Make sure it is covered in the Experimental features page
* Add notes to anywhere it is mentioned to say that it is currently supported behind a pref in Firefox (pref details at https://bugzilla.mozilla.org/show_bug.cgi?id=1625363), and will hopefully be enabled by default shortly.

Then I think we can close this out. It's a shame that we can't shout about this being enabled now, but it's great that you've gotten all the lead up work done; nice one Hamish!

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks. FWIW most of this was already done, but I went though and made some minor "touch ups". Also added a link from the bug page to this issue to help future documenters. Closing this now :-)
