### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Silly_story_generator

### ISSUE THREAD

**Issue by lshenghan** [mdn/sprints#3805]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

radio button 翻译成中文，应该是单选按钮，而不是收音机按钮。

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. You are welcome to update it yourself (please let me know if you want some help with this)
