### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

### ISSUE THREAD

**Issue by xioxvo** [mdn/sprints#3807]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Two sections of sample code used innerHTML to assign text to a < li > tag:
newElement.innerHTML = "message: " + event.data;
newElement.innerHTML = "ping at " + time;
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

Documentation on innerHTML recommends using Node.textContext when inserting plain text:
However, there are ways to execute JavaScript without using <script> elements, so there is still a security risk whenever you use innerHTML to set strings over which you have no control.
For that reason, it is recommended that you do not use innerHTML when inserting plain text; instead, use Node.textContent. This doesn't parse the passed content as HTML, but instead inserts it as raw text.
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

**Comment by prosovskyf** [comment]
please assign. Thanks

**Comment by chrisdavidmills** [comment]
@prosovskyf assigned. Thanks for your interest in working on this!

**Comment by prosovskyf** [comment]
@chrisdavidmills please review

**Comment by chrisdavidmills** [comment]
@prosovskyf looking great, thanks! I removed the note, as I didn't think it was needed, but the code updates are fine.
