### ISSUE TITLE
https://developer.mozilla.org/es/docs/Learn/JavaScript/First_steps/Useful_string_methods

### ISSUE THREAD

**Issue by Maze000** [mdn/sprints#3808]
hey guys, I think you should change ! in this line of code by =, according to the description they make before this line of code: "You can use this to find all instances of the strings that do not contain the substring 'mozilla', or do, if you use the operator negation, as shown below. You could do something like this: "
In https://developer.mozilla.org/es/docs/Learn/JavaScript/First_steps/Useful_string_methods

if (browserType.indexOf ('mozilla')! == -1) {
   // do stuff with the string
}

for

if (browserType.indexOf ('mozilla') === -1) {
   // do stuff with the string
}

thanks.

**Comment by chrisdavidmills** [comment]
Hi @Maze000 !

I've updated the English version, as I think you are right that it is a bit confusing. Can I get your help in updating the Spanish version?

**Comment by Maze000** [comment]
Hi Chris, yes, tell me what you need and I'll help you.

**Comment by Maze000** [comment]
hi, I think if you want to imply that the developer can search for
"mozilla" or ignore strings that contain "mozilla", you should write an
example for each of the cases.
In the described sentence you only describe the case of searching the
string "mozilla". I think an example of each case would be clearer for a
beginner.

As for the spanish translation, you just have to replace the word " o
hacer" with "o hacerlo", that's all. This means that the statement that
follows will search for the strings "mozilla".

**Comment by chrisdavidmills** [comment]
Spanish version fixed; thanks for the help. I'm not really sure what you want me to do with the updated example I provided. I've explained pretty clearly what each one does.

**Comment by Maze000** [comment]
I mean that in the description you refer to selecting mozilla or not
selecting, there could be an example of each case: "! == - 1" and  "! ==
1", but if you think it's fine, its ok.

**Comment by Maze000** [comment]
I mean, based on what I read in the description, when it says "NO" it is:!
== 1 (since it will find the non-mozilla strings) if (browserType.indexOf
('mozilla')! == 1) { // do stuff with the string } , but when it says "or
do it" it is:! == -1 (it will find all mozilla strings) if
(browserType.indexOf ('mozilla')! == -1) { // do stuff with the string } ,
I think that is what you are trying to describe, at least that is what is
understood when one reads, two cases.
I understand it, but perhaps for someone reading it for the first time it
might be helpful if they see the two sentences.
