### ISSUE TITLE
clarification about array's fill

### ISSUE THREAD

**Issue by s-e1** [mdn/sprints#3809]
# Request type
- [ x] Correction or update

# Details

Can you clarify that "fill" doesn't create new sub arrays, but only makes 1 sub array, and all the other sub arrays refer to it. This causes many problem as detailed in theses links:
https://stackoverflow.com/questions/48576792/setting-one-value-in-3d-array-mutates-others-values
https://stackoverflow.com/questions/48963365/push-on-array-of-prefilled-arrays-sets-all-elements
https://stackoverflow.com/questions/64418756/creating-nested-array-with-fill-causes-stack-overflow
https://stackoverflow.com/questions/38940576/javascript-why-array-prototype-fill-actually-fills-a-pointer-of-object-when

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

**Comment by Prerna237** [comment]
@chrisdavidmills : Hi! I can pick this up.

**Comment by chrisdavidmills** [comment]
@Prerna237 great, thanks! I've assigned it.

**Comment by Prerna237** [comment]
@s-e1 : The article already mentions that the static value of the first parameter is set throughout the array. It also mentions that all elements in the array will be this exact value.

Hence, the best way to put across the point you've raised seems to be through an example and I have added it. Let me know if that works.

**Comment by s-e1** [comment]
It should help. Thank you.

**Comment by s-e1** [comment]
**@Prerna237** : It should help. Thank you.
