### ISSUE TITLE
Missing Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for page

### ISSUE THREAD

**Issue by koto** [mdn/sprints#3813]
# Request type

- [X] New documentation
- [ ] Correction or update

# Details
The trusted-types CSP directive ([MDN](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types)) was recently [split](https://w3c.github.io/webappsec-trusted-types/dist/spec/#integration-with-content-security-policy) into two separate directives - `trusted-types` and `require-trusted-types-for`.

MDN only has a page for the former (I've sent a separate wiki edit for it), but not the latter. I'd be happy to provide the content for it (I'm the Trusted Types spec editor), but I can't create a new page in MDN, hence this issue.

https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for

**Comment by chrisdavidmills** [comment]
@koto New page created at the suggested location. Thanks for offering to help populate it with content, and please let me know if you need any help!

**Comment by chrisdavidmills** [comment]
Looks like this was done, so closing.
