### ISSUE TITLE
Using Object.defineProperty() to define object members

### ISSUE THREAD

**Issue by krankj** [mdn/sprints#3815]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[Here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Modifying_prototypes), mentioning about modifying prototypes, I feel it would help if a _note on caution_ is added for the following example:

```
Person.prototype.farewell = function() {
  alert(this.name.first + ' has left the building. Bye for now!');
};

let person1 = new Person('Bob', 'Smith', 32, 'male', ['music', 'skiing']);
```
While` person1.farewell()` can be called upon, it is also necessary to mention that performing

`delete person1.__proto__.farewell ` or `delete Person.prototype.farewell`

removes the `farewell` method from all Person instances too.

Instead, if the `farewell` method were to be defined using `Object.defineProperty()` ( which is normally the best practice ) like this:

```
Object.defineProperty(Person.prototype, 'farewell', {
    value: function() {
    alert(this.name.first + ' has left the building. Bye for now!');
     }
    }
  );
``` 
,the above mentioned situation could be mitigated.

Also, apart from the above, its worth mentioning as a _note_ somewhere on [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Understanding_prototype_objects) page that only while retrieving members from an object is the entire prototype chain traversed, and not while `delete`ing.

I could update the wiki if this sounds valid :)

-kJ

**Comment by sideshowbarker** [comment]
> …
> I could update the wiki if this sounds valid :)

I agree with the rationale outlined in the issue description, and I think it’s worth updating the article to include the suggested changes.

**Comment by krankj** [comment]
@chrisdavidmills @sideshowbarker 

A new note has been added [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes/#Modifying_prototypes) and [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Understanding_prototype_objects)

**Comment by sideshowbarker** [comment]
> A new note has been added [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes/#Modifying_prototypes) and [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Understanding_prototype_objects)

👍 Looks great to me

**Comment by chrisdavidmills** [comment]
Looks great @krankj , thanks so much for the update! I've tweaked the wording of the notes slightly, so you might want to just check them to make sure you are happy, but I think we can close this now.

**Comment by krankj** [comment]
The updated wording looks much better! Thanks.
