### ISSUE TITLE
Out of context section in chaining promises

### ISSUE THREAD

**Issue by alan-jouhar** [mdn/sprints#3816]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

### A section in `Chained promises` is not relevant.
In [Chained promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) section the docs state the following:

`The signatures of these two functions are simple, they accept a single parameter of any type. These functions are written by you, the programmer. The termination condition of these functions determines the "settled" state of the next promise in the chain. Any termination other than a throw creates a "resolved" state while terminating with a throw creates a "rejected" state.`

which is completely out of section's context and seems not relevant to it.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by chrisdavidmills** [comment]
@alan-jouhar I agree; the structure of these paragraphs was a bit confusing. I've tried updating them a bit. Cna you have a look now and tell me if you think this is better?

**Comment by alan-jouhar** [comment]
yes it sounds consistent.thank you.
