### ISSUE TITLE
"Site compatibility" links to a site that no longer operates

### ISSUE THREAD

**Issue by shdon** [mdn/sprints#3817]
**Summary**
_What is the problem?_
All of the "for Developers" release notes have a link in the "See also" section that links to https://www.fxsitecompat.com (which in itself redirects to https://www.fxsitecompat.dev), but that site no longer has any content.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to a page like ["Firefox 82 for Developers"](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82)
2. Scroll down to the ["See also" section](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/82#See_also)
3. Click on the ["Site compatibility for Firefox 82" link](https://www.fxsitecompat.com/en-CA/versions/82/)

**Actual behavior**
_What actually happened?_
The linked page reports: "410 Gone - The Firefox Site Compatibility Working Group has been dissolved. Our resources are no longer available."

**Expected behavior**
_What did you expect to happen?_
I expected to see information about Firefox site compatibility.

**Additional context**
_Is there anything else we should know?_
If this information is no longer available, shouldn't the link just be removed?

**Comment by chrisdavidmills** [comment]
@shdon oh no, I didn't realise that the site compat group were no longer operational! I guess the obvious fix then is to simply delete the See also section from this document. Let me know if you are comfortable with making that fix. Thanks!

**Comment by kelimuttu** [comment]
I updated the article and remove the "See also" section altogether.

**Comment by chrisdavidmills** [comment]
@kelimuttu great, thanks a lot!
