### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/83

### ISSUE THREAD

**Issue by lsze** [mdn/sprints#3820]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
**Developer Tools** section references `:screenshot --fullscreen` flag, should be `--fullpage`

>  ...when taking a fullscreen screenshot using --fullscreen

**Comment by chrisdavidmills** [comment]
Good spot, thanks for reporting @lsze . I've fixed it now.
