### ISSUE TITLE
Triage the webaudio-example repo

### ISSUE THREAD

**Issue by Rumyra** [mdn/sprints#3821]
webaudio-examples repo has some outstanding issues and PRs which need to looked at

Be good to get around to this sometime so adding it as a low priority issue so it gets on my work list - @Rumyra

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1464](https://github.com/mdn/content/issues/1464) via [**ZenHub**](https://www.zenhub.com/)
