### ISSUE TITLE
https://developer.mozilla.org/ru/docs/MDN/Contribute/Feedback

### ISSUE THREAD

**Issue by AlexRobux** [mdn/sprints#3822]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

So, there is error with formatting on Promise.prototype.catch() page in Russian laguage (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)
![image](https://user-images.githubusercontent.com/65112064/96869681-79618f80-1478-11eb-975b-50564bcff6d6.png)

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. you are of course welcome to edit the page yourself (ask me if you want some help with doing this).
