### ISSUE TITLE
Example for ResizeObserver doesn't work in Chrome

### ISSUE THREAD

**Issue by xehpuk** [mdn/sprints#3823]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[In the documentation of `ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver), there is an example ([resize-observer-text.html](https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html)). It works in Firefox, but doesn't in the latest Chrome, even though it should according to the browser compatibility table. The font size doesn't change there.

Smallest width:
![image](https://user-images.githubusercontent.com/3484906/96873215-f12dbb00-1474-11eb-8696-0a10bd93e27a.png)
Biggest width:
![image](https://user-images.githubusercontent.com/3484906/96873225-f68b0580-1474-11eb-96cc-2b1eb1529e5a.png)

[Source of the example](https://github.com/mdn/dom-examples/blob/master/resize-observer/resize-observer-text.html)

**Comment by brookjordan** [comment]
Hey, the problem is that Chrome seems to use a non-standard array for `entry.contentBoxSize`, so the code needs to be updated to check for `entry.contentBoxSize[0].inlineSize`.

I’ve updated the code in the wiki so this will just need the actual example updated now.
See here for a working example:
https://codepen.io/brookjordan/pen/yLJgbBj?editors=1010

**Comment by Rumyra** [comment]
Thanks all 👍 

@chrisdavidmills you can find a PR here https://github.com/mdn/dom-examples/pull/73

**Comment by chrisdavidmills** [comment]
Thanks @Rumyra ! I've merged your PR, and updated the code snippet shown in the article as appropriate. The example works nicely on Chrome and Fx, so I think this one cna now be closed.
