### ISSUE TITLE
Working example of the below URL does not have working example as domain is expired 

### ISSUE THREAD

**Issue by mastergogo** [mdn/sprints#3824]
MDN pages that shows working examples which are hosted on http://www.oaa-accessibility.org/ does not work as domain is expired. there are several pages that redirects to expired pages now for example this page: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute

**Comment by chrisdavidmills** [comment]
Most of these are now fixed, so I'm closing this one. Please file an issue on https://github.com/mdn/content if you notice any more. Thanks!
