### ISSUE TITLE
Change incorrect glossary URL for accessibility tree (not AOM)

### ISSUE THREAD

**Issue by patrickhlauke** [mdn/sprints#3825]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
As per https://twitter.com/aardrian/status/1319393453692850176 this page was incorrect https://wiki.developer.mozilla.org/en-US/docs/Glossary/AOM - it has now been edited to reflect the correct information (to talk about the accessibility tree, and *not* AOM which is a JS API that will aim to provide programmatic access to the accessibility tree and express accessibility semantics). However, the URL is still misleading/incorrect - it should be moved wholesale to https://wiki.developer.mozilla.org/en-US/docs/Glossary/Accessibility_tree and any references to the old URL should be changed

**Comment by chrisdavidmills** [comment]
Cheers pattypoos! Page looks good; I've just tweaked the language a bit, so you might want to quickly skim it again just to make sure I've not adversely affected any of the meaning.

I've also moved the page to the correct URL, and changed the link to it on the main Glossary page.

I think this can be closed now, but ping me if you think it needs anything else.

**Comment by patrickhlauke** [comment]
LGTM cheers fella

**Comment by aardrian** [comment]
Thank you both!
