### ISSUE TITLE
Reflect deleteProperty() wiki seems missing

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3826]
@2shraaf commented on [Fri Oct 23 2020](https://github.com/mdn/mdn/issues/107)

When I go to https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty, it view Reflect.defineProperty() wiki not deleteProperty

**Comment by mikoMK** [comment]
Another user has already reverted the wrong revision on October 29. The page shows the correct content again.
@chrisdavidmills This issue can be closed.

**Comment by chrisdavidmills** [comment]
Great stuff; thanks @mikoMK !
