### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback

### ISSUE THREAD

**Issue by RCopeland** [mdn/sprints#3827]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I'm going though the svg filters tutorial and I *think theres an error in the example at the bottom.
The </filter> closing tag should be moved to wrap the <feMerge> primitive.

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Filters_Tutorial

```
    <filter id="drop-shadow">
      <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur" />
      <feoffset in="blur" dx="4" dy="4" result="offsetBlur" />
      <feMerge>
        <feMergeNode in="offsetBlur" />
        <feMergeNode in="SourceGraphic" />
      </feMerge>
    </filter>
```
Doing that makes it work on my codepen project:

https://codepen.io/robcopeland/pen/eYzNmwe

**Comment by chrisdavidmills** [comment]
Hi @RCopeland !

Thanks for pointing this out. I've fixed the version in the Wiki page: https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Filters_Tutorial. Let me know if you think this needs any more.

I love your example BTW, I wondered if I could be cheeky and ask if you'd be interested in helping to expand the tutoral page? Seems rather incomplete at the moment ;-)

Finally, thanks for making the change on the content repo — that's not the live content right now, but it will be when we move to our new platform on December 14th. If you are interested in helping to test it further, let me know.

Best,
