### ISSUE TITLE
Fullscreen API live examples broken video

### ISSUE THREAD

**Issue by gsouquet** [mdn/sprints#3828]
## URL(s)
https://wiki.developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
The video used in the live example is broken and returns a `403`. 

Link to the live example https://media.prod.mdn.mozit.cloud/samples/domref/fullscreen.html
Link of the broken video used in the example http://videos-cdn.mozilla.net/serv/webmademovies/Moz_Doc_0329_GetInvolved_ST.webm

**Comment by chrisdavidmills** [comment]
To whoever picks this up — easiest/best way to fix this would probably be to create a directory for fullscreen api in https://github.com/mdn/dom-examples/, put the example in there, and then embed it into the page using the `{{EmbedGHLiveSample()}}` macro (see a usage example [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills)).

Also, maybe check the other Fullscreen API pages to see if there are any other broken examples hanging around.

**Comment by tarunbatra** [comment]
Hey, the directions by @chrisdavidmills are very clear and helpful so this should be easy and I will take this up unless somebody objects here.

**Comment by chrisdavidmills** [comment]
@tarunbatra I've assigned you to do this task, thanks very much for picking this up!

**Comment by tarunbatra** [comment]
Hey, as I have started working on it, I have realized I don't have the video to be used as the example. I can use the one used in [Picture-in-picture example](https://mdn.github.io/dom-examples/picture-in-picture/assets/bigbuckbunny.mp4) or is there is no preference.

**Comment by chrisdavidmills** [comment]
@tarunbatra that would be OK by me. Big Buck Bunny is the gold sandard open license video for use in web examples ;-)

**Comment by tarunbatra** [comment]
PR https://github.com/mdn/dom-examples/pull/68 is up for review. ping @chrisdavidmills 

Once that is done, I'll proceed to edit the page itself to include the new example.

**Comment by tarunbatra** [comment]
Hi @chrisdavidmills continuing our discussion from the [PR](https://github.com/mdn/dom-examples/pull/68#issuecomment-718674160), I tried using the macro, the key event worked but the iframe couldn't request fullscreen since `allow="fullscreen"`([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes)) needs to be provided while declaring the iframe. I tested this locally and it worked. Now, I wasn't sure if it's possible to provide that option using the macro.

However, I have updated the [broken link](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Example) so at least we have a stable example as we discuss this.

**Comment by chrisdavidmills** [comment]
@tarunbatra ah, shame that it doesn't work. This isn't the first time someone has asked about how we can provide specific options to the generated `<iframe>`, but we'll have to wait until the engineers have time in their busy schedules to provide such a solution.

For now, I think the page is OK as-is. The explanation is good, and the example is available via a link.

I'd be happy to call this done. Are you OK with that?

**Comment by tarunbatra** [comment]
Yes @chrisdavidmills, I agree this is a good solution given the `iframe` limitations. Adding a button won't display the use of fullscreen API well enough since a button can't be clicked to exit full screen mode. So yeah, this makes sense to me. 👍

**Comment by chrisdavidmills** [comment]
Cool, let's close it then. Thanks a lot for your great work here!

**Comment by Rumyra** [comment]
Again moving to done status as it's closed
