### ISSUE TITLE
Luxembourgish is missing in Dictionaries and Language Packs list – Dictionnary exists

### ISSUE THREAD

**Issue by RaymondWillems** [mdn/sprints#3829]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details

In the [Dictionaries and Language Packs list](https://addons.mozilla.org/en-US/firefox/language-tools/), a language pack for Luxembourgish is missing.

Please find my proposition below.

Locale Name | Language Packs | Dictionaries
-- | -- | --
Luxembourgish | Lëtzebuergesch | [Luxembourgish Dictionary](https://addons.mozilla.org/en-GB/firefox/addon/spellcheckerlu-dictionary/)

Link to the dictionary: https://addons.mozilla.org/en-GB/firefox/addon/spellcheckerlu-dictionary/

Source at Wikipedia:
https://lb.wikipedia.org/wiki/L%C3%ABtzebuergesch
https://en.wikipedia.org/wiki/Luxembourgish

Thanks for your support!!

I wish all of you, the team and families a lot of health!!
Best, Raymond

**Comment by chrisdavidmills** [comment]
Hi @RaymondWillems !

This is an issue with a Firefox add-on, whereas this repo is for reporting issues with [MDN Web Docs](https://developer.mozilla.org) documentation. To find out better places to ask your question, see this page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us.

HTH, and all the best.
