### ISSUE TITLE
Please explain the Date constructor month argument "1-indexed in (Nodejs)" comment

### ISSUE THREAD

**Issue by markogresak** [mdn/sprints#3830]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Examples

One of the example lines of code is
```js
let birthday = new Date(1995, 11, 17)            // the month is 0-indexed (browser) / 1-indexed in (Nodejs)
```

My request is regarding the part of the comment saying "1-indexed in (Nodejs)".

Specifically, I am talking about the following revision: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date$compare?to=1649777&from=1649085

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

I could not believe this, I had to try it myself. I have picked the following code to test:
```js
console.log(new Date(1995, 11, 17).toDateString()
```

If the "1-indexed in (Nodejs)" is correct, I should expect the line to output `"Fri Nov 17 1995"` when running the code in nodejs as opposed to `"Sun Dec 17 1995"` in the browsers.

I ran the following commands to produce the results below:
```sh
echo "node --version: $(node --version)"
echo "result: $(node -e ')')"
```

Between each run, I have changed the `node` version using `nvm use $version`.

Results:
```
node --version: v10.22.1
result: Sun Dec 17 1995

node --version: v12.19.0
result: Sun Dec 17 1995

node --version: v14.14.0
result: Sun Dec 17 1995

node --version: v15.0.1
result: Sun Dec 17 1995
```

I believe this is sufficient proof that the part of the comment is not correct.

**Comment by markogresak** [comment]
I have filed a fix for the comment: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date$compare?from=1649991&to=1650115

**Comment by chrisdavidmills** [comment]
Looks good to me, @markogresak . Thanks for investigating this, and for fixing it too!
