### ISSUE TITLE
Document requestVideoFrameCallback API

### ISSUE THREAD

**Issue by gsouquet** [mdn/sprints#3832]
The requestVideoFrameCallback (https://wicg.github.io/video-rvfc/) needs to be documented. It has landed in Chrome and is pretty useful
It seems that Firefox deems it `worth-prototyping` (https://github.com/mozilla/standards-positions/issues/250#issuecomment-613289284). 

It would be important to add a note next to all references to `HTMLVideoElement.mozPaintedFrames` saying that this information is accessible via `requestVideoFrameCallback`.

Created the issue to validate that we want to document that on MDN or whether it is too early. If this sounds like an API that should be on DM, please assign this issue to me and I'll be happy working on it

**Comment by chrisdavidmills** [comment]
To me, this feels a bit early to document. I've not seen anything over here about an intent to prototype or intent to ship going out yet. Another question for me would be — what evidence have we got that the spec is stable?

Saying that, it does seem to have some momentum and interest among web devs.

**Comment by gsouquet** [comment]
@chrisdavidmills I am a bit unsure how to gather whether a spec is stable or not
The "worth prototyping" standard position from Mozilla might be a good signal that this will be enabled in multiple rendering engine
What other steps can I take to ensure of the stability of this?

Will probably give that documentation a go to test Yari and the new content repo

**Comment by chrisdavidmills** [comment]
@gsouquet fair answers here; it is not always the easiest question to answer. I think creating docs for this as part of the Yari testing would be great (keep the source code somewhere safe so it dfoesn't get lost), and you can always add browser compat data now.

As for finding more about implementation status, we can always ask. @padenot, has any progress been made on implementing `requestVideoFrameCallback()` in Gecko yet?

**Comment by padenot** [comment]
No.
