### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference - missing "export"

### ISSUE THREAD

**Issue by pheirendt-jama** [mdn/sprints#3833]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

Landing page for JavaScript reference is missing `export` statement. Under the section "**Statements**", subsection "**Other**", it lists `import` but is missing `export`.

This page:
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference

**Comment by chrisdavidmills** [comment]
@pheirendt-jama thank you for pointing this out! I've added it now.
