### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage$history

### ISSUE THREAD

**Issue by wolnavi** [mdn/sprints#3834]
# Request type

- [ ] New documentation
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] Correction or update

# Details

May I ask, why was the detailed "Syntax" removed from the current revision? :
![image](https://user-images.githubusercontent.com/10343444/97268087-506d4000-1866-11eb-9824-93b919bbefd2.png)

I think this is very useful as compared to the current `myStorage = window.sessionStorage;`...

**Comment by chrisdavidmills** [comment]
@wolnavi the syntax box is supposed to just contain a concise syntax definition of the feature, whereas what was there before was more like a set of examples. 

But I do see your point that the removed example snippets were very useful and it is a shame to lose them. I've therefore added them into the examples section; see https://wiki.developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage#Examples.
