### ISSUE TITLE
Update CSS Grid docs to remove grid- prefixed gap properties

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#3835]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

(and all guides and pages relating to grid)

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

Now that all browsers support `gap`, `column-gap`, `row-gap` update the examples on these pages to use those rather than the prefixed `grid-gap`, `grid-column-gap`, `grid-row-gap`.

**Comment by rachelandrew** [comment]
So I have been through every grid related page I can find (guides and property pages), updated gaps, also linked to the new `min-content`, `max-content`, and `fit-content()` pages. 

Found various out of date things mostly regarding browser support, mention of old `display: subgrid` value etc. So have tidied these up.

Updated the sidebars. The grid pages use a custom sidebar which is at the bottom of the page. I don't know how this is invoked but there are some pages that don't use it. The content is there however:

- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout
- https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

PRs:

- Small BCD update: https://github.com/mdn/browser-compat-data/pull/7343
- Moving and updating IAs: https://github.com/mdn/interactive-examples/pull/1721

**Comment by chrisdavidmills** [comment]
> Updated the sidebars. The grid pages use a custom sidebar which is at the bottom of the page. I don't know how this is invoked but there are some pages that don't use it. The content is there however:

Ah, this set of pages is using the "Quicklinks" feature to create the custom nav. It creates a sidebar out of whatever is inside the element with the `id` of `Quick_Links`, e.g.

```
<section class="Quick_links" id="Quick_Links">
 ...
</section>
```

In pages in the set that don't have the sidebar, you just need to copy that markup over to those pages.

I also deleted the "Subnav" headings from the pages that have them, as they are not needed, and it is not ideal having "Subnav" appearing in the jump menu.

**Comment by rachelandrew** [comment]
That's what I thought but the ones above do have it, but don't seem to use it - for example https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

You can tell the ones that aren't using it as the Guides are in a jumbled up order and they strangely have `flex` in the list of properties.

**Comment by chrisdavidmills** [comment]
> That's what I thought but the ones above do have it, but don't seem to use it - for example https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

ah, I see what you mean. Hrm, I'm not sure what is going on here, in that case. I wouldn't worry about it just for now.

**Comment by chrisdavidmills** [comment]
Looks like this is done; open a separate issue on the content repo for anything that is still amiss?
