### ISSUE TITLE
Invalid french translation for `autocomplete` values `address-line1`, `address-line2`, `address-line3`

### ISSUE THREAD

**Issue by xel1045** [mdn/sprints#3837]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The French description for `autocomplete` values `address-line1`, `address-line2`, `address-line3` does not have the same meaning in French and in English. 

The correct formulation is in English, and it says:
> Each individual line of the street address. These should only be present if the "street-address" is not present.

Based on that, the French translation should be:
> Des lignes individuelles pour décrire l'adresse postale. Ces valeurs peuvent être utilisées seulement lorsque la valeur `street-address` est absente.

![Screen Shot 2020-10-28 at 11 33 33](https://user-images.githubusercontent.com/1497697/97458785-6d128200-1911-11eb-9dbe-b5e1fd0ee397.png)

https://developer.mozilla.org/fr/docs/Web/HTML/Attributs/autocomplete

**Comment by hamishwillee** [comment]
@xel1045 Thanks for taking the time to post this. I'm closing because the MDN team doesn't have time to maintain translations, but this is a wiki so you are able to make this change yourself and we'd welcome you doing so.
