### ISSUE TITLE
Create new page for "CSS Functional Notations"

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#3838]
## URL(s)

Create one of the following pages:
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functional_Notations (I prefer this one)
* https://developer.mozilla.org/en-US/docs/Web/CSS/Functional_Notations

## Request type

- [x] New documentation
- [ ] Correction or update

## Details

So I was editing the following page:

* [Pseudo-classes](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
* [Pseudo-elements](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements)
* [At-rules](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/At-rule)
* [CSS Data Types](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types)
* [CSS Selectors](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)

Trying to standardize the design, add missing links, add "**Index**" of values where it was missing, add new headings and more...

I noticed that MDN has no page listing all the available "**CSS Functions**" or "**CSS Functional Notations**".  Over the years CSS evolved alot, now it has not only simple unit values but also complex functions processing data. Functions like `url()`, `attr()`, `var()`, `env()`, `calc()`, `min()`, `max()`, `clamp()`, `rgb()`, `rgba()`, `hsl()`, `hsla()`, `linear-gradient()`, `radial-gradient()`, `conic-gradient()` and many many more.

I want to create a page listing all those functional notations, their syntax, and other relevant information.

**Comment by chrisdavidmills** [comment]
Thanks @ramiy ; I agree that it would be a good idea to have a reference page for these.

I am personally not so sure about the URL. I think the second choice is the best in terms of technical correctness, although it is a bit of a repetitive URL (The third one is also correct, but omits the additional "CSS"), and the first one is less correct but probably means more to the average web developer.

We could still have the title as "CSS functional notation", regardless of the URL.

**Comment by ramiy** [comment]
@chrisdavidmills I agree, whatever you decide.

The URL is not important as long as the name is "**CSS functional notation**".

**Comment by chrisdavidmills** [comment]
OK, page created:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functionals

Have you got some time to help fill in the content?

**Comment by ramiy** [comment]
> Have you got some time to help fill in the content?

Yes, I'm on it.

**Comment by chrisdavidmills** [comment]
> > Have you got some time to help fill in the content?
> 
> Yes, I'm on it.

Great, thanks!

**Comment by ramiy** [comment]
@chrisdavidmills The initial article is ready.

But we need to add more functions to the list and create missing articles to each functional notation.

**Comment by ramiy** [comment]
Also we need to add "Related Topics" on the sidebar. Like the one in [CSS Types](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types).

**Comment by ramiy** [comment]
So far, I listed 75 functional notations...
