### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

### ISSUE THREAD

**Issue by Poopooracoocoo** [mdn/sprints#3839]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Well Edge is now based on Chromium.

It uses the `chrome.` namespace (edit: actually I think they equated the `browser.` namespace with `chrome.` for backwards compatibility). Basically everything related to _developing_ extensions Edge could be deleted as it's now just Chromium. I think the publishing requirements are still there though. I don't think you need additional packaging anymore as Microsoft Edge no longer uses the Microsoft Store. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/

**Comment by chrisdavidmills** [comment]
Thanks @Poopooracoocoo . This is something we need to look into.

**Comment by Cimeone** [comment]
I'd be happy to look into this, can this be assigned to me.

**Comment by chrisdavidmills** [comment]
Sure thing @Cimeone, happy to let you have a go.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1462](https://github.com/mdn/content/issues/1462) via [**ZenHub**](https://www.zenhub.com/)
