### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Generator

### ISSUE THREAD

**Issue by Rahim-Chan** [mdn/sprints#3843]
# Request type

- [x] Correction or update

# Details

 The content of `旧生成器对象示例` has a error that `fibonacci` function is missing a `*` symbol；
```
function fibonacci() {
  var a = yield 1;
  yield a * 2;
}

var it = fibonacci();
console.log(it);          // "Generator {  }"
console.log(it.next());   // 1
console.log(it.send(10)); // 20
console.log(it.close());  // undefined
console.log(it.next());   // throws StopIteration (as the generator is now closed)
```

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit the page yourself; https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started explains how.
