### ISSUE TITLE
Chinese word typo

### ISSUE THREAD

**Issue by ceociocto** [mdn/sprints#3845]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

`文本` should be `本文`

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Object-oriented_JS
![image](https://user-images.githubusercontent.com/13405430/97678879-79443e00-1acf-11eb-93ea-ff71c4562e73.png)

**Comment by chrisdavidmills** [comment]
Hi there! Apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit it yourself; [this page](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started) explains how.
