### ISSUE TITLE
Minor semicolon miss

### ISSUE THREAD

**Issue by AleckIDt** [mdn/sprints#3847]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Currently learning JavaScript and that part popped up to me. There should be a semicolon, as prior to finding it, it was taught that semicolons should be made a habit. I'm including a screenshot:
![New Project](https://user-images.githubusercontent.com/24766851/97773343-8442b100-1b57-11eb-9f77-553e055b3077.jpg)

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables
On "Variables 3"

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @AleckIDt ! I've fixed them in the source code, so they should show up in the final page render soon.
