### ISSUE TITLE
Create page: scrollbar-gutter

### ISSUE THREAD

**Issue by felipeerias** [mdn/sprints#3849]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I would like to request the creation of a page to document the standard CSS property `scrollbar-gutter`:

* https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

`scrollbar-gutter` gives control to Web authors over the presence of scrollbar gutters separately from the ability to control the presence of scrollbars (via `overflow`), allowing them to avoid layout changes when the content size changes and unwanted visuals when scrolling isn't needed.

This property has recently been implemented in Chrome ([bug #710214](https://bugs.chromium.org/p/chromium/issues/detail?id=710214)) and is already available as an experimental Web feature, so  IMHO it would be important to have it documented in MDN.

If it helps, feel free to use material from the explainer linked below. Please don't hesitate to ask if there is anything that I could do from my side to help.

References:

* Defined in the [CSS Overflow](https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property) spec
* [Explainer](https://github.com/felipeerias/scrollbar-gutter-explainer)
* [Chromium intent-to-prototype](https://groups.google.com/a/chromium.org/d/msg/blink-dev/GErJ9WbxJrU/F8N2xl1kBgAJ)
* [TAG design review](https://github.com/w3ctag/design-reviews/issues/520)

**Comment by chrisdavidmills** [comment]
Hi @felipeerias ! Thanks for submitting this to MDN. This does sound like a useful property. My only concern here is whether it might be a bit too early to document it on MDN, if it is only available experimentally in Chrome. Is there interest in implementing in other engines (Gecko/WebKit), how stable is the spec.

Any thoughts here?

Also any thoughts on this @rachelandrew ?

**Comment by rachelandrew** [comment]
@chrisdavidmills probably worth adding, it's part of Overflow 4, which is FPWD, but if there is an implementation it's probably a point at which we could doc it. There are a bunch of open issues on it: https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+scrollbar-gutter however several are on finer implementation details that won't be all that interesting to authors. 

I'm generally of the feeling that where it isn't a huge amount of work, and it looks like the property won't vanish, it's worth having these things documented as it gives people writing about them somewhere to link to.

**Comment by chrisdavidmills** [comment]
@rachelandrew OK, I'll agree to having this one documented then, thanks for the input!

@felipeerias if I create the page, are you willing to create the content for it?

**Comment by felipeerias** [comment]
@chrisdavidmills @rachelandrew : Thank you so much for your help! Yes, if you create the page, I will write the content for it.

**Comment by chrisdavidmills** [comment]
Thanks @felipeerias ! the page is now created:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

Use another CSS property page as a template for this one, and feel free to ping us to review it when you are done.

**Comment by felipeerias** [comment]
Great, thank you @chrisdavidmills !

**Comment by chrisdavidmills** [comment]
This looks done
