### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by uhri2020** [mdn/sprints#3850]
I got problem with my security on desktop.
I got archive.org account which is illegal censorshipped on child lock. There's no legal way to use child locking so could you delete it from me. The account is user: waltterikorhonen@yahoo.com.

Thanks, uhri2020

**Comment by chrisdavidmills** [comment]
Hi @uhri2020 !

This repo is for reporting errors with documentation on https://developer.mozilla.org. It sounds like you want to report a Firefox issue; the best place would be https://support.mozilla.org — see the "Get help" menu item at the top.

Best regards.
