### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/createLinearGradient

### ISSUE THREAD

**Issue by FirecYT** [mdn/sprints#3852]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/createLinearGradient

In example on Russian lang nothing.
![изображение](https://user-images.githubusercontent.com/26000286/97915849-33070d00-1d63-11eb-8ad1-92e5d59982c2.png)

**Comment by MendyBerger** [comment]
Fixed it.

Problem was that it was trying to load the example (EmbedLiveSample) with the English title instead of the Russian title.

**Comment by chrisdavidmills** [comment]
Awesome, thanks @MendyBerger !
