### ISSUE TITLE
Same origin policy - inaccurate CORS description

### ISSUE THREAD

**Issue by hamishwillee** [mdn/sprints#3853]
In [Same origin policy > how to add cross origin access](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#How_to_allow_cross-origin_access) it says 

> Use CORS to allow cross-origin access. CORS is a part of HTTP that lets servers specify what hosts are permitted to load content from that server.

@chrisdavidmills Shouldn't it be?:

> Use CORS to allow cross-origin access. CORS is a part of HTTP that lets servers specify any other hosts from which a browser should permit loading of content. 

Technically CORS also provides headers that let a browser a server whether it will allow access to a cross domain resource as a "preflight request", but that is not what this is about.

## Request type

- [ ] New documentation
- [x] Correction or update

**Comment by chrisdavidmills** [comment]
Yeah, that sounds more accurate to me.

**Comment by hamishwillee** [comment]
Cool. Done. Update as discussed at https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#How_to_allow_cross-origin_access
