### ISSUE TITLE
Associativity of conditional ternary operator on "Operator precedence" page

### ISSUE THREAD

**Issue by theonlypwner** [mdn/sprints#3854]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

This entry of the table
> 4 | Conditional | left-to-right | `… ? … : …`

should be
> 4 | Conditional | right-to-left | `… ? … : …`

because the ternary operator is right associative, which is correctly described at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator#Conditional_chains

**Comment by mikoMK** [comment]
The ternary operator is indeed right associative. This can be shown with this short example:
```
(true ? 1 : 2) ? 3 : 4 // Left part grouped: 3
true ? 1 : (2 ? 3 : 4) // Right part grouped: 1
true ? 1 : 2 ? 3 : 4 // No grouping: 1
```
The result without grouping corresponds with the result when the right part is grouped -> right associative
@chrisdavidmills I corrected the table entry
(btw.: Is it ok to @-mention you directly or is there an @-group to use?)

**Comment by chrisdavidmills** [comment]
Great stuff, thanks @mikoMK !

And yes, it's fine to @-mention me directly.
