### ISSUE TITLE
Date parsing example is confusing

### ISSUE THREAD

**Issue by daleharvey** [mdn/sprints#3856]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#To_get_Date_Month_and_Year_or_Time

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

The code used in the example 

    let [month, date, year] = ( new Date() ).toLocaleDateString().split("/")

Is liable to be broken for anyone using it in a non en-US locale as its the only locale that uses the mm/dd/yyyy format as far as I know

```
( new Date() ).toLocaleDateString()
"03/11/2020"
( new Date() ).toLocaleDateString("en-US")
"11/3/2020"
```

**Comment by MendyBerger** [comment]
Added en-US explicitly

Should work for everyone now

**Comment by chrisdavidmills** [comment]
Thanks for youer work on this, @MendyBerger , much appreciated!

@daleharvey , does this change fix your concern here?

**Comment by Lafi0** [comment]
> ## URL(s)
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#To_get_Date_Month_and_Year_or_Time
> ## Request type
> 
>     * [ ]  New documentation
> 
>     * [x]  Correction or update
> 
> 
> ## Details
> 
> The code used in the example
> 
> ```
> let [month, date, year] = ( new Date() ).toLocaleDateString().split("/")
> ```
> 
> Is liable to be broken for anyone using it in a non en-US locale as its the only locale that uses the mm/dd/yyyy format as far as I know
> 
> ```
> ( new Date() ).toLocaleDateString()
> "03/11/2020"
> ( new Date() ).toLocaleDateString("en-US")
> "11/3/2020"
> ```

**Comment by daleharvey** [comment]
Yeh its going to help people who copy and paste the code not have it broken straight away. I am not certain its a great code example to depend on formatting like that but thats definitely a more subjective opinion than a bug
