### ISSUE TITLE
Page formatting directives being displayed in EventTarget API doc

### ISSUE THREAD

**Issue by scramjet** [mdn/sprints#3861]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Page formatting directives like `{{ApiRef("DOM Events")}}` are showing in this page.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget

**Comment by chrisdavidmills** [comment]
I can't reproduce this; can you try Shift + Reloading, and seeing if you still get the issue?

**Comment by scramjet** [comment]
It's all good now. Apparently a transient glitch. Thanks for looking into it.
