### ISSUE TITLE
Unclear what other tasks can execute during `await`

### ISSUE THREAD

**Issue by meatnordrink** [mdn/sprints#3862]
# Request type
 [ ] Correction or update

# Details

* **Page:** https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

* **Issue:** Lack of clarity around the concept of "other code" being able to execute while `await` is pausing execution of your code.

* **Explanation:**
Several times in the (wonderful) async/await article, it's mentioned that "other code" may execute while `await` is pausing execution of your code. I don't think it's clear to someone at the level likely to be reading this article what this "other code" is. Is it subsequent functions in your own code? Is it browser-level tasks, like network requests? Is it other functions already on the callstack?

Examples (all of them on the page, I think): 

> This can be put in front of any async promise-based function to pause your code on that line until the promise fulfills, then return the resulting value. In the meantime, other code that may be waiting for a chance to execute gets to do so.

> The await keyword causes the JavaScript runtime to pause your code on this line, allowing other code to execute in the meantime,

> It does allow other tasks to continue to run in the meantime, but your own code is blocked.

My two best guesses are that it means functions already on the callstack can execute; or it's referring to work off the main thread like network requests.

This is a tricky thing to visualize, and I think all the clarity possible is called for. Just amending to "other tasks like X, Y, or Z" might be a big help.

**Comment by prosovskyf** [comment]
It is confusing. Would be worth rewrite and show it on example with explanation. 
It does not pause your code, it just delegate the task to process on its own without interrupting code which is being run. Also with a word "blocked". Code is not blocked, it is processing elsewhere and JS will pick it up once finished. 
@chrisdavidmills let me know if I understand it correctly and if so please assign to me, I ll rewrite some stuff and add some examples.

**Comment by chrisdavidmills** [comment]
@prosovskyf assigned; thanks for your help!

**Comment by prosovskyf** [comment]
@chrisdavidmills  please review

**Comment by chrisdavidmills** [comment]
Reviewed, and I think this solves the problem nice. Thanks @prosovskyf !

I'm closing this now, but feel free to jump in if you've got any more comments @meatnordrink

**Comment by meatnordrink** [comment]
Sorry, where would I find the new material? (Doesn't seem like it's on the live page yet?) @prosovskyf 
Thanks!
