### ISSUE TITLE
https://developer.mozilla.org/ja/docs/Web/API/Window/scrollBy

### ISSUE THREAD

**Issue by bitvalue** [mdn/sprints#3863]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/ja/docs/Web/API/Window/scrollBy

I'm not sure, if it's typo or not.
```js
window.scrollBy(X,Y);
window.scrollTo(options)
```
I think in Syntax section of scrollBy page
`window.scrollTo(options)` should be 
`window.scrollBy(options)` .

**Comment by chrisdavidmills** [comment]
Yup, a typo; fixed!
