### ISSUE TITLE
HTTP > HTTP caching: Revalidate against spec and subedit

### ISSUE THREAD

**Issue by hamishwillee** [mdn/sprints#3864]
## URL(s)

[Web technology for developers >  HTTP > HTTP caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching )

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

- Add docs for `s-max-age` (missing)
- Re-validation whole page against the spec to verify that nothing is missing.
- Subedit for English ("correct" but parts are not particularly readable for non-native speakers)

This follows on from discussion in  https://github.com/mdn/sprints/issues/3257

**Comment by Jxck** [comment]
I also wanna check and update below.

in [no-store directive section](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives
) says

> max-age=0 is already implied. Setting must-revalidate does not make sense

What is the evidence for here ? [RFC7234](https://tools.ietf.org/html/rfc7234) seems not mentioning such a thing.

**Comment by hamishwillee** [comment]
@Jxck Can you please create specific issues for specific problems. This post is for a general revalidation - easy for a specific question hidden in an issue like this to get missed.

With respect to your question though, 
- If `no-store` is set then there can be no cache record, so "Setting must-revalidate does not make sense" is correct - how can you revalidate something that isn't present in the cache?
- However "max-age=0 is already implied." is not correct as what this directive does is set when the entry goes stale - but how can an entry go stale when it isn't present?


What about if we change this ?:

FROM

> The response may not be stored in any cache. Although other directives may be set, this alone is the only directive you need in preventing cached responses on modern browsers. max-age=0 is already implied. Setting must-revalidate does not make sense because in order to go through revalidation you need the response to be stored in a cache, which no-store prevents.

TO

> The response may not be stored in any cache. Although other directives may be set, this alone is the only directive you need in preventing cached responses on modern browsers. Setting must-revalidate or max-age=0 does not make sense, because in order to go through revalidation (or mark an entry as stale) you need the response to be stored in a cache, which no-store prevents.

**Comment by Jxck** [comment]
> Can you please create specific issues for specific problems. This post is for a general revalidation - easy for a specific question hidden in an issue like this to get missed.

Oh, I misunderstood that problem around cache section should gathered in here.
I opened new issue in #3877

**Comment by hamishwillee** [comment]
No worries. I have deleted my response, and will delete this and your comment shortly :-) Thanks very much.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1460](https://github.com/mdn/content/issues/1460) via [**ZenHub**](https://www.zenhub.com/)
