### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

### ISSUE THREAD

**Issue by lookfirst** [mdn/sprints#3865]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The live example is 404

http://html5-demos.appspot.com/static/navigator.onLine.html

**Comment by chrisdavidmills** [comment]
@lookfirst Thanks for pointing it out. I've just removed the link for now.
