### ISSUE TITLE
clarification of document on Display property

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#387]
https://bugzilla.mozilla.org/show_bug.cgi?id=1427737

**Comment by estelle** [comment]
Made a few edits, but should be given to Rachel

**Comment by rachelandrew** [comment]
It looks like ericbailey has been in and added the note re: `display: contents` which was the critical issue with this document.

However this really needs a complete rewrite especially as display is going to CR. So I propose to add this to my tasks for the next sprint as it's a big chunk of work.

**Comment by rachelandrew** [comment]
Updated page and notified reporter.

**Comment by chrisdavidmills** [comment]
Yup, looks good; we can close this one.
