### ISSUE TITLE
Create new page for "@property" at-rule

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#3871]
## URL(s)

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@propery

## Request type

- [x] New documentation
- [ ] Correction or update

## Details

* https://developers.google.com/web/updates/2020/08/nic85#css-properties
* https://web.dev/at-property/
* https://wiki.developer.mozilla.org/en-US/docs/Web/API/CSS_Properties_and_Values_API

**Comment by chrisdavidmills** [comment]
Setting this as a 1 hour task; need to confirm that there's someone to create the page content after the new page is created.

**Comment by ramiy** [comment]
@chrisdavidmills I will write the content.

**Comment by chrisdavidmills** [comment]
@ramiy ok, I've assigned you, thanks for taking this.

I've created the new https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@property page.

**Comment by ramiy** [comment]
@chrisdavidmills Done. I just need your help with the **Formal Syntax**. Where do I set the syntax generated by **{{csssyntax}}**?

**Comment by chrisdavidmills** [comment]
@ramiy thanks a lot, this looks pretty good.

The content that generates the formal syntax is the relevant entry in the https://github.com/mdn/data repo. You'll have to make sure that `@property` has an entry in there.

**Comment by ramiy** [comment]
Ok, I've add the formal syntax in https://github.com/mdn/data/pull/438 based on https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule

**Comment by ramiy** [comment]
@chrisdavidmills I've also added descriptors at https://github.com/mdn/data/pull/439
