### ISSUE TITLE
Missing HTTP header-specific pages (known)

### ISSUE THREAD

**Issue by hamishwillee** [mdn/sprints#3872]
## URL(s)

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS - broken link to "Downlink"
- https://developer.mozilla.org/en-US/docs/Glossary/Client_hints

## Request type

- [ ] New documentation
- [ ] Correction or update

## Details
There are many missing HTTP header pages - as linked from URLs above. In some cases there have paragraph docs, in others there is nothing. List from the main [Headers Page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers): 
Viewport-Width
Width
Content-DPR
Origin-Isolation
X-Download-Options
X-Permitted-Cross-Domain-Policies
X-Powered-By
Last-Event-ID
Ping-To
Report-To
Sec-WebSocket-Key
Sec-WebSocket-Extensions
Sec-WebSocket-Protocol
Sec-WebSocket-Version
Accept-Push-Policy 
Accept-Signature 
Push-Policy 
Signature 
Signed-Headers 
Service-Worker-Allowed
Upgrade
X-Firefox-Spdy  
X-Pingback 
X-Requested-With
X-Robots-Tag
X-UA-Compatible

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1458](https://github.com/mdn/content/issues/1458) via [**ZenHub**](https://www.zenhub.com/)
