### ISSUE TITLE
Raising issue for the colon is used for **Three-value syntax** is bolder than the other two titles on MDN doc

### ISSUE THREAD

**Issue by YagneshP** [mdn/sprints#3873]
## URL(s)

[Flex-Css](https://developer.mozilla.org/en-US/docs/Web/CSS/flex)

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

the colon is used for **Three-value syntax** is bolder than the other two titles.

![MDN-Flex-issue](https://user-images.githubusercontent.com/29221654/98488217-e2c1fc00-21f5-11eb-919b-f9ef221e6b42.PNG)

## Solution
```diff
-<li><strong>Three-value syntax:</strong> the values must be in the following order:

+<li><strong>Three-value syntax</strong>: the values must be in the following order:
```

**Comment by hamishwillee** [comment]
Thanks @YagneshP - I've fixed this one. For trivial typographic/layout errors like this, please feel free to make the change yourself directly in the wiki. Probably easier for you than posting the issue :-)

**Comment by YagneshP** [comment]
Hi @hamishwillee! I am really new to open source. What do you mean by wiki? How can I make the change there? Thank you

**Comment by hamishwillee** [comment]
Hi @YagneshP 
So what I am saying, is that next time you see a little problem like this one you can go to the bottom of the page on which you see the problem (e.g. [Flex CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#see_also)). There you will see a list like this:
![image](https://user-images.githubusercontent.com/5368500/105658722-2d146880-5f1b-11eb-9a68-7faecc555cbc.png)

Now you could click the second link (blue arrow) and create an issue report (just like this one). What I am suggesting is that instead you click the first link (red arrow). That will take you to the source text for the affected page on github. You can edit the page directly to fix the problem you see. The third link tells you a bit more about contribution.

Hope that helps!
