### ISSUE TITLE
Incorrect description for the radio input checked attribute

### ISSUE THREAD

**Issue by zbrogz** [mdn/sprints#3875]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The description for the radio input `checked` attribute is slightly off: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#checked

Currently it says (emphasis added):

> A Boolean attribute which, if present, indicates that this radio button is the **currently** selected one in the group.

Per the [HTML spec](https://html.spec.whatwg.org/multipage/input.html#attr-input-checked), it should instead say something like this:

> A Boolean attribute which, if present, indicates that this radio button is the **default** selected one in the group.

**Comment by MendyBerger** [comment]
Setting 'checked' programmatically (e.g. with `setAttribute`) will set the checkbox to checked, so maybe the word "default" isn't the most descriptive either

**Comment by zbrogz** [comment]
The spec is a little wonky in my opinion, so I'm not totally sure what the description would be. I do think "default" or "initially" would be less confusing than "currently", however.

Note that the `checked` attribute and `checked` property are not always in sync (`element.getAttribute('checked')` vs `element.checked`). In other words, the checked attribute does not always reflect the currently selected radio.

**Comment by MendyBerger** [comment]
Sorry, my bad, discard my comment.
The fact that setting it programmatically checks the checkbox, is perfectly compatible with the term "default".

I've fixed it in the docs https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio$revision/1653437

**Comment by chrisdavidmills** [comment]
Perfect fix, thanks a lot @MendyBerger !
