### ISSUE TITLE
Create pages for Intl.Segmenter

### ISSUE THREAD

**Issue by mpcsh** [mdn/sprints#3876]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I'm working on documenting the `Intl.Segmenter` API and need several pages created. The following should be under the slug `en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter`:
* `/supportedLocalesOf`
* `/segment`
* `/resolvedOptions`

Then, there are a couple new objects that need documentation as well. The `segment` method above returns a `Segments` object, which has `containing` and `@@iterator` instance methods. `containing`, in turn, returns a `SegmentData` object, which just has several properties that need documenting. I'm not sure if these pages belong under the same slug as above, but wherever they end up I believe this should be a comprehensive list:
* `Segments`
  * `containing`
  * `@@iterator`
* `SegmentData`

Thank you in advance!

**Comment by hamishwillee** [comment]
@mpcsh Awesome. Not done this before, so hope these work for you:
- https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/supportedLocalesOf

**Comment by mpcsh** [comment]
Thank you! And I don't think it's obvious at all, so no worries. If my reading is correct, `SegmentsObject` is an internal object that's created by `CreateSegmentsObject`, but not exposed to the user (i.e. it exists only in the engine). In the spec for [`CreateSegmentsObject`](https://tc39.es/proposal-intl-segmenter/#sec-createsegmentsobject), the return value is created in step 2 from `Segments.prototype`. So by my reading, it's `Segments` that should be documented, because that's what the user will be handed back when they call `Segmenter.prototype.segment` (which calls `CreateSegmentsObject`).

So as far as the slug, how about the following, underneath the same `en-US/Docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter` as above?
- `/Segments/{containing,@@iterator}`
- `/SegmentData`

Let me know if that sounds good to you.

**Comment by hamishwillee** [comment]
@mpcsh Thanks. 
I _think_ SegmentData makes sense so created that: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/SegmentData

Yes, feels like Segments is what we should create. You originally proposed - 
```
Segments\
  containing
  @@iterator
```
Why not just `Segments` and doc those other ones inside it?

But since I lack confidence ... @chrisdavidmills what do you think?

**Comment by chrisdavidmills** [comment]
@hamishwillee I don't have a strong opinion here, except to say that we usually tend to have separate pages for symbols, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator, so create the pages for consistency's sake?

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills 
OK @mpcsh the full set created below - the last three items being the new ones. 
- [Intl.Segmenter.supportedLocalesOf()
](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/supportedLocalesOf)
- [Intl.Segmenter.prototype.segment()
](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment)
- [Intl.Segmenter.prototype.resolvedOptions()](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/resolvedOptions)
- [Intl.Segmenter.SegmentData](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/SegmentData)
- [Intl.Segmenter.Segments
](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segments)
  - [Intl.Segmenter.Segments.containing
](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segments/containing)
  - [Intl.Segmenter.Segments.containing.@@iterator](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segments/@@iterator)

**Comment by mpcsh** [comment]
those pages look great, thank you all for your input and help!
