### ISSUE TITLE
docs/Web/HTTP/Headers/Cache-Control#Directives needs updates

### ISSUE THREAD

**Issue by Jxck** [mdn/sprints#3877]
## Request type

- [ ] Correction or update

## Details

[in no-store directive section](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives) says

> max-age=0 is already implied. Setting must-revalidate does not make sense

What is the evidence for here ? RFC7234 seems not mentioning such a thing.

forked from #3864

**Comment by Jxck** [comment]
[Initial Response](https://github.com/mdn/sprints/issues/3864#issuecomment-724351051) from @hamishwillee 

> If no-store is set then there can be no cache record, so "Setting must-revalidate does not make sense" is correct - how can you revalidate something that isn't present in the cache?
However "max-age=0 is already implied." is not correct as what this directive does is set when the entry goes stale - but how can an entry go stale when it isn't present?

> What about if we change this ?:

> FROM

> The response may not be stored in any cache. Although other directives may be set, this alone is the only directive you need in preventing cached responses on modern browsers. max-age=0 is already implied. Setting must-revalidate does not make sense because in order to go through revalidation you need the response to be stored in a cache, which no-store prevents.

> TO

> The response may not be stored in any cache. Although other directives may be set, this alone is the only directive you need in preventing cached responses on modern browsers. Setting must-revalidate or max-age=0 does not make sense, because in order to go through revalidation (or mark an entry as stale) you need the response to be stored in a cache, which no-store prevents.

**Comment by Jxck** [comment]
@hamishwillee 

> If no-store is set then there can be no cache record, so "Setting must-revalidate does not make sense" is correct - how can you revalidate something that isn't present in the cache?

IIUC, `no-store` for Response works like that. but `no-store` on Request is not. 
If Request has `no-store` it means that "do not store this request and correspond response in any cache". But this is not specified behavior of revalidation, so if cache storage stores previous response, that can be Reuse for `no-store` request.
So if you also wanna Revalidate, set `must-revalidate` in request is meaningful.

> However "max-age=0 is already implied." is not correct as what this directive does is set when the entry goes stale - but how can an entry go stale when it isn't present?

I think it true, but I don't understand why `max-age=0` should mentioned here.
In Request, `max-age=0` almost meaning that `must-revalidate` or `no-cache` because client seems ignore stale response.
In Response, `max-age=0` almost meaning that `must-revalidate` or `no-store` because server seems ignore store or allow store bug immediately require revalidate.

For make all clear, separate request/response seems fine.
I listed point of view which can be alternate.

- Both request and response could have `no-store` and then request and correspond response may not be stored in any cache.
- In measure case, server specifies this directive for "do not store in any cache" meaning.
- In request, `no-store` doesn't ignore reusing response in cache, so `must-revalidate` or `no-cache` should be add together
- In request, `no-store` doesn't invalidate reused response in cache
- In response, `no-store` ignore storing in any cache, so adding more `must-revalidate`, `no-cache`, `max-age`, `public`, `private` are conflicts, say it almost meaningless.

**Comment by hamishwillee** [comment]
@Jxck Thanks. Really appreciate the discussion - this all very confusing. 

There are two cases to think about here. The first is the case where you set `no-store` on a request and there is no cached response. In this case neither the request or response are cached, and any other directive makes no sense because nothing is stored.

The second case is that you have a request with `no-store` that is satisfied by a previous response.
- `must-revalidate` **is a response (only)** - you can't set it in the request. So the behaviour is whatever was cached with the original response.
  - If it does revalidate the new response would not be stored, but I don't know if the stored response would be cleared (probably not (do you know?), and I assume the must revalidate value would stay the same in the cache).
  - If it does not revalidate then the response will just 
- you can set `max-age=0`. Does this force the cache to overwrite the stored max age of the stored resource? Or is the original store date still used? if the former, then this will force the data to become stale, which will force revalidation - so it would have an impact.

**Comment by hamishwillee** [comment]
@Jxck Yes, though the point here w.r.t. the existing docs is that `max-age=0` is not irrelevant (`must_revalidate is).

The changes I propose to make:

[Cache-Control > Preventing Caching ](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Preventing_caching)
- Add this note:
  ![image](https://user-images.githubusercontent.com/5368500/99023165-216e0280-25b8-11eb-9bbb-2878480d7272.png)

[Cache-Control > no-store](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cacheability)
- Replace top version with bottom version.
  ![image](https://user-images.githubusercontent.com/5368500/99024500-d9041400-25ba-11eb-9949-c8812f1b376f.png)

**Comment by hamishwillee** [comment]
@chrisdavidmills Can you please sanity check ^^^^

Essentially the current docs says `--no-store` is the only directive you need to stop caching of responses (i.e. setting `max-age=0` and `must-revalidate` make no sense in this context). 

However the spec says that a  `--no-store` request can still result in a cached response. In this case then a client setting `max-age=0` says revalidate, which will clear the cache. It is true that setting any other directive makes no difference - e.g. `must-revalidate` is provide by the server, and in the pre-cached resource case the request never gets to the server.

**Comment by chrisdavidmills** [comment]
@hamishwillee sounds reasonable to me.

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills 

@Jxck I have made the change as indicated above. If you have further comments let me know, otherwise I will close this tomorrow.

**Comment by Jxck** [comment]
@hamishwillee LGTM thanks!
