### ISSUE TITLE
displaySurface doc looks wrong

### ISSUE THREAD

**Issue by simajzenman** [mdn/sprints#3878]
# Request type

- [ ] Correction or update

# Details

Hello Mozilla,

I've seen in the page about MediaTrackConstraints.displaySurface (https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/displaySurface) that in the first paragraph, it says "is used to specify the type or types of display surfaces which getDisplayMedia() will let the user select among for sharing purposes.". As far as I know (and tested) there is no way to restrain the type of surface you want to allow in javascript on client side; displaySurface (as it is written in the same page) can be used to detect the type of surface for a current stream already going.

If I am wrong, I first apologies for wasting your time and would be happy to have more info.
I also tried to edit it myself but couldn't for that paragraph

In the meantime, if you know where I could find in the doc a way to identify the stream name(meaning if I share facebook tab browser, I should find "facebook" in the name of the current stream), it would really help me.

Have a great one,
Simon

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1456](https://github.com/mdn/content/issues/1456) via [**ZenHub**](https://www.zenhub.com/)
