### ISSUE TITLE
Add information about supported <value> to CSP header page

### ISSUE THREAD

**Issue by contentfree** [mdn/sprints#3879]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

At the [CSP header page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy), the directives are clearly explained but nothing is said about acceptable values. You can glean some info from the examples such as being able to specify just "https:" to only allow HTTPS requests or "none". But publishing detailed information would surely be helpful.

**Comment by MendyBerger** [comment]
Would like to take this one

**Comment by chrisdavidmills** [comment]
@MendyBerger assigned; thanks!
