### ISSUE TITLE
css transform is explicitly considered stable in CSS Snapshot 2020

### ISSUE THREAD

**Issue by rolivo288** [mdn/sprints#3883]
CSS transform is explicitly considered stable in CSS Snapshot 2020 (https://drafts.csswg.org/css-2020/), it is widely used and supported by browsers since the beginning of time. Please is it possible to remove the unstable tag and give developers peace of mind?

**Comment by chrisdavidmills** [comment]
@rolivo288 yes, sounds like a great idea. Where do we have this listed as unstable?

**Comment by rolivo288** [comment]
Hello @chrisdavidmills I just confirmed that it is only for the Spanish version here I leave the link https://developer.mozilla.org/es/docs/Web/CSS/transform

**Comment by chrisdavidmills** [comment]
@rolivo288 ah, i see - you are talking about the experimental banners.

Are you willing to help us out by removing those? Basically edit the relevant MDN pages and remove the `{{seecompattable}}` macro calls.

(If you've never contributed to MDN before, https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started will help you get started)

**Comment by rolivo288** [comment]
> Are you willing to help us out by removing those? Basically edit the relevant MDN pages and remove the `{{seecompattable}}` macro calls.

It will be a pleasure

**Comment by chrisdavidmills** [comment]
@rolivo288 great, thank you!

I've assigned you to the issue, so that you get the credit for the work.
