### ISSUE TITLE
The default value for the text shadow color is specified incorrectly.

### ISSUE THREAD

**Issue by hakantr** [mdn/sprints#3884]
## URL(s)

https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Text_drop_shadows
https://drafts.csswg.org/css-text-decor-3/#propdef-text-shadow

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

Description on the MDN page:
4-The base color of the shadow, which can take any CSS color unit. If not included, it defaults to **black**.

whereas when the color is not defined, the default value takes from the element's color value.

he color of the shadow is not specified, it defaults to currentColor, i.e. the shadow’s color is taken from the element’s color property.

Also:

Multiple shadows
```
text-shadow: 1px 1px 1px red,
             2px 2px 1px red;
```
The effect is not noticeable because the color of both shades is the same.

**Comment by chrisdavidmills** [comment]
@hakantr thanks for reporting this. I've updated it now.
