### ISSUE TITLE
Fix {{CSSxRef}}

### ISSUE THREAD

**Issue by ramiy** [mdn/sprints#3885]
## URL(s)

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

When you try to display CSS functions `{{CSSxRef("attr")}}` it shows **attr**, when you use `{{CSSxRef("attr()")}}` it shows **attr()()**.

We need to use the second parameter `{{CSSxRef("attr", "attr()")}}` to show **attr()**. This is a workaround.

Someone need to fix `{{CSSxRef}}`. When using `{{CSSxRef("attr()")}}` it should shows **attr()**.

**Comment by chrisdavidmills** [comment]
As a note on this, we are aiming to get rid of as many KumaScript macros as possible after we move to the new Yari platform, which includes rendering out macros like this and just using standard links. So it is unlikely this will be fixed.
