### ISSUE TITLE
There's a blatant spam link in the Web APIs list page

### ISSUE THREAD

**Issue by meleu** [mdn/sprints#3886]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

There's a blatant spam link in the Web APIs list page:

![spam-in-the-docs](https://user-images.githubusercontent.com/8508804/98986413-a2b78d80-2503-11eb-855f-de96cb918624.png)

https://developer.mozilla.org/en-US/docs/Web/API

**Comment by chrisdavidmills** [comment]
@meleu fixed; thanks for reporting!
