### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky

### ISSUE THREAD

**Issue by fireattack** [mdn/sprints#3887]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It says
>A regular expression defined as both sticky and global ignores the global flag.

But this doesn't seem to match my observation.
```js
console.log('##-#'.replace(RegExp('#', 'gy'), 'x'));
console.log('##-#'.replace(RegExp('#', 'y'), 'x'));
console.log('##-#'.replace(RegExp('#', 'g'), 'x'));
```

The above all have different behaviors:

```
xx-#
x#-#
xx-x
```
(And they're as expected.)

**Comment by fireattack** [comment]
Same error can be seen at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1454](https://github.com/mdn/content/issues/1454) via [**ZenHub**](https://www.zenhub.com/)
