### ISSUE TITLE
404 on https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap

### ISSUE THREAD

**Issue by ryc76** [mdn/sprints#3888]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The page has a broken link. The top panel contains
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.

    Key: pages/css/grid-row-gap.html
    RequestId: 48F9E1DBAB9B7940
    HostId: VL1UbsGYKqxPQkGVFxh8gCzN11NY+TT2BayvD3UcjDKoCxk5uNdNOB3adVf3HWeQ3Mk7+Y83l5Q=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap

![image](https://user-images.githubusercontent.com/19438429/99072840-b1a64a80-25ac-11eb-91d3-92d6a05cab00.png)

**Comment by chrisdavidmills** [comment]
@ryc76 the box-alignment spec-related examples got move recently inside the repo, and some were renamed; see https://github.com/mdn/interactive-examples/tree/master/live-examples/css-examples/box-alignment

I fixed this by updating the "grid-row-gap.html" referenc ein the macro call to "row-gap.html"

Thanks for reporting!
