### ISSUE TITLE
https://developer.mozilla.org/es/docs/Web/CSS/Especificidad

### ISSUE THREAD

**Issue by RafaelRamosR** [mdn/sprints#3890]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The title and end of the introductory paragraph on the topic of specificity were purposely mistranslated.
![imagen](https://user-images.githubusercontent.com/61805565/99132995-3bbed500-25e6-11eb-81b1-7d730b5d2a6c.png)

[Especificidad - CSS](https://developer.mozilla.org/es/docs/Web/CSS/Especificidad#wikiArticle)

**Comment by mikoMK** [comment]
It seems that someone has already reverted this change today. So this looks fine.
If you find more such errors, you can also login to MDN yourself (with your Github account) to make the necessary changes. ☺️
