### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

### ISSUE THREAD

**Issue by DaggLo** [mdn/sprints#3892]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[Operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) has [Bad link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Logical_AND) (maybe not the only one). The correct one is [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND).

**Comment by hamishwillee** [comment]
Thanks very much @DaggLo ! A bunch or the operators were pointing to the wrong place - the are all good now.

FYI this is a wiki, so if you are sure of a problem and fix we'd welcome you fixing it directly :-)
