### ISSUE TITLE
Correction 

### ISSUE THREAD

**Issue by Tatty79** [mdn/sprints#3895]
# Request type
 
- [ ] Correction or update

# Details
https://wiki.developer.mozilla.org/ru/docs/Web/CSS/padding#%D0%9E%D0%B1%D0%B7%D0%BE%D1%80

"аблосютная длина" must be "абсолютная длина"
I found this mistake 4 times in the document.

 
[
](https://wiki.developer.mozilla.org/ru/docs/Web/CSS/padding#%D0%9E%D0%B1%D0%B7%D0%BE%D1%80)

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
