### ISSUE TITLE
[JavaScript] Intl update > fractionalSecondDigits

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3897]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. The `Intl.DateTimeFormat` constructor's `fractionalSecondDigits` option.

## Related Gecko bugs

1. - [x] [Enable fractionalSecondDigits option support in Intl.DateTimeFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1645107) — already documented, so mainly just needs browser-compat-data updates, although it is worth having a think about whether the constructor options could be better exposed, e.g. somewhere on the main page rather than only on the constructor subpage? 

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Quick review
- fractionalSecondDigits is not in current spec, but it is
  - [PRd here](https://github.com/tc39/ecma402/pull/347)
  - [Documented here](https://docs.google.com/document/d/1KXbFOzTsfIHXhk0uw8p8WXIHZ1Bm1xMZXahtDOiK40Q/edit)
  - Present in [Chromium (84)](https://www.chromestatus.com/feature/5704965743968256) and (obviously) Firefox

Actions
- - [ ] Docs?
- - [ ] BCD is updated
- - [ ] Interactive example and data repos are updated if appropriate
- - [ ] Set bugs to dev-doc-complete
- - [ ] Release note
- - [ ] Firefox experimental features page (Not applicable)

**Comment by hamishwillee** [comment]
@chrisdavidmills I think this is all done - modulo you merging the interactive example.

**Comment by chrisdavidmills** [comment]
Interactive example merged, aaaaaand we can close this.
