### ISSUE TITLE
[WebAPI] MediaRecorder > Exceptions

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3898]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Exceptions thrown by the MediaRecorder API (not just the `MediaRecorder` interface necessarily)

## Related Gecko bugs

1. - [x] [Fire InvalidModificationError on track set changes](https://bugzilla.mozilla.org/show_bug.cgi?id=1581139) — pretty simple, just need to add documentation for the Exceptions thrown by the various parts of the MediaRecorder interface.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
Exception is already here: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/start - in fact all exceptions here are correct.

Updated https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaRecorderErrorEvent/error

Need to check BDC for MediaRecorderErrorEvent - the tests aren't found if I use the mdn-bcd-collector app

**Comment by vinyldarkscratch** [comment]
Happy to see that others are using the mdn-bcd-collector project!  😄 

At the moment, the collector project has disabled testing event APIs, since most of the interfaces aren't exposed on their own.  I opened https://github.com/foolip/mdn-bcd-collector/issues/799 for further discussion regarding adding tests for event interfaces.

**Comment by Rumyra** [comment]
Oh this is brill @vinyldarkscratch thank you so much, I was going to drop you an email to ask!

The app is *great* btw... and in regards to events I'll remember that for the future, so thank you! 🙏 

@chrisdavidmills I'm putting this in for review - I am still unable to change the bug to dev-doc-complete however, apologies!

**Comment by chrisdavidmills** [comment]
@Rumyra reviewed, looks great thanks! I've also set the bug to dev-doc-completed.

We were waiting for any BCD to merge, or shall we close this?

**Comment by Rumyra** [comment]
BCD has been merged :) All is good @chrisdavidmills happy to close this 👍
