### ISSUE TITLE
[WebAPI] DOM > registerProtocolHandler()

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3899]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Removal of the `registerProtocolHandler()` method's title argument (think this is just Firefox-specific)

## Related Gecko bugs

1. - [x] [Remove the title argument from registerProtocolHandler()](https://bugzilla.mozilla.org/show_bug.cgi?id=1631464) — fairly small simple update; it's listed as a web compat update in Mozilla Bugzilla, so I'm guessing this is a change to Fx only, for parity with other browsers. 

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
This is just for firefox, but I'm unsure how to show that in the docs.

I'm inclined to change the syntax to be as per spec (no title), but update notes to explain only Firefox supports the new syntax (basically swapping the current info)

Give me a thumbs up @chrisdavidmills and I'll do it :)

**Comment by chrisdavidmills** [comment]
Sounds basically good; make it clear in the notes what the old syntax is, and also add a BCD entry for it?

**Comment by Rumyra** [comment]
[DRAFT]

BCD PR is here https://github.com/mdn/browser-compat-data/pull/7432 added notes for browsers that have not updated as per spec

**Comment by Rumyra** [comment]
I'm just waiting on BCD for this one

**Comment by chrisdavidmills** [comment]
BCD reviewed, merged, and closing. Cheers @Rumyra !
