### ISSUE TITLE
Compatibility Tables are unreadable without web fonts loaded.

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#390]
From Bugzilla:

What did you do?
================
1. Open Firefox Focus (with web fonts disabled)
2. Visit https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming
3.) Scroll down and try to read the compatibility table.

What happened?
==============
The browser icons are all rendered as squares, making the table unreadbale.

What should have happened?
==========================
The browser icons should ahve been displayed still.

Is there anything else we should know?
======================================
Switching to SVG icons instead of using icon fonts would fix this issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1480106

## Acceptance Criteria

* [x] On mobile viewports, display the name of the browser as apposed to the icon

**Comment by schalkneethling** [comment]
Pull requests:

https://github.com/mdn/kumascript/pull/776
https://github.com/mozilla/kuma/pull/4948

**Comment by jwhitlock** [comment]
Mobile part of the bug is complete. Replacing webfonts on the desktop view will be more challenging, but maybe not as necessary.
