### ISSUE TITLE
[WebAPI] PerformancePaintTiming

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3900]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. PerformancePaintTiming API (mostly already done, needs BCD update and experimental banners removing)

## Related Gecko bugs

1. - [x] [implement PerformancePaintTiming](https://bugzilla.mozilla.org/show_bug.cgi?id=1518999) — [already documented](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming), mainly needs BCD updating, and experimental banners removing.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
I've created a PR for BCD here https://github.com/foolip/mdn-bcd-results/pull/1318 - but I'm interested to see how that comes back as I _think_ it just accounts for desktop FF

**Comment by Rumyra** [comment]
All that's left to do is set the bug to dev-doc-complete @chrisdavidmills

**Comment by chrisdavidmills** [comment]
> I've created a PR for BCD here [foolip/mdn-bcd-results#1318](https://github.com/foolip/mdn-bcd-results/pull/1318) - but I'm interested to see how that comes back as I _think_ it just accounts for desktop FF

Yeah, I'm not sure how this works.

**Comment by chrisdavidmills** [comment]
Set to dev-doc-complete. Thanks @Rumyra !
