### ISSUE TITLE
[WebAPI] Sanitizer API

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3902]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Sanitizer API

## Related Gecko bugs

1. - [x] [Sanitizer API incorrectly hidden behind a pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1673309) — this is actually a bug to correctly hide the Sanitizer interface behind a pref as it is being developed, but it might be nice to get this [spec](https://wicg.github.io/sanitizer-api/) documented, depending on what its status is in Chromium. 

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
Update - I've created draft pages which I need to go through, edit and add examples too 👍 This will remain in progress for the time being

**Comment by chrisdavidmills** [comment]
How is this one going @Rumyra ?

**Comment by Rumyra** [comment]
Funny you should ask - I _just_ finished the pages. Next to do is get them up and make sure all BCD, kumascript & everything is inline. This might be in 24hrs as I'm on Goog tomorrow 👍

**Comment by chrisdavidmills** [comment]
That is perfectly OK — we've still got plenty of time until the launch.

**Comment by Rumyra** [comment]
I'll be adding all the info for this tomorrow... Just one thing: I've created a demo, however it explicitely uses the config object, which has not been implemented yet. see https://wicg.github.io/sanitizer-api/#dictdef-sanitizerconfig (it's optional), so am thinking to hold off adding to demo repo for the moment (basically it doesn't work 😆)

I have documented it however and am happy to add a note for now.

**Comment by chrisdavidmills** [comment]
Yeah, just stick to code snippets for now, and add a note explaining that it doesn't work yet.

**Comment by Rumyra** [comment]
Temp checklist 

- [ ] Kumascript
- [ ] BCD
- [ ] Docs
- [ ] Bug
- [ ] Release notes
- [ ] Experimental

**Comment by Rumyra** [comment]
Vinyl is on BCD for this one - I'll update as per 👍

**Comment by chrisdavidmills** [comment]
Thanks @Rumyra , looking good so far.

**Comment by chrisdavidmills** [comment]
Did this one get finished, @Rumyra ?

**Comment by Rumyra** [comment]
dev-doc-needed flag needs to be removed from the bug (sorry I'm unable to do this)

Added BCD data myself 🤷🏻‍♀️ apologies I should have followed up on this one...
https://github.com/mdn/browser-compat-data/pull/8794

Last little thing:

- [ ] Check pages once BCD data has been merged
https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer

**Comment by chrisdavidmills** [comment]
> dev-doc-needed flag needs to be removed from the bug (sorry I'm unable to do this)

No worries, I can do that. Do you mean removed, or set to `dev-doc-complete`? The work has bene done, right? We are not cancelling the work?

**Comment by Rumyra** [comment]
😆 yes that's what I meant - I'm going to take a break now before my brain mis fires everything

**Comment by chrisdavidmills** [comment]
> 😆 yes that's what I meant - I'm going to take a break now before my brain mis fires everything

No worries, and done!

https://bugzilla.mozilla.org/show_bug.cgi?id=1673309#c11
