### ISSUE TITLE
[CSS] Enable aspect-ratio on Nightly

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3903]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Enabling of `aspect-ratio` property in Nightly (probably just Firefox-specific, but might also affect other browsers?)

## Related Gecko bugs

1. - [x] [Enable aspect-ratio on nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1672078) — see if BCD needs updating for Firefox, and any other browsers. This is really a Firefox-specific change — we are now enabling this by default on Nightly.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills updated the bug and Experimental features page, this was the BCD we were separating out a few weeks ago so that's all up to date and the change reflected on the property page.

**Comment by chrisdavidmills** [comment]
Great, reviewed, and this looks complete.
