### ISSUE TITLE
[CSS] > Grid > Masonry

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3904]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. CSS Grid Masonry experimental feature. @rachelandrew already wrote the docs for this, so this probably just involves checking the docs and updating the BCD for any browsers that have updated their support.

## Related Gecko bugs

1. - [x] [[css-grid-3] Enable masonry layout by default in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1672807)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills this was the work I did a couple of weeks ago, I just updated Experimental Features to flag it enabled in Nightly.

BCD for the new properties and values is awaiting review: https://github.com/mdn/browser-compat-data/pull/7249

**Comment by chrisdavidmills** [comment]
Thanks @rachelandrew ! I reviewed the masonry pages before, so I think we can consider that done. Experimental features page looks OK. I think once the BCD gets reviewed, we can close this.

**Comment by chrisdavidmills** [comment]
BCD merged
