### ISSUE TITLE
[Security] Mixed content and localhost 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3906]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated - *HW: pretty sure this is "not applicable"*
3. - [x] Interactive example and data repos are updated if appropriate - *HW: pretty sure this is "not applicable"*
4. - [ ] The content has been reviewed as needed

## Features to document

1. Hardcoding localhost names to the loopback address. Potentially tricky. Sounds useful, but needs figuring out in terms of where to put it, and what to say about it. See [comment 44](https://bugzilla.mozilla.org/show_bug.cgi?id=1220810#c44) for some useful context.
2. Auto upgrading of passive mixed content. Pretty Firefox-specific, unless of course other browsers are making similar changes. Maybe add some details to https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_passivedisplay_content ?
3. Browsers stopping treatment of "http://localhost/" (by name) as mixed content. Not 100% sure what needs doing here; probably needs some addition to the same page referenced in the previous item.

## Related Gecko bugs

1. - [x] [Consider hardcoding localhost names to the loopback address](https://bugzilla.mozilla.org/show_bug.cgi?id=1220810).
2. - [x] [Consider auto upgrading passive mixed content in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1633743).
3. - [x] [Stop treating "http://localhost/" (by name) as mixed content](https://bugzilla.mozilla.org/show_bug.cgi?id=1488740).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
2. - [ ] [Consider auto upgrading passive mixed content in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1633743)
   > Auto upgrading of passive mixed content. Pretty Firefox-specific, unless of course other browsers are making similar changes. Maybe add some details to [Web security > Mixed content > Mixed passive/display content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_passivedisplay_content) ?

This is an existing [experimental feature](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Upgrading_mixed_display_content) that has been changed from default off to default on in [nightly](https://hg.mozilla.org/mozilla-central/rev/5d0b324f4397#l1.13), starting from Firefox 84.

Actions:
- [ ] Update [experimental feature > Upgrading mixed display content](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Upgrading_mixed_display_content) to state that Nightly is enabled by default from 84
- [ ] Update [Web security > Mixed content > Mixed passive/display content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_passivedisplay_content) just to mention that the switch exists.

**Comment by hamishwillee** [comment]
@chrisdavidmills Nightly vs Developer

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts - lots of "planned for" - should go back and verify?


https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content - add note that you can't do this check locally mabye


https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Warnings_in_Web_Console has note

> Note: Since Firefox 55, the loading of mixed content is allowed on http://127.0.0.1/ (see bug 903966). Chrome allows mixed content on http://127.0.0.1/ and http://localhost/. Safari does not allow any mixed content.

@chrisdavidmills I'm a unclear on how things progress through release channels from nightly, through to developer, beta, release. This feature is nightly only, starting from v84 so I have added it to nightly version 84 in [experimental table](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Upgrading_mixed_display_content). My guess is that when v84 releases this is also in the developer release (so I would update that in table to 84 too). When would this appear in beta, release etc?

**Comment by hamishwillee** [comment]
@chrisdavidmills While reviewing found [Web security > See Secure contexts > Features restricted to secure contexts](https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts). The table [Secure context restrictions that vary by browser](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts#Secure_context_restrictions_that_vary_by_browser) has some "planned" options
![image](https://user-images.githubusercontent.com/5368500/99352416-b5143b80-28f6-11eb-99e6-5262b834e8e4.png)

But how can from the chromium issue can I confirm this went into Chrome 70 and not some other version.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I'm a unclear on how things progress through release channels from nightly, through to developer, beta, release. This feature is nightly only, starting from v84 so I have added it to nightly version 84 in [experimental table](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Upgrading_mixed_display_content). My guess is that when v84 releases this is also in the developer release (so I would update that in table to 84 too). When would this appear in beta, release etc?

It really depends on each individual case. It is rare that a feature is enabled in Nightly, then later in dev edition, then in beta, then later in release. Usually a feature is enabled in Nightly and/or beta, and then goes straight to being enabled in release. In which case you'd see the "ship feature x" bug, update the BCD, write the rel note, and delete the entry in the experimental features page.

Does that help? ;-)

**Comment by chrisdavidmills** [comment]
> But how can from the chromium issue can I confirm this went into Chrome 70 and not some other version.

Best thing to do is probably to ask @jpmedley (hi Joe!) Joe works for the Chrome Dev Team as a tech writer, does a bunch of MDN content, and is generally happy to help us with such issues.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Ready for review (this bit)

Reviewed, and this stuff looks good. Nice work sir!

**Comment by hamishwillee** [comment]
> It really depends on each individual case. It is rare that a feature is enabled in Nightly, then later in dev edition, then in beta, then later in release. Usually a feature is enabled in Nightly and/or beta, and then goes straight to being enabled in release. In which case you'd see the "ship feature x" bug, update the BCD, write the rel note, and delete the entry in the experimental features page.

Maybe. My concern is that, looking at the code, it triggers on "builds on nightly flag". I am just concerned that an official release would have different flags set, so this might not be executed. I'm [clarifying in the bug report](ttps://bugzilla.mozilla.org/show_bug.cgi?id=1633743#c10) but I'll proceed as though it will be in the release.

**Comment by hamishwillee** [comment]
@chrisdavidmills The second part https://github.com/mdn/sprints/issues/3906#issuecomment-728664905 on automatic upgrading is ready to review. i.e. this is all done.

Actually I just reworked the new section on [loading mixed content](https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Loading_mixed-content_resources) so it has sections that cover both these bugs. All fits together quite nicely now.

**Comment by hamishwillee** [comment]
@chrisdavidmills HOW do I set bugs to dev-doc-complete and remove the needed flag. Does not seem to be an option for me.

**Comment by chrisdavidmills** [comment]
All looks great, thanks @hamishwillee !

I've also set the bugs to dev-doc-complete. I can't figure out how to ask for the permissions you need for that.

I believe this can be closed now?

**Comment by mathewhodson** [comment]
> Maybe. My concern is that, looking at the code, it triggers on "builds on nightly flag". I am just concerned that an official release would have different flags set, so this might not be executed. I'm clarifying in the bug report but I'll proceed as though it will be in the release.

@hamishwillee The way the code is right now, the flag will be disabled in the release version of Firefox 84. You can download Firefox Beta 84 right now and see that security.mixed_content.upgrade_display_content is disabled.

There is a chance it could be enabled for 84 but probably not. It it did, the uplift would happen in https://bugzilla.mozilla.org/show_bug.cgi?id=1672106

**Comment by hamishwillee** [comment]
Thanks @mathewhodson - really appreciate you and [Christoph](https://bugzilla.mozilla.org/show_bug.cgi?id=1633743#c12) letting me know. 

@chrisdavidmills I have fixed this up. Note to you - don't include this in the release blog :-)

To "fix this up":
- I have added the feature back to [experimental features](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Upgrading_mixed_display_content)
- Removed release note :-(
  > Firefox now automatically upgrades mixed-display content from HTTP to HTTPs in secure pages. If the upgrade fails (because the media's host doesn't support HTTPS), the media is not loaded. There is also a new console warning for indicating successful content upgrades. ({{bug(1633743)}}, {{bug(1435733)}})
- For [Mixed Content](https://wiki.developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Upgrading_mixed-display_resources) I added a big fat note to say that this is an experimental feature and linked back to that doc. This way it is easy to revert to published state when [bug 1672106 goes in](https://bugzilla.mozilla.org/show_bug.cgi?id=1672106).

**Comment by chrisdavidmills** [comment]
@hamishwillee  just read this thread again; yup, all sounds good!
