### ISSUE TITLE
[WebExtensions] browsingData.remove()

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3907]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Extend `browsingData.remove()` API to remove a subset of data with `cookieStoreId`.

## Related Gecko bugs

1. - [x] [Extend browsingData.remove API to remove a subset of data with cookieStoreId](https://bugzilla.mozilla.org/show_bug.cgi?id=1670811).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by caitmuenster** [comment]
Thanks Chris! We're currently waiting for the browser-compat-table to update and for Luca to review the update to the [browsingData page](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/RemovalOptions$revision/1652552).

**Comment by caitmuenster** [comment]
@chrisdavidmills, this is done, except it looks like the BCD tables haven't been re-generated to reflect updates on production. Can you nudge someone about this?

**Comment by chrisdavidmills** [comment]
@caitmuenster hi there! I did a shift + refresh on the page to regenerate it, and the new CD is now showing. So I think can close this now. Thanks!
