### ISSUE TITLE
MIDIMessageEvent documentation has a broken link

### ISSUE THREAD

**Issue by liamappelbe** [mdn/sprints#3909]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The [MIDIMessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MIDIMessageEvent) docs point the user to the MIDI spec, but [the link is dead](https://www.midi.org/specifications/item/table-1-summary-of-midi-message). It looks like they moved that part of the spec [here](https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message).

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. Fixed now!
