### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by bitsu567** [mdn/sprints#3911]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

[Translation Error] The translation means that the property `margin: 0 auto` can control the position of h1 which is not.
![1](https://user-images.githubusercontent.com/73510290/99753724-c4c39800-2b21-11eb-9cc4-caef6997d6ac.jpg)

<img width="1073" alt="2" src="https://user-images.githubusercontent.com/73510290/99753873-22f07b00-2b22-11eb-86ff-647ce40edd94.png">

tranlation url: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/%E5%AE%9A%E4%BD%8D
origin url: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit the page yourself; https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started explains how.
