### ISSUE TITLE
 Request to create an article related to the use of UseState and Context in React

### ISSUE THREAD

**Issue by KevinJoseph** [mdn/sprints#3912]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details
because I am interested in developing articles related to the topics of use State and context in the React framework. What requirements must I meet?

**Comment by chrisdavidmills** [comment]
Hi @KevinJoseph !

Thanks for getting in touch about this. I am happy to let you have a go at writing some MDN content. The main thing that concerns me is the scope of the work, whether it works in the context of what we already have, and whether it is realistic for you to complete based on the amount of time you have available.

So I'm assuming you want to create some documentation that would go along with the following:

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks#React_tutorials 

To start with, can you elaborate on the scope of what you want to write? Subjects, number/size of articles?

Thanks!
