### ISSUE TITLE
SVGBoundingBoxOptions parameter of SVGGraphicsElement.getBBox() is not documented

### ISSUE THREAD

**Issue by theres-waldo** [mdn/sprints#3914]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [documentation page](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox) of `SVGGraphicsElement.getBBox()` suggests that the method does not have any parameters.

However, in the [SVG 2 draft spec](https://svgwg.org/svg2-draft/single-page.html#types-InterfaceSVGGraphicsElement), the method now has an optional `SVGBoundingBoxOptions` parameter. This parameter is present in Firefox's [WebIDL](https://searchfox.org/mozilla-central/rev/2efcda6dc74c63863fd8f04a6d9d7ac6b09c7eca/dom/webidl/SVGGraphicsElement.webidl#31) but the MDN documentation for it is missing.

**Comment by MendyBerger** [comment]
Think this can now be closed
