### ISSUE TITLE
https://developer.mozilla.org/es/docs/Web/CSS/::before

### ISSUE THREAD

**Issue by judithmg** [mdn/sprints#3918]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

examples result in Spanish not showing

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. The IDs passed to the live example macros were still set to the English IDs, so it wasn't finding them. I've updated them to the Spanish IDs, so they are working now.
