### ISSUE TITLE
default value for Date.UTC() month argument

### ISSUE THREAD

**Issue by voxspox** [mdn/sprints#3919]
# Request type

- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

`month` is an optional option since 2017. What is then the default value?

**Comment by mikoMK** [comment]
@voxspox According to the spec it defaults to 0. I updated MDN.

**Comment by chrisdavidmills** [comment]
Thanks @mikoMK ! I've added an "optional" badge to the parameter, and slightly tweaked the language, but I think we can call this one done.

**Comment by mikoMK** [comment]
Thanks @chrisdavidmills for improving it 👍
