### ISSUE TITLE
Change to Instruction required

### ISSUE THREAD

**Issue by vivi173** [mdn/sprints#3920]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In **Express Tutorial Part 3: Using a Database...**, there's a little issue in the section 'Testing - create some items'. 
**Step 3
Run the script using node in your command prompt, passing in the URL of your MongoDB database (the same one you replaced the insert_your_database_url_here placeholder with, inside app.js earlier): Be sure to pass it as a string by wrapping it with ' '.**

The URL should not be wrapped by ' ' in order for the query to run successfully on the command prompt. Enclosing it in ' ' throws an error.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

![image](https://user-images.githubusercontent.com/43881248/100119955-7144a780-2e9d-11eb-8158-657d22482855.png)

![image](https://user-images.githubusercontent.com/43881248/100120138-9cc79200-2e9d-11eb-9d3d-9e5d22e239a8.png)

**Comment by hamishwillee** [comment]
Thanks for reporting. It works for me either with or without '' on Ubuntu 20.04. What platform are you working on?

**Comment by vivi173** [comment]
Hi Hamish, I'm working on windows 10, version 1909.

**Comment by hamishwillee** [comment]
Thanks very much! I have removed the offending text :-). FYI only double quotes do work.
