### ISSUE TITLE
Options in demo for CSS `perspective-origin` have no effect

### ISSUE THREAD

**Issue by adamalton** [mdn/sprints#3922]
# Request type
- [ ] Bug report

# Details
On the [MDN CSS `perspective-origin` page](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin), selecting the different options in the demo has no effect.

See video: 
https://youtu.be/fSfOspWmXP8

That video was done with Firefox Developer Edition 84.0b3. The behaviour (or lack of it!) is the same in Chrome 87.0.4280.67.

**Comment by rachelandrew** [comment]
@adamalton you are correct - looks like it is missing the `perspective` property. I'll go fix that in the example though it may take a little while to be released onto the site.

**Comment by adamalton** [comment]
Great, thanks @rachelandrew.

**Comment by rachelandrew** [comment]
@chrisdavidmills this now shows up on the page so can probably be closed.

**Comment by chrisdavidmills** [comment]
Great stuff, thanks for the note.
