### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

### ISSUE THREAD

**Issue by andreElrico** [mdn/sprints#3923]
# Request type
- [x] Correction or update

# Details

[Web technology for developers > HTTP > HTTP headers > Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie)

> The Cookie HTTP request header contains stored HTTP cookies previously sent by the server with the Set-Cookie header.

When in javascript I manipulate my cookie via `document.cookie` that updated cookie is still send in the request header? So not only received by `set-cookie`?

**Comment by hamishwillee** [comment]
This is neither a correct or an update.

The simple answer is yes, see [Web/API/Document/cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie). The exception being that there are cookies you can't access in JavaScript - ie. those with HTTPOnly set when in a different origin
