### ISSUE TITLE
No promotion page found

### ISSUE THREAD

**Issue by heysujal** [mdn/sprints#3924]
# Request type

 Correction or update

# Details

[https://wiki.developer.mozilla.org/en-US/docs/MDN/About/Promote](url)

This link shows not found

**Comment by chrisdavidmills** [comment]
I deleted this because it was out of date. Did you find a link to it somewhere?

**Comment by heysujal** [comment]
@chrisdavidmills  Actually  on [mdn web docs](https://wiki.developer.mozilla.org/en-US/)  page under the **Help improve MDN** section there is a link to this page which shows **Not Found**

**Comment by chrisdavidmills** [comment]
@heysujal oops ;-)

I'll transfer this issue to the Kuma repo and ask one of the devs help me to locate this link and remove it. Thanks for reporting!

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7644](https://github.com/mdn/kuma/issues/7644) via [**ZenHub**](https://www.zenhub.com/)
