### ISSUE TITLE
[HTTP Caching] "normalization" anchor

### ISSUE THREAD

**Issue by alcar** [mdn/sprints#3926]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The "normalization" anchor inside the ["Varying responses"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#Varying_responses) section of the "HTTP Caching" page does not seem to work; it currently points to `#normalization` instead of `#Normalisation`.

It's also worth noting that there are occurrences of both "normali**z**ation" and "normali**s**ation" in that page.

**Comment by chrisdavidmills** [comment]
@alcar thanks for reporting this. I've fixed this in the source now, and it should update in the final page soon.
