### ISSUE TITLE
Correction what's in the head

### ISSUE THREAD

**Issue by kinskikick** [mdn/sprints#3928]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The french translation explain that the <script> element should be had at the end of the <body> element, just before the closing tag </body>. And there is no mention of "defer".

By the way, I downloaded both files :  meta-example.html, script.js and style.css, and follow the steps but it seems the JS code doesn't work. I downloaded the css-and-js.html example page and got the same problem : CSS worked, but not the JS.

![image](https://user-images.githubusercontent.com/47078639/100536410-b90e5a80-3220-11eb-95c6-c0a47417b48e.png)
![image](https://user-images.githubusercontent.com/47078639/100536472-1efae200-3221-11eb-8d67-93ad2868434a.png)
![image](https://user-images.githubusercontent.com/47078639/100536478-291ce080-3221-11eb-8925-a39dc8881733.png)

https://developer.mozilla.org/fr/docs/Apprendre/HTML/Introduction_%C3%A0_HTML/The_head_metadata_in_HTML

Thanks for your help.

**Comment by chrisdavidmills** [comment]
Hi there @kinskikick .

This is because the French version is out of date with the English version. The English version has the updated text that talks about `defer`.

I am not sure why your JS code is no working. I just tested it, and put the following lines in the head of the document:

```
<link rel="stylesheet" href="style.css">
<script src="script.js" defer></script>
```

And it worked fine for me. 

Have you definitely got all three files in the same directory?

**Comment by kinskikick** [comment]
Hello, Thanks for your answer.

I saw the difference in the english page. As a French contributor, maybe I have to fix it, even if I am a rookie.

About the code, I try again but it doesn't work. I inspected the source code to check it. My files are in the same directory, and similar to yours. Here some screenshot :

![image](https://user-images.githubusercontent.com/47078639/101213862-5b906880-367b-11eb-93ef-52f526704d67.png)
![image](https://user-images.githubusercontent.com/47078639/101213885-65b26700-367b-11eb-9f50-4824716620fd.png)
![image](https://user-images.githubusercontent.com/47078639/101213900-69de8480-367b-11eb-9136-756bf3c42290.png)

**Comment by chrisdavidmills** [comment]
@kinskikick ah., I think I see what the problem is. At the botto of your JavaScript file you've got a load of text that was accidentally copy and pasted in from the GitHub page.

If you delete everything from "© 2020 GitHub, Inc." downwards, save the file and try again, it should work.

**Comment by kinskikick** [comment]
Thanks, it works ! Thanks for your patience ;-)

**Comment by chrisdavidmills** [comment]
Brilliant, glad I could help.

As for the French translation being out of sync with the English one, we don't have the time on our small team to maintain translations. Would you be interested in helping to update it?

**Comment by kinskikick** [comment]
I would be glad to help the MDN translation, even if I speak english "like a spanish cow" as we say in France (ohlala, la baguette !)

I already made some changes in the content, each time I read something weird. There was some annoying mistakes in this part for exemple : https://wiki.developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

I just don't know how edit the menu. Currently, they are a mix of french and english. I try to found a tuto about that in the doc but I did'nt found it.

![image](https://user-images.githubusercontent.com/47078639/101287345-04f86b00-37f0-11eb-982e-10d26ed0e8c6.png)

**Comment by chrisdavidmills** [comment]
> I would be glad to help the MDN translation, even if I speak english "like a spanish cow" as we say in France (ohlala, la baguette !)

Heh. Your English is much better than my French, so you have my upmost respect.

> I just don't know how edit the menu. Currently, they are a mix of french and english. I try to found a tuto about that in the doc but I did'nt found it.

Yeah...the sidebar system on MDN is currently really horrible. Different sidebars are generated by diferent macros, and to edit these, you have to find the correct macro file. This particular sidebar is generated by https://github.com/mdn/kumascript/blob/master/macros/LearnSidebar.ejs, and you'll see that there are objects that contain different string translations for different locales.

The `fr` string translations start at https://github.com/mdn/kumascript/blob/master/macros/LearnSidebar.ejs#L1490

There are only a few string translations included. Any that don't have a `fr` translation available will just get the English version by default. You could add all of these string translations, but then again when we move to our new platform, we are hoping to create a good sidebar system that just works, and doesn't require all these macros ans strings. So you could just wait.
