### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

### ISSUE THREAD

**Issue by faller222** [mdn/sprints#3929]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Please check this missplaced issue https://github.com/webcompat/web-bugs/issues/62170#issuecomment-731200529

**Comment by chrisdavidmills** [comment]
H there @faller222. Apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit the page yourself; https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started explains how.
