### ISSUE TITLE
Update variable fonts information

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#393]
Update variable fonts information
Target: Fx62
Product: P1
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/View_fonts 

## Acceptance criteria 
Need to make sure we cover an updated description of:
1. - [ ] Font features tool (some information already)
2. - [ ] Variable fonts tool (we should add information about the Variable Fonts tooling once the tools exist)

## Notes from Martin
The fonts panel will get a complete redesign and will include the first editing feature for variable fonts in Fx61. I think here it's time to rewrite the docs.
The redesign you can already check out in nightly, variable fonts is currently being worked on. I'd like to emphasize in the documentation for the fonts overview the following things:
applied font(s) are underlined in rules view
hovering in rules view will give a preview tooltip
the new fonts panel has a cleaner overview of used and other fonts on the page
it clearly shows which fonts are from the system vs. loaded from a URL
the way you edit the preview text changed. there is no input field anymore, instead you have to click one of the preview texts and then it will transform to an input field that you can fill
In the next step we will add an additional fonts panel that allows editing of a specific element. We will need to explain how to get there, and what the user can do. The panel will be different depending on the kind of font applied to the selected element. You can check the mockups already here. I think it makes sense to explain to the user what is possible here.

For font tooling work, see:

https://docs.google.com/document/d/158DRk_iagmFfmqXI32syR1rbDIHz31BkN6gfUMrs-vQ/edit#heading=h.6u5wm0gb9r7u for roadmap
https://bugzilla.mozilla.org/show_bug.cgi?id=1280059 for devtools tracking
https://bugzilla.mozilla.org/show_bug.cgi?id=1302685 for CSS implementation tracking
https://mozilla.invisionapp.com/share/Z3F7OGCTK#/screens/278367863 and https://mozilla.invisionapp.com/share/Z3F7OGCTK#/screens/279202133 for devtools mockups

**Comment by irenesmith** [comment]
I have updated the fonts page with existing information. Today (8/21) I will be adding information about variable font support.

**Comment by irenesmith** [comment]
Completed the proposed new copy for the Fonts page. You can view it on my Google Drive:

[Fonts Updates](https://docs.google.com/document/d/1eAnMr5PDIdcMasuW8iPEJYb5OfVHdWD3-MLpCo0cv1k/edit?usp=sharing)

The new material starts at the heading: "View Fonts"

Click the link to "Proposed content" to get there quickly.

**Comment by chrisdavidmills** [comment]
This is looking good, @irenesmith !

We also have Jason Pamental's variable fonts guide online, just in time: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide

Feel free to reference it, as you update the fonts tooling page.
