### ISSUE TITLE
Inaccurate Example of Optional Chaining

### ISSUE THREAD

**Issue by Dectom** [mdn/sprints#3930]
# Request type
- [x] Correction or update

# Details
On the Optional Chaining Page under the "Stacking the optional chaining operator" Section

At the bottom of the example it has the following two lines
```
// … this also works with optional chaining function call
let duration = vacations.trip?.getTime?.();
```

Vacations isn't referenced anywhere else on the page neither is trip or getTime so this wouldn't work in the example given and the optional chaining would return a TypeError for non-existent root element?

![image](https://user-images.githubusercontent.com/14962862/100632726-1986c000-3325-11eb-9274-8d840c016af0.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by prosovskyf** [comment]
You are right, it is confusing to have different naming in same code block which does not refer to anything. This can be rewritten to 
`let customerName = customer.name?.getName?.(); 
console.log(customerName)` which results in undefined as expected and we keep the same example as defined object above. 
@chrisdavidmills please assign and I'll rewrite it. Thanks

**Comment by chrisdavidmills** [comment]
Sounds good @prosovskyf , assigned!

**Comment by prosovskyf** [comment]
@chrisdavidmills please review

**Comment by chrisdavidmills** [comment]
@prosovskyf looks good to me; thanks!
