### ISSUE TITLE
Show designs of HTML tags for many browsers

### ISSUE THREAD

**Issue by Lich496** [mdn/sprints#3931]
**Summary**
_What problem would this solve?_
We can know how the HTML tag looks in the other browsers without using other computers or installing many browsers.

**Audience**
_Who has this problem? Everyone? Article authors? Etc._
People who don't have mac or windows, and people who can't install a lot of browsers in their computer.

**Rationale**
_How do you know that people identified above actually have this problem?_
I heard that most of my friends have thought that they want to know how the HTML tags like <meter> or <input type="date"> looks in browsers that they don't have, when they only have macbook, windows laptop etc. I think so too.

**Workaround**
_How are the people identified above currently handling this problem?_
By using another computer. But we can't know how it looks in iPhone or android device without uploading into the server.

**Proposal**
_Do you have suggestions for solving this problem?_
Adding images of how it looks in the browsers is one way to solve.

**Additional context**
_Is there anything else we should know?_
I don't have any computer with windows OS. The number of developers who don't have any with macOS is larger than that like us. I do hope you to solve our problem.

**Comment by escattone** [comment]
cc @chrisdavidmills

**Comment by chrisdavidmills** [comment]
This is an interesting idea, but it would be a lot of work, and I'm not sure how useful really. Modern browsers tend to be pretty consistent in their default rendering of most elements these days, with obvious exceptions being elements with complex UIs like `<video controls>` or `<input type="datetime-local">`.

In such cases, it might be good to build up a little gallery of what the elements look like in different browsers.

Another thing to consider is that most professional web developers tend to immediately add custom UI over the top to get rid of rendering differences between browsers anyway, as that's what their clients want.
