### ISSUE TITLE
feComposite docs/support is a mess

### ISSUE THREAD

**Issue by PeterConstable** [mdn/sprints#3933]
# Request type

- [x] Correction or update

# Details
This pertains to the SVG feComposite element, as documented in MDN at <https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite>.

There is a complex example at the bottom of that page. Supposedly, per [CanIUse](https://caniuse.com/?search=fecomp), this is well supported in Firefox, Chrome and Edge. However, I cannot find a single implementation that reproduces the results shows at the bottom of that MDN page—not even close! Not Firefox; not Chrome; not Edge; not Adobe Illustrator...

So, I can't tell if the MDN documentation is correct, but nothing actually supports this (in spite of CanIUse reports), or if the MDN documentation is wrong.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1450](https://github.com/mdn/content/issues/1450) via [**ZenHub**](https://www.zenhub.com/)
