### ISSUE TITLE
Add new example in WebAssembly.Memory documentation

### ISSUE THREAD

**Issue by DesmondWillowbrook** [mdn/sprints#3934]
# Request type

- [X] Correction or update
- [ ] Please close this issue, I accidentally submitted it without adding any details

- [ ] New documentation

# Details

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory
(Specifically: [This](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory#Examples))

Adding another example to the Examples section of the page.
![image](https://user-images.githubusercontent.com/51814158/100701537-de889900-33c5-11eb-8aa5-3d2156a2cb8d.png)

The (2nd) paragraph (of the 1st section) mentions there being two ways to access the Web Assembly Memory, specifically:
- Importing it from Javascript
- Exporting it from Web Assembly

However, the paragraph talks about the second method and immediately swerves to a complete example showcasing the first.
The second example is not explained.

# Changes to be made:

> There are two ways to get a WebAssembly.Memory object. The first way is to construct it from JavaScript. The following example creates a new WebAssembly Memory instance with an initial size of 10 pages (640KiB), and a maximum size of 100 pages (6.4MiB). Its buffer property will return an ArrayBuffer.

Fine the way it is.

> The second way to get a WebAssembly.Memory object is to have it exported by a WebAssembly module.  The following example (see memory.html on GitHub, and view it live also) fetches and instantiates the loaded memory.wasm byte code using the WebAssembly.instantiateStreaming() method, while importing the memory created in the line above. It then stores some values in that memory, then exports a function and uses it to sum some values.

Delete the first line.

Then add a new paragraph.
> The second way to get a WebAssembly.Memory object is to have it exported by a WebAssembly module. This memory can be accessed in the `exports` property of the Web Assembly instance (after the memory is exported within the Web Assembly module).

Even a paragraph pointing someone in the right direction for the second method would be helpful, I think. There's not much need to make a full-blown example, since exporting Web Assembly memory is trivial (I think). Otherwise, we can include an S-expression that shows how to do it.
```wat
(memory (export "memory") 1)
```

This is my first time contributing here, please let me know if I did something wrong!

**Comment by chrisdavidmills** [comment]
Thanks for the report, @DesmondWillowbrook !

Your fix suggestion looks good to me. You are welcome to edit the page yourself, if you like.

**Comment by DesmondWillowbrook** [comment]
Yes, I tried to do exactly that, but couldn't find where the page was
hosted. Could you please point it out to me?

**Comment by Cimeone** [comment]
Here's a link to the page @DesmondWillowbrook, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory, once you're signed in you'll be able to edit the page, let me know if instead you'd like me to do this for you!

**Comment by DesmondWillowbrook** [comment]
I did it! I also added another shorter example to elucidate the usage. Should I make a complete example for the second method or is this much enough?

**Comment by chrisdavidmills** [comment]
@DesmondWillowbrook that looks great, thanks for your contribution!
