### ISSUE TITLE
Where is the page for Function.prototype.prototype?

### ISSUE THREAD

**Issue by ugultopu** [mdn/sprints#3936]
The `prototype` instance property on a function instance allows that function to be used as a constructor. Although the `prototype` property is mentioned in the [new operator] page as:

> You can add a shared property to a previously defined object type by using the [Function.prototype] property. This defines a property that is shared by all objects created with that function, rather than by just one instance of the object type. The following code adds a color property with value "original color" to all objects of type Car, and then overwrites that value with the string "black" only in the instance object car1. For more information, see [prototype][Function.prototype].

Both links point to the same URL which goes to nowhere. That is, the [Function.prototype] page is not present and it simply redirects to the [Function] page.

This is a big omission if I'm not missing something.

[new operator]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
[Function.prototype]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype
[Function]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1449](https://github.com/mdn/content/issues/1449) via [**ZenHub**](https://www.zenhub.com/)
