### ISSUE TITLE
Add support for touch events to violent theremin demo

### ISSUE THREAD

**Issue by normanr** [mdn/sprints#3937]
It would be nice to be able to use the demo in a touch environment (eg: phone or tablet). (Not required: sound could be continuous after a 'start/down' event until an 'end/up' event is received)

**Comment by normanr** [comment]
(side-note: the event listeners for triggering `init` should be removed in `init`, otherwise using the keyboard causes init to be triggered multi times, and `DOMExceptions` when trying to remove the `startMessage` that has already been removed).

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1448](https://github.com/mdn/content/issues/1448) via [**ZenHub**](https://www.zenhub.com/)
