### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/charCodeAt

### ISSUE THREAD

**Issue by jbdemonte** [mdn/sprints#3941]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link to `codePointAt` in the description is wrong : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/codePointAt()

It would be updated to https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/codePointAt

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/charCodeAt

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. You are more than welcome to edit the page yourself; https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started explains how.

**Comment by jbdemonte** [comment]
ofc, normal
I modified it
thanks

**Comment by chrisdavidmills** [comment]
Thank you for your help.
