### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs

### ISSUE THREAD

**Issue by gabrielsbrl** [mdn/sprints#3944]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

# Details
Actually, the better way to work with the play and pause action, is to save the play promise in a variable, and just do the pause action when you know that the promise have been resolved, otherwise an error may appear, saying that you tried to pause a video that wasn't ready to be paused. The article didn't explained that the play action is asynchronous.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1446](https://github.com/mdn/content/issues/1446) via [**ZenHub**](https://www.zenhub.com/)
