### ISSUE TITLE
Some source codes in "Unconventional controls" page not highlighted!

### ISSUE THREAD

**Issue by Rabios** [mdn/sprints#3947]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Yep, Here we go again! ;)

This page source codes not highlighted, At least one JavaScript source code highlighted but other JavaScript source codes not highlighted...

Link: https://developer.mozilla.org/en-US/docs/Games/Techniques/Control_mechanisms/Other

**Comment by Scttpr** [comment]
Hi @chrisdavidmills, as we discussed on Element I fixed it directly with the wiki ! I'm super proud, it is my first - super small - contribution

**Comment by chrisdavidmills** [comment]
@Scttpr this looks fixed now, just perfect! thank you so much for your contribution, and I'm glad you are happy ;-)
