### ISSUE TITLE
Source codes of "Mobile accessibility" page not highlighted!

### ISSUE THREAD

**Issue by Rabios** [mdn/sprints#3948]
## URL(s)
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Mobile

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
Hi again!

So yep i found another page with no source codes highlighting...

Link above, Go for it!

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
