### ISSUE TITLE
Short tutorial for Array methods in JS

### ISSUE THREAD

**Issue by shivamrathi99** [mdn/sprints#3955]
## Request type

- [ * ] New documentation
- [ ] Correction or update

## Details

Hi, i just made a short document of the popular and most used array methods in JS. You can add it in the MDN docs, if you like it.

[Array methods.pdf](https://github.com/mdn/sprints/files/5667741/Array.methods.pdf)

Let me know if you like me to add something, or it needs correction. 

Thanks.

**Comment by chrisdavidmills** [comment]
Thanks for sharing. I don't think we want to put this on MDN — we already have this information on site, albeit it in a different form/structure.
