### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

### ISSUE THREAD

**Issue by quirky23** [mdn/sprints#3956]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

There is an extraneous comma in the sentence in the attached screenshot. It should read "To sum up the values contained in an array of objects,..."

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
![sumup](https://user-images.githubusercontent.com/73012472/101704088-96aee500-3a49-11eb-8949-75728d0a5a56.JPG)

**Comment by chrisdavidmills** [comment]
Fixed, thanks for reporting.
