### ISSUE TITLE
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Function/apply

### ISSUE THREAD

**Issue by fpierrat** [mdn/sprints#3957]
# Request type
- [x] Correction or update

# Details
Section "Examples", first example
=> definition of a method named "construct()":  
  
`Function.prototype.construct = function (aArgs) {...}`

=> use case: call of a method named "constructor()":
```
function MonConstructeur () {...}
...
var monInstance = MonConstructeur.constructor(monTableau);
```

Either I haven't understood anything at all, or the method which should be called is "construct()":

`var monInstance = MonConstructeur.construct(monTableau);`

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Function/apply

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1440](https://github.com/mdn/content/issues/1440) via [**ZenHub**](https://www.zenhub.com/)
