### ISSUE TITLE
updation

### ISSUE THREAD

**Issue by shivamrathi99** [mdn/sprints#3958]
## URL(s)

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts

## Request type

- [ ] New documentation
- [ * ] Correction or update

## Details

it would look good if you can just run the live demo in another tab instead of on the current working tab of the browser. (use target= _blank or something), 
for eg, in one instance 
In our simple-sync.html example (**see it running live)**

this should present live demo on a new tab. thanks.

**Comment by chrisdavidmills** [comment]
Weeeeell, I can see the utility in this, but at the same time using `target= "_blank"` is generally not seen as a good practice, and it is usually better to give the user control over how they use links in their browser (and you can do Ctrl + click to open in a new tab easily enough). Plus for consistency we'd have to make this change for every demo link on the site. I don't think this is a good use of our time right now.
