### ISSUE TITLE
Please remove pages in Japanese which is removed in English

### ISSUE THREAD

**Issue by anatawa12** [mdn/sprints#3959]
# Request type

- [x] Correction or update

# Details

There are some guide pages that are removed in English and other languages but still exist in Japanese. Please remove those Japanese pages.

Those pages are removed in English and other pages but still be in Japanese.
- [例外処理文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Exception_Handling_Statements)
  - [try...catch 文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Exception_Handling_Statements/try...catch_Statement)
  - [throw 文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Exception_Handling_Statements/throw_Statement)

**Comment by chrisdavidmills** [comment]
@anatawa12 deleted. Thank you for reporting this.
