### ISSUE TITLE
Use of regex global flag in String.prototype.replace method example

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3960]
@185driver commented on [Fri Dec 11 2020](https://github.com/mdn/kuma/issues/7675)

# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

# Details

In line 3 of the JavaScript Demo near the top of the page, the regex code line is `const regex = /dog/gi;`.
I would suggest that given the page relates to the `replace` method (and not `replaceAll`), the regex global flag should be removed to read `const regex = /dog/i;`. Doing so would provide a consistent expected output result for both examples.

I think the usefulness of this small change becomes more apparent after comparing this page with the `replaceAll` method [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll). The use of the regex global flag seems more appropriate in the latter than in the former.

Thanks for considering.

**Comment by MendyBerger** [comment]
I think a few more changes would make sense:
* The string example should probably be before the regex example, as I assume most people coming to this page are more interested in the string replacement.
* The `/g` global flag in the `replaceAll` example is redundant as global search is what `replaceAll` is all about.

Hope you don't mind me chiming in :)

**Comment by chrisdavidmills** [comment]
Assigned; cheers @MendyBerger !

**Comment by MendyBerger** [comment]
Turns out that my point about `replaceAll` together with `/g` being redundant is wrong

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#Non-global_regex_throws

**Comment by MendyBerger** [comment]
Think this is resolved now
