### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

### ISSUE THREAD

**Issue by tlebon** [mdn/sprints#3964]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The 'iteration' row of the table comparing objects and maps has an issue for objects. It reads:

> Iterating over an Object requires obtaining its keys in some fashion and iterating over them.

not necessarily true. In the same way maps are iterable with a for..of loop, so are objects with the for ...in, as of ES6.
source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by hamishwillee** [comment]
Thanks! I updated the section as shown:



The for...in statement iterates over all enumerable properties of an object that are keyed by strings (ignoring ones keyed by Symbols), including inherited enumerable properties.

**Comment by tlebon** [comment]
seems nice to me.
