### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

### ISSUE THREAD

**Issue by custs21113** [mdn/sprints#3965]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I found **an editorial error**.
“The  Promise.all () method takes an **iterable** of promises as an input, and returns a single Promise that resolves to an array of the results of the input promises.”
This sentence is Iterable in the original text, but it is wrongly typed as **"idterable"** in the **Chinese version.**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by hamishwillee** [comment]
Hi, 
Generally speaking the MDN team do not have bandwidth to fix translations (in this case I did). In future please free to edit the page and fix these things yourself!
