### ISSUE TITLE
Problem with rendering HTML code

### ISSUE THREAD

**Issue by ap-r** [mdn/sprints#3966]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

I have encountered a strange problem. I was on page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing
and the HTML code was shown with broken tags. All closing tags were wrong. Instead of "`...</p>`" it would be "`...p>`" resulting in not valid code. After refreshing it looks good, but I thing you should know that it may occur. I guess it is not an issue with this lesson particulary but with something that processes HTML code.

**Comment by chrisdavidmills** [comment]
Thanks for reporting. We did fix some stuff around this a while ago, so it is probably ok now.
