### ISSUE TITLE
Change cookbook url

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3968]
### Example
https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Pagination

## Request type

- [ ] New documentation
- [X] Correction or update

## Details
I really like the term recipe book which conceptually conveys the idea. Could you change the url to make it more concise? 

### from
`/docs/Web/CSS/Layout_cookbook/Pagination`

### to
`/docs/web/CSS/cookbook/pagination`

**Comment by chrisdavidmills** [comment]
@rachelandrew is currently doing some work on thinking about how to represent more cookbook type material on MDN. Where there are multiple cookbooks, we'll have to think about how to represent the URLs.

**Comment by chrisdavidmills** [comment]
But I'm closing this for now. We'll open a more general issue to deal with this when the time comes.

**Comment by mattiapontonio** [comment]
Some design in the concept of cooking should be intresting 👍👨‍🍳👩‍🍳🔪🍗🍙🍲🍳🌮🌯🍚
