### ISSUE TITLE
Please do a recipe for responsive tables

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/sprints#3969]
![Screenshot_20201215-001911.png](https://user-images.githubusercontent.com/44380480/102147564-3d8cea00-3e6b-11eb-8a24-2754e6580f7e.png)

    https://developer.mozilla.org/en-US/search?q=responsive+tables

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1438](https://github.com/mdn/content/issues/1438) via [**ZenHub**](https://www.zenhub.com/)
