### ISSUE TITLE
Description in "Math.floor()" function: Wrong words in Korean

### ISSUE THREAD

**Issue by vortrefflich** [mdn/sprints#3971]
# Request type
- [ ] New documentation
- [x] Correction or update

# Details

 **Description about Math.floor() in Korean:
  "Math.floor() 함수는 주어진 숫자와 같거나 작은 정수 중에서 가장 큰 수를 반환합니다."**

It was totally wrong.
**It means "The Math.floor() function returns the largest number which is an integer less than given number or equal to a given number." in English.**
The sentence should be replaced with :
   "The Math.floor() function returns the largest integer less than or equal to a given number."

In Korean, the correct sentence would be:
 **"Math.floor() 함수는 주어진 숫자와 같거나 작은 수 중에서 정수에 해당하는 가장 큰 수를 반환합니다."**
or
 **"Math.floor() 함수는 주어진 숫자와 같거나 작은 수 중에서 가장 큰 정수를 반환합니다."**

URL: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/floor

**Comment by hamishwillee** [comment]
@vortrefflich Could you create a PR for this and link here? The MDN don't have bandwidth (or translation skills) to maintain translations.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
