### ISSUE TITLE
Page "WebGL best practices" source codes not highlighted!

### ISSUE THREAD

**Issue by Rabios** [mdn/sprints#3972]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Yep and again, As it's my favorite work to find pages with non-highlighted code...

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

**Comment by MendyBerger** [comment]
Have an existing PR for this mdn/content/pull/132 ;)

**Comment by Rabios** [comment]
@MendyBerger Nice!

**Comment by MendyBerger** [comment]
Think this can now be closed

**Comment by Rabios** [comment]
@chrisdavidmills @MendyBerger OK...
