### ISSUE TITLE
Move issues #1695 and #1694 back into the mdn/sprints or mdn/data repo

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/sprints#3973]
@Elchi3 moved issues [#1695](https://github.com/mdn/sprints/issues/1695) and [#1694](https://github.com/mdn/sprints/issues/1694) from here into [mdn/kumascript#1378](https://github.com/mdn/kumascript/issues/1378) and [mdn/kumascript#1379](https://github.com/mdn/kumascript/issues/1379), but they should’ve been kept here (or moved to [**@mdn/data**](https://github.com/mdn/data)), because mdn/kumascript has now been archived, but [#1695](https://github.com/mdn/sprints/issues/1695) is still unresolved, as [**@mdn/data**](https://github.com/mdn/data) still has outdated and missing:

- `InterfaceData.json` (tracked in: [#1694](https://github.com/mdn/sprints/issues/1694))
- `GroupData.json`
- `SpecData.json` (PR <https://github.com/mdn/data/pull/397>)
- `SVGData.json`

Since [**@mdn/data**](https://github.com/mdn/data) is used by [**@mdn/yari**](https://github.com/mdn/yari), these issues still apply.

**Comment by Elchi3** [comment]
Hey @ExE-Boss good to here from you again!
I guess alternatively we can always file new issues and refer to old / archived ones as needed. I don't seem to be able to move this back.

**Comment by ExE-Boss** [comment]
The [**@mdn/kumascript**](https://github.com/mdn/kumascript) repository would need to be temporarily un‑archived.

**Comment by chrisdavidmills** [comment]
I think filing a new issue on yari will be best here. Bear in mind that eventually we'll get rid of KS macros, so this issue would be about moving the data files into Yari and making use of them in whatever way would make sense for a new feature set.
