### ISSUE TITLE
Possible error translation

### ISSUE THREAD

**Issue by ejgutierrez74** [mdn/sprints#3976]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ x] Correction or update

https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/throw : Ejemplo: Lanzar un objeto

# Details

try {
   // sentencias para try
   nombreMes = getNombreMes(miMes);
} catch (excepcion) {
   nombreMes = "desconocido";
   registrarMisErrores(excepcion.mensaje, excepcion.nombre); // pasa el objeto exception al manejador de errores
}

try {
   // sentencias para try
   nombreMes = getNombreMes(miMes);
} catch (excepcion) {
   nombreMes = "desconocido";
   console.error( excepcion.mensaje, excepcion.nombre); // pasa el objeto exception al manejador de errores
}

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
