### ISSUE TITLE
Page not found (MDN Web Docs in russian)

### ISSUE THREAD

**Issue by metacortexplus** [mdn/sprints#3979]
At least these 3 links at https://developer.mozilla.org/ru/docs/Web/JavaScript leads to "Page not found" :

https://developer.mozilla.org/ru/docs/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/First-class_Function
https://developer.mozilla.org/ru/docs/Web/JavaScript/%D0%9E_JavaScript
https://developer.mozilla.org/ru/docs/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/Prototype-based_programming

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations at the moment. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
