### ISSUE TITLE
Page not found: broken link at /Web for accessing code snippets

### ISSUE THREAD

**Issue by fearandtrembling** [mdn/sprints#3980]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web

## Request type
- [ ] New documentation
- [x] Correction or update

## Details

The link for the code snippets page(https://developer.mozilla.org/en-US/docs/Code_snippets) at https://developer.mozilla.org/en-US/docs/Web isn't working

The error:  Page not found
Sorry, the page /en-US/docs/Code_snippets could not be found.

**Comment by chrisdavidmills** [comment]
Thanks for reporting; fixed by https://github.com/mdn/content/commit/dea99f433199473342fa8994c8843b88efac2560

I also replaced the link to the Apps docs section to point to the PWA section instead.
