### ISSUE TITLE
Incorrect URL for HTML Drag and Drop API Events

### ISSUE THREAD

**Issue by mkarkachov** [mdn/sprints#3984]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Links of drag and drop events in sidebar on https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API  redirect to "Page not found" (ie: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event)
Actual content is on https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event

![Selection_004](https://user-images.githubusercontent.com/1360242/104120918-31e5f380-5343-11eb-958f-45a46a2605d6.png)

**Comment by chrisdavidmills** [comment]
These links are generated from the data inside our `GroupData.json` — see https://github.com/mdn/yari/blob/master/kumascript/macros/GroupData.json#L782

Whoever fixes this would need to replace `HTMLElement` with `Document` in each case.

@mkarkachov , do you fancy having a go at fixing this?

**Comment by mkarkachov** [comment]
> These links are generated from the data inside our `GroupData.json` — see https://github.com/mdn/yari/blob/master/kumascript/macros/GroupData.json#L782
> 
> Whoever fixes this would need to replace `HTMLElement` with `Document` in each case.
> 
> @mkarkachov , do you fancy having a go at fixing this?

gladly

**Comment by chrisdavidmills** [comment]
> > These links are generated from the data inside our `GroupData.json` — see https://github.com/mdn/yari/blob/master/kumascript/macros/GroupData.json#L782
> > Whoever fixes this would need to replace `HTMLElement` with `Document` in each case.
> > @mkarkachov , do you fancy having a go at fixing this?
> 
> gladly

great, thanks!

**Comment by mkarkachov** [comment]
@chrisdavidmills  Created pull request https://github.com/mdn/yari/pull/2451

**Comment by chrisdavidmills** [comment]
Cool, PR reviewed and merged, so we should see the update in 24 hours or so.

**Comment by chrisdavidmills** [comment]
Congrats on your first MDN contribution, and thanks!
