### ISSUE TITLE
Inspector gives incorrect Mozilla docs link for ScrollLinkedEffects performance

### ISSUE THREAD

**Issue by Scrabble96** [mdn/sprints#3989]
# Request type
- [ ] Correction or update

# Details
I use a JavaScript file to create a 'back to top' icon and function when visitors scroll beyond 350px. In the Firefox (84.0.2 64-bit) Console there was, unsurprisingly, a message about this: 

"This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!"

However, if you go to that URL - [https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects](url) - you get a 404 error. The correct URL is [https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects](url)

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1532](https://github.com/mdn/content/issues/1532) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1533](https://github.com/mdn/content/issues/1533) via [**ZenHub**](https://www.zenhub.com/)
