### ISSUE TITLE
bug 1404669: Fix redirect=no

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#399]
# User story
As a MDN maintainer, I want to remove duplicate content for redirects, to avoid SEO issues.

# References
* [bug 1404669](https://bugzilla.mozilla.org/show_bug.cgi?id=1404669)

# Acceptance criteria
- [x] ``?redirect=no`` displays the redirect text, not duplicate content

**Comment by escattone** [comment]
I submitted the following PR's that comprise the fix:
- https://github.com/mozilla/kuma/pull/5172 (for the development env, also adds regression tests)
- https://github.com/mdn/infra/pull/168 (for the stage and prod environments)

and also a small PR for kumascript that does some cleanup:
- https://github.com/mdn/kumascript/pull/1032

**Comment by jwhitlock** [comment]
Reducing estimate since review is remaining work

**Comment by jwhitlock** [comment]
Regeneration completed on 1/17, details on 
[bug 1404669](https://bugzilla.mozilla.org/show_bug.cgi?id=1404669#c10).

**Comment by escattone** [comment]
Thank you @jwhitlock!
