### ISSUE TITLE
small UI issue on Operators/this page for russian language

### ISSUE THREAD

**Issue by Labean1** [mdn/sprints#3990]
# Request type
- [x ] Correction or update

# Details
Right text alignment for russian language, must be left, just remove dir="rtl" to fix this

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this

![2021-01-29_12h43_24](https://user-images.githubusercontent.com/34482614/106265520-d61ad600-622f-11eb-8043-051ea57a934c.png)

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
