### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Cache/add

### ISSUE THREAD

**Issue by julienw** [mdn/sprints#3991]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

All methods of the Cache API (for example [Cache.add](https://developer.mozilla.org/en-US/docs/Web/API/Cache/add)) are marked as experimental, not to be used in production. But they're implemented in a lot of browsers and the only way to implement offline support now that appcache is being removed.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/browser-compat-data/pull/9149 with a fix
