### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

### ISSUE THREAD

**Issue by alterego707** [mdn/sprints#3993]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Incorrect and confusing text on the English version of "Object prototypes" page:
"The former is the property on each instance, and the latter is the property on the constructor. That is, Object.getPrototypeOf(new Foobar()) refers to a different object than Foobar.prototype."
They actually refers to the same object.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

**Comment by hamishwillee** [comment]
@chrisdavidmills This may seem familiar ...

**Comment by chrisdavidmills** [comment]
@hamishwillee yup, I know we discussed this before...I just couldn't find the previous issue ;-)

**Comment by hamishwillee** [comment]
@chrisdavidmills I was teasing :-) Duplicate-ish here https://github.com/mdn/content/issues/1491 and my whinge here https://github.com/mdn/content/pull/1890#issuecomment-770572970

**Comment by alterego707** [comment]
This part of the article lacks a graphic illustration like this one:
http://dmitrysoshnikov.com/wp-content/uploads/2017/11/js-constructor.png (taken here http://dmitrysoshnikov.com/ecmascript/javascript-the-core-2nd-edition/).
A drawing like this can perfectly demonstrate the difference between __proto__ and the .prototype constructor property, etc.

**Comment by chrisdavidmills** [comment]
I believe this wording got fixed.
