### ISSUE TITLE
There are dead Links all over the place

### ISSUE THREAD

**Issue by DanielOberlechner** [mdn/sprints#3995]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [X] Correction or update

I use the German wiki to lookup my things I need.

# Details

https://developer.mozilla.org/de/docs/Web/Events/load
Here the Links on the bottom of the page don't work because there is a fragment too much in the url.
If you remove the wrong fragment the link suddenly works.

Then I tried to fix it manually but the Feedback site is broken as well:
https://developer.mozilla.org/de/docs/MDN/Contribute/Feedback
Here I tried to click to "Editor" but it wouldn't work.

https://developer.mozilla.org/de/docs/Web/Events/load -> at the bottom like "Related Events"
https://developer.mozilla.org/de/docs/MDN/Contribute/Feedback -> The "Editor" Link Text

I hope I can make things a little bit better, while reporting bugs like these.
Thank you for your good work!

Kind regards,
Daniel Oberlechner

**Comment by chrisdavidmills** [comment]
Hi @DanielOberlechner 

Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
