### ISSUE TITLE
Promise.any not defined

### ISSUE THREAD

**Issue by deepanshu44** [mdn/sprints#3996]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any

## Request type

- [ ] New documentation
- Correction or update

## Details

Console says Promise.any() not defined
![Promise any](https://user-images.githubusercontent.com/62979448/108199311-d1688400-7142-11eb-8038-84ac29d19b39.png)

**Comment by chrisdavidmills** [comment]
This works for for me; are you using a browser that supports `Promise.any()`? Check it out in the compat table: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#browser_compatibility

**Comment by deepanshu44** [comment]
I am using firefox browser
![firefox](https://user-images.githubusercontent.com/62979448/108204135-679fa880-7149-11eb-80b2-53db97d79bdd.png)

**Comment by chrisdavidmills** [comment]
Which version of Firefox are you using? It works fine for me in Firefox.

**Comment by deepanshu44** [comment]
Updated and solved the problem
Thanks
