### ISSUE TITLE
Small typo in spanish version

### ISSUE THREAD

**Issue by NicoMazitelli** [mdn/sprints#3999]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/es/docs/Web/API/Element/scrollLeft  
There's a typo in the spanish version, it says "Síntasix" instead of "Sintaxis".

Sory if this channel wasn't meant for translation issues.

Cheers

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to non-tier 1 locales. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

Spanish might be promoted to tier 1 in the future, if we can find a volunteer team to work on it. Translated content is kept at https://github.com/mdn/translated-content
