### ISSUE TITLE
Document RTCRTPStreamStats

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#40]

**Comment by chrisdavidmills** [comment]
This bug also needs to be kept in mind and DDC'ed when appropriate — [Rename RTCRTPStreamStats to match the spec RTCRtpStreamStats](https://bugzilla.mozilla.org/show_bug.cgi?id=1480498)

**Comment by chrisdavidmills** [comment]
This one also needs sorting at the same time: [getStats: kind is missing from RTPStreamStats](https://bugzilla.mozilla.org/show_bug.cgi?id=1481851)

**Comment by chrisdavidmills** [comment]
This one also needs sorting at the same time: [getStats: kind is missing from RTPStreamStats](https://bugzilla.mozilla.org/show_bug.cgi?id=1481851)

**Comment by a2sheppy** [comment]
This is finished, including the two notes from @chrisdavidmills above.

**Comment by chrisdavidmills** [comment]
Awesome, nice one sheppy!
