### ISSUE TITLE
Translation Issue: "Caixxa".

### ISSUE THREAD

**Issue by AlessandroAlmadaLeal** [mdn/sprints#4003]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hi guys!

In the image below shows the word "Caixxa", written with double "x". On Brazilian grammar the correct must be "Caixa".

![was-Caixxa-to-Caixa](https://user-images.githubusercontent.com/60022798/114338813-3f6d6e00-9b2a-11eb-9573-3cc6aa650417.jpg)

URL: https://developer.mozilla.org/pt-BR/docs/Tools/Network_Monitor

**Comment by chrisdavidmills** [comment]
Apologies, but we are not accepting changes to this locale right now; see https://github.com/mdn/translated-content#tier-1-locales for an explanation of which locales are currently active, and why. https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1 is also useful.
