### ISSUE TITLE
Wrong text color in the buttons with Russian language

### ISSUE THREAD

**Issue by ksbulgakov** [mdn/sprints#4006]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Strings
![image](https://user-images.githubusercontent.com/27681583/119823477-2c093d00-bef5-11eb-84d1-eaa92a3f7383.png)

**Comment by hardikshah197** [comment]
May I take this issue @ksbulgakov ? if no one is working on it.

**Comment by ksbulgakov** [comment]
@hardikshah197  I suppose yes. I've only reported it.

**Comment by hardikshah197** [comment]
![bbbbb](https://user-images.githubusercontent.com/54437046/122551470-a50e3700-d052-11eb-8f7c-d1a95679930b.png)


I guess, this issue need to be closed as this button lies at two place and it seems as show above.
