### ISSUE TITLE
Data not parsed in the CSP documentation: connect-src

### ISSUE THREAD

**Issue by owalid** [mdn/sprints#4015]
## URL(s)

https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

<img width="1200" alt="Screen_shot" src="https://user-images.githubusercontent.com/28403617/142739828-f9e8db32-1622-4169-b5d4-9b8b09b2e65b.png">

**Comment by bsmth** [comment]
I'm closing this one as fixed. Thank you :)
