### ISSUE TITLE
Missing link to video

### ISSUE THREAD

**Issue by AQbernhard** [mdn/sprints#4017]
- [X] Correction or update

# Details
On https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension there are two videos, but the links are not correct.

**Comment by JayedRafiProjects** [comment]
I can fix this. but why the page showing video is made private?

**Comment by caugner** [comment]
The German locale has been retired, so this is no longer an issue.

Transferring to mdn/translated-content and closing as wontfix.
