### ISSUE TITLE
Have no issue - I have a question

### ISSUE THREAD

**Issue by kingainez** [mdn/sprints#4021]
I read the article: " Wprowadzenie do Express/Node" on https://developer.mozilla.org/pl/docs/Learn/Server-side/Express_Nodejs/Introduction#w_tym_module. 
I don`t know who wrote that, but I was so impressed, about the text editor, used by a writer to shows the code examples ... etc.  
![image](https://user-images.githubusercontent.com/76117370/158415733-a39316d6-5876-48e0-bd91-314be6f9ae74.png)

Therefore, I would like to ask:  Which text editor he used (name of the theme, setup ... etc). I love these colors of syntax.

Regards, 
Kinga

**Comment by hamishwillee** [comment]
I have no idea. I suspect either VS Code or Sublime text editor.

**Comment by kingainez** [comment]
> I read the article: " Wprowadzenie do Express/Node" on https://developer.mozilla.org/pl/docs/Learn/Server-side/Express_Nodejs/Introduction#w_tym_module. I don`t know who wrote that, but I was so impressed, about the text editor, used by a writer to shows the code examples ... etc. ![image](https://user-images.githubusercontent.com/76117370/158415733-a39316d6-5876-48e0-bd91-314be6f9ae74.png)
> 
> Therefore, I would like to ask: Which text editor he used (name of the theme, setup ... etc). I love these colors of syntax.
> 
> Regards, Kinga
