### ISSUE TITLE
Identify requirements to ship interactive examples inline

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#406]
User story: I need to know what the requirements are for shipping interactive examples inline, so we can plan the work

Acceptance Criteria:
- [x] Security implications researched and documented
- [x] Contribution workflow concerns researched and documented
- [ ] Plan to address security concerns documented and accepted by dev lead
- [ ] Plan to address contribution workflow concern documented and accepted by IE project lead

**Comment by jwhitlock** [comment]
I'd like to delay additional security and content review until there is some prototype code, such as https://github.com/mdn/sprints/issues/467. It's hard to give a good review to an idea.
