### ISSUE TITLE
Final cleanup of FontAwesome web font from codebase

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#409]
This bug combines all the remaining work to remove the FontAwesome web font from the codebase and replace it with the SVG icon system.

A note from https://bugzilla.mozilla.org/show_bug.cgi?id=1451261#c7

"""
Some usage is in the wiki content and not injected by macros. This Django shell command gathers <i class="icon-*"> usage outside of KumaScript macros:

  from pyquery import PyQuery as pq
  docs = Document.objects.exclude(is_redirect=True).filter(current_revision__content__contains="<i ")
  icons = {}
  for doc_id in docs.values_list('id', flat=True):
    doc = Document.objects.get(id=doc_id)
    parsed = pq(doc.current_revision.content)
    for icon in parsed('i[class*=" icon-"],i[class^=icon-]'):
      for cls in icon.classes:
        if cls.startswith('icon-'):
          full_url = doc.get_full_url()
        i  cons.setdefault(cls, []).append(doc.get_full_url())

  for name, docs in icons.items():
    print name, len(docs)

The usage is:

  icon-trash 216
  icon-weather 1 - https://developer.mozilla.org/sq/docs/Mozilla/Marketplace/Options/Open_web_apps_for_android
  icon-anchor 1 - https://developer.mozilla.org/es/docs/User:davidwalshES
  icon-thumbs-down-alt 181

Font Awesome is included with Django REST Framework (DRF), and is collected by ./manage.py collectstatic. We don't use the default DRF templates, so we don't use this in production. We could stop collecting these assets, but that would be part of a different project.
"""

https://bugzilla.mozilla.org/show_bug.cgi?id=1482383

## Acceptance Criteria

* [ ] All icons across MDN Web Docs displays correctly
* [ ] All icons across MDN Web Docs uses the new SVG icon system
* [ ] FontAwesome and all related assets are removed from the codebase

**Comment by schalkneethling** [comment]
Keeping track of all bugs related to this work so we can remember to close them once the work is complete and in production:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1451261
* https://bugzilla.mozilla.org/show_bug.cgi?id=1496826
* https://bugzilla.mozilla.org/show_bug.cgi?id=1482381
* https://bugzilla.mozilla.org/show_bug.cgi?id=1482370

**Comment by schalkneethling** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1502813

**Comment by jwhitlock** [comment]
Follow-on work to regenerate pages moved to https://github.com/mdn/sprints/issues/686
