### ISSUE TITLE
 webNavigation API: more transitionTypes in events than documentation reports

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#411]
https://bugzilla.mozilla.org/show_bug.cgi?id=1418265

# Acceptance criteria

1. - [ ] Make sure the complete list of transitionType values is supported, as appropriate.

**Comment by irenesmith** [comment]
This issue is a duplicate of #[486](https://app.zenhub.com/workspace/o/mdn/sprints/issues/486) which is assigned for Alicia Keyes, Q4, Sprint 1.
