### ISSUE TITLE
Request to replace Coders & Creators survey banner with Firefox banner on MDN front page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#417]
## External Request

Hi! Requesting a banner on the front page of MDN as per conversations with Ali and Kadir. Sung Park is updating the design and will provide an image that fits the existing banner specs on Monday 8/13.

Thanks very much!

Kirby

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1482538

## Acceptance Criteria

* [x] Firefox banner is live on the homepage in place fo the current survey banner

**Comment by schalkneethling** [comment]
Asked for feedback on the layout as our layout does not exactly match their specs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1482538#c14

**Comment by schalkneethling** [comment]
PR opened: https://github.com/mozilla/kuma/pull/4938

**Comment by jwhitlock** [comment]
Bug is marked Fixed: Resolved, no feedback from non-devs in 5 days, so assuming closed.
