### ISSUE TITLE
Implement syntax improvements for media queries from level 4 specification

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#428]
https://bugzilla.mozilla.org/show_bug.cgi?id=1422225

Update: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries and linked pages.

**Comment by rachelandrew** [comment]
I have updated the table and also added a section about range contexts here: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

Added two examples here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media

As with the other issue, need to figure out how to get the level 5 spec to show up properly here https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries

**Comment by chrisdavidmills** [comment]
I've reviewed the pages you've updated, and made a few small changes; nice work Rachel!

The SpecName and Spec2 macros get their data from the SpecData.json file in our KumaScript repo. I've updated it to include the MQ5 spec, see here: https://github.com/mdn/kumascript/pull/795.

There are only two bits left to do here before we can close this item:

1. Add a note to the Fx63 rel notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63, in the CSS section. Follow the same pattern you can see in there already, making sure you reference the bug using the {{bug}} macro.

2. In the bug itself, ask the engineer who did the work for a review. To do this:

* Go to https://bugzilla.mozilla.org/show_bug.cgi?id=1422225
* Make a note of who did the engineering work on this bug, by looking for the "Assignee" label at the top of the bug. In this case it is Emilio (his bugzilla handle, :emilio, is probably the most useful bit in here)
* At the bottom of the page there is a select dropdown and text field with the label "Need more information from". Find that.
* In the text field, enter the engineer's bugzilla handle. Select the autocomplete suggestion that comes up.
* Add a comment to the bug saying that you've done the documentation work, link to the sections you've added, and ask really politely if Emilio would mind reviewing your doc additions.

Thanks again!

**Comment by chrisdavidmills** [comment]
Looks great, thanks! I'll close this one now.
