### ISSUE TITLE
[css-logical] rename offset-* properties to inset-block-start, inset-block-end, inset-inline-start and inset-inline-end 

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#429]
https://bugzilla.mozilla.org/show_bug.cgi?id=1464782

**Comment by rachelandrew** [comment]
PR for the data: https://github.com/mdn/data/pull/273

**Comment by rachelandrew** [comment]
I have moved and updated the property pages in English and French. Still to do is the compat data.

**Comment by rachelandrew** [comment]
PR for the compat data https://github.com/mdn/browser-compat-data/pull/2682

**Comment by rachelandrew** [comment]
I think this is pretty much done, other than when the fresh compat data gets onto MDN I need to update the refs to it. So I'll leave this one open until that has happened to remind me to go back and do it.

**Comment by rachelandrew** [comment]
I've now updated the refs to the support data so I think this one is done.

**Comment by rachelandrew** [comment]
review requested and release notes updated.

**Comment by chrisdavidmills** [comment]
All looks good. Closing issue. Note that Emilio has responded with a small change request in the bug.

**Comment by rachelandrew** [comment]
PR for that change to the data: https://github.com/mdn/data/pull/280
