### ISSUE TITLE
Add support for CSS prefers-reduced-motion media feature for Windows

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#430]
https://bugzilla.mozilla.org/show_bug.cgi?id=1365045

**Comment by rachelandrew** [comment]
Working on https://developer.mozilla.org/en-US/docs/Web/CSS/@media - I can't see how to get Media Queries Level 5 to show in the specification list: https://drafts.csswg.org/mediaqueries-5/ @chrisdavidmills can you let me know?

**Comment by chrisdavidmills** [comment]
Wow, that is an annoying animation. I love it ;-)

Same as previous comments — add note to Fx63 rel notes, request engineering review.

**Comment by rachelandrew** [comment]
With these reviews should I wait for the data to be merged or just mention that is pending?

**Comment by chrisdavidmills** [comment]
Just link to the PR, so the engineer can see it has been submitted.

**Comment by rachelandrew** [comment]
This has been added to the release notes and the bug updated to notify the engineer.

**Comment by chrisdavidmills** [comment]
Perfect; closing now.
