### ISSUE TITLE
Turn layout.css.offset-logical-properties.enabled off by default

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#431]
https://bugzilla.mozilla.org/show_bug.cgi?id=1471838

**Comment by rachelandrew** [comment]
I'm not sure what needs doing in the docs for this one @chrisdavidmills can you point me in the right direction?

**Comment by chrisdavidmills** [comment]
The way I understand it, turning this pref off means that Firefox no longer will support the offset-* property names as aliases of the newer inset-* property names. If this is true, is it worth mentioning in the browser compat data? If this is not true, or it is true but not worth mentioning, then there is probably nothing to do here.

**Comment by rachelandrew** [comment]
ah right - well if I have got the syntax right for the changes I just made I think that is covered as I've added the offset values as an alternate name, which is removed in 63. So hopefully that will be clear.

**Comment by chrisdavidmills** [comment]
Sounds good to me.

**Comment by rachelandrew** [comment]
Closing as I think this is fixed in issue [#429](https://app.zenhub.com/workspace/o/mdn/sprints/issues/429)
