### ISSUE TITLE
FF63 DDN: Flow-Relative Values for the "resize" Property

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#437]
[css-logical] Flow-Relative Values for the "resize" Property

https://bugzilla.mozilla.org/show_bug.cgi?id=1464786

**Comment by rachelandrew** [comment]
PR for the data https://github.com/mdn/browser-compat-data/pull/2712

**Comment by chrisdavidmills** [comment]
Looks like the property page has details filled in already, so I think all your really need to do here is:

1. Update the formal syntax to show the new values (data taken from the data repo)
2. Add a note to the Fx63 rel notes as mentioned in my previous comment to one of your issues.
3. Request a review from the implementing engineer as mentioned in my previous comment to one of your issues.

**Comment by rachelandrew** [comment]
PR for formal syntax: https://github.com/mdn/data/pull/281

**Comment by rachelandrew** [comment]
Release notes updated and engineer notified in the issue.

**Comment by chrisdavidmills** [comment]
Looks perfect, thanks Rachel! We can close this one now.
