### ISSUE TITLE
DDN FF63:  Implement path() function for offset-path

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#439]
Implement path() function for offset-path [1 day, page exists but needs structure sorting out; BCD needs updating]

https://bugzilla.mozilla.org/show_bug.cgi?id=1429298

**Comment by estelle** [comment]
Pull request for Compat Table: https://github.com/mdn/browser-compat-data/pull/2731

**Comment by chrisdavidmills** [comment]
Page structure looks improved; I've done a bit of clean up too. The page could use an interactive example at the top; also, the scissors don't move on the demo.

**Comment by estelle** [comment]
Still working on that page, and on demos. Not sure FF supports animating along the path. Chrome and Opera do. Also, only path() seems to work. No other values. Ex. https://codepen.io/team/css-tricks/pen/WZdKMq

**Comment by estelle** [comment]
Last 3 things required:

[] Compat Pull request needs to be merged.
[] Interactive example needs to be merged.
[] Examples needs to be added back into page once interactive example is merged.

**Comment by jmswisher** [comment]
@estelle This is still missing the interactive example on the page, correct?

**Comment by estelle** [comment]
https://github.com/mdn/interactive-examples/pull/1128 was closed without merging. Would only be useful with both   motion-offset, offset-distance, and animation.
