### ISSUE TITLE
DDN FF63: -webkit pseudo selectors makes the CSS rules fail

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#440]
-webkit pseudo selectors makes the CSS rules fail. [1 day, not much content but need to investigate where to put it]
https://bugzilla.mozilla.org/show_bug.cgi?id=1424106

**Comment by estelle** [comment]
Locations found: 

note on https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax

**Comment by chrisdavidmills** [comment]
@estelle I'd say a better place to mewntion it would be https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions (as well as the Fx63 rel notes, or course).

I am a bit nervous about mentioning details like this in the beginner's CSS course. I hardly even mention prefixes anywhere in Learn/.

**Comment by estelle** [comment]
code example: https://codepen.io/estelle/pen/GXxGjK
