### ISSUE TITLE
DDN FF63:  Add support for |clip-path: path()

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#441]
Add support for |clip-path: path()

https://bugzilla.mozilla.org/show_bug.cgi?id=1246764

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

[X] update text (automatically live)
[X] syntax (blue box) - https://github.com/mdn/data/pull/296
[X] interactive example - https://github.com/mdn/interactive-examples/pull/1145
[X] list of examples (automatically live)
[X] Live example (codepen) (automatically live)
[X] compat table - https://github.com/mdn/browser-compat-data/pull/2822

Basic shape definition:
https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape
[X] Edit content
[X] Interactive example - pull request: https://github.com/mdn/interactive-examples/pull/1144
[X] Compat table - https://github.com/mdn/browser-compat-data/pull/2821

shape-outside
https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside
Note: path() is not yet supported as a value for shape-outside.

offset-path
https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path
[X] Move path() from function to basic shape.
[X] Change syntax to reflect that change.

SVG d property
https://codepen.io/estelle/pen/YOvMpN
works in Chrome but not FF.

**Comment by estelle** [comment]
Definition of path() 
https://drafts.csswg.org/css-shapes-2/#supported-basic-shapes

to be added to basic shapes at:
https://www.w3.org/TR/css-shapes/#basic-shape-functions

So we should add path() to the MDN basic shape definition
https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape
and add an entry in the compat table
{{Compat("css.types.basic-shape")}}
and add it to the shape-outside property
https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside
along with the compat table
{{Compat("css.properties.shape-outside")}}
and to the CSS Formal Syntax
data/css/syntaxes.json

**Comment by estelle** [comment]
@chrisdavidmills Help!

**Comment by chrisdavidmills** [comment]
@estelle It looks like BasicShapeOrPath is an internal Gecko implementation detail. If you go to https://phabricator.services.mozilla.com/D3636 and search for it, you’ll see that it appears inside the Gecko C++ code; it looks like it is involved with the function that actually applies the visual mask to create the desired effect.

So I’d ignore this and get on with your plan, which sounds totally correct.

**Comment by estelle** [comment]
Notes:

basic shapes: FF supports path() for offset-path and clip-path, but not shape-outside or d (svg)
