### ISSUE TITLE
DDN FF63: Tracking -moz-scrollbars-none when creating webcompat issues.

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#442]
Tracking -moz-scrollbars-none when creating webcompat issues.] 

https://bugzilla.mozilla.org/show_bug.cgi?id=1481125

**Comment by estelle** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow - add "As of Firefox 63, this feature is behind a feature preference setting. In about:config, set layout.css.overflow.moz-scrollbars.enabled to true" to page. Not sure if it should be in compat table as removing a default behavior of a moz only property value.

Only remove from -moz-scrollbars-none, -moz-scrollbars-horizontal, and -moz-scrollbars-vertical . The -moz-hidden-unscrollable value still works.

**Comment by chrisdavidmills** [comment]
I think it'd be neater to put it in the compat table than using some random footnote thingy.

You could just put in a separate row entry for -moz-scrollbars-*, and for that entry set all the browser compat to false, except Firefox/FxA which would be something like

```
"firefox": [
  {
    "version_added": true,
    "version_removed": "63",
  },
  {
    "version_added": "63",
    "flags": [
      {
        "type": "preference",
        "name": "layout.css.overflow.moz-scrollbars.enabled",
        "value_to_set": "true"
      }
    ]
  }
],
```

**Comment by estelle** [comment]
As the overflow property was not removed, I put the note next to the 3 properties removed.

**Comment by chrisdavidmills** [comment]
WFM, thanks!
