### ISSUE TITLE
DDN FF63: swap values of 2-value 'overflow' syntax so block is first and inline is second

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#443]
[swap values of 2-value 'overflow' syntax so block is first and inline is second] (https://bugzilla.mozilla.org/show_bug.cgi?id=1481866)

**Comment by rachelandrew** [comment]
I have updated https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

As a separate thing we need to add the logical properties overflow-block and overflow-inline however as these are not implemented yet that probably doesn't need to be for 63. I'll add a ticket to remind myself about it.

**Comment by rachelandrew** [comment]
I've added this change to the release notes, and notified the engineer.

**Comment by rachelandrew** [comment]
This has been backed out https://bugzilla.mozilla.org/show_bug.cgi?id=1481866#c15

Which I assume means I need to go revert the docs changes.

**Comment by chrisdavidmills** [comment]
Just Firefox, or are all browsers reverting this?

**Comment by rachelandrew** [comment]
I don't think other engines have implemented - here is the CSSWG thread https://github.com/w3c/csswg-drafts/issues/2988

**Comment by chrisdavidmills** [comment]
@rachelandrew Yeah, looks like it; I'm happy for you to revert it.

**Comment by rachelandrew** [comment]
looks like another contributor reverted this so we can close the issue.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow$compare?from=1414645&to=1420213

**Comment by chrisdavidmills** [comment]
Works for me. Closing.
