### ISSUE TITLE
Prioritized Updates for Web Extensions Documentation

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#446]
This is temporarily a placeholder. I am meeting with the Web Extensions team this afternoon and will have a prioritized list here before we finalize the sprint tomorrow. I am also allotting two points for now.

Reorganize the Web Extensions section to match the other sections of our documentation.

# User Story

The current iteration of the Web Extensions documentation makes it difficult to find the information I'm looking for. I want to see the information displayed in a manner consistent to the rest of MDN with the left-hand menu matching the information on the right.

# Acceptance Criteria

- [ ] The left-hand menu now matches the terminology used in the content area.
- [ ] The right-hand content area has been de-cluttered and organized in a manner similar to our other content areas.
- [ ] New content has been reviewed by the Web Extensions Team

**Comment by mconca** [comment]
Irene, here are the Trello cards we discussed during the meeting:

https://trello.com/c/dwUfsA0x - Remove old docs on lightweight themes
https://trello.com/c/EyNu4hBe - Add new docs on using the AMO wizard to create a theme
https://trello.com/c/7acATX5S - Reorganize the "Distribution Options" part of the docs

**Comment by irenesmith** [comment]
This issue has been broken down several parts and most of them moved into the next sprint. What remains here is a reworking of the menu on the landing page to match the entries on the main portion of the page.

**Comment by irenesmith** [comment]
Not sure that this is worth keeping around anymore so I'm assigning to you rather than Richard.

**Comment by Elchi3** [comment]
Seems stalled. Closing.
