### ISSUE TITLE
Work on content for Hack on MDN a11y event

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#450]
# Acceptance criteria

1. - [x] List of suggested tasks and other supporting material produced for starting 

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] Get existing material from Janet.
2. - [ ] Look over Estelle's [a11y content audit](https://docs.google.com/spreadsheets/d/1jq6nfFPa_v0YqqBk4S0QVfpkOgUBx5GR2YLc-uH6uC0/edit#gid=1119448449).
3. - [ ] Refine material and produce list of suggested tasks for working on in the sprint.
4. - [ ] Other supporting material researched; what else do we need? Ask Florian what he did for the BCD HoM.

**Comment by jmswisher** [comment]
Closing this because the Acceptance Criteria is met.
