### ISSUE TITLE
Rewrite display property documentation

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#456]
# User story
As a web developer, I want to know how to use the display property, so I can use it effectively in my CSS.

# Acceptance criteria

1. - [ ] display property documentation rewritten.
2. - [ ] display property documentation reviewed by another writer.
3. - [ ] dependency set to done.

# Tasks

1. - [ ] Include specific tasks here that need to be done.

**Comment by rachelandrew** [comment]
PR for spec data: https://github.com/mdn/kumascript/pull/809

**Comment by rachelandrew** [comment]
PR for data: https://github.com/mdn/data/pull/290

**Comment by rachelandrew** [comment]
So I've been working on the page https://developer.mozilla.org/en-US/docs/Web/CSS/display and I think we are mostly there. 

There are now examples for various parts of the spec, I've explained the inside/outside stuff and legacy values plus linked to other things we already have such as the flow layout info.

I have an issue in that the internal links here: https://developer.mozilla.org/en-US/docs/Web/CSS/display#Syntax are broken because the <code></code> wrapping the content of the headings gets encoded into the id on the anchor. Best way to deal with that?

**Comment by chrisdavidmills** [comment]
Thanks for the help @ExE-Boss.

@rachelandrew, I'll review the display article and let you know if I've got any comments, after which we should be able to call this done.

**Comment by chrisdavidmills** [comment]
OK, review comments:

* The `list-item` value is missing a description in the `Values` section.
* The content is really good, however strictly speaking by MDN guidelines we should probably have separate pages for the different value descriptions and put all the detail about how the values work on there, keeping the descriptions brief in this ref doc.

As an example, a detailed description of all the <color> values is given at

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

What do you think about this?

**Comment by rachelandrew** [comment]
you mean a separate page for `<display-inside>`, `<display-outside>` and so on?It would certainly stop this being so epic!

**Comment by chrisdavidmills** [comment]
@rachelandrew yup, exactly. I mean, some of the pages might become fairly small if you did that, but you could perhaps flesh them out with some additional examples, or links to additional examples (e.g. no need to rehash all the Grid/Flexbox examples all over again).

**Comment by rachelandrew** [comment]
@chrisdavidmills happy to do that, it would make it a bit easier to comprehend I think. I'll have a go at doing so.

**Comment by chrisdavidmills** [comment]
@rachelandrew fabulous, thanks Rachel!

**Comment by chrisdavidmills** [comment]
@rachelandrew hrm, there are some weird things going on here. I managed to move the pages:

https://developer.mozilla.org/en-US/docs/Web/CSS/display-outside
https://developer.mozilla.org/en-US/docs/Web/CSS/display-inside

But I then got emails telling me the moves had failed, when they ... ummm, hadn't.

They look ok now anyway.

**Comment by ExE-Boss** [comment]
@rachelandrew That’s because there used to be a `Web/CSS/display-outside` page, which was since deleted (I’ve now moved the entry to [`Archive/Web/CSS/display-outside`](https://developer.mozilla.org/docs/Archive/Web/CSS/display-outside), which also apparently restored it.

Same with `display-inside`

**Comment by ExE-Boss** [comment]
**Update:** I have now moved the types to the new location and archived the old properties.

**Comment by rachelandrew** [comment]
@chrisdavidmills the pages are now all separate and they have examples. New pages are linked from what were the anchor links.

I'm sure we could continue to add new examples forever, but unless you spot any glaring omissions this could probably be marked done and if I think up other things as I'm working around this subject I'll go add them.

**Comment by chrisdavidmills** [comment]
@rachelandrew OK, I have given these all a copy edit, and things are looking generally good! 

I added an Examples section to the main display page: https://developer.mozilla.org/en-US/docs/Web/CSS/display#Examples

Let me know if you think this reads OK; you might want to add some more suitable links to the list I started of related resources on MDN.

The display-outside page: https://developer.mozilla.org/en-US/docs/Web/CSS/display-outside. Mostly OK, although the explanation of run-in is a bit mind-bending, and could perhaps use some illustrations to show what you mean. Also, do you think the browser compat data for run-in makes sense? It might also be worth stating for the record that block and inline are supported, and have been forever.

Apart form that, looks great!

**Comment by rachelandrew** [comment]
yeah I wasn't sure what to do with the compat data as I couldn't see a way to get at block and inline on their own.

**Comment by ExE-Boss** [comment]
https://github.com/mdn/browser-compat-data/pull/1799 will make it possible to do that.

The other option would be to make `<display‑iside>` and `<display‑outside>` sub‑features of `display`.

**Comment by rachelandrew** [comment]
So display: run-in is a curious one, as it was implemented then removed by most other browsers. I don't think ever implemented in FF.

https://bugzilla.mozilla.org/show_bug.cgi?id=2056

https://quirksmode.org/css/css2/display.html

https://caniuse.com/#search=display%3A%20run-in

So do I add it, and flag the removals as best I can?

**Comment by chrisdavidmills** [comment]
Yeah, I'd just add them all and then fill in the data about `run-in` not being supported in most places. It is still specced, just not supported, right?

**Comment by ExE-Boss** [comment]
Yeah, it is specced, but there are still some issues left to work out in the CSSWG side before browsers attempt to re&#x2011;implement it.

**Comment by rachelandrew** [comment]
@chrisdavidmills there was a bunch of edits made in CSS Display 3, which is now at CR. So the spec is somewhat changed/clarified to the original implementations. I don't think there is much outstanding on it, but it probably isn't high priority to anyone.

**Comment by rachelandrew** [comment]
PR to move display to CR status https://github.com/mdn/kumascript/pull/979

**Comment by chrisdavidmills** [comment]
I think this is basically finished, apart from the BCD updates for run-in/display/block?

**Comment by rachelandrew** [comment]
I believe so.

**Comment by chrisdavidmills** [comment]
cool.
