### ISSUE TITLE
Fx63 Layout DDNs part 3 — the last couple

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#459]
# User story
As a web developer, I want to learn about the new Layout features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [ ] All DDNs complete.
2. - [ ] Reviews request from engineers for all documentation work.

# Tasks

1. - [x] [Add support for CSS prefers-reduced-motion media feature for MacOSX](https://bugzilla.mozilla.org/show_bug.cgi?id=1475462) 
2. - [ ] [Enable the '-webkit-appearance' alias for '-moz-appearance' for EARLY_BETA_OR_EARLIER](https://bugzilla.mozilla.org/show_bug.cgi?id=1480073)

**Comment by rachelandrew** [comment]
1, is already covered by the work I did here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by chrisdavidmills** [comment]
@rachelandrew ah, I thought it sounded familiar! I've added the macOS bug to the release note, and set the bug to DDC.
