### ISSUE TITLE
Update CSP docs to include report-sample

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#463]
`report-sample` is a new CSP directive option that provides a link to an example of the code violating the CSP configuration. It was first implemented in Firefox in 63, and docs have been updated to include it.

BCD needs to be updated to include it as well. However, currently report-sample is listed as a top-level feature, which is fine, since it's a significant one, but it needs to be included in the tables for every directive that supports it, which is most of them. So finishing this work is on hold until PR #1799 lands to add the ability to import features from one place to another. Then we can easily import report-sample to everywhere it's needed.

**Comment by chrisdavidmills** [comment]
@a2sheppy any idea what is going on with this one? You mention waiting until a certain PR lands before continuing, but the wrong PR appears to be linked. Can you investigate? Thanks!
