### ISSUE TITLE
Network: Follow up with HackOnMDN attendees

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#469]
[X] - Email "Thank yous"
[-] - Hand write a few - NOPE
[X] - Ask Eric to write gridcell
[X] - Work with Michiel Bijl to finsh tab and tab panel
[-] - reach out to Knowbility re: doing another hackathon - Janet is doing this
[X] - All non-mozilla attendees have been reached out to.
[X] - A list of new pages attendees agreed to create/edit  - so far just Tab

Acceptance criteria: Letter to each of the following

[X] Eric Bailey
[X] Seren Davies
[X] Hidde de Vries
[X] Eric Eggert
[X] Eva Ferreira
[X] Stephanie Hobson
[X] Bruce Lawson
[X] Josh Mize (chrisMills)
[X] Adrian Roselli
[X] Glenda Sims
[X] Marco Zehe (chrisMills)
[X] Michiel Zoe Bijl
[X] Patrick Kettner (chrisMills)

**Comment by jmswisher** [comment]
Re reaching out to Knowbility: Eric Eggert just connected me with Jillian Fort and Sharron Rush regarding doing something in connection with AccessU.

**Comment by jmswisher** [comment]
Happy to help with thank-yous to attendees you didn't work with directly.

**Comment by chrisdavidmills** [comment]
I am happy to help also, if there's anyone you want me to contact. I think I invited Adrian, Glenda, and Eric B?

**Comment by estelle** [comment]
@chrisdavidmills @janet Would you be able to thank Patrick, Marco and Josh. I'll get the two Erics. Those are the last 5.

**Comment by chrisdavidmills** [comment]
Yup, sure thing. I can do that.

**Comment by chrisdavidmills** [comment]
OK, thank you letters sent to Josh, Patrick and Marco! I bcc'd you in each one.

**Comment by estelle** [comment]
Thanks!
