### ISSUE TITLE
Do research to support decision on WebAPI/JS ref page title changes 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#472]
# User story

As an MDN reader, I want the titles on JS/WebAPI reference pages to not be confusing and factually incorrect, so I can be sure I'm getting accurate information.

# Resources

This work was instigated by a [discourse post from Dominic Denicola](https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641) from Google, who pointed out that the titles on many API reference pages are incorrect — many instance properties/methods are just written as Interface.instanceFeature, when they should be written as Interface.prototype.instanceFeature.

I [wrote some notes](https://docs.google.com/document/d/19ZJbG3tp7CBygsFCj0BeY9CPWCcvnv75GZeTKhGzSlQ/edit#) on how we should fix this, along with a suggested solution.

But It also became clear that we should do some research with real users, rather than just assuming that our hunch is correct. I wrote [a simple questionnaire](https://docs.google.com/forms/d/1ClqKnMcSllGPoX-HhTkrtVzBqlvEDPn_N-G-4Vdabvk/edit) that I thought would help test our theory.

But I need some advice on the best way to test our hunch, and actually start carrying out the research. 

# Acceptance criteria
1. - [x] Advice sought on how to do this research.
2. - [ ] Research plan put into action.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] Advice sought on how to do this research.
2. - [ ] Research plan put into action.

**Comment by chrisdavidmills** [comment]
Talked to Shi Li about this; she is going to have a think and get back to me in a week with her ideas.

**Comment by jmswisher** [comment]
Closed as "No longer valid"
