### ISSUE TITLE
HTML interactive examples: revise guidelines and assess issues

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#485]
We need more detailed guidelines for HTML interactive examples. In this task we'll document some guidelines then do an analysis of the existing examples to see which ones need to be updated, and make a plan to do it.

# Acceptance criteria
* Guidelines for HTML interactive examples are agreed and updated.
* We have a list of examples that need updating.

**Comment by chrisdavidmills** [comment]
Closed as per conversation in final sprint planning

**Comment by wbamberg** [comment]
This is half-done:
* the guidelines update part is pending final review: https://github.com/mdn/interactive-examples/pull/1184
* the assessment part has been moved to a new issue: https://github.com/mdn/sprints/issues/538
