### ISSUE TITLE
Write plan for API reference structural improvements

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#487]
Write a planning document for restructuring the API reference. This will be based on the post I made here: https://discourse.mozilla.org/t/api-documentation-structure-idea/31967

## Acceptance criteria

- [x] Document created and written :)
- [x] Include plan for actual content hierarchy changes
- [x] Cover macro changes that will be needed
- [x] Describe new macros that may be needed
- [x] Pros and cons of actually making these changes (added on October 11)
- [x] Include plan for new page titles
- [x] Submit to Chris and the rest of the team for review and feedback

**Comment by jmswisher** [comment]
Plan document is here: https://docs.google.com/document/d/1h1d2Nr58SW5_Tx38C06pywcJbGE5m6PaPzwWs--c1oE/edit?usp=sharing
