### ISSUE TITLE
Layout cookbook: Bootstrap style list group with badges

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#495]
# User story
As a web developer I want to understand how to create a list group with badges component. Such as http://getbootstrap.com/docs/4.1/components/list-group/#with-badges

# Acceptance criteria

New recipe in the cookbook section with live examples and downloadable code.

# Tasks

1. - [x] Create example
2. - [x] Commit live example and downloadable code to CSS Examples Repo
3. - [x] Write page for the cookbook
4. - [x] Add relevant compat info

**Comment by rachelandrew** [comment]
The page is here: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/List_group_with_badges

**Comment by chrisdavidmills** [comment]
I've given this an edit, looks great! Thanks Rachel.
