### ISSUE TITLE
Layout cookbook: card component

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#496]
# User story

As a web developer I want to understand how to create a card component.

# Acceptance criteria

New recipe in the cookbook section with live examples and downloadable code.

# Tasks

1. - [x] Create example
2. - [x] Commit live example and downloadable code to CSS Examples Repo
3. - [x] Write page for the cookbook
4. - [x] Add relevant compat info

**Comment by rachelandrew** [comment]
This is done here: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Card

**Comment by chrisdavidmills** [comment]
OK, closed.

**Comment by chrisdavidmills** [comment]
Ummm, sorry, this is one of your new ones ;-)

**Comment by chrisdavidmills** [comment]
OK, I have now edited this and am very happy with it. If you are happy, then I think we can close it.
