### ISSUE TITLE
Layout cookbook: pagination recipe

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#497]
# User story

As a web developer I want to understand how to lay out pagination.

# Acceptance criteria

New recipe in the cookbook section with live examples and downloadable code.

# Tasks

1. - [x] Create example
2. - [x] Commit live example and downloadable code to CSS Examples Repo
3. - [x] Write page for the cookbook
4. - [x] Add relevant compat info

**Comment by rachelandrew** [comment]
This is done here: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Pagination

**Comment by chrisdavidmills** [comment]
OK, I've reviewed/edited this one too, and it looks great. Happy to close if you are happy.
