### ISSUE TITLE
Layout cookbook: breadcrumb navigation

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#498]
# User story

As a web developer I want to understand how to create breadcrumb navigation.

# Acceptance criteria

New recipe in the cookbook section with live examples and downloadable code.

# Tasks

1. - [x] Create example
2. - [x] Commit live example and downloadable code to CSS Examples Repo
3. - [x] Write page for the cookbook
4. - [x] Add relevant compat info

**Comment by rachelandrew** [comment]
Completed example is here https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation

**Comment by chrisdavidmills** [comment]
Looks great Rachel; I just added the standard CSSRef navigation sidebar macro, and gave it a small edit to make it consistent with the other recipes. If you are happy with this, we can close.
