### ISSUE TITLE
Update CSS Logical Properties and Values and add non-existent pages

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#499]
# User story

As a web developer I want to understand CSS Logical Properties and values and browser support for them.

# Acceptance criteria

1. No missing property pages under https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
2. All pages have accurate browser compat data
3. All pages have examples demonstrating how the properties and values are used

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] Ascertain exactly what needs doing
2. - [x] Create any missing compat data
3. - [x] Check and update if necessary existing compat data
4. - [x] Create missing property pages
5. - [x] Add examples to each page

It is likely there are other things, it might be good to write a couple of guides to the subject, but this is a pretty chunky task anyway so I'll add anything else I spot as I go.

**Comment by rachelandrew** [comment]
A quick check shows me that the compat data is out of date, as Chrome has implemented a lot of these and that isn't reflected.

**Comment by rachelandrew** [comment]
PR for margin/border/padding properties data https://github.com/mdn/browser-compat-data/pull/2952

**Comment by rachelandrew** [comment]
PR for width/height mappings https://github.com/mdn/browser-compat-data/pull/2955

**Comment by rachelandrew** [comment]
Removed two properties from the page - background-image-transform and border-image-transform (they don't seem to appear in any of the data) as they have been removed from the latest spec https://drafts.csswg.org/css-logical-1/#changes

**Comment by rachelandrew** [comment]
PR for missing properties: https://github.com/mdn/browser-compat-data/pull/3010

**Comment by rachelandrew** [comment]
PR for updated sizing properties https://github.com/mdn/browser-compat-data/pull/3027

**Comment by rachelandrew** [comment]
@chrisdavidmills on this page for the shorthand `inset` property https://developer.mozilla.org/en-US/docs/Web/CSS/inset I think the formal syntax is picking up the values for the basic shape `inset()` function value (the border-radius value does not belong to this property).

I'm not sure how to fix this!

**Comment by rachelandrew** [comment]
I have now created the 12 missing pages for the as yet unimplemented properties, waiting for the data to be merged.

**Comment by chrisdavidmills** [comment]
@rachelandrew Hey there, sorry for the slowness in replies. Looking at the `inset` shorthand page, it looks like this is calling the correct compat data — the compat macro call is {{Compat("css.properties.inset")}}, whereas it'd be {{Compat("css.types.basic-shape.inset")}} if it were calling the type?

The work on this looks like it is coming on nicely. Are you intending to write a couple of guides covering usage of logical properties, once support improves and the reference stuff is sorted out?

**Comment by rachelandrew** [comment]
That's odd then, as the info looks wrong. I'll have a poke around and see if I can work out why.

Yep I'm intending to write guides but I'll probably raise that as a new issue. I didn't want to publish guides when the pages were full of holes though :D

**Comment by rachelandrew** [comment]
Oh - you mention compat data. I was talking about the formal syntax on that page, it mentions `round`, which is what clued me in to something being wrong. https://developer.mozilla.org/en-US/docs/Web/CSS/inset#Formal_syntax

**Comment by chrisdavidmills** [comment]
Ooops, sorry, I missed that you were talking about formal syntax ;-)

So it seems like the formal syntax data is being grabbed from 

https://github.com/mdn/data/blob/59586d402ff236dd84963ef7c54fa90e3b591418/css/syntaxes.json#L311

Which is weird, as formal syntax data is usually grabbed from 

https://github.com/mdn/data/blob/master/css/properties.json

There is no entry for inset in here; it makes me wonder whether we need to add one in to fix it.

**Comment by rachelandrew** [comment]
I'll have a look today - just got to Australia last night so I'm in the future for a few days.

**Comment by rachelandrew** [comment]
PR https://github.com/mdn/data/pull/319

**Comment by rachelandrew** [comment]
PR for interactive examples to rename the offset-* properties https://github.com/mdn/interactive-examples/pull/1209

**Comment by rachelandrew** [comment]
I have now added the interactive examples to those properties which have implementation in more than one browser.

Think this is all pretty much done at this point. Once all the PRs are emerged and data added I'll check through it.

**Comment by rachelandrew** [comment]
One thing I don't have a resolution for is the compat data on the main page, should we remove this and refer to each property page? We don't have a big table like this for flexbox etc. as it seems we can't create a combined view of properties yet.

**Comment by rachelandrew** [comment]
So I think this is in reasonable shape pending the PR I've just updated.

I've actually got some guides half written now, but I'll add those as a new issue for the next sprint to finish off.

**Comment by chrisdavidmills** [comment]
Great! Sounds fine to me. We can close this then, once the PRs are all merged.

**Comment by rachelandrew** [comment]
Logical Properties is the gift that keeps on giving. I need to add pages and data for the four border-radius mappings.

**Comment by rachelandrew** [comment]
Data: https://github.com/mdn/data/pull/327
Compat: https://github.com/mdn/browser-compat-data/pull/3128

**Comment by rachelandrew** [comment]
I've now done the four border-radius property pages.

https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-end-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-start-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-start-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-end-radius

**Comment by chrisdavidmills** [comment]
OK, great, reviewing now!

**Comment by rachelandrew** [comment]
and some missing two-value shorthands https://github.com/mdn/data/pull/329

**Comment by chrisdavidmills** [comment]
So, pages are looking great; I've just given them a bit of an edit, added in some cross references, filled in syntax on the actual page, added an experimental tag on each page so the experimental icon appears next to them in the sidebar. That's it, I think.

Thanks again Rachel, awesome work.

**Comment by chrisdavidmills** [comment]
OK, PR reviewed. I am not that confident on reading the CSS formal syntax, but I am getting better ;-)

**Comment by chrisdavidmills** [comment]
OK, cool. I will bow to your wisdom on this stuff.

**Comment by rachelandrew** [comment]
https://github.com/mdn/data/pull/329

I think I have figured this out, the spec seems inconsistent with itself. We should now match it.

**Comment by rachelandrew** [comment]
I'm pretty sure this is all now complete.

**Comment by chrisdavidmills** [comment]
And this one.
