### ISSUE TITLE
KR: Take over SRE responsibilities

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#5]
With the move of the MDN dev team out of marketing, we don’t have access to the marketing SREs anymore and need to find a way to solve those problems in some other way.

# Acceptance criteria
* Staging and Production are migrated to IT-managed Kubernetes clusters
* Daily operations moves from MozMEAO SREs to IT and MDN staff
* MDN resources in MozMEAO are decommissioned

References
===
* [IT / MDN Weekly customer sync](https://docs.google.com/document/d/1PHxeORIHn0oz68-Ms6u_yUq60Yq-1NzTwPP-hswPgv4/edit?usp=sharing)
* ~~https://github.com/orgs/nubisproject/projects/4 - IT project board~~
* ~~https://waffle.io/mozilla-itcloud/mdn-migration-project - New IT project board~~
* https://github.com/mdn/infra/projects/1 - New IT project board
* [MDN Migration Project milestones](https://github.com/mozilla-itcloud/mdn-migration-project/milestones?direction=asc&sort=due_date&state=open)
* Slack channel #mdn-migration

**Comment by jwhitlock** [comment]
Nice work @escattone!
