### ISSUE TITLE
Publish September 2018 MDN Changelog

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#501]
# User story
As a MDN fan, I want to read the MDN Changelog, so I can see if my PR made the list.

# Acceptance criteria
September Changelog published on Hacks Blog, promoted

# Tasks
* [ ] Submit draft
* [ ] Publish
* [ ] Add to [Discourse](https://discourse.mozilla.org/t/mdn-changelog-2018/25271)

**Comment by jmswisher** [comment]
[Done](https://hacks.mozilla.org/2018/10/payments-accessibility-and-dead-macros-mdn-changelog-for-september-2018/) and [done](https://discourse.mozilla.org/t/mdn-changelog-2018/25271/13)
