### ISSUE TITLE
Update content of Web/HTTP/Cookies

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#504]
Since the existing Web/HTTP/Cookies documentation is missing information,
> could you also extend the section? You could use this blog post as the basis
> for documentation (or just link to that blog post):
> https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/

# Acceptance Criteria
- [x] Existing documentation has been updated with information from the blog post.

**Comment by Rob--W** [comment]
The quote is from https://bugzilla.mozilla.org/show_bug.cgi?id=1351663#c23 and specifically concerns this section: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies

When you have improved this MDN section, could you add a link to that section at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus ? Thanks!

**Comment by irenesmith** [comment]
Information has been added to [SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) on the HTTP cookies page as requested and a link to that section has been added to the definition of cookies.SameSiteStatus.

**Comment by Rob--W** [comment]
That's looking great, thanks!

I have a few more suggestions:

"SameSite cookies are still experimental and not yet supported by all browsers.". The support is actually looking quite good: https://caniuse.com/same-site-cookie-attribute

Could you add an example of setting a SameSite cookie, and state that the default behavior (i.e. if the flag is not set of not supported by the browser) is to include the cookies in any request, including cross-origin requests.

Here is an example:

```
Set-Cookie: key=value; samesite=strict
```

Lastly, on the same page, there is also a section on CSRF: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cross-site_request_forgery_(CSRF)

I suggest to add a bullet point referring to the SameSite section.

**Comment by chrisdavidmills** [comment]
@irenesmith did you follow up on Rob's last few comments?

**Comment by irenesmith** [comment]
Need to make some final changes to this so I have moved it into the current sprint (Erykah Badu) and allocated 0.5 points to the remaining work.

**Comment by irenesmith** [comment]
Made updates according to the above suggestions.

**Comment by irenesmith** [comment]
Sorry, I misunderstood the first comment about the note. I thought you wanted it *added*. I will remove it.

I will make the other changes you list today (1/31)

**Comment by Elchi3** [comment]
Irene, can you also follow-up on https://github.com/mdn/browser-compat-data/pull/2918?
