### ISSUE TITLE
Network Monitor Enhancements

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#507]
Information has been added to the Network Monitor header section on the Headers pane to show the referrer policy.

See Bugzilla: #[1496742](https://bugzilla.mozilla.org/show_bug.cgi?id=1496742) for information about referrer policy.
[Trello Issue - Network monitor enhancements](https://trello.com/c/dE8tJ7my/87-network-monitor-enhancements)

# Acceptance Criteria
- [x] Documentation has been added for referrer policy within the Network Monitor headers tab documentation
- [x] Screenshots have been created and added to the documentation
- [x] Information about referrer policy added to the Firefox 64 Release Notes

**Comment by irenesmith** [comment]
This is not ready to be documented yet.

**Comment by irenesmith** [comment]
It is possible that the CSP policy part of this issue should be moved to a separate issue for a future sprint.

**Comment by chrisdavidmills** [comment]
It's close this, and move any other future work to a new card.
