### ISSUE TITLE
Page Actions

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#508]
[Trello Issue: Page actions](https://trello.com/c/vsKZdybA/115-page-actions-fx-64) covers two Bugzilla issues:

#[1437861](https://bugzilla.mozilla.org/show_bug.cgi?id=1437861) - Implement userScripts.register and execute userScripts.js code in isolated sandboxes
#[1437864](https://bugzilla.mozilla.org/show_bug.cgi?id=1437864) - Implement userScripts API methods to allow an extension to inject custom APIs in the isolated userScripts sandboxes

# Acceptance Criteria
- [ ] Documentation added for userScripts.register()
- [ ] Sample code for userScripts.register()
- [ ] Documentation added for other userScripts API methods
- [ ] One or more examples of injecting custom API code to run in userScripts sandbox
- [ ] Information added to the Firefox 64 Release Notes as appropriate

**Comment by chrisdavidmills** [comment]
This stuff has been pushed out to Fx65/66, so no longer a priority for this, or next sprint. We'll have to keep our ears to the group to find out when it is ready to document.

**Comment by irenesmith** [comment]
I'm temporarily putting this back in the icebox. I've added a needs info to one of the related bugs to check on the status.

**Comment by irenesmith** [comment]
This issue is superceded by [Sprints 2136](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/2136)
