### ISSUE TITLE
Page fragment gets added to the URL twice if the loaded URL already had a fragment

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#509]
From Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1487795

After loading an URL in a new tab that already contains a fragment (the part after the "#" character at the end of the URL), e.g. [1], selecting any link that adds a fragment to the URL will append it at the end, without replacing the original anchor.

## STR:

- Load https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#CC_practices
- Scroll the page up and click on the chain icon near "General Practices"

## Current output:

- https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#CC_practices#General_C.2FC.2B.2B_Practices

Two fragments are present.

## Expected output:

- The awesomebar should contain https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#General_C.2FC.2B.2B_Practices

## Acceptance Criteria

* [ ] If there is an existing hash, the hash is replaced by the new hash not appended

**Comment by schalkneethling** [comment]
Looks like this is already fixed ;) Waiting for confirmation from the reporter here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1487795#c3

**Comment by schalkneethling** [comment]
Confirmed by @jwhitlock that this works in production:
https://bugzilla.mozilla.org/show_bug.cgi?id=1487795#c4

**Comment by jwhitlock** [comment]
Thanks @schalkneethling!
