### ISSUE TITLE
General Web Extension API Enhancements

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#511]
[Trello Issue](https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-64)

Bugzilla Issues
#[1486819](https://bugzilla.mozilla.org/show_bug.cgi?id=1486819) - add support for missing internal features for search engines -- 0.5 points

# Acceptance Criteria
- [x] Add information for #[1280347](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347) to release notes
- [x] Information added to the Firefox 64 Release Notes for #[1367160](https://bugzilla.mozilla.org/show_bug.cgi?id=1367160) as appropriate
- [x] Document search engine features that would be of use for extension developers.
- [x] Information added to the Firefox 64 Release Notes for #[1486819](https://bugzilla.mozilla.org/show_bug.cgi?id=1486819) as appropriate

**Comment by irenesmith** [comment]
Already in release notes, created a BCD pull request for #[1486819](https://bugzilla.mozilla.org/show_bug.cgi?id=1486819)

**Comment by chrisdavidmills** [comment]
@irenesmith make sure you update the actual bugs (dev-doc-complete, plus notes) when you are finished with this work. Then we can move the roadmap card to the archive column too. Thanks!

**Comment by jmswisher** [comment]
@irenesmith @chrisdavidmills This issue did not get moved into Diana Ross. Did it get finished?

**Comment by irenesmith** [comment]
I removed the items from this issue that are not completed and created new cards for the current sprint.

**Comment by chrisdavidmills** [comment]
@irenesmith smith I'm adding this into the tasks for Firefox 67, because it has been sat there since 64, apparently not done. Let's get this one done next sprint.

**Comment by irenesmith** [comment]
The work remaining in this card is all done. It shouldn't be in the 67 Epic at all.

**Comment by chrisdavidmills** [comment]
OK, cool. I see https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 is still marked as dev-doc-needed — can you set it to complete, and write what you did, so there is a record?
