### ISSUE TITLE
Cookie API Enhancements

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#513]
[Trello Issue](https://trello.com/c/AObljdHp/112-cookie-api-enhancements-fx-64)

Bugzilla #[1493057](https://bugzilla.mozilla.org/show_bug.cgi?id=1493057) - Make sure test_ext_privacy.js doesn't depend on the default value of the network.cookie.cookieBehavior preference

# Acceptance Criteria
- [x] Documentation added to [privacy.websites](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites#Properties)
- [x] Information added to the Firefox 64 Release Notes as appropriate

**Comment by chrisdavidmills** [comment]
@irenesmith this was marked as done in the spreadsheet, but it doesn't appear to be done. Can you update me on the status of this?

**Comment by jmswisher** [comment]
@chrisdavidmills @irenesmith Can this issue be closed?
