### ISSUE TITLE
Tabs API Enhancements

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#516]
[Trello Issue](https://trello.com/c/FaVjhDCL/117-tabs-api-enhancements-fx-64)

Bugzilla #[1489814](https://bugzilla.mozilla.org/show_bug.cgi?id=1489814) Add option to prevent tabs.highlight from populating the returned window

# Acceptance Criteria
- [x] New option documented in the tabs.highlight() documentation
- [x] Information added to the Firefox 64 Release Notes as appropriate (63?)

**Comment by irenesmith** [comment]
This was actually a 63 update.

**Comment by chrisdavidmills** [comment]
OK, cool. This is not a biggie, as long as you put the rel note in the right place.
