### ISSUE TITLE
The display property (Fx 64)

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#523]
As a web developer I want to understand the display property and browser support for each value.

# Acceptance criteria

The main page and subpages for display are up to date. 

_I think much of this was covered in my previous work, but I will check._
# Tasks

1. - [ ] Check and update https://developer.mozilla.org/en-US/docs/Web/CSS/display
2. - [ ] Check that this issue is represented correctly https://bugzilla.mozilla.org/show_bug.cgi?id=1486602

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm not sure how we would represent that issue in the docs (https://bugzilla.mozilla.org/show_bug.cgi?id=1486602) as we don't go that fine grained on support in terms of particular elements.

Do you know of any other examples like this?

Otherwise I recently updated display, in the other ticket is an outstanding issue re how we split out block, inline etc. but I think that probably needs someone other than me to make a decision.

**Comment by chrisdavidmills** [comment]
For the list-item/fieldset/legend bug, this is actually pretty easy to represent. You just need to nest another bit of support data inside the data for `list-item`, at the same level as the `list-item`'s `__compat` member:

https://github.com/mdn/browser-compat-data/blob/master/css/properties/display.json#L106

So for example something like:

```
          "list-item": {
          "__compat": {
            "support": {
              "chrome": {
                "version_added": "1"
              },
              "chrome_android": {
                "version_added": true
              },
              "edge": {
                "version_added": "12"
              },
              "edge_mobile": {
                "version_added": "12"
              },
              "firefox": {
                "version_added": "1"
              },
              "firefox_android": {
                "version_added": "4"
              },
              "ie": {
                "version_added": "6"
              },
              "opera": {
                "version_added": "7"
              },
              "opera_android": {
                "version_added": true
              },
              "safari": {
                "version_added": "1"
              },
              "safari_ios": {
                "version_added": true
              },
              "samsunginternet_android": {
                "version_added": true
              },
              "webview_android": {
                "version_added": true
              }
            },
            "status": {
              "experimental": false,
              "standard_track": true,
              "deprecated": false
            }
          },
          "legend-support": {
            "__compat": {
              "description": "Supported on <code>&lt;legend&gt;</code>"
              "support": {
                ...add support info in here
              },
              "status": {
                "experimental": false,
                "standard_track": true,
                "deprecated": false
              }
            }
          },
        },
``` 

Where is the other outstanding issue you mention? The split out block inline thing?

**Comment by rachelandrew** [comment]
ah great - I'll deal with that in a minute.

The other thing was in the other ticket regarding display: https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/456

**Comment by chrisdavidmills** [comment]
Ah, I getcha now.

So in this situation, I'd update the display data to create a new `display-outside` sub-member, have the compat values for `display-outside` set to what you'd expect for the basic `block` and `inline` values (they've been supported forever), and then have the compat data for `run-in` put as a sub-sub-member of `display-outside`.

That way, you could put the macro call on the display-outside page as `{{Compat("css.properties.display-outside", 10)}}`, and it would "basic support" followed by "run-in" in the same table.

**Comment by rachelandrew** [comment]
ah commented on the other thread (not sure how we ended up with two issues):
