### ISSUE TITLE
Document CSS Scroll Snap Level 1

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#524]
As a developer I want to understand the CSS Scroll Snap properties and browser support for them.

# Acceptance criteria

Pages for the relevant properties created, with live examples and browser data.

# Tasks

1. - [x] Create pages for each property
2. - [x] Update compat data
3. - [ ] Create live examples
4. - [ ] Deal with older properties (which are still needed for interop)

**Comment by rachelandrew** [comment]
PR for the data https://github.com/mdn/data/pull/321

**Comment by rachelandrew** [comment]
PR for all the missing compat data https://github.com/mdn/browser-compat-data/pull/3053

**Comment by rachelandrew** [comment]
I have added all the individual property pages now.

So what is outstanding are some live examples. We also only have an interactive example for [scroll-snap-type](https://github.com/mdn/interactive-examples/tree/master/live-examples/css-examples/scroll-snap) which isn't added to the page. Do we want to do that, and should I create interactive examples for the other properties?

With regard to the somewhat untidy state of interop, I think the best approach is to make sure the notes are up to date and then perhaps write a couple of guides, one being an overview of the new spec and another being a guide to compat between browsers which support the new and those which support the old spec.

**Comment by chrisdavidmills** [comment]
I think your view on the guides is fine — that's all it needs. It's not really a very complex spec, although it has loads of properties ;-)

For interactive examples, it is gonna be a pain making all of those. Perhaps you could just create 4 or so examples that demonstrate usage of multiple properties each, then for each interactive example just vary the one property we are showing in that particular page?

**Comment by jmswisher** [comment]
@rachelandrew @chrisdavidmills Looks like the last two tasks here are covered by issues #604 and #606. Can this one be closed?

**Comment by rachelandrew** [comment]
@jmswisher @chrisdavidmills yes I believe all that is now outstanding is the examples, and at least part of that is pending a decision on whether w can change the way examples work.
