### ISSUE TITLE
CSS Box Alignment Properties

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#525]
As a developer I want to understand the box alignment properties and support in browsers for them.

# Acceptance criteria

Pages on MDN which detail Box Alignment, including Guides are up to date and correct. Browser compat data is up to date.

# Tasks

1. - [x] Check and update compat data
2. - [x] Check and update property pages
3. - [x] Check and update Box Alignment Guides

**Comment by rachelandrew** [comment]
PR for compat data: https://github.com/mdn/browser-compat-data/pull/3058

It is very hard to find out exactly when some of this was implemented for flexbox, especially as a lot of it was really buggy initially.

I might ping a few people who may remember and if I get anything useful I'll update further.

**Comment by chrisdavidmills** [comment]
This seems fine to me for now; PR merged.

**Comment by rachelandrew** [comment]
I've been through these and made some changes, mostly to make sure it is clear they aren't just for flexbox.

I want to get those properties out of the flex menu though and into box alignment - they should be in the menu here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Alignment (which currently only shows the non-flex items.

**Comment by chrisdavidmills** [comment]
I think the way to do this is to make sure all the properties you want to appear in that sidebar have the "CSS Box Alignment" group in the data file:

https://github.com/mdn/data/blob/master/css/properties.json

**Comment by rachelandrew** [comment]
Pk, so here is a PR to try that https://github.com/mdn/data/pull/323

**Comment by rachelandrew** [comment]
the sidebar now looks better.

**Comment by chrisdavidmills** [comment]
Yay! ;-)
