### ISSUE TITLE
Create separate page template with only used CSS for testing

### ISSUE THREAD

**Issue by tkadlec** [mdn/sprints#527]
To verify the impact of #262 before spending too much time changing our build process, we want to create a separate page template for testing that has a manually reduced CSS file that contains only the CSS necessary for that page to display, followed by the full CSS being loaded async.

**Comment by jmswisher** [comment]
@tkadlec Can you add acceptance criteria and an estimate to this issue? Thanks.

**Comment by tkadlec** [comment]
- [] Static version of the `forEach` page has been created
- [] Static version of the `forEach` page has been created with unused CSS stripped out
- [] Static version of the `forEach` page has been created with all inline and external JS removed
- [] Static version of the `forEach` page has been created with all CSS and JS removed
- [] Once deployed, all pages are added to SpeedCurve

**Comment by jwhitlock** [comment]
@tkadlec looks like WebPageTest and documenting the results are the remaining tasks. Do you think this will be done this week, or should we move that task to next week / sprint?

**Comment by jwhitlock** [comment]
I've added #628 to cover the work on this thread for the next three weeks. Please think of acceptance criteria, estimates, and any further tasks.
