### ISSUE TITLE
Carry out user research on WebAPI/JS ref page titling

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#530]
# User story
As an MDN editor, I want research carried out into how people search for JS/WebAPI features, so I can name associated reference material intelligently

# Acceptance criteria

1. - [x] Questionnaire sent out
2. - [x] Appropriate material for user testing created
3. - [x] User interviews carried out. 

# Tasks

1. - [x] Send out questionnaire on social media
2. - [x] Create appropriate material for carrying out user testing
3. - [x] Carry out user interviews to observe behavior around searching for WebAPI/JS reference material.

The questionnaire is available here: https://docs.google.com/forms/d/1ClqKnMcSllGPoX-HhTkrtVzBqlvEDPn_N-G-4Vdabvk/edit (edit mode, not final version)

**Comment by jmswisher** [comment]
@chrisdavidmills Looks like this is done, per the AC. Can it be closed?

**Comment by chrisdavidmills** [comment]
Yes! Thanks for the prod.
