### ISSUE TITLE
Update pointer events docs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#534]
# User story
As a web developer, I want to have access to up-to-date pointer events docs, so I can use it effectively in my apps.

The work to be done is documented at https://trello.com/c/tOxWV0Jo/48-pointer-events-fx-64

# Acceptance criteria

1. - [x] Document missing features on MDN
2. - [x] Update BCD, platform-status, Fx 64 rel notes, etc.

# Tasks

1. - [x] Document missing features on MDN
2. - [x] Update BCD, platform-status, Fx 64 rel notes, etc.

**Comment by jmswisher** [comment]
@chrisdavidmills [One bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1507495) is still not marked DDC. Close anyway?

**Comment by chrisdavidmills** [comment]
Yes, because that bug has not been completed, and won't be for a while. So our work is completed as much as can reasonably expected right now. Once the bug to enable PE in Android has been resolves, we can put that card back in a sprint sometime later on.
