### ISSUE TITLE
Update Fullscreen API documentation

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#536]
Our Fullscreen API documentation is out of date.

## Acceptance criteria

- [x] Document `FullscreenOptions` and the `options` parameter on `requestFullscreen()`
- [x] Add `onfullscreenchange` to the `Element` docs
- [x] Add `onfullscreenerror` to the `Element` documentation
- [x] Document `Document.fullScreenEnabled`
- [x] Note that `Document.fullscreen` is historical (use `fullscreenElement` instead)
- [x] Add example for `::backdrop` pseudo-element
- [x] Clean up the `:fullscreen` article.
- [x] Ensure BCD includes all Fullscreen items with valid data for at least Firefox
- [x] Update GroupData.json to include everything
- [x] Verify all existing content is cleaned up
- [x] Ensure new material has appropriate sample coverage

**Comment by a2sheppy** [comment]
Added page: https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions/navigationUI

**Comment by a2sheppy** [comment]
Finished (I think) updates to https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

**Comment by a2sheppy** [comment]
Finished updating https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen

**Comment by a2sheppy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled updated

**Comment by a2sheppy** [comment]
Updated https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreen

**Comment by a2sheppy** [comment]
Updated https://developer.mozilla.org/en-US/docs/Web/API/Document/onfullscreenerror

**Comment by a2sheppy** [comment]
Added https://developer.mozilla.org/en-US/docs/Web/API/Element/onfullscreenerror

**Comment by a2sheppy** [comment]
Updated https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop

**Comment by a2sheppy** [comment]
Everything is done here. I am awaiting the merging of PRs to update BCD and GroupData.json changes; once those are done, this can move to the "Done" column.

**Comment by jmswisher** [comment]
@a2sheppy Did those PRs get merged? I don't see them linked to this issue.

**Comment by jmswisher** [comment]
Oops, no. I see the GroupData one, but not the BCD one.

**Comment by jmswisher** [comment]
Looks like this is the BCD PR? https://github.com/mdn/browser-compat-data/pull/3035
Counting this as Done and closing.
