### ISSUE TITLE
Write 5 interactive WebAPI examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#548]
# User story
For a few reasons:
* investigate how much of a problem Shadow DOM is likely to be
* get a sense of how the contribution workflow is
* get a sense of how the editor is
* prepare for user testing

...we will write 5 quite diverse interactive WebAPI examples.

# Acceptance criteria
5 examples are written and merged.

**Comment by jmswisher** [comment]
Just to be clear: We're putting this issue on ice for now, and not moving it forward to the next sprint (Chaka Khan). Correct?

**Comment by wbamberg** [comment]
Yes, thanks @jmswisher , that is correct.
