### ISSUE TITLE
Define triage process for doc issues in GitHub

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#551]
# Acceptance Criteria
- [x] Triage process has been documented
- [x] Triage process has been reviewed and feedback incorporated

**Comment by jmswisher** [comment]
Added GitHub-related changes as suggestions in the [Content bug triage process document](https://docs.google.com/document/d/1QTOxOni_fbgZmmMmczFBS2f3c7B-tiKafTIj4Hxumag/edit?usp=sharing). Assuming this document is the current state of practice, it should be transferred to a more public channel, such as the [MDN Durable Team Processes]( https://wiki.mozilla.org/Engagement/MDN_Durable_Team/Processes) document on wiki.mo. 

@chrisdavidmills Let me know if my changes look OK, and the document is ready to publish.

**Comment by chrisdavidmills** [comment]
@jmswisher yup, your changes look good, and I'm fine with it being published.

**Comment by jmswisher** [comment]
The [MDN Content issue triage process](https://wiki.mozilla.org/Engagement/MDN_Durable_Team/Processes/Content_issue_triage_process), with GitHub additions, is now on wiki.mo. It has been linked from the [Triage section of the main Processes article](https://wiki.mozilla.org/Engagement/MDN_Durable_Team/Processes#Triaging_Requests), which I also updated to reflect the new way of handling DDNs.
