### ISSUE TITLE
Opportunity Assessment: 6 concerns

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#552]
Create opportunity assessment for 6 areas of concern
https://wiki.mozilla.org/Engagement/MDN_Durable_Team/Processes/Opportunity_Assessment

Six areas: 

    User experience
    Accessibility
    Performance
    Security
    Privacy
    Internationalization

Acceptance criteria:

[x] Memo sent to MDN

**Comment by jmswisher** [comment]
@estelle: Was there a memo to the team about this (per the AC), or just a submission to the Opportunity Assessment form? @atopal Do you have what you need to grade the opportunity?

**Comment by estelle** [comment]
By memo I meant the form.
