### ISSUE TITLE
Continuous research screener survey 

### ISSUE THREAD

**Issue by shilili** [mdn/sprints#554]
# User story
As a researcher, I want to place a survey on MDN so that I can learn about the users of the site and to recruit interesting use cases for our interviews research with the team. 

# Acceptance criteria
1. Review screener survey with Kadir 
2. Agree on the final version to publish on site
3. Kadir places survey on site

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] Review survey with Kadir
2. - [x] Get the ok to publish
3. - [ ] Place on site

**Comment by jmswisher** [comment]
Abandoned
