### ISSUE TITLE
Logical Properties Guide: Introduction

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#598]
# User story
As a  web developer I want to get an overview of logical properties and values.

# Acceptance criteria
Guide written and linked to property pages.

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_Concepts_of_Logical_Properties_and_Values

**Comment by rachelandrew** [comment]
has this one been reviewed @chrisdavidmills? I'm just tidying up my list.

**Comment by chrisdavidmills** [comment]
Yes, this one got reviewed. Feel free to close if you are happy.
