### ISSUE TITLE
Logical Properties Guide: Margin, borders, padding

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#600]
# User story
As a  web developer I want to understand how and when to replace physical MBP properties with flow relative ones.

# Acceptance criteria
Guide written and linked to property pages.

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Logical_properties_for_margins,_borders_and_paddin

**Comment by chrisdavidmills** [comment]
Cool! Reviewing now...

**Comment by rachelandrew** [comment]
In doing this one discovered we are missing the border-radius logical mappings completely, so will need to make their pages.

**Comment by chrisdavidmills** [comment]
Cool, sounds fine.

I've finished my review by the way, looks great!

I was just thinking, maybe since there are so many new properties in this spec, in the reference section on the font page we should split them into categories below different headings?

**Comment by rachelandrew** [comment]
Yes that makes sense, I'll have a go at doing so.

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties 

Split up the properties. I think I am now done with logical properties!

**Comment by chrisdavidmills** [comment]
Yup, happy to close this now. Great work @rachelandrew
