### ISSUE TITLE
Logical Properties Guide: Sizing

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#601]
# User story
As a  web developer I want to understanding how sizing works with flow relative properties and values.

# Acceptance criteria
Guide written and linked to property pages.

**Comment by rachelandrew** [comment]
/en-US/docs/Web/CSS/CSS_Logical_Properties/Logical_Properties_for_Sizing

**Comment by chrisdavidmills** [comment]
Nice work Rachel. I've given both of you guides an edit, and moved them to here to neaten up the URLs and use our title casing rules:

* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Sizing
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts

I also updated the parent page so the links are correct.

**Comment by chrisdavidmills** [comment]
I think you can close these now, if you are happy with my edits.
