### ISSUE TITLE
CSS Scroll Snap Glossary Entries

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#602]
# User story

As a  web developer I want to understand what the new terms introduced for scrolling mean.

1. - [x] Scrollport
2. - [x] Scroll container
3. - [x] Snap positions

# Acceptance criteria

All entries written

**Comment by rachelandrew** [comment]
* https://developer.mozilla.org/en-US/docs/Glossary/Scrollport
* https://developer.mozilla.org/en-US/docs/Glossary/Scroll_container
* https://developer.mozilla.org/en-US/docs/Glossary/Snap_positions

**Comment by chrisdavidmills** [comment]
I've given these a quick edit and added the nav menu, tags, and some cross links. 

Looking great, thanks Rachel! If you are happy with my edits, you can close this.

**Comment by rachelandrew** [comment]
They all had an encoded <p> tag in them for some reason - pasting the sidebar info into the WYSIWYG view perhaps, so I removed that.
