### ISSUE TITLE
Scroll Snap Guide: Overview

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#603]
# User story

As a user I want to understand what scroll snapping is and how to use it.

# Acceptance criteria

Guide written and linked to property pages.

**Comment by rachelandrew** [comment]
This is now written https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts

**Comment by chrisdavidmills** [comment]
Edited, and happy! Feel free to close this if you are happy with my edits.
