### ISSUE TITLE
Scroll Snap Guide: Scroll Snapping across browsers

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#604]
# User story

As a user I want to understand how to get scroll snapping to work with browsers that use the older spec and those implementing the newer.

# Acceptance criteria

Guide written and linked to property pages.

**Comment by rachelandrew** [comment]
This guide is here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/compat

**Comment by chrisdavidmills** [comment]
Edited, and happy!

Moved to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat
