### ISSUE TITLE
Plan rewrite of the Intro to CSS Guide in the Learn area

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#605]
# User story

As the writer of these docs I need a plan in order to be able to tackle the rewrite of the beginners CSS Guide.

# Acceptance criteria

1. Plan created for the new Introduction to CSS series: https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS
2. Tickets raised for each section

**Comment by jmswisher** [comment]
@rachelandrew Wondering what the status is on this issue. Is it likely to get done during the current sprint? (I.e., by Tuesday the 27th) Looks like you're busy with logical properties and scroll snap.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've made a start on this, your comments appreciated. There are a couple of things that might be better put into the Styling boxes section, but I can do that. I mentioned them here as they seem to be something we should cover somewhere.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

Once we have a plan I'll set up issues for each part and I can then work through them. I think that while it is a fairly comprehensive rewrite I should be able to replace sections as I go, rather than needing to write the whole thing before updating it.

**Comment by chrisdavidmills** [comment]
This looks pretty reasonable, and covers the stuff I mentioned in my [tutorials plan](https://docs.google.com/document/d/1Uw5frKniAGw9bG2u-6eWAQzD4Tps3Qh3LLyg1QwvnfE/edit#heading=h.ea689asoy7hk). I've added a few comments, but overall I think sounds like a good plan. Thanks!

**Comment by rachelandrew** [comment]
cool - I'll take a look at your comments and then break it out into individual tasks here.

**Comment by rachelandrew** [comment]
I've created all the individual tickets so I can move these into future sprints. I think that concludes this initial planning work.

**Comment by chrisdavidmills** [comment]
I did see all the tickets for the articles; thanks for that!

Sorry for the late breaking comment, but a one more thing did sprint to mind — assessments. There is currently a pretty lightweight assessment at the end of the intro to css module. Do you think this will be suitable for inclusion in the new course? Do we need new assessments?

**Comment by rachelandrew** [comment]
I'd thought maybe to update that based on the rewritten guide to make sure it reflects the materials, unless you think we should have more of them, or take a different approach.
