### ISSUE TITLE
Bug 1501282 - Add a survey to compat tables

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#607]
We would like to add a new survey to the compat tables. It should be placed where we currently have the link "Update compatibility data on GitHub" for some time (weeks not months).

See e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/microphone#Browser_compatibility

I think there are two options to go about this:

1) Change the macro (https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L680) and re-render a lot of pages when we introduce the survey and when we want to remove it again.

2) Add some JS that does some temporary replacement of the GitHub link (this wouldn't require re-rendering all the pages twice).

John, Schalk, what do you think is better?

----

We decided on implementing this in JS. There is no need for any GA or l10n.

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1501282

## Acceptance Criteria

* [x] Link to survey live on pages with a compat table

**Comment by schalkneethling** [comment]
Hey All,

We need two things for this to complete:

1. The copy to use for the link
2. The link to the survey

Below is the current implementation. Let me know your thoughts @atopal @Elchi3 

![Screenshot 2018-11-26 at 11.20.37.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/d8d784ff-a4a6-47df-9fa7-c3b413749def)

**Comment by schalkneethling** [comment]
The other question is: Do we want to open the survey in a new tab, or the same tab?

**Comment by Elchi3** [comment]
Maybe: "Take the quick survey". Not sure what we used before.

New tab or not: I have no strong feelings. Maybe new tab to not disrupt the reader? What did we do elsewhere, e.g. in the soapbox?

**Comment by schalkneethling** [comment]
> Maybe: "Take the quick survey". Not sure what we used before.

Not sure either, would be good to get Sheeli's input

> New tab or not: I have no strong feelings. Maybe new tab to not disrupt the reader? What did we do elsewhere, e.g. in the soapbox?

Not sure about the soapbox, but the banner on the homepage links in the same tab. Different "workflow" though, seems like a new tab makes most sense.

**Comment by jwhitlock** [comment]
Shipped to production.
