### ISSUE TITLE
Bug 1504320 - For 5 days, replace Grid Tools banner with a Future Design Tools survey banner

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#610]
> Summary

For 5 days, replace Grid Tools banner with a Future Design Tools survey banner

> What feature should be changed? Please provide the URL of the feature if possible.

I'd like to run a banner on the homepage of MDN for en-US visitors (https://developer.mozilla.org/en-US/), temporarily replacing the Grid Tools/DevEdition banner.

The hopeful run date is Nov 19-23 (unfortunately Thanksgiving week, so if it's possible, a couple weekdays sooner would be helpful). We're hoping for at least 1,000 complete responses from Chrome visitors (with an similar amount of responses expected from Firefox users). DevTools developers can handle the coding and pull request, and I can provide a design with your approval. (First draft of the design can be found here: https://mozilla.invisionapp.com/share/CDOXD8KNUK6#/)

The banner would link to a Surveygizmo survey based on these questions (https://docs.google.com/document/d/1VLayXjXcmoAwGms_M7JSAdWuad-5hmi4iaMZC1OZLYE/)

(I know this is a really tight schedule - sorry about this!)

> What problems would this solve?

We want to measure the difference in level of developer interest in each of the ~20 experimental new tooling ideas of the Design Tools project. Determining this will help in prioritization of resources in 2019. 

Our continued goal is to bring Firefox back as an integral part of modern web design workflows.

I'll be presenting at All-Hands about the results.

> Who would use this?

En-US visitors to the MDN homepage.

> What would users see?

A friendly and inviting banner for an open-data survey about developer/designer problems. (First draft: https://mozilla.invisionapp.com/share/CDOXD8KNUK6#/

> What would users do? What would happen as a result?

Hopefully click on the banner and take the survey.

https://bugzilla.mozilla.org/show_bug.cgi?id=1504320

## Acceptance Criteria

* [ ] New survey banner live on landing page

**Comment by schalkneethling** [comment]
Posted screenshots to the bug and asked Victoria for feedback:
https://bugzilla.mozilla.org/show_bug.cgi?id=1504320#c15

**Comment by schalkneethling** [comment]
Opened PR for new banner: https://github.com/mozilla/kuma/pull/5100

**Comment by jwhitlock** [comment]
[bug 1504320](https://bugzilla.mozilla.org/show_bug.cgi?id=1504320) was supposed to track switching back, but has been taken over by a request for a new grid tools banner. Let's track that in a new user story for the next sprint.
