### ISSUE TITLE
DDN 54: -webkit-appearence — 

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#611]
Browser support: Firefox 64, -webkit- browsers of course.
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
Meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1368555

After the last failed attempt, the engineers have now managed to implement a -webkit- alias of appearance that behaves exactly like the WebKit and is therefore useful for compatibility.

https://bugzilla.mozilla.org/show_bug.cgi?id=1368555 - enable -webkit-
https://bugzilla.mozilla.org/show_bug.cgi?id=1480073 - create alias for -moz-
https://bugzilla.mozilla.org/show_bug.cgi?id=1496720 - [css-compat] Unship -moz/webkit-appearance values not supported by other UAs / spec

Acceptance Criteria

[X] - Bugzilla ticket changed to dev-doc-complete
[X] - https://bugzilla.mozilla.org/show_bug.cgi?id=1496720  marked as dev doc complete.

**Comment by estelle** [comment]
@chrisdavidmills There are 155 possible values. We have a table on https://developer.mozilla.org/en-US/docs/Web/CSS/appearance showing an example and listing which browser supports each one. I don't think it makes sense to have a BCD table with 160 rows, as https://bugzilla.mozilla.org/show_bug.cgi?id=1368555#c53 requests. Do you agree?

**Comment by chrisdavidmills** [comment]
@estelle the table is very useful, nice work on that. I agree that this is a case where the conventional BCD table would not be very useful to hold all that information individually.

So, for the BCD table I'd say:

* Definitely don't include any of the Fx-only values that have been removed (or any other browser-specific properties that have been removed)
* See how many properties that leaves you with 
* To cut down the number of rows further, think about which ones are covered by "Basic support"
* To cut down the number of rows further, try grouping together specific types of value that have similar browser support into single rows.

**Comment by chrisdavidmills** [comment]
So let me know how that goes ;-)

**Comment by jmswisher** [comment]
@estelle Is #674 the follow-on to this issue? Can this be closed?

**Comment by jmswisher** [comment]
Assuming the answer was yes.
