### ISSUE TITLE
Screen Capture API: getDisplayMedia() to capture screen

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#617]
Document/update getDisplayMedia() docs.

**Trello card:** https://trello.com/c/0oNSHXub/36-screen-capture-api-fx-64

## Acceptance criteria

- [x] All tasks in Trello completed, unless otherwise determined.
- [x] Submitted to engineering for review

**Comment by jmswisher** [comment]
@a2sheppy Is this continuing into Diana Ross (Sprint 4)?

**Comment by jmswisher** [comment]
@a2sheppy Looks like the Trello card was archived. Can this be closed?
