### ISSUE TITLE
MDN on GitHub Experiment

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#619]
# User Story
As MDN content creators and staff developers, we'd like to better understand the challenges and benefits of moving document creation and maintenance to GitHub, with a specific focus on its effect on the current eco-system of Kumascript macros.

# Details
We'd like to do this by creating a very small working model of MDN based on a GitHub repo containing a set of selected documents, as well as any related code. The goal of this "spike" would be to explore:
* what file or files would define a document and how would they be organized (hierarchical, flat, etc.)
* more easily-maintainable approaches for handling the demand for machine-readable document pieces (summary, interactive-examples, formal syntax, etc.) while at the same time providing a simple way to assemble the pieces into an actual document presentation (e.g., @wbamberg has introduced the idea of `recipes` for this)
* how would Kumascript macros translate into this new approach
* what code would be needed to transform the document files into document presentations, given that the document files may contain macros (e.g., we've talked about a two-phase approach here, where the first phase is to gather data about the documents -- for example the children of each document and/or documents by tag name -- and then, in the second phase, use that data to actually generate the document presentations via recipes and/or macros)

# Acceptance Criteria
* [x] List of results/recommendations/insights from this experiment

**Comment by escattone** [comment]
@wbamberg, @Elchi3 and I worked together on this for 3 days in the PDX office. The result is in the https://github.com/mdn/stumptown-experiment repo. It contains the current working model developed from walking through several HTML and CSS documents, and then actually implementing the HTML video element and the CSS transform property in detail. It is a work in-progress that will evolve with further exploration and input from others. @wbamberg has written a nice summary of our work which will be published to the repo soon, but until then here's a rough summary of our goals, conclusions and recommendations:
- here are our goals:
    - pull request model for content updates: content will live on GitHub and be updated using pull requests
    - a structure for reference docs:
        - concisely and clearly define and enforce the structure that docs (especially reference docs) will follow
        - be able to restructure reference docs relatively easily
        - be able to offer the structured content to third parties via an API
    - make it easy to contribute to our docs using commonly understood tools and formats
    - have a website that's faster, simpler, and easier to maintain than Kuma and Kumascript
- the repo, as it stands, represents the data of MDN, and a separate build step is required to turn that data into a website and perhaps an API as well
- finding the balance between structured, machine-readable content and easily readable/writable content is difficult, but for now we've settled on using a combination of Markdown for prose and, for structure, file hierarchy, YAML files, basic Markdown header hierarchy, and HTML comments as section delimiters.
- we like @wbamberg's idea of using "recipes", or ordered-lists of sections that make-up a document, for internally organizing documents and ensuring consistency among documents that share the same recipe
- block-style Kumascript macros (like `Compat.ejs` and `EmbedInteractiveExample.ejs`) will be replaced with recipe sections (which can be thought of as templates rendered with data gathered by a build step)
- inline-style Kumascript macros (like `xref.ejs`) will be eliminated by replacing them with their output (with the docs in GitHub rather than the Kuma database it will be much easier to do a global search and replace operation if we want to change, for example, a lot of links at a time, so that eases the loss of these kinds of macros)
- we'd like for this approach to deliver value as quickly as possible, and one idea we've thought about is to implement one category of documents, say the HTML documents, using this approach, while keeping the remaining documents under the old approach

**Comment by chrisdavidmills** [comment]
This is really exciting!
