### ISSUE TITLE
Write article about GDPR

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#62]
As a web developer I want to learn about the GDPR, how it affects my work, and what I need to do to be compliant with it.

See here for the relevant docs bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1460916

Note: We need to be careful here — we can't be seen to be giving legal advice, but we can give practical hints and tips, maybe even a checklist. We just need to be careful and provide disclaimers, in the same way we did for the [WCAG docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG).

**Comment by chrisdavidmills** [comment]
1. - [ ] Research what we should write about this.
2. - [ ] Write a plan.
3. - [ ] Get the plan checked by one of our legal folk.
4. - [ ] Write the article.

**Comment by Elchi3** [comment]
Looks stalled and is not currently planned. Closing.
