### ISSUE TITLE
DOM general enhancements

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#625]
# User story
As a web developer, I want to know about DOM enhancements, so I can use them in my work.

# Acceptance criteria
- [x] Doc updates from DDN bugs meet Definition of Done.

# Tasks
1. - [x] Complete bugs.
2. - [x] Set them to dev-doc-complete and ask engineers for reviews.
3. - [x] Add notes to the relevant rel notes.

See https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-64 for specific bugs.

**Comment by jmswisher** [comment]
@chrisdavidmills This issue was marked Done in Chaka Khan on the tracking spreadsheet. Should it be added to the Diana Ross tab, or closed?

**Comment by chrisdavidmills** [comment]
I've closed it; thanks!
