### ISSUE TITLE
Async JavaScript articles

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#627]
# User story
As an aspiring web developer, I want to learn about asynchronous JavaScript, so I can use it in my code.

I don't expect to get all of this done in this sprint, but I want to try and start on it.

# Acceptance criteria

1. - [x] Async landing page written
2. - [x] Introduction to Async JavaScript written.
3. - [x] Async Looping over code written (setInterval, setTimeout, and requestAnimationFrame)
4. - [x] Promises written.
5. - [ ] Async/Await written.
6. - [ ] Get sheppy to review it

# Tasks

See https://trello.com/c/MK3ewPT2/39-cover-async-js-features-in-learning-area for tasks.

**Comment by Elchi3** [comment]
This got written https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous

We can open a new issue if there more to be done
