### ISSUE TITLE
Glossary: visual viewport (p1)

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#635]
https://bugzilla.mozilla.org/show_bug.cgi?id=1490655
Add concept/explainer and glossary docs for visual viewport

We've got docs for the visual viewport API — https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport.

But some of these concepts are complicated, for example what is the difference between the visual viewport and the layout viewport?

I'd like to propose:

* Adding glossary entries for visual viewport and the layout viewport
* Write some kind of a concepts/explainer doc.

There's an explainer available here already: https://github.com/bokand/bokand.github.io/blob/master/web_viewports_explainer.md

But I think we could write one that's a bit more focused and easy to understand.

Tasks:

[X] - add glossary for visual viewport
[X] - updated glossary viewport to include layout and visual
[X] - add "using visualViewport API"  - https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

Acceptance Criteria: 

[x] - Bug resolved as fixed.

**Comment by estelle** [comment]
@chrisdavidmills I updated bugzilla with a question, but apparently my tagging foo is lacking.
what url or page type would be a good home for the "concepts/explainer doc"

**Comment by chrisdavidmills** [comment]
Hey there @estelle !

This is tricky one. Usually, when we write guides or concepts/explainer docs related to a particular API, we put them underneath the API landing page, e.g.

https://developer.mozilla.org/en-US/docs/Web/API/NameOf_API
https://developer.mozilla.org/en-US/docs/Web/API/NameOf_API/Using_the_NameOf_API
https://developer.mozilla.org/en-US/docs/Web/API/NameOf_API/NameOf_API_concepts

In this case, we don't have a proper API landing page, but it is only one interface, so we probably don't need one. We could just put the explainer underneath the Interface page:

https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport/Concepts

However, the viewports explainer is more of a general concept explainer. It is not explicit to this API, right?

In which case I'm not sure...if I had to choose, I'd probably say that it is closest to a CSS thing, so maybe we should put it at somewhere like

https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

?

Perhaps we could go with this for now, to avoid this becoming a blocker. We can always move it later on.

Finally, on Bugzilla if you want to get someone's attention you need to use the "needinfo" feature. Check the "Need more information from" checkbox underneath the commenting field, and enter my email address/handle into the text field to the right of it (it autocompletes).
