### ISSUE TITLE
Broken link in "Using CSS transforms" page (p1)

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#637]
https://bugzilla.mozilla.org/show_bug.cgi?id=1505239

Acceptance Criteria

[X] - Ticket resolved as <s>fixed</s> won't fix.

**Comment by chrisdavidmills** [comment]
I commented in the bug.

**Comment by estelle** [comment]
Ticket filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1509357

**Comment by chrisdavidmills** [comment]
Perfect, thanks. I've set the new bug as blocking the original one, so we can track them more easily.
