### ISSUE TITLE
Learning CSS Rewrite: 1.1 What is CSS?

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#638]
Individual tasks for the rewrite of the learning CSS section.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
with all of these the previous/next links will need to be updated once they are in place. I just copied over the code as a placeholder.

**Comment by jmswisher** [comment]
@chrisdavidmills is reviewing as part of #742

**Comment by Stubbierdisc79** [comment]
What

**Comment by rachelandrew** [comment]
Working on the second draft of this, there were some comments in the doc I didn't really agree with, or where I have moved that information elsewhere. As I wanted to tidy up the doc (but don't want to just delete any thoughts) I'll note them down here.

In addition I have clarified some sections and added a couple of images.

(It would be lovely if a future version of MDN allowed for actual editorial review in some way, perhaps linked to GH issues ...)

Under "What is CSS for?"

Chris: 
> [THIS SECTION SEEMS WAY TOO BRIEF. HERE I'D EXPECT YOU TO EXPLICITLY RUN THROUGH THE DIFFERENT KINDS OF THINGS CSS CAN DO, SO FOR EXAMPLE STYLING TEXT, BACKGROUNDS AND BORDER, LAYOUT, ETC.] SHOW SCREENSHOTS THAT GIVE CLEAR EXAMPLES TO DEMONSTRATE THE POWER AND VERSATILITY OF CSS]

This pretty much came from the original, I don't see what benefit outlining all the things CSS can do with screenshots can have, other than add a load of stuff to wade through). I have added an additional paragraph detailing some things we can do with CSS, I'm be less keen to make this an extensive walkthrough as I just don't feel it is necessary.

Chris:
> [HERE IT MIGHT BE NICE TO INCLUDE A COUPLE OF EXERCISES FOR THE READER TO DO, TO GIVE THEM THEIR FIRST EXPERIENCE OF CSS AND GENTLY INTRODUCE SOME CSS PROPERTIES. SOMETHING LIKE https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/How_CSS_works#Active_learning_Writing_your_first_CSS ?]

This (as in my outline) is moved to the next lesson.

Under CSS Modules:

Chris:
> [I THINK MAYBE THIS AND THE TWO FOLLOWING SECTIONS SHOULD BE PUT LATER ON, IN THE "HOW DOES CSS WORK" ARTICLE. THIS IS POSSIBLY A BIT SCARY? THE READER MIGHT NOT KNOW WHAT A MODULE OR A SPECIFICATION IS AT THIS POINT?]

I disagree. It's how we have arranged things on MDN to start with, which is how I'm explaining it. I don't see why it is scary to state that the language has structure. 

Added an additional paragraph explaining why this information is useful to have at the back of your mind. One of the things I want to do here is to be constantly guiding people into our docs, as that is where they need to be happy by the time they finish the Learn stuff.

**Comment by chrisdavidmills** [comment]
We've discussed all of this already, and I'm happy to bow to your wisdom here. I've just given the article a reread, and it totally makes sense as an introduction. When you're talking about the specific types of things CSS can do, maybe link to a few examples people can go and look at? Even MDN reference pages would be OK, as those have the interactive examples for people to check out.

**Comment by rachelandrew** [comment]
Updated that paragraph with some links.

**Comment by chrisdavidmills** [comment]
Perfect, thanks! I think we can close this one now.
