### ISSUE TITLE
Learning CSS Rewrite 1.2 Getting Started with CSS

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#639]
Individual tasks for the rewrite of the learning CSS section. This one for the second part of the introduction section.

> This is like the “first splash into JavaScript” guide. A practical walkthrough explaining the core concepts via applying simple text styling to a document.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by jmswisher** [comment]
@chrisdavidmills is reviewing as part of #742

**Comment by rachelandrew** [comment]
working on second draft

**Comment by rachelandrew** [comment]
@chrisdavidmills  There weren't comments on this one that I could see, I've done some tidying up as there were some drive-by edits. You mentioned generally to have more live examples so I don't know if you want me to move this way from "here is an example to try this CSS in" to just showing the individual live examples?

I can do that if you like, I just wasn't really sure what you intended.

**Comment by chrisdavidmills** [comment]
I think the fact that you've got one live example near the middle of the article is really nice — it is great to be able to read what you've said to try, and then be able to type it into the live example if you've not got your own code file set up to try it in.

I thought maybe include one or two more live examples at other key places for reader to try subsequent example code in? Maybe:

* One at the bottom of the "Styling things based on their location in a document" section, for trying out classes, descendant selectors, etc.
* One at the bottom of the "Styling things based on state" section, for trying out the link pseudoclasses ?

what do you think? I'm not saying I want you to do this — it is more of a suggestion.

**Comment by rachelandrew** [comment]
could do, I'd kind of assumed that they would be continuing in the same document to avoid repeating the example over and over.

We could of course simplify the first doc and have additional ones for smaller bits. However at the moment it is written assuming they are either working in their local copy or in that live example.

**Comment by rachelandrew** [comment]
I have battled the timeout errors on MDN and added two more examples (I also moved the examples into the repo on GitHub as it was all getting a bit messy and hard to edit.)

**Comment by chrisdavidmills** [comment]
Nice one Rachel — I've given this another minor copy edit, added a note near the top to mention the interactive examples, and played with the examples too. I am really pleased with this now, and think it is ready to g into the main learning area, when the time comes.
