### ISSUE TITLE
Learning CSS Rewrite 1.3  How CSS is structured

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#640]
Individual tasks for the rewrite of the learning CSS section. This one for the third part of the introduction section.

> A simple walkthrough of the various parts of the language, I’d like to tie this back to how we show things on MDN pages too, so right from the start a reader can go to any MDN page and understand what they are being shown.

>Selectors
Properties and Values
@rules
Shorthands
Comments
Functions

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
Updated this one with some images, a couple of live examples (a lot of the code in this one doesn't really make sense as a live example however).

**Comment by chrisdavidmills** [comment]
Makes total sense. I'm pretty happy with this one now too.
