### ISSUE TITLE
Learn CSS Rewrite 1.4 How does CSS work?

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#641]
Individual tasks for the rewrite of the learning CSS section. This one for the fourth part of the introduction section.

> This is the stuff about how HTML and CSS actually make us a webpage in a browser, and can be based on the document created in Getting Started.
> This can cover basic interop stuff, the fact that when CSS is not understood by a browser it is ignored and so on.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by chrisdavidmills** [comment]
Looks like it makes sense so far, thanks! Let me know when you think these are ready to review.

**Comment by rachelandrew** [comment]
I think these 4 are - as mentioned somewhere I haven't linked them together in the header and footer as we'll only have to redo it when we move them.

I also wondered if we wanted a little test type thing for these four rather than just at the end? But if so we can add that to the next sprint anyway.

**Comment by chrisdavidmills** [comment]
Hi @rachelandrew. I reviewed/edited all four of your beginners articles and left comments. 

The comments say quite a lot; although it is looking pretty good already, I've identified a few things I'd like to see improved.

Also, a general comment: They currently seem correct, but a little light on content. Maybe the expanded discussion of the different things css can do will help. Maybe we need an article or assessment at the end that will be a kind of css play ground, and the reader will be asked just to play and get some familiarity?

**Comment by rachelandrew** [comment]
I think maybe what I thought I was doing and what you thought I was doing are a bit different then. I *thought* the idea was to make these shorter and lighter on content in order to be less of a wall of text so we could move the more in depth discussion to the next part?

**Comment by chrisdavidmills** [comment]
I think we are both on the same wavelength. I think it is great that these documents are much lighter than the originals — this is exactly what I wanted. But I get the feeling that they are a little too light, and that the reader needs a few more opportunities to just play with some CSS.

Maybe my comments were a bit heavy handed...

**Comment by rachelandrew** [comment]
I only see comments (in caps) on the first one. And I disagree that we should immediately having people playing with CSS in an article designed to tell them what it is. Tell them what it is, get onto the one with the practical example, rather than mix it all together as it was before.

**Comment by rachelandrew** [comment]
In the second article we _immediately_ go into the example: https://developer.mozilla.org/en-US/docs/user:chrisdavidmills/CSS_Learn/Getting_started_with_CSS

There is someone else messing around with these too.

**Comment by chrisdavidmills** [comment]
That is really weird. I was sure I'd added some comments to the other articles. Maybe I was more jetlagged than I thought I was when I was writing these ;-)

OK, so I think you are right — we don't need to add in loads of practical examples to the first article. But I'd still like to see a bit more said about what you can achieve with CSS, otherwise it might not be clear to beginners why they are bothering with it.

and I also can't shake the feeling that we need slightly more in the way of a practical example to get them playing with a bit more CSS before the end of the first module. Maybe a CSS playground type exercise at the end of it, where you bring what you've learned so far together and write a simple example, then you are invited to edit it to make it look different?

**Comment by rachelandrew** [comment]
> "and I also can't shake the feeling that we need slightly more in the way of a practical example to get them playing with a bit more CSS before the end of the first module. Maybe a CSS playground type exercise at the end of it, where you bring what you've learned so far together and write a simple example, then you are invited to edit it to make it look different?"

yeah - that was why I suggested (above) having a little test at this point rather than just at the end. Given that we are splitting the 4 off from the building blocks. However it wouldn't need to be a marked test, it could just be a playground type thing again. Either really.

**Comment by chrisdavidmills** [comment]
Agreed — I don't think this needs to be a marked test. Just an opportunity to go and play.

**Comment by rachelandrew** [comment]
I have added a live example using various CSS and inviting them to play with that.

**Comment by chrisdavidmills** [comment]
I am pretty happy with this, looks good!
