### ISSUE TITLE
Learn CSS Rewrite 2.1 The Cascade and Inheritance

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#642]
Individual tasks for the rewrite of the learning CSS section. This one for the first part of the CSS Building Blocks section.

> As is says on the tin, explanation of cascade, inheritance, specificity.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
There is a first draft here. Did a lot of restructuring and rewriting, essentially switched the whole order around so we didn't start with a giant block about !important, also I tend to teach this in person starting with inheritance and working up.

I expect it will need more work, but would appreciate an initial read through from someone who hasn't been looking at it for two days as I think this is probably the trickiest one to get right. While at it spotted some missing compat data for `all` so submitted a PR to fix that.

https://developer.mozilla.org/en-US/docs/user:chrisdavidmills/CSS_Learn/Cascade_and_inheritance

**Comment by chrisdavidmills** [comment]
I've read through this, given it a copy edit, and left a few comments IN BOLD in the text. Overall I think this is looking pretty darn good; not too far to go.

**Comment by rachelandrew** [comment]
> "CHRIS - THE ABOVE TEXT SOUNDS LIKE IT SHOULD BE IN THE LANDING PAGE OF THE WHOLE MODULE, NOT SPECIFIC TO THIS ARTICLE. THIS SHOULD BE REPLACED WITH A PARAGRAPH MORE SPECIFIC TO THE CASCASE/SPECIFICITY"

Ah ok, so we'll have two landing pages one for the first four lessons, and then one introducing the building blocks? That makes complete sense, I just hadn't thought to do it :)

**Comment by rachelandrew** [comment]
I think I have addressed all of your comments for this one now.

**Comment by chrisdavidmills** [comment]
Great work Rachel — my comments are addressed really nicely, and I think this is a really good treatment of some very difficult concepts. This is ready to go now, when the time comes.
