### ISSUE TITLE
Learn CSS Rewrite 2.3 The Box Model

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#644]
Individual tasks for the rewrite of the learning CSS section. This one for the third part of the CSS Building Blocks section.

> Pretty similar to the existing guide to the Box Model.

> What is the Box Model?
Basics of margin collapsing
Changing box-sizing

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/The_Box_Model

The original covered overflow, however I have a separate section for that.

It also covered some backgrounds and borders stuff that I think could go into a separate module as mentioned in the other issue, which could also cover color a bit more, things like gradients. This one is quite lengthy already.

**Comment by chrisdavidmills** [comment]
Hey there! I've had a read, and here is some feedback:

* The first section is way too complicated for a beginner audience, imo. For example, "The type of box applied to an element is defined by the display property and relates to the outer value of display" — I think we need to wait a while before talking about inner and outer display.

To begin with, I think we need to show just a very basic example with a few block elements, and a few inline elements, and show the difference between the two main types of display first. Say about how elements have a default display value that governs whether they sit on one line or not, etc.

* Then you should talk about the fact that you can use the display property to change display types, and show something more like the existing first two examples and how you can use display: inline to make a bunch of block elements sit on the same line if you want to.

* Covering display: none might be nice too — show an example, talk about its uses, talk about potential a11y problems that can result.

* then talk about the box model like you have done. This bit is really good.

* then move onto margin, padding, etc. like you have.

* I'd also like to see some stuff about advanced display values like flex, grid, etc. Say that these will be covered in other places, and provide some links.

* Maybe also touch on inner and outer display values somewhere too? I'd be careful though. I struggle with this concept, so I'm not sure how beginners would cope.

**Comment by rachelandrew** [comment]
> The first section is way too complicated for a beginner audience, imo. For example, "The type of box applied to an element is defined by the display property and relates to the outer value of display" — I think we need to wait a while before talking about inner and outer display.

I disagree. This is how we are going to talk about this stuff from now on. It's how it's now defined, new people get the benefit of understanding this stuff from the outset. It's confusing if you didn't start out that way as essentially we've backed this stuff into the specs as a definition.

> "Then you should talk about the fact that you can use the display property to change display types"

This is about the box model not the display property though. The same for talking about grid and flex. This is about the box model. I don't think muddying the waters by talking about different layout methods now is helpful.

I need to mention these things in as much as it is important for people to understand that everything is block or inline, it doesn't matter if it is a flex container or something with display: block, but heading down the road of starting to define what grid and flex layouts are ...? We already have material on that.

**Comment by chrisdavidmills** [comment]
> I disagree. This is how we are going to talk about this stuff from now on. It's how it's now defined, new people get the benefit of understanding this stuff from the outset. It's confusing if you didn't start out that way as essentially we've backed this stuff into the specs as a definition.

OK, fair enough. But in that case you need to explain it carefully and slowly...I'm still worried that it is going to blow people's minds ;-) As it was written, you kind of mentioned it in passing, almost as if we'd talked about it previously. Maybe include a dedicated section to explain inner and outer display in a separate section somewhere?

>This is about the box model not the display property though. The same for talking about grid and flex. This is about the box model. I don't think muddying the waters by talking about different layout methods now is helpful.

>I need to mention these things in as much as it is important for people to understand that everything is block or inline, it doesn't matter if it is a flex container or something with display: block, but heading down the road of starting to define what grid and flex layouts are ...? We already have material on that.

Yeah, I didn't mean you should go into them in great detail; just mention in passing that there are other display types too, which we'll talk about in other places.

**Comment by rachelandrew** [comment]
@chrisdavidmills so I have revised the introductory part of this one, I really think the key thing is the focus on block and inline layout, because they don't have the context of other values as yet.

**Comment by chrisdavidmills** [comment]
This is looking much better, cheers @rachelandrew !

I had a few more comments: 

* "If a box is defined as a block, it will behave in the following ways:" — one key thing I think needs to go into the lists of block and inline characteristics are typical width behaviour — block elements by default span 100% of the width of their parent elements, while inline elements are as wide as their content?
 * In the padding example, with the .container and .box boxes, it might be nice to get them to try changing the padding of container too, and help them understand that .box is the content of .container — it works the same way even though the content is another element, not text.
 * In the inline block section, it might be good to highlight the inline-block characteristics, like you did for block and inline earlier on. I think it is most important to understand that boxes will not break onto a new line, but width and height will apply and padding, etc. will have an effect on the position relative to surrounding elements. Maybe also give spme examples of where inline block is so useful, e.g. the classic horizontal nav items. you don't need to show example code here, maybe just describe, show an image, and link to an example somwhere else?

**Comment by rachelandrew** [comment]
I already had the width behavior (spoiler, it's not width) **"The box will extend in the inline direction to fill the space."**. I have added that in most cases this is width. Could link up the writing modes stuff.

People will be confused about the two value syntax if we persist on insisting that inline = width.

The padding example, that's a good addition. Have done so.

inline-block, turned out it was easier to build an example than find an example, so I have done!

**Comment by chrisdavidmills** [comment]
All sounds reasonable. I've had a look at your latest updates, and I think it all looks good. I think we can call this one done for now. I'll probably make a few more additions when we put it in the right place.

**Comment by rachelandrew** [comment]
I've added an issue which is essentially a task for going through the whole lot for consistency once I'm done, so as well as adding links and so on, making sure I haven't repeated myself or failed to mention something which will be obvious when read as one complete piece.
