### ISSUE TITLE
Learn CSS Rewrite 2.4 Writing Mode and Direction

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#645]
Individual tasks for the rewrite of the learning CSS section. This one for the third part of the CSS Building Blocks section.

> I think this worth covering up front given that newer specs will have support baked in, and working to block and inline, start and end is going to become pretty much the default ultimately.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
This, and the two that follow it (overflow, and sizing) is an attempt to intro things which I think are going to become increasingly important in understanding modern CSS. So not trying to go overboard here, but want to demonstrate the concept of block and inline as something which relates to writing modes (as flex and grid etc. are much easier to understand then).

https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Writing_modes_and_Logical_Properties_and_Values

**Comment by chrisdavidmills** [comment]
@rachelandrew I've read through this, and made a few editorial tweaks. Nothing specific to call out really — I think this is really good. It is a complex topic, but you've kept it simple and explained things well enough that I think this works nicely for the audience.

**Comment by rachelandrew** [comment]
great :)
