### ISSUE TITLE
Learn CSS Rewrite 2.5 Overflow

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#646]
Individual tasks for the rewrite of the learning CSS section. This one for the fifth part of the CSS Building Blocks section.

> What is overflow, how to manage it. Although maybe this should go into the Styling Boxes section?

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
Another short one, really mostly to explain that this concept exists as it's important for sizing and also for people to understand in the context of legacy stuff where they might see things overflowing.

https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Overflow

**Comment by chrisdavidmills** [comment]
Looking good! I just had a couple of comments:

* "You could also scroll on the x axis using {{cssxref("overflow-x")}}, although this is not a recommended way to deal with long words!" - maybe mention briefly what kind of solutiond we have available, e.g. hyphens property?
* Is it worth mentioning the BFC at this stage? What is currently in the article is a bit short and confusing, and probably needs a bit more detail to show an explain and explain why this is significant.

**Comment by rachelandrew** [comment]
1. I'd started mentioning that and then it didn't seem to fit here ... but I could.

2. I can't really explain the BFC more without explaining containing floats and we're ahead of that. I'm not sure what is confusing about explaining it turns the contained element into a mini layout in order to enable it to be a scrollable area. That's perfectly correct. I'd essentially have to remove the explanation otherwise, and I think introducing terms is important personally.

**Comment by chrisdavidmills** [comment]
> I'd started mentioning that and then it didn't seem to fit here ... but I could.

I don't think it needs much — just a couple of sentences and some links. 

> I can't really explain the BFC more without explaining containing floats and we're ahead of that. I'm not sure what is confusing about explaining it turns the contained element into a mini layout in order to enable it to be a scrollable area. That's perfectly correct. I'd essentially have to remove the explanation otherwise, and I think introducing terms is important personally.

I agree that it's good to introduce terms where relevant; I just had a few concerns around what the BFC means in real terms, to a beginner learning CSS:

1. I've been doing CSS for nearly 20 years, and have rarely ever heard this term. I can understand what you mean by it, but it's never been vital for my understanding of how to do CSS layouts. Is it a new thing? I'm not saying I don't think it's important — I believe you; you know this stuff better than I do. But why is it important to know this term, in real terms? 
2. "becomes a mini layout of it's own" — it almost sounds like you're saying it is effectively removed from the rest of the page, so the styling for the BFC is encapsulated, almost like it were in an `<iframe>` for example, but this isn't the case.
3. "Nothing can then poke out of that box into the surrounding layout." — ah, so this is more helpful. I think basically we just mean that the actual content (e.g., the child nodes of the box we are setting overflow auto/scroll on) is contained inside the box, so when including overflow'ed boxes in a layout, it then becomes easier to position them without worrying about the content affecting (or overlapping) what is outside the box? 

So I've changed my mind somewhat; I don't think you should get rid of the content. But I do think  it needs a bit of clarification and some careful wording to make it clear what the real impact of BFCs is on your CSS.

**Comment by rachelandrew** [comment]
> "I've been doing CSS for nearly 20 years, and have rarely ever heard this term."

That's right. We're doing a lot of work to clarify how CSS actually works. There are plenty of things that people who have been doing CSS for 20 years just know, and in some cases didn't really have a name, but now it does, and I believe teaching the correct terminology is important. Just as with not telling people inline = width etc.

CSS is going to get more complex in terms of layout methods and so on, these terms are going to become more important in understanding that.

**Comment by chrisdavidmills** [comment]
> That's right. We're doing a lot of work to clarify how CSS actually works. There are plenty of things that people who have been doing CSS for 20 years just know, and in some cases didn't really have a name, but now it does, and I believe teaching the correct terminology is important. Just as with not telling people inline = width etc.

I think it is a marvellous effort, and I'm so glad our resource can help with this. I am just amazed at how many instances of this we are coming across during this project.

> CSS is going to get more complex in terms of layout methods and so on, these terms are going to become more important in understanding that.

I understand, and agree. I still think it needs a bit of clarification, as per the rest of my comment, but I totally agree.

**Comment by chrisdavidmills** [comment]
> we should start them out in a modern way, rather than inflicting them with the hacky nature of the past :D

Oh, I totally agree, and I knew there would be some changes and additions to terminology, fundaments, etc., to bring it into modern CSS land; I am just surprised by quite how many.

> Added some info about word breaking. Also clarified the BFC stuff, let me know if this is any better for you.

This is fine; I am now happy. We can call this one done for now!
