### ISSUE TITLE
Learning CSS Rewrite 2.6 Values and Units

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#647]
Individual tasks for the rewrite of the learning CSS section. This one for the sixth part of the CSS Building Blocks section.

> Probably broken into separate pages with an initial introduction, including how to read the allowable values if looking at a property page on MDN.

> Text
Numbers
Distance
Colors
Functional Notation

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
@chrisdavidmills https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Values_and_units a first draft for you

**Comment by chrisdavidmills** [comment]
@rachelandrew looking good Rachel! I've gone through it and given it a copy edit. I also had a few comments for you to follow up on:

"Relative units"

-- There are a lot of units in this table, and some are hard to understand by a beginner, for example ex, ch, ic, rlh, vi, vb? I'm pretty experienced with CSS and I've never used these in my life. Could we cut these out and say that the table shows the most commonly encountered relative units, to make it less overwhelming for beginners?

"background-position: top 40px right 5em"

-- In the position section we explain the basic position values but in the example you use four-value syntax, which could be considered more advanced. I'd probably prefer you to use two-value syntax, but if you really want to use four-value syntax can you add explanation of it in the text?

-- In general, you need to go through the code examples and make the indentation consistent and follow the MDN style guide. Some of the examples have the indent set as 2 spaces, and some use 4 spaces (or possibly tabs?) They need to be 2 spaces.

-- Also in the examples, there are a couple of instances of "width:400px;" — there needs to be a space after the colon and before the property value.

**Comment by rachelandrew** [comment]
@chrisdavidmills cool, I'll come back to this once I've got you a first draft of the Box Model stuff.

When we discussed this you suggested having lengths and colors as separate articles. I'm not sure if this needs breaking up though, and while working on the box model stuff I wonder if there is scope for an additional article about practical uses of things like backgrounds and border. That doesn't really fit with "box model" and could cover a bit more interesting usage of color.

**Comment by rachelandrew** [comment]
> "-- There are a lot of units in this table, and some are hard to understand by a beginner, for example ex, ch, ic, rlh, vi, vb? I'm pretty experienced with CSS and I've never used these in my life. Could we cut these out and say that the table shows the most commonly encountered relative units, to make it less overwhelming for beginners?"

yes that's fine, I've shortened it to the most commonly used for webdev.

> "-- In the position section we explain the basic position values but in the example you use four-value syntax, which could be considered more advanced. I'd probably prefer you to use two-value syntax, but if you really want to use four-value syntax can you add explanation of it in the text?"

ok, using two value syntax. Maybe if I do a backgrounds and borders lesson I could intro the four value there?

> stuff re code formatting

I think I have them, I forgot to go through them. AFAIK there is no way to get vscode to format automatically the bits inside the text areas and keep them squoosed up to the edge so we don't get a load of extra white space. 

I think that is everything though.

**Comment by chrisdavidmills** [comment]
I think this is pretty much good to go; a couple more small bits:

* There are still a few 4-space indents, but we can fix these when put it in its final place.
* The following declaration is still confusing — `background-position: 40px right;`. In the current state the value doesn't seem to work, as it is expecting a horizontal then a vertical value, but you've got vertical then horizontal values, so what seems to be happening (in both Fx and Chrome) is that the star is pushed 40px to the right, and then no change vertically. A value like '40px top' makes more sense.

**Comment by rachelandrew** [comment]
> "There are still a few 4-space indents, but we can fix these when put it in its final place."

I just fixed a couple more

> "The following declaration is still confusing"

I'd switched the values, fixed now.

**Comment by chrisdavidmills** [comment]
Perfect, thanks. We can call this one done now.
