### ISSUE TITLE
Learning CSS Rewrite 2.7 Sizing

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#648]
Individual tasks for the rewrite of the learning CSS section. This one for the sixth part of the CSS Building Blocks section.

> I think this is separate to values and units as we need to cover concepts such as intrinsic sizing. In values and units we can cover length being a thing and so on. Again, this might be better as part of styling boxes, if we think so I could write it for there.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
I've got about half of the text of this one so far, so will need to bump into the next sprint as I went back to do the second draft stuff of others.

**Comment by chrisdavidmills** [comment]
That's fine; let me know when it gets finished and I'll review

**Comment by rachelandrew** [comment]
First draft of the Sizing lesson (another of these shorter pieces on core bits of knowledge): https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Sizing

**Comment by chrisdavidmills** [comment]
Looking good @rachelandrew , thanks! This reads really nicely, and provides a great explanation on sizing. I agree that this is really important for beginners to understand early.

Only a couple of comments:

1. In the bit where you talk about responsive images, it might be worth linking to my responsive images article — https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images — for further techniques.

2. The example with the letter A being given a `font-size` in `vh` units doesn't work very well when embedded in the page, as the example's page is the `<iframe>` it is embedded in, so the height never changes. It would work work slightly better using `wv` units, but better still would be just to maybe link to the version directly on GitHub instead?

**Comment by rachelandrew** [comment]
Added the link.

The example with the A does seem to work as I would expect to be honest, in both Nightly and Chrome. It is using the iframe but it does change. We can link to the example if you like but I'm puzzled as to what you are seeing - or not seeing :D

**Comment by chrisdavidmills** [comment]
> The example with the A does seem to work as I would expect to be honest, in both Nightly and Chrome. It is using the iframe but it does change. We can link to the example if you like but I'm puzzled as to what you are seeing - or not seeing :D

This is really weird. When I look at the example standalone (i.e. directly load up the example as it is inside the GitHub repo), then it works as expected.

But when I try altering the viewport width/height of the MDN page when it is embedded inside the article, it doesn't work.

**Comment by chrisdavidmills** [comment]
Apart from that, I am happy to close this one. But I am a little concerned. Maybe link to the github example as well as showing it in the article, just in case?

**Comment by rachelandrew** [comment]
Ah right, what we have here is where what I am describing as working is different to what you are talking about :D I was thinking about people changing the values in the CSS panel, you are describing resizing the window, which of course does not change an iframe.

I have added an explanation and link to the file directly.

**Comment by chrisdavidmills** [comment]
Perfect, thanks!
