### ISSUE TITLE
Learning CSS Rewrite 2.8 Images, media and form elements

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#649]
Individual tasks for the rewrite of the learning CSS section. This one for the eighth part of the CSS Building Blocks section.

> Essentially covering some of the basics of replaced elements and their behavior as regards to CSS.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Images,_media_and_form_elements

A bit of a roundup of useful things to know. In the HTML Forms section of Learn are two detailed guides on form styling which I have referenced, but I wonder if they are better moved into CSS?

**Comment by chrisdavidmills** [comment]
This is really good @rachelandrew . I had a few bits of feedback, but nothing major:

Feedback:

* In the "Sizing images" section, what is there is really great, but I wondered if it was worth mentioning what could be done to make the image look better if it is smaller than the box, e.g. center it using something like display: block; margin: 0 auto?

* In the "CSS Shapes" section, I wonder if it is worth getting them to open up their Firefox DevTools and use the shapes inspector to see what is going on? Maybe just provide a link to the Shapes inspectr if you don't want to add too much

* In the "Form elements" section, it might be better to move the links to the HTML Forms articles to the end of the section, annd tell them to look at those for more details. We can't guarantee that people will have worked through those articles first. I see what you mean about moving them somewhere in the CSS section, but TBH I am not sure where they could go for the best. I am still deciding what to do about the Forms module. I inherited it from somewhere else and it doesn't quite follow the same pattern as the other stuff.

**Comment by rachelandrew** [comment]
> In the "Sizing images" section, what is there is really great, but I wondered if it was worth mentioning what could be done to make the image look better if it is smaller than the box, e.g. center it using something like display: block; margin: 0 auto?

these days you'd probably use flexbox, but this isn't about layout so that seems to be getting ahead of ourselves.

> In the "CSS Shapes" section, I wonder if it is worth getting them to open up their Firefox DevTools and use the shapes inspector to see what is going on? Maybe just provide a link to the Shapes inspectr if you don't want to add too much

I'm covering DevTools in the next section so didn't really want to get into that. I've linked to the article though.

> In the "Form elements" section, it might be better to move the links to the HTML Forms articles to the end of the section, annd tell them to look at those for more details. We can't guarantee that people will have worked through those articles first. I see what you mean about moving them somewhere in the CSS section, but TBH I am not sure where they could go for the best. I am still deciding what to do about the Forms module. I inherited it from somewhere else and it doesn't quite follow the same pattern as the other stuff.

Have done. Maybe we can have a look at it all after we get these new lessons live and see if moving stuff around makes sense.

**Comment by chrisdavidmills** [comment]
@rachelandrew Yup, yup, and yup. I agree with these comments and changes, so nothing more to do for now on this one.
