### ISSUE TITLE
Learning CSS Rewrite 2.9 Inspecting CSS

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#650]
Individual tasks for the rewrite of the learning CSS section. This one for the ninth part of the CSS Building Blocks section.

> Introducing DevTools and how to understand what you are seeing. I think this is separate to debugging as the tools can be used to try things out, or to see how other people have achieved a certain thing. So I’d like to intro tools in that regard first.

https://docs.google.com/document/d/1vN0gWLZe_IweWJnYi9q1eMBUsaxdafxfu-ed383nPI8/edit?usp=sharing

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/User:chrisdavidmills/CSS_Learn/Inspecting_CSS

I didn't want to reproduce all the stuff we have around DevTools as it will only need updating. So I have linked to various existing pages in what I see as a light intro to the fact these things exist and why you should care. Let me know if you think we should repeat anything in particular here.

**Comment by chrisdavidmills** [comment]
I've had a look over this, and given it a copy edit. Looking great! I only had one small comment, which I'm not 100% convinced about:

* Maybe call it "Debugging CSS", as "Inspecting" might be somewhat less familiar to beginners?

**Comment by rachelandrew** [comment]
So this is now debugging CSS as discused with a new section about general debugging, creating a reduced test case etc.

**Comment by chrisdavidmills** [comment]
@rachelandrew I really enjoyed reading this update; it is really good, thanks Rachel!

I just made some small copy edits and added in a few more useful cross links; nothing major to comment on. I think we can call this done now.
