### ISSUE TITLE
UI / a11y: Confirmation checkbox can't be selected by label (vs terms link can't be visited)

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#704]
Before https://github.com/mozilla/kuma/pull/5101, the checkbox label could be clicked to select the checkbox, which is considered good practice for checkboxes. However, the [Payment Terms](https://developer.mozilla.org/en-US/payments/terms) link could not be clicked, and instead selected the checkbox.

As part of https://github.com/mozilla/kuma/pull/5101, the text was changed so the "visible" label doesn't select the checkbox. This allows [Payment Terms](https://developer.mozilla.org/en-US/payments/terms) to be clicked.

It is unknown if it is possible to implement the original design: a label that selects the checkbox, except for the link, which opens the link.

## Acceptance Criteria

* [x] A label that selects the checkbox, except for the link, which opens the link.

**Comment by escattone** [comment]
Deployed.
