### ISSUE TITLE
Bug: Remove highlights around inputs on click.

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#705]
We should remove the grey border/shadow highlight when clicking on elements and only show them when using keyboard interaction.

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be02a353f001c7c0f533e6a/1fc6d1279382beaf277684c8974cd596/Screenshot_2018-11-05_at_11.31.40.png)

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be02a353f001c7c0f533e6a/764b0df37e6392ca52feb090f98ca3a2/Screenshot_2018-11-05_at_11.31.44.png)

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be02a353f001c7c0f533e6a/055dc71fb21ed422a6e8757dcfc77378/Screenshot_2018-11-05_at_11.31.48.png)

## Acceptance Criteria

* [ ] Focus only shown when user starts using keyboard

**Comment by jwhitlock** [comment]
Shipped to production around January 16th.
