### ISSUE TITLE
“Pay” button not visible after clicking it, when required fields are empty

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#706]
Env:
Ubuntu 16.04, Firefox 63
Fedora 28, Firefox 63

STR: 
1. Navigate to mdn staging homepage, not logged in 
2. Click "Support MDN" button
3. Leave all the fields empty and click "Pay" button

Expected:
Error messages are displayed, Pay button is visible

Actual:
Error messages are displayed, Pay button is not visible, even after scrolling up/down. See video below.

https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf3e50ee750cf42a70cce19/dd7072c5bd5facb28a1bfae0efe2c38f/pay_with_empty_fields-2018-11-20_11.00.30.mkv

# Acceptance criteria

1. - [ ] Pay button is not obscured when field errors are shown

**Comment by escattone** [comment]
Deployed.
