### ISSUE TITLE
The email tooltip is wrongly displayed

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#707]
Affected versions]:
Firefox, Chrome, Internet Explorer
 
[Affected Platforms]:
Windows 10, Ubuntu 16.04

[Steps to reproduce]:
1.Go to https://developer.allizom.org
2.Click to expand the Support MDN banner
3.Click the “?” icon located in the email field
4.Scroll the page up/down
 
[Actual result]:
Internet Explorer: the email tooltip is displayed at the top of the page. The tooltip is not moved while scrolling
Firefox/Chrome: The tooltip is moved with the page while scrolling

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf40dfd9286ef894f52ff80/617a709f4f1bad451d3a6a95adf0d93a/2018-11-20_15h27_18.gif)

# Acceptance criteria

1. - [x] Tooltip is always correctly positioned on all supported browsers and operating systems.

**Comment by escattone** [comment]
Deployed.
