### ISSUE TITLE
Design QA: Thank you page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#708]
Various tweaks needed that was identified during design QA.

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be1a0515ad50855058917fc/7b8753733122ac933f7389598c63c207/Screenshot_2018-11-30_at_17.11.30.png)

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be1a0515ad50855058917fc/d325cbbd409da93c2dd052206bf1ddc3/Screenshot_2018-11-30_at_17.06.37.png)

## Tasks

1. [x] Left margins should be consistent down the side of the page: payment section copy ('Thank you for supporting MDN...") and the sections below ('Useful things') should have the same margin.
2. [ ] The secondary headings should align with the footer links (ask Charlie for more info)

**Comment by jwhitlock** [comment]
Deployed around January 16th
