### ISSUE TITLE
Design QA: Banner shown and Banner open form

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#709]
Various tweaks needed that was identified during design QA

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bd97195fd550a3127854b7e/b315d14b9347de73450528842d0c09b8/Screenshot_2018-11-30_at_16.46.14.png)

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bd97195fd550a3127854b7e/0ad186b6fc726c424ad8a0885f447831/Screenshot_2018-11-30_at_16.56.36.png)

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bd97195fd550a3127854b7e/c791144fd6d5e4c4ba21830b7cf128c7/Screenshot_2018-11-30_at_16.56.24.png)

## Tasks

1. - [x] Banner shown: form placeholder text #9B9B9B
2. - [x] Banner shown: one-off payment brackets should have 16px margin between them
3. - [x] Banner open: If user is not logged in, after clicking pay button, the white container should keep the same height as the form when showing the sign in button + copy.
4. - [x] Banner shown and open: Close banner 'x' should be #222222 (matching the shade of black used elsewhere in the form)
5. - [x] Banner shown: 'Give back to MDN' is slightly off vertical center
6. - [x] Banner open: all form inputs margin top should be 16px — as a rule, form spacing, be it padding or margins, should be 16px
7. - [x] Banner open: pay button should be Arial Bold (700)
8. - [x] Banner open: `p.legal-copy` — line height should be 20px, currently 1.35 which isn't right, my fault!)

**Comment by schalkneethling** [comment]
> Banner shown: form placeholder text #9B9B9B

Keeping this as is, as it is a fixed style across all of MDN

> Banner shown: 'Give back to MDN' is slightly off vertical center

No longer applicable

> Banner open: all form inputs margin top should be 16px — as a rule, form spacing, be it padding or margins, should be 16px

We alrighty have a height problem when all of the fields are in an error state. Adding additional top margin is not advisable.

> Banner open: p.legal-copy — line height should be 20px, currently 1.35 which isn't right, my fault!)

It is best practice to not set `line-height` using a unit of measure. Also, `20px` roughly calculates to `1.5` which seems a bit much. I decided to take something in the middle and set it to `1.4`.

**Comment by jwhitlock** [comment]
Deployed to production around January 16th.
