### ISSUE TITLE
Design QA: FAQ page and form

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#710]
![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bd9711075073a641dd23449/20122af57a7ceecc3deaef8c7aa67b91/Screenshot_2018-11-30_at_16.46.29.png)

# Tasks

1. - [x] Dinohead should be behind the first faq card
2. - [x] 'FAQ' h1/2 should share the left margin of the 'Give back to MDN' above.
3. - [x] Anchor links should be blue with an underline
4. - [x] "was this useful" font-weight 700 (bold)
5. - [x] Pay button is not in the same place as on the banner: on banner its aligned left, on FAQ page form its kind of in the middle.
6. - [ ] 'FAQ' title should be fixed on scroll

**Comment by escattone** [comment]
Deployed.
