### ISSUE TITLE
Edge: The banner is displayed with delay when is expanded/compressed

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#711]
It seems like Edge is having a bit of trouble with the expand/collapse CSS transition. It might actually not be Edge itself, but perhaps a low powered machine that is the root cause.

Need to investigate and see what possible resolution there is.

![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf40730e1f68713914d23ce/dcb61e902b7df225d6caad44b549add6/2018-11-20_15h05_03.gif)

**Comment by schalkneethling** [comment]
I have looked at this in Edge. Performance for me is good. I can see that on a system with no GPU and a slow CPU, this can lag to some degree. It is still going to be much better than any JavaScript solution as the animation is handled natively by the browser.

@atopal What . do you think, should we close this as "works for me"?

**Comment by jwhitlock** [comment]
@schalkneethling thanks for investigating. I think we can close the issue since it works well on a "real" computer, not a VM testing rig.
