### ISSUE TITLE
As a user, I want to be able to change the payment method and amount from my MDN profile page.

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#715]
![](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf41a31f7e66275dbbe1212/963b710a5013633f3f3b4b70ab52f1af/Subscriptions_edit_stripe_overlay--inactive.png)

# Acceptance criteria

1. - [ ] Designs for changing payment type and amount

**Comment by jmswisher** [comment]
No longer valid
