### ISSUE TITLE
As a developer, I'd like code to use "Payments" instead of "Contributions", so that I can focus on implementation instead of names.

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#717]
Complete the transition from ``kuma/contributions`` to ``kuma/payments``. These items can be done with other work when it makes sense, and completed in the down time between efforts.

Most name updates have no user impact if done correctly. Changing the name of the waffle flag from ``contrib_beta`` will reset the cohorts. This could be desirable around a change, such as 1% to 5%.

# Acceptance criteria

1. - [ ] Flag constant is ``PAYMENTS_BETA_FLAG=contrib_beta`` (``constants.py``)
2. - [ ] Template context is ``payments_X`` (for example, ``payments_enabled``) (``context_processors.py``, ``jinja2/payments/*``)
3. - [ ] Context processor is ``global_payments_form`` (``context_processors.py``)
4. - [ ] Doc strings use ``payments`` (``utils.py``, ``tests/test_views.py``, etc.)
5. - [ ] Form-handling view is ``payments`` or similar (``views.py``)
6. - [ ] Background task is ``payment_thank_you_email`` (``tasks.py``)
7. - [ ] Tooltip for email input says "...receipt of your payment."  (``form.py``)
8. - [ ] IDs and CSS classes are ``payments-X`` or similar (``jinja2/payments/payments.html``, CSS rules, etc.)
9. - [ ] Template block is ``payment_popup`` (``jinja2/base.html``, ``kuma/landing/jinja2/landing/homepage.html``, ``kuma/wiki/jinja2/wiki/document.html)
10. - [ ] Flag names are ``payments_X`` (``payments_beta``, etc.) (**resets cohorts**, be careful)
11. - [ ] Instances of "contrib", "contribution" in the code and templates are ones we want to keep.

**Comment by jmswisher** [comment]
No longer relevant
