### ISSUE TITLE
Mdn doc  Javascript  with unchangeable chinese language please fix it 

### ISSUE THREAD

**Issue by richardme** [mdn/sprints#726]
# Request type
- [x] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/JavaScript

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
https://developer.mozilla.org/en-US/docs/Web/JavaScript
There was a scripting error on this page. While it is being addressed by site editors, you can view partial content below.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
I don't see the described problem on either the zh-CN or the zh-TW page (not sure which you saw it on). It was probably a temporary problem.
