### ISSUE TITLE
Page title in navigation different than actual page title

### ISSUE THREAD

**Issue by danpoynor** [mdn/sprints#727]
# Request type
- [x] New documentation
- [x ] Correction or update

## Page to change
The left column navigation area (#wiki-left) in the section "Related Topics" under the "JavaScript first steps" menu which includes a link to the page at: 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

# Details
The left navigation lists this page as "Basic in JavaScript — Numbers and operators" when it should probably match the actual page title "Basic math in JavaScript — numbers and operators".
<img width="1389" alt="screen shot 2018-12-30 at 10 03 40 am" src="https://user-images.githubusercontent.com/764270/50548992-371fec00-0c1b-11e9-93d3-17e37555df5f.png">

**Comment by jmswisher** [comment]
Looks like a simple string fix is needed in [LearnSidebar](https://github.com/mdn/kumascript/blob/master/macros/LearnSidebar.ejs).

**Comment by danpoynor** [comment]
PR submitted https://github.com/mdn/kumascript/pull/1030

**Comment by chrisdavidmills** [comment]
Fixed; thanks!
