### ISSUE TITLE
"Step" example missing content

### ISSUE THREAD

**Issue by davemoz** [mdn/sprints#728]
## Request type
- [x] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Learn/Drafts/Python/Loops#Step

## Details
This "Step" section seems to be missing the content following:
> "Instead of going up by 1 each time, we're going up by 2. This means that"

I would submit a correction if it were a grammatical or other similar error, but it's directly content-related, so just bringing it to the attention of moderators.

**Comment by jmswisher** [comment]
This is draft article, indicated by the URL, but not in content. The latest contributor was cautioned against continuing, which meant they left the content incomplete. I'm adding the "draft" macro to the Python tutorial pages, and will discuss with @chrisdavidmills when he's back from PTO.

**Comment by chrisdavidmills** [comment]
It makes no sense for us to publish a vanilla beginner's Python (or any other server-side language) tutorial series. It is not in MDN's remit, would compete with all the other Python stuff already out there, and wouldn't get a high priority.

The only context that might make some kind of sense would be maybe a very brief beginner's Python crash course to add on to https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django, or some kind of "Python for JS developers" type article. But again, we wouldn't give them a high priority at this point.

I am going to delete all these draft articles, to avoid future confusion.
