### ISSUE TITLE
Update pages for page-break and break to accurately reflect reality

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#734]
As a web developer I want to understand the status of the fragmentation properties `break-` and their relationship to `page-break-` now that Firefox has implemented the aliasing of these properties.

# Acceptance criteria

Docs pages and all data and examples up to date.

# Tasks

1. - [x] Docs checked and updated
2. - [x] Compat data checked and updated

Relates to https://bugzilla.mozilla.org/show_bug.cgi?id=775618

**Comment by rachelandrew** [comment]
Added a section re: aliases to pages for old `page-break-*` and new `break-*` properties. Fixed spec links.

**Comment by rachelandrew** [comment]
PR for Level 4 spec data https://github.com/mdn/kumascript/pull/1038

**Comment by rachelandrew** [comment]
We don't have interactive examples at all for these properties or the legacy ones. Support is so patchy I'm not sure if we want to do them or not at this point.

**Comment by rachelandrew** [comment]
PR for data: https://github.com/mdn/data/pull/345

**Comment by rachelandrew** [comment]
So, trying to even figure out support is fun: https://codepen.io/rachelandrew/pen/85b8cd3dc92e3fd099d12c49094b3480?editors=1100

It looks like most of the support is for printing, and not in multicol. So I think it would definitely be useful to split these out to avoid confusion.

**Comment by chrisdavidmills** [comment]
@rachelandrew ack, we give you all the best jobs, don't we ;-)

Yup, splitting them out sounds good to me.

**Comment by rachelandrew** [comment]
break-inside compat data: https://github.com/mdn/browser-compat-data/pull/3315

**Comment by rachelandrew** [comment]
break-before compat data https://github.com/mdn/browser-compat-data/pull/3327

**Comment by chrisdavidmills** [comment]
Totally makes sense.

**Comment by rachelandrew** [comment]
So I think with this one, I'll wait until the compat data is merged so I can add the separate bits to the page and if all looks ok at that point I'll check with the engineers that I have correctly figured out what is supported by the change.

**Comment by rachelandrew** [comment]
I've got the separate compat data now on the three pages, also just made a PR to do some updates based on testing: https://github.com/mdn/browser-compat-data/pull/3374

**Comment by chrisdavidmills** [comment]
Closing this. Bug is DDC'ed, pages are written and checked by the engineer, and PR for the data is merged.
