### ISSUE TITLE
P1: Web Performance

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#740]
Web/Guide/Performance needs content
https://bugzilla.mozilla.org/show_bug.cgi?id=1475056

Acceptance Criteria:

For sprint Erykah Bahdu:
- [X] Epic created
- [X] Tasks created within epic (22 so far)
- [X] two tasks within epic completed.

To close: 
- [X] hack-a-thon complete

**Comment by jmswisher** [comment]
@estelle Is this still waiting on review? It was "Continue in next sprint" for Erykah Badu, and not added to a sprint since then.

**Comment by estelle** [comment]
The next part is the hackathon, so no, it isn't. It's like a sprint epic.

**Comment by jmswisher** [comment]
OK, I'm moving it to the Parking Lot tab in the spreadsheet, and removing the milestone.
