### ISSUE TITLE
Storage Access API docs update

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#745]
See https://trello.com/c/L48xh7RS/11-storage-access-api-fx-65

# Acceptance criteria

1. - [x] Docs update made to satisfy requirements of bug referenced in above trello card.
2. - [x] review of said docs update requested from engineers.

**Comment by jmswisher** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1513021#c9 for changed pages.
