### ISSUE TITLE
Shared worker docs update

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#747]
See https://trello.com/c/BGRBpa8m/160-dedicated-shared-worker-apis-fx-65

# Acceptance criteria

1. - [x] Docs update made to satisfy requirements of bug referenced in above trello card.
2. - [x] Review of said docs update requested from engineers.

**Comment by jmswisher** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1508824#c5 for changed pages.
