### ISSUE TITLE
Properly document disabling of audio autoplay

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#753]
We need to be sure our documentation properly covers how to disable automatic autoplay of audio.

https://bugzilla.mozilla.org/show_bug.cgi?id=1474263

See this meta bug that covers all the engineering efforts involved in getting this right: https://bugzilla.mozilla.org/show_bug.cgi?id=1376321 (most of them have been fixed)

## Acceptance criteria
- [x] Identify all of the places that need to be updated; any methods that start playback, attributes that specify autoplay, and pages generally covering playback of audio; also any pages suggested by the many many bugs which are blockers for this meta bug
- [x] Add a section to the general media introduction content about this topic
- [x] Update the identified pages with appropriate notes and explanations
- [x] Request engineering review of the changes made

**Comment by chrisdavidmills** [comment]
Work related to disabling audio autoplay docs recorded in https://trello.com/c/4emMB6Y8/146-autoplay-api-fx-66
