### ISSUE TITLE
Update WebRTC docs for Firefox 65

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#755]
All that's left is the deprecation of a few older parts of the `RTCStats` stuff. See bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1512517.

Trello:
* https://trello.com/c/ejryeYyB/73-webrtc-10-fx-64

## Acceptance criteria
- [ ] BCD updates are made to the appropriate content and PRs submitted for review - the items covered here are being removed outright in Firefox 66
- [ ] `RTCPeerConnection` and `RTCPeerConnection.getStats()` pages have been updated to  cover the deprecation of the callback form in Firefox X if it's mentioned at all and removed in 66
- [ ] `RTCStats.isRemote` is noted as being deprecated in Firefox Y and removed in Firefox 66

**Comment by a2sheppy** [comment]
This shouldn't be done until these things are actually *removed* in Firefox 66. Right now, they're still there and working but outputting a warning to console. That's not something to document.

**Comment by jmswisher** [comment]
@a2sheppy So, is this done, or is it on hold until Fx66? Should this be closed, or should it go into the Icebox?

**Comment by chrisdavidmills** [comment]
Do we have a bug yet for the actual removal that we can track @a2sheppy ?

**Comment by a2sheppy** [comment]
There is in fact a bug for this, and it is fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1328194

**Comment by chrisdavidmills** [comment]
Great stuff, thanks!

So I've updated the TRello card to include this bug: https://trello.com/c/ejryeYyB/73-webrtc-10-fx-66

At this point I'd suggest closing this issue, and then opening up a new one when you finally do the docs for this bug, to keep tracking clean.
