### ISSUE TITLE
Write and share a Google doc to collect ideas about things we should be automating

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#759]
We all have things we do where we go "it's stupid that I'm doing this by hand; we should be automating this." Let's make a list, prioritize, and see if we can make some of it happen. For now, let's get a list. Everyone will be asked to add to it, and then next writer team meeting we will discuss it.

## Acceptance criteria
- [x] Google doc has been written and shared with the writing team
- [x] The team has been encouraged to write down their ideas for things we should automate, and to vote or comment on the items listed

**Comment by jmswisher** [comment]
Document is here: https://docs.google.com/document/d/1Qi9lwZBi0PZqjvua1MlDxe5OQ-Ki9JgMOz0jM2s4kDQ/edit#
