### ISSUE TITLE
Prototype a new edit profile page using a framework

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#763]
Once we pick a frontend framework, we're immediately going to have to figure out how to use it in practice, including figuring out the necessary toolchain and test infrastructure (see the other issues in this epic.)

In order to do that, we need a real-world web pages to use the framework on, so let's prototype a new version of the edit profile page, with an eye toward adding a "always display pages in english" option which should help us attract logged in users.

### User story

As a Kuma developer I need a small but real-world Kuma feature to convert using a modern frontend framework to help me:

- validate the choice of framework
- develop a toolchain
- have something to write tests against

Secondarily, as an English-speaking MDN user in a country that does not speak English, I would like the option to automatically view all MDN pages in English. Note however, that this issue is just for prototyping a page with this "always view in English" option. It does not include an actual implementation of the feature

### Acceptance criteria

- a prototype version of the "edit profile" page exists using the new framework
- the prototype is integrated with Kuma and is not a standalone server
- but it probably has not been deployed

**Comment by davidflanagan** [comment]
## Summary

I started down working on a react-based edit profile page, learned some things, and then stopped short of completion because there is existing tight integration between our Django python code and our jinja templates for HTML forms (like the one on the profile page), and it didn't seem like a good use of my time to figure out how to transfer the python data structures that describe the form to the client-side so that the form can be recreated in React.

Instead, I switched to a different experiment, redoing the main navigation header menus in React, and adding an index-based quick navigation feature to the header component.

## Prototypes

My work in progress on the edit profile page is in this branch: https://github.com/davidflanagan/kuma/tree/react-experiment

My work in progress for the page header is on this branch https://github.com/davidflanagan/kuma/tree/react-header

Here's a screencast demo of the React-based header: https://drive.google.com/file/d/1gsjED5_cjjCdknjrw1xpvKUSJuLfiyiu

## What I Learned

- Since MDN is a multi-page application, we want to be sure that each page uses the same cached version of the React libraries. We want to avoid the case where we're packing React into each page-specific bundle and serving an entirely new copy on each page load

- The Parcel bundler does not have an easy way to mark React as an "external" and keep it out of the bundle.  On the other hand, Parcel has a really easy to use hot-module reloading that is a joy to use.

- Webpack can do what we need with the react libraries, but I was not able to get HMR working with our django server. It can probably be done but will need more work.

- My approach in both the profile page and the header prototypes was to configure parcel or webpack to put its bundles in the /static directory (*not* in kuma/static). Then, in development mode, I'd use gulp to copy files from kuma/static to /static, and use parcel or webpack (in watch mode) to build bundles and copy them to /static.  Once everything was in /static, the regular django-pipeline flow bundler took over, using the configuration in wiki/config/common.py, and using the javascript macro in our jinja templates.

- For the edit profile page prototype, I added script tags directly to the jinja template for the page to load the react libraries from a cdn.  For the header prototype, I used Parcel and just had react bundled up into one big bundle. But if I switched to webpack, Id' be able to have React in a separate bundle that might give better caching behavior.

## Work remaining

- I've been working in development mode, and haven't yet tried a build. I think this will mostly uust be running parcel or webpack with --build instead of --watch, but I may also need to install other packages or something.

- when converting from a jinja template to a React component I've changed the _() calls to gettext() calls. I'm not getting internationalized strings in my prototypes, however. Though this might just mean that I need to run the appropriate localization tools.

- I have not yet run flow or eslint over the prototype code to see if there are issues there

- I have not yet written tests for the prototype code to see what is involved in (for example) setting up snapshot tests for react components.

**Comment by jwhitlock** [comment]
Thanks @davidflanagan, I believe the report can be the deliverable for this task.
