### ISSUE TITLE
Adopt a modern build/packaging toolchain

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#764]
Once we pick the frontend framework we're going to use, we'll need to put together a toolchain that works for us.  Schalk and I are already moving in the direction of using jest and prettier, but if we adopt React, we'll need to add Babel to the mix. And we'll probably want a packager like webpack or parcel.

We could stay small and use this new toolchain just for pages of the website that use the new frontend framework. Or we could go big and try to convert all of Kuma to use it. John probably already has issues filed about moving us off of Django pipeline, so there may be some overlap there.

### User story

As a Kuma developer I need a modern toolchain to accompany my frontend framework to handle transpilation and asset packaging.

### Acceptance critera

- [x] tools selected
- [ ] selection decisions are documented and communicated
- [x] prototype code using the toolchain exists (probably not deployed, though)

**Comment by davidflanagan** [comment]
I tried Parcel today, and loved the developer experience of it. But it seems strongly oriented toward single-page apps that only need a single bundle. Since we have multiple pages, each page is going to need its own bundle. But it makes no sense to duplicate the react and react-dom libraries in each of these per-page bundles. Those should be separate so they are cacheable. We can have a separate bundle for those or we can load them from a CDN.

Parcel does not really support this use-case because it doesn't have a way to define "externals" or "split chunks" like webpack does. (Parcel supports multiple chunks if we use dynamic import(), but that doesn't work in this case because we need both the react libraries and the per-page bundle immediately when the page loads, I don't want to require one and then have it dynamically require the other. Parcel 2 might have a split chunks feature, but it isn't out yet.)

There has been a Parcel feature request open for over a year to add the ability to define external modules, but it hasn't happened yet: https://github.com/parcel-bundler/parcel/issues/144

This pretty much convinces me that until and unless we switch to SPA, we can't use Parcel, and will need to use webpack instead.

Does this make sense to you @schalkneethling or am I missing something?

**Comment by davidflanagan** [comment]
https://webpack.js.org/guides/caching/ is mostly about adding hashes to bundle names, but also includes a useful example of creating a separate bundle for things like react libraries.

**Comment by schalkneethling** [comment]
Agreed. Webpack does seem like the tool we are going to need.

**Comment by jwhitlock** [comment]
Looks like there is a consensus on Webpack, and implementation will be next sprint. Please update the estimate and confidence as needed.

**Comment by schalkneethling** [comment]
> It appears to me that a runner like `gulp` , `npm` scripts, or a `Makefile` is still needed with Webpack. Is a runner still needed? If so, is there a consensus on the runner?

We won't need anything more than npm scripts. You can see an example of these here:
https://github.com/schalkneethling/mdn-feature-banner-component/blob/master/package.json#L7

**Comment by schalkneethling** [comment]
I do not believe there is a lot for me to do on this, this coming sprint. I am therefore time boxing it to 1 point. Let me know if I am missing something.

**Comment by jwhitlock** [comment]
This one seems like it could have been completed this sprint, but it's unclear if the acceptance criteria are met:

* Tools selected - What tool selections remain?
* Selection decisions are documented and communicated - Is this issue enough, or is there another channel to update?
* Prototype code using the toolchain exists: We're shipping webpack, Babel, and Jest, but there may be additional tool selections.

**Comment by schalkneethling** [comment]
> Tools selected

I reckon this is essentially Webpack?

> Selection decisions are documented and communicated - Is this issue enough, or is there another channel to update?

We did not discuss this but perhaps we need to open an ADR based on this issue and have that go through the process?

> Prototype code using the toolchain exists: We're shipping webpack, Babel, and Jest, but there may be additional tool selections.

I reckon this is what we will be using for the foreseeable future.

**Comment by jwhitlock** [comment]
We discussed this on other issues and in meetings. My summary is that the tool selection is an implementation detail of the other decisions (React, Flow, Emotion), and don't necessarily rise to the level of an ADR. I think this issue can be enough for now.
