### ISSUE TITLE
Decide how to do frontend tests

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#765]
As we transition to using a frontend framework, we should get serious about a frontend testing infrastructure. This should presumably include some kind of unit test for components plus integration tests with selenium

### User story

As a Kuma developer, I want a way to write modern unit and integration tests for frontend code.

### Acceptance criteria

- [ ] testing tools are decided upon
- [ ] a working example of unit and integration tests exists (but has probably not been deployed)
- [ ] testing framework decision is documented and communicated.

**Comment by jwhitlock** [comment]
Moving to next sprint, please update estimate and confidence as needed.

**Comment by schalkneethling** [comment]
We have decided on Jest for JS and True for SaSS. In the next sprint, the bulk of this work will be to ensure we have tests to go along with the React modules we build.

The initial set-up is already in Kuma so, we could probably simply leverage it. Timeboxing to 1 point.

**Comment by jwhitlock** [comment]
With https://github.com/mozilla/kuma/pull/5270 merged, I think we've closed this issue:

* Testing tools: Jest and True
* Working example of Jest merged
* Decision documented here and in code

As we get more examples and confidence in the process, we can formalize in https://kuma.readthedocs.io/en/latest/tests-ui.html.

**Comment by schalkneethling** [comment]
@jwhitlock All good, I just moved it there while the PR was still open. I agree that we can safely close this one. Thanks John.
