### ISSUE TITLE
Write a plan for how we can integrate embedded CodePens into WebAPI ref pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#767]
We want to use embedded CodePens to provide interactive examples for Web APIs.

This user story is to write a plan for what needs to happen for us to do this. It will cover:

* what the initial proposal for a UX will be
* changes needed in Kuma/KumaScript to be able to support that UX
* how we will make interactive example sources available to Kuma/KumaScript
* the main milestones

## Acceptance criteria

Plan for integrating CodePens is written and review by product management, content and engineering representatives. The plan needs to describe at a high level what's needed, and identify the main milestones and the order in which things can get done.

**Comment by wbamberg** [comment]
Plan is drafted: https://gist.github.com/wbamberg/ca85831ec166a0bfed4bbcc031d3bf73 and sent to Schalk, Kadir, Chris.

**Comment by chrisdavidmills** [comment]
This was written, and I believe we gave you feedback, @wbamberg, so this can be closed right?

**Comment by wbamberg** [comment]
I never got any feedback from anyone on this, so I guess it was perfect.

**Comment by chrisdavidmills** [comment]
Apologies Will; I was sure I'd seen this before. I've definitely seen the live example prototype. I justy had a read through, and it loks very well thought out.
