### ISSUE TITLE
Decide whether and how to do CSS-in-JS

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#769]
Modern frontend development very often defines CSS styles for components directly in the JS code that defines the component. This has always made me vaguely uneasy because I worry about performance, but good libraries do this well by dynamically defining style sheets. And, it allows for convenient scoping of styles, and I have found it to be a real productivity boost. We should consider using this technique with Kuma.

### User story

As a Kuma developer I'd like to use a modern library that gives me the flexibility and development ease of defining CSS styles directly in my JS code. But I also don't want to worry that doing this will make my code inefficient.

### Acceptance criteria
- We've decided whether to use css-in-js
- If so, we've decided which solution to use
- We've documented and communicated both decisions
- If we will be using css-in-js, there is prototype code (probably not deployed) that demonstrates how it is done.

**Comment by jmswisher** [comment]
Jen Simmons may have some opinions. I know she's an advocate of using whatever Dev Outreach considers best practices on our signature websites.

**Comment by davidflanagan** [comment]
I've proposed an ADR for using Emotion: https://github.com/mdn/mdn/pull/54

**Comment by davidflanagan** [comment]
The ADR for this just landed, which satisfies the first two acceptance criteria.

There is prototype code showing how Emotion works in Kuma on my react-header branch. For example: https://github.com/davidflanagan/kuma/blob/react-header/javascript/header/dropdown.jsx

That satisfies the 4th acceptance criteria. All that remains is to communicate the decision, which is the third acceptance criterion above, and also the I part of the DACI model. So I'll send an email about that and then close this issue.
