### ISSUE TITLE
Check and update multicol pages and guides to reflect new implementation in Firefox

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#776]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns (and subpages/property pages)

# Details

Firefox has implemented the column-span property and also the fragmentation break properties which apply to multicol. Need to make sure that all pages, property pages and compat data reflect these updates.

## Related issues

* https://bugzilla.mozilla.org/show_bug.cgi?id=775618
* https://bugzilla.mozilla.org/show_bug.cgi?id=1421105

Trello: https://trello.com/c/X0vhUJhk/2-css-multi-col-fx-65

**Comment by rachelandrew** [comment]
It looks as if some internals for multicol which relate to column-span are shipping in 65 but we don't actually have column-span other than behind a flag. I have checked that the compat data and current state of the information is correct.

I'll add a note to Trello as at some point this will come back as shipped, but until we see the info about it being shipped we probably don't need to do anything.

The breaking stuff I am dealing with in another ticket.

**Comment by chrisdavidmills** [comment]
Closing — you've either dealt with this stuff either in other places, or it is not documentation-relevant.
