### ISSUE TITLE
Document Overflow Media Queries

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#777]
# Request type
- [] New documentation
- [X] Correction or update

# Details

Document the overflow media queries which will be in Firefox 66.

## Related issues

* https://bugzilla.mozilla.org/show_bug.cgi?id=1422235
* https://trello.com/c/OiB8Q5Vi/4-media-queries-level-4-fx-66

**Comment by rachelandrew** [comment]
PR for data: https://github.com/mdn/browser-compat-data/pull/3341

I don't think there is anything else to do here as I documented media queries previously and the information is still correct.

**Comment by chrisdavidmills** [comment]
this looks fine; I've checked it out and the data and pages are up-to-date.
