### ISSUE TITLE
Create CSS Values and Units reference

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#778]
# User story

As a web developer I want to understand the various CSS values and Units and be able to easily find all of the information about them on MDN.

# Acceptance criteria

New CSS Values and Units document completed.

Trello: https://trello.com/c/TTxbHx5o/171-css-values-and-units-reference

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

@chrisdavidmills this has highlighted some missing bits and pieces, also pages which could do with an update. Shall I just raise issues for those at this point, or go round and tidy those up as part of this issue?

**Comment by chrisdavidmills** [comment]
Wow, this is already looking fantastic @rachelandrew ! 

In terms of the missing bits of pieces, I think it depends on how big they are. If they are only little fixes, then you might as well just tidy them up as you go along. If they are large bits of work, file new idssues for them and we'll put them in a future sprint.

**Comment by rachelandrew** [comment]
For values like calc() we do a redirect so if someone uses the macro calc() gets redirected to calc.

How do I set this up for things like min() and max()?

**Comment by chrisdavidmills** [comment]
For calc, it looks like someone originally placed the page at https://developer.mozilla.org/en-US/docs/Web/CSS/calc(), but then redireced it to https://developer.mozilla.org/en-US/docs/Web/CSS/calc. You'll see a redirect in place if you go to https://developer.mozilla.org/en-US/docs/Web/CSS/calc()$edit

The easier way to fix this is to include an additional parameter in the cssxref macro call that sets what the display text should be, if different to the URL slug. So for example {{cssxref("min", "min()")}} uses min as the slug, but min() as the link text.

I've fixed all the instances at

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units#Functional_Notation

**Comment by chrisdavidmills** [comment]
For the support data, I think it'd be more workable to just create separate data for combinated types, although I can't see any in the browser-compat-data repo at present that do this.

Can we find an example of a combined type already on MDN that we could follow, or are we making up the rules here?

**Comment by rachelandrew** [comment]
@chrisdavidmills I think it would just essentially be if the browser supports the dimension plus percentage, which is what I started to do and then second guessed myself as to whether that was the right approach. 

However considering potential future usage of the data would be most straightforward. As you could then just look up length-percentage etc. as a thing.

**Comment by chrisdavidmills** [comment]
Yeah, let's do that then.

**Comment by rachelandrew** [comment]
PR for those combined types: https://github.com/mdn/browser-compat-data/pull/3353

**Comment by rachelandrew** [comment]
PR to add them to the data for the menus: https://github.com/mdn/data/pull/352

**Comment by rachelandrew** [comment]
missed your comment on my PR, I've just made that change.

**Comment by chrisdavidmills** [comment]
Cool, let's close this then.
