### ISSUE TITLE
Document Changes Panel

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#785]
# Request type
- [x] New documentation
- [ ] Correction or update

## Page to change
[Examine and Edit CSS](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS)

# Details
- [ ] Adding a section to the page on editing CSS to describe the new changes panel including what is tracked and how.

## Related issues
[1503920](https://bugzilla.mozilla.org/show_bug.cgi?id=1503920) - Initial implementation of Track Changes, a Changes panel in the inspector.

# Success Criteria
- [x] New section has been added to the editing CSS page
- [x] A mention of the changes panel has been added to the 65 release notes

**Comment by irenesmith** [comment]
New section on changes panel added at: [Track changes](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Track_changes)

**Comment by chrisdavidmills** [comment]
This one looks done.
