### ISSUE TITLE
Document the ability to print the Accessibility sub-tree to json

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#788]
# Request type
- [x] New documentation
- [ ] Correction or update

## Page to change
[Accessibility inspector](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#Notable_related_features)

# Details
Need to add the ability to print the Accessibility sub-tree to json

# Success Criteria
- [x] Section has been added to the Accessibility inspector page
- [x] Screenshots of the feature are have been made and inserted on the page
- [x] Mention of this feature added to release notes if appropriate

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by irenesmith** [comment]
There doesn't seem to be a bug for this one.

**Comment by chrisdavidmills** [comment]
This is nicely done.
