### ISSUE TITLE
Roadmap for platform

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#789]

**Comment by atopal** [comment]
Acceptance Criteria: 
* Roadmap for 2019 that includes platform changes and how they relate to OKRs
* Draft Roadmap shared with platform stakeholders 
* At least one round of feedback with stakeholders
* Roadmap published internally to all of developer outreach

**Comment by atopal** [comment]
Roadmap: https://app.productplan.com/p/7KQvPUmD5ZmV_EiHkN9GzW0o9y_Jkkhl

**Comment by peterbe** [comment]
How I hate that there's yet another app/interface to do management. But how I love that chart! I wish sprint stuff was a timeline based chart too.

**Comment by atopal** [comment]
I don't think we'll ever find the one true product that will do everything we need from start to finish, JIRA is trying that, but I have yet to find someone who likes that ;) That said, I sure would like to have a better integration between them :/ At least this is mostly just my problem.
