### ISSUE TITLE
Document Remote Debugging

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#797]
# User story
As a developer, I want to be able to setup and use remote debugging

# Acceptance criteria
- [ ] Remote debugging documented with appropriate examples

# Tasks
TBD

**Comment by irenesmith** [comment]
Moving this out of the Erykah Badu since this task has been moved out to Firefox 68 and is not ready for documentation.

**Comment by chrisdavidmills** [comment]
Sounds good. I've noted the new release number in the trello card

**Comment by irenesmith** [comment]
I am closing this issue because I've created an epic to track the work.
