### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Web/API/Console/error

### ISSUE THREAD

**Issue by MikeWar1ock** [mdn/sprints#803]
![error](https://user-images.githubusercontent.com/26402019/51037452-532f7000-15c1-11e9-8907-bbb6d29c5c9c.png)
# Request type
 Correction

## Page to change
https://developer.mozilla.org/ru/docs/Web/API/Console/error

# Details
*Specifications link doesn't work.*

**Comment by chrisdavidmills** [comment]
You are talking about the link to https://console.spec.whatwg.org/#error, right? This seems to work fine for me.
