### ISSUE TITLE
bug 1432535 - View API key activity without a 500 ISE

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#806]
# User story
As a maintainer, I want to view API activity with out a 500 internal server error, so that I can monitor how the PUT API is used.

# Acceptance criteria
* In the Django Admin in production, the 572 actions for key `xSqy..` can be viewed without an internal server error.

# References
* [bug 1432535](https://bugzilla.mozilla.org/show_bug.cgi?id=1432535)

**Comment by tobinmori** [comment]
low priority. belongs down the backlog.
