### ISSUE TITLE
bug 1518844 - Update bug entry links for content bugs

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#808]
# User story
As a MDN reader, I want to submit a content bug, so a staff member can fix it

# Acceptance criteria
* Links to the content bug form go to GitHub rather than the Bugzilla form.doc

# References
* [bug 1518844](https://bugzilla.mozilla.org/show_bug.cgi?id=1518844)

**Comment by jwhitlock** [comment]
There appear to be a few more instances: https://github.com/mozilla/kuma/search?q=https%3A%2F%2Fbugzilla.mozilla.org%2Fform.doc&unscoped_q=https%3A%2F%2Fbugzilla.mozilla.org%2Fform.doc

**Comment by escattone** [comment]
Oh, good catch! That's my fault for not catching those in my review, sorry!

**Comment by jwhitlock** [comment]
Shipped to production January 18th
