### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by nycpaulll** [mdn/sprints#811]
https://s3.us-east-2.amazonaws.com/atwmggsg/ts/ffaws.html?cid=15473343691159131421246858340755472

**Comment by nycpaulll** [comment]
This web page told me I needed to download a Firefox update.  Obviously a virus.

**Comment by a2sheppy** [comment]
This doesn't seem to be a documentation issue; who do we forward this to?

**Comment by wbamberg** [comment]
Thanks! I tried sending this report to https://www.mozilla.org/en-US/about/legal/fraud-report/.
