### ISSUE TITLE
Document for Intersection Observer API doesn't mention clipping from ancestor

### ISSUE THREAD

**Issue by upsuper** [mdn/sprints#813]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
* https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

# Acceptance criteria
- [x] Explanation of the intersection algorithm updated to correctly and more completely cover clipping effects
- [x] Submitted for technical review

# Details
In the spec, there is a step in [compute the intersection](https://w3c.github.io/IntersectionObserver/#compute-the-intersection) algorithm that clips the rectangle of the observed element with its ancestors' area when they have overflow clipping.

It seems to me that this is actually a very important piece which worth mentioning and probably even emphasizing in the doc, because it actually changes how this API can be used.

The idea from the spec is that, developers should set intersection root to the closest scrollable ancestor of the observed element, and all good.

That is fine, if it is not well explained, developers can get confused by the behavior of the API, because they may try to use a further ancestor or even the implicit root as the intersection root, and would find that `rootMargin` doesn't work as expected, or even worse, in a confusing way.

This is because of the clipping step, since if you use an ancestor beyond the closest scrollable ancestor, then we can almost only calculate the intersection with that closest ancestor, instead of the intersection root, and `rootMargin` would have little meaning.

My colleague was confused yesterday, and the question was brought to me, and then I was confused as well. I thought the confusing way `rootMargin` behaves is probably an implementation bug, until I found that Gecko, Blink, and the polyfill are all doing the same, so I started to read the spec again and found this.

It's not clear what's the best way to document this, though, thus this issue.

**Comment by a2sheppy** [comment]
I've revised the Intersection Observer API page to include content about this. See https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Clipping_and_the_intersection_rectangle for that information. I've also made some revisions elsewhere in this article to fix a few little things and flesh out things that needed reference from this.

Additional changes were made to the following pages to cover things this needed to have covered:

* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/Formatting_Contexts_Explained
* https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context
* https://developer.mozilla.org/en-US/docs/Web/CSS/overflow (added missing `clip` keyword, among other improvements

**Comment by upsuper** [comment]
That's great, thanks!

> A block's clipping is determined by based on the intersection of the two blocks and the clipping mode (if any) specified by the `overflow` property being set to either `hidden` or `clip` or the `clip-path` property.

I suppose any value on `overflow` other than `visible` would trigger the clipping.

Also near the very beginning of the article, there is a sentence says:
> Typically, you'll want to watch for intersection changes with regard to the document's viewport (which is done by specifying `null` as the root element).

which should probably be updated as well. I would suggest something like
> Typically, you'll want to watch for intersection changes with regard to the closest scrollable ancestor, or viewport if there is no scrollable ancestor.

**Comment by a2sheppy** [comment]
@upsuper - I've updated things based on your feedback; thank you!
