### ISSUE TITLE
Simplify Bugzilla macro

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#815]
# User story
As the PM I want the Bugzilla macro to be simplified to only display a link, so we don't show errors on rendering

# Acceptance criteria
* The {{bug}} macro is simplified to only create links to a Bugzilla issue
* Current calls of the bug macro are not broken
* Updated status posted to https://github.com/mdn/kumascript/issues/751

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by a2sheppy** [comment]
What are you talking about removing here? The tooltip with the bug title are very useful, for example.
