### ISSUE TITLE
Remove `char` property from `keydown` event properties

### ISSUE THREAD

**Issue by dima74** [mdn/sprints#816]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/Events/keydown#Properties

# Details
Please remove `char` property from table of properties for `keydown` event (link above), because there is no such property in [specification](https://www.w3.org/TR/uievents/#event-type-keydown). Also description of `key` should be updated then, because it refers to `char` property:

> ![image](https://user-images.githubusercontent.com/6505554/51117903-18774300-1820-11e9-9095-9765d4d3072b.png)

Thank you.

**Comment by a2sheppy** [comment]
We need to double-check to see if this is a non-standard property that actually does exist (or has at some point) so that we can mark it appropriately using {{non-standard_inline}}.

**Comment by jmswisher** [comment]
Fixed by https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event$compare?to=1457560&from=1456047
