### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Math/random

### ISSUE THREAD

**Issue by pfdgithub** [mdn/sprints#823]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random  
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Math/random  

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

> This example returns a random number between the specified values. The returned value is no lower than (and may possibly equal) min, and is less than (and not equal) max.

should be translated to  

> 这个例子返回了一个在指定值之间的随机数。这个值不小于min（但可能等于），并且小于（但不等于）max。

---

> This example returns a random integer between the specified values. The value is no lower than min (or the next integer greater than min if min isn't an integer), and is less than (but not equal to) max.

should be translated to  

> 这个例子返回了一个在指定值之间的随机整数。这个值不小于min（如果min不是整数，那就不小于下一个大于min的整数），并且小于（但不等于）max。

---

> While the getRandomInt() function above is inclusive at the minimum, it's exclusive at the maximum. What if you need the results to be inclusive at both the minimum and the maximum? The getRandomIntInclusive() function below accomplishes that.

should be translated to  

> 上面的 getRandomInt() 函数包含最小值，排除最大值。如果你需要结果中包含最小值和最大值，怎么办呢?  下面的 getRandomIntInclusive() 函数能够实现。

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by Mookiepiece** [comment]
hi @pfdgithub . This page has been fixed by @soyaine.
