### ISSUE TITLE
In Tracking Protection article, make screenshot and description consistent

### ISSUE THREAD

**Issue by jezraj** [mdn/sprints#825]
# Request type
- [ ] New documentation
- [ x] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
Either add an image showing where Firefox displays controls that will let the user disable content blocking, or remove "The Firefox UI will indicate to users when content has been blocked and enable them to unblock it for the current session if they choose. Users will also be able to disable tracking protection entirely if they choose." 

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by irenesmith** [comment]
Updated [Tracking Protection](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection) to show how the UI notifies the user of potential trackers and how the settings can be changed.

**Comment by chrisdavidmills** [comment]
I've reviewed this; looking good!

I just made a couple of minor changes.
