### ISSUE TITLE
Grid layout developer doc page error

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#827]
# Request type
Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

# Details
In the section [One-dimensional vs. two-dimensional layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout#One-dimensional_vs._two-dimensional_layout), the example is followed by the text “In the image, you can see that two items have wrapped onto a new line. These items are sharing the available space and not lining up underneath the items above.”

The code demo above that (a) is not an image, and (b) has only one item on the bottom row.  I have included a screenshot to illustrate this.

![screen shot 2019-01-09 at 11 06 59](https://user-images.githubusercontent.com/286017/51417674-b2066380-1b44-11e9-9c38-b0f8c0cf7be4.png)

## Related issues
This was filed as [bug 1518758](https://bugzilla.mozilla.org/show_bug.cgi?id=1518758) on January 9th. User agent: ``Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15``

The bug reporter also had issues logging into a legacy account.

**Comment by chrisdavidmills** [comment]
I've fixed this by setting a fixed width on the wrapper so that the two item wrapping will always be observed regardless of viewport width.

**Comment by chrisdavidmills** [comment]
Ack, sorry for stealing that from you @rachelandrew ...I didn't see you had assigned it until after i'd fixed it.
