### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

### ISSUE THREAD

**Issue by marxwood** [mdn/sprints#828]
# Request type
- [ ] New documentation
- [ x] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

# Details
Why microdata related attributes are all marked as an experimental API?

**Comment by chrisdavidmills** [comment]
I don't know. they probably shouldn't be, as they are supported in multiple browsers and the feature is stable. I've deleted the experimental markers.
