### ISSUE TITLE
docs(Window#sessionStorage): description unclear

### ISSUE THREAD

**Issue by thefliik** [mdn/sprints#833]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

The first paragraph on `sessionStorage` includes

> Opening a page in a new tab or window will cause a new session to be initiated with the value of the top-level browsing context, which differs from how session cookies work.

Having read the article, I do know what the "top-level browsing context" is or how `sessionStorage` differs from how session cookies work.

I don't have any particular suggestions for improvement, this is just an FYI that, for one person at least, this article is not particularly informative.

I was reading the article with the hope of finding out when, exactly, info in sessionStorage is cleared.

- For example, if someone opens webpages in tabs, opens a new tab and authenticates with a webpage (and that authentication info is stored in sessionStorage), is the session cleared when the tab is closed or when the window is closed?
- If someone has multiple tabs open to domain X as well as other domains, is the session for domain X cleared when all tabs for domain X are closed? Or when the window is closed.
- Etc.

I'm not expecting these questions to be answered in this issue. It's just an example of one way in which the `sessionStorage` article was not helpful for a specific use case.

**Comment by irenesmith** [comment]
I've updated the content of the page to define when and how sessionStorage is created and cleared. Let me know if this helps.

**Comment by thefliik** [comment]
Thanks! It's definitely better.

My experimental evidence seems to show that, at least for google chrome, session storage isn't cleared until *all* the tabs / windows associated with a domain are closed.

This quote seems to imply that the session storage would be cleared after the *first* tab / window was closed:

> Closing a tab or Window ends the session and the objects in sessionStorage are cleared as soon as the tab or Window is closed.

Is this behavior browser specific? Should it read "Closing all tabs or windows associated with a domain ends the session..."

(At this point my specific need for an answer to this question is long in the past. This is largely a rhetorical question for the purpose of improving the docs. That being said, I don't actually know the answer.)

**Comment by irenesmith** [comment]
I believe I tested that (in Chrome and Firefox) before I said it, but I will double-check and update the page if necessary.
