### ISSUE TITLE
The page for the `where()` L4 selector is incomplete

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#834]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/CSS/:where

# Details

This page needs completing, compat data adding.

Spec link: https://drafts.csswg.org/selectors-4/#zero-matches

**Comment by Elchi3** [comment]
Chris did this in https://github.com/mdn/sprints/issues/3190
