### ISSUE TITLE
Document namespaces for type and universal selectors

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#835]
# Request type
- [ ] New documentation
- [*] Correction or update

## Page to change

- https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors
- https://developer.mozilla.org/en-US/docs/Web/CSS/Universal_selectors

# Details

I don't think we detail namespaces anywhere. See: https://drafts.csswg.org/selectors-4/#type-nmsp

**Comment by chrisdavidmills** [comment]
This one got fixed by the referenced PR
