### ISSUE TITLE
Document Video/Audio Play State pseudo-classes

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#840]
# Request type
- [*] New documentation
- [ ] Correction or update

# Details

The Level 4 selectors spec includes pseudo-classes for play state, `:playing` and `:paused`. Add documentation for these: 

https://drafts.csswg.org/selectors-4/#video-state

**Comment by rachelandrew** [comment]
@chrisdavidmills this was completed in https://github.com/mdn/sprints/issues/1687

**Comment by chrisdavidmills** [comment]
Great, closing then
