### ISSUE TITLE
Page for the `:blank` selector is incomplete

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#841]
# Request type
- [ ] New documentation
- [*] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/CSS/:blank

# Details

THis relates to the `:blank` selector in the Level 4 selectors spec: https://drafts.csswg.org/selectors-4/#blank

**Comment by chrisdavidmills** [comment]
I don't see that there's much to do here at the moment; :blank still doesn't seem to be implemented anywhere. Closing for now.
