### ISSUE TITLE
Update page for `:valid` to also include examples

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#842]
# Request type
- [ ] New documentation
- [*] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/CSS/:valid

# Details

This page currently points to the page for `invalid` for details. For consistency and to save people hopping around we should also have examples here.

**Comment by chrisdavidmills** [comment]
Nice example added: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:valid#Examples
