### ISSUE TITLE
Invalid Link - Overview of media technology on the web

### ISSUE THREAD

**Issue by shylinfon** [mdn/sprints#853]
# Request type
- [ ] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/Media

# Details
The link to section "Overview of media technology on the web" is invalid.

**Comment by jmswisher** [comment]
That article hasn't been written, which is why the link is red.

**Comment by irenesmith** [comment]
@a2sheppy Is this already on your plate?

**Comment by a2sheppy** [comment]
This is an article I intend to write. I have not yet scheduled doing so, however.
