### ISSUE TITLE
https://developer.mozilla.org/en-US/users/account/email/confirm

### ISSUE THREAD

**Issue by steven67** [mdn/sprints#854]
# Request type
- [ ] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by steven67** [comment]
Look u sent a link to stipton67@live.com. that is a hacked account even though it was mine for 20 yrs

**Comment by steven67** [comment]
She Laura Jo Hartley has changed that recovery email: cant u ban her

**Comment by steven67** [comment]
Just like google should ban her she has a iphone and uses android apps to steal my data
i need paperwork sent to 1131 n buffalo st 
erwin tn 37650 4232206457

**Comment by jmswisher** [comment]
@steven67: It's unclear what kind of problem you're having, or why you're reporting it as an MDN content problem. MDN uses GitHub's authentication, so the email address associated with your MDN profile is the same as the one for your GitHub profile.
