### ISSUE TITLE
 HTMLMediaElement.pause() page incorrectly shows it as experimental technology

### ISSUE THREAD

**Issue by willowcheng** [mdn/sprints#855]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause

# Details
![screen_shot_2019-01-25_at_2_56_05_pm](https://user-images.githubusercontent.com/6239076/51769562-6e19de00-20b1-11e9-8a86-ae4a3bf509bb.png)
The page incorrectly marks `pause()` method as experimental technology. The left sub navigation shows correctly (which doesn't come with lab icon).

**Comment by chrisdavidmills** [comment]
Yes, I agree with you that this isn't really experimental. I'ev removed that banner.
