### ISSUE TITLE
Web APIs > Index of APIs > File API : Hyperlink is broken (404)

### ISSUE THREAD

**Issue by data-scoop** [mdn/sprints#856]
# Request type
- [x ] New documentation
- [x ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

https://developer.mozilla.org/en-US/docs/Web/API

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

The page lists an index of Web APIs, and specifically shows File API as a hyperlink. Clicking this link returns a 404 Error.

The page should either be created, or the hyperlink removed.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by duduindo** [comment]
@data-scoop I think that shouldn't remove link **File API**, because it's  a Web API: https://w3c.github.io/FileAPI/

**Comment by jmswisher** [comment]
Need to determine whether we need a File API landing page, or if GroupData.json needs an update to point to a different page.

**Comment by chrisdavidmills** [comment]
This is no longer an issue
