### ISSUE TITLE
I found invalid link

### ISSUE THREAD

**Issue by vezzita** [mdn/sprints#857]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
https://developer.mozilla.org/ko/docs/Web/Guide/AJAX

# Details
A number of links on this page are invalid because they have an extra locale code in the URL, e.g., https://developer.mozilla.org/ko/docs/Web/Guide/ko/AJAX/Getting_Started

The links need to be fixed so that they are valid MDN links, that is, they have a locale code only immediately after the domain name.

**Comment by duduindo** [comment]
@vezzita Links fixed. Thank you!

**Comment by jmswisher** [comment]
Thanks @duduindo !
