### ISSUE TITLE
Document the ability to view the CSP policy of a website

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#859]
As a user of the DevTools, I want a convenient way to view the CSP policy of a website.

See Bugzilla: #[1449501](https://bugzilla.mozilla.org/show_bug.cgi?id=1449501) for details about CSP policy.

- [ ] Documentation for Content Security Policy added to the Network Monitor pages
- [ ] Screenshots have been created and added to the documentation
- [ ] Information about CSP added to the Firefox 64 Release Notes

**Comment by irenesmith** [comment]
Just checked with the dev tools team, and this feature still has not been implemented.

**Comment by irenesmith** [comment]
I checked today and Harald confirmed that this hasn't happened yet and they don't have any timeline for it actually being done.

**Comment by jmswisher** [comment]
The Bugzilla bug this refers to is still not implemented. I'm closing this, and we can create a new issue when it lands and has a target release.
