### ISSUE TITLE
Incorrect "for...in" description on the "for...of" page

### ISSUE THREAD

**Issue by DevelAx** [mdn/sprints#863]
# Request type
- [ ] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Difference_between_for...of_and_for...in

# Details
It's said first that:

> _(1)_ The `for...in` statement iterates over the enumerable properties of an object, **in an arbitrary order**.

Further in the in *step by step* description of the example it's said the opposite:

> _(2)_ This loop [implies `for (let i in iterable)`] logs only enumerable properties of the iterable object, **in original insertion order**.

And on the ["for...in"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Deleted_added_or_modified_properties) page it's said:

> _(3)_ A `for...in` loop iterates over the properties of an object **in an arbitrary order** (see the `delete` operator for more on why one cannot depend on the seeming orderliness of iteration, at least in a cross-browser setting).

Which corresponds to the first _(1)_ statement and is supported by the `delete` operator description.

Thus, it looks like the **second** _(2)_ **statement is incorrect with respect to the iteration order**.

**Comment by Elchi3** [comment]
Hey, thanks for your report! I've corrected this to arbitrary order.
