### ISSUE TITLE
TransformStream documentation

### ISSUE THREAD

**Issue by athanclark** [mdn/sprints#864]
# Request type
- [x] New documentation
- [ ] Correction or update

# Details
The Web Streams API seems to be some pretty schnazzy technology - it's reminiscent of pipes or conduit in haskell, for decoupling blocking chunk processing code from a potentially infinite stream of chunks, all while consolidating it from natural control flow. This is also a necessity for the Fetch API.  

Right now, documentation exists for `ReadableStream` and `WritableStream`, but not for `TransformStream`. There's a mention of "the writing side" in the WritableStream documentation, but nothing further.

Is this fleshed out in the ECMA standard? Or is it not implemented yet?

**Comment by irenesmith** [comment]
@chrisdavidmills Is this on the content roadmap?

**Comment by chrisdavidmills** [comment]
We've got it covered under https://trello.com/c/MJpfsY0x/28-readablestreams-api; I wonder if it should be included under it's own card.
