### ISSUE TITLE
«Roll your own browser documentation» is obsolete

### ISSUE THREAD

**Issue by SiegfriedEhret** [mdn/sprints#868]
# Request type
- [ ] New documentation
- [X] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Embedding_Mozilla/Roll_your_own_browser

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

There are lost of things that are obsolete in this page: links, examples...
Multiples links go to http://lxr.mozilla.org/ which is down.

I'd like to learn how to roll my own browser !

Actually there are dozens of browser made on Gecko's competitors, an up to date and working documentation will enable prople to create things on Gecko (I want to).

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by duduindo** [comment]
@SiegfriedEhret Links were replaced. Thank you!

**Comment by SiegfriedEhret** [comment]
Thanks ! <3
