### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/gather_and_modify_data/Plotting_yourself_on_the_map

### ISSUE THREAD

**Issue by DespertaWeb** [mdn/sprints#870]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
[URL](https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/gather_and_modify_data/Plotting_yourself_on_the_map)

# Details
Most of the links are broken

**Comment by duduindo** [comment]
The account **franciov**  was removed

**Comment by chrisdavidmills** [comment]
Francesco disappeared a while and deleted all his github demos. We unfortunately have no copy off them anywhere.

But in any case, a lot of this work is completely out-of-date now. I've fixed this by deleting all the affected pages.

**Comment by chrisdavidmills** [comment]
It is nice that it still exists somewhere, but this is only a part of all the stuff Francesco did. Most of the stuff I deleted was out of date and in need of a lot of work to make it useful again (if that is even possible...a lot of it covered Firefox OS APIs, and some of it duplicated content that was available elsewhere on MDN)
