### ISSUE TITLE
Include list to relevant issue in experimental features

### ISSUE THREAD

**Issue by curtisy1** [mdn/sprints#872]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features

# Details
It's more of a general nice to have feature I noticed when I checked the experimental features page. Some of the features listed there state that they're disabled since Firefox 44 but no further notice to why is provided and the user/developer has to explicitly google for every single feature listed instead of having a direct overview of the tracked issue linked next to the feature.

That's why it might be a good approach to just add another ```<th>``` to every table after the "Preference" column that holds a link to the relevant issue. I'm not sure if that link could be scraped and added automatically somehow though.

## Related issues
Initially issued by me here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1523534

**Comment by chrisdavidmills** [comment]
Probably need bug column on tables...
