### ISSUE TITLE
Make sure units and values reference is linked from relevant places

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#873]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change

@rachelandrew wrote a marvellous CSS units and values reference for us — https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

# Details

The actual page doesn't need any major changes, beyond being given a review/copy edit (which I'll do in a moment). However, we need to make sure it is linked to from all the appropriate places, such as:

* Learning area
* CSS front page
* Main CSS sidebar
* etc.

**Comment by estelle** [comment]
I was going to write that article, and created a ticket for it. Not sure why she didn't claim the ticket if she resolved it.
