### ISSUE TITLE
#Perf: Tutorial: Web Performance Basics

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#883]
New Documentation

Title: Web Performance Basics

Summary: In addition to the front end components of HTML, CSS, JavaScript, and media files, there are features that can make applications slower and features that can make applications subjectively and objectively faster. There are many APIs, Developer Tools, best practices and bad practices relating to web performance. Here we'll introduce many of these features ad the basic level and provide links to deeper dives to improve performance for each topic.

Linked to from https://developer.mozilla.org/en-US/docs/Web/Performance

Acceptance criteria

Complete article

**Comment by jmswisher** [comment]
Moved to next sprint; please update estimate for remaining effort.
