### ISSUE TITLE
Document BigInt64Array and BigUint64Array globals

### ISSUE THREAD

**Issue by jaydenseric** [mdn/sprints#887]
# Request type
- [x] New documentation
- [ ] Correction or update

## Page to change

There pages should be created:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array

The new entries should be listed here:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

And should probably be mentioned in these existing pages:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

# Details

`BigInt` spec section mentioning the `BigInt64Array` and `BigUint64Array` globals: https://github.com/tc39/proposal-bigint#other-api-notes

## Related issues

N/A.

**Comment by chrisdavidmills** [comment]
TRacked in https://github.com/mdn/sprints/issues/1002, so closing.
