### ISSUE TITLE
Remove "event" macro

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#891]
This is a work item for #685.

We need to refactor, delete, or decide what to do with the "event" xref macro.
See https://github.com/mdn/kumascript/blob/master/macros/event.ejs
This macros is used on over 2000 pages in all locales and we will need to either update or remove it, as it links to events in the Web/Events tree which we plan to get rid of as part of the event pages overhauling project.

**Comment by Elchi3** [comment]
Thanks for your thoughts. My 2019 sentence is: "I hate the wiki, too!" :) 

I also agree that xref macros aren't helping at all. Not for maintenance, nor for consistency. I think the plan for the `event` macro would be to replace it with plain links.

> if we had redirects from the old pages to the new ones, then things would continue to work. But I guess we can't do that since an event like close is going to be split into multiple pages.

Yes, this will not work in all cases, but there are also quite some cases where I think a redirect would work fine. I think we can live with those that will be split into multiple pages. There are ~260 event pages, I don't have a number of those we will split into multiple pages, but we could look into it to see how big of a problem it really is.

> I'll be back later to comment on the other macros.

In fact I think that there is enough work for each of these macros that I should split this in several issues. Let's have this one about the `event` macro then.

**Comment by chrisdavidmills** [comment]
This all makes sense so far, from my understanding.

I too, would love to see an end to xref macros. I don't know if we could just do an operation using the PUT API to remove them all and replace them with their simple link equivalents, as part of the future maintenance work, then get rid of the macros?

**Comment by wbamberg** [comment]
>  I don't know if we could just do an operation using the PUT API to remove them all and replace them with their simple link equivalents, as part of the future maintenance work, then get rid of the macros?

For the previous work with PUT, I took the fully-rendered version of the pages and replaced the existing content with that. That's simpler and less risky than selectively replacing parts of the content with the expanded version. Also, that was on archived pages, not actively maintained ones.

I'd be happy to automate changes like this if we could generate a single diff of the prospective changes, review it and apply it cleanly and transparently, and I guess that's the kind of thing that having the content hosted on GitHub gives us. Maybe [if we can get cleaner diffs out of the PUT API](https://bugzilla.mozilla.org/show_bug.cgi?id=1519582) that would be good enough? Might be worth looking into.

**Comment by Elchi3** [comment]
Yes, I think it would be great to have a closer look into {{event}} calls for this work. For the WebSpeech sample move, I also removed all {{event}} calls and there where ones that looked like this: `{{event("end_(SpeechRecognition)","end")}}` which is strange and now I really want to remove it even more...

@jwhitlock can you help us and run https://gist.github.com/jwhitlock/ce1088cf9b6431ff93e74791c610d3ef to get us a list of all pages that use {{event}}? 

Ideally something like this for the [2390 pages](https://developer.mozilla.org/en-US/search?locale=*&kumascript_macros=event&topic=none):

| URL  | macro call  |
|---|---|
| https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/onend  | `{{event("end_(SpeechRecognition)","end")}}`  |

**Comment by jwhitlock** [comment]
I have a [different gist](https://gist.github.com/jwhitlock/c1c7522c530d11e02cba19a2f943c52f) for finding macro usage, but it uses a naive regex parser so it may not catch every user, and combines several macros together. But, I thought quick results may be better than good results. I've uploaded the results to a [Google sheet](https://docs.google.com/spreadsheets/d/1GwObIX7mS4MPmxW89lcNfK8UIWM21OqwIXNZ7VnYCks/edit#gid=507214781). If you need better data, I can iterate on the script.

**Comment by a2sheppy** [comment]
I suggest that we have an event JSON file that provides information about all the events, including the target interface. This would be useful both for the `{{event}}` macro and for several other things, such as generating "related events" lists and automatically generating the blue event info boxes.

Something like:
```
"icecandidate": {
  "api": "WebRTC",
  "target": "RTCPeerConnection",
  "handler": "RTCPeerConnection.oniceconnection", // null if no onfoo
  "type": "RTCPeerConnectionIceEvent",
  "bubbles": false,
  "cancelable": false,
  "related": [
    "iceconnectionstatechange", "icegatheringstatechange"
  ]
}
```
The target interface could then be taken from the JSON and used by `{{event}}` to produce a correct link.
