### ISSUE TITLE
Update WebExtension notification doc to include some screenshots

### ISSUE THREAD

**Issue by rugk** [mdn/sprints#893]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/TemplateType

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

IMHO it would be good to include some screenshots for Firefox on all three platforms (Windows/MacOS/Linux), at least; so one get's an impression of what the notification looks like.

Especially for https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/TemplateType to show the differences/differentiation between the notification types.

Maybe also mobile systems (Android, iOS).

# Acceptance criteria
- [ ] New images added to page

**Comment by irenesmith** [comment]
I did not add an image to the TemplateType page, I added it to the main page for the API: [notifications](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications)
