### ISSUE TITLE
SVG: Attribute 'k' docs page missing

### ISSUE THREAD

**Issue by httpJunkie** [mdn/sprints#894]
# Request type
Update url or add page for non-existing page explaining the 'k' attribute for SVG

## Page to change
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k

# Details
We link to the page here:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute

But we get a 404 error when we visit the page.

**Comment by jmswisher** [comment]
[Reference page for 'k'](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k) now exists, thanks to Sebastian Z.
