### ISSUE TITLE
#Perf: Tutorial: Resource Hints, rel=preconnect/dns-prefetch/preload

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#899]
New Documentation 

Title: 
Controlling resource delivery with resource hints

Summary:
hinting to the browser when it should connect to another server, or preload a resource before the browser knows it ever needs it with rel=preconnect, rel=dns-prefetch, rel=prefetch, and rel=preload, and how to use them to your advantage.

Intro: 
Browsers often know better than we do when it comes to resource prioritization and delivery—but they're far from clairyovant. Native browser features enable us to hint to the browser when it should connect to another server, or preload a resource before the browser knows it ever needs it. When used judiciously, this can make fast experience seem even faster. In this article, we cover native browser features like rel=preconnect, rel=dns-prefetch, rel=prefetch, and rel=preload, and how to use them to your advantage.

Linked to from https://developer.mozilla.org/en-US/docs/Web/Performance

**Comment by Stubbierdisc79** [comment]
What
