### ISSUE TITLE
#Perf: Resource: Dev Tools perf features

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#905]
Update:
Developer Tools Performance Features
https://developer.mozilla.org/en-US/docs/Tools/Performance
This section provides information on how to use and understand the performance features in your developer tools, including Waterfall, Call Tree, and Flame Charts.

Acceptance criteria:

Article on performance features in dev tools: Explain 4 areas Dev tools performance metrics, how to read them, and why they're important.

**Comment by estelle** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Performance/Waterfall
https://developer.mozilla.org/en-US/docs/Tools/Performance/Call_Tree
https://developer.mozilla.org/en-US/docs/Tools/Performance/Flame_Chart

**Comment by jmswisher** [comment]
Looks like the 4th item is https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations
