### ISSUE TITLE
Remove event sidebar ("eventref")

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#907]
This is a work item for #685.

See https://github.com/mdn/kumascript/blob/master/macros/eventref.ejs
I think the sidebar should just be removed step by step as we delete the Web/Events/ doc tree and then this macro can be deleted from kumascript.

If we want events still to be listed when they live in the API docs tree, there is https://github.com/mdn/sprints/issues/906 about APIRef updates.

**Comment by wbamberg** [comment]
-> https://github.com/mdn/kumascript/pull/1139
