### ISSUE TITLE
A link is missing on the "Drawing graphics" page

### ISSUE THREAD

**Issue by y18272609659** [mdn/sprints#908]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

In the "Drawing graphics" page , the introduction article on "WebGL" link page has been lost .
 "Drawing graphics" page: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics
Lost page: https://developer.mozilla.org/zh-CN/docs/Learn/WebGL

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
None.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:
None.

**Comment by chrisdavidmills** [comment]
I've fixed these broken links by updating them to link  to the main MDN WebGL section. The Learning area page was removed because it was not very good.

Thanks for reporting!
