### ISSUE TITLE
window.devicePixelRatio discussion misses important point

### ISSUE THREAD

**Issue by BobHanson** [mdn/sprints#912]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

# Details

This page could be improved by pointing out that when the user increases the zoom on a page, which reduces the screen resolution, this value also increases. For example, I have a machine which reports window.devicePixelRatio = 1.5 when at zoom=100%. But when I zoom to 200%, this become 3.0. 

A comparison with Java's Toolkit.getDefaultToolkit().getScreenResolution(), for example, reports 144 dpi (rather than the standard 96) for my machine. This matches a browser zoom setting of 67%, and a devicePixelRatio of 1.0.  

There seems to be no easy way to discover the machine's actual retina-like resolution. Or, if there is, this would be a page to describe that.

**Comment by a2sheppy** [comment]
Filed a spec bug recommending the addition of a `zoomchanged` event to be used to, among other things, detect when this property changes.

**Comment by a2sheppy** [comment]
Updated:

* https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio -- Added live sample and a significant amount of additional text
* https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia - Clarifications, new details, and live sample
* https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList -- Clarifications, details, tags, and revised format for eventually adding the `change` event underneath
* https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/matches -- Clarifications and live sample
* https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/media -- Clarifications and live sample
