### ISSUE TITLE
videoWidth and videoHeight are not found in docs

### ISSUE THREAD

**Issue by Beraliv** [mdn/sprints#913]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement

# Details
I've provided the page where `videoWidth` and `videoHeight` are unachievable
![image](https://user-images.githubusercontent.com/2991847/52177455-f004b800-27d1-11e9-8a6f-564afa008b79.png)

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

## Acceptance criteria

- [x] videoWidth page has been written
- [x] videoHeight page has been written
- [x] The summaries on the HTMLVideoElement page are correct
- [x] A short example has been written and added
- [x] Submitted for review by developers

**Comment by a2sheppy** [comment]
Yeah, these pages haven't been written yet. I'll see about doing that in the coming sprint.

**Comment by Beraliv** [comment]
I can participate in

**Comment by a2sheppy** [comment]
The pages have been created and the main page's summaries updated. Feedback or corrections welcomed. Otherwise, this is complete.
