### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

### ISSUE THREAD

**Issue by stdAlexTikhonov** [mdn/sprints#914]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
Object.assign works on IE11 on windows10,
 could you mention it in article?

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

![error](https://user-images.githubusercontent.com/9639448/52192561-bf696080-285b-11e9-9f12-998a2b4a8fd1.jpg)

**Comment by duduindo** [comment]
1. Need to update the content in **Русский (ru)** language  
     1. Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
2. To add `Compat("javascript.builtins.Object.assign")` macro
3. Create an issue in https://github.com/mdn/browser-compat-data/issues to mention IE 11 + Windows 10

**Comment by jmswisher** [comment]
@Elchi3 Please add a priority label

**Comment by Elchi3** [comment]
I think the steps in https://github.com/mdn/sprints/issues/914#issuecomment-460251360 have been done.
