### ISSUE TITLE
Refactor speech event docs

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#915]
This is a work item for #685.

I want to use this issue to play through a move for a set of events from the web/events/ tree into the web/api docs as agreed in the event docs refactoring plan. I've randomly selected the WebSpeech API events for this. I think it is not a very complex example API, and should get us a feel for what we want to do here.

I'm trying to record all work that I'm doing, so that we can estimate and see how we want to chunk more event doc refactoring into issues.

Pages:

- [x] https://developer.mozilla.org/en-US/docs/Web/Events/audioend
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/audiostart
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/boundary
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/end_(SpeechRecognition)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/end_(SpeechSynthesis)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/error_(SpeechRecognitionError)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/error_(SpeechSynthesis)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/mark
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/nomatch
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/pause_(SpeechSynthesis)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/result
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/resume
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/soundend
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/soundstart
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/speechend
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/speechstart
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/start_(SpeechRecognition)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/start_(SpeechSynthesis)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/voiceschanged

**Comment by Elchi3** [comment]
Recording steps for the first page move:

- I've moved https://developer.mozilla.org/en-US/docs/Web/Events/audioend to https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audioend_event
- I've changed the sidebar from EventRef to APIRef (the events links are wrong still, but fixing this requires macro work, see the separate issue).
- I've changed the example on https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audioend_event from using the event handler "onaudioend = function" to using addEventListener, so we don't have the same example code on as we have on https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/onaudioend.
- I've updated both onaudioend and audioend_event to link to each other in see also
- I've added the event handler to the blue info box on the audioend_event page.
- I've removed FirefoxOS information.
- I've removed the legacy compat table on audioend_event and added one that queries "api.SpeechRecognition.onaudioend". We can argue whether or not this make sense. The compat data should be the same in this case for event and event handler.
- On https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Events I've renamed the section from "Event handlers" to "Events" and added _"/ audioend event"_ to the list next to its corresponding event handler property.
- I've checked if the page I moved had translations to move, but there weren't any.

I will proceed similarly with the other pages now. 
cc @chrisdavidmills for a first look.

**Comment by chrisdavidmills** [comment]
Looking good so far. I had a few comments to raise:

> I've changed the example on https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audioend_event from using the event handler "onaudioend = function" to using addEventListener, so we don't have the same example code on as we have on https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/onaudioend.

On the event page, I'd expect to see an example that uses addEventListener, and an example that uses onaudioend, with an explanation that code can be written to run in reponse to the event being raised. This won't be true in all cases, as there are events for whom on* equivalents don't exist.

> I've removed the legacy compat table on audioend_event and added one that queries "api.SpeechRecognition.onaudioend". We can argue whether or not this make sense. The compat data should be the same in this case for event and event handler.

I'd prefer to have separate compat data for events, painful as this is. It is not always necessarily the case that every event handler has an on* equivalent.

> On https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Events I've renamed the section from "Event handlers" to "Events" and added "/ audioend event" to the list next to its corresponding event handler property.

I reckon "Events" should be an h2, as events are not a type of property (although event handlers arguably are). For each event, say what it does, then also list the event handler property page below it. Is it worth saying something like "See also the Interface.onevent handler reference page", or is how you've done it clear enough?

This last point also raises the question of how we should list the event handler properties. Logically it makes sense to also list them in the Properties section. But this would be repetitious and possibly confusing. So I'm thinking list them in the Events section, but then still list them in the properties section of the sidebar for each interface (and list the events in a separate Events section in the sidebar).

Worth a discussion anyway.

**Comment by Elchi3** [comment]
Thanks for your feedback!

> On the event page, I'd expect to see an example that uses addEventListener, and an example that uses onaudioend, with an explanation that code can be written to run in reponse to the event being raised. This won't be true in all cases, as there are events for whom on* equivalents don't exist.

Okay, so now the event page has both code examples listed.

> I'd prefer to have separate compat data for events, painful as this is. It is not always necessarily the case that every event handler has an on* equivalent.

Yeah, I reckon this makes sense although it is painful. I've updated the query to "api.SpeechRecognition.audioend_event". We will see if we want to install it this way in BCD. Probably makes sense.

> I reckon "Events" should be an h2, as events are not a type of property (although event handlers arguably are). For each event, say what it does, then also list the event handler property page below it. Is it worth saying something like "See also the Interface.onevent handler reference page", or is how you've done it clear enough?

I agree, Events should be an h2. I've changed it and moved it below "Methods". I've put the event name first now and next to it the event handler. I don't think we want to list them separately as it really is the same thing. For to do in the sidebar exactly we can decide in the issue about the sidebar.

**Comment by Elchi3** [comment]
The second page had a translation. I've moved it to the new URL structure, but didn't touch it otherwise. https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/audiostart_event

**Comment by chrisdavidmills** [comment]
I'm pretty pleased with this now Florian, nice work! I think it's ready to share more widely.

**Comment by Elchi3** [comment]
The new URLs are these:

- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audiostart_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audioend_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/end_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/error_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/nomatch_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/result_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/soundstart_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/soundend_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/speechstart_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/speechend_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/start_event

- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/boundary_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/end_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/error_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/mark_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pause_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/resume_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/start_event

- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/voiceschanged_event

I'm almost done with moving these around. Maybe @wbamberg wants to give this some feedback / reviewing?

**Comment by Elchi3** [comment]
I think the quality these pages have is okay, but of course it is on us whether or not we want to make more updates to the pages as part of this moving project. (adding interactive examples, or other page structure work). @chrisdavidmills , or anyone, let me know if you have thoughts on that. Otherwise the task list above is more or less what I would recommend as part of event reference refactoring.

**Comment by chrisdavidmills** [comment]
I think this task should largely be about getting the page migrations asnd structural work done, and making sure the pages are consistent and not in too terrible a state. Additions such as interactive examples should be separate.

I think it is still worth sending this round to the rest of the team to see if they have any thoughts on what the structure of an event page could/should be.

You should also add the event page type to https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Page_types, and update the [API reference page template](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Page_types/API_reference_page_template) as this should now include the Event section.

**Comment by Elchi3** [comment]
> I think it is still worth sending this round to the rest of the team to see if they have any thoughts on what the structure of an event page could/should be.

OK, sending this to mdn-team.

> You should also add the event page type to https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Page_types, and update the [API reference page template](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Page_types/API_reference_page_template) as this should now include the Event section.

Filed as https://github.com/mdn/sprints/issues/925

**Comment by wbamberg** [comment]
Thanks @Elchi3 , this walkthrough is super-helpful and in general it looks great.

I agree with Chris that this should be an H2. The only this I don't like is this `audiostart` / `SpeechRecognition.onaudiostart` construct.

I would prefer either:

1. keep the `Event handlers` H3 that there was before - after all, they are actual properties so pedantically should appear under the Properties H2

or:

2. keep what you have here, but list them just by the event name `audiostart` and maybe have something at the top like "You can listen for all these events using `addEventListener` and passing the event name, or by assigning an event handler to the `onEVENTNAME` property of this interface".

I think since we are going with separate pages for the `on` property and the event, I'd prefer (1). But we could see how it feels as we go.

**Comment by Elchi3** [comment]
Thanks Will! 
I have no strong feeling on either way, curious to hear what @chrisdavidmills thinks on this one.

**Comment by chrisdavidmills** [comment]
I don't have hugely strong feelings here, provided the pages make sense, and there is no unnecessary repetition.

There is a conflict here in my mind — 

1. Will is right that event handler properties are properties, so it would make sense to have them listed under the "Properties" section.
2. However, it would seem really strange (at least to me) to list "events stuff" in two separate areas of the page. I think I would prefer convenience over correctness in this instance.

But is there a compromise that satifies both? Some ideas:

1. Retitle the "Properties" and "Events" sections to "Non-handler properties" and "Events and handler properties", or something shorter like "Properties" and "Events and handlers"
2. Keep it as it is in Florian's plan, but include a note at the top of each "Properties" section that says "Event handler properties are covered separately in the {{anch("Events")}} section."

Or could we do something else?

**Comment by wbamberg** [comment]
>     1. Retitle the "Properties" and "Events" sections to "Non-handler properties" and "Events and handler properties", or something shorter like "Properties" and "Events and handlers"

Consistently having "Methods", "Properties", "Events" in H2 headings is very useful for navigation, and having longer more complex headings is going to make that much less effective. And do we do it for all interfaces, including ones that don't have events, which will look weird for them, or do we have inconsistent headings between interfaces with events and interfaces with no events?

>     2. Keep it as it is in Florian's plan, but include a note at the top of each "Properties" section that says "Event handler properties are covered separately in the {{anch("Events")}} section."

This is OK, except it doesn't address my whine about `audiostart / SpeechRecognition.onaudiostart`. I just think that construction is clunky, highly repetitive, and makes the names harder to read.

Where something is this repetitive I'd prefer to note it once, which is why I suggested doing it at the start of the "Events" section.

**Comment by chrisdavidmills** [comment]
> having longer more complex headings is going to make that much less effective.

Yup, totally agreed. I didn't particularly love this idea.

> This is OK, except it doesn't address my whine about `audiostart / SpeechRecognition.onaudiostart`. I just think that construction is clunky, highly repetitive, and makes the names harder to read.

> Where something is this repetitive I'd prefer to note it once, which is why I suggested doing it at the start of the "Events" section.

Can you write me a quick example of what the events section would look like, done in the style you're suggesting? I thought you were talking about just having a single line at the top of the events section, which I didn't like because I feel that we need a link to each of the property pages. But I think I misunderstood you.

**Comment by Elchi3** [comment]
I agree, both of Will's version look better than what I proposed with the eventname / oneventname construct.
I think I slightly prefer Will's v1.

**Comment by chrisdavidmills** [comment]
Thanks for the mockups, @wbamberg — this is a perfect way to settle it.

I also agree that v1 is better. Let's go with that.

A quick wordsmithing point — could we make it slightly less verbose? How about just "Available via the oneventname property."?

**Comment by Elchi3** [comment]
For the compat data part of this, please see and review https://github.com/mdn/browser-compat-data/pull/3420.

**Comment by Elchi3** [comment]
I've updated the events listing based on Will's v1 and Chris' comment to make it less verbose:

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Events
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis#Events
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance#Events

**Comment by wbamberg** [comment]
https://github.com/mdn/sprints/issues/915#issuecomment-460259746 is missing the step where you change the page title to _target_: _eventname_ (unless I can't see it).

Also it's perhaps worth noting that you get the place to move the event from its target, as (should be) listed in the event page.

**Comment by wbamberg** [comment]
It seems like there are (at least, ha!) 2 different formats for event pages:
https://developer.mozilla.org/en-US/docs/Web/Events/devicechange
https://developer.mozilla.org/en-US/docs/Web/Events/dblclick

Are we also updating pages to converge on a single format (the first I think, with the blue box)? I suppose we might as well.

Also, note that https://developer.mozilla.org/en-US/docs/Web/Events/devicechange has an H2 "Example" while e.g. https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audiostart_event has "Examples". I think we should use "Examples" consistently.

**Comment by wbamberg** [comment]
Also, of course, events have properties. One of the items in the blue box is "interface" which I guess references an object where the properties are defined. https://developer.mozilla.org/en-US/docs/Web/Events/dblclick, for example, has this as a link to [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent), which defines all the properties. But then the `dblclick` page also has a Properties section which lists the properties...again? Should we try to clean this up?

I guess that falls under "more updates to the pages as part of this moving project" from https://github.com/mdn/sprints/issues/915#issuecomment-460716493.

**Comment by Elchi3** [comment]
Let's go with "Examples".

I think we should agree on one format for the blue box, I think I prefer the one I did for speech events, e.g. https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audiostart_event

I think properties belong to the "interface" of the event, so they should be on e.g. https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent but not on https://developer.mozilla.org/en-US/docs/Web/Events/dblclick. The link to the MouseEvent interface from dblclick is important though as it then gets you the properties you can use, so a consistent blue box where this info is present is very useful.

I think we can try to clean this up and have more consistency, but I guess it is also a judgment call sometimes. We only have so much time for the overall effort on the event reference overhaul. I'll let Chris answer this.

**Comment by chrisdavidmills** [comment]
> I think we should agree on one format for the blue box, I think I prefer the one I did for speech events, e.g. https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audiostart_event

Yup, i prefer this one too.

I would like to make the pages all follow one consistent structure as part of this work, yes. Does that seem too much an ask, from your experience so far? I will be trying my first set of pages probably tomorrow.

**Comment by chrisdavidmills** [comment]
@Elchi3 I've done a full review of the Web Speech API events pages. apart from the bits mentioned below, I just did some small editorial changes. Looking pretty good!

The following pages need:

1. The "Target objects" line removing from blue box.
2. The "Inheritance" section removing (as we aren't including these, right?).
3. BCD submitting.

* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/boundary_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/end_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/error_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/mark_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pause_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/resume_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/start_event

* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audiostart_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/audioend_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/end_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/error_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/nomatch_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/result_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/soundstart_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/soundend_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/speechstart_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/speechend_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/start_event

* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/voiceschanged_event

The following pages also need an addEventListener() example adding to the "Examples" section:

* https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/result_event
* https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/voiceschanged_event

General comment on the "Events" in the target interface page — shouldn't we link the instance of addEventListener() to the addEventListener() page?

**Comment by chrisdavidmills** [comment]
@Elchi3 Ooooh, one more comment too — the event links in the sidebar look a bit screwed, so you could do with sorting those out.

**Comment by Elchi3** [comment]
Thanks for your review, Chris :+1: 


> 1. The "Target objects" line removing from blue box.

Done, and also added `<th scope="row">`.

> 2. The "Inheritance" section removing (as we aren't including these, right?).

Agreed, I've removed this.

>    3\. BCD submitting.

This is https://github.com/mdn/browser-compat-data/pull/3420. Do you want to review it?

> The following pages also need an addEventListener() example adding to the "Examples" section:

Done.

> General comment on the "Events" in the target interface page — shouldn't we link the instance of addEventListener() to the addEventListener() page?

Done.

> @Elchi3 Ooooh, one more comment too — the event links in the sidebar look a bit screwed, so you could do with sorting those out.

The sidebar work is tracked in https://github.com/mdn/sprints/issues/906. I haven't changed anything on it yet, it has been crappy like this for many years :) Or do you have anything in mind particularly that need fixing?

**Comment by chrisdavidmills** [comment]
> The sidebar work is tracked in #906. I haven't changed anything on it yet, it has been crappy like this for many years :) Or do you have anything in mind particularly that need fixing?

I wasn't planning on anything too drastic right now. I've was just thinking of improving the links shown in the sidebar for events, which are taken from Groupdata:

https://github.com/mdn/kumascript/blob/master/macros/GroupData.json#L2210

It would be so much nicer if we could change stuff like "error_(SpeechRecognitionError)" to something like "SpeechRecognition error" or "error (SpeechRecognition)". But I guess changing these would require changing the macros? Hrm, maybe leave this for now and fix them all at the end.

**Comment by Elchi3** [comment]
Yeah, no idea. I think I would rather fix sidebars later and move on with content moving for now.

**Comment by chrisdavidmills** [comment]
Yeah, good call. Let's park this for now.

**Comment by Elchi3** [comment]
I've updated the pages to use the {{compat}} table and I think the remaining issues you raised are fixed as well. For the sidebar, we will fix things in the issue dedicated to APIRef and how it deals with events. Please comment there for specific things we should get right. https://github.com/mdn/sprints/issues/906

Closing this as done.
