### ISSUE TITLE
Remove Layout Debugging survey, return to 'Build in the Browser' banner after April 4th

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#919]
## external-request

Hi MDN friends!

We had great success with the November survey banner on MDN: 292 complete responses, particularly from beginner developers who we weren't able to effectively reach from other channels.

The survey responses yielded interesting findings that offered both validation and changes to our goals. The biggest takeaway was that developers want better CSS layout debugging tools. The Layout Tools team has committed Q1 to research and UX work for these tools. We need to learn more about the main problems users face, so we are planning to run a 1-page follow-up survey in February. Being able to promote the survey on MDN again would be so helpful in getting a full picture of developers' needs.

This doc contains the near-finalized survey text, as well as an image of the proposed banner.

I chatted with Kirby who owns the current DevEdition banner, and she supports the replacement of that banner for 3 weeks.

Time frame: We're pretty flexible and can pre-launch the survey on social media. If the MDN banner change could happen sometime in Feb, that would be awesome.

Happy to make changes or provide more info!

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1524354

# Acceptance criteria

- [x] New banner live in production

# Tasks

1. - [x] Get all relevant assets
2. - [x] Implement new banner design
3. - [x] Get signoff from Marketing
4. - [x] Open PR for review
5. - [x] Pushed to production

**Comment by jwhitlock** [comment]
This has been deployed to production, and 3 weeks out is April 4th. [Bug 1524354](https://bugzilla.mozilla.org/show_bug.cgi?id=1524354) includes "remove the banner" in the description, I'd like to continue using it for removal work. Do we want to continue using this task for removal, or close it for this sprint and write a new task for the next sprint?

**Comment by schalkneethling** [comment]
> This has been deployed to production, and 3 weeks out is April 4th. [Bug 1524354](https://bugzilla.mozilla.org/show_bug.cgi?id=1524354) includes "remove the banner" in the description, I'd like to continue using it for removal work. Do we want to continue using this task for removal, or close it for this sprint and write a new task for the next sprint?

Let's reuse this one. Thanks!
