### ISSUE TITLE
On mobile, heading link widgets are on the next line instead of right after the heading

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#920]
Reported by @a2sheppy - "The link widget that appears after heading text is being drawn along the left margin below the heading text rather than immediately after the heading text. This should be fixed (especially since screen space is at a premium; all the extra wrapping is using up space fast). See the attached screenshot."

![screenshot](https://bug1523643.bmoattachments.org/attachment.cgi?id=9039822)

# Acceptance criteria

- [ ] Heading anchor links do not break to next line on mobile

# Tasks

1. - [ ] Implement CSS change to ensure heading anchor links do not break to next line on mobile

**Comment by jwhitlock** [comment]
This is deployed, and works a lot better. On the [Learn index page](https://developer.mozilla.org/en-US/docs/Learn), the link icon is on the same line, unless the section name is long, in which case it is on the next line:

![learn index](https://user-images.githubusercontent.com/286017/52823703-8c08ac00-307b-11e9-83d8-6484e006ecb7.png)

**Comment by jwhitlock** [comment]
Next sprint work in https://github.com/mdn/sprints/issues/1090
