### ISSUE TITLE
Standup single webpage on mdn.dev

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#922]
# User story

From Ali's email:

"The plan for the short term, meaning the deadline Google gave us of February 12th, is to just get a simple 1-page site up, that points to developer activities on/for MDN. Chris Mills wrote up a content draft, and the MDN engineering team is going to do the development for the web page itself. Long term, we may, or may not, decide to replace developer.mozilla.org with mdn.dev, but that has not been decided yet and won't be before the 12th."

# Acceptance criteria

- [x] Single page live on mdn.dev

# Tasks

1. - [x] Ensure copy is approved
2. - [x] Get relevant design assets
3. - [x] Set-up new project
4. - [x] Implement page design and content
5. - [x] Open PR
6. - [x] Page live on mdn.dev

**Comment by schalkneethling** [comment]
Here is the proposed page design/layout:

![localhost_8080_dist_ 1](https://user-images.githubusercontent.com/10350960/52650097-3d7bd600-2ef2-11e9-8941-fdd1f84e223f.png)

**Comment by chrisdavidmills** [comment]
Looking good @schalkneethling . I think the different repo names could all do with being links to those repos, and maybe the content areas could do with being linked to their respective landing pages, but I think that's about it.

I'd also like another writer to sanity check the content. @a2sheppy , can you give the mdv.dev content I wrote a quick look over to make sure there is nothing terrible in there? ;-)

**Comment by schalkneethling** [comment]
thanks for the feedback @chrisdavidmills

**Comment by schalkneethling** [comment]
I have updated the content to link to all the things.

**Comment by jwhitlock** [comment]
This appears complete, https://mdn.dev is up
