### ISSUE TITLE
Convert from django-pipeline to decoupled asset processing

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#928]
# User story
As a front-end developer, I want to use modern tools to prepare assets, so that I can use more complicated workflows.

# Acceptance criteria
* Asset work is split between processing and collecting
* Asset file locations reflect the workflow
* Asset workflow is documented
* ``django-pipeline`` is removed

# References
* [bug 1380419](https://bugzilla.mozilla.org/show_bug.cgi?id=1380419) - Refactor static asset generation
* [Taiga Epic 1799](https://tree.taiga.io/project/viya-mdn-durable-team/us/1799) - Improve static asset development
* Issue #764 - Adopt a modern build / packaging toolchain
* https://owais.lone.pw/blog/webpack-plus-reactjs-and-django/
* https://github.com/owais/django-webpack-loader
* https://github.com/mozilla/bedrock/pull/5618

**Comment by jwhitlock** [comment]
Now that I've submitted the asset document for review, I'm ready to start on this task. My plan is to create a top-level folder ``assets`` with this structure:

* ``assets``
  - ``static`` - Files that are not changed
  - ``reference`` - Reference files, like photoshop files
  - ``src`` - Sources like Sass and JSX that are processed
  - ``dist`` - Output of processing

For example, [kuma/static/img/avatar.png](https://github.com/mozilla/kuma/blob/master/kuma/static/img/avatar.png) would move to ``assets/static/img/avatar.png``.

I'm not sure if pipeline stuff goes right into ``assets/src``, or an intermediate place like ``assets/pipeline``, and ``webpack`` owns ``assets/src``. I'll think about it this weekend.

**Comment by jwhitlock** [comment]
Status at the end of Sprint 2:

* Static assets moved to ``/assets/static``
* Unused assets moved to ``/assets/legacy``, or ``/assets/reference``, no breakage on production noticed so far. Went from 2055 to 1929 collected assets

In process:
* CKEditor - is it worth getting development mode working? (https://github.com/mozilla/kuma/pull/5266) Then, move to ``/assets/ckeditor4`` (https://github.com/mozilla/kuma/pull/5267, if previous answer is yes).

In Sprint 3:
* JS i18n - Move output directory to ``/assets/jsi18n``, rather than the currently proposed ``/assets/build/locale/jsi18n``.
* Django-pipeline (SASS / CSS) - Move to ``/assets/styles``, convert to ``gulp`` to call Sass tools and output to ``/assets/build/css``, and load in templates with ``{{ static }}`` or similar. I suspect a direct transition to ``webpack`` would be possible, but based on the time available, we should transition to ``gulp`` first, and convert to ``webpack`` as we convert endpoints to use React (``main.js``, ``wiki.js``).
* Django-pipeline (JS) - Need to pick npm scripts, gulp, or go straight to webpack. I think there is a 50% chance that a webpack conversion will be the right choice, and 50% that ``gulp`` wins as a transitional tech.
* React - Using``/kuma/javascript`` for React ``.jsx`` code, with a ``src`` and ``dist`` folder under it. Need to move ``src``, ``dist``, both, or neither to ``/assets``. Need to document React / webpack workflows

**Comment by peterbe** [comment]
Let's look to the Yari future instead.
