### ISSUE TITLE
Work towards updating Kuma to Python 3 (S2 Q1)

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#930]
# User story
As an MDN developer, I want Kuma to run under Python 3, so it's on a current Python release and ready for Django 2.2.

# Acceptance criteria
Time-box the work towards this goal to 5 ideal days.

# Tasks
Continue the effort in #746, working on the tasks outlined in [this issue's epic](https://github.com/mdn/sprints/issues/230).

**Comment by jmswisher** [comment]
@escattone Should I repurpose this issue and reassign to @peterbe for his work in India.Arie?

**Comment by escattone** [comment]
@jmswisher That would be great, thanks!

**Comment by peterbe** [comment]
Here's my start to try to rewrite the work as my own sprint issue: https://github.com/mdn/sprints/issues/1475
