### ISSUE TITLE
bug 1523273 - Switch hreflang from "en-US" to "en", other updates

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#931]
# User story
As a MDN viewer in the U.K., I want to see the en-US version, because the Bambara locale is inappropriate.

# Acceptance criteria
Implement SEO recommendations for language code metadata:
* Use ``lang="en"`` language codes for ``en-US`` pages
* Prefer general locale codes like ``pt`` and ``fy`` to country-specific codes like ``pt-BR`` and ``fy-NL``.
* Do not change locale code in URLs
* Get @rraue's review on the PR

# Tasks
* [ ] Determine preferred country variant for ``bn`` (``bn-BD`` or ``bn-IN``)
* [ ] Determine preferred country variant for ``zh`` (``zh-CN`` or ``zh-TW``)

**Comment by rraue** [comment]
* Use `lang="en"` language codes for `en-US` pages
Thats two tasks imo, as we need to change the html lang and the hreflang from en-US to en.

**Comment by escattone** [comment]
This has been merged to master and deployed to production. Thanks again @rraue for your help!

**Comment by jwhitlock** [comment]
The related PR was https://github.com/mozilla/kuma/pull/5268. "bn" prefers "bn-BD", and "zh" prefers "zh-CN".

**Comment by atopal** [comment]
This was a major success! Here's a selection of countries where you can see a major uptick around the 27th of February. The dashed line is last year, the solid line is this year:

![Ukraine](https://user-images.githubusercontent.com/557852/54425169-f5301d80-4714-11e9-96e9-059f4f4e65d1.png) Ukraine 
![India](https://user-images.githubusercontent.com/557852/54425203-09741a80-4715-11e9-8d05-ddb90fefbf11.png) India
![Canada](https://user-images.githubusercontent.com/557852/54425263-29a3d980-4715-11e9-8897-3e5570b7593b.png) Canada 
![UK](https://user-images.githubusercontent.com/557852/54425271-31637e00-4715-11e9-9319-3a81b71e6c38.png) UK
