### ISSUE TITLE
bug 1441672: Change homepage redirect from 302 to 301

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#932]
# User story
As an SEO expert, I want the homepage to have a 301 Moved Permanently redirect to the default locale ``en-US``, so that pagerank is passed to the homepage.

# Acceptance criteria
* The [homepage](https://developer.mozilla.org/) is a 301 "Moved Permanently" redirect to the [English variant](https://developer.mozilla.org/en-US/).

# References
* https://bugzilla.mozilla.org/show_bug.cgi?id=1441672#c2

# Notes
This will break the cookie-based locale redirect, and restrain our options for providing user-specific locales. On the other hand, SEO.

**Comment by atopal** [comment]
Please don't push this to production. The idea is not to redirect to en-US by default, but using the same logic as before and changing from a 302 to a 301. Raphael will follow up with the explanation.

**Comment by rraue** [comment]
It might be just a misunderstanding because of chinese whispers, but its very important:

We must not change anything for the current logic. If I get it right, users and crawlers are currently sent via a 302 based on their accept language to /locale/. That must not change, we just change the 302 to 301. A german user is still sent to /de/, a french one to /fr/ and an english one to /en-US/ just not with a 302 but a 301.

Reference is www.mozilla.org, where the same logic is implemented, but not via 302 but 301.

The language selector in the footer should still redirect via a 302 and  the cookie-based logic shouldn't change as well. On www it remebers my user choice as well. 

So only when hitting a url without a locale, the redirect must be a 301.

**Comment by safwanrahman** [comment]
@rraue I have left a comment in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1441672#c4) regarding it. 
> We must not change anything for the current logic. If I get it right, users and crawlers are currently sent via a 302 based on their accept language to /locale/. That must not change, we just change the 302 to 301. A German user is still sent to /de/, a French one to /fr/ and an English one to /en-US/ just not with a 302 but a 301.

Its not possible to have the current logic implemented with `301` redirect. the users and crawlers are not only redirected by accept language, but also there is a language preference cookie set on the browser according to their choice where we should redirect. So if we change the redirect to `301`, it will break the functionality of cookie based redirection.

**Comment by escattone** [comment]
@atopal @rraue I just wanted to confirm what @safwanrahman has brought up here (and what @jwhitlock pointed out from the very beginning within the user story above), that this approach -- at least my understanding of it as implemented in https://github.com/mozilla/kuma/pull/5261 -- breaks our current cookie-based redirection, and perhaps that's not worth the SEO benefits (or maybe it is)?

**Comment by atopal** [comment]
@escattone to confirm, it would only break that for the home page and only for people who have the cookie set, right? In which case, I'd be fine with it. The feature request for a cookie based redirect was mainly for people who follow deep links without a locale code in them AFAIK.

**Comment by escattone** [comment]
@atopal I had written my PR for this [mozilla/kuma#5261](https://github.com/mozilla/kuma/pull/5261) based on my understanding of @rraue's comment above, so in other words, not just for the home page, but all pages (so cookie-based redirection would break for all pages). However, perhaps I should have followed the original intent of this task, and only redirected the homepage using 301, and all other pages would still be redirected with 302, so cookie-based redirection would break only for the homepage?

**Comment by escattone** [comment]
There's one detail I wanted to highlight here. Even if we use 301's for the locale redirects, the cookie-based locale selection mechanism would still be used (if a language cookie has been selected) the very first time the locale-free homepage or document URL is requested. After that, of course, the user's browser (using its cache of 301's) will take care of the redirect, or in other words, the user's cookie-based selection has been made "permanent" -- at least until the user clears the browser's cache of 301's. So when we say that the cookie-based redirection has been broken, we really mean, I think, is that it will work only once for any given locale-free URL, and then, following that, ignored for that same URL (the locale selection will have been made "permanent" for that URL).

**Comment by escattone** [comment]
For the record, @atopal and I discussed this issue over Vidyo. @atopal decided that he is OK with using 301's only for the homepage. We won't use 301's for the locale-based redirects for any other pages. So we'll go with the original intention of this user story, which is to focus only on the homepage. I'll adjust [mozilla/kuma#5261](https://github.com/mozilla/kuma/pull/5261) accordingly.

@atopal understands that this means that cookie-based redirects of the locale-free homepage (`https://developer.mozilla.org/`) will be made "permanent" based on the language cookie in place the first time the locale-free homepage is requested. The user's language cookie will be ignored for any further requests of the locale-free homepage (the browser will handle the redirect).

**Comment by safwanrahman** [comment]
@escattone @atopal Why dont we make `301` in the homepage for the crawlers only? so the user experience also not get broken and the SEO issue also get solved?

**Comment by jwhitlock** [comment]
CloudFront removes the user agent string before passing the request to Kuma, so we can't identify crawlers on the backend in production.

**Comment by escattone** [comment]
This has been merged to master and deployed to production.
