### ISSUE TITLE
bug 1523662 - Investigate <wbr/> in search results

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#933]
# User story
As a MDN user, I don't want ``Java<wbr/>Script`` in Google search results, because it is gross.

# Acceptance criteria
- [x] Determine possible causes of ``</wbr>`` in search results, add to [bug 1523662](https://bugzilla.mozilla.org/show_bug.cgi?id=1523662).

**Comment by jwhitlock** [comment]
This is strange to me - Acceptance criteria done, but in Backlog. Maybe the intent was that there is work to do after the investigation? That feels like a new issues. Moving to closed.

**Comment by atopal** [comment]
Apologies, I forgot to move it here. Thanks John.
