### ISSUE TITLE
Export unrendered content to GitHub

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#938]
# User story
As MDN staff, I want wiki page revisions migrated to GitHub, so I can analyze content with code.

# Acceptance criteria / Tasks
* Create an export of MDN content similar to https://github.com/jwhitlock/mdn-archive-proto1
* Document next steps toward goals (offline rendering, KumaScript macro replacement, etc.)

**Comment by jmswisher** [comment]
@wbamberg @ddbeck @escattone  I think this issue was an early stab at something like stumptown. I'm guessing it's no longer relevant. Can it be closed?

**Comment by escattone** [comment]
@jmswisher Yes, I'll close it, thanks!
