### ISSUE TITLE
Implement high-priority mitigations for Codepen integration

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#944]
# User story
As a MDN developer, I want to implement the high-priority mitigations from the Codepen [Rapid Risk Assessment](https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment.html) (RRA), so we continue on the next phase of the API examples project and reduce the risk on MDN.

# Acceptance criteria
* High-priority mitigations are implemented
* (Alternative) Codepen integration is disabled until mitigations can be addressed

**Comment by schalkneethling** [comment]
@jwhitlock During the meeting I had with @atopal and @wbamberg we decided to remove the Codepen and related code during this(upcoming) sprint:

https://github.com/mdn/sprints/issues/947

I guess this would then meet the alternate acceptance criteria for this issue. In the next sprint, we should then decide how we want to move forward and include the suggested security mitigations as part of that work. Sound good?

**Comment by jwhitlock** [comment]
Sounds good to me.

**Comment by Stubbierdisc79** [comment]
Soundd good??

**Comment by schalkneethling** [comment]
One of the items we will need to address here is using SRI for the script we are loading from Codepen. More can be read about it here:

https://hacks.mozilla.org/2016/04/how-to-implement-sri-into-your-build-process/

There is a Webpack plugin to help with this:
https://www.npmjs.com/package/webpack-subresource-integrity

**Comment by schalkneethling** [comment]
Note to self: Remember to follow up with this bug once we pick this up again:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522766
