### ISSUE TITLE
MDN Web DNA CTA

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#946]
# User story
As the PM I want to be able to ask users to take the MDN DNA survey, so we can get wide participation

# Acceptance criteria
* CTA can be localized
* CTA is not overlapping with other banners
* People who click it away are not asked to take the survey again for x days

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by atopal** [comment]
For the MDN developer needs assessment, we'll need the ability to ask people to take a survey. We can't use the soapbox for this, since we need to be able to localize the CTA. 

Ideally, we come up with a universal banner that replaces the current payment banner, task completion survey and the soapbox, but the requirement is that we can field a survey in March.

**Comment by schalkneethling** [comment]
Related Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1525538

**Comment by schalkneethling** [comment]
Hey @atopal 

Starting to work on this so, want to be sure I have everything accurate.

This calls for a CTA banner, in the style of the current payments banner. This iteration should not be tied to any specific design, but instead simply be a container that:

1. On page load expands
2. Has the ability to be minimized - In which case it will remain minimized for 30 days
3. Dismissed - In which case it will be completely removed. The only time it will show up again is if the user views it in a different browser or, the `localStorage` was cleared by the user, browser crash or whatever else
4. The content inside the CTA can essentially be anything

It will have two states
1. minimized
2. expanded

I also believe there is a requirement that if we have for example 3 CTAs, one needs to set the order so, when the first is dismissed, the second shows up, and then the third.

I have a question with regards to this. Do we show the next one in line on the very next page load or, the next browser session? i.e. we store a state in `sessionStorage` and only show the next if the state is not in `sessionStorage`

Still thinking this through so, I may have other questions ;) Thanks!

**Comment by schalkneethling** [comment]
Closing this as the discussion has moved to https://github.com/mdn/sprints/issues/1130
