### ISSUE TITLE
Remove new Codepen integration

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#947]
# User story

From the interactive-examples meeting notes:
https://github.com/mdn/interactive-examples/wiki/(not)-Weekly-Meeting-Notes#5-february-2019

"Last sprint Schalk delivered CodePen embeds on MDN -> work great.

There are concerns about security (loading third party libraries) and about having the code on all pages.

security: assessment is ongoing.
having the code on all pages: unlikely to have a big impact on performance, and having it only on some pages is much harder to implement.
We will not be having user testing of this feature in the next sprint, so the decision is: remove the CodePen integration for now, and add it back when we are ready for user testing."

# Acceptance criteria

- [ ] All code related to the initial implementation is removed from the codebase
- [ ] All code related to the initial implementation is removed from production

# Tasks

1. - [x] Remove code related to the initial implementation from Kuma codebase
2. - [x] Open PR
3. - [ ] Pushed to production

**Comment by schalkneethling** [comment]
Also see https://github.com/mdn/sprints/issues/944

**Comment by schalkneethling** [comment]
For reference, here is the original PR that implemented this:
https://github.com/mozilla/kuma/pull/5202

**Comment by jwhitlock** [comment]
Deployed to staging and production.
