### ISSUE TITLE
Refactor WebVR events

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#948]
This is a work item for #685.

Pages:

- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplayactivate
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplayblur
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplayconnect
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplaydeactivate
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplaydisconnect
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplayfocus
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplaypresentchange

The target interface for all of these here is window, so they would move to https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayactivate_event etc.

**Comment by chrisdavidmills** [comment]
OK, so I think I've finish this refactoring now. Ready for review @wbamberg.

I have moved the pages for the seven existing event ref pages and made changes as discussed:

* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayactivate_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayblur_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayconnect_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaydeactivate_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaydisconnect_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayfocus_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaypresentchange_event

I also created pages for the two events/handlers featured in the spec that weren't documented:

* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaypointerrestricted_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/onvrdisplaypointerrestricted
* https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplaypointerunrestricted_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/onvrdisplaypointerunrestricted

I created the Event section on the Window page. I put them under a WebVR section, as there will be many different sets of events hanging off window that related to different APIs — I thought they could use some organization.

https://developer.mozilla.org/en-US/docs/Web/API/Window#Events

Finally, I submitted a PR to update the BCD:

https://github.com/mdn/browser-compat-data/pull/3492

**Comment by wbamberg** [comment]
These look perfect to me, thanks Chris.

The only departure from spec is that you didn't add links to the `on-` event handler property in See also. But looking at these pages, since we have a link in the blue box, that doesn't seem needed. @Elchi3 , maybe we should stop recommending it? Although I'm not going back to change existing pages again :).

I see Florian merged the BCD PR, so this is r+, and can be marked as done once the pages have been updated to use {{Compat}} and are showing the tables.

**Comment by chrisdavidmills** [comment]
> The only departure from spec is that you didn't add links to the `on-` event handler property in See also. But looking at these pages, since we have a link in the blue box, that doesn't seem needed. @Elchi3 , maybe we should stop recommending it? Although I'm not going back to change existing pages again :).

Ah, OK. I think I missed that part. But yeah, sounds like it can be treated as optional.

**Comment by chrisdavidmills** [comment]
And cheers for the review, much appreciated!

**Comment by Elchi3** [comment]
> The only departure from spec is that you didn't add links to the `on-` event handler property in See also. But looking at these pages, since we have a link in the blue box, that doesn't seem needed. @Elchi3 , maybe we should stop recommending it? Although I'm not going back to change existing pages again :).

I agree it is sufficient enough in the blue box. No need to change this in existing pages.

**Comment by Elchi3** [comment]
> I see Florian merged the BCD PR, so this is r+, and can be marked as done once the pages have been updated to use {{Compat}} and are showing the tables.

I've updated the pages for Chris so that we can set this issue to bed.
