### ISSUE TITLE
Refactor WebGL/canvas events

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#953]
This is a work item for #685.

Pages:
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/webglcontextcreationerror
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/webglcontextlost
- [ ] https://developer.mozilla.org/en-US/docs/Web/Events/webglcontextrestored

This is a small but interesting set of events. As far as I can tell there are no "on" event handler properties for these. The target is HTMLCanvasElement so it should move there.

**Comment by Elchi3** [comment]
I've moved the pages into the API tree. The new listing is here:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement#Events

The three refactored pages:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextcreationerror_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextlost_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextrestored_event

The old compat tables will be replaced with new ones when https://github.com/mdn/browser-compat-data/pull/3474 is reviewed and shipped.

review? @irenesmith

**Comment by Elchi3** [comment]
Is there anything else I need to do to move this forward?

**Comment by chrisdavidmills** [comment]
@irenesmith you were down to do a review on this set of event pages. Can you do so today or tomorrow, please?

**Comment by irenesmith** [comment]
Review completed. LGTM

**Comment by wbamberg** [comment]
I think this can be closed?

**Comment by Elchi3** [comment]
It was just waiting for the BCD to ship. Compat tables are updated now.
