### ISSUE TITLE
Update compat data for two value logical shorthands

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#957]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties and all linked pages dealing with two value shorthands.

# Details
Firefox 66 has the two value logical shorthands for margins, borders and padding. Trello card links to the individual bugs: https://trello.com/c/1CtY17he/51-css-logical-properties-level-1-fx-66

I already documented these as part of my work on logical properties so I think my only task here is a bit of BCD updating and just casting an eye over the relevant pages.

**Comment by rachelandrew** [comment]
PR for compat data https://github.com/mdn/browser-compat-data/pull/3451

Also saw that FF have implemented the radius longhands for 66 so this includes those. Chrome have the shorthands but not the radius features.

**Comment by rachelandrew** [comment]
PR is merged though the compat data is not showing on the pages as yet. I have also updated the main page and the guide for margin, border, padding.

**Comment by rachelandrew** [comment]
@chrisdavidmills this is done, I've been through all the pages and updated them so the data shows up:

* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-width
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-style
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-color
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-width
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-style
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-color
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-width
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-style
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline
* https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block
* https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline
* https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
* https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline

**Comment by chrisdavidmills** [comment]
Perfect; done and dusted!
