### ISSUE TITLE
 Geolocate demo is broken, Google Maps needs an API key

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#959]
Cross-filed from Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1501189

AC: bug is closed.

**Comment by wbamberg** [comment]
I've updated the example in that page: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Geolocation_Live_Example to remove the Google Maps dependency.

It works fine in Chrome and Firefox release, but not in Firefox Nightly. (I get "User denied geolocation prompt" even though I accepted the prompt). I think this is a configuration issue or a Firefox problem though.

@jwhitlock , since this implements your proposal in https://bugzilla.mozilla.org/show_bug.cgi?id=1501189#c2, would you mind reviewing it for me? Thanks!

**Comment by jwhitlock** [comment]
@wbamberg the example works for me, and clicking the link takes me to an accurate OpenStreetMap.

I first tried the example in Safari then Firefox Dev Edition, and it worked both times. Your error sounds similar to the one reported in https://github.com/mdn/sprints/issues/1032, which was reported before your change.

**Comment by wbamberg** [comment]
Thanks John. I'll close this then, on the assumption that the Firefox issue is not related to this particular example.
