### ISSUE TITLE
https://developer.mozilla.org/en-US/Firefox_OS/Debugging/Installing_ADB

### ISSUE THREAD

**Issue by amatobuononato** [mdn/sprints#960]
# Request type
- [ ] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
@amatobuononato Did you find a link to this page somewhere? It has been moved to https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Debugging/Installing_ADB

It's supposed to redirect, so if that's not happening, please say where you found it.
