### ISSUE TITLE
NotificationAction does not have documentation. The generic documentation is very abstract.

### ISSUE THREAD

**Issue by pudupa** [mdn/sprints#962]
# Request type
- [ ] New documentation
- [x ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction

# Details
There is no content in the above documentation. It says 'Page not found'.
The generic documentation about NotificationAction is abstract, confusing and inadequate:
https://notifications.spec.whatwg.org/#dictdef-notificationaction
We need clear documentation/description with examples for the sub properties in there as well, namely 'action'/'title'/'icon'

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
{NotificationAction](https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction) article now exists.
