### ISSUE TITLE
React Spike: Create a new Kuma wiki endpoint for experimentation

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#965]
# User story
As an MDN frontend developer, I want to create a new Kuma endpoint, so I can experiment with React without affecting pages that are user-visible.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1525719

# Acceptance criteria

- [x] the new endpoint allows me to access URLs like /en-US/ducks/Web/HTML/Element/abbr that display exactly the same content (before I begin experimenting) as /en-US/docs/Web/HTML/Element/abbr (though we might use "beta" or "react" or "test" instead of "ducks"

- [x] (optional) the new endpoint only works on the staging server, and is not available to end-users on developer.mozilla.org

**Comment by jwhitlock** [comment]
* Existing page: https://developer.allizom.org/en-US/docs/Web/CSS/appearance
* With React: https://developer.allizom.org/en-US/ducks/Web/CSS/appearance
