### ISSUE TITLE
As a content team member, I want improved processes and tools, so I can spend less time on overhead

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#971]
# Acceptance Criteria 
- [ ] A document has been shared with proposals for changes to processes, and/or creation of tools in the content workflow.

**Comment by jmswisher** [comment]
@chrisdavidmills Is this what you had in mind?

**Comment by chrisdavidmills** [comment]
Yup, sounds good to me. With indicators as to which are the low hanging fruit, which might take a bit longer, calls for involvement from the team, etc.

**Comment by jmswisher** [comment]
Duplicate of #624
