### ISSUE TITLE
P1:  Define "static function" in the Glossary

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#973]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1474403

# Acceptance criteria

1. - [ ] Glossary entry written, as requested in above bug.

**Comment by chrisdavidmills** [comment]
I've written this:

https://developer.mozilla.org/en-US/docs/Glossary/Static_method

@a2sheppy , can you give this a quick review for me, and let me know if you think it needs anything else?

**Comment by a2sheppy** [comment]
LGTM. This is good. Thanks!
