### ISSUE TITLE
Investigate improvement of WebAssembly docs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#974]
# User story
As a web developer, I want to find more useful WebAssembly content on MDN, so I can learn more about it, and how it can benefit my work.

See also https://trello.com/c/5AVHj1RA/19-webassembly-improvements-fx-65-but-mostly-nightly-only-for-now for related docs tasks

# Acceptance criteria

1. - [ ] Conversations had with key WebAssembly engineering folk such as Lin, Till, Aaron, Steve, Ashley?
2. - [ ] Plan written up that communicates ideas for possible improvements, and neccesary research and other follow on work.

**Comment by chrisdavidmills** [comment]
Mail sent to Lin, Aaaron Turon, and Till, to guage their interest and see if they have any thoughts on this.

**Comment by jmswisher** [comment]
@chrisdavidmills This was "Continue in next sprint" at the end of Fantasia, but it was not added to any later sprint. Should I put it in the Parking Lot?

**Comment by chrisdavidmills** [comment]
Yes, please do. I've not gotten round to making progress on this.
