### ISSUE TITLE
Plan for tidying up Credential Management / Web Authn API docs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#976]
# User story
As a web developer, I want high quality documentation on the Cred Man / Web Authn APIs, so I can use them effectively in my work.

The docs for these APIs are already written:

* https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

But they really could use a thorough tidy up / copy edit to improve the quality of the documentation. In addition to this, there might be other, deeper tasks required to bring them up to scratch. 

# Acceptance criteria

1. - [ ] Review the API documentation to see what the general state is
2. - [ ] Review the specifications to see if anything is missing in terms of the reference documentation.
3. - [ ] Research what tutorials may be required; talk to engineers as required.
4. - [ ] Write the above up into a plan
5. - [ ] Start copy editing the documentation as time allows.

**Comment by SphinxKnight** [comment]
Just created https://developer.mozilla.org/en-US/docs/MDN/Doc_status/API/Web_Authentication to have the corresponding fr-l10n doc status page.
I'm not sure of the tags to use in the `DocStatus` call so I targeted quite liberally.
Hope this can help.

**Comment by SphinxKnight** [comment]
As an interested reader on the topic and MDN frequent contributor, I think https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API should be shortened and a separate guide should be made from the "Web authentication concepts and usage".

I'm not saying any introductional content should be removed from this page but rather stating my opinion that the current content is too large for such an API landing page.

**Comment by jpmedley** [comment]
Here are the missing interfaces:
- [ ] FederatedCredential.protocol
- [ ] PublicKeyCredential.rawId
- [ ] PublicKeyCredential.response
- [ ] PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable
- [ ] PublicKeyCredential.getClientExtensionResults
- [ ] AuthenticatorAttestationResponse.getTransports
- [ ] AuthenticatorAssertionResponse.signature
- [ ] AuthenticatorAssertionResponse.userHandle

**Comment by SphinxKnight** [comment]
For the first item (of @jpmedley's checklist :)), I created
* https://developer.mozilla.org/en-US/docs/Web/API/FederatedCredential/protocol and filed  
* https://github.com/mdn/browser-compat-data/pull/3592 for BCD.
If I'm not mistaken, this property is not available in Chrome release or Firefox release so I did not invest too much time dramatically changing the content from the `provider` page (i.e. setting up examples)

**Comment by SphinxKnight** [comment]
@jpmedley should [`PublicKeyCredentialRequestOptions`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialRequestOptions) properties be included as well?

**Comment by SphinxKnight** [comment]
Initial version of https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/PublicKeyCredential.rawId done. I'm not sure the example is relevant (but still better than none).

**Comment by SphinxKnight** [comment]
Initial version of https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/response done. I opted for a longer introduction. Please truncate if you think it must be shorter.

**Comment by SphinxKnight** [comment]
Aaand https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable done.

**Comment by SphinxKnight** [comment]
Looks like https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults is done too.

**Comment by SphinxKnight** [comment]
Wrote https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse/getTransports 

TBD: PR to BCD; @jpmedley from https://github.com/chromium/chromium/commit/28254a4cfe0fd868c58a47c47e39a907774ebd7a#diff-0f684d35848d8674d6bd9c5673588856, I was not (yet) able to figure out how this was available from Chrome (which flag it may be behind). May work on it later today.

**Comment by SphinxKnight** [comment]
It's https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse/signature turn

**Comment by SphinxKnight** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse/userHandle has been written as well

Will collapse all those comment into a single one, sorry for the flood

**Comment by SphinxKnight** [comment]
After https://github.com/mdn/sprints/issues/976#issuecomment-470723248, here is what I done:

- [x] Wrote [`FederatedCredential.protocol` page](https://developer.mozilla.org/en-US/docs/Web/API/FederatedCredential/protocol)
- [x] Filled https://github.com/mdn/browser-compat-data/pull/3592 for BCD for `FederatedCredential.protocol`
- [x] Wrote [`PublicKeyCredential.rawId` page](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/PublicKeyCredential.rawId)
- [x] Wrote [`PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()` page](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable)
- [x] Wrote [`PublicKeyCredential.getClientExtensionResults()` page](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults)
- [x] Wrote [`AuthenticatorAttestationResponse.getTransports()` page](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse/getTransports)
- [x] Wrote  [`AuthenticatorAssertionResponse.signature` page](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse/signature)
- [x] Wrote [`AuthenticatorAssertionResponse.userHandle` page](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse/userHandle)

"Tentative" left to be done: 
- [ ] File a PR on BCD for `AuthenticatorAttestationResponse.getTransports()`
- [ ] Add [`PublicKeyCredentialRequestOptions`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialRequestOptions) and [`PublicKeyCredentialCreationOptions`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions) as `dictionaries` member to [`GroupData` macro](https://github.com/mdn/kumascript/blob/master/macros/GroupData.json#L1889)
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.rp`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.user`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.challenge`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.pubKeyCredParams`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.timeout`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.excludeCredentials`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.authenticatorSelection`
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.attestation` (or mention the static value on the parent page)
- [ ] Write / BCD for `PublicKeyCredentialCreationOptions.extensions`
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.challenge`
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.timeout`
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.rpId`
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.allowCredentials`
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.userVerification` (or mention the static value on the parent page)
- [ ] Write / BCD for `PublicKeyCredentialRequestOptions.extensions`
- [ ] [Write examples for pages missing one](https://developer.mozilla.org/en-US/docs/MDN/Doc_status/API/Web_Authentication#Needs*_tags)

Subject to discussion for guide/tutorial content: 
- Write a guide: "As a web dev, how do I register a new user with WebAuthn"
- Write a guide: "As a web dev, how do I authenticate an existing user with WebAuthn"
- Write a guide: "As a web dev, how do I register another authenticator for an existing user"
- Write a guide: "As a web dev, how do I transition from old FIDO JS API to WebAuthn"
- Write a guide: "As a web dev, how do I deal with progressive enhancement/compatibility - state of the current implementation"

**Comment by jpmedley** [comment]
> @jpmedley should [`PublicKeyCredentialRequestOptions`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialRequestOptions) properties be included as well?
> edit: [`PublicKeyCredentialCreationOptions`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions) properties may be added as well

* [PublicKeyCredentialRequestOptions](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/credentialmanager/public_key_credential_request_options.idl) supported. 
* [PublicKeyCredentialCreationOptions](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/credentialmanager/public_key_credential_creation_options.idl)

I don't have version numbers for either.
