### ISSUE TITLE
Remove App Center

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#977]
The [App Center](https://developer.mozilla.org/en-US/docs/Web/Apps) used to be home to all things Firefox OS and contained a wealth of web app techniques. But it's a shadow of its former self. Much of the content is obsolete and has already been removed, and what remains would make sense placed in other places:

* The PWA content is probably better placed directly under Web/
* The performance information is better off deleted or placed under Estelle's performance section.
* The other information is better placed under the APIs they relate to, or maybe under the learning area. 

# Acceptance criteria

1. - [ ] All content moved to more suitable homes on MDN, or deleted.
2. - [ ] Web/Apps deleted.
3. - [ ] Report written of what happened to the remaining information, reviewed by another team member to verify suitability.

**Comment by chrisdavidmills** [comment]
## Summary of changes to App center:

* PWA articles all moved under https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps (basically one level up the tree)
* MVC architecture series deleted as Ember code contained within it is getting out of date and it has hardly any page views. Useful general MVC content moved to https://developer.mozilla.org/en-US/docs/Glossary/MVC.
* User input and controls stuff is still quite useful, and has been moved under Guides, see https://developer.mozilla.org/en-US/docs/Web/Guide/User_input_methods
* Audio and video manipulation is still quite useful; has been moved under guides: see https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation
* Audio and video delivery is still quite useful; has been moved under guides: see 
https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery
* All other articles deleted, except for the list below.

## Undeletable articles

These articles have had all translations removed that could be removed (see below), and all child pages removed. Yet they won't allow me to delete them. This is blocking the completion of this task, so I'm going to ask the devs about it.

* https://developer.mozilla.org/en-US/docs/Web/Apps
* https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals
* https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals
* https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture
* https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Games
* https://developer.mozilla.org/ja/docs/Web/Apps/Tutorials
* https://developer.mozilla.org/en-US/docs/Web/Apps/Tutorials
* https://developer.mozilla.org/en-US/docs/Web/Apps/App_layout

**Comment by chrisdavidmills** [comment]
Bug filed for investigating the deletion of the remaining pages: https://bugzilla.mozilla.org/show_bug.cgi?id=1529021

**Comment by jwhitlock** [comment]
I've opened issue #1099 to delete the remaining pages, scheduled for the next sprint.

**Comment by chrisdavidmills** [comment]
Thanks @jwhitlock, much appreciated.

**Comment by jwhitlock** [comment]
I've deleted the undeletable pages.
