### ISSUE TITLE
Provide definitions for MDN's "support labels"

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#978]
See https://github.com/mdn/pab/issues/33

Basically, do we provide concrete definitions of support labels we use such as "Basic support"? Write them if not.

# Acceptance criteria

1. - [ ] Research which labels we use, and if we have definions for them on MDN, or on the BCD repo say.
2. - [ ] Write definitions if needed.

**Comment by jmswisher** [comment]
@chrisdavidmills This was "Continue in next sprint" at the end of Fantasia, but was not added to any later sprint. Should I put it in the Parking Lot?

**Comment by chrisdavidmills** [comment]
We can close this. I investigated it, and the conclusion reached was that the main problem label we needed to define was "Basic support" — this then prompted the discussion that led to @Elchi3 submitting a PR to remove the "Basic support" label from the BCD tables.
