### ISSUE TITLE
Document Custom HTML elements (Irene)

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#980]
[Trello Issue](https://trello.com/c/hNQnoIAW/114-general-api-enhancements-fx-64)

## Bugzilla Issues
#[1514809](https://bugzilla.mozilla.org/show_bug.cgi?id=1514809) - Enable userScripts API on release channels **This is now the main bug for this task**
#[1280347](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347) - Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs
#[1437864](https://bugzilla.mozilla.org/show_bug.cgi?id=1437864) - Implement userScripts API methods to allow an extension to inject custom APIs in the isolated userScripts sandboxes
#[1437861](https://bugzilla.mozilla.org/show_bug.cgi?id=1437861) - Implement userScripts.register and execute userScripts js code in isolated sandboxes

## Acceptance Criteria
- [x] userScripts page created
- [x] userScripts.register documented
- [x] UserScriptOptions object documented
- [x] userScripts.RegisteredUserScript object documented
- [x] userScript APIScript documented
- [x] userScripts.onBeforeScript event documented
- [x] custom HTML elements documented
- [x] userScripts manifest section added to the manifest documentation
- [ ] appropriate additions to Web Extensions sidebar made and merged
- [x] BCD updated

**Comment by irenesmith** [comment]
This feature is still behind a pref on Nightly but now they want to start promoting it.

**Comment by irenesmith** [comment]
This doc from Luca Greco has information that will be useful for creating this documentation:

[UserScripts API docs](https://docs.google.com/document/d/1xB_I8D77mFcBt-ZHF_yPvZktnF4-A5Zn-Rq5D85azt0/edit?ts=5c7fbba4#heading=h.u3wdl8yt4eaq)

**Comment by irenesmith** [comment]
# Created the following pages:
- [UserScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts)
= [RegisteredUserScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts/RegisteredUserScript)
- [UserScriptOptions](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts/UserScriptOptions)
- [APIScript](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts/APIScript)

**Comment by irenesmith** [comment]
Need to finish filling in the changes/new pages. Please don't move this to the next sprint.

**Comment by irenesmith** [comment]
This work is done except for the BCD and sidebar changes.

**Comment by jmswisher** [comment]
@irenesmith Are the BCD and sidebar changes done?

**Comment by irenesmith** [comment]
This issue is now superceded by [Sprints 2136](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/2136)

The only remaining item is the sidebar and that is covered in the other issue.
