### ISSUE TITLE
Add locale start pages to sitemap

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#981]
# User story
As an SEO expert I want the locale start pages added to the sitemap, so they are properly crawled and indexed.

# Acceptance criteria
* https://developer.mozilla.org/en-US/ and all other current locales are published in the sitemap

**Comment by jwhitlock** [comment]
The changes are deployed in production. The new sitemaps, like https://developer.mozilla.org/sitemaps/en-US/sitemap.xml, are in the [index sitemap](https://developer.mozilla.org/sitemap.xml), and Google Search Console reports that it has read the new sitemap files and indexed the locale homepages.
