### ISSUE TITLE
Plan for content deletion plan

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#985]
Attempts to update our content are hampered by the existence of huge amounts of outdated and unmaintained content. Much of this content is probably useless, but we still can't break it, so we have to update it when breaking changes get made in the content or platform or macros.

We ought to assess our content, especially in unmaintained locales, and decide what ought to be retired.

This user story is not for that work, but it's to outline how we would go about that work: what kind of data should feed into these decisions and how we can get it.

# Acceptance criteria
* Plan is written and reviewed.

**Comment by jmswisher** [comment]
@wbamberg This was "Continue in next sprint" at the end of Fantasia, but was not added to a later sprint. Should I put it in the Parking Lot?

**Comment by wbamberg** [comment]
Yes, I guess so :(.
