### ISSUE TITLE
 Article on transition-timing-function doesn't say how users can protect ourselves.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#988]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1512826

https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function

Since "ease-in-out" animations are popular, and can hurt, and can trigger severe migraines and severe nausea, it can be important for users to be able to protect ourselves against these. This article only currently discusses how developers can inflict these. If another article discusses how we can protect ourselves, then this article should include a link.

**Comment by estelle** [comment]
added a11y concerns to https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function page
