### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

### ISSUE THREAD

**Issue by JassimAbood** [mdn/sprints#990]
# Request type
- [ ] New documentation
- [ ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
Hi @JassimAbood! Is there a problem with this page that you want to report?
