### ISSUE TITLE
 Subtitles link to nowhere

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#991]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1506432

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest#

Go to the URL and click on "Events", "Types" or a similar title on the left for webRequest. 

What happens: Page jumps upwards as that links to "#" of the current page.

What should happen: I have expected an overview page or so…

I can reproduce this with every subheading on MDN.

**Comment by jmswisher** [comment]
Can no longer reproduce
