### ISSUE TITLE
 Behavior of window.history.back and browser back button not identical.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#994]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1476704

https://developer.mozilla.org/en-US/docs/Web/API/History_API

When using history.pushState(), the window.history.back() function and the browser back button behave different. In which context does this happen? How to overcome that?

See also: https://stackoverflow.com/questions/51404384/history-pushstate-history-back-and-back-button-behave-different

# Acceptance criteria
- [x] documentation for the History API updated appropriately with a description of the difference between the API calls and the back button on the browser.

**Comment by irenesmith** [comment]
Added the following to [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) section that describes history.pushState:

Note: Although history.back normally behaves the same way as clicking the Back button, the history.back method acts differently from the browser Back button after using history.pushState. Calling history.back after history.pushState does not raise a popstate event while clicking on the browser's Back button does raise the event.

**Comment by chrisdavidmills** [comment]
LGTM; thanks Irene.
