### ISSUE TITLE
 Error in documentation of background-scipt.js in connection-based messaging

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#996]
Cross-filed https://bugzilla.mozilla.org/show_bug.cgi?id=1499731

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

In the "Connection-based messaging" (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Connection-based_messaging) "background-script.js" i found a error.

function connected(p) {
  portFromCS = p;
  portFromCS.postMessage({greeting: "hi there content script!"});
  portFromCS.onMessage.addListener(function(m) {
    console.log("In background script, received message from content script")
    console.log(m.greeting);
  });
}

console.log didn't work for me, but if i send the message back to the content script i see that the anonymous function is called

portFromCS.postMessage({greeting: "In background script, received message from content script:" + m.greeting});

# Acceptance criteria
- [ ] Necessary updates made to script

**Comment by jmswisher** [comment]
This was completed in April: https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts$compare?to=1621378&from=1613434
