### ISSUE TITLE
 CSS transition-timing-function no longer has frames(); steps() enhanced

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#997]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1510921

https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function

I think it is just the formal syntax that needs updating. Original poster's message follows:

---

It is hard to know what combination of current standards docs defines all aspects of CSS transition-timing-function, with at least  
"CSS Animations Level 1" (https://www.w3.org/TR/css-animations-1/) and "CSS Easing Functions Level 1" (https://www.w3.org/TR/css-easing-1/) pertinent.  

However it is certainly true that no *current* spec version mentions the "frames()" function documented in this MDN page.

I finally found mention at https://www.w3.org/TR/2018/WD-css-easing-1-20181009/#changes that 

  The following changes have been made since the 21 February 2017 Working Draft:
    Removed `frames()` timing function.
    Added jump-start, jump-end, jump-none, and jump-both keywords to steps() timing function.

That earlier spec version does mention the frames() function at https://www.w3.org/TR/2017/WD-css-timing-1-20170221/#frames-timing-functions

It appears that the proposed usages of frames() were replaced by elaboration of steps() as noted above, and indeed the MDN page does not yet mention those added keywords (e.g. "jump-start")

Please delete frames() from the MDN page, and elaborate the description for steps() with the new enhancements and keywords.

Note: the current spec "CSS Easing Functions Level 1" was previously named "CSS Timing Functions Level 1"

**Comment by estelle** [comment]
waiting for https://github.com/mdn/data/pull/346 to be approved and merged.
