### ISSUE TITLE
 RegExp non-greedy quantifiers don't match the smallest possible match

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#999]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

See https://bugzilla.mozilla.org/show_bug.cgi?id=1517997 for full details of the bug.

**Comment by wbamberg** [comment]
I've had a go at clarifying this and at least :arai is happy: https://bugzilla.mozilla.org/show_bug.cgi?id=1517997#c7 so let's close this one.
